### ISSUE TITLE
Need Docs: http addition

### ISSUE THREAD

**Issue by weekwood** [keystonejs/keystone#1000]
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L173-L182

https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L219

**Comment by weekwood** [comment]
@JedWatson please add zh tag

**Comment by weekwood** [comment]
fixed via e17551a

**Comment by weekwood** [comment]
still need ES

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/99
