### ISSUE TITLE
Need Docs: session config

### ISSUE THREAD

**Issue by weekwood** [keystonejs/keystone#1001]
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L282

https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L315

**Comment by weekwood** [comment]
already finished before

**Comment by weekwood** [comment]
fixed via e17551a

**Comment by weekwood** [comment]
still

**Comment by JohnnyEstilles** [comment]
Still need ES docs.

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/98
