### ISSUE TITLE
Need Docs: Headings

### ISSUE THREAD

**Issue by weekwood** [keystonejs/keystone#1002]
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/database.jade#L349-L374

**Comment by weekwood** [comment]
add zh via #1006 @JedWatson

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/97
