### ISSUE TITLE
Need Docs: Menu

### ISSUE THREAD

**Issue by weekwood** [keystonejs/keystone#1003]
https://github.com/keystonejs/keystone/blob/master/docs/content/en/templates/mixins/docsnav.jade#L76-L81
https://github.com/keystonejs/keystone/blob/da3eaa4a73357612389331df10b2cf7f84b71025/docs/content/en/templates/mixins/docsnav.jade#L51

**Comment by weekwood** [comment]
add ZH via #1017

**Comment by weekwood** [comment]
@JedWatson you can merge and remove tag

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/96
