### ISSUE TITLE
Admin UI Homepage Design Discussion

### ISSUE THREAD

**Issue by snowkeeper** [keystonejs/keystone#1004]
As discussed in #994 there is interest in the community to create a more robust homepage.  As we near the release of 0.3.0 and React components we will have the opportunity to incorporate changes.

From a general stance the homepage should offer the ability to provide custom css and display React components.

**Here are three issues to start with**  
1. What features / components should the Admin UI Homepage include?   
2. How should the Admin UI Homepage incorporate React components?   
3. Should the Admin UI Homepage offer pre-configured components, configurable components, and/or allow user supplied React components and how?

**Comment by JohnnyEstilles** [comment]
I've been looking forward to this feature for a long time!

In addition to @snowkeeper's suggestions, I would like to suggest that, as we consider the technical implementation of this new feature, we do so not only in the context of React, but also of the proposed [Proposed Keystone Package Architecture](https://github.com/keystonejs/keystone/issues/912).

**Comment by cameronjroe** [comment]
I would love to contribute towards a React Markdown component that the Admin UI uses for writing posts. [IA Writer](https://ia.net/writer/mac) has a very clean interface and offers some very simple functionality like changing the text as you write. [Ghost](https://ghost.org/) also has a nice interface that takes a two up approach letting you write markdown on one side and view a preview on the other. This would be idea for writing posts in a familiar syntax.

**Comment by porschuetz** [comment]
personally I am not a big fan of the Ghost model, since it still does not exactly interpretate the front end's design and secondly because the proportions of text are off (splitscreen to super long portrait).

iA writer looks nice. thanks for that tip.

my favorite writer at the moment is the implementation at medium, yet, that is another story.

**Comment by mxstbr** [comment]
This was completely rewritten for 0.4, check out what's on http://demo.keystonejs.com and/or on the master branch at the moment!
