### ISSUE TITLE
sortOrder not being initialized on item creation

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#1007]
After [this commit](https://github.com/keystonejs/keystone/commit/8137c756656aaafadcba083a645858b66e00f183) (alt. implementation of #634, sortOrder type detection fix), `sortOrder` is no longer being initialized when an item is created.

The original code (below) tested the type of the `sortOrder` value, which is `undefined` before `sortOrder` is set, and `number` after it is.

```js
if (typeof this.sortOrder === 'number') {
    return next();
}
```

The current code tests the type of the schema field type, which is always `mongoose.Schema.Types.Number` regardless of whether `sortOrder` is initialized or not. This is causing `sortOrder` not to be initialed upon creation.

```js
var sortOrderType = this.schema.path('sortOrder');
if (typeof sortOrderType !== 'undefined' && sortOrderType instanceof keystone.mongoose.Schema.Types.Number) {
    return next();
}
```

I propose we rollback this commit.

**Comment by JohnnyEstilles** [comment]
@JedWatson do you intend to merge this into both `master` and `0.2.x`?

**Comment by JedWatson** [comment]
It's a breaking change so just 0.3.0
