### ISSUE TITLE
TinyMCE not working properly on latest version?

### ISSUE THREAD

**Issue by vfermino** [keystonejs/keystone#1009]
I am currently using the newest version of KeystoneJS and I ran into a problem related to the Admin UI: the WYSIWYG module, TinyMCE, is not really working. I'm trying to change its parameters in the public/js folder but it's not doing anything.
In the previous version (0.2.42), I changed the parameters within keystone/index.js, like that:
```
var locals = {
		_: _,
		moment: moment,
		numeral: numeral,
		env: this.get('env'),
		brand: keystone.get('brand'),
		nav: keystone.nav,
		messages: _.any(flashMessages, function(msgs) { return msgs.length; }) ? flashMessages : false,
		lists: keystone.lists,
		js: 'javascript:;',
		utils: utils,
		user: req.user,
		title: 'Keystone',
		signout: this.get('signout url'),
		backUrl: this.get('back url') || '/',
		section: {},
		version: this.version,
		csrf_token_key: keystone.security.csrf.TOKEN_KEY,
		csrf_token_value: keystone.security.csrf.getToken(req, res),
		csrf_query: '&' + keystone.security.csrf.TOKEN_KEY + '=' + keystone.security.csrf.getToken(req, res),
		ga: {
			property: this.get('ga property'),
			domain: this.get('ga domain')
		},
		wysiwygOptions: {
			enableImages: keystone.get('wysiwyg images') ? true : false,
			enableCloudinaryUploads: keystone.get('wysiwyg cloudinary images') ? true : false,
			additionalButtons: keystone.get('wysiwyg additional buttons') || '',
			additionalPlugins: keystone.get('wysiwyg additional plugins') || 'table',
			additionalOptions: keystone.get('wysiwyg additional options') || {},
			overrideToolbar: keystone.get('wysiwyg override toolbar'),
			skin: keystone.get('wysiwyg skin') || 'keystone',
			menubar: keystone.get('wysiwyg menubar')
		}
	};
```
However, this is no longer an option in the newest index.js, nor in any file that I can find. I tried to install the classic version of TinyMCE which comes with what I need (tables, basically) on the public directory but it didn't work.
The newer version also doesn't allow me to customize some fields, like the TextArray one (which I was trying to make look closer to the collection array to save space), as there seems to be files that do not interfere at all, like the HtmlType.js, when HtmlField.js is the only one that works.
Thanks.

**Comment by snowkeeper** [comment]
`HtmlType.js` is the react component code. `HtmlField.js` is the list setup for the Type. All fields will follow this convention.  Working with the master branch and what will become 0.3.0 requires building `app.js` when changing any React component (this will soon become part of the startup process).  See  `gulpfile.js` for that.

Passing those values as locals will not have any effect on the Admin UI when working from the master branch, as jade is being phased out and the options pulled from the list setup.  It looks as you have the global options set correctly.  Also, just to be thorough make sure that in your model field definition you have `wysiwyg:true` for  `Types.Html`.

**Comment by mxstbr** [comment]
It seems the question was answered, so I'll close this issue for now. Feel free to comment again if the issue still persists!
