### ISSUE TITLE
Find User by email and password

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1013]
I am implementing oauth2 in keystone.

The routes and models are set up easily. However, I don't know how to use the find syntax to search the encrypted password, my code is 

```
  keystone.mongoose.model('User').find()
    .where('username',username )
    .where('password', password)

```

which obvious return nil as the password field is encrypted by keystone.

in my express.js, the solution is as below. But I don't know how to assign comparePassword methods to keystone.

```
 UserSchema.methods.comparePassword = function(candidatePassword, cb) {
    bcrypt.compare(candidatePassword, this.encrypted_password, function(err, isMatch) {
        if (err) return cb(err);
        cb(null, isMatch);
    });
 } ;
module.exports = mongoose.model('User',UserSchema);

```

**Comment by snowkeeper** [comment]
The documentation is available at [Keystonejs.com](http://keystonejs.com/docs/database/#fieldtypes-password).

`lib/session.js` has an example
```
// match email address and password
		User.model.findOne({ email: lookup.email }).exec(function(err, user) {
			if (user) {
				user._.password.compare(lookup.password, function(err, isMatch) {
					if (!err && isMatch) {
						doSignin(user);
					}
					else {
						onFail(err);
					}
				});
			} else {
				onFail(err);
			}
		});
```

**Comment by snowkeeper** [comment]
Also check out [keystone social login](https://github.com/JohnnyEstilles/keystone-social-login) by @JohnnyEstilles
