### ISSUE TITLE
Add `groupBy` & `aggregate` to queries

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1016]
An example [from here](https://github.com/keystonejs/keystone-5/issues/1003#issuecomment-481098670):

> Given this schema:
> 
> ```javascript
> keystone.createList('Train', { /* ... */ });
> keystone.createList('User', { /* ... */ });
> keystone.createList('Trip', {
>   fields: {
>     user: { type: Relationship, ref: 'User' },
>     train: { type: Relationship, ref: 'Train' },
>   }
> });
> ```
> 
> _For User X, get their 5 most frequently ridden trains, sorted by number of trips descending_

The Prisma team have put a lot of thought into a possible API: https://github.com/prisma/prisma/issues/1312

We don't have the `nodes` concept, but I think we could easily add a `_aggregate` and `_groupBy` pseudo-field (like we already have the `_xMeta` pseudo-fields) which would meet the same needs :+1:

**Comment by MadeByMike** [comment]
@jesstelford Do you have a preposed API for the graphQL query or would you look to replicate the prisma example 1-1?
