### ISSUE TITLE
Add serverside field tests

### ISSUE THREAD

**Issue by kittens** [keystonejs/keystone#1018]
This is an issue tracking my progress on writing serverside field tests:

 - [x] boolean
 - [ ] code
 - [x] color fba0d0f84e6b519c888d3d11149a8df3f8cd8b92
 - [ ] date
 - [ ] datetime
 - [ ] email
 - [ ] embedly
 - [ ] geopoint
 - [ ] html
 - [ ] key
 - [ ] location
 - [ ] markdown
 - [x] money
 - [ ] name
 - [x] number 86d065f8a4208ba97a39463de5dec728fdb10a78
 - [x] numberarray d9254ab7627f8223bf50798ce5522373db2e86d7
 - [ ] password
 - [x] relationship
 - [ ] select
 - [x] text
 - [x] textarea
 - [x] textarray 42535628c42fa99706c80748f1a0121947d12e05
 - [x] url aa23a08ad7167241a119dcfb7f3030534adeb316 148cf5d6aa2858da687af7c147b9cf114040e89a

There also needs to be a testing strategy for the file fields which are as follows:

 - [ ] azurefile
 - [ ] cloudinaryimage
 - [ ] cloudinaryimages
 - [ ] localfile
 - [ ] localfiles
 - [ ] s3file

**Comment by sebmck** [comment]
Some of the tests wont pass because of keystone bugs.

**Comment by mrappweareratio** [comment]
@sebmck do you where test running instructions are located?

**Comment by morenoh149** [comment]
to run keystone tests execute `npm test`

**Comment by mxstbr** [comment]
Superseded by #2438
