### ISSUE TITLE
Need Docs: Types TextArray and NumberArray

### ISSUE THREAD

**Issue by snowkeeper** [keystonejs/keystone#1021]
TextArray and NumberArray need documentation.

**Comment by jossmac** [comment]
+1

**Comment by stosorio** [comment]
+1

**Comment by morenoh149** [comment]
moved

**Comment by simonwidjaja** [comment]
+1

**Comment by ChristianRich** [comment]
+1

**Comment by morenoh149** [comment]
@JedWatson does the site need to be updated with the merged textArray docs?

**Comment by JedWatson** [comment]
@morenoh149 it's had a few updates I need to push out, will do that asap.

**Comment by nifl** [comment]
@JedWatson has this been pushed?

**Comment by mzgol** [comment]
I still don't see it on the site: http://keystonejs.com/docs/database/#fieldtypes-text

**Comment by morenoh149** [comment]
It's in master https://github.com/stosorio/keystonejs-site/blob/master/content/en/pages/docs/database.jade#L921 the actual site might need to be updated. @mzgol this has been moved.

**Comment by chrisslater** [comment]
Does this still need pushing, because I can't see a reference to TextArray or NumberArray on the Keystone docs

**Comment by mxstbr** [comment]
We might need to deploy the site again. /cc @JedWatson

**Comment by jjmpsp** [comment]
+1 `TextArray` & `NumberArray` Types still missing from the official documentation

**Comment by L422Y** [comment]
bump :(

**Comment by export-mike** [comment]
There's been progress on new docs which is currently being worked on, you have a look at it on the staging URL we have http://keystonejs.netlify.com/api/field/textarray/
