### ISSUE TITLE
How to generate a delete link

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1022]
I tried to add the data[method] and confirm to my delete link in frontend, 

but it seems not work.

Is there any standard way to add a delete link?
```
 a(href= '/clients/' + data.client.slug, data[method]= 'DELETE', data[confirm]= 'Are you sure to delete this client?').btn.btn-danger DELETE
```

**Comment by morenoh149** [comment]
you can't make an anchor that sends an HTTP DELETE. http://stackoverflow.com/questions/5823774/linking-to-a-page-with-a-specific-http-method-delete There are some hacks where you call an ajax request upon clicking the link https://gist.github.com/JeffreyWay/5112282

Rails actually has a mixin that inserts a form with a hidden field. http://stackoverflow.com/questions/2809200/how-does-rails-3s-data-method-delete-degrade-gracefully

@arthurtalkgoal If I were you I'd generate an ajax request. Seems like the easiest solution. @keystonejs/owners Should keystone have a  helper mixin for triggering DELETEs on the backend?

**Comment by arthurtalkgoal** [comment]
Hi @morenoh149 ,

I have been using Rails for while, it's very convenient to have helper adding the remote, or delete links.

And I found that many keystonejs and it's tutorial use 
app.all or get HTTP methods for the create, update and delete which seems incorrect in RESTful sense.

And a core helper for links (e.g. link_to or a ) can in fact promote users to have such concept in mind.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/generate-a-delete-links
