### ISSUE TITLE
How to callback methods when AdminUI create, update and delete

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1025]
Hi, 

Is there callback I can set up when AdminUI work on models' create, update and delete, 

such as
```
after_create :create_droplet
after_delete :remove_droplet
```

**Comment by arthurtalkgoal** [comment]
Oh, from sydjs I found the hooks, are these the answer? 



```
/**
 * Hooks
 * =====
 */

RSVP.schema.pre('save', function(next) {
	if (!this.isModified('changedAt')) {
		this.changedAt = Date.now();
	}
	next();
});

RSVP.schema.post('save', function() {
	keystone.list('Meetup').model.findById(this.meetup, function(err, meetup) {
		if (meetup) meetup.refreshRSVPs();
	});
});

```

**Comment by JohnnyEstilles** [comment]
@arthurtalkgoal, yes Keystone supports the callbacks you're referring to via [Mongoose Middleware](http://mongoosejs.com/docs/middleware.html). In addition to the `pre save` and `post save` examples you found in the SydJS code, Mongoose offers additional hooks to which control is passed during the lifecycle of the document.

Check out [http://mongoosejs.com/docs/middleware.html](http://mongoosejs.com/docs/middleware.html) for more information.
