### ISSUE TITLE
Show fields from other models (collections) in keystone.js admin UI?

### ISSUE THREAD

**Issue by rmarji** [keystonejs/keystone#1027]
I have asked about this on stackoverflow I would appreciate if I can get an answer from you guys :)
http://stackoverflow.com/questions/28428416/show-fields-from-other-models-collections-in-keystone-js-admin-ui

**Comment by webteckie** [comment]
@rmarji is this somehow related to #1024 ?

**Comment by JohnnyEstilles** [comment]
@rmarji, I posted an answer on your Stackoverflow question. All you need to do is map whatever field you want to act as the `name` of the model in the `List` definition.

In your case it would be something like this:

```js
var Keyword = new keystone.List('Keyword', {
    map: { name: 'searchvol' }
});
```

**Comment by creynders** [comment]
Answered
