### ISSUE TITLE
Nested meta queries can error when main query result not found

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1028]
Given a query like:

```graphql
  query getGroup($groupId: ID!) {
    Group(where: { id: $groupId }) {
      labels {
        name
        _eventsMeta { count }
      }
    }
  }
```

ie; _"get the labels used by this group, along with how many times it's also been used on an event within this group"_

When passing a `$groupId` which doesn't have a match, the internal query mechanism will still attempt to pull out the meta info for `_eventsMeta`, which (for the Mongo adapter), results in this error:

```
$in requires an array as a second argument, found: missing
```

I think it's because the mongo join builder does something like:

```
{
  $in: "$_groupIds"
}
```

Where `$_groupIds` comes from some earlier stage, but in the case where no match is found, `$_groupIds` would be null (or an empty array?).

**Comment by jesstelford** [comment]
Possibly fixed by #1033

**Comment by gautamsi** [comment]
this is what I get today, more fix needed?

`"message": "Cannot use 'in' operator to search for 'posted_utc' in null"`

**Comment by MadeByMike** [comment]
Need to verify if this is fixed @MadeByMike
