### ISSUE TITLE
on init, `applying update 0.0.1-admins...` takes forever

### ISSUE THREAD

**Issue by 0a-** [keystonejs/keystone#1029]
After doing `node keystone.js`, I was stuck at the line

``
applying update 0.0.1-admins
``

**Comment by JohnnyEstilles** [comment]
Can you share do code of `0.0.1-admins.js`?

**Comment by 0a-** [comment]
Oh, I forgot I edited the file two few days ago.. Thanks for the tip. 

Looks like it was because I failed to call `done()`. Problem resolved  :laughing:
