### ISSUE TITLE
Support Knox MPU on S3

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#1032]
So, it seems like this module

https://www.npmjs.com/package/knox-mpu

extends the basic knox s3 module used by keystone to allow large / async uploads to s3. Might be a great way to extend the current S3 field so that any size file will go. We could just make the upload be sync or async with a field property. This way someone could upload 5 files at once and then a div would populate with status of the uploads. Or would you just want a new field called S3 MPU? We could extend / patch the existing S3 field to add this functionality or create a new field.

**Comment by morenoh149** [comment]
@chrisschaub what do you think about https://github.com/andrewrk/node-s3-client ? I've noticed commented out sections of code that used the `s3` module. And it seems like it has a solution for the problem you described. I think if we solve your problem using the `s3` module it'd be more likely to get accepted into the codebase.

**Comment by chrisschaub** [comment]
Well, Keysonejs is already using "knox" in the S3 field implementation. So,
we've created a version of the S3 field that uses knox-mpu to handle large
files, seems to be working well. We'll post a patch in a few days against
0.3.0. We're just working on the reactjs stuff to show uploading progress,
especially when you upload more than one file async.

On Fri, Feb 13, 2015 at 3:35 PM, Harry Moreno <notifications@github.com>
wrote:

> @chrisschaub <https://github.com/chrisschaub> what do you think about
> https://github.com/andrewrk/node-s3-client ? I've noticed commented out
> sections of code that used the s3 module. And it seems like it has a
> solution for the problem you described. I think if we solve your problem
> using the s3 module it'd be more likely to get accepted into the codebase.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/1032#issuecomment-74331030>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by morenoh149** [comment]
cool. If you share that we could close https://github.com/keystonejs/keystone/issues/816

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/support-knox-mpu-on-s3
