### ISSUE TITLE
include virtuals toJSON

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1033]
I wanna mashall the thumb path and filename for my api, and created a virtual.

Can I include the virutals like this:
http://stackoverflow.com/questions/11557804/mongoose-virtual-fields-included-in-tojson-by-default-schemaoptions-tojson-virt

```
var schemaOptions = {
    toObject: {
      virtuals: true
    }
    ,toJSON: {
      virtuals: true
    }
  };
```

**Comment by morenoh149** [comment]
you need to read the docs yourself http://mongoosejs.com/docs/guide.html#virtuals but that looks correct.

**Comment by JedWatson** [comment]
You can access the schema when you're creating a keystone list like this:

```
var Things = keystone.list('Things');

Things.add(...);

Things.schema.set('toJSON', { virtuals: true });
```

Note that I strongly recommend against including virtuals by default, as Keystone fields add a _lot_ of them. A better way is to extend the `toJSON` option for the schema and add a transform method that includes the values you want (i.e. the thumbnail path for a given size).

Full mongoose docs here: http://mongoosejs.com/docs/api.html#document_Document-toObject
