### ISSUE TITLE
About Select dependsOn and Change option 

### ISSUE THREAD

**Issue by huhan8371** [keystonejs/keystone#1034]
first_select 
{ type: Types.Relationship, ref: 'Category', many: false }

i need after select first_select, admin ui show second_select, and when change first_select, the second_select's options also change

second_select:{ type: Types.Select, dependsOn:????, options: ??? ....}

how to fill second_select?

**Comment by morenoh149** [comment]
What's `first_select` and `second_select`? Could you describe what you want your software to do, your data models and the relationships you want them to have.

**Comment by huhan8371** [comment]
Category  modle may like this：
var Category = new keystone.List('Category', { map: { name: 'title' }});
Category.add({title: { type: String },keys: { type: String }});
the data maybe
{ "_id" : ObjectId("54daee4dfd593a223d3f8ed3"), "__v" : 0, "keys" : "aaa,bbb,ccc,ddd", "title" : "cate_1" }
{ "_id" : ObjectId("54daee6bfd593a223d3f8ed4"),  "__v" : 0, "keys" : "i,m,n,d,e,f", "title" : "cate_2" }
..... a lot records.
first_select and second_select in another model may be like this;
Thing.add({
	name: { type: String, required: true },
	first_select: { type: Types.Relationship, ref: 'Category'},
	second_select: { dependsOn:????, options: ??? ... },
});

i hope on admin ui ,when first_select choose "cate_1", second_select 's use "aaa,bbb,ccc,ddd"  to make 4 opts;then  first_select change to "cate_2",second_select chage to 5 opts；i,m,n,d,e,f

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
