### ISSUE TITLE
connect.js - why is express "app" detection dependent on arguments[i].name === "app"

### ISSUE THREAD

**Issue by mrappweareratio** [keystonejs/keystone#1036]
I'm working with keystone and followed the website instructions for BYO express and mongoose, where it suggests to use:
```
app = express()
keystone.connect(mongoose, app);
```
However, during runtime (at least in a Mohca test), the app argument name and constructor.name are both blank "".

The following code doesn't detect.
```
if (arguments[i].name === 'app') {
	debug('detected express app');
	this.app = arguments[i];
}
```

Can this please be fixed?

I would suggest to simply update the documentation to either set keystone.app directly, or update the connect functionality to take mongoose and express separately.

**Comment by morenoh149** [comment]
ah I came across this too when I was trying to BYO express instance. @mrappweareratio I proposed refactoring the logic to trust the developer and perform no introspection on the incoming express instance. Introspection would work if every module had a name field. But from @BerkeleyTrue research not all modules provide the `name` field.

@mrappweareratio want to write up the pull request so there are no checks on `name` and the software just assumes the object implements the express api?

**Comment by BerkeleyTrue** [comment]
The connect method is deprecated, or at least it was going to be and fell through the cracks for 0.3.0 as express 4 and on no longer has the name field and this is broken. You can already keystone.set('mongoose', mongoose), but I don't think you can use the same method for the express app. 

@JedWatson Is it possible to use keystone.set('express app', app) yet?

see Jeds comment here: https://github.com/keystonejs/keystone/issues/864

**Comment by JohnnyEstilles** [comment]
I agree with @morenoh149. The introspection in `keystone.connect()` is completely unnecessary.

Right now we can set both the Express and the Mongoose instance directly on the Keystone object. (Which is what I've been using to avoid the `.connect()` issues.)

```js
keystone.app = require('express')();
keystone.mongoose = require('mongoose');
```

Interestingly enough, `keystone.init()` uses the `.connect()` method to set the default Mongoose instance, but not the Express instance (see [here](https://github.com/keystonejs/keystone/blob/d51fcf58181e3d62f71a66c93d121c5922044a25/lib/core/init.js#L22-L28)).

AFAICT ... [this](https://github.com/keystonejs/keystone/blob/d51fcf58181e3d62f71a66c93d121c5922044a25/lib/core/init.js#L27) is the only place within Keystone that the `.connect()` method is used. And, personally, I think its convenience has outlived its usefulness. 

I vote for deprecating it in favor of Keystone-like options.

```js
keystone.set('express', require('express')());
keystone.set('mongoose', require('mongoose'));
```

**Comment by JohnnyEstilles** [comment]
@BerkeleyTrue ... didn't notice your comment. I agree 100%. Wasn't aware of #864. If this was already agreed upon let's just submit a PR.

**Comment by JohnnyEstilles** [comment]
Submitted fix ... PR #1042

**Comment by JedWatson** [comment]
Fixed, thanks @JohnnyEstilles.

Needs Chinese docs to match those in #1041, I'll open a new issue for it.

**Comment by JedWatson** [comment]
Whoops no, @JohnnyEstilles beat me to it! #1042

**Comment by JohnnyEstilles** [comment]
I'm that good. :-)
