### ISSUE TITLE
AdminUI Theming and color schemes

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#1037]
Given that AdminUI has evolved and will also be respecting permissions in v5, I propose to have custom theming support. This will help create end user accessible admin page based on their role.

- Provide Theme template (css or styled component override from config)
- Theming should allow change in position of navigation bar (optional)
- Enable different Theming config based on User login
- provide 4-5 built in color schemes for theming

**Comment by JedWatson** [comment]
We've talked about some of this in the context of the new Admin UI design that has started landing with #1023. Now that the design is simpler and cleaner it would be possible to allow customisation of the look and feel to some extent through a couple of customisable colours (the blue in particular)

I'm expecting this would be managed by a `ThemeProvider` component (or similar) that makes design tokens available to the components in the design system on react context. @jossmac is planning to do some work cleaning up the design system in the near-ish future (there's a lot of work to do there) - this would either fit as part of that, or afterwards.

I'd like to be careful opening up too much flexibility though. It can make things much harder to test and change; customising a couple of colours that impact the look of the UI, or injecting branding, is pretty easy; allowing wholesale control of the UI is a can of worms I don't want to open lightly.

If we allow things like alternate layouts (e.g supporting horizontal nav) that could get super complex to support longer term; if anything, I'd probably open up a component replacement API for _very limited amounts_ of the UI similar to how [react-select](https://react-select.com/) works.

Just to set expectations here, Keystone 4 suffered significantly from becoming hard to maintain over time and that included the complexity of the Admin UI implementation. We've got a lot of work to do and a lot of features to build in the coming months, so I want to be really careful of introducing unnecessary complexity that could complicate our lives down the track here.

**Comment by gautamsi** [comment]
thanks for explaining this in details, I agree that maintainability should be a priority given past experience. 

I am fine with your views of essential customization capability (branding, color etc).

On another thought, it may also make sense to make admin ui composable. by compasable I mean I should be able to use my own layout container and add the Admin UI components to get fully featured custom Admin UI which I can extend myself. This way maintenance would not be a problem, it wont break the in built Admin UI, people would have option to revert back to default admin ui (with branding and colors) in case something breaks their custom admin ui. 

This can also be taken up by Userland to develop cool new features on top of admin ui without touching the base repo.
