### ISSUE TITLE
Separate AdminUI presentational props from field config props

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1039]
From https://github.com/keystonejs/keystone-5/pull/1038#issuecomment-483854532

@jossmac says:

> Would a `Textarea` (or other) field type make more sense? I'm not sure that we should let presentational component props inform the config for our types.

I like the idea of separating config for the field and config for the admin UI.

A new field type of `Textarea` would be identical to `Text` in everything except the one `isMultiline` prop, so I'm not a huge fan of making that a new field. It could also lead to many many field types all because they display slightly differently in the admin UI.

Perhaps an alternative is to accept an `admin` prop on the field config level (like we do on the list level config already) which can pass these kinds of options through? That would make it clear this setting is purely for the Admin UI, and opens it up for custom field types to have a way of accepting these presentational-only  props instead of as a generic config.

**Comment by JedWatson** [comment]
So the catch here (for me) is that not every option is absolutely either admin UI or db / graphql related.

If you have two options, `a` and `b`, which both affect the Admin UI, but `a` also affects the graphQL API or db adapter, then you'd probably end up with this:

`path: { type: Field, a: 'value', admin: { b: 'value' } }`

... which I have historically found super hard to make consistent and predictable.

IMO the cleanest approach is to say that "this is the field config API" - document all the options, what they do, and what they relate to. Group options that make sense, but not with artificial and inconsistent boundaries between the Admin UI and the back-end.

**Comment by jesstelford** [comment]
Unfortunately that wont work for things like API keys.

A great example is the CloudinaryImage type - we don't want to accidentally pass the cloudinary api key to the Admin UI.

This has recently come up with Blocks which have this separation of some things executed server side and some things executed client side. See #1097

**Comment by jesstelford** [comment]
The good thing is; there's no reason the server can't have access to the `adminConfig` options.

On the server side, it can access things directly on the `config` object, and/or on `config.adminConfig` :+1:

**Comment by jesstelford** [comment]
Bringing in some more suggestions from https://github.com/keystonejs/keystone-5/pull/1286#issuecomment-499749679

[Some features start] to add a lot of functionality to schema definitions which is only applicable to the _optional_ Admin UI.

Can I suggest we move this to the configuration _of the Admin UI_?

For example (I'm not wedded to this API at all, it's only to demo my thoughts):

```javascript
keystone.createList('Task', {
  fields: {
    title: { type: Text },
    // I want this field hidden in the Admin UI
    sortOrder: { type: Integer },
  }
});

const admin = new AdminUIApp({
  lists: {
    Task: {
      fields: {
        sortOrder: { isVisible: false } // default: true
      }
    }
  }
});

module.exports = {
  keystone,
  apps: [new GraphQLApp(), admin],
};
```

And we can move more of the existing AdminUI only stuff there such as `defaultColumns`, etc:

```javascript
const admin = new AdminUI({
  lists: {
    Task: {
      fields: {
        sortOrder: { isVisible: false } // default: true
      },
      // Only display the '_label', not the 'name' by default
      defaultColumns: ['_label'],
    }
  }
});
```

This is nice because it now sits along side the custom _pages_ config:

```javascript
const admin = new AdminUI({
  adminPath: '/admin',
  pages: [
    {
      label: 'A new dashboard',
      path: '',
      component: require.resolve('./admin/pages/dashboard'),
    },
    {
      label: 'Getting Shit Done',
      children: ['Tasks'],
    },
  ],
  lists: {
    Task: {
      fields: {
        sortOrder: { isVisible: false } // default: true
      },
      // Only display the '_label', not the 'name' by default
      defaultColumns: ['_label'],
    }
  }
});
```

[This] introduces a separation of where things are configured. Personally I like this as it means I am configuring discrete separate things (the schema, and the admin ui).

However, if it makes more sense to you to configure both schema and admin ui at the same time, my suggestion would also allow doing something like:

```javascript
const _ = require('lodash');

const lists = {
  Task: {
    fields: {
      title: { type: Text },
      // I want this field hidden in the Admin UI
      sortOrder: {
        type: Integer,
        adminUI: { isVisible: false },
      },
    }
  }
}

Object.entries(lists).forEach(([key, list]) => {
  // The adminUI key on fields is silently ignored
  keystone.createList('Task', list);
});

const admin = new AdminUIApp({
  lists: _.mapValues(lists, ({ fields }) => ({
    // Pick out only the adminUI key
    fields: _.mapValues(fields, field => _.pick(field, 'adminUI'))
  })),
});

module.exports = {
  keystone,
  apps: [new GraphQLApp(), admin],
};
```

Whereas the inverse cannot be true; this PR does not allow separating the configuration.
