### ISSUE TITLE
Cascading Deletes for Relationships

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1052]
There can be situations where two lists are tightly coupled, and in a to-many relationship, it can be desirable to delete the _many_ item if the _one_ item is also deleted. This is a _cascading delete_.

### Example

```javascript
keystone.createList('Post', {
  fields {
    comments: { type: Relationship, ref: 'Comment.post', many: true }
  }
});

keystone.createList('Comment', {
  fields {
    post: { type: Relationship, ref: 'Post.comments' }
  }
});
```

When a `Post` is deleted, the app developer may want all of its associated `Comment`s to be deleted also.

Today, the delete would look like this:

```javascript
const postId = 'abc123';

await graphqlFetch(
  `
    mutation deleteComments($postId: ID!) {
      deleteComments(where: { post: { id: $postId } }) {
        id
      }
  `,
  { postId }
);

await graphqlFetch(
  `
    mutation deletePost($postId: ID!) {
      deletePost(where: { id: $postId }) {
        id
      }
  `,
  { postId }
);
```

Which isn't too bad, but it gets hairy when there's more nested relationships...

### Example 2

Here's a possible edge-case / more complicated case.

A `Post` has many `Comment`s, each of which may have a single `Attachment`. When a `Post` is deleted, all the posts's `Comment`s should be deleted, and so should all the `Attachment`s for each `Comment`.

But, `Attachment`s aren't exclusive to `Comment`s (they may also be used by `Post`s, or by `User`s, etc, etc), so there's no `Relationship` reference from `Attachment` -> `Comment`.

To do accurately perform the delete, we currently need to go through the `allComments` query to pull out all possible `attachment.id`s, then trigger a `mutation` which deletes all the found `Attachment`s.

And this example code :point-down: assumes every `Comment` has an `Attachment`, which wont necessarily be true.

```javascript
keystone.createList('Post', {
  fields {
    comments: { type: Relationship, ref: 'Comment.post', many: true }
  }
});

keystone.createList('Comment', {
  fields {
    post: { type: Relationship, ref: 'Post.comments' }
    // Note: Does not reference a field on Attachment, only the list
    attachment: { type: Relationship, ref: 'Attachment' }
  }
});

keystone.createList('Attachment', {
  fields {
    // Note: Does not store a reference back to the Comment (because attachments could be for anything, really)
    thing: { /* ... */ }
  }
});
```

So now the delete is:

```javascript
const postId = 'abc123';

const attachments = await graphqlFetch(
  `
    query getAttachmentsForPostComments($postId: ID!) {
      allComments(where: { post: { id: $postId } }) {
        attachment {
          id
        }
      }
  `,
  { postId }
);

const attachmentIds = flatten(attachmentIds.data.allComments.map(({ attachment: { id } }) => id));

await graphqlFetch(
  `
    query deleteAttachments($attachmentIds: [ID]!) {
      deleteAttachments(where: { id_in: $attachmentIds }) {
        id
      }
  `,
  { attachmentIds }
);

await graphqlFetch(
  `
    query deleteComments($postId: ID!) {
      deleteComments(where: { post: { id: $postId } }) {
        id
      }
  `,
  { postId }
);

await graphqlFetch(
  `
    query deletePost($postId: ID!) {
      deletePost(where: { id: $postId }) {
        id
      }
  `,
  { postId }
);
```

### Prior Art

- https://github.com/prisma/prisma/issues/47
- https://github.com/prisma/prisma/issues/1262
- https://github.com/prisma/prisma/issues/1936

**Comment by jesstelford** [comment]
Note: This is distinct from _Nested Delete Mutations_: https://github.com/keystonejs/keystone-5/issues/1244

**Comment by Olya-Yer** [comment]
will this work in AdminUi ? for example if i create an item and add new field/relationship to it by creating one, and then i delete the item, I would expect the newly created relationship field items also gone as i haven't saved my item. Or it can be optional.

**Comment by molomby** [comment]
Side note -- cascading deletes can of course be added to the schema config in most relational DBs. A nice addition but we can't _rely_ on the DB for this -- Keystone needs to manage the cascade itself as Jess suggests. This lets us maintain cross-adapter compatibility and correctly fire the delete hooks for each item (`beforeDelete`, `validateDelete`, `afterDelete`).

**Comment by maheraldous** [comment]
@jesstelford I am new to GraphQL and I xame from REST API and Wordpress. But I have suggestion about this topic. Before I suggest, I want to say I am not expert about how the KeystoneJS work but my suggestion is, wouldn't it be easier if we look at the post as an object with comments and contents items and inside the comments we add the name of every user who commented on the post.

When deleting the post we delete the entire object, which would be easier. If we want to delete a comment we can just tell the id of the comment or the user then delete it from the post fields.

I really liked the relation thing but some how I got stuck sometimes to understand who will have relation with who?

Also the GraphQL docs would be more helpful if it was documented as the original GraphQL page. I made a pull request to edit some error in the CreateUsers documentation.

**Comment by ChuckJonas** [comment]
Is there any update on the best way to do this or plans to bring first class support for this?

**Comment by Thinkscape** [comment]
What is the best way to bump it?
Given that Prisma is used for all the db mapping, and it natively supports cascade delete (for rel. databases) it seems like a missing feature. I guess the trick here is the nature of hooks, where KS is opinionated on having this functionality in userland, as opposed to being managed by the db 🤔 

Maybe that could be implemented on storage level? I.e. if natively supported by storage (i.e. rdbms) and no `afterDelete` hooks defined, then use `SQL`, otherwise use userland "polyfill".

**Comment by dcousens** [comment]
Actually, this issue is old and needs to be refreshed for `@keystone-6`.
@Thinkscape the best way for you to revive this issue is to ask for it as a feature request! :blue_heart:
