### ISSUE TITLE
Decide on an official Custom Field View API

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1054]
_NOTE: This is different to [supporting custom *page* views](https://github.com/keystonejs/keystone-5/issues/7)_.

It's already possible to overwrite the views of a field type by extending a type object.

```javascript
const { Text } = require('@keystone-alpha/fields');

const Field = /* ... Some React ... */;

const CustomText = {
  ...Text,
  views: {
    ...Text.views,
    Field,
  },
};

keystone.createList('User', {
  fields: {
    name: {
      type: CustomText,
    },
  }
});
```

Is this the API we want to continue with?

If not, is there another implementation we could move ahead with?

One possible alternative:

```javascript
const { Text } = require('@keystone-alpha/fields');

const Field = /* ... Some React ... */;

keystone.createList('User', {
  fields: {
    name: {
      type: Text,
      admin: {
        views: { Field }
      }
    },
  }
});
```

An important consideration is the answer to the question "What is a Field Type?". Some discussion is ongoing in #149.

Currently, a _Field Type_ is an envelop describing both GraphQL-side functionality, and AdminUI-side views. For example, [see the `Checkbox` type](https://github.com/keystonejs/keystone-5/blob/master/packages/fields/src/types/Checkbox/index.js).

**Comment by JedWatson** [comment]
Unless there's a compelling alternative use-case, I'm in favour of having the current support being the only way. It's not really much different in terms of code. It does (more or less) force you to create a new field type for any field you want to have custom views for... but it's also one less way of doing the same thing. And personally I like the explicitness.

If you _really_ wanted to, the second example could be written as:

```js
const { Text } = require('@keystone-alpha/fields');

const Field = /* ... Some React ... */;

keystone.createList('User', {
  fields: {
    name: {
      type: { ...Text, views: { ...Text.views, Field } }
    },
  }
});
```

... which, again, is almost the same, but one less variant to implement / test / document. I don't see the value in having a custom `admin` config object that does the same thing.

Also, nitpick: the Admin UI is _not necessarily_ the only place these views will be used in the future. It's absolutely possible we create form generator components / etc that people can plug into their own projects _outside the Admin UI_ which use these views.

Field types consist of:

- A name
- A back-end Implementation
- Database adapters
- A front-end Controller
- A view for rendering the value in a table
- A view for rendering form UI to edit the value
- A view for rendering the filter UI

When fields are configured in a list, they are given a `path`, their `type` and config which is interpreted by both or either of Keystone itself and the field type Implementation.

We could extend this spec in all sorts of interesting ways in the future, including version compatibility information, etc.

**Comment by gautamsi** [comment]
related #2155
