### ISSUE TITLE
Models import function

### ISSUE THREAD

**Issue by nicdutil** [keystonejs/keystone#1056]
While playing around with various ways to specify a value for the cloudinary config, I stumbled upon an ordering issue that could be improved upon.  Suppose we want to set our cloudinary config in code using keystone.set: 
```
keystone.set('cloudinary config', { cloud_name: 'my-cloud', api_key: 'abc', api_secret: '123' });
```
If I have a model that uses the CloudinaryImage Type, then we must set this option before importing the models, otherwise we get the following error:

```
node main.js
Error: Invalid Configuration

CloudinaryImage fields (Client.image) require the "cloudinary config" option to be set.

See http://keystonejs.com/docs/configuration/#services-cloudinary for more information.
```
So,
*Bad ordering*
```
keystone.import('models');
keystone.set('cloudinary config', { cloud_name: 'my-cloud', api_key: 'abc', api_secret: '123' });

```
*Good ordering*
```
keystone.set('cloudinary config', { cloud_name: 'my-cloud', api_key: 'abc', api_secret: '123' });
keystone.import('models');
```
A similar issue happens when setting navigation using keystone.set.  So, keystone.set for these examples triggers certain validation steps that will halt the app if not satisfied. It is not immediately obvious in the error message above, for instance, why the app failed since we did set the 'cloudinary config' option in the code. 

A couple of suggestions to improve this situation:

1 - **Better error messages** (maybe an hint: did you set the option before importing your models)

2 - **Why not include the importing of the models as part of the initialization of the keystone app ?** 
I am not sure why we need to be explicit about the importing of the models.  The keystone.init function could just scan for a folder (configurable) to look for models to import, with an option to shut off the importing of the models. I think 99% of projects using Keystone will at least have one model (User)..  

3 - **Delay validation of Types at startup.**
This might involve a bit of code change though.. 

Thoughts ?

**Comment by mxstbr** [comment]
I think it's fine the way it works right now, so I'll close this issue for now—I do prefer your version, so if you're motivated I'd be happy to point you in the right direction!
