### ISSUE TITLE
Allow reordering of CloudinaryImages

### ISSUE THREAD

**Issue by albertogasparin** [keystonejs/keystone#1060]
It would be nice being able to sort and reorder CloudinaryImages. Currently, you have to delete and reupload all images if you need to change the order.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/allow-reordering-of-cloudinaryimages
