### ISSUE TITLE
DateField: Replace "pickaday" with a react date/time picker

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#1065]
During a conversation with with @JedWatson it was suggested that we should replace the non-react date picker (pickaday) with an existing react component.

There are a number of options available available to us today. Out of our existing choices I would like to suggest the [date & time picker](http://jquense.github.io/react-widgets/docs/#/datetime-picker) from [React Widgets](http://jquense.github.io/react-widgets/docs/#/).

I've created a sample, fully functional `DateField` for Keystone using this component. You can check it out and test it on the `feature/datefield-wip` branch of [my Keystone fork](https://github.com/JohnnyEstilles/keystone/tree/feature/datefield-wip).

Let me know what you think.

**Comment by lojack** [comment]
This works for me, and solves #1038

**Comment by JohnnyEstilles** [comment]
@lojack, yes this would solve #1038, that is the intention. Not sure if there's any community interest in using these existing components, so it might not get implemented.

**Comment by JohnnyEstilles** [comment]
Closing due to lack of community interest ...

**Comment by JedWatson** [comment]
Sorry @JohnnyEstilles! I was getting to it :/

**Comment by internetErik** [comment]
For what it's worth I was also having issues with the current Date ui ( #1038).  Switching to a react component would be more consistent, and hopefully fix this.

**Comment by morenoh149** [comment]
@JohnnyEstilles I think it's the right way forward. Did you see my debugging in the slack room? pikaday is definitely the culprit (or the way pikaday is being called/initialized is the culprit).

**Comment by JohnnyEstilles** [comment]
@morenoh149 ... I did. I'm not 100% certain that `pikaday` is the culprit, but regardless I think we should start moving towards React components. While I'm sure we can use non-React components if we carefully design the React wrapper, the difficulty troubleshooting these components makes them less than desirable. Take this case, for example, where many of us can even replicate the problem at hand.
