### ISSUE TITLE
Need Docs: Code field type

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1070]
I just realised the Code field is completely missing from the Database docs.

We need to add it, should be pretty simple, something along the lines of:

- Code field is a String path
- Uses CodeMirror for the editor UI
- Supports options `heigh` (default 180) and `language`
- Valid language options are
    - `c`
    - `c++`
    - `objectivec`
    - `css`
    - `asp`
    - `c`
    - `vb`
    - `xml`
    - `php`
    - `html`
    - `ini`
    - `js`
    - `java`
    - `coffee`
    - `lisp`
    - `perl`
    - `python`
    - `sql`
    - `json`
    - `less`
    - `sass`
    - `sh`
    - `ruby`
    - `jsp`
    - `tpl`
    - `jade`

**Comment by theolampert** [comment]
Started this on my fork here https://github.com/theolampert/keystone however a little unsure if the language values should be formatted with a line break or not, looks a little odd to me but maybe more readable. This also addresses #1105 in a previous commit. Let me know if I should change anything and I'll make a PR.
