### ISSUE TITLE
WYSIWYG editor is killed when using dependsOn

### ISSUE THREAD

**Issue by lojack** [keystonejs/keystone#1071]
To reproduce this, using the following schema:

    ContentBlock.add(
        {
            title: { type: String, required: true },
            blockType: { type: Types.Select, options: ['One', 'Two'] },
        },
        {
            content: { type: Types.Html, wysiwyg: true, dependsOn: { blockType: 'Two' } }
        }
    );

Simply set blockType to be 'Two' and you'll get a text editor without WYSIWYG controls. Saving the piece of content will make the controls appear.

**Comment by tivac** [comment]
I'm also seeing this. If the `dependsOn` check is truthy at render time it shows the wysiwyg controls fine. If the field is then hidden and reshown based on user input it will have lost the wysiwyg controls again.

**Comment by drlogout** [comment]
same problem here.
