### ISSUE TITLE
Need Docs: Note on Select FieldType similar to Enum

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#1077]
PR #1076

[https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/database.jade#L858](https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/database.jade#L858)

**Comment by morenoh149** [comment]
@JohnnyEstilles there's no `es` dir? https://github.com/keystonejs/keystone/tree/master/docs/content

**Comment by JohnnyEstilles** [comment]
@morenoh149 it currently doesn't, but it will soon.

[https://github.com/JohnnyEstilles/keystone/tree/docs-es/docs/content](https://github.com/JohnnyEstilles/keystone/tree/docs-es/docs/content)

Check out issue #953. We're tagging all new `Need Docs` issues with `ES` (in addition to `ZH`) so that when I'm done translating I can go back (retroactively) and add anything that change or didn't exist when I started.

**Comment by weekwood** [comment]
@JedWatson Chinese doc added.

**Comment by JedWatson** [comment]
Thanks @weekwood!

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/103
