### ISSUE TITLE
Core templates/mixins override

### ISSUE THREAD

**Issue by megheaiulian** [keystonejs/keystone#108]
Is it possible to override the default templates/mixins?
For S3File I would like to add a isImage virtual field then override formField_s3file mixin in order to output a IMG tag in admin if the file is a image.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. If this issues still persists, please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)!
