### ISSUE TITLE
No longer an option to autodetect geo for Location Fields

### ISSUE THREAD

**Issue by stephencoe** [keystonejs/keystone#1083]
I have upgraded to the latest version using react and notice that there is no longer an option on the Location field type to allow the user to "Autodetect and improve location on save".

Having looked around at the legacy code this was in the template ```/keystone/template/fields/location/form.jade``` 

In the current version ```enableMapsAPI``` is being set but I couldn't find anywhere using the value to show this data
 
https://github.com/keystonejs/keystone/blob/master/fields/types/location/LocationType.js#L27

If this has been removed for a reason then is there a way to show it?

**Comment by whnunlife** [comment]
Yeah, I've been running into the same issue as well.

**Comment by morenoh149** [comment]
it was probably on oversight. We're trying to fix a lot of things in the 0.3.x versions.
