### ISSUE TITLE
Multiple relationships dont show up

### ISSUE THREAD

**Issue by manikantapanati** [keystonejs/keystone#1084]
I have three models - Product, Gallery, Review and the following relationship on Product List
```
Product.relationship({ ref: 'Gallery', path: 'product' });
Product.relationship({ ref: 'Review', path: 'product' });
```
```
var Gallery = new keystone.List('Gallery', {
});

Gallery.add({
	product: { type: Types.Relationship, ref: 'Product', many: false },
});

Gallery.register();
```

```
var Review = new keystone.List('Review', {
});

Review.add({
	product: { type: Types.Relationship, ref: 'Product', many: false },
});

Review.register();
```
However, only 1 relationship shows up on Admin UI
![capture](https://cloud.githubusercontent.com/assets/11090147/6286015/c382ed98-b8d0-11e4-86b8-4b0e9c2b2305.PNG)

**Comment by webteckie** [comment]
@manikantapanati what if you do something like:

```
Product.relationship({ ref: 'Gallery', path: 'galleries', refPath: 'product' })
Product.relationship({ ref: 'Review', path: 'reviews', refPath: 'product' })
```

**Comment by manikantapanati** [comment]
Yep, that works. thanks @webteckie 
![capture](https://cloud.githubusercontent.com/assets/11090147/6286653/0962fbc6-b8d8-11e4-8203-cba5e5bf2ec8.PNG)
