### ISSUE TITLE
Update to 0.3.1 from 0.2.39

### ISSUE THREAD

**Issue by jazz-ik** [keystonejs/keystone#1087]
Hi!

How can I update cms from 0.2.39 to 0.3.1?

Thanks!

**Comment by JedWatson** [comment]
@jazz-ik you just need to update the version of Keystone that is declared in your `package.json` file.

There'll be a line that looks like this:

```
"keystone": "~0.2.39",
```

Change it to 

```
"keystone": "~0.3.1",
```

Then run `npm update`.

Also review the [upgrade guide in our wiki](https://github.com/keystonejs/keystone/wiki/0.2.x-to-0.3.x-Changes) to make sure you're across the other changes that you may need to your application.

**Comment by jazz-ik** [comment]
Thanks! and thanks for cms!
