### ISSUE TITLE
Unwanted empty sessions persisted when using Passport and NewRelic

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#1092]
First, I want to clarify that this issue is not exclusive to [NewRelic](http://newrelic.com). I've actually experienced the same issue with other monitoring services, but I didn't want to mention them all on the issue title, so I picked NewRelic, which is the one I use the most.

### Background
Out of the box, Keystone handles sessions beautifully. It defaults the Express session `saveUninitialized` option to `false` so that new/unmodified session objects are not persisted. As a lot of you probably already know, I'm a fan of using [Passport](http://passportjs.org) for authentication in my Keystone powered apps (which is why I created [KSL](https://github.com/JohnnyEstilles/keystone-social-login)). Unfortunately, Passport stores an empty authentication object in the session for later use (see note under the docs for [saveUninitialized](https://github.com/expressjs/session#saveuninitialized)). This renders the `saveUninitialized` option virtually useless.

### The Problem
The Keystone+Passport scenario is not a big deal under normal circumstances. Sessions of unauthenticated visitors eventually expire and are removed during garbage collection. Now add to this scenario a monitoring service like NewRelic, which frequently pings your website/webapp (typically with a simple and un-intrusive `HEAD` request), and we have ourselves a bunch of orphaned empty sessions lingering round in our persisted datastore. Without Passport, this is not a problem because uninitialized sessions would simply not be persisted (assuming `saveUninitialized` is set to `false`). But since Passport ALWAYS causes the session to be persisted, EVERY `HEAD` request originating from NewRelic (or whatever monitoring service) will cause hundreds or even thousands of empty sessions to be persisted, depending on monitoring frequency and session expiration settings.

One of my Keystone apps accumulates around 20,000+ of these orphaned empty sessions. If your using Mongo to persist your sessions I guess it's not much of a big deal, but if you're using Redis ... I don't think you want 20,000 of these babies lingering in memory.

### Proposed Solution
In my non-KeystoneJS apps I deal with this by NOT loading the Express session middleware during `HEAD` requests. The code looks something like this:

```js
var session = require('express-session');
var sessionOptions = { ... };

app.use(function (req, res, next) {
  var method = req.method.toLowerCase();

  // ignore HEAD requests
  if (method === 'head') {
    return next();
  }

  // initialize session middleware
  var expressSession = session(sessionOptions);
  return expressSession(req, res, next);
});
```

Unfortunately, Keystone doesn't afford the developer any control over whether or not to load the Express session middleware.

As a solution to my problem I would like to propose adding an optional Keystone setting called `express session load`. When set to a function, Keystone will invoke it with the `express-session` instance as an argument, allowing it to conditionally decide whether or not to use the Express session middleware. Otherwise (i.e. when not set or set to anything other than a function), Keystone will simply load the Express session middleware as it currently does.

If implemented it could be used as follows:

```js
keystone.init({
...
  'express session load': function(session) {
    return function(req, res, next) {
      var method = req.method.toLowerCase();
      if (method === 'head') {
        return next();
      }
      return session(req, res, next);
    }
  },
...
});
```

@JedWatson, is this something you would be willing to include in Keystone?

If anyone can think of any other way I can resolve this, as always, I'm open to suggestions.

**Comment by JohnnyEstilles** [comment]
After some research I found an easier way to circumvent this problem, regardless of whether or not I'm using Keystone.

Closing issue ...

**Comment by SharadKumar** [comment]
And what was the solution John? :)

I have about 120K sessions persisted in my app over last one week!

**Comment by JohnnyEstilles** [comment]
Sharad! :-) Sorry about that. I did' t think anyone was interested (lack of comments). 

Are you having the same issue, due to a monitor service creating orphaned sessions? If so, does your monitoring service use `HEAD` requests to check for availability (the way Newrelic does)? I only ask because my solution only works under the previous circumstances.

**Comment by SharadKumar** [comment]
My problem was a bit more pronounced with crawlers, so tried to detect user-agent:

if (ua.match(/curl|Bot|B-O-T|Crawler|Spider|Spyder|Yahoo|Java\/|ia_archiver|Covario-IDS|findlinks|DataparkSearch|larbin|Mediapartners-Google|NG-Search|Snappy|Teoma|Jeeves|Charlotte|NewsGator|TinEye|Cerberian|SearchSight|Zao|Scrubby|Qseero|PycURL|Pompos|oegp|SBIder|yoogliFetchAgent|yacy|webcollage|VYU2|voyager|updated|truwoGPS|StackRambler|Sqworm|silk|semanticdiscovery|ScoutJet|Nymesis|NetResearchServer|MVAClient|mogimogi|Mnogosearch|Arachmo|Accoona|holmes|htdig|ichiro|webis|LinkWalker|lwp-trivial|facebookexternalhit/i)) {
    req.session.destroy();
    return next();
  }
