### ISSUE TITLE
Need Docs: Keystone "frame guard" option

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#1094]
PR #1091

**Comment by weekwood** [comment]
@JedWatson  add ZH via #1095

**Comment by weekwood** [comment]
already merge, ZH tag can be removed.

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/93
