### ISSUE TITLE
Admin UI:  relationship reference view should use field name

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1099]
In the following:
![image](https://cloud.githubusercontent.com/assets/5872515/6320249/ec4bed38-baa6-11e4-9a13-bd99ba67423c.png)

I think if it read 'view home page' and not 'view published module' it would be more intuitive.  'home page' being the field name and 'published module' being the relationship reference.  Of course, if  #564 is implemented then there's no need for this since the 'view xxx' will probably go away.

**Comment by andrewlinfoot** [comment]
This is no longer an issue in 0.4 because the item's name in now the link
