### ISSUE TITLE
Test count regression checking

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#1104]
Tim Leslie   [Today at 16:15]
Thanks @mitchell. Thought bubble: it’d be good if we had some kind of test count regression type thing to catch this kind of oversight. :man-shrugging:
2 replies

Mitchell Hamilton   [2 minutes ago]
i think that’s possible with jest. iirc you can make it write a JSON file with the number of tests, ones that are skipped and other things

Tim Leslie   [< 1 minute ago]
Yeah, presumably there’s a way to get circle CI to investigate that and somehow make noise if the numbers change, maybe just a bot like the changeset bot, rather than a hard and fast PR blocker.

**Comment by MadeByMike** [comment]
@mitchellhamilton or @timleslie can we add a bit more detail to this one please :)
