### ISSUE TITLE
Need Docs: markdown field "height" option

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#1105]
I was just trying out the markdown fieldtype. And found the default size too narrow.
Luckily it supports a height argument like so
```javascript
    extended: {
      type: Types.Markdown,
      height: 500
    }
```
[Markdown](http://keystonejs.com/docs/database/#fieldtypes-markdown) needs the height argument documented like [HTML](http://keystonejs.com/docs/database/#fieldtypes-html)

**Comment by JohnnyEstilles** [comment]
EN docs added via #1109

**Comment by weekwood** [comment]
ZH docs added via #1119

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/94
