### ISSUE TITLE
Create Item form maximize

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#1106]
I see that Create <Schema Item> model slides from right. it is good for quick creation of items. I would suggest make this a full page view similar to edit existing item view. 

There should be either maximize button to expand that form into a full form or we limit the form controls for fields by using `initial` attribute like in v4

**Comment by jossmac** [comment]
The horizontal space in the create drawer is _about_ the same width as on the item details screen, so not sure if "fullscreen" behaviour would help too much.

Definitely agree that we should support initial fields like v4. Something like:

```js
keystone.createList('Post', {
  fields: {
    title: { ... },
    author: { ... },
    categories: { ... },
    status: { ... },
    body: { ... },
  },
  adminConfig: {
    initialFields: ['title', 'author'],
  }
});
```

* * *

**Related**: we should also support `requiredFields`, which could inform `initialFields` when not provided.

**Comment by gautamsi** [comment]
I see that edit screen is slightly (10%) bigger for me. Looks like the `Wysiwyg` field which is stretching and makes me think this is better view for items with many fields. 
![image](https://user-images.githubusercontent.com/5769869/57502511-b5974380-7309-11e9-9bdc-7d06ebfc922f.png)

My personal feeling is that centered screen would be better for large number of fields. 

One more caveat with the sidebar: It disappear when you click anywhere on screen. I am not against the sidebar design, but we should be able to promote this to full centered view. I see that it retains the text entered on the fields but accidental clicks may move to different list where those temporary texts are lost. This behavior is annoying.

I propose option similar to one you see on gmail compose VV, it sould be top right corner, next to cancel/create button or to be right/left of the title of sidebar ("Create user")
 
![image](https://user-images.githubusercontent.com/5769869/57502655-49690f80-730a-11e9-8e45-2287764a222b.png)

A configurable default would be helpful. As a user, I may not want to do it on sidebar as most of my lists have many fields, I should be able to change this for Keystone or per list.

**Comment by MadeByMike** [comment]
Yep I's support this

**Comment by MadeByMike** [comment]
A maxamise button like gmail.

**Comment by jossmac** [comment]
> A configurable default would be helpful.

We need to address these sorts of issues with a proper plugin architecture, rather than endless configuration. Please don't implement this.

**Comment by jooola** [comment]
What about making this configurable when creating the list ?
Some list are known to contains only a few fields, other like a blog post might contains more data and require a full width editor.

Creating a new item could open either a full width editor or a side editor depending on this switch.

Also like you said, clicking on the side closes the editor, this is IMO dangerous when you have a content editor writing a long post. He might at some point loose his content.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
