### ISSUE TITLE
Location Field International Format

### ISSUE THREAD

**Issue by diablo2man** [keystonejs/keystone#1106]
According to [document](http://keystonejs.com/docs/database/#fieldtypes-location), we need to update schema to support non-AU address. Can anyone provide document/help on that? I just want standard US address format.

Thanks!

**Comment by JohnnyEstilles** [comment]
@diablo2man, I think what the note under the [Location Field Type](http://keystonejs.com/docs/database/#fieldtypes-location) is trying to say is that the `path` names currently implemented in the `Location` field reflect those commonly used to denote Australian-based addresses, and at the same time it's requesting community input as to how best to "rename" these (internally within Keystone) to better suit international addressing standards. It is not suggesting that there is a "non-documented" way to achieve this at the moment.

Personally I'm for using the widely used [PostalAddress](http://schema.org/PostalAddress) schema from [schema.org](schema.org).

Can you provide any other suggestions on how we should implement this?

**Comment by diablo2man** [comment]
@JohnnyEstilles thanks for the reply. I understand dealing with international location format may be non-trivial since every country has its own address convention. 

I think the postalAddress schema from schema.org looks good to me. But does it take a lot of effort to implement a generic one? I just wonder if there is a quick hack that I can use for shot-term project.

Thanks.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/location-field-international-format
