### ISSUE TITLE
Uploaded Image Preview for LocalFiles (and AzureFiles)

### ISSUE THREAD

**Issue by internetErik** [keystonejs/keystone#1108]
I have a project requirement to show a preview for images uploaded in the admin.  We are using AzureFiles.  I can get this working simply by swapping the CloudinaryImageField in for the LocalFileField in `fields/types/azurefile/AzureFileField.js`.

I assume the reason AzureFile uses LocalFile instead of CloudinaryImage is that AzureFile and LocalFile could be file types other than image (e.g., docx).  This seems sane.  However, would there be interest in having preview support on LocalFile (and so AzureFile) if we could determine that it was an image file type?  What concerns would there be with doing this?

CloudinaryImageField suggests there is support for these file types:
`var SUPPORTED_TYPES = ['image/gif', 'image/png', 'image/jpeg', 'image/bmp', 'image/x-icon', 'application/pdf', 'image/x-tiff', 'image/x-tiff', 'application/postscript', 'image/vnd.adobe.photoshop'];`

I would be happy to write a PR for this.

**Comment by morenoh149** [comment]
I think it'd be very welcome. If you could make the code that detects whether the filetype is a known image type flexible enough to be used for the s3filetype as well that'd be great.

Related https://github.com/keystonejs/keystone/issues/916

**Comment by JedWatson** [comment]
See #1222
