### ISSUE TITLE
Document steps to create new field types

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone#111]
Need to have some documentation/guidance for how to create new field types.

**Comment by cameronjroe** [comment]
Any chance that gist could go in the wiki for now? Until the docs are updated?

**Comment by JedWatson** [comment]
Actually that gist is way out of date, and we're about to publish a new version that will have much better support for adding field types. I'd hold off a few weeks until we get that out and I can do an updated writeup.

**Comment by kadosh1000** [comment]
Hi I have published my npm package: 
https://github.com/kadosh1000/keystone-custom-fieldtypes

It copies your custom fieldTypes from a selected dir into the keystone's fields dir and registers it

**Comment by mxstbr** [comment]
Will do after we've published 0.4, closing this issue to keep the issue tracker as clean as possible.
