### ISSUE TITLE
Populate Array and use it in views Failed - Undefined Error

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1117]
I have an array of objects ***organisations***, in which has an array of ***clients***

I can populate it in my routes

```
  view.query('organisations', Organisation.model.find()
                        .where('createdBy', req.user._id)
                        .populate({ path: 'clients', select: 'slug redirectUri' })
                        .sort('name'));
	view.render('site/organisations');
```
But the ***clients is undefined*** in views

```
// in organisations view
      if organisations.length
        each org, i in organisations
          if i
            hr
          +organisation(org)

// in origanisation.jade mixins

        if org.clients.length    // << Cannot read property 'length' of undefined
          a
            | Client
            each client, i in org.clients
              =client.redirectUri    
            


```

**Comment by morenoh149** [comment]
did you see field selection here http://mongoosejs.com/docs/populate.html ?
See the example under *Field selection difference from v2 to v3*
try it as strings
```
.populate('clients', 'slug redirectUri')
```

**Comment by arthurtalkgoal** [comment]
Hi, 

That create same error - clients undefined

```
  view.query('organisations', Organisation.model.find()
                        .where('createdBy', req.user._id)
                        .populate('clients', 'slug redirectUri')
                        .sort('name'));
```

More, I have verified, the Organisation has a client exists:

![oraginization](https://cloud.githubusercontent.com/assets/7088330/6386376/7677d824-bdb2-11e4-9b1a-df253e8f976e.jpg)

**Comment by arthurtalkgoal** [comment]
Here is my models codes:

```
/**
 * Client Model
 * ==========
 */


var Client = new keystone.List('Client', {
	autokey: { path: 'slug', from: 'client_id', unique: true },
  track: true
});

Client.add({
	client_id: { type: String, initial: true, required: true, index: true, unique: true  },
	client_secret: { type: String, initial: true, required: true },
  status:  { type: Types.Select, options: 'active, inactive, overdue', required: true, default: 'active'},
  redirectUri: { type: String },
  organisation: { type: Types.Relationship, ref: 'Organisation'}, //, filters: { group: 'admin' } },
  machine: { type: Types.Relationship, ref: 'Machine', filters: { group: 'admin' } },
});



/**
 * Organisations Model
 * ===================
 */

var Organisation = new keystone.List('Organisation', {
	autokey: { path: 'slug', from: 'name', unique: true },
  track: true
});

Organisation.add({
	name: { type: String, index: true, initial: true, required: true },
	logo: { type: Types.LocalFile, dest: 'public/uploads/organisations' },
	email: { type: Types.Email, initial: true, required: true, unique: true  },
  telephone: { type: String, required: true, initial: true },
  fax: { type: String },
  address: { type: Types.Location },
  description: { type: Types.Markdown }
  
});


/**
 * Relationships
 * =============
 */

Organisation.relationship({ path: 'clients', ref: 'Client', refPath: 'organisation' });

**Comment by JohnnyEstilles** [comment]
@arthurtalkgoal in your original comment you said that `Organisation` has an array of `clients`. That appears no to be the case, at least according to the models you posted. 

In order to achieve your goal, two things must happen:

1. `clients` must be explicitly defined in `Organisation` as an array of `ObjectId`. 
2. You must push every client onto the the `clients` array. 

If these two conditions aren't met, mongoose has no way of populating the array the way you want.

**Comment by JohnnyEstilles** [comment]
Check out the link to the Mongoose docs that @morenoh149 referred to, under the heading "Refs to Children".

**Comment by arthurtalkgoal** [comment]
HI @JohnnyEstilles ,

First off, thanks. Re pushing ```clients``` array, I have read that Mongoose docs. Sorry that I don't quite relate it in Keystone. 

AS my attached image above show, My Organisation has relate to at least one Client (it is displayed in the keystone backend Organisation object).

Is it the same as the section ***Refs the childen*** doing:
```
aaron.stories.push(story1);
aaron.save(callback);
```

Or I have to
```
.populate('stories')
.exec(function (err, person) {

// should I Push the arrays here explicitly?

  if (err) return handleError(err);
  console.log(person);
})

```

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
