### ISSUE TITLE
evalDependsOn should be refactored as a state change

### ISSUE THREAD

**Issue by matogertel** [keystonejs/keystone#1122]
Here's the situation:
- I'm writing a custom field type that has a google map inside
- I've used my new field type in an object, and it depends on another property of the object.
- So far so good, the field itself shows and hides as expected in the GUI... however...
when it shows I need to redraw the map, otherwise it doesn't fill the whole div its attached to.

After experimenting a little bit, I came to the conclusion that the best way would have been to have a state 'evalDependsOn'

My current code:

    /*
    * Had to make a local copy of `evalDependsOn` since its not exposed by the module
    */
    componentWillReceiveProps: function(nextProps) {
        var evalDependsOn = !evalDependsOn(this.props.dependsOn, this.props.values)
        this.setState({
            evalDependsOn: evalDependsOn
        });
    },

    shouldComponentUpdate: function(nextProps, nextState) {
        var evalDependsOn = !evalDependsOn(nextProps.dependsOn, nextProps.values) ;
        var shouldUpdate = (this.state.evalDependsOn !== evalDependsOn);
        return shouldUpdate;
    },

    componentDidUpdate: function() {
        if (!this.getDOMNode()) return;
        this.refreshMap({ timeoutRefresh: 500 });
    },

Ideal code:

    /*
     * No need to override componentWillRecieveProps, as state is already populated 
     * by the parent Field object
     */
    shouldComponentUpdate: function(nextProps, nextState) {
        var shouldUpdate = (this.state.evalDependsOn !== nextState.evalDependsOn);
        return shouldUpdate;
    },

    componentDidUpdate: function() {
        if (!this.getDOMNode()) return;
        this.refreshMap({ timeoutRefresh: 500 });
    },

**Comment by mxstbr** [comment]
I'll close this issue due to age, let me know if this is still something you'd like considered!
