### ISSUE TITLE
Should I implement Local Image and Local Image Array

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1123]
Hi, I found that keystone has very good File field, I use it to upload my client logo. 

However, what I need is something like 
CloudinaryImages
CloudinaryImage

It seems that there is no dedicated field for the LocalPicture, such as with thumbnail and DropDrop Upload plugins.  Should I implement one? 

If so,  LocalPictures (Array) is also good for me. 

Before my implementation, I wanna see if the community welcome such a picture field?

**Comment by JedWatson** [comment]
@arthurtalkgoal we are currently working on a new refactored File field (see @sebmck's work in the `file-fields` branch). The plan is to develop `Image` and `Images` fields based on this work as soon as they launch. Any involvement with those fields (writing tests, adding features, enhancing UI, etc.) would be very welcome.

**Comment by JedWatson** [comment]
I'm going to close this as it's more of a question than an issue, but if you want to get involved please send me your email address and I'll invite you to our slack channel where we can discuss development of the fields.

**Comment by arthurtalkgoal** [comment]
HI JedWatson, I am happy to contribute! Can you add me to the list.

**Comment by JedWatson** [comment]
jed at keystonejs dot com :)
