### ISSUE TITLE
Best practice for pushing to a Model array

### ISSUE THREAD

**Issue by vfermino** [keystonejs/keystone#1124]
Hello. I'm trying to make a simple Wishlist, and for that, I'm doing the following:
- a Types.Select array for the User model with a Relationship to the Product model (which is the thing wished for), so when someone wishes for an item, it appears for this User specifically  
- a cart route/view, which basically shows the items wished for.  

The problem I'm having is that to push an item to a Types.Select, or any array for that matter, there seems to be more than one option. When I used this same thing with Strings, I could just sum one String with another to update the User instance, but with an array of objects, should I just use the Mongoose $push directly or is there a better option in Keystone to push items from a view to a model?  
Here's an example of what I have been doing:
```
var keystone = require('keystone'),
	Product = keystone.list('Product'),
	User = keystone.list('User');

exports = module.exports = function(req, res) {
	
	var view = new keystone.View(req, res),
		locals = res.locals;
	
	// Set locals
	// Init locals
	locals.section = 'catalog';
	locals.filters = {
		product: req.params.product
	};
	locals.data = {
		products: []
	};
	locals.formData = req.body || {};
	locals.validationErrors = {};
	locals.orderPieceAdded = false;
	
	// Load the current product
	view.on('init', function(next) {
		var q = Product.model.findOne({ slug: locals.filters.product });
		q.exec(function(err, result) {
			locals.data.product = result;
			next(err);
			if(result.state!='oculto' || result.state!='rascunho'){
				console.log("This should load the product page.");
			}else{
				console.log("This should NOT load the product page.");
				res.redirect('catalog');
			}
		});
	});
	
	view.on('post', { action: 'cart' }, function(next) { // The wish is made by a POST
		var query = {'_id': req.body.user};
		User.model.findOne({_id: req.body.user}, function(err, user){
			if (err) { return next(err); }
			if(!JSON.stringify(user.cart).search(req.body.product)){ // I'm sure there is a better way to do this
				console.log("Already on the list!");
			}else{
				console.log("Not on the list!");
				user.cart = user.cart  - ']' + '\"' + req.body.product + '\"]'; // This is what I'm trying to do, although I can't update if I treat the array as an String. In fact, I can't even change it.
				user.save(function(err) {
					
				});
			}
				if (err) { return next(err); }
		});
		next();
	});
	
	// Render the view
	view.render('product');
};

```
I'm sorry if this problem is too specific. Thanks.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
