### ISSUE TITLE
What about fuzzy search in relationship field autocomplete?

### ISSUE THREAD

**Issue by outluch** [keystonejs/keystone#1125]
Made fuzzy search for autocomplete in relationship field
1) made new regexp near `splitSearchRx` [line 840](https://github.com/keystonejs/keystone/blob/master/lib/list.js#L840):
`fuzzySearchRx = new RegExp((searchParts.length > 1) ? _.map(searchParts, utils.escapeRegExp).join('.*') : search, 'i'),`

2) added this at [line 870](https://github.com/keystonejs/keystone/blob/master/lib/list.js#L870):
```
} else if (field && field.type === 'text' && field.path === 'name') {

  searchFilter = {};
  searchFilter[path] = fuzzySearchRx;
  searchFilters.push(searchFilter);
```
Profit!
Now if i have this dropdown http://take.ms/xsqqj and I can filter with string `al mo 54` for example
I'm quite new to github, so maybe someone make this mod to keystone, if it you think it is usefull?

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/fuzzy-search-in-relationship-field-autocomplete
