### ISSUE TITLE
dependsOn truthy issue and S3 file no longer links in admin UI

### ISSUE THREAD

**Issue by AndersonTaylor** [keystonejs/keystone#1130]
In  version 2.x   I could use

```
dependsOn: { fieldName: true }
```
to match (I assume) a truthy value.

For example:

```
Foo.add({
	name: { type: Types.Text, required: true, index: true },
	optionalInfo: { type: Types.Text },
	moreAboutOptional: { type: Types.Text, dependsOn: { optionalInfo: true } },

	upload: { type: Types.S3File, s3path: 'uploads' },
	uploadExtendedInfo1: { type: Types.Number,  dependsOn: { upload: true } },
	uploadExtendedInfo2: { type: Types.Textarea, dependsOn: { upload: true } }
});
```

In version 2.x moreAboutOptional would appear as soon as you tabbed/clicked out of a non-empty optionalInfo box.  The uploadExtendedInfo fields would only appear after a save (but that's good enough for my use case).

![screen shot 2015-03-01 at 2 09 59 pm](https://cloud.githubusercontent.com/assets/1709939/6432634/9102b034-c01d-11e4-8fb2-f05a3730a77d.png)

In version 3.x  neither shows up, even after the save.

![screen shot 2015-03-01 at 2 08 09 pm](https://cloud.githubusercontent.com/assets/1709939/6432638/a6ad1aaa-c01d-11e4-8810-bd43c973cf10.png)

The second issue is the 2.x version gives a link to the s3 file and the 3.x version just gives a 
text box with the filename.

(sorry, not sure if github etiquette is to report these separately, I just noticed this when I was making the screenshots)

**Comment by albertogasparin** [comment]
I confirm that the described behaviour got lost. I've done a PR to restore it.
