### ISSUE TITLE
EJS in keystone package.json

### ISSUE THREAD

**Issue by captainchung** [keystonejs/keystone#1131]
When I looked at the keystone package.json i did not see ejs in there. Is it no longer supported or accidentally removed?

**Comment by JohnnyEstilles** [comment]
Internally, Keystone uses `jade`. In your app you can use any express-supported engine, but you will have to add it yourself to your project's dependencies in your `package.json`. See `view engine` under the Keystone [Web Server Options](http://keystonejs.com/docs/configuration/#options-server) for more information.
