### ISSUE TITLE
Bug in 3-level Conditional Selection

### ISSUE THREAD

**Issue by bigfoam** [keystonejs/keystone#1136]
I added a 3-level conditional select in add function in model/Post.js (and you can add the code to any model). In Admin UI,selecting level_2 = 2 will trigger the showing of level_3, but level_3 will not show up when selecting level_2 = 1.

![1](https://cloud.githubusercontent.com/assets/4132817/6457772/a8ff2ef2-c148-11e4-90eb-c67c6692aa42.png)

level_3 is not showing

![2](https://cloud.githubusercontent.com/assets/4132817/6457773/a8ff88f2-c148-11e4-8b53-6671ce5228a0.png)

level_3 is showing

Here is my code:

'3-Level Conditional Select',
{ level_1: { type: Types.Select, options: ['1', '2', '3'] } },
//level_1 = 3 will not result in a next level selection----------------------------------------------------
{ level_2: { type: Types.Select, options: ['1_1', '1_2'], dependsOn: { level_1: '1' } } },
{ level_2: { type: Types.Select, options: ['2_1', '2_2'], dependsOn: { level_1: '2' } } },
//------------------------------------------------------------------------------------------------------------------
{ level_3: { type: Types.Select, options: ['1_1_1', '1_1_2'], dependsOn: { level_1: '1', level_2: '1_1' } } },
{ level_3: { type: Types.Select, options: ['1_2_1', '1_2_2'], dependsOn: { level_1: '1', level_2: '1_2' } } },
{ level_3: { type: Types.Select, options: ['2_1_1', '2_1_2'], dependsOn: { level_1: '2', level_2: '2_1' } } },
{ level_3: { type: Types.Select, options: ['2_2_1', '2_2_2'], dependsOn: { level_1: '2', level_2: '2_2' } } },

Thanks for helping me!

**Comment by bigfoam** [comment]
Anyone has the same trouble as me?

**Comment by webteckie** [comment]
@bigfoam in level 3 have you tried using an array of dependsOn, instead?  For example:
```
{ level_3: { type: Types.Select, options: ['1_1_1', '1_1_2'], dependsOn: { [level_1: '1', level_2: '1_1']} } },
{ level_3: { type: Types.Select, options: ['1_2_1', '1_2_2'], dependsOn: { [level_1: '1', level_2: '1_2']} } },
{ level_3: { type: Types.Select, options: ['2_1_1', '2_1_2'], dependsOn: {[level_1: '2', level_2: '2_1']} } },
{ level_3: { type: Types.Select, options: ['2_2_1', '2_2_2'], dependsOn: {[level_1: '2', level_2: '2_2']} } },
```

**Comment by bigfoam** [comment]
@webteckie Thanks for the suggestion. I tried your code and get the error below:

![untitled](https://cloud.githubusercontent.com/assets/4132817/6487037/e3d1723c-c25c-11e4-8795-4c833ea09d5a.png)

**Comment by webteckie** [comment]
@bigfoam ah, my bad misread the requirements.   I believe the post-merge improvements discussed in #811 may solve it for you.   @snowkeeper what's the status of post-merge improvements discussed in #811?

**Comment by bigfoam** [comment]
@webteckie  Thanks, I will take a look!

**Comment by snowkeeper** [comment]
@webteckie we have not moved the code over to the KeystoneJS org yet.  We can still use it if there is not  a better implementation on npm.  

@bigfoam did you get your use case working?  Just from a quick look you were using the same key name multiple times which would overwrite each other.  The code you posted looks to be functioning correctly.  In the current implementation you need to rename the multiple `level_2` and `level_3` to be unique.

**Comment by bigfoam** [comment]
@snowkeeper Thanks very much for the suggestion of renaming. However, if I do the renaming like:

{ level_1: { type: Types.Select, options: ['1', '2', '3'] } },

{ level_21: { type: Types.Select, options: ['1_1', '1_2'], dependsOn: { level_1: '1' } } },
{ level_22: { type: Types.Select, options: ['2_1', '2_2'], dependsOn: { level_1: '2' } } },

{ level_31: { type: Types.Select, options: ['1_1_1', '1_1_2'], dependsOn: { level_1: '1', level_21: '1_1' } } },
{ level_32: { type: Types.Select, options: ['1_2_1', '1_2_2'], dependsOn: { level_1: '1', level_21: '1_2' } } },
{ level_33: { type: Types.Select, options: ['2_1_1', '2_1_2'], dependsOn: { level_1: '2', level_22: '2_1' } } },
{ level_34: { type: Types.Select, options: ['2_2_1', '2_2_2'], dependsOn: { level_1: '2', level_22: '2_2' } } },


It will create too many records and it's hard for a query to find something with level_3='xxx'. One solution is that I can enum from level_31 to level_34 to see which one is existing.

But if Admin users update the field, for example changing from level_31 to level_32. Two field, level_31 and level_32 will both exist, then I have no way to tell which one is current selection.

So I think conditional select may be a good function to be added.

**Comment by razb** [comment]
I'm having the same issue. I've named the fields to be unique, but there is no way to tell which is the latest value once a change is made.

One potential solution is force an overwrite of the document so that only one set of level1, level2 and level3 fields exists in the document at any point in time 

Another option could be to create hidden fields such as level10, level20, level30 which are updated every time a change is made via pre hooks.

Ideally we should be able to dynamically create the selection for the level 2 and level 3 fields so there would be no need to create multiple fields for each level.

**Comment by wmertens** [comment]
(triage) Is this still happening?

**Comment by stennie** [comment]
Closing out stale issues which predate the Keystone 4 development cycle. If this still affects Keystone 4, please create a new report with further details.

Thanks,  
Stennie
