### ISSUE TITLE
Avoiding extreme bandwidth costs by caching cloudinary images to S3 on high bandwidth sites.

### ISSUE THREAD

**Issue by dboskovic** [keystonejs/keystone#1138]
I had a client who I built a site for (ecommerce) that had a lot of high resolution images. (running about 500gb/mo). Cloudinary charges $500/mo for this usage and Amazon charges about $40. I wrote some middleware that I used to wrap my cloudinary urls with in order to enable caching. This is entirely transparent and still enables you to use all the cool cloudinary effect and resizing functions. Hopefully this is useful to someone! 

I think using `deasync()` here is janky but I couldn't think of another way to do it that allowed for quite as easy a fix.

Maybe this idea though could somehow become a core method on the Keystone cloudinary object? If not, at least for anybody else who has clients really upset about the costs, here's the fix.

https://gist.github.com/dboskovic/23858511bf3c1cbebdbd

**Comment by stephencoe** [comment]
+1 for this, I am having this exact problem right now.

**Comment by morenoh149** [comment]
This is an excellent strategy :+1: 
Ideally I'd love to see all the cloudinary functionality available within keystone itself so we wouldn't have to bother with cloudinary. But in the meantime this seems like a great solution.

Did you consider using fastly or amazon cloudfront for the caching as well? This gist shows how to use one s3 bucket to do 'caching' but for some large traffic sites that may not be enough. It'd be great to demonstrate how to do this in another gist.

**Comment by dboskovic** [comment]
@morenoh149 I did but the basic s3 is enough for this site, you could easily modify the code to include that though.

**Comment by morenoh149** [comment]
added to knowledge base https://github.com/keystonejs/keystone/wiki/Knowledge-Base
