### ISSUE TITLE
Clean up error handling options and default behaviour

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#114]
At the moment, if you've configured 404 / 500 error handlers for Keystone that themselves don't work, node will throw an error relating to the error handler rather than the underlying problem.

A few things could be done to fix this:

* Add documentation for how to configure and use error handling
* Catch errors that occur using the handler and rethrow the original error
* Build more of the standard error handling (including default templates, etc) into Keystone itself so there is less to configure in simple projects

**Comment by mxstbr** [comment]
Highly likely done with 0.4, closing to keep the issue tracker clean.
