### ISSUE TITLE
Warn on multi-user editing

### ISSUE THREAD

**Issue by tivac** [keystonejs/keystone#1148]
If two users are editing the same entry there's currently no warning that another user has it open. Also if another user saves an edit to a field you're looking at/editing there's no notification and your changes will simply blow theirs away.

I realize this can be a really big architectural problem, but I've gotta ask because otherwise our CMS users are going to be stomping all over each other on accident.

**Comment by tivac** [comment]
@JedWatson and I chatted about this for a bit tonight, here's what we discussed.

> **jed**: that's shouldn't be too crazy... I'll ponder on it.
> **jed**: would be _really_ easy if we tied it to the new history feature but might be more useful if it was standalone.
> **jed**: also have to work out a solution for cross-process sharing. we could pretty simply add another system collection for open documents w/ a TTL.
> **tivac**: I was wondering if it made sense to make that part of the `tracking` metadata somehow
> **jed**: I nearly made `history` part of the `tracking` feature but realised it could stand on its own
> **tivac**: yeah, I think the distinction there is useful
> **jed**: Having document "locking" tied to at least _one_ of them would make it easier
> **tivac**: especially since not everyone will want to keep revisions around
> **tivac**: revisions makes diffing/recovering from a conflict easier
> **tivac**: but that's still gnarly code to write
> **jed**: ... you could hash `doc.toObject()` when its loaded and compare that on save, warn if there's a difference. And track `keystone_editor_sessions` in a collection w/ the `list.key`, `doc.id` and `user.id` and use that for warnings. Then it'd be totally independent.
> **jed**: Then pull up the differences... gets a _little_ crazy
> **jed**: Much nicer if you can depend on the revisions
> **tivac**: does a tiered solution make sense? Base-level would be independent which can show a "So and so is editing this" banner w/ no diffing
> **jed**: I was really happy with the way the `changed[]` meta worked out in revisions, by the way. We're going to be able to create a sweet UI with that.
> **tivac**: then if revisions are enabled some sort of differy could be used, though lord knows what that looks like
> **tivac**: especially with some components like datepickers and the like
> **jed**: Tiered solution is pretty in-theme with Keystone. More complicated to build but it's nice to be able to opt-in to different levels.

**Comment by creynders** [comment]
:+1: for the tiered solution, since it allows gradual implementation. Having "so and so is editing" would already be a _huge_ benefit, even if it's just a warning with no other possible course of action than "let's get the hell out".

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/warn-on-multi-user-editing
