### ISSUE TITLE
Allow filtering & connecting with authenticated item

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1148]
For example:

Get all to-do's filtered by the currently authenticated User:

```graphql
query {
  allTodos(where: { user: { _authenticated: true } }) {
    task
  }
}
```

Create a new Todo for the currently authenticated User:

```graphql
mutation {
  createTodo(data: {
    task: "Be awesome",
    user: { connect: { _authenticated: true } }
  }) {
    task
  }
}
```

NOTES:
- The use of `_` is to disambiguate from a possible field called `authenticated`
- We don't need to append the list name to `_authenticated` as we already know it based on context of the type of field we're filtering against.

**Comment by jesstelford** [comment]
Also, for Access Control:

```javascript
keystone.createList('User', {
  fields: {
    email: {
      type: Text,
      access: { update: { authenticatedUser: true } }
    }
  }
});
```

**Comment by MadeByMike** [comment]
@jesstelford what if this was just an implementation of a computed field with a custom function?
