### ISSUE TITLE
Better handling of dropped database connection while app is running

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#115]
At the moment, Keystone.start() listens for `error` and `open` on the mongoose connection.

If the database connection fails on application init, it will log the error and the web server won't start - which is fine.

But if the connection fails after the application has been initialised, the same log message will be displayed (failed to launch: mongo connection error) and the application will continue to try and process requests (probably leading to either a hang or error on the process) - which should be handled better.

This could be improved by managing the internal state of the database connection and displaying a default page if the connection fails, as well as trying to reconnect periodically.

Would be good to look at what mongoose does in this case, and what other robust patterns have been developed as a basis for the best way to implement this.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/better-handling-of-dropped-database-connection-while-app-is-running)!
