### ISSUE TITLE
Relationship fields should be cleaned up when documents are deleted

### ISSUE THREAD

**Issue by liamwooding** [keystonejs/keystone#1152]
If I link some Student documents to a Class using a relationship field, then delete some Students, the relationship field on the Class will still contain their IDs. My feeling is that they should be cleaned up, but this behaviour might not be to everyone's taste, so it could be a field option on Types.Relationship.

It would also be nice to be warned before deleting a document if its ID is found in any relationship fields.

**Comment by ttsirkia** [comment]
Another option (not in this context but generally) would be to delete the linked students if the class is removed. This can be achieved by using pre-save but an option would be much nicer.

**Comment by creynders** [comment]
:+1: for this. It would be very useful in some cases, but I'd prefer the option presented in the admin UI, i.e. you delete a student and you need to choose whether you want all references to them deleted as well.

**Comment by creynders** [comment]
Just another thing, to avoid high search times, it could exclusively search the relationships if they're explicitly set using [relationship definitions](http://keystonejs.com/docs/database/#relationship-definitions).

**Comment by creynders** [comment]
I think I'm going to tackle this one. But I'm going to make it a bit more flexible, i.e. to allow more use cases. My goal is to set up relationship watchers which allow you to react to the removal of their targets, something like this, suppose we got a `UserModel` and `PostModel` with an `author` field which references `UserModel`.

```js
var Post = new keystone.List('Post', {
	map: { name: 'title' },
	autokey: { path: 'slug', from: 'title', unique: true },
	watch:{ 
		author: {
			onRemoveTarget: function(target){
				this.remove();
			}
		}
	}
});
```

This would delete a post if its author is deleted. But if you'd only want to set the reference to null instead, you could do:

```js
onRemoveTarget: function(target){
	this.author=null;
	this.save();
}
```

Or if you prefer non-destructive removals:
```js
onRemoveTarget: function(target){
	this.deleted=true;
	this.save();
}
```

@liamwooding any thoughts?

**Comment by liamwooding** [comment]
@creynders watchers for relationships sounds like a great idea, gives people a lot of options. Go for it!

**Comment by ttsirkia** [comment]
To make this easier to use, I'd also suggest an option in fields to use this kind of default functionality.

**Comment by ttsirkia** [comment]
However, this kind of watchers are great idea!

**Comment by liamwooding** [comment]
Agreed, maybe there could be a field option which is a reference to a handler function:
`{ type: Types.Relationship, ref: 'Class', onRemoveTarget: function ()  { this.remove() } }`

We could provide a default removeThis function for ease of use.

**Comment by ttsirkia** [comment]
I would remain the possibility to add custom functions only in `watch` and in field definition there might be just simple boolean option to delete.

**Comment by creynders** [comment]
Yeah, maybe it _is_ better to have it as a field option instead.

**Comment by ttsirkia** [comment]
`{ type: Types.Relationship, ref: 'Class', removeTarget: true, removeThis: true }`

Something like this but the option names should be good. One removes the target if the parent is removed and the second vice versa.

**Comment by creynders** [comment]
@ttsirkia wait, what?! Ah, I think I get it:

1. `removeTarget:true` if the post is deleted then the user is deleted too
1. `removeThis:true` if the user is deleted then the post is deleted too

That's what you mean? But there's another use case we need to accommodate as well: setting `author` to `null` when the user is deleted. Which is why I opted for a function.

How 'bout something like this: removeTarget accepts either a string with value "remove" or "unreference" or a function?

**Comment by ttsirkia** [comment]
Sounds good to me. And `true` can be parsed as remove, for example. But those names are not good they are too confusing as you already noticed.

**Comment by creynders** [comment]
However, I think the `removeTarget` functionality as you propose it, might be confusing and potentially harmful and it's not really necessary is it?

The way I see it now is to have `onRemoveTarget` as a field option that accepts a string with values "remove" and "unreference" or a function. And that's it.

**Comment by ttsirkia** [comment]
`onRemoveTarget` is definitely more important and higly useful.

However, as I already mentioned earlier, there might be problems to implement this if `MyModel.model.remove` is used because no `pre`or `post` events are fired. To make sure that everything works, an object must be first searched and then remove called on that object.

**Comment by creynders** [comment]
Argh, yes, of course. Sorry, I somehow overlooked you mentioning that. Likaa kaljaa eilen :wink: 

Hmmm I'll need to ponder on this.

**Comment by JohnnyEstilles** [comment]
@creynders ... I think that your proposal is excellent. I wanted to ask, will your solution address `ObjectId` cleanup in many-to-one relationships? For example:
```js
Class.add({
  ...
  students: { type: Types.Relationship, ref: 'Student', many: true, onTargetRemove: 'remove' },
  ...
});
```
So that when a student is removed, it is likewise removed from the `students` array of `ObjectId`.

**Comment by creynders** [comment]
@JohnnyEstilles ah yes, another thing to take into account. Should be trivial to have `unreference` check whether it's an array or a single value and accordingly though. Speaking of which would you prefer "cleanup" instead of "unreference" (since that's how you described it)?

**Comment by JohnnyEstilles** [comment]
@creynders ... I would stick with `unreference` and `remove`, since these clearly denote the two distinct actions to be taken. `cleanup` is rather ambiguous.

**Comment by creynders** [comment]
@ttsirkia on the other hand, maybe we could leave that scenario as a caveat of `onRemoveTarget`. The more I think about it, the more sense it makes IMO to leave it up to the developer to take care of that, i.e. they should use `document#remove` not `model#remove`. It's the same situation with `model#save` none of the type- or field specific validation is run either. Granted, a `list#getUpdateHandler` is provided exactly for those cases. Maybe I should provide a `list#getRemoveHandler` as well...

**Comment by JohnnyEstilles** [comment]
+1 for a `list#getRemoveHandler` ...

**Comment by creynders** [comment]
:grin: this just turned from a should-take-me-a-few-hours-to-fix into a what-am-I-getting-myself-into

**Comment by webteckie** [comment]
@creynders is it possible to summarize the final proposed solution  (perhaps injecting possible use cases)?  I think this will be a great addition!

**Comment by creynders** [comment]
@webteckie what I'm proposing is this:


E.g. we have 

1. a `Usermodel` 
2. a `PostModel` with an `author` relationship field referencing `UserModel` (or an `authors` field with `many:true`)

#### A user is deleted, we want to remove the user's id from `author`

```js
Post.add({
// ...
	author: { 
		type: Types.Relationship, 
		ref: 'User', 
		index: true,
		onRemoveTarget: "unreference"
	}
});
```

#### A user is deleted, we want to remove the post too

```js
Post.add({
// ...
	author: { 
		type: Types.Relationship, 
		ref: 'User', 
		index: true,
		onRemoveTarget: "remove"
	}
});
```

#### A user is deleted, we want to set a `deleted` field to `true`

```js
Post.add({
// ...
	author: { 
		type: Types.Relationship, 
		ref: 'User', 
		index: true,
		onRemoveTarget: function(targetItem){
			this.deleted = true;
			this.save();
		}
	},
	deleted : {
		type: Boolean,
		hidden: true,
		default: false
	}
});
```

I.e. the function would be called with the document as an execution context.
 
I'd let it accept asynchronous functions as well, so you could do some stuff in the DB or so

#### A user is deleted, we want to do something asynchronous

```js
Post.add({
// ...
	author: { 
		type: Types.Relationship, 
		ref: 'User', 
		index: true,
		onRemoveTarget: function(targetItem, callback){
			setTimeout(callback, 1000);
		}
	}
});
```

**Comment by creynders** [comment]
One major hurdle I didn't think about is the whole list dependency thing. I can't just go `require`ing lists inside other lists, so I need to find a way to hook into the keystone application lifecycle at the appropriate time, i.e. _after_ all lists have initialized and _before_ `updates` has run. If anybody has some genius ideas, let me know!

**Comment by ttsirkia** [comment]
If your creating `deleteHandler`, I think you could check the models at that point and perform the required removes. So no need to inject `pre` or `post` handlers to models after they have been created.

However, if you would like to support `document#remove`, then some logic to add new handlers is required.

**Comment by webteckie** [comment]
@creynders thanks for the summary.  Some comments:

- isn't the "unreference" something that should be done, anyways?   If the user being referenced is deleted then doesn't it go without saying that any references to it must be automatically unreferenced?  Unless the intention is to make it explicit so as to preserve the existing behavior?  But to me it seems like a bug if deleted lists are still being referenced.  

- shouldn't the option be called  "onRemoveRef" since it is referring to the list configured in the ref option?

**Comment by JohnnyEstilles** [comment]
@webteckie 

> isn't the "unreference" something that should be done, anyways? If the user being referenced is deleted then doesn't it go without saying that any references to it must be automatically unreferenced?

I think that's one of the points of this request. ATM, references to deleted docs do not get automatically "unreferenced" by Keystone. Many of us take care of this "post delete cleanup" using `post delete` hooks, but the suggestion is that it should be the default behavior. Do you believe it should not be?

> shouldn't the option be called "onRemoveRef" since it is referring to the list configured in the ref option?

This seems like a reasonable request since, as you mention, within Keystone we alwaays refer to relationship targets as the `Ref`.

**Comment by creynders** [comment]
@JohnnyEstilles If I understood @webteckie correctly he _does_ think it should be default behaviour.
I too think it should be default, but that's a breaking change obviously. 

`onRemoveRef` is more in line with the other options, but there's a reason I didn't choose it: to me it sounds as an event handler that runs when a reference is removed from the list using the relationship field, not when a document is removed that the list's field is referencing. Phew, I hope that makes sense?

**Comment by JohnnyEstilles** [comment]
@creynders ... roger! I guess I just misunderstood. :-) And, yes this is definitely a breaking change, but I'm sure it will be welcome to those of us who constantly deal with this issue.

**Comment by webteckie** [comment]
@creynders @JohnnyEstilles yeah I was implying that unreference as described should be a default behavior.   OnRemoveRefTarget? No big deal  ☺

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/relationship-fields-should-be-cleaned-up-when-documents-are-deleted
