### ISSUE TITLE
.less in public can be minified but .js isn't

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1158]
I have a model that store customized less and JS into public folder.

It works great if I stored ***.less*** files; it will minified automatically.

However, the ***.js*** doesn't minified. 

Is there any way to minify it? Otherwise, can I implement it and PR?

**Comment by JedWatson** [comment]
This is because we're using `less-middleware` to process less, which supports minification on the fly. A PR adding similar support for JS public assets would be welcome, but I suspect something like a built-in browserify capability may be more valuable.

**Comment by kadosh1000** [comment]
Maybe should be minified only running on production env. this could get done using grunt or gulp that will run on keystone run

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/minify-admin-interface-js!
