### ISSUE TITLE
can yo keystone upgrade my 0.2.4 to 0.3.2

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1159]
Hi, 

I have an existing ```keystone version 0.2.4```; I have upgraded it to ```0.3.2```

I am not sure if I should upgrade my ```templates, routes and config etc``` with
```
yo keystone
```

***or I have to do it manually?***

**Comment by morenoh149** [comment]
do manually. All you have to do is change the dependency in your `package.json` See also https://github.com/keystonejs/keystone/wiki/0.2.x-to-0.3.x-Changes
