### ISSUE TITLE
Possibly missing OPTIONS method from default CORS settings

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1170]
Just had a quick look at https://github.com/keystonejs/keystone/blob/master/lib/middleware/cors.js#L27
Shouldn't this include OPTIONS by default as well? Or is OPTIONS automatically whitelisted?
I haven't used this middleware yet, since I've relied on my own CORS resolutions so far.

**Comment by liuwei0514** [comment]
+1

**Comment by brettdaman** [comment]
+1
