### ISSUE TITLE
Add new datatype for times

### ISSUE THREAD

**Issue by ttsirkia** [keystonejs/keystone#1171]
It would be useful to have a datatype for times without the date part. Because Javascript does not natively support this, it could be persisted as number of minutes (or seconds) after the midnight.

This allows some queries that are not possible with `DateTime`, for example which stores are still open. It is not meaningful to store the opening and closing times as `DateTime`objects.

**Comment by WingedToaster** [comment]
I need this too, I can take a crack at adding the field type if no one else wants it. 

Is there any particular time picker that the group has in mind? I used this one on the front-end of my site, after I modified it to use english throughout and also a few bug fixes.

http://weareoutman.github.io/clockpicker/

**Comment by mxstbr** [comment]
We don't use a time picker at all, we let people enter the time manually for our `DateTime` field:

<img width="871" alt="screen shot 2016-03-21 at 13 26 27" src="https://cloud.githubusercontent.com/assets/7525670/13909491/9179bf28-ef68-11e5-9a3b-16edec0de80c.png">

While we'd appreciate the help a lot, be aware of the fact that we're currently rewriting all the fields to a new/different format, and not many of them are done, especially not the complexer ones. (e.g. #2454, [full list](https://github.com/keystonejs/keystone/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amxstbr)) I'm not sure right now is a good time to implement a new field, so I'd rather you hold off until we release 0.4. :+1:

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/time-field!
