### ISSUE TITLE
Add a `json` database adapter

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1177]
This will greatly simplify our demo projects and minimum getting started requirements.

The adapter can be "dumb" and just read/write disk on every adapter request. It's not meant for prod.

**Comment by dcousens** [comment]
> It's not meant for prod.

You say that,  but,  knowing life,  please back it with something well tested,  because it will be used...

**Comment by jesstelford** [comment]
Definitely should have tests.

... And probably a `console.warn("You're using the JSON DB adapter. This is not meant for production. You are at risk of losing all your data.")` 👍

**Comment by jesstelford** [comment]
Work has begun! See #1310

**Comment by molomby** [comment]
Dupe of #947? Also relates to #324.

**Comment by jesstelford** [comment]
In-memory, and JSON adapters are distinct. It just so happens I was able to reuse the JSON adapter implementation for the In-memory implementation too 👍
