### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by bahtou** [keystonejs/keystone#118]
How would I go about adding pagination?

I see in the `templates/views/list.js` that their is some pagination going on but it's not implemented in the keystone-demo.

Any suggestions?

**Comment by Ventis** [comment]
@JedWatson I needed this as well, please add this to the documentation.

**Comment by wuhaixing** [comment]
I just created PR #886 for this

**Comment by JedWatson** [comment]
Merged; thanks @wuhaixing.

**Comment by morenoh149** [comment]
@wuhaixing 😎

**Comment by wuhaixing** [comment]
It's my pleasure,thanks for your encourage,@JedWatson @morenoh149

**Comment by Aj2529** [comment]
I am trying to pass results to from .js to .jade file but it says 'users' not defined, my code in .js file is as like below


    var keystone = require('keystone');
    var User = keystone.list('users');
    exports = module.exports = function(req, res) {
	
        var view = new keystone.View(req, res);
        var locals = res.locals;

        User.paginate({
		    page: req.query.page || 1,
		    perPage: 10,
		    maxPages: 10
        }).exec(function(err, results) {
		    locals.data.users = results;
		    //console.log("==---="+JSON.stringify(results));
		    next(err);
        });

	    view.render('members');
	
    };

**Comment by maxkoryukov** [comment]
@JedWatson

>List.paginate() returns a query object, **NOT** just as List.model.find()

I use bluebird's promises, and the `.paginage()` method does not return the correct `promise` object. So the behavior of `paginate` and `find` is very different from this point of view;) Could you make changes in the documentation (untill 0.4 in development)?

*UPD*: as I see, it is well-known bug #576
