### ISSUE TITLE
Replace our custom Cypress `upload_file` function with `cypress-file-upload` plugin

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1180]
Our implementation will [break on Chrome >=73](https://github.com/abramenal/cypress-file-upload/issues/34), and the module is better maintained and tested than our version.

Our implementation is also copy+pasta'd about 3 times throughout the codebase (search for `upload_file`).

https://github.com/abramenal/cypress-file-upload

**Comment by Amrithnath** [comment]
Hey @jesstelford I would like to work on this, let me know if I need to know anything important before I do

**Comment by dhuang612** [comment]
Hi it seems like @Vultraz is working on this?
Wanted to confirm, thanks
