### ISSUE TITLE
No Error Message if file upload failed

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1180]
I tried to upload a file 900Kb, it should be failed due to size (I haven't look into where to set up size limit yet, but it is fine after i convert it into jpg with 200Kb).

It keeps on waiting until time out

![bigmug](https://cloud.githubusercontent.com/assets/7088330/6549004/a80c7fde-c645-11e4-9c52-7a2bf90f902f.png)

![bigmug](https://cloud.githubusercontent.com/assets/7088330/6549003/a8089b30-c645-11e4-9eb7-8eae92390d91.jpg)

**Comment by morenoh149** [comment]
What fieldtype are you using for the upload?

**Comment by arthurtalkgoal** [comment]
Png files, the ones posted in my issues are what i uploaded

**Comment by arthurtalkgoal** [comment]
And successful one is jpg

**Comment by morenoh149** [comment]
Where is your server running? On heroku the local filetype will fail due to the way heroku works

**Comment by arthurtalkgoal** [comment]
Oh, it works in my ubuntu server! 

The server with problems is an old Fedora.  I just moved all my codes to the ubuntu today. 

Thanks @morenoh149
