### ISSUE TITLE
Updated from 0.3.0 to 0.3.0 and got @select-menu-max-height is undefined

### ISSUE THREAD

**Issue by sseppola** [keystonejs/keystone#1182]
Here is the full error message:

  LESS Name error : variable @select-menu-max-height is undefined
  LESS File : /Users/Sindre/projects/wdBlog/node_modules/keystone/node_modules/react-select/less/select-menu.less 21:13
Name Error thrown for request: /keystone/styles/keystone.min.css
{ [Error: variable @select-menu-max-height is undefined]
  type: 'Name',
  filename: '/Users/Sindre/projects/wdBlog/node_modules/keystone/node_modules/react-select/less/select-menu.less',
  index: 732,
  line: 21,
  callLine: NaN,
  callExtract: undefined,
  column: 13,
  extract:
   [ '\tmargin-top: -1px;',
     '\tmax-height: @select-menu-max-height;',
     '\tposition: absolute;' ],
  message: 'variable @select-menu-max-height is undefined',
  stack: undefined }

**Comment by sseppola** [comment]
Either it is not imported with defaults from keystone, or it is a react-select issue. It worked after adding a @select-menu-max-height variable at the top of the select-menu.less file, but the same variable is set in default.less

**Comment by freder** [comment]
I also wasn't sure if it was a keystone or a react-select issue, so I opened [https://github.com/JedWatson/react-select/issues/87](https://github.com/JedWatson/react-select/issues/87).

**Comment by esparragito** [comment]
Have found the root of the problem I think. The @select-menu-max-height which seems to be a new addition to react-select isn't defined in keystones public/styles/react/react/less file. Add it in there and everything should be grand.

The default.less file in the react-select module never gets loaded by keystone, so any variables in there never get seen.

**Comment by porschuetz** [comment]
ah, just opened very similar issue. #1188 

@esparragito thanks. fixed it.

**Comment by porschuetz** [comment]
what height did you set it to? I did 300 and now it is quite interesting.

![screen shot 2015-03-10 at 11 03 45](https://cloud.githubusercontent.com/assets/1228101/6572767/3bfa179a-c715-11e4-957a-a4b652ea2ec0.png)

**Comment by esparragito** [comment]
I'm afraid I'm using less, and I haven't had any problems setting it to that value. Is SASS normally happy without units being defined?

**Comment by JedWatson** [comment]
This shouldn't have anything to do with SASS, as the Admin UI stylesheets are all implemented with LESS...

Fixed by #1183

**Comment by porschuetz** [comment]
oh, sorry, I used units. it is actually working. was getting a little confused with all the parallel test installs I had to figure out the problem.

Will have to remember the issue though =)
