### ISSUE TITLE
Admin UI conflict building in sass & less

### ISSUE THREAD

**Issue by porschuetz** [keystonejs/keystone#1188]
Hello I just repetitively been installing with the yeoman generator.

The problem I run into is possibly due to me trying to use sass instead of less (I remember it was working.

but, not I tried both and well. comes anyhow. variable not set, but that crashes the script? I wonder what that may be.

thanks for your help. I guess I will just quickfix it for now. and see if there is any way I can distribute this later.

GET /keystone/ 200 140.556 ms
  LESS Name error : variable @select-menu-max-height is undefined
  LESS File : /Users/dannydevelop/www/dev3.containerwelt/node_modules/keystone/node_modules/react-select/less/select-menu.less 21:13
Name Error thrown for request: /keystone/styles/keystone.min.css
{ [Error: variable @select-menu-max-height is undefined]
  type: 'Name',
  filename: '/Users/dannydevelop/www/dev3.containerwelt/node_modules/keystone/node_modules/react-select/less/select-menu.less',
  index: 732,
  line: 21,
  callLine: NaN,
  callExtract: undefined,
  column: 13,
  extract: 
   [ '\tmargin-top: -1px;',
     '\tmax-height: @select-menu-max-height;',
     '\tposition: absolute;' ],
  message: 'variable @select-menu-max-height is undefined',
  stack: undefined }

![screen shot 2015-03-10 at 10 18 04](https://cloud.githubusercontent.com/assets/1228101/6572039/19f36c92-c70f-11e4-9057-7724bffc07e4.png)

**Comment by porschuetz** [comment]
Update: 

I generated with less and here is the new error message. 

can't find files? but I am not sure why, because they are there.

---
LESS File error : '../../../node_modules/react-select/less/select.less' wasn't found. Tried - /Users/dannydevelop/www/beta.containerwelt.info/node_modules/keystone/node_modules/react-select/less/select.less,../../../node_modules/react-select/less/select.less
  LESS File : /Users/dannydevelop/www/beta.containerwelt.info/node_modules/keystone/public/styles/react/react.less 35:0
File Error thrown for request: /keystone/styles/keystone.min.css
{ [Error: '../../../node_modules/react-select/less/select.less' wasn't found. Tried - /Users/dannydevelop/www/beta.containerwelt.info/node_modules/keystone/node_modules/react-select/less/select.less,../../../node_modules/react-select/less/select.less]
  type: 'File',
  filename: '/Users/dannydevelop/www/beta.containerwelt.info/node_modules/keystone/public/styles/react/react.less',
  index: 1377,
  line: 35,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract: 
   [ '',
     '@import "../../../node_modules/react-select/less/select.less";',
     '@import "../../../fields/types/markdown/less/bootstrap-markdown.less";' ],
  message: '\'../../../node_modules/react-select/less/select.less\' wasn\'t found. Tried - /Users/dannydevelop/www/beta.containerwelt.info/node_modules/keystone/node_modules/react-select/less/select.less,../../../node_modules/react-select/less/select.less',
  stack: undefined }
![screen shot 2015-03-10 at 10 34 27](https://cloud.githubusercontent.com/assets/1228101/6572264/11ba917a-c711-11e4-87dc-c5e223dd20e7.png)
keystone

**Comment by dennybritz** [comment]
Seems to be a problem with the latest version of [react-select](https://github.com/JedWatson/react-select/). I downgraded from 0.3.5 to 0.3.4 and now things are working again.

**Comment by JedWatson** [comment]
Apologies for this. Fixed w/ #1183
