### ISSUE TITLE
Support server side hot module replacement

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1188]
For example, to reload the Apollo Server: https://twitter.com/zachcodes/status/1129600383200813059?s=20

Once #1109 is merged, adding this to the default custom server would be a nice place for it.

**Comment by MadeByMike** [comment]
@jesstelford do you still want to add this to the default server?

**Comment by jesstelford** [comment]
Yes!

This could be one approach: https://twitter.com/dan_abramov/status/1192898770842931209?s=20
