### ISSUE TITLE
Make GraphQL Playground link more obvious in AdminUI

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1190]
Since we only display the GraphQL Playground in dev mode, and it's a highly useful feature of the admin UI, we should surface it in a more obvious place for app developers to find.

Mockup:

![Screen Shot 2019-05-20 at 11 11 02 am](https://user-images.githubusercontent.com/612020/57991111-066c2080-7af0-11e9-9b98-e067c2a91f84.png)

**Comment by jossmac** [comment]
Perhaps we just have a big button fixed to the bottom of the sidebar "Developer Resources", which takes users to a dedicated page detailing what's available and that it is strictly visible in development.

**Comment by jesstelford** [comment]
I'd prefer to avoid the extra click. The links go away in prod mode anyway, so it'll only be devs who see them (unless they're deploying in dev mode, but then they've got other issues :P )

**Comment by MadeByMike** [comment]
I politely disagree here :) Getting to the graphQL playground is something we are interested in and we know where it is. But I think we should be designing for people how use the admin interface to manage real world applications.

I'd like to get a UX design opinion as well.

**Comment by jesstelford** [comment]
Would love some UX help!

Keep in mind my comment above too;

> The links go away in prod mode anyway, so it'll only be devs who see them
