### ISSUE TITLE
CodeMirror:  syntax highlighting does not work with jade mode/lang

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1192]
As mentioned in #1161 syntax highlighting does not work when using the jade mode/language.

**Comment by webteckie** [comment]
@JedWatson: I figured out this one out.  Basically the issue is that keystone is not pulling in required files (e.g., jade.js and maybe other's per the codemirror jade example).  So the following is how I got it to work just for jade but I'm afraid we may have to solve this for any language:  

NOTE:  For this test I copied the node_modules\codemirror directory to public\lib replacing the existing codemirror directory with codemirror-compressed.js in it since the extra included files below refer to just codemirror...we may need play games here and require the directory instead, which probably means we would need to replace codemirror\codemirror-compressed.js with codemirror\index.js, unless there's a better way.

```
templates\layout\base.jade:

replace:
		script(src="/keystone/js/lib/codemirror/lib/codemirror.js")
with:
		block codemirror_js
 
templates\views\item.jade:

add:
block codemirror_js
	if list.fieldTypes.code
		script(src="/keystone/js/lib/codemirror/lib/codemirror.js")
		script(src="/keystone/js/lib/codemirror/mode/css/css.js")
		script(src="/keystone/js/lib/codemirror/mode/xml/xml.js")
		script(src="/keystone/js/lib/codemirror/mode/javascript/javascript.js")
		script(src="/keystone/js/lib/codemirror/mode/htmlmixed/htmlmixed.js")
		script(src="/keystone/js/lib/codemirror/mode/jade/jade.js")
```

Thus, right away you can see an advantage in that codemirror.js does not have to be included unless a code field is defined perhaps saving some cycles in initial page load.  However, the dilemma now, as I see it, is trying to match the set of script files included to the configured mode/language in the model.  I guess a possible solution, assuming that we can check the configured options in item.jade is to:

1. create another jade file (e.g., code.jade) that configures the scripts to included based on the configured language option
2. include this new file in item.jade

Looking for guidance here!

**Comment by webteckie** [comment]
Never mind, got it working by rebuilding codemirror-compressed.js with the config and options I need!  And I think I will take the approach of overriding codemirror-compressed.js since there's so many different permutations of configurations any particular developer/app may want.  However, I did test introducing a "block js_codemirror" in layout and filling that from item.jade so that codemirror is not included in every single page thus speeding up page load.  Let me know if you want a PR for that.

**Comment by JedWatson** [comment]
@webteckie you've given me an idea, I may be able to make this work elegantly. Reopening while I investigate.

**Comment by webteckie** [comment]
@JedWatson sure let me know when you have something for me to try.

**Comment by webteckie** [comment]
@JedWatson will the "elegant" solution be introduced in the 0.3.x line?

**Comment by webteckie** [comment]
@JedWatson since there's so many combinations of CodeMirror features a developer may want for now the simplest solution here is for the developer to build their own codemirror-compressed.js and to override the one at admin\public\js\lib\codemirror.  To build a custom codemirror-compressed.js either the command line (didn't work for me) or the online compresser at http://codemirror.net/doc/compress.html.  I've also just submitted a change (https://github.com/webteckie/keystone/commit/3bc37c53ef40adc02d4512c05d7c282bdf5825f4) to only load CodeMirror in the item form page.

**Comment by webteckie** [comment]
@JedWatson is your `I may be able to make this work elegantly` above still applicable here?

**Comment by JedWatson** [comment]
Oh... I don't even remember what I had in mind... sorry!

This whole thing has changed, I'm hoping you'll be able to easily wrap the `Code` React component with your own Codemirror config when 0.4 is launched. Then all the plugins you want will be included in the browserify build and it should "just work".

**Comment by webteckie** [comment]
Ok, I will close this for now and reference #1979 in case we need to handle any enhancements for this.
