### ISSUE TITLE
UpdateHandler refactoring

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1194]
Related to #1150 since we need to clean up `updateHandler` first before we can even try and get rid of the other switch-cases.

So, I've delved into the mysteries of the `UpdateHandler` and so far, AFAICT, its life-cycle is as follows:

It iterates over all fields and does inline type-specific validation for some field types.
Next, it calls the `validateInput` method of the field.
And lastly it calls field-specific validation, as declared in the models.
All of this sprinkled with conditionals in case the field value is already invalid.

However, there's a number of problems:

1. the inline type-specific validation _seems_ superfluous since field types already have a `validateInput` method, but I need to check whether the current correct functioning of item validation isn't an ephemeral side-effect of the inline validation and `validateInput` combined.
1. `validateInput` is called twice for each field that has a changed (valid) value. This definitely needs to go.
1. `UpdateHandler` is monolithic and could _definitely_ use some refactoring
	1. its constructor signature is messy and leaks responsibilities all over the place, for instance: `req` is a required argument, but the only use of `req` is for its `flash` method to warn the user of errors.
	1. `res` is even worse, it's a required argument, but isn't used. At all.
	1. `UpdateHandler#process` is huge and messy

So what I'll be aiming for is:

1. drop the dependency on `req`
1. drop the dependency on `res`
1. consolidate the inline error handling into a separate hook/whatever
1. drop inline validators and only use the type specific validators as declare by the types
1. tests, duh!

These are breaking changes, no doubt, but well worth the effort and even easily patchable if backwards-compatibility is mandatory.

@jedwatson let me know what you think.

I'll turn this into a PR the moment i've got some non-explosive code.

**Comment by creynders** [comment]
I wanted to add the following, I think it's best we leave the error handling up to the `UpdateHandler` client (with a default handler obviously). For instance in REST API's the whole `flash` business is unnecessary, yet it's definitely beneficial to use `UpdateHandler` instead of saving directly through the model, to benefit from custom and type-specific validation. Unless we could hook the validation straight into mongoose `model#save`, but I assume that's not possible.

**Comment by JedWatson** [comment]
I've found mongoose validation doesn't provide the level of control I want, and yes - everything (including REST APIs) should go through the UpdateHandler. You've basically nailed the spec on this task from what I can tell.

**Comment by creynders** [comment]
Yeah, that's what I thought (re: mongoose validation) good to know it confirmed, so I don't spend time spiking stuff that's bound to fail.

**Comment by creynders** [comment]
Been scouring through all the field types' `validateInput`s, these are the ones that do any "real" validation:

* LocationType
* MarkdownType
* MoneyType
* NameType
* NumberArrayType
* NumberType
* PasswordType
* RelationshipType
* SelectType
* TextArrayType

The others simply return `true`.

Looking at the validation code a little closer it seems to me, they could all be split in two functions:
1. checking if a value is present for when the field is `required`
1. _really_ validating a value

Probably I'll need to split these. :snowman:

**Comment by creynders** [comment]
Then, on to the `UpdateHandler#process` inline validation. Turns out it's more of a pre-validation validation. It uses `field.getRequestHandler`, which e.g. will upload a file (LocalFileType) and here `req` _is_ used, e.g. `req.files[paths.upload]`. 
Thus. 
I can't get rid of `req` _that_ easily. :panda_face: 

Included are:

* AzureFileType
* CloudinaryImageType
* CloudinaryImagesType
* LocalFileType
* LocalFilesType
* LocationType
* PasswordType
* S3FileType

It seems PasswordType is the only one which has _some_ overlapping validation, but I strongly suspect some quantum entanglement there. Basically there's a bunch of situations to be checked:

1. _inline_ if `password` is empty and not required: bail
1. _inline_ if `password` and `password_confirm` are not equal: :bomb:
1. _validateInput_ if `password` and `password_confirm` are not equal: :bomb:
1. _validateInput_ if `password` has a value: :rainbow:
1. _validateInput_ if `password` has no value and is `required`: :umbrella:

Yep, that's some spooky action on a distance, as Albert E. (may his brains float in peace) might say.

**Comment by creynders** [comment]
Full tracing output for a valid form submission:

```
GET /keystone/users/55013ef0c6c0d7da7b260fc0 200 536.937 ms
UpdateHandler#process
UpdateHandler#process field: name
UpdateHandler#process inline validation: name
UpdateHandler#process field.validateInput(): name
UpdateHandler#process field.updateItem() name
UpdateHandler#process field: email
UpdateHandler#process inline validation: email
UpdateHandler#process field.validateInput(): email
UpdateHandler#process field.updateItem() email
UpdateHandler#process field: brand
UpdateHandler#process inline validation: brand
UpdateHandler#process field.validateInput(): brand
UpdateHandler#process field.updateItem() brand
UpdateHandler#process field: avatar
UpdateHandler#process inline validation: avatar
UpdateHandler#process field.validateInput(): avatar
UpdateHandler#process field.updateItem() avatar
UpdateHandler#process field: password
UpdateHandler#process inline validation: password
UpdateHandler#process field: isAdmin
UpdateHandler#process inline validation: isAdmin
UpdateHandler#process field.validateInput(): isAdmin
UpdateHandler#process field.updateItem() isAdmin
UpdateHandler#progress
UpdateHandler#progress remove request handler: avatar
UpdateHandler#process getRequestHandler callback avatar
UpdateHandler#progress
UpdateHandler#progress remove request handler: brand
UpdateHandler#process getRequestHandler callback brand
UpdateHandler#progress
UpdateHandler#saveItem
UpdateHandler#saveItem callback
POST /keystone/users/55013ef0c6c0d7da7b260fc0 302 100.785 ms
GET /keystone/users/55013ef0c6c0d7da7b260fc0 200 229.735 ms
```

**Comment by creynders** [comment]
Full tracing output for an invalid form submission:
```
GET /keystone/users/55013ef0c6c0d7da7b260fc0 200 392.525 ms
UpdateHandler#process
UpdateHandler#process field: name
UpdateHandler#process inline validation: name
UpdateHandler#process field.validateInput(): name
UpdateHandler#process field.updateItem() name
UpdateHandler#process field: email
UpdateHandler#process inline validation: email
UpdateHandler#process field.validateInput(): email
UpdateHandler#process field.updateItem() email
UpdateHandler#process field: brand
UpdateHandler#process inline validation: brand
UpdateHandler#process field.validateInput(): brand
UpdateHandler#process field.updateItem() brand
UpdateHandler#process field: avatar
UpdateHandler#process inline validation: avatar
UpdateHandler#process field.validateInput(): avatar
UpdateHandler#process field.updateItem() avatar
UpdateHandler#process field: password
UpdateHandler#process inline validation: password
UpdateHandler#process field.validateInput(): password
UpdateHandler#process field.updateItem() password
UpdateHandler#process field: isAdmin
UpdateHandler#process inline validation: isAdmin
UpdateHandler#process field.validateInput(): isAdmin
UpdateHandler#process field.updateItem() isAdmin
UpdateHandler#progress
POST /keystone/users/55013ef0c6c0d7da7b260fc0 200 276.262 ms
```

**Comment by creynders** [comment]
AFAICT `getUpdateHandler` is only ever used with `req` and no other arguments
https://github.com/keystonejs/keystone/search?utf8=%E2%9C%93&q=getUpdateHandler

`UpdateHandler#process` however is passed either `req.body` or `req.query` as `data`. inside `process` it passes `this.req` (received in the ctor arg) to `Field#getRequestHandler`

**Comment by creynders** [comment]
So, basically UpdateHandler is used for one specific reason: to allow field- and type-specific validation occur. However, it doesn't really solve the problem of people wanting to benefit from mongoose `model#save` instead of `document#save` since it's a schema method, i.e. you already need the document before you can use `getUpdateHandler`.

Conclusion: I think it would be a good idea to have some sort of `List#getUpdateHandler` (or maybe use another name) which allows you to retrieve an update handler for a specific id. This has to be async, and therefore it probably _should_ be named differently.
It also allows to add the same kind of convenience method for removeHandler, see #1203 and maintain consistency.

**Comment by creynders** [comment]
Also, let's not forget, there's already some kind of convenience method called `List#updateAll`which does _not_ use `getUpdateHandler`, though for consistency it should. This is probably due to allow for calling `updateAll` in non-middleware functions. Its only call site in keystone is in [/routes/views/list](https://github.com/keystonejs/keystone/blob/master/routes/views/list.js#L160) which however _is_ a middleware function.

**Comment by creynders** [comment]
`updateHandler` will be dropped entirely.
