### ISSUE TITLE
Cloudinary - Image Upload Failed

### ISSUE THREAD

**Issue by caseymorrisus** [keystonejs/keystone#1198]
This seemed to work the past few days, but I can't get an image to upload anymore using Cloudinary. Get this error: 
```bash
Image upload failed - Invalid Signature bdcbf09d52758c39cb147e4e940457e8dfa11e95. String to sign - 'tags=posts_image,posts_image_550095bb0e63f11f171bdd89,dev&timestamp=1426101730'.
```

**Comment by justin14** [comment]
I'm having this same issue.

**Comment by justin14** [comment]
https://gist.github.com/justin14/6573961fec906b87af9f

**Comment by justin14** [comment]
Well, just FYI, for mine I had copied only part of the API Secret.  A bonehead move, but hope it helps someone else.
