### ISSUE TITLE
New field type: multiselect

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#12]
Similar to the select field, but allows the selection of multiple values (stores values as an array of Numbers or Strings).

UI configurable as either a list / grid of checkboxes, or a tags-style list (similar to *many* relationships).

**Comment by mazki516** [comment]
Hey guys !

Any news on this field ? sounds like the dream field to work along with the storage api .

**Comment by raoabishay** [comment]
This is a very essential feature. Would be waiting for this one!

**Comment by zivchen** [comment]
+1

**Comment by ajarbol** [comment]
+1

**Comment by kadosh1000** [comment]
Hi I have published my npm package: 
https://github.com/kadosh1000/keystone-custom-fieldtypes

It allows you to create custom field types, and copy your custom fieldTypes from a selected dir into the keystone's fields dir and registers it.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://github.com/keystonejs/keystone/issues/12

**Comment by r3wt** [comment]
essential features > roadmap

**Comment by jorisw** [comment]
I have found the following workaround that doesn't involve putting the desired values in a List linked via Relationship.

I just set a particular field as a nested plain object with Boolean fields in there. Functionality wise, this achieves what a multi select with predefined options would.

```

myList.add({
	"hobbies":
		{
			"travel": 				{type: Types.Boolean},
			"music": 				{type: Types.Boolean},
			"gardening": 			{type: Types.Boolean},
			"collecting": 			{type: Types.Boolean},
			"sports": 				{type: Types.Boolean},
			"reading": 			{type: Types.Boolean},
			"volunteering": 		{type: Types.Boolean},
			"cooking": 			{type: Types.Boolean},
			"culture": 				{type: Types.Boolean},
			"friends-family": 		{type: Types.Boolean}
		},
});
```

These options will show up in the Admin UI after creating a list entry, and the Admin UI as well as the REST API will correctly translate them to Mongoose.

**Comment by r3wt** [comment]
Thanks @jorisw for your helpful workaround.

**Comment by phoniks** [comment]
Truth be told, this workaround had an unexpected advantage over a normal multi-select list because I can actually set different input types for each item in the list.  Not sure how I'll make it work in the UI, but for my purposes, I think the lack of that functionality led to a happy ending.

**Comment by MillerApps** [comment]
This likely a stupid question but for the workaround how would I be able to use this within a form (event registration)? I haven’t been able to get it working. Thanks In adavnce!

**Comment by askdesigners** [comment]
This is actually really shitty!

**Comment by internetErik** [comment]
@MillerApps Maybe this is something you're looking for?

Regarding the workaround from @jorisw, and regarding connecting this to some front-end form, the following may be helpful.

Assuming you have a model MyList with the code from @jorisw 

```JavaScript
// this is probably in /routes/views
keystone.list('MyList')
      .model
      .findOne({})
      .exec((err, result) => {
        locals.hobbies = Object.keys(result).map(key => ({name: result[key], value:  result[key]}))
        next();// or view.render('something')
      });
```

Assuming .hbs (since this is what I do)
```
<form>
{{#each hobbies}}
  <input type="checkbox" name="{{ name }}" {{#if value}}checked{{/if}} />
{{/each}}
</form>
```

**Comment by askdesigners** [comment]
I ended up storing it as a text array as I'm mostly working with it via an API. Not very user friendly I must say.

**Comment by agmt5989** [comment]
The [documentation](https://keystonejs.netlify.com/api/field/select/) for the Select field type states:
> If you want to provide multiple values, you can use TextArray or NumberArray, although neither will have the same constrained input. You can limit the options using a pre-save hook.
Does anyone know exactly how to implement this pre-save constraint hook? I'm trying not to follow relationships for my current use-case
