### ISSUE TITLE
Need Docs: "cloudinary folders" requires "Auto-create folders" enabled in Cloudinary

### ISSUE THREAD

**Issue by danielkhan** [keystonejs/keystone#1200]
"Auto-create folders" must be enabled in Cloudinary for the 'cloudinary folders' option to work.
I think this is missing in the docs.

**Comment by morenoh149** [comment]
Please add this :)

**Comment by JohnnyEstilles** [comment]
EN docs added via #1201

**Comment by weekwood** [comment]
ZH  docs added via #1219
