### ISSUE TITLE
Add `removeHandler`

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1203]
Since we'll be doing some automated deleting, we'll have to provide a convenience method for deleting items that triggers `pre` and `post` remove hooks. :sweat: 
Seems logical to make it symmetrical to `updateHandler`, i.e. a `List#getRemoveHandler` which returns a `RemoveHandler` instance which runs on `RemoveHandler#process`

See #1152 for more info.

**Comment by creynders** [comment]
`getUpdateHandler` has 3 call sites:

1. [/routes/views/item](https://github.com/keystonejs/keystone/blob/7f07ad7d8a994d495a877b6d2a9d6ef4f2f402b7/routes/views/item.js#L175)
1. [/routes/views/list](https://github.com/keystonejs/keystone/blob/7f07ad7d8a994d495a877b6d2a9d6ef4f2f402b7/routes/views/list.js#L222)
1. [/routes/api/list](https://github.com/keystonejs/keystone/blob/3e9c15b3e1d6b0bad29b2bac6c826527853e890d/routes/api/list.js#L135)

Chances are we need to replace whatever deletion logic happens in these files with a `removeHandler`

**Comment by creynders** [comment]
Definitely at:

1. [/routes/views/list](https://github.com/keystonejs/keystone/blob/master/routes/views/list.js#L184)
1. [/routes/api/list](https://github.com/keystonejs/keystone/blob/master/routes/api/list.js#L183)

**Comment by creynders** [comment]
So, if we keep it consistent with updatehandler, the most common use case will look like this:
```js
item.getRemoveHandler().process();
```

which seems overly verbose and is in fact totally useless, it's far easier to use `item.remove()`

**Comment by creynders** [comment]
@JohnnyEstilles what's your take on the following?

A breakdown of the problem: a mongoose `document#remove` already calls `pre` and `post` 'remove' handlers, i.e. that's no reason to add a `removeHandler` symmetrical to `updateHandler`. So, AFAICT the only reason to have a `removeHandler` is to allow a convenience method on the list, something like:

```js
var Post = keystone.list("Post");
list.getRemoveHandler( "54fd7bf2433d93386cf0eb53" ).process(function(err, item){
  console.log("removed:", item.id);
});
```

And to promote this instead of letting people use the mongoose `model#remove` directly.

**Comment by JohnnyEstilles** [comment]
> And to promote this instead of letting people use the mongoose `model#remove` directly.

I think this is a good reason (though not a great one) to create a `RemoveHandler`. Just like `UpdateHandler` should be the standard way to create/update items in Keystone (assuming we want to take advantage of the validation and other features it includes), `RemoveHandler` should also become the default way to delete Keystone items (assuming we want to take advantage of the post delete cleanup features you intend to include).

Use cases that don't require the additional bells and whistles provided by `UpdateHandler` and `RemoveHandler` can certainly use `document#save` and `document#remove` respectively. Likewise, use cases that don't require `pre` and `post` hooks can use `model#save` and `model#remove`. I just think it would be a matter of documenting them well and letting Keystone consumers choose.

This feels to me like a reasonable addition, but I'm just one vote. :-)

**Comment by creynders** [comment]
I don't think this really makes sense anymore
