### ISSUE TITLE
How to turn off tinymce clean up ?

### ISSUE THREAD

**Issue by Yinear** [keystonejs/keystone#1207]
I wrote this in the html editor
```html
<a href="javascript:runscript(jade_variable)">something</a>
```
After update tinymce to 4.x, the href always be ate.
So I tried to set 'wysiwyg additional options': { cleanup: false } in keystone config, but it doesn't work.
How should I stop tinymce cleanup?

**Comment by drlogout** [comment]
Add "allow_script_urls: true" to 'wysiwyg additional options' in the object your passing to keystone.init():

```
'wysiwyg additional options': {
	allow_script_urls: true
}
```

**Comment by Yinear** [comment]
Thank you!
