### ISSUE TITLE
Notification errors in production

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1208]
Is there any way or npm to turn on exception notifications in production, like rails' exception_notifications gem

https://github.com/smartinez87/exception_notification

**Comment by JohnnyEstilles** [comment]
@arthurtalkgoal, this is not really a Keystone related issue, so I'm going to close this issue.

However, here ([https://github.com/saschagehlich/node-exception-notifier](https://github.com/saschagehlich/node-exception-notifier)) is a node implementation might want to check. I'm sure you can adapt it to your own needs.
