### ISSUE TITLE
Feature: Add Field Min/Max/Limits

### ISSUE THREAD

**Issue by typ90** [keystonejs/keystone#1209]
There should be a way to limit the number of characters, relationships, etc. on various fields/field types. I've gone through the documentation and source and so far don't see anything to do this directly. 

I'm sure I can implement client side validation, but there's nothing built in. There should be a way to do this. *If there is please let me know.*

**Comment by morenoh149** [comment]
There's client side validation libraries - https://github.com/formvalidation/formvalidation comes to mind. And there are standard mongoosejs validations http://mongoosejs.com/docs/validation.html min, max are among those.

**Comment by typ90** [comment]
Yeah sorry for the lack of clarification. I meant this more as an explicit feature for Keystone. I know I can add client side validation libraries, but in general I'm having trouble customizing small things like this on the admin side of my keystone install. Thanks for the response anyway :)

**Comment by morenoh149** [comment]
ah validation of adminUI fields? I achieve that through a mongoose pre save hook http://mongoosejs.com/docs/middleware.html

**Comment by typ90** [comment]
1. Awesome, thank you.
2. The reason I was having so much trouble is because I didn't realize I had to manually run the Gulp rebuild for keystone when I made changes to it......now that I've figured that one out I should be able to make some progress haha.

Thanks again!
