### ISSUE TITLE
Need docs: S3 File headers

### ISSUE THREAD

**Issue by montmanu** [keystonejs/keystone#1211]
Need translations of the documentation for S3 File `headers` option and `default headers` value of `s3 config` introduced by #1167

**Comment by weekwood** [comment]
Pick Link from EN docs

https://github.com/montmanu/keystone/blob/29fb14c971837bb8e40d6704fe8e0b67b271412e/docs/content/en/pages/docs/configuration.jade#L512-523

https://github.com/montmanu/keystone/blob/29fb14c971837bb8e40d6704fe8e0b67b271412e/docs/content/en/pages/docs/database.jade#L1175-1214

**Comment by weekwood** [comment]
add ZH via #1230

**Comment by JedWatson** [comment]
Thanks @weekwood!
