### ISSUE TITLE
Better options for using UpdateHandler manually

### ISSUE THREAD

**Issue by ttsirkia** [keystonejs/keystone#1216]
`UpdateHandler`makes very nice job for updating items in the database by taking new data directly from `req.body`.

However, there are cases when only some fields should be updated. For example, user (and I mean end user, not admin) cannot never change his/her admin status or something like this. It is possible to set `noedit` (btw. inconsistent casing here) to `true` but then the value cannot be anymore updated from Admin UI.

I would like to suggest two improvements:
* create two field options: one for Admin UI and another for other updates via `UpdateHandler`
* add a new option to `UpdateHandler` for blacklisting certain fields

Of course it is easy to set the fields that should be updated but if the model contains 20 fields and only two of them should be ignored, blacklisting is easier than whitelisting.

Any ideas, comments or suggestions?

**Comment by ttsirkia** [comment]
Any objections if I add new option `exclude` to UpdateHandler's options? It partially solves this issue.

**Comment by mxstbr** [comment]
The updateHandler will be completely replaced with the 0.4 update to using an API for communication with the admin interface. I'll close this issue, thanks for chiming in though!
