### ISSUE TITLE
Editor Icons

### ISSUE THREAD

**Issue by bahtou** [keystonejs/keystone#122]
In the`ui- wysiwyg.js` I add the `media` button icon in the plugin and the toolbar.

`jQuery(function($) {
	
	if (!window.tinymce)
		return;
	
	tinymce.init({
		selector: 'textarea.wysiwyg',
		menubar: false,
		plugins: [ 'code', 'link', 'image', 'media' ],
		theme_advanced_buttons1_add: 'media',
		toolbar: 'bold italic | alignleft aligncenter alignright | bullist numlist | outdent indent | link | image | media',
		skin: 'keystone'
	});
	
});`

But the `media` button icon does not show up.  Where can I go and add the icon?

**Comment by jeffreypriebe** [comment]
See more recent Issue #1518

**Comment by JedWatson** [comment]
Closed in favour of #1518 (which is also closed :)
