### ISSUE TITLE
Errors thrown from hooks are not caught

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1220]
For example, on a Field Type:

```javascript
class Foo extends File {
  async validateInput() {
    throw new Error('hi');
  }
}
```

### Expected behaviour

Fail the mutation and show the thrown error in the `errors` array

### Actual behaviour

Causes the server to hang when creating a new item.

**Comment by Vultraz** [comment]
Tested with this:
```js
    validateInput: () => {
      console.log("HOOK TEST");
      throw new Error('Y U DO DIS');
    }
```
The error *does* show up as a GraphQL Error popup in the admin UI, but not the console. So, this is fixed, I guess?
