### ISSUE TITLE
ReferenceError: signinWithUser is not defined

### ISSUE THREAD

**Issue by montmanu** [keystonejs/keystone#1224]
Looks like `doSignIn` used to be [defined](https://github.com/keystonejs/keystone/commit/541c7cd776cfe2cd12460a585f161d3796a5d8a9#diff-0a6235c4445253f49367a39ab5ff3b7cL37) within the scope of `exports.signin`, but after the recent refactor, `signinWithUser` is a named function expression assigned to `exports.signinWithUser` and is not in scope when [called from within `exports.signin`](https://github.com/keystonejs/keystone/commit/67c02bb18a4214da51e56172c284fc8072ba4f90#diff-0a6235c4445253f49367a39ab5ff3b7cL86).

Could probably be resolved by explicitly invoking `exports.signinWithUser` [similar to how `exports.signin` is invoked from within `exports.persist`](https://github.com/keystonejs/keystone/blob/67c02bb18a4214da51e56172c284fc8072ba4f90/lib/session.js#L149)

**Comment by JohnnyEstilles** [comment]
Fixed via #1225
