### ISSUE TITLE
beforeChange hook on custom field implementation has incorrect docs

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#1227]
The beforeChange hook on a custom field implementation provides an "actions" object argument. This object is missing the getList function.

docs:
https://v5.keystonejs.com/api/hooks#resolve-input-arg-list

**Comment by jesstelford** [comment]
This is a documentation issue, there is a parameter called `actions` which has a key `query` that allows you to perform the same actions as outlined in the docs:

```javascript
keystone.createList('User', {
  fields: { ... },
  hooks: {
    beforeChange: async ({
      resolvedData,
      existingItem,
      context,
      originalInput,
      actions,
    }) => {
      const { data: { count } } = actions.query(`query { _allUsersMeta { count } }`);
    }
  }
});
```

**Comment by molomby** [comment]
Dupe of #591? Worth a bump though..

> There is no .getList method exposed.
What is the preferred method of accessing other lists from within a hook? This needs to be resolve at runtime to "breaks" circular dependancies, so something like `.getList()` probably is needed.

**Comment by MadeByMike** [comment]
#591 is resolved but we need to document the callback params for hooks

**Comment by gautamsi** [comment]
@jesstelford seems `actions` is renamed to `list`, see the latest hooks doc.
