### ISSUE TITLE
Startup takes a while

### ISSUE THREAD

**Issue by foobar8675** [keystonejs/keystone#1227]
When I start keystone locally, it always takes a 10 or so seconds to start up. I was wondering if that is as expected or if it is something specific to my environment.

**Comment by ttsirkia** [comment]
In my environment, it takes about two seconds to start Keystone.

**Comment by captainchung** [comment]
thanks for responding and 2 seconds sounds great. i ran spy-node and all it is telling me is the script:keystone took about 3.4 seconds - while there is definitely something else going on. you don't have any thoughts on figuring out where else the issue might be, do you?

**Comment by ttsirkia** [comment]
Sorry, no clear ideas. Are you running Keystone with grunt-watch or similar tools which restart the process when a file changes? Could there be some library that has a long-running initialization process?

**Comment by captainchung** [comment]
Hmm. thanks. I'm just doing /usr/local/bin/node --debug-brk=59506 --nolazy
keystone.js , no grunt. This is kind of odd.

On Wed, Mar 18, 2015 at 11:19 AM, Teemu Sirkiä <notifications@github.com>
wrote:

> Sorry, no clear ideas. Are you running Keystone with grunt-watch or
> similar tools which restart the process when a file changes? Could there be
> some library that has a long-running initialization process?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/1227#issuecomment-83108707>
> .
>



-- 
Regards,
Matt

**Comment by creynders** [comment]
@captainchung Have you tried `DEBUG=* /usr/local/bin/node --debug-brk=59506 --nolazy keystone.js`?
It shows you a lot of debugging output, maybe it'll give you an idea of what process stalls/fails.

**Comment by captainchung** [comment]
That is a great suggestion. Seems to only happen when I have a debugger
attached - which should help me narrow the issue. If you have other
thoughts please send, but otherwise, thanks a lot!

On Thu, Mar 19, 2015 at 3:34 AM, creynders <notifications@github.com> wrote:

> @captainchung <https://github.com/captainchung> Have you tried DEBUG=*
> /usr/local/bin/node --debug-brk=59506 --nolazy keystone.js?
> It shows you a lot of debugging output, maybe it'll give you an idea of
> what process stalls/fails.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/1227#issuecomment-83496815>
> .
>



-- 
Regards,
Matt

**Comment by ttsirkia** [comment]
The debugging interface will slow down the process. You might want to send [SIGUSR1](https://www.npmjs.com/package/node-inspector#advanced-use) to your Node process when you want to start debugging instead of using ``--debug`` option.

**Comment by captainchung** [comment]
I'll try that. Thanks Teemu!

On Thu, Mar 19, 2015 at 8:19 AM, Teemu Sirkiä <notifications@github.com>
wrote:

> The debugging interface will slow down the process. You might want to send
> SIGUSR1 <https://www.npmjs.com/package/node-inspector#advanced-use> to
> your Node process when you want to start debugging instead of using
> --debug option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/1227#issuecomment-83624624>
> .
>



-- 
Regards,
Matt
