### ISSUE TITLE
autokey results in MongoError: E11000 duplicate key

### ISSUE THREAD

**Issue by GlennGeenen** [keystonejs/keystone#1228]
So I add an autokey to my list but I don't want it to be unique. Either not including unique or using unique:false results in the same Mongo error.

Keystone 0.3.4
MongoDB 3.0.1

Setup:

```javascript
var Team = new keystone.List('Team', {
  map: {
    name: 'title'
  },
  autokey: {
    path: 'slug',
    from: 'title'
  }
});

Team.add({
  title: {
    type: String,
    required: true
  }
});

```

Create Team

```javascript
var newTeam = new Team.model({
  title: 'test'
});

newTeam.save(function (err) {
  if (err) {
    console.log(JSON.stringify(err));
  } 
});
```

Error on creating a team with existing title:

```javascript
{
"name":"MongoError",
"code":11000,
"err":"E11000 duplicate key error index: db.teams.$slug_1 dup key: { : \"test\" }"
}

```

**Comment by ttsirkia** [comment]
Could it be possible that there is a unique index already in the database which is created earlier? Have you tried to [drop indexes](http://docs.mongodb.org/manual/reference/method/db.collection.dropIndex/)?

**Comment by medv** [comment]
Get this once in a while after editing my models with existing documents. Dropping collection fixes it. Hopefully this is the same issue here.

**Comment by GlennGeenen** [comment]
Thanks, dropping the indexes fixed it.
