### ISSUE TITLE
View all Uploaded files

### ISSUE THREAD

**Issue by santi6291** [keystonejs/keystone#1231]
Keystone docent have a section to view all uploaded media, I believe having a section to preview all media that was uploaded and a field type that can easy allow to select files to attach to a model item would help greatly, 
I'm sure this can be done by creating a model to upload files to but when referencing that in another model you would only get the file names no file preview.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/view-all-uploaded-files!
