### ISSUE TITLE
Model Validation Not working in frontend

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1232]
My User model is using email fields, It defines:
```
User.add({
	name: { type: Types.Name, required: true, index: true },
	email: { type: Types.Email, initial: true, required: true, index: true},
...

````
The email validation works fine in AdminUI.

However, My frontend signup doesn't works. My signup route is cloned from sydjs project, the update part is as follow:

```
	var userData = {
					name: {
						first: req.body.firstname,
						last: req.body.lastname,
					},
					email: req.body.email,
					password: req.body.password
				};

				var User = keystone.list('User').model,
					newUser = new User(userData);

				newUser.save(function(err) {
					return cb(err);
				});

```

User successfully signup even with ***email=a***

**The issue is weird, as I open the user in AdminUI and save it, then the error pop up correctly.**

**Comment by ttsirkia** [comment]
The model is not validated by Keystone's own validation mechanism if you just call `save`. That call is handled in Mongoose and in Mongoose that field is a string field.

If you want to validate your data, you should use `UpdateHandler`. There are many examples in SydJS project.

**Comment by mxstbr** [comment]
This question was thoroughly answered by @ttsirkia, so I'll close it! Feel free to comment again if you have another question!
