### ISSUE TITLE
I can't get "PUT" request from client.

### ISSUE THREAD

**Issue by alexander-tsig** [keystonejs/keystone#1233]
Hi everyone,
I am enjoying KeystoneJS, but I have a trouble on implementing REST API.

Here is what I did.
views/routes/index.js
var routes = {
	api: importRoutes('./api'),
};

...
app.put	('/api/shows/:id?',		keystone.middleware.api,			routes.api.shows.update);
...

routes/api/shows.js

exports.update = function(req, res, next) {
	console.log('here');
	res.apiResponse({
		show: 'asdfsd'
	});
	return function(){};
	Show.model.findById(req.params.id).exec(function(err, item) {
		if (err) return res.apiError('database error', err);
		if (!item) return res.apiError('not found');
		item.getUpdateHandler(req).process(data, function(err) {
			if (err) return res.apiError('create error', err);
			res.apiResponse({
				show: item
			});
		});
	});
}
 

When I ran KeystoneJS and sent the "PUT" request, KeystoneJS seems to accept the request, but it does not call "routes.api.shows.update" method.
How can I fix this issue?

KeystoneJS Started:
Fountain is ready on port 3000

PUT /api/show/550af3aebbb8ab9bd522615d 404 29.028 ms

**Comment by JohnnyEstilles** [comment]
@alexander-tsig, although you're not sharing any of your front-end code, there seems to be a discrepancy in the routes/urls of your server-side and client-side code.

The route definition (on your server-side code) says:
```js
app.put ('/api/shows/:id?', keystone.middleware.api, routes.api.shows.update);
               ^--- (shows in plural)
```   
But the error log (showing then connections from your client-side code) says:
```js
PUT /api/show/550af3aebbb8ab9bd522615d 404 29.028 ms
         ^--- (show in singular)
```

**Comment by alexander-tsig** [comment]
Thanks! You saved my time!

**Comment by JohnnyEstilles** [comment]
@alexander-tsig ... You're welcome!
