### ISSUE TITLE
LocalFiles Type cannot remove or format not working

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1238]
I have the LocalFiles type for images upload.  However, once I uploaded the file, I cannot delete it. (no error return neither;)

On the other hand, The format isn't working, it keeps showing the "PNG 123423434343.png" format in the Admin UI

```
Layout.add({
  name: { type: String, initial: true, required: true, index: true, unique: true  },
	thumb: { type: Types.LocalFile, dest: 'public/uploads/layouts'},
  status:  { type: Types.Select, options: 'active, inactive', required: true, default: 'active'},
  description: { type: Types.Textarea, required: true, initial: true}, //, wysiwyg: true, height: 400}
  images: { type: Types.LocalFiles, 
                dest: 'public/uploads/layouts',      
                format: function(item, file){
                  return '<img src="/uploads/layouts' + file.filename+'" style="max-width: 300px" title="'+ file.originalname+ '">'
                }
          },
});

```

Here is the field's html in AdminUi:
```
<div class="file-item" data-reactid=".0.2.4:$images:0.4.0.$2"><img class="file-icon" src="/keystone/images/icons/32/png.png" data-reactid=".0.2.4:$images:0.4.0.$2.0"><span class="file-filename" data-reactid=".0.2.4:$images:0.4.0.$2.1">638c9cbd1921c1a2a3264286cd912010.png</span><span class="file-size" data-reactid=".0.2.4:$images:0.4.0.$2.2">1.13kb</span><span class="file-action" data-reactid=".0.2.4:$images:0.4.0.$2.3">remove</span></div>

```

The file is indeed Uploaded successful in the server. It exists in my upload folder.

**Comment by Nuwen** [comment]
Yeah, I'm running into this issue too on 0.3.8. 

I suspect we'll have to author a function that hooks into the POST request, e.g. 

```view.on('post', callback)```

The callback would then manipulate the model.

**Comment by Nuwen** [comment]
Okay, ignore my last post - that was a stupid, generic response. I've spent the better part of the day getting super familiar with this codebase, and I managed to figure this one out.

It looks like LocalFilesField.js was cloned from CloudinaryImagesField.js, but the property names used by LocalFiles aren't quite the same as CloudinaryImages.

The action submitted was also called "remove" but LocalFilesType.js expects to receive "delete". 

**Before**
![post_localfiles](https://cloud.githubusercontent.com/assets/2601819/7524790/75be6900-f4d2-11e4-9eef-462277cbc9d1.PNG)

**After**
![post_localfilesfixed](https://cloud.githubusercontent.com/assets/2601819/7524797/81e68fd2-f4d2-11e4-831c-a31dd759f574.PNG)

Submitting a pull request now ^^v

**Comment by arthurtalkgoal** [comment]
Oh, @Nuwen, that's cool seems you have fixed it!

**Comment by aokoli** [comment]
Thanks @leigh-johnson. The issue still persists for "Types.LocalFile", and your fix is for "Types.LocalFiles" (I have been trying to resolve this for hours for "Types.LocalFile", but your reference to #1370 above made me try "Types.LocalFiles", and that works).
