### ISSUE TITLE
Needs docs: new list history feature

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1240]
Should be added to the list options docs.

There's a new feature, list history, which saves revisions of documents when they're created / updated / removed.

You enable it on a per-list basis with the option `history: true`

History document schema is

```js
{
	i: id, // id of changed document
	t: Date.now(), // timestamp
	o: this.isNew ? 'c' : 'u', // c(reated) u(pdated) r(emoved)
	c: [], // array of field paths that have been changed
	d: data // data snapshot
};
```

It also adds a `__rev` path to the main Schema, which is an auto-incremented number of revisions made.

See https://github.com/keystonejs/keystone/blob/master/lib/schemaPlugins/history.js for details.

**Comment by morenoh149** [comment]
🎉

**Comment by varatep** [comment]
Is there an example of how to use this?

Would it be something like:

`var Documentation = new keystone.List('Documentation', {
	map: { name: 'title' },
	autokey: { path: 'slug', from: 'title', unique: true },
	history: true
});`

**Comment by creynders** [comment]
Why exactly are the schema fields so cryptically named? To save space? Is it really worth it?

**Comment by mxstbr** [comment]
https://github.com/keystonejs/keystonejs-site/issues/100
