### ISSUE TITLE
Show revisions in the Admin UI

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1241]
We now have a list history feature (see #1240)

The current revision, and a way to browse revision history, should be revealed in the Admin UI somewhere.

Should be pretty easy to do with a new API and some React magic.

**Comment by tivac** [comment]
I thought about this for a bit. 

Something kinda like this seem reasonable? It's not exactly sexy, but it is pretty functional IMO.
![revisions](https://cloud.githubusercontent.com/assets/49545/6796676/9f534074-d1b4-11e4-9886-49e6894ab3dc.png)
_(please ignore my terrible spacing issues)_

**Comment by albertogasparin** [comment]
What would be really cool is a [time slider like on Etherpad](https://etherpad.mozilla.org/ep/pad/view/wZUhcvCCWr/latest).
We don't need the word by word changes, but with React is quite easy to change the content as you click through the saved revisions.

**Comment by medv** [comment]
Slider or not, what @tivac sketched up there is still good for quick glance.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/show-revisions-in-the-admin-ui!
