### ISSUE TITLE
Tinymce adding <span> with inline styles on 'paste'??

### ISSUE THREAD

**Issue by cantuket** [keystonejs/keystone#1242]
Hi,

Could someone explain to me how Tinymce is being initialized? I need to add this option ( 'paste_remove_spans': True, ) to prevent the adding of span tags with inline styles whenever I paste in content. I have absolutely no clue why this would be a default setting in Tinymce, seems a little absurd.

If I cant get this figured out Im going to have to ditch Keystone completely, which also seems pretty ridiculous.

Thanks for any help!

**Comment by albertogasparin** [comment]
[Read the documentation](http://keystonejs.com/docs/configuration/#options-ui). It's simple: add `wysiwyg additional options` key to your `config` object in `keystone.js`.

``` js
'wysiwyg additional options': { 
  'paste_remove_spans': true
}
```

Then TinyMCE will pick up that option on init.

**Comment by cantuket** [comment]
Thank you for the help, but this specific option still doesn't work for me, nor does the 'paste_as_text' option for the paste plugin.

The closest solution I was able to come up with to activate the 'menu bar' and use the 'clear formatting' option.

I appreciate the help though.

**Comment by drlogout** [comment]
with these settings pasting with and without formatting is working for me with keystone v0.3.6:

```
'wysiwyg additional plugins': 'paste',
'wysiwyg additional options': {
	paste_as_text: true,
	paste_webkit_styles: "color font-size"
}
```

**Comment by cantuket** [comment]
Awesome, this is what did it for me.

Thanks!
