### ISSUE TITLE
`delete`/`deleteAll` nested mutations

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1244]
We [already have](https://github.com/keystonejs/keystone-5/blob/master/packages/fields/src/types/Relationship/README.md) nested mutations for:

- `create`
- `connect`
- `disconnect`
- `disconnectAll`

Where `connect`/`disconnect` are the inverse of eachother.

We currently have no inverse of `create`.

## Proposal

Given the following (contrived) schema:

```javascript
keystone.createList('Gallery', {
  fields: {
    title: { type: Text },
    images: { type: Relationship, ref: 'Image', many: true }
  }
});

keystone.createList('Image', {
  fields: { ... }
});
```

### `delete`

_Equivalent API as `disconnect`_

For example; a user deletes a single image from a gallery while also editing the title, and we want to perform the nested delete along with the update to the gallery

```graphql
mutation {
  updateGallery(
    id: "...",
    data: {
      title: 'One less image'
      images: {
        delete: [{ id: "..." }] # an array because it's a to-many relationship
      }
    }
  ) {
    id
  }
}    
```

### `deleteAll`

_Equivalent API as `disconnectAll`_

For example; this time the user deletes all images:

```graphql
mutation {
  updateGallery(
    id: "...",
    data: {
      title: 'Imageless'
      images: {
        deleteAll: true
      }
    }
  ) {
    id
  }
}    
```

New order of operations:

1. `deleteAll`
1. `delete`
1. `disconnectAll`
1. `disconnect`
1. `create`
1. `connect`

**Comment by jesstelford** [comment]
Work has begun in the `nested-delete-mutations` branch.

**Comment by ralvs** [comment]
Hey guys, are there any updates about that?
