### ISSUE TITLE
CA Bundles

### ISSUE THREAD

**Issue by justinsullard** [keystonejs/keystone#1247]
@snowkeeper Unfortunately the current implementation only appears to be setup for a single ca bundle path, but https.createServer option spec (https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) allows for an array of them. If a bundle file is used (GoDaddy ca_bundle for instance) https only serves up the first cert in the file, not all contained, so the array must be implemented.

**Comment by snowkeeper** [comment]
@justinsullard can you give the following branch a test and see if the array implementation is working for you.  I do not have a bundle on hand to test it out...
`npm install snowkeeper/keystone#ca-bundle`

`keystone.set('ssl ca') = ['file1','file2']`

**Comment by mxstbr** [comment]
We now have `keystone.set('https server options', { /* your options here */ })` thanks to @molomby! Ref #2481 and #2482
