### ISSUE TITLE
Filter tests for built in types

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#125]
- [x] Text
- [x] Select - In progress (branch `select-filter-tests`)
- [x] Relationship
- [x] Password
- [ ] File
- [x] CloudinaryImage (this will be moving out of core)

**Comment by MadeByMike** [comment]
@timleslie is this still required?

**Comment by MadeByMike** [comment]
Relationships are done - going to open a new ticket for implementation tests on file field
