### ISSUE TITLE
Embedded <script> in HTML field breaks react editor

### ISSUE THREAD

**Issue by pswoodworth** [keystonejs/keystone#1250]
I've been using keystone for a blog, and I've discovered that since the 0.3.x upgrade to react in the editor, an embedded script in an HTML field (that is to say, the blog content) breaks the editor. Specifically, the `</script>` tag does not seem to be properly escaped and leads to an `Unexpected EOF` error. I'm not very familiar with react (yet) so I'm not sure how to go about tackling this one. I'd really appreciate any help – my blog thirsts for embedded tweets!

**Comment by morenoh149** [comment]
what fieldtype are you using for the editor? this one? http://keystonejs.com/docs/database/#fieldtypes-html

**Comment by pswoodworth** [comment]
yep I’m using the HTML field type


On March 24, 2015 at 4:50:48 PM, Harry Moreno (notifications@github.com) wrote:

what fieldtype are you using for the editor? this one? http://keystonejs.com/docs/database/#fieldtypes-html

**Comment by lojack** [comment]
Having the same problem, screenshot attached.

![screen shot 2015-03-27 at 1 53 48 pm](https://cloud.githubusercontent.com/assets/180470/6873741/d2a4e38e-d488-11e4-9f19-a8c90437fd19.png)

**Comment by pswoodworth** [comment]
yep – that's exactly what I'm getting

**Comment by lojack** [comment]
I opened a PR with a fix. A potential side effect of this is that after saving, content may change to have the escaped </script> tag. Not quite sure the best way to handle this, but this should at least be better than an error.

**Comment by JedWatson** [comment]
I'm a bit worried about this, in hindsight - escaping / double escaping sounds like a trap.

I'm rewriting this screen to load data as JSON from the API, which needs to happen anyway - will hopefully fix this issue without any potential for double-escaping data.
