### ISSUE TITLE
Cannot remove TextArray After Add

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1251]
I am using the latest version.  The TextArray cannot be removed once inserted in AdminUI.

**Comment by morenoh149** [comment]
did you try 
* saving your file 
* restarting the dev server 
* `ctrl + F5` to load a fresh copy of the js assets

**Comment by arthurtalkgoal** [comment]
Oh @morenoh149 

It works after I restart the server!
