### ISSUE TITLE
Allow relationship fields to override duplicate filtering

### ISSUE THREAD

**Issue by leftmostcat** [keystonejs/keystone#1252]
As it currently stands, the react-select component defaults to removing duplicate entries. There are instances where it may be useful for a relationship to be order-preserved with duplicates allowed, but keystone provides no means of tapping into the react-select functionality that would allow this. This could be implemented either as a field option for allowing duplicates, with an internally-provided filterOptions override, or by allowing the field to provide a function to override filterOptions.

I would be willing and able to create a PR for this, but could use some guidance on the method the project would prefer.

**Comment by mikestopcontinues** [comment]
+1

**Comment by mxstbr** [comment]
I'll close this due to inactivity, let me know if this is still desired by commenting below!
