### ISSUE TITLE
Allow logic to control whether an autokey is updated

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1253]
Autokeys only have limited control over whether they are updated or not; either they always change, or (when `fixed: true`) they don't change once they have been set.

There's a use case where you'd only want the key to be locked based on dynamic logic; e.g. don't change if `state === 'pubilished'`.

We could add an optional function to be provided that implements custom logic and returns a boolean:

```
{
  autokey: {
    from: 'name',
    path: 'slug',
    shouldUpdate: function(value, modified) { return this.state !== 'published'; }
  }
}
```

**Comment by mxstbr** [comment]
https://productpains.com/post/keystonejs/allow-logic-to-control-whether-an-autokey-is-updated
