### ISSUE TITLE
How to deploy Keystone 5 to now.sh v2 (serverless)

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1258]
> _Part of "Keystone 5 deployment strategies" #1257_

Work is ongoing in the [`now-deploy`](https://github.com/keystonejs/keystone-5/tree/now-deploy) branch.

The current state of deploying to `now` involves creating a monolithic lambda which serves all associated [_apps_](https://v5.keystonejs.com/discussions/apps) (except `next`, which should be a first-class citizen on `now`).

TODO:

- [ ] Create a `@keystone-alpha/deployment-now` package based on `demo-projects/blog/target-now.js`
- [ ] Publish the packages so the build command correctly exist on `now`
- [ ] TinyMCE build needs to copy assets from `node_modules` to the `distDir` during
  `build`, and serve those files during `prepareMiddleware`.
- [ ] Should throw error during building when using `localFileAdapter` and `--target=serverless`
- [ ] If a `nextApp` is detected during build; bail out with a helpful error about using the `@now/next` builder and explicitly defining it in your `now.json`
- [ ] Get `now dev` working(?)
- [ ] Add caching headers on the admin bundles (does this store those bundles on a public CDN somewhere? If so, that's bad)
- [ ] Document how to use this ☝️ 
- [ ] Confirm that decoupling the build & middleware functions means only the ones that are used get bundled by `ncc` and pushed to `now` (ie; so we can reduce the bundle down from `8.7MB`)

MAYBE TODO:

- [ ] Auto generate the `now.json` routes
- [ ] Support custom Admin UI pages
- [ ] Building needs to correctly split the lambdas at app boundaries so they're no longer monolithic
  - [ ] Create separate entry points for each lambda
  - [ ] Automatically generate a `now.js` routes & builders file

For a live example of a now deployment, see: https://blog-demo.keystone.now.sh

**Comment by MadeByMike** [comment]
Low priority until there is a large use-case
