### ISSUE TITLE
Field validation: Max characters

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#126]
It'd be nice to be able to add { maxChars: x } to a field

**Comment by albertogasparin** [comment]
+1 :+1: 
However I think that `crop` is bad UX. Cropping text without notice could lead to undesired strings.
I think the default behaviour should be `validate` (aka Twitter-like): the counter goes red, displays a -N and the item cannot be saved.
The alternative behaviour is `warn`, which makes the counter orange but nothing more.

**Comment by bradwbradw** [comment]
+1

**Comment by ericelliott** [comment]
> I think the default behaviour should be validate (aka Twitter-like): the counter goes red, displays a -N and the item cannot be saved.

:+1:

**Comment by bradwbradw** [comment]
@ericelliott  agreed!

**Comment by prachi-159** [comment]
In which file do we have to add this feature ?

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this over, from now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/field-validation-max-characters)!

**Comment by shankarjois** [comment]
What is status of this?

**Comment by VinayaSathyanarayana** [comment]
is this not in latest beta?

**Comment by sheldon-sminq** [comment]
There is a bug in the beta version
current code
`
text.prototype.validateInput = function (data, callback) {
        var max = this.options.max;
        var min = this.options.min;
        var value = this.getValueFromData(data);
        var result = value === undefined || value === null || typeof value === 'string';
        if (max && typeof value === 'string') {
                result = value.length < max;
        }
        if (min && typeof value === 'string') {
                result = value.length > min;
        }
        utils.defer(callback, result);
};
`
With fix
`
text.prototype.validateInput = function (data, callback) {
        var max = this.options.max;
        var min = this.options.min;
        var value = this.getValueFromData(data);
        var result = value === undefined || value === null || typeof value === 'string';
        if (max && typeof value === 'string') {
                result = value.length < max;
        }
        if(result) {
           if (min && typeof value === 'string') {
                result = value.length > min;
           }
        }
        utils.defer(callback, result);
};

`

**Comment by tsuNammi** [comment]
Does this work for the WYSIWYG/tinymce too?
