### ISSUE TITLE
Changes in pre-save hook not persisted

### ISSUE THREAD

**Issue by snawbel** [keystonejs/keystone#1261]
This might be due to a local mind-melt but I can't get changes in the save-hook to persist to DB. Steps to reproduce:

1. `yo keystone` with defaults
2. Add to Post.js
```
Post.schema.pre('save', function(next) {
  this.foo = 'bar';
  next();
});
```

Just me, or?

**Comment by creynders** [comment]
Have you declared `foo` in your schema? Mongoose schema's are `strict` by default, which means only values for fields that are explicitly declared will be stored to the DB.

**Comment by snawbel** [comment]
Thanks; need to brush up on Mongoose.
