### ISSUE TITLE
delete button on current user profile

### ISSUE THREAD

**Issue by snowkeeper** [keystonejs/keystone#1264]
The user currently logged in can not successfully delete themselves.  Should the UI be updated to hide the delete button in this case?

**Comment by creynders** [comment]
:+1: Personally I'd go for a disabled button instead. Not sure what other people think.

**Comment by mxstbr** [comment]
Duplicate of #265, moved to ProductPains! https://productpains.com/post/keystonejs/can-delete-all-admin-users
