### ISSUE TITLE
Write a guide on deployment options for Keystone

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1265]
> _Part of "Keystone 5 deployment strategies" #1257_

WIP Notes:

- Ways to trigger a build
  - link to Git repo & deploy on push to `master`
  - Or, use heroku cli to push to heroku's `master`
- `build` / `start` commands
  - Can use `Procfile` with `web` (start) or `release` (install)
  - Or (better), use the Node Build Pack, which auto runs `yarn build` & `yarn start` for you
- Free Dyno:
  - Goes to sleep, so shows the "Connecting to Keystone page" when waking up
  - _Might_ run out of memory (static builds may have fixed this)
- Hobby Dyno:
  - Cost: $7/mo
  - Stays awake
- Add-ons may provide a nice all-in-one-service experience:
  - mLab Mongo DB with free tier (400MB storage)
  - Cloudinary with free tier

**Comment by mitchellhamilton** [comment]
> mLab Mongo DB with free tier (400MB storage)

The free tier doesn't allow mongo 4 btw
