### ISSUE TITLE
S3 file deletes are not working

### ISSUE THREAD

**Issue by foobar8675** [keystonejs/keystone#1266]
Let me know how to provide more details. I just
1. created a new record in my new document that looks like this

    	AudioFile.add({
    	name: { type: Types.Name, required: true, index:true },
    	creator: { type: Types.Relationship, ref: 'User', index: true },
    	audioFile : {type: Types.S3File},
    	createdAt: { type: Date, default: Date.now },
    	categories: { type: Types.Relationship, ref: 'AudioFileCategory', many: true, index:true }
    });

2. I went to the admin page and 'Uploaded File' 
3. I hit save
4. I verified my file in s3
5. I hit 'Remove File'
6. I hit save see no errors
7. My file is still in s3

Anyways, I'm pretty new to Keystone so any help is appreciated.

**Comment by morenoh149** [comment]
can you verify this line https://github.com/keystonejs/keystone/blob/40563de928892deb9f707a4498439663d154443d/fields/types/s3file/S3FileType.js#L140 executes? It may be that the model deletion code isn't calling the s3file delete method.

**Comment by captainchung** [comment]
For me, that line is on L160 instead of L140 (just did npm update and am on 0.3.4) but no, I do not see that line being called.

**Comment by creynders** [comment]
We're doing a full rewrite of all file fields, including S3. This _should_ be fixed once that's finished :grin:

**Comment by captainchung** [comment]
Got it. Thanks creynders.

On Tue, Mar 31, 2015 at 12:59 AM, creynders <notifications@github.com>
wrote:

> We're doing a full rewrite of all file fields, including S3. This *should*
> be fixed once that's finished [image: :grin:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/1266#issuecomment-87987361>
> .
>



-- 
Regards,
Matt

**Comment by captainchung** [comment]
One question, is there going to be the ability to download/view an uploaded S3 file? I don't see the ability in the current version.

**Comment by creynders** [comment]
Yes, download will be included

**Comment by rnjailamba** [comment]
@creynders 
How are things looking at the moment ?

**Comment by andrew-kennedy** [comment]
I'm also curious about the progress on this. +1

**Comment by mxstbr** [comment]
Sadly, this got a bit stuck. We'll get to it eventually, but right now we have other priorities (admin interface). This is well on our radar though and we're looking into it actively!
