### ISSUE TITLE
Note on s3 documentation

### ISSUE THREAD

**Issue by foobar8675** [keystonejs/keystone#1267]
Not sure where to send feedback on the docs, but on this step here

http://keystonejs.com/docs/configuration/#services-amazons3

With my newly created bucket, I had to add the S3_REGION environmental variable as well. Without it, I was getting errors.

**Comment by carlafranca** [comment]
I would add to it the Region you choose when creating the S3. 
The "Signature Version(s) support" seems to be only version 2.
I tried to use Frankfurt but It didn't work. "version 4 only"
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by mxstbr** [comment]
https://github.com/keystonejs/keystonejs-site/issues/106
