### ISSUE TITLE
Add custom validation for sign in

### ISSUE THREAD

**Issue by ttsirkia** [keystonejs/keystone#1269]
The ready-made `signin` function is quite handy if you override the original login view. However, it might be a good idea to add here

```javascript
exports.signin = function(lookup, req, res, onSuccess, onFail) {
```

sixth parameter for a custom validation function which retrieves the `User` and returns `true` or `Error` object. For example, you might have a field for `accountLocked` and that should be checked when user logs in.

I can make a PR if the idea sounds good.

**Comment by creynders** [comment]
Sounds like a good idea, however I'm not sure about passing it as a 6th parameter. Maybe there's a better approach? Maybe we could provide `pre` and `post` "signin" hooks which could be used?
Basically there's a number of situations that might be of interest:

* _before_ the whole shebang
* _after_ the matching user is retrieved, but _before_ authentication
* _after_ authentication

What do you think?

**Comment by ttsirkia** [comment]
Sounds better but requires more work. :smiley:

**Comment by creynders** [comment]
LOL. 

_If_ you're interested in tackling this, you should know I've extracted all hooking functionality from keystone into a separate module: [grappling-hook](https://github.com/keystonejs/grappling-hook) which you can use to add/call hooks. The documentation is pretty thorough, but I you need to know anything, let me know! Keystone v0.4 will use grappling-hook, i.e. in `master` it's not in use yet.

**Comment by ttsirkia** [comment]
Is there need for hook before the whole authentication? Could `pre` be when `User` is retrieved and password is checked but not yet registered to session and `post` after `User` is in Session?

**Comment by creynders** [comment]
Hmm, yeah I don't know. So, for instance (just free-wheeling here) something like this:

```js
keystone.pre("signin", function(user, auth, next){
  if(user.accountLocked){
    return next( new Error("ACCOUNT LOCKED, MOFO!"));
  }
  next();
});
```

It _does_ make sense to have the user object available. I'm just wondering whether there are situations where you'd want to hook into _before_ the user is retrieved. But I must confess I can't come up with a viable use case.

**Comment by ttsirkia** [comment]
Looks exactly what I was thinking.

**Comment by ttsirkia** [comment]
@creynders are you working with this? I might have time next week to implement this feature unless you have already started.

**Comment by creynders** [comment]
@ttsirkia Totally forgot. `grappling-hook` landed into keystone, i.e. this should take me very little time to add. Should have a moment or two today, will keep you updated.

**Comment by creynders** [comment]
Landed. Usage is:

```js
keystone.post("signin", function(){
  //`this` refers to the `user` object
  if(this.accountLocked){
    return next( new Error("ACCOUNT LOCKED, MOFO!"));
  }
  next();
});
```

I.e. two things differently from the above example: you need to use `post("signin")` and instead of getting the `user` object as a parameter, the middleware is executed in the scope of the user object.

**Comment by ttsirkia** [comment]
Great job, thanks!

**Comment by kartsims** [comment]
Great feature, thanks guys ! It is a shame it is not in the documentation.. I had to dig my way here to find out about the implementation (I did notice it in the code so I thought there would be something out there)

Want help in documenting this ?

**Comment by morenoh149** [comment]
@kartsims yes please

**Comment by kartsims** [comment]
Opened up an issue a few days ago https://github.com/keystonejs/keystonejs-site/issues/53
