### ISSUE TITLE
.scss partials not being imported on request

### ISSUE THREAD

**Issue by Aweary** [keystonejs/keystone#1278]
From what I understand, Keystone should be compiling my `scss` files on request. I generated my project using Yeoman, and chose Gulp as a task runner.

The `scss` files are not being compiled on request. If I add the change directly to the `main.scss` file then it will re-compile. If I make a change to a partial (such as site/_layout.scss) it will not re-import the newly edited partial.

I have to stop the node process and run `node keystone` again for the changes to propagate. My `keystone.init` configuration has the following set for sass (the defaults):

```javascript
keystone.init({
'sass': 'public',
'static': 'public',
 // irrelevant code removed 
});
```

And here is my `package.json` dependencies

```javascript

{
  "name": /* REMOVED */ ,
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "keystone": "~0.3.0",
    "async": "~0.9.0",
    "underscore": "~1.7.0",
    "moment": "~2.8.1",
    "cloudinary": "^1.0.12",
    "express-handlebars": "~1.1.0",
    "handlebars": "~2.0.0",
    "node-sass": "~1.0.1",
    "node-sass-middleware": "^0.4.0",
    "dotenv": "~0.4.0"
  },
  "devDependencies": {
    "gulp": "~3.7.0",
    "gulp-jshint": "~1.9.0",
    "gulp-watch": "~0.6.5",
    "jshint-stylish": "~0.1.3",
    "node-sass": "^1.0.3"
  },
  "engines": {
    "node": ">=0.10.22",
    "npm": ">=1.3.14"
  },
  "scripts": {
    "start": "node keystone.js"
  },
  "main": "keystone.js"
}


```

Is this an issue with Keystone, the sass configuration, or with node-sass?

**Comment by mxstbr** [comment]
This works out of box now, not sure why that was broken back then! Thanks for taking the time to submit this bug!
