### ISSUE TITLE
Specifying relationship fields in the searchFields option for a list throws obscure errors 

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#128]
If a list has a relationship field listed in its `searchFields` option, `mongoose.query` throws an obscure error:

```
TypeError: undefined is not a function
    at Query.count (/Keystone/node_modules/mongoose/lib/query.js:1197:5)
    at Function.count (/Keystone/node_modules/mongoose/lib/model.js:1073:13)
    at module.exports (/Keystone/routes/api/list.js:35:31)
    at callbacks (/Keystone/node_modules/express/lib/router/index.js:164:37)
    at initList (/Keystone/index.js:615:3)
```

The option should validate its arguments and warn on invalid config if this is the case.

I'm also not sure why this specific error is being thrown, it appears that `this.cast(this.model);` is throwing, and `callback` has not been defined yet. May not be a problem, since this situation shouldn't be possible anyway...

**Comment by wmertens** [comment]
Is this still happening?

**Comment by lazaridis-com** [comment]
@wmertens, @JedWatson, a 3 year old open issue looks always a bit strange.

**Comment by stennie** [comment]
Closing out stale issues which predate the Keystone 4 development cycle. If this still affects Keystone 4, please create a new report with further details.

Thanks,  
Stennie
