### ISSUE TITLE
Relationship select field shuffling order of entries

### ISSUE THREAD

**Issue by lojack** [keystonejs/keystone#1281]
Using a Relationship field with `many` set to true, I've been running into an issue where the elements in the field are being reordered when adding and removing items from the list. 

I've only been able to recreate this on slow networks, and doesn't occur when I'm doing local development.

**Comment by creynders** [comment]
I've had this too, but in my experience this was only a UI problem, i.e. the order _was_ maintained when persisted to the DB. But maybe I was just lucky.

**Comment by JedWatson** [comment]
Fixed by #1287
