### ISSUE TITLE
Why keystone does not support multiple file upload?

### ISSUE THREAD

**Issue by janryWang** [keystonejs/keystone#1282]

**Comment by morenoh149** [comment]
Multi-file upload isn't detailed anywhere in these modules. This would be a nice feature to have. See https://github.com/Automattic/knox https://www.npmjs.com/package/s3

**Comment by janryWang** [comment]
@morenoh149 Because I live in China, to access these services is too slow.

**Comment by janryWang** [comment]
@morenoh149 Because I live in China, to access these services is too slow.

**Comment by JedWatson** [comment]
@creynders may be able to confirm this but I suspect we will be able to land this when our new `File` field type is implemented...

**Comment by janryWang** [comment]
Thank you, in fact, I've solved this problem, and also I want to submit a PR for this project.

**Comment by morenoh149** [comment]
@janryWang 👍 go ahead. I thought about this some more. Did you simply ask for more than one file from the filesystem and call the upload routine multiple times?

**Comment by janryWang** [comment]
@morenoh149 Yes, I mean that I can upload more than one file , while connected to a cloud service.
https://gist.github.com/janryWang/2c91e20df7b94df07c72

Of course, if this upload component can support fragmentation uploading large files, it is very cool.

**Comment by creynders** [comment]
hey @janryWang looks like you're adding a new cloud storage type? Bad news is, as I already mentioned a few times, we're rewriting all file field types and your gist clearly is based on the old types. Have a look in the v0.4 branch, there's you'll see the new approach for file field types. Also, I'm in the process of trying to come up with a solution to allow _all_ file fields to accept multiple files, so I really think it's in your best interest to have a look at the new version.

**Comment by gcortese** [comment]
hi sorry if I missed something ..
any update or documentation on this point for the new version ?
thanks a lot

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/support-multiple-file-upload
