### ISSUE TITLE
moment() seems to be stuck on a previous time

### ISSUE THREAD

**Issue by hatzipanis** [keystonejs/keystone#1284]
In `Notice.js`, a model, I define:

```javascript
var now = moment();
var then = now.clone();
then.add(3, 'months');
````

then I use it inside `Notice.add({})` like so:

```javascript
publishedDate: { type: Types.Datetime, default: now, index: true },
expiryDate: { type: Types.Datetime, default: then, index: true }
````

but when I create a Notice via Admin UI the time is incorrect. The date is correct but time seems to be a time in the not so distant past.

For example, I just created a new Notice within the Admin UI and despite being 9:22am on my computer clock, the time used for `moment()` was 12:41am. If I create another one sure enough it's still 12:41am. The time seems to be stuck on this time for a period before then finding another time to use. I haven't been able to distinguish a pattern although oddly if I re-save `Notice.js` and then create a Notice I will get what seems to be the time that the model file was re-saved.

However what is even stranger is that I have a form on the front-end that users can submit notices via and this time is correct every single time.

Does anybody know what could be going on here?

**Comment by ttsirkia** [comment]
I think that default value is evaluated only once and that happens when that file is loaded to memory. You should use a function which returns the desired date.

**Comment by hatzipanis** [comment]
@ttsirkia thank you! Using a function fixed the issue.
