### ISSUE TITLE
Need Docs: field "size" option for Admin UI appearance

### ISSUE THREAD

**Issue by albertogasparin** [keystonejs/keystone#1286]
It looks like Keystone fields have a `size` option that can be used to customise the width of the field in the Admin UI. Possible values are [defined here](https://github.com/keystonejs/keystone/blob/master/fields/types/Type.js#L129):

```
small
medium
large
full
```

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/108
