### ISSUE TITLE
Validate user-returned data from `resolveInput` hook

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1289]
The `resolveInput` hook allows the app developer to return an arbitrary object which then gets passed into internal workings of KS5. If this object is incorrectly structured, it will throw confusing errors such as:

```
Task validation failed: goal: Cast to ObjectID failed for value "{ connect: { id: '5cf8c1dfc69e5402f905811c' } }" at path "goal"
```

In this case, the mistake is returning `originalInput` from the `resolveInput()` method instead of the `resolvedData`:

```javascript
resolveInput({ resolvedData, originalInput }) {
  return originalInput; // <-- WRONG
}
```

(where:

```javascript
const resolvedData = {
  goal: "5dslkjdsflkjwer",
};
const originalInput = {
  goal: {
    connect: { id: "5gdfgiousdfjkhasdlkj" }
  }
};
```
)

Ideally we'd catch this mistake and throw an error such as:

> _`resolveInput() hook returned data of incorrect shape, expected "String" at path "goal", received "Object". Did you mean to return `resolvedData`?`_

**Comment by thiagodebastos** [comment]
I had some trouble last night using hooks too. In the `afterChange` hook, I was comparing `updatedItem.id` with the array of ids of related items.
The array of ids of `Relationship` items is an array of Mongo `ObjectId`s while `updatedItem.id` is a string.
Is that a related issue? If not I will create a new one.

```js
keystone.createList('SkillNode', {
  fields: {
    id: MongoId.primaryKeyDefaults.mongoose.getConfig(),
    name: { type: Text, schemaDoc: "The name of this skill" },
    slug: { type: Slug, from: 'name', isUnique: true, isRequired: true },
    children: {
      type: Relationship,
      ref: 'SkillNode.children,
      many: true,
    }, 
    children: {
      type: Relationship,
      ref: 'SkillNode.parents',
    },
  },
  hooks: {
    afterChange: ({ updatedItem }) => {

      const { children, existingItem, id } = updatedItem

      console.log(children.findIndex(el => {
        return el === id                         // false
      }))

      console.log(children.findIndex(el => {
        console.log(typeof el, typeof id)        // object string
        console.log(Object.keys(el))             // [ '_bsontype', 'id' ]
        return el.toString() === id.toString()   // true
      }))
      return updatedItem
    }
  }
});
````

**Comment by jesstelford** [comment]
This sounds like a seperate issue which we need to address! Can you open a new GitHub issue? Good catch 👍

**Comment by thiagodebastos** [comment]
I've created a new issue: https://github.com/keystonejs/keystone-5/issues/1499

**Comment by thiagodebastos** [comment]
Seems like I've landed here again! This looks like a related issue this time, what do you think?
```
bundle.esm.js:63 Uncaught (in promise) Error: GraphQL error: Cast to ObjectId failed for value "{ connect: { id: '5d57836667a5b04d9b5bf577' } }" at path "_id"
    at new ApolloError (bundle.esm.js:63)
```
