### ISSUE TITLE
Double escaping in autocomplete dropdown

### ISSUE THREAD

**Issue by albertogasparin** [keystonejs/keystone#1293]
If an item has a special char in the title, it will rendered as &dash; and not as –.
This happens because the API response has the title escaped ([see api/list.js](https://github.com/keystonejs/keystone/blob/master/routes/api/list.js#L64)).

Personally I think that it is not needed anymore calling `utils.encodeHTMLEntities` to escape the document title ([see lib/list.js](https://github.com/keystonejs/keystone/blob/master/lib/list.js#L826-L829)). 
React does it out of the box.

**Comment by ttsirkia** [comment]
#1215 should have fixed this issue. However, when the autocomplete is not used but the value is already in the field, it seems to have this escaping problem.

**Comment by ttsirkia** [comment]
Maybe the whole escaping feature should be removed from `lib/list.js` because it shouldn't be server-side feature.

**Comment by albertogasparin** [comment]
:+1: 
@JedWatson do you agree? If so, could we address this for the next release?

**Comment by albertogasparin** [comment]
Version 0.3.5 fixes this issue. It is not happening anymore on autocomplete nor on field population.
Well done.
