### ISSUE TITLE
Change in documentation

### ISSUE THREAD

**Issue by cadwmaster** [keystonejs/keystone#1296]
On the documentation about the configuration of keystone (http://keystonejs.com/docs/configuration/) you point to check node-sass for the options when actually those options are passed to node-sass-middleware, you should link that library instead.

    sass options Object	 
        Optional config options that will be passed to the sass middleware; see github.com/sass/node-sass for more information.

**Comment by JedWatson** [comment]
As I understand it, the options are passed directly through from node-sass-middleware to node-sass, so the best place to find the documentation reference is in the node-sass project itself.

Is that not the case?

**Comment by cadwmaster** [comment]
Actually no, because the options are for node-sass-middleware, as you can see in the keystone file: */lib/core/mount.js*

			app.use(sassMiddleware(_.extend({
				src: this.expandPath(value),
				dest: this.expandPath(value),
				outputStyle: this.get('env') === 'production' ? 'compressed' : 'nested'
			}, sassOptions)));


and then if you follow the code of [node-sass-middleware] (https://github.com/sass/node-sass-middleware/blob/master/middleware.js) the options passed to the middleware are used only there and never sent to node-sass

**Comment by creynders** [comment]
@cadwmaster yes, that definitely does seem to be the case.

**Comment by mxstbr** [comment]
Moved to `keystonejs-site`: https://github.com/keystonejs/keystonejs-site/issues/109
