### ISSUE TITLE
whitespace in type.less break less compiler

### ISSUE THREAD

**Issue by ctaepper** [keystonejs/keystone#1299]
there are some whitespaces in type.less which break my gulp tasks
line 48, 58 and 68. 

please fix

```json
{ [Error: Unrecognised input in file /demo/node_modules/keystone/public/styles/keystone/type.less line no. 49]
  type: 'Parse',
  filename: '/demo/node_modules/keystone/public/styles/keystone/type.less',
  index: 720,
  line: 49,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract: 
   [ ' ',
     '@media (max-width: @screen-md-max) {',
     '\th1, .h1 { font-size: 2.4em; }' ],
  message: 'Unrecognised input in file /demo/node_modules/keystone/public/styles/keystone/type.less line no. 49',
  stack: undefined,
  lineNumber: 49,
  fileName: '/demo/node_modules/keystone/public/styles/keystone/type.less',
  name: 'Error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less',
  __safety: { toString: [Function] } }
```

**Comment by ctaepper** [comment]
allright, fixed it myself and did my first ever pull request:
https://github.com/keystonejs/keystone/pull/1300

**Comment by JedWatson** [comment]
Nice work @ctaepper, thanks for the PR!

**Comment by ctaepper** [comment]
you're welcome
awesome project!

**Comment by arlejeun** [comment]
Thank you! It helped me a lot. I cloned sydjs today and css was not being loaded. For some reason, this issue was not fixed.
"Unrecognised input LESS File" was my issue. I removed the whitespace in type.less file as described here and it worked.

**Comment by JedWatson** [comment]
@arlejeun thanks for pointing out it was the same issue breaking there - I've just applied the same fix there!
