### ISSUE TITLE
Social Auth should not require knowing the GraphQL Endpoint

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1300]
While waiting on #1275, the workaround is to make a HTTP request to the graphQL endpoint from within the social auth code.

Here: https://github.com/keystonejs/keystone-5/pull/1294/files#diff-ccfbb235ca5aa2f2cb26c6e9fae250d9R108

Once #1275 is done, we should remove the `endpoint` option passed to the Social Auth Strategies, and use `keystone.query()` directly.

**Comment by MadeByMike** [comment]
There are a few different places that need to be aware of the GraphQL endpoint or even the Graphiql playground in the case of the AdminUI and with multiple schemas we need to re-think a bit of how this works. 

I think the sensible approach it to require users to specify the endpoints in config?

**Comment by Vultraz** [comment]
This one can be closed, I think (b08c499e9b9b2dc1fa0139cfbf601e4f695251bf removed `hostURL` and `apiPath`).
