### ISSUE TITLE
v0.3.5 breaks `schema.path` field retrieval

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1301]
If I upgrade to v0.3.5 suddenly all `list.schema.path("field")` return `undefined`.
This is a major issue since it's mainly used for field value validation. E.g.:

```js
Document.schema.path( "link" ) .validate( function( value,
                       isValid ){
    if( !!value ){
      isValid( !this.file.size );
    } else {
      isValid( !!this.file.size );
    }
  }, "You need to supply either a local file OR an external link." );
```

On a side-note: it would be pretty useful if the `vx.x.x` tags were pushed to the repo too, it allows for easier diffing between versions.

**Comment by JedWatson** [comment]
Hmm. May have been related to the new `inherits` feature... I'll check it out.

+1 for tagging versions, I'll implement that.

**Comment by JedWatson** [comment]
Tagging versions is in, #1302 

On the downside this is definitely a side-effect of #1121

The paths aren't added to the schema before the list is registered, which in hindsight is not really a workable solution. I'll have to figure out a better way of handling it, _fast_.

We should really add a test to catch this in the future... I wasn't expecting to need to test Mongoose's functionality from within Keystone but this has demonstrated a need to ensure we don't accidentally break access to it.

**Comment by lojack** [comment]
What we would need to do is add the base schema fields on instantiation and go back to the old way of adding fields to the schema on add(). 

There was a reason I was adding fields to schema in register(), but I don't believe thats really necessary with my final solution.

**Comment by JedWatson** [comment]
Fixed it, you're right @lojack we can add the fields to the schema immediately with the way it's written now. I'm going to push a new version out with this fix so nobody else gets caught by it.
