### ISSUE TITLE
Many Relationships do not have consistent empty state

### ISSUE THREAD

**Issue by pr1ntr** [keystonejs/keystone#1306]
If I make a new Model with a relationship and do not add anything to the relationship that property on the model is `undefined`.

If I add something to that relationship, save it, then remove the items from the relationship then it becomes `array[0]`.

This makes error handling more complicated than necessary. Additionally its really annoying having relationships default to undefined at all since many times views will loop through them.

Could we make it so its always an empty array by default?

**Comment by webteckie** [comment]
@pr1ntr I think you can default the relationship field value to [] in the model definition.

**Comment by morenoh149** [comment]
I think the more mongo-y behaviour is to use `undefined`

**Comment by morenoh149** [comment]
@pr1ntr I'm unable to reproduce. Using the https://github.com/JedWatson/keystone-demo I create a `Post` which has many `Post Categories`. You get an empty array.
![screenshot 2015-04-14 16 19 14](https://cloud.githubusercontent.com/assets/587438/7149427/371173e0-e2c2-11e4-87c8-95ca10f0929a.png)

**Comment by pr1ntr** [comment]
Maybe this is because I keep changing my models and didn't resave them after the schema change.
