### ISSUE TITLE
Add limit field option to List.relationship()

### ISSUE THREAD

**Issue by mbayfield** [keystonejs/keystone#131]
Currently it returns all related items, but should default limit to 20 items, which then has an over-ride on the model def..

The UI could then show a link for "more", which passes a filter to the list screen to show all the related items.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/add-limit-field-option-to-listrelationship)!

**Comment by harshalyeole-tudip** [comment]
How is it closed without a solution??
