### ISSUE TITLE
Admin UI can create duplicate user with the same user name, email and password.

### ISSUE THREAD

**Issue by leijing7** [keystonejs/keystone#1310]
I just found the UI can create exact the same user with the same logins. 
I just delete one of them. So don't know what the consequences would be.
But I think it should not be allowed that create a user has the same name or email.

**Comment by morenoh149** [comment]
A `User` model is just an ordinary Keystone model. You must specify any validations yourself.
Consult [this issue](https://github.com/keystonejs/keystone/issues/311) where @JedWatson shows a middleware solution and a solution involving a mongo [unique index](http://docs.mongodb.org/manual/core/index-unique/).

You may also achieve the effect using a mongoose plugin https://github.com/blakehaswell/mongoose-unique-validator detailed here https://github.com/keystonejs/keystone/issues/421

**Comment by creynders** [comment]
I kinda agree that user is a bit of a special case, since it's used to login. Maybe we should add some validation to the email field in generator-keystone @morenoh149?

**Comment by morenoh149** [comment]
yes! I was about to mention the demo site and generator should enforce uniqueness if they have user models. Thanks for catching that @creynders
