### ISSUE TITLE
instal form github

### ISSUE THREAD

**Issue by betasap** [keystonejs/keystone#1312]
hi, 
how can I install keystone form gitgub ( without yo ) ?

i've done:
1) mkdir && cd keystone 
2) git clone https://github.com/keystonejs/keystone.git .
3) npm install 
4) node index.js ( but it didn't work ) -

thanks in advance

**Comment by creynders** [comment]
Hi @betasap what exactly do you want to achieve? Just asking, since I need to get a bit of a sense of your knowledge of node in general. Let's turn it around, why don't you want to use `yo`?

**Comment by betasap** [comment]
hi I'm newbie :-)
I've installed keystone via yo - but I've changed some files in folder node_modules/keystone - and now i want  to upload this to heroku - how can i upload all I've changed ( include files in this folder )? 

that's the reason i'm trying to install via github 

do you know better solution ?

**Comment by creynders** [comment]
Short answer:

- create a fork of keystone on github
- push your keystone changes to your fork
- and use the fork url as a dependency instead of the keystone package itself.

The long answer would take a couple of hours to write down. I strongly suggest you read up on node and its best practices.

Closing this, since it's not an issue and doesn't really relate to keystone.

**Comment by snowkeeper** [comment]
`npm install git-username/repo#branch`

If I wanted to install the latest keystone...
`npm install  keystonejs/keystone`

**Comment by betasap** [comment]
my problem:

 i've installed keystone via yo - all is ok - but i've made some changes in node_modules/keystone

and  when i upload project to heroku - they get new keystone instance form package.json 

how to solve it  ?

**Comment by morenoh149** [comment]
@betasap you must push your modified version of keystone to an accessible place on the web (use a github fork) then in your package.json specify your keystone dependency to point to that location.
See http://stackoverflow.com/a/23781107/630752
