### ISSUE TITLE
List view should show loading animation when a filter is added.

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#1313]
The lists view does not show a loading animation when a new filter is added in the admin UI. 

This is normally not an issue but when there is many item the request takes a while and there is no indication to the users that the filter has been successfully applied.

**Comment by singhArmani** [comment]
This issue seems to be resolved.
![filter-loading](https://user-images.githubusercontent.com/11068601/89758697-c0074500-db2b-11ea-8321-4222f838b0b6.gif)
