### ISSUE TITLE
GraphQl queries are taking a while to respond

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#1316]
I have a list with about 300 000 items, When I apply a filter to the list the graphql query takes up to 45 seconds to complete. 

The following query takes 45 seconds to respond
```
  allAgreementCountryGoods(first: 50, search: "", skip: 0,  where: {parentAgreement: {id: "5d02d8b3804f7e0c5df54df8"}}, orderBy: "hsCode_DESC") {
    id
  }
```

If I remove the `orderBy` argument the same query only takes 5 seconds to respond. 

If I remove the `where` clause the query only takes 1 second to respond.

The combination of the two arguments is whats causing the issue. This is probably related to MongoDBs aggregate functionality.

**Comment by w01fgang** [comment]
@SeanDoyleGit do you have indexes for fields in `where` and `orderBy`?

**Comment by molomby** [comment]
Sounds like non-optimal indexing to me!

Closing due to age.
