### ISSUE TITLE
Couchdb / pouchdb ?

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#1317]
Just curious if any consideration has been give to using alternate db's like couchdb? The whole pouchdb / couchdb thing is really compelling for replication. I know express supports couch http://expressjs.com/guide/database-integration.html#couchdb .

**Comment by morenoh149** [comment]
We've talked about supporting many databases in the past as a nice to have, but not a priority. A lot of it hinges on the fact we depend on mongoose for object modeling. See this discussion https://github.com/keystonejs/keystone/issues/838 so it's not enough that express supports couchDB we'll also need an ORM of sorts that can abstract that concern away.
