### ISSUE TITLE
Can Select multiple?

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1318]
Hi, I tried to have multiple Select Field in admin UI but failed. 

I tried to add ```multiple: true```, or ```many: true``` to my ```type: Types.Select``` model fields.

Is multiple Select allowed in Admin UI?

**Comment by creynders** [comment]
@arthurtalkgoal I don't think that's supported ATM. Closing this as a duplicate of #12

**Comment by akoesnan** [comment]
@creynders  do you know what is needed to support hits?

**Comment by morenoh149** [comment]
@akoesnan we need support for user defined fieldTypes. We're not there yet. If you'd like to join our slack to discuss let me know.

**Comment by akoesnan** [comment]
@morenoh149  What is the slack for keystonejs?

**Comment by morenoh149** [comment]
@akoesnan https://keystonejs.slack.com/ pm me your email and I'll add you
