### ISSUE TITLE
Admin UI New User - Errors reset the form, no check for unique email

### ISSUE THREAD

**Issue by tylkomat** [keystonejs/keystone#1320]
When I create a new User using the Admin UI and there is an error, like wrong email address, or not matching passwords. The form is reset, except for the email address.

Probably only wrong values and the password should be reset.

Additionally there is no check if the email address is unique. I can basically create 2 times the same User.

**Comment by morenoh149** [comment]
For uniqueness use a Mongo unique index

**Comment by tylkomat** [comment]
Ah I see now, this issue should probably go into the generator

**Comment by morenoh149** [comment]
yep on it (sorta lol)
