### ISSUE TITLE
Additional operations after remove

### ISSUE THREAD

**Issue by kommancs96** [keystonejs/keystone#1322]
I've done a lot of research, but I can't figure out how could I do some operations after a record is deleted in the admin UI. I'm looking for something like this:
```javascript
var callback = function(err,item){
        //Do something with item 
}
var Post = keystone.list("Post");
Post.add({
        onRemove: callback
});
```
Then callback would be called when I push the delete button in the UI.

**Comment by morenoh149** [comment]
http://mongoosejs.com/docs/middleware.html did you try `post remove` ?

**Comment by kommancs96** [comment]
Thank You, I could solve my problem using that.
