### ISSUE TITLE
Tags like creation of items from Type.Relationship

### ISSUE THREAD

**Issue by gaurav21r** [keystonejs/keystone#1324]
First of Keystone is truly FAN-tastic. I can't believe how fast I'm building website backends :+1: :+1: :+1: !

What would a very basic requirement for most CMSs is the ability to add **tags**. I was a little shocked that no one else had raised this point (or if it has been implemented / raised before, my apologies)

The difference between Tags & Categories from a UX point of view is that, while in **Edit Post** one can create new tags simply by typing them and ending with comma. Whereas one would need to already create a category somewhere else before it could be added to the post.

I think its a very basic requirement and the answer lies in changing `types\relationship\RelationshipField.js` but since I'm not fluent in React I can't submit a PR!

For any reference implementation one can consult any CMS including **WordPress** and **Ghost**.  

Generalising this, what I mean to say is that for one to many relationships, the entity that is multiple (Tags) can be created from the screen where the single entity is created (Create Post)

Your thoughts @JedWatson ?

**Comment by albertogasparin** [comment]
I think this is a behaviour similar to #95

**Comment by milosdakic** [comment]
+1

**Comment by jossmac** [comment]
Closing in favour of #95
