### ISSUE TITLE
Item view is broken with switch from jade to react

### ISSUE THREAD

**Issue by lojack** [keystonejs/keystone#1327]
Currently using master. I get an error for every admin page, and the Item view doesn't display properly. Looks like its because LocalFilesField.js is requiring `bytes`, which doesn't seem to be available. If I remove traces of this library everything seems to work fine.

Screenshot attached.

![screen shot 2015-04-22 at 12 50 27 pm](https://cloud.githubusercontent.com/assets/180470/7280123/c9d16208-e8ee-11e4-9a1d-ad3f59135bc4.png)

**Comment by morenoh149** [comment]
sounds like all you've got to do is add `bytes` to the package.json dependencies

**Comment by GlennGeenen** [comment]
I have the same issue, installing bytes doesn't change anything.

**Comment by creynders** [comment]
see #1332, should be fixed now. And is related/duplicate anyway, so closing this. If the problem _is_ unrelated or persistent, feel free to re-open.
