### ISSUE TITLE
Does the keystone editor supports storage the current edit state?

### ISSUE THREAD

**Issue by janryWang** [keystonejs/keystone#1328]

**Comment by creynders** [comment]
You mean in local storage? I.e. if you close the browser when editing a document and return to it, it will show the modified document? If so, no, that's not implemented.

**Comment by drlogout** [comment]
You can use the autosave plugin http://www.tinymce.com/wiki.php/Plugin:autosave

Add 
```
'wysiwyg additional plugins': 'autosave'
```
to the object you pass to keystone.init() and in the editor under "File" you will find "Restore last draft"

**Comment by dcousens** [comment]
@janryWang I believe this question was answered, re-open if you have any further questions.

**Comment by janryWang** [comment]
Thanks @drlogout
