### ISSUE TITLE
Relationship field not shown during initial object creation

### ISSUE THREAD

**Issue by alsoicode** [keystonejs/keystone#1329]
I have two models:

    // JobCategory.js
    
    var keystone = require('keystone'),
        Types = keystone.Field.Types;
    
    
    var JobCategory = new keystone.List('JobCategory', {
        autokey: {
            from: 'name',
            path: 'slug',
            unique: true
        },
        defaultColumns: 'name, active',
        defaultSort: 'sortOrder',
        label: 'Job Category',
        plural: 'Job Categories',
        sortable: true
    });
    
    JobCategory.add({
        name: {
            type: String,
            required: true
        },
        active: {
            type: Boolean
        }
    });
    
    JobCategory.relationship({
        path: 'jobs',
        ref: 'Job',
        refPath: 'category'
    });
    JobCategory.register();
    
    
    // Job
    var keystone = require('keystone'),
        Types = keystone.Field.Types;
    
    
    var Job = new keystone.List('Job', {
        autokey: {
            from: 'title',
            path: 'slug',
            unique: true
        },
        defaultSort: '-createdAt',
        drilldown: 'category',
        searchFields: 'title category',
        track: true
    });
    
    Job.add({
        category: {
            type: Types.Relationship,
            intial: true,
            ref: 'JobCategory'
        },
        title: {
            type: String,
            initial: true,
            required: true
        },
        description: {
            type: Types.Markdown,
            initial: true,
            toolbarOptions: {
                hiddenButtons: 'Code'
            }
        },
        active: {
            type: Boolean
        }
    });
    
    Job.register();

When creating a new `Job` record, the `category` field is not visible until after the record has been created. It's only visible when editing. What am I missing?

**Comment by webteckie** [comment]
@alsoicode you have a typo in the category field.  Should be "initial" not "intial".

**Comment by webteckie** [comment]
You didn't see any error messages anywhere about this syntax error?

**Comment by alsoicode** [comment]
Oh for shit's sake. Thank you very much for pointing that out. No, I wasn't receiving any syntax errors, but the problem is fixed.
