### ISSUE TITLE
specify the pages to display banner

### ISSUE THREAD

**Issue by jazz-ik** [keystonejs/keystone#1331]
Hi everyone!

Is there way to set parameter for displaying banner on specify page? For example: I have one banner and I want display him at main page and at contacts page. Other banner I want to display only main page.

I can't understand which type of field I should add to model for it?

**Comment by JedWatson** [comment]
@jazz-ik thanks for getting involved :)

This is actually a better question for our google group, we try and keep github for discussing issues and development of keystone itself. There are a number of people there who I'm sure would be happy to share ideas with you.
