### ISSUE TITLE
Admin UI displayed mailid/password combination fails

### ISSUE THREAD

**Issue by mohanr** [keystonejs/keystone#1333]
Using it for the first time. The CMS connects to mongodb. I am using the mailid/password combination displayed in the 'Welcome' page. But it fails to login to the Admin UI.

**Comment by creynders** [comment]
Have you checked the DB whether the doc exists in the `users` collection? ATM the e-mail field is case-sensitive (it has been fixed in the mean time, but not released yet) so make sure you type it in exactly as written down.

**Comment by mohanr** [comment]
> show dbs
leanportal  0.078GB
local       0.078GB
> use leanportal
switched to db leanportal
> show collections
app_updates
leanportals
system.indexes

**Comment by creynders** [comment]
It appears something went wrong when installing, could you show us the mongo uri you use?

**Comment by mohanr** [comment]
It is the default in localhost. Port is 49152.

**Comment by creynders** [comment]
Yeah, I meant the exact MONGO_URI string, but nvm it probably has nothing to with that. Do you use the  "model prefix" configuration setting? 
The reason why I ask is that apparently it created a `leanportal` collection (?) inside your `leanportal` database, which it shouldn't. You should have something like this:

```sh
> show collections
app_updates
users
posts
system.indexes
```

**Comment by mohanr** [comment]
I don't use 'model prefix' setting. Should I be ? I have directly installed it without changing anything like that.

**Comment by mohanr** [comment]
I think I could install it again. Clean mongo and install again ?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
