### ISSUE TITLE
Elemental Admin UI 

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1335]
@jossmac and I are working on a new React UI framework called Elemental (like react-bootstrap or material-ui but in Keystone's style and with our own components)

The framework is largely being designed around the requirements of Keystone's Admin UI and projects we build _with_ Keystone. It's a building block in our goal of making rich app development simpler.

The first step is to get Elemental packaged and published independently in its own repo with examples and docs (currently underway), once this is at least partly done we'll be replacing the current Bootstrap CSS framework in Keystone's Admin UI with Elemental's. Finally we'll replace the ad-hoc React components in the UI.

More updates to come as we progress.

**Comment by mobinni** [comment]
I there an update on this yet? Me and my team of developers are currently waiting on this in release 0.4.0

**Comment by morenoh149** [comment]
@mobinni get that team of devs into the slack channel and help us out.

**Comment by JedWatson** [comment]
Ready to close this issue now; @jossmac has done the migration in the `elemental-integration` branch.

There's still work to do to get that branch release-ready, but I'm going to start tracking individual issues for the remaining tasks as we get closer.

**Comment by SharadKumar** [comment]
Nice!

**Comment by mobinni** [comment]
Elemental baby

**Comment by jossmac** [comment]
This probably belongs here: http://elemental-ui.com

**Comment by stosorio** [comment]
Really looking forward to this!
Does [this file](https://github.com/elementalui/elemental/blob/master/less/variables.less) mean that it will be reasonably easy to theme the admin area? This would be amazing :+1:

**Comment by jossmac** [comment]
Keystone has always been [themeable](https://github.com/keystonejs/keystone/blob/master/admin/public/styles/theme/variables.less) :)

But yes, we intend to simplify and document the process
