### ISSUE TITLE
Relationship Lists displaying 'Stale' Data in Admin UI

### ISSUE THREAD

**Issue by jimulle** [keystonejs/keystone#1337]
I have a list of tags which is shared by multiple post types. For some reason when creating/editing items of both post types in the Admin UI, I am seeing only a stale list of tags (I have added/removed tags and I still seem to be seeing an old list). The tags list out properly on the front end, but I can't assign newly created tags to any of my posts. Am I missing something that should trigger this list to refresh or a point at which the relationship list is becoming cached?

**Comment by morenoh149** [comment]
have you saved the updated document to mongodb?

**Comment by jimulle** [comment]
I think the issue is in the 'async' calls that populate the 'relationships'. I am seeing the same issue in the author fields.

**Comment by jimulle** [comment]
This issue seems to have resolved itself by updating Keystone.
