### ISSUE TITLE
Keystone data not passed to the template (handlebar) when there are a lot of traffic

### ISSUE THREAD

**Issue by dtuyenle** [keystonejs/keystone#1338]
We are having an issue with data not passed to the template when a lot of requests hitting keystone. I am not sure if anyone ever experienced anything like this or not ?

And also i am not sure if this is a keystone thing or nodejs thing. We techcanilly having 8 keystone instances with 1 mongodb behind each one and all of them behind a load balancer but still we seeing the issue.

Please help

**Comment by dtuyenle** [comment]
And this is what i see in the log 

before
5
after
5
before
5
after
5
[90mGET /h/early-hiv-rash [32m200 [90m152ms[0m
[90mGET /h/early-hiv-rash [36m304 [90m131ms[0m

The before after are just console log to check the data before rendering the view. And looks like the data is populated just fine from the database. Does this mean 2 requests hit keystone at the same time ?

**Comment by dtuyenle** [comment]
Looks like the data is not passed into the views. That's what we found out so far.

**Comment by morenoh149** [comment]
try https://gitter.im/keystonejs/keystone for this kind of help
