### ISSUE TITLE
Install Semantic-UI or Materialize and uninstall Bootstrap

### ISSUE THREAD

**Issue by msintaha** [keystonejs/keystone#1342]
I want to customize the CSS of the whole site and am interested in using the above mentioned UIs instead of Bootstrap. Even if i delete bootstrap folder, the design still remains. How do I replace bootstrap with these UIs and also tweak css of all the templates as well?

**Comment by medv** [comment]
After deleting bootstrap folder did you recompile style.min.css? Should be as easy as making a change to style.css

**Comment by JedWatson** [comment]
@msintaha are you talking about the Admin UI or your project (i.e that you created with the yeoman generator)

**Comment by msintaha** [comment]
I'm using the project created with yeoman generator. I deleted the bootstrap folders in the public folder and pasted the less files of semantic, but the page us just generated with no styling. I even wrote the dependencies of semantic-ui-less in the package.json, but the project still can't identify my semantic files. And yes I figured out the normal customized css but I want the whole css UI of semantic

**Comment by JedWatson** [comment]
@msintaha If I understand you correctly, you'll also need to pull the new stylesheets into your website. Check out the base jade template (or whichever template you selected) - it'll be pulling in a .css file that you need to replace to see the new styles.

This is more of a "using keystone" issue so please post on our google groups if you still need help - we just use github issues for tracking the development of keystone itself.

Thanks!
