### ISSUE TITLE
LocalFile images

### ISSUE THREAD

**Issue by razb** [keystonejs/keystone#1343]
I've been reading some of the comments around using Local storage for files instead of CLoudinary. Is this functionality usable in Keystone 0.3.8?

I can obviously change the model for posts to use local files, and that allows me to upload files successfully.

It does break the views though, so I guess my question is whether it's actually usable for images. Would all the cloudinary methods for resizing have to be recreated to get local image functionality?

**Comment by morenoh149** [comment]
The functionality is in 0.3.8

Should be useable for images. The cloudinary methods are not available, but you'd have local image functionality. 

If you do this you could try to get feature parity with cloudinary using stuff like https://www.npmjs.com/package/resize weening ourselves off cloudinary is something I'd love to see in keystone.

**Comment by razb** [comment]
Thanks for the link. I think the best approach for my needs is to create 2 copies of each uploaded image.  A thumbnail of 300 x300 and a full size image with a maximum width of 1280. That way I can handle the rest with CSS.
