### ISSUE TITLE
Closing script tag in content causes rendering issue in admin panel list view

### ISSUE THREAD

**Issue by alobodig** [keystonejs/keystone#1348]
Including a closing `</script>` tag anywhere in the content of a text field breaks the list view. 

![screen shot 2015-04-27 at 2 53 11 pm](https://cloud.githubusercontent.com/assets/1733093/7355194/5ac870f0-ecee-11e4-94d8-18587599233a.png)

**Comment by lojack** [comment]
Could you try a newer version of keystone? #1250 was for a similar issue on the detail view, which may have also fixed this for you.

**Comment by JedWatson** [comment]
Actually, I'm working on a resolution for this in the `react-list` branch _right now_ with @pieer and @leo7568. The issue will be fixed once we're loading the list data from a JSON API call rather than generating JSON into `<script>` tags in the jade template.

**Comment by mxstbr** [comment]
I'm 99% sure this is fixed due to age, so I'll close it. Let me know if this bug still exists!
