### ISSUE TITLE
Automatic Datestamp field

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#135]
New field type that watches for changes in other fields and updates a timestamp when they occur.

Would automate tracking changes to other fields, e.g.

* setting `subscribedAt` when a `subscribed` boolean changes to true
* setting `unsubscribedAt` when a `subscribed` boolean changes from true to false
* setting `modifiedAt` when any field is changed
* setting `passwordLastChangedAt` when a password is changed

... etc.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/automatic-datestamp-field)!
