### ISSUE TITLE
Single Sign on

### ISSUE THREAD

**Issue by razb** [keystonejs/keystone#1350]
Trying to auto-create users and initiate sessions by passing authenticated user names via http headers. If I pass in the user name as REMOTE_USER, how would I read that? In the PHP world, that would be by reading $_SERVER['REMOTE_USER'] or in rails, request.headers. Whats's the node/express way to accomplish this?

**Comment by morenoh149** [comment]
http://devdocs.io/node/http#http_message_headers my guess

**Comment by JedWatson** [comment]
correct, you should be able to read it from `res.headers` in a route handler function (which is express middleware)
