### ISSUE TITLE
Auto complete on relationship fields

### ISSUE THREAD

**Issue by razb** [keystonejs/keystone#1351]
Still going through the docs, and really liking what I've seen so far. This is an awesome project. On to my latest challenge. I'm trying to get forms with relationship fields to autocomplete like they do in the AdminUI. I've defined the skills as utilized in the mentor/mentoring views as relationships to the Urer model. This allows me to define new skills and have them available for selection in the member/user forms in the AdminUI.

I've tried to make them also available in the me view, but no success. The field is defined in the appropriate models as far as I can tell since it does work correctly in the adminUI.

**Comment by JedWatson** [comment]
You'd have to build this yourself in the front-end using React or a component like selectize (and expose an API endpoint to pull data from)

You should be able to look at the way the Admin UI does it and replicate the functionality without too much difficulty, or ask the google groups / gitter chat for an example.

We're working on a new set of Admin UI components that you'll be able to simply drop into your own front-end to replicate the same functionality that's in the Admin UI, which will be awesome when it lands! No timeline yet, but it's on our roadmap for 1.0.0

**Comment by JedWatson** [comment]
p.s

> This is an awesome project.

Thanks :smile:
