### ISSUE TITLE
Types.Select with comma in text getting cut off

### ISSUE THREAD

**Issue by WingedToaster** [keystonejs/keystone#1352]
I have found a bug where if I put a comma in the value or the label in the options of a Types.Select in the model the text after the comma gets cut off. I have tried both an array of string and an array of dictionaries. 

		income: {
			type: Types.Select,
			options: [
				{value: 'Less than $20,000', label: 'Less than $20,000'},
				{value: '$20,000 to $49,999', label: '$20,000 to $49,999'},
				{value: '$50,000 to $79,999', label: '$50,000 to $79,999'},
				{value: '$80,000 to $99,999', label: '$80,000 to $99,999'},
				{value: '$100,000 to $149,999', label: '$100,000 to $149,999'},
				{value: '$150,000 or more', label: '$150,000 or more'}
			]
		},

![select-bug-example-1](https://cloud.githubusercontent.com/assets/4502315/7363156/2bc84724-ed3b-11e4-9284-9736507657b7.png)
![select-bug-example-2](https://cloud.githubusercontent.com/assets/4502315/7363157/2bd492d6-ed3b-11e4-9447-8938ef395d8e.png)

**Comment by JedWatson** [comment]
Thanks for the report @WingedToaster, that looks like a bug in the `react-select

**Comment by JedWatson** [comment]
Thanks for the report @WingedToaster, that looks like a bug in the `react-select` component. I'll check it out.

**Comment by WingedToaster** [comment]
It appears the value is correct in the respective hidden input field, so it's just a display issue. 

Should I open an issue on <code>react-select</code> component instead and close this one?

**Comment by JedWatson** [comment]
Yes please :)

**Comment by WingedToaster** [comment]
Copied to <a href="https://github.com/JedWatson/react-select/issues/149">Issue #149</a> on the <code>react-select</code> component github.

**Comment by WingedToaster** [comment]
Created <a href="https://github.com/keystonejs/keystone/pull/1442">PR #1442</a> as a work around to this issue.
