### ISSUE TITLE
Convert the List view from Jade to React

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1355]
Currently working on this with @pieer and @leo7568 in the `react-list` branch.

Moving ahead with converting the Admin UI to React, one of the next goals is to convert the List view from Jade to React.

There are several things that need to be done in preparation:

- [x] Implement an additional List script (for now, filters will remain in Jade - it's our next target!)
- [x] Set up the Field Type Columns infrastructure
- [ ] Load the list results from a JSON API, will also fix #1348
- [ ] Turn the Pagination and Header into React components
- [ ] Re-implement the Sortable and Delete functionality in the React Table

Then we need to port all the Field Types to React column classes:
- [x] Text (needs to support being the name field, and linking to the item)
- [ ] Name (needs to support being the name field, and linking to the item)
- [ ] Email
- [ ] Boolean
- [ ] Key
- [ ] Textarea
- [ ] File/s (all providers)
- [ ] CloudinaryImage/s
- [ ] Relationships (including subfield handling)
- [ ] HTML
- [ ] Markdown
- [ ] Code
- [ ] Color
- [ ] Date / Datetime
- [ ] Date / String / Number Array
- [ ] Embedly
- [ ] Geopoint
- [ ] Location
- [ ] Money
- [ ] Password
- [ ] Select
- [ ] URL

**Comment by mxstbr** [comment]
Closing this as it's done.
