### ISSUE TITLE
Relationship Fields ref as basic Array not working

### ISSUE THREAD

**Issue by stursby** [keystonejs/keystone#1358]
So in my Model file, I have the following line:

```javascript
categories: { type: Types.Relationship, ref: ['one', 'two', 'three'], many: true },
```
Per the [docs](http://keystonejs.com/docs/database/#relationship-fields), it seems like I can set the `ref` to either __ObjectID field or array__, however, I'm getting the following error:

```javascript
Unknown keystone list ["one","two","three"]
```

Am I missing something? Or do I have to set the `ref` to another Model?

**Comment by milosdakic** [comment]
Once this is fixed, would something like the following work?

```javascript
value: { type: Types.Relationship, ref: ['Post', 'Page', 'Category', 'Media'] },
```

Where the ref are models within Keystone.

**Comment by stursby** [comment]
@milosdakic That currently works if I use an array of Keystone Lists, what I'm looking for is the ability to have a `many: true` / multiselect from a plain Array.

**Comment by milosdakic** [comment]
@stursby aren't you after `Types.Select` then?

**Comment by stursby** [comment]
@milosdakic Not necessarily. I'd like to select *multiple* values, whereas `Types.Select` only lets you select one value.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted.

I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/new-field-type-multiselect!
