### ISSUE TITLE
Add min. password complexity options

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#136]
At the moment, password fields validate with any complexity / length.

We should create options on the password field to specify complexity, min. length, valid characters, etc. and enforce a reasonable default.

**Comment by foobar8675** [comment]
I'd like this feature as well.

**Comment by UrvashIBanthia** [comment]
I would like to contribute in this project. Can you please tell us where can I find its source code?

**Comment by mxstbr** [comment]
This would have to be added in `fields/types/password/PasswordType.js`, specifically the `validateInput` function in there!

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/add-min-password-complexity-options)!
