### ISSUE TITLE
Add stats to `createItems` calls

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#137]
Related to #135.

> The v4 implementation [...] did some nice stats collection too, which we logged out to the console when it was executed as part of an upgrade script: https://github.com/keystonejs/keystone-classic/blob/0caf792a89e46853aeffb5e23444f436423cf2f3/lib/core/createItems.js#L326

_- @JedWatson_

**Comment by MadeByMike** [comment]
Closing as there is no intention to add to the `createItems` API see: https://github.com/keystonejs/keystone/issues/144
