### ISSUE TITLE
Implement a list history plugin

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#137]
As suggested in #135, would be enabled with a list option and could be based on https://github.com/rossan/mongoose-history

**Comment by JedWatson** [comment]
Finally! Just landed this. Needs docs, but you set the list option `history: true` to enable it.

**Comment by britztopher** [comment]
Wooo hooo!!!

**Comment by A7bert** [comment]
Hi, the history plugin is awesome. Is there a way to display the info to the admin UI or maybe to the web pages? At the moment, I have to fetch data directly from mongodb via node js.
