### ISSUE TITLE
Select uses addEventListener/removeEventListener, which don't exist in IE8

### ISSUE THREAD

**Issue by StefanBilliet** [keystonejs/keystone#1372]
Hi

In Select.js->componentWillMount(), you add/remove event listeners for when clicking outside the element. Apparently, IE8 doesn't support addEventListener/removeEventListener; it only supports attachEvent/detachEvent (the name of the click event is also different).
It's fairly simple to fix: https://github.com/StefanBilliet/react-select/commit/f0b004833b9f5a7545773425f36d28e4eea84ef5
My question is, are you open to these kinds of fixes?

With kind regards
Stefan Billiet

**Comment by morenoh149** [comment]
:/ do we support ie8. Not sure.

**Comment by StefanBilliet** [comment]
Uh, I think I made a mistake. I wanted to to log an issue in the react-select repo; I don't really understand how I wound up making one here. Sorry -_-
