### ISSUE TITLE
Cors

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#1374]
So, I've read through the cors threads and see it is now baked into Keystone. I'm writing a mobile hybrid app with ionic that talks to keystone for some data. I've tried adding
```
 app.all('/api/events', keystone.middleware.cors, routes.api.events);
```
or
```
 app.all('/api/*', keystone.middleware.cors, routes.api.events);
```
Restart and I still get the cors error. Is there anything else I need to do? The routes work fine otherwise.

Thanks.

**Comment by mikeblakeney** [comment]
I ran into the same thing.  Did some digging and found the middleware file in the source: https://github.com/keystonejs/keystone/blob/master/lib/middleware/cors.js

Check out lines 21 and 23.  Basically if the origin is set to true then allow all ( * ).  So in my keystone.js file I added:
keystone.set('cors allow origin', true);  

Hope this helps!

**Comment by xianlin** [comment]
Basically you need to do the above 2 steps:

1. In your middleware `index.js` 
```
app.all('/api*', keystone.middleware.cors);
```

2. In your `keystone.js`
```
keystone.set('cors allow origin', true);
```

Then you will be able to see the correct CORS header response
```
Access-Control-Allow-Headers:Content-Type, Authorization
Access-Control-Allow-Methods:GET,PUT,POST,DELETE
Access-Control-Allow-Origin:*
```

**Comment by morenoh149** [comment]
solved

**Comment by useralive003** [comment]
var express = require('express'); 
    var app = express(); 
    var bodyParser = require('body-parser');
    var multer = require('multer');

    app.use(function(req, res, next) { //allow cross origin requests
        res.setHeader("Access-Control-Allow-Methods", "POST, PUT, OPTIONS, DELETE, GET");
        res.header("Access-Control-Allow-Origin", "http://localhost");
        res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
        next();
    });

    /** Serving from the same express Server
    No cors required */
    app.use(express.static('../client'));
    app.use(bodyParser.json());  

    var storage = multer.diskStorage({ //multers disk storage settings
        destination: function (req, file, cb) {
			//console.log(file);
            cb(null, './uploads/');
        },
        filename: function (req, file, cb) {
            var datetimestamp = Date.now();
            cb(null, file.fieldname + '-' + datetimestamp + '.' + file.originalname.split('.')[file.originalname.split('.').length -1]);
        }
    });

    var upload = multer({ //multer settings
                    storage: storage
                }).single('file');

    /** API path that will upload the files */
    app.post('/upload', function(req, res) {
		
		console.log(req.body);
		
        upload(req,res,function(err){
            if(err){
                 res.json({error_code:1,err_desc:err});
                 return;
            }
			
             res.json({error_code:0,err_desc:null});
        });
    });

    app.listen('3000', function(){
        console.log('running on 3000...');
    });

**Comment by tomheathershub** [comment]
I have the following set in keystone.js

`keystone.set('cors allow origin', true);
keystone.set('cors allow methods', true);
keystone.set('cors allow headers', true);`

The correct CORS header response is correct on my local environment: 
`Access-Control-Allow-Headers:true
Access-Control-Allow-Methods:true
Access-Control-Allow-Origin:*`

However once deployed to live, these don't exist... any suggestions? 

You can see the ajax request here: http://www.tomheather.co.uk - request URL: http://cms.tomheather.co.uk/page/home

**Comment by asliwinski** [comment]
@tomheathershub http://cms.tomheather.co.uk/page/home responds with 503: Service Unavailable. Nothing to do with CORS.
