### ISSUE TITLE
Types.DateTime more options

### ISSUE THREAD

**Issue by milosdakic** [keystonejs/keystone#1375]
Add new options to DateTime type for hiding or showing date or time.

```javascript
{ type: Types.DateTime, date: false }
{ type: Types.DateTime, time: false }
```

**Comment by ttsirkia** [comment]
Because these use JavaScript `Date` objects, there will be always the date part as well. Without adding new options, you can achieve the same result by giving an own default format which includes only date or time part.

**Comment by mxstbr** [comment]
There is `Dates.Date`, which replaces the `time: false` options, but we don't currently have a `Types.Time` field – I'll close this issue for now, but feel free to respond with specific use cases for a `Time` field and we'll think about adding it!
