### ISSUE TITLE
Ensure proper Mobile support in the Admin UI

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#1376]
Hi everyone,

I'm doing a bit of tidying up and was wondering how many of you, or your clients, actually use the admin interface on mobile devices?

I'm talking about phones in particular, like 480px and below.

Thanks!

**Comment by morenoh149** [comment]
I don't think any of ours do. But letting the admin panel be usable on mobile should be a goal for the project.

**Comment by JedWatson** [comment]
I say mobile support is a priority for the Admin UI. While there are some field types (e.g WYSIWYG) and workflows that would be compromised, we should absolutely design for the best mobile UX we can.

**Comment by jamlen** [comment]
I (try) to use the Admin UI from a mobile... mostly to "unpublish" an article that some ~~idiot~~ other person published when they shouldn't have!

**Comment by JedWatson** [comment]
I think we got a definitive "yes" on this one @jossmac, let's make sure we nail it for the Elemental release.

**Comment by jossmac** [comment]
Thanks for the input all. Some things of note for v0.4.0:
- mobile specific navigation bar/panel allows two-tap access to all lists
- optimised list filters based on various breakpoints 
- horizontally scrollable list table on mobile
- elemental does a good job of handling mobile forms, so not much to do on the item view
- many contextual copy changes based on breakpoint

Closing for now, but will keep an eye on this going forward.
