### ISSUE TITLE
Installation issue on ubuntu vps

### ISSUE THREAD

**Issue by JasoonS** [keystonejs/keystone#1379]
when I run <code>yo keystone</code> I get the following errors half way through the install:
<pre><code>
create public/styles/site/variables.less
npm WARN locking Error: EACCES, open '/home/keystone/.npm/_locks/underscore-8283d615439c13a3.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/keystone/.npm/_locks/underscore-8283d615439c13a3.lock failed { [Error: EACCES, open '/home/keystone/.npm/_locks/underscore-8283d615439c13a3.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/keystone/.npm/_locks/underscore-8283d615439c13a3.lock' }
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /home/keystone/sacmmt.com/sacmmt/node_modules/underscore, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/keystone/.npm/_locks/async-e5753c1ee18c9fc1.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/keystone/.npm/_locks/async-e5753c1ee18c9fc1.lock failed { [Error: EACCES, open '/home/keystone/.npm/_locks/async-e5753c1ee18c9fc1.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/keystone/.npm/_locks/async-e5753c1ee18c9fc1.lock' }
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /home/keystone/sacmmt.com/sacmmt/node_modules/async, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/keystone/.npm/_locks/keystone-97ab5f6ecfab21b2.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/keystone/.npm/_locks/keystone-97ab5f6ecfab21b2.lock failed { [Error: EACCES, open '/home/keystone/.npm/_locks/keystone-97ab5f6ecfab21b2.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/keystone/.npm/_locks/keystone-97ab5f6ecfab21b2.lock' }
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /home/keystone/sacmmt.com/sacmmt/node_modules/keystone, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/keystone/.npm/_locks/dotenv-7165615045acdf4a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/keystone/.npm/_locks/dotenv-7165615045acdf4a.lock failed { [Error: EACCES, open '/home/keystone/.npm/_locks/dotenv-7165615045acdf4a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/keystone/.npm/_locks/dotenv-7165615045acdf4a.lock' }
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /home/keystone/sacmmt.com/sacmmt/node_modules/dotenv, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keystone/sacmmt.com/sacmmt/npm-debug.log
</code></pre>

And when I run <code>node keystone</code> I get:
<pre><code>module.js:338
    throw err;
          ^
Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/keystone/sacmmt.com/sacmmt/keystone.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
</code></pre>

(I have created a .env file, so I am not sure what the issue is. I got this running perfectly on my local ubuntu machine)

Help much appreciated!!

**Comment by dcousens** [comment]
`npm install dotenv`?

**Comment by mldangelo** [comment]
It looks like your cache might contain some files which are not writeable by your current user.
If you can install other packages as non-root, then try removing the bad cache entries. 
> npm cache clean

And then reinstall the generator.
> npm install -g generator-keystone

If that doesn't work, try running 
> sudo npm install -g generator-keystone

and then regenerate your project.

**Comment by JasoonS** [comment]
Yes it was an issue with permissions but I didn't work out what exactly. I tried variations of adding sudo or not, and it was giving me issues. I eventually redid everything and it worked.
