### ISSUE TITLE
Implement Flux using Alt

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#1383]
Last year, during the initial discussions or the Admin UI rewrite in React I raised a question regarding the possibility of using flux. This was back in August, so Facebook had just recently open-sourced [flux](https://github.com/facebook/flux), and while it look promising it seemed like it wasn't the right point in time for the discussion.

Now that we're in the final stretch of the conversion to React and the use of the flux pattern is a more widely accept practice, I think it's time to rehash the flux discussion.

Though during the original discussion there seemed to be an inclination to use flux, I guess my initial question to @JedWatson, @dcousens, @jossmac and the rest of the contributors is: Are we still inclined to use the flux pattern in the new Admn UI?

Since Facebook's original flux library, a number of new and very interesting implementations have appeared. One that has particularly caught my attention is [Alt](https://github.com/goatslacker/alt). It is a well-written, unopinionated, actively maintained, pure flux implementation with a lot of very interesting features. I encourage everyone to check out their [repo](https://github.com/goatslacker/alt) and read about the all its cool features. It is written in ES6 and out of the box it include a number of very useful utilities for:

- atomic transactions,
- immutability,
- isomorphic rendering, and
- state rollback

... just to name a few. These are all features I've found myself using over and over again while building be React/Flux apps.

This is obviously not the only flux implementation in the wild, so if Alt is not something We want to consider for Kestone, I hope this issue, at the very least, resparks the discussion of using flux in our Admin UI.

**Comment by morenoh149** [comment]
Alt looks good. But I'll just have to plug our implementation of Flux [Thundercats](http://thundercats.js.org/) ⚡️🐯

**Comment by JohnnyEstilles** [comment]
@morenoh149, Thundercats looks very interesting. I like the use of RxJS observables. Is it production ready?

**Comment by morenoh149** [comment]
@JohnnyEstilles I'd say no. We'll be using it in a major site soon, but I can't say anyone has put serious load on it yet.

**Comment by JohnnyEstilles** [comment]
I assume we'll be using @JedWatson's [Store Prototype](https://github.com/JedWatson/store-prototype) implementation. Closing this issue.
