### ISSUE TITLE
Relative path not resolving for react.less when react-select is a top level dependency 

### ISSUE THREAD

**Issue by d4ncer** [keystonejs/keystone#1384]
My Keystone application uses react-select as a dependency for a client-side React + Flux micro-application, and I ran into an issue where react.less was unable to find react-select's LESS file to import, since npm install does not recursively install react-select into Keystone's node_modules folder as it is already a top-level dependency (see [here](https://github.com/npm/npm/issues/1341), this is a documented issue).

```
File Error thrown for request: /keystone/styles/keystone.min.css
{ [Error: '../../../node_modules/react-select/less/select.less' wasn't found. Tried - /mnt/data/2/node_modules/keystone/node_modules/react-select/less/select.less,../../../node_modules/react-select/less/select.less]
  type: 'File',
  filename: '/mnt/data/2/node_modules/keystone/public/styles/react/react.less',
  index: 1419,
  line: 36,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract:
   [ '',
     '@import "../../../node_modules/react-select/less/select.less";',
     '@import "../../../fields/types/markdown/less/bootstrap-markdown.less";' ],
  message: '\'../../../node_modules/react-select/less/select.less\' wasn\'t found. Tried - /mnt/data/2/node_modules/keystone/node_modules/react-select/less/select.less,../../../node_modules/react-select/less/select.less',
  stack: undefined }
  LESS File error : '../../../node_modules/react-select/less/select.less' wasn't found. Tried - /mnt/data/2/node_modules/keystone/node_modules/react-select/less/select.less,../../../node_modules/react-select/less/select.less
  LESS File : /mnt/data/2/node_modules/keystone/public/styles/react/react.less 36:0
```

As a hack-around I forked Keystone, and fixed the relative path to point to the main node_modules folder. I'm curious if there is a better way (I'm not well versed in using LESS, but maybe a try catch with an absolute path to the root folder might be a solution).

**Comment by JedWatson** [comment]
I just found this today as well. What a pain... trying to work out how I can work around it, I might revert to a pre-built solution as a quick fix, because we're having other difficulties with the dynamic build in some situations as well.

Will post a proper fix soon.

**Comment by JedWatson** [comment]
Solved!
