### ISSUE TITLE
FieldType "plugins"

### ISSUE THREAD

**Issue by baseio** [keystonejs/keystone#1386]
Hi,

After a bit of fiddeling, I managed to create a new FieldType.

This is the route I took:

- Create the Type file at `node_modules/keystone/fields/types/{Fieldname}Type.js`
and add it to `node_modules/keystone/lib/fieldTypes.js`

- Create the Field file at `node_modules/keystone/fields/types/{Fieldname}Field.js`
and add it to `node_modules/keystone/admin/src/fields.js`

Question:
How can I store the new FieldType without touching the node_modules/keystone folder?
Maybe it could be possible to accomplish this making "plugins" ala:
Package your fieldType a new npm module (named like "keystone-fieldtype-fieldname"),
npm install it, and let keystone know about it through Keystone.init()?

**Comment by morenoh149** [comment]
@baseio are on the slack? I feel like that's the ideal place to have future discussions like this.

**Comment by milosdakic** [comment]
+1 I just did this yesterday with two field types. Would love to take it out of the keystone module.

**Comment by porschuetz** [comment]
same issue. we decided not to touch the node_modules and overcomplicate things a bit on our side for it.

**Comment by snawbel** [comment]
To be able to `npm install keystone-field-mycustomfield` without touching the core would be a huge deal for Keystone. I'm currently starting several large:ish projects that will be powered by keystone and we will need to make several custom fields. Would be nice to join the slack to discuss these issues there.

**Comment by davibe** [comment]
Can you also have to 'custom field' code in your application and append it to keystone.Field.Types at runtime before starting keystone ?

**Comment by mzgol** [comment]
@morenoh149 I don't see any other issue about creating custom types, could this one be considered a feature request for that?

**Comment by kadosh1000** [comment]
currently working on an npm package that will make that whole process automatic. will post here when I'm done. guess in the next few days

**Comment by kadosh1000** [comment]
Hi I have published my npm package: 
https://github.com/kadosh1000/keystone-custom-fieldtypes

It copies your custom fieldTypes from a selected dir into the keystone's fields dir and registers it

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/fieldtype-plugins
