### ISSUE TITLE
`keystone.createItems` should validate data against the schema before insertion

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#139]
The GraphQL endpoints do this validation for us. Here, we are circumventing those checks and blindly pushing data into the database. We should be more strict about validating it before we do.

**Comment by JedWatson** [comment]
@gautamsi I was thinking we could come up with a package that contains similar functionality to keystone 4's `View`, especially to help with transitions from Keystone 4. It will hopefully be fairly simple now that everything's decoupled.

**Comment by gautamsi** [comment]
Working on it now, can you assign this issue to me.

**Comment by JedWatson** [comment]
@gautamsi thanks! assigned 👍

**Comment by gautamsi** [comment]
@JedWatson I have PR #1024 in which I have focused on view compatibility. but it seems it needs more than just view to implement full features of v4 view with backward compatibility. 

Should I create a separate PR for each of following or just update PR #1024 with additional features? All of them related to v4 comatibility

1. keystone.updateHandler
2.  route importer
3. keystone.populaterelated + list model schema methods (populateRelated and getRelated)
4. List.updateItem

I am inclined to add another package `v4-compat` (or suggest better name) which wraps Keystone and List with helper methods to help upgrade in place for v4 project with minimal changes. This will obviously focused with mongoose adapter. to be included in pr #1024. I am planning to test this with `sydjs-site`.

thoughts

**Comment by MadeByMike** [comment]
Maybe solution is to remove createItems. Re-document the createItems\Initial data with `executeQuery`

**Comment by molomby** [comment]
Should be removed; see #1756.

**Comment by MadeByMike** [comment]
Closing issues related to `createItems` as we're not going to work on it further.
