### ISSUE TITLE
LocalFile Type href: backslashes on windows

### ISSUE THREAD

**Issue by tylkomat** [keystonejs/keystone#1390]
On windows the href path has backslashes instead of slashes. I tested with **LocalFile.**
```
thumbnail: {
    type: Types.LocalFile,
    dest: baseDir + '/data/thumbnails',
    prefix: '/thumb/',
    allowedTypes: [
        'image/jpeg', 'image/png', 'image/gif', 'image/svg+xml'
    ],
    filename: function(item, file) {
        return item.id + '.' + file.extension;
    },
    format: function(item, file) {
        return '<img src="' + file.href + '" style="max-width: 300px">';
    }
}
```
`{{ item.thumbnail.href }}` for example outputs `\thumb\5542306ff9800d1c23a3cf3b.png`

This happens because `path.join()` creates a platform specific path, but you want to create a URL path, string concatenation should be sufficient. Otherwise [url-join](https://www.npmjs.com/package/url-join) or [URIjs](https://www.npmjs.com/package/URIjs) are probably the packages to go for.

**Comment by JedWatson** [comment]
I created #1406 before I saw this issue, solved now.
