### ISSUE TITLE
Move the site / docs into its own repo

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1391]
Will clearly separate the docs / site issues from actual Keystone issues, make working with keystone lighter, and make working on the site simpler.

I'll set up the repo, move the code across, publish the gh-pages branch and move the domain. I'm going to fix up the publishing process at the same time, the current one's old and a pain to run.

If somebody could volunteer to transition all the open docs issues across to the new repo when it's ready, that would be great.

**Comment by JohnnyEstilles** [comment]
+1 ... This is a great idea! I have a question though. I intended to submit a PR to correct something in the docs today. Should I still submit or wait until the docs are migrated.

**Comment by Gouthamve** [comment]
+1 Managing docs will be easier. And I would love to migrate the issues.

We could just use this: https://github.com/google/github-issue-mover or I could do it manually.

**Comment by JedWatson** [comment]
Thanks @Gouthamve! Looks like that tool will do the trick nicely.

Feel free to submit today @JohnnyEstilles, I'll update this issue when I start migrating.

**Comment by JedWatson** [comment]
Closing this, the new repo has been created and the docs have been moved. We still need to transition the open issues for docs changes.
