### ISSUE TITLE
Can I re-yo the Enquiry model?

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1393]
Ooops, I haven't ```yo``` the Enquiry model when I created my keystone.

Can I rebuild the ```Enquiry``` using the keystone yo commands?

Thanks!

**Comment by medv** [comment]
I personally created a blank project for the purposes of carrying out my task, but also made a second project that has all sample work and comments included that I peek into for reference. This has been very helpful. On top of this, https://github.com/JedWatson/sydjs-site is a wealth of information.

Not exactly an answer to your question, but it is a question I had myself and this is how I approached it.

**Comment by arthurtalkgoal** [comment]
Hi @medv,

I got what you means, that can solve my problems too!   

Anyway, I think if the yo can do individual tasks, then it's cool.
