### ISSUE TITLE
[Question] Support for one to many relationships

### ISSUE THREAD

**Issue by tusharmath** [keystonejs/keystone#1394]
I want to create a `Doctor` list with some educational info like `college` and `degree`. Also a doctor could have multiple of these education entries. In essence I am looking for a one-to-many relationship, which is available in mongoose via `[]`. Does keystone also support it?

**Comment by hbksagar** [comment]
+1

**Comment by morenoh149** [comment]
http://keystonejs.com/docs/database/#relationships bad issue

**Comment by JedWatson** [comment]
@tusharmath @hbksagar you just need to specify the `many: true` option in your relationship field, please see the docs @morenoh149 linked to.

**Comment by tusharmath** [comment]
Thanks we were able to figure that out from the docs. But there is no way to reverse drill down from the ui?

**Comment by JedWatson** [comment]
@tusharmath what do you mean by reverse drill down?

**Comment by tusharmath** [comment]
Let me create another issue. Since its not relevant to this question.
