### ISSUE TITLE
adding cssautoprefixer

### ISSUE THREAD

**Issue by medv** [keystonejs/keystone#1398]
Hi guys, how would I go about putting cssautoprefixer into the mix after node-sass-middleware does its job? I think this issue belongs here because it is about how to extend/override Keystone files (/lib/core/mount.js from what I can understand). Unless I got something wrong and I can do it by passing something as config in Keystone.js to node-sass-middleware, in which case feel free to shame me.

```
var autoprefixer = require('autoprefixer-core');
var sass = require('node-sass');

var css = sass.renderSync({
    file: 'index.css'
});

autoprefixer.process(css).css;
```

But how to do this in a way that gets along with Keystone, so that I can `npm update` properly, instead of having to fork it.

Maybe the answer is I should fork Keystone and edit mount.js directly?

Do I make a new gulp task to watch the output .css that is the result of node-sass-middleware and inside the gulp task pipe it through to autoprefixer? Seems like adding a process that node-sass-middleware is trying to eliminate in the first place.

Is the problem actually with node-sass-middleware? So I should fork that, add the ability to add autoprefixer via passing 'options' and then go back to my project's keystone.js and simply pass an option to my modified node-sass-middleware via 'sass options': { ... } therefore not needing to stray from Keystone's codebase at all?

Trying to wrap my head around the best strategy, maybe those much smarter than me could chime in.. Thanks :)

**Comment by andrewlinfoot** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)
