### ISSUE TITLE
Create item form submits values for blank/unedited fields

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#1398]
The create form in the Admin UI submits all fields to the API, including those not entered.
This breaks DB-side defaults in Knex.

Consider the following list, with a DB default on the `category` field:

```js
const { Keystone } = require('@keystone-alpha/keystone');
const { KnexAdapter } = require('@keystone-alpha/adapter-knex');
const { Text } = require('@keystone-alpha/fields');

const keystone = new Keystone({ name: 'Keystone To-Do List', adapter: new KnexAdapter() });

keystone.createList('Todo', {
  fields: {
    name: { type: Text },
    category: { type: Text, knexOptions: { defaultTo: 'misc' } },
  },
});
```

Produces this table:

```sql
CREATE TABLE keystone."Todo" (
    id integer DEFAULT nextval('keystone."Todo_id_seq"'::regclass) PRIMARY KEY,
    name text,
    category text DEFAULT 'misc'::text
);
```

If we create a new todo using the admin UI and leave the `category` field blank...

![Screenshot 2019-07-15 at 14 41 11](https://user-images.githubusercontent.com/2416367/61196033-660d3380-a70f-11e9-93b6-f8d1ce5f9659.png)

The admin UI sends a `null` value for the category:

![Screenshot 2019-07-15 at 14 41 40](https://user-images.githubusercontent.com/2416367/61196100-b5536400-a70f-11e9-93fe-035893833c3a.png)

This prevents the DB-level default being applied since the `null` is explicit. If the field is excluded altogether, as in this mutation...

```graphql
mutation {
  createTodo (data: {name: "Eat some Gelato"}) {
    id name
  }
}
```
Then the default value will be used:

![Screenshot 2019-07-15 at 14 43 57](https://user-images.githubusercontent.com/2416367/61196143-eb90e380-a70f-11e9-9bb4-148fbab30d59.png)

This behaviour differs from the update form which (correctly) only submits values for fields that have been edited:

![Screenshot 2019-07-15 at 14 52 23](https://user-images.githubusercontent.com/2416367/61196197-3a3e7d80-a710-11e9-9dfe-f30833f7246a.png)

![Screenshot 2019-07-15 at 14 52 44](https://user-images.githubusercontent.com/2416367/61196202-3e6a9b00-a710-11e9-8ce7-320333af472b.png)

**Comment by jesstelford** [comment]
We need to copy the logic to omit fields which we already have in the `update` mutation:

https://github.com/keystonejs/keystone-5/blob/master/packages/app-admin-ui/client/pages/Item/index.js#L157-L160

The only thing this surfaces is the known issue of "how do we set a `null` value on a nullable field which has a default set?". But we can ignore that for now and just assume that any field without a value has not been "set".
