### ISSUE TITLE
Auto Cleanup Cloudinary does not work

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1399]
Hi ,

I set up the ***autoCleanup*** attribute for my post image, but I checked the ***cloudinary*** dashboard, the image is still there.  

Shouldn't it automatically remove the image?

```
Post.add({
	title: { type: String, required: true },
	state: { type: Types.Select, options: 'draft, published, archived', default: 'draft', index: true },
	author: { type: Types.Relationship, ref: 'User', index: true },
	publishedDate: { type: Types.Date, index: true },
	image: { type: Types.CloudinaryImage, autoCleanup : true, folder:  '/post' },
	content: {
		brief: { type: Types.Html, wysiwyg: true, height: 150 },
		extended: { type: Types.Html, wysiwyg: true, height: 400 }
	},
	categories: { type: Types.Relationship, ref: 'PostCategory', many: true }
});
```

**Comment by JohnnyEstilles** [comment]
I'm not quite sure I unerstand your issue. Are you trying to say that while `autoCleanup` was set to `true`, you attempted to delete a Cloudnary image via the admin UI, and the image still appears in the Cloudinary dashboard?

**Comment by arthurtalkgoal** [comment]
Hi @JohnnyEstilles ,

Sorry for the confussion made first.

And you are right! that's what I found. 

I deleted the image via Admin UI, but the Cloudinary dashboard still have the image.

**Comment by JohnnyEstilles** [comment]
Just out of curiosity, were you holding down the <kbd>ALT</kbd> key when you pressed the delete button for the Cloudinanimage?

**Comment by arthurtalkgoal** [comment]
Nope.  I just clicked the delete image button in backend. 

What is the difference with the ```ALT```?

**Comment by JohnnyEstilles** [comment]
I asked because <kbd>ALT</kbd> change the behavior or the delete button for Cloudinary images in the admin UI. When `autoCleanup` is `true`, you can use <kbd>ALT</kbd> if you DON'T want to delete the image from Cloudinary.  The opposite is true when `autoCleanup` is `false` or not set. 
<hr />
Regarding the <kbd>ALT</kbd> key, I used HTML, not Markdown. 

```html
<kbd>ALT</kbd>
```

**Comment by mxstbr** [comment]
This is a duplicate #162!
