### ISSUE TITLE
Write Cypress Tests for the Twitter OAuth flow

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#140]
This might be impossible to make it portable? Who do we login as? What Twitter app do we log into?

Ideally, we'd be able to mock out the Twitter URL and act as an OAuth provider in between... Or something.

**Comment by MadeByMike** [comment]
Maybe https://www.npmjs.com/package/oauth2-mock-server

**Comment by jesstelford** [comment]
This is not a feature being supported into Keystone Next.
