### ISSUE TITLE
Provide a means to pass options to morgan (logger) middleware

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#1401]
At the moment, Keystone consumers can set the output format used by [morgan](https://github.com/expressjs/morgan) via the `logger` option. In addition to the output format, morgan takes an `options` object as it's second parameter with which one can set:

* `skip` - a function which allows us to filter the entries logged, and
* `stream` - an output stream to which morgan will write the log.

I propose we create a new option (e.g. `logger options`) that when set will be passed to morgan as it's second parameter.

```js

var logFilter = function(req, res) {
  return res.statusCode < 400
};

var logStream = fs.createWriteStream(__dirname + '/access.log', {flags: 'a'});

keystone.init({
  ...
  'logger options': {
    skip: logFilter,
    stream: logStream
  },
  ...
});
```

If you guys agree, I'll submit a PR adding this feature. Your thoughts?

**Comment by JedWatson** [comment]
Closed by #1407
