### ISSUE TITLE
Support for Hierarchical data

### ISSUE THREAD

**Issue by lojack** [keystonejs/keystone#1403]
I would like to propose the idea of having a built-in way to support hierarchical content from within keystone. This is a common feature in other CMS's. This concept can be used to build navigation as well as listing pages. 

Right now this ends up being a bespoke feature in almost every site I work on. 

Some considerations include:

- Not all content is hierarchical in nature. 
- Navigation isn't always built using the site heirarchy. (i.e. blog articles may be children of a blog index page, but their navigation follows a /:year/:month/:day/:slug format).
- Fast lookups of children, parents (for breadcrumbs), siblings using something like mongoose-nested-set
- There may need to be multiple root hierarchies.

**Comment by Adam14Four** [comment]
This would be useful for me too.  I have a need for heirarchical data and I can setup the models to support it, but they don't work terribly well in the Admin UI.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/support-for-hierarchical-data
