### ISSUE TITLE
Pagination with populateRelated

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1408]
Hi, 

I want to ***paginate*** the nearby deals for the codes as follows.

```
    Company.model
    	.find({'address.geo': {
              '$near': {
                   '$geometry': {
                      type: "Point" ,
                      coordinates:  [ center[1], center[0]  ]
                   },
                   '$maxDistance': 5000    // meters
                }             
          }
        })
        
        .exec(function(err, companies) {
          keystone.populateRelated(companies, 'deals', function(err) {  
...
```

There is a nodejs pagination plugin, but I am not sure how to use it in the ***keystone.populateRelated***

https://github.com/edwardhotchkiss/mongoose-paginate

**Comment by arthurtalkgoal** [comment]
In addition,

Can I do the ***select*** for ***populateRelated***?
e.g.

```
  keystone.populateRelated(companies, 'deals')
            .select('-_id name slug start end')
```

**Comment by ttsirkia** [comment]
Have you checked `List.prototype.paginate` for pagination? And if I understood correctly, could you use normal Mongoose population and field selection? http://mongoosejs.com/docs/populate.html

**Comment by andrewlinfoot** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)
