### ISSUE TITLE
Types.Boolean is set to false if not shown

### ISSUE THREAD

**Issue by drlogout** [keystonejs/keystone#1410]
If a Types.Boolean field depends on a Types.Select field, the Boolean is set to false if it's not shown when saving.
For example:

```
Test.add({
  name: { type: String, required: true },
  select: {type: Types.Select, numeric: true, options: [{value: 0, label: 'A'},{value: 1, label: 'B'}] },
  a: {type: Types.Boolean, dependsOn: {select: 0}},
  b: {type: Types.Boolean, dependsOn: {select: 1}}
});

```
If I set **a** to true, save it, then set **b** to true, save it, **a** I set to false again and vice versa.

**Comment by mxstbr** [comment]
Since this bug is almost a year old I'll close it, feel free to comment again if this still exists for you!
