### ISSUE TITLE
Most middleware (like limit) is no longer bundled with Express

### ISSUE THREAD

**Issue by freder** [keystonejs/keystone#1412]
I tried to use `keystone.set('file limit', '10mb')`, but express is complaining, saying:

```
/Volumes/Macintosh HD 2/Projects/project/platform/node_modules/keystone/node_modules/express/lib/express.js:89
      throw new Error('Most middleware (like ' + name + ') is no longer bundle
            ^
Error: Most middleware (like limit) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
```

according to [https://github.com/senchalabs/connect#middleware](https://github.com/senchalabs/connect#middleware) [`raw-body`](https://www.npmjs.com/package/raw-body) should be used now.

**Comment by JedWatson** [comment]
Thanks for the report, will get this fixed asap

**Comment by dvdcastro** [comment]
I fixed it using the new body-parser conventions on the file [mount.js lines 358 to 366](https://github.com/keystonejs/keystone/blob/master/lib/core/mount.js#L358-L366)

	var bodyParserParams = {};
	
	if (this.get('file limit')) {
		debug('adding file limit');
		bodyParserParams.limit = this.get('file limit');
	}

	debug('adding standard middleware');
	app.use(bodyParser.json(bodyParserParams));

	bodyParserParams.extended = true;
	app.use(bodyParser.urlencoded(bodyParserParams));

**Comment by jacargentina** [comment]
@JedWatson There is my PR for this, please merge?

**Comment by JedWatson** [comment]
done! will publish a release soon.
