### ISSUE TITLE
Local Files - file name and extension

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#1414]
Whilst testing our file fields I noticed that the naming function for LocalFile on the docs website returns `undefined` for the file extension.

Docs can be found here:
http://keystonejs.com/docs/database/#fieldtypes-localfile

The function in question:
```
function(item, file){
  return item.id + '.' + file.extension
}
```

N.B. the file name is returned successfully as the item id

**Comment by Gouthamve** [comment]
I cannot reproduce this. I am getting the filename with its extension. Also I tried putting an ```console.log(file.extension)``` before the return and successfully printed out the extension name.

I just played with local files today and copied the function right off the docs and it worked!

**Comment by jossmac** [comment]
@Gouthamve thanks for testing!
