### ISSUE TITLE
Need Documentation - How to add a widget(eg: customize TextBox or a Button) at Admin UI?

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [keystonejs/keystone#1418]
I have tried, but getting following error
**Invalid Value for Schema path 'button.type' in 'Post'.**
**Did you missspell the field type?**

**Comment by morenoh149** [comment]
@harpreetkhalsagtbit we don't have this feature. You'll have to dig into your fieldtype's source code. Should be possible after `custom fieldtypes` land. Keep an eye on https://github.com/keystonejs/keystone/blob/master/ROADMAP.md or ask in the [gitter](https://gitter.im/keystonejs/keystone) chat.

**Comment by harpreetkhalsagtbit** [comment]
Hi @morenoh149 
I have figured out How to add a Field in KeyStone and documented it.
Please let me know, How can I contribute the documentation to KeyStoneJS.

**Comment by morenoh149** [comment]
@harpreetkhalsagtbit please read https://github.com/keystonejs/keystone/blob/master/CONTRIBUTING.md and contribute documentation to https://github.com/keystonejs/keystonejs-site
