### ISSUE TITLE
Customize Admin UI

### ISSUE THREAD

**Issue by cflorion** [keystonejs/keystone#1419]
Is the Admin UI fully customizable ?
I am building a website for a client and I want the backoffice to be really custom made, with the minimal set of features they need.

In KeystoneJS, is this something that is:
1. possible (I haven't seen where in the code, I mean without modifying the module)
2. not possible with Keystone and will never be
3. not possible with Keystone but will be someday

If it's the 3rd option, maybe I could help with that, where should I look ? Do you think it's a big amount of work (re-design things a little) ?

**Comment by morenoh149** [comment]
3.
Customizing the Admin UI involves being able to theme it (https://github.com/keystonejs/keystone/issues/548) and adding custom widgets to the Admin UI is in the pipeline (can't find the relevant issue atm). If you'd like to join the slack channel let me know.

**Comment by cflorion** [comment]
I'll look into it. Is anything done on the subject already ?
If you have already an idea on how to make that, could you give me your point of view ? :)

PS: Good idea, I'd like to join the slack channel yes, thanks.
