### ISSUE TITLE
Linking IDs for related items when using createItems

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#142]
Following from #138 and the discussion in #135 

I think we should support inserting data directly into relationship fields if the IDs of the items to be related can be known ahead of time. e.g

```
const category = await keystone.lists.Category.model.findOne({ name: 'Keystone' });
const jed = await keystone.lists.User.model.findOne({ name: 'Jed Watson' });

keystone.createItems({
  Post: [
    { title: 'Keystone 5 Annnouncement', categories: [category.id], author: jed.id  }
  ]
});
```

_Arguably_ this is possible with the `where` syntax, **but**:

If we can do this in the initial phase (i.e don't separate out relationship fields when they contain simple values) then it enables a workaround if the relationship fields are required in the schema.

**Comment by MadeByMike** [comment]
@jesstelford I know this code has changed a bit since this issue was raised. Is it still relevant?

**Comment by jesstelford** [comment]
This is still an issue with `createItems`. There are other discussions around whether or not we should even have `createItems` or if it should just be graphQL queries now that we have `keystone.executeQuery()`. See: #1756

**Comment by MadeByMike** [comment]
I think we are clear now that `createItems` has known limitation and that other methods will provide for better seeding and migration solutions.
