### ISSUE TITLE
"prodiction" instead "production"

### ISSUE THREAD

**Issue by poliveira89** [keystonejs/keystone#1426]
I was wondering on `gulpfile.js` when I found it this typo: [prodiction](https://github.com/keystonejs/keystone/blob/master/gulpfile.js#L17)

I have my doubts if it's on purpose. :smile:

**Comment by morenoh149** [comment]
@poliveira89 yes that's a mistake. please submit a pr :)

**Comment by dcousens** [comment]
Fixed in https://github.com/keystonejs/keystone/commit/876b8a1c4de86f335dc153e4302aaa6e1e92bced

**Comment by poliveira89** [comment]
@dcousens @morenoh149 I didn't create a PR because I thought it was "over-kill" for a typo. Next time I will do it :+1:

**Comment by dcousens** [comment]
@poliveira89 vs making an issue exactly describing the issue so we can read it and then go ahead and fix it ourselves?  Nah, a PR is a one-click merge for us, especially for something like a typo.

Thanks for pointing this out :)

**Comment by poliveira89** [comment]
@dcousens makes sense :+1: 
Again sorry for the trouble, I was thinking the wrong way :(

**Comment by JedWatson** [comment]
@poliveira89 no trouble, thanks for getting involved :)
