### ISSUE TITLE
CloudinaryImage  required but cannot initial

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1427]
Hi, 

I wanna required the image field, but Keystone asked me to initial it (you must initial a required field currently)

```
image: { type: Types.CloudinaryImage, autoCleanup : true, folder:  '/topics', initial: true,required: true},
```
However, it then pop up error than CloudinaryImage cannot be initialed!
```
CloudinaryImage fields (Topic.image) do not currently support being used as initial fields.
```

It seems that no ways to required a CloudinaryImage field?

**Comment by morenoh149** [comment]
Uploading a file is pretty time consuming. The js way would be to do the file upload asynchronously and thus there's no way to require the cloudinaryimage. You could try a pre-save hook that adds the cloudinaryimage and if that upload fails it aborts saving this model.

**Comment by arthurtalkgoal** [comment]
Thanks @morenoh149 ,  you are right, I added the pre validate hook to do that.

Anyway, I am not familiar with the keystone field logic, can we put the pre validate cooks in keystone if CloudinaryImage is required? like put the following into the keystone logic? 

```
Topic.schema.pre('validate', function (next) {
  var self = this;

  if (!(self.image && self.image.url)) {
    self.invalidate("image", "Please upload an image");
  }
  return next();

});
```

**Comment by arthurtalkgoal** [comment]
Oh, @morenoh149 ,  I think I got what you mean, you refer to the inital problem instead of the required problem.
