### ISSUE TITLE
Slug History

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1428]
Hi, 

for models using autokey - there will be slugs created. 

However, the slug will be update if the ***from*** field is updated, e.g.

```
autokey: { path: 'slug', from: 'title', unique: true, locale: 'zh' },

```
If title is updated, the slug will be updated.

***Then it will be a problem if the related object is shared and title is updated***, the object just be 404!

In Rails friendly_id gem, for e.g., it has a slug history table, is it applicable in nodejs? 

Due to the fact that my blogs is shared in linkedIn and social network, once I update a word in title, the shared link will fail.

**Comment by morenoh149** [comment]
@arthurtalkgoal I'm a fan of the friendly_id gem from rubygems as well.
looks like this module could be what you want https://www.npmjs.com/package/mongoose-friendly-id
otherwise you could try coding up the module yourself. I'm sure it'd be popular.

**Comment by arthurtalkgoal** [comment]
Hi @morenoh149 ,

Great to meet another Rails and FriendlyId fans!

The mongoose-friendly-id looks good. What I used most and missing in currenty keystone autokey are:

1. Slug History
2. FindByIdOrSlug

I tried to do the 2. by myself, but it's very troublesome; since ***_id*** is ObjectId type in keystone, but ***slug*** is a string.   

Fact, these problems relate to the workflow we write e.g. a Post in a Blog.

Before the Title is written, the slug may be the ***_id***, once it's drafted, the ***slug*** is initialized.  And when it published, the ***slug*** may already have a few versions. 

Do you have similar problems? Or how to tackle this problem in the community?

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, feel free to upvote it there if this feature is important to you: https://productpains.com/post/keystonejs/slug-history!
