### ISSUE TITLE
Linking refs for related items when using createItems

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#143]
Following from #138 and the discussion in #135

Using the `where` syntax for relationships in `createItems` is potentially dangerous when you're running a script against a populated database, esp. in production (e.g as part of a data migration or import)

It would be much safer to bring back the `ref` concept for resolving IDs for newly-created items from Keystone 4, which is probably simplest with the following syntax:

```
import { ref } from '@keystonejs/core'; // is a Symbol

keystone.createItems({
  Users: [{
    name: 'Jess',
    [ref]: 'jess',
  }],
  Posts: [{
    title: 'Hello world',
    author: { ref: 'jess' }
  }],
});
```

I _am hopeful_ this should be fairly straightforward to implement given the current approach; it requires us to find the `ref` symbol in items when we create them, and then add their resulting ID to an internal map. In the third phase, where we update the relationship fields, any objects with the `ref` key (as opposed to a `where` key) get resolved internally from the map rather than executing a query.

Note that I've diverged from keystone 4 syntax in two ways:

* Now using a symbol instead of a magic `_ref` key
* Using an object `{ ref: 'jess' }` instead of a string representing the ref so the syntax doesn't clash with #142

**Comment by MadeByMike** [comment]
Closing as there is no intention to add to the `createItems` API see: https://github.com/keystonejs/keystone/issues/144
