### ISSUE TITLE
Less, Semantic-UI and Keystone

### ISSUE THREAD

**Issue by stunjiturner** [keystonejs/keystone#1432]
I removed the bootstrap import statement in my site.less file. I do have 'less': 'public', in my keystone init file. I created a folder in public named semantic and included are the less source file in a folder structure as follows semantic -> definitions -> 

'''/* Global */
& { @import "semantic/definitions/globals/reset"; }
& { @import "semantic/definitions/globals/site"; }

/* Elements */
& { @import "semantic/definitions/elements/button"; }
& { @import "semantic/definitions/elements/divider"; }
& { @import "semantic/definitions/elements/flag"; }
& { @import "semantic/definitions/elements/header"; }''

But the import statements do not generate a site.min.css file with the correct css. It is actually blank. I have a successfully deployed app running on heroku?

**Comment by vitalbone** [comment]
Here is how to get [Semantic-UI-Less](https://github.com/Semantic-Org/Semantic-UI-LESS) working in Keystone:

Directory structure:
```
styles
|- semantic
    - definitions
        - elements
        - globals
    - themes
    - semantic.less
    - theme.config
    - theme.less
|- site
    - layout.less
    - site.min.css
    - variables.less
|- site.less
|- site.min.css
```

Make sure you have a Semantic-UI theme in the `themes` directory.
Make sure you have `theme.config` & `theme.less` files.

Inside your `site.less`:

```
// styles/site.less

@import "semantic/semantic.less";
```

Inside your `semantic.less`:

```
// styles/semantic/semantic.less

/* Globals */
@import "definitions/globals/reset";
@import "definitions/globals/site";

/* Elements */
@import "definitions/elements/button";
@import "definitions/elements/divider";
@import "definitions/elements/flag";
@import "definitions/elements/header"
```

You'll also need to remove any reference to bootstrap variables in `site/layout.less`

**Comment by stunjiturner** [comment]
should i rename theme.config to theme.config.less. If not how does keystone pickup and understand a .config file

**Comment by vitalbone** [comment]
No need to add `.less` to `theme.config` - Keystone treats `theme.config` like any other config file. In the example case found [here](https://github.com/Semantic-Org/Semantic-UI-LESS/blob/master/theme.config.example) `theme.config` let's your project know where the themes folder is located (`themes`), where the site override folder is (`site`) and to import `theme.less`

**Comment by stunjiturner** [comment]
Thanks for the explanation.

Sightuary

**Comment by stunjiturner** [comment]
@vitalbone Still not able to get the semantic-ui-less files to work in my setup, I am using keystone 0.3.15 latest nom install of the semantic-ui-less. does the semantic.json file thats generated have any use in keystone?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
