### ISSUE TITLE
Color Picker does not work in Admin UI

### ISSUE THREAD

**Issue by pr1ntr** [keystonejs/keystone#1433]
Am I crazy because the color pickers aren't working for me in the admin UI. 

This is the model code.
```
colorPrimary:{
            type:Types.Color,
            label:"Primary Color"
        }
        ,colorSecondary:{
            type:Types.Color,
            label:"Secondary Color"
        }
```

This is the result. Nothing happens when I click on them.
![screen shot 2015-05-29 at 4 13 30 pm](https://cloud.githubusercontent.com/assets/1272089/7894382/af2e1eae-061d-11e5-9cbe-5efc58ee4ce6.png)

**Comment by medv** [comment]
As a sidenote related to color picker, maybe the little color square in the right side should have a slight border, because it just looks like a regular textbox if you put #fff in there.

**Comment by andrew--grant** [comment]
I'm the same, nothing at all happens when I click on my color field, my expectation was to see a color picker.

ProductColour.add({
	name: {type: String, required: true},
	colourValue: {type: Types.Color}
});

**Comment by mxstbr** [comment]
Definitely working `master`!
