### ISSUE TITLE
Upload CSV to Keystone Database

### ISSUE THREAD

**Issue by xianlin** [keystonejs/keystone#1434]
I am trying to upload a csv file via an **upload** button in Keystone Admin UI to insert the content of the CSV file into the mongodb database.

For example, I have a blog post CSV file and I want to upload it to the Post table in the Keystonejs database.

Such upload button does not exist so I have to create one beside the existing **Create Post** button.

![image](https://cloud.githubusercontent.com/assets/1726373/7901275/ce33b238-07b1-11e5-9146-9ffea87bfcdd.png)

Also I have to make some csv to mongodb logic code and put it to somewhere.

I am hoping someone here using Keystone can give me a bit direction on how to implement this **upload** button and **update mongodb logic** as in where/which file to put the code?

To me right now, it looks like the path `/node_modules/keyston/admin/src/views` is the place to go. Am I right?

**Comment by morenoh149** [comment]
this sounds doable but will require some coding. What part are stuck on? Sounds like you'd end up having to write a custom keystone module that takes a csv, parses it and hooks into the [updaters](http://keystonejs.com/docs/getting-started/#runningyourapp-writingupdates) tool.

**Comment by xianlin** [comment]
I am stuck on which file I should put the **"Upload" button** html/css code into?

I found "Create" button code in the `ItemViewHeader.js` file. At line [158](https://github.com/keystonejs/keystone/blob/master/admin/src/components/ItemViewHeader.js#L158), `renderCreateButton` was defined here. OR I can hooks into the updaters tool like @morenoh149 suggested. (I don't know how to hook but will look into the guide, thanks for the suggestion)

Can I copy this **Create** Button code, modify it to become **Upload** button code then bind to my new customized `toggleUploadCSV` function?

So I can have "Create" and "Upload" button side by side for the customer to decide either create item manually one by one OR upload a csv file to update the whole table.

**Comment by xianlin** [comment]
hi @morenoh149 , how to hooks into the updaters tool? 

On the keystonejs website:

> When the option is set to true, Keystone will scan the updates directory for .js files, each of which should export a method accepting a single argument:

Say I have a `csv_update_db.js` file ready to update db from the csv file uploaded, but how to **trigger** Keystone to scan the `csv_update_db.js` file after upload csv file?

**Comment by morenoh149** [comment]
I'm just thinking out loud here. But the example update script makes one user and stores it in the db. Your script should iterate over the csv rows and make mongoose models, then store them. Try asking in the gitter.

**Comment by xianlin** [comment]
Finally I got it done.

I hope my work can help someone who want this CSV upload feature.

Here is the code/meat/HowTo:

modify the `keystone/admin/src/views/list.js`, I am ONLY allow upload csv for `Post` list, you can use your own list.

```javascript

   var React = require('react');
var CreateForm = require('../components/CreateForm');
var UploadForm = require('../components/UploadForm');

var View = React.createClass({

    displayName: 'ListView',

    getInitialState: function() {
        return {
            createIsVisible: Keystone.showCreateForm,
            uploadIsVisible: Keystone.showUploadForm,
            animateCreateForm: false,
            animateUploadForm: false
        };
    },

    toggleCreate: function(visible) {
        this.setState({
            createIsVisible: visible,
            animateCreateForm: true
        });
    },

    toggleUpload: function(visible) {
        this.setState({
            uploadIsVisible: visible,
            animateUploadForm: true
        });
    },

    renderCreateButton: function() {
        if (Keystone.list.autocreate) {
            return (
                <a href={'?new' + Keystone.csrf.query} className="btn btn-default btn-create btn-create-item">
                    <span className="ion-plus-round mr-5" />
                    Create {Keystone.list.singular}
                </a>
            );
        }
        return (
            <button type="button" className="btn btn-default btn-create btn-create-item" onClick={this.toggleCreate.bind(this, true)}>
                <span className="ion-plus-round mr-5" />
                Create {Keystone.list.singular}
            </button>
        );
    },

    renderCreateForm: function() {
        if (!this.state.createIsVisible) return null;
        return <CreateForm list={Keystone.list} animate={this.state.animateCreateForm} onCancel={this.toggleCreate.bind(this, false)} values={Keystone.createFormData} err={Keystone.createFormErrors} />;
    },

    renderUploadButton: function() {
        if (Keystone.list.singular === 'Post') {
            return (
                <button type="button" className="btn btn-default btn-create btn-create-item" onClick={this.toggleUpload.bind(this, true)}>
                    <span className="ion-plus-round mr-5" />
                    Upload CSV for {Keystone.list.singular}
                </button>
            );
        }
    },

    renderUploadForm: function() {
        if (!this.state.uploadIsVisible) return null;
        return <UploadForm list={Keystone.list} animate={this.state.animateCreateForm} onCancel={this.toggleUpload.bind(this, false)} />;
    },

    render: function() {
        if (Keystone.list.nocreate) return null;
        return (
            <div className="create-item">
                <div className="toolbar">
                    {this.renderCreateButton()}
                    {this.renderUploadButton()}
                </div>
                {this.renderCreateForm()}
                {this.renderUploadForm()}
                <hr />
            </div>
        );
    }

});

React.render(<View />, document.getElementById('list-view'));
```

Add a new `UploadForm` by create `keystone/admin/src/components/UploadForm.js`, please note the form submit action can be customized, mine is `/uploadcsv_post`.

```Javascript

var _ = require('underscore'),
    React = require('react');

var Form = React.createClass({

    displayName: 'UploadForm',

    render: function() {

        var list = this.props.list;
        var modalClass = 'modal modal-md' + (this.props.animate ? ' animate' : '');

        return (
            <div>
                <div className={modalClass}>
                    <div className="modal-dialog">
                        <form className="modal-content" encType="multipart/form-data" method="post" action='/uploadcsv_post'>
                            <input type="hidden" name="action" value="create" />
                            <input type="hidden" name={Keystone.csrf.key} value={Keystone.csrf.value} />
                            <div className="modal-header">
                                <button type="button" className="modal-close" onClick={this.props.onCancel}></button>
                                <div className="modal-title">Upload CSV for {list.singular}</div>
                            </div>
                            <div className="modal-body">
                                CSV File:<input type="file" id="csvFile" accept=".csv" name="csvFile"/>  
                            </div>
                            <div className="modal-footer">
                                <button type="submit" name="submit" className="btn btn-create">Upload</button>
                                <button type="button" className="btn btn-link btn-cancel" onClick={this.props.onCancel}>cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div className="modal-backdrop"></div>
            </div>
        );
    }

});

module.exports = Form;
```

Continue to add `/uploadcsv_post` logic to keystone route, create `routes/api/uploadcsv.js`, please note that I added my own customized json parser to suit my own CSV file format, you should modify it to suit your needs.

```javascript
/**
 * Upload CSV for Posts
 */

var keystone = require('keystone'),
  _ = require('underscore'),
  Menu = keystone.list('Post');

exports = module.exports = function(req, res) {
    var Converter=require("csvtojson").core.Converter;
    var fs=require("fs");
    //CSV File Path or CSV String or Readable Stream Object
    var csvFileName=req.files.csvFile.path;
    var fileStream=fs.createReadStream(csvFileName);
    //new converter instance
    var csvConverter=new Converter({constructResult:true});

    //end_parsed will be emitted once parsing finished
    csvConverter.on("end_parsed",function(jsonObj){
      //res.json(jsonObj);
      var postJson = _.each(jsonObj, function(value,key){
        value.date = new Date(value.date).toISOString().slice(0, 10);
      });
      console.log(postJson);
      Post.model.find({}).remove().exec();
      keystone.createItems({
        Post: postJson
      },function(err, stats) {
        if (err) return res.json(err);
        //stats && console.log(stats.message);
        res.redirect('/keystone/posts');
      });
    });

    //read from file
    fileStream.pipe(csvConverter);
}
```

Don't forget to change the route at `routes/index.js` with below code:

```javascript
 app.post('/uploadcsv_post', keystone.middleware.cors, routes.api.uploadcsv);
```

Also install `csvtojson`:

```shell
npm install csvtojson --save
```

I hope someone can use it or even better, integrate this feature into Keystone.js.

**Comment by NTruchaud** [comment]
Hi, 
I used your method to upload my csv, and it worked great. So first of all, thank you for the time you spared me. 
But I have an issue : I have 2 tables : 1 table call project and one call Info.
When I add all my infos with the CSV, I'd like to be able to select the project the infos are related to, and I have no idea how to proceed. I've read and read the relationship part of the KeystoneJS documention, but couldn't find what I'm looking for.

Regards,

**Comment by xianlin** [comment]
when you upload `info` csv file, you like to upload the record in the `project` table related to the `info` record as well?

Then you need one more layer of logic in the `upload` javascript script. After read all records from the `info` CSV file, DO NOT update/insert to mongodb first. You should query the mongodb table `project` and search for the related record against loaded `info` CSV record ONE BY ONE. 

IF the record match/found, then allow mongodb insert/update action to happen till the last `info` record was searched and updated in the mongodb.

Yes, you need write your own code in the logic and this is not an easy task for me either.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/upload-csv-to-keystone-database

**Comment by slim01** [comment]
Is there any way to do this in the new version?
I want to convert uploaded shapefiles to geojson and save it to the mongodb

**Comment by jelordreygulle** [comment]
Is there an update to this ? in the new version of keystone js ?

Upload a csv file via an upload button in Keystone Admin UI to insert the content of the CSV file into the mongodb database.

For example, I have a blog post CSV file and I want to upload it to the Post table in the Keystonejs database.
Thanks.

**Comment by MorMeshulam** [comment]
also joining to @jelordreygulle request.
need to import simple data from csv (without relations).

**Comment by jelordreygulle** [comment]
@JedWatson , Sir , Any update to this ?

**Comment by gautamsi** [comment]
v4 is in maintenance mode, there is very little (tiny) chance that new feature would make into the repo. 
that said, it is not much a problem if you want to create something yourself. you can have uploaded file which can inject the data in your database. use `fast-csv`, `papaparse` is also very popular for processing csv files. depends on how you upload you can use list's `updateHandler` to process those records.

**Comment by jelordreygulle** [comment]
Thank you for the details.

**Comment by Rajivkumar1234** [comment]
@xianlin , you could reduce your csv to json with the ff code
```

var csv = require("csvtojson");
  var csvFilePath=req.files.csvFile.path;

  csv()
  .fromFile(csvFilePath)
  .then(function(jsonArrayObj){ //when parse finished, result will be emitted here.
     console.log("jsonArrayObj", jsonArrayObj); 
   })
```
