### ISSUE TITLE
using updateHandler with non-keystone fields

### ISSUE THREAD

**Issue by freder** [keystonejs/keystone#1435]
hi,

I would like to have a model with a fields that contains an array of strings. — from what I understand, having arrays of `<something>` is not (yet) possible, that's why you have to add the field to the mongoose `schema` instead of defining a `keystone.Field`:

```
var Step = String;
Recipe.schema.add({
	steps: [Step]
});
```

I don't necessarily need to see `steps` in the admin ui, so that's fine. however, I would like to continue using the `updateHandler`. unfortunately this doesn't seem to work:

```
Error thrown for request: /api/recipe/new
Error: UpdateHandler.process called with invalid field path: steps
    at UpdateHandler.<anonymous> (/Volumes/Macintosh HD 2/Projects/xyz/node_modules/keystone/lib/updateHandler.js:211:10)
```

it's the same as what @TejasCMehta describes [here](https://github.com/keystonejs/keystone/issues/648#issuecomment-56712203) — although he didn't seem to have created a new issue in the end.

is there any way to do this?

thanks a lot in advance.

**Comment by mxstbr** [comment]
We have a `TextArray` field now!
