### ISSUE TITLE
Easily "duplicate" existing items in the Admin UI

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1435]
Allow users to duplicate list items. For complex lists with lots of data it can save time to duplicate and change specific values.

**Comment by MadeByMike** [comment]
I'm posting this in response to user request however I think it might be better solved for the majority of users simply by applying sensible default values.

Perhaps a good candidate for a third-party plugin\extension.

**Comment by jesstelford** [comment]
Oooh, I like the idea of duplicating! Great suggestion 👍

**Comment by VinayaSathyanarayana** [comment]
It is more "Cloning" an existing record and not duplicating

**Comment by gautamsi** [comment]
> Perhaps a good candidate for a third-party plugin\extension. 

there are much more to do in preparation before we can add third party extension.

duplication of existing record should be `admin ui` feature where someone just has to apply value for unique filed, auto generated field should do their job regardless.

**Comment by MadeByMike** [comment]
> there are much more to do in preparation before we can add third party extension.

Totally, but I also think this is a feature that only a small number of users might need so I can't see it being prioritised soon.

**Comment by molomby** [comment]
Isn't this best solved by just populating the "new" screen with the values of an existing item? I imagine this is technical simple (basically the "new" screen loading data like the "edit" screen does) and gives the use an opportunity to fix/resolve any validation error, duplicate keys/slugs, etc.

**Comment by gautamsi** [comment]
@molomby https://github.com/keystonejs/keystone/pull/1724 allows duplication but @MadeByMike is working on infrastructure to add this as UI hook (plugin/action/..) so that it also becomes example of how to add similar features.

**Comment by gautamsi** [comment]
Creating duplicate item was very easily possible after some hooks got merged (`listItemActions` hooks and `itemHeaderActions` hook).

unfortunately the `CreateIteemModal` is refactored in such a way that you can not have more than 1 instance on a page. I need to refactor the CreateItemModal to be generic OR use a copy into the hook which works too but gets outdated with new changes happening to createItem modal day by day.

**Comment by savager** [comment]
Would love to see an option to enable this functionality in the admin UI. Theoretically it would populate the already existing create modal that slides in from the left with data from the fields in the current item.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
