### ISSUE TITLE
Sortable lists should always use sortOrder in context views

### ISSUE THREAD

**Issue by vasklund** [keystonejs/keystone#1439]
When a list is `sortable`, has a `sortContext` and a `defaultSort`, the current behavior will sort the list according to the defaultSort both in its main list, but also when it is presented as a context (relationship).

Contrived example:
```
var Team = new keystone.List('Team'});
Team.relationship({ path: '_players', ref: 'Player', refPath: '_team' });

var Player = new keystone.List('Player', {
  defaultSort: '-updatedAt',
  sortable: true,
  sortContext: 'Team:_players'
});
Player.add({ _team: { Types.Relationship, ref: 'Team' } });
```

A setup like this will show a sortable list of all players on the admin edit page for each team, which is very convenient. The problem is that as soon as the list is sorted and saved, and the page is refreshed, the defaultSort `-updatedAt` causes the players to be presented in a different order than what the admin just sorted them to (even though the sortOrder is saved correctly in the database). The next time an admin wants to reorder the list, they have to reorder all players again.

**Comment by jeffreypriebe** [comment]
Various [other](https://github.com/keystonejs/keystone/issues/623) [issues](https://github.com/keystonejs/keystone/issues/441) point at sortContext not working.

**Comment by morenoh149** [comment]
Closing in favor of those
