### ISSUE TITLE
File Type helper functions exists and delete should be async

### ISSUE THREAD

**Issue by tylkomat** [keystonejs/keystone#1443]
The Helper functions in LocalFile(s), CloudiaryImage(s), S3 File should be asynchronous, as they rely on external protocols (http, fs). Using fs.existsSync for example in the case of LocalFile(s) is not the way how nodejs is intended to work. Also there is generally no error handling.

**Comment by mxstbr** [comment]
We'll be reworking the storage fields completely soon after 0.4 is launched, then we'll take a look at this! Thanks!
