### ISSUE TITLE
Support Cloudinary context metadata?

### ISSUE THREAD

**Issue by snawbel** [keystonejs/keystone#1444]
I have a modified version of the `CloudinaryImage` field type that supports Cloudinary's api for adding arbitrary key/value, textual metadata to an image resource:

`img: {type: Types.CloudinaryImage, context: ['caption', 'credit']}`

The elements in the `context` array will be displayed as simple text fields next to the image info in the admin ui.

Until #153 is solved I find this to be a decent way to add a caption and similar data. If there is interest I could polish this into a PR. What do you think?

**Comment by fde31** [comment]
any chance you could share this? doesn't seem too hard to achieve but would be curious how u did it. I'm looking for a smooth integration of title and alt attributes.

Thanks!

**Comment by snawbel** [comment]
I went with another solution using imgix+Amazon instead of Cloudinary. If you really want to I could try to dig out my old code.

**Comment by fde31** [comment]
thanks for the quick response. No worries, I got a approach working on my end for this so no need.

**Comment by mxstbr** [comment]
Since this seems done, I'll close this issue! Let me know if you're still having problems!

**Comment by semeano** [comment]
@snawbel can you share your code? I can't find any fork on your repos. Thanks
