### ISSUE TITLE
Review code in /lib/session.js for secureness

### ISSUE THREAD

**Issue by WingedToaster** [keystonejs/keystone#1448]
In the <a href="https://github.com/keystonejs/keystone/blob/master/lib/session.js#L82">doSignin</a> function of <code>/lib/session.js</code> it appears that one can simply pass in a <code>userId</code> without a password and still trigger a successful login (the req.user and req.session.userId fields are populated). 

I'm sure this is there for a good reason, but I would think there needs to be some sort of validation to ensure the user is who they say they are. Is there something else along the way that might be doing the validation before it gets to this function?

Thoughts?

**Comment by Gouthamve** [comment]
This function helps in situations such as using oAuth and passport where you will get the id from Fb, etc and will not have a password.

I think the validation is done by Fb or any other oAuth provider who gives us the id after verification.

**Comment by mxstbr** [comment]
What @Gouthamve said 👍
