### ISSUE TITLE
Field Encryption

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#1448]
We should consider an option for encryption of particular fields in a List. 
This will help us with handling PII (Personally Identifiable Information)

E.g: socialsecuritynumber: { type: Text, encrypt: true }

We can leverage
Mongodb: https://www.npmjs.com/package/mongoose-encryption 
Knex: TBD (I am not knowledgeable about Knex)

**Comment by jesstelford** [comment]
Ooh, interesting idea!

Would this be a one-way hash, or a public-private key type encryption?

For now you can add this functionality yourself with hooks:

```javascript
keystone.createList('User', {
  fields: {
    socialsecuritynumber: {
      type: Text,
      hooks: {
        resolveInput: ({ resolvedData }) => encrypt(resolvedData.socialsecuritynumber)
      }
    }
  }
});
```

**Comment by gautamsi** [comment]
I have done this already, missed a field which is masked in `admin-ui`. Basically I want this field to be masked and not show encrypted characters.

Text field can have following options to help support this. 
`maskCharacter: '*'` - renders test field with password like field on display, when you want to change you can unmask to view content and make changes. 
`encrypt: Function` - encrypt hook to encrypt the content
`compare: Function` - for comparing this for equality, similar to the password field hashing but this time it is reversible - what a developer want. 
`decrypt: Function` - optional for scenario like data at rest

`encrypt` and `decrypt` can also be extended to more fields to support data at rest like situation. These function can also be in the keystone lib to support generic situation like salt based encryption, or public-private key based encryption.

**Comment by VinayaSathyanarayana** [comment]
Thanks @gautamsi 

This is needed for all field types and not just Strings.

I would suggest that we separate the display and encryption
// Display
// none - show as is, 
// * - show only *s, 
// last4char - show only last 4 chars
// function - maskfunc(user,fieldvalue) - This should take the user as an input - as masking could be 
// different for different users - some are allowed to see the value, and some are not
displayMask: none | * | last4char | function


Encryption is to support Encryption at Rest requirement

// Field Encryption Options
// none - no encryption (default),
// true - encrypt using default keys provided in List Creation and/or System/App Level
// functionSet - funcSet(encrypt,decrypt,compare) use the function for encryption, decryption,comparison
encryptField:  none | true | function

// List Encryption Options
// none - no encryption (default),
// true - encrypt using default keys provided in List Creation and/or System/App Level
// encryptKey = key
// functionSet - funcSet(encrypt,decrypt,compare) use the function for encryption, decryption,comparison

Question: How to handle if the encrypted field is part of  / used in Virtual or Calculated Field

**Comment by VinayaSathyanarayana** [comment]
@gautamsi Is your PR Merged? Would like this functionality to be part of Base/core KeystoneJS 5

**Comment by gautamsi** [comment]
There was no PR for this, I had done that for my customer without extending keystone keystone

**Comment by VinayaSathyanarayana** [comment]
@gautamsi  - can you provide a PR for this?
@jesstelford - Please prioritize this.

**Comment by VinayaSathyanarayana** [comment]
Would prefer if this is part of keystone at the earliest

**Comment by VinayaSathyanarayana** [comment]
Would love to have this feature in Keystone-5

**Comment by bladey** [comment]
Hi @VinayaSathyanarayana,

**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
