### ISSUE TITLE
Support TimeOfDay field type

### ISSUE THREAD

**Issue by tinganho** [keystonejs/keystone#1453]
Can't really do opening hours correctly right now for a client website.

```
Mon-Fri 10am - 22pm
Sat 10am - 23pm  
```

**Comment by WingedToaster** [comment]
+1
Should we try to find a good time picker ui to use for this? This one seems decent...any others?
http://jquense.github.io/react-widgets/docs/#/datetime-picker

I'm not a big fan of this one...takes too many clicks to get the time that you want.
http://zippyui.com/react-time-picker/

**Comment by tinganho** [comment]
Maybe also have TimeOfDayRange as well. That support start and end time.

**Comment by ppiekarczyk** [comment]
@WingedToaster if you are talking about an Admin UI, that will be taken care of via Elemental
http://elemental-ui.com/date-picker

It's just a matter of implementing a solution :)

**Comment by ttsirkia** [comment]
This is kind of same as in #1171

**Comment by mxstbr** [comment]
Closing as a duplicate of #1171, thanks very much for notifying us of the need for this field type, we'll take a look!
