### ISSUE TITLE
Is it possible to disable the SASS middleware?

### ISSUE THREAD

**Issue by rmilesson** [keystonejs/keystone#1454]
I want to handle all my CSS preprocessing separate from Keystone and have no need for the SASS middleware. Is it possible to disable it?

**Comment by internetErik** [comment]
Hi,

if you comment out/delete this line in your keystone.init() it should stop using the sass middleware (you also don't need it installed then.):
`'sass': 'public',`

Somebody tell me if this is incorrect, but it works for me.

**Comment by rmilesson** [comment]
Cool! I'll check it out!

**Comment by rmilesson** [comment]
This worked beautifully.
