### ISSUE TITLE
TinyMCE events not firing

### ISSUE THREAD

**Issue by mattfordham** [keystonejs/keystone#1455]
I am attempting to use the [paste_postprocess] (http://www.tinymce.com/wiki.php/Configuration:paste_postprocess) hook within `wysiwyg additional options`, like so...

```
'wysiwyg additional options': {
  paste_postprocess: function(plugin, args) {
        console.log(args.node);
  } 
}
```

It seems to have no effect. Also, I attempted using the `setup` callback... same problem. Is it possible functions defined here don't got through to the front-end... and only string config settings?

**Comment by mattfordham** [comment]
It seems this line is the issue: https://github.com/keystonejs/keystone/blob/0293651c97ecefd1718b1bcde0712a2705e5d261/templates/views/list.jade#L12

JSON.stringify strips out any function members. 

Any refactor ideas that would allow functions to pass through?

**Comment by mxstbr** [comment]
Due to age, I'll close this issue—we appreciate you submitting it, if this is still something you're willing to look into I'll gladly point you in the right direction!
