### ISSUE TITLE
Worker?

### ISSUE THREAD

**Issue by okvic77** [keystonejs/keystone#1456]
What can be the best way for work with Keystone in the Background. The web process and the WORKER process, for send email, check data, etc.

```javascript
keystone.start(); // This but without mount a server.
```

**Comment by morenoh149** [comment]
That sounds ambitious. Share your email with me to join the Slack channel and discuss next steps.

**Comment by brianjd** [comment]
I was playing with something like this several months ago.  Though it never made it out of development in my project, for my purposes I simply used a standalone worker/queue process (à la Heroku).  It will be interesting to see the direction people want to go with this.  But having predefined job templates, and queue visibility from directly within keystone/the Admin UI would be cool.

**Comment by ttsirkia** [comment]
I'm running another Node process with code like this:

```javascript
var mongoose = require('./node_modules/keystone/node_modules/mongoose');
var keystone = require('keystone');

keystone.init({'name': 'MyApp'});
keystone.import('models');

// ************************************************************************************************

var MyModel = keystone.list('MyModel');

mongoose.connect('localhost', 'julia');
mongoose.connection.on('open', function() {

  // do something

});
```

You could use `setInterval` and other similar approaches here to run periodical tasks.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)!
