### ISSUE TITLE
Deployment on Digitalocean posible?

### ISSUE THREAD

**Issue by t0t** [keystonejs/keystone#1461]
Hello,
How can I do a deployment on Digitalocean?
I've created a MEAN droplet and can access to ssh to the main folder but no idea on how put the keystone files and Mongo files. I would like to push there my public static content folder from github but what about the other files?
thanks.
![captura de pantalla 2015-06-13 a las 3 45 22](https://cloud.githubusercontent.com/assets/6004806/8142439/bbe4f202-117c-11e5-9f3c-50f7ef0d1299.png)

**Comment by morenoh149** [comment]
try the gitter

**Comment by t0t** [comment]
Maybe is easy for me with Heroku
