### ISSUE TITLE
Backup function

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#1464]
Hello, everyone.
Keystone is the best CMS in my opinion, but I can't find how to backup the site.
So I want suggest my way. Maybe I was invent a bicycle, but...
I was create a model 'Backup.js'
```
var keystone = require('keystone'),
	Types = keystone.Field.Types,
	exec = require('child_process').exec,
	spawn = require('child_process').spawn,
	moment = require('moment'),
	path = require('path'),
	fs = require('fs'),
	bytes = require('bytes');

/**
 * Backup Model
 * =============
 */

var Backup = new keystone.List('Backup', {
	autokey: { from: 'name', path: 'key', unique: true },
	defaultColumns: 'name, url, size, date'
});

Backup.add({
	name: {	type: String, label: 'Имя', index: true },
	url: { type: Types.Url },
	size: { type: String, label: 'Размер'},
	date: { type: Types.Datetime, default: Date.now, label: 'Дата' }
});

Backup.schema.pre('save', function(next) {
	this.wasNew = this.isNew;
	if (this.wasNew) {
		this.createBackup(next);
	}
	else {
		next();
	}
});

Backup.schema.pre('remove', function (next) {
	fs.unlink('./node_modules/keystone/admin/public/'+this.url, function (err) {
  console.log('Result', err);
	});
		next();
});

Backup.schema.methods.createBackup = function(next) {
	var dir = './node_modules/keystone/admin/public/',
	      prefix = 'backUp/',
	       backup = this,
		filename = 'backup-' + moment(backup.date).format('YYYY.MM.DD-hh.mm.ss') + '.tar.bz2',
		args = ['--db', keystone.mongoose.connections[0].name, '--out', './backup/'],
		tar_args = ['--exclude=./node_modules', '-cjf', dir + prefix + filename, '.'],
		mongodump = spawn('/usr/bin/mongodump', args);
		backup.url = prefix+filename;
	path.exists(dir+prefix, function(exists) {
		if (!exists) { // for first run
			exec('mkdir ./backup');
			exec('mkdir '+dir+prefix);
		}
	});
	mongodump.stderr.on('data', function(data) {
		console.log('stderr: ' + data);
	});
	mongodump.on('exit', function(code) {
		if (code === 0) {
				var tar = spawn('tar', tar_args);
				tar.on('exit', function(data) {
					backup.size = bytes(fs.statSync(dir+prefix+filename)["size"]);
					next();
				});
		} else {
			next();
		}
	});
}
Backup.defaultSort = '-date';
Backup.register();
```
Then in Admin panel you create new record and save without modifications. To download the file you need to return in backup records list and click on the filename.
The mongo database dump is in the 'backup' folder in the downloaded file.
The backup file is very small, because make backup of node_modules isn't need.
p.s. this is for the local mongodb server.

**Comment by creynders** [comment]
I think the "normal" approach is to use [`mongodump`](http://docs.mongodb.org/manual/reference/program/mongodump/) At least that's how I do it.

I set up a separate git repo for the DB backups and use a cronjob that calls a `.sh` script at regular intervals, which does a mongodump, adds and commits to git.
Benefits: incremental, regular backups which are taggable and easily checked in and out.

This is obviously for simple, small applications.

**Comment by w01fgang** [comment]
But for client who uses the backup function the "normal" is not to use strange "mongodump" word.
The client want to see a normal backup function. I think it is more easy to use than mongodump.
All CMS have the backup fuction. I think it is "De facto" standard.

**Comment by morenoh149** [comment]
@w01fgang make a pull request. A UI to backup a keystone site would be useful. I agree.

**Comment by creynders** [comment]
@w01fgang sorry, I didn't realise it was necessary to be able to trigger it from the admin UI. I thought you meant any kind of backup. Agree with @morenoh149 it would be useful.

**Comment by creynders** [comment]
Closing this since it's not really an issue. A PR is still welcome though!
