### ISSUE TITLE
How to do polymorphism?

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1465]
Hi,

I have a ```Tag``` model which can be attached to many target models.

e.g.

```

Deal.add({
...
taggable_type:  {...}
 taggable_id: {　...},
  
});

```
Or
```
Deal.add({
...
taggable: { type: Types.Relationship, ref: 'Tag'},
...
});

```

Then  how to define the relationship in ```Tag``` model?
```
Tag.relationship({ path: 'objects', ref: '???', refPath: 'taggable' });
```

Thanks,

**Comment by martinduparc** [comment]
You should be able to do ```Tag.relationship({ path: 'objects', ref: 'Deal', refPath: 'taggable' });```

**Comment by arthurtalkgoal** [comment]
Hi @martinduparc ,

Thanks for your advise, 

The problem is the ***ref*** can be ```Deal, Post, Page``` etc.

Thanks,
Arthur

**Comment by arthurtalkgoal** [comment]
In Rails e.g.

```
class TeachingAssistant < ActiveRecord::Base
  belongs_to :ta_duty, polymorphic: true
end
```

ref: http://www.gotealeaf.com/blog/understanding-polymorphic-associations-in-rails

**Comment by webteckie** [comment]
@arthurtalkgoal would the work that @lojack did recently with adding  support for parent lists help you here?  Perhaps taggable should be a parent list to your other lists?

**Comment by martinduparc** [comment]
@arthurtalkgoal Do you want to display all relationships in the admin?

**Comment by arthurtalkgoal** [comment]
Hi @webteckie , thanks first, not quite sure if parent lists are same concept of polymorphism. Let me have a look

What I found there's common relationship where a list/model is relate to a dynamic type of lists/models; where you can't predefine the belongs to type.


e.g. Tag belongs to taggables (can be posts, deals, people);
Students belongs to Subjects (can be Math, English, Chinese);
Asset belongs to Album (can be Images, Videos, Files, etc).

**Comment by creynders** [comment]
@arthurtalkgoal haven't tested it out, but I'm pretty confident this will work; you need to add the relationship declaration for each model. I.e:

```js
Tag.relationship({ path: 'objects', ref: 'Deal', refPath: 'taggable' });
Tag.relationship({ path: 'objects', ref: 'Post', refPath: 'taggable' });
```

**Comment by creynders** [comment]
@arthurtalkgoal did the above work?

**Comment by arthurtalkgoal** [comment]
Hi @creynders ,

Sorry for the late response. I have updated my other codes until today.

I have tried:
```
Tag.relationship({ path: 'taggables', ref: 'Deal', refPath: 'tags' });
Tag.relationship({ path: 'taggables', ref: 'Company', refPath: 'tags' });
```

But in the admin UI, Tag model ***only display the Company*** in the Tag relationships section.

I bet the first statement is overriden by the 2nd statement.

The objective of my polymorphic setting is Tag can easiler search all it's taggables independent of its types.

**Comment by arthurtalkgoal** [comment]
I found someone check about polymorphism in mongoose:

https://github.com/briankircho/mongoose-schema-extend/issues/25

```
+1 We also need to have polymorphism within an array of subdocuments. When I use the base schema as the type in the array definition, none of the fields in the extended schemas are saved. When I use a mixed schema type, the _type discriminator key does not get saved.
```

seems that it's the mongoose community still looking for a handling on the polymorphism.

It's very cool if Tag and populate all it's taggables independent of types in an array.

**Comment by creynders** [comment]
Argh, my bad, `path` should have a unique name each time, i.e.:

```js
Tag.relationship({ path: 'tagsInDeal', ref: 'Deal', refPath: 'tags' });
Tag.relationship({ path: 'tagsInCompany', ref: 'Company', refPath: 'tags' });
```

**Comment by creynders** [comment]
Closing this, since I think it's solved; if not, please reopen.
