### ISSUE TITLE
Windows 8 Installation Error

### ISSUE THREAD

**Issue by i007422** [keystonejs/keystone#1467]
All our resources using Windows 8 get this error attempting to install Keystone JS. For the Mac users it works fine.

Any ideas how to resolve this issue?

C:\Users\i007422\github\Test>npm install -g generator-keystone
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
generator-keystone@0.3.5 C:\Users\i007422\AppData\Roaming\npm\node_modules\generator-keystone
├── colors@1.0.3
├── keystone-utils@0.1.13 (html-stringify@0.0.3, underscore@1.7.0, i@0.3.3)
├── lodash@3.7.0
└── yeoman-generator@0.17.7 (dargs@2.1.0, isbinaryfile@2.0.4, class-extend@0.1.1, rimraf@2.4.0, diff@1.4.0, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.2, debug@1.0.4, cross-spawn@0.2.9, nopt@3.0.2, grouped-queue@0.3.0, chalk@0.5.1, run-async@0.1.0, shelljs@0.3.0, mkdirp@0.5.1, file-utils

C:\Users\i007422\github\Test>yo keystone

Welcome to KeystoneJS.

? What is the name of your project? My Site
? Would you like to use Jade, Swig, Nunjucks or Handlebars for templates? [jade | swig | nunjucks | hbs] jade
? Would you like to use LESS or SASS for stylesheets? [less | sass] sass
? Would you like to include a Blog? Yes
? Would you like to include an Image Gallery? Yes
? Would you like to include a Contact Form? Yes
? What would you like to call the User model? User
? Enter an email address for the first Admin user: scott.boudreau@sap.com
? Enter a password for the first Admin user: admin
? Would you like to include gulp or grunt? [gulp | grunt] grunt
? Would you like to create a new directory for your project? No
? ------------------------------------------------
    KeystoneJS integrates with Mandrill (from Mailchimp) for email sending.
    Mandrill accounts are free for up to 12k emails per month.
    Would you like to include Email configuration in your project? Yes
? ------------------------------------------------
    Please enter your Mandrill API Key (optional).
    See http://keystonejs.com/guide/config/#mandrill for more info.

    You can skip this for now (we'll include a test key instead)

    Your Mandrill API Key:
? ------------------------------------------------
    KeystoneJS integrates with Cloudinary for image upload, resizing and
    hosting. See http://keystonejs.com/docs/configuration/#services-cloudinary for more info.

    CloudinaryImage fields are used by the blog and gallery templates.

    You can skip this for now (we'll include demo account details)

    Please enter your Cloudinary URL:
? ------------------------------------------------
    Finally, would you like to include extra code comments in
    your project? If you're new to Keystone, these may be helpful. Yes
   create package.json
   create .env
   create .jshintrc
   create keystone.js
   create .editorconfig
   create .gitignore
   create Procfile
   create Gruntfile.js
   create grunt\concurrent.js
   create grunt\express.js
   create grunt\jshint.js
   create grunt\node-inspector.js
   create grunt\nodemon.js
   create grunt\sass.js
   create grunt\watch.js
   create models\User.js
   create models\Post.js
   create models\PostCategory.js
   create models\Gallery.js
   create models\Enquiry.js
   create routes\index.js
   create routes\middleware.js
   create routes\emails.js
   create routes\views\index.js
   create routes\views\blog.js
   create routes\views\post.js
   create routes\views\gallery.js
   create routes\views\contact.js
   create templates\layouts\default.jade
   create templates\mixins\flash-messages.jade
   create templates\views\errors\404.jade
   create templates\views\errors\500.jade
   create templates\views\index.jade
   create templates\views\blog.jade
   create templates\views\post.jade
   create templates\views\gallery.jade
   create templates\views\contact.jade
   create templates\emails\enquiry-notification.jade
   create updates\0.0.1-admins.js
   create public\fonts\glyphicons-halflings-regular.eot
   create public\fonts\glyphicons-halflings-regular.svg
   create public\fonts\glyphicons-halflings-regular.ttf
   create public\fonts\glyphicons-halflings-regular.woff
   create public\fonts\glyphicons-halflings-regular.woff2
   create public\images\logo-email.gif
   create public\images\logo.svg
   create public\js\bootstrap\affix.js
   create public\js\bootstrap\alert.js
   create public\js\bootstrap\bootstrap-3.3.4.js
   create public\js\bootstrap\bootstrap-3.3.4.min.js
   create public\js\bootstrap\button.js
   create public\js\bootstrap\carousel.js
   create public\js\bootstrap\collapse.js
   create public\js\bootstrap\dropdown.js
   create public\js\bootstrap\modal.js
   create public\js\bootstrap\npm.js
   create public\js\bootstrap\popover.js
   create public\js\bootstrap\scrollspy.js
   create public\js\bootstrap\tab.js
   create public\js\bootstrap\tooltip.js
   create public\js\bootstrap\transition.js
   create public\js\jquery\jquery-1.11.2.js
   create public\js\jquery\jquery-1.11.2.min.js
   create public\js\jquery\jquery-2.1.3.js
   create public\js\jquery\jquery-2.1.3.min.js
   create public\favicon.ico
   create public\styles\bootstrap\_bootstrap-compass.scss
   create public\styles\bootstrap\_bootstrap-mincer.scss
   create public\styles\bootstrap\_bootstrap-sprockets.scss
   create public\styles\bootstrap\_bootstrap.scss
   create public\styles\bootstrap\bootstrap\_alerts.scss
   create public\styles\bootstrap\bootstrap\_badges.scss
   create public\styles\bootstrap\bootstrap\_breadcrumbs.scss
   create public\styles\bootstrap\bootstrap\_button-groups.scss
   create public\styles\bootstrap\bootstrap\_buttons.scss
   create public\styles\bootstrap\bootstrap\_carousel.scss
   create public\styles\bootstrap\bootstrap\_close.scss
   create public\styles\bootstrap\bootstrap\_code.scss
   create public\styles\bootstrap\bootstrap\_component-animations.scss
   create public\styles\bootstrap\bootstrap\_dropdowns.scss
   create public\styles\bootstrap\bootstrap\_forms.scss
   create public\styles\bootstrap\bootstrap\_glyphicons.scss
   create public\styles\bootstrap\bootstrap\_grid.scss
   create public\styles\bootstrap\bootstrap\_input-groups.scss
   create public\styles\bootstrap\bootstrap\_jumbotron.scss
   create public\styles\bootstrap\bootstrap\_labels.scss
   create public\styles\bootstrap\bootstrap\_list-group.scss
   create public\styles\bootstrap\bootstrap\_media.scss
   create public\styles\bootstrap\bootstrap\_mixins.scss
   create public\styles\bootstrap\bootstrap\_modals.scss
   create public\styles\bootstrap\bootstrap\_navbar.scss
   create public\styles\bootstrap\bootstrap\_navs.scss
   create public\styles\bootstrap\bootstrap\_normalize.scss
   create public\styles\bootstrap\bootstrap\_pager.scss
   create public\styles\bootstrap\bootstrap\_pagination.scss
   create public\styles\bootstrap\bootstrap\_panels.scss
   create public\styles\bootstrap\bootstrap\_popovers.scss
   create public\styles\bootstrap\bootstrap\_print.scss
   create public\styles\bootstrap\bootstrap\_progress-bars.scss
   create public\styles\bootstrap\bootstrap\_responsive-embed.scss
   create public\styles\bootstrap\bootstrap\_responsive-utilities.scss
   create public\styles\bootstrap\bootstrap\_scaffolding.scss
   create public\styles\bootstrap\bootstrap\_tables.scss
   create public\styles\bootstrap\bootstrap\_theme.scss
   create public\styles\bootstrap\bootstrap\_thumbnails.scss
   create public\styles\bootstrap\bootstrap\_tooltip.scss
   create public\styles\bootstrap\bootstrap\_type.scss
   create public\styles\bootstrap\bootstrap\_utilities.scss
   create public\styles\bootstrap\bootstrap\_variables.scss
   create public\styles\bootstrap\bootstrap\_wells.scss
   create public\styles\bootstrap\bootstrap\mixins\_alerts.scss
   create public\styles\bootstrap\bootstrap\mixins\_background-variant.scss
   create public\styles\bootstrap\bootstrap\mixins\_border-radius.scss
   create public\styles\bootstrap\bootstrap\mixins\_buttons.scss
   create public\styles\bootstrap\bootstrap\mixins\_center-block.scss
   create public\styles\bootstrap\bootstrap\mixins\_clearfix.scss
   create public\styles\bootstrap\bootstrap\mixins\_forms.scss
   create public\styles\bootstrap\bootstrap\mixins\_gradients.scss
   create public\styles\bootstrap\bootstrap\mixins\_grid-framework.scss
   create public\styles\bootstrap\bootstrap\mixins\_grid.scss
   create public\styles\bootstrap\bootstrap\mixins\_hide-text.scss
   create public\styles\bootstrap\bootstrap\mixins\_image.scss
   create public\styles\bootstrap\bootstrap\mixins\_labels.scss
   create public\styles\bootstrap\bootstrap\mixins\_list-group.scss
   create public\styles\bootstrap\bootstrap\mixins\_nav-divider.scss
   create public\styles\bootstrap\bootstrap\mixins\_nav-vertical-align.scss
   create public\styles\bootstrap\bootstrap\mixins\_opacity.scss
   create public\styles\bootstrap\bootstrap\mixins\_pagination.scss
   create public\styles\bootstrap\bootstrap\mixins\_panels.scss
   create public\styles\bootstrap\bootstrap\mixins\_progress-bar.scss
   create public\styles\bootstrap\bootstrap\mixins\_reset-filter.scss
   create public\styles\bootstrap\bootstrap\mixins\_resize.scss
   create public\styles\bootstrap\bootstrap\mixins\_responsive-visibility.scss
   create public\styles\bootstrap\bootstrap\mixins\_size.scss
   create public\styles\bootstrap\bootstrap\mixins\_tab-focus.scss
   create public\styles\bootstrap\bootstrap\mixins\_table-row.scss
   create public\styles\bootstrap\bootstrap\mixins\_text-emphasis.scss
   create public\styles\bootstrap\bootstrap\mixins\_text-overflow.scss
   create public\styles\bootstrap\bootstrap\mixins\_vendor-prefixes.scss
   create public\styles\site.scss
   create public\styles\site\_layout.scss
   create public\styles\site\_variables.scss
-

> v8-profiler@5.2.9 preinstall C:\Users\i007422\github\Test\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler
>

|
> v8-debug@0.4.6 preinstall C:\Users\i007422\github\Test\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
>

npm WARN optional dep failed, continuing default-browser-id@1.0.2
/

> ws@0.4.32 install C:\Users\i007422\github\Test\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
npm WARN optional dep failed, continuing fsevents@0.3.6spector\node_modules\node-inspector\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild \
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
\
> kerberos@0.0.9 install C:\Users\i007422\github\Test\node_modules\keystone\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\i007422\github\Test\node_modules\keystone\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
|
> bson@0.2.21 install C:\Users\i007422\github\Test\node_modules\keystone\node_modules\mongoose\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\i007422\github\Test\node_modules\keystone\node_modules\mongoose\node_modules\mongodb\node_modules\bson>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
/
> v8-profiler@5.2.9 install C:\Users\i007422\github\Test\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "C:\Users\i007422\github\Test\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.9\node-v14-win32-x64\profiler.node" is installed via remote

> v8-debug@0.4.6 install C:\Users\i007422\github\Test\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "C:\Users\i007422\github\Test\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v14-win32-x64\debug.node" is installed via remote
\
> node-sass@2.1.1 install C:\Users\i007422\github\Test\node_modules\node-sass
> node scripts/install.js

> node-sass@2.1.1 postinstall C:\Users\i007422\github\Test\node_modules\node-sass
> node scripts/build.js

`win32-x64-node-0.12` exists; testing
Binary is fine; exiting
-
> cld@2.4.0 install C:\Users\i007422\github\Test\node_modules\keystone\node_modules\keystone-utils\node_modules\limax\node_modules\cld
> node-gyp rebuild

C:\Users\i007422\github\Test\node_modules\keystone\node_modules\keystone-utils\node_modules\limax\node_modules\cld>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn c:\Python27 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\i007422\github\Test\node_modules\keystone\node_modules\keystone-utils\node_modules\limax\node_modules\cld
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! cld@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cld@2.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\i007422\github\Test\npm-debug.log

------------------------------------------------

Your KeystoneJS project is ready to go!

For help getting started, visit http://keystonejs.com/guide

We've included a test Mandrill API Key, which will simulate email
sending but not actually send emails. Please replace it with your own
when you are ready.

We've included a demo Cloudinary Account, which is reset daily.
Please configure your own account or use the LocalImage field instead
before sending your site live.

To start your new website, run "node keystone".

C:\Users\i007422\github\Test>

**Comment by webteckie** [comment]
@i007422 assuming you have Visual Studio installed you may want to try:

```
npm install --msvs_version=2012
(or whatever VS version you have)
```

Not sure about this one but you may also need to install python and do add to the previous line since there's also an error above that can't find python:

```
--python=<install-dir>\python.exe
```

I always just install with just the msvs_version and works fine.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)!
