### ISSUE TITLE
Display relationships in admin lists

### ISSUE THREAD

**Issue by martinduparc** [keystonejs/keystone#1468]
Is it possible to display relationship values (e.g. a parent) in an admin list using `defaultColumns`?

In the following example, I would to display the parent User for each Post.

```
User.add({
    name: { type: String, required: true },
    posts: { type: Types.Relationship, ref: 'Post', many: true }
});

------------------------------

Post.add({
    title: { type: String, required: true }
});

Post.relationship({ path: 'users', ref: 'User', refPath: 'posts' });

```

Thanks!

**Comment by morenoh149** [comment]
I think there are several issues requesting this. https://github.com/keystonejs/keystone/issues/564 https://github.com/keystonejs/keystone/issues/23
