### ISSUE TITLE
Store more meta information about CloudinaryImages

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1470]
The cloudinaryImage type currently stores filename, mimetype, publicURL, etc.

We're missing other meta information such as:

- width
- height
- width/height ratio

The width/height ratio can be particularly useful for a query such as:

```graphql
query {
  User(id: "...") {
    avatar {
      publicUrl: publicUrlTransformed(transformation: { width: '300' })
      ratio
    }
  }
}
```

Then you can render a placeholder while the image loads:

```javascript
if (isLoading) {
  return (
    <div css={[loadingStyles, { width: 300, height: 300 / data.User.avatar.ratio }]} />
  }
} else {
  return (
    <img src={data.User.avatar.ratio} />
  )
}
```

**Comment by dcousens** [comment]
> width/height ratio

https://github.com/keystonejs/keystone-5/issues/1117
