### ISSUE TITLE
Offline Docs

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#1471]
Consider submitting docs to Dash https://kapeli.com/docsets

**Comment by weekwood** [comment]
+1

**Comment by ppiekarczyk** [comment]
:+1: and http://www.devdocs.io

**Comment by morenoh149** [comment]
Come upvote keystoneJS for Devdocs.io (it's under javascript [todo] all the way at the bottom) https://trello.com/b/6BmTulfx/devdocs-documentation

We can help by writing a scraper https://github.com/Thibaut/devdocs#scraper

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/offline-docs!
