### ISSUE TITLE
`Select` field type: better "default default" and supplying `options` as a Map

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#1471]
Right now the `Select` field supports the standard `defaultValue: ...` and `knexOptions: { defaultTo: ... }` options. If neither of these are suppled, fields defaults to `null` or (unset in Mongo I guess?).

All this is fine but I often find myself wanting to default the value to the first of the supplied options, eg:

```js
   status: {
      type: Select,
      options: statusOptions,
      defaultValue: statusOptions[0],  // <-- this is clunky
   },
```

This is also ok, but it kinda breaks the flexibility of the `options` option which, as per [the docs](https://github.com/keystonejs/keystone-5/tree/master/packages/fields/src/types/Select#options), can be a list, array of strings or array  of objects. So when I'm building my list I need to know which format is being used, ie.. is it `statusOptions.split(',')[0]`, `statusOptions[0]` or `statusOptions[0].value`? If, later, `statusOptions` is converted from an array of strings to an array of objects, for example, my fields keep working but the default value breaks. 😕

**Solution 1**

There's already logic for resolving these different `options` formats in the field type, let's make it easy for solution devs and add a `defaultToFirstOption` option or something. Then my field def can be..

```js
   status: {
      type: Select,
      options: statusOptions,
      defaultToFirstOption: true,
   },
```

.. without needing to worry about the format of my `statusOptions` variable.

**Solution 2** (my preference)

Maybe defaulting to using the first option as the default should itself be the default behaviour and `null`/`undefined` values should only be allowed _if they're specified as an option_. After all, the solution dev is literally saying "these are the valid options for this field"; if they want `null`/`undefined` to be allowed they can supply it as an option.

This would also require the field type to accept `options` as a Map (Object keys are always strings so can't be null).

With this solution, the `statusOptions` variable used above could be defined as.. 

```js
// `null` values allowed, defaults to 'pending'
statusOptions = ['pending', 'processed', 'canceled', null];

// `undefined` works the same
statusOptions = ['pending', 'processed', 'canceled', undefined];

// `null` values allowed and also the default option
statusOptions = [null, 'pending', 'processed', 'canceled'];

// Can set a  label for `null` values using a Map
statusOptions = new Map()
   .set(null, '(No value stored)')
   .set('pending', 'Pending processing')
   .set('processed', 'Processing complete')
   .set('canceled', 'Canceled by user');
```

In the common case, this solution makes our field definitions a lot simpler, eg:

```js
   status: { type: Select, options: statusOptions },  // 😀
```

**Comment by jesstelford** [comment]
> `null`/`undefined` values should only be allowed _if they're specified as an option_.

🤔 Then how does `isRequired: false` work? All other fields default to `null` when `isRequired: false`.

> `defaultToFirstOption: true`

What then happens if they specify both `defaultValue` _and_ `defaultToFirstOption`? It becomes a documentation / good error message design problem, but I feel like it's starting to muddy the waters a bit.

---

A possible third option:

```javascript
status: {
  type: Select,
  options: statusOptions,
  defaultValue: Select.DEFAULT_TO_FIRST_OPTION,
}
```

Then in the `Select` type:

`index.js`
```javascript
const { DEFAULT_TO_FIRST_OPTION, /* ... */ } = require('./Implementation');

export default {
  DEFAULT_TO_FIRST_OPTION
};
```

`Implementation.js`
```javascript
const DEFAULT_TO_FIRST_OPTION = Symbol('Default to first option');

// ...

constructor({ defaultValue, options }) {
  const normalisedOptions = normaliseOptions(options);
  if (defaultValue === DEFAULT_TO_FIRST_OPTION) {
    defaultValue = normalisedOptions[0];
  }
}
```

Some benefits:
- Meets the requirement of defaulting to the first item
- Will continue to work no matter what option formats we support in the future (eg `Map`)
- Doesn't overload what `isRequired: false` does for defaults
- Is explicit
- Doesn't require a different option which effects `defaultValue` differently to the `defaultValue` setting.

**Comment by jossmac** [comment]
> array of strings

That doesn't sound right... Couldn't we just enforce a shape?

**Comment by MadeByMike** [comment]
This seems like a minor problem and `defaultValue: statusOptions[0]` seems about as clunky as anything else suggested.

I'd like to suggest leaving as is and closing as `wont-fix` :/
