### ISSUE TITLE
Custom Mutations can throw errors due to double-resolution of data

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1473]
Let's say I have a custom mutation setup, like so:

```javascript
keystone.createList('Post', {
  fields: {
    title: { type: Text },
    publishedAt: { type: DateTime },
  },
  mutations: [
    {
      schema: 'relatedPosts(related_to: ID!): [Post]',
      resolver: async (obj, args, context, info, { query }) => {
        // ... Some logic to determine the related items
        const relatedIds = /* ... */;

        const { allPosts } = await query(
          `
            query getPosts($where: PostWhereInput!) {
              allPosts(where: $where) {
                id
                title
              }
            }
          `,
          { variables: { where: { id_in: relatedIds } } }
        );

        return allPosts;
      }
    }
  ],
});
```

This works fine; the client gets an array of `Post` items, each with `{ id, title}`.

However, if we modify that query to also fetch the `publishedAt`, we get an error:

```javascript
keystone.createList('Post', {
  fields: {
    title: { type: Text },
    publishedAt: { type: DateTime },
  },
  mutations: [
    {
      schema: 'relatedPosts(related_to: ID!): [Post]',
      resolver: async (obj, args, context, info, { query }) => {
        // ... Some logic to determine the related items
        const relatedIds = /* ... */;

        const { allPosts } = await query(
          `
            query getPosts($where: PostWhereInput!) {
              allPosts(where: $where) {
                id
                title
                publishedAt
              }
            }
          `,
          { variables: { where: { id_in: relatedIds } } }
        );

        return allPosts;
      }
    }
  ],
});
```

Error:

```
Cannot call function `.toISOString()` of undefined
```

🤯

Turns out this is because the data we are returning from `allPosts` looks like this:

```javascript
[
  { id: "...", title: "...", publishedAt: "2019-08-09T02:40:25.964Z" },
  { id: "...", title: "...", publishedAt: "2019-03-01T02:30:25.964Z" },
  { id: "...", title: "...", publishedAt: "2019-07-09T02:50:25.964Z" },
  { id: "...", title: "...", publishedAt: "2019-01-09T02:43:25.964Z" },
]
```

And we're returning that from our resolver. But GraphQL isn't done with the data yet! It sees the field `publishedAt`, and says _"A-ha! I know that field, and I know it has a resolver (from the `DateTime` field type), so I'm going to execute that resolver, and pass in the data `"2019-08-09T02:40:25.964Z"`"_.

The `DateTime` field resolver looks like this:

```javascript
  get gqlOutputFieldResolvers() {
    return { [`${this.path}`]: item => item[this.path] && item[this.path].toISOString() };
  }
```

Which tries to execute: `"2019-08-09T02:40:25.964Z".toISOString()`, and hence the error.

The same problem arises for `Relationship`s, etc.

I have no idea how to work around this :/

**Comment by gautamsi** [comment]
@jesstelford here is a diff of what I tried and things worked like it should, do not see any errors or exception thrown at any time for this. 

https://github.com/keystonejs/keystone-5/compare/master...gautamsi:issue%231473?expand=1

I only had to change the de-structuring properly. I tried two scenario.
` const { data: { allPosts } } = await query(`.

**Comment by gautamsi** [comment]
@jesstelford is this still an issue?

**Comment by gautamsi** [comment]
@jesstelford  is this still relevant?
this feature is replaced in #1532.

**Comment by jesstelford** [comment]
Yep, still an issue even with `keystone.extendGraphQLSchema()` :(
