### ISSUE TITLE
How to delete multiple items at once in Keystone Admin UI

### ISSUE THREAD

**Issue by xianlin** [keystonejs/keystone#1474]
say you are in Admin UI of keystone and want to delete all your posts dated between 1st day and 10th day of this month, you can filter the date and find all posts. But you have to click the delete icon next to the record entry one by one to delete them all.

Is there a faster way to do that with Admin UI? or I have to write my own code? Thanks.

**Comment by JedWatson** [comment]
This is something I've been meaning to add, we'll include it in the next major release (when the list is rendered by React)

**Comment by jonathanp** [comment]
This was added in #1819
