### ISSUE TITLE
Replace mongoose with loopback

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#1477]
I was discussing today with @BerkeleyTrue about keystone memory size consumption. He suggested perhaps moving to loopback due to it's lower memory footprint. Is anyone else knowledgeable about this topic? please chime in.

**Comment by mikeblakeney** [comment]
I can tell you from my experience that loopback has a much harder learning curve to get started.  One of the biggest factors for keystone with me was that you get a nice admin UI for free and it's very clear as to how it's inner workings operate.  There's not a lot of magic that happens.

**Comment by morenoh149** [comment]
? I've never used loopback. I was suggesting changing the underlying implementation. The UI exposed to the user shouldn't change.

**Comment by mikeblakeney** [comment]
that would work if you already have your admin built and just swap out the data service.  I couldn't tell you anything about the memory footprint though.  I moved on to keystone after I saw the 'free' admin ui.

**Comment by BerkeleyTrue** [comment]
Not sure what @mikeblakeney means by 'free'. Generally CMS have some sort of admin panel. I don't think @morenoh149 is advocating getting rid of the admin panel at all.

I've transitioned a more than a couple of projects that where using Mongoose to Loopback and have noticed a huge drop in memory usage and an huge decrease in startup time.

If Keystone where to replace Mongoose with Loopback I think it would be a huge win, but unfortunately it would not be a trivial swap and would be a huge api change. Especially when you considering that one (not the only) of the best features of Keystone is actually not a Keystone feature but the Mongoose query building api.

**Comment by mikeblakeney** [comment]
Free as in not a lot of work to get the admin ui going.  the idea of using loopback instead of mongoose is very interesting.  I agree with @berkleytrue in that it would be a large undertaking with a huge advantage.

**Comment by JedWatson** [comment]
It's interesting but Loopback is not, as far as I am aware, anything close to a drop-in replacement for mongoose, and the biggest change would be that anyone building an app on Keystone would have to switch from mongoose to loopback to implement their data layer. We're talking about a massive breaking change here, and putting anyone who works with Keystone through the loopback learning curve to develop their app.

Loopback also provides a lot of "framework", and as far as I've seen effectively replaces express as the web server (or, rather, api layer, which then leaves you to implement your own web server).

I'm more interested in getting Keystone's `List` definitions documented as a standard, and extracted from the core. Same with the Admin UI.

Once we've converted the Admin UI to an SPA that runs against a JSON API, as long as you can feed it the correct metadata (models, fields, etc) it could really run against any back-end, which is very interesting, and makes the whole system more useful. Keystone's current back-end (mongoose + express + api) then simply becomes the _default_ option to use.

These are very draft thoughts, but a plan I've been working on in the background. Don't be offended but I'm going to close this issue and we can reopen the discussion later, as we've got a huge number of open issues and I'm now trying to cut down the number of open ideas / speculative issues as we get closer to the next major release.
