### ISSUE TITLE
Change to Port 80

### ISSUE THREAD

**Issue by DenDix** [keystonejs/keystone#1478]
Since I'm on Amazon Web Services, the only way I can see my web site is if I am on port 80 and can access on my home lap top. Tried to change the port by adding "keystone.set('port',80)" to keystone.js. But received these error messages when typing "node keystone" in the terminal:

------------------------------------------------
KeystoneJS Started:
Mendo is ready on port 3000
------------------------------------------------

^Cubuntu@ip-172-30-0-67:/var/nodes/stone/mendo$ node keystone
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at EventEmitter.app.listen (/var/nodes/stone/mendo/node_modules/keystone/node_modules/express/lib/application.js:595:24)
    at Object.events.onMount (/var/nodes/stone/mendo/node_modules/keystone/lib/core/start.js:134:31)
    at mounted (/var/nodes/stone/mendo/node_modules/keystone/lib/core/mount.js:601:29)
    at /var/nodes/stone/mendo/node_modules/keystone/node_modules/grappling-hook/index.js:71:5
    at process._tickCallback (node.js:448:13)

I don't know what to make of all that. Am I approaching things incorrectly?

**Comment by mikeblakeney** [comment]
You can set the port using the environment variable PORT .  You can set this on the system or use a .env file.  There's also an option to set the port in the keystone.js file.  Just check the under web server optionss http://keystonejs.com/docs/configuration/

Sometimes you have to be root or a sudo user to run services on ports at the lower port number ranges.  You can try that as well.

**Comment by mikeblakeney** [comment]
Ive also seen configs were you have a some proxy service listen on 80 or an ip tables route that forwards to the node process running on 3000.

**Comment by creynders** [comment]
I'd definitely recommend _not_ to set it to port 80, but rather use a proxy with port forwarding.

**Comment by medv** [comment]
AWS has routing settings somewhere under Security I think? Anyway you can make it accept on 80 and forward to 3000.

**Comment by DenDix** [comment]
I inserted "keystone.set('port',80);" into keystone.js and then ran "sudo node keystone" and it works.
Judging from the comments here, I should change my port in the iptables and also not use "sudo".
However, I'm guessing that AWS requires me to use "sudo", but I could be wrong. I also don't want to change my iptables out of fears that I'll break something else. Possibly if I had a better grasp of what I'm doing I could make the appropriate changes. Thanks for everyone's help.

**Comment by mikeblakeney** [comment]
I'd stick with changing the security group like @medv suggested.  You definitely don't want to run the service as sudo under production.

**Comment by medv** [comment]
AWS shouldn't require you to use sudo. Not sure what your iptables looks like, but AWS security groups essentially replace the need for a firewall. Correct me if I'm wrong, I have not used AWS in production, but when I experimented a few days ago I simply forwarded to 3000 using the AWS console.

**Comment by ppiekarczyk** [comment]
I would start by trying to update `process.env.PORT` to 80 first whether it's through the .env file or directly inside the code.

Keystone will first look for the port number via `process.env.PORT` as shown here:
https://github.com/keystonejs/keystone/blob/d20417d02a1704b46bfe732e627b87b08970be36/index.js#L49

**Comment by creynders** [comment]
Seriously, the only "good" solution is to forward. Any port under 1024 needs root access and running node as root is a [notoriously bad idea](http://syskall.com/dont-run-node-dot-js-as-root/)

For anyone stumbling here looking for answers:

### do not run your node app on port 80
use any kind of port forwarding/proxying/redirecting

### do not run node as `root`
which isn't necessary anyways if you don't run it on port 80
