### ISSUE TITLE
No confirmation warning on delete

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1479]
The "delete {type}" button on the item details view used to have a confirmation warning... in the latest version, it just immediately deletes, which is really unsafe. We need to put the confirmation back in.

**Comment by SlashmanX** [comment]
This is the same for the "reset changes" button. It seems that `data-confirm` isn't behaving as expected

**Comment by gerotakke** [comment]
I've got it fixed, the element wasn't in the DOM when the bind is done. I'm looking into github right now, this will be my very first pull request ;)

**Comment by JedWatson** [comment]
Great first pull request - thanks @gerotakke!
