### ISSUE TITLE
tracking for programmatically inserted data

### ISSUE THREAD

**Issue by ctaepper** [keystonejs/keystone#1486]
i have a keystone list, which gets its data from a external source. i run a script, that reads data from an external REST api and inserts/updates the data into mongodb using the keystone models. that is working fine, however i have set track=true for that list, but there is no track information saved, i'd like to have that though :)

my guess is, it is not working, because there is no current user, when i use the models in my code... is there a way to workaround that?

**Comment by ppiekarczyk** [comment]
I think the idea behind track is to keep track of changes made by the user. What sort of tracking are you looking for, if not based on the user?

Even so, what you can do is create a fake User model and then modify your import script to include an hidden `updatedBy` field?

That would look like this:

```javascript
 { type: Types.Relationship, ref: userModel, hidden: true, index: true };
```

https://github.com/keystonejs/keystone/blob/d20417d02a1704b46bfe732e627b87b08970be36/lib/schemaPlugins/track.js#L90

**Comment by ctaepper** [comment]
yes, i want to base it on a user. i would create an additional user, for example "importer"... the importer can create items and can also update items... but also a regular user can update items, so i need tracking who made the latest changes.

i am aware, that i can set those fields manually in the import script, i was just wondering, if there is way to automatically apply the user relation

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
