### ISSUE TITLE
Bikeshed: Types named by appearance vs function

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#149]
In #147, it was suggested to rename the type field from `Boolean` to `Checkbox` (to avoid conflicting with JS globals).

This implies we name the types after a specific appearance, rather than their functionality.

I propose we name the types after functionality as we have no control over what the appearance will be (in a client app).

In the case of #147, I think the type `Bool` is appropriate.

This also applies to the `Select` type. Naming it based on functionality (instead of appearance) would yield `Enum` as the type name.

**Comment by molomby** [comment]
Closed issue, I know, just dumping some thoughts.

There seems to be a bit of an assumption in this discussion that lists and fields will be not only visible but also editable in the admin UI. These terms (eg. `Checkbox`, `Select`) refer specifically to the _default_ interface used to edit those values.

Keep in mind that:

* Fields will sometimes not be editable though the admin UI
* Whole lists will sometimes not be editable though the admin UI
* Some installs won't use the admin UI at all 😱
* The appearance of the fields (for viewing and editing) are probably the most likely part of a field type to be customised

I can see how it's intuitive for more UI/frontend minded people to conceptualise fields in terms of their interface (and what's intuitive for that audience _is_ very important) but, it seems to me, that by doing so we're also tying the identity of field types to a facet of them that's most likely to change or be irrelevant in many cases.

This is also just comes down to my personal perspective I guess. When I'm creating a list schema I'm thinking about the data, not the interface. I don't care how a value will be edited by the user (if it even is), I'm thinking about the data types themselves. So, for me at least, terms like `Bool` or `Flag` are much more natural.

_On the other hand_, in some cases it's more complicated. Regarding `Select` fields -- they surface as `enum` in GraphQL but they're stored as a `String` in Mongoose and `text` on Knex. The Knex schema builder does support [`enum` columns](https://knexjs.org/#Schema-enum) but in Postgres they usually aren't [mapped to the native `enum` data type](https://github.com/tgriesser/knex/issues/394), they're stored as `text` with a constraint. So there can be a lot of confusion/variability around the underlying data too; the "interface" might be the most stable thing to name field types after in these cases.
