### ISSUE TITLE
View template engine & Email template engine are not consistent

### ISSUE THREAD

**Issue by sylvainlap** [keystonejs/keystone#1494]
Hi,

When setting the "view engine" in Keystone, the template engine is set for the views, but not for the emails. I think it should be more consistent if the configured "view engine" is used for views AND emails.

Regards,
Sylvain

**Comment by morenoh149** [comment]
I agree it'd be more consistent but customization is a feature. I recall one user interested in using multiple template engines within keystone itself (not even emails) and thought that would be a great feature to add to keystone as it's supported by express. See http://devdocs.io/express/index#app.engine

**Comment by mxstbr** [comment]
Closing this due to age and @morenoh149's A+ answer
