### ISSUE TITLE
Admin Pagination

### ISSUE THREAD

**Issue by joshjung** [keystonejs/keystone#1495]
It appears by default that lists on the admin page are paginated to 50 per page. Is there a way to adjust this number?

**Comment by morenoh149** [comment]
looks like `perPage` falls back to 50 in certain cases https://github.com/keystonejs/keystone/search?utf8=%E2%9C%93&q=perpage

**Comment by JedWatson** [comment]
You can set this option on the List. May be missing from the docs, if so we should add it.

```
var MyList = new Keystone.List('MyList', {
    perPage: 100
});
// or, later
MyList.set('perPage', 100);
```

**Comment by JedWatson** [comment]
Just checked and this does need to be added to the docs, I'll open an issue on the docs site.

**Comment by joshjung** [comment]
Perfect, thank you!

**Comment by playwolf719** [comment]
@JedWatson I do hope that you can make the doc with more details considering that it lacks mass of info. Thx.
