### ISSUE TITLE
[nodemon] watching 31,640 files - this might cause high cpu usage. To reduce use "--watch".

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#1497]
How can the gruntfile.js be updated to ignore node-modules?

**Comment by morenoh149** [comment]
@emaddoma are you refering to the gruntfile generated by the yeoman generator? https://github.com/keystonejs/generator-keystone

**Comment by emaddoma** [comment]
I am.  Should I submit this issue there instead?

**Comment by morenoh149** [comment]
it'd be better
