### ISSUE TITLE
Support for importing models given an array of locations

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1498]
As a user I would like to be able to configure an array of models to import.  For example:

keystone.set('models', keystone.import(['base-path', 'addons-path']);

PS:  seems fairly straightforward by updating the import method in https://github.com/keystonejs/keystone/blob/master/index.js to check if the input dirname is an array and by looping on the array calling doImport() for each resolved directory path.

**Comment by webteckie** [comment]
See PR 878ef7a

**Comment by mxstbr** [comment]
I think this works maybe? I'll close it for now, feel free to reopen!
