### ISSUE TITLE
Adminless Deployment

### ISSUE THREAD

**Issue by shauntrennery** [keystonejs/keystone#1501]
The current node_modules folder for a Keystone deployment contains over 120k files. Would it be possible to offer deployment / feature variations? 

i.e. 

Normal
Adminless
etc.

An alternative would be to select which features a deployment includes.

**Comment by mxstbr** [comment]
This is on the roadmap, with #2566 the admin interface will be completely decoupled which means we'll be able to get rid of a lot of those modules!
