### ISSUE TITLE
s3 file downloads

### ISSUE THREAD

**Issue by foobar8675** [keystonejs/keystone#1502]
I looked and hacked around the s3 field and filetypes trying to figure out a way to download s3 files from the admin interface - but found myself lost after not too long. Does anyone have any pointers or general steps I could try to follow?

The admin interface is awesome and really want to use keystone, but am stuck and do need to figure this out soon or go to another solution. (deletes too, but I think I may have hacked my way around that) So if anyone has any suggestions, it would be appreciated.

**Comment by mikeblakeney** [comment]
I'm actually in the middle of writing a more detailed article on this, but what I ended up doing for a project was adding a file link field that calculated the link and showing the link on the model's list view:

```javascript
    audioFileLink: {
      type: Types.Url,
      hidden: true,
      noedit: true,
      watch: true,
      value: function() {
        console.log(this.audioFile.url);
        return 'https:' + this.audioFile.url;
      },
      format: function(url) {
        console.log(url);
        return url;
      }
```

You can then display the link in the model's list view:

```javascript
AudioFile.defaultColumns = 'title, status|20%, audioFileLink, publishedAt|15%';
```

Also, if you wanted to display the link in the model instances's edit view then just set hidden to false or remove that property from the model definition.

**Comment by captainchung** [comment]
Hello @mikeblakeney , thanks so much for writing. I'm not sure I understand how to use the example. 

I have a gist https://gist.github.com/captainchung/a08e1901378f4b5dc2fa where I added your snippet `audioFileLink` as a key to an AudioFile object. I see in the admin tool, on creation of a new AudioFile, the filename function https://gist.github.com/captainchung/a08e1901378f4b5dc2fa#file-gistfile1-txt-L28  gets hit and can set the link value with a saved variable. https://gist.github.com/captainchung/a08e1901378f4b5dc2fa#file-gistfile1-txt-L17 

However, this only works on creation, which I have been doing via the admin. It doesn't work when retrieving a document. I also tried using a Pre hook on `find` but that gave an error I couldn't figure out.

Anyways, if you have any thoughts, it would be appreciated.

**Comment by mikeblakeney** [comment]
Hi @captainchung, my pleasure!  The watch property in the AudioFileLink tells keystone to update the field anytime something changes in the model (http://keystonejs.com/docs/database/#fields-watching).  

Your value function doesn't look correct.  You can refer to the model with 'this'.  So, try something like this: 
```javascript
value: function() {
        console.log(this.audioFile.url);
        return 'https:' + this.audioFile.url;
      }
```

I use the audioFileLink to provide a link in the model list.  If you just want to get a link to the file for use in your templates, then referencing the audioFile.url in your template or json or however you output, should be enough.

If you need more information on the pre/post hooks, you should read through the mongoose docs on middleware, http://mongoosejs.com/docs/middleware.html

**Comment by foobar8675** [comment]
Ah, I get it. Thank you!

**Comment by foobar8675** [comment]
Also, looking forward to your article. If you need a proof reader , let me know.
