### ISSUE TITLE
Select boxes for relationships seem to have a numeric limit in what they display

### ISSUE THREAD

**Issue by gerotakke** [keystonejs/keystone#1503]
I believe it is like this: when opening the dropdown, there's only X options displayed, but when using the search option, I can find others that are not included in the first displayed X entries.
I think that this is intentional and I don't think it's a problem, but I would expect some information in the UI. I'd try and implement this myself, by adding a last row like “... and more”.
Am I right and would that be the way you'd like to handle it?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
