### ISSUE TITLE
[Add Keystone to Existing Apps] How to Utilize Existing Mongoose Models

### ISSUE THREAD

**Issue by Plypy** [keystonejs/keystone#1508]
Based on the instruction given in WIKI, I modified my app.
Added this line to import my models defined.
```
keystone.imports('models')
```
Thing is, though I can access the keystone admin panel, I can't see anything. The panel is empty, no model monitored there.

Should I do a `list.register()` first to see it's shown in the panel. If it is, then how I can register a well-defined Mongoose model, or must I rewrite the model in keystone's `List` style?

Regards.

**Comment by robbyoconnor** [comment]
Open a JIRA issue and just use github for PRs

**Comment by shaond** [comment]
I have the same question, we have an existing app with quite a large number of models, but I'd love to integrate Keystone's Admin UI. It's just that a rewrite of our mongoose models might not be worth the pain.

**Comment by hustKiwi** [comment]
+1

**Comment by morenoh149** [comment]
@Plypy where is `imports` defined? it's not in keystone or mongoose.

@hustKiwi 
[list.register()](https://github.com/keystonejs/keystone/blob/ebe237477d78ab2e6d797903e357f23c56c32eb2/lib/list/register.js) is run from a mongoose object (I think) so try
```javascript
Keystone.prototype.register.call(yourMongooseObject)
```
and see if it get's wired up correctly.

**Comment by cameronjroe** [comment]
@Plypy Pretty sure the method is [`keystone.import`](https://github.com/keystonejs/keystone/wiki/How-to-Add-Keystone-to-an-Already-Existing-Express-App)

Alternatively, you can just `require('./models')` from your `keystone.js` file before the routes. https://github.com/JedWatson/keystone-demo/blob/master/keystone.js#L38

**Comment by AlexYegupov** [comment]
+1 to shaond question
Is there ability or future plans to allow using in keystone existing application mongoose models without necessity to redefine their duplicates via MyMongooseModel.add({...})

**Comment by creynders** [comment]
@AlexYegupov I can't quite imagine how that would work, since keystone lists add a lot of functionality. Some kind of mapping mechanism? E.g. a mongoose schema defines a field as a `string` but keystone'll need to know what kind of string that is. Is it a text field? Or is it a Url? Et cetera.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
