### ISSUE TITLE
Update Location Lat Lng by using Google Map

### ISSUE THREAD

**Issue by xianlin** [keystonejs/keystone#1509]
Hi, how can I update the Location Fields (Lat/Lng values) in Admin UI by drag/drop a point on the google map?

Any plan to implement this cool feature in React UI?

Basically we need to add a "Pin-point Location" button and by clicking on it, a google map "modal" window will pop up and you can drap and drop a point on the map and save to the Lat/Lng point.

**Comment by mxstbr** [comment]
There's plans, just nobody has done it yet! Take a look here: https://productpains.com/post/keystonejs/add-support-for-a-map-field
