### ISSUE TITLE
IE Caching Admin Pages (updates won't appear in back-end)

### ISSUE THREAD

**Issue by cantuket** [keystonejs/keystone#1511]
I'm experiencing a pretty sever error in the Admin Area with Internet Explorer 11 (likely other versions as well). After editing any Post fields in IE, the saved data is not populated in the Admin Area, because it is caching the initialized page with empty fields.

I've created a custom Keystone repo and so far I've tried...

1) Prevent caching on the front-end by adding this HTML (Jade) to keystone > templates > layout > base.jade
```
html
   head
      meta(http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate")
      meta(http-equiv="Pragma" content="no-cache")
      meta(http-equiv="Expires" content="-1")
   
   (body)

   head
      meta(http-equiv="Pragma" content="no-cache")
      meta(http-equiv="Expires" content="-1")
```

2) Prevent caching by setting these HTTP header parameters in keystone > app > browserify.js:86 ( under 'function send () { ' )
```
res.setHeader('Cache-Control', 'private, no-cache, no-store, max-age=0, proxy-revalidate, s-maxage=0'); 
res.setHeader('Expires', 'Sat, 12 Oct 1991 05:00:00 GMT');
res.setHeader('Pragma', 'no-cache'); 
res.setHeader('Vary', '*');
```

I'm pretty sure that I'm doing this completely wrong, but I believe option 2 (setting the HTTP header) is the right way to handle this. I'd really, really, really appreciate any hep on this because I'm likely going to lose my biggest client if I cant figure this out soon. Though I hate IE, I think that supporting the basic functionality for of newer versions is going to be integral to the success of the platform. All of my clients are finance, law and professional services so this will be a big issue for me going forward.

Thanks for any help

**Comment by jimulle** [comment]
I am experiencing a similar issue. If you refresh the page after you save does the newly saved data now show up (that is what is happening for me)?

**Comment by cantuket** [comment]
I'm not sure anymore it all depends on how IE is configured for you. My clients and I have just changed the cache setting in IE so now saved data is rendered every time for us, but this is far from an ideal solution. I'd really love to get this figured out before taking on another client running IE, which might be the case soon, especially since none of them have ever heard Keystone.js and convincing them away from Wordpress can be challenging enough as it is.

To prevent cacheing change...
Internet Options > General (tab) > Browsing History (section) >   Settings >  select: "Every time I visit the webpage" option

**Comment by jimulle** [comment]
I modified my IE settings to fix the issue but I am in the same boat with my users.

**Comment by cantuket** [comment]
I took another crack at this, but can't get it fixed. I added ...

```
res.header('Cache-Control', 'private, no-cache, no-store, must-revalidate');
  	res.header('Expires', '-1');
  	res.header('Pragma', 'no-cache');
```
To...
Keystone > Admin > Routes > Views > item.js
Keystone > Lib > Core > render.js 

, which is now setting the HTTP Headers to the correct Cache settings, but IE is still showing 'stale' pages. I started a repo here if anyone wants to help 

[Keystone no-cache admin](https://github.com/cantuket/keystone-no-cache)

**Comment by imaximym** [comment]
Hello! I found solution. To prevent caching in IE need to set header in moment when we get updated data from server - Keystone > Admin > api > item > get.js. 
Need to set header before sending json result
```javascript
res.header("Expires", "-1");
res.header("Cache-Control", "no-cache, no-store, private");

```

**Comment by cantuket** [comment]
Awesome, thanks @imaximym !

@morenoh149  Should this be implemented in new releases? It is a pretty big headache for all my clients on IE, which is almost all of them.

**Comment by morenoh149** [comment]
@cantuket @imaximym feel free to submit a PR

**Comment by mxstbr** [comment]
I think this was fixed? Let me know if not!
