### ISSUE TITLE
Updating Number and Boolean

### ISSUE THREAD

**Issue by yazevedopure** [keystonejs/keystone#1513]
I'm using a Keystone list to collect data from a form made by 4 steps.
At the end of the first step I save the list as a new document and for the following steps I update the same document using custom API calling `item.getUpdateHandler(req).process` sending back the correct `_id`

I've found that values for Number and Boolean fields are lost if I don't send back the whole document.

I fixed that in NumberType.js at line 89 changing from 
```
if ((value === undefined || value === '') && 'number' === typeof item.get(this.path)) {
	item.set(this.path, null);
	return;
}
```
to
```
if ((value === undefined || value === '') && 'number' === typeof item.get(this.path)) {
	item.set(this.path, item.get(this.path));
	return;
}
```

The same happens with booleans, (see BooleanType.js at line 60) but to get it working is necessary, from Admin UI, to send the field value even if it's false, otherwise it would be impossible to set a field to false after has been set to true.

I don't know if this is a real issue or is made this way for a certain reason. Please let me know!

**Comment by mxstbr** [comment]
This has been fixed with 0.4!
