### ISSUE TITLE
Get Local Time Display Instead of UTC Time by Editing Jade Template

### ISSUE THREAD

**Issue by xianlin** [keystonejs/keystone#1520]
I am using KeystoneJS default `Type.Datetime` in my List fields `datetime`.

In the `view` folder and `post.jade` file I have the below format line of code
```
td= post._.datetime.format("MMM Do YYYY, h:mm:ss a, Z")
```

It gives me the below format after rendering the web page from Jade

`Fri Jul 10 2015 05:12:36 GMT+0000`

But I want to get the local time format by add **8 hours** to the UTC hour:

`Fri Jul 10 2015 13:12:36`

or `GMT+8` format

`Fri Jul 10 2015 13:12:36 GMT+0800`

How to achieve that?

**Comment by DemersM** [comment]
I would like to know how to achieve this.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
