### ISSUE TITLE
Hosting Admin Panel Changes on Heroku

### ISSUE THREAD

**Issue by Rekenna** [keystonejs/keystone#1527]
Hey there,

I've been messing with Keystone for a few hours and I absolutely **love** it. I've been trying to customize the Admin Ui/backend etc though the only resources I'm digging up tell me to modify the keystone module in my node_modules folder. To me that seems a little odd, especially since as soon as I commit my changes to git or Heroku none of them will get saved in production. Is that truly the only way to do it or is there another way that I'm missing?

Thanks for help!

Also, I've seen mention of a slack chat and I'd really like to be a part of that.

**Comment by bscheibe** [comment]
The ability to edit the admin UI and have the changes persistent should be implemented in version 0.4.0

Please see #220 for more info and some possible work arounds

Regarding slack access please see #534
