### ISSUE TITLE
[RFC] A StateMachine type

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1528]
Request For Comments on a new field type `StateMachine`:

---

# `StateMachine` Field Type

The `StateMachine` field type allows you specify a [Finite State Machine](https://en.wikipedia.org/wiki/Finite-state_machine) to control the possible states and transitions between those states in a declarative syntax, ideal for setting up publishing workflows or user onboarding walkthroughs.

The `StateMachine` field type is powered by [the `xstate.js` state chart library](https://xstate.js.org/docs/).

## Example

```javascript
keystone.createList('Post', {
  fields: {
    name: { type: Text },
    status: {
      type: StateMachine,
      defaultValue: 'draft',
      states: {
        draft: {
          on: {
            ready: [
              { target: 'ready', cond: 'isAdmin' },
              { target: 'ready', cond: 'isAuthor' },
            ],
          },
        },
        ready: {
          on: {
            published: [{ target: 'published', cond: 'isAdmin' }],
            rejected: [{ target: 'rejected', cond: 'isAdmin' }],
          },
        },
        rejected: {
          on: {
            draft: [
              { target: 'draft', cond: 'isAdmin' },
              { target: 'draft', cond: 'isAuthor' },
            ],
          },
        },
        published: {
          on: {
            draft: [{ target: 'draft', cond: 'isAdmin' }],
          },
        },
      },
      guards: {
        isAdmin: ({ context }) => context.authedItem && context.authedItem.isAdmin,
        isAuthor: ({ context, existingItem }) => context.authedItem && context.authedItem.id === existingItem.author,
      },
    },
  },
});
```

The `states` and `guards` are passed straight to `xstate`.

[See the equivalent xstate state machine here](https://xstate.js.org/viz/?gist=0781a6d629aaae371c754a6a466a2bc6) (try changing the values returned from `isAdmin`/`isAuthor` to see the different transitions which are enabled/disabled):

<img width="258" alt="visualisation of Post.status state chart" src="https://user-images.githubusercontent.com/612020/63590089-31ce4200-c5ee-11e9-9790-1048b323d02a.png">

The AdminUI Field would display as a drop-down of the current state and any possible states which can be reached from there. Something like:

<img width="566" alt="Select Dropdown showing 4 options with 2 disabled, 1 enabled, and 1 selected." src="https://user-images.githubusercontent.com/612020/63590392-00a24180-c5ef-11e9-9071-97a3bd8866e5.png">

---

Whatchya think?

**Comment by VinayaSathyanarayana** [comment]
This will be really useful

**Comment by vmdao** [comment]
Like it :)

**Comment by mahcr** [comment]
Is there any update?

**Comment by wcalebgray** [comment]
Hey all, any updates on this? I think it sounds awesome and my project could really use this functionality as a replacement for the `dependsOn` feature that was in previous versions of Keystone.

**Comment by joseDaKing** [comment]
Hi, everbody there is state machine library in javascript called [xstate](https://xstate.js.org/docs/) it might can be used for this use case
