### ISSUE TITLE
Multiple Domains?

### ISSUE THREAD

**Issue by kfancy** [keystonejs/keystone#1529]
Are there any plans for multiple domain support within Keystone?

Use Case:
- upon arriving at foo.example.com or bar.example.com, certain config variables are set on the fly (database connections, template file directories, etc) to allow a single keystone instance to serve multiple sites.

**Comment by Abinader** [comment]
I need this too, and i really liked this project and would like to give my contribution.

If you want, you can send me the overview of the changes that i gonna develop.

I'm studing this project and learning about, but if you guide me, i can develop more fast.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/multiple-domains-with-one-keystone-instance!
