### ISSUE TITLE
Sub-collections

### ISSUE THREAD

**Issue by azproduction** [keystonejs/keystone#153]
Hello!

I have complex model with nested collections. I'm trying to define such model

``` js
{
    title: { type: String, required: true },
    images: {
        type: [{
            name: String,
            image: Types.Url,
            thumb: Types.Url,
            description: String
        }]
    }
}
```

And I get an error `Error: Fields must be specified with a type function` @ `keystone/lib/list.js:298:9`.

Is it possible to define that collection in keystone? (it is possible in Mongoose)

In admin UI this field should look like list of items with Add, Edit and "Trash" buttons. Add and Edit buttons should open modal dialog.

I am new to keystone, but I want to contribute to this project. And it will be great if you guide me a bit.

**Comment by wangpingsx** [comment]
Really expect to have this feature!!!!!

And what i want is a Dynamic array field, which like tags for a blog post.

I have a temporary solution, I would like to share:

Design.add( {
	design: { type: String , initial: true, required: true, index: true },
	priceGroup: { type: String },
	price: { type: String},
	image: { type: Types.CloudinaryImage },
	},
	"Colours", { 
		1: { 
			type: String,collapse:true
		},
		2: { 
			type: String,collapse:true
		},
		3: { 
			type: String,collapse:true
		},
		4: { 
			type: String,collapse:true
		},
		5: { 
			type: String,collapse:true
		},
		6: { 
			type: String,collapse:true
		},
		7: { 
			type: String,collapse:true
		},
		8: { 
			type: String,collapse:true
		},
		9: { 
			type: String,collapse:true
		},
		10: { 
			type: String,collapse:true
		},
		11: { 
			type: String,collapse:true
		},
		12: { 
			type: String,collapse:true
		},
		13: { 
			type: String,collapse:true
		},
		14: { 
			type: String,collapse:true
		},
		15: { 
			type: String,collapse:true
		},
		16: { 
			type: String,collapse:true
		}
});

I know I am terrible smart!!!!!   :-)

All colours fields are collapsed when you open the create view of admin UI. 

if you need only one colour open the first colour field.

All looks great!!, But it will always have 16 sub items in mongodb like this:

{
    "_id" : ObjectId("ddddadfasdfasdfasdfasdfasdf"),
    "design" : "aaa",
    "__v" : 0,
    "1" : "red",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "price" : "ccc",
    "priceGroup" : "bbb"
}

**Comment by wangpingsx** [comment]
Type.TextArray could be a solution for string list only.

but if there is a Type.AnyObjectArray will be great!

**Comment by isjackwild** [comment]
@JedWatson Is there any ETA on when this feature may be implemented? I'm exploring Keystone for a new project I'm about to start on (due to launch in around 4 months), and I would LOVE to use Keystone for this, I think it seems really promising. More so than other solutions I've explored.

However, the ability to have nested arrays is a pretty make-or-break feature in this case, as we need it to be nice and easy to add new repeat sections and media in a post. At least in time for when we launch.

**Comment by mandb** [comment]
This should be required Type.nested looks like the right way to go about it.  @JedWatson  any way we can contribute to getting this added into main branch other than with PR?  Thanks.

**Comment by morenoh149** [comment]
@mandb what's wrong with a PR?

**Comment by mandb** [comment]
I'm asking if there is a way to contribute to a feature other than by providing code.

**Comment by morenoh149** [comment]
@mandb in-depth discussion and coordination can be done on the slack. If you're interested in an invite let me know

**Comment by mandb** [comment]
I would be interested thanks!

**Comment by metasansana** [comment]
@mandb feedback on #821  will also be useful. If all the other fields ui's are embeddable it should be possible to manage them in table form.

**Comment by wangpingsx** [comment]
Hi guys, 

I have solved this issue

This blog explains how to use it:
http://baiduhix.blogspot.co.uk/2015/01/a-new-type-of-keystonejs-objectarray.html

This blog explains the source code of my solution:
http://baiduhix.blogspot.co.uk/2015/01/a-new-type-of-keystonejs-objectarray_26.html

@JedWatson let me know if you have any issue with that.

Thanks,
Peter

**Comment by mandb** [comment]
@wangpingsx - very nice plugin, will look into it but this seems to be the best approach so far.

**Comment by mandb** [comment]
@wangpingsx, does it only support string-objects or can you use more complex object types in the sub object definitions?

**Comment by wangpingsx** [comment]
@mandb  only string for sub-object' fields  at that moment.  you can make it to support number by this:

E.g. i can make the "ext" field as number by this:

xxxxx.add( 
	{
		
		//***** Note, this is nessary !!!  Start *****//
		'contacts': { type: ObjectArray, initial: true,
			subObjectDefine: { 
				role: { type: String}, //only string now
				ext:{ type: String}
			}
		}
		//***** Note, this is nessary !!!  End *****//
	}
);

//***** Note, this is also nessary !!!  Start *****//
var mongoose = keystone.mongoose;
    var schemaPaths = new mongoose.Schema({
        role:       String,
        ext:Number
    });

    // schema.add(this._path.addTo({}, [schemaPaths]));
    
storeObject.schema.add({
    contacts: { type: [schemaPaths] }
});


But it still display as a string input on admin ui, which means you only lose your number format ability.

If the user type "abc" in this field, he/she will get error for that.

**Comment by medv** [comment]
Just sitting here hoping this gets some progress, so I can advise my client for a rough ETA (so far I have said that the project gets a lot of love, but it could still be another year). It's a key feature for this project (and almost every other that I will be using Keystone for - fantastic framework!)

**Comment by jmkII** [comment]
Really anticipating this feature too! So far I've been able to work around this, but this would definitely be a huge improvement in admin functionality. Thanks for all your great work guys!

**Comment by svenrobin** [comment]
same here, this is essential for me to even be able to use keystone

**Comment by mandb** [comment]
Do we want to sponsor a feature then? How can we go about that.

**Comment by medv** [comment]
I think we might have to wait since there is the whole refactor to react thing going on - plus talk of making the admin panel a single-page-app (also required). This is what has been stopping me from getting in there myself, as any code that isn't in collaboration with owner would quickly be outdated.

**Comment by svenrobin** [comment]
another month passing without any updates?

**Comment by morenoh149** [comment]
@svenrobin wanna join the slack and help build it?

**Comment by mandb** [comment]
I believe it was on hold until the reactjs update, since a kit will be
changing and any pr's before it will likely conflict.  Is this still the
case?

**Comment by Bockit** [comment]
I'm trying to use the mongoose mixed schema type and I'm running into some trouble.

I tried to follow the steps above with the [mixed schema type][mixed] but my changes aren't saving (I am using `markModified()`)

```coffeescript
User.schema.add({
    testResults: {
       type: {}
    }
})
```

Then in a schema method:

```coffeescript
User.schema.methods.updateTestProgress = (moduleId, recordId, passed) ->
    @testResults = {foo: 'bar'}
    @markModified('testResults')
```

Calling `user.save()` after `user.updateTestProgress(...)` doesn't save the testResults data to the document.

Does anyone know what I'm doing incorrectly? Thanks for your time.

[mixed]: http://mongoosejs.com/docs/schematypes.html

**Comment by piitaya** [comment]
Hi ! Is there any work in progress concerning the nested field ? I am very interested in this feature !
Thank's for all your work ! Keystone is awesome :)

**Comment by simonwidjaja** [comment]
I'm also VERY interesting in the progress of this feature. It's a show stopper for one of our projects right now.

**Comment by J4G-** [comment]
I also could really use this feature!

**Comment by jmkII** [comment]
Is there any plan to implement this in the future?

**Comment by JedWatson** [comment]
Yes - we will get to it. There are still bigger concerns we're working through that will make this an easier thing to add in the future.

**Comment by micahbule** [comment]
Any updates on this feature? I'm willing to help out in any way I can.

**Comment by mandb** [comment]
Mongo 3.2 has the new $lookup aggregate which allows you to effectively do
a left outer join - this would be a good candidate.

**Comment by morenoh149** [comment]
@mandb :+1: I saw that as well. Haven't used it yet though.

**Comment by mandb** [comment]
Doesn't work on sharded collections and can only work with exact matching
fields, but it's a good step and can give exactly this functionality.

**Comment by QualityWorksCG** [comment]
+1

**Comment by vostreltsov** [comment]
+1 Waiting for this feature.

**Comment by BackdoorDan** [comment]
+10 This is the only thing preventing me from using keystone in a number of production websites/apps.

**Comment by simonwidjaja** [comment]
+10 same here...

**Comment by NebirosFeR** [comment]
+1

**Comment by davisml** [comment]
+1

**Comment by blueonrails** [comment]
+1

**Comment by simonwidjaja** [comment]
Any news on this?

**Comment by Alvarobeta** [comment]
+1

**Comment by vostreltsov** [comment]
+1

**Comment by NebirosFeR** [comment]
+1

**Comment by jogonru** [comment]
+1

**Comment by RyanCCollins** [comment]
+2, would love to use this functionality in an app I am creating.  Any help would be appreciated.

**Comment by wmertens** [comment]
@Bockit Did you get it to save?
@JedWatson without saving there is no workaround for this :cry:.

If this gets implemented, does that mean that the current conversion of nested objects into flat fields will become objects again? If so, that's a breaking change of course, if not, how to do it?

Note that with React, making nested editors for nested objects is easy, simply recurse editors in the rendering function.

**Comment by sachss** [comment]
I'd suggest anyone interested in this see and support #2265.

**Comment by Bockit** [comment]
I did, the code is at home, I'll try and dig it up. IIRC I was misunderstanding something about how the feature worked.

**Comment by VinayaSathyanarayana** [comment]
Any updates on this? Will this be part of V0.4?

**Comment by jjhesk** [comment]
if i need to use cloudinary in the api just to insert the info as the object. How can i use the cloudinary schema object as the new insert object? any sample code?

**Comment by jbpin** [comment]
I admit it will be really pleasant to have an ObjectArray type instead of using relations. +1

**Comment by wmertens** [comment]
Arrays of Objects are being worked on, they are already working in fact :)

See https://github.com/keystonejs/keystone/pull/3300 and https://github.com/keystonejs/keystone/pull/3282 for progress.

I hope that we can replace all the Array types with them (in a backwards compatible way). Then we can implement reordering too.

**Comment by lazaridis-com** [comment]
@azproduction , @JedWatson , @wmertens - Is this issue solved in version 4?

**Comment by simonwidjaja** [comment]
+1 I would be interested in an update as well...

**Comment by ghuroo** [comment]
Any chance of seeing this in a 4.0.6 beta?
Or can we implement sub-collections trusting that this feature will be out someday soon?

**Comment by Adrian-Kardasz** [comment]
Yeah this is such a critical thing for me so that the web app admins can edit data easily (they're not to savy)

**Comment by mrth2** [comment]
yah, this should be done for the extendable admin 👍 
any update @JedWatson ?

**Comment by semeano** [comment]
This would be so awesome!

**Comment by jennaprice** [comment]
I found this in some code I was working on which solved my problem:

`var getForm = function(name, callback){
    name = name ? name : req.params.name;
    keystone.list('Form').model.findOne({
      'slug': name
    })
    .populate({
      path: 'formFields',
      populate: {
        path: 'validationRules',
      }
    }).exec(function(err, form){
      callback(form);
    });
  };`

**Comment by vlatri** [comment]
Hey, @JedWatson, are there any updates on this one?

**Comment by medv** [comment]
Please go see https://graphcms.com/ and their open-source offering. So many advances have been made in the last several years while this issue remained open, that I'm not sure how Keystone could keep up at this pace.

**Comment by semeano** [comment]
I've ended up creating a new type called List that allows that. You can check [my fork of keystone](https://github.com/semeano/keystone).

```
images: { type: Types.List, required: true, initial: true, default: [],
	fields: {
		title: { type: Types.Text, required: false, initial: true },
		alt: { type: Types.Text, required: false, initial: true },
		url: { type: Types.Text, required: true, initial: true }
	}
}
```

**Comment by dejavu1987** [comment]
+1

**Comment by ohadperry** [comment]
+10

**Comment by leouz** [comment]
+1

**Comment by gautamsi** [comment]
unfortunately nested lists are dropped from keystone 4, see #3282, Keystone 5 promises to pick it up. see https://github.com/keystonejs/keystone-5/issues/195

closing this for tidiness.
