### ISSUE TITLE
Get Started Guide improvement

### ISSUE THREAD

**Issue by boonier** [keystonejs/keystone#1531]
Probably me being dumb, but I think on Step 3 of the quick start guide there should be a sub step just before `$ node keystone` that says to make sure MongoDB is running. Obviously if you have just installed it in the pre-requisites step then chances are high that it's already running, but if you've already installed it prevously, it might not be... I was scratching around re-installing, and when going through the errors in terminal when it struck me that I hadn't started mongod. Again prob me being a bit new to this setup.

Otherwise looking forward to getting my hands dirty in this v promising looking cms!

Thanks

**Comment by stosorio** [comment]
Maybe under Step1/Prerequisites, like "Before you begin, make sure you have Node.js 0.10+ installed and MongoDB v2.4+ installed and running." ?

**Comment by jeffreypriebe** [comment]
The page in question could be edited to PR here: https://github.com/keystonejs/keystonejs-site/blob/master/content/en/pages/docs/getting-started.jade

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
