### ISSUE TITLE
Use  other geocoding-service for location enrichment when no Google Maps API-Key available

### ISSUE THREAD

**Issue by stosorio** [keystonejs/keystone#1533]
As much as I enjoy using Google's APIs, maybe it would be nice to have something that works out of the box without having to provide an API-Key?
Mapquest for example: http://open.mapquestapi.com/nominatim/

**Comment by stosorio** [comment]
Processwire (a PHP CMS/CMF which i used a couple of times) uses google geocoding without needing an API Key.
https://github.com/ryancramerdesign/FieldtypeMapMarker/blob/48090d01a524ed33c1de71d61003e848067e5152/MapMarker.php#L79

Also Google Developer Guide sounds like an API Key isn't strictly neccessary?
https://developers.google.com/maps/documentation/geocoding/intro
> All Geocoding API applications should use an API key. Including a key in your request:
> * Allows you to monitor your application's API usage in the Google Developers Console.
> * Enables per-key instead of per-IP-address quota limits.
> * Ensures that Google can contact you about your application if necessary.

**Comment by morenoh149** [comment]
+1

**Comment by JedWatson** [comment]
You're correct, not sure if this changed but it looks like you don't actually need an api key for a limited number of geocodes with google. Also happy to bring this to the client, but I don't think we should get rid of the server-side implementation because it's useful in other cases. No problem having both options.

I guess we should get rid of the check for the API Key to enable the geolocation functionality, and we can update the generator as well.

**Comment by stosorio** [comment]
Yes, the server-side implementation would definitely stay relevant.
I wouldn't get rid of the check completely though - perhaps add an option to Type.Location to allow geocoding without key?
This is because Google has [certain restrictions](https://developers.google.com/maps/terms#section_10_1) about the ways in which you can use data gained through the API (e.g. you aren't allowed to use it with other map providers or in se), so activating it should still be a deliberate choice.

**Comment by stosorio** [comment]
I suppose if i want to tackle a client-side implementation it would be best to do this in the elemental-integration branch?

**Comment by stosorio** [comment]
Apparently, the check that enables the API [checks for the wrong key](https://github.com/keystonejs/keystone/search?utf8=%E2%9C%93&q=%22google+api+key%22&type=Code)?
But then again, the provided key [isn't used anyway](https://github.com/keystonejs/keystone/blob/123e4f980b5e6ae8583ec1cb03479667b6445daf/fields/types/location/LocationType.js#L371).
