### ISSUE TITLE
Speed up Keystone init time

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1534]
The first `require('keystone')` statement takes _too long_, and loads a lot of packages that aren't necessarily even going to be used by the app.

Probably the biggest offender is `lib/fieldTypes`, which initialises all field types whether they're used by models or not.

The `module.exports[fieldType]` statements could be replaced by [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Defining_a_getter_on_new_objects_in_object_initializers) and it would speed up init time considerably. This technique could also be applied elsewhere throughout the codebase.

**Comment by JedWatson** [comment]
_BAM_ average 800ms improvement on my dev machine. :grinning:

**Comment by webteckie** [comment]
Fantastik!
