### ISSUE TITLE
Travis badge

### ISSUE THREAD

**Issue by theolampert** [keystonejs/keystone#1535]
Just a tiny one, travis badge doesn't link to the correct url, it also shows build status for all branches. Might be worthwhile just showing master branch to avoid confusion?. 

For example:

`[![Build Status](https://travis-ci.org/keystonejs/keystone.svg?branch=master)](https://travis-ci.org/keystonejs/keystone)`

**Comment by stosorio** [comment]
+1
I was wondering about the error already ^^

**Comment by JedWatson** [comment]
Good call @theolampert. Done.
