### ISSUE TITLE
Display Virtuals As NoEdit Fields In Keystone Admin UI

### ISSUE THREAD

**Issue by philipheinser** [keystonejs/keystone#1538]

**Comment by morenoh149** [comment]
Could you add a description.

**Comment by foobar8675** [comment]
@morenoh149 are virtuals supposed to display in the admin ? They are not right? I was just looking here https://github.com/JedWatson/sydjs-site/blob/master/models/User.js and when i run this example, I don't see an admin field for url. 

Just was hoping you could confirm my understanding.

**Comment by morenoh149** [comment]
@foobar8675 virtuals are not viewable from the adminUI afaict. Because a virtual is more like a function or computed value and are not actually persisted to the mongodb database. See http://mongoosejs.com/docs/guide.html#virtuals

**Comment by philipheinser** [comment]
@morenoh149 I would love to see some my virtual in the admin ui as non editing fields. We could have a setting virtuals: true if someone would like to enable this.

**Comment by webteckie** [comment]
I believe you can do what you need with the existing functionality by using the post init hook.  For example: 

Assum the Post has the following, of which contentFull will be filled from the content.full virtual:
```
...
content: {
	brief: { type: Types.Html, wysiwyg: true, height: 150 },
	extended: { type: Types.Html, wysiwyg: true, height: 400 }
},
contentFull: {type: Types.Html, wysiwyg: true, height: 400, noedit: true}
...
Post.schema.virtual('content.full').get(function() {
	return this.content.extended || this.content.brief;
});
```

Then you can fill up contentFull as follows:
```
Post.schema.post('init', function() {
    this.contentFull = this.content.full;
});
```

**Comment by webteckie** [comment]
@JedWatson fyi, in the example I gave above the HTML tags are displayed when rendering the contentFull property in the Admin UI, if using the noedit:true attribute.  I believe that was resolved a long time ago and it's broken again!

**Comment by foobar8675** [comment]
thanks for the explanation @morenoh149 @webteckie that looks clever. i'm looking forward to giving that a shot.

**Comment by webteckie** [comment]
@foobar8675 although it works, you may be disappointed to know that that it is not a reliable solution (:-  Mongoose post methods run asynchronously!  That means if the Admin UI thread renders before the post init method has finished then you will not get your virtual value rendered!!!  It would take some extra logic in keystone to watch server-side async field changes and have the Admin UI dynamically react to those.  Not sure if that's a feature in the road map, though.  I know, a bummer :-)

**Comment by foobar8675** [comment]
yeah that is a bummer.  :(

**Comment by creynders** [comment]
If I'm not mistaken it should work if you use `pre('save')` instead.

**Comment by webteckie** [comment]
Yeah, if you are willing to save that virtual field in which case it wouldn't be a virtual anymore ☺

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/display-virtuals-as-noedit-fields-in-keystone-admin-ui!
