### ISSUE TITLE
Implement field-specific filtering methods

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1539]
List filtering is currently implemented with a big switch statement in `lib/list.js` for per-field-type filtering logic. The logic should be implemented on a per-field basis for any field type that supports filtering, to support custom (non-core) field types in the future.

Since we're reimplementing the filtering UI and logic in 0.4, this is a good opportunity to clean up the options and logic for each data type.

Filter methods should be implemented as a `addFilterToQuery(filter, query)` method on the fieldtype.prototype. This won't be implemented on the base `Field` prototype.

Initial types to implement:

- [x] text
- [x] date
- [x] boolean
- [x] number
- [x] select
- [x] relationship
- [ ] name
- [x] password
- [ ] markdown
- [ ] location

**Comment by mxstbr** [comment]
This is done!
