### ISSUE TITLE
relation name should be shown in Admin interface

### ISSUE THREAD

**Issue by davibe** [keystonejs/keystone#1540]
If i have a relation like like this

    Asset.relationship({ path: 'thisIsMyCustomAttribute1', ref: 'Bridget', refPath: 'source'});
    Asset.relationship({ path: 'thisIsMyCustomAttribute2', ref: 'Bridget', refPath: 'destination'});

"thisIsMyCustomAttribute*" are not shown in the admin interface. This makes it impossible to make a distinction between them.
<img width="1028" alt="screenshot 2015-07-20 10 32 06" src="https://cloud.githubusercontent.com/assets/123929/8772228/98a977ac-2eca-11e5-8473-2e6a4c333da4.png">

**Comment by mldangelo** [comment]
This would be useful for me too! Might I suggest adding a "label" attribute instead? That way we can call them whatever we want. I'm happy to work on this after @JedWatson lands the elemental integration.

**Comment by davibe** [comment]
if we just show the 'path' attribute (i.e. "thisIsMyCustomAttribute2") is fine for me, no additional labels

**Comment by creynders** [comment]
Unless I totally misunderstood what you're trying to achieve, this is already implemented, just add "label" to your mutual relationship declarations, e.g.:

```js
Asset.relationship({ 
  path: 'thisIsMyCustomAttribute1', 
  ref: 'Bridget', 
  refPath: 'source', 
  label:'Sources'
});
```

If you're trying to achieve something else, please reopen.
