### ISSUE TITLE
S3 image uploads being auto-renamed with temporary string

### ISSUE THREAD

**Issue by budkin76** [keystonejs/keystone#1541]
Hello,

I'm pretty new to Keystone as I recently inherited a codebase on a project that used it. We were locked into version 0.2.42 so I just updated to the latest, version 0.3.12 and now I'm having a strange issue. All our models with images use S3 for upload (Types.S3File) and it used to just place the image with the original file name at the root of the specified S3 bucket. Now, however, the files are being renamed with what I'm guessing is a temporary string name. For example if I upload a file called "MyImage.jpg," it will upload as something like "7830c3a6bc7b6790e63de9a3c3716b06.jpg." Is there a new configuration I need to edit to retain the original file name as used to be the case? Thank you for your help.

Seth

**Comment by jeffreypriebe** [comment]
Reviewing fields\types\s3fil\S3FileType.js : .uploadFile > doUpload, it doesn't seem like it should be.
Look around there but `knox.createClient(field.s3config).putFile(file.path, path + filename, &#8230;` ([@L402](https://github.com/keystonejs/keystone/blob/v0.3.12/fields/types/s3file/S3FileType.js#L402)) would suggest that the filename is as it came in from the call in [getRequestHandler](https://github.com/keystonejs/keystone/blob/v0.3.12/fields/types/s3file/S3FileType.js#L476) unaltered.

**Comment by budkin76** [comment]
Thank you @jeffreypriebe. I'll try and set some breakpoints around there to see if I can determine what is going on.

**Comment by jeffreypriebe** [comment]
Let us know what you find out.

**Comment by morenoh149** [comment]
Sometime in june we started preserving the original filename https://github.com/keystonejs/keystone/commits/v0.3.12/fields/types/s3file/S3FileType.js it didn't used to preserve it before.

**Comment by jeffreypriebe** [comment]
Good catch. According to that, the filename preservation should be in v0.3.12.
@budkin76 - I'd suggest double-checking your bits to ensure you have v0.3.12 with the filename preservation code.

**Comment by budkin76** [comment]
@jeffreypriebe and @morenoh149 thank you for your help. This bit was the key:

```javascript
if ('function' === typeof field.options.filename) {
    filename = field.options.filename(item, filename, originalname);
}
```

The "Post" Keystone list that the previous programmer had written only had `type` defined for the `image` field. I added that `filename` option as well:

```javascript
	image: {
		type: Types.S3File,
		filename: function(item, filename, originalname){
			// prefix file name with object id
			return originalname;
		}
	},
```

And now all is well! Appreciate it guys!

Seth

**Comment by morenoh149** [comment]
@budkin76 that's a pull request right there

**Comment by jeffreypriebe** [comment]
Thanks for sharing the solution. I'm sure others will want to know.

I would wonder why `originalname` isn't the default behavior (in keystone). Breaking change to be sure, but likely most of the time people would want the original name.

**Comment by bradwbradw** [comment]
i wanted the original filename.  Luckily it's documented in this issue, but the doc here needs updating: http://keystonejs.com/docs/database/#fieldtypes-s3file

i ran into this running version `0.3.19`

**Comment by jeffreypriebe** [comment]
@bradwbradw Sounds like an easy PR to the docs repo.
