### ISSUE TITLE
CloudinaryImage file format bug

### ISSUE THREAD

**Issue by hatzipanis** [keystonejs/keystone#1543]
I have a CloudinaryImage field type and I wanted to create a thumbnail preview of the PDF that I uploaded. I tried the Handlebars helper: ``{{cloudinaryUrl data.listing.attachment format="jpg" width='150' height='150' crop='fill'}}`` however this simply appends ``.jpg`` to the end of the outputted URL instead of *replacing* the original file extension.

**Example:**

Outputted image URL that *doesn't* work: http://res.cloudinary.com/dpwmelbjz/image/upload/c_fill,h_150,w_150/v1/events/attachment/udtlfznyrut1waksr2ee.pdf.jpg

According to Cloudinary documentation this should be (and *does* work):
http://res.cloudinary.com/dpwmelbjz/image/upload/c_fill,h_150,w_150/v1/events/attachment/udtlfznyrut1waksr2ee.jpg

I looked at the Handlebars helper but it looks like the bug runs deeper than that?

See the Cloudinary [documentation](http://cloudinary.com/blog/uploading_converting_and_generating_thumbnails_for_pdf_documents) for more information.

**Comment by jeffreypriebe** [comment]
That is odd. The helper seems to be confused.
If you simplify the [cloudinaryUrl helper](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/templates/default-hbs/views/helpers/index.js#L204) it works.
Instead of
```
var imageName = context.public_id.concat('.',context.format);
return cloudinary.url(imageName, options.hash);
```
Simply:
```
return cloudinary.url(context.public_id, options.hash);
```

Cloudinary is expecting an id, the [helper function in the template](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/templates/default-hbs/views/helpers/index.js#L204) passing a computed

**Comment by hatzipanis** [comment]
Thanks @jeffreypriebe, appreciate the solution.

Does the generator need to be updated? Should I open an issue on that repo?

**Comment by jeffreypriebe** [comment]
Could do.
I'm not certain that there wasn't a reason the code wasn't that way to begin with. I'd check the file history to try to figure out why if there was a change to that alternate option somewhere. Maybe the cloudinary library changed?

**Comment by mxstbr** [comment]
Closing due to staleness, feel free to reopen if you think this is still an issue!
