### ISSUE TITLE
How to embed local file images to a blog post model

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystone#1545]
I've searched for an example, but every of those just have 1 image using *CloudinaryImage*

What i wanted is to have a Blog model with its Html field, but attach some "Local" images to it, and be able to embed those on the html body

Any advice is welcome!

**Comment by jeffreypriebe** [comment]
There isn't a great option, but there is a basic one. No upload, simply linking an existing image that is on the web somewhere.

The basic option is adding the TinyMCE `images` plugin . That will get you something like this:
![Keystone Images Plugin Button in action](http://i.imgur.com/JzGrWr8.png)


In your keystone.js:
```js
keystone.init({
...
  'wysiwyg additional plugins': 'images',
  'wysiwyg additional buttons': 'images',
...
});
```
(If you already have plugins or buttons, that should be a comma-delimited string, e.g. `'first-plugin, images'`. See [docs](http://keystonejs.com/docs/configuration/#options-ui).)
<sub>(Dimensions won't truly resize the image for you, but just input those dimensions to the image tag that it inserts. However dimensions do get auto-populated by the size of the image.)</sub>

**Comment by jeffreypriebe** [comment]
There are several efforts to provide more file upload options. None have been completely folded into Keystone yet. Most require various levels of core integration and need core code shuffled.
* [Uploadcare Images PR](https://github.com/keystonejs/keystone/pull/1510)
* [StorageAPI](https://github.com/keystonejs/keystone/issues/526)
* [Massive, Official File fields](https://github.com/keystonejs/keystone/pull/1222)

**Comment by jacargentina** [comment]
Yeah, i think may be i should wait for those efforts to be merged. Or stick to a "own served image" somehow with the "images" plugin you first mentioned.

**Comment by jacargentina** [comment]
@jeffreypriebe I've thought of writing some plugin for tinymce to serve image ulrs from my own keystonejs server... but...

http://www.tinymce.com/wiki.php/Plugin:image

It seems it is already there? I mean, i can use the image_list option

http://www.tinymce.com/wiki.php/Configuration:image_list, under *Example of JSON url with images*
i read it would be easy to provide an endpoint from keystonejs itself, to return a list from a given directory for example?

**Comment by jeffreypriebe** [comment]
That image-list is interesting. I don't see anything in the source that would suggest that it would work but the idea of passing it a script/url that provides images to pick from is enticing.
Is there a demo of that behavior somewhere?

**Comment by jacargentina** [comment]
No demo. Just you have to configure keysonejs like this:

````javascript
keystone.init({
 ...
  'wysiwyg additional plugins': 'image',
  'wysiwyg additional buttons': 'image',
  'wysiwyg additional options': {
    'image_list' : '/images',
  }
 ...
});
````

And then implement the `/images` endpoint like this (in routes/index.js)

````javascript
// Bind Routes
exports = module.exports = function(app) {
  ....
 app.get('/images', function(req, res, next) {
     // Just an example. Ideally an array would be fetched from disk, database, etc
     res.json([
             {title: 'Dog', value: 'mydog.jpg'},
             {title: 'Cat', value: 'mycat.gif'}
        ]);
 });

  ....
}
````

**Comment by jacargentina** [comment]
Anyway, i've come to a simple implementation, by using available things like data uri for images https://en.wikipedia.org/wiki/Data_URI_scheme and TinyMCE support for drag/drop or paste images.

So i dont need to save the images on its own files; also, a blog post is somehow like a unit (text + embeded images), somebody can point me disavantages/cons of this model, but i prefer looking at advantages/pros; and also it's VERY easy to forget the problem, and start USING it!

I've simply done this:

##### Enable pasted images as data-uris on TinyMCE (disabled by default)

````javascript
keystone.init({
 ...
  'wysiwyg additional plugins': 'paste',
  'wysiwyg additional options': {
    'paste_data_images': true
  }
 ...
});
````

**Comment by jeffreypriebe** [comment]
So the image selected gets inserted in the content directly as the data/base64. From the last keystone init, seems like that behavior is a TinyMCE option.
It would be good to document this as it is another reasonable interim solution (beats the imageupload IMO, and only lacks the upload ability of cloudinary images).

I can't think of any good arguments against the insertion of image data directly.
One might argue image cache reuse (if pointing at an external image, a browser can cache across multiple pages) but that seems unlikely for more images that someone would put into content.

On the plus side, it has a strong performance point of saving another HTTP request ([Yahoo! goes as far as *recommending* inline images with data:URL use](https://developer.yahoo.com/blogs/ydn/high-performance-sites-rule-1-fewer-http-requests-7163.html) for exactly this reason.)

Feels like a clever [judo](https://signalvnoise.com/posts/312-lingo-judo) solution. Nicely done.

**Comment by jacargentina** [comment]
Nice...  Yahoo supporting... me! ;)
Hope this serves to somebody using keystone too.

**Comment by dfsdfsdfs** [comment]
One comment says  'wysiwyg additional plugins': 'images', and another  'wysiwyg additional plugins': 'image'. That little difference in the ending "s" stole two hours from my life. I suggest removing/editing first comment.

**Comment by tobeatiger** [comment]
Hi @jacargentina
Just have the same issue and tried your solution, it works great for small images, but if you paste/drag a big image (say more than 1M), the whole content will broken after successfully saved. Not sure it's the limitation of mongoDB or the TinyMCE. Did you have the same issue?

**Comment by jacargentina** [comment]
@tobeatiger never. Maybe i've not used anything so big yet.
