### ISSUE TITLE
Feature Request: Add multiple, unique HTML (WYSIWYG) fields in the admin

### ISSUE THREAD

**Issue by dallasbpeters** [keystonejs/keystone#1546]
I would love to see the ability to click "add" and get another WYSIWYG box in the admin UI. (Rather than have a client try to mess with markup to create sections on a page). Has anyone else brought this up?

**Comment by lojack** [comment]
I believe this would be accomplished by #257

**Comment by dallasbpeters** [comment]
:+1:
