### ISSUE TITLE
Admin UI customize defaultColumn links

### ISSUE THREAD

**Issue by celiao** [keystonejs/keystone#1547]
It appears that the column in defaultColumns that is mapped to name contains the links to get to the respective documents.

I would like to use a different column to contain the links, a `noedit: true` column that is computed by my middleware.  Is this possible with the current version of KeystoneJS?

If not, the syntax could be something like:
```
MyModel.defaultColumns = 'recordNumber|links, assignedTo, title, createdAt';
```
With column widths:
```
MyModel.defaultColumns = 'recordNumber|links|10%, assignedTo|10%, title, createdAt';
```
With links available in multiple columns:
```
MyModel.defaultColumns = 'recordNumber|links|10%, assignedTo|10%, title|links, createdAt';
```
If a column in `defaultColumns` contains items of type `Types.Relationship`, a `links` modifier would be ignored, and the links would still take you to the related items.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/advanced-default-columns!
