### ISSUE TITLE
Jade include an html file with script links

### ISSUE THREAD

**Issue by DenDix** [keystonejs/keystone#1548]
I want to include an html file in a " /template/layouts/views/***.jade" file.
Plus I want to keep the navigation bars at the top derived from "layouts/default.jade"
The html file resides at "/public/river/riverdata/index.html", but it has a number of scripts that it links to.
If in my browser I access the html file by "......com/river/riverdata/index.html" the scripts run fine.

But if I add the line "include ../../public/river/riverdata/index.html " in my ***.jade file, it finds the html file and renders it inside my  layout with the navigation bar, but the scripts no longer work.

Since I can run the html file perfectly fine with keystone running, there must be a way to have it run also inside a jade layout. I have some ideas as to what is going on, but they're only guesses. Any help is appreciated.

**Comment by jeffreypriebe** [comment]
It sounds like you want the contents of an existing HTML file inside your jade template. If so, then that isn't really what jade is about. It is meant as a template engine that translates into HTML.
You might be able to snip out the parts of the HTML file that you want and include those. For example, the scripts and links need to be included in such a way that they would run, possibly separate from the rest of the content. See this [stackoverflow answer](http://stackoverflow.com/a/30250843/1592) for ideas.

**Comment by DenDix** [comment]
I finally solved the problem with a sort of ugly hack. Inside feeds.jade I added this line:

iframe(src="http://ec2....amazonaws.com/river/riverdata/index.html" width='100%' height='800' frameborder=0 scrolling='yes')
(/river is in my public directory)

In order for it to run the scripts in index.html I had to treat the html like it was on a completely different site.This can't be the best way to do this.

The reason I want to put the html inside feeds.jade was I still wanted the top tabs from the keystone default layout. If there are other ways to include parts of the layout wihout using jade I'm open to that also.

However, I don't think it has anything to do with jade. 
In " routes/views/feeds.js" the line : "res.sendFile('/var/nodes/stone/mendo/public/river/riverdata/index.html');"
and
In "templates/views/feeds.jade" the line: "include ../../public/river/riverdata/index.html"
both get the same error in the browser console: "Syntax Error: JSON.parse:unexpected character" at the line where it calls a script inside the index.html file.

Also if I replace index.html with mytest.html which doesn't have any scripts, both of the above work.

It also works if you access the file directly in the browser with:
http://ec2.....amazonaws.com/river/riverdata/index.html
but then of course it doesn't have the layout tabs at the top.

If I wasn't such a novice I would say that there is a bug in the express program. But more than likely it has to do with my ignorance.

**Comment by webteckie** [comment]
Not sure if I capture your problem correctly, but you should be able to do something like:

```
    var view = new keystone.View(req, res);

    view.render('<whatever-path-has-your-html-file>/' + req.params.name,
        {

                return html;
        }
    });

```

**Comment by webteckie** [comment]
Sorry, pressed the Comment button before complete answer was ready.  I updated the answer above.  Again, not sure it is what you are looking for but something to chew on.

**Comment by DenDix** [comment]
If I understand your comment, I should put the following in feeds.js (there was an extra } in your code):
    view.render('feeds',
        {
               renderHtmlFile: function(path, options) {
                    // may need to read your html file synchronously here
                    htmlContent = sendFile(path);
                    return htmlContent;
                }
        }
    );

Then in feeds.jade I put:
    != renderHtmlFile('/var/nodes/stone/mendo/public/river/riverdata/mytest.html')
   
The idea here is that feeds.jade won't render until renderHtmlFile gets done reading the file?
But apparently sendFile is not the correct command. I got the error "sendFile is undefined". What do I use to actually read the html file?

I wouldn't think this would work any ways, since from my above comment:
In " routes/views/feeds.js" the line : 
    res.sendFile('/var/nodes/stone/mendo/public/river/riverdata/index.html');
also hangs even when no jade file is called to render.

Thanks for your help.

**Comment by cantuket** [comment]
Not very clean or performant solution, but you could just load the content through an AJAX call(s) from your Public folder if it isn't above-the-fold content, but since you say it impacts navigation this may not be an option. I haven't tested it, but you may be able just to add the below script directly to your HTML file, stick all outside scripts inside the on-load function and then use your initial Jade 'include'. This should defer the JS from running until the HTML is rendered. Then you may need to use jQuery to pull in any outside JS files  ...

```
$(window).bind("load",function() { 
// add scripts using jQuery's...
$.getScript( "/js/whatever.js");

});
```
For another project I did something similar because I was refactoring from another site with like 100 partials that need to be loaded dynamically and didn't want to convert it all to jade mixins. Unless this is the case for you I would highly recommend converting everything to Jade. The following package is the best I've found and is the only converter I've found where you can specify the Jade syntax/indentation...

[npm html2jade ](https://www.npmjs.com/package/html2jade)

I believe Keysonte is built to use mixins for this sort of thing though. I too would like to figure out how to implement @webteckie 's solution because this will be the most performant and scalable. I'll let you know if I manage to figure it out at some point.

**Comment by webteckie** [comment]
@DenDix no you wouldn't do sendFile from there.  You actually need to read the HTML file inside the renderHtmlFile block and return it.  That HTML will be inserted at the spot where you call the function from the container page and then the container page is returned.  Note that you can name the renderHtmlFile function whatever you want.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
