### ISSUE TITLE
Admin UI: How to attach a "pre-save" js code

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystone#1552]
I've looked on the issues but did'nt found... there is some "standard keystonejs way" to add some code to be run just BEFORE the actual model is saved?

What i want is to invoke TinyMCE *editor.uploadImages(...)* which would allow me to upload all pasted images to mongo.

**Comment by morenoh149** [comment]
http://mongoosejs.com/docs/middleware.html see `Pre`

**Comment by jacargentina** [comment]
No, i mean executing some javascript on the CLIENT side, just BEFORE the document is sent to the server (where yes i could handle that pre)

If there is no infrastructure to achieve that, would be nice begin working on some API to allow that @JedWatson  ?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
