### ISSUE TITLE
Inheriting models depends on filename

### ISSUE THREAD

**Issue by celiao** [keystonejs/keystone#1553]
I have the following models:
```
models/Repair.js
models/Maintenance.js
models/Service.js
```
and want Maintenance and Repair to inherit Service:
```
Maintenance.js

    ...
    var Maintenance = new keystone.List('Maintenance', {
        inherits: keystone.list('Service'),
    });
    ...
```
but I get the following error:
```
ReferenceError: Unknown keystone list "Service"
```

If I change the name of `Service.js` to `AAService.js`, it works fine.

Is there any way to remove the alphabetic dependency for `inherits:`, e.g., to specify a `List/model`creation order?

**Comment by webteckie** [comment]
Interesting! I'm assuming this is more of an issue when using keystone's dynamic model import.  If you, instead, use the manual "require" way of importing where you have an index.js with the list of require statements in the order you choose maybe it's not so much of an issue.  In the auto-import scenario perhaps keystone should support dynamically allocating lists if these haven't, yet.  It may need to cache the models directory (ies) so that keystone.list can use it.  Of course, this is assuming I understood the issue correctly.  @JedWatson and others may have a better solution.

**Comment by lojack** [comment]
@webteckie that is correct. I work around this by exporting any models that need to be inherited and setting the inheritance directly to the actual model. 

Service.js:

    ....
    model.exports = Service;
    ....

Maintenance.js:

    var Service = require('./Service');

    ...
    var Maintenance = new keystone.List('Maintenance', {
        inherits: Service,
    });
    ...

**Comment by webteckie** [comment]
@lojack curious, in your setup, is keystone also explicitly allocating the base Service model such that it is retrievable via keystone.list('Service')?  Or is Service, in this case, like an abstract interface that you cannot access via keystone.list('Service)?  If it is configured in keystone.list, is Service a polymorphic model that allows for fetching aggregated, per the original example, Maintenance and Repair listings?  Haven't worked with model inheritance, yet, but I may have a use case in my project that can make use of it.

**Comment by celiao** [comment]
Hey @lojack, thanks for your solution.  It works great!  I'm closing this issue.

**Comment by lojack** [comment]
@webteckie it is retrievable via `keystone.list('Service')` and also accessible within the keystone admin (with only the base fields)

**Comment by webteckie** [comment]
@lojack cool...I may be using this inheritance feature then.  Thanks!

**Comment by celiao** [comment]
Another nice trick is to hide the base model in the Admin UI and show the models that inherit.  e.g.,
```
in Service.js
...
var Service = new Keystone.List('Service', {
...
    hidden: true,
});

in Maintenance.js
...
var Maintenance = new Keystone.List('Maintenance', {
    inherits: Service,
...
    hidden: false,
});
```

**Comment by morenoh149** [comment]
@webteckie so do we need to document this implementation detail? no way to fix this right?

**Comment by webteckie** [comment]
@morenoh149 there's a lot of info here that probably should be documented.  Perhaps create a doc issue to handle it.
