### ISSUE TITLE
`isRequired` on a field with knex adapter throws errors during back link updates

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1553]
The back linking process for a to-single field uses a brute-force approach right now where it forces the linked field to `null`, then immediately after sets it to the id.

But if you've got `isRequired` set, knex will throw an error during the first phase of the back linking.

**Comment by singhArmani** [comment]
@jesstelford @MadeByMike : Hi guys, I couldn't reproduce this issue. It seems to be resolved. Closing it now :)

**Comment by MadeByMike** [comment]
Fixed by Tim \o/
