### ISSUE TITLE
Documentation Issue: Sass extension incorrect.

### ISSUE THREAD

**Issue by chriseaton** [keystonejs/keystone#1554]
I'm new to SASS and I ran into an issue following the documentation on the following page:
http://keystonejs.com/docs/configuration/

It mentions it will compile ".sass" files to ".css", but it actually will not - it compiles ".scss" files (note the "c"). If, like me, you name your files *.sass, they will not compile to css. 

Here's the wording (for the listed "sass" option), explicitly calling out to use the ".sass" file extension (which doesn't work):
> If you want Keystone to automatically compile **.sass** files into .css files, set this value to the same path as the static option.
When this option is set, any requests to a .css or .min.css file will first check for a **.sass** file with the same name, and if one is found, the css file will be generated.

**Comment by morenoh149** [comment]
What error did you get when you tried sass syntax?
You provided sass syntax in a `.sass` file? or some other combination? We should figure out how to support both.

**Comment by jacargentina** [comment]
I've had the same problem to figure out. By default it searches for files with `.scss` extension and NOT `.sass` as the Configuracion page states.

**Comment by giusepperj** [comment]
@chriseaton The node-sass package has an indentedsyntax option that lets .sass files get compiled. All you have to do is pass an object in the sass options of your keystone.js file and you're good to go.

**Comment by chriseaton** [comment]
@giusepperj Hi, sorry, a bit new to sass, does what you describe mean I should:

Instead of this
`keystone.set('sass', 'static');`
I should do this
`keystone.set('sass', {indentedSyntax: true, *other opts*});`

**Comment by giusepperj** [comment]
Sorry, I'm far from a computer at the moment but it is something like this.

Keystone.init({
'name':'...'
'...':'...',
'sass': 'static',
'sass options': {
indentedSyntax: true
}



G.
---
c. 3103514919
fb. giusepperj
twt. @giusepperj

**Comment by morenoh149** [comment]
if we make the default object here https://github.com/keystonejs/keystone/blob/20fede3b28932cf92fd41fd7e2941854b70e7996/lib/core/mount.js#L296 `sassOptions = this.get('sass options') || { indentedSyntax: true};` would that out of the box support for both syntaxes?

**Comment by morenoh149** [comment]
`keystone.set('sass options', { indentedSyntax: true })` @chriseaton does that work?

**Comment by chriseaton** [comment]
Late reply and this is closed, but the sass option suggested by @morenoh149 did not work. Keystone continues to ignore the .sass file, but as @jacargentina mentioned, it does look for the .scss file.

**Comment by chriseaton** [comment]
This is closed but I want to say for anyone else that finds this: The issue was ultimately I didn't realize sass and scss are actually differently formatted files. The .scss format is mixed css/sass, and the .sass is the indented *only* sass format. Look at the node-sass documentation for ref.

My bad!

**Comment by morenoh149** [comment]
@chriseaton so do you need to set the `indentedSyntax` option to true? if not then we need to revert the documentation

**Comment by chriseaton** [comment]
@morenoh149 Yeah, you need to set that if you want the *.sass files to compile. The *.scss files compile out of the box though. This was my own fault for not understanding the difference between sass and scss file formats.
