### ISSUE TITLE
Inconsistent failure behavior for view.query between development and production

### ISSUE THREAD

**Issue by gmmeyer** [keystonejs/keystone#1558]
If you have an error in your view's query queue, like the following:

```
  view.query('data.categories', keystone.list('PostCategory').model
    .where('name').in("hi I'm a string and mongoose can't map over me").sort('name'))
```

it will silently fail in development, but everything that doesn't rely on that will work. Basically, it works as if it isn't even there. In production, however, the entire rest of the initQueue will stop and render will be called right there. Now, this makes sense. What doesn't make sense is why the behavior is different.

If you call view.render with a function, instead of with a string, the behavior will be the same across production and development. The error will be handled in the render function.

What I can't figure out is why the behavior differs between production and development.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
