### ISSUE TITLE
Cannot create items

### ISSUE THREAD

**Issue by vucuong12** [keystonejs/keystone#1560]
I created a keystone.js folder using Yeoman. In file keystone.js, I add a some code right before keystone.start() to add an new item and list all current items like this:
	
    var newPost = new Post.model({
		title: 'New Post'
	});

	newPost.save(function(err) {
	    // post has been saved		
	});
	
	Post.model.find(function (err, posts) {
	  if (err) return console.error(err);
	  console.log(posts);    
	})
    keystone.start();

However, the posts in Post.model.find is an empty array, which means there was no item added. Can anyone help me out?
Thank you in advance.

**Comment by morenoh149** [comment]
That logic is better off in an update http://keystonejs.com/docs/getting-started/#runningyourapp-writingupdates
