### ISSUE TITLE
Heroku mandrill add-on without free tier

### ISSUE THREAD

**Issue by optikfluffel** [keystonejs/keystone#1561]
Hi, the mandrill add-on at Heroku now starts at 9,95$ a month. Maybe we should change to Mailgun, they still have a free tier of 400 messages per day?

**Comment by stosorio** [comment]
+1

**Comment by mark-bradshaw** [comment]
How about sendgrid?  Their free tier is also 400 a day.

**Comment by mark-bradshaw** [comment]
The more I think of it, what we really need to do is allow the sending engine to be decoupled from the implementation of lib/email.js, so that users can switch out for different engines at will.

**Comment by stosorio** [comment]
Absolutely. There seems to be an issue for that already: #528

**Comment by optikfluffel** [comment]
Closing in favor of #250
