### ISSUE TITLE
Update Multer

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1563]
[Multer](https://github.com/expressjs/multer) has been updated with breaking changes to the API. We need to review the changes and update the implementation in `lib/core/mount.js` accordingly.

**Comment by JedWatson** [comment]
So this is going to be much simpler is expressjs/multer#229 is merged, otherwise we'll have to change the public API significantly for application routes and pre-generate Admin UI routes that accept white-listed field names. Fingers crossed.

**Comment by mxstbr** [comment]
This can be closed

**Comment by JedWatson** [comment]
@mxstbr actually... multer is still pinned to an old version, this is still an active concern. Just lower priority than other issues in 0.4

**Comment by bassjacob** [comment]
I've picked this up at https://github.com/keystonejs/keystone/pull/3794 and will make the changes there.

**Comment by jstockwin** [comment]
> So this is going to be much simpler is expressjs/multer#229 is merged

This has been merged and released into 1.1.0, if this helps anything? cc/@bassjacob @JedWatson

**Comment by bassjacob** [comment]
yep, the .any change should make this an out of the box fix. I'm going to have a look into their security recommendations and timebox that before just shipping to .any change.

**Comment by stennie** [comment]
Closing as a duplicate of #4428, which will be addressed in Keystone `4.0.0-rc.2`.
