### ISSUE TITLE
You cannot update populated relationships

### ISSUE THREAD

**Issue by hatzipanis** [keystonejs/keystone#1567]
`Error: fieldTypes.relationship.updateItem() Error - You cannot update populated relationships.`

Why not? :pensive:

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by steveinatorx** [comment]
i work around this issue by saving off the populated field to an array variable, deleting the populated parameter, then mapping and converting the populated objects to objectIDs and then mutating the array and saving the object with regular mongo save.  It probably isnt the safest pattern but it works

```
//doc.linkedData = the populated field
var linkedArr=doc.linkedData.map(function(o){
        return safeObjectId(o._id);
});    

//mutate the array as you need
linkedArr.unshift(safeObjectId(newLinkedDatum._id));
doc.linkedData=linkedArr;
                   
doc.save(function(err) {
   
   // error check, do stuff

});

```

**Comment by lglossman-ring** [comment]
My workarounds was to populate a different field using [Mongoose virtuals](http://mongoosejs.com/docs/populate.html)

Here is an example of single and many relationships:

`
User.add({
        ....
	location: {type: Types.Relationship, ref: 'Location', required: false, index: true, many: false},
	teams: {type: Types.Relationship, ref: 'Team', many: true, required: false, initial: true},
        ....
});

User.schema.virtual('_location', {
	ref: 'Location',
	localField: 'location',
	foreignField: '_id',
	justOne: true // for single relationship

});

User.schema.virtual('_teams', {
	ref: 'Location',
	localField: 'location',
	foreignField: '_id'
});

function populate(next) {
	//this.populate('location teams'); // Populating original fields breaks KeystoneJS Admin UI
	this.populate('_location _teams');
	next();
}

// Hooks to populate relationship fields automatically
User.schema.pre('findOne', populate);
User.schema.pre('find', populate);
`
