### ISSUE TITLE
Database Field filter condition or - admin or owner

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1568]
Hi,

from http://keystonejs.com/docs/database/, we are able to filter The relationship using ```filter```
```
author: { type: Types.Relationship, ref: 'User', filters: { group: 'admin' } }
...
bestPost: { type: Types.Relationship, ref: 'Post', filters: { author: ':_id' } }
```

My question is how can we filter on ```or``` - either ***admin or the owner***?

**Comment by mxstbr** [comment]
The filters are completely revamped in 0.4, take a look!
