### ISSUE TITLE
Aggregate project items created with 7 days

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1570]
Hi,

I tried to match items created 7 days again, however, it always return an empty list

this find works and return a list.
``` 
Reading.model.find({createdAt: {'$gt': moment().subtract(7, 'days') }})
```

but this match>project return emtpy:

```javascript
Reading.model.aggregate([
  { $match: {
       createdAt : { $gt: moment().subtract(7, 'days') }
      }   
  },
  { $project: {
      _id: 0,
      createdAt: 1,
      hour: { $hour: "$createdAt"  },
      weekday: { $dayOfWeek: "$createdAt"  }
    }
  }
])
```

It is very weird for me, removing the $match options can get return indeed.

**Comment by morenoh149** [comment]
does the same aggregation work from the mongo shell?

**Comment by creynders** [comment]
closing this, since it doesn't really have anything to do with keystone. If I'm mistaken, please reopen.

**Comment by yao23** [comment]
It complains aggregate not found

**Comment by yao23** [comment]
correct syntax: 

    keystone.list('Reading').model.aggregate([ ]).exec(function(err,data){console.log(data);})

**Comment by bilalyaqoob** [comment]
var Prospect = keystone.list('Prospect');
var Quote = keystone.list('Quote');
Prospect.model.aggregate([
		{ $lookup:{
				from: "Quote",
				localField: "_id",
				foreignField: "prospectId",
				as: "dat"
		}},
		{ $project:{
				grandTotal:1,
				city:1
		}}
	]).then(function (prospect) {
		 console.log('====================================');
		 console.log(prospect);
		 console.log('====================================');
	});
