### ISSUE TITLE
Would it be possible to attach properties to a Types.Relationship field?

### ISSUE THREAD

**Issue by ivarni** [keystonejs/keystone#1572]
I'm trying to create a cookbook using keystonejs and I want to do things like scaling recipes and calculating total nutritional values for a meal so I'll need something beyond plain text/html to model which ingredients go into a recipe.

Ideally, I'd love to be able to do the following

```
var Recipe = new keystone.List('Recipe');
Recipe.add({
    name: {
        type: String,
        required: true,
        index: true
    },
    ingredients: {
        type: Types.Relationship,
        ref: 'Ingredient',
        amount: Types.Number,
        many: true
    }
});
```

That is, I'd like to attach arbitrary metadata to a relationship. From what I can tell this is not something that's currently possible (and please do correct me if I'm wrong, being wrong is a great chance to learn).

I imagine the resulting collection for a recipe could look something like

```
{
    "_id": {
        "$oid": "555f4e949a632934180e752b"
    },
    "__v": 1,
    "ingredients": [
        {
            "$oid": "55a8bb691b6647c40ad7aef6",
            "amount": "300"
        },
    ],
    "name": "300 boiled somethings"
}
```

For the admin UI, possibly one of them material design (+) buttons popping up both a select for the relation and an appropriate input field for the type of metadata.

I realize that this would probably mean having to introduce a new data-type (because it would require a different admin UI from what is currently used for relationship) and that my usecase might be too localized to really be useful but I'm giving it a shot to see what you think.

If it's something that stands a chance of eventually being merged, I'd be happy to try my hand on creating a PR.

**Comment by mandb** [comment]
This sort of goes against the fundamental design ideology of noSQL.  That being said, you can create a remote-field array inside keystone and link it to another collection, but this will ONLY allow you to add the objectIDs for the remote documents in a remote collection, it will not allow you to then append extra things to it such as a quantity of ingredients.

**Comment by NullEntity** [comment]
Create a new List as a container to store a relationship to an Ingredient and its Quantity. Then the Ingredients relationship can point to an object in that new list.

**Comment by ivarni** [comment]
Fair enough :)
