### ISSUE TITLE
Add a `REST` database adapter

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1573]
We have mongoose, knex, and [soon](https://github.com/keystonejs/keystone-5/issues/1177) json adapters. These all assume that the database sits directly below Keystone.

What about the case where there is existing REST endpoints which sit below Keystone? Or maybe some other data source (socket based RPC, etc)? Can we build a database adapter that allows a Keystone App developer to leverage their existing infrastructure, effectively putting a GraphQL layer in front of the REST endpoints, but with all the benefits of relationships and filtering and meta queries, and and and all the fun stuff KS5 comes with for free?

Something like:

```
+-------------------------------+
|                               |
|         Keystone 5            |
|                               |
|  +-------+     +---------+    |   +----------+     +----------+
|  |       |     |         |    |   |          |     |          |
|  |       |     |         |    |   |          |     |          |
|  |GraphQL+---->+ REST DB +------->+   REST   +---->+ Database |
|  |       |     | Adapter |    |   | Endpoint |     |          |
|  |       |     |         |    |   |          |     |          |
|  +-------+     +---------+    |   +----------+     +----------+
|                               |
+-------------------------------+

```

**Comment by VinayaSathyanarayana** [comment]
I support this. Hasura.io and other provide similar functionality

**Comment by VinayaSathyanarayana** [comment]
Any update on this?

**Comment by gingibash** [comment]
@molomby can't you just use Apollo's RESTDataSource?

**Comment by timleslie** [comment]
Closing this as we've decided to focus on the Prisma adapter as our primary database adapter, freeing up resources to focus on other parts of the system. https://next.keystonejs.com/roadmap#streamlined-back-end-with-prisma
