### ISSUE TITLE
Wysiwyg support for S3

### ISSUE THREAD

**Issue by jrit** [keystonejs/keystone#1574]
There is support for Cloudinary uploads in wysiwyg but none for S3 uploads, so I just added that on my fork. This seems like it would be a useful feature, but some of the setup I have isn't that elegant right now:
- The `doUpload` function in `fields\types\s3file\S3FileField.js` has some core S3 handling code that feels like it should be shared if uploads are going to happen in other places, like the new `admin\api\s3.js` file that I added to enable this support. (Matching the routing and directory structure for cloudinary)
- In the configuration, there is a property of `wysiwyg cloudinary images` so the reasonable setting to add for S3 would be `wysiwyg s3 images` - I really just wanted to see if you agree with that.

Let me know if you have any feedback.

Ref https://github.com/jrit/keystone/commit/74aba49aa7132b6aec0a529680655588e66b5001

**Comment by jeffreypriebe** [comment]
I've been looking at similar goals (S3 in wysiwyg). Your API setup seems like a good idea.
Given that it puts files accepted over the wire, I would definitely implement the CSRF checks. Look at [list.js#L79-81](https://github.com/jrit/keystone/blob/master/admin/api/list.js#L79) for an example:
```
if (!keystone.security.csrf.validate(req)) {
	return sendError('invalid csrf');
}
```

(The cloudinary upload should API probably have these as well.)
