### ISSUE TITLE
autoCleanup for CloudinaryImage type doesn't work on 'Remove Image'

### ISSUE THREAD

**Issue by autoboxer** [keystonejs/keystone#1577]
I tracked it down to code responsible for saving to Cloudinary not executing when removing an image.  The code which should run is in an ```else if``` statement in 

keystone -> fields -> types -> cloudinaryimage -> CloudinaryImageType.js 

at line 375 due to ```req.files[paths.upload]``` being set to undefined.  ```req.files[paths.upload]``` is set to an ```Object``` during 'Upload Image' and 'Change Image' operations.  This value being ```undefined``` causes the code at line 430 of the same file beginning with ```imageDelete.onFulfill(function(result)``` to never execute, and the file removal never to propagate to Cloudinary.

**Comment by morenoh149** [comment]
@autoboxer any ideas on how to get to be defined?

**Comment by autoboxer** [comment]
I haven't had a chance to dig deeper into the code, but I'll post or create a pull request if I can figure it out.

**Comment by autoboxer** [comment]
@morenoh149, I've dug as deep as I can go without speaking to a developer on the team who can help me track it further.  Here's what I've discovered.  When the Save button is clicked for an item, the ```UpdateHandler.prototype.process(data, options, callback)``` function is called.  In the ```req``` object, there is a member property that drives the Cloudinary functionality, called ```req.files```.  

When a ```cloudinaryItem``` upload action occurs, ```req.files``` is set to an object with identifying information about the file to upload.

When a ```cloudinaryItem``` change image action occurs, ```req.files``` is set to an object with identifying information about the file to upload.

When a ```cloudinaryItem``` remove image action occurs, ```req.files``` is set to an empty object.

I believe the cause of the problem is ```req.files``` being set incorrectly when initiating a remove image action.  If it were set, the following check at line 365 of CloudinaryImageType.js, ```else if (req.files && req.files[paths.upload] && req.files[paths.upload].size) {...```, would execute, binding the promise and removing the remote image.

I'd be happy to help fix this, but can't figure out how to alter the request object, and would need a team member with understanding of this code to talk to.

**Comment by mxstbr** [comment]
We're revamping all of that currently, so this should be working very soon! Thanks for notifying us and the detailed dig down!
