### ISSUE TITLE
Help on embedding CID images using keystone mailer 

### ISSUE THREAD

**Issue by mldangelo** [keystonejs/keystone#1580]
Hey all, 

I'd like to embed a CID image using the keystone mailer, but I'm not exactly sure where or how to start. I understand how to add hyperlinked images and base64 encoded images, but gmail doesn't like to display either of those formats. Is there a way to add CID images using a jade email template? Or does functionality need to be added to lib/email.js? Thanks so much!

**Comment by morenoh149** [comment]
I think [lib/email.js](https://github.com/keystonejs/keystone/blob/abc5e58f75cdac12e31cc24e3876e8650dee0448/lib/email.js) would have to be expanded to add an `images` field to out going message objects https://mandrillapp.com/api/docs/messages.nodejs.html#method=send

**Comment by morenoh149** [comment]
closing because I think I explained what's required. Reopen if you still have problems.
