### ISSUE TITLE
How can I preview an image from a image url in admin edit mode?

### ISSUE THREAD

**Issue by lkho0215** [keystonejs/keystone#1581]
<tt>
```
Photo.add({
	name: { type: String, required: true },
	publishedDate: { type: Date, default: Date.now },
	url:{
		type: Types.Url,
		format: function(url){
			return url;
		}
	}
   });
```
</tt>

Url is a link that can directly access through the browser. Now, I can only display this link and view that image by clicking the link but I want to preview it in the item list rather than clicking it the view. How can I do it? Thank you.

**Comment by morenoh149** [comment]
the url fieldtype could be expanded to accept a new format option `image` which will attempt to inline the url as an image in the adminUI https://github.com/keystonejs/keystone/blob/751c82955b481d85156470c317eb80c8c1e036ea/fields/types/url/UrlType.js#L13 http://keystonejs.com/docs/database/#fieldtypes-url

@JedWatson thoughts?

**Comment by SlashmanX** [comment]
Doesn't the `format` for URL work the same as for LocalImage, where you can display the image inline if you wanted?

http://keystonejs.com/docs/database/#fieldtypes-localfile

**Comment by morenoh149** [comment]
@SlashmanX that would be very cool if it's true. Can't test it myself. If it works it should be documented for the `URL` fieldtype as well.

**Comment by lkho0215** [comment]
@SlashmanX I only got the URL of the image. Is it possible to save it to the LocalFile field?
My aim is to let user can see the photos in the mongodb and then select one of them and view the details. Therefore, I just display all the images in another layout and link it to the keystone admin page while the user click that photo.

**Comment by SlashmanX** [comment]
Did you try: 

```
Photo.add({
    name: { type: String, required: true },
    publishedDate: { type: Date, default: Date.now },
    url:{
        type: Types.Url,
        format: function(url){
            return '<img src="'+url+'" style="max-width: 300px">'
        }
    }
   });
```

?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by playwolf719** [comment]
@SlashmanX Acturlly it's not working for me, do you have any other solution?

**Comment by ZeroCho** [comment]
Is there any way to see image in Admin UI? format function doesn't work.

**Comment by Pei116** [comment]
Any updates here?

**Comment by tomtom87** [comment]
Looking for a way to do this also, if anyone has any ideas.

@ZeroCho I think because it's using Storage class now, format is deprecated.
