### ISSUE TITLE
Quick Start tutorial images are broken

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1581]
On https://v5.keystonejs.com/quick-start/ the thumbnails appear oddly (it looks like 3 images are kinda smooshed into one):

<img width="793" alt="Screen Shot 2019-09-03 at 6 55 04 pm" src="https://user-images.githubusercontent.com/612020/64158740-5d69eb80-ce7c-11e9-92df-cd535d089d4d.png">

And clicking that thumbnail takes you to a 404:

<img width="742" alt="Screen Shot 2019-09-03 at 6 55 55 pm" src="https://user-images.githubusercontent.com/612020/64158800-7a9eba00-ce7c-11e9-94d8-9f871f70f7f3.png">

**Comment by singhArmani** [comment]
@MadeByMike: do you have any updates on this? It seems the thumbnail link is working as expected and to me the thumbnail doesn't appear to be oddly as mentioned 😄
