### ISSUE TITLE
How to get an admin "edit" link for a given document instance

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystone#1584]
I've searched on keystone sources, for an utilitary function to get an "edit" link (or at least the valid href path) so i can generate on my own jade templates, an "Edit this" button, when users are keystone admins.

So far, i've found the paths are actually embeded, for example on the `templates/mixins/columns.jade` i see this around line 18:

````jade
    if col.refList && refData && refData.id
        +column_link(value, '/keystone/' + col.refList.path + '/' + refData.id)
    else
        +column_basic(value)
````

Would be nice to add (if not existing yet of course) an utilitary mixin to generate that path based on a given document, for example:

````jade
    +get_edit_link(doc_instance)
````

I can try to help implementing this. 

@JedWatson, thoughts?

**Comment by JedWatson** [comment]
that's a good idea, I think the best way is to make a function on the `List` that does it. Gimme a sec.

**Comment by JedWatson** [comment]
What do you think of

`List.getAdminURL(item)`?

Might be better to be more generic than `edit` (since it may be read-only) and it's a URL, not a link...

**Comment by JedWatson** [comment]
Added it :grinning:

**Comment by jacargentina** [comment]
Nice! On the List route, i can then query that function, and pass it to the `locals` to render where needed on the template. I'm just interested on that href by now, but if there are others over there, would be nice also to make them *API accesible*. Do u think other cases on those jade templates?

**Comment by JedWatson** [comment]
What do you mean by _API Accessible_?

Heads up, I'm busily refactoring the entire Admin UI into a single page react app right now... see `elemental-integration`

That includes integration with the new API endpoints I've been adding.

**Comment by jacargentina** [comment]
I didn't mean *API* ala *external web service endpoint* but just *access it programatically from other place* :)

**Comment by JedWatson** [comment]
We need different words for that :)

Does that commit give you want you need?

**Comment by jacargentina** [comment]
Yes!
:+1:

**Comment by webteckie** [comment]
Requires documentation?

**Comment by JedWatson** [comment]
@webteckie good call.

**Comment by JedWatson** [comment]
@webteckie actually I'm not sure we _have_ the `List` API documented anywhere :disappointed:
