### ISSUE TITLE
Please create a Koa fork. Why stay on Express forever... should be easy to upgrade :)

### ISSUE THREAD

**Issue by kristianmandrup** [keystonejs/keystone#1586]

**Comment by LorbusChris** [comment]
was was this closed? please explain

**Comment by morenoh149** [comment]
It didn't sound like an earnest request. I'd personally like to see a argument for why this is the best thing to do. As far as I can tell koa isn't as popular as express. And though it's billed as a successor to express I'm not sure it's the right move for keystone. If in the future it's evident everyone prefers koa over express then maybe then keystone would be written to use it.

**Comment by LorbusChris** [comment]
That's a fair point, thanks. Maybe the discussion could happen here, though. Maybe reopen and label it "suggestion"?

**Comment by kristianmandrup** [comment]
I ported it to Koa in less than 1 hour. Now making all the tests pass. No big deal ;)
I only use Koa myself. Why stay with ancient tech :P ES2015 is live and kicking!!!!

**Comment by kristianmandrup** [comment]
All test pass with koa :)

```sh
✘-4 ~/repos/koa-projects/keystone [koa|✚ 10…7] 
23:26 $ mocha
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version


  225 passing (145ms)
```

**Comment by NullEntity** [comment]
This shouldn't be closed yet @kristianmandrup . You should justify why Keystone should use Koa over Express. I'm totally for it myself. I believe the generator syntax can really help clean up the code base and make it a lot more clear what some stuff is doing. I'm not a fan of callbacks in Express at all.

**Comment by kristianmandrup** [comment]
Thanks @NullEntity 
I believe Keystone should support both Express and Koa for the time being. Why I made a Koa fork (and it works now). 

It also includes support for Stylus (over SASS). Pure Node.js, way better... ;) Much simpler and more powerful! I'd never use SASS again

**Comment by LorbusChris** [comment]
+1 for dual Express/Koa support. Maybe this can be done with the Yeoman Generator? 
From what I've read, Koa seems to be a good alternative. Their Repository doesn't seem overly active, though.

**Comment by kristianmandrup** [comment]
As TJ wrote in a post. They pretty much "nailed" Koa on their first design attempt. It is super minimal (like ~500 lines of code), everything else in modules/middleware. 
Why there is hardly ever any reason to touch it...

**Comment by JedWatson** [comment]
I'm for dual Express and Koa support, and props for getting that version up and running so quickly @kristianmandrup.

_However_ I'm concerned by forking at this stage; I'm planning a fairly significant refactor of the Express implementation in Keystone as soon as we get the next version out. I would have done it sooner but don't want to introduce too many potentially breaking changes in one version, so I've been treading around it for now (you can see the start of it with the new `/admin/app` code).

Can I suggest that we hold off until `0.4` is out, then we can do the following:

- Refactor and isolate the Express implementation into `keystone-express`
- Re-implement that as `keystone-koa` and allow developers to choose one or the other

As for the Stylus support, @kristianmandrup would you mind submitting that as a PR against the `master` branch? I'd love to add that in.

**Comment by JedWatson** [comment]
I opened a new issue to discuss the longer term plan of supporting koa properly, let's continue the discussion about the plans for official dual support there.

**Comment by kristianmandrup** [comment]
The stylus integration is about 5 lines of code, mostly copy paste of the less part, except substituting `less` for `stylus` and using `require('koa-stylus')` mw. No magic there.

With respect to express vs koa. Really, the express/koa part is pretty minimal. It took me less than ~1hour to get that working, mostly related to using more koa mw modules instead of built in express equivalents. The main "pain" was to refactor the tests, but once I got one working, the rest was grunt work... I think it would be awesome to extract modules `keystone-koa` and `keystone-express` :)
Exactly the right strategic mindset! For now, let's keep the branch. I'm using it on my own projects in progress already.. but is "unofficial support", no worries. Do your 0.4 refactor, then extract `keystone-express`, then lets use my fork as reference for `keystone-koa`
