### ISSUE TITLE
View on('post') in series?

### ISSUE THREAD

**Issue by udp** [keystonejs/keystone#1587]
Currently if I register several on('post') in a view e.g.

    view.on('post', function a() { ... });
    view.on('post', function b() { ... });
    view.on('post', function c() { ... });

They are pushed to the action queue in order, but view.render then pushes the whole action queue to the initQueue:

	this.initQueue.push(this.actionQueue);

Which results in the functions being executed in parallel:

	async.eachSeries(this.initQueue, function(i, next) {
		if (Array.isArray(i)) {
			// process nested arrays in parallel
			async.parallel(i, next);

So there's no way to get the on('post') to run in series.  The comment for render says:

     * It is expected that *most* init stacks require processing in series,
     * but it is safe to execute actions in parallel.
     *
     * If there are several init methods that should be run in parallel, queue
     * them as an array, e.g. `view.on('init', [first, second])`.

regarding init functions, so why should action functions be any different?  I think the assumption that actions can be executed in parallel is dangerous and provides little benefit.

**Comment by udp** [comment]
Any thoughts on this?  I'm still using a fork of Keystone to avoid this problem.

**Comment by morenoh149** [comment]
If your fork has a solution please share it as a PR.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
