### ISSUE TITLE
Empty string in required string field fails validation

### ISSUE THREAD

**Issue by udp** [keystonejs/keystone#1588]
Field.prototype.validateInput = function(data, required, item) {
        if (!required) return true;
        var value = this.getValueFromData(data);
        if (value === undefined && item && item.get(this.path)) return true;
        if ('string' === typeof data[this.path]) {
            return (data[this.path].trim()) ? true : false;
        } else {
            return (data[this.path]) ? true : false;
        }
    };

Empty strings are falsy in JavaScript.  What if I want to populate a string field that has required: true, but I want to populate it with an empty string?  The validation will fail.

**Comment by morenoh149** [comment]
@udp add a solution to handle empty strings then. Like this commit https://github.com/keystonejs/keystone/commit/43c5d3f88afda7159c8588296e1433aa317abc4a

@JedWatson is there any reason the `type.js` isn't in it's own folder? I'm asking because I'm curious how adding tests for the `type` file might work.

**Comment by creynders** [comment]
It doesn't make sense IMO to have a required field not fail on an empty string. That's why it's required, no?

**Comment by udp** [comment]
Isn't there a difference between "not present" and "present and empty"?

**Comment by creynders** [comment]
Yeah, but then it's not required. It just needs a default value.

```js
{
  required: false,
  default: ''
}
```

**Comment by JedWatson** [comment]
@creynders is correct, the "required" state for `text` fields means it needs a value (and not a blank string). The default value is the correct workaround for what you're talking about @udp - no need to validate that.

@morenoh149 I'm not sure that `type` needs independent tests, it should be covered by `text` type tests as none of the default behaviours in `type` are replaced or extended. At the moment it's on its own for clarity; it's not usable in the way the other types are. If we want to test it directly, those tests could go in the main `test` folder on the top level of Keystone.
