### ISSUE TITLE
Further leverage schema-first GraphQL and directives

### ISSUE THREAD

**Issue by rajington** [keystonejs/keystone#1588]
The GraphQL portion of this is extremely attractive, and I think there's the potential to extend it all the way to schema definition and more with schema-driven design.

Instead of:
```javascript
keystone.createList('Todo', {
  fields: {
    name: { type: Text },
  },
});
```

We could define:
```graphql
type Todo {
  name: String!
}
```
This is similar to [Prisma's datamodel.graphql](https://www.prisma.io/docs/reference/service-configuration/data-model/data-modelling-(sdl)-eiroozae8u#example)

Even for the views I like the concept of defining some things in GraphQL, for example:
```graphql
query Todos($completed: Boolean){
  todos(completed: $completed) {
    name @title("title")
  }
}
```
Would automagically generate a page showing all the todos, create a checkbox to modify the query arguments, and output the results in a table with the name field in a "title" column. 

```graphql
@description("Create a new Todo")
mutation AddTodo($name: String! @placeholder("Pick Up Milk...")) {
  createTodo(name: $name) @refetch("Todos")
}
```
This would create a form for a new todo with a title and placeholder, it could be combined with above.

Obviously can extend to mutations and custom UI elements could be defined via fragments on types:
```graphql
query Users {
  avatar @fragment("profile")
}
```

**Comment by MadeByMike** [comment]
Hi @rajington thanks for the kind words!

We totally agree that you could determine a simple list with just a schema definition and we'd love to create a package that takes a schema and creates Keystone lists. It's something we've talked about a few times. 

Unfortunately we cannot completely do away with `keystone.createList` as there is a lot more that can happen here including defining access control, how fields appear in the adminUI, as well as plugins, hooks and more...

But YES, there are big similarities between defining lists and schema and we would like to make going between these easier.

I would love to hear more thoughts on this, if you have any.

**Comment by rajington** [comment]
> defining access control
I've seen [good examples](https://www.prisma.io/blog/graphql-directive-permissions-authorization-made-easy-54c076b5368e) of using schema directives for even field-level access control, I feel it'd be a great case for schema directives.

> how fields appear in the adminUI
I was trying to demonstrate that with the `@title` directive but I think you could accomplish pretty advanced layout techniques as well. I could expand on the fragment example to show how you could really customize their appearance in a modular way.

> as well as plugins, hooks and more...
It's hard to say everything has directive examples, but if they're currently being defined in `createList` then I think the SDL would be the right (if not better) place.

**Comment by MadeByMike** [comment]
Directives look like a great way to do a lot of things, but wouldn't this force us to have a set of pre-defined access control functions/rules? 

The way our access control work, you can define any function you want. You get access to an authentication object and might want to do any number of complicated things.

Here is an example from an application I'm working on where I have a list of `Comments`. For read access I want to filter the results to only include items that have been approved unless the authenticate user is an admin user, in which case I will return all comments.

```javascript
const Comment = {
  fields: {
    comment: { type: Text }
    approved: { type: Checkbox },
  },
  access: {
    read: ({ authentication: { item } }) => {
      if (item.isAdmin) {
        return {}; // Don't filter items for admin users
      }
      // Return only approved comments
      return {
        approved: true
      };
    }
  }
};
```

This is a really simple example but I think the point is we don't want to force users to have a 'role' based access control system or any other specific system. I think that is a strength of Keystone. It doesn't force you down any path.

That said I am still **very** interested in these ideas because we want to make the most common path easy without sacrificing the flexibility.

One thing we could do is define a bunch of common directives for things like access control so that people can user them if they want. We could then feed these into a middleware that generates Keystone lists and then allow users to augment these lists further before initialising these in Keystone.

What I'm thinking is some kind of `schema-to-list` package that people can opt into. A standalone package that gives you these options and perhaps some more opinionated options around access control etc.... I think that would be useful for some people.

**Comment by gautamsi** [comment]
I like  `schema-to-list` approach very much, we can also have canned set of features for the list including authentication but can also use the resolvers as part of `schema-to-list` which can contribute to GraphQL layer customizations including role based access.

**Comment by MadeByMike** [comment]
> which can contribute to GraphQL layer customizations including role based access.

Exactly this

**Comment by jesstelford** [comment]
Using a JS based schema definition was a conscious decision for the reasons @Madebymike mentioned above (and many others). Generating a GraphQL API based on a GraphQL SDL is not something which would ever make it into core, however Is happily link to a 3rd party package `schema-to-list` (or perhaps `sdl-to-list`?) somewhere in the docs if it's in enough demand 👍

**Comment by rajington** [comment]
In that Prisma example they do show specific directives, but these directives aren't part of any spec, they're completely custom implementations ([Apollo example](https://www.apollographql.com/docs/graphql-tools/schema-directives/#uppercasing-strings)).

Directives themselves act more like a "middleware" and keystone could provide common ones like you mentioned, but also let users define custom (and reusable) directives that can be take in arguments as well as leverage various information from the schema and runtime values.

For your specific example, I think that's better solved with multiple resolvers rather than one that behaves differently, since they fit two different product usecases (user viewing comments, or an admin viewing unmoderated comments to approve).

This is a rough example of what yours might look like:

# data model 
```graphql
type Comment {
  comment: String!
  approved: Boolean!
}
```
# auto-generated query (~[OpenCRUD](https://github.com/opencrud/opencrud))
```graphql
type Query {
  comments(where: CommentWhereInput): [Comment!]!
}
```
# restricting generated using a [custom-defined directive](https://www.apollographql.com/docs/apollo-server/schema/creating-directives/#enforcing-access-permissions)
```graphql
extend type Query {
  comments(where: CommentWhereInput): [Comment!]! @auth(requires: ADMIN)
}
```
# custom un-authed comment query
```graphql
extend type Query {
  approvedComments: [Comment!]!
}
```
```typescript
const resolverMap = {
  Query: {
    approvedComments() {
      return comments.filter(comment => !comment.approved)
    }
  }
}
```
and to demonstrate how powerful SDLs might be, although I haven't seen this implemented anywhere yet, I believe we'll eventually be using shortcuts to implement resolvers that compose other resolvers using only SDL... something like
```graphql
extend type Query {
  approvedComments: [Comment!]! @`
    {
      comments(where: { approved: true })
    }
  `
}
```

**Comment by rajington** [comment]
@jesstelford I definitely think this can be a 3rd party integration or decided based on popularity, but I feel the approach is flexible and powerful enough that it's interesting to explore as the **primary** way to accomplish things. I personally feel leveraging the SDL reduces complexity and creates a stronger integration point for developers to leverage.

I say this with complete appreciation for all of keystone's previous work, and this new effort, and I completely understand if this level of GraphQL adoption isn't what you had in mind.

**Comment by timleslie** [comment]
This is an interesting discussion for the archives, but I don't think there's any further action to be taken in the core repo based on this ticket, so I'm going to close this issue 👍
