### ISSUE TITLE
Relationship Type - Random order

### ISSUE THREAD

**Issue by mosey101** [keystonejs/keystone#1595]
When adding and saving new items into a 'relationship' field with the 'many: true' setting, when clicking save, on page refresh, the results are randomised.

Checking the database, they're inserted in the correct order so the issue is only visually wrong on the CMS.  This is most likely due to the asynchronicity of keystone,

E.g.
Projects: A, B, C
Save & page refresh
Projects: B, C, A
Save (With or without changes) & page refresh again
Projects: C, B, A
Save (With or without changes) & page refresh again
Projects: B, A, C

Is there a way to force this section to be synchronous or is there another setting that can prevent this?

Thanks

Ian

Tested on versions 0.2.42 & 0.3.4

**Comment by lojack** [comment]
This was fixed by #1281 which should be included in 0.3.5

**Comment by mosey101** [comment]
Great stuff thanks!
