### ISSUE TITLE
Add support for koa

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1599]
Following up on the conversation in #1586

At _some_ point (after 0.4) we will look into separating out the Express implementation into its own package, so we can also support Koa and give developers a choice between the two.

**Comment by andyhu** [comment]
+1
IMO it's better support koa 2.0 and use babel + ES 2016 async await

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/koa-support!
