### ISSUE TITLE
Forum on the keystonejs.com website

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#160]
It'd be nice to have a forum on the actual website rather than pushing people off to a Google group. We could allow Google authentication (along with Twitter and Github) to make the experience as seamless as possible.

This would also be a great way to showcase the flexibility and functionality of KeystoneJS at solving common problems on the web.

**Comment by dcousens** [comment]
Closing.  This is not high priority and the idea appears to have been abandoned. @JedWatson re-open if necessary.

**Comment by creynders** [comment]
Just jotting it down here in case people stumble upon this, when searching for it: the official two forums ATM are the [google group](https://groups.google.com/forum/#!forum/keystonejs) and [gitter](https://gitter.im/keystonejs/keystone). With gitter clearly gaining popularity. We've got [slack](https://keystonejs.slack.com) too, but you need an invite first and it's restricted to contributor discussion, i.e. no keystone usage QA.

**Comment by jossmac** [comment]
If anyone is looking for a forum implementation in keystone: https://github.com/JedWatson/keystone-forum

**Comment by JedWatson** [comment]
aah the gap between "basically ready to go" and "we can use it in production"

maybe one day we'll revisit the "build our own forum" idea but for now I'm happy to let this go and leave the project Joss linked as a reference.
