### ISSUE TITLE
Referencing embedded/related document attributes in schema?

### ISSUE THREAD

**Issue by kristianmandrup** [keystonejs/keystone#1603]
I have the following model schema. Was wondering how best to do the auto key for `CartItem`.
is it possible to reference the embedded/related document such as product like `product.sku` ? 
Alternatively do I need to update a CartItem attribute of the same name every time I update the related document somehow? how would I best achieve this?
Documentation does not cover this scenario, but must be a common question... 
Thanks ;)  

```js
var keystone = require('keystone'),
    Types = keystone.Field.Types;

var CartItem = new keystone.List('CartItem', {
    autokey: { path: 'slug', from: 'product.sku', unique: true },
    defaultSort: '+product.sku'
});

CartItem.add({
    quantity: { type: Number, required: true, default: 1 },
    product: { type: Types.Relationship, ref: 'Product' }
});

module.exports = CartItem;
```

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
