### ISSUE TITLE
Admin UI - multiple fields on same line

### ISSUE THREAD

**Issue by celiao** [keystonejs/keystone#1609]
Is it possible to have Keystone JS Admin UI display multiple fields on the same line in a detail view (like Location's State and Postcode, or Split Name's first name and last name)?

**Comment by JedWatson** [comment]
There's no way to do this at the moment, I'm marking this for the roadmap while we settle down the major upcoming release. It's definitely something I'd like to add.

**Comment by celiao** [comment]
This could be implemented by allowing arrays of Objects in Object.add().  e.g.,
```
Post.add({
    [ category: { type: Types.Select, options: 'user, editor, admin', default: 'user' },
      title: { type: String, required: true },],
    author: { type: Types.Relationship, ref: 'User', filters: { group: 'admin' } }
});
```
would result in `category` and `title` on the same line.

**Comment by mxstbr** [comment]
This will be possible with the new `keystone.set('admin ui styling')` option, so I'll close this!

**Comment by forsetius** [comment]
Where can I find some documentation on how to use this `keystone.set('admin ui styling')` option? Some example perhaps?
