### ISSUE TITLE
Admin UI - colored text

### ISSUE THREAD

**Issue by celiao** [keystonejs/keystone#1613]
Is it possible to display colored text in the Admin UI?

For example, I'd like to use a Generated Value Field (computed via watch and value), with possible values:
- `'<span style="color:green">Acceptable</span>'`
- `'<span style="color:yellow">Caution</span>'`
- `'<span style="color:red">Defective</span>'`

Then, when the field is displayed in the Admin UI, the HTML is interpreted, so the text is colored.

If such a feature isn't available, perhaps there could be an `html` option for the `Text` and `Textarea` fields.

**Comment by celiao** [comment]
A similar technique could be used to insert clickable links into fields.

**Comment by mxstbr** [comment]
We're working on extensibility of the admin interface, it's one of the biggest features we want to get in before 1.0! I'll close this issue, it's definitely on our roadmap but it'll be a bit of time until we get everything set up to get this done!
