### ISSUE TITLE
Type.Html; wysiwyg: true is showing html tags on the web page

### ISSUE THREAD

**Issue by caitlin-mohnike** [keystonejs/keystone#1621]
I cannot figure out this issue and have googled around - hoping someone here can help me.

I made a couple of my fields type: Type.Html and wysiwyg: true. It appears to work fine in the admin UI, but when I view it on the webpage, I can see the html tags. Which is not great. Has anyone else had this issue? Does anyone know where I should look? I tried to use the markdown and had that show up on my page too.  Tried making fields from scratch - same thing. Tried removing any html tags around it in case they were affecting it - no dice. Help!

**Comment by ignlg** [comment]
In Jade, this
```
p= something
```
escapes html, so it'll be visible.

But this
```
p!= something
```
doesn't escape html and the value is injected directly. Mind the `!`.

**Comment by cantuket** [comment]
I've never used @ignlg 's method (p!=) above so thats nice to know, but if you are trying to include wysiwyg data you generally don't want to wrap it in a ``` <p> </p>``` tag as the example above would do. The wysiwyg data will already include the html markup you want so I would recommend...

```
.parentDiv
      !{variable}   
(executes HTML, no tags) 
```

,but if you are trying to include other variables as text (non-wysiwyg data) and want to concatenate it with other text or other variables within an HTML tag you would use...
```
.parentDiv
      p  #{variable1}  #{variable2}  and more text here.
```
Also, if you want to include a variable as/in an HTML attribute/property you would use the same hashtag markup...
```
img(src="/images/folder/#{variable}.jpg")
```
if your variable is the full img URL the you could use the shortcut mentioned above...
```
img(src=variable)
```

**Executes HTML, no tags**
```
!{variable}
p!= variable
```

**Escapes HTML, shows tags**
```
#{variable} 
p=variable 
```

**Comment by acontreras89** [comment]
@ignlg's solution isn't limited to `p` elements. Simply use `!=` in your templates wherever it suits you.
For example:
```jade
.wrapper
  != post.content.extended
```

See _Unescaped buffered code_ in [jade reference.](http://jade-lang.com/reference/code/)

**Comment by JedWatson** [comment]
Thanks for all the help everyone, @caitlin-mohnike hope this gives you what you needed. I'm going to close the issue now, because it's definitely resolved :)

**Comment by caitlin-mohnike** [comment]
Oh gosh, sorry, forgot to respond. 

The issue is that I was using EJS. In EJS to escape the html, I have to use <%-  %> instead of  <%= %>

Hopefully that helps someone else using EJS and keystonejs. Thanks for your responses everyone!
