### ISSUE TITLE
How do I prevent site.min.css from overriding styles of my plugin ?

### ISSUE THREAD

**Issue by ishandutta2007** [keystonejs/keystone#1622]
I have installed the plugin using Bower in public/js/bower_components folder.Now the directory structure looks like this:

public
##|----js
######|----- Bower Components
##########|-----JS Plugins(Bower Managed)
################|-----MyPlugin's 
##################|------.bower.json
##################|------dist
########################|----Myplugin.css
###|---styles
######|-----site-min.css

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
