### ISSUE TITLE
[Inheritance] Append fields to Headings

### ISSUE THREAD

**Issue by SlashmanX** [keystonejs/keystone#1623]
Right now if you create a model that inherits from another, all the 'extras' are placed at the bottom of the UI. It would be nice if this interacted with the 'headings' that can be present in the models and at least append it to the 'section'.

Example:

"Info" is a heading present in the child and parent model, and "Info > Type" is the only extra field in the child model.

<img width="607" alt="screen shot 2015-08-27 at 15 58 50" src="https://cloud.githubusercontent.com/assets/871743/9524025/8fde151a-4cd4-11e5-9dcc-6375e326ba15.png">

Note: I might take a look at this and see how hard it is to implement, just thought I'd log an issue to keep track and get input

**Comment by Mentioum** [comment]
Yes would be super useful. +1

**Comment by mxstbr** [comment]
We're working on extensibility of the admin interface, it's one of the biggest features we want to get in before 1.0!

I'll close this issue, it's definitely on our roadmap but it'll be a bit of time until we get everything set up to get this done!
