### ISSUE TITLE
Oneclick Backup

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#1624]
Regarding https://github.com/keystonejs/keystone/issues/1464
A single button that invokes `mongodump` and prompts the browser to store a database backup file locally would be very welcome.

**Comment by wmertens** [comment]
Agreed, but running mongodump as in e.g. https://github.com/myrne/mongo-utils is a bit crude. You don't need the session db, for example.

Perhaps it would be better to simply list out all models that are included in the backup, and serialize them on the fly? Then restoring is a matter of reading them in again, optionally overwriting or clearing.

**Comment by wmertens** [comment]
…and of course a more advanced option would be incremental backups, where you get only the objects that changed since x. Then with a quick script you could do offsite backups.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/oneclick-backup!
