### ISSUE TITLE
s3 image jade error

### ISSUE THREAD

**Issue by jforaker** [keystonejs/keystone#1625]
Using s3 images, seems jade is throwing an error. I've properly set 's3 config'

```
Sorry, an error occurred loading the page (500)

/Users/jakeforaker/dev/keystone/templates/views/blog.jade:21
19| if post.image.exists
20| #{post.image}
> 21| img(src=post._.image.fit(160,160)).img.pull-right
22| p!= post.content.brief
23| if post.content.extended
24| p.read-more: a(href='/blog/post/' + post.slug) Read more...

undefined is not a function
```

If I comment out line 21, line 20 above will print out:
`<{ url: '//keystonejakef.s3.amazonaws.com/3c757ddc6e0035df83cab497d3d70b24.jpg', filetype: 'image/jpeg', size: 1684603, path: '', originalname: 'IMG_2728.jpg', filename: '3c757ddc6e0035df83cab497d3d70b24.jpg' }>`

How to render the image correctly in the jade template?

**Comment by morenoh149** [comment]
try removing the styling or moving it inside `img(src=post._.image.fit(160,160) class=".img.pull-right")`

**Comment by morenoh149** [comment]
could you share your schema for your post model?

**Comment by SlashmanX** [comment]
Shouldn't `img(src=post._.image.fit(160,160)).img.pull-right` be:

`img(src=post.image._.fit(160,160)).img.pull-right`

?

**Comment by jforaker** [comment]
@SlashmanX: yes, that was an artifact of trying different things.. still the same result when i changed to back to what you suggested.

Post model:
```
var keystone = require('keystone');
var Types = keystone.Field.Types;

/**
 * Post Model
 * ==========
 */

var Post = new keystone.List('Post', {
	map: { name: 'title' },
	autokey: { path: 'slug', from: 'title', unique: true }
});

Post.add({
	title: { type: String, required: true },
	state: { type: Types.Select, options: 'draft, published, archived', default: 'draft', index: true },
	author: { type: Types.Relationship, ref: 'User', index: true },
	publishedDate: { type: Types.Date, index: true, dependsOn: { state: 'published' } },
	image: {
		type: Types.S3File
	},
	content: {
		brief: { type: Types.Html, wysiwyg: true, height: 150 },
		extended: { type: Types.Html, wysiwyg: true, height: 400 }
	},
	categories: { type: Types.Relationship, ref: 'PostCategory', many: true }
});

Post.schema.virtual('content.full').get(function() {
	return this.content.extended || this.content.brief;
});

Post.defaultColumns = 'title, state|20%, author|20%, publishedDate|20%';
Post.register();
```

**Comment by morenoh149** [comment]
@jforaker as I suspected. `.fit` is an underscore method available on the cloudinaryimage fieldtype http://keystonejs.com/docs/database/#fieldtypes-cloudinaryimage not on the S3file fieldtype.

In the future it would be nice to have these sorts of methods available on an `image` fieldtype using something like https://www.npmjs.com/package/resize Feel free to open up such an issue

**Comment by jforaker** [comment]
Thanks. Any way to resize an s3 image?  If not, could you point in me in the right direction? Appreciate the help.

**Comment by morenoh149** [comment]
for some context, the way `fit` can resize cloudinaryimages (I'm guessing) is by passing in the dimensions in the url (http://cloudinary.com/documentation/node_image_manipulation#display_images). That's one of the coolest features of cloudinary, is it can resize images on demand by simple requesting the resource with extra params.

How to achieve this in keystone is unclear. Many webapps hook into imagemagick to perform the image processing (resizing). Off the top of my head I would try using https://www.npmjs.com/package/resize in a mongoose pre-save hook (http://mongoosejs.com/docs/middleware.html). But this may be a blocking operation that renders your backend unable to response for a couple of seconds. Try asking further questions in the gitter.im chatroom.

**Comment by tomtom87** [comment]
> In the future it would be nice to have these sorts of methods available on an image fieldtype using  something like https://www.npmjs.com/package/resize Feel free to open up such an issue

Any chance this has been added by now?
