### ISSUE TITLE
Docker deployment mongoose connection error.

### ISSUE THREAD

**Issue by giusepperj** [keystonejs/keystone#1626]
I'm trying to deploy a Keystone.js Website throught Tutum.co and I keep getting this error whenever I deploy my container: 

```
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.710585245Z ------------------------------------------------
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.711064828Z Mongo Error:
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712262136Z 
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712273145Z [Error: failed to connect to [10.7.0.3:27017]]
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712797295Z /root/node_modules/keystone/lib/core/mount.js:587
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712819396Z 	throw new Error('KeystoneJS (' + keystone.get('name') + ') failed to start'
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712824563Z 	      ^
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712827846Z Error: KeystoneJS (docker-cont) failed to start
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712831256Z     at NativeConnection.<anonymous> (/root/node_modules/keystone/lib/core/mount.js:587:10)
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712834703Z     at NativeConnection.emit (events.js:107:17)
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712837963Z     at NativeConnection.Connection.error (/root/node_modules/keystone/node_modules/mongoose/lib/connection.js:389:8)
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712841275Z     at /root/node_modules/keystone/node_modules/mongoose/lib/connection.js:416:14
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712844418Z     at /root/node_modules/keystone/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:57:21
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712847558Z     at /root/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:286:18
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712850840Z     at /root/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:365:7
docker-cont-dd5afd3b-1 | 2015-08-29T10:05:25.712854197Z     at process._tickCallback (node.js:355:11)
```
I encountered this [article](http://baiduhix.blogspot.com/2015/01/the-way-keystonejs-handling-mongo.html) that explains the error but no fix was given.

I'd love to know if anyone has encountered this error before and if there's a possible fix for the upcoming 0.4.0 release.

Thanks.

**Comment by webteckie** [comment]
Is there really a mongo instance running at 10.7.0.3:27017?  And, if so, is that it's own container?  And, if so, is that container exposing port 27017?

**Comment by giusepperj** [comment]
@webteckie Yes, yes and yes... both the mongo and the keystone containers are linked otherwise the `10.7.0.3:27017` host:port would not show up since it comes from a linked docker environment variable at task start up time. My only guess is that it has something do with how tutum handles its port mappings (the project is still in BETA) however the article I referenced does make a point as to how Keystone handles that specific mongoose connection error. Thank you in advance.

**Comment by webteckie** [comment]
Have you successfully ran the same container configuration locally using docker tools?  The promise of docker is that if it runs in one it should run in all docker environments. If not, I would start by doing that since it is easier to debug.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
