### ISSUE TITLE
How do I add a new attribute to an existing object of Keystonejs list ?

### ISSUE THREAD

**Issue by ishandutta2007** [keystonejs/keystone#1627]
keystone.list(‘MyModel').model.findOne( { _id: searchId } , function (err, mymodel) {
      mymodel.oldAttribute = “Changed Old VAL";
      mymodel.newAttribute = “Entered New VAL";
      mymodel.save(function (err) {
          if(err) { throw(err); }
      });
 });

But when I check after the update I get only this,
{ _id: 55e17723b4856b85b1cf5f0a,  updatedAt: Sat Aug 29 2015 15:40:18 GMT+0530 (IST),key: '55e17723b4856b85b1cf5f0a',  __v: 0,  oldAttribute: 'Changed Old VAL',  createdAt: Sat Aug 29 2015 14:40:59 GMT+0530 (IST) }

**Comment by webteckie** [comment]
Have you defined newAttribute in the MyModel list?

**Comment by ishandutta2007** [comment]
Got it !!! Thanks
