### ISSUE TITLE
sign in when don't have password

### ISSUE THREAD

**Issue by foobar8675** [keystonejs/keystone#1628]
I'm using the following, https://gist.github.com/JedWatson/f88b60e9d6b33b6c47c4 , are there thoughts on how to sign in a user when you don't have the password?

for example, if one registers, and i send them a user verification email, then they click on a link to register which brings them to a webpage ... i'd like to sign them in, but i don't have the password at that point.  thoughts?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
