### ISSUE TITLE
Redirect after sign in for no admin users

### ISSUE THREAD

**Issue by ianaya89** [keystonejs/keystone#1631]
When a no admin user sign in in the application a keystone screen is rendered.
Hi, I am trying to handle the action after a sign in for no admin users, to redirect (or render) to another route or page.

I am trying using a middleware but I can't find how to trigger the middleware after the sign in success.

Any idea?

**Comment by ianaya89** [comment]
Here is the fix for what I want.
https://github.com/keystonejs/keystone/issues/1489

**Comment by vamshi9** [comment]
@ianaya89 I've gone through it but didn't solve the issue, function method is not working out.Would you please check this out!
