### ISSUE TITLE
Deploying on AWS Elastic BeanStalk

### ISSUE THREAD

**Issue by foobar8675** [keystonejs/keystone#1632]
Is anyone using AWS Elastic bean stalk to deploy? My deploys are taking 20 minutes+ so I was wondering if anyone had any suggestions.

**Comment by morenoh149** [comment]
ELB takes a long time to spin up databases. In my experience.

**Comment by foobar8675** [comment]
Is that what it is? i had thought the npm install was the culprit.

**Comment by medv** [comment]
It's why I decided to go for cloudformation instead of elastic beanstalk. Just took too long to deploy and I think it was npm install at fault. You want to create an image that has everything ready and spool that up in a matter of seconds rather than provisioning a new one every deploy. When image requirements change, you make a new image and use that instead.

**Comment by foobar8675** [comment]
thanks medv. i've switched from a t2 micro to a small and am seeing improvements but a few seconds sounds great and will look into cloudformation.

**Comment by cameronjroe** [comment]
I'd also recommend checking out [Docker](http://aws.amazon.com/docker/).

**Comment by morenoh149** [comment]
I've been following the https://github.com/remind101/empire project since I heard about it. It leverages cloudformation (or Amazon container service, I forget which) for deploys.

**Comment by medv** [comment]
@foobar8675 If it helps, my most recent delve into cloudformation sees me doing something like

Vagrant <- Packer -> Terraform -> AWS

You bake your image in Packer, which creates an AMI able to be used as an EC2 instance in Terraform config (which you write like you would a CloudFormation config) as well as prepares an image for you to use in Vagrant (so you can develop locally with minimal differences to production). Then you deploy your Terraform config into AWS. You might want to consider how Consul might fit into this. All these services are made by HashiCorp.

**Comment by foobar8675** [comment]
@medv thank you. i was hoping for something more turn key but appreciate your advice will definitely look into it.

**Comment by medv** [comment]
You can very well still use Docker with this setup. Quick search returns:

https://github.com/dublx/packer-terraform-docker-aws-test

To answer your question, I'm trying out different methods of deployment from project to project and this one is my current top pick. I have not tried docker beyond just messing around with it on my own machine for fun, but I will give it a proper try after I see how this goes.
