### ISSUE TITLE
Items Table row spacing is off, stylesheet needs review

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1635]
@jossmac, over to you for this one.

Since we removed the `line-height` styling from Elemental, our Items table doesn't look right, we need to add it back in to Keystone to line everything up properly again.

There are also some margin issues for links to relationships (specifically, many relationships) and the classes I've created for various column types could really use your review. I think being more specific with the field type wrappers & styles will clean it up nicely.

**Comment by jossmac** [comment]
Sorted. We now have explicit classes for handling various column links:
- `interior` looks like text until hover/focus
- `exterior` looks like a link
- `padded` expands hit area

These have been implemented for the following:
- text
- name
- email
- relationship

Let me know if I've missed anything
