### ISSUE TITLE
Deleting an item (A) that's stored in a Relationship of another item (B) will break the Relationship UI of (B)

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1637]
The endpoint that retrieves the item details for Relationship fields (the `react-select` control) correctly returns a 404 error, but this breaks the RelationshipField component - which should just drop the invalid item from its value.

To reproduce in the [test project](https://github.com/keystonejs/keystone-test-project):

- Create a PostCategory (A)
- Create a Post (B), link it to the PostCategory (A)
- Save the Post (B)
- Delete the PostCategory (A)
- View the Post (B)

... the **Categories** relationship field will just display _loading_, and the 404 will be logged to the console. There's no way to fix the value of the Relationship field.

**Comment by sarith** [comment]
I can confirm this bug also exists and behaves in exactly the same way in 0.3.x. Not sure if that helps but it's clearly nothing to do with React at least, yes?

**Comment by JedWatson** [comment]
Closed by #1658

**Comment by bradwbradw** [comment]
This bug still occurs in version 0.3.16

**Comment by morenoh149** [comment]
probably wasn't backported to the 0.3.x line @lojack ?
