### ISSUE TITLE
Write documentation how to set up keystone in production

### ISSUE THREAD

**Issue by markokocic** [keystonejs/keystone#1640]
I couldn't find a recommended / blessed documentation how to run `keystone` apps in production.

What is the recommended setup? Should it run standalone or behind an Apache/Nginx reverse proxy? How to configure it properly to run behind reverse proxy? Who should serve static content, how to set up routes, ...?

**Comment by morenoh149** [comment]
that should eventually be added to https://github.com/keystonejs/keystone/wiki/Deployment-Checklist or https://github.com/keystonejs/keystone/wiki

**Comment by foobar8675** [comment]
That's pretty interesting, i was running on a t2 micro https://aws.amazon.com/about-aws/whats-new/2014/07/01/introducing-t2-the-new-low-cost-general-purpose-instance-type-for-amazon-ec2/
which has only 1G ram and was having issues. so i switched to a t2.small and it's been better.

**Comment by morenoh149** [comment]
yeah it's great to compile all this info into the wiki so we don't all repeat effort
