### ISSUE TITLE
Problem with yo keystone - can't install node-sass

### ISSUE THREAD

**Issue by pietrofxq** [keystonejs/keystone#1643]
So i'm trying to run ```yo keystone``` to generate my project with the sass option, but the terminal get stuck on the ```node-sass``` instalation. The last lines are 

```bash
linux-x64-node-0.12 exists; testing
Binary is fine; exiting
```
reference: https://github.com/sass/node-sass/issues/497

**Comment by AxelHo** [comment]
same Problem here

**Comment by morenoh149** [comment]
I ran into something similar recently but I assumed it was something I messed up. I simply reinstalled the node-sass plugin `npm install node-sass` you could also try `rm -rf node_modules`. If more people run into the same issue then we may need to update the node-sass version or something.

**Comment by morenoh149** [comment]
moving
