### ISSUE TITLE
Cannot empty date once set

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1644]
Once you set a date in the form, you can not empty the field, even if the field's not required.
To be clear, this is a DateField, not a DateTimeField.
This is on the v0.3 branch, not sure whether v0.4 has the same problem.

**Comment by mxstbr** [comment]
Pretty sure this is fixed on 0.4, and I'm not sure it's worth the effort to fix this on 0.3 so I'll close it for now!
