### ISSUE TITLE
Add nav-links for custom pages

### ISSUE THREAD

**Issue by ajayvishwanath** [keystonejs/keystone#1645]
I have gotten around to understand some of the basic ways to configure keystone. For example, creating models, adding routes, middleware and changing which columns appear in Admin UI. They all work pretty smooth. :)

However, what has been bugging me for the past few days is that I am able to create my custom routes and templates but unable to provide any "links" to those routes, either in the homepage or the header navigation. The header navigation allows you to add only keystone lists.

How do I add a non-keystone list in my navigation panel (say an About Us page) and at the same time have the Admin UI enabled for the keystone lists?

**Comment by creynders** [comment]
Hi @ajayvishwanath you can add any links you want to the navigation by adding an object instead of a string:

```js
keystone.set( "nav", {
  "content": [
    "posts",
    "post-categories",
    "enquiries",
    {
      label: "reports",
      key: "reports",
      path: "/api/reports"
    },
  ]
});

**Comment by ajayvishwanath** [comment]
Hey, thanks for the reply!

I tried and it works pretty well. Thanks.

**Comment by r3wt** [comment]
this no longer works? whats the new way to work around this issue?

**Comment by ifiok** [comment]
@r3wt Did you find a workaround for this?

**Comment by alexandrecardinal** [comment]
@r3wt @ifiok I just found a workaround
`keystone.set('nav', {
	venues: 'venues',
	customers: 'customers',
	users: 'users',
	'reservations': [
		{
			label: 'Reservations',
			key: 'reservations',
			path: '/reservations'
		}
	]
});`

In this case, this will give me a menu item called 'Reservations' leading me to '/reservations'. You HAVE to wrap your menu item with an array... this is probably a bug that should be fixed at some point.

**Comment by alexandrecardinal** [comment]
@r3wt I really doubt you can do that without modifying the keystonejs module. I did some research and it seems doable in v4.0.0 but not the in v0.3.x
