### ISSUE TITLE
Mongodb 3.x auth fails, 2.6 works

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#1646]
So, when I change my auth scheme and db to Mongo 3.x, keystone can't mount/authenticate at startup. But, when I roll mongo back to 2.6 all is well. Any way to get keystone to work with mongo 3.x.?

**Comment by alobodig** [comment]
@chrisschaub, is it giving an error message?

**Comment by creynders** [comment]
@chrisschaub is this still an issue?

**Comment by JedWatson** [comment]
We have been running mongodb 3.x for a while with no issues, I'm going to close unless more information on how to reproduce it comes up.
