### ISSUE TITLE
`originalInput` not correctly passed to `beforeChange()` and `afterChange()` hooks

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#1649]
There's a bug in the `List` class where the (internal) `_beforeChange()` and `_afterChange()` functions have these signatures:

```js
async _beforeChange(resolvedData, existingItem, context, originalInput) { ... }
async _afterChange(updatedItem, existingItem, context, originalInput) { ... }
```

But when they're called, an `operation` argument is also provided. Eg..

```js
this._beforeChange(resolvedData, existingItem, context, operation, originalInput);
this._afterChange(newItem, existingItem, context, operation, originalInput);
```

As a result, when one of these hooks is executed, the `originalInput` comes though as a string (ie. "update" or "create") rather than an object [as documented](https://github.com/keystonejs/keystone-5/blob/master/docs/api/hooks.md#hooks-function-properties).

**Comment by Vultraz** [comment]
Looks like this one can be closed @jesstelford

**Comment by molomby** [comment]
Was merged
