### ISSUE TITLE
[0.4] Field values don't wrap properly

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1649]
@jossmac `noedit` field values aren't formatted properly when they span multiple lines:

![image](https://cloud.githubusercontent.com/assets/872310/9704649/e37d0234-54f0-11e5-9e8f-5557e1575115.png)

**Comment by jossmac** [comment]
This is now [handled by elemental](https://github.com/elementalui/elemental/commit/7f68726dd6213c040fc5b4a5cb415b4064d80eb0)
