### ISSUE TITLE
Question: different base layout for admin and site

### ISSUE THREAD

**Issue by tanis2000** [keystonejs/keystone#1651]
Is there any way to have two different layouts for the actual site and the admin UI?

**Comment by foobar8675** [comment]
in your keystone.init, you can also set the default template to whatever you want. here's a snippet of what mine looks like using handlebars but really a default template that uses react.

	'custom engine': handlebars.create({
		defaultLayout: 'react',
		helpers: new require('./templates/views/helpers')(),
		extname: '.hbs'
	}).engine,

**Comment by tanis2000** [comment]
@foobar8675 thanks for the suggestion, but that's fine if you want to use the same layout both for the admin and the site. In the end I just went for passing the layout to the rendering engine for each single page like this:

    view.render('index', { layout: 'site' });

I have to do it for every page but it does work :)

**Comment by morenoh149** [comment]
added to knowledge base https://github.com/keystonejs/keystone/wiki/Knowledge-Base

**Comment by supertrens** [comment]
add this in your `keystone.js` file
