### ISSUE TITLE
Admin UI - allow fields to be edited in list view

### ISSUE THREAD

**Issue by celiao** [keystonejs/keystone#1652]
It would be handy to allow fields to be edited in the list view, as in [Django](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_editable).  It could be implemented with pipes in defaultColumns, e.g., `name|editable`.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/field-editing-in-list-view!
