### ISSUE TITLE
Knex adapter doesn't implement the `search` condition

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#1654]
There's a (somewhat half-baked) implementation of the `search` condition [in the Mongoose adapter](https://github.com/keystonejs/keystone-5/blob/master/packages/adapter-mongoose/lib/adapter-mongoose.js#L29
). 

This filter is used by the AdminUI when selecting a related item for a Relationship field in the create and edit forms. The GraphQL queries look like this:

```graphql
query RelationshipSelect($search: String!, $skip: Int!) {
   allUsers(first: 10, search: $search, skip: $skip) { id _label_ __typename }
   _allUsersMeta(search: $search) { count __typename }
}
# Eg. variables: {search: "molo", skip: 0}
```

**The Knex adapter doesn't implement this filter**. This partially breaks the Relationship field UI.

It actually looks like the UI itself re-applies the filter to the results it receives from the backend it doesn't break quite as hard as it could/should. The downside of this is that, this filtering is applied to the `_label_` field where as, on the backend, the filtering is applied to the `name` field. Usually this is the same value but they can diverge. This will become more of a problem when we [fix the fields the `search` filter is applied to](https://github.com/keystonejs/keystone-5/issues/640).

The short term fix is probably just to mirror the functionality the Mongoose adapter implements across to the Knex adapter. In the long term, list need a much more configurable filtering solution (as described in #319). We should also remove that client-side filtering.

**Comment by jesstelford** [comment]
I think we should remove searching across the board and instead open the Relationship filter to be a proper nested set of filters instead of a react-select input field thing.

**Comment by molomby** [comment]
> I think we should remove searching across the board and instead open the Relationship filter to be a proper nested set of filters instead of a react-select input field thing.

Why? Surely just typing someones name and getting a filtered set of result to pick from provides a faster/easier/more intuitive user experience in some cases. Not to mention that, free form text search _was_ a list-level filter in KS4 -- something we've always planned to restore.

There's no reason this can't be made performant on both Mongo and Relational DBs, we just need to support some full-text indexing at a list level.

I agree that there are other interfaces that should be available to manage relationship field (including a sort of "full, embedded list view with filters" as you suggest) but which interface is appropriate depends on the properties of the relationship. [The way I think about it](https://gist.github.com/molomby/0b3fa2a22747ca053199e75945334da3#admin-ui), the interface used should be a function of...

1. How many items you need to select (ie. one, a few items or _heaps_ of items)
2. How many items you need to select _from_ (ie. a small number or a large number)

This produces a sort of matrix against which different UIs can be mapped against. If you need to select a single item from a very large set of items something like the filterable select field we currently have is a good fit.
