### ISSUE TITLE
Missing markdown icons

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#1654]
Markdown field button icons aren't showing for contact item:

http://keystone4-preview.herokuapp.com/keystone/contacts

![image](https://cloud.githubusercontent.com/assets/2730833/9727880/ff2ab2ea-5646-11e5-9a6c-f5751f8b5579.png)

**Comment by erg0dic** [comment]
Works for me locally

**Comment by jossmac** [comment]
Cannot reproduce. It appears to have been resolved since I opened this issue
