### ISSUE TITLE
Date field bug(s)

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#1656]
Date is set by default, which is displayed in the list view and is misleading. On inspection this may be a requirement of `react-day-picker` :cry: 

Need to finish the date fields...

**Comment by geloescht** [comment]
I don't really understand the description, but is this maybe fixed? If not, could you please elaborate?

**Comment by Noviny** [comment]
Going to close this as incidentally solved by #4112. If this isn't the case, let me know.
