### ISSUE TITLE
Email helper fails when utilizing Nunjucks templates + Fix

### ISSUE THREAD

**Issue by chriseaton** [keystonejs/keystone#1663]
If you switch the email template engine to Nunjucks, the e-mail will fail to render. The reason is that the compile() function returns an object that is not a function so the following line fails:

lib/email.js Line 215
```
var html = template(locals);
```
I was able to overcome the problem for now by doing the following:
```javascript
var html = null;
var template = templateCache[this.templateName];
if (typeof template === 'function') {
    html = template(locals);
} else if (typeof template.render === 'function') {
    html = template.render(locals);
}
```

Performance-wise you could probably pre-cache the template rendering option on initialization, or set the rendering option as a "default" property of the Email object, but this is the essence of it

**Comment by chriseaton** [comment]
So above is actually only a partial fix. It turns out the initial compile function call (lib/email.js Line 319)  causes issues as well due to the different argument arrangement. Nunjucks doesn't like the jade-style 2nd argument... I don't have a resolution at the moment other than break the e-mail compatibility w/ jade.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by mxstbr** [comment]
The entire `Keystone.Email` class was rewritten as an external module, `keystone-email`. This should be fixed over there, if this issue still exists for you with the new code feel free to comment again!
