### ISSUE TITLE
Default spinner for async loading

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystone#1667]
Would'n be nice to have a .gif already included somewhere with keystone, and being able to use it easily on jade templates ?

**Comment by jacargentina** [comment]
I've discovered http://github.hubspot.com/pace/docs/welcome/
Already using it as a bower dependency and its NICE!

**Comment by creynders** [comment]
:+1: for using pace. I think it's a good idea to integrate it into keystone.

**Comment by morenoh149** [comment]
I fiddled with pace. It's just pace.min.css and a small amount of theme specific css. Very simple.

**Comment by mxstbr** [comment]
Done with 0.4!
