### ISSUE TITLE
MongoError: Btree::insert: key too large to index

### ISSUE THREAD

**Issue by mikestopcontinues** [keystonejs/keystone#1668]
Hey, I'm getting the following error when I try to save too much to an HTML field...

```MongoError: Btree::insert: key too large to index, failing app-name.posts.$body_1 10315```

I'm running Keystone 0.3.14 and mongoose 4.1.6.

This happens no matter what I disable here:

```js
const Post = new keystone.List('Post', {
  defaultSort: '-updatedAt',
  defaultColumns: 'name, project|15%, published|20%',
  track: {
    createdAt: 'created',
    createdBy: false,
    updatedAt: 'updated',
    updatedBy: false
  },
  autokey: {
    from: 'name',
    path: 'slug',
    unique: true,
    fixed: true
  }
});

Post.add({
  name: {
    type: Types.Text,
    required: true,
    initial: true
  },
  body: {
    type: Types.Html,
    required: true,
    initial: true,
    wysiwyg: true,
    height: 400
  },
  slug: {
    type: Types.Key,
    initial: true,
    index: true,
    seperator: '-'
  },
  published: {
    type: Types.Datetime,
    initial: true,
    default: Date.now
  },
  project: {
    type: Types.Relationship,
    ref: 'Project',
    initial: true
  }
});

Post.register();
```

Even though it doesn't happen here:

```js
const Medium = new keystone.List('Medium', {
  defaultSort: 'name',
  defaultColumns: 'name, slug|15%',
  track: false,
  autokey: {
    from: 'name',
    path: 'slug',
    unique: true,
    fixed: true
  }
});

Medium.add({
  name: {
    type: Types.Text,
    required: true,
    initial: true
  },
  body: {
    type: Types.Html,
    required: true,
    initial: true,
    wysiwyg: true
  },
  slug: {
    type: Types.Key,
    initial: true,
    index: true,
    seperator: '-'
  }
});

Medium.register();
```

Any ideas?

**Comment by medv** [comment]
You can start mongod with "failIndexKeyTooLong=false" argument. 

However you can also try dropping the problem table and see if that fixes it, i think it will from what I remember.

**Comment by morenoh149** [comment]
more info http://docs.mongodb.org/manual/reference/limits/#Index-Key-Limit should keystone add anything to circumvent or prevent large key sizes?

**Comment by mikestopcontinues** [comment]
@medv I'll give those a try tonight.

@morenoh149 It's the Types.Html field that's giving me the problem ("body" key). What I'm trying to save  is only a few thousand characters long, and it works in the Html field in my other model. 

I'll get back with my results. Thanks guys!

**Comment by mikestopcontinues** [comment]
Dropping the table worked. Thinking about it, I might've had index: true at some point, but in debugging, I'd explicitly set index: false, and it hadn't destroyed the index. This is a mongoose bug if anything, so extra thanks for the help!

**Comment by medv** [comment]
Yeah, I think this does happen if you are working on your model and changing stuff over time. Pretty sure you don't have to drop the whole table, just the indexes part. But I always drop the whole thing since I don't have anything to lose.
