### ISSUE TITLE
Create a React App

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1669]
Create a React App. Basically an express middleware that runs `create-react-app` in dev and builds in prod.

Question: React uses the `webpack-dev-server` should we proxy to this or re-create the process with an express middleware?

**Comment by jesstelford** [comment]
🤔 We can use `execa` to start a child process which basically just runs `npm start` in the directory, but you're right we'd have to either proxy requests, or start it on a different port and make that clear to the user (but then the "prod" version would be on the same port which has implications for cookies and CORS, etc).

**Comment by jesstelford** [comment]
Something like https://github.com/chimurai/http-proxy-middleware might work well 👍

**Comment by MadeByMike** [comment]
Yes! Maybe a proxy middleware is the right move and it can serve any front-end application framework that comes with it's own dev server. The only challenge with that is finding a sensible way to kick-off the applications within the middleware so that it feels like a single `yarn dev` command.

**Comment by JedWatson** [comment]
This would be really nice to have, but not a high priority if it takes much time. Setting as low for now. Would be a great contribution 👍

**Comment by GasimGasimzada** [comment]
Does it have to be "Create React App"? What about managing a custom webpack configuration?
