### ISSUE TITLE
How to provide a link to a document from a to-many field

### ISSUE THREAD

**Issue by foobar8675** [keystonejs/keystone#1669]
I was hoping for a suggestion. I have a to many relationship
````
Group.add({
	name: { type: Types.Text, required: true, index: true },
	children: {type: Types.Relationship, ref: 'Child', many: true, index: true},
	parents: {type: Types.Relationship, ref: 'User', many: true, index: true}
});
````
which shows in the admin tool like this.

![screen shot 2015-09-10 at 11 30 43 am](https://cloud.githubusercontent.com/assets/1685700/9797343/6f78c58c-57af-11e5-9f8e-da85b5f7c33f.png)

but I would like to give people the ability to click on one of the parents or children and go straight to a page with the respective document, the child or parent in this case. I know if I change the relationship to be not many, that option is provided but was hoping for a suggestion for this case.

**Comment by webteckie** [comment]
@foobar8675 I think this is a duplicate of #564

**Comment by foobar8675** [comment]
yes it is.
