### ISSUE TITLE
Cant start keystone project

### ISSUE THREAD

**Issue by shubham14** [keystonejs/keystone#1671]
I installed keystone according to the steps given on the site,but I am getting this error repeatedly,Please help 

Mongo Error:

[Error: failed to connect to [localhost:27017]]
/Users/ankitadash/Desktop/docs/my-test-project/pitchplease/node_modules/keystone/lib/core/mount.js:587
			throw new Error('KeystoneJS (' + keystone.get('name') + ') failed to start'
			      ^
Error: KeystoneJS (PitchPlease) failed to start
    at NativeConnection.<anonymous> (/Users/ankitadash/Desktop/docs/my-test-project/pitchplease/node_modules/keystone/lib/core/mount.js:587:10)
    at NativeConnection.emit (events.js:107:17)
    at NativeConnection.Connection.error (/Users/ankitadash/Desktop/docs/my-test-project/pitchplease/node_modules/keystone/node_modules/mongoose/lib/connection.js:389:8)
    at /Users/ankitadash/Desktop/docs/my-test-project/pitchplease/node_modules/keystone/node_modules/mongoose/lib/connection.js:416:14
    at /Users/ankitadash/Desktop/docs/my-test-project/pitchplease/node_modules/keystone/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:57:21
    at /Users/ankitadash/Desktop/docs/my-test-project/pitchplease/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:286:18
    at /Users/ankitadash/Desktop/docs/my-test-project/pitchplease/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:365:7
    at process._tickCallback (node.js:355:11)

**Comment by morenoh149** [comment]
that routinely happens when you haven't in fact started mongodb on your computer.

**Comment by cameronjroe** [comment]
Yes, as @morenoh149 said. You need to have mongo installed and start the daemon before starting keystone: `$: mongod`

**Comment by shubham14** [comment]
@cameronjroe i have already included mongod and still getting this error,please help

**Comment by cameronjroe** [comment]
@shubham14 Have you set all your database options correctly within Keystone's config? http://keystonejs.com/docs/configuration/#options-database

**Comment by creynders** [comment]
Closing this, due to inactivity + not really an issue. Feel free to contact us on [gitter](https://gitter.im/keystonejs/keystone) if you have any questions, or reopen this, if it _is_ an issue
