### ISSUE TITLE
[0.4] Issue with the 'down arrow' icon

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1672]
@jossmac I'm seeing a split down the middle of the dropdown icon in Safari, can you take a look?

<img width="702" alt="screen shot 2015-09-13 at 8 33 59 pm" src="https://cloud.githubusercontent.com/assets/872310/9836290/d6a53232-5a56-11e5-9f19-0305648e2147.png">

**Comment by jonathanp** [comment]
Just linking this up with a reference to [issue #92 in the elemental ui repo](https://github.com/elementalui/elemental/issues/92). :)

**Comment by jonathanp** [comment]
Fixed in https://github.com/elementalui/elemental/commit/6e4d6227206fbdfcfbae4554ec9656919d5ff364
