### ISSUE TITLE
Improve CI speed

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1672]
The CI is a little slow as we get more contributions this problem will get worse. There is already a backlog of jobs on busy days which means some of us are spending evening merging small PRs.

I don't want to be doing this :) 

The goal here is to spend a couple of hours looking to see if we can reduce the time it takes to run CI.

**Comment by mitchellhamilton** [comment]
While we should definitely improve CI time, to lessen the problem, maybe we could use something like https://github.com/chdsbd/kodiak?

**Comment by MadeByMike** [comment]
@mitchellhamilton we should use whatever you tell us to use! I trust you fully on this 🤣

**Comment by mitchellhamilton** [comment]
(I haven't actually used the thing I linked, I've just heard about it but we might as well try it)

**Comment by timleslie** [comment]
CI is currently adequate. Closing this until such time as we have a more specific speed requirement.
