### ISSUE TITLE
Refactor creation of aux lists in Content blocks

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1674]
Pull request #1673 introduced an access control function repeated in all field implementations with AUX tables see: https://github.com/keystonejs/keystone-5/pull/1673/files#diff-17ecbca59700f2ff86be5edc3ee5f317R60

```
access: Object.entries(listConfig.listAccess).reduce(
  (acc, [schemaName, access]) => ({
    ...acc,
    [schemaName]: Object.entries(access).reduce(
      (acc, [op, rule]) => ({ ...acc, [op]: !!rule }), // Reduce the entries to truthy values
      {}
    )
  }),
  {}
);
```

This should be added to a utility function or one level higher with the way we create these Aux lists for blocks.

@timleslie is especially keen to make this improvement.

**Comment by timleslie** [comment]
We should *definitely* factor out the Aux list creation, not just the access control portion, as there is a bunch of other duplicated stuff in there already.
