### ISSUE TITLE
req.flash requires sessions

### ISSUE THREAD

**Issue by shailendra735** [keystonejs/keystone#1674]
We just deployed our app to production and have suddenly started facing this error: 
```
Error: req.flash() requires sessions 
at Error (native) 
at IncomingMessage._flash [as flash] (/app/node_modules/keystone/node_modules/connect-flash/lib/flash.js:60:41) 
at exports.flashMessages (/app/routes/middleware.js:88:13) 
at /app/node_modules/keystone/lib/view.js:354:4 
at /app/node_modules/keystone/node_modules/async/lib/async.js:689:13 
at /app/node_modules/keystone/node_modules/async/lib/async.js:239:13
at _arrayEach (/app/node_modules/keystone/node_modules/async/lib/async.js:91:13) 
at _each (/app/node_modules/keystone/node_modules/async/lib/async.js:82:13) 
at async.forEachOf.async.eachOf (/app/node_modules/keystone/node_modules/async/lib/async.js:238:9) 
at _parallel (/app/node_modules/keystone/node_modules/async/lib/async.js:688:9) 
at Object.async.parallel (/app/node_modules/keystone/node_modules/async/lib/async.js:702:9) 
at /app/node_modules/keystone/lib/view.js:364:10 
at /app/node_modules/keystone/node_modules/async/lib/async.js:187:20 
at iterate (/app/node_modules/keystone/node_modules/async/lib/async.js:265:13) 
at process._tickCallback (node.js:355:11) 
```

```
86 exports.flashMessages = function(req, res, next) {
87	var flashMessages = {
88		info: req.flash('info'),
89		success: req.flash('success'),
90		warning: req.flash('warning'),
91		error: req.flash('error')
92	};
93	res.locals.messages = _.any(flashMessages, function(msgs) {
94		return msgs.length;
95	}) ? flashMessages : false;
96	next();
97 };
```
We're using `connect-mongostore` as our sessions store, and we've also set up the `session store options`.
This error,however, is not consistent. It may or may not come. It suddenly pops up while browsing and crashes the app. We never faced this issue while in sandbox. 

Any ideas to debug it?

**Comment by creynders** [comment]
I've been using connect-mongostore as well and have not come across this. 

The error is thrown from [this line](https://github.com/jaredhanson/connect-flash/blob/master/lib/flash.js#L60) where it checks on `this.session` and AFAICT `this` refers to the `req` object. So, somehow the `session` prop of the `req` object becomes `undefined` in your case. 

By 'sandbox' do you mean an identical box as your production one? Or your local development machine?

**Comment by shailendra735** [comment]
By 'Sandbox' i mean a machine identical to our production one. 
I haven't been able to reproduce this as well. It just shows up randomly.

**Comment by creynders** [comment]
Do you have production specific code running? Something like

```js
if(NODE_ENV==='production')
```

**Comment by creynders** [comment]
Maybe we should continue this in the [gitter channel](https://gitter.im/keystonejs/keystone), since this isn't a keystone issue, I think. You can refer to this issue there to provide some context.

So, I'm closing this for now. If it however _does_ turn out to be keystone's fault, please feel free to reopen.
