### ISSUE TITLE
Configuration in admin UI

### ISSUE THREAD

**Issue by acontreras89** [keystonejs/keystone#1677]
I had the need to add a section to the admin UI in which users could upload static resources to later use in the website (e.g. scripts, styles, fonts...) or switch config options.
I worked around it by creating a collection (with `nocreate` and `nodelete` flags), consisting of `LocalFiles` and `Boolean` fields.
It would be nice if we could achieve something like this without the need for collections (and with an improved navigation inside the admin).

**Comment by jacargentina** [comment]
I also have a use case: i need to provide admin users the ability to run certain actions, which can be considered "administrative tasks". Obviously i could hook my own "secondary admin ui" routes, but i think a better centralized way would be if keystone admin ui provides some hooks, as anybody can "extend" its capabilities to do those extra custom tasks.

My use case is: i'm implementing a website index with https://github.com/fergiemcdowall/search-index module, and i need to show admin users the index status, and also a "Index now" button to launch the crawl process when desired, to force a re-index.

@JedWatson Any advice would be nice!

**Comment by mxstbr** [comment]
Admin extensibility is something we're very much working towards, but we're not quite there yet. We're currently cleaning our issue tracker, so I'll close this issue, but we're aware and working towards this!
