### ISSUE TITLE
Handlebars flash messages helper doesn't render text

### ISSUE THREAD

**Issue by joeyfromspace** [keystonejs/keystone#1679]
It appears the the built-in Handlebars helper for handling flash messages expects an array of objects with three optional properties (title, detail, list), when in fact the input is an array of strings.

Therefore the text is never rendered since the message is a string, and not an object with the properties the helper is looking for. 

Not sure if it was planned, or implemented at some point, for flash messages to have titles and details? I'm guessing since Handlebars isn't the default template engine that this was overlooked and never corrected. I am happy to submit a pull request with a corrected helper.

**Comment by creynders** [comment]
Correct me if I'm wrong but I think this should be an issue in the `generator-keystone` repo instead, no? If so, would you mind opening one there? And PR's are always **most** welcome. :grin:

**Comment by joeyfromspace** [comment]
My bad! I'll take a look at generator-keystone.
