### ISSUE TITLE
[Information request] - Add error processing middleware

### ISSUE THREAD

**Issue by murdockcrc** [keystonejs/keystone#1681]
At this point, I am not sure if keystone supports adding error processing middleware.

My site uses csrf tokens. I recently integrated keystonejs into our application. In the past, we used the following express middleware to catch errors and, in case of a csrf bad token error, return a 'EBADCSRFTOKEN' reply to our clients (this response is needed by iPhone app to differentiate a normal http500 from a csrf bad token http 500 error):

```
//csrf custom error handler
app.use(function (err, req, res, next) {
  if (err.code !== 'EBADCSRFTOKEN') return next(err);
  res.status(500);
  res.send('EBADCSRFTOKEN');
});
```

This middleware does not work on keystone anymore, so I added the following function to `middleware.js`:
```
	//csrf custom error handler
exports.csrfError = function csrfError(err, req, res, next) {
  if (err.code !== 'EBADCSRFTOKEN') return next(err);
  res.status(500);
  res.send('EBADCSRFTOKEN');
};
```

And loaded into into keystone by adding the following line to the `routes/index.js` file:
```
keystone.pre('routes', middleware.csrfError);
```

However, the parameters do not contain the correct error object.
So it looks like Keystone does not support adding middleware to handle errors, that's why I'm submitting this issue, but please point out if this is not correct, as I am new to the software.

**Comment by creynders** [comment]
Ah yes, quite right. ATM `pre:routes` middleware isn't registered as `express` middleware but called manually by the `grappling-hook` module. It was easier and cleaner to implement it like this, but I totally forgot the error handling middleware has an extra parameter. I'll have a look into this, to see what would be the best approach to fixing this.

**Comment by creynders** [comment]
Just had a look. The reason why I implemented it like it is, is because a `pre:routes` middleware should never handle errors.
Quote from [express docs](http://expressjs.com/guide/error-handling.html):

>You define error-handling middleware last, after other app.use() and routes calls

So  your first solution _should_ work if you add it last.
I just tested it out by adding this:

```js
	app.use( function( err,
					   req,
					   res,
					   next ){
		res.status(500).send('ERROR MIDDLEWARE');
	} );
```

last to my `routes/index.js file` and it works as expected.

**Comment by murdockcrc** [comment]
Correct, I was not sure where to place this middleware under the keystone structure, but I just put it under the Setup Route Bindings and works as expected. Might be worthwhile to consider adding this to the keystone documentation, so people can immediately know where to place middleware error handlers.

Thanks.

**Comment by creynders** [comment]
Good point! I'll open an issue in the docs repo.
