### ISSUE TITLE
Use mockgoose to have an in-memory db

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#1683]
While developing, needing mongodb is a bit annoying.

It would be nice if keystone could be optionally set up with https://github.com/mccormicka/Mockgoose and even nicer if the state could be stored in a flat file.

**Comment by JedWatson** [comment]
That looks really neat, especially for testing. Have you tried it to see if it works?

**Comment by creynders** [comment]
@wmertens AFAICT it should work out-of-the-box, i.e. no changes to keystone should be necessary to make this happen. There's two approaches here:

1. Wrap the shipped mongoose package with mockgoose:

```js 
//file: keystone.js
//right after keystone.init()
require('mockgoose')(keystone.mongoose);
```

2. provide your own wrapped mongoose version to keystone:

```js
//file: keystone.js
var mockgoose = require('mockgoose')(require('mongoose'));
keystone.init({
    mongoose: mockgoose
});
```

**Comment by LorbusChris** [comment]
This does the trick for me, Idk if its any different from the solutions above:
```
//file: keystone.js
//right before keystone.init()
var mongoose = require('mongoose');
var mockgoose = require('mockgoose')
mockgoose(mongoose);
```
Would be awesome to somehow automatically use mockgoose in dev mode, and Mongo otherwise. But until then its really not a huge effort to set up manually :)

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/use-mockgoose-to-have-an-in-memory-db!

**Comment by LorbusChris** [comment]
@creynders @wmertens Do you still use this? Does it still work for you? I can't seem to get it working like before...I'd highly appreciate if anybody'd try it out again and share the result!

**Comment by wmertens** [comment]
No not using it sorry…
