### ISSUE TITLE
Images not loading from custom field type in Admin UI

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1684]
# Bug report

## Describe the bug

The Admin UI is returning the wrong mime-type for svg which breaks the star custom field type.

A clear and concise description of the bug.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Launch the test project in `test-projects/basic`
1. Create new content 
1. Compare with screenshots

## Expected behaviour

The image should render.
The content can be loaded but the network panel shows a `type` of document.
I think that is incorrect for SVG?

## Screenshots

![image](https://user-images.githubusercontent.com/1320567/65289850-cb5a2680-db8f-11e9-88da-5dd69ccc8cef.png)

![image](https://user-images.githubusercontent.com/1320567/65289860-d614bb80-db8f-11e9-9c07-9501cd80ebd7.png)

**Comment by jesstelford** [comment]
🤔 That URL is on the root `/admin` path which implies it's part of the Admin UI bundle. Which then implies it's something to do with webpack not serving the file's mimetype correctly.

@MadeByMike do you see the same behaviour when doing `yarn build && yarn start` (ie; a "Production" build)?

**Comment by MadeByMike** [comment]
Ahhh! Nice pick-up @jesstelford it works with a build and start. It's getting the correct mime-type. What I'm not sure about is why it was able to load the SVG source in the first place.

Is there a bug here or should we close this one?

**Comment by MadeByMike** [comment]
@jesstelford I'm going to close this I think. Could you re-open if you think there is an issue here.

**Comment by jesstelford** [comment]
It looks like there's still a bug in dev mode where it's not setting the right mime type.

**Comment by Vultraz** [comment]
Is this related to #1823 (or vice-versa)?
