### ISSUE TITLE
Cannot set Admin role to users

### ISSUE THREAD

**Issue by goldo** [keystonejs/keystone#1684]
Hello, Im on keystone@0.4.0-alpha and I think one of the recent commits introduced a bug in Admin panel: I cannot Add 'admin role' to anyone.
I can remove it (checkbox empty > save) but I can't check it & save it in DB, there is no error but it looks like the checkbox isnt verified or anything.

Hope it helps. 
Thanks

**Comment by JedWatson** [comment]
Thanks for the bug report @goldo. This turned out to be an issue with our new Checkbox control which I've just fixed.
