### ISSUE TITLE
Question: Add options to a select dynamically

### ISSUE THREAD

**Issue by acontreras89** [keystonejs/keystone#1685]
Just a question. I need to expand models dynamically, (sometimes adding new fields and others expanding already existing ones). 
I can't find the proper way to add options to a Select field that has already been added to a list. Is this supported in any way?

**Comment by acontreras89** [comment]
For now, I'm using 
```
keystone.list('MyList').fields.mySelectField.ops.push({value: value, label: label});
```
But I'm not certain this won't break on some cases. 

If my approach is OK, feel free to close this issue :)

**Comment by creynders** [comment]
Afaik that's not possible. When the list is registered the field config is used to setup virtuals and other stuff.

**Comment by acontreras89** [comment]
Is it possible to override a path? I believe I can get the initial options for the field. If it was possible to override it, I could simply extend those options and re-create it.

Or any other idea which could help me work around this?

**Comment by snowkeeper** [comment]
Have a look at https://github.com/keystonejs/keystone/blob/master/fields/types/select/SelectType.js#L65.  This is where the enum values are created and stored in the schema.  You can access them through `keystone.list('MyList').schema.path('mySelectField').enumValues`.  

You will most likely run into issues when trying to mutate this object.  For more help and to find some workarounds, I would look to mongoose specific information. Keystone is simply performing the work for you to prepare your Mongoose lists.

**Comment by snowkeeper** [comment]
Also, you can check out the schema option `strict: false` documentation at http://mongoosejs.com/docs/guide.html if you have not done so.

**Comment by acontreras89** [comment]
Thanks @snowkeeper! This looks really helpful :smiley:

**Comment by creynders** [comment]
@acontreras89 closing this for now, since I think it's been answered+ it's not really an issue. Feel free to contact us on the [gitter channel](https://gitter.im/keystonejs/keystone) in case you have further questions, or re-open this, if you feel it _is_ an issue.
