### ISSUE TITLE
Feature Request: Drag and drop adding of images to posts

### ISSUE THREAD

**Issue by designatednerd** [keystonejs/keystone#1689]
It'd be really helpful to be able to drag an drop an image into the post editor when creating a post instead of only being able to add it through the image insert button. 

Current behavior when you attempt to do this is that the image just loads up in the browser (using Chrome for Mac 45.0.2454.99 (64-bit)), which nukes any unsaved draft you were working on.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/drag-and-drop-adding-of-images-to-posts!
