### ISSUE TITLE
Promise A+/Spec Implementation

### ISSUE THREAD

**Issue by grindfuk** [keystonejs/keystone#1690]
Hi, awesome package.  

Don't know if this is a stupid question but it didn't come up while searching through the issues. 
I was looking through the promise implementation and it uses JQuery promises which isn't Promise/A+ spec compliant (missing .catch() for one). Was wondering if this was in the roadmap and whether there is something in the config that I am missing that would change Promise libraries? 

Thanks

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
