### ISSUE TITLE
Add Navigation Component

### ISSUE THREAD

**Issue by radiovisual** [keystonejs/keystone#1691]
Because navigation is such a standard component to any web app, it would be nice to have a navigation component to make the managing / creation of navigation items simple. 

If I am reading things correctly, Issue #153 presents the challenges of creating sub-collections (and waiting for the Admin UI to be re-written in React) and numerous issues have already presented the problems with creating nested items (Issue #1657).

Right now, to get my navigation structure working (and configurable via the Admin UI), I am having to create a `NavigationItem` model and a `SubNavigationItem` model and using a relationship to connect them. It's a little clunky, but it is getting the job done for now.

**Comment by LorbusChris** [comment]
I'm tinkering around with a navbar component as well. see ref #428

**Comment by radiovisual** [comment]
@LorbusChris , that sounds awesome. Keep us updated on your progress. I would like to see your implementations for multi-lang support.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
