### ISSUE TITLE
Add a Type.Icon option

### ISSUE THREAD

**Issue by radiovisual** [keystonejs/keystone#1692]
This is an enhancement request. 

I have a use-case where I am wanting to add font-awesome icons to various parts of my keystone site. It would be really cool if there was a `Type.Icon` field to allow easy search / selection of icons from some of the popular icon libraries, like [font-awesome](https://fortawesome.github.io/Font-Awesome/icons/). 

That way, I could do something like this (see: `content.icon.type`): 

```js
SubNavigationItem.add({
	title: { type: String, required: true, initial:true },
	state: { type: Types.Select, options: 'visible, hidden', default: 'visible' },
	content: {
		icon: { type: Types.Icon, required: true, initial:true },
		link: { type: Types.Url }
	}
});
```

And this would create an icon field in the Admin UI that would allow me to select from a collection of icons. 

**I would be happy to write this plugin in React** if the community thinks there would be some value in it. I would need a little direction, since I am new to the keystone codebase.

**Comment by JedWatson** [comment]
I think this is a great idea, but might better implemented as an extension to the Select control. It's fundamentally an enum that pulls its value from the list of icons available in an icon library.

@jossmac and I have been discussing adding alternate renderers to the select field type to allow things like radio buttons or iOS-style tab strips, being able to render icons with options in the select would also be a nice usability feature (e.g. icons for "draft / published / archived" states in a blog...)

Popular icon libraries (like font-awesome or ionicons) could then be set up as presets for the Select control (either built-in or as additional modules)...

**Comment by radiovisual** [comment]
Yeah, I agree, it would be really nice to bring icon support to the CMS/Admin UI. Right now I am just using  `type: 'String'` and storing the font-awesome markup (i.e: `<i class="fa fa-plane"></i>`) in the database, but it would be much cleaner (and like you say, offer icon support within the Admin UI) if icons were an extension of the Select control. 

**I really like the idea of the different render options for the select field type.**

If you want any help, you can point me in the right direction and I will do what I can.

**Comment by mxstbr** [comment]
I'm closing this due to age, but we'll definitely look into this after 0.4 is released! (very soon…)
