### ISSUE TITLE
can't install 0.3.14 in node 4.1.1/NPM 3.3.4

### ISSUE THREAD

**Issue by gitawego** [keystonejs/keystone#1693]
in npm3, peerDeps aren't auto-installed anymore, as browserify is a peerDep in module browserify-shim, it throws error when installing:
```
npm WARN EPEERINVALID browserify-shim@3.8.10 requires a peer of browserify@>= 2.3.0 < 12 but none was installed.
```
could you please move ``browserify`` from devDependencies to dependencies ?

**Comment by JedWatson** [comment]
Done! thanks @gitawego
