### ISSUE TITLE
Date selector in create modal is broken

### ISSUE THREAD

**Issue by lojack** [keystonejs/keystone#1696]
I'm unable to select a date in the date selector field because it is behind the modal popup. This is for Keystone 0.4

Not sure if this is an elemental bug or a keystone bug.

![screen shot 2015-09-25 at 9 53 50 am](https://cloud.githubusercontent.com/assets/180470/10102303/a54a2a94-636b-11e5-899b-585c242ebf83.png)

**Comment by JedWatson** [comment]
Fixed by #1699
