### ISSUE TITLE
Any reason Keystone includes multiple GraphiQL Playgrounds?

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#1699]
Ok so.. Keystone uses `@keystone-alpha/app-graphql` to create it's GraphQL API. This package uses `apollo-server-express` to create the main API endpoint. It also allows you to [configure a GraphiQL Playground endpoint](https://github.com/keystonejs/keystone-5/blob/master/packages/app-graphql/README.md) using package `@keystone-alpha/app-graphql-playground`. The GraphiQL endpoint path (`graphiqlPath`) defaults to '/admin/graphiql' making the playground available by default, at that path, in all environments.

But `apollo-server-express` _already includes_ the GraphiQL Playground. It's _also_ available by default but the path defaults to the same one used by GraphQL endpoint ('/admin/api' in most Keystones). Unlike the `@keystone-alpha/app-graphql-playground` version, the `apollo-server-express` playground turns itself off in production (based on `NODE_ENV` I guess?).

Was it intentional to double up like this? It seems to me we could remove the `@keystone-alpha/app-graphql-playground` package and refactor `@keystone-alpha/app-graphql` to [pass it's `graphiqlPath` config though to `apollo-server-express`](https://www.apollographql.com/docs/apollo-server/v1/graphiql/#using-with-express). This would both reduce complexity and prevent Keystone from publishing the playground in production environment by default (a good thing to avoid).

**Comment by molomby** [comment]
Not sure how this interacts with #1267

**Comment by molomby** [comment]
Fyi, right now both packages seem to be exposing `v1.7.31` of the playground.

**Comment by molomby** [comment]
Chatted to @timleslie about this; we figured it was probably sensible to keep the GraphiQL config separate. Having it separate lets solution developers configure playgrounds independent of the (potentially multiple) GraphQL endpoints that my host (potentially multiple) Keystone schemas (see #1614).

**Comment by jesstelford** [comment]
The original reason was Apollo used to provide GraphiQL, not GraphQL Playground. GraphQL Playground has more features, so we added it and turned off Apollo's GraphiQL.

Apollo has caught up now, so happy to use that one.

But agreed with @timleslie that multiple endpoints complicates this.

**Comment by MadeByMike** [comment]
What's the action here? Sounds like we are keeping the `@keystone-alpha/app-graphql-playground` separate? Is there any tidy-up with how we use `apollo-server-express` to avoid unnecessary duplication?
