### ISSUE TITLE
Rendering Admin UI components anywhere on the site

### ISSUE THREAD

**Issue by brankosekulic** [keystonejs/keystone#170]
Want to give users ability to write their own posts, so I think it would be the best if users can list and edit posts in their own profile. To make everything consistent we should use the same templates and functionality form Admin UI (maybe sometimes it doesn't fit exact requirements, but having that would help in lot of cases).

If it's not possible, can we give user access to keystone, but with restricted privileges - viewing particular components and editing only their own posts.

**Comment by arthurtalkgoal** [comment]
Can I ask if I can use the UI components in my frontend pages now?

**Comment by SharadKumar** [comment]
I am familiar with getUpdateHandler, but is there a starter guidance on how to re-use Admin UI React components on the site (outside Admin UI) for React noobs?

**Comment by morenoh149** [comment]
@SharadKumar not yet. If you write up a guide feel free to add it to the https://github.com/keystonejs/keystone/wiki/Knowledge-Base

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. If this need still exists, please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)!

**Comment by mxstbr** [comment]
(Also moved the request for documentation here: https://productpains.com/post/keystonejs/reuse-admin-interface-components-in-the-frontend)

**Comment by VinayaSathyanarayana** [comment]
+1

**Comment by VinayaSathyanarayana** [comment]
Any plans to provide Admin UI templates outside the Admin UI?

**Comment by max8hine** [comment]
I am looking the document about getUpdateHandler and similar Keystone APIs or Methods and couldn't find it in anywhere.
