### ISSUE TITLE
Investigate JWT vs Session IDs for Authentication

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#170]
See _[Session Authentication vs Token Authentication](https://security.stackexchange.com/a/92123/144162)_ for more details.

**tl;dr**:

- JWTs have expiry and memory implications, but are stateless so don't require any server side infrastructure
- Session IDs can be expired instantly, are low memory, but require serve side infrastructure (especially in a multi-server environment, ie; Redis, etc).

Our current implementation is Session IDs.

See also #169

**Comment by MadeByMike** [comment]
@jesstelford is this now possible to implement with a custom session store?

**Comment by jesstelford** [comment]
No, it's fundamentally a different model and not supported with custom session stores unfortunately.

**Comment by gautamsi** [comment]
Should this be a session adapter which can make sure consistency in behavior when using jwt or session id?

**Comment by jesstelford** [comment]
Keystone Next will continue to use tokens.
