### ISSUE TITLE
Memory leaks and consumption too high on Simple Hosting

### ISSUE THREAD

**Issue by sarlam** [keystonejs/keystone#1700]
Hey,

I got a keystone app on a Simple Hosting (gandi.net) and memory is locked at 250Mb, therefore my app consume around 80Mo in dev and in prod it reach 250Mo at start !

Simple Hosting kill my node process and my website is now always unavailable. 

I use keystone 0.3.14 and connect-mongo as session storage. 

I read that it's usual for a keystone app to reach that kind of memory usage but with my Simple Hosting I just can't, Is there a way to fix it ? Where should I look if I want to improve keystone memory comsuption ?

Thanks,
Paul J.

**Comment by morenoh149** [comment]
some quick searching reveals https://github.com/joyent/node-stackvis for generating flame charts of node.js applications. It'd be great if there were something obvious from looking at such a chart.

**Comment by sarlam** [comment]
thanks for the quick answer, I couldn't try it earlier but I will generate charts this afternoon, thanks a lot, come back to you as quick as I can

**Comment by medv** [comment]
You only use 80Mb in development? For me regardless of environment it can go to 450mb at any time.

**Comment by mxstbr** [comment]
This is something we definitely have to look into before releasing 1.0!
