### ISSUE TITLE
Searching only possible using filters

### ISSUE THREAD

**Issue by OpenGrid** [keystonejs/keystone#1701]
Something changed with searching. Now it is only possible to find things using filters. General search doesn't work anymore

Additionally if you enter special characters like + in search input you get error 500 from the server

**Comment by JedWatson** [comment]
@OpenGrid are you reporting this for `master` (`0.4-alpha`) or `0.3.x`?

**Comment by OpenGrid** [comment]
master 0.3.x used in production

**Comment by mxstbr** [comment]
Fixed in 0.4, I believe also fixed in 0.3.18!
