### ISSUE TITLE
New List / Item Update method

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1705]
To enable RESTful API support for the Admin UI (as well as custom API routes), we need a new List.prototype.updateItem method to replace List.prototype.getUpdateHandler.

This is a placeholder issue while I work out what the API should actually look like, but in particular it needs to allow for Fields to hook their own update and async logic in, rather than having it built into the core function as is the case with the UpdateHandler functionality.

Probably relates to #1563, how we handle files will be an important part of how the method works.

Once the single-item update is working, we need to make a call on continuing to support the `UpdateHandler` as it is, or whether it can be implemented as a wrapper for the new method. I'd like to avoid breaking the API for 0.3 > 0.4 if possible, but this is an area that really needs to be cleaned up.

**Comment by JedWatson** [comment]
Status update: basic field updates work now (where `Field.prototype.updateItem` is sufficient); needs more testing around validation, and needs to support async update processes (e.g. file upload)

**Comment by ericelliott** [comment]
:+1:

**Comment by JedWatson** [comment]
Progress update / more info:

We're basically replacing

* https://github.com/keystonejs/keystone/blob/master/admin/server/routes/item.js and
* https://github.com/keystonejs/keystone/blob/master/lib/updateHandler.js

with

* https://github.com/keystonejs/keystone/blob/master/admin/server/api/item/update.js and
* https://github.com/keystonejs/keystone/blob/master/lib/list/updateItem.js

... and fully fleshed-out / async update methods on Field types as per #1713

Then we can complete #1714

**Comment by ericelliott** [comment]
Thank you! I was just trying to dig into these details. =) You read my mind!

(∩｀-´)⊃━☆ﾟ.*･｡ﾟ

**Comment by ericelliott** [comment]
Where are the API tests?

**Comment by JedWatson** [comment]
There aren't any tests yet for the REST API (we should add some as part of this work), the field types have a `/test` folder under each `/fields/types/{type}` which directly tests the field type class

**Comment by ericelliott** [comment]
Cool. I've been reading up a bit more on lists and field types in the docs. I'll play with it a bit more and try to soak up enough context to write good tests. =)

**Comment by wmertens** [comment]
Note that the exact implementation is still being discussed at #3209

**Comment by JedWatson** [comment]
This is done now, good to close!
