### ISSUE TITLE
0.4: Do not get the Update button when managing all

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1708]
Steps to reproduce using the keystone-test-project:

1. Off the Home Screen click on Users
2. Click Manage
3. Click All
4. Click Update
5. Select any field (e.g., Can access Keystone)

Do not get the Update button:

![image](https://cloud.githubusercontent.com/assets/5872515/10298319/aed69064-6bab-11e5-86cc-b405ad962bb9.png)

NOTE:  If you click anywhere or switch windows then the button shows.  But there's that initial moment that you have no clue what to do!

OS: Windows 10
Browser: Chrome

**Comment by jossmac** [comment]
Closing in favour of #1709
