### ISSUE TITLE
0.4:  Manage All does not update fields

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1709]
Steps to reproduce using the keystone-test-project:

1. Off the Home Screen click on Users
2. Click Manage
3. Click All
4. Click Update
5. Select any field (e.g., Can access Keystone)
6. Try to update it -- does not work

OS: Windows 10
Browser: Chrome

**Comment by JedWatson** [comment]
Just FYI, this is a "known issue" , the UI for the feature is done but the back-end processing is WIP. Should be done soon.

**Comment by mxstbr** [comment]
I'll close this as it's on my radar for the 0.4 release.
