### ISSUE TITLE
Email class option templateBasePath and Keystone emails option

### ISSUE THREAD

**Issue by snowkeeper** [keystonejs/keystone#1710]
Do the Email class option `templateBasePath` and the Keystone option `emails` do the same thing but  independently of each other?  

Keystone email option: https://github.com/keystonejs/keystone/blob/master/lib/email.js#L285

`options.templateBasePath` : https://github.com/keystonejs/keystone/blob/master/lib/email.js#L333

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
