### ISSUE TITLE
0.4:  Creating a new user throws error

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1711]
![image](https://cloud.githubusercontent.com/assets/5872515/10326628/775e62a4-6c6b-11e5-9dd8-d7df0cfcccb0.png)

The following input reproduces the issue:
![image](https://cloud.githubusercontent.com/assets/5872515/10326859/26ef95c4-6c6e-11e5-8b89-9b96cb626940.png)

OS:  Windows 10
Browser: Chrome

**Comment by JedWatson** [comment]
Fixed by @kumo's PR
