### ISSUE TITLE
0.4: erratic 'Relationships' text

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1712]
In the following perhaps that "Relationships" section at the end should not be display if there's not relationships active:

![image](https://cloud.githubusercontent.com/assets/5872515/10326906/cb9390c6-6c6e-11e5-8363-7ed6f2b76a1b.png)

OS:  Windows 10
Browser: Chrome

**Comment by JedWatson** [comment]
I've implemented relationships correctly now, that old code is gone. It works in 0.4 like it did in 0.3.
