### ISSUE TITLE
0.4 [BABEL] Note: The code generator has deoptimised the styling of

### ISSUE THREAD

**Issue by mahnunchik** [keystonejs/keystone#1715]
```bash
$ node -v
v4.1.1
$ npm -v
3.3.6
```

keystone@0.4.0-alpha

Keystone displays a lot of messages like this:
```
[BABEL] Note: The code generator has deoptimised the styling of "/blabla/node_modules/lodash/index.js" as it exceeds the max of "100KB".
```

**Comment by LorbusChris** [comment]
same here.

**Comment by ChuckPierce** [comment]
node_modules need to be ignored as well in the babelify configuration

Something like:

```
b.transform(babelify.configure({
			ignore: ['**/lib/**', '**/node_modules/**'],
			plugins: [require('babel-plugin-object-assign')]
		}));
```

**Comment by terenzeyuen** [comment]
Same here.

**Comment by JedWatson** [comment]
Should be fixed now, let me know if you still see this...

**Comment by tim-smart** [comment]
@JedWatson Still seeing this on latest master!

**Comment by mxstbr** [comment]
Not seeing this anymore, so I'll assume this is fixed. Let me know if this issue still exists for you!

**Comment by terenzeyuen** [comment]
I think fixed, not getting them anymore.
