### ISSUE TITLE
Is Model Inheritance broken?

### ISSUE THREAD

**Issue by kfancy** [keystonejs/keystone#1717]
I'm trying to use model inheritance, but any attempts result in:

MY_APP/node_modules/keystone/lib/list/register.js:32
		this.model = this.get('inherits').model.discriminator(this.key, this.schema)
		                                       ^
TypeError: Cannot read property 'discriminator' of undefined

Checking the Object.keys() on this.get('inherits'), there is no top level "model" property on the returned object, and doing an object tree dump I can't quite find how to get to it.

Anyone out there confirm or deny?

**Comment by lojack** [comment]
Not sure without more detail on your code, but my guess is that `register()` was never called on the parent list.

**Comment by kfancy** [comment]
I just checked, and register() is called on the parent list.
I also dumped the result of this.get('inherits') and it returns the parent list, but the parent list just has no top-level property "model" to chain into .discriminator().

locally added this code to lib/list/register.js (around line 32) to see what happens, here's the result:

console.log( Object.keys( this.get('inherits') ) );
[ 'options',
  'key',
  'path',
  'schema',
  'schemaFields',
  'uiElements',
  'underscoreMethods',
  'fields',
  'fieldsArray',
  'fieldTypes',
  'relationshipFields',
  'relationships',
  'mappings' ]

**Comment by kfancy** [comment]
Fresh dump, includes parent list object (via console.dir) after the Object.keys() output.

Object Keys:
```
[ 'options',
  'key',
  'path',
  'schema',
  'schemaFields',
  'uiElements',
  'underscoreMethods',
  'fields',
  'fieldsArray',
  'fieldTypes',
  'relationshipFields',
  'relationships',
  'mappings' ]
```
List Object:
```
{ options: 
   { schema: 
      { collection: 'users',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strict: true },
     noedit: false,
     nocreate: false,
     nodelete: false,
     autocreate: false,
     sortable: false,
     hidden: false,
     track: false,
     inherits: false,
     searchFields: '__name__',
     defaultSort: '__default__',
     defaultColumns: '__name__' },
  key: 'User',
  path: 'users',
  schema: 
   { paths: { _id: [Object] },
     subpaths: {},
     virtuals: { id: [Object] },
     nested: {},
     inherits: {},
     callQueue: [ [Object], [Object] ],
     _indexes: [],
     methods: {},
     statics: {},
     tree: { _id: [Object], id: [Object] },
     _requiredpaths: undefined,
     discriminatorMapping: undefined,
     _indexedpaths: undefined,
     s: { hooks: [Object], queryHooks: [Object] },
     options: 
      { collection: 'users',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strict: true } },
  schemaFields: [],
  uiElements: [],
  underscoreMethods: {},
  fields: {},
  fieldsArray: [],
  fieldTypes: {},
  relationshipFields: [],
  relationships: {},
  mappings: 
   { name: null,
     createdBy: null,
     createdOn: null,
     modifiedBy: null,
     modifiedOn: null } }
```

**Comment by stuartflanagan** [comment]
The example on the site has the Parent declaration in the same file as the child that is inheriting from. This ensures that register is called before inheritance is implemented in the child.

I can see why this would be required but it breaks the ability to use Model inheritance across a range of models. Or alternatively store all models in one file?

**Comment by stuartflanagan** [comment]
I was trying
````JavaScript
var Video = new keystone.List('Video', {
  autokey: { from: 'name', path: 'key' },
  inherits: keystone.List('Media')
});
```
Both in separate files. It only worked when combined in the same file and Media.register() called before being used in Video.inherits

**Comment by creynders** [comment]
@Stuartflanagan have you tried `require`ing Media.js explicitly at the top of Video.js?

**Comment by stuartflanagan** [comment]
No I have not! Thanks @creynders I will try that out tonight.

**Comment by creynders** [comment]
Or create a separate directory `base` with `Media` in it. Then add `keystone.import('./base')` to your `keystone.js` right before `keystone.import('./models')`

**Comment by stuartflanagan** [comment]
Ensuring exports.Media = Media; in my Media.js model file then importing into Video.js and Image.js model files works well.

Thank you @creynders

**Comment by ericelliott** [comment]
All good now? close?

**Comment by stuartflanagan** [comment]
I did not open it. Just chimed in through ignorance. But yes it works for me thank you.

**Comment by ghuroo** [comment]
@stuartflanagan can you provide a sample of how you implemented it? I want to replicate this logic but so far I didn't manage to :/
