### ISSUE TITLE
Pagination Header Spillover with large collection

### ISSUE THREAD

**Issue by grindfuk** [keystonejs/keystone#1718]
Hi, 
In a collection with a large number of documents (ie. > 50000), the Pagination__List with the numbers 1-500 appears to spill over into and on top of the ItemList table. 

I don't know of a good solution to this. 
It may be simply masking a section of the numbering to be like "1, 2, 3 , ... " but then you would need a button frame for moving along the display results  "3, 4, 5, ... "

**Comment by erg0dic** [comment]
I can reproduce this:
<img width="1348" alt="screen shot 2015-10-13 at 11 47 09 am" src="https://cloud.githubusercontent.com/assets/5550520/10459995/53b0736c-71a0-11e5-9ca1-7a9c32dd2842.png">

**Comment by JedWatson** [comment]
Fixed :)

**Comment by grindfuk** [comment]
Thanks!!!
