### ISSUE TITLE
DRY: CreateItemModal duplicated across admin-ui and RelationShip Field

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#1719]
I see that the code for `CreateItemModal` component in the `admin-ui` and relationship field view is largely the same.

Should this be unified into separate package? Separate package may also help in enabling people use them in extensions / plugins for admin-ui being worked on.

I have created a diff url http://quickdiff.net/?unique_id=D23C0BBE-07A9-855A-DA6E-BBD8C1377EE9

**Comment by MadeByMike** [comment]
Yep, I think this could be an export from somewhere. Not sure where it should live maybe with other utils... ?

Probably worth doing next time someone touches either instance of this code but no urgency now :)

**Comment by gautamsi** [comment]
I am working on something where I need to make use of existing admin ui components, I will try to make this a new package and have some existing components exported out.

@MadeByMike any preference on name, some options I can think of

`@keystonejs/ui`
`@keystonejs/components`
`@keystonejs/ui-parts`

I see that it can be stand alone exports and reused by anyone, it may also go into `@keystonejs/utils/ui`

**Comment by gautamsi** [comment]
on another thought, it may make sense to exports parts from the `admin-ui` itself and have Relationship view get the `CreateItemModel` as props from `admin-ui`
