### ISSUE TITLE
handlebars demo - submit

### ISSUE THREAD

**Issue by jdarling** [keystonejs/keystone#172]
@JedWatson @sheo13666 

Ok, got tired of everyone (including myself) asking about how to create using a different template engine, so I'm posting my progress on a clone of the keystone-demo in handlebars.  It is located at https://github.com/jdarling/keystone-handlebars-demo

Feel free to clone and submit pull requests if you decide to flush it out more.  Shows how to use default layouts, page views, and partials.

**Comment by mxstbr** [comment]
The generator supports multiple templating languages now!
