### ISSUE TITLE
Cannot scroll in select dropdowns on the create Item modal

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#1720]
# Bug report
Cannot scroll in in selects on the create Item modal

## Describe the bug
Cannot scroll in select dropowns on the create Item modal in the admin UI

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:
1. Create an item which has a select field. 
2. Try and scroll in the select modal

## Expected behaviour
should be able to scroll

## Screenshots
![2019-10-02 09 59 34](https://user-images.githubusercontent.com/42298774/66008958-d0a66200-e4fb-11e9-950f-483ede03a2b7.gif)

## System Information
Google chrome
Mac OS Mojave 10.14.6

**Comment by jossmac** [comment]
This is a bug in react-select, specifically with async options. It's unlikely that it will be resolved in the current version. A more configurable "headless" implementation is hopefully coming soon.

**Comment by ayush-goyal** [comment]
I'm still having this issue, any ideas on how to get around this?

**Comment by stenvix** [comment]
I'm still having this issue, is there a solution to this problem?
