### ISSUE TITLE
0.4:  Align symbols in select box

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1722]
In the following image the "x" and the "down carret" in the "Favorite Flavour" select box look misaligned:

![image](https://cloud.githubusercontent.com/assets/5872515/10383420/9b5bb142-6dfc-11e5-9e4a-52b562162cab.png)

OS:  Windows 10
Browser: Chrome

**Comment by morenoh149** [comment]
Just the 'x' looks misaligned to me. The downcaret looks like it's where is should be. Assigning this to myself. If anyone else wants to tackle it feel free to do so after some grace period.

**Comment by jossmac** [comment]
@webteckie would you mind checking this again?

About a month ago I fixed a few bugs with react-select layout, I'm hoping this is the case :)

**Comment by webteckie** [comment]
@jossmac looks good now...tnx!
