### ISSUE TITLE
0.4: Update to React 0.14

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1725]
I've updated the bundled version of React to 0.14 and it works, but there are a number of warnings (some of which are coming from packages Keystone depends on including Elemental UI) that we should work through.

Related to elementalui/elemental#77

**Comment by lojack** [comment]
This seems to break the item view for me.
![screen shot 2015-10-09 at 10 59 44 am](https://cloud.githubusercontent.com/assets/180470/10398020/b9eda3dc-6e78-11e5-8a02-132ef90911c8.png)

**Comment by JedWatson** [comment]
@lojack I'm seeing the same thing, working through it now. This seems to be an issue in one of the packages, all the references to `react/addons` are removed in Keystone itself.

**Comment by JedWatson** [comment]
All the warnings are gone now, so this looks safe to close.
