### ISSUE TITLE
Loading Gallery, but not the blog

### ISSUE THREAD

**Issue by kelthenoble** [keystonejs/keystone#1726]
On localhost:3000 it's loading the gallery post, but not loading the blog posts. 
On localhost:3000/keystone, i have created a few sample test, I've added 2 blog post & 2 gallery post. 
![screen shot 2015-10-09 at 9 56 29 am](https://cloud.githubusercontent.com/assets/1773260/10400196/2fff3412-6e6c-11e5-88d0-77dd2a3b0378.png) 
![screen shot 2015-10-09 at 9 56 55 am](https://cloud.githubusercontent.com/assets/1773260/10400207/392b92c4-6e6c-11e5-92c1-f537f3d44bae.png)
![screen shot 2015-10-09 at 9 57 11 am](https://cloud.githubusercontent.com/assets/1773260/10400223/4b24e02a-6e6c-11e5-913d-53893cf4ce24.png)
![screen shot 2015-10-09 at 9 57 27 am](https://cloud.githubusercontent.com/assets/1773260/10400228/4f388c16-6e6c-11e5-8593-f3899ade5e33.png)

**Comment by kelthenoble** [comment]
It's in the DB, but not showing in the client-side, how ever it is showing categories. 
![screen shot 2015-10-09 at 11 09 47 am](https://cloud.githubusercontent.com/assets/1773260/10401835/650bc56c-6e76-11e5-8646-3ff684cbf801.png)

**Comment by 0rland0Wats0n** [comment]
@kelthenoble if you haven't figured this out as yet, I see that the state of the posts are set to draft. This could be the issue so set them to published and they should show up.

**Comment by kelthenoble** [comment]
Yup, that worked. Thank you!
![screen shot 2015-10-09 at 10 57 58 pm](https://cloud.githubusercontent.com/assets/1773260/10409529/3d843958-6ed9-11e5-8ab9-6c24cc4d153a.png)
