### ISSUE TITLE
RFC: Expose keystone settings via Admin UI

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1729]
It would be very convenient, and even practical, to be able to update keystone settings via the Admin UI.  For example, a core list model (Settings) can be introduced to serve as the container for all settings.  Keystone would be directly responsible for managing this model both at startup when it hasn't been initialized, yet, and when a permissible user tweaks a setting via the Admin UI.  It is possible that certain settings would not be changeable via the Admin UI and these can be marked Read-Only or if these are changeable then it would require a restart of the keystone app for the changes to take effect.    The aim is to, for as many settings as possible, have their intended action take effect immediately without a keystone app restart.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/expose-keystone-settings-via-admin-ui!
