### ISSUE TITLE
Invalid prop `children` suppled to `Form`

### ISSUE THREAD

**Issue by r1b** [keystonejs/keystone#1731]
Can't seem to render any content items on master branch. I imagine this is a part of the bump to react 0.14.

As an example, I get the following output when trying to view the admin user in the ui:
<img width="1432" alt="screen shot 2015-10-13 at 1 55 15 pm" src="https://cloud.githubusercontent.com/assets/5550520/10463450/bbcfbea0-71b2-11e5-9ab2-330d364cf6a9.png">

I can trace this back to the call ```this.renderFormElements()``` in admin/src/components/EditForm.js:244, but at that point I'm afraid I become useless :)

**Comment by jacargentina** [comment]
It seems current master branch is unusable (Admin UI edit items).

**Comment by mxstbr** [comment]
Yeah there's tons of warnings at the moment, I'll slowly be tracking them down and fixing them with #2566!
