### ISSUE TITLE
Keystone admin lists "Create New [OBJECT]" button not showing the modal

### ISSUE THREAD

**Issue by kfancy** [keystonejs/keystone#1732]
Using the new admin, I can see the list of items (admin "home") and go to a list object (choosing a list from admin "home") but once there, the create button for the list will fire, write the React form element into the dom, but it never actually shows.

Tried in Safari, Opera, Chrome on OSX.

**Comment by lawrencealan** [comment]
also seeing this issue

**Comment by ericelliott** [comment]
Anybody want to take a crack at digging into this? Remember to add tests for the fix. =)

**Comment by erg0dic** [comment]
Works for me against master, tried OS X Chrome, Safari & Firefox.

**Comment by mxstbr** [comment]
Thanks so much for testing this @r1b, sorry for the slow reply—I'll close this issue!
