### ISSUE TITLE
📌 These issues 👇 are our backlog (not just bugs)

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1732]
The Keystone 5 team use GitHub issues as a task manager _and_ bug tracker. We find this keeps our work closer to our project management which helps reduce cognitive load.

When you see `Issues 259`, don't think _"Whoa, that's a lot of bugs!"_, instead think _"Whoa, this team has a huge backlog they're working through; I can't wait for what's to come!"_ ❤️

**Comment by dcousens** [comment]
These are [probably] bugs https://github.com/keystonejs/keystone-5/labels/bug
