### ISSUE TITLE
Incorrect password checking

### ISSUE THREAD

**Issue by amaax** [keystonejs/keystone#1733]
At [/lib/session.js:110 (master)](https://github.com/keystonejs/keystone/blob/master/lib/session.js#L110) it's incorrect password checking.

It compares unhashed input password to hashed hash of password.

I tried to fix it but stored hash and hashed input never matches, so I copy-pasted checking above and it worked.

**Comment by wmertens** [comment]
@amaax Obviously this doesn't always happen or nobody would be able to log in :) Do you still have this problem? If so, can you show your configuration?

**Comment by mxstbr** [comment]
Closing due to staleness and not being able to replicate. Feel free to comment again if this issue still exists for you!
