### ISSUE TITLE
Cloudinary folder option not saving images to expected location

### ISSUE THREAD

**Issue by alsoicode** [keystonejs/keystone#1734]
I have set the "Auto-create folders" for my Cloudinary account to true, but no matter what folder option I specify, or if I create the folder ahead of time at Cloudinary, images are always uploaded to the Cloudinary root.

Example model:

    Sample.add({
        title: { type: Types.Text, required: true, initial: true },
        thumbnailImage: { type: Types.CloudinaryImage, folder: 'samples', autoCleanup: true },
    });

**Comment by njk** [comment]
did you set 	'cloudinary folders': true in keystone? @alsoicode

**Comment by mxstbr** [comment]
What @njk said should solve your problem as far as I understand, so I'll close this issue for now. Feel free to comment again if this is still an issue for you!

**Comment by alsoicode** [comment]
Sorry for the *extremely* late reply, but I can confirm that adding the cloudinary folders setting is working as expected.

**Comment by mxstbr** [comment]
Hah, awesome that you came back! Glad to hear!

**Comment by alsoicode** [comment]
It's been a busy year :)

**Comment by mxstbr** [comment]
That's the way it should be! Still using Keystone?

**Comment by alsoicode** [comment]
Oh absolutely. I have two sites currently in development for personal clients using Keystone.

One uses it as a full-stack solution for a public site plus as an API for an Aurelia powered SPA that is primarily designed for mobile.

The other site is full-stack. Additionally, Keystone powers my personal site as an API to an Aurelia front-end.

The dynamic admin is worth its weight in gold.

**Comment by mxstbr** [comment]
So happy to hear that, you're going to *love* 0.4 when we finally release it! Rock on!
