### ISSUE TITLE
Add "alt" field on CloudinaryImages Type

### ISSUE THREAD

**Issue by mespeche** [keystonejs/keystone#1735]
Currently, image upload via Cloudinary does not give access to an option to add an "alt" (and "title") attribute on the images.
This feature can be very useful for SEO and accessibility :wink:

**Comment by gillesbourgeat** [comment]
:+1:

**Comment by morenoh149** [comment]
Cloudinary allows adding any kind of extra info in the `context` field. See http://cloudinary.com/documentation/node_image_upload#all_upload_options
Anyone can add extra options into the options object here https://github.com/keystonejs/keystone/blob/cc4385037151f6c1e3af5dee342672fb6b8e6954/admin/api/cloudinary.js#L8
Then we should show it in the admin at https://github.com/keystonejs/keystone/blob/cc4385037151f6c1e3af5dee342672fb6b8e6954/fields/components/columns/CloudinaryImageSummary.js#L65 to illustrate how an end-user may display alt in their own templates.

@mespeche @gilesbutler PR welcome

**Comment by mikaoelitiana** [comment]
I will work on this.

**Comment by morenoh149** [comment]
Feel free to ask questions on the gitter chat @MichaelZaporozhets

**Comment by mikaoelitiana** [comment]
Thanks!

**Comment by lomegg** [comment]
So... any updates? That feature would be very useful.

**Comment by mxstbr** [comment]
The feature exists, as @morenoh149 said. It's just a documentation issue, so I've moved it to keystonejs-site: https://github.com/keystonejs/keystonejs-site/issues/110

**Comment by clodal** [comment]
Can we re-open this issue? https://github.com/keystonejs/keystonejs-site/issues/110
