### ISSUE TITLE
0.3: compress and bodyparser don't apply for custom routes

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#1737]
When using the `routes` option, these routes have to use their own compress and bodyparser, any reason? I didn't test 0.4.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
