### ISSUE TITLE
Set Redirect Status Code

### ISSUE THREAD

**Issue by boatrokr** [keystonejs/keystone#1739]
After looking at core:redirect it looks like you can't set the redirect status code using keystone.redirect.

Reading this https://moz.com/learn/seo/redirection tells me that search engines don't treat 302s kindly, which is what keystone.redirect defaults to.

Am I correct in assuming that anything redirected by keystone.redirect is not indexed by search?

If this is the case, I'm willing to make a PR where keystone.redirect takes 3 args as well as what you have now.

**Comment by mahnunchik** [comment]
+1

```js
// default 302
keystone.redirect('/old-route', 'new-route');

// custom code
keystone.redirect('/old-route', 'new-route', 301);
```

```js
keystone.redirect({
  'old-route': 'new-route',
  'old-route2': {
    route: 'new-route',
    code: 301
  }
});

```

**Comment by morenoh149** [comment]
@mahnunchik is that how you envision the new feature working or does that code currently work?

**Comment by mahnunchik** [comment]
Hi @morenoh149 

It is my envision. I think it saves backward compatibility.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/set-redirect-status-code!
