### ISSUE TITLE
v0.3 dependencies cause conflicts with React 0.14

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#1741]
keystone 0.3 has react-select and react-alt-text as deps, and those don't work with React 0.13.

This shouldn't be a problem, because keystone only uses its React dependencies in its own pages, completely disconnected from the app, but instead it blocks upgrades (and on top of that the npm error is really hard to track down but that has nothing to do with Keystone).

Ideally, the dependencies for the keystone admin page should be completely decoupled from the project. Perhaps the admin pages could be compiled to plain JS and included in that form?

**Comment by celiao** [comment]
I would like to learn from the way Keystone and the admin is set up with React.  Keeping that connection as exposed as possible would be preferred.

**Comment by wmertens** [comment]
@celiao the source would still be there to read and build on…

**Comment by mxstbr** [comment]
This is very stale, so I'll close it.
