### ISSUE TITLE
Form Builder

### ISSUE THREAD

**Issue by AddoSolutions** [keystonejs/keystone#1744]
Hello, I just wanted to see if a form builder for usage on the frontend of the site is in the works, or planned.  I saw some chatter that there was some ideas for it but not much in the way of responses.

I am a NodeJS developer and am considering helping build that part out, but some direction would be very helpful.

Thanks!

**Comment by AddoSolutions** [comment]
Just thinking about this one a little bit, some of the pieces that will need consideration:

* Dynamic models (assuming we would store different forms in their own collection?)
* Interface and place in Admin UI for developing the form-builder
* Considerations for the React Rebuilt
* Ensuring that the front-end has a decent aesthetic look by default

Any insights on any of those points would be great.

**Comment by morenoh149** [comment]
KeystoneJS doesn't really concern itself with the frontend of the "site". Do you mean a form builder for the adminUI ?

**Comment by AddoSolutions** [comment]
Yes, so the ability to design a contact form in the backend and have it shown and submitted on the front end. Sign up forms, request quite, etc. email results, store the results, etc.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/gui-form-builder!
