### ISSUE TITLE
ACL

### ISSUE THREAD

**Issue by AddoSolutions** [keystonejs/keystone#1745]
I am also looking to build out an ACL (access Control Layer) to do the following:

* Allow creation of security groups of users with specific permissions
* Allow assigning of users to security groups
* Enforce those permissions
* Ideally log activity of each and have a way to show those logs

I am more than willing to build this out, but am curious to get the rest of the community's feed back before I do too much.

The reason I am focusing on these is because I have several clients who have this (and the form builder) as make-or-break issues, and I suspect this is true of many others.

**Comment by riyadhalnur** [comment]
:+1:

**Comment by webteckie** [comment]
Duplicate of #803 ?

**Comment by morenoh149** [comment]
@AddoSolutions yep this is a duplicate. Please read the existing issues. #803 and #899 We are very excited to have your help. Checkout the #keystonejs channel on [reactiflux](http://www.reactiflux.com/)
