### ISSUE TITLE
Autocomplete not working on v0.4 (master)

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystone#1749]
I'm getting this when trying to use autocomplete on a Ref field:

    CastError: Cast to ObjectId failed for value "autocomplete" at path "_id"

I'm simply migrating my app from 0.3.15 to 0.4 from master

**Comment by sebastianandreasson** [comment]
Also seeing this error, currently trying out 0.4.

**Comment by jacargentina** [comment]
@JedWatson please merge my fix?

**Comment by JedWatson** [comment]
I've fixed this. Took a major rewrite of react-select and updates to basically everything about relationship fields, but was totally worth it.
