### ISSUE TITLE
What does `required` mean for a "many" Relationship?

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#175]
Or; How can we force there to always be at least one item in a "many" Relationship?

Eg;

```javascript
keystone.createList('Group', {
  fields: {
    owners: { type: Relationship, ref: 'User', many: true, required: true },
  },
});
```

👆 A `Group` must always have at least 1 owner.

## Open Questions

- Does this make sense?
- How can we enforce this for `delete` / `update` / etc operations. It has impacts on when the `User` item is deleted, the `owners` field might still list them as a Relationship, even though they don't exist. Do we fail the `deleteUser` command there?

**Comment by 1337cookie** [comment]
I often opt for "soft-delete" wherever practical in applications I'm building for this reason. It can also make reverting mistakes and potentially vandalism easier than going to a backup on a live application. It could be applicable here. For users that's probably not GDRP compliant but you could create a unique placeholder "Deleted user" or "Deleted owner" in such instances that would take over all the same relationships but carry a deleted flag. It might be a little more complex but at least your not returning nulls or making changes that could be unpredictable beyond the scope of the desired action to delete a user.

**Comment by jesstelford** [comment]
Closing this as demand doesn't seem high.
