### ISSUE TITLE
Demo AdminUI - Unable to access admin

### ISSUE THREAD

**Issue by gRoberts84** [keystonejs/keystone#1751]
Hi there,

Just went to take a look at KeystoneJS as I'm interested in implementing it however after logging in with the demo account details, I am only shown the login page with a message stating I'm already logged in.

Thanks

Gav

**Comment by zanetaylor** [comment]
+1

http://demo.keystonejs.com/keystone/ redirects to http://demo.keystonejs.com/keystone/signin after logging in.

**Comment by adamburmister** [comment]
+1

**Comment by morenoh149** [comment]
issue exists over at the project repo https://github.com/keystonejs/keystone-demo/issues/25

**Comment by rafamontoya** [comment]
+1
