### ISSUE TITLE
0.3 Error: Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by mahnunchik** [keystonejs/keystone#1752]
```bash
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

node: 4.2.1
npm: 2.14.7
keystone: 0.3.15

**Comment by mahnunchik** [comment]
Related issue: https://github.com/keystonejs/keystone/issues/1707

**Comment by nifl** [comment]
updating mongoose resolves this error for myself

**Comment by ericelliott** [comment]
@JedWatson Just ran into this myself using the React generator.

**Comment by JedWatson** [comment]
This is an issue related to keystone v3 being pinned to mongoose 3, which isn't compatible with node v4+

I've held off bumping 0.3 to mongoose 4 because it contains breaking changes in a major dep. I don't like the status quo but probably the best way through this is to just push hard at the 0.4 release to bring us up to date with the latest mongoose

Otherwise we could push a new minor version just for mongoose 4, but I was really hoping not to do that...

**Comment by ericelliott** [comment]
@JedWatson Is there a workaround that I can use right now?

**Comment by ericelliott** [comment]
The error goes away when I run Keystone 0.4 (I'm working against the latest master) 

`¯\_(ツ)_/¯`

**Comment by srahulprdxn** [comment]
This below given stackoverflow link can be a workaround until the issue is resolved.

http://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson

**Comment by ericelliott** [comment]
dupes:

* https://github.com/keystonejs/keystone/issues/959
* https://github.com/keystonejs/keystone/issues/1942

**Comment by mxstbr** [comment]
This is fixed!

**Comment by jasontwong** [comment]
@mxstbr How is this fixed? I'm still getting this error using the yoeman generator.

node: 6
npm: 3.8.6
keystone: 0.3.16

**Comment by mxstbr** [comment]
Fixed in v4 :+1:

**Comment by jasontwong** [comment]
Sweet. Thanks for the hard work! Can't wait to use it.

**Comment by danielmahon** [comment]
im still getting this in 0.4.0-alpha

**Comment by ccqgithub** [comment]
`Fixed in v4` what this mean? The latest version also has this problem……

**Comment by wmertens** [comment]
@ccqgithub you need to use the `master` branch from git by running `npm i keystonejs/keystone`.

**Comment by ccqgithub** [comment]
@wmertens tks 👍

**Comment by Maudulus** [comment]
Still having an issue with this...

**Comment by Maudulus** [comment]
Ok, super weird but had to follow this post https://github.com/keystonejs/keystone/issues/2916 (thanks @nfatah) and change: 
MONGODB_URI:      mongodb://heroku_hr12345:asdfjklmn@ds23456.mlab.com:12345/heroku_hr12345

TO

MONGOLAB_URL:      mongodb://heroku_hr12345:asdfjklmn@ds23456.mlab.com:12345/heroku_hr12345

and then it all works!
