### ISSUE TITLE
can you add a comment module for keystonejs?

### ISSUE THREAD

**Issue by eimhee** [keystonejs/keystone#1754]
can you add a comment module for keystonejs?
thanks.

**Comment by brianjd** [comment]
Hi @eimhee can you be a bit more specific as to what you are trying to achieve? Depending on your purposes there are different approaches available.

**Comment by eimhee** [comment]
http://demo.keystonejs.com/blog/post/testing123
why the demo site has "sign in to comment"?
but when I install keystone in my local machine, the use can not give a comment on a blog article

**Comment by morenoh149** [comment]
@eimhee maybe the deployed app differs from your installed app. Maybe the deployed app has a setting enabled that allows the comment to be made

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
