### ISSUE TITLE
Pass data to Javascript variable from Handlebars in Keystone.JS

### ISSUE THREAD

**Issue by rinku9900** [keystonejs/keystone#1755]
I am using Handlebars for my views and I want to pass returned data from database to javascript/JQuery. So what will be the similar logic to this code in Handlebars:

```jade
//These lines of code are from Jade template.
var SydJS = {};
SydJS.meetup = !{JSON.stringify(meetup)};
```

Thanks.

**Comment by jeffreypriebe** [comment]
You could populate it as in the meetup route:

```
view.on('init', function(next) {
  Meetup.model.findOne()
  ...
  .exec(function(err, meetup) {
	...
	locals.meetup = meetup;
```

https://github.com/JedWatson/sydjs-site/blob/master/routes/views/meetup.js#L27
