### ISSUE TITLE
Remove `keystone.createItems` now that we have `keystone.executeQuery`

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1756]

**Comment by timleslie** [comment]
c.f. https://github.com/keystonejs/keystone-5/pull/1091

**Comment by MadeByMike** [comment]
A lot of people still make use of createItems. Can we change the direction of this to first make sure that the alternatives are clearly documented and add a deprecation warning. There is also a possibility of moving this to it's own package that maps a `createItems` call to an `executeQuery`.

After this I'd say we can safely remove it.

**Comment by gautamsi** [comment]
`executeQuery` has one downside compared to `createItems`. It can not connect to items based on fields other than `Id`. Once #2977 is reality, this may be closed.
