### ISSUE TITLE
Cann't change session store from mongo to redis

### ISSUE THREAD

**Issue by wuhaixing** [keystonejs/keystone#1758]
I change sydjs's session store from `mongo` to `redis`,server start successfully,but I got `Error: Can't set headers after they are sent.` when access any page.

**Comment by jorge07** [comment]
It's your configuration something like that?

'session store':'connect-redis',
    'session store options': {
        'port': process.env.redisPort || 6379,
        'host': process.env.redisHost || 'localhost',
        'pass': process.env.redisPrimaryKey || process.env.redisSecondaryKey || null
    }

**Comment by wuhaixing** [comment]
Yes,I can connect to redis sever,and Keystone do `persist` in /lib/session L169 successfully,but after that...I got `Error: Can't set headers after they are sent`

**Comment by jorge07** [comment]
Ok, Seems you're sending the response to the client more than once.

**Comment by wuhaixing** [comment]
Thanks for your concern @jorge07 ,I change nothing but session store,and after I switch it back to mongo,error was gone too.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
