### ISSUE TITLE
Support for basic keyboard shortcuts

### ISSUE THREAD

**Issue by BorisBozic** [keystonejs/keystone#176]
CMD+S to save changes, please?

**Comment by prachi-159** [comment]
In which file do we have to add this feature ?

**Comment by morenoh149** [comment]
this might do it https://www.npmjs.com/package/keyboard-shortcut

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/support-for-basic-keyboard-shortcuts)!
