### ISSUE TITLE
can't change language locale

### ISSUE THREAD

**Issue by dfsdfsdfs** [keystonejs/keystone#1765]
for example for published post dates

el #{post._.publishedDate.format('MMMM Do, YYYY')} 

el #{post._.publishedDate.format('MMMM Do, YYYY', 'MYLANG')} should be enough for moment, but it's bugged

**Comment by w01fgang** [comment]
I use momentjs.
In keystone.js I was added moment to locals:
```
keystone.set('locals', {
  _: require('underscore'),
  moment: require('moment'), 
  env: keystone.get('env'),
  utils: keystone.utils,
  editable: keystone.content.editable
})
```
and in template:
```
#{moment.locale('it')&&moment(post.publishedDate).format("MMMM Do, YYYY")}
```
or
```
#{moment(post.publishedDate).locale('it').format("MMMM Do, YYYY")}
```
For all methods see Moment.js documentation.
