### ISSUE TITLE
How to add view number for the blog article?

### ISSUE THREAD

**Issue by eimhee** [keystonejs/keystone#1768]
How to add view number for the blog article?

thanks.

**Comment by mldangelo** [comment]
There are lot of different ways to do this. A great easy way would be to modify the keystone post model. You could add a view field to the post model ie: 

```javascript
views: { type: Number, default: 0} 
```
and increment and save the field each time the route is accessed. 

```javascript
       // In routes/views/post.js from keystone generator
	view.on('init', function(next) {

		var q = keystone.list('Post').model.findOne({
			state: 'published',
			slug: locals.filters.post
		}).populate('author categories');

		q.exec(function(err, result) {
		   // The magic part 
		   result.views += 1; 
		   result.save(); 
		   // end magic
		   locals.data.post = result;
		   next(err);
		});
	});
```

and then display the viewcount in your templating language as  #{data.post.views}

or you could any one of a number of services that will track views for you. I hope this helps!

**Comment by morenoh149** [comment]
google analytics is probably better if you want to track visits. I think this question is answered by @mldangelo

**Comment by eimhee** [comment]
yes, it works, thanks mldangelo.
add a view field to the post model,
views: { type: Number, default: 0, hidden:true}

is there performance issue with this solution? 
maybe we can update the view number every minute.

**Comment by webteckie** [comment]
Perhaps the following mongoose api maybe more efficient:  http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate

**Comment by mldangelo** [comment]
@morenoh149 has a great point! I'd definitely recommend adding google analytics to your project. 

@eimhee I wouldn't worry about performance! This is a low overhead solution and shouldn't cause you any problems even if you're handling hundreds of requests per second on a micro ec2 instance.  I think @webteckie's solution is a bit faster and cleaner if you'd like to try that instead. 

Aside: I don't quite understand why you're hiding the view count in the admin UI. You should check out some of the other available flags (ie noedit) here: http://keystonejs.com/docs/database/#fields-options

**Comment by jeffreypriebe** [comment]
You could also query the pageview data for any given page out of Google Analytics and not store the data yourself.
https://developers.google.com/analytics/devguides/reporting/core/v3/common-queries

And cache the API call for a reasonable period of time.
