### ISSUE TITLE
how to add cache to the query?

### ISSUE THREAD

**Issue by eimhee** [keystonejs/keystone#1772]
for example, I want to find the most popular article list, I don't want to query the database for each request, first check the cache if it exist,  and load the data from the cache.
how to do with it? thanks.

<code>
    view.on('init', function (next) {

        var q = Post.model.find()
            .where('state', 'published').sort('-views').populate('author').limit('10');
        
        q.exec(function (err, results) {
            locals.data.hotPosts = results;
            next(err);
        });

    });
</code>

**Comment by mldangelo** [comment]
Hey @eimhee! Unfortunately mongodb doesn't directly cache recent queries. It does keep recently accessed data in memory, so unless you have lots of posts (ie millions) the queries are (typically) efficient enough that caching them shouldn't matter. 

Before you decide to spend time implementing a cache, why not perf test the page you want to cache results for? You could compare running the database query vs defining an object to locals.data.hotPosts 10 times. I don't think you'll notice a meaningful difference in performance. When I experimented with caching results things actually slowed down for me (take this with a grain of salt - I am not a good software engineer).

**Comment by lojack** [comment]
You could do something like this...
```javascript
var hotPosts;

view.on('init', function (next) {
    if(!hotPosts) {
        var q = Post.model.find()
            .where('state', 'published').sort('-views').populate('author').limit('10');
        q.exec(function (err, results) {
            hotPosts = results;
            locals.data.hotPosts = results;
            next(err);
        });
    } else {
        locals.data.hotPosts = hotPosts;
        next(err);
    }
});
```
This would only load hotPosts the first time the view is initialized, essentially caching it. The drawback is that there would be no cache invalidation, and the results would remain in memory for the entire lifespan of the NodeJS process.

**Comment by mldangelo** [comment]
I suppose I should have given you a solution. Building on @lojack's answer and on the assumption that you want the query to expire every minute (from https://github.com/keystonejs/keystone/issues/1768), you could add a time field:

```javascript
var hotPosts;

view.on('init', function (next) {
    if(!hotPosts || Date.now() - hotPosts.createdAt > 1000*60) {
        var q = Post.model.find()
            .where('state', 'published').sort('-views').populate('author').limit('10');
        q.exec(function (err, results) {
            hotPosts = results;
            hotPosts.createdAt = Date.now();
            locals.data.hotPosts = results;
            next(err);
        });
    } else {
        locals.data.hotPosts = hotPosts;
        next();
    }
});
```

**Comment by eimhee** [comment]
thanks, @mldangelo and @lojack , I am a nodejs beginner, it is helpful for me
