### ISSUE TITLE
how to use a cdn to serve static files?

### ISSUE THREAD

**Issue by eimhee** [keystonejs/keystone#1774]
Hi, 
I want to use a static domain to serve all static files,  such image, styles, javascript.

for example,
from
link(href="/styles/site.min.css", rel="stylesheet")

to http://static.xxx.com/styles/site.min.css,

but I don't want to hardcode the domain name, how to do with it?

**Comment by morenoh149** [comment]
most static assets are already served in the `public` directory. Let us know if that doesn't work.

**Comment by eimhee** [comment]
maybe I should change the title to how to use cdn for static files,  CDN('/img/sprite.png')

**Comment by morenoh149** [comment]
@eimhee yes that's completely different. Something like amazon cloudfront or fast.ly?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
