### ISSUE TITLE
Implementing Filter UI Components for Field Types in 0.4

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1776]
Currently WIP, completion of each field type also means checking the back-end implementation of filtering in the FieldType.

- [x] boolean
- [x] code
- [x] color
- [x] date 
- [x] datearray (#2544)
- [x] datetime
- [x] email
- [x] geopoint (#2546)
- [x] html
- [x] key
- [x] location
- [x] markdown
- [x] money (#2480)
- [x] name (#2545)
- [x] number
- [x] numberarray (#2511)
- [x] password
- [x] relationship
- [x] select
- [x] text
- [x] textarea
- [x] textarray (#2510)
- [x] url

----

- [ ] *azurefile*
- [ ] *cloudinaryimage*
- [ ] *cloudinaryimages*
- [ ] *embedly*
- [ ] *localfile*
- [ ] *localfiles*
- [ ] *s3file*

*Not critical for initial release*

**Comment by mxstbr** [comment]
Testing the already done `addFilterToQuery` methods now!

**Comment by mxstbr** [comment]
Have to fix text filtering. The text fields `addFilterToQuery` checks the `filter.mode` to be `startsWith`, but the admin interface sets it to `beginsWith` so that filter doesn't work.

**Comment by mxstbr** [comment]
Also need to improve array filtering, it works for now but only filters for "at least one element in the array does x". It should also be able to filter for "all elements in the array do x" or "y amount of elements in the array do x".

**Comment by mxstbr** [comment]
All done!
