### ISSUE TITLE
Allow multiple instances of keystone

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1777]
Continuation of #1775. Let's track our progress here, @snowkeeper @JedWatson 

> So for the time being all that needs to happen is for instance in `List`, instead of `var keystone=require('../');` we want to make it like this (as you already suggested @jed):

```
  module.exports = function(keystone){
      //do something with    keystone
  } 
```

> My suggestion for now is that we ​_do_​ leave the circular dependencies. We rewrite all the `keystone` dependents to use a closure as above. 

I think these are the files that need to be updated and obviously also **wherever they are `require`d**, not including tests:
- [x] admin/server/api/cloudinary.js 
- [x] admin/server/api/counts.js 
- [x] ~~admin/server/api/download.js~~ ???
- [x] admin/server/api/item/delete.js 
- [x] admin/server/api/item/get.js 
- [x] admin/server/api/list/delete.js 
- [x] admin/server/api/list/download.js 
- [x] admin/server/api/s3.js 
- [x] admin/server/api/session/signin.js 
- [x] admin/server/api/session/signout.js 
- [x] admin/server/routes/home.js 
- [x] admin/server/routes/item.js 
- [x] admin/server/routes/list.js 
- [x] admin/server/routes/signout.js 
- [x] fields/types/cloudinaryimage/CloudinaryImageType.js 
- [x] fields/types/cloudinaryimages/CloudinaryImagesType.js 
- [x] fields/types/location/LocationType.js 
- [x] lib/content/index.js 
- [x] lib/content/page.js 
- [x] lib/email.js 
- [x] lib/list.js 
- [x] lib/list/register.js 
- [x] lib/list/relationship.js 
- [x] lib/schemaPlugins/history.js 
- [x] lib/schemaPlugins/methods/getRelated.js 
- [x] lib/schemaPlugins/track.js 
- [x] lib/session.js 
- [x] lib/updateHandler.js 
- [x] lib/updates.js 
- [x] lib/view.js 

All changes should be pushed to the `prototype` branch. Also, don't forget to rebase on top of master!

IMPORTANT: wherever a file only uses a dependency of keystone, please inject the dependency directly, if possible. E.g. `admin/server/api/counts.js` only uses `keystone.lists`, i.e. I'll be injecting `lists` instead of `keystone`.

**Comment by creynders** [comment]
@JedWatson Any idea where `admin/server/api/download` is used? Can't seem to find any `require` calls or references.

**Comment by snowkeeper** [comment]
I just pushed my changes in #1785

To move through in a timely manner, anything that was a prototype and needed keystone injected got moved to the constructor.  Y'all can clean that up if you want.

In testing I needed a new mongoose instance for each new instance so I changed `this.mongoose = require('mongoose')` to `this.mongoose = new mongoose.Mongoose()`.  Not sure how you want to handle that.

Everything else I have tested works so far.  I included `test/server.all.test.js`.  It creates a new instance for each server.  Creates `httpModel` and `sslModel` in database **keystone** and `socketModel` in database **test-site**.

**Comment by creynders** [comment]
@snowkeeper you're a machine! At a first glance everything looks good. I think the `mongoose` thing is ok, we just have to keep in mind that people need to be able to overwrite the mongoose instance with their own instance, i.e. when we provide a `stop` method I think it would be best if we add a `keystone.vendors.mongoose` which could be used to create new mongoose instances of, or change the line to:
```js
this.set('mongoose', new (this.get('mongoose') || mongoose).Mongoose());
```

**Comment by JedWatson** [comment]
@creynders hmm...

* `keystone.vendor.mongoose`
* `keystone.modules.mongoose`
* `keystone.packages.mongoose`

...?

We could bundle `express` in there as well. I like it, simplifies the new app creation stuff too.

**Comment by creynders** [comment]
I'd go for `vendor` since it's a community default name for 3rd party modules. And yes, let's stuff express in there as well!

**Comment by creynders** [comment]
@JedWatson I manually merged #1785, rebased on top of master and fixed conflicts. I think we need to land this one ASAP, since it'll only become harder and harder to integrate it, due to future conflicts.

**Comment by creynders** [comment]
I'll make the `vendor` stuff a separate PR, once this has landed

**Comment by creynders** [comment]
@JedWatson is there a reason you're withholding this one? Or simply cold feet? ;)

**Comment by mxstbr** [comment]
Did this ever happen? #1785 got closed...

**Comment by JedWatson** [comment]
Unfortunately this got really out of date... I've picked it up in much smaller pieces and am working through the remaining bits. Will tag this issue in my commits, but basically going to do this bit by bit (and ensure everything works with individual commits going forward in master) rather than try and branch then merge a big PR.

**Comment by derekmpeterson** [comment]
@JedWatson Has there been any more progress made on this?

**Comment by gautamsi** [comment]
Keystone 4 is going in maintenance mode. Expect no major change. see #4913 for details.
[Keystone v5](https://github.com/keystonejs/keystone-5) is modular and flexible, see if it helps, if not open issue there.
