### ISSUE TITLE
"First User" app for initialising a Keystone install

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#1782]
The idea here is to create a package that can be added to tutorial and other "getting started" type examples. It's configured with info on the main `User` list and attached into the web server middleware. On start, it check whether any users exist and, if not, serves an interface that lets a someone configure the initial user account.

Basically, similar to the workflow used by Wordpress and similar for initial installs:

![setup5](https://user-images.githubusercontent.com/2416367/66975735-22014480-f0eb-11e9-8951-fc728630a6d6.png)

@JedWatson has ideas about how this would all work.

**Comment by molomby** [comment]
There are obvious security risk in letting an unauthenticated user create accounts. This functionality would inherently circumvent access control.

Maybe there should be a stricter check than just "is the user list empty"? The wizard could be enabled using a specific env var or something..?

**Comment by MadeByMike** [comment]
I'd like this to work in a slightly more generic way than to assume a 'User'. Basically we already have the ability to generate the UI for any list. I think we could use that to create a generic initialise list middleware. 

There are 2 things you might want to do rather than just passing the entire list config:

1. Select fields that users can initialise
1. Specify default values for fields


This should include specifying default values for fields you don't want the user to change.

I'm thinking:

```js
const config = {
  description: 'Welcome to the famous one-minute Keystone List configuration',
  fields:['username', 'email'],
  defaults: { 
     username: "Mike",
     email: "example@example.com",
     hiddenField: 42
}
initialiseList('User', config)
```

**Comment by gautamsi** [comment]
Best would be to check if initial setting is complete in settings, initial thoughts in #1639

See my comments https://github.com/keystonejs/keystone-5/issues/1639#issuecomment-531659814

**Comment by jesstelford** [comment]
The way WordPress _used_ to do it was a file existed on disk which would be looked for. If that file existed, then the installation wasn't setup and the wizard would be triggered. On completion of the wizard, the file is deleted so next time the wizard is skipped.

We could do a similar thing, or maybe invert it to check something in the database in some `meta` list, etc.

**Comment by molomby** [comment]
@jesstelford Yeah something like that. As you imply though, we can't rely on disk and needs to work for clusters of machines.

@gautamsi, I was thinking along the lines of #1639 as well.

We'd probably want to combine all these though, right? Like, the wizard should only appear if a) the user list has no items AND b) the `ENABLE_INITIAL_USER_WIZARD` env var exists AND c) the `INITIAL_USER_WIZARD_RAN_AT` "system setting" is undefined.

I mean, the package should never be included in actual production systems but sooner or later someone will leave it "plugged in". We should be as defensive as is practical, I'd say.

**Comment by molomby** [comment]
@MadeByMike I agree we shouldn't assume the list key or field names, etc.  but I think we _can_ and _should_ assume this will be used to create an "user-equivalent" item. That is, an item that:

* Will be authenticated with a user name and password
* Is being operated by a person in a browser (specifically, _the_ person who is using the wizard)

Once the wizard is competed, the user (physical person sitting at a browser) will be signed into the Admin UI. They can then use the standard interfaces to create other items or update/populate their own user item as they see fit. This is really intended as a **bootstrap that gets the first admin user signed into the Admin UI of an otherwise completely empty KS install**.

As such, I don't think we need (or want) to support anything other than the username/identity field and secret/password fields configurable for the `PasswordAuthStrategy`.

Off the top of my head, I imagined usage would go something like this...

```js
const config = {
   // Mirroring the `PasswordAuthStrategy` config names?
   list: 'User',
   identityField: 'email',
   secretField: 'password',

   // Text or markdown?
   intro: 'Welcome to the famous one-minute Keystone List configuration',

   // Values added to the item created
   // Must include whatever is needed to give them access to the Admin UI
   // Could also be used in the form I suppose? Less important though
   itemData: { 
      email: "example@example.com",
      isAdmin: true,
      emailAddressConfirmed: true,
      hiddenField: 42,
      // Etc..
   },
};

// When setting up the webserver
configureInitialWizard(expressApp, config);
```

Does that resonate with anyone or am I on the wrong track here?

**Comment by gautamsi** [comment]
Should we use json file based (initial) config or meta list? 

Advantage of config file is that we can change settings and restart server. Also possible to inject/install plugins which can be loaded in production and not necessarily included in the initial development

**Comment by dcousens** [comment]
Temporary password via `process.ENV.SETUP_PASSWORD` to _then_ initialize the administrator account.

After that you can remove it from your `ENV`;  and if you don't,  **the program aborts**.
