### ISSUE TITLE
Review .eslintrc

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1797]
I've noticed a lot of things that should be considered warnings or errors are passing our linter. The configuration needs to be reviewed, may be out of date given updates to ESLint (and the React plugin)

**Comment by morenoh149** [comment]
https://github.com/keystonejs/keystone/pull/1781 similar

**Comment by morenoh149** [comment]
I took some time to review it https://github.com/keystonejs/keystone/blob/master/.eslintrc One thing I'll note is if a rule is not being used (value `0`) then it should be omitted from the ruleset altogether.

My suggestion is to review all the recommended rules [here](http://eslint.org/docs/rules/) and see which of those you like.

**Comment by JedWatson** [comment]
I've made some major updates and fixed a lot of issues in the codebase, including pulling a lot of rules from `standard`. Also updated some old `jslint` flags in the code.

.eslint is much closer to "good", I've also got a wishlist of rules that I want to add next but will require code refactoring to pass:

```
* `"brace-style": 2,`
* `"dot-notation": 2,`
* `"eqeqeq": [2, "allow-null"],`
* `"guard-for-in": 1,`
* `"indent": [2, "tab"],`
* `"key-spacing": 2,`
* `"new-cap": 2,`
* `"no-undef": 2,`
* `"no-unused-vars": [2, { "vars": "all", "args": "none" }],`
* `"no-unneeded-ternary": [2, { "defaultAssignment": false }],`
* `"one-var": [2, { "initialized": "never" }],`
* `"operator-linebreak": [2, "before"],`
* `"prefer-const": 2,`
* `"space-in-parens": 2,`
* `"spaced-comment": 2,`
* `"yoda": 2,`
```

These can only be added once the codebase is fixed and they pass, otherwise we'll break our tests on PRs and commits.

If anybody has a chance to take any of these on and PR them shout out here and let us know, otherwise I'll work through the rest asap so we can close this.

Feedback on the rules I've gone with is also welcome!

**Comment by karlbright** [comment]
- [ ] (dot-notation)[http://eslint.org/docs/rules/dot-notation]
- [ ] (eqeqeq)[http://eslint.org/docs/rules/eqeqeq]
- [ ] (guard-for-in)[http://eslint.org/docs/rules/guard-for-in]
- [ ] (indent)[http://eslint.org/docs/rules/indent]
- [ ] (key-spacing)[http://eslint.org/docs/rules/key-spacing]
- [ ] (new-cap)[http://eslint.org/docs/rules/new-cap]
- [ ] (no-undef)[http://eslint.org/docs/rules/no-undef]
- [ ] (no-unused-vars)[http://eslint.org/docs/rules/no-unused-vars]
- [ ] (no-unneeded-ternary)[http://eslint.org/docs/rules/no-unneeded-ternary]
- [ ] (one-var)[http://eslint.org/docs/rules/one-var]
- [ ] (operator-linebreak)[http://eslint.org/docs/rules/operator-linebreak]
- [ ] (prefer-const)[http://eslint.org/docs/rules/prefer-const]
- [ ] (space-in-parens)[http://eslint.org/docs/rules/space-in-parens]
- [ ] (spaced-comment)[http://eslint.org/docs/rules/spaced-comment]
- [ ] (yoda)[http://eslint.org/docs/rules/yoda]

**Comment by karlbright** [comment]
### ESlint Documentation

- [dot-notation](http://eslint.org/docs/rules/dot-notation)
- [eqeqeq](http://eslint.org/docs/rules/eqeqeq)
- [guard-for-in](http://eslint.org/docs/rules/guard-for-in)
- [indent](http://eslint.org/docs/rules/indent)
- [key-spacing](http://eslint.org/docs/rules/key-spacing)
- [new-cap](http://eslint.org/docs/rules/new-cap)
- [no-undef](http://eslint.org/docs/rules/no-undef)
- [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars)
- [no-unneeded-ternary](http://eslint.org/docs/rules/no-unneeded-ternary)
- [one-var](http://eslint.org/docs/rules/one-var)
- [operator-linebreak](http://eslint.org/docs/rules/operator-linebreak)
- [prefer-const](http://eslint.org/docs/rules/prefer-const)
- [space-in-parens](http://eslint.org/docs/rules/space-in-parens)
- [spaced-comment](http://eslint.org/docs/rules/spaced-comment)
- [yoda](http://eslint.org/docs/rules/yoda)

**Comment by ericelliott** [comment]
:+1:

**Comment by webteckie** [comment]
What's the correct linebreak format for keystone?  I enabled the latest .eslintrc in Webstorm and complains about the following for any file I open:
```
ESLint: Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
```

**Comment by LennyBoyatzis** [comment]
Hey guys, the rule "brace-style": 2 doesn't permit start and end braces being on the same line i.e.  `props.onClick = () => { this.toggleCreate(true); };` creates a linter error.
We have about 80 instances of this throughout the code. To prevent this rule from picking up such instances I can add config option `{ "allowSingleLine": true }`. Is this something we would want to do? Alternatively I could go ahead and remove the curly braces or place the statement on a separate line. Let me know what you think!

**Comment by mxstbr** [comment]
@LennyBoyatzis I think `{ "allowSingleLine": true }` makes sense in that case, I personally prefer it.

**Comment by JedWatson** [comment]
This is good to close now! we're all linted up.
