### ISSUE TITLE
Markdown Type: How to limit to safe tags only?

### ISSUE THREAD

**Issue by fridays** [keystonejs/keystone#1798]
Is there a way to allow only certain tags to be used in a Markdown field?

I would like to allow users to use common tags like `a` but for example not `script`.

Thank you!

Edit: Looks like [this is where](https://github.com/keystonejs/keystone/blob/v0.3.x/fields/types/markdown/MarkdownType.js#L66) keystone transforms markdown input to html and I would like to enable the `sanitize` option from [marked](https://github.com/chjj/marked) as described in their readme.

**Comment by creynders** [comment]
@fridays allowing the sanitation of markdown would be really useful, feel free to open a PR for passing options to `marked`.
