### ISSUE TITLE
Multiple Update/ Delete not working

### ISSUE THREAD

**Issue by terenzeyuen** [keystonejs/keystone#1810]
![screen shot 2015-11-14 at 19 30 54](https://cloud.githubusercontent.com/assets/2553680/11165423/42af221e-8b06-11e5-9755-97a2c4ca81b9.png)

These doesn't seem to be working yet – a known todo?

**Comment by snowkeeper** [comment]
Yes, saw this yesterday...
 https://github.com/keystonejs/keystone/blob/master/admin/client/views/list.js#L110-L122

**Comment by terenzeyuen** [comment]
Ok cool, how can we contribute.

**Comment by morenoh149** [comment]
Fixed by #1819

**Comment by terenzeyuen** [comment]
Massupdate still doesnt seem to work?

**Comment by morenoh149** [comment]
@terenzeyuen are you on master?

**Comment by snowkeeper** [comment]
Management mode is currently only available when running in dev mode....

KEYSTONE_DEV=true node your-startfile.js

**Comment by terenzeyuen** [comment]
Ok let me try

**Comment by terenzeyuen** [comment]
Hm it says this in coode though:
console.log('Update ALL the things!');

**Comment by terenzeyuen** [comment]
Sorry I meant mass update and not mass delete..

**Comment by twlamb** [comment]
What version of keystone do you have to have to make this work? I've tried running 

```
KEYSTONE_DEV=true node your-startfile.js
```

And I don't see any difference in the Admin UI
