### ISSUE TITLE
Time Type for fields

### ISSUE THREAD

**Issue by ianaya89** [keystonejs/keystone#1812]
Hi There,

I am not it already exists but I can not find any information about that. Would be great if you can include a Time type for Keystone fields where you can set for specific time in hours and minutes without any specific date.

Thanks!

**Comment by snowkeeper** [comment]
Included in #1826.  The proposed **datetime** option is `onlyTime`.

**note** - A date will **always** be included as this is a **datetime** field, and will be set as the date the time was initially created.  We just ignore the date and use the time only.
#### field
![datetime](https://cloud.githubusercontent.com/assets/6615106/11222537/f61629ae-8d38-11e5-929e-151d93cb2fd3.png)
#### ui filter
![onlytime](https://cloud.githubusercontent.com/assets/6615106/11222564/28a4f224-8d39-11e5-9d7f-24584e8e46ae.png)

**Comment by ttsirkia** [comment]
Duplicate with #1171
