### ISSUE TITLE
Modal footer covers select

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#1814]
When select field is used on modal form, the footer of the form covers select field options.
To fix that behavior I need to change z-index from 1 to 2 on selector .Select-menu-outer in keystone.min.css
But I can't find this selector :( It is only in minified version.

**Comment by jonathanp** [comment]
Nice find @w01fgang! Since that style rule comes from the [`react-select`](https://github.com/JedWatson/react-select) component I added an override for it in `admin/public/styles/keystone/base.less`, see #1818
