### ISSUE TITLE
Express routes with admin-ui

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#1818]
BUG report:

express routes are not working well when using custom server example with admin ui. 

following error is thrown in every non keystone routes
`UnhandledPromiseRejectionWarning: Error: No default engine was specified and no extension was provided.`

I have already registered the `view engine` and `views` using `app.set(......)`. 

if I remove `admin-ui` from exported app (same as custom server example, no admin-ui use in custom server example) it works fine.

I can also change the order and add express routes first then `app.use` keystone middlewares, it then works but `/admin` url no longer works.

this is critical as it breaks keystone contrib `views` package.

**Comment by MadeByMike** [comment]
@gautamsi have you got an example I can test? I'm not sure I understand which page you're getting that error for. Is it an adminUI page or a custom app page?

**Comment by gautamsi** [comment]
checkout this branch https://github.com/keystonejs-contrib/keystonejs-contrib/tree/upgrade-to-keystone-alpha-16 

run `yarn dev` inside `examples/blog-view` (create .env from example there)

you will see the error in console. 

when you move line `app.use(middlewares)` to just before `app.listen` this is no longer an issue but you can not open admin console and the `app-static` path do not work

**Comment by timleslie** [comment]
@gautamsi Just following up on this, is there anything left to do here, or can we close this issue now?

**Comment by gautamsi** [comment]
this one is fixed partially in https://github.com/keystonejs/keystone/pull/2202

Someone has to use [Custom Apps](https://www.keystonejs.com/guides/apps#custom-apps) to get view engine and templates with ExpressJs
