### ISSUE TITLE
📌 Is Keystone 5 stable to be used in production? (Yes!)

### ISSUE THREAD

**Issue by GasimGasimzada** [keystonejs/keystone#1820]
I am very confused by what is going on in Keystone 5. Should I use this package or use Keystone 4? The homepage shows Keystone 5 as the latest version while the prefix when installing packages is `@keystone-alpha`. Is this a usable version? Currently, some of the things in docs do not match with usage and I am going through source code to understand what is going on.

**Comment by MadeByMike** [comment]
@GasimGasimzada **yes** Keystone 5 is absolutely stable, ready to use and is already working in production for a number of large scale applications. The `keystone-alpha` label is about to be removed. I'll share the announcement from the Slack channel here incase anyone else finds this:

---

Hi everyone, some exciting news today! \o/ Very shortly we will be removing the alpha label from Keystone 5.

To avoid confusion we are re-naming the existing keystone package to keystone-classic and the @keystone-alpha/* packages will be renamed to @keystone/*.

What do you have to do? Nothing. If you don't do anything, everything will work the same as always. However next time you update, you should be aware that there is no direct upgrade path from Keystone 4 to Keystone 5. You can switch to using keystone-classic and continue to receive community support and patches. It will remain free OSS forever.

For the core team, going forward the focus of our development efforts will be on Keystone 5 and future versions.

Whether you choose to stick with keystone-classic or re-platform applications to work with Keystone 5, we will continue to support you as best we can. We also want to thank you for being a part of this community and all the contributions and support we've had for Keystone over the years. We hope this continues with the next version of Keystone.

After many months of working hard in the open and with multiple successful high-traffic deployments in the wild, we're really excited to officially release Keystone 5!

---

> We were hoping to complete work on the transition yesterday but hit a small snag with publishing to npm. You can expect updates today. I'll post them here too.

Regarding docs, there is definitely more work to do but what's there should be correct. Can you point me to anything that is not matching usage and I'll get on it right now!

**Comment by jesstelford** [comment]
@GasimGasimzada you've caught us in a transition period! We're currently moving the packages from `@keystone-alpha` -> `@keystonejs`. We prematurely updated the docs before the packages were actually published (my bad!).

I'm busy getting those packages released right now, so everything should line up very soon 👍 

Sorry for the confusion.

**Comment by jesstelford** [comment]
@GasimGasimzada the `@keystonejs` packages have all been published, so they should now match the documentation.

Try again and as you're going, please feel free to open issues here with anything you find that might need clarification <3

**Comment by GasimGasimzada** [comment]
Great! I updated all the packages to @keystonejs org. No more confusion on that part :)

**Comment by tobydeh** [comment]
Where can i find documentation on upgrading from v4? 😄

**Comment by MadeByMike** [comment]
Here: https://v4.keystonejs.com/documentation

It's also linked to from the v5 site and github

**Comment by MadeByMike** [comment]
I'm going t

**Comment by tobydeh** [comment]
@MadeByMike sorry, im having trouble finding the docs on upgrading from v4 to v5 - could you provide a link? Thanks.

**Comment by gautamsi** [comment]
@tobydeh there is no migration path, you have to rewrite the entire application if you want to take full advantage of keystone 5. 

however I worked on a package to support keystone 4 like `View` which may help reuse the template systems but that is also stuck due to some bug, see this - https://github.com/keystonejs-contrib/keystonejs-contrib
