### ISSUE TITLE
File upload thumbnails not displaying in AdminUI

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#1823]
# Bug report

## Describe the bug

When uploading a file with the File field (I'm using the LocalFileAdapter), the thumbnail will show up in the Create dialog, but not when viewing the entry in the list (see below). I have both `src` and `path` properties of the file adapter set to the same place:

```js
const fileAdapter = new LocalFileAdapter({
  src: './files',
  path: './files',
});

keystone.createList('FileTest', {
  fields: {
    name: { type: Text },
    file: { type: File, adapter: fileAdapter },
  }
});
```
A look in Chrome seems to indicate it's trying to fetch the files from `localhost:3000/admin/files` instead of `localhost:3000/files` (where they actually are). Not sure how to fix this one.

## Screenshots
![image](https://user-images.githubusercontent.com/3558659/67446102-25e91580-f65b-11e9-8cb7-ef5e492c5303.png)

![image](https://user-images.githubusercontent.com/3558659/67446180-6fd1fb80-f65b-11e9-9215-de541c225787.png)

## System information

- OS: Windows 10 1903
- Browser: Chrome 78

**Comment by MadeByMike** [comment]
@Vultraz what happens if you change the path to `/files`? `./files` would indicate a relative path on the web.

**Comment by gautamsi** [comment]
I think the path should be `files` and `app-static` configured with same path and src.

**Comment by Vultraz** [comment]
Ok, with the absolute path (`/files`) it *does* look in `localhost:3000/files` but it still returns a 404.
![image](https://user-images.githubusercontent.com/3558659/67448687-7a908e80-f663-11e9-83c7-bc1bdbc8f2b0.png)

(not sure if the `text/html` bit is relevant).

When trying to visit the path in the browser you get:
> Cannot GET /files/5db06df14660714c0c734571-bigthonker.jpg

And I have confirmed the file exists in the filesystem at that path.

**Comment by gautamsi** [comment]
You also need the `@keystonejs/app-static` or express.static path configured

**Comment by Vultraz** [comment]
Ok, this just gets weirder and weirder! When `src` is set to a *relative* path (i.e. `./files`), that folder is created at server toplevel (`/`). For me that would be `C:\Users\exodi\Documents\testapp2\files`.

But if it an absolute path (i.e. `/files`), the folder is created at OS root - `C:\files`! There's literally a toplevel folder in `C:\` with files from when I was testing with an absolute `src` path 😱

**Comment by Vultraz** [comment]
@MadeByMike I think I've tracked down the problem. The admin UI's `createDevMiddleware` function doesn't include the `express.static` middleware. Adding `express.static('/')` to the returned list makes the thumbnails show up correctly again.

**Comment by MadeByMike** [comment]
This is interesting.... the reason make sense. We can't know if the path that the user nominates for images is a part of a web server set-up for their front-end application, or not. You would assume it always is but I don't want to make that assumption. 

I also don't want to rely on the user to set-up a web server to serve these images in the admin UI as it currently requires.

I don't want to set-up a static server in `createDevMiddleware` as this have privacy implications. What if for example the user intends to serve these images behind a paywall or for authenticated users only. We might be leaking private data if we allow a static server.

The best way to solve this is to create a route in the AdminUI that serves the images (perhaps by id) not a static route, and one that only works when for authed users.

**Comment by MadeByMike** [comment]
> But if it an absolute path (i.e. /files), the folder is created at partition root - C:\files! There's literally a toplevel folder in C:\ with files from when I was testing with an absolute src path 😱

-- This is actually ok, the user may want to store images outside the web root. Perhaps they have a different web server running on another path. That is up to them, but this is exactly why we cannot simply create a static server for them.

**Comment by maheraldous** [comment]
Anyone found a solution about this?

**Comment by jabusir** [comment]
Facing this issue. Still haven't found a solution

**Comment by jabusir** [comment]
> Anyone found a solution about this? @Vultraz

Did you ??

**Comment by HostenMarijn** [comment]
Hey guys,

I've been setting up a Keystone + React project and bumped into the same issue.
Found a solution that works with my setup.

**Make sure that the StaticApp src starts the same as the FileAdapter src** (in my case ../my-app)

Folders: 
 - my-app
    - public/files/1234image.png
    - build
    - ... other CreateReactApp things

 - server
    - lists/product.js
    - index.js
    - ... other KeyStone things

_index.js_
```
new StaticApp({
      path: '/',
      src: '../my-app/build',
      fallback: '../my-app/build/index.html'
    })
```

_product.js_
```
const fileAdapter = new LocalFileAdapter({
  src: '../my-app/public/files',
  path: '/files'
});
```

Hope this helps anybody!

**Comment by bladey** [comment]
Hi all,

Thank you for posting your resolution @HostenMarijn, I hope it helps others who are facing the same issue.

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!
