### ISSUE TITLE
Improve startup instructions

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#1824]
If I run 

```
yarn create keystone-app my-app
```

and then follow the instructions, I get to this:

```
  Next steps:

  - Edit my-app/index.js to customize your app.
  - Open the Admin UI (http://localhost:3000/admin)
  - Read the docs (https://keystonejs.com)
  - Star KeystoneJS on GitHub (https://github.com/keystonejs/keystone-5)
```

It suggests that I can go directly to `http://localhost:3000/admin`, however this is not the case. We need to run `yarn build && yarn start` before that is possible. We should include something to that effect in these instructions.

**Comment by timleslie** [comment]
Or maybe just `yarn dev`?

**Comment by jesstelford** [comment]
`yarn dev` is better as it puts them in development mode and only requires a single command.

Also need to mention `cd my-app`
