### ISSUE TITLE
Node-Sass / Stylus + Keystone?

### ISSUE THREAD

**Issue by avramvb** [keystonejs/keystone#183]
Has anyone experimented with a fork of keystone that uses node-sass instead of less-middleware? how could someone make that switch?

**Comment by J4G-** [comment]
Updates on Stylus?

**Comment by medv** [comment]
This is a little bit of a tangent, but I'd appreciate if someone can drop a line on this. With less-middleware in keystone, what would be the preferred way to integrate something like css-autoprefixer?

**Comment by prog666** [comment]
i'd like to participate, if someone helps me, because only way of using stylus i know is to compile it to css with gulp in development, and also have no idea about yo generator :(

**Comment by morenoh149** [comment]
@prog666 please email me your email or post it here (if you're comfortable). I'll invite you to the slack.

**Comment by prog666** [comment]
gnomdan@yandex.ru

**Comment by morenoh149** [comment]
So has anyone here actually gotten stylus working with keystone? if so please share a gist or repo. Once we confirm that it's possible we can work on getting it working from the generator over at https://github.com/keystonejs/generator-keystone/issues/134

**Comment by morenoh149** [comment]
I'm going to close this issue as it's clear we can get keystone to work well with both sass and stylus. It's just a matter of adding those as working options in the generator.
