### ISSUE TITLE
npm packages don't link back to monorepo

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1831]
The `repo` link in packages are missing, so there's no link back to the repo from npm:

![Screen Shot 2019-10-25 at 10 50 45 am](https://user-images.githubusercontent.com/612020/67533353-6016ed80-f715-11e9-933b-cbc3cba4767a.png)

**Comment by KuznetcovDima** [comment]
Same problem, can't install

**Comment by dhuang612** [comment]
I can work on this

**Comment by MadeByMike** [comment]
@dhuang612 PRs welcome - let me know if you need any help!

**Comment by dhuang612** [comment]
created PR #1859 for this issue

**Comment by dhuang612** [comment]
Hi created pr #1866 closed #1859 
Please let me know if anything else needs to be changed
