### ISSUE TITLE
Relationship Field suggest by field other name

### ISSUE THREAD

**Issue by b96705008** [keystonejs/keystone#1834]
<img width="508" alt="screen shot 2015-11-18 at 1 13 50 pm" src="https://cloud.githubusercontent.com/assets/1639087/11233237/6076d24a-8df6-11e5-9ad8-6241d62fa574.png">

I have a model and one of the relationship field is related to User model.
User model has a name field, and it can be showed and suggested when keyin value in the related input on other models' create data form.
However, I wanna be suggested and search value other than name, for example: email.
Is there any other method can solve it?

**Comment by jjhesk** [comment]
+1

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
