### ISSUE TITLE
Can I use custom id values in Keystone 5

### ISSUE THREAD

**Issue by KuznetcovDima** [keystonejs/keystone#1834]
# Can i use my own _id values while create new items?

I use ERP system with API which takes to me some documents, where id stores in UUID format, for example `4a7c55d1-d235-11e9-0a80-01800012e538`. This document has a lot of references and links between themselves. And i want download this structure for operations, BI, etc, but save references between entities. I tryed use Keystonejs 4, but it impossible to manage items _id. So, i can write exist id to another field (like `outer_id`), but it brakes Relationships, and get a lot troubles with sync down.

Can i use Keystone 5 and create items with my own _id's?

Is there solutions, which can help with one-way-sync existing database to Keystone?

> Sorry for my bad English and "spasibo" =)

**Comment by jesstelford** [comment]
You can specify a custom `id` field, but I don't think you'll be able to set them from within `createX` mutations 🤔 

The config for an `id` field would look something like: https://github.com/keystonejs/keystone/blob/master/packages/fields/src/types/Uuid/index.js#L21-L24

@molomby might know more about how to set a custom id if at all possible.

**Comment by molomby** [comment]
Yep, you can configure the `id` field however you want; the `id` fields added by Keystone use the standard Keystone field types. I think the only limitation is the name -- the config needs to be added to the Keystone list as `id`; if there's no `id` field specified, the adapter will add one with the default config. (If you're running on Mongoose this maps down internally to `_id` which is fine; it's just a quirk of Mongo.)

There's a PR from a few months ago with [examples using the MongoID field type](https://github.com/keystonejs/keystone/pull/1396). If you're after UUIDs, you can use the [Keystone `Uuid` field type](https://github.com/keystonejs/keystone/tree/master/packages/fields/src/types/Uuid)...

```js
keystone.createList('Todo', {
   fields: {
      id: { type: Uuid },
      // ...
   },
});
```

The problem with this ^^^ is the field doesn't configure any default values so you'll get errors _unless you specify a unique `id` whenever you inset an item_. (@KuznetcovDima, based on your description, this might actually be ok?)

Building on the above, you could generate default values in Keystone by supplying a `defaultValue` function; using, for example, the [`uuid` package](https://www.npmjs.com/package/uuid):

```js
const uuidv4 = require('uuid/v4');

keystone.createList('Todo', {
   fields: {
      id: { type: Uuid, defaultValue: uuidv4 },
      // ...
   },
});
```

This is usually how you'd use the `Uuid` type if you're running on the **Mongoose** adapter.

_However_, be aware that this solution will only add IDs _for items inserted through Keystone_. If 
you're using a relational DB or other systems are working with your DB directly, you'll usually want items (aka. records) to be assigned IDs _regardless_ of how they're inserted. In this case you want to configure a default on the DB schema itself, not just in Keystone.

We can achieve this using the `knexOptions` config option and `knex.raw()` but the specifics differ depending on your DB platform. For example, if you're using the Knex adapter on **Postgres**, you might want something like this:

```js
keystone.createList('Todo', {
   fields: {
      id: { type: Uuid, knexOptions: { defaultTo: knex => knex.raw('gen_random_uuid()') } },
      // ...
   },
});
```

This adds a default to the column in the DB schema using [the `gen_random_uuid()` function](https://www.postgresql.org/docs/current/pgcrypto.html#id-1.11.7.34.9) (supplied by the `pgcrypto` module). You'll need to run the command `CREATE EXTENSION pgcrypto;` for this to work. ([`uuid_generate_v4 ()` from the `uuid-ossp` module](https://www.postgresql.org/docs/current/uuid-ossp.html#id-1.11.7.53.4) would also work.)

If you're using the Knex adapter on **MySQL**, you'd use [it's `uuid()` function](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid) instead:

```js
keystone.createList('Todo', {
   fields: {
      id: { type: Uuid, knexOptions: { defaultTo: knex => knex.raw('uuid()') } },
      // ...
   },
});
```

Other DB platforms should have equivalent functionality that can be utilise with the same pattern.

Regardless of if or how you configure these default functions (ie. using `defaultValue` or on the DB schema), you can always specify a known UUID value when creating items; the default will only be used when no `id` value is supplied.

**Comment by KuznetcovDima** [comment]
@molomby, thanks for good answer, but i have a trouble with id.
Me schema looks like:
```
const Customerorder = {
  fields: {
    id: {
      type: Uuid,
      defaultValue: () => {
        let uuid = RandomUuid();
        console.log('uuid', uuid);
        return uuid;
      },
    },
    name: {
      type: Text,
    },
  },
  access: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
};
```

And when i add new item through admin UI, i see in console.log(…) correct generated uuid and save item success nofitycation. But in items list (UI) i see, than id different:
![image](https://user-images.githubusercontent.com/47210720/71473320-86c1d500-27e7-11ea-99b3-16bda46f4198.png)
And if i try click label i get blank page after GraphQL request
```
{
  Customerorder(where: {id: "5e048c7db01b951606f9e3b4"}) {
    _label_
    id
    name
    __typename
  }
}
```
response: 
```
{
	"errors": [
	{
		"message": "You do not have access to this resource",
		"name": "AccessDeniedError",
		"time_thrown": "2019-12-26T10:57:30.772Z",
		"data":
		{
			"type": "query",
			"target": "Customerorder"
		},
		"path": ["Customerorder"],
		"uid": "ck4mm4z2s00010yvk3u6n22mp"
	}],
	"data":
	{
		"Customerorder": null
	},
	"extensions":
	{
		"tracing":
		{
			"version": 1,
			"startTime": "2019-12-26T10:57:30.767Z",
			"endTime": "2019-12-26T10:57:30.772Z",
			"duration": 5354527,
			"execution":
			{
				"resolvers": [
				{
					"path": ["Customerorder"],
					"parentType": "Query",
					"fieldName": "Customerorder",
					"returnType": "Customerorder",
					"startOffset": 1571800,
					"duration": 3431570
				}]
			}
		}
	}
}
```

**Comment by ClientsideDesign** [comment]
Is it possible to use an arbitrary text string (which I understand would be required and need to be unique) as the ID for a list. E.g. if I had a list of customers, could I use their email addresses as their ID? I imagine the list setup would look something like:

    id: {
        type: Text,
        isRequired: true,
        defaultValue: ({ context, originalInput }) => {
            return originalInput.email;
        },
    },

This would simplify `getItem` requests for that list.

Thanks - love your work!

**Comment by MurzNN** [comment]
Got the similar problem with setting custom ID for items in #4824 
@molomby @KuznetcovDima - did you find the solution for this problem, to make `createX` mutations work properly when passing ID value to them?

**Comment by MurzNN** [comment]
Seems this is only mongodb-related, so I filled a separate issue about this problem: https://github.com/keystonejs/keystone/issues/4871

**Comment by gautamsi** [comment]
with mongo I don't think you can override `_id` value to non ObjectId type. What I would want with this that `id` field gets mapped to some other field in mongo instead of `_id` and make use of that field for all purpose. 

I have `sku` in ecommerce operation to be unique but I always have to run `allSku(where: {sku: 2345})` to get single item array in query rather than `Sku(where: {sku: 12345})` to get the sku object itself.

**Comment by MurzNN** [comment]
MongoID works well with non-`ObjectId` `_id` field types using clean Mongoose and custom code, so there is no limitation on Mongo side.
Here is my modified "todo" demo of Keystone, which works well with String `_id` field type: https://github.com/keystonejs/keystone/compare/master...MurzNN:todo-custom-ids?expand=1

The only problem now is `deleteMany` mutation, that don't do conversion of `id` to `_id at now:
```
mutation deleteMany($ids: [ID!]) {
  deleteTodos(ids: $ids) {
    id
  }
}
```
But I try to solve this too. Will make a PR when I solve all problems.

**Comment by gautamsi** [comment]
it is very hard to get this built in to Keystone, check with @timleslie or others if this is in their roadmap. 

Also current version of KeystoneJs is going maintenance mode soon https://next.keystonejs.com/roadmap#project-status

**Comment by MurzNN** [comment]
Thanks for clarification, seems in Keystone-next custom id field type support is much better, regarding to https://next.keystonejs.com/apis/schema#id-field
So I will try convert my project to Keystone-next and make PRs to that branch, if something works wrong. Only thing that I afraid, is that Keystone-next is in very early development stages, so API can be changed in release...

**Comment by MurzNN** [comment]
I try same thing on last keystone-next version and this issue is reproduced with mongoose adapter, with knex all works well via filling `idField`, here is example of implementing Text id field for `examples-next/todo` demo:
```js
  Todo: list({
    ui: {
      listView: {
        initialColumns: ['label', 'isComplete', 'createdAt', 'createdBy', 'updatedAt', 'updatedBy'],
      },
    },
    fields: {
      label: text({ isRequired: true }),
      isComplete: checkbox(),
      assignedTo: relationship({ ref: 'User.tasks' }),
      finishBy: timestamp(),
      ...trackingFields,
    },
    idField: text({
      access: {
        public: {
          create: true,
        }
      },
      ui: {
        createView: { fieldMode: 'edit' },
        itemView: { fieldMode: 'read' },
      },
    }),
  }),
```

**Comment by bladey** [comment]
Hi all,

Thank you everyone who contributed to this issue. As mentioned by @gautamsi and @MurzNN Keystone 5 is now in a maintenance phase, we'll take this information on-board as we build the new version.

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!

**Comment by MurzNN** [comment]
I have created a PR that implement this feature for keystone-5 and keystone-next too, it is here: https://github.com/keystonejs/keystone/pull/4826 and it works well on my two projects.
