### ISSUE TITLE
how to query by object id?

### ISSUE THREAD

**Issue by eimhee** [keystonejs/keystone#1836]
how to query by object id? the below code doesn't work. 
```
                  Post.model.findOne()
                        .where('id', highlight.entity.id)
                        .populate('author')
                        .exec(function(err, post) {

                            if (err) return res.err(err);
                            if (!post) return res.notfound('Post not found');


                            console.log(post);

                        });
```

**Comment by creynders** [comment]
Not sure whether that's the problem, but have you tried:

```
...
.where({ id: higlight.entity.id})
...
```
? According to the docs you should pass it an object or a mongoose query.

**Comment by JedWatson** [comment]
The actual path used for the ID in MongoDB is `_id`, so for the above query to work you'd need:

`.where('_id', highlight.entity.id)`

or in @creynders's example, which is equivalent:

`.where({ _id: higlight.entity.id })`

There's a shorthand method available that's a bit neater:

`Post.model.findById(highlight.entity.id)`

This returns a query, the same as `findOne()`
