### ISSUE TITLE
Secure Keystone API using bearer auth

### ISSUE THREAD

**Issue by ytzvan** [keystonejs/keystone#1837]
Hello, I'm thinking in migrate an existing Express project to Keystone, but I have a mobile app which consumes the REST API, currently I'm using bearer auth from my mobile app. Keystone includes Bearer auth ? Or I need to implement it manually using passport ? Any thoughts ? Thanks.

**Comment by brianjd** [comment]
Hi @ytzvan ,

You may want to start off by reviewing as a starting point: 

https://github.com/JedWatson/sydjs-site/tree/master/routes/auth

You can go the full blown passport route, or you can create simple middleware to look up/validate tokens and apply that to the necessary routes.
