### ISSUE TITLE
[0.4] Filtering needs to clear pagination

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1839]
Scenario:

* There are 120 items in a list. Go to page 2.
* Apply a filter that returns 80 results. The UI will say that there are no visible items, because there is only one page of results.

Simple fix is to reset pagination when filters are applied, we could get fancy and try and retain page selection when filters change but it's potentially complex and probably not really that useful anyway.

**Comment by jonathanp** [comment]
I agree, the expected behaviour is to reset the pagination when filters are applied.

**Comment by JedWatson** [comment]
Fixed!
