### ISSUE TITLE
Update range_check dependency

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1842]
The [`range_check`](https://github.com/keverw/range_check) package has been rewritten and is much nicer now, but has some breaking changes and will need updates to https://github.com/keystonejs/keystone/blob/master/lib/security/ipRangeRestrict.js

I suspect we can fairly significantly reduce the code in that file using the built-in validation features of range_check.

**Comment by JedWatson** [comment]
@JohnnyEstilles do you have a bot or something that keeps adding the "in progress" label to PRs and issues?

**Comment by morenoh149** [comment]
pretty sure that's from waffle.io https://waffle.io/keystonejs/keystone/settings/columns
