### ISSUE TITLE
Non-List Admin Page Items

### ISSUE THREAD

**Issue by GHowlett** [keystonejs/keystone#1845]
Is there a way to create a keystone model that's meant to have only one instance (for example to hold the textual content of a homepage) and can be edited through the admin page? It seems that only collections of models are supported, which doesn't make sense for such a use case.

If not, I would imagine it could be implemented by having an internal schema-less collection that holds each of these single-instance documents and associates them with a schema meant for producing an admin interface (not for validating documents).

**Comment by creynders** [comment]
Closing this as duplicate of #1522
