### ISSUE TITLE
File Limit and body parser

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#1846]
Do I have to add body-parser manually before using set file limit? Thanks.

**Comment by morenoh149** [comment]
looks like someone already thought of exposing that as a keystone option https://github.com/keystonejs/keystone/blob/a146e39f4d44d32bcd0d912380225ff97a1d8981/server/bindBodyParser.js#L8

Please update the documentation so this would have been more obvious for future users.
