### ISSUE TITLE
Using Social Media to login

### ISSUE THREAD

**Issue by rinku9900** [keystonejs/keystone#1848]
@JedWatson I want to use social media such as Facebook, Twitter, etc to authenticate the user to use my Keystone.js application. I don't want to store the FB or Twitter information in my USER model or in database. How can i achieve this functionality in my application? I also using passport-facebook Strategy to authenticate the user. I tried to follow the example of Sydjs site but it store the social media information in the mongodb. Any help would be appreciated.

**Comment by jossmac** [comment]
Hi @rinku9900,

Apart from the SydJS implementation this isn't really a Keystone concern, so I'll close the issue

Sounds like Local Storage might be what you're looking for, check out this MDN write up https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

Also you could try asking over at the Google Group, someone may have done something similar https://groups.google.com/forum/#!forum/keystonejs
