### ISSUE TITLE
Plugin Architecture

### ISSUE THREAD

**Issue by dboskovic** [keystonejs/keystone#185]
@JedWatson @bladey @JossMackison

I'm absolutely loving working with Keystone. I'd be very interested in helping to develop out a plugin API and directory. This would open up Keystone to user-contributed admin functionality.

I noticed a transition to modularizing the different field's UI files... Is this something you're planning? If so, are you interested in my contribution to help expedite it? If not, let's discuss it here further to decide on a pattern and I can work on it and then issue a PR.

**Comment by JohnnyEstilles** [comment]
Continuing discussion on issue #912 ...
