### ISSUE TITLE
S3FileAdapter for static file uploads

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1853]
# Feature request

> how to hook up their static app/File field to a cloud provider for file storage (e.g AWS s3?)
(_[from Slack](https://keystonejs.slack.com/archives/C02FLV1JG/p1572212221116600)_)

## Describe the solution you'd like

A new file storage adapter which allows me to save & retrieve files directly to/from an S3 bucket.

Something like;

```javascript
const { File } = require('@keystonejs/fields');
const { S3FileAdapter } = require('@keystonejs/file-adapters');

const fileAdapter = new S3FileAdapter({
  /*...config */
});

keystone.createList('Applicant', {
  fields: {
    file: {
      type: File,
      adapter: fileAdapter,
      isRequired: true,
    },
  },
});
```

The implementation of `S3FileAdapter` should follow the patterns of `CloudinaryFileAdapter`: https://github.com/keystonejs/keystone/blob/master/packages/file-adapters/lib/cloudinary.js

**Comment by LiamAttClarke** [comment]
https://github.com/keystonejs/keystone/pull/1986

**Comment by Vultraz** [comment]
Can be closed now.
