### ISSUE TITLE
0.4: sign-in screen logo is not customizable

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1854]
The code in the browser looks like this:
```
img src="/keystone/images/logo.png" width="205" height="68" alt="MyKeystoneApp"
```

Seems the `alt` attribute is correctly set from the config but not the logo.  @JedWatson says this may be a regression.

**Comment by jossmac** [comment]
@webteckie have tried to reproduce, these configurations work:

As a string:
```
keystone.init({
  'signin logo': '/images/layout/logo.png',
});
```
As an array:
```
keystone.init({
  'signin logo': ['/images/layout/logo.png', 125, 125],
});
```

We will add a breaking change down the track with updated syntax:
```
keystone.init({
  'signin logo': { url: '/images/layout/logo.png', width: 125, height: 125 },
});
```
