### ISSUE TITLE
Autodetect in Location field not working - broken in LocationType.js

### ISSUE THREAD

**Issue by jordanyim1** [keystonejs/keystone#1864]
This line of code seems to have broken location auto-detect in the keystone editor for me - pressing 'Autodetect and improve location on save' would no longer geolocate the address. 

Tracked it down to this commit introduced in version 0.3.13.  
https://github.com/keystonejs/keystone/pull/1537/files

If I delete these lines of code in fields/types/location/LocationType.js (line 375) it works again.

```javascript
if (keystone.get('google server api key')){
     options.key = keystone.get('google server api key');
}
```

**Comment by emaddoma** [comment]
Is there a workaround for this issue?  I really need the Google Maps integration to work on a current project.

**Comment by emaddoma** [comment]
The documentation could benefit from telling folks they need to enable the Google Maps Geocoding API.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by jordanyim1** [comment]
Hi, this still seems to be broken as of v0.3.22.  It's not a support request but a bug - the code to remove to fix it is in my post above.  I would create a PR but i don't know if that does something else.

**Comment by jordanyim1** [comment]
For future users:  Having no 'google server api key' will work for in keystone 0.3.13 and earlier.  But for later versions, if you have a key that doesn't have the Geocoding API enabled, it will break.  Here is the link to the geocoder.

https://console.developers.google.com/apis/api/geocoding_backend/

**Comment by molomby** [comment]
As far as I can tell this is not longer the case. Location fields will be "improved" (ie. geocoded and other values corrected) when `enableMapsAPI: true` is set for the field, regardless of whether a `google server api key` is configured for Keystone. (Obviously this is subject to Google API serving the request despite the lack of key.)
