### ISSUE TITLE
Missing Installation Instructions

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#1867]
# Bug report
The new KeystoneJS (V5) document misses out the crucial step of how to install Keystone either with npm or yarn or git or yo generator

## Describe the bug
```npm init keystone-app myapp ``` 
as in the Getting Started Video does not work on a fresh Linux system

Currently one is confused on whether to
* Clone the Github repository
* install a yo generator
* some other way

## Expected behaviour

A clear and concise description of how to get started with KeystoneJs.

**Comment by MadeByMike** [comment]
Is this simply because the user needs to install node/npm?

If so, I'd say `npm` is a prerequisite we're prepared to assume. We list node v10 as a prerequisite in the getting started guide. If I'm not mistaken this includes npm?

**Comment by VinayaSathyanarayana** [comment]
Not node or npm

Currently one is confused on whether to

Clone the Github repository
install a yo generator
some other way

**Comment by timleslie** [comment]
Could you provide the output that you're seeing when you run `npm init keystone-app myapp`. This will help us determine the best course of action to update the docs to cover your use case. Thanks!

**Comment by VinayaSathyanarayana** [comment]
$ sudo npm init keystone-app myapp
[sudo] password for vinaya:
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (vinaya)

**Comment by MadeByMike** [comment]
![image](https://user-images.githubusercontent.com/1320567/68257929-11f4d900-0089-11ea-902f-f0510671681f.png)

Works for me. Can we get on info on node version, npm version and OS?

**Comment by MadeByMike** [comment]
I'm closing this one because I can't reproduce and not new information. There have been several releases since this was logged so if there was an issue or a bad npm cache it's likely related to an older version now.
