### ISSUE TITLE
0.4: email error validation popup

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1867]
If I create a new user and enter an invalid email format I get the following...it blanked out the first/last name and focus on the wrong field.  Should leave the first/last alone and focus on the email field:

![image](https://cloud.githubusercontent.com/assets/5872515/11386875/a23f8904-92f3-11e5-9022-6efa9960d675.png)

**Comment by webteckie** [comment]
This can be a symptom of the Admin UI not being a SPA, yet.  But will leave this open to ensure that after SPA-fication that it works ok.

**Comment by mxstbr** [comment]
Added to #2652, so closing this one!

**Comment by mxstbr** [comment]
This is actually kinda resolved with the SPA-ificiation. It's not perfect yet, but when we introduce client side validation this will become a lot better!
