### ISSUE TITLE
0.4: selected extra columns in list view not persisted

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1869]
If I select extra columns in the list view then I expect these columns to be remembered for the session.  But as soon as I navigate (e.g., view an list item) and return to the list view the extra columns are gone.

**Comment by JedWatson** [comment]
Fixed :)

**Comment by webteckie** [comment]
@JedWatson this seems to work fine if you use the browser's back in history link but does not work if you use keystone's ways of getting back to the listing page (like the breadcrumbs or the admin ui menu).
