### ISSUE TITLE
0.4:  Error: Related List Posts has no field postCategory

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1870]
In the keystone-test-project, get `Error: Related List Posts has no field postCategory` while viewing Post Categories.  Checked the models and seem fine to me:

![image](https://cloud.githubusercontent.com/assets/5872515/11387192/2e6cf176-92f6-11e5-9de7-32bea36f14bf.png)

**Comment by JedWatson** [comment]
Thanks for the report @webteckie - has been fixed.

**Comment by jobfiander** [comment]
How did you resolve this issue? We're seeing the same error in our application.

**Comment by snowkeeper** [comment]
@jobfiander check and see if your relationship definition is correct.  I needed to change
`PostCategory.relationship({ ref: 'Post', path: 'categories' });` to `PostCategory.relationship({ ref: 'Post', refPath: 'categories' });`

**Comment by kat-liger** [comment]
Just wanted to add that the current master branch doesn't have this fix.

**Comment by mmccoy** [comment]
Not sure if this is entirely fixed.  I'm using `4.0.0-beta.4` and although the fix from @snowkeeper using `refPath` does fix the error and shows the relationship, it does not successfully populate the entities from the relationship path.  I get persistent 'loading dots', and no javascript errors in the console.

<img width="1172" alt="screen shot 2016-12-23 at 11 46 08 am" src="https://cloud.githubusercontent.com/assets/200675/21458548/72a21722-c905-11e6-895a-7acc7ce2d4ad.png">

**Comment by DmitryKvant** [comment]
You can't fix it for two years already ?! And how should I be?

**Comment by JedWatson** [comment]
Turns out this was a configuration issue in the generator - not sure what happened to the fix that was originally applied but thanks to @biphobe for picking it up and submitting the PR!
