### ISSUE TITLE
0.4:  Can those + signs be made a bit more visible

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1871]
In my screen they look almost invisible...or maybe it is time for a vision check :-)

![image](https://cloud.githubusercontent.com/assets/5872515/11387305/45612dc4-92f7-11e5-8483-27cb33342754.png)

**Comment by mxstbr** [comment]
I think they're fine, I'll close this but ping @jossmac if he has any input about the design. :+1:
