### ISSUE TITLE
0.4: annoying warning message logged in chrome console

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1872]
**Warning: Failed propType: transitionLeaveTimeout wasn't supplied to ReactCSSTransitionGroup: this can cause unreliable animations and won't be supported in a future version of React. See https://fb.me/react-animation-transition-group-timeout for more information. Check the render method of `ListFiltersAdd`:**

![image](https://cloud.githubusercontent.com/assets/5872515/11387408/26580398-92f8-11e5-99ea-c15d310aa78c.png)

**Comment by geloescht** [comment]
Cannot reproduce on Chromium 48.0.2564.82 Ubuntu 15.10 (64-bit) with keystone rev. 8db233f95d . Are there any special steps that are needed to reproduce other than opening Admin UI pages? Otherwise I guess this can be closed.

**Comment by mxstbr** [comment]
This definitely happens when you build the packages in the development env, i.e. npm run build-dev. (These warnings are suppressed by react in production)

**Comment by mxstbr** [comment]
I'll close this, it's on my list: #2652
