### ISSUE TITLE
how to filter duplicate images?

### ISSUE THREAD

**Issue by eimhee** [keystonejs/keystone#1875]
user upload images to cloudinary cdn server. 
cloudinary can return ETag respons, when
do a HEAD request and compare the ETag response (MD5 of the file's content).

like this: 0a7dc51c9efadc5f37d97cbd9aaaa297
I want to use it and filter duplicate images,
but how to store the ETag in mongodb?

**Comment by morenoh149** [comment]
you get an etag via http. You can add data to mongodb by using the node driver (included in keystonejs) or make a mongoose collection. Questions like these are more appropriate in the [gitter](https://gitter.im/keystonejs/keystone)
