### ISSUE TITLE
Best approach to resize image or generate thumbnails from Cloudinary in Keystone

### ISSUE THREAD

**Issue by ytzvan** [keystonejs/keystone#1881]
Hello, need to manipulate some images and I try to find the best way to do that:
First. using the underscore methods from Type.CloudinaryImage and using
```javascript
thumbnail(width, height, options)
```
But I don't figure out a way to use underscore functions inside Keystone, maybe if you provide an example how to implement this will be great.

Second. Using directly the Cloudinary API and applying the parameters in the URL. Cloudinary needs this parameters after the '/upload/' in the URL, so I can create a function to manipulate the url String. I can do this but if you have a better approach will be great.
Example: 
URL From Model.image.url: http://res.cloudinary.com/keystone-demo/image/upload/v1448516320/p9kavpzwosr5hujehhg8.jpg
URL needed: http://res.cloudinary.com/keystone-demo/image/upload/c_fit,w_640/v1448516320/p9kavpzwosr5hujehhg8.jpg
Any thoughts ?

**Comment by tomchambers2** [comment]
I was having trouble with this as well. The underscore method should be used in the template like so:

```
	view.on('init', function(next) {
		Book.model.find().exec().then(function(result) {
			locals.books = result;
			next();
		}, function(err) {
			next(err);
		});
	});

{% for book in books %}
{{ book.image.url }}
    {{ book.image._.tag() }}
{% endfor %}
```

**Comment by axaq** [comment]
You should be able to see usage examples for underscore in the keystone demo. Here is one:

https://github.com/keystonejs/keystone-demo/blob/master/templates/views/post.jade#L21

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
