### ISSUE TITLE
Underscore in field name causes GraphQL error: Unable to find Mongo field which maps to graphQL path error

### ISSUE THREAD

**Issue by derkweijers** [keystonejs/keystone#1885]
# Bug report

## Describe the bug

I'm migrating from Keystone 4 to Keystone 5. I have a database that has fields which have underscores in them (news_site, news_site_long). When I define these fields in `createList` I get the following error:

`GraphQL error: Unable to find Mongo field which maps to graphQL path news`

I've been searching in the docs to prevent this behavior, but I couldn't find an option.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Define a field with an underscore in it
2. In the admin GUI, Click on the list
3. See error

## Expected behaviour

I expect to see a list of all my entries in that MongoDB collection.

## Screenshots

![image](https://user-images.githubusercontent.com/11644998/68022311-412fd280-fca4-11e9-92e4-70e74c3f72d3.png)

## System information

- OS: Debian, MacOS
- Browser (if applies): Opera, Chrome

**Comment by Vultraz** [comment]
Did you try camelcase? Ie, `newsSite` and `newsSiteLong`?

**Comment by derkweijers** [comment]
Hi,

Thanks! I've been away this weekend and will check it tonight.

Kind regards,
Derk

**Comment by derkweijers** [comment]
No errors with camelcase, but also no data:

![image](https://user-images.githubusercontent.com/11644998/68150518-32fde280-ff40-11e9-8a66-4f164dc60a2d.png)

**Comment by Vultraz** [comment]
Hmmmmmmm... well, definitely sounds like a bug if you can't access fields with underscores 😬 Is there any way for you to convert the values on the DB side to camelcase? With the Mongo shell, perhaps?

**Comment by derkweijers** [comment]
To test or permanently? If it's to test something; yes. If it's for real; I'm afraid that will get me in trouble with devs that connect to my API :)

**Comment by Vultraz** [comment]
Ooof 😂 Yeah, I was suggesting for production. Let's see if @MadeByMike has any insight...

**Comment by MadeByMike** [comment]
I can't seem to reproduce this one. Here is the test config I used:
```
keystone.createList("Test", {
  fields: {
    name: { type: Text },
    the_mostest_underscores: { type: Text }
  }
});
```
I opened the Admin UI and I was able to create an item. The field labels and data both showed up:

![image](https://user-images.githubusercontent.com/1320567/68257749-6b103d00-0088-11ea-94a4-b05a63d2fb9f.png)

Have I done this right?

**Comment by derkweijers** [comment]
Hi!

Apologies for the late reply, I'm a bit busy.

It looks the same yes, here's my code:
`module.exports = {
  fields: {
    newsSite: {
      type: Text,
      isRequired: true,
    },
...
}`

In my index.js file (enty point):
`keystone.createList('Article', ArticleSchema);`

Here's a snippet directly from MongoDB:

![image](https://user-images.githubusercontent.com/11644998/68529559-327a9880-0300-11ea-8deb-3b8f855eefbf.png)

And this results in what's posted before.

I hadn't tried creating new documents and I just did. This seems to work at first (I see them in the UI) but it's inserted camel cased in the database:

![image](https://user-images.githubusercontent.com/11644998/68529612-b9c80c00-0300-11ea-9103-3b948dca1f2f.png)

**Comment by derkweijers** [comment]
By accident, I found a possible solution/workaround:
Define a non-underscore item as first item in the list (title, name, etc.). All underscore items will now behave correctly.

**Comment by derkweijers** [comment]
Unfortunately, with `defaultSort:` it breaks again when you try to sort on an item with an underscore.

**Comment by kvssandhu** [comment]
Facing similar issue.  

Solution : change the item names to camelCase (for Mongo Users) 

In case you are using Knex Adapter with postgreSQL, change the item names to all lowercase or uppercase, depending upon column names in your DB.

**Comment by derkweijers** [comment]
> Facing similar issue.
> 
> Solution : change the item names to camelCase (for Mongo Users)
> 
> In case you are using Knex Adapter with postgreSQL, change the item names to all lowercase or uppercase, depending upon column names in your DB.

That worked partially for me, as `defaultSort: ` breaks it again.

**Comment by hew** [comment]
This also occurs over on the Postgres side. When you click to sort by key, any key with an underscore will throw the following error: 

> GraphQL error: Cannot read property 'sortKey' of undefined

Since keystone caches the currently visible tabs, all subsequent reloads without clearing the cache will throw the error before even displaying any information. 

Kind of a major bug. If anyone has any workarounds that would be great.

**Comment by hew** [comment]
To clarify, the underscore fields will display information in the default filtering. The error occurs when you click on the ordering tab for a key that has an underscore in it. 
 
![image](https://user-images.githubusercontent.com/3103241/82103348-85764380-96c7-11ea-94f2-f2a61c0679f2.png)

**Comment by hew** [comment]
Steps to reproduce: 

1. Start a new keystone project
2. Choose postgres/Knex
3. Create a list with a key that has an underscore
4. Try to view that list

**Comment by cicibobo** [comment]
> By accident, I found a possible solution/workaround:
> Define a non-underscore item as first item in the list (title, name, etc.). All underscore items will now behave correctly.

Works for me as well

**Comment by radospanny** [comment]
I have still issue with a field name containing underscore. The GraphQL returns error in sortBy. Any help?
Thank you very much.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
