### ISSUE TITLE
0.3: Redirect loop to sign in page

### ISSUE THREAD

**Issue by riyadhalnur** [keystonejs/keystone#1886]
Is anybody else getting redirected back to the sign-in page when trying to access the dashboard?

**Comment by JedWatson** [comment]
@riyadhalnur can you give some more context? is this in your own project / the demo / etc?

Sounds like permissions (the `canAccessKeystone` property on the `User` model, usually a virtual pointed at an `isAdmin` Boolean) aren't set up right for the user you're logging in as.

**Comment by riyadhalnur** [comment]
oh right. i totally forgot about that. problem fixed
