### ISSUE TITLE
Custom options to Knex adapter do not do anything.

### ISSUE THREAD

**Issue by Stegosource** [keystonejs/keystone#1890]
# Bug report

## Describe the bug

Following the basic setup instructions and using Postgres with Knex, I should be able to pass a custom config to the Knex adapter for my remote Postgres DB. However, Knex always looks for Postgres on localhost.

The error messages look like this:
```
⠙ Connecting to databaseCould not connect to database: 'ks_test'
If this is the first time you've run Keystone, you can create your database with the following command:
createdb ks_test
✖ Connecting to database
Error: connect ECONNREFUSED 127.0.0.1:5432
```

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. `yarn create keystone-app my-app`
    ✔ What is your project name? … example
    ✔ Select a starter project › Starter (Users + Authentication)
    ✔ Select an adapter › Knex
2. Open `index.js`
3. Replace `adapter: new Adapter(),` with:
```
adapter: new Adapter({
    client: "pg",
    connection: {
      host: [db host],
      user: [db user],
      password: [db password],
      database: [db database]
    }
  }
),
```
4. `yarn dev`

## Expected behavior

The project should connect to the remote DB and continue the init process.

## System information

- OS: Ubuntu 10.10

## Additional context

Im not sure if this message is relevant:
`If this is the first time you've run Keystone, you can create your database with the following command:
createdb ks_test`
I dont think it should be, because the knex options should still try to connect to the remote host with the db name I provide. 

Also not that I tested a super simple knex script to confirm that it was not knex or my settings that had an issue:
```
var knex = require("knex")({
  client: "pg",
  connection: {
    host: [db host],
    user: [db user],
    password: [db password],
    database: [db database]
  }
});

(async () => {
  const r = await knex("todo").select();
  console.log(r);
})();
```
And I got back `[]` which is expected.

**Comment by timleslie** [comment]
Hi @Stegosource, you need to pass through the options as `knexOptions`. If you try the following it should work: 

```
adapter: new Adapter({
  knexOptions: {
    client: "pg",
    connection: {
      host: [db host],
      user: [db user],
      password: [db password],
      database: [db database]
    }
  }
}),
```

Let me know if that doesn't work for you. Is there a piece of documentation somewhere we can update to make this clearer?

**Comment by Stegosource** [comment]
Ahhh. I see now. I missed the `options.knexOptions` in the docs. Sorry about that. Working now :)

**Comment by mohanen** [comment]
> Hi @Stegosource, you need to pass through the options as `knexOptions`. If you try the following it should work:
> 
> ```js
> adapter: new Adapter({
>   knexOptions: {
>     client: "pg",
>     connection: {
>       host: [db host],
>       user: [db user],
>       password: [db password],
>       database: [db database]
>     }
>   }
> }),
> ```
> 
> Let me know if that doesn't work for you. Is there a piece of documentation somewhere we can update to make this clearer?

I also got bit confused, 
This example would do better in the docs https://www.keystonejs.com/keystonejs/adapter-knex/

**Comment by DungRaymond** [comment]
@timleslie I have similar problem and it won't connect to database. Needs for an knexOptions prop `port` because appending it to the end of host string won't work.
