### ISSUE TITLE
Stylus doesn't compile when choosing the stylus option in the yo keystone generator - spaces issue *resolution*. 

### ISSUE THREAD

**Issue by plimbs** [keystonejs/keystone#1893]
Hey, 

There is a spacing issue in the stylus file _layout.styl causing the stylus not to compile and throw an error.

in the .gallery-image img the spacing is set to tab and it needs to be set to 'indent using spaces' like the rest of the spacing in the file. 

Once I changed this and installed and ran nib the site.styl file compiled a site.css file.

**Comment by morenoh149** [comment]
moved to generator repo
