### ISSUE TITLE
0.4 suggestion : Image thumbnails in admin panel

### ISSUE THREAD

**Issue by vikrant1011** [keystonejs/keystone#1894]
I tried to find another post by same suggestion but couldnt find one.

currently it gets tough to manage products without thumbnails in the admin panel. It will be great if you can manage to do that in the next update.

I see that the issue for sorting is already listed in another post so not adding it here. but that was another problem i faced with 0.4

thanks for your efforts!!

**Comment by ericelliott** [comment]
@JedWatson I saw another admin panel image-related feature yesterday. Related?

**Comment by JedWatson** [comment]
Can you expand a bit on how your lists are set up and what you want the use-case to be @vikrant1011?

If I'm understanding you correctly you want to be able to add thumbnails to the way relationships are managed?

**Comment by mxstbr** [comment]
Closing due to staleness, let me know if you're still interested in this!
