### ISSUE TITLE
User session does not survive browser close

### ISSUE THREAD

**Issue by murdockcrc** [keystonejs/keystone#1895]
Hello,

Since we integrated our nodejs into Keystone, we've noticed that whenever a logged-in user closes the browser and opens it again, the user is not authenticated anymore. We store our sessions on redis and set a long TTL, so these sessions should persist despite the user closing the browser. Here is how we configure our keystone app for session management:
```
keystone.init({
  'name': 'My app',
  'compress': true,
 
  'static': ['public'],
  
  'views': 'views',
  'view engine': 'handlebars',
  
  'auto update': true,
  'mongo': configuration.app_options.mongodb.connectionString[configuration.env],
  
  'session store': 'connect-redis',
  'session store options': {    
    host: configuration.redis_options[env].host,
    port: configuration.redis_options[env].port,
    pass: configuration.redis_options[env].pass,
    ttl: 31104000
  },
  'session': true,
  'auth': true,
  'user model': 'User',
  'cookie secret': credentials.cookieSecret[env]
});
```
Would appreciate any pointers on how to configure a keystone app to persist user sessions.

**Comment by morenoh149** [comment]
Please check if the browser is receiving any cookies. https://developers.google.com/web/tools/chrome-devtools/iterate/manage-data/cookies?hl=en

**Comment by murdockcrc** [comment]
@morenoh149 It does receive a cookie names "keystone.sid". Chrome reports it with an "Expires" value of "Session"

**Comment by morenoh149** [comment]
https://github.com/expressjs/session#cookie-options
```
By default cookie.maxAge is null, meaning no "expires" parameter is set so the cookie becomes a browser-session cookie. When the user closes the browser the cookie (and session) will be removed.
```

**Comment by murdockcrc** [comment]
@morenoh149 Agree, that is true. However, how can I change that configuration in keystone? Without keystone, I would use something like `app.use()` middleware to set the cookie as persistent. As per the code above, I am adding the TTL parameter to the keystone.init call but this does not seem to be affecting the behavior. Any pointers on this configuration for keystone?

**Comment by morenoh149** [comment]
looks like https://github.com/keystonejs/keystone/blob/master/lib/core/initExpressSession.js#L41 https://github.com/keystonejs/keystone/blob/master/lib/core/initExpressSession.js#L94 might needs to be augmented with a `cookie options` param. Could you try passing in
```
session({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: true,
  cookie: { secure: true, maxAge: 31104000  }
})
```
and see if that works

**Comment by murdockcrc** [comment]
@morenoh149 sorry, where should that code go into, exactly?

**Comment by morenoh149** [comment]
ah `session options` is missing from the documentation. https://github.com/keystonejs/keystone/blob/master/lib/core/initExpressSession.js#L18 https://github.com/keystonejs/keystone/blob/master/lib/core/initExpressSession.js#L122 try setting
```
keystone.init({
...
  'session options': {
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: true,
    cookie: { secure: true, maxAge: 31104000  }
  }
...
});
```

**Comment by murdockcrc** [comment]
@morenoh149 So I added that conf (just changed 'secure' to false, for testing) but the keystone.sid cookie expiration is still 'Session'. This is how the 'init' function parameters look like:

```
keystone.init({
  'name': 'Helden der Volksmusik',
  'compress': true,
 
  'static': ['public'],
  
  'views': 'views',
  'view engine': 'handlebars',
  
  'auto update': true,
  'mongo': configuration.app_options.mongodb.connectionString[configuration.env],
  
  'session store': 'connect-redis',
  'session store options': {    
    host: configuration.redis_options[env].host,
    port: configuration.redis_options[env].port,
    pass: configuration.redis_options[env].pass,
  },
  'session options': {    
    cookie: { secure: false, maxAge: 31104000  }
  },
  'session': true,
  'auth': true,
  'user model': 'User',
  'cookie secret': credentials.cookieSecret[env]
});
```

**Comment by morenoh149** [comment]
step through the app in a debugger and see what `sessionOptions` looks like after line https://github.com/keystonejs/keystone/blob/master/lib/core/initExpressSession.js#L121

**Comment by JedWatson** [comment]
Sounds like that may be a bug in the session initialisation code, @murdockcrc do you mind tweaking `initExpressSession` and seeing if you can track it down?

**Comment by jacargentina** [comment]
@JedWatson @mxstbr @murdockcrc @morenoh149 May be my PR helps to fix this. Cheers!
