### ISSUE TITLE
Plugin Architecture

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1898]
It would be great if KeyStone users could do most of their custom development on a plugin architecture.

Plugin architectures provide several major advantages. One huge advantage is that new features can be developed as plugins, and we can provide a mechanism to toggle features on and off in production. Ideally, most new KeyStone development should be possible to do in plugins, rather than in the core.

Here are some plugin extensibility points worth consideration:
- [ ] Adding middleware to or pre-built routes to the express stack
- [ ] Adding custom field types
- [ ] Adding pre-built models
- [ ] Replacing some or all of the management UI for certain lists
- [ ] Adding components to Lists in the Admin UI (probably in the sidebar but could sit around or in the form as well)
- [ ] Adding custom views to the Admin UI
- [ ] A more fleshed-out API will help with this.

API related issues:
https://github.com/keystonejs/keystone/issues/1705
https://github.com/keystonejs/keystone/issues/1713
https://github.com/keystonejs/keystone/issues/1714

**Comment by stkrzysiak** [comment]
This sounds great, how do we get something like this approved and on the road map @JedWatson & others?  I was actually a bit surprised to see that this doesn't exist yet for keystone(been a yr since I looked it over).

**Comment by larsha** [comment]
Is there no way to customize the admin UI in a nice way, own routes/views with own logic?

**Comment by mxstbr** [comment]
Not yet @larsha, it's one of the big things after 0.4 is finally out that we want to get to!

**Comment by SharadKumar** [comment]
Here is an example of the first task (as middleware).
https://github.com/ForestAdmin/keystone-demo

@JedWatson

**Comment by Fogetti** [comment]
Is there any news on this? The admin interface refactoring has been out for a year now and I still can't find the new admin UI plugin architecture. All I see is a not very specific reference in the wiki which says: "Subsequent releases (...) Create a Plug-in architecture"

**Comment by henrypip** [comment]
Just echoing @Fogetti, it'd be great to know when a plugin architecture is being planned, right now editing the Keystone source code isn't something we're keen on doing.

**Comment by pinussilvestrus** [comment]
+1

**Comment by Noviny** [comment]
Just reiterating Max for those who have asked since he replied. This is still a high priority task for after 4 is released.

**Comment by zilveer** [comment]
any update here?

**Comment by PTZ2002** [comment]
Hello,

I'm interested if the plugin system is build in the version 4.0.0-beta5 or if there is any method or way to develop custom plugins for keystone?

Best regards,
 Tamas

**Comment by gautamsi** [comment]
Keystone 4 is going in maintenance mode. Expect no major change. see #4913 for details.

There is initial discussion to have plugin/extension in v5 keystonejs/keystone-5#842, contribute there if you want Plugin architecture in v5
