### ISSUE TITLE
New field type: JSON

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#190]
Would store a JSON string in the database, and have a nice renderer / editor in the Admin UI.

Could use [pretty-stringify](https://github.com/JedWatson/html-stringify) for formatting the JSON, and [Code Mirror](http://codemirror.net) for editing.

Would validate JSON on save.

**Comment by uptownhr** [comment]
problem with using "Types.Code" is that it will store the JSON as text. Meaning you will not be able to run queries against it.

**Comment by morenoh149** [comment]
@uptownhr someone has to code it. There's probably no technical reason blocking this.

**Comment by jbalde** [comment]
I created a field type Types.Json that store in mongo a JSON in raw format. I commit two pull requests to branch 0.3.x and master.

**Comment by kadosh1000** [comment]
Hi I have published my npm package: 
https://github.com/kadosh1000/keystone-custom-fieldtypes

It allows you to create custom field types, and copy your custom fieldTypes from a selected dir into the keystone's fields dir and registers it.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/new-field-type-json)!

**Comment by ChristianRich** [comment]
This worked for me and allowed my to save an arbitrary object, only it's not visible in the Admin UI because it is unsupported. But you can query the fields just fine.

```
list.schema.add({
    model: mongoose.Schema.Types.Mixed
});
```

**Comment by gemscng** [comment]
@mxstbr  @JedWatson  i have make a pull request on latest version base on . @jbalde 
 code.  https://github.com/keystonejs/keystone/pull/4855

**Comment by victusfate** [comment]
since this has been around for 3 years, is there a suggested work around for existing data schema with Mixed types (responses from third parties etc)

trying out keystone v5 and was hoping to hit the ground running with a light cms around my data
```
    transcription_job: { type: JSON, schemaDoc: 'response of transcription job' }
```

no good atm

**Comment by internetErik** [comment]
@victusfate 
Not a great solution, but you could just save JSON as plain test - perhaps in a Textarea type - and after reading it in from mongo in your controller run JSON.parse on it.
