### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1901]
With a fresh keystone repo clone after `$ npm install`:

```sh
$ npm run test-cov

> keystone@0.4.0-alpha pretest-cov /Users/eric/Dropbox/dev/keystone
> npm run clean


> keystone@0.4.0-alpha clean /Users/eric/Dropbox/dev/keystone
> rimraf ./coverage


> keystone@0.4.0-alpha test-cov /Users/eric/Dropbox/dev/keystone
> istanbul cover ./node_modules/mocha/bin/_mocha




  0 passing (25ms)
  1 failing

  1) List schema pre/post save hooks "before all" hook:
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:27017
      at Object.exports._errnoException (util.js:874:11)
      at exports._exceptionWithHostPort (util.js:897:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

Same thing happens with `$ npm test`.

Inside the test directory, there's a README:

---
# Keystone Tests

## Server

to test the ssl configuration you must tell node to ignore certificate errors

```sh
NODE_TLS_REJECT_UNAUTHORIZED=0 mocha lib/server.https.test.js 
```
---

This results in zero tests running.

**Comment by JedWatson** [comment]
That looks potentially like a MongoDB connection error - are you running the mongo server locally on the default port (21017)?

**Comment by JedWatson** [comment]
Just confirming the tests run fine locally for me, so I think this is environmental

**Comment by ericelliott** [comment]
Resolved. And Mongo.. wtf? ಠ_ಠ
