### ISSUE TITLE
Docker Dev Environment

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1902]
One of my installers blasted my homebrew setup to bits.

I discovered this because mongo didn't work when I tried to run the Keystone tests.

A docker dev environment would be a great quickstart for the dev environment. No weird cross-platform install issues. Just run a docker command and everything gets set up proper. =)

**Comment by JedWatson** [comment]
:+1: if someone gets this set up I'd be very happy to add it to the project

**Comment by webteckie** [comment]
I use docker for my keystone app.  @ericelliott what would you consider requirements as to what the keystone docker image should have?  At some point I also thought that a docker setup may be good but not too sure as to exactly what purpose the image should serve.  For example, should it configure the demo app?  the test project app? should it yo scaffold a new app structure upon setup?  no app?  I think we need some basic requirements for this image, which serves the best use case(s).

**Comment by ericelliott** [comment]
> For example, should it configure the demo app? the test project app?

This particular issue is for developers who want to contribute to Keystone core, so it should include all the Keystone dependencies including Mongo and Redis, and clone the Keystone repo.

🎸🎶🔥

**Comment by ericelliott** [comment]
I think deploy configs would be great, too! Those would have containers for the dbs & all the deps pre-installed, but not Keystone itself. Let the user manually install their own Keystone app. I think that should be it's own issue, though. ;)

**Comment by JedWatson** [comment]
I think having the keystone demo and test-project repos installed locally and linked with `npm link` would be a good starter environment for people developing keystone.

So something like this (folders placed where appropriate)

```
/keystone // clone of the repo, on master, + npm install + npm link
/keystone-demo // npm install + npm link keystone
/keystone-test-project // npm install + npm link keystone
```

Running latest mongodb (currently 3.x) node.js (currently 5.x) and npm (currently 3.x)

**Comment by webteckie** [comment]
We can start with what @JedWatson says as a basic setup and move on from there to more complex deploy configs like @ericelliott Are you going to work on this @ericelliott or do you want me to take a stab at some initial proposal?  My issue is time:-)

**Comment by ericelliott** [comment]
Nice. =)

Take a stab if you like. I think we may have other burning priorities to focus on today.

**Comment by mgan59** [comment]
In the past for Keystone and other projects I was using vagrant with the docker provisioner to create containers for mongodb and redis.  While using bash to provision the nodejs environment, I had placed this work inside of the generator so you could create a keystone project with docker support -- https://github.com/mgan59/generator-keystone/commit/94a7b8bfa9c7846042ad7de020744f47eadad72c
Initial implementation was from Feb 2015, so much has changed in docker eco-system.

The new docker-toolbox includes docker-machine and compose which means vagrant can be dumped and there are easier ways to manage volumes and networking of containers using compose.  

Happy to be involved in this process.  My question is do we want this to be part of the keystone repo for developers and also expose this as part of the generator?  Could expose as part of the generator the option to create docker containers for mongodb/redis but allow the developers to run express locally, versus a full containerized stack. 

To **note** putting things in docker isn't an end-all-be-all solution.  Inevitably docker containers can fail and it requires the developer to trouble shoot the environment.  Which if you aren't familiar with docker it can be a nightmare to figure out what went wrong, especially around networking / port-forwarding.  We could alleviate some of this with `gulp` tooling.

**Comment by webteckie** [comment]
@mgan59 I've been busy and haven't thought about this.  Feel free to run with it.  I was thinking that maybe we should start with defining basic use cases to better understand how to configure the image(s).  As a basic first step I was going to do what @JedWatson suggested and create a docker image with keystone along with its demo and test projects.  However, as I think of the purpose of this I would think it is to by default have master:keystone but then be able to override it with a copy from a local repo so that a user can do sanity testing against some reasonable websites before pushing changes.  But not sure about this.  So feel free to do what you think is the most useful approach.

**Comment by ericelliott** [comment]
> My question is do we want this to be part of the keystone repo for developers and also expose this as part of the generator?

Yes, I think that's a good approach.

> I think having the keystone demo and test-project repos installed locally and linked with npm link would be a good starter environment for people developing keystone.

:+1: 

I'm using this in my test project dev environment `package.json`:

```js
   "keystone": "file:///Users/eric/Dropbox/dev/keystone",
```

An automated solution would be very cool.

**Comment by jonathanp** [comment]
>I'm using this in my test project dev environment `package.json`:

> ```js
   "keystone": "file:///Users/eric/Dropbox/dev/keystone",
```

> An automated solution would be very cool.

@ericelliott doesn't that give you the same thing as [`npm-link`](
https://docs.npmjs.com/cli/link)? :)

**Comment by webteckie** [comment]
I think automating npm link between the container and the host is going to be a bit challenging if want to make this images also work with windows hosts...unless some kind of tricks can be used to symlink the relevant npm link directory in both sides.

**Comment by mxstbr** [comment]
Closing since nobody seems to be working on this anymore, I'd love to have this though!
