### ISSUE TITLE
Relative requires make it harder to refactor

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1907]
I suggest we stop all the relative requires everywhere. Doing so will require that we set an environment variable on startup, but that can be made easy using npm scripts to start Keystone. See the [Universal React Boilerplate example](https://github.com/cloverfield-tools/universal-react-boilerplate#requiring-modules).

We'll need to share that information with the compiler tools, as well.

**Comment by adnasa** [comment]
:+1: great suggestion!

**Comment by JedWatson** [comment]
I love the idea of using `NODE_PATH` but I don't think it's safe for Keystone to do; would require environment configuration in each project to configure the path for Keystone correctly.

Seems like something that's good for projects and not libraries.

Unless I'm mistaken?

**Comment by ericelliott** [comment]
Doesn't Keystone already require some environment configuration? I can't imagine a project like this without it...

**Comment by JedWatson** [comment]
Actually, it works out of the box without any :dancer: 

You can use _either_ the options or `process.env` to configure things like mongo and the session secret, and optional things like cloudinary, but it's all optional which makes getting up and running really easy.

**Comment by ericelliott** [comment]
Yeah.. I'm forgetting that this is a lib, and not a boilerplate / base project like WordPress or Universal React Boilerplate.

I'm not sure how we could do a default require path is a lib... any ideas?

**Comment by JedWatson** [comment]
I've seen it asked a lot of times but not found a viable solution that works universally.

You can do fancy things with symlinks in `node_modules` but it's hacky, and breaks on Windows.

There's an exception for client-side code, which we make use of to bundle the field types, where you can browserify something and expose it as a named package, then exclude that from your other bundles; but I haven't found a solution for node.

If we can break apart the core well enough, it's possibly cleaner to just move towards more granular node modules (so e.g. `require('keystone-core')` or `require('keystone-list')` - this will remove a lot of the relative paths that traverse the codebase significantly, and hopefully make the project easier to reason about.

I've been rearranging a lot of the codebase for this version with this in mind, e.g. the monolithic functions that were `keystone.start` and `keystone.mount` have been broken down into files in `/server`, and the Admin UI has been given its own express app*

*well, router, which is basically the same thing

**Comment by ericelliott** [comment]
Sounds like a good strategy. I'm satisfied. =)
