### ISSUE TITLE
use pm2 start

### ISSUE THREAD

**Issue by bookyo** [keystonejs/keystone#1907]
how can i use pm2 start keystone app.

**Comment by MadeByMike** [comment]
I didn't know what `pm2` was. But I googled it and reading their docs it looks like maybe something like this:

`pm2 start npm --name "app_name" -- run dev`

I'm not sure this one is a Keystone question and the answer lies somewhere in the `pm2` docs. You should also be aware that you can start keystone manually with a custom server: https://www.keystonejs.com/guides/custom-server

Maybe that's helpful with pm2?

**Comment by bookyo** [comment]
thank you very much. awesome project!
