### ISSUE TITLE
[0.4] Filtering by relationship

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#1910]
Loading forever when invoked from toolbar:
![image](https://cloud.githubusercontent.com/assets/2730833/11579861/e0abc7ea-9a85-11e5-8d43-8e2a6424ce41.png)

Once applied, the related items are render:
![image](https://cloud.githubusercontent.com/assets/2730833/11579871/f456eaea-9a85-11e5-9b84-b47a258da481.png)

**Comment by erg0dic** [comment]
How can I reproduce this?

**Comment by jossmac** [comment]
Cannot reproduce. It appears to have been resolved since I opened this issue
