### ISSUE TITLE
[0.4] Default sort should be inherited

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#1911]
If no default sort is set, users never see the sort UI:
![image](https://cloud.githubusercontent.com/assets/2730833/11579904/3141ba66-9a86-11e5-9761-c220bb21a94f.png)

**Comment by JedWatson** [comment]
More info: this only happens on lists with no `name` mapping, from what I can tell...

**Comment by erg0dic** [comment]
Correct, if you have a name mapping in the schema the default sort will be on the column mapped to name.

The only property guaranteed to be available to sort on would be "id", but I didn't have any luck mapping name to "id" or "_id". 

Further, id/_id are not available for selection in the search UI.

**Comment by mxstbr** [comment]
I think this works now? I'll close this issue, feel free to reopen if you're still experiencing this issue!
