### ISSUE TITLE
ENOSPC error

### ISSUE THREAD

**Issue by ibriq** [keystonejs/keystone#1915]
I ran the Yeoman generator to create a Keystone website to play with. The website works well, it's just that a few minutes after I run `node keystone.ks`, usually at one of the first requests, it prints out the error listed below and then it dies. For the moment, pm2 keeps restarting it every time, so it works, but it's clearly not the best option. Do you have any idea what I could do to make Keystone.js stop running out of memory?

Thanks!

    GET / 200 398.654 ms
      Error: watch node_modules/node-sass/node_modules/oauth-sign ENOSPC
          at exports._errnoException (util.js:860:11)
          at FSWatcher.start (fs.js:1313:19)
          at Object.fs.watch (fs.js:1341:11)
          at createFsWatchInstance (/home/ubuntu/my-test-project/my-site/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:24:15)
          at setFsWatchListener (/home/ubuntu/my-test-project/my-site/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:47:19)
          at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/ubuntu/my-test-project/my-site/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:177:15)
          at EventEmitter.NodeFsHandler._handleDir (/home/ubuntu/my-test-project/my-site/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:301:8)
          at EventEmitter.<anonymous> (/home/ubuntu/my-test-project/my-site/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:342:12)
          at FSReqWrap.oncomplete (fs.js:82:15)
      root@vps-server:/home/ubuntu/my-test-project/my-site#

**Comment by morenoh149** [comment]
so we have a filesystem watcher. Then the oauth-sign seems to trigger a write to disk as `ENOSPC` means a write failed due to lack of disk space. Can you share the output of `df` on this box?

**Comment by ibriq** [comment]
Thank you for your attention to the issue I brought. Below I pasted the listing of the `df` command:

    Filesystem     1K-blocks    Used Available Use% Mounted on
    /dev/xvda1      16369496 2380184  13219036  16% /
    none                   4       0         4   0% /sys/fs/cgroup
    udev             1019284      12   1019272   1% /dev
    tmpfs             204852     348    204504   1% /run
    none                5120       0      5120   0% /run/lock
    none             1024240       0   1024240   0% /run/shm
    none              102400       0    102400   0% /run/user

I am using a custom theme I bought from Envato Market and that later I had integrated it to Keystone — the admin panel is pretty stable, but whenever I load one of those pages it kills the server instantly.

**Comment by KuroTsuto** [comment]
Many base Linux boxes set a considerably low default [inotify](https://en.wikipedia.org/wiki/Inotify) watch limit, which is often unsuitable for applications that watch a large number of files concurrently as the `pm2` package can (especially if pm2's [configured to actually watch your project](http://pm2.keymetrics.io/docs/usage/watch-and-restart/) - you can check if watching is enabled in the output of `pm2 monit`).

Somewhat counter-intuitively, `ENOSPC` might not signify a physical lack of disk-space in such scenarios, but rather that inotify's watch limit has been hit. You can increase your system's watch limit by setting `fs.inotify.max_user_watches` to a larger number in `/etc/sysctl.conf` (or your distribution's equivalent), i.e.

    fs.inotify.max_user_watches=524288

See [this StackExchange Q&A](http://unix.stackexchange.com/questions/13751) for more information regarding the practice, as well as a method for trial & error that can be applied should you wish to find a less arbitrary maximum.

**Comment by bpavot** [comment]
I had the same issue running Keystone with nunjucks on CloudFoundry (where max_user_watches is as low as 8192 and I don't think can be changed)

My workaround was to disable nunjucks watch with 
`nunjucks.configure(undefined, {watch: false});`

in keystone.js file.

Maybe that could be an improvement to automatically setup nunjucks that way in production env

**Comment by mxstbr** [comment]
This seems to have answered the question, so I'll close this issue! Thanks for jumping in @KuroTsuto and @bpavot!
