### ISSUE TITLE
CloudinaryImages folder option 

### ISSUE THREAD

**Issue by Benjamin23** [keystonejs/keystone#1918]
There is a problem  with uploading images to Cloudinary and automatically creating folder for them. When i use CloudinaryImage type in my database model and define the folder option, everything works. But if i change it to CloudinaryImages with the same option, the folder doesn't get created.

**Comment by Benjamin23** [comment]
I've determined that the issue is in the CloudinaryImagesTypes.js. On line 340 it checks for the property filenameAsPublicID, and since that option is not set it sets the uploadOptions to undefinded and the folder never gets created. I don't know what that option is supposed to do, so I'm reporting it as a bug.

**Comment by morenoh149** [comment]
are you sure? seems like it's defined on line 302. The conditional on line 323 only adds an extra field to `uploadOptions` if `filenameAsPublicID` is defined.

**Comment by Benjamin23** [comment]
yes you are correct. This looks differently than my version of keyston, but the version number is the same. I will check again tomorrow, but this will solve the issue.
