### ISSUE TITLE
Pre-fill the forms in the create form with default field values

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#192]

**Comment by AmayAgrawal** [comment]
So here basically you are talking about the default value or the placeholder thing

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/pre-fill-the-forms-in-the-create-form-with-default-field-values)!
