### ISSUE TITLE
Using keystone with a pre-existing project

### ISSUE THREAD

**Issue by TechRapport** [keystonejs/keystone#1925]
Hello,

Keystone seems really great!  Thanks for all of your hard work. 

I built a small keystone application to get a feel for it and I really like it. I run a web application that I think would benefit from the admin UI of keystone. 

For the past two days, I have been setting up Keystone within my app. 

I've been reading the docs and followed along with the "BYO Keystone / Express" section.  I keep running into the same error message and find myself wondering what is going on behind the scenes.  The message is: "Unknown Keystone List "User".  The db is definitely running and I passed it off to keystone. 

My question is this, when integrating keystone into an existing project built on express / mongoose, are there any keystone config settings I need to watch out for?  Reading the documents makes me think that keystone is specific about the route configuration and session management.  Will I have to pass off session management to keystone and reconfigure my routes to a keystone friendly format? Hopefully my question makes sense, but if not, I will post some code. Essentially, I'm having passport manage my sessions and then I have my controllers setup in ./controllers. My routes are configured in ./controllers/routes.  I believe I read somewhere that keystone's admin routes are hard coded.

I love the software and really hope that I can use it on my project. I'm just having a bit of difficulty in implementing it into a preexistting project. Any help or resources would be much appreciated.

**Comment by TechRapport** [comment]
Sorry. Not actually an issue. If there's somewhere else I should ask this question, feel free to close this. 

A bit more context: I am trying to use an existing user model for multiple permissions.  What I think would work is to have Keystone just manage admin sessions and I will pass off the session to keystone when an admin signs in. Of course this is not ideal, but it seems like having keystone manage all sessions means a complete makeover of my routes and controllers.

**Comment by morenoh149** [comment]
solution found in gitter
