### ISSUE TITLE
[0.4] Admin UI relationship does not referring correct URL

### ISSUE THREAD

**Issue by kossel** [keystonejs/keystone#1926]
Inside the admin UI, relationships does not mapping url correctly. 
Eg. in post table, user column element are mapping to 
`undefined/users/:id`
instead of
`/users/:id`

The cause is because 
in `keystone/fields/types/relationship/RelationshipColumn.js`
the variable `this.props.adminPath` is `undefined`
replace with `Keystone.adminPath` sovles the problem

Also RelationshipFilter.js  has the same bug

npm 3.5.0
keystone-demo 95fe3e60a63bbe57dcf4c0307fc799db4af50293

![image](https://cloud.githubusercontent.com/assets/1760498/11593287/168fd364-9a69-11e5-9faa-c3f36302def1.png)

**Comment by JedWatson** [comment]
Thanks for picking this up @kossel!

I've converted all references from `props.adminPath` to `Keystone.adminPath` for now. We're unfortunately passing that down through a lot of components and it needs to be externalised, or we'll make more mistakes like this as we rearrange the codebase.

**Comment by ericelliott** [comment]
Hmm.. seems like we should automate the testing of generated paths. =)

**Comment by JedWatson** [comment]
@ericelliott I read your comment and all I see is

> seems like we should automate the testing of _ALL THE THINGS_

:grinning:
