### ISSUE TITLE
Move GraphQL tests from Cypress to Jest for speed and happiness

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#193]
#166 introduced a bunch of access control tests (yay!), but they rely on spinning up an entire Cypress instance to run (boo!). #171 [includes examples](https://github.com/keystonejs/keystone-5/pull/171/files#diff-143c82c0f1ce77128936850059e7a873) of running graphql tests via Jest for much speed and many happy (wow!).

**Comment by dhuang612** [comment]
I would be interested in working on this!

**Comment by timleslie** [comment]
We now have extensive tests of the graphQL API using `jest` in the `api-tests` directory 👍
