### ISSUE TITLE
someting wrong in adminui

### ISSUE THREAD

**Issue by bookyo** [keystonejs/keystone#1933]
my lists:
```
keystone.createList('Category', {
  schemaDoc: '视频的类型',
  fields: {
    title: { type: Text, isRequired: true},
  },
  access: {
    update: access.userIsAdmin,
    create: access.userIsAdmin,
    delete: access.userIsAdmin,
  },
  label: '分类',
  labelField: 'title'
})

keystone.createList('Tag', {
  schemaDoc: '视频的标签，也可以说是分类。',
  fields: {
    title: { type: Text, isRequired: true },
    counts: { type: Integer, defaultValue: 0},
  },
  access: {
    update: access.userIsAdminOrOwner,
    create: access.userIsAdmin,
    delete: access.userIsAdmin,
    auth: true,
  },
  label: '标签',
  labelField: 'title',
})

keystone.createList('Video', {
  label: '视频',
  schemaDoc: '关键的视频数据，可以设置标题等信息',
  fields: {
    title: { type: Text, isRequired: true},
    category: { type: Relationship, ref: 'Category' },
    counts: { type: Integer, defaultValue: 0},
    createdAt: {
      type: DateTime,
      format: 'DD/MM/YYYY',
      defaultValue: new Date()
    },
    tags: { type: Relationship, ref: 'Tag', many: true },
    poster: { type: Text },
    summary: { type: Wysiwyg },
    url: { type: Text, isMultiline: true }
  },
  access: {
    update: access.userIsAdminOrOwner,
    create: access.userIsAdmin,
    delete: access.userIsAdmin,
    auth: true,
  },
})
```
bug: 
一、add tags fiels ，cant click × to delete。
![QQ图片20191107185635](https://user-images.githubusercontent.com/20472717/68383437-a1d17a80-0190-11ea-95fe-3f9f4eb3fb9f.png)
![QQ图片20191107185653](https://user-images.githubusercontent.com/20472717/68383440-a1d17a80-0190-11ea-867e-18dbb78edce9.png)

二、When create a video in adminui, includes fieds: category and tags. after save i cant go into http://127.0.0.1:3000/admin/videos, page is blank.
console show some error。
![QQ图片20191107185803](https://user-images.githubusercontent.com/20472717/68383467-adbd3c80-0190-11ea-97dc-bfb5a11b7f18.png)

**Comment by bookyo** [comment]
another question：
theres some way to use req.session in "keystone.extendGraphQLSchema({ mutations: [ {},  ],});"?

**Comment by bookyo** [comment]
and one thing: create anything all warning: Cannot read property 'refetch' of undefined

**Comment by Vultraz** [comment]
I've also seen the "Cannot read property 'refetch' of undefined" error.

**Comment by LiamAttClarke** [comment]
I'm experiencing the same issue. It seems to only affect lists with relational columns. Removing relational columns from `adminConfig.defaultColumns` fixes the error until the column is manually added via the visible column selector interface.

Furthermore, I have also seen the `Cannot read property 'refetch' of undefined` error when creating new objects.

**Comment by LiamAttClarke** [comment]
> and one thing: create anything all warning: Cannot read property 'refetch' of undefined

https://github.com/keystonejs/keystone/issues/1941

**Comment by MadeByMike** [comment]
I was able to verify the "Cannot refetch error but I could not replicate the errors you are seeing with videos.

My test worked fine with the same list definitions you posted:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/1320567/68630362-2e868a80-053b-11ea-9e71-0c9dd76e86da.png">

**Comment by bookyo** [comment]
@MadeByMike 
it only happens in the latest version. last week i deploy one project and dont view this error。

**Comment by minhdinhvq** [comment]
I have same issue for both `Cannot read property 'refetch' of undefined` and `Cannot read property of id of undefined` when I select columns to show on Relationships fields. :(

**Comment by MadeByMike** [comment]
@bookyo thanks, confirmed with the latest version. I will look at this in more depth again today.

**Comment by MadeByMike** [comment]
More context: works without the relationship fields.

**Comment by MadeByMike** [comment]
Update minimum reproducible example is this:

```
keystone.createList("Child", {
  fields: {
    title: { type: Text, isRequired: true }
  }
});

keystone.createList("Parent", {
  fields: {
    tags: { type: Relationship, ref: "Child" }
  }
});
```

**Comment by MadeByMike** [comment]
I't not happening in the mono-repo so maybe all we need to do is a release. My package versions are:

```
    "@keystonejs/adapter-mongoose": "^5.1.2",
    "@keystonejs/app-admin-ui": "^5.1.0",
    "@keystonejs/app-graphql": "^5.0.0",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.0.1",
    "@keystonejs/file-adapters": "^5.1.0",
    "@keystonejs/keystone": "^5.2.0",
```

**Comment by MadeByMike** [comment]
We've done a release and this should now be resolved with the latest Keystone packages.

**Comment by MadeByMike** [comment]
This is resolve and there is now a new issue for the refetch warning
