### ISSUE TITLE
babel-6 .babelrc build errors due to unknown options

### ISSUE THREAD

**Issue by Cspeisman** [keystonejs/keystone#1934]
```
keystone/admin/src/fields.js
keystone/admin/src/views/home.js
keystone/admin/src/views/list.js
keystone/admin/src/views/item.js
```
All encounter build errors due to me having a `.babelrc` file in my project root directory with configurations for babel6

I get error messages that look like this:
```
error building fields.js:
[BABEL] /Users/cspeisman/Sites/project_inception/node_modules/keystone/admin/src/fields.js: Unknown option: /Users/cspeisman/Sites/project_inception/.babelrc.presets while parsing file: /Users/cspeisman/Sites/project_inception/node_modules/keystone/admin/src/fields.js
```

**Comment by ericelliott** [comment]
can you show the `.babelrc` file contents?

**Comment by Cspeisman** [comment]
@ericelliott 
```
{
  "presets": ["es2015"]
}
'''

**Comment by ericelliott** [comment]
And what version of Keystone is your project using?

**Comment by Cspeisman** [comment]
I've seen the issue on both 3.15 and 3.16

**Comment by ericelliott** [comment]
What does your package.json look like?

**Comment by Cspeisman** [comment]
@ericelliott sorry about the delay. Here is my package.json file: 

```
{
  "name": "project_inception",
  "version": "1.0.0",
  "description": "internal DD playbook",
  "main": "index.js",
  "scripts": {
    "start": "node ./keystone.js"
  },
  "author": "Corey Speisman <cspeisman@gmail.com> (http://github.com/cspeisman)",
  "license": "ISC",
  "dependencies": {
    "keystone": "^0.3.16"
  },
  "devDependencies": {
    "babel-cli": "^6.3.15",
    "babel-preset-es2015": "^6.3.13"
  }
}
```

**Comment by ericelliott** [comment]
Looks like you're trying to use the 6.x Babel API with a version of keystone that isn't compatible with it. Two ways forward:

* Use the (experimental) 0.4.x Keystone, or..
* Use the 5.x.x Babel line (including all Babel utils, as well)

**Comment by Cspeisman** [comment]
:+1: Thanks @ericelliott 
Is it worth opening a ticket for 6.x Babel support in 0.3.x Keystone or keep it as is?

**Comment by ericelliott** [comment]
I think that's a question for @JedWatson. IMO, our priority should be to release the next stable version, instead.

Which means we should decide the scope of what's going into it and start working toward a finished milestone ASAP. =)

**Comment by pipinov** [comment]
I solved this problem for myself. 

Keystone 0.3 use react 0.13 and babel 5, but I need to use babel 6 and react 0.14. I use react for first server side rendering.

I go to /node_modules/keystone and run npm i, after that all keystone dependencies will installed in keystone/node_modules. After that i go to root of my project and install react 0.14 react-dom and babel 6.

Ok, after that I place my react components in public/components and put .babelrc file in public directory.
```
{
	presets: ["react", "es2015"]
}
```

**Comment by ericelliott** [comment]
:+1:
