### ISSUE TITLE
Node v5.1.0 Issue

### ISSUE THREAD

**Issue by miketlawrence** [keystonejs/keystone#1935]
I am using Node v5.1.0. Is this version of Node supported. I'm having issues getting Node Sass to work on this version.

When I try and run <code>nodemon</code> I get the error:
<code>Error: `libsass` bindings not found. Try reinstalling `node-sass`?</code>

**Comment by morenoh149** [comment]
We may have fixed that in the generator here https://github.com/keystonejs/generator-keystone/commit/a4bbe486d12cbbea2fadb071e334210b2676f9e8 try using generator version 0.3.10

**Comment by megheaiulian** [comment]
I am using node 5.1.0 and keystone is working fine ...

**Comment by okjake** [comment]
A workaround is to remove `node-sass` and `node-sass-middleware` from your package.json and reinstall them with `npm install --save node-sass node-sass-middleware`

**Comment by morenoh149** [comment]
closing. If @miketlawrence is still experiencing this issue please chime in.
