### ISSUE TITLE
Weirdness with the Content field

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#1935]
# Bug report

## Describe the bug

I have a list set up like so:
```js
const { Text, DateTime, Url } = require('@keystonejs/fields');
const { Content } = require('@keystonejs/field-content');
const { heading, link } = Content.blocks;

module.exports = {
    fields: {
        name: { type: Text },
        date: { type: DateTime },
        body: { type: Content, blocks: [heading, link] },
        link: { type: Url },
      },
}
```

In the admin UI, few issues:
1. I can only click on the highlighted div despite the viewable area being much higher.
2. There's  weird visual... something that appears to the side when focused (highlighted in red).
3. Clicking the box also causes the console error shown to appears
4. Adding the blocks to my schema didn't seem to change anything about the editing section.

![image](https://user-images.githubusercontent.com/3558659/68416489-af1a5380-01e8-11ea-913a-9e27471da7c2.png)

## System information

- OS: Windows 10 1903
- Browser: Chrome 78

**Comment by Vultraz** [comment]
There's also this error in the console after selecting:
```
backend.js:6 Warning: React does not recognize the `indicatorVariant` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `indicatorvariant` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by Context.Consumer)
    in EmotionCssPropInternal (created by ForwardRef(ButtonElementComponent))
    in ForwardRef(ButtonElementComponent) (created by PseudoState)
    in PseudoState (created by ForwardRef)
    in ForwardRef (created by ForwardRef(LoadingButtonComponent))
    in ForwardRef(LoadingButtonComponent) (at Footer.js:82)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (at Footer.js:81)
    in div (created by Context.Consumer)
    in Toolbar (at Footer.js:80)
    in Footer (at Item/index.js:356)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by Card)
    in Card (created by Context.Consumer)
    in EmotionCssPropInternal (at Item/index.js:295)
    in ItemDetails (created by Context.Consumer)
    in withRouter(ItemDetails) (at Item/index.js:456)
    in Mutation (at Item/index.js:436)
    in div (created by Context.Consumer)
    in Styled(div) (at Item/index.js:435)
    in main (at Item/index.js:431)
    in Query (at Item/index.js:395)
    in Suspense (at Item/index.js:392)
    in ItemPage (at client/index.js:79)
    in Route (at client/index.js:71)
    in Switch (at client/index.js:62)
    in Route (at client/index.js:112)
    in Switch (at client/index.js:109)
    in Suspense (at client/index.js:108)
    in div (created by Context.Consumer)
    in Page (at Nav/index.js:413)
    in div (created by Context.Consumer)
    in PageWrapper (at Nav/index.js:358)
    in ResizeHandler (at KeyboardShortcuts.js:73)
    in KeyboardConsumer (at KeyboardShortcuts.js:73)
    in Unknown (at Nav/index.js:344)
    in Nav (created by Context.Consumer)
    in withRouter(Nav) (at client/index.js:107)
    in ScrollToTop (created by Context.Consumer)
    in withRouter(ScrollToTop) (at client/index.js:106)
    in Route (at client/index.js:105)
    in Switch (at client/index.js:100)
    in Router (created by BrowserRouter)
    in BrowserRouter (at client/index.js:99)
    in ToastProvider (at client/index.js:96)
    in KeyboardShortcuts (at client/index.js:95)
    in ApolloProvider (at client/index.js:94)
    in HooksProvider (at client/index.js:93)
    in KeystoneAdminUI (at client/index.js:136)
    in Suspense (at client/index.js:135)
```

**Comment by jesstelford** [comment]
I've seen these issues also.

For whoever picks these up, here is what I know so far:

> 1. I can only click on the highlighted div despite the viewable area being much higher.

I think this is a styling issue on the Slate element. We need to make sure the min-height is 100% so it can also expand to be higher than the containing input area.

> 2. There's weird visual... something that appears to the side when focused (highlighted in red).

That's the action menu (where you can select to insert things like Images, etc, if those blocks are included), but it's given a low z-index and is showing behind the create modal. If you save that item, then edit it from the details screen you'll see it's given the correct z-index and is a circle with `+` in it.

Ideally, this shouldn't by visible at all if there are no action items from blocks, which I don't think `heading` or `link` have.

> 3. Clicking the box also causes the console error shown to appears

AFAIK, this is coming from within Slate, and doesn't actually cause any errors.

> 4. Adding the blocks to my schema didn't seem to change anything about the editing section.

The formatting options are non-obvious; you have to first select text, then a popup window will appear to allow selecting of "Header" or "Link". This probably should be surfaced as a toolbar at the top of the input area also.
