### ISSUE TITLE
0.4:  Cannot navigate to item

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1936]
I have a list for which I cannot navigate to the item:

![image](https://cloud.githubusercontent.com/assets/5872515/11645212/8083f50c-9d20-11e5-8b84-fd9276a173a5.png)

~~The only odd thing about that page is that I haven't populated the site logo for the item (optional), yet, and thus that may be throwing off the ability to click the name column to navigate to the item.  No relevant console logs appear.~~

Update:  It seems not populating the logo is irrelevant.  I populated it and still cannot navigate to the item since neither the logo nor the name is clickable.  Worked just fine in 0.3

**Comment by webteckie** [comment]
fyi...updated issue above

**Comment by JedWatson** [comment]
@webteckie can you share the `List` definition please? I think it's getting confused because there's a name column but it's not first in the row.

**Comment by webteckie** [comment]
@JedWatson sent (via slack)

**Comment by webteckie** [comment]
@JedWatson @jossmac more info on this:

- It seems as though you put a default column of field type CloudinaryImage as the first column (you cannot view the item at all)
- If you make the field type CloudinaryImage the second default column and the name (String) the first column then it works but you cannot click on the second column
- if you add columns of Type.Url it throws a warning:  `Invalid Column specified: <column-name>`

I'm assuming there are other fields in the list, which may cause similar issues when used as default columns.

**Comment by mxstbr** [comment]
I'm pretty sure this is fixed with #2566, so I'll close this for now. Let me know if it still doesn't work, I couldn't replicate!
