### ISSUE TITLE
Add a Semver field type

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#1937]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to keep track of which version of my application was used to create/update certain items. I can always use a `Text` field to store this information, but that does not provide any support for doing comparisons as part of the graphQL query. I would like to have a field type where I can make queries such as "show me all the items updated with a version less than `x.y.z`", etc.

## Describe the solution you'd like

I would like there to be a `Semver` field type, which provides a rich range of filtering and validation options.

## Additional context

Semver has a [well defined spec](https://semver.org/spec/v2.0.0.html) which we should follow. There is a [postgres extension](https://pgxn.org/dist/semver/doc/semver.html) which provides a lot of the functionality this field type will require for the postgres adapter. Its API should also help inform the kind of filtering operations we want to support in the graphQL API.

**Comment by MadeByMike** [comment]
@timleslie feels like a good use-case for a list plugin? Maybe not a contrib package too?

**Comment by timleslie** [comment]
> @timleslie feels like a good use-case for a list plugin?

See #1938 :-)
