### ISSUE TITLE
0.4:  Relationship references appear to be broken

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1937]
Defining a relationship:
```
MyList.relationship({ ref: 'OtherList', refPath: 'that' , path: 'this'});
```
does not seem to work in the latest.  The relationships do not show.

**Comment by dracupid** [comment]
I met the same problem migrating from 0.3.x to 0.4. In my case, the Relationships block does show, while no related items is listed.

**Comment by dracupid** [comment]
@webteckie I am not sure whether my PR be able to solve you problem, but it did solve mine. Please have a try!

**Comment by webteckie** [comment]
I will close this because the particular issue as reported is fixed.  But I'll open other related issues as some setups do not look right.
