### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by Deva7** [keystonejs/keystone#1939]
# Bug report

## Describe the bug
Keystone list level 'Search' is not working even after adding filters

## Expected behaviour
With filters and without filters List level Search should work checking the entire items in the list.

## System information

- OS: [ macOS, Windows]
- Browser [chrome, safari]

**Comment by MadeByMike** [comment]
@timleslie @jesstelford  - What do we want to do about this one? Is search a viable option in a future with many more 'Db' Adapters? I think we should make the search an optional feature triggered by the adapter. Any thoughts?

**Comment by german-st** [comment]
Hello.
I have the same problem. After entering text in search field, the list does not change. Only the use of filters is works. We are use Knex adapter. Thank's

**System information**
- OS: [Ubuntu 18.04, Windows]
- Browser: [chrome, safari]
- DB: PostgreSQL 10.10
