### ISSUE TITLE
Install KeystoneJS from nothingness with an external  database? (atlas)

### ISSUE THREAD

**Issue by ffxivguild** [keystonejs/keystone#1940]
As the title implies, I'm curious about Keystone so I tried the quickstart guide for v5. I don't use local mongodb, as I have a test cluster on atlas for such things. How do I change the database variables - it's nowhere to be found... old posts refer to a .env file I can edit... which again is nowhere to be found. 

I'm exceptionally weak at starting up these kinds of projects, so maybe I'm missing something here. I guess it boils down to "How do I use an external database?".

I found adapter-mongoose.js, and I can setup my variables at the core index.js file... how would I know what variable names to use in the first place ?

**Comment by Vultraz** [comment]
You can pass the database address to the `MongooseAdapter` constuctor, like so:
```js
const { Keystone } = require('@keystonejs/keystone');
const { MongooseAdapter } = require('@keystonejs/adapter-mongoose');

const keystone = new Keystone({
  adapter = new MongooseAdapter({ moingoUri: 'mongodb://address/of/atlas/cluster' })
})
```

You can also set one of the environment variables listed [here](https://www.keystonejs.com/keystonejs/adapter-mongoose/#api-new-mongooseadapteroptions) if you don't want to keep the address in your production code.

If you don't already have a `.env` file you can just create one and add this line to the top of your `index.js` file:
```js
require('dotenv').config()
```

Then, inside the `.env` file...
```
MONGO_URI=mongodb://path/to/atlas/cluster
```

**Comment by ffxivguild** [comment]
Thank you! I figured it out before you replied... 

I wonder if quickstart guide should allow the use of external DB's...

**Comment by liamlevesque** [comment]
Agree - this should be covered in db setup in the docs IMO

**Comment by maheraldous** [comment]
Anyone have the fix for this code
It won't let me connect to the database

```
const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new Adapter({ mongoUri: "mongodb+srv://maheradmin:<password>@cluster0.w2n89.mongodb.net/<dbname>?retryWrites=true&w=majority" }),
});
```

This is my Clusters https://prnt.sc/u8kfef
