### ISSUE TITLE
Universal Routing

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1941]
I need Universal Routing for my apps, and it looks like it is already under discussion. I figured this might be a good place to keep track of implementation details & collect feedback.

It seems to me that routing should be a pretty simple drop-in replacement in most apps. I thought at first there might be a lot of hooks into the routing system for middleware, etc, but a cursory glance at the code only reveals a few potential breaking spots. If you know of others, please chime in:

cursory glance over potential breaks:
- [ ] https://github.com/keystonejs/keystone/blob/3c20f30981480104037aae8adbe4a6c89ea4a1fd/admin/server/app/createDynamicRouter.js
- [ ]  https://github.com/keystonejs/keystone/blob/2c2fab2641bec11616bfaa09fe4c8e2168a5fe94/lib/core/redirect.js
- [ ] Not sure about this? What is this importing, exactly? https://github.com/keystonejs/keystone/blob/2c2fab2641bec11616bfaa09fe4c8e2168a5fe94/lib/core/importer.js

Are there more middleware hooks I should be aware of?

There's also a test getKeystone helper that will probably need fixing.

For implementation, I'm looking at [Redux Simple Router](https://github.com/jlongster/redux-simple-router). Happy to discuss other options.

See also:
- https://github.com/keystonejs/keystone/issues/1592
- https://github.com/keystonejs/keystone/issues/1897

cc @JedWatson

**Comment by LorbusChris** [comment]
> For implementation, I'm looking at Redux Simple Router. Happy to discuss other options.

I've been wondering how much this would opinionate Keystone as a framework. How about simply using React Router, leaving the choice of further react router integration up to the App?

Personally I'd be interested in a Relay/GraphQL Implementation using [React-Router-Relay](https://github.com/relay-tools/react-router-relay) for my website's public (/frontend/non-admin) UI. Relay will hopefully soon become universal/isomorphic: https://github.com/facebook/relay/issues/589 , this could be great!

**Comment by ericelliott** [comment]
> I've been wondering how much this would opinionate Keystone as a framework. How about simply using React Router, leaving the choice of further react router integration up to the App?

Redux simple router does use React Router, and takes a minimalist approach to it.

> Personally I'd be interested in a Relay/GraphQL Implementation using React-Router-Relay for my website's public (/frontend/non-admin) UI. Relay will hopefully soon become universal/isomorphic: facebook/relay#589 , this could be great!

Since redux-simple-router is really just a thin integration with React Router, we may be able to support both.

**Comment by gautamsi** [comment]
Keystone 4 is going in maintenance mode. Expect no major change. see #4913 for details.
[Keystone v5](https://github.com/keystonejs/keystone-5) is using GraphQL extensively and one of the few examples are based on SSR with Next.js for React.
