### ISSUE TITLE
Issue running demo projects

### ISSUE THREAD

**Issue by Greg1992** [keystonejs/keystone#1944]
# Bug report

## Describe the bug

When running any of the commands listed in keystone.README,md for the demo projects.

yarn demo blog dev

I run into an error each time. That prevents me being able to try anything.

## Screenshots
![image](https://user-images.githubusercontent.com/37276159/68549027-9037df00-03eb-11ea-9205-da274fe2fe9b.png)

## System information
Windows 10

**Comment by jesstelford** [comment]
Looks like you've cloned the Keystone repo and are trying to run the demo projects from there. Can you confirm that you ran `yarn` in the root directory after cloning?

That should setup the yarn workspaces correctly, leading to a correctly installed set of dependencies (including the Mongoose adapter).

**Comment by MadeByMike** [comment]
I spoke with Greg on our slack and I'm pretty sure this was an issue with using yarn workspaces.

**Comment by Greg1992** [comment]
Hiya all, I've tried once again going through the instructions and the advice given here, this is what i'm getting (which i was getting before but i took note notice) 

![image](https://user-images.githubusercontent.com/37276159/69920827-82bec380-1484-11ea-98c8-17f2fcb820f9.png)
