### ISSUE TITLE
Pass "require" variable to jade

### ISSUE THREAD

**Issue by DenDix** [keystonejs/keystone#1945]
I created a node module which contains one simple js file. I want to use this js function inside my jade file. In music.js I require the module "myplayer":

    var keystone = require('keystone');
    exports = module.exports = function(req, res) {
    	var view = new keystone.View(req, res);
	var locals = res.locals;
        locals.myplayer = require('myplayer');
    	// locals.section is used to set the currently selected
	// item in the header navigation.
    	locals.section = 'music';
	// Render the view
    view.render('music');
    };

I know that it is accessing this file because I have a console print statement contained inside the myplayer js file that appears in my terminal when I go to music.jade in my browser.
Then in my music.jade file I try to use the myplayer function, myplayer().tryplay.

    extends ../layouts/default
    block content
  	.container: .jumbotron
		img(src='/images/logo.svg', width='160')
		h1 Welcome
		audio#test(controls='')
			source(src='/mymusic/cold.mp3')
			| Your browser does not support the audio element.
		button Click me
			if (section == 'music')
				li sees variable
		p The Music page is currently under construction
		hr
    block js		
 	script.
		$(document).ready(function(){
		$("button").click(myplayer().tryplay)	
		});

It seems like I'm passing the variable correctly since I'm doing exactly the same as locals.section, which effects whether "sees variable" gets printed. 

The error I get is "Reference Error: myplayer is not defined"

So I have a number of questions. Is the "if (section == 'music')" statement actually a jquery command, not css? But I don't see a "$" or anything to signify that.

"Section" clearly is a variable of value "music", but I can't figure out how to print it out either inside the music.jade css script or in the internal javascript.

And last, of course is, why can't "$("button").click(myplayer().tryplay)" find the variable myplayer?

It seems like I'm just making simple syntax errors, but I'm afraid I'm really lost.

Thanks for any help.

**Comment by webteckie** [comment]
@DenDix have you tried interpolating the myplayer var using !{}...something like:
```
script.
    var myPlayer = !{myplayer}
    $(document).ready(function(){
    $("button").click(myPlayer().tryplay)   
    });
```

I think you first need to transfer the locals value from the jade context (executed in the server) to the client context.

**Comment by DenDix** [comment]
If I do the above I get this error:
SyntaxError: missing ] after element list
I'm also asking the same question on stackoverflow. Here's the link:
http://stackoverflow.com/questions/34171941/in-node-js-how-do-you-pass-a-require-object-to-jade
The comment I got there made me think I shouldn't be using "locals" since locals are strings, not functions?
So I made changes so as not to use "locals" but I'm still getting the error:
ReferenceError: myplayer is not defined
Any ideas?

**Comment by webteckie** [comment]
Can you no ship the player to the client via a regular script tag?

**Comment by DenDix** [comment]
I don't understand what "no ship" means. 
But from this link:
http://stackoverflow.com/questions/24397379/script-path-for-expressjs-in-node-modules
 I realized I'm not supposed to access node_modules functions with music.jade. I would have to add a new route in keystone.
     app.use(express.static(path.join(__dirname, 'node_modules')));
I was trying to work my way towards running jplayer from a node_modules, but apparently I should have installed it using bower, I think.
I left a more complete description on my stackoverflow post:
 http://stackoverflow.com/questions/34171941/in-node-js-how-do-you-pass-a-require-object-to-jade
Thanks for your help.

**Comment by morenoh149** [comment]
*not ship
