### ISSUE TITLE
Getting Error ETIMEDOUT after running for a while

### ISSUE THREAD

**Issue by terenzeyuen** [keystonejs/keystone#1948]
Pulled latest version and after successfully running KeystoneJS for a few minutes, it throws an connect ETIMEDOUT error. Looks like Mongo but shouldn't it not being able to start if it is? Mongo is running fine.

Error: connect ETIMEDOUT localhost:27017
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by morenoh149** [comment]
not necessarily. Things can timeout over time if there is a queue of work for example. Though I have no idea what's going on in your situation. Please share more relevant information.

**Comment by terenzeyuen** [comment]
Not getting it now, closing
