### ISSUE TITLE
Option to choose what to display in relationship field

### ISSUE THREAD

**Issue by TomKremer** [keystonejs/keystone#1949]
Hello,

I got a particular issue with relationships. My models work fine but for usability improvement, I need to display another value than the mapped field. Is this currently possible or is there a workaround?

Best,
Tom

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by christopherreay** [comment]
it would be 100% vastly more better to open the request yourself and link to it from here!
