### ISSUE TITLE
Change Cloudinary upload folder before uploading 

### ISSUE THREAD

**Issue by Benjamin23** [keystonejs/keystone#1954]
Hello, I was wondering if it is possible to change cloudinary folder option of the CloudinaryImageType  based on a field value or username. I know that the folder option can be set in the Model file, but I need to set the folder option based on some other parameter before uploading.

**Comment by megheaiulian** [comment]
if you have a field called "images" you can do something like this:
```
//Cloudinary folder virtuals
Schema.virtual('images.folder').get(function() { return 'some/other/path'; });
```

**Comment by Benjamin23** [comment]
Thanks man, I think this is going to work. I'll try it out and get back to you with the results :)

**Comment by Benjamin23** [comment]
The solution that you proposed unfortunately did not work since the folder is an CloudinaryImageTypes property, and not a custom defined. I found a solution for this. Before calling the updateHandler in my function, i set the custom folder location over: keystone.set('cloudinary customFolder', 'some/other/path'). https://github.com/keystonejs/keystone/blob/master/fields/types/cloudinaryimages/CloudinaryImagesType.js#L82 I have added a line that checks if the customFolder has been set. The funciton now looks like this.
```javascript
if (keystone.get('cloudinary folders')) {
			if (field.options.folder) {
				folderValue = field.options.folder;
			} else {
				if(keystone.get('cloudinary customFolder')) {
					folderValue = keystone.get('cloudinary customFolder');
				} else {
					var folderList = keystone.get('cloudinary prefix') ? [keystone.get('cloudinary prefix')] : [];
				folderList.push(field.list.path);
				folderList.push(field.path);
				folderValue = folderList.join('/');
				}
			}
		}
 ```

**Comment by Benjamin23** [comment]
I got it to work by using the virtual method. But instead of get, i used the set method. 
```javascript
Schema.virtual('photos.folder')
	.set(function(title) {
		this.photos.folder = title;	
	});
```
