### ISSUE TITLE
Admin: Ability to specify Admin Slug

### ISSUE THREAD

**Issue by walker** [keystonejs/keystone#1955]
I think, as another option (in addition to headless), there should be the ability to set the 'admin slug' (or some such option name) that defaults to 'keystone' if not set by the user either in process.ENV or keystone.js....

**Comment by jonathanp** [comment]
Such an option already exists, they key is `'admin path'`. Unfortunately it's not documented yet though.

It was added in the https://github.com/keystonejs/keystone/pull/1820 PR.
