### ISSUE TITLE
Admin View Templates: Standardize single or double quotes

### ISSUE THREAD

**Issue by walker** [keystonejs/keystone#1956]
This is _really_ minor, but, I still think, important! I'd be willing to submit a PR for it, but for such a minor change, I didn't want to presume.

In the admin UI's jade templates there's a mix-and-match of single & double quotes. It might be nice to choose one (in certain circumstances) throughout.

For instance, [here](https://github.com/keystonejs/keystone/blob/master/admin/server/templates/includes/script/components.jade):

Where on [line#2](https://github.com/keystonejs/keystone/blob/master/admin/server/templates/includes/script/components.jade#L2):

```
script(src="#{adminPath}/js/lib/move/move-0.1.1.min.js")
```

Where on [line#9](https://github.com/keystonejs/keystone/blob/master/admin/server/templates/includes/script/components.jade#L9):

```
script(src='#{adminPath}/js/lib/jqueryfileupload/vendor/jquery.ui.widget.js')
```

**Comment by mxstbr** [comment]
Sorry for the late reply, we'd definitely appreciate you fixing the code style once #2566 has landed! Due to the age of this issue I'll close it, but feel free to comment again and I'll reopen it!
