### ISSUE TITLE
"View related items" link breaks with integer id fields

### ISSUE THREAD

**Issue by LiamAttClarke** [keystonejs/keystone#1958]
# Bug report

## Describe the bug

Clicking "View related items" on a Relationship field with `many: true` links to an unfiltered list.

After some invesitigation:
This issue only exists when using KnexAdapter. KnexAdapter uses the IntegerField for ids which does not have an `in` or `not_in` filter option.

## To Reproduce

1. Setup a project with the KnexAdapter
2. Setup a one-to-many relationship field:
```
// User model
{
  fields: {
    posts: { type: Relationship, ref: 'Post.user', many: true }
  }
}
```
3. Associate Posts to a User
4. Click "View related items" beside the User.posts field.
5. :'(

## Expected behaviour

When using KnexAdapter, clicking "View related items" on a one-to-many Relationship field should navigate to a filtered list of items.

**Comment by timleslie** [comment]
Closing this as I have confirmed that the reproduction steps no longer result in an error.
