### ISSUE TITLE
Cannot read property 'refetch' of undefined

### ISSUE THREAD

**Issue by johnnykramer** [keystonejs/keystone#1962]
# Bug report

## Describe the bug

I want to create new entity in the DB using Admin UI.
But when I filled form and click 'Create' button I got notification `Cannot read property 'refetch' of undefined`. Then was opened edit view and I clicked 'Save Changes' and got positive notification :)

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. `yarn create keystone-app my-test-app`
2. `keystone.createList("test", {
  fields: {
    title: { type: Text }
  }
});`

## Expected behaviour

Don't show error notification and successfully saved new entity.

## Screenshots

https://www.dropbox.com/s/5zatk8tay75awaz/Screenshot%202019-11-14%2017.22.27.png?dl=0

## System information

- OS: macOS 10.15
- Browser: Google Chrome 78.0.3904.97

**Comment by will8137** [comment]
Can confirm this. 

Been adding lists and get the same error!

**Comment by kristjaningi** [comment]
Getting the same error when using createList

**Comment by MadeByMike** [comment]
Hey everyone, this is confirmed and on my list. It's a very visible bug, but not causing any problems so it might be a week or two before I land a fix for this one. Apologies for any alarm caused.

**Comment by Vultraz** [comment]
Fixed by #2080

**Comment by cloud90bk** [comment]
Hi, I've updated the node modules but still have the error message. It has been released?
I use this version now:
"@keystonejs/adapter-mongoose": "5.1.3",
    "@keystonejs/app-admin-ui": "5.4.0",
    "@keystonejs/app-graphql": "5.0.1",
    "@keystonejs/app-static": "5.0.0",
    "@keystonejs/auth-password": "5.0.1",
    "@keystonejs/fields": "6.0.1",
    "@keystonejs/file-adapters": "5.2.0",
    "@keystonejs/keystone": "5.3.0",
