### ISSUE TITLE
CalendarDay `date: null` when `isRequired: true`

### ISSUE THREAD

**Issue by omarchehab98** [keystonejs/keystone#1964]
# Bug report

## Describe the bug

When `CalendarDay` is required, creating fails because the GraphQL request sends the field value as `null` regardless of what the user input.

## To Reproduce

1. Define a list with `CalendarDay` `isRequired: true`

```
date: {
    type: CalendarDay,
    format: 'Do MMMM YYYY',
    yearRangeTo: new Date().getFullYear() + 30,
    isRequired: true,
},
```
2. Create a new item in that list and set the date field value

![image](https://user-images.githubusercontent.com/12089120/68978392-a1586580-07c8-11ea-8841-925b198d2e94.png)

3. Click create

![image](https://user-images.githubusercontent.com/12089120/68978420-b208db80-07c8-11ea-88db-07776a879bed.png)

4. Observe outgoing GraphQL request payload

```js
{"operationName":"create","variables":{"data":{"date":null, ...}}}
```

## Expected behaviour

It should send the date value.

## System information

- OS: MacOS
- Browser: Chrome
- Keystone Versions
- Keystone Database: Postgres

```
    "@keystonejs/fields": "^5.2.0",
    "@keystonejs/keystone": "^5.0.0",
```

**Comment by Vultraz** [comment]
This seems to be a deeper problem with the field... I can't actually seem to save *any* data value. :/
