### ISSUE TITLE
[0.4]: Cloudinary Images uploading (0.4.0 - Demo - Galleries List)

### ISSUE THREAD

**Issue by cantuket** [keystonejs/keystone#1967]
This one is kind of obscure, but figured I'd mention it. 

If you...
1) add multiple images 
2) don't save them
3) add more images to batch
4) save images

It will blow away the first group of images and will only save the second group of images.

**Comment by mxstbr** [comment]
We're going to rework the storage fields after 0.4, so I'll close this issue for now! Thanks for reporting it!
