### ISSUE TITLE
What's default user name and password to login admin ui

### ISSUE THREAD

**Issue by hades217** [keystonejs/keystone#1969]
# Question about Keystone

GitHub Issues are reserved for Bug reports and Feature requests.

The best place to get a question answered is sign-up to our Slack: https://launchpass.com/keystonejs

**Comment by Vultraz** [comment]
There is no default username and password. You'll need to disable authentication and remove access controls from the User list (if you're using the project template)  and create an initial user manually.

**Comment by bookyo** [comment]
ni must create a User, link: https://www.keystonejs.com/guides/authentication  , you can follow this doc.

**Comment by bookyo** [comment]
hi man, i have a solution can create default user.
use mongo
use yourcollection
db.users.create({email: 'admin@admin.com', password: '$2b$10$GkB7C5CIGbh8.9BzhQ1GOOjg3fyYg6EcUZ/xL24lG/d5UFpd8fD/S', isAdmin: true});

try it.  admin@admin.com adminadmin

**Comment by lazurey** [comment]
> ni must create a User, link: https://www.keystonejs.com/guides/authentication , you can follow this doc.

It will be really appreciated if this is written clearly in quick start page. I've been searching for the username and password for an hour.

**Comment by tedyyu** [comment]
the successful hack is 
`db.users.insert({email: 'admin@admin.com', password: '$2b$10$GkB7C5CIGbh8.9BzhQ1GOOjg3fyYg6EcUZ/xL24lG/d5UFpd8fD/S', isAdmin: true});`

as there is no .create method.
