### ISSUE TITLE
Return specific invalid field paths from the updateHandler when validation fails

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#197]
Currently you only get the field path itself.

It would be useful to know that (for example) `location.street1` was valid but `location.suburb` was the field that caused the validation fail on the `location` field, so individual inputs can be hi lighted as having errors without additional logic in the route controller.

**Comment by wmertens** [comment]
@JedWatson Did this change with the v0.4 changes?

I think this and several other problems can be solved generally by making the models recursive. The Lists themselves are still collections of Model instances, but the UI simply works on individual objects and each sub-array and sub-object gets another UI instance. With React, this is easy and works great.

**Comment by mxstbr** [comment]
This is on the roadmap already, we're going to replace the updateHandler completely for the new API. I'll close this issue for now!
