### ISSUE TITLE
[0.4]: Modal inputs lose focus

### ISSUE THREAD

**Issue by zewt112** [keystonejs/keystone#1970]
On the v0.4.0 keystone-test-project, all modal text inputs lose focus after every keydown, eg new post modal. You can bring focus back to the input, with some difficulty.

![image](https://cloud.githubusercontent.com/assets/5418359/11761088/27710812-a0ac-11e5-986c-daffdef56d03.png)

**Comment by jonathanp** [comment]
Thanks for bug report! Since this is a duplicate of #1958 I'm closing this.
