### ISSUE TITLE
New item name dialog deselects after every keystroke

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1973]
![aargh](http://g.recordit.co/YFKr6dEgUG.gif)

(╯°□°)╯︵ ┻━┻

[Repro here](https://github.com/ericelliott/universal-keystone-boilerplate/tree/c95632846a2d0ff74af7d12543032751635df54b)

**Comment by JedWatson** [comment]
This shouldn't happen any more - there was an issue with the `Modal` component introduced into Elemental that added accessibility features that conflict with the way focus is handled in Keystone.

If you update everything (keystone, and elemental if that is also linked) this will be resolved.

**Comment by ericelliott** [comment]
This is not fixed. );

**Comment by ericelliott** [comment]
Additionally - pressing the spacebar breaks the universe:

![universe asplodes](http://g.recordit.co/S2IXknC9EW.gif)

◔̯◔

**Comment by ericelliott** [comment]
All good now.
