### ISSUE TITLE
Relationship filed in admin UI stuck with loading...

### ISSUE THREAD

**Issue by piermariacosina** [keystonejs/keystone#1974]
I don't know when this issue begun maybe updating keystone but the relationship in the admin UI now shows always 

Loading... without showing the dropdown 

in the console there is two errors
Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/keystone/js/fields.js:4627 Uncaught Error: Not Found

the relationship in the model looks like this 

services: { type: Types.Relationship, ref: 'Service',filters: { state: 'published' }, many: true }

**Comment by creynders** [comment]
That's keystone v0.3.x right? It's a bug with a relationship reference to a no longer existing document.

**Comment by piermariacosina** [comment]
Yes it is, is there a more stable version? I need a fix asap

**Comment by piermariacosina** [comment]
0.3.16

**Comment by jjakshay** [comment]
I have the version 0.3.16, Still Admin UI is getting stuck while loading the filtered contents according to the relationship reference.

**Comment by olivierlizotte** [comment]
Any known workaround / Fix ?

**Comment by grdunn** [comment]
Having the same issue now.

**Comment by piermariacosina** [comment]
The only workaround I've found is rolling back to 0.2.42
npm install keystone@0.2.42 --save
this fix also the issue with image preview for localfiles

**Comment by grdunn** [comment]
@piermariacosina i didn't even know image preview for local was an option. always assumed mine not working was standard functionality. thanks.

**Comment by mxstbr** [comment]
Fixed after #2566 lands!
