### ISSUE TITLE
0.4: List models with nocreate set to true should not offer create option

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1978]
Mark a list as nocreate: true, for example:
```
var MyList = new keystone.List('MyList', {
    nocreate: true
});
```
and the "+ Create MyList" button will be active.  IMO, it should not show.  Likewise, the Admin UI's home screen will also enable the "+" button to add a new MyList item.  IMO, it should be disabled

**Comment by jossmac** [comment]
Resolved by commit e043f12
