### ISSUE TITLE
Add an isOrderable flag to all field types to indicate whether they can be used as an orderBy field

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#1982]
Not all field types are necessarily orderable (e.g. Location, Relationship, Password, etc). We should set an explicit field on field types to indicate this and then respect this flag when setting up the `orderBy` enumeration and also when presenting column sort functions in the Admin UI.

c.f. #1981

**Comment by molomby** [comment]
#183 has some related thoughts.

Ultimately where we want to end up is having field types (or field type adapters?) define the "orderings"/"collation" they support. Some, like `Password`, probably shouldn't define any. Others like, say, `CloudinaryImage` might want to define multiple (height, width, file size, ...?).

See also #391 for some relevant complications around ordering `null` values.
