### ISSUE TITLE
relationship issue, can't filter by _id

### ISSUE THREAD

**Issue by netssfy** [keystonejs/keystone#1985]
I have 2 model
```javascript
var City = new keystone.List('City');
City.add({
  name: { type: String, required: true },
  districts: { type: Types.Relationship, ref: 'District', many: true, filters: { city: '_id' } },
});

var District = new keystone.List('District');
District.add({
  name: { type: String, required: true },
  city: { type: Types.Relationship, ref: 'City' },
});
```
City contains multiple districts.

In admin ui, when I open a city. an exception threw out:
API Error (database error):
{ [CastError: Cast to ObjectId failed for value "_id" at path "city"]
  message: 'Cast to ObjectId failed for value "_id" at path "city"',
  name: 'CastError',
  type: 'ObjectId',
  value: '_id',
  path: 'city' }
GET /keystone/api/districts/autocomplete?context=relationship&q=&list=cities&fie
ld=districts&filters[city]=_id 500 5.109 ms

looks like keystone didn't replace _id placehold.

Does keystone support fliters on a many side?

**Comment by wmertens** [comment]
This is a confusing issue. Why do you want to have this circular relationship?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
