### ISSUE TITLE
How to create seperate API for Admin and Production (v5)

### ISSUE THREAD

**Issue by sambhav2612** [keystonejs/keystone#1993]
Using v5 KeystoneJS

Aforementioned, I've come across a scenario which requires me have different endpoints for the Admin UI / GraphiQL Playground and the actual API to be served as endpoint in production. We need this due to the fact that we are using a custom middleware (as Authentication Guard) to filter out unauthenticated requests before they can even reach the resolvers that actually process any incoming API requests.

For example: 

Endpoint for Admin UI: `/admin/keystone`
Endpoint for Production: `/api/v1`

Can anyone help?

**Comment by Vultraz** [comment]
You should be able to set those with the `adminPath` and `apiPath` [AdminUI App config options](https://www.keystonejs.com/keystonejs/app-admin-ui/).

**Comment by sambhav2612** [comment]
No, by that I meant, different API endpoints for Admin UI and the App we're building with KeystoneJS.

For example:

API Endpoint for Admin UI: /admin/keystone
API Endpoint for Production: /api/v1

**Not path**.

**Comment by sambhav2612** [comment]
@optnio00

**Comment by Vultraz** [comment]
`admin/api` *is* the default API endpoint. If you dispense a `fetch()` request to that address you can get back the results of GQL queries client-side. For example:
```js
async function keystoneGQL(query, variables = {}) {
  return fetch('/admin/api', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      variables,
      query,
    }),
  }).then(result => result.json());
}
```

I haven't tested, but I imagine if you set the API path to `api/v1` it would work just the same as the default endpoint.

**Comment by sambhav2612** [comment]
@Vultraz actually, we authenticate any kind of API request based on a custom middleware we've put in place. Now, either I can enable it for production apps or admin UI but it won't work for both as they tend to ask for data at same API endpoints: `/admin/api`

**Comment by gautamsi** [comment]
you can always run another instance of keystone connected to same database and mount `admin-ui` in that instance which listen to a separate port or internal IP instead of default.

**Comment by MadeByMike** [comment]
You don't event need another you can run multiple graphQL and adminUI apps if you want and they can have different schemas.

We need to get some docs on this as it's a pretty new feature. Let me ask the team.

**Comment by MadeByMike** [comment]
I've verified locally this is working so it's not really a bug but probably a configuration issue. If you'd like support please jump on the community slack: http://community.keystonejs.com/
