### ISSUE TITLE
Add option to set logger (pino) options and destination

### ISSUE THREAD

**Issue by LiamAttClarke** [keystonejs/keystone#1998]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to output logs to a separate file based on logger name. Currently, there is no way to provide that option.

## Describe the solution you'd like

I would like an option on the `Keystone` constructor for modifying logger options passed to `pino` a well as an option to set the `destination` option on the `pino` instance.

**Comment by LiamAttClarke** [comment]
My temporary fix:
```js
// Make sure this runs before you import other keystone modules
const memoize = require('fast-memoize');
const pino = require('pino');
const falsey = require('falsey');
const keystoneLogger = require('@keystonejs/logger');

keystoneLogger.logger = memoize((name) => {
    return pino(
        {
            name,
            enabled: falsey(process.env.DISABLE_LOGGING),
            // Additional logger options
        },
        pino.destination('./app.log')
    );
});
```

**Comment by MadeByMike** [comment]
Hi @LiamAttClarke, I think your temporary 'fix' is exactly the correct API for updating the logger.

**Comment by LiamAttClarke** [comment]
@MadeByMike It's not an elegant api to have to override the pino logger. I had to add pino, falsey, and fast-memoize to my project just to get this working. This code also has to run before importing any keystone modules to ensure the correct pino instance gets memoized.

That said, I believe https://github.com/keystonejs/keystone/pull/2119 solved the issue.

**Comment by clemenspeters** [comment]
In Keystone4: 

in `keystone.js`:

```js
const { requestLogger } = require("./utils/requestLogger");
keystone.pre("logger", requestLogger); // use custom pino request logger
keystone.init({
  logger: false, // disable morgan logger (see: https://v4.keystonejs.com/documentation/configuration/server-options)
});
```

in `requestLogger.js`

```js
const logger = require('pino')()
const requestLogger = require("express-pino-logger")({
  logger,
  customSuccessMessage: function (res) {
    return `${res.req.ip} - ${res.req.originalMethod} ${res.req.originalUrl} - ${res.statusCode}`;
  },
  customErrorMessage: function (error, res) {
    return `${res.req.ip} - ${res.req.originalMethod} ${res.req.originalUrl} - ${res.statusCode}`;
  },
});

module.exports = {
  requestLogger,
};
```
