### ISSUE TITLE
Migrating keystone between servers the admin panel lose image preview

### ISSUE THREAD

**Issue by piermariacosina** [keystonejs/keystone#1999]
I don't know if this is a bug, but in any case the admin panel lose preview of images (localfile) after migrating new server.

Migration is done following these steps:

1. dump of db 
2. restore of db
3. move code repo
4. move images
5. start keystone with forever 

everything works fine only previews in admin are lost

**Comment by piermariacosina** [comment]
No one has a solution on this ? Or have experienced this issue?

**Comment by morenoh149** [comment]
are the files locally stored on the filesystem? at the same path? not heroku?

**Comment by piermariacosina** [comment]
locally stored on a vps server , same path, they are loaded in fronted
but the format function in the local file seams broken

**Comment by piermariacosina** [comment]
Still no solution on this? Is it a confirmed bug?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
