### ISSUE TITLE
List-level hooks for authentication and deauthentication mutations

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#2001]
Recently we've started thinking of the `auth` operations on a list as almost in the same category as create, read, update and delete operations (CRUDA?). This has been [extended to access control](https://github.com/keystonejs/keystone/pull/1627) but not yet been rolled out to hooks.

## Use Cases

* Logging user signins to track active users; eg. updating a `lastSeenAt` Timestamp field (or similar) on the user item
* Adding rate limiting based on request characteristics (eg. IP range), auth ID value (eg. username) or both
* Account lockout (and/or notification) after some number of failed attempted
* Adding additional layers of security to authentication mutations (eg. IP whitelisting) without requiring a custom auth strategy
* Additional logging for security auditing or debug

## Existing Solutions

Note the `auth-passport` packed does already support `onAuthenticated()` and `onError()` hooks but..

* Theres no reason for these to be auth strategy-specific
* Their signatures are express-middleware-like (makes sense for Passport but doesn't necessarily generalise to other auth strategies)
* Not setup to intercede _before_ the authentication is processed (although I guess you could stop the token being returned)

## Proposed Solution

My first pass at a design would be to add three list-level hooks to lists with signatures like..

```js
async beforeAuth(
  authStrategy // The auth strategy to be used (alternatively could be `authType`)
  args // The arguments supplied to the auth mutation (ie. `email`, `password`)
  context // GraphQL context object
  audiences // Array of audience keys included in the session
): {
  // Nothing? Or maybe replace/override..
  authStrategy,
  args,
  audiences
};
```

```js
async afterAuth(
  authStrategy // The auth strategy to be used (alternatively could be `authType`)
  args // The arguments supplied to the auth mutation (ie. `email`, `password`)
  context // GraphQL context object
  audiences // Array of audience keys included in the session
  item // The item being authenticated as
  success // Boolean
  message // Message being returned to caller
  token // The session token
): {
  // Nothing? Or override...
  item, // The item being authenticated as
  success, // Boolean
  message // Message being returned to caller
};
```

```js
async beforeUnauth(
  context
  session
): {}
```

## Open Questions

* Do these hooks make sense in the context of existing hook names, etc.?
* Should these hooks be able to return/replace the values being used (ie. override the auth strategy, return alternate args to use for auth, etc.)...?
* .. Or should they only be allowed to produce side effects?
* Anything else I've missed?

**Comment by jesstelford** [comment]
`authenticateUser`, etc, are custom operations which the Keystone core inserts for us.

We should have hooks available on all custom operations, and this just becomes a config option when setting up the auth strategy.

**Comment by molomby** [comment]
@jesstelford when you say "custom operations" do you mean custom mutations or something else?

I think we'd lose some of the benefit if we were to generalise these hooks to custom mutations -- a lot of the potential arguments and return values don't have parallels there. Also, are there many situations adding hooks to a custom mutation would be useful? (You could just add the additional steps to the mutation itself, no?)

I agree it might be nice to configure auth hooks when you're setting up the auth strategy (ie. when `keystone.createAuthStrategy()` is being called) rather than when you're calling `keystone.createList()`.

Come to think of it... why are these calls separate at the moment? Maybe the `createAuthStrategy()` config could be moved into the list config along with everything else...? 🤔

**Comment by gautamsi** [comment]
we had list level queries and mutations, which would have been helpful in this scenario. We could use create list and add list level hooks

We can also add keystone level hooks which would run for all the list and we can apply custom mutations and queries on specific list like `User` in this case. 

another way is to re-look at #842 and #1498
