### ISSUE TITLE
Move from numeral.js to numbro

### ISSUE THREAD

**Issue by markuplab** [keystonejs/keystone#2002]
Hello! Keystone use Numeral.js as main library for work with numbers. Now, numeral is frozen project, but we have maintained fork http://numbrojs.com/ with correct i18n packages. I think it's good idea to move to numbro.

**Comment by ericelliott** [comment]
Is the functionality not available in Moment.js?

**Comment by morenoh149** [comment]
looks like we use if for some money stuff https://github.com/keystonejs/keystone/blob/333f3e1ed9d46c9e8eab99415a4886038dd5840b/fields/types/number/NumberColumn.js#L16

https://github.com/keystonejs/keystone/search?utf8=%E2%9C%93&q=numeral

**Comment by LorbusChris** [comment]
Formatjs (react-intl) could possibly also provide this functionality...

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, feel free to upvote it if it's important for you: https://productpains.com/post/keystonejs/move-from-numeraljs-to-numbro!
