### ISSUE TITLE
Missing item in a Relationship field type causes error with stuck "Loading..." message

### ISSUE THREAD

**Issue by JonathanJJudge** [keystonejs/keystone#2004]
I'm working on a blog using KeystoneJS, and I noticed that if someone deletes a category that a blog post was related to, instead of that field coming up empty for me on the post's edit page in the admin so I can assign a new category, it gets stuck at "Loading...".

Is there any way to resolve this by interpreting the API's 404 response to mean that I can select a new category, or perhaps there's a better solution?

**Comment by piermariacosina** [comment]
As I've understand the fix will be in version 4 for now I rolled back to version 2.42 to make this thing work

**Comment by morenoh149** [comment]
@piermariacosina please share a link to the commit that fixed this

**Comment by mxstbr** [comment]
This is definitely fixed in v4, but not when `many` is true – closing this in favor of #2382.
