### ISSUE TITLE
Refactor `Keystone` and `List` classes so auth strategies belong to lists

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#2004]
There's a legacy misconception that authentication is in some way a Keystone-level function. I contest it's purely list-level, like fields and hooks. There's a strong push to centralise list config in the `keystone.createList()` invocation; auth strategies should conform to this pattern.

In concrete terms, this*:

```js
keystone.createList('User', {
  fields: {
    name: { type: Text },
    email: { type: Text, isUnique: true },
    password: { type: Password },
    // .. other fields
  },
});

const authStrategy = keystone.createAuthStrategy({
  type: PasswordAuthStrategy,
  list: 'User',
});

module.exports = {
  keystone,
  apps: [
    new GraphQLApp(),
    new AdminUIApp({ enableDefaultRoute: true, authStrategy }),
  ],
};
```

Could be written like this:

```js
keystone.createList('User', {
  fields: {
    name: { type: Text },
    email: { type: Text, isUnique: true },
    password: { type: Password },
    // .. other fields
  },
  authStrategies: [{ type: PasswordAuthStrategy }],
});

module.exports = {
  keystone,
  apps: [
    new GraphQLApp(),
    new AdminUIApp({ enableDefaultRoute: true, authListKey: 'User' }),
  ],
};
```

Most of the work is around refactoring the Keystone and List classes, specifically moving `keystone.auth` (currently keyed by `listKey` anyway) into the list themselves. This lets us ditch things like the `getAuth()` function passed by Keystone into list.

The `AdminUIApp` class is currently hard coded to only support the password strategy so this doesn't make that any worse; it just needs to retrieve the password strategy from whichever list it's given.

We can leave the `keystone.createAuthStrategy()` function in place for backwards compatibility -- with a deprecation warning I guess?

---

\* Example code taken/paraphrased from the [starter example project](https://github.com/keystonejs/keystone/blob/master/packages/create-keystone-app/example-projects/starter/index.js).

**Comment by timleslie** [comment]
I’m strongly on board with this plan.

**Comment by molomby** [comment]
Going a little deeper on this.. keying the auth strategies like fields would give us a way to easily customise the name of the resultant GraphQL mutation. This solve another related issue -- list can't currently have multiple strategies with the same `authType`.

Eg. here the system can generate tokens and email them to users as "signin links" without interfering with the user's existing password:

```js
keystone.createList('User', {
  fields: {
    name: { type: Text },
    email: { type: Text, isUnique: true },
    password: { type: Password },
    authToken: { type: Password },
    // .. other fields
  },
  authStrategies: {
    password: { type: PasswordAuthStrategy },
    emailLink: {
      type: PasswordAuthStrategy,
      config: {
        identityField: 'id',
        secretField: 'authToken',
      },
    },
  },
});

module.exports = {
  keystone,
  apps: [
    new GraphQLApp(),
    new AdminUIApp({ enableDefaultRoute: true, authStrategy: 'User.password' }),
  ],
};
```

(Maybe you'd want a [hook](https://github.com/keystonejs/keystone/issues/2001) or something to clear the token once it had been used.. but you get the idea.)

It would produce mutations like this:

```graphql
authenticateUserWithPassword(
  email: String
  password: String
): authenticateUserOutput

authenticateUserWithEmailLink(
  id: ID
  authToken: String
): authenticateUserOutput
```

**Comment by gautamsi** [comment]
I like the idea, I also had some thought on [auth improvements](https://github.com/keystonejs/keystone/issues/878#issue-423433018) 

I am not sure whether it would be best to add this into list config, alternate way (in combination to #878)

this should initialize using default `User` list and do not need any specific list config,if you need to use separate list than default `User` list, add `isAuthList` to list config. 

```js
const passwordAuthStrategy = new PasswordAuthStrategy(......);
const twitterAuthStrategy = new TwitterAuthStrategy(......);
const facebookAuthStrategy = new FacebookAuthStrategy(......);
keystone.useAuthStrategy(passwordAuthStrategy, twitterAuthStrategy, facebookAuthStrategy);

// in list config
keystone.createList('People', {
  fields: {
    name: { type: Text },
    email: { type: Text, isUnique: true },
    password: { type: Password },
    // .. other fields
  },
  isAuthList: true,
});
```

**Comment by molomby** [comment]
@gautamsi I agree with the jist of #878 in that the admin UI should support more auth types.

It's important to remember though, systems may have multiple lists supporting authentication -- there should be no concept of _**the**_ auth list in Keystone. Similarly, there's no reason Keystone shouldn't support multiple instances of the admin UI in a single app (at some point).

In this context, having an options like `isAuthList` in the list config doesn't make sense to me. Conceptually, what I think we're saying is:

* Lists can have zero or more auth strategies defined for them. This information belongs with the list config.
* An instance of the admin UI should be able to nominate zero or more auth strategies from zero or more lists. This information belongs with the admin UI config.
* Lot of this needs to be fairly explicit. I wouldn't want Keystone to assume, for example, that a list was authenticate-able because of it's name.

**Comment by gautamsi** [comment]
What would be use case with multiple auth list?

I can think of this -  have different auth list for different admin-ui? Additionally different purpose like admin auth list and user auth list? Strapi moved to similar strategy, having separate auth list for user and admin, for admin I believe they have built in list

I see the point to have multiple admin-ui, but are you  proposing each admin-ui to use different list for auth?

**Comment by molomby** [comment]
@gautamsi

> What would be use case with multiple auth list?

As you say, different groups of people (eg. admins, support staff, sales people, end users) could be modelled with different lists.

Authentication doesn't necessarily have anything todo with people though. Eg..

* Physical device may need to auth (eg. shared tablets or hand-held barcode scanners, etc.); these could be tracked individually, auth'ed with client certificates or something
* Related external systems (eg. on-site servers, partner systems, etc.) could have distinct credentials for API access
* Other internal systems (eg. maybe pools of workers processes have distinct credentials)
* Alternate authentication methods for people. Eg. users might have normal username/password auth but can also create multiple API keys with different permissions per key. These API keys are stored in a related list and, when used, the caller is effectively authenticating as the _key_ not the user

> .. are you proposing each admin-ui to use different list for auth?

Not specifically -- I don't have a strong opinion on that. This issue is only tangentially related to the Admin UI. Note that none of the scenarios I've listed above expect or require the Admin UI -- these could all be systems with custom UIs, native apps, CLIs, etc. that use the GraphQL API.
