### ISSUE TITLE
0.4: Types.Textarea looses its formatting when set to noedit:true

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2008]
The formatting inside textareas should be preserved if `noedit: true` is set.  Currently the format is lost.

**Comment by w01fgang** [comment]
The format isn't lost. There is missing props.
The component expects prop `multiline`
![component](https://cloud.githubusercontent.com/assets/8686751/14743678/13b424da-08a3-11e6-8fbf-2f6d14dd8ebd.png)
But it doesn't passed to the component:
![props](https://cloud.githubusercontent.com/assets/8686751/14743769/912028c4-08a3-11e6-8acb-ad3ae58e6b3b.png)

No prop `multiline` - no class `multiline`. If I manually add the class the styles is well.

**Comment by mxstbr** [comment]
Good catch @w01fgang, maybe somebody who's been around longer than me knows why that was done that way?

**Comment by webteckie** [comment]
@w01fgang once you add your workaround is the text area content still protected from edits?  If so, then seems like you've got a fix.  Perhaps submit a PR :-)

**Comment by w01fgang** [comment]
@webteckie yes it's still protected from edits

**Comment by webteckie** [comment]
@w01fgang awesome...PR coming?
