### ISSUE TITLE
0.4: Types.Code height attribute not working

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2009]
The attribute value is currently not being applied.

**Comment by yn5** [comment]
The referenced pull request: https://github.com/keystonejs/keystone/pull/2016 tries to fix this by passing the height property on to CodeField's FormInput component similair to how it is done in the HtmlField component. Unfortunately CodeMirror does not seem to use the height set on the textarea provided to CodeMirror#fromTextArea.

**Comment by webteckie** [comment]
@yn5 you may need to use the setSize api.  See http://codemirror.net/doc/manual.html#setSize

**Comment by yn5** [comment]
Thanks @webteckie. Updated the pull request.
