### ISSUE TITLE
Backtick template string error in pre ES6 node version

### ISSUE THREAD

**Issue by pangorgo** [keystonejs/keystone#2014]
Hi, I am using node 0.12.x and getting errors for ES6 backtick templates introduced in commit: 0374c2300d3934ec794f893190fba1d0e19e6428

Is it intentional behavior and 0.12.x is not supported any more?

**Comment by morenoh149** [comment]
I think a modern node version is requirement of running keystone nowadays (nothing formally announced). Try using the `--harmony` flag on older versions of node to get things running.

**Comment by pangorgo** [comment]
`--harmony` flag in 0.12 do not bring ES6 templating feature but I totally understand that we should go on and develop on modern node version

**Comment by ericelliott** [comment]
The Node 4.x line is the first LTS line. Projects using older versions of Node should look for an upgrade migration path.
