### ISSUE TITLE
adminui cant search relationship field use chinese~

### ISSUE THREAD

**Issue by bookyo** [keystonejs/keystone#2015]
![批注 2019-11-28 214825](https://user-images.githubusercontent.com/20472717/69811372-e947a580-1228-11ea-9c68-1ca74b5bdc68.jpg)
![批注 2019-11-28 214857](https://user-images.githubusercontent.com/20472717/69811373-e9e03c00-1228-11ea-9585-61b7745269c0.jpg)
#640 i think i find the solution. but if i use title filed what can i do, can i config a search field?

**Comment by MadeByMike** [comment]
@bookyo yes, I think this is a duplicate and not related to language. Keystone should handle that fine. We need to add a fix to make sure it searches labels as well as name.

**Comment by MadeByMike** [comment]
It's marked 'good-first-issue' I don't think it's a huge task!
