### ISSUE TITLE
sortable cloudinaryImages

### ISSUE THREAD

**Issue by pangorgo** [keystonejs/keystone#2019]
What do you think about drag&drop sorting of cloudinaryImages field type?
I personally miss sorting feature on galleries a lot, and would like to work on that if there is green light for such enhancement.

**Comment by mxstbr** [comment]
Duplicate of #1060, see https://productpains.com/post/keystonejs/allow-reordering-of-cloudinaryimages!

**Comment by n-lavrenko** [comment]
+1
