### ISSUE TITLE
0.4: Add tooltip to Admin UI list icons

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2020]
The icons used in the Admin UI list do not have a tooltip.  For example, these:

![image](https://cloud.githubusercontent.com/assets/5872515/12027549/33ef47e2-ad96-11e5-80c4-d2e4b658055f.png)

**Comment by JedWatson** [comment]
Fixed by @yn5 in #2025, @webteckie close this if you're happy with that solution or let us know if you think more is necessary.

**Comment by webteckie** [comment]
Looks good!  Thanks @yn5
