### ISSUE TITLE
Sortable drag and drop does not work

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2021]
Not sure if it's just my environment (latest chrome, windows 10) but adding sortable to a list does not seem to enable drag and drop on that list.  I do see the icon below being added to the list items but cannot do anything with it.  Nor if I pick an item and drag it it does not work.

![image](https://cloud.githubusercontent.com/assets/5872515/12027618/3d549a2a-ad97-11e5-851b-9ede1a3510f4.png)

I've added keystonejs/keystonejs-site#54 just in case it's a documentation issue.

**Comment by snowkeeper** [comment]
I had an implementation in the pr list for a while but it keep falling too far behind.  Should I re-factor and resubmit?

**Comment by webteckie** [comment]
@snowkeeper ah, I thought drag and drop was already merged :-)

**Comment by mxstbr** [comment]
Works now!

**Comment by XESLLC** [comment]
Does this work now? 
Model:
```var Speaker = new keystone.List('Speaker', {
  sortable: true,
});

Speaker.add({
    app_user: { type: Types.Relationship, label: 'App User', ref: 'AppUser', initial: true, required: true, index: true, unique: true },
    bio_url: { type: Types.Url, label: 'Link to Web Bio', initial: true },
    type_tags:  { type: Types.Select, options: 'Primary, Headliner, Sponsor', initial: true },
    member_since: { type: Types.Date, label: 'Member Since', initial: true, required: true, default: Date.now },
    featured: { type: Types.Boolean, initial: true }
});
```
