### ISSUE TITLE
Gallery Image Stores

### ISSUE THREAD

**Issue by riyadhalnur** [keystonejs/keystone#2023]
It's a bit weird that a *Gallery* model is bound to Cloudinary for multiple images. Cloudinary is one choice of storage in Keystone which is why it makes no sense to offer only Cloudinary as the storage choice when building a model with a field that can accept/store multiple images at a time.

**Comment by AubreyHewes** [comment]
The generated Gallery model is an _example_. You can change the Gallery model _example_ to use other types, see [docs](http://keystonejs.com/docs/database/#fieldtypes)

i.e use local file storage.

 * `heroImage` type `LocalFile` 
 * `images` type `LocalFiles` 

or any other supported type..

**Comment by riyadhalnur** [comment]
Umm, I would like to use S3

**Comment by AubreyHewes** [comment]
True there is only `S3File` and no `S3Files` (yet) ;-)
