### ISSUE TITLE
Keystone-app generator doesn't detect yarn and todo app yarn install fails

### ISSUE THREAD

**Issue by Canice-James** [keystonejs/keystone#2026]
# Bug report

## Describe the bug
Yarn 1.19.2 is installed globally and works in other projects. Upon starting a new todo project, Keystone fails to detect yarn and fails to install dependencies with npm as well. 

Running yarn/ npm in the project folder afterward fails as well. Errors are in screenshots attached.
Node: v10.17.0
NPM: 6.11.3
Yarn 1.19.2

Package.json

{
  "name": "@keystonejs/example-projects-todo",
  "description": "An example KeystoneJS project showcasing a simple Todo List with a Keystone StaticApp front-end.",
  "private": true,
  "version": "5.0.0",
  "author": "The KeystoneJS Development Team",
  "license": "MIT",
  "engines": {
    "node": ">=8.4.0"
  },
  "scripts": {
    "dev": "cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev",
    "build": "cross-env NODE_ENV=production keystone build",
    "start": "cross-env NODE_ENV=production keystone start"
  },
  "dependencies": {
    "@keystonejs/adapter-mongoose": "^5.0.0",
    "@keystonejs/app-admin-ui": "^5.0.0",
    "@keystonejs/app-graphql": "^5.0.0",
    "@keystonejs/app-static": "^5.0.0",
    "@keystonejs/fields": "^5.0.0",
    "@keystonejs/keystone": "^5.0.0",
    "cross-env": "^5.2.0"
  }
}

## Expected behaviour
To experience regular setup and run a Keystone 5 project. 
## Screenshots

![image](https://user-images.githubusercontent.com/20664703/69923081-38cfe080-1478-11ea-93b2-2040538269cd.png)
![image](https://user-images.githubusercontent.com/20664703/69923101-69b01580-1478-11ea-9868-e1115b86bb70.png)
![image](https://user-images.githubusercontent.com/20664703/69923133-ca3f5280-1478-11ea-9a92-ff351d735055.png)

## System information

- OS: Windows

## Additional context

I've been building a project with Keystone 4 for the past couple months and I'm trying to setup a new Keystone 5 project before seeking it transition it over.

**Comment by Vultraz** [comment]
Looks like you don't have `node-gyp` installed.

**Comment by MadeByMike** [comment]
Yep, this is an issue definitely an issue with bcrypt/node-gyp.

I'd follow this: https://stackoverflow.com/questions/41899719/how-to-npm-install-bcrypt-on-windows-7/49778365

**Comment by Canice-James** [comment]
> Yep, this is an issue definitely an issue with bcrypt/node-gyp.
> 
> I'd follow this: https://stackoverflow.com/questions/41899719/how-to-npm-install-bcrypt-on-windows-7/49778365

You're right. After installing VS Windows SDK, locally installing bcrypt@3.0.6 (the latest didn't work) before finally rerunning npm install - everything went swimmingly. 

Much thanks!
