### ISSUE TITLE
Support aliases for /keystone URL

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#203]
Has been mentioned it would be nice to allow alternate URLs for the /keystone admin path.

As it's hard-coded in the .less and client-side js files, it might introduce a fair bit of complexity (custom build process, etc.) to change it completely, but we might be able to set up an alias at least for the auto-bound route urls to support other paths (e.g. /admin)

**Comment by digitalcraft** [comment]
Any progress on this?

**Comment by drlogout** [comment]
As I'm using a nginx reverse proxy I just added a location:

```
 location = /admin {
   return 301 /keystone;
 }

```
So you can type http://example.com/admin to access the backend.

**Comment by creynders** [comment]
Merged in #1820
