### ISSUE TITLE
how to use keystone admin api from external page

### ISSUE THREAD

**Issue by netssfy** [keystonejs/keystone#2037]
After create a model, keystone has setup the CRUD and their pages for me. That's great.
From reading the code, I know keystone support api as well.
I want to use api to get data in my another website page like $.get(http://hostname/keystone/api/orders)
But if I didn't login via keystone's login page before, this api won't work.
Does keystone support OAuth or Is there a login api for me to login

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
