### ISSUE TITLE
Allow inclusion of custom templates in the Details Admin UI

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#204]
Would be rendered with the context of the item to allow display of virtual properties, etc.

For bonus points, would be great to be able to add custom buttons to call methods specified on the item (e.g. on a User model, calling a sendForgottenPassword() method)

**Comment by arthurtalkgoal** [comment]
Hi,

Can we add custom button to keystone admin UI now? 

I really want to add a button to trigger related function of the current object.

Thanks,

**Comment by VinayaSathyanarayana** [comment]
What is the current status of this?

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/allow-inclusion-of-custom-templates-in-the-details-admin-ui
