### ISSUE TITLE
TinyMCE wysiwyg buttons not appearing

### ISSUE THREAD

**Issue by rogersillito** [keystonejs/keystone#2047]
When specificying toolbar buttons for tinymce, some toolbar icons do not appear (although the button does actually appear as an empty box):

![croppercapture 18](https://cloud.githubusercontent.com/assets/2572893/12080576/fc0be19e-b256-11e5-9a32-562fe27c684e.jpg)

My wysiwyg config is as follows:

    toolbar: 'undo redo | bold italic | table',

This has been reported via the group but I don't believe it's been logged as an issue yet (https://groups.google.com/forum/#!searchin/keystonejs/tinymce$20toolbar/keystonejs/b7APTy1N1YY/aUZQJDN0724J)

I'm using Keystone 0.3.16.

**Comment by mxstbr** [comment]
Does this issue still exist on `master`?

**Comment by varatep** [comment]
Still exists for me @mxstbr specific to the spellchecker button and search & replace
