### ISSUE TITLE
Routing with React components

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#2049]
I got universal routing working with React in the [universal-keystone-boilerplate](https://github.com/ericelliott/universal-keystone-boilerplate/commit/db215c50c95f85887f1e6bd5ced22d16966b025d) and made [a factory that takes react-router-routes and returns an express router](https://github.com/ericelliott/universal-keystone-boilerplate/blob/db215c50c95f85887f1e6bd5ced22d16966b025d/source/routes/create-component-router/index.js).

The idea is to move this capability into Keystone core and use a new `component routes` option in `Keystone.init()` to configure React routes to enable universal Routing with React in Keystone apps.

However, when I try to move this into Keystone proper, the routes are 404. );

See my [component routes fork](https://github.com/ericelliott/keystone/tree/component-routes).

The factory is in [createComponentRouter.js](https://github.com/ericelliott/keystone/blob/component-routes/server/createComponentRouter.js).

I'm attempting to use the factory in `createApp.js`:

```js
	// Configure component routes
	if (keystone.get('component routes')) {
		app.use('/', createComponentRouter(keystone.get('component routes')));
	}
```

I have verified that `keystone.get('component routes')` returns the expected object, and I have tried moving the `app.use()` call up above the application routes config here:

```js
	// Configure application routes
	if ('function' === typeof keystone.get('routes')) {
		keystone.get('routes')(app);
	}
```

Don't want to waste too much time stuck on this. Any ideas?

## Reproduce

To test this, you can clone the [universal-keystone-boilerplate](https://github.com/ericelliott/universal-keystone-boilerplate) and follow the [getting started guide](https://github.com/ericelliott/universal-keystone-boilerplate#getting-started). `npm install` and `npm test` to verify that you've got everything set up correctly.

The tests on master should pass.

Then check out the [`move-component-routing` branch](https://github.com/ericelliott/universal-keystone-boilerplate/tree/move-component-routing) and replace the `keystone` directory in `node_modules` with the [`component-routes` keystone fork](https://github.com/ericelliott/keystone/tree/component-routes).

### Actual Result

Run the tests in the boilerplate again, and you should see the 404 fails.

### Expected Result

All tests should pass.

**Comment by snowkeeper** [comment]
I think it has to do with the babel version...

Change `createComponentRouter.js` to use `routes.default`
```
module.exports = function createComponentRouter (routes) {
  return function componentRouter (req, res, next) {
    match({ routes: routes.default, location: req.url },
        function (error, redirectLocation, renderProps) {

      if (error) return res.status(500).send(error.message);

      if (redirectLocation) {
        return res.redirect(302,
          redirectLocation.pathname + redirectLocation.search);
      }

      if (renderProps) {
        return res.render('default', {
          content: renderToString(React.createElement(RoutingContext, renderProps))
        });
      }

      next(null);
    });
  };
};
```
http://stackoverflow.com/a/33573195/5598114

**Comment by ericelliott** [comment]
@snowkeeper Thanks!

Turns out I was using `require()` + Babel to import the routes in the boilerplate, and for some reason, babel didn't assign the default export to the variable. The correct place to fix the error was in the boilerplate.

Merged now. =) I'v added you as a collaborator to the `universal-keystone-boilerplate` project in case you'd like to continue helping with it. If not, just let me know, and I'll remove you. =)

**Comment by ericelliott** [comment]
Resolved in https://github.com/ericelliott/universal-keystone-boilerplate/pull/34
