### ISSUE TITLE
How to inject second-level heirarchy while initialising data via onConnect [v5]

### ISSUE THREAD

**Issue by sambhav2612** [keystonejs/keystone#2050]
We have a model called `Vehicle` in the following format: 

```js
fields: {
        name: {type: Text},
        model: {
            type: Relationship,
            ref: 'VehicleModel',
            many: true
        },
    },
```

and another model `VehicleModel` as described:

```js
 fields: {
        name: {type: Text},
    },
```

We are using the `onConnect` flag while initializing keystone instance to import data in the above model, current script we're using: 

```js
fs.createReadStream(path.join(__dirname, '../assets/cars.csv'))
            .pipe(csv({separator: ','}))
            .on('data', (row) => {
                let obj = row;
                row = {};
                row['name'] = obj['Make '] + " " + obj['Model '];    // for creating name field
                row['model'] = {name: obj['Variant']};                   // for creating new `VehicleModel` and referencing back in `Vehicle` model
                results.push(row);
            })
            .on('end', async () => {
                await keystone.createItems({Vehicle: results});
                console.log(' CSV file successfully processed ----------');
            });
```

After each attempt, the script initializes data for the name field in `Vehicle` model, but misses out on the `model` field, screenshot from DB: 

![Screenshot from 2019-12-06 17-32-51](https://user-images.githubusercontent.com/19583619/70321837-76ed4b80-184e-11ea-94bc-0804f66e3ee0.png)

Would love to get support on this :smile:

**Comment by sambhav2612** [comment]
@Vultraz

**Comment by Vultraz** [comment]
Try `{ where: { name: obj['Variant'] } }`;

**Comment by sambhav2612** [comment]
@Vultraz nope didn't work

**Comment by MadeByMike** [comment]
What's the shape of `results` in `await keystone.createItems({Vehicle: results});` ? 

I'm having trouble determining if this is a Keystone related issue or not.

**Comment by sambhav2612** [comment]
@MadeByMike it's an array

**Comment by MadeByMike** [comment]
Sorry to close this one but without steps to reproduce I don't think I can help. I'm hoping it has been resolved. If not and you've got a simple way to reproduce please re-open this or create a new issue and tag me!
