### ISSUE TITLE
renderFrontLink and back url in PrimaryNavigation.js

### ISSUE THREAD

**Issue by teaualune** [keystonejs/keystone#2073]
Hi, I noticed that the `renderFrontLink` in `/admin/client/components/PrimaryNavigation.js` set `href` to root path statically. Is there any chance we can customize it? I was supposing that it uses `keystone.get('back url')` since I'm working on a subdomain keystone app. Or maybe we can have another keystone value *e.g.* `keystone.set('front url', '/something')`? Thanks!

**Comment by mxstbr** [comment]
Good catch, that should be configurable! We'll take a look.

**Comment by teaualune** [comment]
@mxstbr thanks! :coffee:
