### ISSUE TITLE
after build ,why have no update button?

### ISSUE THREAD

**Issue by bookyo** [keystonejs/keystone#2073]
yarn dev:
![QQ图片20191209214807](https://user-images.githubusercontent.com/20472717/70440677-aa89d900-1acd-11ea-8a80-cd43f16dc249.png)

yarn build & yarn start:
![QQ图片20191209214830](https://user-images.githubusercontent.com/20472717/70440759-da38e100-1acd-11ea-938e-a364b3b2a8c6.png)

something wrong?

**Comment by MadeByMike** [comment]
That update button was never fully completed and only shown in dev. It's not working all the time. It's now only show if `ENABLE_DEV_FEATURES` is set to true in your `.env` files.
