### ISSUE TITLE
Save and New

### ISSUE THREAD

**Issue by TomKremer** [keystonejs/keystone#2086]
Hi,

this is a proposal for improving the admin ui when creating a lot of objects. Next to the Save button I propose a "Save and New" (better wording possible?) button that saves the current object and displays a new empty form.

This could maybe integrated into the new react admin ui?

Best,
T

**Comment by alobodig** [comment]
I've seen such a button labelled "Save and Create Another," but that's a but wordy.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/save-and-new-button!
