### ISSUE TITLE
0.4: How do I create new Field Types for KeystoneJS v0.4?

### ISSUE THREAD

**Issue by jacobbubu** [keystonejs/keystone#2088]
I've started to try the new KeystoneJS but did not find a way to create my own field type as following:
https://gist.github.com/JedWatson/8519769

**Comment by wuhaixing** [comment]
I think create another field type is the last choice.As an option,maybe you can populate what you want in transform like this:
    
    transform.toJSON(Player,function(rtn) {
	  if(this.photo && this.photo.filename) {
		rtn.photo.href = this.photo.prefix + this.photo.filename
	  }
    });

If another filed type is your only option,there is a pull request to add LocalImageType I just closed 
https://github.com/wuhaixing/keystone/commit/b4dd231f83d059f83f5d60a33bbfa3dbc15eac6e

**Comment by jacobbubu** [comment]
Thank you for the response. In China, due to the accessibility issue, I can not use S3, Cloudinary... directly.
I've not found a way to import modules like `ItemsTableCell`, `ItemsTableValue` , `..Field` in my project.

**Comment by wuhaixing** [comment]
We have a QQ group 234990985 to discuss keystone,welcome to join us.

**Comment by kadosh1000** [comment]
Hi I have published my npm package: 
https://github.com/kadosh1000/keystone-custom-fieldtypes

It copies your custom fieldTypes from a selected dir into the keystone's fields dir and registers it

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by mikeerickson** [comment]
@mxstbr That would surely explain why I had so many notifications for Keystone issues :-)
