### ISSUE TITLE
Types.Number: ability to enter negative values?

### ISSUE THREAD

**Issue by bradwbradw** [keystonejs/keystone#2105]
Currently, in the Number field editor, all keystrokes other than '0-9' are blocked.  This makes sense because it's a Number, but it also blocks the character '-', so it's impossible to input a negative number.

There could potentially be a field option to allow the number to be negative, or not.

**Comment by TomKremer** [comment]
Good idea and maybe also add international support > , instead of . for point numbers. This is important when displaying but also while entering data. I tried to support it by running model pre validation on that field but failed.

**Comment by jannispl** [comment]
I'd much prefer a 'min/max'  constraint field option over a 'can be negative' option.

**Comment by morenoh149** [comment]
:+1: min, max contraints

**Comment by mxstbr** [comment]
@snowkeeper is this still in progress? (label)

**Comment by WelltokCaleb** [comment]
I created this fix a while ago, and am just getting around to a PR. I think it addresses the needs above, plus a couple of other cases I needed: https://github.com/keystonejs/keystone/pull/3003

**Comment by mxstbr** [comment]
@WelltokCaleb that's a really solid PR :fire:

**Comment by stennie** [comment]
In Keystone 4.0.0 the `Number` field type should allow any valid JS Number value by default (including negative and floating point values).

Additional validation constraints (such as min/max) would be a separate feature request. The PR in #3003 needs updating to catch up with the latest codebase, but seems a likely starting point.

Regards,
Stennie
