### ISSUE TITLE
[docs] Launchpass still shows Keystone@4 as the production release

### ISSUE THREAD

**Issue by thekevinbrown** [keystonejs/keystone#2109]
# Bug report

## Describe the bug

https://launchpass.com/keystonejs says

```
The current production release series is Keystone 4.x:
```

which I think is incorrect.

## Expected behaviour

Keystone 5.x is the production version, no?

**Comment by MadeByMike** [comment]
We should close that down. We're not using launchpass anymore since a people were having issues with ad blockers. It should not be linked from anywhere as far as I know.

**Comment by thekevinbrown** [comment]
I got there from GitHub -> Issues -> New Issue -> Question About Keystone 5

![Screen Shot 2019-12-17 at 6 14 40 pm](https://user-images.githubusercontent.com/1531750/70973142-2ea91580-20f9-11ea-9f28-e0b0e4b05e7d.png)

**Comment by MadeByMike** [comment]
Ahhh thanks!

**Comment by MadeByMike** [comment]
Updated the issue template
