### ISSUE TITLE
[v4.0] Decouple /admin/client/components and /fields/components

### ISSUE THREAD

**Issue by geloescht** [keystonejs/keystone#2110]
I was trying to rip out the Admin UI from the main keystone module in order to customise it. The client code, that is served to the browser via browserify, resides in the folders /admin/client and /fields and there are dependencies between both of those directories, in particular between the subdirectories named components. However I _think_ only code in /admin/client should depend on code in /fields and not the other way round. This would be a big win for modularity.
I am not overly familiar with keystone's codebase, so please correct me if this is a bad idea. I think code that could be useful for front-end code as well as the Admin UI should reside in /fields. All code that is specific to the Admin UI should be in /admin (or possibly even in its own module).

**Comment by geloescht** [comment]
I have been thinking about this and come up with an idea:
Keystone could (and should) provide re-usable React components for field types, that, with a little work from app developers, can exist on the front-end (provided that it uses React) as well as in the admin UI. Dependency Injection is the keyword.
Right now, field components have a lot of hard dependencies on components specific to the admin UI. Instead of doing import for those components, the admin UI could pass these components down using React's context mechanism. Frontend code could pass its own implementations, or, possibly use a simplified default implementation. See here for more information on context and higher order components: http://jaysoo.ca/2015/06/09/react-contexts-and-dependency-injection/
#2090 also proposes usage of React contexts for other purposes.
On the other hand, I don't know how many of those admin UI components will be replaced by Elemental. For example we have admin/components/Checkbox.js and we have Checkbox from Elemental and both are currently used by field components.

**Comment by geloescht** [comment]
OK, although this approach works, I now believe it is unsuited for the task at hand. The reason is, that static analysis of dependencies, as browserify does, cannot distinguish between modules that are actually used and the ones that just hang around in the context to be maybe used somewhere else. So if we put components into the context, they will be compiled into all bundles, that have the context, and therefore bundles will include all kind of unnecessary code.

A different approach might be injecting while building the bundle. Via browserify.require({expose: true}) includes can be made available under a different path. However, this feature appears not to be the most reliable.

**Comment by mxstbr** [comment]
I agree with you, that is a bit weird and bit me while doing #2566, but I put those that are shared across the admin interface and the fields into a `shared` folder!

I'll close this issue for now, thanks for thinking about this!
