### ISSUE TITLE
select: true in Cloudinary field generates JavaScript error

### ISSUE THREAD

**Issue by autoboxer** [keystonejs/keystone#2114]
Note:  This issue has been tested and exists in Keystone 0.3.13 and 0.3.16.

When creating a field in any model with type: Types.CloudinaryImage and select: true set, the following behavior occurs:

1.  Let's say you have a model with one field (field B) depending on the value of another field (field A) using the dependsOn attribute.  When creating a new item, if you select a value in field A, field B appears as expected.  After saving and being taken to the screen displaying information about the record you just saved, if you select a value for field A, a JavaScript error is thrown: error 'Uncaught TypeError: Cannot read property 'length' of undefined', and field B remains hidden.

2.  After you create a new item, when you're taken to the screen displaying information about the record you just saved, typing or deleting text from any field throws a JavaScript error 'Uncaught TypeError: Cannot read property 'length' of undefined'.  In some cases with text based fields, after each character is typed, that character is auto-erased, in other cases, it is not, however, an error is always thrown.

It turns out the problem is with the select: true attribute.  I've tried every combination of select: true with a specified folder (with the folder both existing and not in Cloudinary), and selectPrefix (with the folder both existing and not in Cloudinary).  I was also sure to set cloudinary folders to true in keystone.js using the following: keystone.set('cloudinary folders', true);.  No combination of attributes was successful in getting rid of the JavaScript error until the select: true attribute was removed.

Here is a link to the original thread in the Keystone forum on Google Groups with the full model definition: https://groups.google.com/forum/#!topic/keystonejs/V0d3uK17Sh4

**Comment by bringking** [comment]
I am having this issue as well with Keystone 0.3.13 and 0.3.16. Have ```select:true``` on the Cloudinary field, breaks other select fields. In my case it is breaking the ability to change the post state to "published". As soon as you click the select box, it throws the above mentioned error. I can't get the line number since it is minified, but the error in the the "react-select" component and the function is "loadAsyncOptions"
<img width="399" alt="screenshot 2016-01-25 16 45 07" src="https://cloud.githubusercontent.com/assets/864845/12568418/0c051466-c383-11e5-8fc7-dbd8438726b6.png">

**Comment by bringking** [comment]
It looks like this is an issue with the version of react-select (0.6.12) included in the 0.3.16 build. However, even changing to the ```0.6.12-fix-async ``` version doesn't seem to fix the issue. @JedWatson Any ideas, aside from forcing "cacheAsyncResults" to be false?

**Comment by mxstbr** [comment]
Does this problem still exist?

**Comment by bringking** [comment]
@mxstbr I believe my pr #2166 fixed the bug on master, but I believe it is still broken on the 3.x branch.

**Comment by mxstbr** [comment]
Thanks @bringking, since this is fixed on master I'll close this for now!
