### ISSUE TITLE
Can't populateRelated object's property value

### ISSUE THREAD

**Issue by wuhaixing** [keystonejs/keystone#2128]
Here is my model:

    Scoreboard.add({
	  name: { type: String, required: true, index: true },
	  scores: { type: Types.Relationship, ref: 'Score',many: true }
    });

    transform.toJSON(Scoreboard);
    Scoreboard.defaultColumns = 'name, league, season,round';
    Scoreboard.register();

If there is no `scores` field,or declare it as relationship:

    Scoreboard.relationship({ ref: 'Score', refPath: 'scoreboard', path: 'scores' });

When I do `scoreboard.populateRelated('scores')`,there is no value in `scoreboard.scores`.

If I got the results by query,can't set it to `scoreboard` either as I used to do.

**Comment by jjhesk** [comment]
+1

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
