### ISSUE TITLE
User not created when setting up Keystone with Postgres

### ISSUE THREAD

**Issue by martinheidegger** [keystonejs/keystone#2133]
# Bug report

I tried setting up Keybase following the getting started guide but on `npm run dev` it starts keystone but no user is created.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. init Keystone
2. install a Postgres database
3. set the user confirguration for the postgres db
4. start the server and see that no user is created

## Expected behaviour

The user should be created immediately or there should be a screen that shows to create a user when starting the app like #1782.

## Additional context

I tried to debug `initial-data.js` and changing following:

https://github.com/keystonejs/keystone/blob/06bff4119a44769b359006e8e6b9e07c32b21a8e/packages/create-keystone-app/example-projects/starter/initial-data.js#L6-L10

to:

```javascript
  const res = await keystone.executeQuery(
    `query {
      _allUsersMeta {
        count
      }
    }`
  )
  console.log(res)
  // Count existing users
  const {
    data: {
      _allUsersMeta: { count },
    },
  } = res;
```
I got following error:

```
{
  errors: [
    error: relation "public.User" does not exist
        at Connection.parseE (./keystonejs/my-app/node_modules/pg/lib/connection.js:604:13)
        at Connection.parseMessage (./keystonejs/my-app/node_modules/pg/lib/connection.js:403:19)
        at Socket.<anonymous> (./keystonejs/my-app/node_modules/pg/lib/connection.js:123:22)
        at Socket.emit (events.js:210:5)
        at addChunk (_stream_readable.js:308:12)
        at readableAddChunk (_stream_readable.js:289:11)
        at Socket.Readable.push (_stream_readable.js:223:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
    From previous event:
        at Client_PG._query (./keystonejs/my-app/node_modules/knex/lib/dialects/postgres/index.js:236:12)
        at Client_PG.query (./keystonejs/my-app/node_modules/knex/lib/client.js:168:17)
        at Runner.query (./keystonejs/my-app/node_modules/knex/lib/runner.js:133:36)
        at ./keystonejs/my-app/node_modules/knex/lib/runner.js:39:23
        at ./keystonejs/my-app/node_modules/knex/lib/runner.js:253:24
        at processImmediate (internal/timers.js:439:21)
    From previous event:
        at Runner.ensureConnection (./keystonejs/my-app/node_modules/knex/lib/runner.js:251:8)
        at Runner.run (./keystonejs/my-app/node_modules/knex/lib/runner.js:25:12)
        at Builder.Target.then (./keystonejs/my-app/node_modules/knex/lib/interface.js:15:43) {
      message: 'select count(*) from "public"."User" as "t0" where true - relation "public.User" does not exist',
      locations: [Array],
      path: [Array]
    }
  ],
  data: [Object: null prototype] {
    _allUsersMeta: [Object: null prototype] { count: null }
  }
}
```
Not sure why.

# System:

```
{
  "name": "@keystonejs/example-projects-starter",
  "description": "An example KeystoneJS project with a User list and Authentication.",
  "private": true,
  "version": "5.0.1",
  "author": "The KeystoneJS Development Team",
  "repository": "https://github.com/keystonejs/keystone.git",
  "homepage": "https://github.com/keystonejs/keystone",
  "license": "MIT",
  "engines": {
    "node": ">=8.4.0"
  },
  "scripts": {
    "dev": "cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev",
    "build": "cross-env NODE_ENV=production keystone build",
    "start": "cross-env NODE_ENV=production keystone start"
  },
  "dependencies": {
    "@keystonejs/adapter-knex": "^6.1.2",
    "@keystonejs/app-admin-ui": "^5.3.0",
    "@keystonejs/app-graphql": "^5.0.1",
    "@keystonejs/auth-password": "^5.0.1",
    "@keystonejs/fields": "^6.0.0",
    "@keystonejs/keystone": "^5.3.0",
    "cross-env": "^5.2.0"
  }
```

**Comment by MadeByMike** [comment]
@martinheidegger it looks like the User table has not been set-up. Has the database been database created?

**Comment by MadeByMike** [comment]
Can you try setting the `dropDatabase` flag on the Adapter like this:
```
const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new Adapter({dropDatabase:true}),
  onConnect: initialiseData,
});
```

That should force it to initialise

**Comment by patrickjmorris** [comment]
Having the same issue, and tried the above fix (dropDatabase = true) to no avail.

**Comment by patrickjmorris** [comment]
I just ran the Mongoose version, and things look good. `onConnect: initialiseData` doesn't seem to run when connecting with knex.

**Comment by chris-kobrzak** [comment]
> Can you try setting the `dropDatabase` flag on the Adapter like this:

Many thanks for this tip, @MadeByMike - I can confirm this results in database tables being created.

**Comment by PoulpiFr** [comment]
I just got this as well.

In order to create the table, I had to use the `dropDatabase` flag. 

However, when using it, the database seems to be dropped before the `onConnect()` call **but the new User table is not yet created.**

Hence, the `onConnect()` call fails (I'm doing a `keystone.createItems()`in it), makes the server die and thus the User table is never provisionned (I guess that it's provisionned when on a `keystone.createList()` call later in the execution).

My initial fix was to:
- Launch the server with `dropDatabase` and without onConnect callback -> it creates and provision the table
- Remove the `dropDatabase`flag (otherwise the database will be dropped another time, erasing the table) and put back the `onConnect` callback to create my items and relaunch the server

And it works.

I'm looking into a better fix that wouldn't require manual intervention.

**Comment by PoulpiFr** [comment]
I got a very ugly solution.

index.js
```
(...)
const shouldDropDb = process.env.NODE_ENV === "production" ? false : true;

const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new Adapter({dropDatabase: shouldDropDb}),
  onConnect: initialiseData
});

// Access control functions
const userIsAdmin = ({ authentication: { item: user } }) => Boolean(user && user.isAdmin);
const userOwnsItem = ({ authentication: { item: user } }) => {
  if (!user) {
    return false;
  }
  return { id: user.id };
};
const userIsAdminOrOwner = auth => {
  const isAdmin = access.userIsAdmin(auth);
  const isOwner = access.userOwnsItem(auth);
  return isAdmin ? isAdmin : isOwner;
};
const access = { userIsAdmin, userOwnsItem, userIsAdminOrOwner };

keystone.createList('User', {
  fields: {
    name: { type: Text },
    email: {
      type: Text,
      isUnique: true,
    },
    isAdmin: { type: Checkbox },
    password: {
      type: Password,
    },
  },
  access: {
    read: access.userIsAdminOrOwner,
    update: access.userIsAdminOrOwner,
    create: access.userIsAdmin,
    delete: access.userIsAdmin,
    auth: true,
  },
});
(...)
```
initial-data.js
```
// Lets not hardcode password, even for test data
const password = process.env.INITIAL_DATA_PASSWORD;
const PASSWORD_MIN_LENGTH = 8;

const validatePassword = () => {
  if (!password) {
    throw new Error(`To seed initial data, set the 'INITIAL_DATA_PASSWORD' environment variable`);
  } else if (password.length < PASSWORD_MIN_LENGTH) {
    throw new Error(
      `To seed initial data, the 'INITIAL_DATA_PASSWORD' environment variable must be at least ${PASSWORD_MIN_LENGTH} characters`
    );
  }
};

module.exports = async keystone => {

  // Check the users list to see if there are any; if we find none, assume
  // it's a new database and initialise the demo data set.
  const users = await keystone.lists.User.adapter.findAll();

  if (!users.length && process.env.NODE_ENV !== 'production') {
    // Ensure a valid initial password is available to be used
    validatePassword();

    console.log(`
    💾 Creating initial data...
    `);

    // This is a hack to wait for the User table to be provisioned by Keystone
    await (() => setTimeout(() => Promise.resolve(), 2000))();

    await keystone.createItems(initialData);
  }

  console.log(`
    💾 User created:
  email: ${initialData.User[0].email}
  password: ${initialData.User[0].password}

  Please change these details after initial login.
`);

};

const initialData = {
  User: [
    { name: 'Admin User', email: 'admin@example.com', isAdmin: true, password },
  ]
};
```

@MadeByMike > Is there any way to have a callback on Database provisioning success instead of on connection? (which is too soon for the data to be inserted in PostgreSQL as the DB schema is not yet setup).

**Comment by MadeByMike** [comment]
Hi folks. Apologies for the late reply. It's likely you need to run `yarn create-tables`. Check the release notes for the Arcade release for context on why: https://www.keystonejs.com/discussions/new-data-schema/#arcade---a-new-data-schema-for-keystone

In short Keystone will not automatically initialise an SQL database but there is a command to do this. The docs on seeding tables are here: https://www.keystonejs.com/quick-start/#installing-keystone

**Comment by aeblin** [comment]
@MadeByMike Hey Mike, wanted to note that I just ran through the Quick Start, which, like the CLI, recommends seeding the tables with `yarn keystone create-tables` 
Doing so resulted in the following error - `Error: No executable schema named 'public' is available. Have you setup '@keystonejs/app-graphql'?
    at Keystone._executeOperation (/Users/user/keystone/node_modules/@keystonejs/keystone/lib/Keystone/index.js:132:9)
    at Keystone.executeQuery (/Users/user/keystone/node_modules/@keystonejs/keystone/lib/Keystone/index.js:276:19)
    at Object.module.exports [as onConnect] (/Users/aeblin/ripster/initial-data.js:10:22)
    at Keystone.connect (/Users/user/keystone/node_modules/@keystonejs/keystone/lib/Keystone/index.js:494:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createTables (/Users/user/keystone/node_modules/@keystonejs/keystone/bin/commands/create-tables.js:11:3)`

However, what you suggest here `yarn create-tables` ran successfully, and didn't encounter that same error. I'm not sure whether this has something to do with my local environment or not, but you may want to update the messaging in the CLI and the Quick Start if not.

**Comment by timfee** [comment]
I have a brand new repo with the same problems (for pgsql):
```
keystone@timfee:/var/www/timfee.dev$ npx keystone create-tables
ℹ Command: keystone create-tables
⠙  No cookieSecret value was provided. Please generate a secure value and add it to your app. Until this is done, a random cookieSecret will be generated each time Keystone is started. This will cause sessions to be reset between restarts. See [https://www.keystonejs.com/keystonejs/keystone/#cookiesecret] for details.
⠹  Knex adapter: Dropping database
✖
Error: No executable schema named 'public' is available. Have you setup '@keystonejs/app-graphql'?
    at Keystone.executeGraphQL (/var/www/timfee.dev/node_modules/@keystonejs/keystone/lib/Keystone/index.js:230:13)
    at Object.module.exports [as onConnect] (/var/www/timfee.dev/initial-data.js:10:22)
    at Keystone.connect (/var/www/timfee.dev/node_modules/@keystonejs/keystone/lib/Keystone/index.js:438:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```


```
const adapterConfig = { knexOptions: { connection: 'postgres://keystone:keystone@localhost/keystone' }
```

This is despite `psql postgres://keystone:keystone@localhost/keystone` loading correctly:

```
keystone@timfee:/var/www/timfee.dev$ psql postgres://keystone:keystone@localhost/keystone
psql (12.4 (Ubuntu 12.4-0ubuntu0.20.04.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

keystone=# \dn
  List of schemas
  Name  |  Owner
--------+----------
 public | keystone
(1 row)
```

**Comment by dfinton** [comment]
@timfee - Yeah the docs need to be updated as they don't really tell you what to do with a postgres database and the directions provided from command line are incorrect; they tell you to run `npx keystone create-tables` but that just spits out that error you got.

Instead of doing what the instructions tell you, you'll need to run `npm run create-tables` or `yarn create-tables`. Then you can start up keystone in dev mode and it will create the `admin@example.com` user. The output of the command will tell you what the password is (it's randomly generated).

**Comment by pimvanderheijden** [comment]
So the key is to run Keystone in development mode? This is not obvious when in production / Kubernetes...

Previous comment suggests the problem arises from an implicit distinction between NODE_ENV "production" and "development".

So I tried running:
```NODE_ENV=development NODE_CONFIG='{"postgres" : "postgres:5432"}' yarn create-tables```

Added NODE_CONFIG override of my config (https://www.npmjs.com/package/config) because my postgres hostname is different in Kubernetes.

Eventually the result is still the same:
```No executable schema named 'public' is available. Have you setup '@keystonejs/app-graphql'?```

This was unexpected because I can connect to my postgres with the same URL my Keystone app is using ánd I managed to successfully run `yarn create-tables` in local development.

**Comment by pimvanderheijden** [comment]
After quite some struggle finding the right port overrides with the `PORT` env var I managed to run the following command in in Kubernetes inside the keystone app container.

`PORT=4000 NODE_ENV=development CREATE_TABLES=true keystone dev`

This created tables and seeded the database.

**Comment by DungRaymond** [comment]
Had the same problem, ran `npx keystone create-tables` with error returned (looks like it ran with different environment which was not my project's). Should just run `yarn create-tables` which worked fine.
