### ISSUE TITLE
Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env'

### ISSUE THREAD

**Issue by mariohmol** [keystonejs/keystone#2133]
Hi there!

I'm doing my first app using keystonejs and docker. It runs local and in my local docker as well, no problem at all.

But when i try to deploy that docker image to a server, i'm getting a new error.

`Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env'``

I had to use keystonejs version 0.4 (master) because of another error:

* https://github.com/keystonejs/keystone/issues/959#issuecomment-163090545

If i remove `var dotenv = require('dotenv'); ` in the beginning of the keystone.js , it do not shows me this 
`Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env'`` message. But the log is the same (just without that line)
 
Any ideas?

Thanks

````
npm ERR! /opt/app/npm-debug.log
npm ERR! Please include the following file with any support request:

npm ERR! There is likely additional logging output above.
npm ERR! npm owner ls mysite
npm ERR! You can get their info via:
npm ERR! node ./app.js
npm ERR! Tell the author that this fails on your system:
npm ERR! not with npm itself.
npm ERR! This is most likely a problem with the mysite package,
npm ERR! Failed at the mysite@1.0.0 start script 'node ./app.js'.
npm ERR!
npm ERR! Exit status 137
npm ERR! mysite@1.0.0 start: `node ./app.js`
npm ERR! code ELIFECYCLE
npm ERR! npm v2.14.7
npm ERR! node v4.2.3
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! Linux 3.13.0-48-generic
npm info mysite@1.0.0 Failed to exec start script

Killed
development
Environment for Node Process
{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

> node ./app.js
> mysite@1.0.0 start /opt/app

npm info start mysite@1.0.0
npm info prestart mysite@1.0.0
npm info using node@v4.2.3
npm info using npm@2.14.7
npm info it worked if it ends with ok
````

**Comment by mariohmol** [comment]
Sorry guys, it was a problem in my AWS, where has a limited RAM memory. So if you got killed without a warn or error message.. now you know =)

**Comment by Shubhangi1722** [comment]
@mariohmol hey can you please help with this error. how did you solve it

**Comment by mxstbr** [comment]
Add more memory to your AWS instance!

**Comment by morenoh149** [comment]
++ lower keystone memory usage @mxstbr is there an open issue for that?

**Comment by mxstbr** [comment]
I know there used to be one, we might've closed it in the issue triage since I can't seem to find it at the moment. We should probably open a new one!

**Comment by battalian** [comment]
I am getting this error when i tried to install cordova & ionic "sudo npm install -g cordova ionic", what should i do??
![image](https://user-images.githubusercontent.com/18572376/27468289-a9fafe9c-5806-11e7-86e8-09813bf5b82b.jpg)
