### ISSUE TITLE
Expose base64 uploading to Cloudinary for mobile APIs

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#214]
Would be good to have this as an underscore method to simplify the development of APIs for mobile apps with image functionality.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/expose-base64-uploading-to-cloudinary-for-mobile-apis
