### ISSUE TITLE
[docs] Confused about schemaDoc

### ISSUE THREAD

**Issue by thekevinbrown** [keystonejs/keystone#2153]
# Bug report

## Describe the bug

In the docs, `schemaDoc` is a boolean (https://www.keystonejs.com/keystonejs/fields/), but in the ToDo example project: 

```javascript
keystone.createList('Todo', {
  schemaDoc: 'A list of things which need to be done',
  fields: {
    name: { type: Text, schemaDoc: 'This is the thing you need to do' },
  },
});
```

## Expected behaviour

Probably should be a string? What are the valid values for this field?

**Comment by MadeByMike** [comment]
This totally looks like the table was copied and the **type** was not changed. Will fix!

**Comment by MadeByMike** [comment]
Updated the docs to `String`
