### ISSUE TITLE
How to find like mongoose?

### ISSUE THREAD

**Issue by williamhqs** [keystonejs/keystone#2154]
# Question about Keystone

Anyway to make a find like in mongoose?

I googled to see likes a way to find the list results:
```

var keystone = require('keystone'),
    Post = keystone.list('Post');

Post.model.find()
    .where('state', 'published')
    .populate('author')
    .sort('-publishedAt')
    .limit(5)
    .exec(function(err, posts) {
        // do something with posts
    });

```

I tried the same way but `list` method not found. Any way to query the results?

**Comment by Vultraz** [comment]
That is the old keystone 4 method for querying. Keystone 4 was moved to the [keystone-classic](https://github.com/keystonejs/keystone-classic) repo. Keystone 5 and later use GraphQL.

**Comment by jesstelford** [comment]
As @Vultraz says; the new Keystone uses GraphQL for querying (both internally and externally).

In Keystone 5+ (indicated by the `@keystonejs/keystone` package, rather than `keystone-classic`), your example above would be done like so:

```javascript
const { Keystone } = require('@keystonejs/keystone');

const keystone = new Keystone({
  /*...config */
});

keystone.createList('Posts', {
  /*...config */
});

const results = await keystone.executeQuery(`
  query {
    allPosts(
      where: { state: 'published' }, # equivalent to .where('state', 'published')
      sortBy: 'publishedAt_DESC', # equivalent to .sort('-publishedAt')
      first: 5, # equivalent to .limit(5)
    ) {
      id
      title
      author { # equivalent to .populate('author')
        id
        name
      }
    }
  }
`);
```

**Comment by jesstelford** [comment]
@williamhqs hopefully that answers your questions! We also have a Slack group you can ask questions in too: https://launchpass.com/keystonejs

I'll close this question as "answered" for now, but feel free to reopen if you need more help!

**Comment by williamhqs** [comment]
@jesstelford 
Any way to convert the query results from your answer into json data?

I tried the way from the document to get JSON: 

```
const GET_ALL_USERS = `
query GetUsers {
  allUsers {
    name
    id
  }
}`;

fetch('/admin/api', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: {
    query: GET_ALL_USERS,
  },
}).then(result => result.json());
```

but I got error:
```
UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions
```

if I change the path from `admin/api` to `http://localhost:3000/admin/api` then the error is:

```
FetchError: invalid json response body at http://localhost:3000/admin/api reason: Unexpected token < in JSON at position 0
```

Thanks!

**Comment by gautamsi** [comment]
you want to use graphql client library like Apollo or some other.

**Comment by williamhqs** [comment]
@gautamsi Thanks for the tips. Figured it out.
