### ISSUE TITLE
'Adding initial data' is confusing

### ISSUE THREAD

**Issue by datner** [keystonejs/keystone#2158]
# Question about Keystone
in the "Adding initial data" segment, the `keystone.createItems` method is just used implicitly without context. 
This can be quite confusing. It took me some digging to realize to invoke this after keystone is initialized **and** connected to the database, unlike `createList`. This (as far as I understand) is reachable in the `onConnect` hook of the keystone instance.
The issue is that this hook is not referenced anywhere in the segment, the 'starter' project uses a different, more direct approach through graphql mutations, and invoking `createItems` before the connection is actually established throws a vague 
```
cannot read property 'create' of null
```

I think this should either be addressed in the segment, changed in the starter template, or somehow make sure it workes after keystone is initialized synchronously (like with createList)

I might also have encountered a completely different issue and I am wrong, if you recognize this as a misunderstanding, please correct me

**Comment by timleslie** [comment]
Closing as `keystone.createItems` no longer exists 👍

**Comment by datner** [comment]
😅
