### ISSUE TITLE
Creating extra pages in Admin area

### ISSUE THREAD

**Issue by felipenmoura** [keystonejs/keystone#2159]
I was wondering if is there any way to do this, and if not, if this wouldn't be useful for a lot of people.

I want to create some pages that will provide me with some reports, perhaps some charts, based on what is in the db, so I can see the frequency of posts from different authors, who wrote more, etc.
But such page should only be accessible to people who can actually log into Keystonejs.
I wanted to use the keystone admin structure and already restrict area to have the reports.

What do you think about that?

**Comment by morenoh149** [comment]
What would happen if you just put an html file here? https://github.com/keystonejs/keystone/tree/master/admin/public

**Comment by WingedToaster** [comment]
+1 

I would LOVE this. I wrote some code to draw a heat map of all my users but it doesn't seem like I can use it inside the admin section without modifying the keystone node_module.

**Comment by sarmadsangi** [comment]
+1 that be ideal.

**Comment by mxstbr** [comment]
This is firmly on our roadmap after 0.4 is finally released, extensibility of the admin interface is a very important feature we're working towards. We're far ahead, but not fully there yet, but it'll be soon after 0.4! (#2566 is an important step in that direction)

I'll close this issue for now, we've opened a ProductPain for this here, feel free to upvote it: https://productpains.com/post/keystonejs/admin-interface-extensibility

**Comment by jesster2k10** [comment]
Any news on this?
