### ISSUE TITLE
Be able to duplicate a List/document 

### ISSUE THREAD

**Issue by sarmadsangi** [keystonejs/keystone#2161]
Probably a `duplicate` button just besides `new` button to create a duplicate of current document. This is helpful in some cases where document is huge and some people just want to duplicate it and change one or two fields that they want to.

Proposed UI for `EditFormHeader`
![screen shot 2016-01-26 at 2 01 32 pm](https://cloud.githubusercontent.com/assets/640416/12573569/9a160672-c435-11e5-9090-b7acb4c462bd.png)

Same `CreateForm` UI (just copies the values and passes down to `CreateForm` component)
![screen shot 2016-01-26 at 2 04 06 pm](https://cloud.githubusercontent.com/assets/640416/12573580/b2e72064-c435-11e5-9d02-03ac89a55f93.png)

I have done this by forking `master` for one of the projects i am working on as of now, just wondering if its ok for us to have this build in by default in keystone. I checked roadmap on wiki but didn't found any information on this so was wondering if its ok if i send a pull request.

If yes two ways to go about this which i can think of,
1. Always have it there for each List/document
2. Have it configured when creating new List ie `duplicateListLink: true`
```
var Content = new keystone.List('Content', {
      autokey: { path: 'slug', from: 'name', unique: true },
      track: true,
      duplicateListLink: true
});
```

Pardon me if i missed out on any information before creating this issue. Looking forward to hear from you guys :)

**Comment by fabiowitt** [comment]
I was looking for this. It would be great for me. I'm starting to internationalise my documents, I created a new field called "lang" and I filter them depending the lang I get from the header. The best approach for the business team to translate would be to duplicate the object and start translating eaceh field for each language. @sarmadsangi Have you created something on your own? Or just made the suggestion?

**Comment by sarmadsangi** [comment]
@fabiowitt i did a small hack here,
https://github.com/keystonejs/keystone/compare/master...Redmart:feature/duplicateItem

i can clean it up and send a PR if this suggestion is accepted into keystone.

**Comment by mxstbr** [comment]
This is firmly on our roadmap after 0.4 is finally released, extensibility of the admin interface is a very important feature we're working towards. We're far ahead, but not fully there yet, but it'll be soon after 0.4! (#2566 is an important step in that direction)

We're not going to merge this feature specifically into core, since this would be a perfect use case for a admin interface plugin. I'll thus close this issue for now, thanks so much for letting us know this is something you're interested in.

We've opened a ProductPain for this here, feel free to upvote it! https://productpains.com/post/keystonejs/admin-interface-extensibility

**Comment by sarmadsangi** [comment]
thanks @mxstbr i have up voted it. I am actively working on hacking admin ui to add Google Analytics reporting, duplicate and other such stuff. Interface extensibility would be ideal and i would personally help create some extensions/plugins to help it grow.

Cheers!

**Comment by mxstbr** [comment]
Awesome, great to hear! Can't wait to get this feature in and see what everybody comes up with!
