### ISSUE TITLE
Keystone with next.js query

### ISSUE THREAD

**Issue by casperleerink** [keystonejs/keystone#2162]
Hi I have a question regarding using keystone with next.js

I have read that to use server side queries I have to use keystone.executeQuery

However whenever I try to require the keystone instance from the main index.js I get the error:
Can't import the named export 'feature' from non EcmaScript module (only default export is available)

Just starting with keystone 5, so I might be doing something wrong..

Any help in the right direction towards getting data into my next.js website would be helpful!

Thanks

**Comment by johnniehard** [comment]
I'm new to this as well so I don't know for sure just yet. But my understanding is that you would use the generated API endpoints as in this example using fetch: https://www.keystonejs.com/guides/intro-to-graphql#executing-queries-and-mutations

**Comment by dijs** [comment]
I am stuck on this as well. Did someone ever figure this out?

This seems like a crucial part of getting data into your next app via keystone.

**Comment by gautamsi** [comment]
have you looked at [this](https://github.com/keystonejs/keystone/blob/master/demo-projects/meetup/site/pages/_app.js)? you can use apolloClient for this which is on ctx object. 

if `ctx.req` is available, you are server side and you can still use the apolloclient

**Comment by dijs** [comment]
`apolloClient` is undefined in my `ctx.req`

**Comment by gautamsi** [comment]
apollo client is at `ctx.apolloClient`

`ctx.req` means you are on server (rendered)

**Comment by gengue** [comment]
I have the same problem a using redis queue, when the job executes, I try to import keystone instance from `index.js` but I get this `UnhandledPromiseRejectionWarning: Error: Attempted to execute keystone.query() before keystone.prepare() has completed.`

example:

```js
// queue definition
const Queue = require('bull');
var videoQueue = new Queue('video transcoding', 'redis://127.0.0.1:6379');

// job processor
const { keystone } = require('./../../index');

videoQueue.process(function(job, done) { 
  // some heavy work here ...
  // update record
  const variables = { reportId: job.data.id }
  const { errors, data } = await keystone.executeQuery(
    `
        mutation UpdateReport($reportId: ID!) {
          updateReport($reportId, data: { videoIsReady: true }) {
            id
            status
            type
          }
        }
      `,
    { variables }
  );
}

```

I am wondering how can I use `executeQuery` securely outside client side or keystone lists

**Comment by gautamsi** [comment]
you may be triggering this executeQuery before prepare is completed, you can either have some flag for prepare and wait for that flab being true, or trigger the process function in `keystone. onConnect` callback

**Comment by gengue** [comment]
Thank you, I solved it setting the queue inside `onConnect` callback:

index.js
```javascript
const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new MongooseAdapter({
    mongoUri: 'mongodb://127.0.0.1/my-webapp',
  }),
  onConnect: instance => {
    initializeData(instance); // create admin user on first time
    queues.setProcess('bots', runBot(instance));
  },
});
````

queues.js
```javascript
const path = require('path');
const Queue = require('bull');

class QueuesManager {
  queues = {};

  constructor(conn) {
    conn.forEach(c => {
      this.queues[c.name] = new Queue(c.name, c.setup);
      if (conn.handler) {
        this.queues[c.name].process(conn.handler);
      }
    });
  }

  getQueue(name) { /* */ }
  getAllQueues() {/* */ }
  add(name, params) { /* add a new queue */ }

  // set a process handler to the queue
  setProcess(name, handler, concurrency = 10) {
    this.queues[name].process(concurrency, handler);
  }
}

const queues = new QueuesManager([
  { name: 'bots', setup: 'redis://127.0.0.1:6379' },
]);

module.exports = queues;

```

**Comment by gautamsi** [comment]
for anyone still looking for solution

you can add keystone instance to `request` object which is `context.req` or `ctx.req` based on where you are looking at.

this works in hooks context, custom graphql context, nextjs and any other place where the incoming request is exposed.

```js
module.exports = {
  keystone,
  apps: [
    // apps
  ],
// this is what you do to have keystone added to request obejct
  configureExpress: app => {
    app.use((req, res, next) => {
      req.keystone = keystone;
      next();
    });
  },
  distDir,
};
```

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
