### ISSUE TITLE
[0.3][0.4] error passed from update script disappears into the void

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#2164]
A bug was introduced here https://github.com/keystonejs/keystone/blob/cdc8655fdb1beabbcb2c801e13ad316f92a5bf7f/lib/updates.js#L109

As you can see nothing happens when the `err` object is truthy. The same applies to https://github.com/keystonejs/keystone/blob/cdc8655fdb1beabbcb2c801e13ad316f92a5bf7f/lib/updates.js#L100
This means that if you pass an error from your update script, everything hangs and nothing is written to the out stream, keystone just sits there waiting.

@webteckie what do you think, is this as easily solved as I think, just by adding:

``` js
}else{
    done(err);
}
```

??

**Comment by webteckie** [comment]
@creynders yeah, it seems like a bug not to call done(err).  However, if memory serves me well even if you did that the process would exit before the logs would be flushed.  And it may be one of those intermittent things.  The updates function (e.g., createItems) should be logging the error.  Anyways, feel free to fix, at least, not to hang the process :-)

**Comment by JedWatson** [comment]
@webteckie fixed by #2197?

**Comment by mxstbr** [comment]
_ping_ @webteckie is this fixed?

**Comment by Noviny** [comment]
Going to close this as solved by #2197. Happy to reopen if it's not.
