### ISSUE TITLE
npm init keystone-app my-app fails

### ISSUE THREAD

**Issue by bothwellw** [keystonejs/keystone#2164]
Hi

I am following the getting started documentation and I am getting this error when I run 

npm init keystone-app my-app

npx: installed 61 in 15.448s
(node:10908) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Colorize (C:\Users\dev\AppData\Roaming\npm-cache\_npx\10484\node_modules\create-keystone-app\node_modules\cfonts\lib\index.js:328:69)
    at AddLetterSpacing (C:\Users\dev\AppData\Roaming\npm-cache\_npx\10484\node_modules\create-keystone-app\node_modules\cfonts\lib\index.js:412:17)
    at Render (C:\Users\dev\AppData\Roaming\npm-cache\_npx\10484\node_modules\create-keystone-app\node_modules\cfonts\lib\index.js:788:14)
    at Object.Say [as say] (C:\Users\dev\AppData\Roaming\npm-cache\_npx\10484\node_modules\create-keystone-app\node_modules\cfonts\lib\index.js:884:15)
    at showWelcomeMessage (C:\Users\dev\AppData\Roaming\npm-cache\_npx\10484\node_modules\create-keystone-app\lib\show-welcome-message.js:4:10)
    at C:\Users\dev\AppData\Roaming\npm-cache\_npx\10484\node_modules\create-keystone-app\bin\cli.js:14:3
    at Object.<anonymous> (C:\Users\dev\AppData\Roaming\npm-cache\_npx\10484\node_modules\create-keystone-app\bin\cli.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:10908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by masbossun** [comment]
experienced same issue using `yarn create`

**Comment by zoltanradics** [comment]
Same for me. Neither npm or yarn install works at the moment.

**Comment by dufemeng** [comment]
I also have this problem.

**Comment by joshhopkins** [comment]
Same issue.

**Comment by SDroidLabs** [comment]
Having the same issue

**Comment by swr7der** [comment]
Having the same issue

**Comment by rkefi84** [comment]
Same issue using both commands

**Comment by chris-kobrzak** [comment]
Same problem here.

I have tried both `npm init` and `yarn create` commands to create the app on several versions of Node.js (10, 12 and 13), both on macOS and Ubuntu 18.04.

**Comment by brstkr** [comment]
Same problem here. 
Also didn't worked for me with trying the solution from @chris-kobrzak  .

**Comment by TylerSustare** [comment]
I'm having the same issue. I was all excited to try out keystone after the syntax episode today

**Comment by souljacker** [comment]
Same here 👎

**Comment by seanrreid** [comment]
Same,  `npm` and `yarn`.

**Comment by MurrayJack** [comment]
jumping on this bandwaggon, doesn't work for me either :(

**Comment by anselmdk** [comment]
Me neither. Neither npm nor yarn works.

**Comment by dominikwilkowski** [comment]
This should be fixed via #2188 
I just checked that it works with the latest.

**Comment by bothwellw** [comment]
it works..
![image](https://user-images.githubusercontent.com/16897613/72011749-28730880-3263-11ea-91ae-2b201b8b68e6.png)

**Comment by wesbos** [comment]
👋🏻 Syntax listeners!

**Comment by nasouhmr** [comment]
Same issue on npm and yarn

**Comment by Yinear** [comment]
Same issue on npm and yarn, its 2021.

**Comment by dominikwilkowski** [comment]
@Yinear The original issue has been fixed and I just verified that it has so can you please add more details so we know what you mean. Step me through what you're doing to make it fail?

**Comment by vurtne0511** [comment]
Same issue +1, its 2021.

**Comment by SergiOca87** [comment]
Same issue.

**Comment by SergiOca87** [comment]
> @yinear The original issue has been fixed and I just verified that it has so can you please add more details so we know what you mean. Step me through what you're doing to make it fail?
> 
> Running `npm init keystone-app my-app` on node v14 works just fine for me:
> <img alt="Screen Shot 2020-12-29 at 6 10 31 pm" width="707" src="https://user-images.githubusercontent.com/1266923/103265231-36381580-4a01-11eb-9b6b-4a8778bea0ce.png">

Fails with node 16

**Comment by filipe-freire** [comment]
> > @yinear The original issue has been fixed and I just verified that it has so can you please add more details so we know what you mean. Step me through what you're doing to make it fail?
> > Running `npm init keystone-app my-app` on node v14 works just fine for me:
> > <img alt="Screen Shot 2020-12-29 at 6 10 31 pm" width="707" src="https://user-images.githubusercontent.com/1266923/103265231-36381580-4a01-11eb-9b6b-4a8778bea0ce.png">
> 
> Fails with node 16

Can confirm this, using the LTS (14.17.3) version allowed me to run `npm init keystone-5-app my-app` with no issues. ✌🏻
