### ISSUE TITLE
Error uploading to S3 using read streams and putObject

### ISSUE THREAD

**Issue by BitForger** [keystonejs/keystone#2165]
# Bug report

I was trying to use the S3 adapter to upload files in the admin api using the File field type. When attempting to upload the file I would get a 'nested errors' message. There wouldn't be anything in the CLI log where the app was running. I had make my own version of the adapter in a stand-alone project locally to debug this. Essentially, the file is getting a read stream and the `putObject` method of the AWS SDK expects a binary string. This can be resolved by using the `upload` method as it is smart and can handle read streams. I can prepare a PR if you would like.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Setup S3 file adapter like demonstrated in the documentation.
2. Try to upload file
3. Error

## Expected behaviour

Uploading a file should work

## Screenshots

![https://dsh.re/7c44e](https://dsh.re/7c44e)

## System information

- OS: Linux (Docker)

## Additional context

https://github.com/keystonejs/keystone/blob/1d7f2e62756f054f0b2ba1c34043387e9f945393/packages/file-adapters/lib/s3.js#L39

**Comment by LiamAttClarke** [comment]
According to the docs, s3.putObject accepts "Buffer, Typed Array, Blob, String, **ReadableStream**".

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

**Comment by BitForger** [comment]
@LiamAttClarke yeah I see that. I don't know why it doesn't work with that implementation. When I've used the SDK I've always used `putObject` with Buffers or binary strings and it's worked fine. Maybe there is a bug in the SDK when dealing with ReadStreams? All I can tell you is that I replicated the behavior using my own plugin and that I was able to fix it using the `#upload` method on the S3 SDK.

**Comment by LiamAttClarke** [comment]
> @LiamAttClarke yeah I see that. I don't know why it doesn't work with that implementation. When I've used the SDK I've always used `putObject` with Buffers or binary strings and it's worked fine. Maybe there is a bug in the SDK when dealing with ReadStreams? All I can tell you is that I replicated the behavior using my own plugin and that I was able to fix it using the `upload` method on the S3 SDK.

I'm using the S3Adapter without issue. Could you post the constructor options you passed to the S3Adapter?

**Comment by LiamAttClarke** [comment]
@BitForger I was able to reproduce this error when uploading via the GraphQL api. Send over your PR for this fix. I'll test on my machine as well.

**Comment by BitForger** [comment]
@LiamAttClarke #2249 is exactly what I did to fix it.

**Comment by chalupagrande** [comment]
I had a similar issue. I ended up randomly commenting out the uploadParams (as they were recommended in the docs and it started working 🤷 

```
// uploadParams: ({ filename, id, mimetype, encoding }) => ({
//   Metadata: {
//     keystone_id: id,
//   },
// }),
```

**Comment by borg** [comment]
Because of [this](https://github.com/keystonejs/keystone/pull/3351) I think
