### ISSUE TITLE
Add a telephone field

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2173]
This may be a bit challenging but I think it would be good to consider it.  Some reference:  https://en.wikipedia.org/wiki/E.164

**Comment by andrewlinfoot** [comment]
Probably wouldn't be as bad as you think because we could piggyback off some existing libraries. Check out https://github.com/mukeshsoni/react-telephone-input and https://github.com/wajatimur/node-phonenumber

**Comment by webteckie** [comment]
Alright sounds good :-)

**Comment by prachi-159** [comment]
In which file this feature has to be added?

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, upvote it there if you want this: https://productpains.com/post/keystonejs/telephone-field!
