### ISSUE TITLE
Add a credit card field

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2174]
There's probably standard guidelines for credit card validations.  For example:  https://adywicaksono.wordpress.com/2008/02/17/how-to-validate-credit-card-number/

**Comment by johannes-scharlach** [comment]
Stripe built an awesome opensource jQuery library that does that
https://github.com/stripe/jquery.payment

it even detects what credit card it is and is extensible by custom card types, if necessary.

As per the backend: I think it sends the wrong kind of signal to make it easy to store credit card numbers in the database... In most countries that's highly illegal without having the right kind of PCI compliance , so people should be discouraged from that.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/credit-card-field!
