### ISSUE TITLE
How to change admin UI logo

### ISSUE THREAD

**Issue by williamhqs** [keystonejs/keystone#2175]
# Question about Keystone

1. How to change the admin UI logo? Like in v4 it's:
`keystone.set('signin logo', '../correct/path/logo.png');`

2. Any way to hidden a field that has a default value in the admin UI? for example the `uploadedAt` hide it from UI?

Hide this part, I want to hide it because it has the default value:

<img width="553" alt="aaa" src="https://user-images.githubusercontent.com/354829/71639824-00126980-2cb9-11ea-9763-2e1c274b36f4.png">

```
keystone.createList('TextList', {
  fields: {
   ...
    uploadedAt: {
      type: DateTime,
      format: 'MM/DD/YYYY h:mm A',
      yearRangeFrom: '2019',
      yearRangeTo: '2025',
      yearPickerType: 'select',
      defaultValue: new Date(),
    }
  },
});
```

Another question is even set up `yearPickerType` to `select`, no picker UI displayed, also the `CaldenarDay` type has no picker too.

Thanks for the help!

**Comment by Vultraz** [comment]
`CaldenarDay` does not currently have a picker.

**Comment by HackerYunen** [comment]
same question.

**Comment by abhijithvijayan** [comment]
Did someone figure this out?

Setting a custom admin UI logo?

**Comment by HackerYunen** [comment]
> Did someone figure this out?
> 
> Setting a custom admin UI logo?

If you are really want to change the default logo, you can edit the `@keystonejs/app-admin-ui/client/components/KeystoneLogo.js`  file, the default logo svg is in there :)

**Comment by abhijithvijayan** [comment]
oh that's not a feasible solution is it?

Next `yarn install` will overwrite the changes

**Comment by HackerYunen** [comment]
> oh that's not a feasible solution is it?
> 
> Next `yarn install` will overwrite the changes

Yes, keystonejs version 5 remove the default logo hook, this issue is link to pull request #2474, you can wait for it.

**Comment by aamir-bitsol** [comment]
You can change the sign in page image, by following the path, same as that in keystone node_modules
