### ISSUE TITLE
Can not request restful API on heroku

### ISSUE THREAD

**Issue by sanglnv** [keystonejs/keystone#2176]
Hi, I faced with an issue that can not request rest API after deployed to Heroku, enabled cors request on keystone v4 as below:
1. set 'cors allow origin' to true
2. set "api/v1/*" with keystone.middleware.cors

-> the response is **The document has moved**

Regards

**Comment by timleslie** [comment]
Keystone v4 issues should be opened at https://github.com/keystonejs/keystone-classic
