### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by ronenteva** [keystonejs/keystone#2184]
Hey,
I'm new to KeystoneJS and wonder about the status of social login?
I saw an old plugin but but it's unsupported since 0.2.
Is there any docs on how to implement passport.js authentication manually?

Also, how safe it is to start using 0.4? 
Should I expect mostly bugs in the admin panel, or in the core features as well?

Thanks.

**Comment by morenoh149** [comment]
please ask in the [gitter](https://gitter.im/keystonejs/keystone)

**Comment by ronenteva** [comment]
What a disappointing answer.

**Comment by creynders** [comment]
@ronenteva I understand your disappointment, but we try to limit the GH issues to bug reports, feature requests and API discussions. We're flooded already, if this becomes a support channel too our ship will sink ;)

**Comment by erg0dic** [comment]
@ronenteva You can find an example keystone site that uses social login here:
https://github.com/JedWatson/sydjs-site
