### ISSUE TITLE
Knex + Keystone 5?

### ISSUE THREAD

**Issue by sarink** [keystonejs/keystone#2184]
I can't seem to get the latest knex adapter (using postgres) and latest keystone to create any of my tables. I see a lot of other issues like https://github.com/keystonejs/keystone/issues/2133

I'm just wondering if there is a version of knex or keystone that we can downgrade to to get this to work? Or some other workaround? I'm starting a new project and I don't want to use mongo.

Thanks

**Comment by MadeByMike** [comment]
Apologies for the late reply. It's likely you need to run `yarn create-tables`. Check the release notes for the Arcade release for context: https://www.keystonejs.com/discussions/new-data-schema/#arcade---a-new-data-schema-for-keystone

The docs on seeding tables have also been updated here:

https://www.keystonejs.com/quick-start/#installing-keystone

And if you are running an existing database that needs to be migrated you can find more on that here: https://www.keystonejs.com/guides/relationship-migration
