### ISSUE TITLE
Datetime type graphql Validation failed after resolveInput hook

### ISSUE THREAD

**Issue by sinbargit** [keystonejs/keystone#2186]
# Bug report

I use the resolveInput hook but do nothing on the resolvedData except return it directly:
```
updated: {
            type: DateTime, format: 'DD/MM/YYYY h:mm A',
            hooks: {
                resolveInput: ({
                                         operation,
                                         existingItem,
                                         originalInput,
                                         resolvedData,
                                         context,
                                         actions,
                                     }) => {
                    return resolvedData;
                }
            }
        }
```
But when I save the data, there is a error: 
`{"errors":[{"message":"Validation failed: DateTime must be either `null` or a valid ISO 8601 string","locations":[{"line":2,"column":3}],"path":["updatePost"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Validation failed: DateTime must be either `null` or a valid ISO 8601 string","    at item (C:\\code\\blog\\node_modules\\@keystonejs\\fields\\dist\\fields.cjs.js:2437:15)","    at pReduce (C:\\code\\blog\\node_modules\\p-waterfall\\index.js:5:43)","    at next (C:\\code\\blog\\node_modules\\p-reduce\\index.js:17:9)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}},"uid":"ck50qsg1w0001e4wlaauqakcs","name":"GraphQLError"}],"data":{"updatePost":null},"extensions":{"tracing":{"version":1,"startTime":"2020-01-05T08:16:30.704Z","endTime":"2020-01-05T08:16:30.787Z","duration":82914099,"execution":{"resolvers":[{"path":["updatePost"],"parentType":"Mutation","fieldName":"updatePost","returnType":"Post","startOffset":2626500,"duration":79113000},{"path":["_allPostsMeta"],"parentType":"Query","fieldName":"_allPostsMeta","returnType":"_QueryMeta","startOffset":49866900,"duration":821900},{"path":["_allPostsMeta","count"],"parentType":"_QueryMeta","fieldName":"count","returnType":"Int","startOffset":50864900,"duration":20309299}]}}}}`
And my request payload is: 
`{"operationName":"update","variables":{"id":"5e1180420891a121280cf095","data":{}},"query":"mutation update($id: ID!, $data: PostUpdateInput) {\n  updatePost(id: $id, data: $data) {\n    id\n    __typename\n  }\n}\n"}`

**Comment by Vultraz** [comment]
From my testing, I see `resolvedData` is an object that looks something like this:
```js
{ [fieldName]: '2019-12-12T07:00:00.000+11:00' }
```
You'll want to return `resolvedData.updated` in your case.

For the record, if you're attempting to add time updated tracking, there is a [list plugin](https://www.keystonejs.com/keystonejs/list-plugins/at-tracking) for that.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
