### ISSUE TITLE
Doesn't work in Safari on ios

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#2192]
Can't view the record on iPhone/iPad, show white screen.
There is an error on debugger:
```
SyntaxError: Attempted to redefine property 'downloadItems'.
```
I found that in `/admin/client/stores/CurrentListStore.js` the function `downloadItems` defines twice, and they are identical.

**Comment by JedWatson** [comment]
Thanks for picking that up @w01fgang!
