### ISSUE TITLE
Initial Modal is Clueless

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2199]
The initial modal is clueless...what exactly is a user supposed to enter?  Some apps want to offer part of the Admin UI to visitors who are not Admin UI experts.  For example, in the following it would be nice if the Admin UI actually spelled out that it wants a Post Title

![image](https://cloud.githubusercontent.com/assets/5872515/12698680/31c24c90-c771-11e5-9adb-243febe3bcc8.png)

To me the following reads more useful:

![image](https://cloud.githubusercontent.com/assets/5872515/12698708/c5554804-c771-11e5-98cf-3b1404a939e4.png)

**Comment by snowkeeper** [comment]
Adding `initial: true` will give you the field name or `label` value.

![screenshot_2016-01-30_22-14-57](https://cloud.githubusercontent.com/assets/6615106/12699989/1eeff274-c79f-11e5-8f0c-a56b9f3781ee.png)

**Comment by webteckie** [comment]
@snowkeeper you are absolutely right, missed that on this particular list :-)  However, since the Admin UI still works fine without it should I leave this open to display, at least, the name or mapped name?

**Comment by mxstbr** [comment]
Good point, I'll mark this as a bug since that's not very user friendly. Good catch!

**Comment by vseprav** [comment]
Is it make sense fix this issue in https://github.com/keystonejs/generator-keystone repo? Just add `initial: true`  in https://github.com/keystonejs/generator-keystone/tree/master/app/templates/models

**Comment by gautamsi** [comment]
closing in favor of #1840. workaround is also provided in comments. 
given that Keystone 4 is going in maintenance mode (see #4913 for details), this may not be addressed as critical bug.
