### ISSUE TITLE
Implement a way to customise / replace the Admin UI Theme

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#220]
The Admin UI Theme was designed to be either extended or replaced using LESS, and defaults to vanilla Bootstrap styling.

Let's expose a way for projects to add in their own less files to customise the UI, or a way to provide a complete theme.

**Comment by nikolowry** [comment]
Any news on this? Don't want to touch the source or inject on front-end.

**Comment by morenoh149** [comment]
@nikolowry you're going to have to as of this writing.

**Comment by nikolowry** [comment]
@morenoh149 no worries. 

However, I'll share what my solution was for future reference. In addition to allowing theming, it also allows for the admin backend url to be something other than "/keystone".

https://gist.github.com/nikolowry/5083ecd1d0499ab5f44c/.

----

Quick overview:
Because I didn't want to edit the source, I overrode the keystone's private methods "routes" and "render".  The custom methods check for newly introduced env variables and renders accordingly.

![screenshot from 2015-01-13 18 55 52](https://cloud.githubusercontent.com/assets/597310/5731819/18f6cbfc-9b56-11e4-891c-4567a206b99d.png)

**Comment by metasansana** [comment]
I think the landing page could be swapped for a SPA. Provide a clean ajax interface for manipulating the lists and an option that lets users switch off all the other routes. 

That way all the user has to do is intercept the /keystone route and it's like you have your own theme right?

It's a start.

**Comment by joaosamouco** [comment]
How is this going? 
Did you guys came to any conclusion about how this should be built?

**Comment by magalhas** [comment]
It would be awesome to be able to hook features into the backoffice as we do for the NavBar. Are there any plans for it? If not, is a PR welcome?

**Comment by morenoh149** [comment]
PR is welcome. Current focus is on adding testing to project and dynamically generating the browserify build at run-time.

**Comment by binhwpo** [comment]
I really want this feature too. Need something to be flexible.

**Comment by vikrant1011** [comment]
a modular structure is required.

if i have to use keystone on 5 different projects, its a minimum requirement to have different admin interfaces else i'll keep on getting confused as to which app I am currently logged into. 

plz let it be modular.

**Comment by vikrant1011** [comment]
https://github.com/keystonejs/keystone/issues/322

**Comment by JedWatson** [comment]
Here's an update, this is a major current dev focus right now that I'm undertaking with @jossmac.

1. We're transitioning to use [Elemental UI](http://elemental-ui.com) (which replaces bootstrap). At the end of this process, the Admin UI will be an SPA, and jQuery et al. will be removed. See the `elemental-integration` branch for progress.
2. I'm refactoring the express app initialisation process to use Express Router objects. This will streamline integrating Keystone into a custom express app.
3. I've rewritten our Admin UI browserify process to support dynamic source, which will (shortly) allow you to include your own code in the Admin UI to extend or replace parts of it. It also significantly improves load times.
4. We'll do something similar with the LESS which will allow you to include your own theme file that can change variables (Elemental is highly customisable), override classes or add your own.
5. The home page has been redesigned (slightly) and will allow custom components to be provided for the new list 'tiles'.

I expect when all this lands, it'll be released as 0.4.0 because it doesn't seem like the scope of change that should be released in a patch. There may also be some breaking changes, and it will need a fair amount of testing in the wild.

**Comment by vikrant1011** [comment]
super!! 

will be waiting to do extensive testing (Y)

**Comment by sphvn** [comment]
Glad to hear this. Will await patiently.

**Comment by dallasbpeters** [comment]
:+1:

**Comment by heyallan** [comment]
+1

**Comment by yn5** [comment]
+1

**Comment by wmertens** [comment]
So what is the actual desired feature?

It seems to me that you should be able to specify the less in the keystone configuration and this will result in it a keystone admin build with the new css.

* This means that an admin build for the UI must get the config at build time, and then build a custom build for the UI.
* This means that the Keystone UI modules must be pre-built as ES5 source but not as a bundle, and that the build process must be able to read the keystone config.

Right? Seems to me that that build process would be a different feature to be made for 4.0?

**Comment by oliverwh** [comment]
hi, any news here?

**Comment by mxstbr** [comment]
Yeah, this is more-or-less done, but we're working on an admin interface rework (#2566) so we don't recommend doing anything yet since everything will change.

**Comment by keith24** [comment]
Reworked UI looks great!  But I still don't know how to override the new admin styles...

**Comment by lazamar** [comment]
While people wait, just create a task that adds your custom stylesheet to Keystone's admin UI and override the theme.

You can automate that, to run it after updates, with something like this:
``` javascript

    // Load UI template fileu
    const buff = fs.readFileSync('node_modules/keystone/admin/server/templates/index.html');
    const content = buff.toString();

    const styleLink = '<link rel="stylesheet" href="/styles/site.css">';

    // If already links to our stylesheet we have nothing else to do
    if (content.includes(styleLink)) {
      return;
    }

    // Add link to our stylesheet at the end of <head>
    const newContent = content.replace('</head>', `${styleLink} \n </head>`);
    fs.writeFileSync('node_modules/keystone/admin/server/templates/index.html', newContent);
```

**Comment by vincentracine** [comment]
@lazamar What file would you put this code snippet in?

**Comment by lazamar** [comment]
@vincentracine This would be the content of a task from Gulp or Grunt. If you are not using any of them you can just create a `js` file in your root with this snippet and make sure to execute it every time you update keystone. For that you can add a `postinstall` script in your `package.json` telling it to execute this snippet.

**Comment by TitchyDean** [comment]
Here is our working code altered from what @lazamar wrote to use custom styling for the admin UI if this helps anyone!

```
// Load UI template files
const fs = require('fs');
const buff = fs.readFileSync('node_modules/keystone/templates/layout/base.jade');
const content = buff.toString();

const styleLink = 'link(rel="stylesheet", href="/styles/admin.css")';

// If it already links to our stylesheet we have nothing else to do
if (content.includes(styleLink)) {
    console.log("Admin CSS already applied.");
    return;
}

// Add link to our stylesheet at the end of <head>
const newContent = content.replace('block css', `${styleLink}\n\t\tblock css`);
fs.writeFileSync('node_modules/keystone/templates/layout/base.jade', newContent);
console.log("Applied styling!");
```

**Comment by hari419** [comment]
Can anyone suggest a code which can override the keystone.min.css in keystonejs?

**Comment by oliverwh** [comment]
u should work with less files. css generated from there @hari419

**Comment by hari419** [comment]
Tq, but i tried that, its not working...
styles are applied from node modules i.e.., keystone.
can you mention the code which can override that styles?

**Comment by daominhsangvn** [comment]
@hari419 Try this,

```
// Load UI template files
const fs = require('fs');
const path = require('path');
console.log(__dirname);
const buff = fs.readFileSync(path.join(__dirname, '../node_modules/keystone/admin/server/templates/index.html'));
const content = buff.toString();

const styleLink = '<link rel="stylesheet" href="/styles/admin.css">';

// If it already links to our stylesheet we have nothing else to do
if (content.includes(styleLink)) {
	console.log("Admin CSS already applied.");
	return;
}

// Add link to our stylesheet at the end of <head>
const newContent = content.replace('</head>', `\t${styleLink}\n </head>`);
fs.writeFileSync(path.join(__dirname, '../node_modules/keystone/admin/server/templates/index.html'), newContent);
console.log("Applied styling!");

```

**Comment by Jtosbornex** [comment]
This seems to be the accepted approach now:

...
`'adminui custom styles' : '/path/to/admin.less',`
...


Inside of admin.less

`@import "../../node_modules/keystone/admin/public/styles/keystone.less";`
