### ISSUE TITLE
Optimize database queries to only pull out fields actually requested

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#220]
Can use [the `info` parameter passed to the resolver](https://www.prisma.io/blog/graphql-server-basics-demystifying-the-info-argument-in-graphql-resolvers-6f26249f613a/) to pick out only the fields.

Eg, given this schema:

```graphql
type User {
  id: ID!
  name: String
  avatar: Blob
  longVideo: Blob
}
```

When we do a query like:

```graphql
User(id: "foobar") {
  id
  name
}
```

We don't want to pay the cost of pulling the `avatar` and `longVideo` out of the database.

In the resolver, we can use the `info` parameter to see what fields are actually requested:

```javascript
const resolvers = {
  User: (_, { id }, context, info) => {
    const nodeQueryInfo = info.fieldNodes[0]; // 0th is always the currently resolving node
    const fields = nodeQueryInfo.selectionSet.selections.map(({ name }) => name.value);
    return db.findById(id, fields); // (or `SELECT ${fields.join()} FROM ...`, etc)
  },
};
```

**Comment by MadeByMike** [comment]
@timleslie was any of this optimised with the relationship restructure?

**Comment by timleslie** [comment]
> @timleslie was any of this optimised with the relationship restructure?

Nope, this issue is still in the category of nice to have, but tricky to implement.
