### ISSUE TITLE
Cannot find module error and solution

### ISSUE THREAD

**Issue by The-Outrider** [keystonejs/keystone#2202]
Hey Guys:

Packages:

node 4.2.4 
keystone 0.3.16

When trying to fetch a req.params.id the following error happens.

{ [CastError: Cast to ObjectId failed for value "17ZDwpKiCRYfXWLuq4I9FPWG" at path "_id"]
  message: 'Cast to ObjectId failed for value "17ZDwpKiCRYfXWLuq4I9FPWG" at path "_id"',
  name: 'CastError',
  type: 'ObjectId',
  value: '17ZDwpKiCRYfXWLuq4I9FPWG',
  path: '_id' }

A well documented issue on why: https://github.com/Automattic/mongoose/issues/2729

Solved by upgrading mongoose to 4.3.7 and doing an npm install on the keystone folder to update packages.

Also it got rid of this odd error I got when always running node keystone.

<img width="748" alt="screen shot 2016-01-31 at 9 23 48 am" src="https://cloud.githubusercontent.com/assets/6240904/12703275/60cbf74e-c7fc-11e5-838e-498ab7995c46.png">

**Comment by The-Outrider** [comment]
Small edit update. In case anyone replies only to email on this.

**Comment by The-Outrider** [comment]
Ok I found out that the CastError either was a PEBCAK error or the  3.8.38 version solved it.

However updating mongoose does remove that Cannot find module error.

**Comment by mxstbr** [comment]
Thanks for pinging us about this!
