### ISSUE TITLE
Min Max character support.

### ISSUE THREAD

**Issue by The-Outrider** [keystonejs/keystone#2203]
So mongoose supports the min max character lengths. 

http://mongoosejs.com/docs/api.html#schema_string_SchemaString-maxlength

Is anyone working towards supporting this? Or is there anything currently for any of the fields?
Doesn't work for String atm.

**Comment by mahnunchik** [comment]
Hi @JedWatson @mxstbr @The-Outrider 

It would be really useful to have [`maxlength`](http://mongoosejs.com/docs/api.html#schema_string_SchemaString-maxlength) and [`minlength`](http://mongoosejs.com/docs/api.html#schema_string_SchemaString-minlength) validators.

**Comment by mxstbr** [comment]
Please go ahead and implement them on the `text` field type! We'd love to have them!

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/field-validation-max-characters!
