### ISSUE TITLE
Inheritance lists is in alphabetical order?

### ISSUE THREAD

**Issue by terenzeyuen** [keystonejs/keystone#2206]
Maybe I am doing it wrongly but this is my set up:

Lifestyle (parent)

Events (inherits Lifestyle)

Then when Keystone loads events model, it doesnt have access to Lifestyle since it is not loaded yet. :(

**Comment by webteckie** [comment]
Duplicate of #1553

**Comment by terenzeyuen** [comment]
Thanks
