### ISSUE TITLE
Inheritance – E11000 duplicate key error index

### ISSUE THREAD

**Issue by terenzeyuen** [keystonejs/keystone#2207]
So, I have created a parent and two child that inherits from the parent.
```
Autokey, as default is set to use the title and unique.
autokey: { path: 'slug', from: 'title', unique: true }
```
Issue is when I create an item with title "Test" in child A, then when I try to create the same "Test" in child B, I am getting this error:
```
MongoError: E11000 duplicate key error index: dbname.lifestyles.$slug_1 dup key: { : "test" }]
```
Anything we have done wrong or because it's inheritance?

**Comment by morenoh149** [comment]
@terenzeyuen a parent and two child of what? are these 3 Lists? 2 Lists (1 of parent, 2 of child)? or one List?

the error will be coming from specifying `unique: true` for the index creation.

**Comment by terenzeyuen** [comment]
Hi @morenoh149,

So its a base class and two inheritances of 3 lists.

Okay let me try turning that off. 

Thanks

**Comment by webteckie** [comment]
Or you can specify multiple fields that make up the slug.

**Comment by terenzeyuen** [comment]
ok thanks.
