### ISSUE TITLE
Adding helpers in new files

### ISSUE THREAD

**Issue by claudiojulioferraz** [keystonejs/keystone#2209]
It seems that helpers only works in the `/template/views/helpers/index.js`. How to add helpers for new files? I'm using Handlebars.

_Using Google Translate_.

**Comment by mxstbr** [comment]
To add new helpers, add them to the `helpers/index.js` file to the `_helpers` variable!

**Comment by Miladinho** [comment]
Are helpers the only place we can include js functions that our template files need to control UI?
