### ISSUE TITLE
[0.x] A few suggestions for history implementation

### ISSUE THREAD

**Issue by r1b** [keystonejs/keystone#2212]
I am building a workflow system on top of keystone v0.3.x. I am using the revisions collection to collect changes made over some time range. I have two thoughts based on this experience:

- Consider keeping _id in "i" regardless of operation

I use the document id to collect all types of CRUD revisions. It is somewhat annoying to have to look both in the "i" field (where the id goes for a create/update operation) and the "d" field (it looks like _id sticks around there for a remove operation).

- Consider storing an empty object in "d" for a remove operation

The semantics of "d" for other operations appears to be "the state of the object after this operation was applied". It would be nice to have the same semantics for removals. If one wants to see what was removed, one can look at the state of the object on the previous operation.

Best,
Rob

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
