### ISSUE TITLE
S3Files with Format no Working on 

### ISSUE THREAD

**Issue by mariohmol** [keystonejs/keystone#2215]
Hi,

i'm using master branch of keystone (v0.4.0) with S3File.

I'm trying to use the format to show the image in Admin UI but nothing changes:

```
images: { type: Types.S3File,
			format: function(item, file) { return '<pre>' + JSON.stringify(file, false, 2) + '</pre>' +
					'<img src="' + file.url + '" style="max-width: 300px">'; }
		}

```

Did u tested this format with S3File it in this new version?

Thanks

**Comment by mariohmol** [comment]
I tested this solution, but value: event is not called as well

**Comment by mxstbr** [comment]
Closing in favor of #916, thanks for reporting this!
