### ISSUE TITLE
Display different Select options based on another field

### ISSUE THREAD

**Issue by ElliotChong** [keystonejs/keystone#2217]
Greetings,

From the docs it doesn't appear there is a way to change a Select's available options depending on another field. Is this currently possible in some undocumented way?

Thanks for Keystone! Cheers!

**Comment by morenoh149** [comment]
only select that changes it's contents currently is when you want to pick a related list item via a relationship http://keystonejs.com/docs/database/#relationships

**Comment by webteckie** [comment]
If you can get away with defining multiple select fields (each with its appropriate set of options) then you should be able to use the dependsOn field property on each of those fields to select the appropriate one.

**Comment by ElliotChong** [comment]
Thanks for the feedback! I'll leave this issue open in case there's a desire to officially support this use-case.

API proposal:
```
List.add({
  category: {
    type: Types.Select
    options: ['A', 'B', 'C']
  },
  subcategory: {
    type: Types.Select
    options: [
      {
        dependsOn: { 'category': ['A', 'B'] }
        value: 'foo'
        label: 'Foo'
      }, {
        dependsOn: { 'category': 'B' }
        value: 'bar'
        label: 'Bar'
      }
    ]
  }
})
```

Essentially, extend the current Array / Object format of declaring `options` with a `dependsOn` property.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by ElliotChong** [comment]
Hi @mxstbr! This was intended as a feature request, not just a support / question. Would you prefer it to be recreated, reopened, or dropped entirely? Thanks!

**Comment by mxstbr** [comment]
Oh sorry, I misread the issue! Can't clean out 400 issues without making a mistake, my bad!

Please submit the feature request on Product Pains: https://productpains.com/products/keystonejs
It makes prioritization so much easier for us maintainers :+1:
