### ISSUE TITLE
Default DateTime format inconsistent

### ISSUE THREAD

**Issue by jahbini** [keystonejs/keystone#2225]
The Database document for the DateTime (http://keystonejs.com/docs/database/#fieldtypes-datetime) states the default format is

format string - the default format pattern to use, defaults to Do MMM YYYY hh:mm:ss a

This indicates leading zeroes for hour, minute and seconds fields

However, the code at line 20 of https://github.com/keystonejs/keystone/blob/master/fields/types/datetime/DatetimeType.js
states:

```
this.formatString = (options.format === false) ? false : (options.format || 'YYYY-MM-DD h:m:s a');
```

This suppresses leading zeroes in the hour, minutes and seconds fields

**Comment by mxstbr** [comment]
That is a bug in the documentation, would love a PR fixing this!

**Comment by jahbini** [comment]
ISO 8601 prefers the hh:mm:ss format -- for maximum data interchange, maybe the documentation is correct for a change.

**Comment by erdivartanovich** [comment]
I want to handle this please

**Comment by Noviny** [comment]
@erdivartanovich Is that volunteering to make a pull request? :D

**Comment by Noviny** [comment]
[new website](http://keystonejs.netlify.com/api/field/datetime/) has corrected the documentation.
