### ISSUE TITLE
Add support for functional dependsOn?

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2227]
Something like...

```
{
    includes: {
        type: Types.Relationship,
        ref: 'pageinclude',
        many: true
    }
}, {
    heading: "Callout Content",
    dependsOn: {
        includes: function(include) {
            return include.type === 'callout';
        }
    }
}

```

**Comment by snowkeeper** [comment]
The `dependsOn` comparison engine should allow for a custom comparer function to be set, but the way we are passing the field definitions to the Admin UI does not allow for functions.

Can someone else verify that this is the case?

**Comment by mxstbr** [comment]
I think #2420 will cover this!
