### ISSUE TITLE
[0.4] Searching does not reset paging in list view

### ISSUE THREAD

**Issue by alobodig** [keystonejs/keystone#2229]
When searching a list, if the list was initially viewing a page, the UI tries to display that page of the search results. This causes the message "No __ found" when the result set actually does contain items. 

![video](http://g.recordit.co/Sbv8ucpOZA.gif)

**Comment by snowkeeper** [comment]
Looks like the internal page number needs to be reset to 1.

**Comment by mxstbr** [comment]
Fixed with #2415

**Comment by danielgormly** [comment]
I believe this is a problem again with 4.0.0!
