### ISSUE TITLE
"dependsOn" field prop in keystone 5

### ISSUE THREAD

**Issue by Davo1997** [keystonejs/keystone#2231]
Where is the "dependsOn" property of fields  in list???

**Comment by MadeByMike** [comment]
Closing this as a duplicate of #2260

There is no `dependsOn` in Keystone 5 and we're not yet sure how we should approach this in v5+

**Comment by acmoune** [comment]
Probably because your are considering PostgreSQL too, but it is alright.

**Comment by acmoune** [comment]
Probably because your are considering PostgreSQL too, but it is alright.
