### ISSUE TITLE
Dependency problems with history@2.0.0

### ISSUE THREAD

**Issue by ardiadrianadri** [keystonejs/keystone#2232]
Hello:

 When I try to install key stone with npm I get this error:

```
npm ERR! Linux 3.13.0-76-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@2.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ardi/Cursos/alt-arq/keystonejs-portal/npm-debug.log

```
It seems a dependency problem between history 2.0.0 and react-router 1.0.3

This is the command I run to install keystone:
`npm install keystone`

With the 0.3.15 I don't have any problems.

**Comment by JedWatson** [comment]
which version are you getting the error on? a 0.3.x version or git master?

**Comment by JedWatson** [comment]
I think I've fixed it by updating to react-router 2.0.0-rc6

Tests pass with that version, heads up @ericelliott - I can't see any issues with the server-side rendering functionality you added but just wanted to make you aware of the update.

**Comment by ardiadrianadri** [comment]
Sorry for the confusion. 
The issue is with the 0.4.0- alpha which, I guess, is the git master. The 0.3.16 works fine. I have both installed in two differents virtual machines. I think I've mixed the terminals in my head.

**Comment by ardiadrianadri** [comment]
I've tested the react-router 2.0.0-rc6 in the 0.4.0-apha of keystone and seems fine.

Thank you @JedWatson
