### ISSUE TITLE
[0.4] Keystone should use the Mongoose validate

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2233]
I think it would be cool if keystone can make use of a field's schema validate function that may be configured in the field.  The issue with letting mongoose process it is that input values are all cleared upon a fail validation as well as auto focus of an invalid field does not work.  For example:
```
    description: {
        type: Types.Html,
        validate: {
            validator: function(v) {
                    return (v && v.length > 0)
            },
            message: 'Please provide a description!'
        }
    },
```

keystone should check if a validate/validator is defined and make use of it so that it may address the issues above.

**Comment by webteckie** [comment]
The point about the input values being cleared is not really a mongoose validator thing.  That happens because the Admin UI redraws itself thus losing values.  That issue should be gone when the Admin UI becomes a SPA where views are not re-rendered but updated from asynchronous data.  So maybe this is currently all supported and a non-issue?  The only thing is validation will happen at 3 stages:  the client, the server during post/update handling, and then at mongoose during the actual save.  @JedWatson do you agree with this assessment?

**Comment by JedWatson** [comment]
I agree with the assessment.

The challenge with using Mongoose validation is that it's tied to a specific path, whereas Keystone fields validate as a set of fields, and relate to how the data from the input is interpreted before it is set on the item, including potentially data that is present but never passed to Mongoose (e.g. password matching)

So I like the idea of being able to provide custom validation, as above, but I think we'll keep it in Keystone so we have complete control over it.

**Comment by webteckie** [comment]
Ok, do you  see value in leaving this issue open to look into keystone swallowing the specified validator?

**Comment by creynders** [comment]
I see no value in having KS swallow the validator. I prefer seeing an explicit mongoose validator, since I know what it does. The less API surface for Keystone the better, since  it's yet another thing less to a) maintain, document etc b) learn when starting out with KS.
If it's not a facade or adapter it's not valuable IMO.

I.e. close this muthafucker! 😉 
Close all the issues! MUHAHAHAAA
Sorry, got a bit carried away.

**Comment by mxstbr** [comment]
BOOM

**Comment by gemscng** [comment]
@creynders @mxstbr @JedWatson   So how can we create custom validation now?  If pass Error in pre save now will treated as Database Error.

**Comment by suavelizard** [comment]
Is there ANY way to show a custom error message with the mongoose validator?
