### ISSUE TITLE
Add FAQ for windows users failed install

### ISSUE THREAD

**Issue by AllanFerencz** [keystonejs/keystone#2239]
# Feature request

## Is your feature request related to a problem? Please describe.

I've been struggling to finish the Getting Started with Keystone. I'm on Windows and after looking into Github issues I see it's known that Windows users have issues. 

When running "yarn create keystone-app my-app" it completes with no issues but when you run "yarn dev" You are hit with a cannot find module "\node_modules\@keystonejs\keystone\bin\cli.js"

When running "yarn" in the project it fails on "Bcrypt".

Windows users need to have "Windows build tools" installed to install Bcrypt.

This is mentioned in a GitHub issue comment here [#2053](https://github.com/keystonejs/keystone/pull/2053#issuecomment-565635121). 

Once done "yarn" worked and Keystone started up.

## Describe the solution you'd like

I'm not sure the best place to put this, but Windows users should see they need to install this to run Keystone. This should be right in the getting started documentation as a gotcha instead of researching on Github.

I'm sure some Windows users don't research why it fails and stop trying to install it.

**Comment by timleslie** [comment]
We have replaced the use of `bcrypt` with `bcryptjs`, so windows users no longer need to have the build tools installed.
