### ISSUE TITLE
[0.4] Item form does not recall field values upon failed validation

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2239]
After filling up a bunch of fields in the item form screen you press `Save` and if there is a validation error in any of the fields then none of the input values are restored.  This is very annoying since some of the values could be long text.  Perhaps save the field's input values as state in some item store?

UPDATE:  I think this hinges on the Admin UI becoming a SPA.  Will leave open so that we can ensure that after the Admin UI becomes a SPA that this issue is verified fixed.

**Comment by AlexYegupov** [comment]
+1 
reproduced on 0.3.16 with Email field

**Comment by mxstbr** [comment]
Fixed in #2566!
