### ISSUE TITLE
Add support for a calendar field

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2240]
Perhaps using something like https://github.com/Hanse/react-calendar  I'm a fan of clndr.js

**Comment by israelroldan** [comment]
There is already a date field, what would the use of this field be? Defining a date range?

**Comment by webteckie** [comment]
@israelroldan to display calendar events, custom coloring, etc.  A date/datetime field is like a GeoPoint field for maps.  I would also like to see the map with the GeoPoint marker :-)  Same idea with the calendar.  This may eventually be more useful for front end display but being able to see it in the admin ui as well helps.  Suppose you are writing some sort of bookings app.  I would like to visually see in the Admin UI all existing bookings by simply navigating the full fletch calendar.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/calendar-field!
