### ISSUE TITLE
Why is there no documentation at all for CloudinaryImage field type?

### ISSUE THREAD

**Issue by Roeefl** [keystonejs/keystone#2241]
Hello,

This is not a complaint, I'm just kind of puzzled by it... how come there is no documentation at all for how to upload, or at least get (in queries) images from cloudinary?

at:
https://www.keystonejs.com/keystonejs/fields/src/types/cloudinary-image/

It's weird to be doing guesswork for something like this.

If this is missing and wanted, I'd be happy to contribute.

Thank you

**Comment by wesbos** [comment]
Here are some details on how to use it:

https://github.com/wesbos/advanced-react-rerecord/issues/4

and here is me setting it up on my client: https://github.com/wesbos/advanced-react-rerecord/blob/master/frontend/lib/withData.js#L6

and me using it:

https://github.com/wesbos/advanced-react-rerecord/blob/master/frontend/components/CreateItem.js#L60-L69

**Comment by MadeByMike** [comment]
Official docs can be found here: https://www.keystonejs.com/keystonejs/fields/src/types/cloudinary-image/#cloudinaryimage (although Wes is at least semi official)
