### ISSUE TITLE
Decimal fields resets

### ISSUE THREAD

**Issue by bsides** [keystonejs/keystone#2242]
# Bug report

## Describe the bug

In a list, I have 2 decimal fields. In Admin UI, updating one of those decimal fields makes them reset (both or one of them only). Sometimes it deletes both data, sometimes just one of them.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Create a new project `yarn create keystone-app bug-example`, when the wizard asks, name it `bug-example`, `blank` template and `mongoose` for database connection
2. Create 2 lists like the ones below (Person and Bill)
3. Create a new Bill with a Name, Price and Installment Price in decimal (with dot, like 1234.00 and 123.00). Try to make it in one go.
4. After creating hit Save and you'll notice the fields being resetted.
5. If you try to put the values there again it will keep resetting.

The code. Paste below `new Keystone`...

```javascript

const PersonSchema = {
  fields: {
    name: { type: Text, isRequired: true },
    shortName: { type: Text },
    cpf: { type: Text },
    email: { type: Text, isUnique: true, isRequired: true },
    telephone: { type: Text },
    billList: { type: Relationship, ref: 'Bill.person' }
  }
}

const BillSchema = {
  fields: {
    name: { type: Text, isRequired: true },
    description: { type: Text },
    price: { type: Decimal, isRequired: true },
    dueDate: { type: DateTime },
    barCode: { type: Text },
    installments: { type: Integer },
    installmentsPaid: { type: Integer },
    installmentsPrice: { type: Decimal },
    isPaid: { type: Checkbox },
    person: { type: Relationship, ref: 'Person.billList', many: true }
  }
}

keystone.createList('Person', PersonSchema)
keystone.createList('Bill', BillSchema)
```

## Expected behaviour

The values should stay put. In GraphQL and directly manipulating in the database works correctly.

## Screenshots

![WZ9iYfbuI3](https://user-images.githubusercontent.com/87631/72426768-1c0e1480-3769-11ea-923c-b3e225f16030.gif)

## System information

- OS: Windows 10 
- Browser (if applies): Firefox or Chrome
- Mongoose for Windows

**Comment by Vultraz** [comment]
Fixed by #2537, can be closed.
