### ISSUE TITLE
Underscore error on LocalFilesField.js

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#2243]
I use `Types.LocalFiles` and when I select file in admin area there is an error:
`Uncaught TypeError: _underscore2.default.contains is not a function`
This is an Underscore error.
Actually `_.contains` has an alias `_.includes` and is work.
Should I try to implement this function without `underscore`? Or I can use `lodash`? Or simply change `_.contains` with `_.includes`?

**Comment by jacargentina** [comment]
Same error here: but in demo.keystonejs.com everything works fine.
I've seen that on my localsetup i get `underscore.VERSION = "4.5.1"` while on demo.keystonejs.com i get `underscore.VERSION = "1.5.1"`

Any ideas?
May be there is some problem with my gulp build-packages setup...

**Comment by jacargentina** [comment]
The `react-color` dependency has lodash: 4.3.0 as a dependency.

Somehow, i think this is related to this problem, need help from somebody with more knowledge here, browserify, react, babel etc.

**Comment by jacargentina** [comment]
I think i've got it; there is just one place i could find where:

````javascript
var _ = require('lodash');
````

It's on `cloudinary` module. I think this breaks everything as it defines the global _

@JedWatson Which would be the right fix... upstream bug on cloudinary may be ?

**Comment by jacargentina** [comment]
Found it: `lodash@4.5.`1 is overwriting `window._` (which points to `underscore@1.51`)

https://github.com/lodash/lodash/issues/1852

This is caused in this pseudo  stack:

````javascript
var ColorPicker = require('./components/Color');

... which then loads...

var _Swatches = require('./swatches/Swatches');

... which then loads...

var _reactMaterialDesign = require('../../../modules/react-material-design');

... which then loads...

var _libComponentsTabs = require('./lib/components/Tabs');

... which then loads...

var _lodash = require('lodash');

... which  runs this code

  (freeWindow || freeSelf || {})._ = _;

````
before that code, `window._.VERSION == 1.5.1`
after it is `window._.VERSION == 4.5.1`
