### ISSUE TITLE
Middleware returns HTML errors on JSON requests

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#2247]
The standard middleware methods incorrectly return HTML errors (or perform a `302` redirect to an HTML page) even when the `accept` header is `"application/json"`

This makes working with the built-in middleware and API much harder than it needs to be; all the middleware methods should check for `req.headers.accept === 'application/json'` and bail out with JSON accordingly.

Related: #663

**Comment by mxstbr** [comment]
Is this fixed @JedWatson?

**Comment by autoboxer** [comment]
@JedWatson, do you know if this has been fixed?

**Comment by JedWatson** [comment]
Yep, was closed in ee666e19e8393de4e6cfff9e05a3532ea1809ad0
