### ISSUE TITLE
forceSSL middleware addition

### ISSUE THREAD

**Issue by snowkeeper** [keystonejs/keystone#225]
I added a small block of code to use to force to the secure server for pages:
app.all('/:mode(signin|join|attend)', keystone.forceSSL);

Have a look and let me know what you think.    What about a reverse function to leave https for http and should there should be a way to redirect back to http after login instead of staying on https?

code to add to jndex.js:
```javascript
Keystone.prototype.forceSSL = function(req,res,next) {
	//this should work for local development as well
	var sslHost = keystone.get('ssl host') || keystone.get('host') || process.env.SSL_HOST || process.env.HOST || process.env.IP,
		sslPort = keystone.get('ssl port') || 3001;
	if(!sslHost) {
		var gethost=req.get('host').replace('http://','').split(':');
		sslHost=gethost[0];
	}
	//fix port for external webserver use
	if(sslPort)sslPort=':'+sslPort;
	if (!req.secure) {
        return res.redirect('https://' + sslHost + sslPort + req.url);
    }
	next();
}
```

**Comment by sebmck** [comment]
Probably not necessary to include Keystone core when you can just drop in some [middleware](https://github.com/battlejj/express-force-ssl). Keystone is moving towards a more modular core so including something like this by default would add bloat.
