### ISSUE TITLE
{field}_in where filter

### ISSUE THREAD

**Issue by ricardonogues** [keystonejs/keystone#2257]
# Bug report

## Describe the bug

When I try to use the {field}_id where filter I keep getting:
$in requires an array as a second argument, found: objectId

In GraphQL playground

## To Reproduce

1. Create a List with a field of type Relationship with many: true
2. In GraphQl playground try to do a query to a field of the Relationship list using _every and _in

```javascript
query {
  allBooksAttributes(
    where: {
      attribute_every: { name_in: ["Fiction", "Sci-Fi"] }
    }
  ) {id}
}
```
## Expected behaviour

The {field}_in clause should work with an array of string and not error

**Comment by MadeByMike** [comment]
Hi @ricardonogues 

This worked for me with the following schema:

```js
keystone.createList("Book", {
  fields: {
    attribute: {
      type: Relationship,
      many: true,
      ref: "Attribute",
      isRequired: true
    }
  }
});

keystone.createList("Attribute", {
  fields: {
    name: {
      type: Text
    }
  }
});
```

![image](https://user-images.githubusercontent.com/1320567/73799841-32107180-480b-11ea-8cd2-8a35e256d65d.png)


Perhaps you can share more about your list configurations?

**Comment by ricardonogues** [comment]
hey @MadeByMike,

I have these two lists:

`keystone.createList("PersonaImageAttribute",{
    fields: {
        personaImage: { type: Relationship, ref:'PersonaImage' },
	attribute: { type: Relationship, ref:'Attribute', many:true },
    }
})`

`keystone.createList("Attribute",{
    fields: {
        name: { type: Text, isRequired: true },
    }
})`

and this query

`query {
  allPersonaImageAttributes(
    where: {
      attribute_every: {name_in: ["Fiction"]}
    }
  ) {id}
}`

returns this

The argument to $size must be an array, but was of type: objectId

**Comment by timleslie** [comment]
I believe this issue has now been fixed. I attempted to reproduce your issue with the same list config and queries and everything appears to be working fine.

If you are able to reproduce this with the latest packages please re-open this issue.

<img width="1299" alt="Screen Shot 2020-04-09 at 2 50 03 pm" src="https://user-images.githubusercontent.com/616382/78859070-9c46cc00-7a71-11ea-9260-6d02588cca2a.png">
