### ISSUE TITLE
Creating Custom Field Types

### ISSUE THREAD

**Issue by Alexcraftish** [keystonejs/keystone#2259]
Hey I really love what you are doing with keystone!

But i just wondered, how can I create my own custom field types?
The documentation here: https://www.keystonejs.com/guides/custom-field-types doesn't really help.

Thanks!

**Comment by wbarcovsky** [comment]
You can use some implementations of the fields in the project as an example.
I think [@keystonejs/fields-wysiwyg-tinymce](https://github.com/keystonejs/keystone/blob/master/packages/fields-wysiwyg-tinymce/package.json) might be a good one, if you want to store your data in DB (and revice in from API) as text and not borther with graphQL settings

You can also take a look at the [Select](https://github.com/keystonejs/keystone/tree/master/packages/fields/src/types/Select) - this one is more advanced

**Comment by MadeByMike** [comment]
I wrote a guide for creating custom field types: https://www.keystonejs.com/guides/custom-field-types

There is also a demo project in the keystone repo: https://github.com/keystonejs/keystone/tree/master/demo-projects/custom-fields/
