### ISSUE TITLE
Document field types and how they work

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#226]
- [x] How-to create a new field type (and why you probably shouldn't)
 - [x] What do all the methods do (API docs) (#740)
 - [x] How does the UI relate to the backend field types?

**Comment by molomby** [comment]
Building on [earlier thoughts](https://github.com/keystonejs/keystone-5/issues/226#issuecomment-414189625), fields should also detail how they are rendered and interact with the Admin UI.

**Comment by ashinzekene** [comment]
Also, it would be beneficial to show how to import field types. For example, I had to check the codebase before I could import the `Markdown` field

**Comment by molomby** [comment]
Bump. #2241

**Comment by MadeByMike** [comment]
I think we've resolved most of these. We have Guides for custom fields. API docs for all field types and between that a much better description of how the UI relates to backend field types.

Still more to do but I think this issue has served purpose.
