### ISSUE TITLE
Full Cloudinary API support

### ISSUE THREAD

**Issue by jaydson** [keystonejs/keystone#2260]
I was looking for a way to use [JPEGmini](http://cloudinary.com/documentation/jpegmini_image_compression_addon) feature on my images, but it seems Keystone didn't have a way to pass more options to Cloudinary.

Please correct me if I wrong.

If I'm right, I'd like to work on that feature, but I need some guidance.

**Comment by nadavofi** [comment]
Applying addons on-the-fly via URL requires the URL to be [signed](https://support.cloudinary.com/hc/en-us/articles/206649029-Why-am-I-getting-401-Unauthorized-when-trying-to-manipulate-an-image-using-add-ons-).
The signature must be generated on the server-side as it is based on the API_SECRET which should not be revealed on the client-side.
For instance, this is how we generate the signature and build the URL within the PHP libraries:
https://github.com/cloudinary/cloudinary_php/blob/master/src/Cloudinary.php#L470

**Comment by mxstbr** [comment]
Since @nadavofi answered the question it appears, I'll close this issue—feel free to comment again if you feel like that's not the case!
