### ISSUE TITLE
S3 File Adapter only works after creating object first

### ISSUE THREAD

**Issue by Mylab6** [keystonejs/keystone#2266]
# Bug report

##  To save files using the S3 file adapter I need to first create the object. 
The expected behvaoir would allow me to create the object with the uploaded file. 

For example if you have an object called book reports, create the book report object and then edit the object. When editing the object, save a file, then the file will be saved to S3. 
But if you try to create the object with the uploaded file , it doesn't work . 

Here's my file adapter code. 

const fileAdapter = new S3Adapter({
  accessKeyId: s3Auth.S3Id,  //'ACCESS_KEY_ID',
  secretAccessKey: s3Auth.S3AccessKey,  //'SECRET_ACCESS_KEY',
  region: 'us-east-1',
  bucket: bucketName,
  folder: S3_PATH,
  //publicUrl: ({ id, filename, _meta }) =>   `https://${s3Auth.CloudFrontID}.cloudfront.net/${filename}`,
  s3Options: {
    apiVersion: '2006-03-01',
  },
})

In the UI this error message appears 
NestedError
Nested errors occured

In the console,. this error appears 

Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Object.onCreate (index.js:100)
    at CreateItemModal.js:74

**Comment by LiamAttClarke** [comment]
@Mylab6 I was not able to reproduce this issue. Could you share the value of `S3_PATH`?

**Comment by Mylab6** [comment]
const S3_PATH = '/uploads';

I actually moved to Strapi since it fits my needs better, thank you for your time .

**Comment by seedwalk** [comment]
I am experiencing the same issue @Mylab6.

I abandoned strappi as it content manager is not as good as keystone

**Comment by seedwalk** [comment]
@Mylab6 figured it out, keystone id needs to be a string

**Comment by kochomati** [comment]
Like this:
`uploadParams: ({ filename, id, mimetype, encoding }) => ({
      Metadata: {
        keystone_id: String(id),
      },
    }),`
