### ISSUE TITLE
keystone start configuration for Mongo session management

### ISSUE THREAD

**Issue by kevinian** [keystonejs/keystone#227]
Hello,

I wanna use the session store in keystone. But when I checked the source code of keystone, I found the following

```javascript
app.use(express.session());
app.use(require('connect-flash')());

if (this.get('session') === true) {
	app.use(this.session.persist);
} else if ('function' == typeof this.get('session')) {
	app.use(this.get('session'));
}
```
if I define the session option in the keystone.init as following
```javascript
'session': express.session({
    secret: settings.cookie_secret,
    store: new MongoStore({
        db: settings.db
    })
}),
```

This means the express app have used the express.session for two times, will the app still work as normal? I have really no idea.

Best regards,
Kevin

**Comment by creynders** [comment]
Configurable through "session store" and "session store options"
