### ISSUE TITLE
bug: defaultSort doesn't work

### ISSUE THREAD

**Issue by madhums** [keystonejs/keystone#2274]
# Bug report

## Describe the bug

In the `adminConfig` property of `keystone.createList`, I am specifying defaultSort to be `createdAt` but it doesn't sort the results in the admin UI.

## To Reproduce

```js
keystone.createList('Observation', {
  // ... fields
  plugins: [atTracking({ format: 'DD/MM/YYYY h:mm A' }), byTracking()],
  adminConfig: {
    defaultColumns: 'name, completed, assignee, createdAt',
    defaultSort: 'createdAt'
  }
});
```

Here's the [repo](https://github.com/rodekruis/dc510-backend/blob/master/schema.js#L201-L204) with full code in case you need it.

## Expected behaviour

The listing in the admin should be sorted by `createdAt` date.

## Screenshots

<img width="825" alt="Screenshot 2020-01-22 at 17 35 03" src="https://user-images.githubusercontent.com/123815/72913542-93c9d980-3d3d-11ea-9b95-71d2b93b2195.png">

## System information

- OS: Linux
- Browser: Brave

## Additional context

I first thought, may be it doesn't work on a date field so tried on an integer field, it looks like that doesn't work as well.

**Comment by cowjen01** [comment]
@madhums I think I found out why this is happening. Look at this [line](https://github.com/keystonejs/keystone/blob/master/packages/app-admin-ui/client/pages/List/url-state.js#L15). There is a difference between:

```js
const val = {foo: "abz"} || "str" ? {foo: "foo"} : null;
```
and..
```js
const val = {foo: "abz"} || ("str" ? {foo: "foo"} : null);
```

**Comment by cowjen01** [comment]
@MadeByMike this is easy to fix
