### ISSUE TITLE
Live editor

### ISSUE THREAD

**Issue by kmiddlesworth** [keystonejs/keystone#2274]
![keystone-with-page-editor](https://cloud.githubusercontent.com/assets/7379536/13014441/6d6865d8-d179-11e5-8618-74a39d9e6000.gif)

This is a prototype using Keystone's responsive layout in an iframe to accompany a drag and drop page editor. There is no altering of Keystone's functionality. Rather, it rests as a module sitting alongside Keystone's Admin UI and REST data from Keystone.

I wanted to post this to get some discussion going about different ways to use Keystone.

**Comment by webteckie** [comment]
That looks pretty cool!  I like the idea!  Are you using a particular client side framework for the front end?

**Comment by kmiddlesworth** [comment]
This was a quick and dirty prototype, so at this point, there's no framework being used. I think it would be a perfect candidate for React, though.

**Comment by VinayaSathyanarayana** [comment]
Is there a PR for this?

**Comment by mxstbr** [comment]
This is definitely awesome and something I could see us having/supporting – lets put it on the feature wishlist: #1897

**Comment by mxstbr** [comment]
Reopening for visibility

**Comment by Noviny** [comment]
Closing as an old topic, keeping the issue tracker clear. This is a really neat thing to do though.
