### ISSUE TITLE
Use lodash instead of underscore?

### ISSUE THREAD

**Issue by andyhu** [keystonejs/keystone#2287]
I've seen a lot of benchmarks that shows underscore is slower than lodash. Can we use lodash instead?

**Comment by JedWatson** [comment]
Yes. It's just a matter of switching over and making sure there are no regressions due to the minor differences between the two libraries.

**Comment by JedWatson** [comment]
@jacargentina that would be brilliant, thanks!

**Comment by jacargentina** [comment]
@JedWatson 
Mmmm, it was very easy and fast. I've run the tests, and tested the UI on chrome.
Everything its just fine?

**Comment by morenoh149** [comment]
that's why tests are awesome :+1:

**Comment by jacargentina** [comment]
@JedWatson Mmmm it seems the test are missing some .... tests!

I've checked by going back previous the merge with my code.

It seems there is some code involved on the save logic which is related to underscore, and its working different with lodash. SImply try creating any object, and saving it: i thinkg the title of a blog post iv'e created was "duplicated", i mean: Title = "Test", after saving, Title = "Test, Test"

**Comment by jacargentina** [comment]
@jedwatson the path changes where about my setup with node 5.7.0... Which has regressions on the path module. Sorry about that

Also, could'nt run ALL tests... Seleniun somehow breaks on my setup... So... Sorry. Next time i'll be more cautious
