### ISSUE TITLE
Re-sort items in Admin UI List by dragging and dropping

### ISSUE THREAD

**Issue by thomasjonas** [keystonejs/keystone#2289]
## Feature request

Provide the ability to re-sort items in the admin UI by dragging and dropping them.

Sometimes I want to be able to re-sort/re-order list items directly in the list view. It would be easier to just to drag-and-drop items in the right order then to edit each item separately.  It seems this functionality was available in Keystone v4, but is missing from v5. So I would imagine it could work very similar to how the v4 version worked, but maybe it should be rewritten as a plugin?

I could not find any hints in the code that would indicate it's already there, and also no issues indicating this has been addressed earlier or it's being worked on. But I could very well be wrong or missed something. I hope this is a feature that will be considered for the future.

**Comment by timleslie** [comment]
Hi @thomasjonas, this is a feature which we don't currently have in Keystone 5, but we are planning on introducing in the future. At the moment lists have a natural ordering which happens to be an artefact of how they are stored and retrieved from the database. The new feature will most likely be called `OrderedList` and we'll explicitly control and enforce the order in the database and provide mutations which allow the user to manipulate this order.

**Comment by thomasjonas** [comment]
Thanks for your answer and your work on Keystone. Looking forward to feature releases!

**Comment by joephuz** [comment]
+1 for this, the lack of this feature has kept me stuck in v4 as this feature is almost always required by my clients. I hope this can be implemented soon and thanks for everyones hard work on this project!

**Comment by joshlasdin** [comment]
While not a perfect replacement, we made this list plugin as a stop-gap measure: https://www.npmjs.com/package/@globobeet/keystone-sortable-list-plugin

It adds a numeric field that automatically shifts surrounding documents when needed. It may help!

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
