### ISSUE TITLE
can not debug

### ISSUE THREAD

**Issue by 1767083130** [keystonejs/keystone#2294]
In vscode,I can debug when start the web,but when I add code  'debugger' in routes/view/index.js,I can not access ‘http://localhost:3000’.
the other projects is not so.

**Comment by morenoh149** [comment]
? if place a `debugger` statement in javascript the program will stop executing at that breakpoint. It shouldn't be surprising the server returns no response if it's stopped at a breakpoint. Also this isn't an issue please ask questions in the [gitter](https://gitter.im/keystonejs/keystone)

**Comment by 1767083130** [comment]
@morenoh149  It didn't stop executing at that breakpoint.
who can help me?
