### ISSUE TITLE
KnexAdapter error when launching KeystoneJS application

### ISSUE THREAD

**Issue by singhArmani** [keystonejs/keystone#2297]
# Bug report
Keystone app fails to start up when setting up a self-referential many relationship with KnexAdapter

## Describe the bug
The Keystone app was failing to start up when you create a list having a `1-to-many` **self referential** relationship with **KnexAdapter**. The error was happening while trying to connect to database. Removing the `many` relationship allows the app to run as expected though. 

Nonetheless, aforementioned error doesn't occur while using **MongooseAdapter**. 
## To Reproduce

1. Tweak the **todo** demo example to have the following configuration: 
```js
// using KnexAdapter
const keystone = new Keystone({
  name: 'Keystone To-Do List',
  adapter: new KnexAdapter({dropDatabase: true})
});

keystone.createList('Category', {
  labelField: 'title',
  schemaDoc: 'Categories',
  fields: {
    title: {
      type: Text,
      required: true,
    },
    meta: {
      type: Text,
      required: true,
      schemaDoc: 'Meta data',
    },
    subCategories: {
      type: Relationship,
      ref: 'Category',
      many: true,
      schemaDoc: 'Categories under this category',
    },
  },
});
```
2. Running `yarn dev` throws the following error:
```
Error: create table "public"."Category_subCategories" ("Category_id" integer not null, "Category_id" integer not null) - column "Category_id" specified more than once
 ...
  errors: {
    KnexAdapter: error: column "Category_id" specified more than once
   ...
  }
```

## Expected behaviour

The app should be able to run without any errors. Ideally, the KnexAdapter should pass different column name while trying to create tables with the many self-referential relationship. PostgreSQL won't like it if column name are identical. 

## Screenshots

![image](https://user-images.githubusercontent.com/11068601/73329760-e9106880-42b2-11ea-935b-e16ce0d114e6.png)

## System information

- OS: macOS
- Browser: Chrome

## Additional context

This issue was discovered while trying to reproduce the #1816.

**Comment by timleslie** [comment]
This has been fixed as of the [`Arcade`](https://www.keystonejs.com/discussions/new-data-schema) release.
