### ISSUE TITLE
Help Required(ACL integration with Keystone)

### ISSUE THREAD

**Issue by kcnkumar** [keystonejs/keystone#2298]
Hi,

Can some one help me on integration of [acl](https://www.npmjs.com/package/acl) with Keystone [Demo site](http://demo.keystonejs.com/),
here I am using MONGODB as back-end 

Thanks in advance
Nishanth

**Comment by morenoh149** [comment]
where are you stuck? what did you try?

**Comment by kcnkumar** [comment]
Hi @morenoh149  thanks for reply

> i am doing one custom portal something same as  Keystone [Demo site](http://demo.keystonejs.com/), and my task is to create 5 roles based on role i have to load menu and respective data.

i added following code in routes/index.js
`var mongoose = require('mongoose');
var redis = require("redis"),
    client = redis.createClient(27017, '127.0.0.1', {no_ready_check: true});
var acl = require('acl');
var dbc = mongoose.createConnection('mongodb://127.0.0.1:27017/mydb', {});
//console.log(dbc)
acl = new acl(new acl.mongodbBackend(dbc.db.databaseName, 'acl_'));`

and in exports


`exports = module.exports = function(app) {
	
	// Views
	app.get('/', routes.views.index);
	app.all('/contact', routes.views.contact);
	console.log(acl)
	
		 acl.allow('guest', 'blogs', ['edit','view', 'delete'])

	acl.isAllowed('guest', 'blogs', 'view', function(err, res){
    if(res){
        console.log("User guest`` is allowed access blogs");
    }
	else{console.log(err);}
});
};`

this is my try(i don't know exactly from where i start) and stuck with errors.

Regards
Nishanth 
Skype ID: nishanthrajsh

**Comment by mxstbr** [comment]
We sadly don't have the time to do support for every single use case. If somebody has done this before and wants help out here that'd be appreciated, but this isn't an issue with keystone itself so I'll close it for now!
