### ISSUE TITLE
Suport relationships as List columns

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#23]
Columns on the List screen can currently display fields (including relationship fields).

Relationships should be able to be displayed too.

**Comment by tivac** [comment]
@morenoh149 or @JedWatson This is fixed.

**Comment by martinduparc** [comment]
@JedWatson Any chance you could point me to the right place? I can work on the issue.

**Comment by morenoh149** [comment]
@martinduparc I think you need to add an extra member to `rel` https://github.com/keystonejs/keystone/blob/64f3831374781e1b3cc08ecca6eb962327f4e05a/templates/views/item.jade#L34

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/suport-relationships-as-list-columns
