### ISSUE TITLE
Establish a pattern for handling environment and config options

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#230]
We currently have a proto-version of this in `packages/server/WebServer/initConfig.js`, but a more mature system will be required as we move forward.

**Comment by dcousens** [comment]
Seeing things like https://github.com/keystonejs/keystone-5/blob/51e7330abe22d1f3cf2d5babedcb0ce37b54b564/packages/admin-ui/server/env.js#L1-L4 show this hasn't progressed very far.
I think we shouldn't be seeing `process.env` variables anywhere near this level,  at least not in way that cannot be overwritten by a configuration object.

**Comment by MadeByMike** [comment]
I've started the process of moving environmental variable out as far as possible or at-least ensuring they can be overwritten with config.

@timleslie has published a PR that allows you to manually override express options in the default server that should help with some config.

Once we hoist out some of the other env config stuff we should close this.
