### ISSUE TITLE
Upload local image to cloudinary field

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#2300]
Hi,

My project need to upload images in batch (user upload it via ftp). My model is using clouindary image field.

Therefore, I tried to use the updater to update the image file.

I am able to get the file paths in the server:

```
fs.readdir(path, function(err, data){
    if (err) throw err;
    files =  data;
    for(var i=0;i<1; i++){
      uploadIt(path + files[i], function(err, img){
        console.log(img);

      });

    }
    callback(null, files);
  });
```

however, I found there is no field accessor for my image path. How to tackle it?

e.g. ```this.image.local_path = myfile```?

Or I tried to do the cloudinary uploader myself, but cloudindary cannot be required

```require('cloudinary')``` failed

How to **upload cloudinary image already exist in the server**?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
