### ISSUE TITLE
Admin UI makes duplicate API requests

### ISSUE THREAD

**Issue by mikehazell** [keystonejs/keystone#2302]
# Bug report

## Describe the bug

The Admin UI makes at least 2 requests to the API when showing a list page.

In the worst case, this becomes a repeating request if the list is sorted by a field which will not return a consistent sort order.

## To Reproduce

This can be reproduced in a standard starter app "Starter (Users + Authentication)" created with `yarn create keystone-app`

1. Create and start the app

<img width="580" alt="Screen Shot 2020-01-30 at 10 59 14 am" src="https://user-images.githubusercontent.com/814227/73408412-460e2c00-4350-11ea-89d3-21b2b3ab93a3.png">

2. Sign in to the new app
3. Open the browsers Network panel 
4. Navigate to `http://localhost:3000/admin/users`
5. In the network panel you will see 2 identical api requests

![Screen Shot 2020-01-30 at 11 01 51 am](https://user-images.githubusercontent.com/814227/73408547-ae5d0d80-4350-11ea-83ee-a9fdd7f02168.png)

![Screen Shot 2020-01-30 at 11 02 10 am](https://user-images.githubusercontent.com/814227/73408549-ae5d0d80-4350-11ea-82b4-b2c812332655.png)

## Expected behaviour

Expected only one api request.

## System information

- OS: Mac
- Node v12.6.0
- Browser: reproduced on Chrome, Firefox and Safari for Mac
- Package Versions:
```
    "@keystonejs/adapter-mongoose": "^5.1.3",
    "@keystonejs/app-admin-ui": "^5.3.0",
    "@keystonejs/app-graphql": "^5.0.1",
    "@keystonejs/auth-password": "^5.0.1",
    "@keystonejs/fields": "^6.0.0",
    "@keystonejs/keystone": "^5.3.0",
```

## Additional context

The more problematic case is harder to reproduce ... but if the list is sorted by a field which will not give a consistent sort order, the request will repeat indefinitely. This appears to only occur for requests which take more than 1 or 2 seconds to resolve.

In my use case, we have a table with ~166000 items (using Postgres). One of the fields is a text field. When I set a `contains` filter for that field and have the sort order set to a Relationship field we see infinite api requests about 1 second apart. ie. as each request completes, a new one begins.

**Comment by Vultraz** [comment]
I was trying to look into this. I could indeed repro. It seems the AdminUI is making a *lot* of queries O_O
![image](https://user-images.githubusercontent.com/3558659/75607282-89bfa580-5b49-11ea-8b6f-e5fc86104037.png)

At least 4 of which are network ops...
![image](https://user-images.githubusercontent.com/3558659/75607310-d5724f00-5b49-11ea-91dc-b846f6a08c57.png)
![image](https://user-images.githubusercontent.com/3558659/75607317-e15e1100-5b49-11ea-8159-4354fcfaf5f6.png)
![image](https://user-images.githubusercontent.com/3558659/75607319-e9b64c00-5b49-11ea-8f3f-5dffbd7e7c6c.png)
