### ISSUE TITLE
UpdateHandler.process called with invalid field path:

### ISSUE THREAD

**Issue by justinwen** [keystonejs/keystone#2307]
There is a issue   in the updateHandler.js

Here is my code 

```JS
req.user.getUpdateHandler(req).process(req.body, {
  fields: 'name, email, notifications.meetups, notifications.posts, website, isPublic, bio, photo,',
  flashErrors: true
}, function(err) {
```		

Here is the print out 

```
Processing field name
Processing field email
Processing field notifications.meetups
Processing field notifications.posts
Processing field website
Processing field isPublic
Processing field bio
Processing field photo
Processing field 
```

The exception is

```
Error: UpdateHandler.process called with invalid field path: 
    at UpdateHandler.<anonymous> (.../node_modules/keystone/lib/updateHandler.js:213:10)
    at .../node_modules/keystone/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (.../node_modules/keystone/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (.../node_modules/keystone/node_modules/async/lib/async.js:209:22)
```
I notice the last field is always empty , Not sure what is the root cause to the empty string.  Ant this emtpy string always cause my update process to fail.  My string pass in shall not contain any empty space. I didn't put too much time to dig deeper . I hope you can help me out.  

I add a small  patch to fix  this  issue 
Added following code into updateHandler.process. 
```
              if(path===""){
                      return callback();
		}
````

Thanks

**Comment by morenoh149** [comment]
please use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks)

**Comment by mxstbr** [comment]
The problem is that in your `fields` options you have a trailing comma:

`, photo,'`

Since we use `.split(',')` on that to create an array, we get an empty array element which makes it fail. (see [here](http://jsbin.com/gazuqopoxa/1/edit?js,console) for a replication)

Removing the trailing comma should fix your issue!
