### ISSUE TITLE
Add query helper to the virtual field resolver

### ISSUE THREAD

**Issue by cowjen01** [keystonejs/keystone#2316]
# Feature request

## Is your feature request related to a problem? Please describe.

As it has been discussed here  #2298 to save computation resources the virtual's field resolver should not to provide related objects for relationship fields. To achieve this we should make a graph QL query to fetch the data by our selves. To make this easy, resolver method should provide an access to `Query Helper` to easily get data from current context.

## Describe the solution you'd like

Provide `actions` object as the argument of resolver method in the same way as the [hooks](https://www.keystonejs.com/api/hooks#hook-sets) have got.

> Contains a query functions that queries the list within the current operations context, see Query Helper

**Comment by MadeByMike** [comment]
@cowjen01 Do you think you could "spec" this out a little more? How would you expect the API for this to work?

Remember that in the virtual field resolver you can do a fetch, then resolve the ids manually. I'd be interested to know how any addition to the API would make this process easier or clearer before we commit to it. 

Let's write some examples first.

**Comment by MadeByMike** [comment]
Here is an example that would manually fetch relationships on an item:

```
fields: {
  stats: {
    type: Virtual,
    resolver: (item) => {
      return keystone.executeQuery(`query {
        User(where: { id: ${item.id} }) {
          id
          answers {
            id
          }
        }
      }`);
    },
  },
  answers: {
    type: Relationship,
    many: true,
    ref: 'PollAnswer',
  },
}
```

**Comment by cowjen01** [comment]
IMHO I'm kind of confused when should I use `keystone.executeQuery` method and when to execute a query using `actions: { query }` method available in a hook callback. For example I have got all models placed into separate files and import them from entry file like this:

```js
keystone.createList('User', models.user);
keystone.createList('Stream', models.stream);
keystone.createList('Poll', models.createPollModel(keystone));
```

Look at the last model called `Poll` - I had to provide the keystone instance so I could execute query as you've described in the example above. For me it would be easier and more consistent to execute a query helper as the hook's callback does.

```js
stats: {
   type: Virtual,
   resolver: async (poll) => {
     const results = await getResults(keystone.executeQuery, poll.id);
     return getStatsPrint(results);
   },
},
```

```js
beforeDelete: async ({ existingItem, actions: { query }}) => {
   const list = await getAnswers(query, existingItem.id);
   await deleteAnswers(query, list);
},
```

**Comment by ra-external** [comment]
@MadeByMike I would second this request. 

In the [documentation](https://www.keystonejs.com/keystonejs/fields/src/types/virtual/) about Virtual fields it says

> If you need to access related items, you can perform a subsequent graphql query within the resolver.

But how do we make this graphql query from inside a Virtual field resolver?  If I want to do keystone.executeQuery I need access to keystone  — I’m also not being passed actions like within the hooks, so I can’t access `actions.query`

Combining an example from the Keystone documentation and that of @cowjen01 above:

```
const { Virtual, Text } = require('@keystonejs/fields');

keystone.createList('Example', {
  fields: {
    name: {
      type: Virtual,
      resolver: (item, query) => {
              const list = await getAnswers(query, existingItem.id);
              await deleteAnswers(query, list);
        }
      };
    },
  },
});
```

Or one could pass in `keystone`, as one does with the custom mutations/resolvers

`const myExtendedQueryResolver =  keystone => async (_, { id }: { id: string }) => {
`

(I have had better luck with `query` than with `executeQuery`, though -- `executeQuery` did not work for a mutation I was doing inside a hook (this was before I realised that `query` was available, that that's another story)
