### ISSUE TITLE
Admin UI freeze on create if the model contains relationship field

### ISSUE THREAD

**Issue by cowjen01** [keystonejs/keystone#2318]
# Bug report

## Describe the bug

If you try to create a new record of object that contains relationship field the side panel of admin UI freeze. I had to close the tab with the application because the browser completely stopped responding.

## To Reproduce

1. create a new model with relationship field (type many)
2. enter admin UI and click on create button

```js
fields: {
    question: {
      type: Text,
      isRequired: true,
    },
    answers: {
      type: Relationship,
      many: true,
      ref: 'PollAnswer',
      isRequired: true,
    },
  },
```

## Screenshots

<img width="1440" alt="Screenshot 2020-01-31 at 21 18 38" src="https://user-images.githubusercontent.com/6173850/73575778-33434680-4479-11ea-8b2e-c05ceeb64e22.png">
<img width="1440" alt="Screenshot 2020-01-31 at 22 19 15" src="https://user-images.githubusercontent.com/6173850/73575779-33434680-4479-11ea-8449-8a51c25c40e1.png">

## System information

- OS: macOS
- Browser:chrome

## Additional context

Working packages:

```
    "@keystonejs/app-admin-ui": "5.6.0",
    "@keystonejs/fields": "6.1.0",
```

Packages contains bug:

```
    "@keystonejs/app-admin-ui": "5.7.1",
    "@keystonejs/fields": "6.2.0",
```

**Comment by MadeByMike** [comment]
Hi Folks, 

It looks like this is to do with a version miss match between the AdminUI and the Fields Package. 

In the last release a component was added to the Admin-UI version `5.7.1` that is used in fields version `6.2.0`. Even though you have updated both version it looks like the dependency in the package.json for fields specifies version `^5.3.0` which would allow for an older version of the AdminUI if you already have it in `node_modules`.

I'm trying to figure out why our release process did pick up on this and bump the version and I'll get a release out ASAP.

If this is impacting you one possible fix is to delete your lock file, this should remove old versions and only fetch the latest.

Sorry about any inconvenience!

**Comment by Sylchi** [comment]
I have keystone running in docker container and its rebuilding it and it still crashes

**Comment by bertez** [comment]
It crashes for me as well using the latest version :(

**Comment by forrest-wilson** [comment]
For the meantime, are there specific package versions that we can install in order to get things up and running?

**Comment by codenakama** [comment]
Same for me

**Comment by chrishahn1975** [comment]
This doesn't work:

 `  "@keystonejs/adapter-mongoose": "^5.1.5",
    "@keystonejs/app-admin-ui": "^5.6.0",
    "@keystonejs/app-graphql": "^5.0.1",
    "@keystonejs/auth-password": "^5.0.2",
    "@keystonejs/fields": "^6.1.0",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.0.4",
    "@keystonejs/keystone": "^5.4.2",
    "@keystonejs/list-plugins": "^5.0.2",
    "cross-env": "^5.2.0",
    "rxjs": "^6.5.4"`

**Comment by MadeByMike** [comment]
Very sorry about this bug people. A new version of fields and the admin-ui have been released:

🦋  New tag:  @keystonejs/app-admin-ui@5.7.2
🦋  New tag:  @keystonejs/fields@6.2.2

I've verified this as fixed but if you could all check and let me know if there are any further issues.

**Comment by MadeByMike** [comment]
Thank you all for reporting this and helping me track it down.

**Comment by forrest-wilson** [comment]
Thank you @MadeByMike! Works a treat mate.

**Comment by chrishahn1975** [comment]
thanks, works

**Comment by cowjen01** [comment]
Thank you @MadeByMike! Works great 🙂

**Comment by wuichen** [comment]
im still seeing the same error with this set of dependencies.  @MadeByMike can you share the ideal dependencies to get it working? thank you very much!

mine: 
		"@keystonejs/app-graphql": "^5.0.1",
		"@keystonejs/app-next": "^5.0.2",
		"@keystonejs/auth-password": "^5.0.1",
		"@keystonejs/build-field-types": "^5.1.4",
		"@keystonejs/field-views-loader": "^5.1.0",
		"@keystonejs/fields": "6.2.2",
		"@keystonejs/fields-wysiwyg-tinymce": "^5.0.4",
		"@keystonejs/file-adapters": "^5.4.0",
		"@keystonejs/keystone": "5.4.3",
		"@keystonejs/list-plugins": "^5.0.2",
		"@keystonejs/session": "^5.0.0",
		"@keystonejs/utils": "^5.1.3",
		"@keystonejs/access-control": "^5.0.0",
		"@keystonejs/adapter-knex": "^6.2.0",
		"@keystonejs/adapter-mongoose": "^5.1.4",
		"@keystonejs/app-admin-ui": "^5.7.2",
		"@keystonejs/field-content": "^5.3.0",

**Comment by wuichen** [comment]
im using a custom copy of app-admin-ui in my project for some custom webpack scripts to enable finding typescript. it used to work seamlessly before the update. however, im seeing the same error as OP with the new update.

switching the import from original `@keystone/app-admin-ui` to a brand new copy in root folder and importing like this `./app-admin-ui` causes admin ui freezes on create button click. what might be the possible cause?

i have updated all the dependencies to latest.

<img width="547" alt="Screen Shot 2020-02-10 at 2 30 14 AM" src="https://user-images.githubusercontent.com/6353587/74107672-8b7ef480-4bad-11ea-860f-eac3a37e46cb.png">
<img width="579" alt="Screen Shot 2020-02-10 at 2 32 33 AM" src="https://user-images.githubusercontent.com/6353587/74107677-a3567880-4bad-11ea-9f04-add107b4ec99.png">

**Comment by chomamateusz** [comment]
@wuichen same problem here.

I even tried to copy latest admin-ui files and updating dependencies. No solution. @wuichen  did u find one?

**Comment by laukaa** [comment]
same with latest version 5.9.3&7.0.2, after i  copied the admin-ui to root path, want to custom the admin-ui by how
