### ISSUE TITLE
New field type: DateRange

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone#232]
As Keystone already uses moment.js, I would like to propose a DateRange field Type using the moment plugin [moment-range](http://gf3.github.io/moment-range/) as mentioned on the [moment docs](http://momentjs.com/docs/#/plugins/range/).

The UI could display this as either two date pickers or (my preference) a single date picker which treats the first click as the start and a second click as the end - or drag, similar to many sites especially travel related.

**Comment by izifortune** [comment]
In my experience they are not that great as UI. Would rather wait the next version of http://amsul.ca/pickadate.js/ that should include a date range picker.

**Comment by morenoh149** [comment]
I'm a fan of pickadate as well. Didn't know a date range was being built by him.

**Comment by izifortune** [comment]
The problem is seems the last commit on v4 its from months ago, don't know when he's gonna release that

**Comment by morenoh149** [comment]
@izifortune email him :)

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/new-field-type-daterange
