### ISSUE TITLE
Keystone - is it only possible to use with MongoDB?

### ISSUE THREAD

**Issue by n1alloc** [keystonejs/keystone#2323]
I'd like to build a CMS with Keystone and host on AWS, with the associated database being DynamoDB.
Can I do this with Keystone currently?
If so, how?

If not, trying to gauge how much would need to be edited to make it work with dynamodb if i decided to fork the code and proceed. All advice welcome and appreciated.

**Comment by morenoh149** [comment]
There's a heavy reliance on mongoose. Interest has been shown in the past to support other databases via an ORM layer of sorts [1](https://github.com/keystonejs/keystone/issues/1600) [2](https://github.com/keystonejs/keystone/issues/838)

I would explore the [aws-sdk](https://github.com/aws/aws-sdk-js/) and see if you can interface keystone's List type with dynamodb.

Topics like these are better suited to the [gitter](https://gitter.im/keystonejs/keystone) as this is not an issue.
