### ISSUE TITLE
Remove the Keystone.adminPath from the login redirect url (query params from)

### ISSUE THREAD

**Issue by Rmannn** [keystonejs/keystone#2326]
I am using the 0.4 branch.

A few days ago, the redirect after login action was fixed and was working great.
Using the from parameter to redirect on the good page after login. In my case (oauth2) the user must login, then he is redirected to the authorization page.
Now, the redirect path is always prepended with the Keystone.adminPath, and there is no way to override this behavior.
That means we can't use the keystone login page without been redirected to the admin.
https://github.com/keystonejs/keystone/blob/master/admin/client/views/signin.js#L48
Commit 056ec5b7e9ddd470f7f19a2f26aaee6ae72b9b3b

**Comment by morenoh149** [comment]
@Rmannn could you reproduce this via an e2e test that fails, but would pass if keystone behaved correctly? that would help A LOT

**Comment by Rmannn** [comment]
Thanks for the info.
In the login test in https://github.com/keystonejs/keystone/blob/master/test/e2eTests/adminUI/group001Login/uxTest001SigninView.js#L18
I saw there is a comment "// just in case we're redirected somewhere other than home page"
What will be the best way to add test ? should I edit the existing test or create a new one ?

**Comment by morenoh149** [comment]
fork the project and write up a new test that goes through the flow as you want. Not resetting the location in case we are redirected. We should be testing what keystone does without navigating to specific pages like that.

**Comment by Rmannn** [comment]
Ok i understand.

**Comment by erg0dic** [comment]
I agree with @Rmannn. When I submitted that patch, I intended to support redirections to any path.

**Comment by webteckie** [comment]
@Rmannn feel free to add another test suite to group001Login.  You may, for example, call it:
```
uiTest002SigninViaOath2.js
uxTest002SigninViaOath2.js
```

For the record, I decided to use 'ui' to denote tests that just check for UI element presense and ux for tests that do/take actions in the UI.
