### ISSUE TITLE
Admin UI css/js files served with incorrect mimetype on Node 5.7.0

### ISSUE THREAD

**Issue by alsoicode** [keystonejs/keystone#2329]
## Problem
After upgrading to Node 5.7.0, Keystone Admin CSS and JS files are served with the incorrect mimetype

![sign into my site - google chrome_005](https://cloud.githubusercontent.com/assets/86738/13294025/127350c2-daf0-11e5-9e33-29360168cdbb.jpg)

Using nvm, I am able to use 5.6.0 and Keystone Admin works as expected.

**Comment by eggytronixx** [comment]
I also notice this error after updating node js to 5.7.0

**Comment by raduchiriac** [comment]
Same as #2325. Downgrading will fix it. I am trying to find a hack to get around it

**Comment by alsoicode** [comment]
Closing as this is a duplicate of: https://github.com/keystonejs/keystone/issues/2325
