### ISSUE TITLE
Mandrill changes

### ISSUE THREAD

**Issue by cleechtech** [keystonejs/keystone#2332]
I got this email from Mandrill.

> Going forward, all Mandrill users will be required to have a paid monthly MailChimp account and verify ownership of all sending domains. Here's the timeline: Starting 3/16, all new Mandrill users will create accounts through MailChimp, and current Mandrill users can merge their existing Mandrill account with a monthly MailChimp account. Current users will have until 4/27 to merge their accounts.

Is Mandrill and Keystone still going to work with these new changes?

**Comment by JedWatson** [comment]
It will, those changes only affect accounts from what I can tell, and not the API or keys.

Having said that I'm currently reconsidering our first class support for Mandrill. We brought it in when Mandrill had great free limits and easy accounts to manage, it doesn't look like it's providing the same value to the project it used to. They've also turned off their Heroku addo-on, which makes the whole setup process more complicated when starting a project.

From their email, tbh it sounds like they don't care so much about Mandrill customers anymore unless you're a paying Mailchimp customer using it for marketing emails. :disappointed:

**Comment by riyadhalnur** [comment]
As far as I know, API calls are directly related to the monthly email limits where 1 email = 1 API call. So if you don't have a free account anymore, you won't be able to utilise those 25k/month free emails they provide.

**Comment by riyadhalnur** [comment]
I think we'd be better off using [nodemailer](https://github.com/nodemailer/nodemailer) for emails.

**Comment by jwils0n** [comment]
In light of this, would it be possible to implement a plugin/adapter feature for email services? I don't think it makes sense to tie to another service--and I sure wouldn't mind writing an adapter or two. If not, I second using nodemailer.

**Comment by jrit** [comment]
There seems to be a plugin of sorts for nodemailer here https://github.com/bgag/keystone-nodemailer and I'm working on making something similar for SES since there doesn't seem to be anything out there right now. It would be better if keystone had more of a provider architecture for email, right now that nodemailer plugin is just replacing `keystone.Email.prototype.send`.

**Comment by riyadhalnur** [comment]
Nodemailer includes support for most email providers including Gmail and SES out of the box.

**Comment by jrit** [comment]
Ha, thanks, I should read the manual

**Comment by morenoh149** [comment]
:+1: nodemailer

**Comment by cleechtech** [comment]
There is definitely some extra config trying to get up and running with nodemailer because it is a lower level solution. That said it is more sustainable long term. I'm a huge fan of the email functionality with Keystone.js! Thank you @JedWatson. Let's move this discussion over to #250 (Add support for nodemailer) .. Happy to reopen if Mandrill gives us more problems
