### ISSUE TITLE
Mongoose update is breaking

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#2333]
The latest patch version of Mongoose (see #2327) is breaking our tests, in a way that suggests some internals we're relying on have changed.

Needs investigation, if anyone can take this on and figure out what's going on that would be great.

**Comment by erg0dic** [comment]
I can look into it tonight

**Comment by JedWatson** [comment]
@erg0dic any news?

**Comment by erg0dic** [comment]
I played with this a little over the weekend, it looks like all of the failures are due to a failure to resolve keystone.mongoose.Schema.Types.ObjectId in fields/types/relationship/RelationshipType.js.

It was bizarre, though, because by logging I could see that ObjectId resolved correctly the first time it was accessed but failed on subsequent accesses.

**Comment by JedWatson** [comment]
@vkarpov15 any chance you can shed some light on this? ping me if you need help working out how to reproduce / what's relevant to Keystone, etc.

**Comment by creynders** [comment]
My guess is [this commit](https://github.com/Automattic/mongoose/commit/0a04079472c6ba18bdbed8d423a6dd648f8f8161) is the culprit and something goes wrong when wrapping the mongoose singleton with the thenable.

**Comment by JedWatson** [comment]
Good sleuthing @creynders, that makes sense to me (that it would be related, not what the issue is that thenable is causing). Maybe the `mongoose` object is being mutated in some way after the initial access? I had the impression `mongoose.Schema.x` was all public API for mongoose.

**Comment by creynders** [comment]
Ah yes, of course any function is mapped to the same `key` all over again, since he doesn't use an iife: https://github.com/Automattic/mongoose/blob/0a04079472c6ba18bdbed8d423a6dd648f8f8161/lib/index.js#L58 to create a closure object and pass the value of `key` to it.

**Comment by creynders** [comment]
Ah, it's been fixed in master :) https://github.com/Automattic/mongoose/blob/master/lib/index.js#L58

**Comment by creynders** [comment]
And released, i.e. update mongoose to v4.4.6 guys.

**Comment by creynders** [comment]
It's still a problem since here https://github.com/keystonejs/keystone/blob/master/fields/types/relationship/RelationshipType.js#L17
`keystone.mongoose.Schema` refers to the wrapped function, i.e. it doesn't have a `Types` property.

Time to submit an issue in the mongoose repo I think.

**Comment by creynders** [comment]
https://github.com/Automattic/mongoose/issues/3940

**Comment by vkarpov15** [comment]
Thanks for reporting, sorry about the issue. The change to make '.connect()' thenable caused a lot of unintentional side effects. Will fix on the mongoose end next week

**Comment by creynders** [comment]
@vkarpov15 cool, thanks!! :ok_hand:

**Comment by JedWatson** [comment]
:+1: thanks @vkarpov15, much, appreciated!

**Comment by creynders** [comment]
Fixed with #2410
