### ISSUE TITLE
De-register lists

### ISSUE THREAD

**Issue by geloescht** [keystonejs/keystone#2336]
Sometimes a developer might want to remove a list again from keystone dynamically without restarting the server. It can be useful in a scenario, where plugin-style modules are allowed to define lists, but can be added and removed at runtime.

**Comment by mxstbr** [comment]
I'm not sure I fully understand the usecase for this. In what scenario would I want to remove or add a list without having the option to restart the server?

**Comment by geloescht** [comment]
It'd be possible to restart the server whenever a component is added or removed from our application. However, I'd prefer to avoid any downtime or disruption to long-running websocket connections. The only problem that arises from the inability to remove lists is, that components that get removed and re-added (for example when they are updated) cannot register identically named lists again.
I would rate this a minor feature request as a restart is an option. I just prefer to have a remove method for every add method. Old C++ programmer habit ;)

**Comment by mxstbr** [comment]
Seems reasonable! I'll close this issue since we've moved the feature requests, can you add this one to product pains?

Thanks! https://productpains.com/create/keystonejs
