### ISSUE TITLE
Disable counting items on the Admin UI "Dashboard" screen (and/or use approximate counts)

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#2336]
One of the systems I work on has millions of items in its lists. Every time the Admin UI is opened, the main Dashboard screen runs a query to count the items _in every list_ so it can render the list cards, like this (but with more, obviously):

<img width="666" alt="Screenshot 2020-02-05 at 13 24 16" src="https://user-images.githubusercontent.com/2416367/73805537-0e552780-481b-11ea-83e4-5e9beda0cb6e.png">

For the system in question, the GraphQL query to retrieve this info can take multiple seconds to run. This loads the DB for no good reason but, more noticeably, slows down the page render, making the admin sign in experience feel a _lot slower_. There are also potential security implications for all admins being able to see the number of items in each list.

It'd be nice if this count could be easily turned off, possibly on a per-list basis. 

Alternatively (or maybe additionally), most DBs have a method where approximate counts can be retrieved much faster than completely accurate counts. In Postgres you can query the approximate number of rows in a table from [the `pg_class` catalog](https://www.postgresql.org/docs/current/catalog-pg-class.html). This can be orders of magnitude faster than a standard `count()`:

```sql
-- 100-1700 ms 😧
select count(*) as accurate_rows from "Post";

-- < 1 ms 🥳
select reltuples as approx_rows from pg_class where relname = 'Post';
```

We could, for example, add an `approximateCount: Int` field (without any filters) to the `_ListMeta` GraphQL type, then update the Admin UI to query it instead.

----

Interestingly (and somewhat alarmingly?) Mongo actually gives approximate counts in this case _by default_:

> Avoid using the db.collection.count() method without a query predicate since without the query predicate, the method returns results based on the collection’s metadata, which may result in an approximate count.

-- [`db.collection.count()` docs](https://docs.mongodb.com/manual/reference/method/db.collection.count)

So.. I guess that's a good thing? 🙃

**Comment by jesstelford** [comment]
Oooh, I like the `approximateCount` field idea!

I'm also happy to add an option to remove display of totals from the dashboard.

Want to split this into two tickets?

**Comment by gautamsi** [comment]
Could this be configurable?
