### ISSUE TITLE
Add a "Forgotten Password" plugin / package / demo

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2337]
# Feature request

Most apps with user-facing authentication will use email/password. People are forgetful. They want a way to reset their password when they forget it.

## Describe the solution you'd like

A "standard" Forgotten Password flow either built into Keystone, or as a plugin / separate package that's easy to get started with.

## Additional context

The meetup demo has this flow built in: https://github.com/keystonejs/keystone/pull/1253

**Comment by gautamsi** [comment]
I feel this can be a plugin for user list. 

at this point I strongly feel that there should be some core list `User`, `Settings/Config` and few more if needed. this way some of the assumptions could be baked in. 

we can also have name of such list configurable.

**Comment by ralexrdz** [comment]
Here is a demo project with forgotten password characteristic. Plus: on user registration, they are inactive, validation token is created and probably sent via email.

Is same code from meetup demo, simplified

https://github.com/centroculturadigital-mx/keystone-user-management-demo

```
├── access.js
├── CHANGELOG.md
├── hooks
│   ├── afterUserChange.js
│   ├── index.js
│   └── validateUserInput.js
├── index.js
├── initial-data.js
├── lists
│   ├── ForgottenPasswordToken.js
│   ├── index.js
│   ├── User.js
│   └── UserValidationToken.js
├── package.json
├── package-lock.json
├── README.md
├── schema
│   ├── index.js
│   └── mutations
│       ├── changePasswordWithToken.js
│       ├── startPasswordRecovery.js
│       └── validateUserWithToken.js
```

index.js 

```
...
keystone.createList('User', User)
keystone.createList('ForgottenPasswordToken', ForgottenPasswordToken)
keystone.createList('UserValidationToken', UserValidationToken)

keystone.extendGraphQLSchema(CustomSchema)
...
```

Hope will help someone else :wink:

**Comment by ClientsideDesign** [comment]
Thanks for the hard work - an inbuilt forgotten password flow would be very useful
