### ISSUE TITLE
Passwordless Auth Strategy

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2338]
# Feature request

Add a "Passwordless" auth strategy to the core package.

## Describe the solution you'd like

The user auth flow would go like so:

1. User is prompted to enter their email address
2. If this email is new, a `User` item is created, and the email address is set
3. A `loginToken` is generated for the `User`
4. The `loginToken` is sent to the user via some trusted 3rd party channel (eg; email)
5. The user presents the `loginToken` to Keystone (eg; by clicking a link in their email)
6. The `loginToken` is used to look up the user
7. The user is logged in
8. The `loginToken` is invalidated

Note that step 4 doesn't have to be just email (although it's the easiest method), it could also be things like "Post a message to the Bitcoin blockchain", or "Send a message via previously agreed GPG keys", etc. Any trusted 3rd party channel will work.

## Describe alternatives you've considered

This would help solve the [Forgotten Password](https://github.com/keystonejs/keystone/issues/2337) problem, and also significantly simplifies the security requirements for sites with user data.

## Additional context

This is somewhat similar to the social auth strategies, but without any of the OAuth dance.

**Comment by molomby** [comment]
This would be an awesome user flow to support well. A few thoughts:

Anyone who presents to the system with a users identifier (eg. username/email address) and a valid `loginToken` for that user is authenticated as the user. As such, the `loginToken` is basically a time-limited, single-use password. We wouldn't want to store the tokens in plain text for example, as anyone who could get access to the DB could compromise the (small number of) accounts for which a current `loginToken` exists. Instead, we'd store a hash of the token and validate against that. So internally `loginTokens` should probably use the `Password` field type. (Basically this auth strategy will be "passwordless" in the same sense as "serverless" -- there's still a password, you just don't use it directly 😄).

Between the existing functionality in the password field and the auth mutation hooks which I can hopefully wrap up soon, we'll have all the building blocks for this. (The auth hooks stuff is kicking around in [some docs](https://github.com/keystonejs/keystone/pull/2037/commits/001930509ffffe1cccc102405987ec20ab56af09), work in progress, slowly).

Something like this would get you most of the way I think:

```js
// The user list has two auth strategies, the normal one and one for the token
// The normal auth strat is passed to AdminUIApp() later (not shown here)
const standardLogin = keystone.createAuthStrategy({ type: PasswordAuthStrategy, list: 'User' });
const tokenLogin = keystone.createAuthStrategy({
  type: PasswordAuthStrategy,
  list: 'User',
  config: { secretField: 'loginToken' },
});

// Define the user list
keystone.createList('User', {
  fields: {
    email: { type: Text },
    password: { type: Password },

    // Field to support emailing login tokens
    loginToken: { type: Password },
    loginTokenValidUnill: {},
  },
  hooks: {
    // Before we attempt to auth, check the user identified has been issued a token
    validateAuthInput: async ({ resolvedData, actions: { query }, addFieldValidationError }) => {
      const gqlQuery = `
        query {
          users: allUsers(where: {
            email: $email
            loginToken_is_not: null
            loginTokenValidUnill_gt: $now
          }) { id }
        }`;
      const options = {
        skipAccessControl: true,
        variables: { email: resolvedData.id, now: new Date() }
      };
      const { errors, updateUser } = await query(gqlQuery, options);
      if (errors && errors.length > 0) throw errors;
      if (updateUser && updateUser.length === 0) {
        addFieldValidationError(`User not found, no token issued or token has expired`);
      }
    },

    // If the user matches and the token is valid, etc. clear the token so it can't be used again
    afterAuth: async ({ item, success, actions: { query } }) => {
      if (!success) return;

      const gqlQuery = `mutation { updateUser(id: $id, data: { loginToken: null }) {} }`;
      const options = { skipAccessControl: true, variables: { id: item.id } };
      const { errors } = await query(gqlQuery, options);
      if (errors && errors.length > 0) throw errors;
    },
  },
});
```

_(I haven't, like, run this ^^ or anything; just for an illustration purposes)_

We just need to (finish the auth hooks work and) wrap this up as a nice, configurable list plugin 🥳

**Comment by rmcsharry** [comment]
I'd love to hear if there has been any progress on this potentially "nice configurable list plugin"?
