### ISSUE TITLE
Change e-mail service to Mailgun

### ISSUE THREAD

**Issue by ytzvan** [keystonejs/keystone#2338]
Due to a recent changes into Mandrill, now Malchimp wants you to use their paid service in order to send transactional e-mail, [article here](http://blog.mailchimp.com/important-changes-to-mandrill/). 
I suggest move the default e-mail service to [Mailgun](https://www.mailgun.com/). 

I can check how this works inside Keystone and make a pull req in the near future.
What do you think guys?

**Comment by morenoh149** [comment]
I feel like the community is favoring moving to nodemailer #205 let me know if you still want the issue open.

**Comment by ytzvan** [comment]
@morenoh149 I think nodemailer is a good option, but the easy integration with Mandrill is a great feature. I think we can provide multiple e-mail providers, same as how keystone provides multiple view engines, but this will require more work to do. I'm happy to contribute with this. Maybe you can leave the issue open for a few days in order to know what the community things.

**Comment by morenoh149** [comment]
I see nodemailer can also be hooked up to mailgn https://github.com/nodemailer/nodemailer#delivering-bulk-mail

**Comment by mzgnr** [comment]
I think we should work on mailgun option.

**Comment by mzgnr** [comment]
The other option is Sparkpost. https://developers.sparkpost.com https://www.sparkpost.com and they love developers

**Comment by danielmahon** [comment]
I like the idea of nodemailer, and maybe including a rather detailed setup for ONE easy transport like gmail by default, direct others to nodemailer for info

**Comment by sagarrao** [comment]
I tried to integrate sendgrid coz of the recent developments with Mandrill(As mentioned in OP). But, my app(deployed on heroku) suffers wherein none of the css/js loads. The page renders but without any css applied. On my console I see logs like :

404 /{app-name|/js/lib/jqueryfileupload/vendor/jquery.ui.widget.js 

So, on and so forth. Once I remove sendGrid and add Mandrill this works but I can't send emails coz I don't have a paid account.

**Comment by mxstbr** [comment]
Lets close this and track all related questions in #250.
