### ISSUE TITLE
Markdown fields with noedit:true - fail in admin UI when having an undefined value

### ISSUE THREAD

**Issue by trentmillar** [keystonejs/keystone#2339]
This can be verified using Jed Watson's SydJS website.

Reproduce by editing the User model and setting the "Bio" field (which is Markdown) to `noedit : true`. When I open any user not having this defined will fail - specifically the `value` property is undefined and the `md` call fails.

FYI- the `Html` field type doesn't have the same problem.

<img width="1296" alt="no-edit_true" src="https://cloud.githubusercontent.com/assets/1146672/13342576/2935cf90-dc00-11e5-8962-fa74ef632fde.png">

**Comment by victoriafrench** [comment]
Looked at this one to fix it, and it is an easy fix. I want to check with @JedWatson first though. It appears that the MarkdownField in master may not be completed yet. He may have a version not checked in. Will update.

**Comment by JedWatson** [comment]
Good find @victoriafrench - that field type has not been updated to the latest standard. I don't have any work on it not checked in so please feel free to clean it up :)

**Comment by JedWatson** [comment]
Fixed by #2359 - thanks @victoriafrench!
