### ISSUE TITLE
SECURITY.md

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#2343]
# Feature request

We should have a SECURITY.md file for Keystone

## Describe the solution you'd like

We should establish SECURITY.md file to have people a way to responsibly report vulnerabilities

## References

https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository

**Comment by VinayaSathyanarayana** [comment]
PR #2344

**Comment by MadeByMike** [comment]
Closed by #2344
