### ISSUE TITLE
Create documentation for custom page views

### ISSUE THREAD

**Issue by parkerhutchinson** [keystonejs/keystone#2348]
# Create Documentation for Custom Page Views. 

## Is your feature request related to a problem? Please describe.

A user should (and does) have the option to create custom page views for keystone. The code was implemented back in April 2019 [#1019](https://github.com/keystonejs/keystone/pull/1019). The only way I know you can is by reading the PR. This is a pretty common ask I would think.

## Describe the solution you'd like

Concise documentation on custom page view creation. dependencies and configuration documentation.

**Comment by MadeByMike** [comment]
We have this: https://www.keystonejs.com/keystonejs/app-admin-ui/#pages

As well as some demo projects that use custom pages. If anyone would like to write a guide contributions would be most welcome :)
