### ISSUE TITLE
morgan logger logging to file

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#2348]
How do i set options for the morgan logger to log to a file with file rotation?

**Comment by VinayaSathyanarayana** [comment]
Got it working

**Comment by morenoh149** [comment]
mind sharing the solution?

**Comment by VinayaSathyanarayana** [comment]
What worked was 
In Keystone.js
`// Logging Starts here
var FileStreamRotator = require('file-stream-rotator')
var fs = require('fs')
var logDirectory = __dirname + '/log'
// ensure log directory exists
fs.existsSync(logDirectory) || fs.mkdirSync(logDirectory) 
// create a rotating write stream
var accessLogStream = FileStreamRotator.getStream({
  date_format: 'YYYYMMDD',
  filename: logDirectory + '/access-%DATE%.log',
  frequency: 'daily',
  verbose: false
});

`
Add this to the keystone options
	'logger options' : {stream: accessLogStream}
