### ISSUE TITLE
Admin UI slower than expected in production mode

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#235]
As mentioned on the [Google Group](https://groups.google.com/forum/#!topic/keystonejs/orzksUhkUJ8), the admin pages don't seem to speed up significantly in production mode. We should look into why.

**Comment by sebmck** [comment]
@JedWatson Has any work been done on this?

**Comment by JedWatson** [comment]
Some, yes; certain scripts are only included as necessary and the move to browserify / react changes things considerably too. I think it's safe to close this now, the speed will continue to improve as we move towards a SPA.
