### ISSUE TITLE
yo keystone Error keystone

### ISSUE THREAD

**Issue by liskiew** [keystonejs/keystone#2351]

**Comment by nobaidu** [comment]
Everything looks all right!
+ yo@2.0.5
updated 1 package in 41.909s
[root@VM_0_9_centos ks]# yo keystone
/www/server/nvm/versions/node/v10.15.0/lib/node_modules/yo/node_modules/write-file-atomic/index.js:197
    throw err
    ^

Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json.327516535'
    at Object.openSync (fs.js:439:3)
