### ISSUE TITLE
Run Cypress tests against Firefox & Edge

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2351]
[Cypress now supports Firefox & Edge](https://cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0).

We should run our Cypress tests against FF & Edge.

There's [a Cypress CircleCI Orb](https://circleci.com/orbs/registry/orb/cypress-io/cypress#executors-browsers-chrome73-ff68) which might make this easier, but I'm not sure.

**Comment by individual-it** [comment]
I would like to work in this, can you assign me?

**Comment by jesstelford** [comment]
Thank you @individual-it! Be sure to read `CONTRIBUTING.md` & jump in [the Slack](http://community.keystonejs.com/) if you have any questions 👍

**Comment by individual-it** [comment]
as first step I updated cypress #2674 , and the PR used to be green, but after other changes (that I reverted) CI does not pick it up and does not run on it. Any idea?

**Comment by individual-it** [comment]
@timleslie thanks for merging #2674 
I have now the same problem with CI in #2733, circleci does not start. Any idea why?
