### ISSUE TITLE
Cloudinary eager transformations

### ISSUE THREAD

**Issue by larsha** [keystonejs/keystone#2360]
Hi,

Does Keystone support eager transformations in Cloudinary uploads? I can't find any information about it. (http://cloudinary.com/documentation/upload_images#eager_transformations)

Or is it possible to set image preset when uploading? (To let Cloudinary handle eager transforms based on the preset in the upload)

**Comment by mxstbr** [comment]
Tracking in #2260, thanks for reminding us!
