### ISSUE TITLE
Connection to Microsoft SQL Server fails because Keystone checks for PostgreSQL version

### ISSUE THREAD

**Issue by ccalvarez** [keystonejs/keystone#2361]
# Bug report

## Describe the bug

Connection to Microsoft SQL Server fails because the code enters to the [checkDatabaseVersion](https://github.com/keystonejs/keystone/pull/2112/commits/54960ba81e67f093f9f5e9e2b15a718888de17aa) function which is checking for PostgreSQL version.

## To Reproduce

1. Go to the entry point of the KeystoneJS application (`index.js`) and configure [Knex Adapter options](https://www.keystonejs.com/keystonejs/adapter-knex/#optionsknexoptions) to connect to MS SQL Server:

```
const ConnectionString = require('mssql/lib/connectionstring');

const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new Adapter({
    knexOptions: {
      client: 'mssql',
      connection: ConnectionString.resolve(
        'mssql://pruebas:pruebaspassword@localhost:8666/KeystoneJS'
      ),
    },
  }),
});
```

2. Run the application with `yarn dev`

3. See error:

![image](https://user-images.githubusercontent.com/2665104/74355945-28df5180-4d83-11ea-9e31-065b2f97de00.png)

## Expected behaviour

Expected behaviour is to connect to MS SQL Server successfully as it does if I comment the call to the `checkDatabaseVersion` function:

![image](https://user-images.githubusercontent.com/2665104/74356258-a86d2080-4d83-11ea-9ef1-932748e1d619.png)

## System information

- OS: Windows 10, Version 1709, Build 16299.1087

- Packages versions:

create-keystone-app@1.5.1

```
"@keystonejs/adapter-knex": "^6.2.0",
    "@keystonejs/app-admin-ui": "^5.3.0",
    "@keystonejs/app-graphql": "^5.0.1",
    "@keystonejs/app-static": "^5.0.0",
    "@keystonejs/fields": "^6.0.0",
    "@keystonejs/keystone": "^5.3.0",
    "cross-env": "^5.2.0",
    "dotenv": "^8.2.0",
    "msnodesqlv8": "^0.8.6",
    "mssql": "^6.0.1"
```

Thank you.

**Comment by MadeByMike** [comment]
Good catch, we don't officially support MySQL in that we do not build and test against it however Knex can support this and we don't want to do anything that would stop this from working. Happy to accept PRs to wrap this is a try catch or an option to ignore.

**Comment by znk** [comment]
A workaround by overriding the Adapter class:
```js
const { KnexAdapter: Adapter } = require('@keystonejs/adapter-knex');

// ref: https://raw.githubusercontent.com/keystonejs/keystone/master/packages/adapter-knex/lib/adapter-knex.js
Adapter.prototype.checkDatabaseVersion = async (...args) => true
```

**Comment by Vultraz** [comment]
See PR ^
