### ISSUE TITLE
GeoPoint field enhancements

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2362]
May be good to introduce some of the feature/options described at https://www.elastic.co/guide/en/elasticsearch/reference/1.4/mapping-geo-point-type.html into the GeoPoint field.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/geopoint-field-enhancements!
