### ISSUE TITLE
Access Control for standard Keystone Lists

### ISSUE THREAD

**Issue by deepcode666** [keystonejs/keystone#2363]
I want to implement access control to standard Keystone Lists. I am looking to provide access control for Create, Read/View, Update, Delete (CRUD Operations). 

I see that the Keystone urls 
a. For Delete - http method is post and the last word in path is "delete" - I can distinguish based on this OK

b. For Create, Read and Update - I see that the http method is get and the last word in path is "autocomplete" - Because of this I am unable to distinguish between Create, Read/View and Update. 

@JedWatson can you please help me understand how to distinguish the various requests.

**Comment by VinayaSathyanarayana** [comment]
Can we have a standard middleware option that is called with a signature something like this
keystoneAccessControl(user, crud_operation, list, [ObjID] ) and the method returns true if the access can be provided and false if access cannot be provided.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
