### ISSUE TITLE
[Admin UI] Hot Reload on Admin UI?

### ISSUE THREAD

**Issue by maximelebreton** [keystonejs/keystone#2369]
Hello,

Any plans to implement Hot Reloading on Admin UI?
I don't see it in your roadmap: https://www.keystonejs.com/guides/road-map

Currently we have to relaunch the server on **every little** modification, like edit the fields options (defaultValue etc...), and this is a big waste of time during the development phase.

Thanks!

**Comment by Vultraz** [comment]
The admin UI itself already supports hot reloading. The thing is, the field configs don't 😬

**Comment by maximelebreton** [comment]
Thanks @Vultraz, but then, is this only a bug or a deeper case you won't fix?

**Comment by Vultraz** [comment]
Well, you could use `nodemon` to auto-restart the server.

**Comment by justintemps** [comment]
@maximelebreton Here's how I got this to work with nodemon:
```
"scripts: {
    ...
    "dev" : "cross-env NODE_ENV=development DISABLE_LOGGING=true nodemon --exec keystone dev"
,
```

**Comment by MadeByMike** [comment]
Yep, nodemon is the solution for this for now.

**Comment by timothy02** [comment]
Hey, in my case solution provided by @justintemps doesn't work. When keystone prints in the console `√ Builder initialized` nodemon resets and the building starts from the beggining causing an infinite loop. Any ideas how to solve it?

**Comment by justintemps** [comment]
@timothy02 yea sorry I was assuming you'd already build the dist files before running keystone dev. I don't think it will do that if you run `keystone build` first.

**Comment by matkoklaic** [comment]
`nodemon --exec keystone dev` fails when _nodemon_ restarts keystone instance in my case 

![Screenshot from 2021-11-23 12-35-06](https://user-images.githubusercontent.com/2469643/143036411-eb1783c1-6024-4115-878c-3b0627e16c8d.png)

**Comment by gautamsi** [comment]
hot reloading is in built now see - https://keystonejs.com/releases/2021-11-02#server-side-live-reloading
