### ISSUE TITLE
[AdminUI] defaultValue as function not working on Calendar Day

### ISSUE THREAD

**Issue by maximelebreton** [keystonejs/keystone#2370]
Hey there,

I wanted to put the **current day** as default value on the `CalendarDay` field.  

So I read the [fields config documentation](https://www.keystonejs.com/keystonejs/fields/#config): 
![image](https://user-images.githubusercontent.com/1072425/74587133-11a49c00-4fef-11ea-9346-4e187ab1b766.png)

And then [CalendarDay config documentation](https://www.keystonejs.com/keystonejs/fields/src/types/calendar-day/#config)

I tried to do this, but **it doesn't work**:

```js
fields: {
    date: {
      type: CalendarDay,
      defaultValue: () => Date.now().toISOString() // doesn't work
```

So to be sure, I tried this, and **it works**:

```js
fields: {
    date: {
      type: CalendarDay,
      defaultValue: "2020-01-01" // works
    }
```

So I tried this, and **it doesn't work**...
```js
fields: {
    date: {
      type: CalendarDay,
      defaultValue: () => "2020-01-01" // doesn't work
    }
```

So the **defaultValue** prop as **function** doesn't work...

Maybe it's related to all fields, I haven't tested it?

**Personal thought:**
Please switch to Typescript, we shouldn't meet anymore this kind of stuff in 2020 :)

**Comment by 2xAA** [comment]
This also seems to be the case with the `DateTime` type.

My schema:

```JavaScript
fields: {
  createdAt: {
    type: DateTime,
    defaultValue: () => new Date().toISOString()
  }
}
```

**Comment by reubano** [comment]
dupe #2043

**Comment by MadeByMike** [comment]
Yes, this is a duplicate and I've just updated the documentation so that this doesn't happen again. @maximelebreton I'm sorry for the confusion please for why this must be a string: #2043

**Comment by Vultraz** [comment]
Actually, after #2347 the function default *should* work as long as `isRequired` is false.
