### ISSUE TITLE
MIME type text/html for auth.min.css on Heroku

### ISSUE THREAD

**Issue by yustnip** [keystonejs/keystone#2384]
I've tried to deploy the app to Heroku but styles for the Sign In page isn't applied. Error:
```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://***.herokuapp.com/keystone/signin?from=/keystone/styles/auth.min.css".
```
Is this a bug of Heroku or KeystoneJS?

**Comment by victoriafrench** [comment]
references #2378

**Comment by mxstbr** [comment]
I'll close this issue now that #2378 is merged into v3, let me know if you're still running into this problem!

**Comment by mxstbr** [comment]
(also, thanks @victoriafrench for the reference linking, that was very helpful!)
