### ISSUE TITLE
Multiple blogs

### ISSUE THREAD

**Issue by Vladimir37** [keystonejs/keystone#2385]
Is it possible to have more than one blog on one Keystone site? Different blogs have the different posts, own feed. Is it possible?

**Comment by webteckie** [comment]
@Vladimir37 why not:
```
var BlogPost1 = new keystone.List('BlogPost1', {});
BlogPost1.add({...whatever fields...});

var BlogPost2 = new keystone.List('BlogPost2', {});
BlogPost2.add({...whatever fields...});

...
```
You may even be able to use inheritance where you define a parent blog post model with all the fields and just discriminate for the different blogs via derived child blog lists.  See the `Inheritance example` section in the [docs](http://keystonejs.com/docs/database/#lists-options). 

The Admin UI panel will support this just fine.  If you will also have front-end views, you just need to wire the routing/views correctly.

Hope this helps and will close this.  If you require more help, feel free to ask in [gitter](https://gitter.im/keystonejs/keystone).
