### ISSUE TITLE
Admin UI Path error on mac

### ISSUE THREAD

**Issue by Yinear** [keystonejs/keystone#2388]
keystone/admin/app/static.js  line45 and 46

```
router.use('/styles', less(__dirname + '../../public/styles', lessOptions));
router.use(express.static(__dirname + '../../public'));
```
The less path and static is xxx/admin/app../../public
This works on linux but not on mac。

On my mac , I changed it to  __dirname + '/../public'  and it works.

Do you have the same problem？

**Comment by victoriafrench** [comment]
router.use('/styles', less(path.join(__dirname, '../public/styles'), lessOptions));
router.use(express.static(path.join(__dirname, '../public')));

is the fix that is pending in the pull releases.

associate with #2378

**Comment by mxstbr** [comment]
Since #2378 was merged, I'll assume this is fixed – feel free to comment/reopen this issue if you're still running into it.
