### ISSUE TITLE
Housekeeping: Upgrade slate

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#2389]
`slate` 0.50.0 completely redesigned the codebase and the upgrade is is apparently non-trivial. See https://github.com/ianstormtaylor/slate/blob/master/Changelog.md#0500--november-27-2019 for more info.

**Comment by jesstelford** [comment]
Yes! I've been meaning to look into this deeper.

The biggest hurdle I think we're going to face is any data-shape changes meaning existing sites may have to migrate their data somehow into the new format. I hope the changes are minimal.

**Comment by Vultraz** [comment]
Started working on this locally.

**Comment by Vultraz** [comment]
#2510 (very WIP)

**Comment by acoreyj** [comment]
@JedWatson I saw somewhere a new field is being added that uses the new version of Slate, is there an ETA for that?

Thanks!

**Comment by timleslie** [comment]
The new [document field in keystone-next](https://next.keystonejs.com/guides/document-fields) will use an updated version of slate. The `Content` field will not be supported in `keystone-next`, so I'm going to close this issue.
