### ISSUE TITLE
Change default for `<FieldType>.getQueryFragment()`

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#239]
> we should (somehow?) inspect the fields provided by the implementations getGraphqlOutputFields()

See: https://github.com/keystonejs/keystone-5/pull/237/files#diff-42e58ca6bffd2dcc9e634cd62255fca8R11

**Comment by MadeByMike** [comment]
@tim is this still relevant?

**Comment by timleslie** [comment]
Closing this issue as it is no longer relevant for `keystone-next`.
