### ISSUE TITLE
[0.3] Open redirects as in keystone/signin?from=ftp://example.com considered an attack vector

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#2394]
I got notification today that one of the keystone sites I'm developing is considered having malicious content, of the flagged URL's two contained a signin redirect and the other two were the results of the redirect. When checking Google's [Identify the vulnerability page](https://support.google.com/webmasters/answer/3013681) it says:

>Open redirects are coded with the intention for the URL structure to allow the addition of another URL so users can reach a useful file or webpage on the site. For example:

>http://example.com/page.php?url=http://example.com/good-file.pdf
>Hackers can abuse open redirects by adding their spammy or malware page to the site’s open redirect, similar to this:
>http://example.com/page.php?url=<malware-attack-site>

The solution to this would be

>whether your code can prohibit off-domain redirects, or if you can sign the redirect so that only those with properly hashed URLs and the cryptographic signature can be redirected.

We need to fix this. What would be the best approach? Sifting off-domain redirects or?

@JedWatson @dcousens @jossmac

**Comment by creynders** [comment]
I didn't find where the redirection happens after the user successfully signs in on v0.4, but for v0.3 there's only a partial sifting: https://github.com/keystonejs/keystone/blob/v0.3.x/admin/routes/views/signin.js#L29

This will not match (i.e. it allows) any non http(s) protocol: `ftp://example.com`, file:///some.file`

**Comment by creynders** [comment]
Tried it out on the demo site and it doesn't appear to be a problem on 0.4-alpha

**Comment by JedWatson** [comment]
So I'd be happy to prevent the protocol and domain parts altogether, this feature is really only intended to bounce you to somewhere on the same host (usually into a page in the Admin UI)

Any more sophisticated sign in / redirection behaviour that that should be custom anyway.

**Comment by JedWatson** [comment]
... which is to say, I'd be happy to accept a PR implementing that and push out a patch update to 0.3 that fixes this for you @creynders - there are some other PRs for 0.3.x it would be good to review & get released as well

**Comment by creynders** [comment]
@JedWatson I implemented a hotfix here: https://github.com/d-pac/keystone/commit/9593fa0c40fc47e07e2513a1394353bb06bd2da7
If that's good enough for you guys, I'll turn it into a PR. I'm also waiting on a google review, just to be sure I haven't forgotten/overlooked anything.

**Comment by JedWatson** [comment]
That looks good to me @creynders

**Comment by creynders** [comment]
@JedWatson Ok, I'll turn it into a PR. Just got Google approval BTW and the phishing notification was removed.

**Comment by mxstbr** [comment]
Fixed in #2408

**Comment by molomby** [comment]
This issue reemerged in the 0.4 branch, was picked up by Marc Wickenden (4ARMED) and [written up](https://www.4armed.com/blog/open-redirect-in-keystonejs).

Re-fixed in 1c93aa293.
