### ISSUE TITLE
Support direct editing of cloudinaryimage fields

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#24]
You should be able to edit the public_id and other fields of a CloudinaryImage field (advanced mode).

Should include copy + paste functionality to copy images from one item to another.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/support-direct-editing-of-cloudinaryimage-fields
