### ISSUE TITLE
UnicodeData！！what's the happen, it's net error?

### ISSUE THREAD

**Issue by winfan** [keystonejs/keystone#2400]
try to read file /usr/share/unicode/UnicodeData.txt …
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt

by   mac pro os x

**Comment by winfan** [comment]
npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1

**Comment by geloescht** [comment]
Appears not to be an issue with keystone. See here for solutions: https://www.npmjs.com/package/unicode

**Comment by creynders** [comment]
Closed, since it's not a keystone issue. Thanks @geloescht for pointing @winfan in the right direction!

**Comment by xusai2014** [comment]
@geloescht how to solve the questions. I want run keystone in mac os

**Comment by geloescht** [comment]
Try if you can download http://unicode.org:80/Public/UNIDATA/UnicodeData.txt manually. If not, somethings wrong with your connection. If yes, unicode.org is down or something else might be wrong with the unicode package's install process on MacOS.

**Comment by xusai2014** [comment]
@geloescht Yes, I can download the txt file with browser. How to handle the error on MacOs? I failed to try some solutions.

**Comment by geloescht** [comment]
I don't use MacOS, so no idea. I only know it's not a keystone problem, so please ask here: https://github.com/dodo/node-unicodetable/issues

**Comment by srl295** [comment]
cause:  https://github.com/dodo/node-unicodetable/issues/16#issuecomment-288306521
