### ISSUE TITLE
Date resets in Datetime field on admin panel

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#2401]
Description
-------------------
If I change the time after the date, the date field lost changes.
It does because the `DateInput` component has his own state and don't pass changes to parent component `DatetimeField`, so props and state is different.
![datetime](https://cloud.githubusercontent.com/assets/8686751/13679068/2606ecbc-e6f2-11e5-98d7-0be4730943c2.png)
When I change the time, parent component rerenders and pass old `props`.
Maybe `DateInput` must be stateless?

**Comment by mxstbr** [comment]
Good catch, I can replicate this – we'll take a look!

**Comment by mxstbr** [comment]
Here's a gif replication:

![datetime-bug](https://cloud.githubusercontent.com/assets/7525670/13869128/43ba4a72-ed25-11e5-8310-4ade40a70933.gif)

**Comment by geloescht** [comment]
Can't replicate in v0.4, is it fixed? @mxstbr

**Comment by mxstbr** [comment]
Yeah, I fixed that while I was at it, thanks for reminding me!
