### ISSUE TITLE
Tagging input type

### ISSUE THREAD

**Issue by bringking** [keystonejs/keystone#2402]
Does Keystone support a on-the-fly tagging input type similar to the method shown here- 

https://en.support.wordpress.com/posts/tags/

as opposed to going to "Tags -> Creating a tag -> saving -> going to Post -> Associate Tag"?

**Comment by mxstbr** [comment]
This is not currently supported, but we intend to implement this after the v4 update. Good question!

**Comment by wmertens** [comment]
@bringking could you clarify what your expectations of this feature are? That will help in getting this created.

**Comment by bringking** [comment]
@wmertens Sure thing. I have been thinking about trying to implement this myself on the the 3.x branch, since I need it for a client. So let me know if someone is already tackling it. Basically I am expecting something to work in the following ways -

* Have Keystone automatically create or allow the user to specify a "Tag" model. 
* The "Tag" Model must specify at least a single column "Text" or "Value". This will serve as a Unique column and will be indexed.
* The "Tag" Model can be added as a Relationship to other models
* When editing a model with "Tags", a Select component with the "allowCreate" option will be present
* On creation, Keystone will save a new "Tag" and associate with the target object upon saving.

Is this helpful?

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/tagging-input-type!
