### ISSUE TITLE
How to use EJS template engine in Keystone?

### ISSUE THREAD

**Issue by SuperSpaceZova** [keystonejs/keystone#2403]
I'm trying to replace the standard template engine in keystone with EJS, but none of the methods described on your documentation works since they do not explain how to load the partials, helpers, etc. I've read of a package called ejs-locals, but it's deprecated. I've also been using the ejs.create({ as with hbs.create({ but this makes keystone crash... Is there any solution for this matter? I need it cause I'm planning to use Google Polymer as frontend, and hbs conflicts with the built-in templateBinding... Thanks for your help!

**Comment by chowndown** [comment]
Hi @SuperSpaceZova, 

All that is necessary is for you to switch your rendering engine in your keystone.js file

// Modified web.js to use the ejs-locals custom template engine.
var keystone = require('keystone');
var engine   = require('ejs-locals');
keystone.init({
  ...
  'custom engine': engine,
  'view engine': 'ejs',
  ...
});

[Using other template languages](http://keystonejs.com/docs/getting-started/#routesviews-templates)

**Comment by SuperSpaceZova** [comment]
Ok, I already did this but it doesn't allow us to bind the views with the variables set into the models. How should I do it? Are there other steps that need to be taken? Note that I've used the Keystone yeoman generator to build my instance, selecting hbs as the default template engine. Btw, you have suggested me to use ejs-locals, but I've found out that it's a deprecated and unmantained package, and the examples are given for express 3.0 while I'm using the latest keystone release built on top of express 4.0. Some more examples on how to solve my problem will be appreciated. Thanks again for your help.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
