### ISSUE TITLE
What is the "hooks" method for customising the Admin UI?

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2405]
We are trying to understand how to customise the KeystoneJS admin UI.  There is an example in the demo projects, but not any documentation.  I've been informed that the method used in this example is the 'legacy' method, and that there is a new way of customising the admin UI through hooks.  Can someone point me to documentation of how I would use hooks to do this?  An example?

We are trying to evaluate KeystoneJS for a large project, and it would be helpful if there were better documentation available.

**Comment by wuichen** [comment]
Check the demo projects. I think the blog one has some examples of it

**Comment by Vultraz** [comment]
Preliminary documentation has been added: https://www.keystonejs.com/keystonejs/app-admin-ui/#hooks

**Comment by MadeByMike** [comment]
Demos in the demo project folder and docs are on the website. I'd say this one is solved. Good work team :)
