### ISSUE TITLE
mongoose query mixin graphql

### ISSUE THREAD

**Issue by epubreader** [keystonejs/keystone#2411]
I want to upgrade keystone-classic to keystone5,
I know I need to change mongoose to graphql, but it need a lot of time,
Can I write mongoose query in front-end? and I just using graphql for admin site
can I use mongoose and graphql together?
thanks

**Comment by gautamsi** [comment]
there is no way to do it with v5 features and how the examples are setup. 

if you want to develop your app like v4 with express views, see here - https://github.com/keystonejs-contrib/keystonejs-contrib/tree/master/examples/blog-view
