### ISSUE TITLE
Are underscore methods available on Types.CloudinaryImages?  If so, how do you use them?

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2412]

**Comment by mxstbr** [comment]
There are a bunch of them available, check the `Underscore methods` section of the [`Cloudinary Image` doc](http://keystonejs.com/docs/database/#fieldtypes-cloudinaryimage)!

```
src(options) String - returns the url of the image, accepts all options cloudinary supports

tag(options) String - returns an <img> tag

scale(width, height, options) String - scales the image to fit the exact width and height, retaining aspect ratio

fit(width, height, options) String - scales the image to fit within the specified width and height, retaining aspect ratio

lfit(width, height, options) String - scales the image to fit within the specified width and height, retaining aspect ratio (without exceeding the original dimensions)

limit(width, height, options) String - scales the image (down only) to fit within the specified width and height, retaining aspect ratio

fill(width, height, options) String - scales the image to fill the specified width and height

crop(width, height, options) String - crops the image to fill the specified width and height

pad(width, height, options) String - pads the image to fill the specified width and height

lpad(width, height, options) String - pads the image to fill the specified width and height (without exceeding the original dimensions)

thumbnail(width, height, options) String - crops the image to fill the specified width and height
```

**Comment by emaddoma** [comment]
#oma-signature {
	PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; -webkit-text-size-adjust: none
}
TABLE[id='oma-signature'] {
	PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px; -webkit-text-size-adjust: none
}
#oma-signature A {
	BORDER-TOP: 0px; BORDER-RIGHT: 0px; BORDER-BOTTOM: 0px; COLOR: #a2ad00 !important; TEXT-DECORATION: none; BORDER-LEFT: 0px
}
TABLE[id='oma-signature'] A {
	BORDER-TOP: 0px; BORDER-RIGHT: 0px; BORDER-BOTTOM: 0px; COLOR: #a2ad00 !important; TEXT-DECORATION: none; BORDER-LEFT: 0px
}
#oma-signature IMG {
	BORDER-TOP: medium none; BORDER-RIGHT: medium none; BORDER-BOTTOM: medium none; BORDER-LEFT: medium none
}
TABLE[id='oma-signature'] IMG {
	BORDER-TOP: medium none; BORDER-RIGHT: medium none; BORDER-BOTTOM: medium none; BORDER-LEFT: medium none
}




Um... for CloudinaryImage, yes. For CloudinaryImages, no. I couldn't figure out how to access the methods from the image array. Show me an example and I'll believe you. 

Sent from my iPhone




 










Erik Madsen









Erik.Madsen@offmadisonave.com




Main Line: 

480.505.4500 



Direct Line: 

303-506-0795 










Send large files using 
my secure ShareFile account.









 
 








On Mar 14, 2016, at 9:43 PM, Max Stoiber <notifications@github.com> wrote:




There are a bunch of them available, check the Underscore methods section of the
Cloudinary Image doc!
src(options) String - returns the url of the image, accepts all options cloudinary supports

tag(options) String - returns an <img> tag

scale(width, height, options) String - scales the image to fit the exact width and height, retaining aspect ratio

fit(width, height, options) String - scales the image to fit within the specified width and height, retaining aspect ratio

lfit(width, height, options) String - scales the image to fit within the specified width and height, retaining aspect ratio (without exceeding the original dimensions)

limit(width, height, options) String - scales the image (down only) to fit within the specified width and height, retaining aspect ratio

fill(width, height, options) String - scales the image to fill the specified width and height

crop(width, height, options) String - crops the image to fill the specified width and height

pad(width, height, options) String - pads the image to fill the specified width and height

lpad(width, height, options) String - pads the image to fill the specified width and height (without exceeding the original dimensions)

thumbnail(width, height, options) String - crops the image to fill the specified width and height

**Comment by mxstbr** [comment]
See the `CloudinaryImages` doc:

> "Stores multiple images in a array as a nested Schema, each of which expose the same methods as the cloudinaryimage field."

So you can loop over your `CloudinaryImages` array and call whatever underscore method you want on them:

```JS
yourModel.images.forEach(img => {
  img.crop(200, 200);
});
```

**Comment by jordanyim1** [comment]
Is it possible to have this added to the documentation?  I think it would really help people searching for it.

**Comment by mxstbr** [comment]
We plan on rewriting the documentation for/maybe after the 0.4 release to be more user friendly. Right now it's great if you're developing keystone itself, but not so great if you're using keystone to develop a website.

We plan to change that – if you want to help check out: https://github.com/keystonejs/keystonejs-site

**Comment by KirAndStas** [comment]
So  what ? It is really non understandable how to use it in model. Give at least any docs for read about it.

**Comment by hoanguyen311** [comment]
I still can't use underscore methods for cloudinary images
trying

`                 product.images.forEach(function(img) {
                     console.log(img.tag());
                 });`

**Comment by cantuket** [comment]
'4.0.0-beta.7' Underscore methods aren't working anywhere, including Cloudinary

**Comment by alessandropaglia** [comment]
Image underscore methods aren't working:

*player model*
    
    [...]
    Player.add(
    'test',
    { photos: { type: Types.CloudinaryImages } },
    [...]

*players.twig*

    [...]
    {% for player in data.players.results %}
	  {% include 'player_item.twig' with {p: player} %}
    {% endfor %}
    [...]

*player_item.twig*

    [...]
    <img src="{{ p.photos[0].limit(92,92) }}">
    [...]

**Comment by kamontat** [comment]
@mxstbr Still cannot use underscore method. In keystone version 4.0.0
