### ISSUE TITLE
Back References are throwing an error, refers to a non-existant field

### ISSUE THREAD

**Issue by drobati** [keystonejs/keystone#2412]
# Bug report

## Describe the bug

When using back references with mongodb, an error is being thrown. If I remove the back references, everything runs fine.

```
Error: Price.item refers to a non-existant field, Item.prices
    at Keystone._consolidateRelationships (/node_modules/@keystonejs/keystone/lib/Keystone/index.js:349:13)
    at Keystone.prepare (/node_modules/@keystonejs/keystone/lib/Keystone/index.js:726:10)
    at executeDefaultServer (/node_modules/@keystonejs/keystone/bin/utils.js:112:42)
```

## To Reproduce

For a price
```
  fields: {
    amount: { type: Decimal, isRequired: true },
    item: { type: Relationship, ref: 'Item.prices' },
    unit: { type: Relationship, ref: 'Unit.prices' },
    ...commonFields
  },
```

For a item
```
  fields: {
    name: { type: Text, isRequired: true },
    user: { type: Relationship, ref: 'User' },
    units: { type: Relationship, ref: 'Unit', many: true },
    prices: { type: Relationship, ref: 'Price', many: true },
    ...commonFields
  },
```

## Expected behaviour

I expect it to work as the documentation suggests. I considered migration but I don't believe that to be necessary with MongoDB, I could be wrong here.

## System information

- OS: macOS 10.15.3
- Node: v12.5.0

Packages
```
    "@keystonejs/adapter-mongoose": "^5.0.0",
    "@keystonejs/app-admin-ui": "^5.0.0",
    "@keystonejs/app-graphql": "^5.0.0",
    "@keystonejs/auth-password": "^5.1.0",
    "@keystonejs/keystone": "^5.0.0",
    "cross-env": "^5.2.0"
```

**Comment by liamlevesque** [comment]
@drobati did you find a solution to this? I'm having the same problem

**Comment by EricKit** [comment]
Have you tried this? From the documentation it looks like both sides of the relationship need to specify the subfield.

https://www.keystonejs.com/tutorials/relationships

Changing 'Unit' to 'Unit.item' or whatever the field name is you are Back Referencing.

fields: {
    name: { type: Text, isRequired: true },
    user: { type: Relationship, ref: 'User' },
    units: { type: Relationship, ref: 'Unit.item', many: true },
    prices: { type: Relationship, ref: 'Price.unit', many: true },
    ...commonFields
  },

**Comment by timleslie** [comment]
Hi @drobati,

What you are seeing is actually the intended behaviour. If you are using a two-way relationship then both `Relationship` fields must refer to each other, or else it is in invalid configuration. In your case you want to have:

```javascript
  fields: {
    ...
    unit: { type: Relationship, ref: 'Unit.prices' },
    ...commonFields
  },
...
  fields: {
    ...
    prices: { type: Relationship, ref: 'Price.unit', many: true },
    ...commonFields
  },
```

For more information, please see the new [relationship documentation](https://www.keystonejs.com/discussions/relationships).
