### ISSUE TITLE
Conditional required/noedit attributes

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2420]
There are some use cases where having the `required` and/ or `noedit` options in fields is better served by specifying some expression to evaluate.  That's exactly what dependsOn does.  I propose that we also accept a dependsOn expression as a value for these two options.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/conditional-requirednoedit-attributes!
