### ISSUE TITLE
Wrong autokey value

### ISSUE THREAD

**Issue by promethe42** [keystonejs/keystone#2423]
Hello

I'm trying to use the "autokey" feature to generate slugs for each blog post.
Here's how I do it :

```js
var Post = new keystone.List('Post', {
    autokey: { path: 'slug', from: 'title', unique: true },
    map: { name: 'title' },
    defaultSort: '-createdAt'
});
```

Surprisingly, it works "sometimes".
For example the "Example Of Blog Post" value for the "title" field will have the slug "example-of-blog-post". Sometimes not. It will have the value of the post ID instead.

It's very hard for me to understand how/when the autokey features works as expected. But it looks like the post ID and the autokey (source field) are sometimes mixed up.

How can I help understanding and eventually fixing this?

Regards,

**Comment by promethe42** [comment]
OK I found the problem: you can't save such model if the specified autokey field is missing.
For example this will break the autokey:

```js
Post.model.findById(req.params.id)
	.select('status author')
	.exec(function(err, post)
    {
		post.status = req.params.status;
		post.save(function(err)
		{
                        // post.slug is broken here
			return res.apiResponse({post:post});
		});
	});
```

I'm guessing the autokey feature is trying to update the target field ("slug" in this case) even if it's already set and the source field ("title" in this case) is not set upon every call to `save()`.

The workaround is to make sure the autokey source field is always selected:

```js
Post.model.findById(req.params.id)
	.select('title status author') // don't forget to select the title field !!!
	.exec(function(err, post)
    {
		post.status = req.params.status;
		post.save(function(err)
		{
                        // post.slug is broken here
			return res.apiResponse({post:post});
		});
	});
```

Couldn't we just make sure the autokey is not updated if it's source field is not defined and the target field is already set ?

Thanks,

**Comment by creynders** [comment]
AFAICT [some checking _is_ done](https://github.com/keystonejs/keystone/blob/fff4a9e3e2faf00ba0dc02146682524d0314c9b9/lib/schemaPlugins/autokey.js#L78), but probably not covering every nook and cranny. Feel free to come up with a solution! (We sure could use the help :grin:)

**Comment by geloescht** [comment]
I am willing to implement a fix and submit a pull request. As autokey can be generated from multiple source fields, there are two ways this could be done:
a) only update autokey, if all source fields are present and one of them is modified. Might not regenerate autokey in some cases, where it is desired.
b) update autokey as soon as at least one source field is modified and present. Might not include all source fields if one of them is missing.
If only one source field is specified, a) and b) are equivalent.

**Comment by geloescht** [comment]
Investigated this a bit. The checks work properly, but only if the generated field is also selected. The culprit is the check for a thruthy value in line 94:
```
// if has a value and is unmodified or fixed, don't update it
if ((!modified || autokey.fixed) && this.get(autokey.path)) {
	return next();
}
```
It seems we try to make sure that a value is generated when there is none in the database, but do not take the possibility of selection / projection into account.
Maybe @JedWatson can shed some more light on the purpose of this check.
See #2619 for unit test reproducing this issue.
