### ISSUE TITLE
wysiwyg cloudinary image upload https

### ISSUE THREAD

**Issue by steveellis** [keystonejs/keystone#2427]
Wondering if there is a configuration option for making the inserted image source be https when inserting a cloudinary image using the wysiwyg option (enabled by the 'wysiwyg cloudinary images': true option) for the html data type .

I've tried doing

keystone.set('cloudinary secure', true);

but the inserted url is still http.

Would be super duper great to have this because otherwise would have to train users to view source and add https to every image they upload--something easily forgotten. :)

**Comment by mxstbr** [comment]
That is a good catch, that should probably happen when `cloudinary secure` is true.

**Comment by steveellis** [comment]
Thanks for confirming and for marking it as a bug.
