### ISSUE TITLE
createReadStream is not a function when using cloudinary adapter

### ISSUE THREAD

**Issue by wuichen** [keystonejs/keystone#2428]
# Bug report

trying to upload a image through graphql endpoint but it returns error saying nested graphql error

## Describe the bug

using the meetup example, trying to update my avatar image but returns error from network tab. 
## To Reproduce
1. yarn dev meetup example

## Expected behaviour

Everything else seems to work fine but changing avatar image causes error.

## System information

- OS: macOS
- Browser: Chrome

## Additional context

error from network tab
`{"errors":[{"message":"Nested errors occured","name":"NestedError","time_thrown":"2020-02-24T11:02:25.198Z","data":{"errors":[{"name":"TypeError","message":"createReadStream is not a function","stack":"CloudinaryImage.resolveInput (node_modules/@keystonejs/fields/dist/fields.cjs.js:685:20)\n"}]},"uid":"ck70cqe990006v68kfi9k67cl"}],"data":{"updateUser":null},"extensions":{"tracing":{"version":1,"startTime":"2020-02-24T11:02:25.193Z","endTime":"2020-02-24T11:02:25.197Z","duration":3338910,"execution":{"resolvers":[{"path":["updateUser"],"parentType":"Mutation","fieldName":"updateUser","returnType":"User","startOffset":217704,"duration":3028052}]}}}}
`

**Comment by timleslie** [comment]
I have tried to reproduce this with the latest iteration of the meetup demo and haven't been able to reproduce the error here. I'm going to close this issue, but if you can provide more details and confirm that you are still seeing the issue then please re-open it.
