### ISSUE TITLE
wysiwyg img uploads and embed

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2435]
We're using the option for cloudinary image uploads in wysiwyg fields and though the image displays properly in the editor, the code in the database appears as...

```
<div>
[img]http://res.cloudinary.com/.../.../imagename.png[/img]
</div>
```

We're using Swig as our template engine.  How is this supposed to output properly?

**Comment by kadosh1000** [comment]
I had the same problem with bold text, the output was:

`[b]Text[/b]`


It has nothing to do with the template engine, no template engine will accept that.

**Comment by emaddoma** [comment]
Obviously.  I'm just wondering if there's some undocumented feature in Keystone that perhaps would assist with making it useable.  So I guess image embeds with WYSIWYG editor makes it useless.  Wonderful.

**Comment by lkula** [comment]
Disabling the bbCode plugin fixes it.

**Comment by mxstbr** [comment]
@Ikula thanks for jumping in and helping out!

**Comment by emaddoma** [comment]
@mxstbr May I suggest you remove "bbcode" from your documentation?  :)

**Comment by mxstbr** [comment]
That sounds reasonable - would you like to submit a PR? :+1:
