### ISSUE TITLE
Same example for createItems with Simple and Array Relation Syntax in Docs

### ISSUE THREAD

**Issue by ralexrdz** [keystonejs/keystone#2438]
It seems to me there is a mistake in [Adding initial data](https://github.com/keystonejs/keystone/blob/3abc58831e0f9b5871569a3fa6b21be7dc269cf3/docs/guides/initial-data.md)  

Both examples of Simpla and Array Relation Syntax has the same code.

**Comment by mjomble** [comment]
I just noticed this as well. Seems like in the array relation syntax example, user Barry should also have a `posts` field that contains an array of queries, but there's no such field and the code is identical to the single relation syntax example
