### ISSUE TITLE
Version Control for Document Tracking

### ISSUE THREAD

**Issue by britztopher** [keystonejs/keystone#244]
I dont know if this should be new feature or an enhancement, so I decided to do new feature.  I think it would be beneficial to everyone using the CMS tool if there was some type of versioning.  I see that when mongo saves the document you put a `__v` element, which gives mongo the ability to version documents.  I would like to contribute to this functionality, however, I would need some help understanding why you might not have added versioning or if it already exists.  Let me know what I can do to help.

**Comment by JedWatson** [comment]
Landed! see notes in #264 and #137.
