### ISSUE TITLE
admin page blank on Safari 8 OS X

### ISSUE THREAD

**Issue by nvcken** [keystonejs/keystone#2443]
After login this page is blank
http://demo.keystonejs.com/keystone/posts
It works fine on Chrome
p/s: seem others link blank too http://demo.keystonejs.com/keystone/enquiries

**Comment by mxstbr** [comment]
Are you getting any messages in the console?

**Comment by nvcken** [comment]
```
SyntaxError: Attempted to redefine property 'downloadItems'.
(anonymous function)list.js:5786
list.js:5786
```

**Comment by mxstbr** [comment]
Thanks for reporting this, we managed to replicate it!

> I've opened an issue in the keystone-demo repo: https://github.com/keystonejs/keystone-demo/issues/42 so I'm closing this one
