### ISSUE TITLE
Example: Using Password Compare

### ISSUE THREAD

**Issue by zobione** [keystonejs/keystone#2444]
# Question about Keystone
Hello, I am trying to use keystone as a backend for its simplicity, though there is something that I quite didn't catch. 

When reading the documentation for Password fields it says that it exposes a compare method to check one password against another (https://www.keystonejs.com/keystonejs/fields/src/types/password/#auth-strategies). It also says that once a password has been set up it cannot be retrieved anymore (https://www.keystonejs.com/guides/access-control#example) therefore my question is the following:
How can you use the compare method on the password field if you cannot read the user password ? Can you provide any example using this method this can be usefull.

Thanks

**Comment by Vultraz** [comment]
The `compare()` function there is just a backend wrapper around `bcrypt`:
```js
  compare(candidate, hash, callback) {
    return bcrypt.compare(candidate, hash, callback);
  }
```

The password auth strategy (not to be mixed with the password field) has this check:
```js
    // Ducktype the password field; it needs a comparison function
    if (
      typeof secretFieldInstance.compare !== 'function' ||
      secretFieldInstance.compare.length < 2
    ) {
      throw new Error(
        `Field type specified does not support required functionality.` +
          `The PasswordAuthStrategy for list '${this.listKey}' is using a secretField of '${secretField}'` +
          ` but field type does not provide the required compare() functionality.`
      );
    }
```
 As far as I can see, it's just making sure the password auth strategy is used together with a field (in this case, Password), that implements the necessary `compare` function to check passwords against one another. Theoretically, you could implement a custom field type that used a comparison method other than `bcrypt`.

As for how `bcrypt` does the comparison, that's an implementation detail. I don't know, but for all intents and purpose it doesn't matter.

**Comment by zobione** [comment]
Thanks for your answer, so if I understand correctly it cannot be used in a graphql query to compare an incoming password against an existing password. Am I right ?

Thanks

**Comment by Vultraz** [comment]
Well, you can't query passwords, only if a password is set.

**Comment by molomby** [comment]
> it cannot be used in a graphql query to compare an incoming password against an existing password

This is correct. The only comparison option the password field type adds to the GraphQL schema is a boolean `is_set` field.

As @Vultraz mentioned, behind the scenes the password field is using the [bcrypt algorithm](https://en.wikipedia.org/wiki/Bcrypt), which is a [one-way cryptographic hash function](https://en.wikipedia.org/wiki/Cryptographic_hash_function). This type of function allows candidate passwords to be compared with the "stored" password while ensuring the "stored" password itself can't be retrieved or extracted from the DB. (The password itself is never actually stored, only a derived value called a "hash".)

The comparisons themselves are intentionally resource intensive (ie. they require significant CPU time and memory). This protects against an attacker trying to guess (brute force) individual passwords. It also makes having a comparison _filter_ (eg. at the GraphQL layer) impractical. This is actually a good thing from a security perspective.

> How can you use the compare method on the password field if you cannot read the user password

The password field is generally used in conjunction with the [password auth strategy](/packages/auth-password/README.md) but, if you were building a custom mutation or other server-side functionality, you could access the compare function yourself to do whatever comparisons you want.

**Comment by MadeByMike** [comment]
Thanks Mombly and Vultraz!
