### ISSUE TITLE
Migrating to keystone

### ISSUE THREAD

**Issue by kadosh1000** [keystonejs/keystone#2447]
Hi, I have an old website using MSSQL and I am now starting migrate it all to keystone.
My main issue is the data, I think what would be the best approach to handle its migration.

The first option is to make a script that will generate a json array of documents and then use mongoimport to import all the data.

My second approach is to use the keystone's updates, install some MSSQL ORM and then create my models from there, the thing is that I don't really want to keep holding and installing that ORM after the migration has done. 

The Migration process is going to run only once when going to production.

**Comment by mxstbr** [comment]
I found [this answer on StackOverflow](http://stackoverflow.com/a/25142889) which explains a relatively straightforward process that sounds reasonable.

I'm going to close this issue to keep the issue tracker from becoming full of questions, but if anybody has done this before a comment would be much appreciated I'm sure!
