### ISSUE TITLE
Error patterns and handling: design and document

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#245]
Clear and specific errors can greatly improve the maintainability and usability of a system; the difference between a `request failed` error or message like `Post (ID: 123ASD234) cannot be deleted due to it's state: 'PUBLISHED'` is huge. However, the content of an error needs to be keenly aware of it's audience (developer, admin, end user, etc) and security context.

Errors usually contain details about the inner workings of a system (file paths, software version, internal values, etc) that's critically important for some audiences but should be completely censored for others. Additionally, interfaces are often better places to provide clear, relevant error information than the code from which the error originated. These front ends need to be able to reliably recognise different categories of error and display their own, custom messages.

Basically, there's a great deal to consider. We need a clear, documented strategy (or at least some guidelines) describing:

* The responsibilities of different areas of the system re: errors (ie. is it ok to throw here? Has this error already been logged or should I log it now?)
* Who are the different "error audiences" and how are they bounded by the system (ie. results from GraphQL -vs- `stderr`/`stdout` -vs- Keystone error messages)
* Conventions around how error content for these audiences is referenced (eg. `err.message` -vs- `err.public`?)
* A reliable way of identifying specific error states across the system so interfaces can add their own interpretation (Error codes -vs- error keys? eg. `[passwordAuth:secretMismatch]`)
* What should and shouldn't be logged? Protection of personal info, etc. (eg. passwords/secrets should never be logged or included in error messages. What about email addresses, IP addressed and other personal info? [GDPR makes this a big deal](https://www.ctrl.blog/entry/gdpr-web-server-logs))

Possibly related topics include:

* Error logging react front ends? (eg. something like [Rollbar](https://rollbar.com/error-tracking/javascript)?)
* Warnings and other debug
   - What should Keystone warn about on init? (`stderr` or `stdout`?)
   - What are the convention for debug (are we using the [debug package](https://www.npmjs.com/package/debug) throughout? how are messages scoped?)
* Other things..?

**Comment by molomby** [comment]
@MadeByMike Hey I've removed the `good first issue` label -- this is a ticket about designing and documenting broad-reaching architectural patterns in Keystone. Whoever takes this on is going to need a deep understanding of Keystone and systems development generally.

**Comment by MadeByMike** [comment]
That was probably a mistake.
