### ISSUE TITLE
Move bundled TinyMCE dependency to npm

### ISSUE THREAD

**Issue by mxstbr** [keystonejs/keystone#2456]
Ref: https://github.com/keystonejs/keystone/pull/2455#issuecomment-198218775

> We vendor it in because there's a customised theme file included. we're cautious about updates for the same reason - any breaking change to their stylesheet "api" needs to be tested. TinyMCE is also finnicky about where it's served from due to the way they load plugins and other assets after the page has loaded. I haven't checked recently though, so this may not be a concern anymore.
> 
> If we can vendor in any of our currently bundled dependencies with npm and use them as commonjs modules, I'm down with that.

**Comment by JedWatson** [comment]
@mxstbr I'm not sure we actually want to track this as an issue. It's "nice to have" at best, and dependent on structural issues with TinyMCE that are beyond our control as far as I can tell.

**Comment by josephg** [comment]
As far as I can tell there's nothing stopping you bumping it out into its own npm module. `npm publish @keystone/tinymce`.

**Comment by gautamsi** [comment]
Closed by #4897 
repo for this is at [keystonejs/keystone-tinymce](https://github.com/keystonejs/keystone-tinymce)
npm is published as [keystone-tinymce](https://www.npmjs.com/package/keystone-tinymce/)
