### ISSUE TITLE
CloudinaryImage error field.folder is not a function

### ISSUE THREAD

**Issue by programmer4web** [keystonejs/keystone#2457]
After updating keystonejs version I get:
Error thrown for request: /keystone/
field.folder is not a function at model.schemaMethods.folder (\keystone\fields\types\cloudinaryimage\CloudinaryImageType.js:179:17)

In keystone init I have 'cloudinary folders' : true,
I don't have an folder on models fields as the folders are automatically created, this used to work.

**Comment by mxstbr** [comment]
Is that a `0.3.x` version or are you using `0.4.0-alpha`?

**Comment by programmer4web** [comment]
updated package.json with git+https://github.com/keystonejs/keystone.git solved the problem thanks.
