### ISSUE TITLE
Inconsistent implementation of field notes

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#246]
With some recently added field types, and the move to parsing field nodes with markdown, the implementations have become inconsistent.

Problems include:

- Notes for checkboxes are escaped, and when unescaped the parsed markdown causes a line break after the &mdash; prefix
- Notes aren't displayed for AzureFile fields
- Code fields escape notes

It needs a review across all field types, and the markdown parsing should possible be made optional, so as at least not to mess with the checkbox display by default.

**Comment by mxstbr** [comment]
We've reworked the field types, so I'll close this for now. If this issue still persists for you, feel free to comment again!
