### ISSUE TITLE
Heroku Excessive Memory Usage

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2460]
We've got two applications in production using Keystone that have been experiencing major memory usage errors.  I've done quite a bit of analysis and it seems that there is something about/in the AdminUI and/or it's routes that is causing this.  We have thrown load testing bots at every publicly accessible URL in the application and seen memory usage behave appropriately.  When our customers use the Admin UI, the memory usage climbs to 1.5GB and fails to release, exceeding the quota and causing Heroku to throttle the server.

For reference, here are the URLs...

http://www.nikegrind.com
http://www.dmshealth.com

**Comment by morenoh149** [comment]
related https://github.com/keystonejs/keystone/issues/1700 it's a known issue. Try generating a flamegraph. I've been thinking about this for a while and tried graphing out keystone's dependencies.

**Comment by mxstbr** [comment]
I'll close this as a duplicate

**Comment by emaddoma** [comment]
I would have to say it's more than a little concerning that an issue so critical hasn't been dealt with.  Is there anything we can do to help?

**Comment by mxstbr** [comment]
Yes!! We would love to fix this issue, we just haven't had the time/didn't know where to start. If you could do an in-depth performance analysis and find out where the memory leak is that'd be absolutely amazing!

**Comment by webteckie** [comment]
@emaddoma I wonder if you can instrument your app as detailed at http://www.nearform.com/nodecrunch/self-detect-memory-leak-node/  seems like some nice tooling for node apps memory leak detection.
