### ISSUE TITLE
is it possible to create a CloudinaryImage object programatically?

### ISSUE THREAD

**Issue by bearprada** [keystonejs/keystone#2468]
I write a script to migrate the data from MySQL to Keystone.js. but I want to migrate the image file from the local file into Cloudinary Image also.

is it any suggestion for it? I don't want to manually upload all of the images by myself.

**Comment by ctaepper** [comment]
if you write a a migration script, you can use the various cloudinary libraries to upload the image and save the result into your migrated data.

**Comment by mxstbr** [comment]
There are [a bunch of libraries and integrations](https://support.cloudinary.com/hc/en-us/categories/200477762-Client-Libraries-and-Integrations) for it, I'd start by checking there as @ctaepper said!
