### ISSUE TITLE
Feature Request: Mailing Lists

### ISSUE THREAD

**Issue by jdarling** [keystonejs/keystone#247]
Since Mandrill is already supported in Keystone and so is HTML input and contact lists, why not make a simple admin interface for creating, queuing, and sending HTML emails?

**Comment by thoughtpalette** [comment]
+1

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/feature-request-mailing-lists
