### ISSUE TITLE
[AdminUI] VirtualField: Cannot access 'value' before initialization

### ISSUE THREAD

**Issue by cozawariat** [keystonejs/keystone#2470]
# Bug report

## Describe the bug

cant get Virtual field to work :confused:
`Uncaught ReferenceError: Cannot access 'value' before initialization`
`The above error occurred in the <VirtualField> component`

my setup is simple:

```
fields: {
      firstName: {
        type: Text,
        isRequired: true
      },
      lastName: {
        type: Text,
        isRequired: true
      },
      fullName: {
        type: Virtual,
        resolver: item => (`${item.firstName} ${item.lastName}`)
      }
}
```

## To Reproduce

The error occurs when i am trying to edit existing record in Admin UI

## Expected behaviour

Edit form should be opened

## System information

- Windows 10
- Chrome

**Comment by Vultraz** [comment]
Are you using the latest `@keystonejs/fields` package? This sounds like what was fixed in bd4096ee86f7790c76db23090b38f880e5aa7ecc.
