### ISSUE TITLE
manage environments

### ISSUE THREAD

**Issue by kadosh1000** [keystonejs/keystone#2470]
Hi, I would like to know what would be the best way to manage my environmental variables.
Mainly the mongoDb connection string.

**Comment by morenoh149** [comment]
typically https://www.npmjs.com/package/dotenv

**Comment by mxstbr** [comment]
Yep, `dotenv` is the most popular solution to this. Typically one then sets/checks `NODE_ENV`, which would be `production` or not. See [this tutorial](https://medium.com/@rafaelvidaurre/managing-environment-variables-in-node-js-2cb45a55195f#.l43ej15u6) for more information.
