### ISSUE TITLE
byTracking plugin causes webpack error

### ISSUE THREAD

**Issue by chomamateusz** [keystonejs/keystone#2472]
# Bug report

## Describe the bug

A webpack error is thrown when I create new list with `byTracking` plugin. Without this plugin there is no error.

It seems like .ts type definition is in .js file, and there should not be, in line 102 of file:
`@keystonejs/list-plugins/node_modules/@keystonejs/app-admin-ui/client/components/ListTable.js`

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Init users and auth sample project
2. Add new list with byTracking plugin:

```javascript
const { atTracking, byTracking } = require('@keystonejs/list-plugins');
const { Text } = require('@keystonejs/fields');

// ... keystone int etc.

keystone.createList('Lesson',{
  fields: {
    name: { type: Text },
  },
  plugins: [
    atTracking(),
    byTracking(),
  ],
});

// ... module exports

```
3. Run app.
4. See error after admin login.

## Expected behaviour

No error.

## Screenshots

![admin-error](https://user-images.githubusercontent.com/20150525/75785980-de8b3800-5d64-11ea-9e1e-904db0e7e035.png)
![code-error](https://user-images.githubusercontent.com/20150525/75785992-e1862880-5d64-11ea-8863-5c1e03528269.png)

## System information

- OS: Pop_OS! (Ubuntu)
- Browser: Chrome

**Comment by Vultraz** [comment]
Can you confirm removing the TS definition fixes the problem? I can't repoduce this.

**Comment by chomamateusz** [comment]
No, it does not resolve the problem.

The "unexpected token" moves to next non-standard JS line the class property `onClick = `. When I move it to standard JS constructor  the "unexpected token" moves to JSX. So it seems like this file was not transpiled??

**Comment by Vultraz** [comment]
Hmmmmm 🤔 That's odd... Again, I can't repro it on my end, so I'm not sure what to do.

**Comment by chomamateusz** [comment]
@Vultraz I've created new fresh repo form starter template, added "Lesson" as described above and same issue. 

Here is the repo - https://github.com/chomamateusz/keystone-issue-2472

Just:

```
npm install
npm run dev
```

Login as admin and see this error.

By the way:

```
node --version
v13.2.0
```

**Comment by Vultraz** [comment]
I still can't repro :( Only difference is I used `yarn` instead of `npm install` since I kept getting this error when using the former: `npm ERR! cb() never called!`. Could you see if using `yarn` yourself makes any difference? It would be weird, who knows 😬

**Comment by chomamateusz** [comment]
WAAAAAT? It works! I've done it twice because I did not believe it!

So with `npm` the error stands and with `yarn` there is no error! Both in this test project above and the production project where I first fond this error!

@Vultraz can you try with `npm`? We will see if the problem is in `npm` itself or maybe it is on my machine only.

**Comment by Vultraz** [comment]
I tried running `npm install` twice earlier and both times I got that `cb() never called` error. Not sure how to get past that here. Guess `npm` is messing with both of us today!

**Comment by chomamateusz** [comment]
Are you using same node version as I? `v13.2.0`

**Comment by Vultraz** [comment]
I'm using Node 13.7.0, npm 6.14.1, yarn 1.22.0.

**Comment by lucatk** [comment]
Issue happening for me aswell.
Using these versions:
- Node v10.18.0
- yarn 1.22.4
- @keystonejs/keystone 5.6.0
- @keystonejs/app-admin-ui 5.9.0
- @keystonejs/list-plugins 5.1.1

**Comment by Vultraz** [comment]
Well, that's... odd 🤔 I really don't know what could cause that.

**Comment by thekevinbrown** [comment]
Issue happens with me using npm as well.

My suspicion is that NPM is installing a set of versions that aren't actually compatible with each other, while Yarn manages to resolve versions differently.

My fix (still using NPM) was to delete `package-lock.json` then `npm i` which fixed it. Haven't done more digging to see what set of versions is not compatible that NPM resolves to which Yarn avoids.

**Comment by ahmedjahmi** [comment]
@thekevinbrown Having this issue now, considering trying this method out. Any new discoveries?

**Comment by gautamsi** [comment]
get latest version if you have stale version.

**Comment by jackhkmatthews** [comment]
I've also ran into this issue.

@gautams
> get latest version if you have stale version.

Do you mean the latest version of npm?

**Comment by gautamsi** [comment]
I meant use the latest version of this plugin.

**Comment by jackhkmatthews** [comment]
Thanks @gautamsi!

I installed `@keystonejs/list-plugins` `v7.1.0` but still get the `Module parse failed: Unexpected token` error.

Would you mind sharing which keystone package versions you are using?

**Comment by gautamsi** [comment]
```json
    "@keystonejs/adapter-mongoose": "^9.0.1",
    "@keystonejs/app-admin-ui": "^7.3.0",
    "@keystonejs/app-graphql": "^6.1.0",
    "@keystonejs/app-static": "^5.1.2",
    "@keystonejs/auth-password": "^5.1.13",
    "@keystonejs/fields": "^16.0.0",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.3.5",
    "@keystonejs/file-adapters": "^7.0.3",
    "@keystonejs/keystone": "^13.1.0",
    "@keystonejs/list-plugins": "^7.0.5",
    "@keystonejs/server-side-graphql-client": "^1.1.1",
    "connect-mongo": "^3.2.0",
    "cross-env": "^7.0.0",
    "dotenv": "^8.2.0",
    "esm": "^3.2.25",
    "express-session": "^1.17.1",
    "firebase-admin": "^9.1.1",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.5.0"
```

**Comment by jackhkmatthews** [comment]
Thanks @gautamsi 

I manage to resolve this yesterday by updating all of my keystone dependencies:

```
    "@keystonejs/adapter-knex": "^11.0.3",
    "@keystonejs/app-graphql": "^6.1.1",
    "@keystonejs/app-next": "^5.2.2",
    "@keystonejs/auth-password": "^5.1.14",
    "@keystonejs/email": "^5.1.6",
    "@keystonejs/keystone": "^14.0.1",
    "@keystonejs/list-plugins": "^7.1.0",
    "@keystonejs/server-side-graphql-client": "^1.1.1",
```

**Comment by thekevinbrown** [comment]
#2606 strikes again. :-)

**Comment by timleslie** [comment]
Closing as the original issue appears to have been resolved.
