### ISSUE TITLE
Bug with Grappling Hook

### ISSUE THREAD

**Issue by terenzeyuen** [keystonejs/keystone#2477]
I've noticed a small coding bug in grappling hook module which causes keystone failed to run. Not sure where to report this but here you go:

https://github.com/keystonejs/grappling-hook/blob/greenkeeper-lodash-4.0.0/index.js#L498

The "this" will reference the object in the loop, therefore losing the reference to this.__grappling. Perhaps should have a **var self = this** before the loop starts?

**Comment by mxstbr** [comment]
Could you submit this in the grappling hook repo? Thanks! 

Also, where and how does this bug come into effect, is there a replicateable problem?

**Comment by terenzeyuen** [comment]
It's for 0.4 Keystone, latest master branch. Have i reported at wrong place?

**Comment by mxstbr** [comment]
No this was absolutely fine, thank you so much for notifying us of this problem! We'd just like to keep the issues as clean as possible and since this is a bug that needs to be fixed in grappling hook, it makes more sense for this to be submitted over there.

**Comment by terenzeyuen** [comment]
Make sense :+1:

**Comment by creynders** [comment]
@terenzeyuen KS uses grappling-hook v3 which uses lodash v3.x, i.e. it _does_ accept a `context` parameter in the iterator functions, so that shouldn't be the problem...
