### ISSUE TITLE
Why the AdminUI supports only email/pass auth strategy?

### ISSUE THREAD

**Issue by chomamateusz** [keystonejs/keystone#2480]
I've added 2 auth strategies: Google and FB, with redirects URL `/auth/google` and `/auth/fb`. 

Next I've forked the AdminUI, and I've added 2 regular buttons with href to URLs mentioned above.

![FBandGoogleLogin](https://user-images.githubusercontent.com/20150525/75907281-53836e00-5e48-11ea-9f19-b51874653ac1.png)

Why this is not allowed by `new AdminUIApp` constructor? Only thing that UI needs in OAuth auth is the redirect URL for each method (and maybe button props) and it could simply generate this buttons for me.

I've not battle tested it yet, but for now as I'm testing Keystone possibilities, it works like a charm - I can log is through FB and Google.

Is that more complicated than I think? Or simply no one implemented it yet?

**Comment by jesstelford** [comment]
> Why this is not allowed by new AdminUIApp constructor?

We literally just haven't gotten to it yet 😉

Would love to see a PR with some of these enhancements.

One thing to consider is; not every app will want every authentication method. And there may be apps which use a non-core authentication method (for example; I have a custom library which does a hacky passwordless thing that's WIP right now, maybe I want to be able to plug that straight into the Admin UI too).

**Comment by dimaip** [comment]
Does anyone know if this is still the issue for Keystone-next or if its admin supports more auth methods now?

**Comment by dcousens** [comment]
Please see our discussions on this topic, https://github.com/keystonejs/keystone/discussions?discussions_q=is%3Aopen+authentication and for specific feature requests
