### ISSUE TITLE
Problems with static app and LocalFileAdapter

### ISSUE THREAD

**Issue by bertez** [keystonejs/keystone#2481]
# ~~Bug~~ report

## Describe the ~~bug~~

I have a keystone app with a StaticApp configured to serve files located on the public folder on the root of my project:

```js
new StaticApp({ path: '/public', src: 'public' })
```

and a LocalFileAdapter configured to store files on a subdirectory of the static app path:

```js
const fileAdapter = new LocalFileAdapter({
  src: 'public/uploads',
  path: '/public/uploads'
});
```

This setup works fine on development mode but in production mode when the app is built the contents of the root public folder are copied to `dist/public` and thats the folder served by the keystone server... so when a file is uploaded using the admin UI it goes through the LocalFileAdapter to the `public` folder on the root of my project so I get a 404 when I try to access the file using the public path URL because the file does not exist in `dist/public`. 

## To Reproduce

Explained above.

## System information

- OS: macOS and Linux
- Browser: any

**Comment by bertez** [comment]
I've checked the app-static package and it seems that this is the expected behaviour and not a bug:

https://github.com/keystonejs/keystone/blob/faa57f3d102df8797e18a716b0efe4f99c5b8831/packages/app-static/index.js#L26

So my question is... what's the right way to config the LocalFileAdapter? 

- Saving the files on a directory outside the static app src?
- Saving the files on the dist directory? (in this case I understand the files will be overwritten on the next build)

btw, I'm using docker and I need this folder to persist between docker restars so it must be mapped to a local volume

Thanks in advance!

**Comment by bertez** [comment]
Related issue: https://github.com/keystonejs/keystone/issues/1823

**Comment by Vultraz** [comment]
What happens if you use `src` with a relative path? Ie, `'./public/uploads'?

**Comment by bertez** [comment]
It's the same... I understand the behavior of the Static App is correct and I finally set up the local file adapter to save the files in a different folder and set up nginx in production to serve that folder as static content.

While in development I use express.static:

```js
module.exports = {
  keystone,
  apps,
  configureExpress: app => {
    app.set('trust proxy', 1);
    isDev && app.use('/uploads', express.static('uploads'));
  }
};
```

Maybe there is a better way but for the time being this works for me.

**Comment by HostenMarijn** [comment]
Hey, 

Does the file adapter throw weird error responses on your nginx server?

Mine goes like this when I try to upload an image (works fine on localhost/development):
![Screenshot 2021-01-12 at 11 27 57](https://user-images.githubusercontent.com/30017922/104302628-510e8d80-54c9-11eb-899f-8502148ae46d.png)

And the image isn't uploaded to the webserver. File permissions are 755 across the board...

Thanks for any feedback
