### ISSUE TITLE
Keystone.js not loading css

### ISSUE THREAD

**Issue by sachingill** [keystonejs/keystone#2485]
I tried "deploy to Heroku"  as well as "keystone-generator" on my local machine. Deployment was fine but when i tried to perform signup, css files were not loaded. I chose sass deployment in my local.Is it a know issue and how to resolve this issue.

**Comment by mxstbr** [comment]
The solution is to change one of the  `.scss` files to trigger compilation. See here for more information: https://github.com/nodejs/nodejs.org/issues/581#issuecomment-199547398
