### ISSUE TITLE
Advanced use of the relationship field type

### ISSUE THREAD

**Issue by gRoberts84** [keystonejs/keystone#2486]
Hey all,

I'm trying to work out how to best utilise the relationship field type to fit my needs and I feel I'm probably missing something inherently obvious.

**Question 1:**

    Category.add({
        title: { type: String, initial: true, required: true, index: true },
        parent: { type: Types.Relationship, ref: 'Category', initial: true }
    });

So, from the above, you can see I've created a `Category` model that references it self to create a simple parent/child relationship.

Can I exclude the current item from the dropdown to prevent a circular reference? Also, is there anyway to reflect the parent/child relationship within the dropdown, i.e. indenting?

**Question 2:**

I have a one-to-many relationship that references the `Category` model above, which works lovely, however I need to find a way of adding an additional field that marks one of the related categories as the primary category.

I presume the only way is to add another relationship dropdown to select the primary category but this will include all of the categories and not just the ones selected.

Thanks

Gav

**Comment by mxstbr** [comment]
I'm about 90% sure we don't support self-referencing relationships at the moment, so you'll have to use workarounds to make this happen. We'll look into adding it in the future!
