### ISSUE TITLE
Add support for nodemailer

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#250]
Nodemailer looks great - http://www.nodemailer.com

Would be nice to integrate it as an alternative to Mandrill for sending emails.

**Comment by pentode** [comment]
+1

**Comment by LorbusChris** [comment]
+1

**Comment by JedWatson** [comment]
Much more relevant now that mandrill has dropped its free tier... I'm focused on our new API and getting the elemental rebuild out so if anyone would like to step up and work on this in the short term that would be great.

**Comment by bergos** [comment]
I've implemented basic Nodemailer support in this [module](https://github.com/bgag/keystone-nodemailer). It does keystone message object to Nodemailer object mapping. Because of the missing documentation I'm not sure how the output mapping should look like. Feel free to use and fork this code or even integrate it into keystone.

**Comment by wuhaixing** [comment]
@bergos Thank you very much!

**Comment by bergos** [comment]
@wuhaixing It's designed as an optional module for keystone. I'm not sure if it should be part of the keystone package by default (even just as a dependency). It would also require a possibility in keystone to configure the mailer module. At the moment keystone-nodemailer replaces `keystone.Email.prototype.send`. I would propose something like that: `keystone.set('email mailer', 'keystone-nodemailer');`. Than keystone could dynamically require the defined module.

**Comment by morenoh149** [comment]
@JedWatson should https://github.com/bgag/keystone-nodemailer be integrated? otherwise I think this issue can be closed

**Comment by danielmahon** [comment]
I like the idea of nodemailer, and maybe including a rather detailed setup for ONE easy transport like gmail by default, direct others to nodemailer for info

**Comment by w01fgang** [comment]
Is there any news about nodemailer support? 
We have time until April 27, 2016 on mandrill mailing service.

**Comment by w01fgang** [comment]
I have tried [keystone-nodemailer](https://github.com/bgag/keystone-nodemailer) with [nodemailer-mailgun-transport](https://github.com/orliesaurus/nodemailer-mailgun-transport)
works but not inlines css, Mailgin recommends to use  [node-premailer](https://github.com/JedWatson/node-premailer) by @JedWatson :)
can we integate it with keystonejs?

**Comment by mxstbr** [comment]
Definitely high up on our feature list, since Mandrill shut down, but I'm in the middle of #2566 at the moment. Do you want to take a look at starting this off?

**Comment by w01fgang** [comment]
I have started to learn programming about a year ago, because I have changed the country of living.
I really want to help, but for now it's too hard for me, sorry.

**Comment by crawft** [comment]
MailChimp are recommending SparkPost as a Mandrill alternative, they are committed to a free tier https://www.sparkpost.com/mandrill-migration-guide

**Comment by w01fgang** [comment]
keystone-nodemailer with nodemailer-mailgun-transport sends emails, but doesn't sends attacments.
First bug in keystone-nodemailer: the array of attachments passed to send function before `Array.map` finished, because of synchronous.
And the second bug with attachments is in nodemailer-mailgun-transport, in Mailgun logs `attachments` is an empty array.
In the sparkpost api I don't see any attachments support.

**Comment by w01fgang** [comment]
@mxstbr please, can you take a look at #2698 
I was integrated it in my projects, works well.

**Comment by ddaddy** [comment]
I see it was suggested a year ago to add node mailer support. Did this get implemented?
I can add the `keystone-nodemailer` package, but don't see how to configure it and the comments above say it is buggy.

**Comment by bergos** [comment]
There are some PR for keystone-nodemailer and I have a patch for text mail support. I will merge the stuff next week.

An official interface in keystone would be nice. Replacing `keystone.Email.prototype.send` is a ugly hack.

**Comment by ddaddy** [comment]
Thanks. So in it's current form is there nowhere to set say `SMTP` details?

**Comment by bergos** [comment]
The nodemailer options can be configured using the keystone property `email nodemailer`. The value/object is used in the `nodemailer.createTransport` [call](https://github.com/bgag/keystone-nodemailer/blob/master/index.js#L21).

**Comment by ddaddy** [comment]
Sorry I missed that. Got it working thanks :)

**Comment by yieme** [comment]
+1 for keystone-nodemailer and mailgun :-)

**Comment by JedWatson** [comment]
See https://github.com/keystonejs/keystone-email - this is nearly complete, would love some review and testing. I'm planning to replace `keystone.Email` in 0.4 with this

**Comment by mxstbr** [comment]
Closing as no longer relevant with `keystone-email`.
