### ISSUE TITLE
Add browserify CLI npm script and remove gulp

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#2500]
We really don't need gulp just to browserify + uglify our common packages for the Admin UI.

If someone can take our last remaining gulp task `build-packages` and rewrite it as an npm script that would be great. There are two tasks: build for production (with `NODE_ENV=production`, strips warnings etc. from React, and minifies the build) and build for dev (with source maps, debug flags, etc) that need to be replicated.

**Comment by cameronjroe** [comment]
Thoughts on using webpack for the build? It has a number of benefits in regards to bundling/optimization.

**Comment by JedWatson** [comment]
@cameronjroe I'm definitely open to that but we'd need to replace the custom browserify middleware we have too, which is probably worth another issue to discuss. It currently handles some things I'm not sure how to do effectively with Webpack (possibly due to inexperience) including the ability to build from generated JS code at runtime (which we'll need for supporting custom field types).

Seems simpler to use the same system for the prebuilt packages and the dynamic admin bundle so until then we'd stick with Browserify (or not? reasons?)

Ultimately a webpack setup would be great, hot reloading for dev alone would be worth it.

**Comment by cameronjroe** [comment]
Cool, yeah webpack has has a number of [loaders](https://webpack.github.io/docs/list-of-loaders.html) that help for bundling. There's also [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) that could be used in node for dev purposes. If it's just client-side code being bundled though, you probably would want to serve that up statically no? What I do see out there is plenty of isomorphic [webpack configurations](https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/webpack/prod.config.js) that help with the static builds. It's not too bad once you see how the configuration works.

**Comment by JedWatson** [comment]
It's just client-side code being bundled at the moment, I don't see isomorphic/universal rendering being a great advantage for the Admin UI. At least, it's not a near-term target.

I've used webpack for other projects but to summarise the current requirements for Keystone that I haven't worked out with it yet:

- Common bundles (React, Elemental, etc) get pre bundled (and minified, etc) to keep launch time fast - this file gets committed into the repo and rebuilt when npm packages are updated, which is kind of unfortunate but ultimately better for users
- The rest of the Admin UI JS needs to be bundled at project runtime from a dynamic template so only Field types actually used by Lists, and including custom field types from npm, and plugins down the track, are included
- The HTML for the Admin UI needs to be built at runtime so we can generate the `Keystone` global, which includes list definitions, and some other data

If someone can hit those targets with webpack in a PR, I'd be very happy to use it.

**Comment by JedWatson** [comment]
ping @nkbt for thoughts

**Comment by nkbt** [comment]
I am always super happy when gulp is removed :). 

Will check pr too bit later today. I'm in Thailand this week so my internet outside oh hotel is too imperfect.

**Comment by nkbt** [comment]
Ah it is not a PR. So yes we are good with this one. might be a bit complicated for beginners, though super good experience. 

Ping @butenkome

**Comment by suryagh** [comment]
@JedWatson I was looking into this issue and had a question: 

Do you know if the `"release": "gulp release" -- ` inside the `package.json` -- is needed anymore. I could not find any definition for the `gulp release` inside the `keystone` repo.

https://github.com/keystonejs/keystone/blob/master/package.json#L145

**Comment by mxstbr** [comment]
@suryagh that npm script definitely isn't needed anymore – Jed just removed the gulp release task [18 days ago](https://github.com/keystonejs/keystone/commit/9fce1ce8cfad6bfcd8f441f7ff412302918ff5b5#diff-b9e12334e9eafd8341a6107dd98510c9) so we can get rid of the npm script!

**Comment by JedWatson** [comment]
Thanks for catching that @suryagh!

I've just pushed a change that removes that script.

Something else relevant to this; the packages build needs to `require` the packages listed in `admin/client/packages.js`, which I suspect rules out pure CLI syntax, and which means I mis-spec'd this task.

I still don't think there's value in using gulp, which is quite heavy, but we might need to use the JS API for browserify (and babel, etc) so we can read the common packages array and loop over them, building up the options for browserify.

If that approach works, and is simpler, maybe it could go in a `build.js` file in the root folder, replacing `gulpfile.js`

**Comment by JedWatson** [comment]
Implemented by #2669 with thanks to @suryagh!
