### ISSUE TITLE
Docs homepage design tweaks

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2501]
See: https://github.com/keystonejs/keystone/pull/2475

@jordanoverbye did an excellent overhaul of the docs homepage which does a much better job of giving new users a jumping off point.

I think the wording on the homepage could be tweaked to be less generic and also more compelling for our target audience:

<img width="574" alt="Screen Shot 2020-03-10 at 10 26 11 am" src="https://user-images.githubusercontent.com/612020/76268622-be0e3100-62c2-11ea-9023-771dadfbf1c1.png">

There are a couple of things we could improve:

- Remove the "Wall of text" effect of the large header + long paragraph
- Aim for a "6 word" version which conveys as much meaning as possible
- Remove vague phrases such as "platform", "extensible", and "applications"
- Remove some of the buzz words
- Ensure the heading and the paragraph compliment eachother rather than restating
- Target our audience better. We're not for "All NodeJS application developers", we're for "Frontend devs who need a backend"

Random brainstormed ideas:

---

> **Headless GraphQL API framework for Node**

> Configure your data model in JavaScript, and KeystoneJS will generate a powerful GraphQL API + Admin UI.

---

> **For frontend devs who need a GraphQL backend**

> Configured in plain old JavaScript, KeytoneJS will auto generate a powerful GraphQL API + Admin UI in just minutes.

---

> **BYOF`*` GraphQL CMS for Frontend Devs**

> KeystoneJS auto generates your GraphQL API + Admin UI from plain old JavaScript so you can get back to building your product sooner. As your product matures, KeystoneJS is right there for you with multiple extensibility options and a strong community of passionate developers just like you.

> _`*`BYOF: Bring Your Own Frontend_

**Comment by Vultraz** [comment]
Out of the three options I like the last best.

**Comment by jahlherapath** [comment]
I like option one straight to the point and you know exactly what it is.
