### ISSUE TITLE
Misleading documentation for 'resolveInput' for field hooks?

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2508]
The [documentation](https://www.keystonejs.com/api/hooks#resolveinput) for `resolveInput` for field hooks seems a bit misleading.  When it says

> The return of resolveInput can be a Promise or an Object. It should resolve to the same structure as the resolvedData. The result is passed to the next function in the execution order.

and gives as an example

```
const resolveInput = ({
  operation,
  existingItem,
  originalInput,
  resolvedData,
  context,
  actions,
}) => {
  // Input resolution logic
  // Object returned is used in place of resolvedData
  return resolvedData;
};
```

instead it would seem that you can't return `resolvedData` but rather the _field_ inside `resolvedData` for which you're writing a hook.  For instance, in my `Article` list I had this field

```
text: {
                type: Wysiwyg,
                hooks: {
                    async resolveInput({ originalInput,resolvedData }) {
                        console.log('resolvedData');
                        console.log(resolvedData);
                        return resolvedData;
                    }
                }
```

but on saving the `Article` I kept getting this error within the AdminUI

```
GraphQLError
Cast to string failed for value "{ text: '<p><img src="static/blop.jpg" alt="" width="580" height="388" /><img src="static/blop.jpg" alt="" /></p>' }" at path "text"
```

The same thing happened when I used the `resolveInput` hook on another field, 
```

title: {
				type: Text, schemaDoc: 'Title for published article',
                hooks: {
                    async resolveInput({ originalInput,resolvedData }) {
                        console.log('resolvedData');
                        console.log(resolvedData);
                        return resolvedData;
                    }
			}
```

thus it wasn't unique to the`Wysiwyg` field type.

The solution was not to return `resolvedData`, but `resolvedData.text` (or `resolvedData.title`, respectively).

I think the docs should be changed, since the example at least doesn't make it clear what one should do.

**Comment by msalahat** [comment]
Thank you!

You saved my day!
