### ISSUE TITLE
Field hook 'resolveInput' throws GraphQL error when returning 'resolvedData'

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2509]
Edit:  I believe the answer is that one _does not_ return the entire `resolvedData` object, but instead the _field_ on that object whose hook you are in.  Thus, in the case below, one would return `resolvedData.text` (or `resolvedData.title`).  I believe the docs could be improved, since it would seem that one returns the entire `resolvedData` object.
----------
The [documentation](https://www.keystonejs.com/api/hooks#resolveinput) for `resolveInput` says

> The return of resolveInput can be a Promise or an Object. It should resolve to the same structure as the resolvedData. The result is passed to the next function in the execution order.

and gives as an example

```
const resolveInput = ({
  operation,
  existingItem,
  originalInput,
  resolvedData,
  context,
  actions,
}) => {
  // Input resolution logic
  // Object returned is used in place of resolvedData
  return resolvedData;
};
```

In my `Article` list I have this field

```
text: {
                type: Wysiwyg,
                hooks: {
                    async resolveInput({ originalInput,resolvedData }) {
                        console.log('resolvedData');
                        console.log(resolvedData);
                        return resolvedData;
                    }
                }
```

but on saving the `Article` I get this error within the AdminUI

```
GraphQLError
Cast to string failed for value "{ text: '<p><img src="static/blop.jpg" alt="" width="580" height="388" /><img src="static/blop.jpg" alt="" /></p>' }" at path "text"
```

The same thing happens when I use the `resolveInput` hook on another field, 
```

title: {
				type: Text, schemaDoc: 'Title for published article',
                hooks: {
                    async resolveInput({ originalInput,resolvedData }) {
                        console.log('resolvedData');
                        console.log(resolvedData);
                        return resolvedData;
                    }
			}
```

thus it isn't unique to the`Wysiwyg` field type.

If I return a text string inside of the object, there is no complaint, but the `validateInput` hook is never reached.

**Comment by Vultraz** [comment]
Yes, you return the field you want in the `resolvedData` object.
