### ISSUE TITLE
Date Selector stolen one day after save

### ISSUE THREAD

**Issue by wuhaixing** [keystonejs/keystone#2509]
keystone "version": "0.4.0-alpha", "react-day-picker": "1.2.0", Safari 9.0.2 (11601.3.9) 

After save the model in admin panel,the date will be changed.For example,I set the player's birth to 2000-01-31,every time I click save button,the birth will forward one day,became 2000-01-30,2000-01-29...

**Comment by mxstbr** [comment]
Is your server by chance in a different timezone from the machine you're accessing the website from?

**Comment by wuhaixing** [comment]
Nope,and this problem not happen when I use chrome.

**Comment by mxstbr** [comment]
I just tried this with the current master branch (and Safari 9.0.2), and this bug doesn't seem to exist anymore:

![datetime-bug](https://cloud.githubusercontent.com/assets/7525670/14197843/ee23b616-f81e-11e5-8e6a-838f63cfd64d.gif)

Thanks for reporting this!

**Comment by wuhaixing** [comment]
Sorry,I still got the error in Safari & Firefox,but not in chrome.

Here is my model:

```
Player.add('基本信息',{
	name: { type: String, label:'姓名',initial: true, required: true, index: true },
	weight: { type: Types.Number, label:'体重（kg）',initial: true },
	birth: { type: Types.Date, label:'生日',initial: true, required: true},
	goodFoot: { type: Types.Select, label:'惯用脚',options: '左脚, 右脚', index: true },
});

Player.add('个人信息', {
	mobile: {type: String, label:'电话'},
	photo: { 
		type: Types.LocalFile,
		dest: 'public/images/players',
		prefix: '/images/players/',
		allowedTypes:['image/jpeg','image/png'],
		label:'照片',
		note: '400*400的png图片'
	}
});
```

And here are some dates reduced after each time I save the model in admin panel:

    1986/7/31,1988/8/26,1989/5/17,1987/4/15

It's very strange and I don't have any clue to fix it.
