### ISSUE TITLE
Connection to Mongo with SSL and a self-signed certificate

### ISSUE THREAD

**Issue by olivierlizotte** [keystonejs/keystone#2516]
Hi,
I am trying to configure Keystone to connect to a Mongo instance through an encrypted connection. Its possible to pass the "?ssl=true" parameter in the url, but I could not find how to pass other options (like sslValidate=false). Anyone has done this before?

**Comment by snowkeeper** [comment]
You can create the mongoose connection and pass it to Keystone if that works better for your use case.
```
keystone.init({
    'mongoose': mongoose
});
```

**Comment by olivierlizotte** [comment]
I tried passing the connected mongoose object, but Keystone does a 'mongoose.connect' using its own uri, which throws an error when it was already called.
Anyway, looks like it was an issue with a specific version of connect-mongo. The uri options are all passed now. Thanks!
