### ISSUE TITLE
Custom drop down menu doesn't work

### ISSUE THREAD

**Issue by yao23** [keystonejs/keystone#2517]
I added the drop down menu ([w3c school link](http://www.w3schools.com/howto/howto_css_dropdown.asp)) on the top, the section below it is block, but the drop down menu doesn't work, is there any code example to learn from?

**Comment by mxstbr** [comment]
We don't have an implementation of that available as far as I'm aware, sorry!

_This kind of question about custom HTML and CSS would be better suited for [Stackoverflow](https://stackoverflow.com), as you're more likely to get help there!_
