### ISSUE TITLE
Test Field Filter methods

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#2519]
I've added a [new test framework](https://github.com/keystonejs/keystone/blob/master/test/unit/field-filters.js) for running unit tests on each Field Type's `addFilterToQuery` method.

Now the fun begins and we need to write tests for them all! (we can skip those that inherit their `addFilterToQuery` method from another field type, of course - they can be ticked off when the type they inherit from is tested)

~~Related: see #1776 for progress on implementing the `addFilterToQuery` methods.~~ EDIT: All `addFilterToQuery` methods are implemented! :tada: 

# Field Types

- [x] boolean
- [x] code
- [x] color
- [x] date (#2548)
- [x] datearray
- [x] datetime
- [x] email
- [x] geopoint (#2550)
- [x] html
- [x] key
- [x] location (#2560)
- [x] markdown (#2553)
- [x] money
- [x] name (#2554)
- [x] number
- [x] numberarray (#2559)
- [x] password (#2555)
- [ ] relationship
- [x] select
- [x] text
- [x] textarea
- [x] textarray (#2558)
- [x] url

**Comment by geloescht** [comment]
Shouldn't this issue be closed, considering that #2480 has been merged?

**Comment by mxstbr** [comment]
Good catch @geloescht, closing as this is done! :tada:
