### ISSUE TITLE
Instantiating Content Field with CloudinaryImage.blocks.image throws an error

### ISSUE THREAD

**Issue by justintemps** [keystonejs/keystone#2520]
The docs for [Content Field](https://www.keystonejs.com/keystonejs/field-content/) suggest you should be able to use CloudinaryImage.blocks.image when instantiating a Content Field like this:

```
const { Content } = require('@keystonejs/field-content');

keystone.createList('Post', {
  fields: {
    body: {
      type: Content,
      blocks: [
        CloudinaryImage.blocks.image
      ],
    },
  },
});
```

However, doing so throws the following error: `Error: No file adapter provided for File field.`

Looking into the implementation of `Cloudinary.blocks.image`, I can see that it's a class whose constructor wants the following arguments:

`({ adapter }, { fromList, joinList, createAuxList, getListByKey })`

`adapter` is obviously an instance of `CloudinaryAdapter` but no idea what kind of object the second set of arguments are from.

**Comment by Wkasel** [comment]
Same error

**Comment by Wkasel** [comment]
(fix) 
```javascript
keystone.createList('Post', {
...
      blocks: [
        CloudinaryImage.blocks.image
      ],
   ...
// change to 
      blocks: [
        [CloudinaryImage.blocks.image, { adapter: cloudinaryAdapter }]
      ],
});
```

**Comment by justintemps** [comment]
Thanks @Wkasel ! It seems like this should be explained in the docs. I'll try to make a quick edit later today.
