### ISSUE TITLE
Safely merge filters

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#2527]
When queries are generated with conditions spanning multiple fields, some of the field types need to specify top-level conditions in the query object (e.g. Name fields use `$or`) and these would override each other.

The fields aren't the right place to encapsulate this logic - they should only be responsible for the criteria they themselves require, so we need to do something at a higher level (probably `List.prototype.addFiltersToQuery`) that will merge conflicting conditions safely (e.g. for a first pass, any `$or` conditions get combined into an `$and: [{ $or: $or1 }, ...]` condition)

**Comment by JedWatson** [comment]
Implemented, this should be safe now.

**Comment by mxstbr** [comment]
Niiiice, good work!
