### ISSUE TITLE
Edit file before AmazonS3 Upload

### ISSUE THREAD

**Issue by quitequinn** [keystonejs/keystone#2530]
How do I edit the KeystoneJS file before it is uploaded to AmazonS3

It sounds like I should be able use an underscore method... but I don't know how to implement it.

![default](https://cloud.githubusercontent.com/assets/2885870/14075403/b8042bd6-f48d-11e5-9ed5-ded89ef8e648.jpg)

So for example, lets say I want to convert the file to base64 before it is uploaded to S3 and it is done with a function. How do I get the file, apply functions or methods to it, and then upload it.

```javascript
Model.add({
    file: {         
        type: Types.S3File,
        filename: function(item, filename, originalname){                       
            return "fonts/original/" + item.slug + '.file';
        },

        // ** // ** // ** // ** // ** // ** 
        // Seems like it should go here...
        // On upload EVENT convert file to base64 and upload to S3
        // ** // ** // ** // ** // ** // ** 

    }
});
```

I've also asked this on Stack (Incase you want the points)
http://stackoverflow.com/questions/36259412/keystonejs-edit-file-before-amazons3-upload

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted, sorry about the troubles!

**Comment by quitequinn** [comment]
np
