### ISSUE TITLE
CloudinaryImage(s) field cannot upload non-image files

### ISSUE THREAD

**Issue by aegaas** [keystonejs/keystone#2549]
Cloudinary's API now supports uploading "raw" files into their service. For instance, the project I'm working on now will have Powerpoint files uploaded into keystone records through Cloudinary. Cloudinary's API looks like this:

http://cloudinary.com/documentation/upload_images#uploading_non_image_files_as_raw_files

```
cloudinary.v2.uploader.upload("sample_spreadsheet.xls", 
    { resource_type: "raw" }, 
    function(error, result) {console.log(result); });
```

Unfortunately CloudinaryImage and CloudinaryImages both block uploads of this file type.

I suggest that this alert is removed and if the type check fails, we set `{ resource_type: "raw" }` into the upload request like above.

It'd also be really nice to lock down which file types the keystone author could upload into a Cloudinary field.

**Comment by mxstbr** [comment]
We're currently in the process of reworking how all field types work. One part of that rework is that field types _should be shareable_. Users should be able to `$ npm install some-field` and use that field easily in their application.

 Another part is that we want to do something with the storage fields. (i.e. `azurefile`, `cloudinaryimage(s)`, `localfile(s)` and `s3file`) They shouldn't really be in the core, they're very specialised and the perfect candidates for being in separate repos/on npm. We're not sure in what direction we're going here yet, but we'll find out soon!

Thanks for reporting this, we're keep this feature in mind!
