### ISSUE TITLE
Cloning keystone project -> build error

### ISSUE THREAD

**Issue by syphuongcuong3** [keystonejs/keystone#2550]
I have a project use KeystoneJS and push to github. Two days ago, my laptop have some problem and I use another laptop. However, when I run `npm run dev` I got message error 

` 'keystone' is not recognized as an internal or external command,
operable program or batch file.`
I tried reinstall keystone by `npm install keystone` but it didn't work.
Thanks!

__________
Sorry about my poor English

**Comment by timleslie** [comment]
I suspect the problem here is that you need to run `npm` to install all the dependencies on your new laptop. If you're still unable to resolve and think it's a keystone bug then feel free to reopen this issue with more details.
