### ISSUE TITLE
Cookie sameSite attribute

### ISSUE THREAD

**Issue by Sylchi** [keystonejs/keystone#2551]
# Feature request

## Is your feature request related to a problem? Please describe.

Cannot auth from localhost because chrome blocks the cookie because its missing the samesite attribute

## Describe the solution you'd like

Add cookie samesite configuration to keystone constructor

**Comment by intmainvoid** [comment]
Seems this PR https://github.com/keystonejs/keystone/pull/2602 aims to fix precisely this

**Comment by intmainvoid** [comment]
This issue currently breaks solutions that rely on invoking the Keystone API in the browser where Keystone is on a different domain from which the web content is served.

For example, if your web content is server via AWS S3, and the Keystone API is served on an AWS EC2 instance, Chrome and Chromium browsers (and soon other browsers) will block the storage of the cookie.

See: https://www.chromestatus.com/feature/5633521622188032
and: https://digiday.com/media/what-is-chrome-samesite/

**Comment by thekevinbrown** [comment]
This is urgent as Chromium has already pushed a change soon that requires us to set this attribute, which they've now rolled back because of Covid-19, but it's coming and it's coming very soon.

https://blog.chromium.org/2020/04/temporarily-rolling-back-samesite.html
