### ISSUE TITLE
How can I create a middleware on graphqlapp?

### ISSUE THREAD

**Issue by HackerYunen** [keystonejs/keystone#2554]
# Question about Keystone

I want to add a google recaptcha module in my project, when users post a comment on my site, they need to pass the google recaptcha serives first. The post data are send to graphql api, and i cant didn't know how to add a middleware to verify the recaptcha token. 

I had tried to make a middleware in nuxtjsapp, but it didn't work when I visit the graphql api. 
help plz. :)

**Comment by Vultraz** [comment]
I think you want a custom `app`: https://www.keystonejs.com/guides/apps

**Comment by HackerYunen** [comment]
> I think you want a custom `app`: https://www.keystonejs.com/guides/apps

@Vultraz  It work!! thx you very much :)
