### ISSUE TITLE
Cannot load Blog demo's Admin UI when Iframely enabled

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2559]
If I add a value for `IFRAMELY_API_KEY=XX` in `demo-projects/blog/.env`, I am unable to login to the AdminUI:

```
yarn demo blog dev
```

![iframely-bug](https://user-images.githubusercontent.com/612020/77158482-82ac0780-6af7-11ea-9181-20374cf288a1.gif)

The full error:

```
ERROR in /Users/jess/dev/keystone-5/packages/fields/dist/index-23119b0f.esm.js
Module not found: Error: Can't resolve 'bcrypt' in '/Users/jess/dev/keystone-5/packages/fields/dist'

ERROR in /Users/jess/dev/keystone-5/node_modules/pg-connection-string/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/jess/dev/keystone-5/node_modules/pg-connection-string'

ERROR in /Users/jess/dev/keystone-5/packages/keystone/lib/Keystone/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/jess/dev/keystone-5/packages/keystone/lib/Keystone'

ERROR in /Users/jess/dev/keystone-5/node_modules/knex/lib/dialects/mssql/index.js
Module not found: Error: Can't resolve 'mssql/package.json' in '/Users/jess/dev/keystone-5/node_modules/knex/lib/dialects/mssql'
```

You can see in the gif that I am successfully logged in, and have a valid session token in the cookie. So whatever's happening is happening when trying to render the page _after_ signin.

I haven't investigated further, but it looks like a webpack build issue? I've tested this out on a brand new clone of `master` (commit d65c7ba59), so it's not any kind of old build artefacts laying around.

**Comment by Vultraz** [comment]
Related to #2523 maybe?

**Comment by joshlasdin** [comment]
Noticing this in our project that uses an iframely adapter as well

**Comment by joshlasdin** [comment]
Not totally sure, but think there may be more going on than just iframely as well. We were noticing similar errors while trying to create a custom field. To ensure it wasn't anything going wrong in our toolchain, we created a fresh keystone install, and attempted to copy over the custom Stars field, which can be found in the test-projects directory. Upon loading up the admin, we're getting a ton of very similar errors ([screenshot](https://d.pr/i/xv7rFT)):

```
ERROR in /mnt/d/sites/test-keystone/stars/views/Cell.js
Module not found: Error: Can't resolve './Implementation' in '/mnt/d/sites/test-keystone/stars/views'
ERROR in /mnt/d/sites/test-keystone/stars/views/Cell.js
Module not found: Error: Can't resolve './views/Cell' in '/mnt/d/sites/test-keystone/stars/views'
ERROR in /mnt/d/sites/test-keystone/stars/views/Cell.js
Module not found: Error: Can't resolve './views/Field' in '/mnt/d/sites/test-keystone/stars/views'
ERROR in /mnt/d/sites/test-keystone/node_modules/@keystonejs/fields/dist/index-23119b0f.esm.js
Module not found: Error: Can't resolve 'bcrypt' in '/mnt/d/sites/test-keystone/node_modules/@keystonejs/fields/dist'
ERROR in /mnt/d/sites/test-keystone/node_modules/@keystonejs/keystone/lib/Keystone/index.js
Module not found: Error: Can't resolve 'fs' in '/mnt/d/sites/test-keystone/node_modules/@keystonejs/keystone/lib/Keystone'
ERROR in /mnt/d/sites/test-keystone/node_modules/knex/node_modules/pg-connection-string/index.js
Module not found: Error: Can't resolve 'fs' in '/mnt/d/sites/test-keystone/node_modules/knex/node_modules/pg-connection-string'
ERROR in /mnt/d/sites/test-keystone/node_modules/knex/lib/dialects/mssql/index.js
Module not found: Error: Can't resolve 'mssql/package.json' in '/mnt/d/sites/test-keystone/node_modules/knex/lib/dialects/mssql'
```

**Comment by gautamsi** [comment]
I hit this too, any workaround?

**Comment by RubberDuckDestroyer** [comment]
Hi I have a project I'm trying to update. I get the same errors as #2582 and follow it to end up having this error. Are there any solutions to this?
