### ISSUE TITLE
Auto-scaffold API endpoints for models

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#256]
Although you'd usually want some custom control over API endpoints, we could add some simple API scaffolding that generates standard API endpoints over models for simple CRUD.

This would at least make it easy to rapidly develop applications against the API, and may (if configurable enough or in simple enough use-cases) be fine to go live with too.

Should take into account the conventions used by client-side frameworks like Angular or Backbone, so they're simpler to use out of the box.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/auto-scaffold-api-endpoints-for-models
