### ISSUE TITLE
Model defaultFilters

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2568]
Thought it might be cool if it were possible to set default filters for the Admin UI on a model.

```
var MyModel = new keystone.List('MyModel', {
    defaultFilters: [
        {
            fieldName: 'value'
        }
    ]
});
```

**Comment by meelis79** [comment]
+1 we need this functionality

I would suggest it like this:
defaultFilters: { fieldName: 'value', otherField: true}

I also need "not null" and ''null" type filter, so I can use default filter lockedDate: ''null"

**Comment by mxstbr** [comment]
Closing as a duplicate of #741, thanks for notifying us @meelis79! We'll look into adding this!
