### ISSUE TITLE
Update-admin created without isAdmin

### ISSUE THREAD

**Issue by kadosh1000** [keystonejs/keystone#2569]
Hi I am using the default admin creation update method to create my initial user:

`exports.create = {
	User: [
		{ 'name.first': 'Admin', 'name.last': 'User', email: 'admin@yyy.com', password: '1234', isAdmin: true }
	]
};`

The thing is that the user is indeed been created but without the isAdmin property.
I started debugging it and found out on the `createItem.js` that it's not being added to the list.fields object and therefore also not for the final doc.

It has worked before and maybe have something to do with the 3.17 release, as in 3.16 it used to work

How can I solve that?

**Comment by mxstbr** [comment]
Did you close the issue because you found the solution to your problem?
