### ISSUE TITLE
Add support for nested, repeating schemas

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#257]
As mentioned on the google group, it would be useful to be able to set up repeating fields in Lists and have them render in the Admin UI.

There's a fair bit of work to do to make this possible, so this issue is a placeholder for now.

**Comment by dscafati** [comment]
+1

**Comment by extragalactic** [comment]
+1

**Comment by thewolff** [comment]
+1

**Comment by msimpson** [comment]
+1

**Comment by gopeter** [comment]
Any updates on this?
I found various issues (#322, #446, #646, #257, ...), but I think it's not possible to use "repeating fields" today?

**Comment by jonathanredford** [comment]
+1

Will this possibly be a feature in the new admin ui?

**Comment by milosdakic** [comment]
PR #1336 is a good start for this. I'm using it as a base at the moment for allowing nested repeated schemas. Just looking to hook it up with the fields supported by Keystone.

**Comment by hatzipanis** [comment]
+1

**Comment by jacargentina** [comment]
Hi! My idea is try to reuse existing infrastructure for nested fields, and also have a clean definition ala mongoose native nested schemas, like explained here http://mongoosejs.com/docs/subdocs.html

My idea is to simply use array definitions:

````javascript
var parentSchema = new Schema({
  children: [{ name: 'string' }]
})
````

I'm going on with this on my jacargentina/keystone repo. The idea is simple detect that the `children` field is an array, and instance a `nested` field type which does the needed logic.

@JedWatson I would love to get your feedback on my idea.

**Comment by dragosstancu** [comment]
This one did it for me but not for the admin UI:

var Survey = new keystone.List('Survey', {
	...
});

Survey.add({
	saveDate : {
		type : Types.Date,
		default : Date.now
	},
	....
});

Survey.schema.add({
	answers : {
		type : [{
			date : {
				type : Types.Date,
				default : Date.now
			},
			value : {
				type : Types.Number
			},
			question : {
				type : keystone.mongoose.Schema.Types.ObjectId
			}
		}]
	}
});

... where Question was defined in a model file.

**Comment by jacargentina** [comment]
@dragosstancu My branch intention is to bring those nested schemas to the Admin UI.

**Comment by webteckie** [comment]
@jacargentina not sure what your implementation looks like but would the intention be to use [the new concept of] a keystone sub-list to represent a reusable nested sub-document?  The sub-list would define standard fields.  The sub-list can then be included in any other list. I would think in the Admin UI the sub-list is only shown as part of whatever list includes it if it's an embedded sub-list, or as its own list with independent sub-items if it's a shared sub-list. The shared concept can be a relationship-like association I suppose.   Food for thought!

**Comment by jandrade** [comment]
@jedwatson Any updates about this issue? I would like to see if I could look for a solution, but before I would like to understand better the architecture.

**Comment by megheaiulian** [comment]
+1

**Comment by barneyfoxuk** [comment]
+1

**Comment by dragosstancu** [comment]
I would stay away from changing the core, maybe a module can interact with the admin UI and add functionality for repeaters. I'm not that good :)

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/add-support-for-nested-repeating-schemas
