### ISSUE TITLE
0.3.17 Update TinyMCE

### ISSUE THREAD

**Issue by bewards** [keystonejs/keystone#2571]
Can TinyMCE be updated to 4.3 from 4.1 in the latest stable release of keystone? I need to use the CodeSample plugin, which is new in 4.3. I can understand if regression testing has to be done?

**Comment by mxstbr** [comment]
Probably, though I'm not 100% sure. Try it, and tell us how it goes!

**Comment by bewards** [comment]
Have only seen some small UI updates that have to do with the **codesample plugin** css not being added to x-4.0-alpha:

1. 
![image](https://cloud.githubusercontent.com/assets/3927169/14234863/fb3a786e-f9bb-11e5-9f4c-69a43ce1aa08.png)
- this was fixed by switching back to default lightgray tiny mce theme
![image](https://cloud.githubusercontent.com/assets/3927169/14234951/c99b6776-f9bd-11e5-95c1-5ec7ae8aaef2.png)

2.
![image](https://cloud.githubusercontent.com/assets/3927169/14234955/f706827c-f9bd-11e5-9fd0-1aa59a8c8dc0.png)
