### ISSUE TITLE
dependsOn not working at all in .4.x

### ISSUE THREAD

**Issue by Lemmmy** [keystonejs/keystone#2575]
With the following code, the "school" field does not work at all. This also appears to apply to the `String` and `Types.Text` datatypes.

```
postType: {
	type: Types.Select,
	options: 'news/update, high school, college',
	default: 'news/update',
	index: true
},
school: {
	type: Types.Relationship,
	ref: 'School',
	index: true,
	dependsOn: {   
		postType: ['high school', 'college']
	}
},
```

![](http://shitty.download/numerous_ran_relative.gif)

Additionally, saving does not make the field appear.

**Comment by jdr0dn3y** [comment]
This is limited to .4.x - I tested it on 0.3.17 and ```master```

**Comment by mxstbr** [comment]
Interesting, thanks for reporting this - any idea why this is the case?

**Comment by snowkeeper** [comment]
This is use case that differs slightly from 0.3.x to 0.4.x.  In 0.3.x an Array value is treated as an OR, but in 0.4.x with expression-match it is treated as an AND.  So dependsOn is working but returning a false.

The options are: 
1. Update the docs to reflect using  $or for arrays.
```
dependsOn: {   
        postType: { or:  ['high school', 'college']  }
}
```
2. Set the default expression as $or in Keystone using the 3rd argument for expression-match.
```
{ expression: $or }
```

**Comment by mxstbr** [comment]
I'm not entirely sure what the up- and downsides of either approach are?

**Comment by webteckie** [comment]
I'm fine with updating the docs to force an explicit `or` operator in this case.  @snowkeeper there's a wiki section for breaking changes and this breaking change should be noted there.

cc: @JedWatson

**Comment by snowkeeper** [comment]
Thanks @webteckie.  I will make the note if we stick with the current form.

**Comment by Lemmmy** [comment]
Thank you!

**Comment by webteckie** [comment]
@snowkeeper if want to update your library to match the 0.3 behavior then I guess that's even better.   Myself don't have a preference either :-)

**Comment by snowkeeper** [comment]
I was thinking as a separate module that Arrays should be an `$and`, but that obviously didn't match the original use case in Keystone, so I added the option to change the default to `$or`.  I am really interested in how it should work as opposed to how I thought it should work though.  Not sure if it would ever get use outside of Keystone, but I tried to build it under that mindset, while having the option to fit the Keystone use case in 0.3.x if desired.

**Comment by creynders** [comment]
My 2 cents: ditch the default and let it be set explicitly. Having it default to $or (or $and) just hides the fact that it's configurable and brings almost no value.

**Comment by webteckie** [comment]
+1 for forcing explicit operators when it may be interpreted ambiguously!  Also, if not already, the docs should link to your library's usage guide.

**Comment by neekolas** [comment]
Are we sure the @snowkeeper 's A is correct? I can't make that work with the current master. 

Looking at the expression-match docs I think it should be

```javascript
dependsOn: {
       $or: [{
           postType: ['high school', 'college']
       }]
}
```

That version does work for me, although it's kinda ugly (especially with multiple ORs). I'm not sure that is the desired solution.

To make the current syntax work you could add something like this to evalDependsOn.js
```javascript
Object.keys(dependsOn).forEach(k => {
    if (Array.isArray(dependsOn[k])) {
      dependsOn[k] = {
         $regex: '^(' + dependsOn[k].join('|') + ')$/'
      };
   }
});
```

**Comment by snowkeeper** [comment]
@neekolas is correct.  I did not confirm and misspoke.

I was under the impression that we had the option of a multi select field, which we do not.  Do we plan on offering that in the future?

I can go through expression-match and re-write some things or the solution provided by @neekolas works as well if we plan on not offering a multi select field.

To add to the answer provided by @neekolas  for a select you can use an Array to target multiple fields or an Object for just one...
```
dependsOn: {
       $or: {
           postType: ['high school', 'college']
       }
}
```
```
dependsOn: {
       $or: [
           { postType: ['high school', 'college'] },
           { anotherType: 'test' }
       ]
}
```

**Comment by snowkeeper** [comment]
I pushed an update for **expression-match** to remove any breaking changes from 0.3.x to 0.4.x.  Simple array values will work as intended.  The following are all equal:
```
dependsOn: {
    field1: ['value1', 'value2']
}

dependsOn: {
    or: [
        { field1: ['value1', 'value2'] }
    ]
}

dependsOn: {
    or: [
        { field1: 'value1' },
        { field1: 'value2' }
    ]
}


dependsOn: {
    or: {
        field1: ['value1', 'value2'] }
    }
}

dependsOn: {
    field1: {
        or: ['value1', value2']
    }
}
```

**Comment by mxstbr** [comment]
I think this can be closed, let me know if that's not the case by commenting again!

**Comment by VinayaSathyanarayana** [comment]
Can the final syntax be documented?
