### ISSUE TITLE
[AdminUI] How to add multiple images in Keystone?

### ISSUE THREAD

**Issue by maximelebreton** [keystonejs/keystone#2576]
Hello Keystone Team,

I wonder how can we add **multiple images** in a Keystone field on AdminUI?

I tried to use [CloudinaryImage](https://www.keystonejs.com/keystonejs/fields/src/types/cloudinary-image/), but it's for **one image** only...

Did I miss something or Keystone does not cover this **basic** but essential feature?

Thank you!

**Comment by jesstelford** [comment]
Hey @maximelebreton, thanks for the question.

We find when asking questions of maintainers who volunteer their time to work on free OSS it's best to avoid any phrasing or emphasis which may signal passive aggressiveness. We're all working hard, and are super excited that folks like yourself get the chance to leverage this work in your own projects. We ask to be approached with respect in return ❤️

The easiest way to do multiple images is with a separate list:

```javascript
keystone.createList('Post', {
  fields: {
    images: { type: Relationship, ref: 'Image', many: true },
  }
});

keystone.createList('Image', {
  fields: {
    image: { type: CloudinaryImage, adapter: cloudinary },
  }
});
```

This has the advantage that you can now re-use images across multiple posts as it's just a relationship.

**Comment by maximelebreton** [comment]
Damn, i'm so sorry, I didn't mean to be disrespectful at all, I've wrote it late and dont re-read before posting.
As a maintainer too (not on Keystone), I am perfectly aware of what you describe, so again I'm very sorry that you took it like this, my mistake.

Thanks for your answer @jesstelford!
