### ISSUE TITLE
Multiple string paths in a single field

### ISSUE THREAD

**Issue by theskabeater** [keystonejs/keystone#259]
Not sure if this is possible but it would be nice to add multiple string paths to a single field. Similar to Type.Name but customizable and not limited to 2 string paths.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/multiple-string-paths-in-a-single-field
