### ISSUE TITLE
npm install error on master

### ISSUE THREAD

**Issue by liming** [keystonejs/keystone#2601]
After upgrade react.js recently. npm install error.

> npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer elemental@0.5.14 wants react@^0.14.0 || ^15.0.0
> npm ERR! peerinvalid Peer react-addons-css-transition-group@15.0.1 wants react@^15.0.1
> npm ERR! peerinvalid Peer react-alt-text@1.1.0 wants react@>=0.12.0
> npm ERR! peerinvalid Peer react-color@1.3.8 wants react@^0.14.0
> npm ERR! peerinvalid Peer react-day-picker@1.3.2 wants react@~0.13.x || ~0.14.x || ^15.0.0
> npm ERR! peerinvalid Peer react-dnd@2.1.4 wants react@^0.14.0 || ^15.0.0-0
> npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
> npm ERR! peerinvalid Peer react-select@1.0.0-beta12 wants react@^0.14 || ^15.0.0-rc || ^15.0.0

**Comment by JedWatson** [comment]
Totally aware of this, I updated react without considering how much npm was going to whinge about it 😁 

Not much we can do but wait for all those dependencies to update their peer deps, hopefully won't take long. I've fixed the ones I'm responsible for!

**Comment by liming** [comment]
Thank you JedWatson. Have you updated elemental? I didn't see the change on master https://github.com/elementalui/elemental

**Comment by liming** [comment]
Hi @JedWatson , still the elemental UI has not updated to adapt react 15.0.1.

**Comment by mxstbr** [comment]
Closing this issue as there's nothing actionable for us left to do here. Sorry about the problems, there's nothing we can do from our side except wait!

**Comment by liming** [comment]
@JedWatson and @mxstbr , just want to ask, is there any workaround? It's really bother me because heroku deploy need npm install every time so I cannot deploy my latest implementation for about 2 weeks.

**Comment by JedWatson** [comment]
I think I'm just going to fork `react-color`... 😞

**Comment by liming** [comment]
Forked react-color and keystonejs to work around this problem.

**Comment by morenoh149** [comment]
@liming links?

**Comment by liming** [comment]
https://github.com/liming/keystone

**Comment by morenoh149** [comment]
https://github.com/liming/react-color is the interesting one

**Comment by JedWatson** [comment]
That's actually not exactly what we need. We haven't made the changes that we need to to go to 2.0.0 yet, so we need a fork of 1.3.8. And it's better if all our deps are loaded from npm, which you can use scoped packages to do.

I've published a fork of react-color to npm that will work for us and am about to update keystone to use it. Should get everything working again, I'm just testing it now. We'll just have to stay with that until @casesandberg gets around to updating `react-color` again.

**Comment by casesandberg** [comment]
My bad guys, will get that fixed today 🏇

**Comment by liming** [comment]
Good to know!
