### ISSUE TITLE
Export data as CSV

### ISSUE THREAD

**Issue by RubberDuckDestroyer** [keystonejs/keystone#2604]
# Feature request
A button that exports data as csv

## Describe the solution you'd like
Hi I am working on a project where I need to export my data generated as a CSV. Say I add filters on user data where user address contains 'xyz', I'd like to have a button that would download the filtered/generated user data as CSV for me. 

I see that this feature is available in keystone v4. Is there an estimate on when this will be added in v5?

## Describe alternatives you've considered
Right now I'm doing everything off AWS Lambda and seperate APIs for exporting my data.

**Comment by jesstelford** [comment]
@MadeByMike would this be a good usecase for custom elements in the Admin UI?

**Comment by molomby** [comment]
There are a few sides to this:

* Hooking into the Admin UI to add a button (or similar) to trigger a server side action. This is captured by #1452) I think.
* Creating the exported itself and issues around that (ie. should it be async, how does it interface with the DB adapter, etc.). Issue #310 talks about this.
* How the resultant file is stored/transferred

We're working pretty actively on the first point but the backend parts of the problem are largely in the hands of project developers. 

You should probably look to add a custom endpoint into the express app Keystone provides. Checkout [the `configureExpress` hook](https://www.keystonejs.com/guides/custom-server#you-may-not-need-a-custom-server). From there, you should be able to create an endpoint that has access to..

* Keystone session info, via. `req.authedItem` I think?
* The GraphQL server, via [`keystone.executeQuery()`](https://www.keystonejs.com/keystonejs/keystone/#executequeryquerystring-config)
* DB adapter, via `keystone.adapters`

**Comment by gautamsi** [comment]
given there is support for admin ui hooks for items pages view and further being finalised this can be reality soon. 

some work already done in https://github.com/keystonejs/keystone/pull/1739 which was closed in favour of https://github.com/keystonejs/keystone/pull/2469 and other split PRs

**Comment by RubberDuckDestroyer** [comment]
Hi, is there any update on implementing this in keystone v5?

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
