### ISSUE TITLE
Scrolling and Searching for referenced data

### ISSUE THREAD

**Issue by RubberDuckDestroyer** [keystonejs/keystone#2605]
# Bug report
Hi, I am working on a project where I have referenced custom elements within a custom element. Think of it as a Blog having an Author, where Author just refers to the Users collection.
On creating an item from the Admin User panel, I cannot search or scroll in the list of my referenced data. 

In my current collection, I cannot search referenced data when applying filters.

## To Reproduce
1. Create a collection that has datapoints that are referenced from an existing collection.
2. On creating an item, error occurs.
3. On searching current items, apply a filter on referenced data. Try to search for an existing item. The issue occurs here too. 

## Expected behaviour
On creating an item
a. I am able to search for referenced data available
b. I am able to scroll through referenced data available

On filtering my current data
a. I am able to search for existing data that is referenced from another collection.

## Screenshots
On creating an item:
<img width="602" alt="Screen Shot 2020-03-30 at 12 19 20 PM" src="https://user-images.githubusercontent.com/24650979/77865462-f59d4700-728a-11ea-88be-9d721523d1a1.png">
on searching for an existing item to use: 
<img width="608" alt="Screen Shot 2020-03-30 at 12 19 34 PM" src="https://user-images.githubusercontent.com/24650979/77865465-f7ffa100-728a-11ea-9852-bcb196d3a2aa.png">

On filtering current items:
<img width="316" alt="Screen Shot 2020-03-30 at 12 20 55 PM" src="https://user-images.githubusercontent.com/24650979/77865468-fb932800-728a-11ea-81f3-beb7330120a8.png">
on searching for an existing item
<img width="316" alt="Screen Shot 2020-03-30 at 12 21 06 PM" src="https://user-images.githubusercontent.com/24650979/77865469-fdf58200-728a-11ea-80b7-7af5e11b9cde.png">

## System information
- OS: macOS Catalina 10.15

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
