### ISSUE TITLE
Adopting git-flow

### ISSUE THREAD

**Issue by cameronroe** [keystonejs/keystone#2606]
Considering there are a lot of branches. Thoughts on adopting a git-flow model for PRs so it's a little more clear as to what's what? https://github.com/nvie/gitflow

**Comment by mxstbr** [comment]
Too much cognitive overhead with little benefit, I think the system works fine as-is. We need to close long-standing PRs but that's it!

**Comment by cameronroe** [comment]
Okay, maybe in the future.
