### ISSUE TITLE
Which packages are compatible with others?

### ISSUE THREAD

**Issue by thekevinbrown** [keystonejs/keystone#2606]
# Feature request

## Is your feature request related to a problem? Please describe.

There have been a few issues hit by the community because it's not clear which versions of the packages are compatible with each other. For example: https://github.com/keystonejs/keystone/issues/2588

## Describe the solution you'd like

I think there are two ways to solve this problem:

1) Do what Gatsby does. Every package in their monorepo is versioned together, so as a user all you need to do is ensure all your keystone packages are the same version, and you know they'll work together. If a package isn't changed in a release, it still gets its version bumped so you can just treat Gatsby as all having the same version number.
2) Publish a compatibility matrix of every version of every package and what other package versions are compatible. Implement checks in each package to make sure the other packages are compatible on start up.

## Describe alternatives you've considered

Stab in the dark with various versions until you get something that appears to work, but may be broken in subtle ways because of incompatibilities. (Seems less than ideal to me.)

## Additional context

To be production ready, we really need to know what's compatible with what.

- Can I use `@keystonejs/app-admin-ui` version 5.9.1 with `@keystonejs/keystone` version 6.0.2?
- What about `@keystonejs/app-admin-ui` version 5.9.1 with `@keystonejs/keystone` version 7.0.0? 

How can I check that these combinations are compatible or not compatible?

**Comment by timleslie** [comment]
Thanks for bringing this up, @thekevinbrown, I strongly agree that this is an an issue we need to handle better. I'm open to hearing ideas about how this can be best be handled, and how best to communicate this to users.

FWIW, the pattern I follow when upgrading keystone is to always upgrade all packages at the same time, and to always check my `yarn.lock` and eliminate duplicate packages in the `@keystonejs` namespace.

Perhaps @Noviny or @mitchellhamilton have some ideas within this space?

**Comment by thekevinbrown** [comment]
@timleslie that approach works when you're staying current, but in the scenario where you don't always want the latest, we need some kind of way to tell what's compatible with what. For example let's say that we've been working on a release, we're really close, then there's a point update of the Knex adapter that fixes a bug, while at the same time the core keystone package gets bumped up to `8.0.0`. We want the bug fix, but don't want to introduce instability in the system. Can we pull in the bug fix without bumping core Keystone? At the moment we just have to read the code for ourselves and guess.

I think Gatsby's approach is the easiest because you don't then have to maintain a huge matrix, and it'd become clear just by the numbering of the packages if the Knex adapter point fix depends on the new Keystone `8.0.0`.

**Comment by Noviny** [comment]
I do!

The biggest idea I have been thinking about with monorepos versioned together is that when you version packages, you do a single 'release' - it would be good to tag a release on npm so you can

```
yarn upgrade @keytonejs/keystone@cool-tag @keytonejs/admin-ui@cool-tag
```

This sort of doesn't solve all the problems you're talking about with understanding the possible upgrade matrix, as it's just 'make sure they're all the same, but make making upgrading to particular releases easy'.

Peer dependencies are a way to declare this a little better, but I mostly see them adding NOISE without actually adding value.

'everything is the same version' is really good for consumer-facing packages (it flattens out comms a lot) but DREADFUL for if it includes a bunch of internal utilities. Suddenly you'll have major versions of your main package because you made a breaking change to something that affects literally nobody.

There's a concept being used in `emotion` of linked versioning which is a bit of a compromise. This lets you link *some* package versions, but not *all* package versions. The hitch at the moment is that it only iterates the version if the package is being published, not all versions.

Example time because that was confusing. I have:

```
@keystonejs/keystone@1.0.0
@keytonejs/admin-ui@1.0.0
```

I add a minor to `@keystonejs/keystone` and publish. I now have:

```
@keystonejs/keystone@1.1.0
@keytonejs/admin-ui@1.0.0
```

I then do a second release with a minor to `@keystonejs/admin-ui` and a patch to `@keystonejs/keystone` - after versioning I get:

```
@keystonejs/keystone@1.2.0
@keytonejs/admin-ui@1.2.0
```

This mostly helps because they will all always get major bumps together.

---

*deep breath*

So there are some thoughts.

**Comment by thekevinbrown** [comment]
@Noviny I'm not sure how a consumer of the packages can tell that admin-ui version 1.0.0 is compatible with keystone v1.1.0.

> 'everything is the same version' is really good for consumer-facing packages (it flattens out comms a lot) but DREADFUL for if it includes a bunch of internal utilities. Suddenly you'll have major versions of your main package because you made a breaking change to something that affects literally nobody.

I think I'm not understanding the problem you're referring to.

- Even if the package is purely an internal utility thing, we still need to know if it's compatible with another version of a package we depend on. If there's a breaking change, and that's not published as such, then we're going to end up with incompatibilities that we don't notice in a point release, no? And if it is a breaking change in the utility package, then we release a point update of everything else, that could be very very problematic unless done very carefully, because I might bump just the Knex adapter and nothing else. Now suddenly I'm weirdly broken because there are two instances of the utilities package that do different things and don't expect to coexist.
- So wouldn't we need to do a breaking change even in this case? To me, breaking changes should be advertised as such so that we can be sure as a package consumer that we treat them in more of an all or nothing way than we would a point release.

**Comment by Noviny** [comment]
It propagates changes to the highest shared version + bump type per release, but only releases things when they are changed, rather than publishing versions of packages with no changes from the previous version.

This is what Babel and emotion do.

It’s bad to include utilities as I should be able to make a breaking change for an internal utility that only patches the core package (used by consumers) but keeps the user-facing packages in close-to lockstep.

**Comment by thekevinbrown** [comment]
Can we talk about specifics instead of broad concepts?

- What exactly are the utility packages in Keystone? The vast majority seem to be user facing to me. Is this even a thing that is likely to affect us?
- What is an example of a breaking change in one of those packages that you wouldn't want to release a new version for? For example if we're talking about changing how `session` works, that'd be something that's probably best published with a breaking change in `keystone` anyway, no?

I just don't see why it's so bad to bump versions when things change and I don't understand the requirement to be able to change a utility package without bumping everything. You keep saying it's bad, but I don't understand why you think it's bad.

**Comment by Noviny** [comment]
Sorry for slow reply: life happened.

---

### Examples:

Say we have three packages in our repository.:

```
@keystonejs/keystone@1.0.0
@keystonejs/admin-ui@1.0.0
@arch-ui/button@1.0.0
```

where you use the `admin-ui` with `keystone`, and `button` is used inside admin-ui but isn't exposed in the `admin-ui` to the user.

I make a breaking change to `button` (Say I rename the `danger` button appearance to `cancel`) and queue up to do a major release of button.

Under version lockstep, I do a major release of `admin-ui` and `keystone` as well.

The current approach we are using would be to patch `admni-ui` to use the new major of button (which will be tested internally to the monorepo), and leave `keystone` alone. This allows us to correctly semver as many things as possible, while having the minimal number of breaking changes.

The 'some things are locked approach' says that we patch both `admin-ui` and `keystone`. BUT if the breaking change was in `admin-ui`, we would cut a new major of `keystone` and `admin-ui`

The second question is "Do we publish everything each time" - that is, when I publish `admin-ui` as a new major, do I also publish `keystone` as a major so they stay in lockstep. It makes sense if the goal is 'install same version of everything' but plays merry hell  with making anything that looks like correct semver.

---

I'm not a hug fan of approaches that lock everything in the repo together, personally, but there's definitely an issue around 'how do I install 'slice-of-time' releases from the monorepo' which isn't solved.

There's an issue we're discussing [over in changesets](https://github.com/atlassian/changesets/issues/249) at the moment that ties all packages released at one time together, without baking that into a shared semver range, which to me feels like the best of both worlds.

**Comment by thekevinbrown** [comment]
@Noviny that makes sense, thanks.

I think the most confusing thing about the approach you're proposing is it kind of misses the point of semver to me. If all of these were definitely separate things that work separately, then sure, they each version separately. But very few people in the world are going to be using one of these without stringing them together. Here's what's in my `package.json`:

```
"@keystonejs/adapter-knex": "6.2.0",
"@keystonejs/app-admin-ui": "5.7.2",
"@keystonejs/app-graphql": "5.0.3",
"@keystonejs/auth-password": "5.0.2",
"@keystonejs/fields": "6.2.2",
"@keystonejs/keystone": "5.4.3",
```

Does fields 6.2.2 work with keystone 5.4.3? What about adapter-knex v6 with admin-ui 5.7.2? It's confusing to have Keystone be behind the packages it's using that had breaking changes but still work with it. To me it feels dogmatic to stick to, "Keystone hasn't had a breaking change, so it doesn't move, but fields has, so it does" because it doesn't actually help consumers understand what the breaking change is. Do I need to change my code? What are we signalling with that version change that someone external to the package needs to know? This approach feels to me like a history lesson as opposed to useful information for me as a consumer.

Also, over time if this drift continues we're going to be looking at something like fields v24 being compatible with keystone v11, and that's completely unhelpful from my perspective. What does it help me to know that there have been 24 breaking changes in fields, and 11 in Keystone? That's a history lesson. I want to know if the packages I'm using work together, not the history of how we got here, and on each release I want to know if I can safely incorporate that release without breaking my setup. From my current package.json, the answer from the versioning is "maybe", which to my mind defeats the purpose of using semver in the first place. I should know what's safe to incorporate from the version number, or semver isn't helping me. That's what semver is for.

I'd propose that a compromise here would be:

- Arch UI is a separate thing, because it actually is in terms of how it's published already.
- When you have a major version bump in any `@keystone` package you major bump and publish all of the packages so they don't drift so far apart as to be confusing. The minor and patch bumps can drift all they like within the majors, but as a consumer I know what the boundaries are when consuming updates of the various packages.

From my perspective that solves all of the major concerns both of us have and actually makes the semver more meaningful and useful to consumers than it is currently.

**Comment by gautamsi** [comment]
I am thinking if there could be keystone utility which can help in upgrading to correct version combination. 

I am sure the data from chnageset `version package` PRs could help in either correcting the packages in the dependency chain or help validate and provide suggestion. 

something like this

```sh
>keystone upgrade @keystonejs/keystone@8.0.1
# OR
>keystone validate @keystonejs/keystone@8.0.1
```

keystone can then update package.json or validate package.json for version compatibility to make sure all the packages updated in same changeset are indeed listed correctly. 

We can pick specific package version based on interest (like last package before arcade release) then this will give us correct packages in package.json.

not sure if this will be easy or even more complex.

**Comment by thekevinbrown** [comment]
My perspective on that is, if we can’t tell from the version numbers what’s safe to upgrade to, then why are we using semver? I don’t think this is so complex as to need new non-standard tooling, it just means following the intent of semver.

**Comment by gautamsi** [comment]
Is semver designed to help across cross referenced large number of packages or more like expectation with one single package across version?

If semver is not designed to help with cross packages then we come to workaround of matching versions in release. I see Apollo does that for react packages and makes every package release same time.  OR you try to be creative (maybe not) and have some mechanism which tracks and installs version compatibility across the packages.

**Comment by thekevinbrown** [comment]
@gautamsi From semver.org:

> Under this scheme, version numbers and the way they change convey meaning about the underlying code and what has been modified from one version to the next.

Semver itself gives no guidance about what to do with large networks of connected packages. I'd suggest that indeed semver is designed to convey meaning to package consumers at the cost of more complexity for package maintainers. Many other monorepo based projects successfully using only semver to convey this information to package consumers suggests to me that it's a tool that's fit for this purpose.

Since the Node community's tooling understands semver intuitively, and it's possible for us to use semver in a way that conveys more meaning about the underlying changes, why wouldn't we do that?

**Comment by thekevinbrown** [comment]
@timleslie @Noviny @gautamsi 

Is there a plan to move forward here? Can I help with anything? I'm keen to have more visibility into what's compatible and am happy to help with anything that needs doing here.

**Comment by thekevinbrown** [comment]
This is still biting people.
<img width="679" alt="Screen Shot 2020-05-12 at 11 14 46 am" src="https://user-images.githubusercontent.com/1531750/81627614-eb519980-9441-11ea-94f0-28dd002629d2.png">

**Comment by mitchellhamilton** [comment]
Given that most things are now in the `@keystone-next/keystone` package and the other packages have a peer dependency on `@keystone-next/keystone` making it clear what version of `@keystone-next/keystone` it needs, I think this is now addressed.
