### ISSUE TITLE
when I use Relationship ,the Admin only show "ID"，not the title 

### ISSUE THREAD

**Issue by QianDingwei** [keystonejs/keystone#2609]
# Question about Keystone

GitHub Issues are reserved for Bug reports and Feature requests.

The best place to get a question answered is sign-up to our Slack: http://community.keystonejs.com/
![image](https://user-images.githubusercontent.com/47747920/77889205-17ed8f80-72a0-11ea-8414-d9d16e89e4bd.png)
![image](https://user-images.githubusercontent.com/47747920/77889300-38b5e500-72a0-11ea-8761-12e33b446c92.png)
as is show above,I init when the project start,but I use  the RelationShip,in the adminUI，Only show id like 1,2,3

**Comment by timleslie** [comment]
The contents of the `select` component for a relationship use the `labelField` of the related list. By default it will look for a field called `name`. If this doesn't exist it will use the `id` field, which is what you are seeing. You can configure the field used with the `labelField` config option. If you would like it to use the `postition` field you can do:

```
module.exports = {
  fields: { position: { type: Text, ... } },
  labelField: "position",
};
```
