### ISSUE TITLE
Question: does keystone supports built-in "remember me"

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystone#2620]
As i've posted on here without answer for a long time

https://github.com/keystonejs/keystonejs-site/issues/84

Hope asking the same here i get some answer?

I want to avoid having to enter my credentials each time i use the website.

**Comment by mxstbr** [comment]
Pretty sure it doesn't at the moment, but that sounds like a very reasonable feature that should be there! Would you mind commenting in #2566, I'll take a look!

**Comment by jacargentina** [comment]
I've made a very little change which permits me to have this working now:

https://github.com/jacargentina/keystone/commit/b5540ffb4fbac866c8c700f000d650a1bed43000

I've found that `cookie signin` works just fine, but the cookie was alive just for the current _Session_ (ie, expires when closing the browser), so i've added an extra option named `cookie signin expire` which permits to configure a fixed amount of time for the cookie to live (even when closing the browser)

**Comment by mxstbr** [comment]
Would you mind submitting a PR for this? Sounds useful!
