### ISSUE TITLE
Mandrill. 

### ISSUE THREAD

**Issue by oliverwh** [keystonejs/keystone#2627]
Hi there,

So far Mandrill is going to be completely integrated into MailChimp and they force all user to get paid MailChimp account to continue to use it.
All changes should be done by 27th of April.
Moreover, new  accounts are looking slightly different then old ones.

I guess there should be a new way to configure mailing system for keystoneJS.

**Comment by mxstbr** [comment]
Duplicate of #250. We're aware and will hopefully get a new integration out with 0.4 or 0.4.1, thanks for the reminder!
