### ISSUE TITLE
meta: v4 in production

### ISSUE THREAD

**Issue by r1b** [keystonejs/keystone#2628]
I'm trying to make a business case at my workplace for upgrading to v4. There are a number of improvements in v4 that are critical to our process.

I have been able to run our CMS project against master on our test environment without any serious issues. However, per dev process, I cannot pull from keystone master in production or fork.

I understand that the keystone team & the community are working hard on the v4 release. My problem is that I am finding it hard to make a business case for an upgrade without a clear timeline to v4.

I would like the team to consider one of the following solutions for current keystone deployments:

* Cut a v4-beta or similar release candidate

A sanctioned release would be much easier to get into production & would help get keystone users excited about the new features/look-and-feel.

* Provide a more concrete timeline of v4 tasks

I know that we have a [v4 milestone](https://github.com/keystonejs/keystone/milestones/0.4.0) but there is a lot of noise. It is hard to tell what is actually being worked on & what stands in the critical path.

Thanks again for all of your hard work! v4 is a huge step forward.

**Comment by mxstbr** [comment]
Both of these things are planned!

The updates about the v0.4 timeline are written, just need to be proofread/added to and should be out at the very latest end of tomorrow CEST.
A v0.4 pre-release will be cut as soon as #2566 is merged and most things work as expected. Said release will mostly be to test the new admin interface against production apps. Look forward to massively improved performance and perceived performance of the interface, consistent and tested field validation and a bunch more!
