### ISSUE TITLE
addFieldValidationError in validateInput field hook causes new item to not be saved

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2630]
## Describe the bug

In the AdminUI, when you create a new item -- let's say a new "Article" -- by clicking on the CREATE button on the top right of the screen a new form appears to fill out.  That is, you can start filling out the form and 'creating' the item immediately, before it's saved. 

![3e897d91-c150-4594-90fb-031ea9bdd296](https://user-images.githubusercontent.com/60699805/78112411-7892de80-73fe-11ea-8986-524ba7c37c7d.jpg)

However, if you do validation of the input using the`validateInput` hook, this hook will be called when the user clicks on the second CREATE button, this time in the 'half window' with the form where they've been introducing data.   If in this hook you call `addFieldValidationError`, not only will the alert pop up but also the half-window with the form and all the entered data will disappear.

This could lead to someone filling out the data, clicking CREATE the second time and then losing all their work.

It also contrasts with the behavior seen when one has already _created_ the item and is editing it.  In this case the error alert pops up but the window is not dismissed.

![imgpsh_mobile_save](https://user-images.githubusercontent.com/60699805/78113106-85fc9880-73ff-11ea-991b-5b069f71f9a9.jpg)

## To Reproduce
1. Write a field validation hook.
2. Call `addFieldValidationError` in this hook on some easily reproducible circumstance (for instance, when entering 'oops' in a text field)
3. Run Keystone, then create a new item of which the field is a part.  Cause the error to be thrown (by entering 'oops' in the field, for example)

## Expected behaviour

When an error is thrown in a not-yet-fully-created item (that is, when it is still in the 'half-window' state), if an error is thrown or `addFieldValidationError` is called, the error alert should pop up but the half-window should not be dismissed.

## Screenshots

See above.

## System information

- OS: MacOS 10.14

**Comment by Vultraz** [comment]
@ra-external wasn't this found to be fixed by updating?

**Comment by ra-external** [comment]
@Vultraz, yes, I'll close it.
