### ISSUE TITLE
Tracking plugin does not set updatedAt, updatedBy on remove

### ISSUE THREAD

**Issue by r1b** [keystonejs/keystone#2631]
I have a pre-remove hook on all of my models. Within the hook, I would like to see which user initiated the removal. This does not work. I see in [lib/schemaPlugins/track.js](https://github.com/keystonejs/keystone/blob/0e5a4a11d13d4ced058b392b119140f42116dc7e/lib/schemaPlugins/track.js) that tracking is only registered pre-save. Is this something that would be useful for others?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
