### ISSUE TITLE
 How to setup Website URLs: Help Needed - Urgent

### ISSUE THREAD

**Issue by devadmin1** [keystonejs/keystone#2639]
Hello,

I have a domain www.abc.ind.in  with GoDaddy
I have created a keystone app in abc.herokuapp.com
In GoDaddy I have setup url forwarding to abc.herokuapp.com

when a user enters www.abc.ind.in the user is redirected to abc.herokuapp.com

I would like the title/url window  to show www.abc.ind.in and not abc.herokuapp.com

When a user clicks on gallery, the title should show www.abc.ind.in/gallery (instead of abc.herokuapp.com/gallery)

What settings should I change to do this?

**Comment by geloescht** [comment]
I think you cannot do anything on the side of keystone about this. A HTTP redirect does exactly what you describe and cannot do anything else.
What you want is probably a DNS entry for your domain that refers to your IP address. Ask the people at heroku and GoDaddy. Often you have to pay (more) for such a setup.

**Comment by mxstbr** [comment]
This is definitely not on Keystones, but on your DNS' side, there's nothing we can do here – sorry!
