### ISSUE TITLE
AdminUI fails to upload image using LocalAdapter

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2641]
We have a Keystone App that we’ve been working on a while, where we upload images using the LocalFileAdapter.

The image uploading is set up
```

const staticPath = 'public';
const staticRoute = '';
const imageFileAdapter = new LocalFileAdapter({
 src: `${staticPath}/images`,
 path: `${staticRoute}/images`
})

```
and used in the 'Image' list

```
import { File } from '@keystonejs/fields';
import log from '../util/log';
export default (keystone, { imageFileAdapter }) => {
 log(`file adapter for image ${imageFileAdapter}`);
 keystone.createList('Image', {
  schemaDoc: 'Image for Article',
  labelResolver: item => item?.file?.originalFilename ?? '',
  fields: {
   file: { type: File, adapter: imageFileAdapter }
  }
 });
};
```
The AdminUI allows us to start the image creation process, and pick the image from disk. But when we click on CREATE we get a 400 error which says the file data being uploaded is null, but this may in fact be the way GraphQL is uploading the image.  The data seems to be there.  However the browser console reports

![imagen](https://user-images.githubusercontent.com/60699805/78274066-f266bd00-750f-11ea-9b9f-fa36f987d294.png)

This is the information on the network request:

![bd6f4f0a-0272-42d2-b4c8-4e310298d710](https://user-images.githubusercontent.com/60699805/78242569-7efa8680-74e2-11ea-93fb-284a9d6ea078.jpg)

This has worked fine for 6 weeks up until now.  The keystone versions we are using are the following -- we haven't updated as updating the newest packages broken the application (we are waiting for the upcoming keystone/keystone 8.0.0 to try to update again):
```

"@keystonejs/adapter-mongoose": "^5.2.0",
"@keystonejs/app-admin-ui": "^5.8.0",
"@keystonejs/app-graphql": "^5.1.0",
"@keystonejs/app-next": "^5.1.0",
"@keystonejs/app-static": "^5.1.0",
"@keystonejs/auth-password": "^5.1.0",
"@keystonejs/field-content": "^5.4.0",
"@keystonejs/fields": "^6.3.0",
"@keystonejs/fields-markdown": "^5.1.0",
"@keystonejs/fields-wysiwyg-tinymce": "^5.2.0",
"@keystonejs/file-adapters": "^5.5.0",
"@keystonejs/keystone": "^5.5.0",
"@keystonejs/oembed-adapters": "^5.1.0",
```

**Comment by MadeByMike** [comment]
@ra-external have you been able to resolve this? We've had no other reports related to file uploads through the adminUI and I believe our CI also tests this. 

If it's still an issue I'd like to see if we can replicate it!

**Comment by ra-external** [comment]
@MadeByMike  I believe updating the packages solved this.  I'll close it.
