### ISSUE TITLE
Admin UI: Is threre any hooks for replace component  to custom one?

### ISSUE THREAD

**Issue by ghost** [keystonejs/keystone#2652]
i found the hooks config for using custom pages, its so cool, but usually we want  to change part of page, like nav style, or search bar functions for each page ... ,is there any way easily to done this,

may i change globle css for all in one place?
may i replace a component  by custom'?

Please check this,Thank you very much!!!

**Comment by lauka** [comment]
same question

**Comment by MadeByMike** [comment]
We've just released a bunch of new hooks for the AdminUI details in: https://www.keystonejs.com/keystonejs/app-admin-ui/#hooks
