### ISSUE TITLE
File Upload Issues

### ISSUE THREAD

**Issue by micahbule** [keystonejs/keystone#2654]
I found 2 related bugs regarding file upload fields.

- When using either LocalFile, LocalFiles, CloudinaryImage, or CloudinaryImages fields, canceling the upload dialog overrides any queued files, thus uploading no files at all.
*How to Replicate*
Using any of the fields mentioned above, click "Upload" button and select any image to upload. After clicking "OK" from the dialog box, click the "Upload" button again, but this time don't select any image, just click the "Cancel" button. Then hit save. Instead of uploading any queued files, nothing gets saved.

**Lead**
Upon digging, I found that clicking the "Cancel" button in the dialog box still sends an event that is processed by the file upload component. However, this event contains NO files since it's technically an action to cancel an upload. I tried to validate the event by counting the files, and ignore processing if there are no files present in the event, but it seems like the underlying file input element still overrides the queued files regardless.

- When using LocalFiles or CloudinaryImages, adding files consecutively only uploads the last file queued.
*How to Replicate*
Using LocalFiles or CloudinaryImages, click "Upload" button and select ONE image to upload, then click "OK" from the dialog box. Then click "Upload" button again, select another image. In the UI, it queues BOTH images, but upon hitting save, you can only see one image file successfully uploaded and saved. This is also applicable when selecting multiple images at a time.

**Lead**
Similar to my other lead, the component properly processes the queued files, but the underlying file input element is overwriting the queued files.

**Comment by mxstbr** [comment]
Thanks for this detailed bug report!

We'll be reworking the storage fields after the 0.4 update completely, they need a total overhaul. I'll close this issue for now as there's nothing actionable to do at the moment, thanks so much for showing us this problem!
