### ISSUE TITLE
Audio upload

### ISSUE THREAD

**Issue by slaymantis** [keystonejs/keystone#2655]
Hello

I am trying to get audio and video uploads working with keystone and cloudinary.
The test project has an Cloudinary Image upload example
I see the code under node_modules/cloudinary/cloudinary.js
There are methods there for images and video it seems
exports.image = function (source, options) 
exports.video = function (public_id, options)

I would like to also have one for audio (since wloudinary now supports it)

Currently in a model in keystone you would use it like this
image: { type: Types.CloudinaryImage },

how would I go about creating a way to  do something like this?
audio: { type: Types.CloudinaryAudio },

and perhaps
video: { type: Types.CloudinaryVideo },

Any suggestions?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by maximelebreton** [comment]
+1 @slaymantis

**Comment by dijs** [comment]
@slaymantis Did you ever figure this out?

**Comment by slaymantis** [comment]
Yes I did actually. I just wrote another class to handle audio uploads based on the video class.
I can post a link somewhere for you?

**Comment by dijs** [comment]
That would be wonderful!

**Comment by slaymantis** [comment]
Im not sure if this is the place to post this.
I can move it another forum? 

I pulled out the files I made for my project
I think these are all the files I added
I  put them into their respective folders (you will need to merge this with your folders)
In my modeI could then access the new type like this:

audio: { type: Types.CloudinaryAudio }

I hope it helps
Here is the method I used to add and modify these files:
https://github.com/keystonejs/keystone/wiki/Create-a-custom-field-type-for-app-development

And the files
[cloudinary_audio_example.zip](https://github.com/keystonejs/keystone/files/1502090/cloudinary_audio_example.zip)
