### ISSUE TITLE
Admin UI: Handle authenticated but unauthorized users better

### ISSUE THREAD

**Issue by zenflow** [keystonejs/keystone#2655]
# Feature request

## Problem

Some non-admin users will inadvertently end up on admin pages. The admin UI should handle them in a sensible way. Currently, they are just shown the login page, which doesn't make much sense for a user who is already signed in.

## Proposed Solution

Add an "Access Denied" screen to show to users who are signed in but unauthorized to access the Admin UI.

Also, after an unauthorized user signs in, rather than  showing them the Access Denied screen, redirect them to the site's public home (root path `/`).

**Comment by MadeByMike** [comment]
There is a better way to handle this. There is an `isAccessAllowed` that will allow you to restrict who had access to the adminUI: https://www.keystonejs.com/keystonejs/app-admin-ui/#isaccessallowed

**Comment by zenflow** [comment]
@MadeByMike Yeah, I'm aware of that option. I think you may have misunderstood the issue: This is about how the app **handles** those users that are not allowed access (i.e. users for which `isAccessAllowed` returns `false`) (i.e. "non-admin users", as I referred to them above).

> Currently, they are just shown the login page, which doesn't make much sense for a user who is already signed in.

That's not a really sensible way to handle these users who are authenticated but unauthorized, is it? Can we reopen this?

**Comment by zenflow** [comment]
I'll break it down another way:

Currently the login screen is the default catch-all route in the public version of the frontend app, even if the user is already logged in.

I suggest replacing the default catch-all route (in the public version of the frontend app) with an "Access Denied" screen .

Since the public version doesn't know about all the private pages, it can't differentiate between a page that is protected and a page that really doesn't exist. So we need to make a choice.

The alternative is a "Not Found" screen (for the default catch-all route in the public version of the frontend app), which would fix the problem too.
