### ISSUE TITLE
'Relationship' fields do not seem to be passed to list hooks through 'existingItem'

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2663]
NOTE: I see this is related to https://github.com/keystonejs/keystone/pull/1855 and https://github.com/keystonejs/keystone/issues/1856

## Describe the bug

Fields which are designated as 'Relationship' fields are not passed to list hook.

## To Reproduce

Create a List, add a 'Relationship' field to that list.  Populate that Relationship field with values via the AdminUI.  Save the item.  Examine the 'existingItem' data in a list hook.

## Expected behaviour

That the saved --and thus existing-- Relationship field data be passed to the hook.

## Additional context

I have an `Article` list.  I need to send to the client a list of 'Recommended Articles' based on that an Article's `Tag`s.  `Tag` is a `Relationship` field, already populated with data.  My thought was to also have a  `RecommendedArticle` field, of type `Relationship`, with ref `Article`, which I would dynamically populated in the `resolveInput` list hook of `Article`, first grabbing the current `Tags`, then performing a query to obtain related `Articles` and then passing those to `resolvedData`.  But I can't get the `Tags`, even though the data is there.  I suppose I could do an initial query based on the current `Article` id, but I had thought that there would/should be a way to access this through `existingItem`

**Comment by gautamsi** [comment]
I think it is deliberately not done as to reduce the data being fetched. Keystone would not know how much data it would fetch from relationships item, there may be 100s of item in relationship (1 to many).

Also the nested relations, there could be no limit in some cases. It would be easier to have you do it as needed with actions param to hook.

**Comment by molomby** [comment]
This is the intended behaviour, however it should be documented.

**Comment by MadeByMike** [comment]
I documented this: https://github.com/keystonejs/keystone/pull/3122
