### ISSUE TITLE
I18n 

### ISSUE THREAD

**Issue by ruspython** [keystonejs/keystone#2666]
Hello guys, I'm trying to configure i18n in my keystone app. But it doesn't work in the templates (I'm using handlebars).  That's how I do it:
keystone.js
```
// Configure i18n

i18n.configure({
	locales:['en', 'ru'],
	cookie: 'locale',
	directory: __dirname + '/locales'
});
```
routes/index.js
```
// Add-in i18n support
keystone.pre('routes', i18n.init);

```
helpers/index.js
```
	_helpers.__ = function () {
		return i18n.__.apply(this, arguments);
	};

	_helpers.__n = function () {
		return i18n.__n.apply(this, arguments);
	};

```
And two files in /locale: `en.json` and `ru.json`

It works in the middleware functions, but sets wrong language in templates.

**Comment by johannes-scharlach** [comment]
@ruspython The way you describe it, your folder is called `/locale` and you're passing a folder name of `/locales` to i18n. If the i18n module can't find a `ru.json` file in the specified folder, it will make it impossible to set that language and fall back to English.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
