### ISSUE TITLE
Old docs pages should redirect instead of 404

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2671]
From @JedWatson https://github.com/keystonejs/keystone/pull/2643#issuecomment-608963362:

> # 1. Redirects for docs pages we move?
> @jossmac @mitchellhamilton @timleslie has anybody thought about handling redirects? this changes the urls on the website, which could break links to the page. there are a few ways of handling this - we could add suggested pages to the 404 template, or we could keep a list of renamed pages and redirect. Haven't looked yet but I would expect gatsby has a solution for the second, the first could just be data we keep in the website for when we do stuff like this.
> 
> tbh [in some cases it's not a] problem because there are no internal links to the page in other parts of the site and indexers will catch up -- I'm not sure it's a big problem at this point, but definitely something we should be thinking about in the future and maybe worth just sorting out now

**Comment by jesstelford** [comment]
One work around for now is to never delete a page. Instead, replace its contents with something like:

```
This page has been moved to [/guides/foo](./guides/foo)
```

**Comment by jesstelford** [comment]
Perhaps we could auto-generate these "empty" pages during `gatsby build` which do a client-side redirect based on some config we give it of url mappings?

**Comment by Noviny** [comment]
Netlify has a section for `redirects` as well which is the best user experience, but probably requires manually tracking the changes to add them.

**Comment by molomby** [comment]
Vaguely related to #892 -- if we had a fix for both of these they'd need to work together.

**Comment by timleslie** [comment]
This issue appears out of date and no longer actionable, so I'm going to close it.
