### ISSUE TITLE
'Keystone upgrade relationships' gives error when using TypeScript with subdirectory for build

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2676]
I have a Keystone project in Typescript that builds to the subdirectory `tsout`
```
// from tsconfig.json
"compilerOptions": {
  ...
    "outDir": "tsout",
  ...
  },
```
When I run `keystone upgrade relationships` I get 

```
ℹ Command: keystone upgrade-relationships
✖
Error: --entry=index.js was passed to keystone, but 'index.js' couldn't be found in /Users/ranthony/Documents/projects/yaa-cms.
```

My `package.json` script is
```
"dev": "tsc && cross-env NODE_ENV=development DISABLE_LOGGING=true keystone --entry=tsout/index.js dev --port=4545",
```
Coincidentally I get a similar error when trying to debug under WebStorm:

```
/Users/ranthony/.nvm/versions/node/v12.14.0/bin/node /Users/ranthony/Documents/projects/yaa-cms/node_modules/@keystonejs/keystone/bin/cli.js dev
Debugger listening on ws://127.0.0.1:57962/6784997d-5f53-4000-bf21-311cf38412b3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
- Initialising Keystone CLI
ℹ Command: keystone dev
-
✖ Validating project entry file
Error: --entry=index.js was passed to keystone, but 'index.js' couldn't be found in /Users/ranthony/Documents/projects/yaa-cms.
```

**Comment by timleslie** [comment]
Hi @ra-external, can you provide a bit more info for me:

1) Can you show me exactly how you are running `keystone upgrade-relationships`
2) Do you have an script in your `package.json` for running `keystone upgrade-relationships`?

I suspect that you are running the command without passing in `--index=tsout/index.js`, but I would need to see the exact command used to be sure.

**Comment by ra-external** [comment]
@timleslie  -- That might have been the issue, as I was just running it from the command line with `keystone upgrade-relationships`(or `yarn keystone upgrade-relationships`, I can't remember at the moment).

I just put a script into `package.json` following your suggestion above

`    "keystone-upgrade": "keystone upgrade-relationships --index=tsout/index.js"`

but when I run that

`yarn keystone-upgrade`

I get the following -- perhaps I'm just missing the correct syntax on how to run the command?

```
➜ yarn keystone-upgrade
yarn run v1.22.1
$ keystone upgrade-relationships --index=tsout/index.js
ℹ Command: keystone upgrade-relationships
✖
Error: --entry=index.js was passed to keystone, but 'index.js' couldn't be found in /Users/ranthony/Documents/projects/yaa-cms.
Ensure you're running keystone from within the root directory of the project.
    at getEntryFileFullPath (/Users/ranthony/Documents/projects/yaa-cms/node_modules/@keystonejs/keystone/bin/utils.js:25:7)
    at Object.exec (/Users/ranthony/Documents/projects/yaa-cms/node_modules/@keystonejs/keystone/bin/commands/upgrade-relationships.js:196:29)
    at Object.exec (/Users/ranthony/Documents/projects/yaa-cms/node_modules/@keystonejs/keystone/bin/command-runner.js:47:30)
    at Object.<anonymous> (/Users/ranthony/Documents/projects/yaa-cms/node_modules/@keystonejs/keystone/bin/cli.js:65:4)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
```

**Comment by timleslie** [comment]
My bad, that should be ` --entry=`, not ` --index=`.

**Comment by ra-external** [comment]
That worked!  Did I just miss this or is it not clearly documented?  In case of the latter I'd advise putting that in to (new) docs on `upgrade-relationships`...

**Comment by timleslie** [comment]
It is mentioned in https://www.keystonejs.com/guides/relationship-migration#identify-required-changes

**Comment by ra-external** [comment]
Doh!
