### ISSUE TITLE
Required Relationship field does not throw error in AdminUI if left empty

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2677]
## Describe the bug

A required field that is of type Relationship does not throw an alert in AdminUI on 'save' if left empty 

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

Create a List, let's say 'Article', in which you have, say, an 'Author' field 

```
	author: {
				schemaDoc: 'Article author',
				type: Relationship,
				ref: 'Author',
				isRequired: true,
				
			},
```

When an `Article` is created and `save changes` is clicked in AdminUI, it perhaps creation of the `Article` item with a blank `Author` field.

The resulting `Article` is saved to the DB (in this case Mongo) with the required field set to `null`
```
/* 3 */
{
    "_id" : ObjectId("5e8c8c9e4a2c98acd52abffa"),
    "tag" : [ 
        ObjectId("5e8c89def1f0afa90bfefaef"), 
        ObjectId("5e8c89e5f1f0afa90bfefaf1")
    ],
    "title" : "ghi",
    "visible" : "hidden",
    "updatedAt_utc" : ISODate("2020-04-07T15:16:52.773Z"),
    "updatedAt_offset" : "+00:00",
    "createdate_utc" : ISODate("2020-04-07T14:22:22.010Z"),
    "createdate_offset" : "+00:00",
    "__v" : 0,
    "author" : null
}
```

## Expected behaviour

An alert should pop up signaling that one needs to enter a value in the required field and one should not be able to create/save an item without required fields.

**Comment by MadeByMike** [comment]
@ra-external this is really tricky to enforce and there are some known issues. See: #719

We're not quite sure if/how we should enforce required on relationships. Where two things relate to each other it becomes impossible to create the first item. We're still working through this and for now I'd recommend using a custom validation hook to meet your needs. https://www.keystonejs.com/api/hooks#field-hooks

I'm closing this in favour of #719 as the canonical issue on this topic.
