### ISSUE TITLE
Admin UI Improvements

### ISSUE THREAD

**Issue by yemi** [keystonejs/keystone#268]
I love how simple the admin ui is, although I miss a beautifully designed landing page/dashboard/latest posts kind of thing following the same idiom.

I know that keystone is very customizable and that it would be hard to make a general dashboard that would fit for every project but maybe theres at least something that could be done with how the models are displayed and maybe present latest content from each model in a nice way.

prismic.io is a content focused content management tool/system that does a good job at presenting content in the admin ui, although im not saying it cant be done in other manners.

So I'm wondering if there are any plans or work in progress for something like this?

If theres any interest in improving the admin ui i would be happy to contribute with graphical idéas or mockups on how this could look.

**Comment by morenoh149** [comment]
Closing this issue. New issues can be opened for any suggestions that came up in the thread.
