### ISSUE TITLE
Markdown Editor Image Uploads Lead?

### ISSUE THREAD

**Issue by andrew-kennedy** [keystonejs/keystone#2680]
I'm interested in trying to build into Keystone the ability to upload images into an S3 bucket from the markdown editor, and use them in said editor. I'm not really sure where to begin or the "proper" keystone way to do this, however. Anyone have any insight?

**Comment by morenoh149** [comment]
you would have to enable drag and drop on the markdown text area. I'd look at reusing `react-dnd` already used in the itemstable https://github.com/keystonejs/keystone/search?utf8=%E2%9C%93&q=react-dnd&type=Code and obviously the markdown UI https://github.com/keystonejs/keystone/blob/0e5a4a11d13d4ced058b392b119140f42116dc7e/fields/types/markdown/MarkdownField.js#L138
