### ISSUE TITLE
uploading files to s3

### ISSUE THREAD

**Issue by SamVanHoof** [keystonejs/keystone#2682]
I'm trying to upload local images while looping over the items of a collection, I keep getting the error: "[TypeError: Cannot read property 'uploadFile' of undefined]". "newQuestion.image" is not undefined when i log it.

the code:

```
for (i = 0; i < questions.length; i++) {

var newQuestion = Question.model();

try {
var s3ImageSrc = {path: "../../data_export/media/" + questions[i].image.path};
newQuestion.image._.uploadFile(s3ImageSrc);
}
catch(err){
console.log(err);
}

}
newQuestion.save();

```

model:
```
image: {
		type: Types.S3File,
		s3path: "dev"
}
```

My guess is that the image field is not initialised as a s3File type, and that's why it cant access the ._.uploadFile function.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
