### ISSUE TITLE
Unable to upload Cloudinary image through Content Field

### ISSUE THREAD

**Issue by 3lijah** [keystonejs/keystone#2683]
# Bug report

## Describe the bug

I do not see the "Add Block" button for the Content field.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

After starting a fresh project with `@keystonejs/example-projects-starter`, I attempted to create a Content field for an Article:
```
keystone.createList('Article', {
  fields: {
    title: { type: Text },
    url: { type: Slug },
    status: { type: Select, options: 'draft, published' },
    postDate:  {
      type: DateTime,
      format: 'MM/DD/YYYY h:mm A',
      yearRangeFrom: 1901,
      yearRangeTo: 2018,
      yearPickerType: 'auto',
    },
    body: {
      type: Content,
      blocks: [
        Content.blocks.blockquote,
        Content.blocks.link,
        Content.blocks.orderedList,
        Content.blocks.unorderedList,
        Content.blocks.heading,
        [CloudinaryImage.blocks.image, { adapter: cloudinaryAdapter }],
      ],
    },
  }
})
```

1. Log In
2. Navigate to Articles
3. Create new Article
4. There is not button to add block or upload image
5. Open Web Inspector
6. The Add Block button is positioned `left: -9999px; top: -9999px;`

## Expected behaviour

I should see a button to add blocks and clicking it should show me a button to upload an image.

## Screenshots

<img width="735" alt="Screen Shot 2020-04-07 at 3 27 34 PM" src="https://user-images.githubusercontent.com/1908949/78711153-8788fd80-78e4-11ea-8bf8-118410853ba9.png">

<img width="740" alt="Screen Shot 2020-04-07 at 3 27 42 PM" src="https://user-images.githubusercontent.com/1908949/78711368-db93e200-78e4-11ea-9526-faced5e80f49.png">

## System information

- OS: macOS
- Browser: Tested in Chrome & Firefox

## Additional context

No error messages in the console. I was able to successfully create an article and view it but the button still does not display.

@keystonejs/fields 8.0.0
@keystonejs/field-content 5.4.5
@keystonejs/keystone 7.1.0

**Comment by 3lijah** [comment]
I am now seeing this message in the console:
```[GraphQL error]: Message: select "t0".* from "public"."_Block_Article_cloudinaryImage" as "t0" left outer join "public"."undefined" as "t1" on "t0"."undefined" = "t1"."id" where true and "t0"."undefined" = $1 - relation "public.undefined" does not exist, Location: [object Object], Path: Article,body,cloudinaryImages```

Note: I'm using Postgres/KnexAdapter for this project.

**Comment by 3lijah** [comment]
Reverting to `field-content@5.4.1` appears to fix the issue.

**Comment by nyinyinyanlin** [comment]
I had the same problem. How do you revert to field-content@5.4.1?

**Comment by 3lijah** [comment]
In the package.json set the line to`"@keystonejs/field-content": "5.4.1",`
then delete your node_modules folder
then in your terminal do `npm install` or `yarn install`

**Comment by jpask1392** [comment]
Has anyone found a solution to this? I'm seeing the same missing button behavior.  I reverted back to `field-content@5.4.1` but experienced the Multiple errors in BaseKeystoneAdapter.postConnect() error.

Running-
@keystonejs/keystone: 9.0.0
@keystonejs/fields: 10.0.0
@keystonejs/field-content: 6.0.0

**Comment by zamkevich** [comment]
The bug still actual, any update here?

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
