### ISSUE TITLE
Multiple dependsOn for same object?

### ISSUE THREAD

**Issue by hamadkh** [keystonejs/keystone#2684]
```
name: { type: Types.Select, options:['one', 'two'],index: true, initial: true},

Dome: {type: Types.Select, options:['Teide Dome 1','Teide Dome 2'], dependsOn: {name:'one'}},
```

Lets say now I also want to add another set of new options for another dependsOn in the same 'Dome' object, I dont want to create another one.

I want to be able to have multiple dependOn and Option Conditions for one single 'Dome'.

**Comment by geloescht** [comment]
See the docs here: http://keystonejs.com/docs/database/#fields-conditional
Please note that there is an unresolved issue with dependsOn in v0.4, where behaviour differs from v0.3: #2575

Please close this issue if this answered your question.

**Comment by geloescht** [comment]
Ah, I think I misunderstood. You want to offer different options depending on the value of another field, right? AFAIK this is not possible for select fields currently. It might be possible for relationship fields using the filter option, though.

**Comment by geloescht** [comment]
See #2217

**Comment by hamadkh** [comment]
What I want is not possible with relationship type.  I want a many to many options availability.

```
name: { type: Types.Select, options:['Canary', 'Chile ', 'Hawaii '],index: true, initial: true},
	Dome: {type: Types.Select, options:['Teide Dome 1','Teide Dome 2'], dependsOn: {name:'Canary'}},
	Dome: {type: Types.Select, options:['Chile Dome 1','Chile Dome 2'], dependsOn: {name:'Chile'}},
	Dome: {type: Types.Select, options:['Hawaii Dome 1','Hawaii Dome 2'], dependsOn: {name:'Hawaii'}}, 

```
So i want it to give me options:['Chile Dome 1','Chile Dome 2'] for dome, when I select chile in the 'name' options. Same for other two conditions. Of course it is ignoring the first two options and always giving the last options for any condition.

**Comment by geloescht** [comment]
Well, imo you can do it like this, with an aditional list called Domes (you'd need to put your data about domes there):
```javascript
Domes.add(
{
  name: { type: String, required:true, initial: true},
  location: { type: Types.Select, options: [ 'Canary', 'Chile', 'Hawaii'], required:true, initial: true }
});

OtherList.add(
{
  name: { type: Types.Select, options:['Canary', 'Chile ', 'Hawaii '],index: true, initial: true},
  Dome: {type: Types.Relationhip, ref: 'Dome', filters: { location: ':name' } }
});
```

See here for more information on the filters property on Relationship fields: http://keystonejs.com/docs/database/#relationship-fields

If you still feel a relationship is the wrong field type (for example if you dislike that the options for Dome are defined in the database instead of in code), please follow #2217 .

**Comment by hamadkh** [comment]
Thanks for your help but i dont want a List for Dome, what I really want is to be able to have multiple options sets and DependsOn for the same field.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
