### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by zephyrus23** [keystonejs/keystone#2695]
Upon running `npm install -g generator-keystone` the following warning is issued:

`npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'`

**Comment by zephyrus23** [comment]
Upon running `yo keystone` the following NPM warnings were returned during setup:

`npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade`

`npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm`

`npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

`npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.`

`npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

**Comment by hamadkh** [comment]
I received these warnings too, but my generator still ran properly and the project is running fine also. Are you facing any issues going forward?

**Comment by geloescht** [comment]
Can you trace those dependencies to the corresponding package.json files? Afaict, keystone itself doesn't directly depend on any of those package versions except for jade, which is already known. It's probably dependencies of keystone at fault and maybe also generator-keystone creates those outdated dependencies. If so, please file a report at keystonejs/generator-keystone.

**Comment by mxstbr** [comment]
There's nothing actionable for us to do here, so I'll close this issue for now!
