### ISSUE TITLE
Enhancement of the implementation of relationship filters in the UI not working as expected

### ISSUE THREAD

**Issue by macsdragon** [keystonejs/keystone#2703]
I saw that there has been a pull request [462](https://github.com/keystonejs/keystone/pull/462) for Enhancement of the implementation of relationship filters in the UI. According to that request in newer versions of keystonejs the relationship field filters should update the relationship select list on the client-side if the filter value changes. I try to implement that feature however this seems to only work if on the filtered field a selection has been made and has subsequently been cleared. 

For instance if the relationships of Field B are filtered by the values of Field A, changing the value of Field A does not change the filtered options of Field B if the value of Field B is empty. I does update the filters of Field B only if Field B has a non empty value and that value has been cleared. Is this supposed to work like this? Shouldn't Field B be dynamically filtered on the client-side independent of whether there has been a selection made and cleared on Field B? 

I am using keystonejs version 0.3.17

**Comment by MacIt** [comment]
Had exactly the same issue here, with earlier version, 0.3.x. Expect to fix it soon.

**Comment by Independente** [comment]
also in 0.3.19

**Comment by mzahidriaz** [comment]
I've faced the exact same issue.
Solved it using dependsOn

field B dependsOn field A

This way by changing the value of field A field B re-renders itself with new query

**Comment by lukezona** [comment]
I'm having the same issue with 0.3.21:

Test: {
 article : { Types.Relationship, refPath: 'Article' ... }
 author : {Types.Relationship, refPath: 'Author', filters { article: ':article' } ... }
}

But it still shows every Author without filtering it on the article selected before, of course I checked twice the models fields and they are correct.

@mzahidriaz What did you write as dependsOn condition to make it working again?

**Comment by mzahidriaz** [comment]
try

`author : {Types.Relationship, refPath: 'Author', dependsOn:{article: true}, filters { article: ':article' } ... }`

**Comment by thewolff** [comment]
dependsOn no longer appears to be working on such a way where this is a valid solve. Any ideas on how to get this to work?

**Comment by Noviny** [comment]
Closing this as an issue as we are no longer supporting 0.3. If this is still an issue you are experiencing this in 4, please reopen.

**Comment by dufemeng** [comment]
Did this bug fixed ?
