### ISSUE TITLE
Not able to run the keystone behind the Nginx reverse proxy

### ISSUE THREAD

**Issue by shivathejas** [keystonejs/keystone#2704]
# Question about Keystone

GitHub Issues are reserved for Bug reports and Feature requests.

The best place to get a question answered is sign-up to our Slack: http://community.keystonejs.com/

**Comment by jesstelford** [comment]
Hey @shivathejas can you have a look over this and see if any of it solves your problem?
https://gist.github.com/molomby/6fa22c165e0025f0f83d55195f3c6e37

**Comment by shivathejas** [comment]
Hi @jesstelford , The above solution was helpful. Now I can hit the endpoint. But when I'm trying to login to my admin UI, it is not routing to the admin dashboard. But this is working fine in my dev and UAT env but not in production. I have initialized the secureCookies to true for production.

**Comment by jesstelford** [comment]
I'll have to defer to @molomby for this one - I'm afraid this isn't my area of expertise.

**Comment by gengue** [comment]
I have the same problem using Caddy server

**Comment by MadeByMike** [comment]
@shivathejas I hope you've been able to resolve this. I'm going to close the issue as we've got instructions for running Keystone behind a reverse proxy. I've started a discussion where we can talk more about specific implementations: https://github.com/keystonejs/keystone/discussions/3097
