### ISSUE TITLE
Do the methods of keystone v3 and v4 like set(), init(), etc., are available under v5?

### ISSUE THREAD

**Issue by shivathejas** [keystonejs/keystone#2705]
# Question about Keystone

GitHub Issues are reserved for Bug reports and Feature requests.

The best place to get a question answered is sign-up to our Slack: http://community.keystonejs.com/

**Comment by Vultraz** [comment]
KS 5 is a complete redesign, so the API has changed significantly. The new docs site is here: https://www.keystonejs.com/quick-start/
