### ISSUE TITLE
Boot-up HTML page is returned when calling the GraphQL API during boot-up

### ISSUE THREAD

**Issue by Abogical** [keystonejs/keystone#2709]
# Bug report
## Describe the bug
GraphQL query requests return the HTML boot-up page when keystone is booting up, not the JSON result. Confusing static site generators.
## To Reproduce
1. Start up a keystone instance
2. Send a GraphQL query request **before** Keystone finishes booting up.

An HTML page of the boot up is returned, not the GraphQL result.

## Expected behaviour
Response made after Keystone boots up. Responding with the JSON result.

## Additional context
This issue occurs because I've deployed this CMS on [Google App Engine](https://cloud.google.com/appengine). The CMS isn't called very often, thus most of the time no instances of this CMS is made. When a GraphQL request is made, App Engine "hot starts" a new instance, taking time to boot up keystone. However keystone immediately responds to the request with the HTML boot-up page, not the JSON GraphQL result.

This is why occasionally my Gatsby build doesn't work, as it attempts to parse the HTML page from the GraphQL API as JSON. Providing the infamous cryptic error message `Unexpected token < in JSON` :cry:

Solving this issue may solve #2686

**Comment by Abogical** [comment]
In case anyone using Gatsby sees this, I've fixed the issue with the following modifications to `gatsby-config.js`:
```JavaScript
// Install this package first (npm install sleep-promise).
const sleep = require("sleep-promise");
// ...
module.exports = {
  // ...
  plugin: [
    // ...
    {
      resolve: "gatsby-source-graphql",
      options: {
        // ...
        headers: { Accept: 'application/json' },
        fetch: async (uri, options={}) => {
          let response = await fetch(uri, options);
          let json = response.json();
          response.json = async () => {
            while ((await json).loading) {
              await sleep(500);
              json = (await fetch(uri, options)).json();
            }
            return json;
          }
          return response;
        }
      },
    },
  ]
}
```

**Comment by MadeByMike** [comment]
Interesting, however if Keystone is booting and we remove the loading message. Gatsby is going to get a 404, since the GraphQL app is not available yet. There is no way to serve data before the application has started.

I understand the issue with servers sleeping and we're looking for better support for serverless infrastructure in future but until the the only suggestion I have is a workaround similar to what you've suggested or deploy to a server that doesn't sleep.

**Comment by molomby** [comment]
> .. if Keystone is booting and we remove the loading message. Gatsby is going to get a 404, since the GraphQL app is not available yet.

It won't 404, the request will be held until either the service is ready or the request times out. In many cases this will actually work.

We're looking to overhaul the start up process pretty soon so this'll likely be resolved in the coming months.

I don't think things the waiting screen HTML should be used outside the dev environment. Opening ports before the app is actually ready to serve traffic breaks assumptions most hosting setups make and returning HTML from a JSON API is generally a bad idea.

**Comment by Abogical** [comment]
> I haven't used GAE for ages but I'm pretty sure it won't 404. The request will likely be queued until either the service is ready or the request times out.

As @molomby said, the fix to the issue is to *hold* the request until Keystone is ready. Sorry if that wasn't clear but the issue shouldn't be closed yet.

> I don't think things the waiting screen HTML should be used outside the dev environment. Opening ports before the app is actually ready to serve traffic breaks assumptions most hosting setups make and returning HTML from a JSON API is generally a bad idea.

I disagree. The HTML boot-up page can still remain outside the dev environment, just not when querying the GraphQL endpoint (usually `/admin/api`). It's still nice to have the boot-up page when entering the main page. A port could still be open before Keystone boot up, but may queue requests to its GraphQL endpoint until it's ready to respond.
