### ISSUE TITLE
It is not possible to activate CORS for the default application. 

### ISSUE THREAD

**Issue by aseleznev** [keystonejs/keystone#2710]
It is not possible to activate CORS for the default application. 

I tried
```
module.= {
    configureExpress: app => {
        app.use(cors({ origin: 'http://localhost:8080' }));
    },
    keystone,
    apps: [new GraphQLApp(), new StaticApp({ path: staticRoute, src: staticPath }), adminApp].
};
```
and
```
module.= {
    keystone,
    apps: [new GraphQLApp(), new StaticApp({ path: staticRoute, src: staticPath }), adminApp],
    cors: { origin: 'http://localhost:8080' },
    distDir
};
```
But "Access-Control-Allow-Origin" does not appear in the request header.

<img width="444" alt="изображение" src="https://user-images.githubusercontent.com/2737115/79039149-b4952300-7bf8-11ea-8205-f15b34b78043.png">

- OS: macOS
- Browser: chrome, firefox

**Comment by npinon** [comment]
@aseleznev how have you resolve the issue ? I'm facing the same problem

**Comment by aseleznev** [comment]
> @aseleznev how have you resolved the issue ? I'm facing the same problem

In my case the question was incorrect, I tried to activate CORS on the backend and looked at the request headers from the frontend. Describe your problem in detail, maybe I can give you a hint.

**Comment by npinon** [comment]
In fact I was trying to call an external API from a custom field (in Field.js, client side) and I was facing CORS issue.
I have solved the problem by creating an aux query server side which is calling my external API. Client side I juste have to call my GraphQL API to retrieve the informations.
It is much more secured and working well :)
