### ISSUE TITLE
Test environment server's date field doesn't work. 

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2711]
Something is slightly off with the test server's date popup field on Firefox. It works fine on Chrome, but in FF I am unable to click the arrow keys to change the month, resulting in me only being able to choose dates from the current month. 

I've got a live site built on the npm version of keystone-generator, and it's not an issue here. 

To reproduce, run `node test/e2e/server.js --notest` in your keystone root directory. You can sign in with username 'test@test.e2e' and password 'test'. Once PR #2709 is merged, there will already be a model, "Dates", which will contain a date field for you to test on.

**Comment by jstockwin** [comment]
@mxstbr @yn5 Should this issue now be closed?

**Comment by mxstbr** [comment]
Yeah, thanks I missed it! :+1:
