### ISSUE TITLE
"Getting started" doesn't work for postgres

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#2712]
# Bug report

## Describe the bug

Open https://www.keystonejs.com/quick-start/#installing-keystone and follow instructions.
Run command for postgres:
```
$ yarn create-tables
Error: Attempted to execute keystone.query() before keystone.prepare() has completed.
    at Keystone.executeQuery (/app/my-keystone-app/node_modules/@keystonejs/keystone/lib/Keystone/index.js:113:13)
    at Object.module.exports [as onConnect] (/app/my-keystone-app/initial-data.js:10:22)
    at /app/my-keystone-app/node_modules/@keystonejs/keystone/lib/Keystone/index.js:460:37
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createTables (/app/my-keystone-app/node_modules/@keystonejs/keystone/bin/commands/create-tables.js:11:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Screenshots
![image](https://user-images.githubusercontent.com/1394025/79056296-6b2aef00-7c5d-11ea-9eac-3c6e12d15106.png)

## Question

Is the Keystone project support postgres as the first-class database? Or it's some experimental feature.
I want to use the Keystone with postgres for my new project is this a good idea? Or it'll be better to it with mongo?

**Comment by pahaz** [comment]
My workaround hotfix:

```
const { asyncForEach } = require('@keystonejs/utils');
const chalk = require('chalk');

const createKeystoneTables = async keystone => {
  await asyncForEach(Object.values(keystone.adapters), async adapter => {
    if (!adapter._createTables) {
      console.info(chalk.yellow.bold(`create-tables is only required for KnexAdapter`));
      return;
    }
    try {
      console.log('Creating tables...');
      await adapter._createTables();
    } catch (e) {
      if (e.message.includes('already exists')) {
        console.fail(chalk.red.bold(`Table already exists`));
        console.warn('Create tables should be used on an empty database');
        console.warn(e.message);
      } else {
        console.error(e);
      }
    }
  });
}
```

You can call it for example on `Keystone.onConnect` event:
```
...
const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new Adapter(adapterConfig),
  onConnect: createKeystoneTables,
});
...
```

**Comment by Vultraz** [comment]
No, Postgres support is indeed first-class, not an experimental feature. I think this is a recent regression.

**Comment by pahaz** [comment]
But there is lots of docs only with Mongo examples. Like here: https://github.com/keystonejs/keystone/pull/2728

And there is quite hard to use Keystone with Postgres without better migration support.
But thanks!

**Comment by timleslie** [comment]
@pahaz You're correct that a lot of the docs don't cover postgres as well as Mongo. This is something we're currently trying to address. The postgres implementation is on the same footing as the mongo implementation, it's just the docs and dev workflow which are not yet up to scratch. We are actively using postgres in production environments, but we need to make the experience of getting into production much simpler for new users. This is something we're actively working on at the moment, so we appreciate any feedback, such as this bug report 🙏

**Comment by pahaz** [comment]
@timleslie thanks for your reply. In my opinion, it's hard to use it with Postgres, because of migrations. 
It'll be useful with migrations examples. Thanks!
