### ISSUE TITLE
Clarification about securing the API request using only token

### ISSUE THREAD

**Issue by hayanisaid** [keystonejs/keystone#2716]
# Question about Keystone

I have a concern about securing all the API request by using just a token, but with KeystoneJs for example in this case,  if I sent a request from the client to create a user it returns this error message `{"errors":[{"message":"You do not have access to this resource","name":"AccessDeniedError","time_thrown":"2020-04-12T03:02:51.490Z","data":{"type":"mutation","target":"createUser"},"path":["createUser"],"uid":"ck8wgqkbo000iv40n6qtj4qoz"}],"data":{"createUser":null},"extensions":{"tracing":{"version":1,"startTime":"2020-04-12T03:02:51.489Z","endTime":"2020-04-12T03:02:51.492Z","duration":2921067,"execution":{"resolvers":[{"path":["createUser"],"parentType":"Mutation","fieldName":"createUser","returnType":"User","startOffset":189781,"duration":230543}]}}}} `

because the access control set User to be created only by admin and he must be authenticated to do that 
```
  access: {
    read: access.userIsAdminOrOwner,
    update: access.userIsAdminOrOwner,
    create: access.userIsAdmin,
    delete: access.userIsAdmin,
    auth: true
  }```

My question is I just want a way to set a token as a base to be able to create new users from the front end?

**Comment by Vultraz** [comment]
That's just the auto-generated default access control setup for the `User` list when using the `create-keystone-app` starter. You can always change the `create` access to something different to accommodate your own access logic.

**Comment by hayanisaid** [comment]
Hey, @Vultraz  thanks for the answer, but I generally need a way to secure the GraphQL API using a token, I need a way to set up middleware for every request and check if the request contains a token or not. is there any way to do it with the GraphQlApp()?
```
 new GraphQLApp({
      // All config keys are optional. Default values are shown here for completeness.
      apiPath: '/admin/api',
      graphiqlPath: '/admin/graphiql',
      schemaName: 'admin',
      apollo: {},
    }),
```

**Comment by Vultraz** [comment]
Not that I know of, but you could create your own [middleware app](https://www.keystonejs.com/guides/apps#custom-apps).
