### ISSUE TITLE
Did not ask to start mongod

### ISSUE THREAD

**Issue by subhog** [keystonejs/keystone#272]
Nowhere during generating my application I was instructed to start `mongod` myself, I only found out it's necessary after `node keystone` failed to connect to the db. It would be more user friendly to either:

- Instruct new user to run `mongod` before starting `node keystone`,
- Run `mongod` as a part of `node keystone` by default.

**Comment by mxstbr** [comment]
This is a documentation issue, so I've moved this to https://github.com/keystonejs/keystonejs-site/issues/86!

**Comment by curtisaallen** [comment]
Hey subhog, Thanks for posting this.
