### ISSUE TITLE
Applicatin Port

### ISSUE THREAD

**Issue by shivathejas** [keystonejs/keystone#2727]
How to run the keystone V5 application on a different port?

**Comment by pahaz** [comment]
You can use `PORT` https://github.com/keystonejs/keystone/blob/78193f9c9d93655fb0d4b8dc494fbe4c622a4d64/packages/keystone/constants.js#L2 

And change `package.json` file scripts like so:

![image](https://user-images.githubusercontent.com/1394025/79560512-65e00100-80b0-11ea-9a41-f2e8226f953b.png)

Or you can use `--port` argument https://github.com/keystonejs/keystone/blob/78193f9c9d93655fb0d4b8dc494fbe4c622a4d64/packages/keystone/bin/utils.js#L60

![image](https://user-images.githubusercontent.com/1394025/79560763-ddae2b80-80b0-11ea-8e56-a63d973767ae.png)

**Comment by kilinkis** [comment]
is this still true for v6 @pahaz? none of the above methods worked for me
