### ISSUE TITLE
multiple relationships within same model

### ISSUE THREAD

**Issue by johnlo1992** [keystonejs/keystone#2728]
Hi!

I was wondering how to implement multiple relationships within the same model. For example:

Project Model:

var keystone = require('keystone');
var Types = keystone.Field.Types;
Project.add(
	'People',
	{
		role1: { type: Types.Relationship, ref: 'People', index: true},
		role2: { type: Types.Relationship, ref: 'People', index: true},
		role3:  { type: Types.Relationship, many: true, ref: 'People', index: true},
	}
);`

People Model:

var keystone = require('keystone');
var Types = keystone.Field.Types;
People.add(
	'Contact',
	{
		name: {type: String, index: true},
		phone: {type: String},
	}
People.relationship({ path: 'project', ref: 'Project', refPath: 'role1' });
People.relationship({ path: 'project', ref: 'Project', refPath: 'role2' });
People.relationship({ path: 'project', ref: 'Project', refPath: 'role3' });

When I implement these two models it seems relationship projects show up only for people who are in role3

Thanks!

**Comment by mxstbr** [comment]
We're trying to keep our issue tracker free of support questions, so I'll close this issue for now! 

Please post this question on either [StackOverflow](https://stackoverflow.com) or ask it in our [Gitter channel](https://gitter.im/keystonejs/keystone)!
