### ISSUE TITLE
/admin/signin always loading after push to server

### ISSUE THREAD

**Issue by azolyoung** [keystonejs/keystone#2729]
# Bug report
Hi there, thanks for the awesome project, I'm new to here and NODEJS, I had pushed my keystone5 project to my AWS server (a t2.small server), and the keystone5 is running by docker.  After everything is done, I can open the admin page, then type the admin@example account and password, tap login, and it just keeps loading page(white page), can't view the admin panel, but the RESTAPI in my keystone5 is working fine.

in addition, the keystone5 was worked fine in my local env, but the admin panel not working in my AWS server, and the console does not output any error about it.

this is my dependencies:
"dependencies": {
        "@fidm/x509": "1.2.1",
        "@keystonejs/adapter-mongoose": "8.0.1",
        "@keystonejs/app-admin-ui": "5.9.5",
        "@keystonejs/app-graphql": "5.1.5",
        "@keystonejs/app-static": "5.1.1",
        "@keystonejs/auth-password": "5.0.1",
        "@keystonejs/fields": "9.0.0",
        "@keystonejs/keystone": "8.1.1",
        "@keystonejs/list-plugins": "5.1.4",
        "alipay-sdk": "3.0.8",
        "axios": "0.19.2",
        "big-integer": "1.6.48",
        "cross-env": "7.0.0",
        "crypto": "1.0.1",
        "googleapis": "48.0.0",
        "graphql": "14.6.0",
        "immutable": "4.0.0-rc.12",
        "keystone": "4.2.1",
        "mysql": "2.18.1",
        "restful-keystone": "0.3.0",
        "restify": "8.5.1",
        "semver": "7.1.3",
        "string-random": "0.1.3",
        "uuid": "7.0.2",
        "xml2js": "0.4.23",
        "xmlreader": "0.2.3"
    }

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Release the codes to  server
2. docker-compose build
3. docker-compose up -d
4. type the admin URL on the chrome
5. It will show the login form, type the example account, click login
6. it just loading, and the current URL is /admin/signin

## System information

- OS: AWS Linux AMI
- Browser (if applies) chrome

**Comment by ralexrdz** [comment]
having same results. Aparently /admin.123987asadu132.bundle.js is being looked differently by the front. I'll keep you posted

**Comment by econveyir** [comment]
I am having the same issue, except I am not deploying to docker. However when running the build/production environment locally. 

Steps to reproduce are:

1. Install the sample `todo` app by running through the wizard: https://www.keystonejs.com/ 
2. After everything is set up, run `npm run build`
3. Start build, `npm run start`
4. Try logging in inside `/admin/signin`, you will notice it refreshes the page but never actually opens the admin dashboard.

**Comment by thekevinbrown** [comment]
The best writeup at the moment is here: https://gist.github.com/molomby/6fa22c165e0025f0f83d55195f3c6e37

**Comment by econveyir** [comment]
thank you! @thekevinbrown

**Comment by thekevinbrown** [comment]
I'll assume that's resolved the issue, please open another if I'm wrong!

Also, there is an effort to put this writeup into the docs themselves.

**Comment by 3lijah** [comment]
With my host, I don't have access to change the `X-Forwarded-Proto` header in the requests. Is this something that can be changed in keystone?
