### ISSUE TITLE
Can't get css, js files in admin after deploying keystonejs app. What should i do to make it work?

### ISSUE THREAD

**Issue by prostoandrei** [keystonejs/keystone#2731]
Example here http://clevercontent.org/keystone/signin

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by prostoandrei** [comment]
Ok, thank you.
