### ISSUE TITLE
Add example or document for Location type field

### ISSUE THREAD

**Issue by kevinian** [keystonejs/keystone#274]
Hello,

If more documents about how to query of filter locations or some more examples about that exists, it will be useful.

Can anyone explain me how can I implement a filter based on location without google map?

Best regards,
Kevin

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/add-example-or-document-for-location-type-field
