### ISSUE TITLE
Should be able to cap revisions collection

### ISSUE THREAD

**Issue by r1b** [keystonejs/keystone#2742]
If history is enabled for a list & the data is frequently modified the associated revisions collection grows quickly. This is easy to add since it is [supported in mongoose](http://mongoosejs.com/docs/guide.html#capped) but I am hesitant to set a hard & fast limit for all revisions collections. In some cases it may not be necessary to cap the collection, in others it may be impossible (e.g: legal requirements for audit history).

**Comment by r1b** [comment]
I just realized this may not be appropriate as an issue anymore, if so feel free to close

**Comment by mxstbr** [comment]
Thanks @r1b, that sounds like a good idea! Would you mind moving it to https://productpains.com/product/keystonejs? Thanks!
