### ISSUE TITLE
nodejs cannot start recent keystoneapp

### ISSUE THREAD

**Issue by acastro** [keystonejs/keystone#2746]
I've migrated my application to a new server using the same version of nodejs and a fresh database, however I receive this error:

Starting keystone
------------------------------------------------
Applying update 0.0.1-admins...
node.js:433
        callback();
        ^

TypeError: callback is not a function
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
