### ISSUE TITLE
Docs don't specify the supported date and time formatting tokens for DateTime and CalendarDay

### ISSUE THREAD

**Issue by dimitriaatos** [keystonejs/keystone#2748]
From the DateTime docs:
> **format**
Defines the format of the string that the component generates. For example, `MM/DD/YYYY h:mm A`.

A link could be added, pointing to the table of tokens of the date utility library used for formatting.

**Comment by pahaz** [comment]
You can find the example here: https://github.com/keystonejs/keystone/blob/3fb6e901602ff2de7f2ca7b457ad157416d71d3f/demo-projects/blog/schema.js#L45-L49

And you can find more info about formats here: https://date-fns.org/

Keystone uses `date-fns` package at the moment:
https://github.com/keystonejs/keystone/blob/3fb6e901602ff2de7f2ca7b457ad157416d71d3f/packages/fields/package.json#L48

**Comment by timleslie** [comment]
Thanks for raising this as an issue @dimitriaatos, it's now been fixed 👍 I've added a few examples along with a link to the full docs of the underlying library (date-fns) https://www.keystonejs.com/keystonejs/fields/src/types/calendar-day/
