### ISSUE TITLE
Signin redirect not working

### ISSUE THREAD

**Issue by tuan23** [keystonejs/keystone#2753]
`keystone.set('signin redirect', '/redirect-url');` used to work, but isn't working anymore.

Looks like it's missing from the new `createDynamicRouter.js` (https://github.com/keystonejs/keystone/blob/master/admin/server/app/createDynamicRouter.js)

Signin redirect option in [Keystone Doc](http://keystonejs.com/docs/configuration/#options-database).

@mxstbr Could you have a look and confirm if it's the case?

Thanks!

**Comment by mxstbr** [comment]
That is definitely true, will fix asap!

**Comment by jdr0dn3y** [comment]
Confirmed in master.
