### ISSUE TITLE
post:routes hook missing

### ISSUE THREAD

**Issue by matankadosh-softangible** [keystonejs/keystone#2756]
Hi, Is there a hook for the post:routes,
I really need the req.route property which exists only after the route has been initialized.
The think is that the only hook currently supports this property is pre:render, but this hook is being called after the route controller.

How can I make that happen?

**Comment by mxstbr** [comment]
@creynders is the master of the hooks, so I'll let him chime in here. I'm not sure if this is a bug or a feature request, to be honest!

**Comment by matankadosh-softangible** [comment]
@mxstbr this is more of a feature request.
what i did for now was to wrap the keystone's View constructor.
using `keystone.set('pre:view',function(req,res,next){})` and in the constructor to check if `pre:view` exists and if so add `view.on('init',keystone.get('pre:view'))`

**Comment by mxstbr** [comment]
Ah right, could you post it on ProductPains then? https://productpains.com/product/keystonejs

I'll close this issue, we're trying to keep the issue tracker free of feature requests. :blush:
