### ISSUE TITLE
Response for preflight has invalid HTTP status code 404

### ISSUE THREAD

**Issue by stijn26** [keystonejs/keystone#2757]
Hi,

On my Keystonejs api I want to do a post request. I'm doing this in Angular 2:

`return this.http.post(this._employeesUrl + id, JSON.stringify({firstName:'Joe',lastName:'Smith'}), {headers:headers}) `

When the request gets fired, I get this error:
`
Response for preflight has invalid HTTP status code 404`

My api endpoint looks like this:

```
exports.update = function(req, res) {
  Employee.model.findById(req.params.id).exec(function(err, item) {

    if (err) return res.apiError('database error', err);
    if (!item) return res.apiError('not found');

    var data = (req.method == 'POST') ? req.body : req.query;
    
    item.getUpdateHandler(req).process(data, function(err) {
      
      if(req.body.firstName){
        item.firstName = req.firstName;
      }
      if(req.body.lastName){
        item.lastName = req.body.lastName;
      }
      
      if (err) return res.apiError('create error', err);
      
      res.apiResponse(
        200
      )
      
    });
  });
}
```
How can I resolve this? Is this a bug? It seems like i need to enable OPTIONS in cors.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

To answer your question: I don't know the root of your problem, but if you indeed need to enable OPTIONS in cors this is only supported on `master`. (ref #2730)
