### ISSUE TITLE
possible to store an array of child list items in a list, and have the child list hidden from admin interface?

### ISSUE THREAD

**Issue by r3wt** [keystonejs/keystone#2766]
http://stackoverflow.com/questions/37056832/building-faq-lists-with-keystone-lists

basically my idea was to use another list for the individual question/answers inside the `FAQ` list. is this even possible?

**Comment by pll33** [comment]
Answered your post on Stack as well, but for the hidden from admin interface option, it would be something like:

`items: { type: Types.Relationship, ref: 'Pair', many: true, hidden: true }

**Comment by r3wt** [comment]
Yes, i've already accomplished it in this way. but coming from a UX perspective, its much more convenient for the user to be able to add/edit/delete these inline from within the FAQ record. after thorough investigation, i have determined was not possible. I appreciate your time though.

**Comment by pll33** [comment]
I suppose you could also remove the hidden attribute which would let you add/delete items inline in the FAQ record. To edit the items, you would still need to go to a particular item though.

**Comment by r3wt** [comment]
Well, i might end up giving that a try. hopefully in the future inline editing will be possible. Today was my first day with keystone.js(and on the job) but my i really like it already. now i have to learn react though.
