### ISSUE TITLE
MailChimp instead of Mandrill

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#2769]
Can Keystone migrate to MailChimp from Mandrill -

See:-

On April 27, Mandrill became a paid MailChimp add-on. Sending for any accounts that were not merged has been disabled, but you may still log in to retrieve your data, close your account, or merge your Mandrill and MailChimp accounts to resume sending immediately. More information about this transition is in this blog post.

**Comment by w01fgang** [comment]
Keystone have support of [mailgun](http://mailgun.com), documentation isn't updated yet, look at this PR #2752

**Comment by mxstbr** [comment]
We're trying to keep the issue tracker free of feature requests, please submit this on product pains: https://productpains.com/product/keystonejs 

Thanks! :+1:

**Comment by JedWatson** [comment]
That Product Pains note may have jumped the gun a little, this is already implemented and just related documentation / examples to be updated. I'm going to reopen this since ensuring that's complete is more of a technical task to be done than a feature to be added.

**Comment by katopz** [comment]
ref https://github.com/keystonejs/keystone-demo/issues/47

**Comment by mikey0000** [comment]
Yup need some documentation around mailgun which I am using, am happy to write it once I figure it out. Found the key names but keystone is still complaining that I haven't set the mailchimp/mandrill keys this is in 4.0 branch.

**Comment by JedWatson** [comment]
@mikey0000 I've actually _almost_ finished rewriting email support for Keystone - would love your feedback, see https://github.com/keystonejs/keystone-email

**Comment by mikey0000** [comment]
Oh great, Will take a look. Meanwhile I found the line I needed to get mailgun working from the sydjs site example.

**Comment by mxstbr** [comment]
`keystone-email` is now finished and we have full support for Mandrill and Mailgun, so closing this!
