### ISSUE TITLE
Unable to upload files to S3 bucket in production

### ISSUE THREAD

**Issue by chalupagrande** [keystonejs/keystone#2771]
# Bug report
Unable to upload photos to s3 bucket. 

## Describe the bug
In production, when trying to create upload a file using the S3FileAdapter, after clicking the "Create", the button is disabled and it seems to be loading, but then nothing happens. The web console displays: 
`[Network error]: ServerParseError: Unexpected token < in JSON at position 0`

The s3 bucket shows no evidence of the file, and the record is not created

## To Reproduce
Deploying to Dokku instance on a digital ocean droplet. 
Using [this index.js file](https://gist.github.com/chalupagrande/ef9a97819e3dbea7e00138392c6ab34c)

## Expected behaviour
The record would be created, and the file would upload to the s3 bucket.

## System information
- dokku version 0.19.12
- mongo version 4.2.5

## Other Context: 
[Here is the stack trace](https://gist.github.com/chalupagrande/ac7e15a6f4601c34114d73d5039bdc28)

**Comment by chalupagrande** [comment]
S3FileAdapter not working on node 13.  Changed it to 12 and it worked fine.
Leaving this open for others to find.

**Comment by MadeByMike** [comment]
We're moving some instructions related to this bug into the docs. The closed issue will still be discoverable and this thread provides more detail: #2101
