### ISSUE TITLE
Unknown problem has bothered me for a few days, can you help me?

### ISSUE THREAD

**Issue by yanwenjun** [keystonejs/keystone#2773]
ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/ListTable.js 102:5
Module parse failed: Unexpected token (102:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // Functional Components
> type SortLinkProps = {
|   handleSortChange: Function,
|   active: boolean,

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/CreateItemModal.js 134:6
Module parse failed: Unexpected token (134:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const formComponent = useCallback(
|     forwardRef((props, ref) => (
>       <form ref={ref} autoComplete="off" onSubmit={_onCreate} {...props} />
|     )),
|     [_onCreate]

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/List/Pagination.js 13:4
Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   return (
>     <Pagination
|       currentPage={data.currentPage}
|       id={CYPRESS_TEST_ID}

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/Item/AddNewItem.js 16:4
Module parse failed: Unexpected token (16:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const cypressId = 'item-page-create-button';
|   return (
>     <Tooltip content="Create" hideOnMouseDown hideOnKeyDown>
|       {ref => (
|         <IconButton

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/List/Filters/ActiveFilters.js 23:4
Module parse failed: Unexpected token (23:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   return (
>     <Fragment>
|       {filters.length
|         ? filters.map(filter => {

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/UpdateManyItemsModal.js 28:11
Module parse failed: Unexpected token (28:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     this.state = { item, selectedFields, validationErrors, validationWarnings };
|   }
>   onUpdate = async () => {
|     const { updateItem, isLoading, items } = this.props;
|     const { item, selectedFields, validationErrors, validationWarnings } = this.state;

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/providers/List.js 29:4
Module parse failed: Unexpected token (29:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   };
|   return (
>     <ListContext.Provider
|       value={{
|         list,

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/List/index.js 37:2
Module parse failed: Unexpected token (37:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const HeaderInset = props => (
>   <div css={{ paddingLeft: gridSize * 2, paddingRight: gridSize * 2 }} {...props} />
| );
| 

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/List/Management.js 43:4
Module parse failed: Unexpected token (43:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   return (
>     <Fragment>
|       <FlexGroup align="center">
|         <SelectedCount>

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/List/Search.js 44:4
Module parse failed: Unexpected token (44:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // webkit, so we apply the attribute to a form tag here.
|   return (
>     <form
|       css={{ ...elementOffsetStyles, position: 'relative' }}
|       autoComplete="off"
ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/List/FieldSelect.js 50:4
Module parse failed: Unexpected token (50:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   return (
>     <Options
|       isOptionSelected={isOptionSelected}
|       getOptionValue={getOptionValue}

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/ToastContainer.js 6:32
Module parse failed: Unexpected token (6:32)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { DefaultToastContainer } from 'react-toast-notifications';
| 
> const ToastContainer = props => <DefaultToastContainer {...props} css={{ zIndex: 3 }} />;
| 
| export default ToastContainer;

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/Popout.js 79:4
Module parse failed: Unexpected token (79:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }) => {
|   const defaultTarget = handlers => (
>     <Button variant="subtle" appearance="primary" {...handlers}>
|       {buttonLabel}
|       <DisclosureArrow />

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/PageLoading.js 7:4
Module parse failed: Unexpected token (7:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default function PageLoading() {
|   return (
>     <div
|       css={{
|         height: 200,

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/providers/AdminMeta.js 88:9
Module parse failed: Unexpected token (88:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   };
| 
>   return <AdminMetaContext.Provider value={value}>{children}</AdminMetaContext.Provider>;
| };
| 

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/pages/Item/ItemId.js 8:9
Module parse failed: Unexpected token (8:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const ItemId = () => {
|   let { id } = useItem();
>   return <IdCopy id={id} />;
| };
| 

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/DeleteItemModal.js 9:4
Module parse failed: Unexpected token (9:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const [deleteItem, { loading }] = useMutation(list.deleteMutation);
|   return (
>     <Confirm
|       isOpen={isOpen}
|       onKeyDown={e => {

ERROR in /home/node/node_modules/@keystonejs/fields/node_modules/@keystonejs/app-admin-ui/client/components/DeleteManyItemsModal.js 9:4
Module parse failed: Unexpected token (9:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const [deleteItems, { loading }] = useMutation(list.deleteManyMutation);
|   return (
>     <Confirm
|       isOpen={isOpen}
|       onKeyDown={event => {

**Comment by Vultraz** [comment]
Did you try deleting `node-modules` and running `yarn` fresh?

**Comment by yanwenjun** [comment]
I use docker to run keystonejs, where node-modules are placed in the container, I have regenerated the container once (docker-compose build --no-cache), and then re-run, still the same

**Comment by jesstelford** [comment]
What command are you running to see that error?

It looks like it hasn't correctly loaded babel, so doesn't understand the JSX syntax.

**Comment by yanwenjun** [comment]
yarn dev

**Comment by jesstelford** [comment]
Thanks! And what does your `package.json` look like?

**Comment by yanwenjun** [comment]
> Thanks! And what does your `package.json` look like?

{
    "name": "@keystonejs/example-projects-starter",
    "description": "An example KeystoneJS project with a User list and Authentication.",
    "private": true,
    "version": "5.0.1",
    "author": "The KeystoneJS Development Team",
    "repository": "https://github.com/keystonejs/keystone.git",
    "homepage": "https://github.com/keystonejs/keystone",
    "license": "MIT",
    "engines": {
        "node": ">=10.0.0"
    },
    "scripts": {
        "build-doc-and-run": "/home/node/generate_api_doc.sh",
        "dev": "cross-env NODE_ENV=development keystone dev",
        "build": "cross-env NODE_ENV=production keystone build",
        "start": "cross-env NODE_ENV=production keystone start"
    },
    "dependencies": {
        "@fidm/x509": "1.2.1",
        "@keystonejs/adapter-mongoose": "8.0.1",
        "@keystonejs/app-admin-ui": "5.9.5",
        "@keystonejs/app-graphql": "5.1.5",
        "@keystonejs/app-static": "5.1.1",
        "@keystonejs/auth-password": "5.0.1",
        "@keystonejs/fields": "9.0.0",
        "@keystonejs/keystone": "8.1.1",
        "@keystonejs/list-plugins": "5.1.4",
        "alipay-sdk": "3.0.8",
        "axios": "0.19.2",
        "big-integer": "1.6.48",
        "cross-env": "7.0.0",
        "crypto": "1.0.1",
        "googleapis": "48.0.0",
        "graphql": "14.6.0",
        "immutable": "4.0.0-rc.12",
        "keystone": "4.2.1",
        "mysql": "2.18.1",
        "restful-keystone": "0.3.0",
        "restify": "8.5.1",
        "semver": "7.1.3",
        "string-random": "0.1.3",
        "uuid": "7.0.2",
        "xml2js": "0.4.23",
        "xmlreader": "0.2.3",
        "yarn": "^1.22.4"
    }
}

here is the conent of generate_api_doc.sh:

#! /bin/sh


apidoc -i ./api -o doc/

echo ‘Resetting PM2 Metadata …’
pm2 reset all
echo ‘Calling pm2-runtime …’
pm2-runtime start pm2.config.j

**Comment by jesstelford** [comment]
🤔 Looks like you've got conflicting versions of keystone installed: All the `@keystone/*` packages are for [Keystone v5](https://medium.com/the-thinkmill/introducing-keystone-5-89fd52d65368), but the `keystone` & `restful-keystone` are for [`keystone-classic`](https://github.com/keystonejs/keystone-classic).

Which version of keystone are you trying to run? It'll be a good idea to remove the dependencies you're not in need of, clear out your `node_modules`, and try again.

**Comment by mannyyang** [comment]
Getting the same issue. I generated a project through keystone cli and was following the tutorial on creating relationships. As soon as I added a relationship in the Todo list, it throws the error above. Works fine without the relationship.

**Comment by MadeByMike** [comment]
@mannyyang Sorry for the trouble but could you try upgrading all keystone packages.

**Comment by mannyyang** [comment]
@MadeByMike no trouble at all, and thanks that seemed to have resolved my issue. Looks like the cli might need the package.json template updated.

**Comment by yanwenjun** [comment]
@jesstelford  I'm using keystone v5 now, and all the codes in my project are looks like keystone5 style, I check again the version of `keystone` and `restful-keystone` on the npmjs.com,  they are 4.2.1(https://www.npmjs.com/package/keystone) and 0.3.0(https://www.npmjs.com/package/restful-keystone), May I know which version of them you using?

Thanks!

**Comment by yanwenjun** [comment]
@mannyyang
Thanks for you reply! So you just solve it by update all the  keystone packages?

**Comment by Vultraz** [comment]
@yanwenjun if you're using v5, you need to remove the `keystone` and `restful-keystone` packages from your dependencies. The v5 version of `keystone` is the `@keystonejs/keystone` package, which you already have in your dependencies.

**Comment by mannyyang** [comment]
@yanwenjun yes, I was able to resolve the issue with these versions:

```
  "dependencies": {
    "@keystonejs/adapter-mongoose": "^8.0.1",
    "@keystonejs/app-admin-ui": "^5.9.6",
    "@keystonejs/app-graphql": "^5.1.5",
    "@keystonejs/auth-password": "^5.1.6",
    "@keystonejs/fields": "^9.0.1",
    "@keystonejs/keystone": "^8.1.1",
    "cross-env": "^7.0.0"
  }
```

**Comment by jesstelford** [comment]
@yanwenjun Since you're using `yarn`, an easy way to update to the latest version of the keystone packages is:

```
yarn upgrade -S @keystone --latest
```
