### ISSUE TITLE
Sign in redirects don't work on test server restart

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2773]
To re-create:

1) run `node test/e2e/server.js --notest`
2) Open the site in your browser and log in to keystone
3) Stop and start the server, while leaving the webpage open. 
4) Click a link on the keystone page in your browser.

Your session has been destroyed by the server restarting. What should happen is you should be redirected to the sign in page to sign back in. 

What actually happens is you get a nice ... loading animation, and then a flash error: `There is a problem with the network, we're trying to reconnect..`. In the meantime, if you look at your console, it is getting spammed with get requests for `/keystone/signin` (as it should, I guess), but the sign in page never loads.

**Comment by mxstbr** [comment]
This is a really important bug we'll need to address soon. Didn't see this, so another issue with the same contents was created and a bit of dicussion happened there, so I'll close this for now! #3337
