### ISSUE TITLE
Error: Cannot find module 'connect-mongo/es5'

### ISSUE THREAD

**Issue by alirussell** [keystonejs/keystone#2775]
Our main website/keystone project has been broken by this change: https://github.com/keystonejs/keystone/commit/66404848bde2e3ab871042853daaf71b18358461

It seems in production we run on an older version of node (0.12), but at runtime the connect-mongo/es5 library does not seem to exist (we use 0.8.2).  I have bumped our node version to get around this, but thought i would bring this up as other people maybe experiencing the issue as well.

**Comment by vijaigridpro** [comment]
We are facing same issues with a keystonejs site in heroku. How do i get the site working ?

**Comment by mxstbr** [comment]
Marking this critical as we want to support Node 0.12 and up for v0.3 and v0.4.

**Comment by JedWatson** [comment]
So I think the real solution here is to upgrade the version of `connect-mongo` used in your project; but we don't want to break existing usage or force package upgrades with the current release so I've added a workaround that should fix usage with old versions.

@mxstbr if this works, maybe worth a patch release to 0.3?

**Comment by mxstbr** [comment]
Closing since this seems to be resolved? Feel free to comment again if that's not the case for you.
