### ISSUE TITLE
Changes from Admin UI branding hook #2474 not included when keystone-create-app is used

### ISSUE THREAD

**Issue by nyinyinyanlin** [keystonejs/keystone#2776]
# Bug report

## Describe the bug

Merged changes from PR [Admin UI branding hook #2474](https://github.com/keystonejs/keystone/pull/2474) are not included in `app-admin-ui` package when `yarn create keystone-app app-name` is used to initialize the project.

## To Reproduce

1. `yarn create keystone-app app-name` as in [Getting Started](https://www.keystonejs.com/quick-start/#installing-keystone)
2. Insert `new AdminUIApp({ hooks: require.resolve('./admin-ui-hooks') })` in `index.js` and create `admin-ui-hooks` folder
3. Create `admin-ui-hooks/index.js` which exports `{ logo: <myLogo /> }` 
4. `yarn dev`

## Expected behaviour

Admin-UI Sign-in page's logo should have changed to which provided in `admin-ui-hooks/index.js`.

## System information

- OS: Linux (Ubuntu 16.04)
- `yarn version: 1.22.4`
- `node version: v11.2.0`
- `npm version: 6.14.3`

## Additional context

My purpose is to change Sign-In page's logo to my custom logo using Admin-UI Hooks. I am aware that PR #2474 has already merged to master branch. However, files inside `node_modules/@keystonejs/app-admin-ui` are not updated to #2474 changes. My project has just initialized recently using `yarn create keystone-app`.

**Comment by gautamsi** [comment]
wait for this to merge https://github.com/keystonejs/keystone/pull/2739
then it will be published to get included in create-keystone-app

**Comment by nyinyinyanlin** [comment]
@gautamsi Thank you very much for your clarification. I guess this can be closed now.

**Comment by MadeByMike** [comment]
Yep, we need to do a release before that's included. Expect it soon (upgrade manually in the mean time)

**Comment by nyinyinyanlin** [comment]
@MadeByMike the change-set has been merged recently. Thank you and team for working hard on this project. 

I'm pretty new to this project and I am wondering how do I upgrade manually using yarn? My app is created using `yarn create keystone-app` and it is pushed to heroku for production server.

As I understand, heroku reads `package.json` to fetch necessary packages and build itself.

I want to make a few changes to source code, like this one #2700 and push to heroku server, so that local changes are preserved.

Could you tell me how do I do this please? I don't want to open an issue since this is not a bug, just a how-to. Thank you very much.
