### ISSUE TITLE
dependsOn with Types.Boolean and nested fields.

### ISSUE THREAD

**Issue by r3wt** [keystonejs/keystone#2778]
How should i write this code:
```js
Slider.add({
	button:{
		visible:{type: Types.Boolean, label:'Show Button'},
		text: {type: String, label:'Button Text',dependsOn: { button['visible']: true } },
		url: {type: String, label: 'Button URL',dependsOn: { button['visible']: true } }
	}
});
```

`button.text` and `button.url` depend on `button.visible` to be checked (true)

i tried all 4 of the following:

`dependsOn: { visible: true }`
`dependsOn: { button.visible: true }`
`dependsOn: { button['visible']: true}`
`dependsOn: { button: { visible: true } }`

None of these work, as the fields are never shown in the admin interface. thoughts?

**Comment by geloescht** [comment]
Nested fields are not supported in the admin UI yet. For dependsOn, maybe 'button.visible':true (note the quotes!) could work.

**Comment by r3wt** [comment]
thats a vital piece of information missing from the documentation. i already worked around it with a toplevel field and a note in our codebase as to why its not included in the button group.

**Comment by geloescht** [comment]
It's not mentioned that it works that or any other way, either. In the meantime you can use headings to group fields.

**Comment by mxstbr** [comment]
Obviously that is missing from the documentation since nested support isn't available. Feel free to upvote this if you need this feature: https://productpains.com/post/keystonejs/add-support-for-nested-repeating-schemas

**Comment by r3wt** [comment]
No skin off my neck. If you want to be butthurt little trolls everytime someone reports a mistake be my guest.
