### ISSUE TITLE
error loading bson cpp module with non root user, even when started as sudo

### ISSUE THREAD

**Issue by r3wt** [keystonejs/keystone#2779]
![img](http://puu.sh/oIsQ6/9c0196e628.png)

**Comment by geloescht** [comment]
Probably some problem during npm install. Never, ever run a server with sudo! Don't run npm as sudo unless you know how to fix unix file permissions.
Please try to remove your node_modules directory and run npm install again.
The keystone team is making an effort to keep the bug tracker free of support questions, so it might be more appropriate to ask them on StackOverflow or keystone's Gitter channel.

**Comment by r3wt** [comment]
So possible that this is related to installing global packages with sudo? i couldn't get npm to install globally without sudo, due to file permissions and the fact that root user is disabled on my machine.

**Comment by geloescht** [comment]
It is possible, yes. There are resources on the web explaining how to get npm to install globally without sudo. The most important thing to keep in mind is that only very few packages should be installed globally, namely the ones that have a command line tool. For keystone, no globally installed packages should be needed.
