### ISSUE TITLE
Password errors are less informative

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2782]
@mxstbr I noticed this while fixing the ux tests yesterday but forgot to mention it. 

If you enter a different password in the password and confirm password fields, you used to get an error saying "Passwords must match", however it now says "Error". 

If this is intended/expected then feel free to close this, but it seems like a bit of an unnecessary backwards step?

**Comment by mxstbr** [comment]
Simple oversight, will fix it!

**Comment by jstockwin** [comment]
@mxstbr let me know when you do, as the e2e tests will have to be updated too :)

**Comment by webteckie** [comment]
Not sure you should tell the evil user exactly why he/she/it couldn't login :-)  But a more informative message would certainly make sense.

**Comment by jstockwin** [comment]
@webteckie this isn't for logging in, this is when editing a model with a password field :)

**Comment by webteckie** [comment]
duh :-)
