### ISSUE TITLE
RFC: replace swig with Twig.js

### ISSUE THREAD

**Issue by r3wt** [keystonejs/keystone#2784]
Swig is no longer maintained: https://github.com/paularmstrong/swig/issues/628

Its arguably inferior to [Twig.js](https://github.com/twigjs/twig.js), which is actively maintained and supports cacheing and a host of other improvements over swig. 

This RFC is a proposal to replace swig with Twig as an option for templating language. If accepted, i will do the PR as this is very important for my team.

**Comment by mxstbr** [comment]
Is this for the generator, i.e. when running `$ yo keystone` instead of having a Swig option having a Twig option?

**Comment by r3wt** [comment]
Yes, I should have mentioned

**Comment by mxstbr** [comment]
Lets discuss in the `generator-keystone` repo! https://github.com/keystonejs/generator-keystone/issues/180
