### ISSUE TITLE
Foundation generated app.css throws server error

### ISSUE THREAD

**Issue by thomasdegry** [keystonejs/keystone#2787]
Hey all!

I tried replacing bootstrap with Foundation, I installed foundation using npm `npm install foundation-sites`. I added the components I wanted to use to my `app.scss` file like such:
```
@import "settings";
@import "foundation";
@include foundation-global-styles;
@include foundation-flex-grid;
@include foundation-typography;
@include foundation-forms;
```

For this to work I modified the gulp sass task like such, it has an `includePaths` array now that points to the `scss` folder for foundation. That folder holds `foundation.scss`.
```
gulp.task('sass', function(){
  console.log(path.join(path.dirname(require.resolve('foundation-sites')), '../scss/'));
  gulp.src(paths.style.all)
    .pipe(sass({
        includePaths: [path.join(path.dirname(require.resolve('foundation-sites')), '../scss/')]
      }).on('error', sass.logError))
    .pipe(gulp.dest(paths.style.output));
});
```

And this works! If I solely run `gulp sass`, my `app.css` file looks correct and has all the foundation components I want it to have. The problem starts when I run `node keystone` though. I get an internal server error 500 on `http://localhost:3000/styles/app.css `.

This is the error that my terminal throws:
```
GET / 304 45.651 ms
Error thrown for request: /styles/app.css
Error: File to import not found or unreadable: util/util
Parent style sheet: /Users/thomas/Developer/.../_settings.scss
    at options.error (/Users/thomas/Developer/.../node_modules/node-sass/lib/index.js:271:32)
```

Not sure why this is happening as my app.css doesn't have any import statements for `util/util` anymore. My css file seems valid, no weird stuff and is present in `/public/styles/app.css`.

Anyone a clue what I'm doing wrong?
Thanks! Let me know if I forgot to include info.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead, thanks!

I think Keystone is trying to compile the Sass files (`"Parent style sheet: /Users/thomas/Developer/.../_settings.scss"`) but it doesn't like something. Might be that whereever `utils/utils` is, isn't included in the `includePaths`? (probably something like `"../node_modules/foundation-sites/"`)

**Comment by mhoffmeyerDC** [comment]
@thomasdegry I'm having the *exact* same issue. Did you figure it out? Thanks!
