### ISSUE TITLE
Display virtual properties in admin

### ISSUE THREAD

**Issue by matankadosh-softangible** [keystonejs/keystone#2792]
Hi, 
I have a model with a virtual property,
is there a way to display the virtual property in the admin?
And also to be able to give it all the other options we can put on normal properties such as label.

**Comment by mxstbr** [comment]
This isn't yet possible.

Read the discussion in #1538 and upvote this feature on ProductPains if you want it! https://productpains.com/post/keystonejs/display-virtuals-as-noedit-fields-in-keystone-admin-ui
