### ISSUE TITLE
easy way to re-enable email functionality

### ISSUE THREAD

**Issue by Wlkrshrpe** [keystonejs/keystone#2799]
Hi,

I have a finalized/ongoing project built that during the initial `yo` command, when it asked me if i planned on using mandrill, i had opted for "no" because I did not have an account/etc on hand at the time, and was going to postpone until later 

considering the change in policy of mandrill recently, and lurking thru here, found that the new update 0.3.19 supports mailgun -- so placed the `keystone.set(etc)` relevant lines in keystone.js, and spent about another hour wondering why things weren't working, trying to dig thru code, etc 

after doing a vanilla install and purposefully selecting yes @ the mandrill option,  i find this changes what might as well be the entire project.. it adds routes.. views.. etc.. i can assume it changes some core files as well 

anyway, when i first got the console error "configure emails option" in the keystone.init, -- well, that property is missing from your documentation as well 

anyway guys, it would be really like ... *sweet* ... if you know, the project included the primary files/dependencies for sending emails **as a default** and you just place a line in keystone.js to the effect of emails: true/false ... and you know... not have my project generate with missing files.. without any clear documentation I'm even missing files... and if emails==false, just have those files be ignored rather than missing enitrely 

just some feedback from somebody who spent an hour and a half wondering why tf i couldnt find anything in the documentation 

but keystone is great overall... this was just a bit aggravating, and figured my feedback might improve experience for other users , right now the quickest fix is just using new install and importing views etc

**Comment by mxstbr** [comment]
That sounds reasonable and I definitely see value in having that!

We're trying to keep the issue tracker clean of feature requests, so I'll close this for now—would you mind resubmitting it on our Product Pains? https://productpains.com/product/keystonejs Thanks! :+1:
