### ISSUE TITLE
Change Admin UI login image

### ISSUE THREAD

**Issue by lazamar** [keystonejs/keystone#2800]
Is there a way to change the logo in the AdminUI login screen? I didn't find it in the docs.

**Comment by mathemagik** [comment]
![screen shot 2016-05-09 at 2 22 52 pm](https://cloud.githubusercontent.com/assets/16509501/15123391/921c6b1a-15f1-11e6-8b1f-6fde6c9711b5.png)

Assuming that you're talking about this little guy, it's nested pretty far in there. If you dig into node_modules/keystone/templates/includes, you'll find a file called auth-brand.jade. The image is located in node_modules/keystone/admin/public/images. 

However, I can't find a "good" way of doing it. Maybe someone else will provide a more insightful response.

**Comment by jossmac** [comment]
@lazamar It seems this is undocumented! Will jump on that today.

You can set this in your keystone config - `signin logo` accepts a string of `url` or an array of `url`, `width`, and `height`.

```JS
keystone.init({
  ...
  'signin logo': ['../logo.png', 200, 100]
});
```

Should really be an object with named properties...

**Comment by lazamar** [comment]
I am setting this property but the image continues the same. Is it working in your project?

**Comment by jossmac** [comment]
Have you run `node keystone.js` again?

**Comment by lazamar** [comment]
Yes. And also tried cleaning the cache and opening in a different browser. It still references the same image.

**Comment by jossmac** [comment]
That's odd. What version of keystone are you running?

**Comment by lazamar** [comment]
Version 0.4.0. I have my `package.json` pointing to the the project's github repository to get the latest version of Keystone as recommended in [issue 1612](https://github.com/keystonejs/keystone/issues/1612), so it looks like this:
```
"keystone": "https://github.com/keystonejs/keystone.git",
```

**Comment by jossmac** [comment]
Thanks! Fixed now :)

`npm install keystone` again and it should be working

Let me know how you go

**Comment by lazamar** [comment]
Yep! Working like a charm. Thanks.

**Comment by jossmac** [comment]
No worries :)

**Comment by IamGabrielWu** [comment]
Hi @lazamar @jossmac  I followed above to npm install keystone and still it looks like my logo can't be added to the sign in page of Admin UI

As below:
![2016-10-05 23 17 49](https://cloud.githubusercontent.com/assets/11718739/19119328/01e2c14e-8b52-11e6-8563-0deee69f10cc.png)

from the log on console i can see web.svg is found and also i can see the web.svg is loaded at browser side.

![2016-10-05 23 16 30](https://cloud.githubusercontent.com/assets/11718739/19119302/eba508e2-8b51-11e6-8d66-9aacbbdd620e.png)


![2016-10-05 23 15 40](https://cloud.githubusercontent.com/assets/11718739/19119242/bad5a708-8b51-11e6-9fb5-a649b0ee623b.png)

the logo picture is put under the root folder of public in my project.

Here's my code

```
var keystone = require('keystone');
keystone.init({
  
  'name': 'mysite',
  
  'favicon': 'public/favicon.ico',
  'less': 'public',
  'static': ['public'],
  
  'views': 'templates/views',
  'view engine': 'jade',
  
  'auto update': true,
  'mongo': 'mongodb://localhost/metinvest_site',
  'session': true,
  'auth': true,
  'user model': 'User',
  'cookie secret': '(your secret here)'
  
});
console.log('running enviroment: '+keystone.get('env'))
**keystone.set('signin logo', 'web.svg');**
require('./models');

keystone.set('nav', {
    'users': 'users',
    'business': ['projects', 'stocks']
});
 
keystone.set('routes', require('./routes'));

keystone.start();

```

**Comment by jossmac** [comment]
From the "broken image" icon it looks like the path to your SVG is incorrect.

Can you access the file from `localhost:3000/web.svg`?

**Comment by IamGabrielWu** [comment]
@jossmac yes. i can access the file from localhost:3000/web.svg.  if the picture for admin UI logo is not supposed to be under the public folder, where is it supposed to be ?  i have no clue where i should modify to change admin UI.

**Comment by IamGabrielWu** [comment]
@jossmac  i fixed the problem by change the path of picture.

`keystone.set('signin logo', '../images/logo.png');`

default it's looking for logo under node_module/keystone/...,  after i add ' .. ' and picture placed under public/images, it can reference to the picture i expect.

**Comment by jossmac** [comment]
Yup, that looks right

**Comment by jgar2020** [comment]
For Keystone5, is there a different way to change the logo for the admin ui login page?
