### ISSUE TITLE
Keystone.lists.map is not a function

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystone#2803]
I've migrated to current master and i'm getting the error `Keystone.lists.map is not a function`

Anybody can help me on why e2e tests works, but my wesite is not?

I'll also try the `keystone-demo` github repo with latest keystone from upstream to check

**Comment by jacargentina** [comment]
Found it: i'm not using any `keystone.set('nav', ...)` option. 

My website was born using this tutorial http://keystonejs.com/docs/getting-started/

And there is not any indication this option is **required**. It is now?

**Comment by mxstbr** [comment]
Good catch, that's a bug in the new admin interface! Will look into it.

**Comment by liming** [comment]
Same problem. It's weird because source code seems fine.
