### ISSUE TITLE
Upgrade react-color

### ISSUE THREAD

**Issue by liming** [keystonejs/keystone#2804]
At the moment the react-color is a forked project and pushed to npm repository. This is to solve the problem of npm peer dependencies. 

A couple days ago react-color has upgrade to react 15.0.x so can we change back to react-color.

**Comment by mxstbr** [comment]
Sounds like a good plan! Mind submitting a PR for that?

**Comment by liming** [comment]
@mxstbr Thanks for remind.

 https://github.com/keystonejs/keystone/pull/2805

**Comment by jossmac** [comment]
@mxstbr this can be closed now, right?

**Comment by mxstbr** [comment]
Nope, we didn't merge the PR yet: https://github.com/keystonejs/keystone/pull/2805#issuecomment-218763194
