### ISSUE TITLE
Problem with required initial noedit fields

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2814]
A field which is all three of `initial`, `noedit` and `required` cannot be created. It results in a validation error, even when the field has been filled in in the initial form:
```
############## Console.log the POST data:
{ action: 'create',
  _csrf: '6FTbnsyb6ynEuzi09O/l8kjQp6FU1kM0vaEjY=',
  name: 'test name',
  food: 'test food' }
########## Console.log the error:
{ [ValidationError: SelectFieldOnInitial validation failed]
  message: 'SelectFieldOnInitial validation failed',
  name: 'ValidationError',
  errors:
   { food:
      { [ValidatorError: Path `food` is required.]
        message: 'Path `food` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'food',
        value: undefined } } }
POST /keystone/api/legacy/select-field-on-initials/create 400 19.532 ms
```

`food` is an initial required noedit field. You can see that the post request is sending the value of food, but the update handler is throwing a validation error.

**Comment by jstockwin** [comment]
It does hit the console.log here if you [uncomment](https://github.com/keystonejs/keystone/blob/master/lib/updateHandler.js#L218) it. 

Should we just skip this check if it's a create task rather than an update task? 
Should this also throw an error/warning somewhere, rather than potentially going unnoticed?

**Comment by JedWatson** [comment]
Thanks for the PR @jstockwin, that fixes this correctly.
