### ISSUE TITLE
keystone.routes missing in alpha?

### ISSUE THREAD

**Issue by weisjohn** [keystonejs/keystone#2817]
I'm using the bring-your-own express and mongoose instances, as I'm seeking to tack this into an existing project. 

I was trying to overcome this error:

```
ReferenceError: Unknown keystone list "js"
    at list (/Users/john/my_api/node_modules/keystone/lib/core/list.js:12:18)
    at /Users/john/my_api/node_modules/keystone/lib/core/routes.js:55:24
    at Layer.handle [as handle_request] (/Users/john/my_api/node_modules/express/lib/router/layer.js:95:5)
```

which seems to be a duplicate of https://github.com/keystonejs/keystone/issues/2325 and https://github.com/keystonejs/keystone/issues/2370 because of node versions.

 - I then moved from Node v5.10.0 to v5.6.0, which still didn't solve the problem.
 - I tried moving to node v4.4.4 LTS, which didn't work either. 
 - I then tried to move to the latest alpha as per https://github.com/keystonejs/keystone/issues/2325#issuecomment-200272734

Now I'm getting this error:

```
/Users/john/my_api/lib/keystone.js:9
  keystone.routes(app);
           ^

TypeError: keystone.routes is not a function
    at module.exports (/Users/john/my_api/lib/keystone.js:9:12)
```

**Comment by wmertens** [comment]
is this still happening?

**Comment by Murmand** [comment]
I'm exactly in a same situation and I tried to solve it just like you. With same result and now I'm stuck at this point as well. Did you solve it?

**Comment by wmertens** [comment]
@weisjohn `keystone.routes(fn)` moved to `keystone.set('routes', fn)` in 0.4.

Not sure about the error in v0.3 though :(

**Comment by wmertens** [comment]
@Murmand see comment above this one

**Comment by JedWatson** [comment]
Sorry, that should have been noted in the upgrade guide. I'll add a warning if you use `keystone.routes` to avoid this confusion in the future.
