### ISSUE TITLE
TinyMCE Spellchecker Plugin 404

### ISSUE THREAD

**Issue by varatep** [keystonejs/keystone#2818]
Using:

```
keystone.set('wysiwyg additional buttons', 'searchreplace visualchars, spellchecker');
keystone.set('wysiwyg additional plugins', 'searchreplace, spellchecker');
```

When clicking on the spell checker button (which has no icon), I receive a `Spellchecker request error: 404` which seems to make a POST call to `http://localhost:3000/keystone/js/lib/tinymce/plugins/spellchecker/`. Is there an additional server I need to be running somewhere?

**Comment by varatep** [comment]
Adding `keystone.set('wysiwyg additional options', {browser_spellcheck:true});` does not resolve this.

**Comment by mxstbr** [comment]
Are you on `0.3.x` or on the current alpha 0.4 version that is on the `master` branch?

**Comment by varatep** [comment]
0.3.17

**Comment by mxstbr** [comment]
Cannot replicate on `master`, closing for now!

![screen shot 2016-08-25 at 12 10 37](https://cloud.githubusercontent.com/assets/7525670/17954257/fe0050d8-6abc-11e6-9fb0-85822da3159e.png)
