### ISSUE TITLE
How to debug Keystone.js

### ISSUE THREAD

**Issue by lazamar** [keystonejs/keystone#2819]
How do I do to debug server-side Keystone.js? When I run `node-debug keystone.js` the keystone server does not start.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted.

I don't know the answer to the question, so please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead! Thanks! :+1:
