### ISSUE TITLE
Broken Links in Documentation section in Readme

### ISSUE THREAD

**Issue by Linda-Ikechukwu** [keystonejs/keystone#2820]
# Bug report
The API documentation and Guides documentation links in the documentation section of the readme are broken/do not exist.

## To Reproduce

1. Go to readme.md > Documentation
2. Click on API documentation and Guides documentation.
3. See error -
![Capture](https://user-images.githubusercontent.com/32891838/80202193-291a8980-861d-11ea-916a-b9dbe58fd8af.PNG)

**Comment by MadeByMike** [comment]
@jossmac looks like we removed the index page but the title was still a link? Can't rememberyou or @jordanoverbye did this.. anyway. I'll fix it on Monday.

**Comment by KuroiiJ** [comment]
I can get this fix - I assume we want the link to go to v5 > v4?

**Comment by MadeByMike** [comment]
It's not monday but I've finally done this.
