### ISSUE TITLE
AdminUI doesn't confirm on 'cancel in item create

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2822]
When one is creating a new item, for example an 'Article', if one clicks on the 'create' button top right 

![image](https://user-images.githubusercontent.com/60699805/80214133-94bf1f80-863a-11ea-8772-6746ff8b72ba.png)

and one fills out the item's fields and then clicks 'cancel' on the bottom

![image](https://user-images.githubusercontent.com/60699805/80214200-b1f3ee00-863a-11ea-9cc3-25b08aa60c6f.png)

one does not receive a confirmation asking if one really wants to abandon editing.  This causes all entered data to be lost.

What should happen is that you get a confirmation 'dialog' such as one gets when one deletes an item 

![image](https://user-images.githubusercontent.com/60699805/80214276-d9e35180-863a-11ea-9268-d9761d320985.png)

In the meantime, is there any way I can implement the desired behavior?

**Comment by gautamsi** [comment]
when you hit create again, you should have the date filled in already

**Comment by ra-external** [comment]
Ok, that's good to know, but it's not very intuitive -- I would think a standard pop-up warning would be, well, standard...

**Comment by MadeByMike** [comment]
Yep, seems reasonable. This is probably a good first issue if you'd like to have a crack at it @ra-external you are getting fairly familiar with the Admin UI. If not I'd say it's going to be a lower priority compared with other things on our list for a while.

**Comment by ra-external** [comment]
@MadeByMike  -- Thanks, when I can come up for air from the project I'm working on I'll take a look at it.
