### ISSUE TITLE
Bad v5 link on v4 docs site

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#2834]
The banner on the v4 docs site links to `https://v4.keystonejs.com/https://keystonejs.com/`. Looks like maybe https://github.com/keystonejs/keystone-classic/commit/e9954ef1c91e73332aaa156049ac8c64ec3173c8 wasn't applied to the live site? 🤔

**Comment by MadeByMike** [comment]
Where did you see that? Looks ok for me.

**Comment by Vultraz** [comment]
...odd. It works now. 🤔
