### ISSUE TITLE
[0.4] WYSIWYG editor breaks in Firefox if shown and hidden twice

### ISSUE THREAD

**Issue by geloescht** [keystonejs/keystone#2834]
I added a Html field that dependsOn a Boolean. If I toggle the checkbox twice, a regular textarea appears after the second time that contains just the HTML code of the edits I made earlier. This only happens in Firefox. An error appears in the console:
`NS_ERROR_UNEXPECTED: 1 tinymce.min.js:5:0`

Apparently this is due to an unfixed issue in TinyMCE reported here (the exception throws on the same line):
https://github.com/tinymce/tinymce/issues/794
A workaround is found in this comment:
https://github.com/tinymce/tinymce/issues/794#issuecomment-203701329

**Comment by geloescht** [comment]
I don't think we even call editor.remove().
I tried to invoke that inside componentWillUnmount(), but it seems we never get there. Can someone with more experience in React and tinyMCE please investigate?

**Comment by r3wt** [comment]
fyi, datetime pickers don't work in firefox either. i've tried it in multiple installs so its not a one off thing.

**Comment by mxstbr** [comment]
Is that on `master` or on `v0.3.x`?

**Comment by geloescht** [comment]
Current master.

**Comment by mxstbr** [comment]
I think the fix might be to call `tinymce.remove()` before the `init()` call here: https://github.com/keystonejs/keystone/blob/master/fields/types/html/HtmlField.js#L43
