### ISSUE TITLE
Date in admin ui resetting on save

### ISSUE THREAD

**Issue by andrew-kennedy** [keystonejs/keystone#2836]
Use case: latest stable build of keystone. When setting a Date on a Datetime object via the admin ui, and clicking save, every time the list item is saved the time gets set back 7 hours. I am in the Pacific time zone which is UTC -7, so I think this may be related. I don't have any code I can think of that would modify this time.

**Comment by andrew-kennedy** [comment]
This is a duplicate of #1345 actually. I'm closing this and will report there instead.

**Comment by mxstbr** [comment]
Thanks for finding that Andrew!
