### ISSUE TITLE
Keystone pulls in way too many modules

### ISSUE THREAD

**Issue by josephg** [keystonejs/keystone#2837]
Keystone currently (transitively) pulls in 1294 modules, 37k files (24k of which are in javascript). The dependancies installed by npm are just shy of 250 megs[1].

This is _crazy_.
### Some places to start:
- Cloudinary, azure and the markdown editor should all be external modules. They're each quite dependancy-heavy, and that cost should only be bourne if they're used. Making those modules external would also allow us to remove jquery(??) from the admin UI. (Its currently included because its required by TinyMCE.)
- Move react (and friends) to `devDependancies`. Compile the admin UI's javascript in an `npm prepublish` step. This won't work if we want to statically render the page's JS.
- Remove jade (we aren't using it)
### Future work:
- Split keystone into a few parts: Admin UI, fields and the rails-style configuration stuff.
- ???

I chatted to @JedWatson about this and he wants to hold these changes until after the pending 4.x release to preserve backwards compatibility.

[1]

```
$ npm ls | wc -l
    1294
$ find node_modules/ | grep js$ | wc -l
   24254
$ find node_modules/ | wc -l
   37378
$ du -hs node_modules/
247M    node_modules/
```

**Comment by mxstbr** [comment]
We are using Jade actually, in `admin/server/templates`. Other than that sounds good to me!

**Comment by vkammerer** [comment]
"Cloudinary, azure and the markdown editor should all be external modules" sounds great! There should be a clearer difference between core and plugins.

**Comment by Noviny** [comment]
Closing as most of these points have been addressed, and these are unlikely to be pulled out in 4.
