### ISSUE TITLE
Error when non-existent IDs requested

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2846]
When you're viewing a model, e.g. a post, the link looks like
`/keystone/<model name>/<items id>`
If you manually alter the item's id, instead of getting a 404 error or similar, you are instead told
`There's a problem with the network, we're trying to reconnect...`

If you look in your browsers console, or the server's console, you'll see your browser spamming the console with requests. This seems bad. Similar to #2773

**Comment by mxstbr** [comment]
This is a bug due to the fact that I assume it's a network problem and try to fetch the content. Good catch!

**Comment by jstockwin** [comment]
@mxstbr That makes sense. What's the solution here? Should this just not happen if it's a 404? If it's a true network error, surely that doesn't return a 404?

**Comment by JedWatson** [comment]
The fix for this is spec'd as part of #3041, I'm going to close this so we only have one place to track the work.
