### ISSUE TITLE
Preview pages/content

### ISSUE THREAD

**Issue by benrlodge** [keystonejs/keystone#2848]
I apologize if this functionality exists and I'm just missing it, but if not, are there plans to add the ability to preview pages, notably drafts? I love this project, but unfortunately not having this feature is a deal breaker for my client work.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. We don't currently support this at the moment.

I've moved this to ProductPains, please upvote it there if you want this feature: https://productpains.com/post/keystonejs/add-ability-to-stage-changed-content-for-publication!
