### ISSUE TITLE
Cloudinary Images not updating when save.

### ISSUE THREAD

**Issue by terenzeyuen** [keystonejs/keystone#2849]
Noticed a bug with cloudinary **images** in latest master branch (0.4). If you upload an image and hit save, it still stays there although it has already been saved?

Okay for cloudinary image (single).

So see screenshot below, I have uploaded an image and hit save but the counter is still there. If I hit save again, it saves the image twice..

<img width="545" alt="screen shot 2016-05-13 at 23 42 01" src="https://cloud.githubusercontent.com/assets/2553680/15263721/5fe28cc6-1964-11e6-87d2-0a092638ed20.png">

**Comment by mxstbr** [comment]
Yeah, they are currently still broken, we're aware of that. We'll be reworking them entirely shortly.

Thanks for submitting this bug report!

**Comment by terenzeyuen** [comment]
Anything I can help?
