### ISSUE TITLE
"TimeoutError: Knex: Timeout acquiring a connection" when using with Node 14

### ISSUE THREAD

**Issue by iamacup** [keystonejs/keystone#2849]
At the moment, running `knex/postgres` on `node:14.x` using `@keystonejs/adapter-knex@9.0.3` will not connect to a database because of a dependency on `pg 7.x` which does not work with `node:14.x`

https://github.com/knex/knex/issues/3831#issuecomment-620470821
https://github.com/brianc/node-postgres/issues/2180

`Knex 0.21.1` currently depends on `pg 8.0.3` which fixes this issue

### Suggested fix 

bump versions in `@keystonejs/adapter-knex`:  https://github.com/keystonejs/keystone/blob/master/packages/adapter-knex/package.json

`"knex": "^0.20.6"` => `"knex": "^0.21.1"` 
`"pg": "^7.17.0"` => `"pg": "^8.0.3"`

There are a number of changes detailed here for 7.x to 8.x - https://node-postgres.com/announcements, but it looks like the only large one is:

```
Now we will use the default ssl options to tls.connect which includes rejectUnauthorized being enabled. This means your connection attempt may fail if you are using a self-signed cert. This makes pg a bit more secure "out of the box" while still enabling you to opt in to the old behavior.
```

### Temporary fix

Using yarn resolutions to force versions on `node:14.x`:

```
  "resolutions": {
    "@keystonejs/adapter-knex/knex": "0.21.1",
    "@keystonejs/adapter-knex/pg": "8.0.3"
  }
```

**Comment by andyfcx** [comment]
Had this problem too.

**Comment by tomasztunik** [comment]
Thanks for sharing @iamacup - was starting to pull my hair out on this one! The error message was not really helpful. Adding full error message I received to improve searchability on this one:

Keystone error:
```
Could not connect to database:
```
Knes error:
```
Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```
