### ISSUE TITLE
KeystoneJS watch:lint is not in your gulpfile

### ISSUE THREAD

**Issue by Stalso** [keystonejs/keystone#2851]
Hello. I have the same issue as this guy described in this SO thread http://stackoverflow.com/questions/37205321/keystonejs-watchlint-is-not-in-your-gulpfile . How can I fix this?

**Comment by morenoh149** [comment]
moved to https://github.com/keystonejs/generator-keystone

**Comment by Stalso** [comment]
Oh. I am surry. It is my mistake to open it here
