### ISSUE TITLE
node_module css stylesheet not being loaded in production

### ISSUE THREAD

**Issue by Nikodermus** [keystonejs/keystone#2859]
# Bug report
Stylesheets loaded as imports inside a custom page, are not bundled in a production build.

## Describe the bug

In a custom page, I have a CSS import in the way of
```javascript
import '@secret/venue-map-component/dist/VenueMap.css';
```

This works in development mode, but the stylesheet is missing in the production build

## Expected behaviour

node_modules stylesheet should be added in production build as with local css stylesheets.

## Screenshots
Dev
![Screen Shot 2020-04-29 at 3 35 35 PM](https://user-images.githubusercontent.com/7080621/80647751-9fabf280-8a34-11ea-914c-79c24d8bdcd1.png)
Prod
![Screen Shot 2020-04-29 at 3 35 04 PM](https://user-images.githubusercontent.com/7080621/80648729-48a71d00-8a36-11ea-96aa-6f1455a78f3a.png)

## System information

- macOS 10.14 (18A391)
- Browser: All

**Comment by Nikodermus** [comment]
Fixed in #2860

**Comment by MadeByMike** [comment]
Resolved: #2860
