### ISSUE TITLE
The ui with TextArray type doesn't work well.

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#2865]
### Expected behavior
Open and edit the records in admin panel.
### Actual behavior
There is an error `TypeError: Cannot read property 'map' of undefined` in `fields/mixins/ArrayField.js ` in 
```
renderField: function () {
		return (
			<div>
				{this.state.values.map(this.renderItem)}
				<Button ref="button" onClick={this.addItem}>Add item</Button>
			</div>
		);
	},
```
`this.state.values` is undefined
### Steps to reproduce the behavior
Enter to admin panel -> first open record for model without `TextArray` type -> then open record of model with `TextArray` type.
If I enter in the record of model with `TextArray` type, `this.state.values` in an empty array, but after enter in record without `TextArray` type it's becoming `undefined`.

And another:
I create item in `TextArray` field. If I paste numbers all works well, but if I paste text, it clears after saving.

This is the latest version from `master`

**Comment by mxstbr** [comment]
Awesome bug report, thanks @w01fgang!

**Comment by jstockwin** [comment]
I just got the same thing with DateArray too. Same error, same place. 

Further, after this error has been thrown, no item is created and when I try to navigate between tabs I get 
`TypeError: Cannot read property 'componentWillReceiveProps' of null` at `packages.js:15`

**Comment by w01fgang** [comment]
@jstockwin yes, I also have this error.
Accordingly the error in the `ArrayField` mixin.

**Comment by jstockwin** [comment]
So, `this.state` is somehow stuck onto the last field you viewed. 
So if you create an email `test@example.com`, and then try and view the date array, `this.state` in the snippet of the original issue is `values: 'test@example'com'`, even though you're currently viewing a datearray.
