### ISSUE TITLE
How i can create users a registration/login(next.js)?

### ISSUE THREAD

**Issue by kaaboeld** [keystonejs/keystone#2875]
# Question about Keystone
* Site users in a separate List(not Users)
* User signup by email/password(field type Password)
* User must be login to the site
* User go to separate(not /admin) Login form
* User fill email and password fields in the form
* User try to submit a form(GraphQL query)
...
Password type - Not read(by doc), I can't compare password from Form with an encrypted password in DB(I can't get a field with this Field type).
How I can log in User to the Site?

**Comment by gautamsi** [comment]
Need to get list level authentication work.

https://github.com/keystonejs/keystone/pull/2017
AND 
https://github.com/keystonejs/keystone/pull/2039

Are in that direction but seems stale for now.

**Comment by kaaboeld** [comment]
@gautamsi thanks, can u add an example for use? I added authStrategies... but when I try request 
```
query {
            allMembers(where: { email: "aaa", password: "bbb", isBanned: false } ){
                id email password isBanned 
            }
        }
```
I get response:
message: "Field "password" is not defined by type MemberWhereInput. Did you mean password_is_set?"

**Comment by gautamsi** [comment]
you want to look at how [meetup-demo](https://github.com/keystonejs/keystone/blob/master/demo-projects/meetup/site/lib/authentication.js) does that

**Comment by MadeByMike** [comment]
@kaaboeld hope you got this working. The short answer is you can use `keystone.executeQuery` for small stuff, or a migration framework to initialise a database: https://github.com/keystonejs/keystone/discussions/299

We don't offer a complete solution for migrations yet but we have some demo projects with patterns you can copy.
