### ISSUE TITLE
[Documentation Request] FusionAuth as Auth Provider

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#2876]
# Documentation request

Please add documentation/ example of how to use https://fusionauth.io/ as Auth Provider.

**Comment by MadeByMike** [comment]
At this stage you'd need to write your own auth provider and although possible this is not something that currently has a public API we're ready to document in this way.

The best documentation at the moment would probably be to have a look at the Password Auth provider: https://github.com/keystonejs/keystone/tree/master/packages/auth-password
