### ISSUE TITLE
LocalFiles field incorrectly handles multiple files upload

### ISSUE THREAD

**Issue by dudv** [keystonejs/keystone#2876]
Given 3 files via open files dialog, the field creates 3 instances of a single file. See screenshots.
<img width="945" alt="screen shot 2016-05-17 at 17 53 25" src="https://cloud.githubusercontent.com/assets/2914397/15327529/7591bd3c-1c5a-11e6-8959-8cc971cd4593.png">
<img width="906" alt="screen shot 2016-05-17 at 17 55 36" src="https://cloud.githubusercontent.com/assets/2914397/15327530/7594261c-1c5a-11e6-97b5-827594aa9393.png">
I use latest keystonejs version.

**Comment by r3wt** [comment]
Isolated repro please? Unable to reproduce issue

**Comment by dudv** [comment]
The bug was caused by my incorrect filename function provided to model configuration. Sorry for false bug report.
