### ISSUE TITLE
Access Control for Custom Actions and Custom Pages

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#2877]
# Feature request

How should one implement access control for Custom Actions and Custom Pages?

**Comment by MadeByMike** [comment]
Access control relates to lists and fields so you'd get access control on these for free, when executing graphQL queries from the client. 

There is not really a concept of access control for pages in the Admin UI. It only attempts to validate and remove fields where appropriate. For example it can know `update: false` should be removed but it assumes that `update: () => false` is true, and will render a field that fails on update.

At the moment we have no plans to change this. So for anything beyond the above or not related to lists and fields you'd add your own access control checks and bake these into the page. 

It's a neat little demo idea. And it might be possible to make use of the authenticated user to do that. If you create and share a demo this might generate so idea for how we can make it easier for people wanting to do this.
