### ISSUE TITLE
Help : Array support for mongodb Model. [Priority]

### ISSUE THREAD

**Issue by mjarpitanand** [keystonejs/keystone#2879]
![image](https://user-images.githubusercontent.com/14835964/80931074-3d0c7b00-8dd5-11ea-9eca-d123ed7f4122.png)

I have a field OF ARRAY datatype in mongodb, I have so somehow from keystone put value in this.

I am early in keystone, 1 day old, Please help.SORRY IF IT IS REPEATED.

**Comment by mjarpitanand** [comment]
https://www.keystonejs.com/guides/custom-field-types

Can we use this to construct the Array field.

**Comment by timleslie** [comment]
Keystone does not have a field type which corresponds to the mongoDB `Array` type. If you want to model something like this then you need to use a `Relationship` field, however please note that this will model the data using scalar ID fields in the appropriate collection. https://www.keystonejs.com/guides/relationships

You might be able to create a custom field type which solves your use case, however you might find it to be more work than taking advantage of the existing data modelling structures.
