### ISSUE TITLE
Custom validation does not return the expected metadata for errors

### ISSUE THREAD

**Issue by alsoicode** [keystonejs/keystone#2887]
### Expected behavior

When adding custom validation to a path, I would expect the error information to contain the `path` value in the error.
### Actual behavior

The `path` value is `undefined`.
### Steps to reproduce the behavior

Add a list with a custom validator:

```
var ContactRequest = new keystone.List('ContactRequest', {
    nocreate: true,
    noedit: true
});

ContactRequest.add({
    firstName: { type: Types.Text, required: true },
    lastName: { type: Types.Text, required: true },
    email: { type: Types.Email, required: false },
    phone: { type: Types.Text, required: false },
    replyVia: { type: Types.Select, options: ['Email', 'Phone'] },
    message: { type: Types.Textarea, required: true },
    createdAt: { type: Date, default: Date.now }
});

ContactRequest.schema.path('email').validate(function(value) {
    return this.replyVia == 'Email' && value;
});
```

or alternatively, add a `validate` method directly to a field:

`phone: { type: Types.Text, required: true, validate: function(value) { return /^\([0-9]{3}\)[0-9]{3}-[0-9]{4}$/.test(value) } }`

When submitting a form lacking an `email` value, the error information returned is:

```
{ undefined: 
   { name: 'ValidatorError',
     path: undefined,
     message: 'Validation failed',
     type: 'required' } }
```

I would expect it to be:

```
{ email: 
   { name: 'ValidatorError',
     path: 'email',
     message: 'Validation failed',
     type: 'required' } }
```

**Comment by geloescht** [comment]
@alsoicode Is this on v0.4 aka master or 0.3?

**Comment by alsoicode** [comment]
This is on 0.3.19

**Comment by Noviny** [comment]
Closing 0.3 issues, as we are no longer supporting 0.3
