### ISSUE TITLE
Deploying on Elastic Beanstalk

### ISSUE THREAD

**Issue by alexhillel** [keystonejs/keystone#2893]
I have a Keystone application I'm trying to deploy on Elastic Beanstalk. During the deployment process, the deployment is erroring with the following output:

```
> kerberos@0.0.11 install /tmp/deployment/application/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)


Running npm install: /opt/elasticbeanstalk/node-install/node-v4.4.3-linux-x64/bin/npm
Setting npm config jobs to 1
npm config jobs set to 1
Running npm with --production flag
Failed to run npm install. Snapshot logs for more details.
Traceback (most recent call last):
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 681, in 
main()
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 663, in main
node_version_manager.run_npm_install(options.app_path)
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 131, in run_npm_install
self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 166, in npm_install
raise e
subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v4.4.3-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status -9.
```

Is there something I need to configure in .ebextensions in for this part of the build to work correctly?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

Also, as it says in the log "Snapshot logs for more details.", it would be good if you posted those snapshot logs too!

**Comment by eliotfallon213** [comment]
@alexhillel I'm assuming you've sorted your error by now, but in case anyone else stumbles on this looking at the same problem in my case the problem was resolved by using a larger EC2 instance. The free tier instance appears to be too small.
