### ISSUE TITLE
Option to stop Less compiling for admin UI in production

### ISSUE THREAD

**Issue by negomi** [keystonejs/keystone#2896]
I'm using 0.3.x, and this is related to some of the issues raised in https://github.com/keystonejs/keystone/issues/1295

The admin UI loads its stylesheet fine in development, but once deployed, the use of less-middleware (I think) is preventing it from loading in my case.

What happens is that Keystone tries to compile the Less, but in production (when the process is running without write permissions), it can never write the .css file, so the UI remains unstyled.

A workaround is to increase the permissions for that directory, but this doesn't feel like a great solution.

Is there a reason the Less has to be compiled in this way, or would it be possible to add an option to compile it once on startup, and then just serve the static .css file?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

----

The thing is that we might want to bundle up custom fields in the future, which would require us to compile those files when they are bundled. (that's the reason it is the way it is)

We're currently discussing about ways to change that, see #2824!
