### ISSUE TITLE
Email settings for development

### ISSUE THREAD

**Issue by subhog** [keystonejs/keystone#290]
I'd like to be able to develop email features without the necessity of creating and configuring account for this service. A good solution would be to just dump email to console when in development mode.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/email-settings-for-development
