### ISSUE TITLE
Multiple passportSession entries for a given user and service

### ISSUE THREAD

**Issue by bndnio** [keystonejs/keystone#2912]
# Bug report

## Describe the bug

When a user logs in using passport authentication multiple times, new lines are created in the `passportSession` table for each new `tokenSecret` (even when the `user` and `serviceId` remain the same), thereby creating a situation where it's unclear which token is valid for a user for a given service. 

Because the `secretToken` (or `accessToken` as some services call it) is used for accessing the oauth provider's endpoints by the server, they are typically revoked when new ones are requested. Therefore, creating new lines without a `createdAt` or `valid` field means that they cannot be reused, and the server must re-prompt the user each time a request to the oauth provider needs to be made.

## To Reproduce

1. Create Keystone app using passport auth (and a postgres db)
2. Create a custom LinkedIn Auth Strategy (yes the config is strange because their implementation is non-standard):
```js
const PassportLinkedIn = require('passport-linkedin-oauth2').Strategy;
const { PassportAuthStrategy } = require('@keystonejs/auth-passport');

const scope = ['r_emailaddress', 'r_liteprofile'];

class LinkedInAuthStrategy extends PassportAuthStrategy {
    constructor(keystone, listKey, config) {
        super(
            LinkedInAuthStrategy.authType,
            keystone,
            listKey,
            // config
            {
                state: true,
                scope,
                ...config,
                strategyConfig: {
                    // Scope list duplicated due to how the Linkedin Strategy needs to be initialized with Keystone
                    scope,
                    ...(config.strategyConfig || {}),
                },
            },
            PassportLinkedIn
        );
    }
}

LinkedInAuthStrategy.authType = 'linkedin';

module.exports = LinkedInAuthStrategy;
```
3. Create the auth strategy with keystone
```js
return keystone.createAuthStrategy({
        type: LinkedInAuthStrategy,
        list: 'User',
        config: {
            idField: 'linkedinId',
            appId: LINKEDIN_APP_ID,
            appSecret: LINKEDIN_APP_SECRET,
            loginPath: '/auth/linkedin',
            callbackPath: '/auth/linkedin/callback',

            // Reorganize data from linked in for our User model
            resolveCreateData: ({ createdData, serviceProfile }, req, res) => {
                const { provider, id } = serviceProfile;
                logger.info(
                    `Creating new user profile for login with service provider: ${provider} and service id: ${id}`
                );

                logger.info('Created data (should be empty unless something strange happened):\n', createdData);
                logger.info('Service profile:\n', serviceProfile);

                const name = serviceProfile.displayName;
                const email = serviceProfile.emails.length && serviceProfile.emails[0].value;

                if (!name) console.warn(`Missing account info on creation. Missing name on ${provider} response`);
                if (!email) console.warn(`Missing account info on creation. Missing email on ${provider} response`);

                return {
                    ...createdData,
                    name,
                    email,
                };
            },

            // Once a user is found/created and successfully matched to the
            // linkedinId, they are authenticated, and the token is returned here.
            onAuthenticated: async ({ token: sessionToken, item: user }, req, res) => {
                logger.info(`LinkedIn Auth Successful for user: ${user.id}`);
                logger.info(`Redirecting user ${user.id} to login`);
                res.redirect(`/`);
            },

            // If there was an error during any of the authentication flow, this
            // callback is executed
            onError: (error, req, res) => {
                console.warn(`LinkedIn Auth Failed with error: ${error}`);
                res.redirect('/?oauth_error=Uh-oh');
            },
        },
    });
```
4. Hit the login url and login with LinkedIn
5. Open a new private browser window and hit the login url and auth with LinkedIn again
6. See in the passportSession table for multiple entries

## Expected behaviour

For a given user, if they use passport oauth login with a service they have previously used (i.e. there is a line in the `passportSession` table with a matching `user`, `service`, and `serviceId`), upon a successful login, the new `tokenSecret` should replace the existing `tokenSecret`.

## Screenshots

<img width="1144" alt="Screen Shot 2020-05-01 at 12 06 45 PM" src="https://user-images.githubusercontent.com/11308382/81204123-a4fdc580-8f7d-11ea-96d3-116a5787592b.png">

## System information

macOS Catalina (10.15.3),
Postgres 11

## Additional context

Chat in KeystoneJS #questions channel regarding this:

**Brendon Earl  5 days ago**
I've been using Passport auth for our Keystone app to provide LinkedIn OAuth (with passport-linkedin-oauth2) and I'm unsure if the following is expected:
The potential problem I've encountered is that when we re-prompt a user to login using Keystone Passport (i.e. a user uses oauth to login), it always creates a new entry in the passportSession table with the new accessToken (or tokenSecret). This would be fine, but there's no created, modified, or expiry columns in the table so there's no real way to differentiate between active and inactive accessTokens.
Is it expected behaviour that a new row is inserted for each time a passportSession re-authenticates? Or should it instead replacing the value in the tokenSecret column for accounts that are already registered (as in there exists a row with the same serverUserId and item FK)

<img width="1144" alt="Screen Shot 2020-05-01 at 12 06 45 PM" src="https://user-images.githubusercontent.com/11308382/81203401-c611e680-8f7c-11ea-8f7f-39808aa93357.png">

**Jess  3 days ago**
If it were to replace the value of an existing row, I think it would log out any other instances of that login. Ie; someone logs in on both mobile & desktop at the same time. So we have to keep all instances around.
> there's no real way to differentiate between active and inactive accessTokens.
Even with created at times, etc, there'd be no way to differentiate what's "active" from Keystone's perspective. It's an application level concern as to what is considered an "active" token. Ie; do you expect a token to expire after 30 days? 1 day? Can only login to one device at a time? etc.
I can't remember the entire OAuth flow; remind me what the tokenSecret is used for - is that then exchanged for the session token? Or is that the session token?

**Brendon Earl  22 hours ago**
Thanks for the response! Just to clear up a couple points, I think I maybe wasn't super clear in my initial post:
> If it were to replace the value of an existing row, I think it would log out any other instances of that login. Ie; someone logs in on both mobile & desktop at the same time. So we have to keep all instances around.
This would be correct if these were the session tokens for user login (i.e. what they're using with keystone to authenticate their identity). To my knowledge, session tokens are stored in memory by Keystone, so replacing these lines shouldn't impact login.
>Even with created at times, etc, there'd be no way to differentiate what's "active" from Keystone's perspective. It's an application level concern as to what is considered an "active" token. Ie; do you expect a token to expire after 30 days? 1 day? Can only login to one device at a time? etc.
If these were session tokens that's a really good point! Like above though, these tokens/secrets are for reaching out to the service from the API, not validating a user session, so it shouldn't make a difference.
So, the tokenSecret maps to the access token given by an oauth provider. This token is usually provisioned for X number of hours/days, and can be used as the Bearer authentication token when using their service.
In this particular case, LinkedIn calls it their access token, and a key property of it is that when new ones are created, old ones are revoked.

**Brendon Earl  22 hours ago**
So in my mind, the use case for these tokenSecrets are to link to a user, and use it to pull information on their behalf from the service they've oauthed for (i.e. pull profile information from LinkedIn after they've logged in with LinkedIn).
The problem I see with so many instances of the passportSessions, is then I don't know which I can use, so I have to re-prompt the user for a new token, use that, then it gets added to the bin of maybe-active maybe-not-active tokens

**Brendon Earl  22 hours ago**
Because it's handled entirely by the Keystone Passport plugin, I don't really have the ability to extend it or change that behaviour, other than by running some graphQL delete mutation in one of the hooks to manually delete the other sessions (which doesn't feel quite right)

**Jess  6 hours ago**
D'oh, I got it mixed up, sorry!
You're right that they're more than likely exclusive tokens.
This sounds like a bug in Keystone's passport auth implementation!
Could you do me a favour and create an issue in the Keystone repo with a copy+paste of this conversation? That way we can keep track of it and get it fixed :+1: (edited)

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
