### ISSUE TITLE
Adding multiple local or Cloudinary files for upload only uploads the last file

### ISSUE THREAD

**Issue by gregbendes** [keystonejs/keystone#2913]
Uploading multiple files on the Admin UI only uploads the last file that was added to the queue. 

This applies to both the _LocalFiles_ and the _CloudinaryImages_ type.
### Expected behavior
- Add multiple files for upload on the Admin UI
- Hit Save
- All files should be uploaded
### Actual behavior
- Only the last file is uploaded from the queue.
### Steps to reproduce the behavior
- Log into the Admin UI
- Add multiple files with either the LocalFiles or CloudinaryImages type
- Hit Save

You can reproduce this on the [Keystone Demo](http://demo.keystonejs.com/keystone/galleries) site if you create a new Album in the Galleries section.

**Comment by ytzvan** [comment]
+1

**Comment by jstockwin** [comment]
@mxstbr - I tried having a quick look at this but wasn't really sure where to start. Any ideas?

**Comment by gregbendes** [comment]
**Just an additional info:** I saw that the save request itself only contains the last file to be uploaded, so in _LocalFilesType.js_, the _uploadFiles_ method will only have the details of the last file in the request parameter. The problem must be before that.

I also had a look at the _LocalFilesField.js_ file which seems to be responsible for adding the files, but as I have no experience in React.js, I could only poke around without really getting anywhere.

Maybe that's a good place to start.

**Comment by mxstbr** [comment]
Puuh @jstockwin, I think we should leave this be for now, and fix it when we're reworking the storage fields entirely. (in ~2-3 weeks hopefully) Not sure it's worth fixing now :blush:

**Comment by rinku9900** [comment]
I am having the same issue.

**Comment by vieirav** [comment]
@rinku9900 As a workaround, you can select all images at once before saving it.

**Comment by larskarbo** [comment]
@mxstbr Any update on this? I still have this problem

**Comment by larskarbo** [comment]
The problem comes from the nature of the html input file element. Every time you select file(s) it will overwrite the previous.

To fix this problem, you have to add another input file element after adding files, but maybe its better to use some kind of library.

I see that the admin ui has some script tags for jquery upload scripts. Are these going to be used?

**Comment by itzaks** [comment]
still having this problem, any updates or workarounds?

**Comment by Noviny** [comment]
Closing this in favour of #4133 which talks about the updated field (but still has the issue) .
