### ISSUE TITLE
Keystone Logger pino options (or LOGGING_LEVEL)

### ISSUE THREAD

**Issue by bndnio** [keystonejs/keystone#2913]
# Feature request

## Is your feature request related to a problem? Please describe.

I wish to customize what level of keystone pino logger (@keystonejs/logger) logs are output using an environment variable. This however runs into two problems:
1. The built-in logging module doesn't allow for any configuration beyond the `filename` (pino `name`).
2. A log level environment variable would conflict with the existing pattern in that the `DISABLE_LOGGING` environment variable exists to turn logging off. However, if the two were consistently applied across the app I believe they could co-exist.

## Describe the solution you'd like

I wish to pass a custom pino options to the logging config for different environments (similar to the `pinoOptions` in the core Keystone module for the express pino logger).

## Describe alternatives you've considered

I've added `level` to the `pinoOptions` config in the main app, but that is only applied to the express logger. I wish to carry that functionality across to the rest of my logs when using `@keystonejs/logger`. At the moment the only way to resolve the custom configuration problem is to create my own Pino logger.

## Additional context

Currently I'm doing the following in creating loggers for my application:
```js
// Abstracted pino logger
const keystoneLogger = require('@keystonejs/logger');

const {
    helpers: { str: userStr },
} = require('./lists/User');

module.exports = filename => {
    const logger = keystoneLogger.logger(filename);
    logger.debug(`${filename} logger setup complete`);

    logger.route = req => {
        logger.debug('setting up route child logger');
        if (!req) logger.warn("'req' not passed to logger.route");
        const { path, hostname, method, user, body } = req || {};

        return logger.child({ path, host: hostname, method, user: userStr(user), body });
    };
    return logger;
};
```

I would love to change this:
```js
    const logger = keystoneLogger.logger(filename);
```
to:
```js
    const { LOGGING_LEVEL } = process.env
    const logger = keystoneLogger.logger({
        name: filename,
        level: LOGGING_LEVEL,
    });
```

I think this could be solved by either exposing a config param to keystone logger, or for my narrow use case implement the LOGGING_LEVEL environment variable in the logger component.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.

**Comment by MurzNN** [comment]
So what is an alternative in Keystone-6 to use internal logger? I can't see mentions of `pino` in Keystone-6, seems it isn't use any logger?

**Comment by dcousens** [comment]
@MurzNN this is a good question!  Could you open it as a GitHub discussion?

**Comment by MurzNN** [comment]
Seems Keystone-6 doesn't use any logger at all, so you must DIY...
