### ISSUE TITLE
Got Authorization header of type Basic, but expected Bearer

### ISSUE THREAD

**Issue by bertez** [keystonejs/keystone#2921]
# Bug report

## Describe the bug

In my keystone app I get constant warnings on the console with this message:

`Got Authorization header of type Basic, but expected Bearer`

I only get those messages on the production environment, not in development.

My keystone class is configured this way:

```js
const keystone = new Keystone({
  secureCookies: true,
  cookieSecret: process.env.COOKIE_SECRET,
  name: '---',
  adapters: ...,
  sessionStore: new RedisStore({ client: redisClient })
});
```

I think the issue is related to the session management but I've checked the code and don't know what could be happening.

## System information

- OS: keystone is running on a alpine linux Docker image

Thanks for your help!!

**Comment by jesstelford** [comment]
This warning is thrown when Keystone parses the `Authorization` header on incoming requests.

Does this happen even when viewing your Admin UI? Or only when requests are made to your frontend application?

**Comment by bertez** [comment]
It happens in both cases.

Thanks for your answer!

**Comment by jesstelford** [comment]
It's your production deployment behind a proxy? Sounds like something is passing an Authorisation header when is shouldn't be.

**Comment by bertez** [comment]
Yes! the app is proxied through nginx:

```
        location / {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
```

but it seems that there is no authorisation header passed to the app.

Thanks again!
