### ISSUE TITLE
fs: re-evaluating native module sources is not supported. graceful-fs

### ISSUE THREAD

**Issue by HughGrant** [keystonejs/keystone#2922]
when I ran `npm start`, it tells me follows info:
`fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.`

Then I ran `npm update graceful-fs`, and nothing happens, still gets the same error.

after ran `npm list | grep graceful-fs`, I get to know, there're many versions of graceful-fs installed
```
│   │     │ ├── graceful-fs@1.2.3
│   ├── graceful-fs@3.0.8
│ │ │ ├── graceful-fs@3.0.8
│ │ │   │ │ └── graceful-fs@4.1.3
│   ├── graceful-fs@4.1.4
```
What should I do? I am new to the node world, why there's many versions of same package in here?

I've tried uninstall and install graceful-fs many times, no effort at all.

**Comment by HughGrant** [comment]
After digging up a little bit, I found it's caused by a package named "gulp" which installed other dependencies that installed lower version of graceful-fs.

I will close this issue now.

**Comment by mxstbr** [comment]
Awesome, thanks for digging in yourself!
