### ISSUE TITLE
adminUIApp 6.0.0 Error on initializing

### ISSUE THREAD

**Issue by Zhdanown** [keystonejs/keystone#2928]
# Bug report

## Describe the bug

error when starting app 

## To Reproduce
install @keystonejs/app-admin-ui": "^6.0.0 and you get an error
However, @keystonejs/app-admin-ui": "^5.9.5 works ok

## Screenshots

error message
![image](https://user-images.githubusercontent.com/29001510/81437127-587bdb00-9173-11ea-9f48-add4d99d9e86.png)

my package.json
![image](https://user-images.githubusercontent.com/29001510/81437444-d9d36d80-9173-11ea-8401-38a3bee2262d.png)

## System information

- OS: Windows 10

**Comment by Vultraz** [comment]
You'll also need to update your `@keystonejs/keystone` dependency to `9.0.0` or later.

**Comment by thekevinbrown** [comment]
#2606

**Comment by MadeByMike** [comment]
I think this will be solved by updating dependencies: https://github.com/keystonejs/keystone/discussions/3087
