### ISSUE TITLE
socket.io example

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#2929]
# Feature request

At the moment the Keystone doesn't have examples for an HTTP server customization like `socket.io`. There is only `configureExpress` hook but it's useless for the HTTP customization like socket.io.

What should I do if I need to customize the HTTP server?

**Comment by jesstelford** [comment]
We allow you to fully customise your server, as long as you're able to consume the express middleware Keystone provides: https://keystonejs.com/guides/custom-server

**Comment by pahaz** [comment]
Yes, you can, but it not the same as just define `configureExpress`

**Comment by jesstelford** [comment]
I'm not sure I understand. `configureExpress` just passes you the express app for you to do what you need. At that point you can do pretty much anything like attaching new routes or middleware.

If you need more customisation, I linked to the docs which show a bunch of examples of how to build a fully custom server.

**Comment by bonniss** [comment]
@pahaz it's been a while, have you got any solutions?
