### ISSUE TITLE
[0.4] dependsOn does not initialize correctly in create dialog

### ISSUE THREAD

**Issue by geloescht** [keystonejs/keystone#2929]
### Expected behavior

A field with `dependsOn` and `initial: true` should display or not display in the create dialog according to the default value of its dependency.

### Actual behavior

The field is not displayed until it's dependency is changed. This occurs only if the default value of the dependency matches the dependsOn value of the dependent field. 

### Steps to reproduce the behavior

Create a model and add the following fields:

```javascript
{
  dependency: { type: Boolean, initial: true, default: false },
  dependent:
  {
    type: Types.Select,
    options: ['spam', 'ham'],
    initial: true,
    dependsOn: { dependency: false }
  }
}
```

Open the admin UI and click on the plus symbol to add a new item to the collection of your model. Note how `dependent` does not show up until you toggle `dependency` twice.

**Comment by geloescht** [comment]
Reason is incorrect bootstrapping of default values: Some fields get an empty string instead of their proper (boolean) value. I suspect this is due to a comparison for falsiness or truthiness somewhere instead of checking for `undefined`.

**Comment by jstockwin** [comment]
This can now be reproduced on the current master by running
`node test/e2e/server.js --config ./test/e2e/adminUI/nightwatch.json --group test/e2e/adminUI/tests/group999FixMe/2945.js`
