### ISSUE TITLE
Build a `TimeZone` field type

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#2937]
Presented in the Admin UI as a select field. Storing a [standard time zone name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), eg. `Australia/Sydney`.

This type would be useful for thing like...

User preferences, eg. for storing the time zone in which _all_ dates should be rendered before presentation to the user (screenshot from Harvest):

![Screenshot 2020-05-11 at 23 03 50](https://user-images.githubusercontent.com/2416367/81564982-f40f8480-93db-11ea-94cc-c4f9e36ecd98.png)

Storing the time zone in for specific dates or ranges, eg. for an event (screenshot from Google Calendar):

![Screenshot 2020-05-11 at 23 02 55](https://user-images.githubusercontent.com/2416367/81565036-0db0cc00-93dc-11ea-98a7-c1f9a69eaa05.png)

---

Note: it's important this stores the standard **time zone name**. No an offset, not an offset nickname (like "Australian Eastern Daylight Savings Time" or "Australian Eastern Standard Time"  or their abbreviations, etc).

**Comment by VinayaSathyanarayana** [comment]
As part of UserProfile, we should collect the User Timezone and use that for 
- display
- default timezone for 'date-time with timezone' data entry

**Comment by molomby** [comment]
This has been bumped up a bit in priority; may be worked on soon.

In terms of implementation, I imagine this would wrap the `Select` type with a predetermined set of options. We'd probably source data directly from the [IANA database](https://www.iana.org/time-zones. See for eg, the current [zone1970.tab](https://github.com/keystonejs/keystone/files/5266823/zone1970.txt) file.

Option value would be the string time zone name (eg. `America/Bahia_Banderas`) while the label could incorporate the comment info too (eg. maybe `America/Bahia_Banderas (Central Time - Bahía de Banderas)`?). These options could be updated periodically when the package was republished (or maybe as part of the build process?).

**Comment by molomby** [comment]
See also #7327
