### ISSUE TITLE
Admin UI: hidden:true doesn't work for inherited Relationship fields 

### ISSUE THREAD

**Issue by maxkoryukov** [keystonejs/keystone#2941]
### Expected behavior

Fields, declared with `hidden:true` should be invisible
### Actual behavior

I have two collections, say `Base` and `Child`.

Both has the same field `somefield`. But for `Base` visibility is not set, and for `Child` this field is `hidden`. But I see the field in the admin UI for both collections.
### Steps to reproduce the behavior

Create models with the following fields:

``` js
Base.add({
    somefield: { type: Types.Relationship, ref: 'Somefield' },
});

Child.add({
    somefield: { type: Types.Relationship, ref: 'Somefield', hidden: true, noedit: true },
});
```

Open admin UI

**Comment by jstockwin** [comment]
This can now be demonstrated in current master by running
`node test\e2e\server.js --env default --config ./test/e2e/adminUI/nightwatch.json --group test/e2e/adminUI/tests/group999FixMe/2941.js`

**Comment by geloescht** [comment]
Before I go and try to fix this: Do we actually support redefining fields of the same name in the inherited list?

**Comment by jstockwin** [comment]
Does calling the fields different names solve the issue?

**Comment by maxkoryukov** [comment]
@jstockwin I think yes) because in other case _hidden_ does not work for inheritance)) Let me check

**Comment by maxkoryukov** [comment]
### sample 1
```js
Base.add({
    somefield: { type: Types.Relationship, ref: 'Somefield' },
});

Child.add({
    somefield_2: { type: Types.Relationship, ref: 'Somefield', hidden: true },
});
```

In editor of the `Child` item I could see just `somefield`, so it is work (but it is not a solution)

### sample 2

```js
Base.add({
    somefield: { type: Types.Relationship, ref: 'Somefield' },
});

Child.add({
    somefield: { type: Types.Relationship, ref: 'Somefield', hidden: true },
    somefield_2: { type: Types.Relationship, ref: 'Somefield', hidden: true },
});
```

There is one field - `somefield` . Should be - 0.

Another one note: I could set `hidden:false` in the definition of the `Base` model, then the field `somefield` will be invisible in both editors, for `Child` and for `Base`, ignoring settings of `somefield` on child.

**Comment by webteckie** [comment]
@maxkoryukov I think what you expect makes sense.  Are the values stored as you expect in the mongo database collection?

**Comment by maxkoryukov** [comment]
@webteckie my problem - Admin UI, not DB, DB works good. **UI** looks as not expected.

**Comment by webteckie** [comment]
Fair enough:-)  Would it be possible for you to debug this to see if you can arrive at a solution and a PR with the changes?

**Comment by maxkoryukov** [comment]
@webteckie, no.. Sad, but right now I am not ready to create a PR...

**Comment by export-mike** [comment]
This issue is no longer an issue therefore I am closing. 
I've been adding tests using nightmare e2e framework and can see its no longer an issue 
https://github.com/keystonejs/keystone/commit/73d144ebe825f761e5afdd2e5b91ab95bd01408c
