### ISSUE TITLE
LocalFileAdapter file deletion bug

### ISSUE THREAD

**Issue by kasonde** [keystonejs/keystone#2948]
# Bug report

## Describe the bug

In the documentation for file adapters, we're provided with a nifty hook to delete existing files before/after new ones are changed / deleted. Unfortunately the `existingItem` shown in the [docs](https://www.npmjs.com/package/@keystonejs/file-adapters)  does not carry a `file` property as show. So the condition is always false and files are never deleted.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Go to 'https://www.npmjs.com/package/@keystonejs/file-adapters'
2. Setup a file field and a local file adapter as shown in the docs
3. Upload a file, and attempt to delete it.
4. File remains undeleted.

## Expected behaviour

I expect the existing file or in this case `existingItem.file` to be deleted.

## System information

- OS: macOS
- Node: 10.13.0

**Comment by Vultraz** [comment]
I can't repro this 🤔 I tested, and the code in the docs works fine.

**Comment by kasonde** [comment]
I see. That's odd. For reference, here's my config

I'm using MongoDB as my DB.

`
const fileAdapter = new LocalFileAdapter({
	src: "./uploads/test_people",
	path: "/uploads/test_people"
});

keystone.createList("TestPersonImage", {
	fields: {
		image: {
			type: File,
			adapter: fileAdapter,
			hooks: {
				beforeChange: async ({ existingItem }) => {
					console.log("Field: ", existingItem);
					if (existingItem && existingItem.file) {
					  	await fileAdapter.delete(existingItem.file);
					}
				},
			}
		}
	},
	// hooks: {
	// 	beforeDelete: async ({ existingItem }) => {
	// 		console.log(existingItem);
	// 		await fileAdapter.delete(existingItem.filename);
	// 	},
	// }
})

keystone.createList("TestPerson", {
	fields: {
		name: {
			type: Text,
		},
		images: {
			type: Relationship,
			ref: "TestPersonImage",
			many: true,
		}
	}
});
`

Note that I'm working directly with the TestPersonImage list and not the parent list. I'm performing CRUD from the admin panel.

**Comment by Vultraz** [comment]
You need to have both sets of hooks from the example enabled. The first is a *field*-level hook; it handles the case where the file - and just the file - actually changed. The other is a *list*-level hook; it handles the case where the entire list entry was deleted.

More info on hooks here: https://www.keystonejs.com/api/hooks/

**Comment by kasonde** [comment]
@Vultraz the code above has it omitted. This because I was probably 10 tries in at that point pulling things out and putting them back in. But I have it noted down that even with both, it still doesn't work for me.

**Comment by MadeByMike** [comment]
@kasonde I've also been able to get this working... do you think you could post an example project to gitHub that has the bug? That way we can see if there's something different about your local environment or ideally get an example that allows us to reproduce the issue.

Sorry about the trouble. If it turns out to be config, we can still improve the docs based on your experience!

**Comment by tshih5** [comment]
@MadeByMike I initially had the same issue with files not getting removed when I attempted to delete them. The way I fixed it is replacing the  `.file` property from `existingItem.file` to the actual name of the field when you define it. In @kasonde  's case, the field name is "image", so I would replace `existingItem.file` with `existingItem.image`. 

I'm fairly certain the docs explaining the file adapters don't say anything about using the field name as the property for `existingItem`, so it could be confusing for some readers.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
