### ISSUE TITLE
Support for GraphQL subscriptions

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#295]
GraphQL subscriptions allow a remote app to make a query and be _pushed_ a constantly updated set of results (ie. without polling). This is super-handy. It's already supported by the client side (Apollo) and server side (graphql-js) packages we use (yes?), we just need to build out support for it in Keystone.

However, to implement this in a performant way requires the support of the DB layer (otherwise you end up polling server side, generating more load for less-good results). Fortunately both MongoDB and pgSQL support subscription-like features we can wrap:

- Mongo has [change streams](http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html)
- pgSQL has [listen/notify](https://www.postgresql.org/docs/current/static/sql-notify.html)

The work required is:

- Update the Keystone data store adapter spec to support subscriptions
- Updates to any existing adapters to implement the functionality
- Updates to the GraphQL layer

**Comment by zenflow** [comment]
@molomby Would the admin UI use the "subscriptions" feature to become "real-time" (update automatically when there are changes in the data in the database)? (Not even sure if the admin dashboard uses the graphql interface or something else)

**Comment by zenflow** [comment]
Note that mysql also (in addition to mongo and pgsql) supports subscriptions (in a less elegant way) with it's [Binary Log feature](https://dev.mysql.com/doc/refman/8.0/en/binary-log.html). In the js ecosystem it has been implemented as [zongji](https://github.com/nevill/zongji) (built on the [`mysql` package](https://github.com/mysqljs/mysql)) and as a feature in the [`mysql2` package](https://github.com/sidorares/node-mysql2) (not much documentation here).

**Comment by VinayaSathyanarayana** [comment]
This will be a very useful feature to get real time updates on critical changes.

**Comment by timleslie** [comment]
#2418 will help with this as it will improve the patterns we use to generically generate graphql typedefs and resolvers.

**Comment by VinayaSathyanarayana** [comment]
Any updates on this crucial feature

**Comment by iamacup** [comment]
Hey, thought it might be worth chucking this in here for reference: https://github.com/hasura/graphql-engine/blob/master/architecture/live-queries.md - it has some good discussion (at least on the postgres side) about the use of Listen/Notify and various other bits and pieces that might shape the Keystone implementation from a performance perspective
