### ISSUE TITLE
move auth from cookie to token

### ISSUE THREAD

**Issue by benkroeger** [keystonejs/keystone#2952]
I'm integrating keystone as CMS into a loopback application. While working with 0.4.0-alpha made my life much easier already, it still requires cookie based auth for the admin ui - while the rest of my app does not.
I was wondering if there are plans to support token auth (e.g. Bearer token via authorization header).
I understand that this request has impact on both, admin ui and server routers.
However, it will give a great deal of flexibility and open possibilities even wider.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted.

I've moved this to ProductPains, please upvote it there: https://productpains.com/post/keystonejs/token-authentication! Thanks!
