### ISSUE TITLE
relative path for static files in subpages 

### ISSUE THREAD

**Issue by msio777** [keystonejs/keystone#2956]
Hi,

I'm using handelbars and I defined layout where I use some static files (icons,images) from public folder. When this layout part is rendered in some subpages like blog/article/my_article. Path to static files is not relative to app but it will be like /blog/article/img/icon.jpg and  no image will be found. But If I switch just to /blog. All static files will be found. my routes are 

`app.get('/blog', routes.views.blog);
app.get('/blog/article/:post', routes.views.post);` 

thanks for any help
Best Regards 
Michal

**Comment by jstockwin** [comment]
Hi @msio777 ,

We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

I'd suggest posting it on stackoverflow, and if you reply here with a link I'll have a look for you! When you ask the question, please can you also include the relevant code from your handlebars template?
