### ISSUE TITLE
@keystone/file-adapter's S3Adapter incorrectly requires constructor parameters

### ISSUE THREAD

**Issue by intmainvoid** [keystonejs/keystone#2965]
# Bug report

## Describe the bug

Creating an instance of `S3Adapter` (from `@keystone/file-adapters`) without providing accessKeyId, secretAccessKey and region throws an error and terminates Keystone's Node.js instance. The error is thrown with the following message:

> S3Adapter requires accessKeyId, secretAccessKey, region, bucket, folder.

## To Reproduce

Create an instance of the `S3Adapter` as follows:
``` Javascript
const fileAdapter = new S3Adapter({
	// accessKeyId // not provided
	// secretAccessKey: // not provided
	// region: // not provided
	bucket: 'website-submission-attachments',
	folder: 'test',
	s3Options: {
		apiVersion: '2006-03-01',
	},
	uploadParams: ({ filename, id, mimetype, encoding }: UploadParams) => {
		return {
			Metadata: {
				keystone_id: String(id),
			},
		};
	},
});
```

## Expected behaviour

The `S3Adapter` connects to the S3 bucket regardless of the presence of the 3 missing parameters and that no attempt is made by the `S3Adapter` to pass the the three missing parameters on to the `AWS.S3` constructor params.

## Screenshots

N/A

## System information

macOS

## Additional context

`@keystone/file-adapter`'s `S3Adapter` requires - among others - the following parameters in its constructor which are then passed to the AWS SDK constructor: `AWS.S3`:

```
    accessKeyId,
    secretAccessKey,
    region,
```

There are many common use cases where creating an S3 instance without these parameters are valid - and in fact - `accessKeyId` and `secretAccessKey` are [deprecated](https://github.com/aws/aws-sdk-js/blob/master/lib/config.d.ts#L197) in the AWS SDK.

## Proposed solution

Remove the hard requirement for these parameters to be provided and instead simply allow the user to provide them as required in the `s3Options` object.

**Comment by MadeByMike** [comment]
Fixed in #2967
