### ISSUE TITLE
_.contains is not a function on S3FileType

### ISSUE THREAD

**Issue by pmminov** [keystonejs/keystone#2966]
What the title says. I saw a merge request to fix this on Cloudinary File Types by replacing .contains with .includes. Can you guys do it for S3Files? S3FileType.js line 341 :D

I know you guys got a lot on your plate, but S3Files have been forsaken for a bit... share the love

**Comment by jstockwin** [comment]
@pmminov I think the problem most of the contributors have here is that most of us (myself included) don't actually have S3 accounts, so can't really test any changes we make.

If you think you know the correct change, then could you try it out to check it works? If it does, it would be an amazing help if you could make a Pull Request for that change, and then hopefully it should be merged into master pretty quickly! 

If not, I'm happy to have a look at this, but it'll be a few days before I'm able to. Would you also mind posting some steps to reproduce this error?
