### ISSUE TITLE
When changing view to twig during `yo install` the view engine is still set to jade.

### ISSUE THREAD

**Issue by UndergroundLabs** [keystonejs/keystone#2967]
**Keystone Version**: 0.3.16
**Node Version**: 6.2.0

### Expected behavior

When selecting `twig` during installation using `yo keystone` the `keystone.js` file should have the view engine set to `twig` and the code within the views formatted should be using `twig`.

### Actual behavior

When selecting `twig` during installation the view engine is still set to `jade` and code within views is also using `jade`.

### Steps to reproduce the behavior

Run `yo keystone` to have the generator create a keystone project. When asked to select your view enter `twig`. After installation inspect `keystone.js` and it will contain:

    'view engine': 'jade',

**Comment by geloescht** [comment]
Thanks for your report, this is a known issue in generator-keystone. Please see this issue: keystonejs/generator-keystone#180

**Comment by r3wt** [comment]
@UndergroundLabs if you need it before the `0.4` release, apply pressure to the team. i can rebase and submit a pr on current master to get it fixed asap. i have a local pr based on an older branch, shouldn't be difficult to bring up to date. sorry for the trouble, this is totally my fault.

**Comment by UndergroundLabs** [comment]
@r3wt It's ok for now as I was able to stick with `Jade` in this instance but it would be useful to have on future projects.

**Comment by r3wt** [comment]
@UndergroundLabs well, unfortunately it doesn't work with keystone's email utility anyway. i had to write a custom component to send emails.

**Comment by JedWatson** [comment]
Um... just to confirm - isn't this an issue with the generator and not a bug in Keystone itself?

Unless there's something in Keystone this isn't tied to the 0.3/0.4 version.

If there _is_ an issue in Keystone itself, we're prepping a patch release of 0.3 in the next few days with some fixes, and I'd be happy to make sure this gets into that if someone can do the PR.

**Comment by r3wt** [comment]
The pr i opened completely removes swig, so its a breakimg change. Id have to rebase and add twig without removing swig, so more work. Additionally ive found that the email class always expects jade as the template language, so thats a side issue. I will make a PR on main tomorrow, in hopes it makes it into the next release. Ive got another keystobe project starting next week so the sooner it lands in the generator the better for me and anyone else who rightfully desires to use twig.
