### ISSUE TITLE
Inconsistent mongo/postgres behavior

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#2968]
# Bug report

## Describe the bug

I have a bug inside my [query](https://github.com/8iq/nodejs-hackathon-boilerplate-starter-kit/blob/28c8a97274fd6b00f06ccbcd099cfd4cd624dd11/packages/%40core.keystone/schemas/User.js#L203-L218). As you can see the `now` variable has an `Int` type, but the GraphQL query assume that it should be a `DateTime`.

```
const now = Date.now() // *!* Int *!*
...
const { errors: userAndTokenErrors, data } = await query(
    `
    query GetUserAndToken($user: ID!, $now: DateTime!) {
      ...
      allForgotPasswordActions( where: { user: { id: $user }, expiresAt_gte: $now, usedAt: null }) {
        token
        ...
      }
    }
`,
    { skipAccessControl: true, variables: { user: userId, now } },
)
```

And there is no type checking here!

1) If I run the code with the Mongo, [won't be any errors](https://github.com/8iq/nodejs-hackathon-boilerplate-starter-kit/runs/667389633).
2) If I run the code with the Postgres, there will be [an error](https://github.com/8iq/nodejs-hackathon-boilerplate-starter-kit/runs/667389609).
```
'select "t0".* from "public"."ForgotPasswordAction" as "t0" left outer join "public"."User" as "t0__user" on "t0__user"."id" = "t0"."user" where true and ("t0__user"."id" = $1) and ("t0"."expiresAt_utc" >= $2) and ("t0"."usedAt_utc" is null) - invalid input syntax for type timestamp: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN"',
```

## Expected behaviour

I assume that the Keystone query should check the variable type. 
And I should get an error as soon as possible.

**Comment by MadeByMike** [comment]
Perhaps we should validate the input. 

What I see happening here is date/time values in GraphQL are effectively strings, the integer becomes a string and this is passed to the field adapter. The field adapter is then responsible for saving the value. It may or may not preform transformations and validations before handing it to the database. Mongo accept the value (as it usually does, Mongo doesn't care) and SQL tends to be more strict. 

Maybe we should be more opinionated in the middle here, but I'm not sure that differences in behaviour between adapters is necessarily a bug in every case.

**Comment by molomby** [comment]
Yep, sounds like a bug. The [`DateTimeUtc` type](/packages/fields-datetime-utc) gets this right I think, you might want to try it instead.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
