### ISSUE TITLE
Just broke the Keystone 4 demo

### ISSUE THREAD

**Issue by pantgurra** [keystonejs/keystone#2969]
Steps to reproduce:

-Upload a file to Gallery
-Press save
-Press save again without changing anything

It crashes with error:
TypeError: Cannot read property 'public_id' of undefined at /usr/src/app/node_modules/keystone/fields/types/cloudinaryimages/CloudinaryImagesType.js:35:14

Unfortunately we still need keystone 4 in a project and the client keeps pressing that button making the site crash.

**Comment by pahaz** [comment]
I think. It will be better to post in here: https://github.com/keystonejs/keystone-classic/issues
