### ISSUE TITLE
pre:routes middleware not working in admin pages

### ISSUE THREAD

**Issue by yatping** [keystonejs/keystone#2974]
Keystone Version: 0.4
Node Version: 0.12.7

### Expected behavior
pre:routes middleware not working in admin pages, but works in front-end pages.

### Actual behavior
pre:routes middleware works in admin pages as of keystone v0.3.x

**Comment by creynders** [comment]
@yatping we'll need a bit more info, what do you mean with `pre:routes middleware not working in admin pages`? 
Could you give a code sample?

**Comment by wmertens** [comment]
I think this is the same as #3162, I'll close this one in favor of that one which has line urls :)
