### ISSUE TITLE
Relationships and Polymorphism (Inherits functionality too limited)

### ISSUE THREAD

**Issue by feedyourmind** [keystonejs/keystone#2978]
I have a model like this:
list x - field relationship to p (parent)
p can be C1, C2 or C3 .. (for child1, 2 and 3)
in the admin ui, when I navigate from x to the p, it loads the fields of only the parent, instead of bringing up the right child (c1, 2 or 3) . 
This defies the whole point of modelling relationships with polymorphism.

To get around it, I had to model the whole thing differently:
I put the relationship field on the P like this:
P -> many X

and then on the X side, I added a relationship declaration for each child type:
X.relationship(..., ref:'C1')
X.relationship(..., ref:'C2')
X.relationship(..., ref:'C3')

At least this way, now I can navigate from X to the right P model. 
But this sucks:
- it is unnatural
- allows for invalid state of a X-P many-to-many when the intention was for it to be X-P Many-To-One
- it makes building the view with mongoose queries more challenging, because I can not use populate(....
- For every new Child of P a new relationship declaration is needed on the side of X

I guess, since I could do it using this workaround, a few changes could be done in the code to make it load the right child when the owner of the relationship is the other object (x in the example)

This is important, otherwise, it's really a very small benefit of using inheritance in the first place

**Comment by geloescht** [comment]
Thanks for your report. This issue has already been reported here #2321, so I am closing this issue as a duplicate. Please feel free to comment on #2321 with your thoughts!

**Comment by feedyourmind** [comment]
initially I added a comment in that ticket, but then I thought it's not really exactly the same.

from my perspective the thing I'm most interested in is for a way to navigate from one list to another, so, when displaying relationship information, I just needed to display links to the children as well as the parents. 

the way I interpreted ticket #2321 is as a more fundamental change , which will load the child list when specific id is requested. 
Anyway, I'll add my thoughts as a comment again, although I think what I'm talking about would be easier to implement and it would add huge value to people who use inheritance and collections until the other change is implemented.

**Comment by geloescht** [comment]
Both ideas, changing the item page to show all fields or simply swapping the links, are possible. At first I didn't think of all the places where the link would need to be changed, though.

**Comment by feedyourmind** [comment]
Seems like the following issue has been marked as a blocker for this 
Allow discriminatorKey to be set to existing field #2649

For the change proposed here of having the item page showing all fields, is it also a blocker?
if not, maybe it would be better if we reopen this issue, so that someone upgrades the item page until the more challenging change can be realized.

**Comment by geloescht** [comment]
Seems like it shouldn't be a blocker, removed the tag.
