### ISSUE TITLE
Allow the values of select fields to be generated dynamically

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#298]
Would be useful to have select fields that can generate their values dynamically based on the value of other fields in the item (or an other condition).

For example, a list of cities that depends on the country selected in another field.

Not sure how this would interact yet with features like the ability to pluck other values from the currently selected one, may need further investigation to ensure full support (or a new field type).

**Comment by olivierdupont** [comment]
I'm in need of this feature, I think this is already the case when the data is fetched but not when you are manipulating the data on the fly.  Correct?

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/allow-the-values-of-select-fields-to-be-generated-dynamically

**Comment by dhniels** [comment]
was this feature ever added, or a way to accomplish this?
