### ISSUE TITLE
Add support of single types

### ISSUE THREAD

**Issue by M0ustach3** [keystonejs/keystone#2981]
# Feature request

## Is your feature request related to a problem? Please describe.

This feature request is **not** due to a bug. I was wondering if it could be possible to have a single type option. For example, I imagined a website with a top banner that admins could change in their UI overtime. BUT this could get annoying if they do not understand that you have to **MODIFY** the existing row instead of creating one... This could lead to multiple duplicated rows.

## Describe the solution you'd like

This could be good to have an option to allow only one row in a table. For example, consider the following structure : 

A banner type with:

A title : string
A description: string

If a user wants to modify the existing data, we should only allow him to modify the current row and not to create other ones.

## Describe alternatives you've considered

I've considered checking if any existing row is present in the DB before doing any insert in the UI but this does not seem really optimized :/

EDIT : I also thought of using the Access-Control API to restrict delete and create on a specific type, only allowing update :)

## Additional context

None

**Comment by timleslie** [comment]
There are a few different ways this can be achieved. There's an open PR #2838 which you might want to pull in to your project as a custom list hook. We're currently doing design work on specialised "List Types" such as Singletons, Ordered Lists, etc, but there's no time frame on this yet as there are a lot of edge cases to be designed around. If you have a specific use case in mind then you're probably best off using the existing hooks system to prevent more than one item ever being created.

**Comment by M0ustach3** [comment]
@timleslie Alright, thanks a lot I will look into that ! :)
