### ISSUE TITLE
signin csrf error

### ISSUE THREAD

**Issue by sylarmeng** [keystonejs/keystone#2982]
### Expected behavior
When testing just one keystone instance on my computer,everything seemed to be ok. Today I deployed the second instance(copyed from the local instance) on a cloud server, both admin signin pages showed CSRF warning.
### Actual behavior
"There was an error with your request, please try again." always jumped out, and the csrf tokens of the request and responce were different. How could I solve this problem? 
Thanks!
### Steps to reproduce the behavior
Run the same keystone example, one on local computer, one on cloud server. 

After commented the seesion option
`'session options': {
	    cookie: { secure: true, maxAge: 31104000
	    }
	},`
the signin became all right. How the csrf related with the session and cookie?

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted and easy to manage for us maintainers. We'd kindly ask you to move this question to [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

Thanks! :pray:
