### ISSUE TITLE
Keystone.email rewrites to: argument

### ISSUE THREAD

**Issue by vitalbone** [keystonejs/keystone#2984]
If you call:

```javascript
const ADDRESSES = ['foo@example.com'];
keystone.Email('someview').send({to: ADDRESSES});
console.log(ADDRESSES);
```

Then you'll find your ADDRESSES constant was modified in place, and now looks like `[{email:'foo@example.com'}]`.

The argument shouldn't be modified in place. If it needs to be edited it should be cloned first.

+ @josephg

**Comment by mxstbr** [comment]
This should be fixed by the new `keystone-email` package, please try that one!
