### ISSUE TITLE
Error Start on Window OS

### ISSUE THREAD

**Issue by vmdao** [keystonejs/keystone#2985]
WindowOS: Windows_NT 10.0.10565
Log Errors:
Ouput Console: 

> [09:31:58] Using gulpfile F:\Apps\repository\test\test-ketstone\gulpfile.js
[09:31:58] Task 'watch:lint' is not in your gulpfile
[09:31:58] Please check the documentation for proper gulpfile formatting

File log:

> 0 info it worked if it ends with ok
1 verbose cli [ 'F:\\Apps\\projects\\nodejs\\node.exe',
1 verbose cli   'F:\\Apps\\projects\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart test-ketstone@0.0.0
6 info start test-ketstone@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info test-ketstone@0.0.0 Failed to exec start script
9 verbose stack Error: test-ketstone@0.0.0 start: `gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (F:\Apps\projects\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (F:\Apps\projects\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid test-ketstone@0.0.0
11 verbose cwd F:\Apps\repository\test\test-ketstone
12 error Windows_NT 10.0.10565
13 error argv "F:\\Apps\\projects\\nodejs\\node.exe" "F:\\Apps\\projects\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error test-ketstone@0.0.0 start: `gulp`
17 error Exit status 1
18 error Failed at the test-ketstone@0.0.0 start script 'gulp'.
18 error This is most likely a problem with the test-ketstone package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs test-ketstone
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls test-ketstone
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by AntuanKhanna** [comment]
The issue probably belongs to [keystonejs/generator-keystone](https://github.com/keystonejs/generator-keystone) and already fixed with [3fa24da2](https://github.com/keystonejs/generator-keystone/commit/3fa24da2562ddf31df86d9d1c09689889e6e1424#diff-2e6ad34bed54ee43674888cab984c475) commit.

Package in npm registry is outdated, to get latest changes you can update it directly from the repository.

**Comment by mxstbr** [comment]
Will publish a new version very soon, meanwhile cloning the `generator-keystone` repo should fix your issue as @AntuanKhanna correctly mentioned!
