### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2988]
# Feature request

Support running a Keystone project in Deno.

## Describe alternatives you've considered

Everything works perfectly with node, but there hasn't been a new nodejs release in 13 days, clearly it's an abandoned project.

## Additional context

- https://deno.land/v1
- https://twitter.com/JessTelford/status/1260756707690418177?s=20

**Comment by timleslie** [comment]
No thanks :-)
