### ISSUE TITLE
Add Static Type Checking with Hegel

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2989]
# Feature request

## Is your feature request related to a problem? Please describe.

[Adding types to our codebase is a non-starter](https://github.com/keystonejs/keystone/issues/1373).

The main problem types are solving is the static analysis. Could we have that without any of the downsides of TypeScript, like _adding types_?

[Yes](https://hegel.js.org/docs#benefits-and-disadvantages-over-typescript).

## Describe the solution you'd like

Add [Hegel's static type checker](https://hegel.js.org/docs/install) to our test / CI process (but no types).

## Describe alternatives you've considered

See #1373.

Also, we used to have Flow, but striped it out because it was noisy and annoying to work with.

## Additional context

- [Hegel docs](https://hegel.js.org)
- [Hegel vs Typescript](https://hegel.js.org/docs#benefits-and-disadvantages-over-typescript)
- [Random Twitter thread](https://twitter.com/devongovett/status/1262069817655259136)

**Comment by MadeByMike** [comment]
If it doesn't offer the same level of auto-completion in VSCode as TypeScript it's not valuable for me. Personally I care less about the purity of type safety, I just want to know what the item value contains in the async access control function I'm writing without stepping through 5 layers of Keystone's core code.
