### ISSUE TITLE
Reorder or sort uploaded files in Admin UI

### ISSUE THREAD

**Issue by rinku9900** [keystonejs/keystone#2990]
I want to know if Keystone provides a functionality to reorder or sort uploaded files. I am using Types.LocalFiles and I want to reorder these files in the admin UI once they got uploaded to DB. Some sort of drag and drop functionality. If keystone does not provide this support, then how to accomplish using hooks or implementing own logic? See below snapshot for reference.

![image](https://cloud.githubusercontent.com/assets/7141716/15757653/a9f048ba-28d4-11e6-8fc5-3d0f4c5c2957.png)

**Comment by mxstbr** [comment]
We don't currently support this feature, but thanks for letting us know you want this, we appreciate it! :pray:

We're closing all feature requests here to keep the issue tracker unpolluted—I've moved this to ProductPains, feel free to upvote it there: https://productpains.com/post/keystonejs/allow-reordering-of-cloudinaryimages
