### ISSUE TITLE
fileName option ignored for Types.LocalFile ?

### ISSUE THREAD

**Issue by r3wt** [keystonejs/keystone#2991]
### Expected behavior

supplied function is used to format the file name into a human readable, seo friendlyish format:

```js
fileName: function(item,file){
	var n = ''+item.title;
	n = n.toLowerCase();
	n = n.replace(/[^a-zA-Z0-9 ]/g,"").replace(' ','-');
	return n + '.' + file.extension;
},
```

### Actual behavior
some random hashing algorithm is used to generate the file name instead

### Steps to reproduce the behavior

```js

var keystone = require('keystone');
var Types = keystone.Field.Types;

var ds = new keystone.List('Data Sheet',{autocreate: true});

ds.add({
	title:{type: String},
	file:{
		type: Types.LocalFile, 
		dest: 'public/ul/',
		allowedtypes: ['application/pdf','application/x-pdf','text/html'],
		fileName: function(item,file){
			var n = ''+item.title;
			n = n.toLowerCase();
			n = n.replace(/[^a-zA-Z0-9 ]/g,"").replace(' ','-');
			return n + '.' + file.extension;
		},
		format: function(item, file){
			return '<a target="_blank" href="../../ul/'+file.filename+'">View Datasheet</a>';
		}
	},
	products: { type: Types.Relationship, ref: 'Product', many: true}
});

ds.schema.post('save',function(){
	var products = this.products;
	var id = this._id;
	keystone.list('Product').model.update({
		_id: { $in : products }
	},{
		$push: { datasheets: id }
	},{
		multi: true
	},
	function(err,nAff){
		
	});
});

ds.register();

```

**Comment by geloescht** [comment]
Are you sure it is not a mistake in capitalization? The docs say it's "filename" and I remember it working just fine for me.

**Comment by r3wt** [comment]
@geloescht i will check when i get back from vacation. you are probably right, i may have mistakenly assumed camelcase since its a javascript best practice.

**Comment by r3wt** [comment]
@geloescht you were correct. closing

**Comment by JedWatson** [comment]
Maybe we can add something to the docs to make the case jump out? Or maybe it's just user beware... We use camelCase everywhere but I believe the difference here is that "filename" is one word, not two concatenated... that or it may have been done to be consistent with another API.

**Comment by geloescht** [comment]
Or, maybe we could log a warning about any unrecognized option.
