### ISSUE TITLE
DateTime through TimeZone

### ISSUE THREAD

**Issue by maxkoryukov** [keystonejs/keystone#2995]
### Expected behavior

Admin's interface should display and save datetime using one certain timezone.

### Actual behavior

DateTime is shifted, when the same post is viewed and saved in admin UI in different timezones.

### Steps to reproduce the behavior

Model:

```javascript
Post.add(
	'Post settings',
	{
		publishedDate: { type: Types.Datetime, index: true, dependsOn: { state: 'published' } },
	}
)
```

I have a server in timezone +x hours.

I am in location with timezone +y hours. I have opened and saved a post (I did't edit the `publishedDate` field, and there is no virtuals/handlers, it is a field out of the box). 

Then, my friend in timezone +z hours, did the same things.

Now, I have the post with shifted publishedDate, but nobody edit it.

I am sure, the problem is somewhere between displaying the value, and saving it back to DB, but in one direction (one of GET/SET , lets think, it is GET data) was applied timeshift-conversion, and in other direction (SET, save to DB), wasn't.

Sorry for my english;) but bug exists..

**Comment by jstockwin** [comment]
@maxkoryukov: This is a duplicate of #1345, which was fixed in current master with #2894. 

What version of keystone are you using? (I'm hoping it's 0.3.x from npm, rather than the current master version, since it _should_ be fixed in master). 

@keystonejs/core-devs - Can we somehow get #2894 merged into 0.3.x?

**Comment by maxkoryukov** [comment]
@jstockwin, sorry, and thank you.. really, I have added duplicate...

I use **0.3.16**

Plz, tell me: is it safely to use **master** (not the NPM version) for production?

**Comment by jstockwin** [comment]
@maxkoryukov not sure I'm confident answering that, but maybe check out #1612, specifically "This means that master may be unstable for a while". Perhaps @mxstbr may have a little more to add on this though.
