### ISSUE TITLE
Cannot edit items if property type is Types.Html

### ISSUE THREAD

**Issue by jackoob** [keystonejs/keystone#2998]
Hi all. I'm experiencing following bug with keystone 3.17.

### Expected behavior
Being able to edit items in the admin UI list

### Actual behavior
The item in the admin UI list is not clickable.

### Steps to reproduce the behavior
I have this simple model:
```
var keystone = require('keystone');
var Types = keystone.Field.Types;

var Testtt = new keystone.List('Testtt', {
    map: { name: 'name' },
	autokey: { from: 'name', path: 'slug', unique: true },
	sortable: true,
	noedit: false
});

Testtt.add({
	name: { type: Types.Html, wysiwyg: true, initial: true, required: true },
});

Testtt.defaultColumns = 'name'
Testtt.register();
```

Now, if I create new item in admin UI and go back to list view, the item I created is not clickable and cannot be edited anymore.

Using search to navigate to the item edit view work well.

**Comment by mxstbr** [comment]
Not replicatable on current `master`, will close for now! Feel free to respond again if this is still happening to you.
