### ISSUE TITLE
Fields with Underscores Cause Runtime Error when Using Postgres/Knex

### ISSUE THREAD

**Issue by hew** [keystonejs/keystone#3004]
# Bug report

## Describe the bug

If you create a List with a field that has an underscore using Postgres/Knex, Keystone errors out. 

## To Reproduce

1. Start a new keystone project
2. Choose postgres/Knex
3. Create a list with a field that has an underscore (ie: `user_id`)
4. Try to view that list

```
 "@keystonejs/adapter-knex": "^10.0.0",
 "@keystonejs/app-admin-ui": "^6.0.0",
```

## Expected behaviour

Keystone should not crash when viewing a list that has an underscore.

## Screenshots

![image](https://user-images.githubusercontent.com/3103241/82475068-c6cc7180-9a80-11ea-9bf6-e9316559dc20.png)

## System information

- OS: macOS
- All browsers

## Additional context

Fields with underscores seem to be missing at the graphQL filtering level.

**Comment by hew** [comment]
Reproduced here. Just needs a database with a `player` table and a field with an underscore.

https://github.com/hew/keystone-postgres-error-reproduced.

**Comment by hew** [comment]
Issue is caused by [this line].(https://github.com/keystonejs/keystone/blob/63e00d805f3653863002befdaeda74c711f36f6b/packages/adapter-knex/lib/adapter-knex.js#L659) and [this line](https://github.com/keystonejs/keystone/blob/63e00d805f3653863002befdaeda74c711f36f6b/packages/adapter-knex/lib/adapter-knex.js#L652)

I'll see about pushing a fix tomorrow at work.

**Comment by MadeByMike** [comment]
Oh nice pick up! That should be fixed.

**Comment by BikramjeetSingh** [comment]
Is this already fixed? If not, can I pick this up?

**Comment by hew** [comment]
@BikramjeetSingh You can pick it up. Thanks.

**Comment by BikramjeetSingh** [comment]
Okay, I am looking into this issue.

**Comment by BikramjeetSingh** [comment]
I have created a PR for this bug [here](https://github.com/keystonejs/keystone/pull/3225). Could you please take a look? @hew @MadeByMike

**Comment by BikramjeetSingh** [comment]
My PR has been merged, so this issue can be marked as resolved and closed.

**Comment by hew** [comment]
Nice work. Closing this issue. Thanks @BikramjeetSingh!
