### ISSUE TITLE
Angular 2 and sailsjs support

### ISSUE THREAD

**Issue by ajayphp** [keystonejs/keystone#3006]
Hi, 

I am newbie from LAMP stack  to MEAN stack and its been great to found you,
will try certainly. 

But while research i finalize of Angular 2 and sailsjs
as both latest version is really promising and feels would be future for mean stack. 

so, could you also add-on or another branch with Angular 2 and sails js
or advice me why react is good in admin rather Angular 2 

or how can i use on your stack with my Angular and sailsjs lib

Regards,
Ak

**Comment by morenoh149** [comment]
You may have to learn more about javascript development. The [sydjs](https://github.com/JedWatson/sydjs-site) site is a good example of using keystone. Ultimately you have total control over your frontend, keystone only concerns itself with providing a UI to the backend.

**Comment by ajayphp** [comment]
Hi ,
Thx. for your reply . 

would you please give me direction steps of how could i use keystone with Angular 2 and sails js ?

Regards,
AK

**Comment by morenoh149** [comment]
Angular 2 you could get a keystone backend to deliver the bundle with enough work. I wouldn't recommend sails js but it is expressjs based so you could try https://github.com/keystonejs/keystone/wiki/How-to-Add-Keystone-to-an-Already-Existing-Express-App

but these usecases are fairly rare and keystone is still an early project. So you're going to have to solve a lot of things yourself. I'd recommend http://www.nodaljs.com/ if you want something more rails/django -esque and figure out how to get keystone's adminUI to play nice with it.
