### ISSUE TITLE
Deply to heroku

### ISSUE THREAD

**Issue by lazydino** [keystonejs/keystone#3009]
Hi,

Anyone try successfully with the "Deploy to Heroku" button? The build status of KeystoneJS project is "build|failing"?

**Comment by brianjd** [comment]
My guess is that https://github.com/JedWatson/keystone-starter is stale.

**Comment by mxstbr** [comment]
Indeed it is!

We're currently hard at work on 0.4, so the current `master` is very unstable and changes daily. `keystone-starter` has not been updated since August of last year, and we'll probably only update it after the 0.4 release. Thanks for pointing that out!

**Comment by morenoh149** [comment]
it should still properly deploy 3.x

@brianjd in what ways could the starter be stale? I'm looking at it now and all I can image in updating the deps, but see no reason why older deps would fail.


@lazydino I don't think the build status of keystone master influences the keystone-starter project. What is your exact error?

**Comment by brianjd** [comment]
@morenoh149 Sorry, I should have been more specific.  I bumped the engine versions (node/npm) in a fork I just made, and the "one click deploy" built/deployed fine.  It just crashed after as it was trying to connect to a local instance of Mongo.  It seems support wasn't added to Keystone for MongoLab's new connection string variable till April 12 of this year (https://github.com/keystonejs/keystone/commit/a6c1a3de59c5ec36e31e8de6729a67abcfa63052).

**Comment by morenoh149** [comment]
the npm engine issue on heroku has been documented before https://github.com/keystonejs/keystone/issues/1680 we haven't come to a consensus on how to address it sadly.

If theres a mongo URI fix that landed later it would make sense to update the dependency in the start to the latest in the 3.x line https://github.com/keystonejs/keystone/blob/master/HISTORY.md#v0318--2016-04-27

**Comment by mxstbr** [comment]
Ah yeah, you're right @morenoh149, my bad! :pray:
