### ISSUE TITLE
npm start stops with ReferenceError: bind is not defined

### ISSUE THREAD

**Issue by drsdre** [keystonejs/keystone#3010]
### Expected behavior

After first setup(yo keystone) to have 'npm start' start the KeystoneTest application.

### Actual behavior

$ npm start

> drekeystonetest@0.0.0 start /var/www/nodejs/keystone/my-test-project
> gulp

[21:43:03] Using gulpfile /var/www/nodejs/keystone/my-test-project/gulpfile.js
[21:43:03] Starting 'watch'...
[21:43:03] Finished 'watch' after 59 μs
[21:43:03] Starting 'runKeystone'...
/var/www/nodejs/keystone/my-test-project/node_modules/lodash/index.js:11775
    lodash.bind = bind;
                  ^

ReferenceError: bind is not defined
    at runInContext (/var/www/nodejs/keystone/my-test-project/node_modules/lodash/index.js:11775:19)
    at Object.<anonymous> (/var/www/nodejs/keystone/my-test-project/node_modules/lodash/index.js:12247:11)
    at Object.<anonymous> (/var/www/nodejs/keystone/my-test-project/node_modules/lodash/index.js:12278:3)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/var/www/nodejs/keystone/my-test-project/node_modules/grappling-hook/index.js:78:9)
[21:43:04] 'runKeystone' errored after 1.05 s
[21:43:04] Error: Command `node keystone.js` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at maybeClose (internal/child_process.js:819:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE
npm ERR! drekeystonetest@0.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the drekeystonetest@0.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the drekeystonetest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs drekeystonetest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls drekeystonetest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/nodejs/keystone/my-test-project/npm-debug.log

### Steps to reproduce the behavior

Init of Keystone:
$ yo keystone

Welcome to KeystoneJS.

? What is the name of your project? KeystoneTest
? Would you like to use Jade, Swig, Nunjucks, Twig or Handlebars for templates? [jade | swig | nunjucks | twig | hbs] hbs
? Which CSS pre-processor would you like? [less | sass | stylus] less
? Would you like to include a Blog? Yes
? Would you like to include an Image Gallery? Yes
? Would you like to include a Contact Form? Yes
? What would you like to call the User model? User
? Enter an email address for the first Admin user: myname@gmail.com
? Enter a password for the first Admin user:
 Please use a temporary password as it will be saved in plain text and change it after the first login. admin
? Would you like to include gulp or grunt? [gulp | grunt | none] gulp
? Would you like to create a new directory for your project? No
? ------------------------------------------------
    KeystoneJS integrates with Mandrill (from Mailchimp) for email sending.
    Would you like to include Email configuration in your project? No
? ------------------------------------------------
    KeystoneJS integrates with Cloudinary for image upload, resizing and
    hosting. See http://keystonejs.com/docs/configuration/#services-cloudinary for more info.
    
    CloudinaryImage fields are used by the blog and gallery templates.
    
    You can skip this for now (we'll include demo account details)
    
    Please enter your Cloudinary URL: 
? ------------------------------------------------
    Finally, would you like to include extra code comments in
    your project? If you're new to Keystone, these may be helpful. Yes

P.s. Initially the framework failed with 'Task 'watch:lint' is not in your gulpfile', so I removed the watch:lint task from gulpfile.js.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted and easy to manage for us maintainers. We'd kindly ask you to move this question to [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

Thanks! :pray:

**Comment by drsdre** [comment]
This was a bug filing not a request for help...

**Comment by mxstbr** [comment]
Ah yes, sorry, I misunderstood the issue, my bad! :pray:

Would you mind reporting this over at the `generator-keystone` repo so we can take a look? Thanks! https://github.com/keystonejs/generator-keystone
