### ISSUE TITLE
format option not working for Date type

### ISSUE THREAD

**Issue by autoboxer** [keystonejs/keystone#3011]
### Expected behavior

Providing a format option as a moment.js string will show that format for placeholder text in the Date field.
Providing a format option as a moment.js string will display a selected date using that format.

### Actual behavior

The placeholder always displays 'YYYY-MM-DD'.
Providing a format option as a moment.js string doesn't affect the value displayed for a selected date.

### Steps to reproduce the behavior

Create a Date field with `format='MMM Do YYYY'` and note that it doesn't affect the placeholder or the displayed date once one is selected.

**Comment by JedWatson** [comment]
Closed by #3012
