### ISSUE TITLE
[0.4] Admin UI 404 polls backend

### ISSUE THREAD

**Issue by josephg** [keystonejs/keystone#3013]
If you go to an admin page for a document that doesn't exist, the browser page polls the database for the non-existent document.

**Comment by mxstbr** [comment]
Ahh, nice catch!

This is happening because I assume a network error by default and keep polling until some data comes in, which will obviously never come for a 404. See `admin/client/App/screens/List/actions/items.js`!

**Comment by jstockwin** [comment]
This is a duplicate, or perhaps just similar, to #2846.

**Comment by mxstbr** [comment]
Ah yeah, that _is_ a duplicate, thanks @jstockwin!
