### ISSUE TITLE
Update on 0.4 branch

### ISSUE THREAD

**Issue by kevinsimper** [keystonejs/keystone#3022]
What are the status of 0.4 branch? The readme was updated 11 months ago and it seems a bit outdated still having saying the same.

I understand that things take time, but what can be done to help? What is missing?

**Comment by mxstbr** [comment]
We very recently finished the admin interface rework. (with the exception of a few remaining bugs) The last big step for the the 0.4 release is a complete rework of the file fields, which has been holding us back for a while!

I've been working on other things the past few weeks, but I'm back to Keystone with the beginning of next week and will kick this off!

> what can be done to help? What is missing?

Fix bugs that are in the issue tracker, we'd really appreciate the help!

For easy bugs, there's a `reproduced (e2e)` label which you can search for, those bugs have e2e tests that replicate the problem. Running those will tell you what fails, and then you can fix the problem and run the tests again to see if it's fixed!

**Comment by kevinsimper** [comment]
What could we write in the readme? :)

**Comment by morenoh149** [comment]
I think the readme does explain the current status of the project. The only thing that would clarify further would be a list of issues until the change is ready.

For a list of what's remaining https://github.com/keystonejs/keystone/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.4.0 would give you a good overview.
