### ISSUE TITLE
Admin bundle pulls in loadash (despite it being excluded)

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#3023]
### Expected behavior

Loadash is in the list of excluded packages (it's part of the common bundle) and shouldn't be included by the dynamically generated Admin UI bundle.

### Actual behaviour

For some reason, it's not being excluded. This bumps our file size up by about 70k.

### Steps to reproduce the behaviour

run this:

```
KEYSTONE_WRITE_DISC=true KEYSTONE_WRITE_BUNDLES=true KEYSTONE_PREBUILD_ADMIN=true npm start
``` 

Keystone will generate static files for the bundles and a disc overview of what's in them.

Open `admin/bundles/disc/App/index.html` in your browser to view what's included.

**Comment by JedWatson** [comment]
@mxstbr you probably should be aware of how I fixed this :)

**Comment by mxstbr** [comment]
Thanks for the ping, that makes a lot of sense! Will keep in mind!
