### ISSUE TITLE
Option createInline: true breaks admin ui

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3028]
### Expected behavior

Setting `createInline: true` on a relationship field should work correctly. 

### Actual behavior

Once you create the item, the list view no longer loads. 

### Steps to reproduce the behavior

Run `node test/e2e/server.js --env default --config ./test/e2e/adminUI/nightwatch.json --test test/e2e/adminUI/tests/group999FixMe/3028.js`

**Comment by geloescht** [comment]
The test passes for me, can this issue be closed and the test be moved?

**Comment by mxstbr** [comment]
Sounds good @geloescht!

**Comment by export-mike** [comment]
working as expected with new e2e tests also: https://github.com/keystonejs/keystone/commit/73d144ebe825f761e5afdd2e5b91ab95bd01408c
