### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone#303]
Since the site I am working on is an existing one and I'm transferring stuff from a PHP site to Keystone… how do I redirect pages that are now dead?

For example: 

- index.php => /
- sermons.php => /
- sermon.php (with query string) => /sermon/{id}

**Comment by kraigh** [comment]
FWIW, I was able to implement the [express-redirect](https://www.npmjs.org/package/express-redirect) plugin with my keystone app by requiring it and just doing
```javascript
keystone.redirect("/foo", "/bar");
redirect(keystone);
keystone.start();
```
I definitely like the idea of being able to support query arguments on both sides though, as @JedWatson mentioned above. Would definitely help preserve SEO juice when redeveloping an existing site.

**Comment by cantuket** [comment]
It would be extremely helpful to be able to specify 301 vs 302 redirects with this feature.

**Comment by ericelliott** [comment]
If you're already using a reverse proxy from nginx (which I do for all my Node powered sites), I recommend implementing your redirects at that level for better performance, and to keep the details of your old site's configuration out of your new site/application code.

**Comment by cantuket** [comment]
Awesome, thanks @ericelliott 

I like this solution better. Worked great!

**Comment by ericelliott** [comment]
`\( ﾟヮﾟ)/`

**Comment by ericelliott** [comment]
@jamlen @JedWatson Do we need to keep this open tracking some planned work, or should we close this ticket?

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/redirects

**Comment by yao23** [comment]
@JedWatson is there any way to redirect naked subdomain to www subdomain, for example, from https://example.com to https://www.example.com?

**Comment by mxstbr** [comment]
@yao23 that's a DNS thing, it has nothing to do with Keystone. Here's a [guide for nginx](https://www.digitalocean.com/community/tutorials/how-to-redirect-www-to-non-www-with-nginx-on-ubuntu-14-04) for example.

**Comment by yao23** [comment]
@mxstbr I have no permission to change the server setting, so achieve it in code:

```
/* Keystone/routes/middleware.js */
/**
 Redirect naked domain (example.com) to full domain (www.example.com)
 */

exports.redirectToFullDomainName = function(req, res, next) {
	if(req.headers.host === 'example.com') {
		return res.redirect('http://www.example.com'+req.url);
	}
	next();
};

/* Keystone/routes/index.js */
// Common Middleware
keystone.pre('routes', middleware.redirectToFullDomainName);
keystone.pre('routes', middleware.initLocals);
keystone.pre('render', middleware.flashMessages);
```

**Comment by alexgrant999** [comment]
@JedWatson Hi Jed,
I am trying to get all pages on my site: www.findyoga.com.au to redirect to the https instead of http as google is indexing both the secure and non-secure sessions.  Is there an easy way to get a redirect happening?  
Thanks:)

**Comment by cbstodd** [comment]
Hey guys, a bit of a noob question (I can't find anything anywhere). I'm hosting on Heroku, and I'm noticing that my Google search results are showing my https://colinstodd-v2.herokuapp.com in the results. I'm looking to create a 301 redirect to redirect the app to its home page/custom domain http://www.colinstodd.com (or home). Everything is set up correctly, I just want to get rid of the https://colinstodd-v2.herokuapp.com/ from being indexed by Google, and Heroku suggests setting up a 301 redirect. I thought to do `keystone.redirect('colinstodd-v2.herokuapp.com', '/');` but that's not working. 

Im a bit lost. Sorry to be the noob. FWIW, I'm loving Keystone :)

**Comment by danurbanowicz** [comment]
@cbstodd If the Google results are your only issue, you could do this by placing a canonical tag in the `<head>` for each of your pages e.g.

`<link rel="canonical" href="http://www.colinstodd.com">`

This would eventually prevent Google from displaying the Heroku Domain in search results and is better than setting up a redirect as it is often useful to be able to access your site via the Heroku Domain, independently of your own custom domain(s).
