### ISSUE TITLE
format option not working for Datetime type

### ISSUE THREAD

**Issue by autoboxer** [keystonejs/keystone#3030]
### Expected behavior

Providing a format option as a moment.js string will show that format for placeholder text in the Datetime field.
Providing a format option as a moment.js string will display a selected Datetime using that format.
Providing `false` in the format string will not display any placeholder text and the Datetime field will be formatted using the default format.

### Actual behavior

The placeholder for the date portion is missing.
The placeholder for the time is hardcoded to `h:m:s a`.
Providing a format option as a moment.js string doesn't affect the value displayed for a selected Datetime.

### Steps to reproduce the behavior

Create a Datetime field with `format='MMM Do YYYY h:mm a'` and note that it doesn't affect the placeholder or the displayed Datetime once one is selected.

**Comment by JedWatson** [comment]
Fixed by #3032
