### ISSUE TITLE
change label @ createList changes listKey

### ISSUE THREAD

**Issue by swang2019** [keystonejs/keystone#3032]
# Bug report

change label @ createList changes listKey

keystone.createList('Passenger', {
    fields: {
........
},
     label: 'Example',
});

expect only admin UI to be show Passenger as Example, however, this field in fact = change "Passenger" to "Example"

**Comment by timleslie** [comment]
I'm not sure I understand what the issue is here. Could you please provide some more descriptions, possibly with screenshots pointing out where you're seeing unexpected behaviour?

**Comment by swang2019** [comment]
As documented “label” -> refers to value of display(only) label on Admin UI, however, the actual behavior is it’s override the “listKey”….

**Comment by MadeByMike** [comment]
The label doesn't override the list key. You can see how it works here: 

https://github.com/keystonejs/keystone/blob/master/packages/app-admin-ui/client/classes/List.js#L16

I had a good look through the code, everywhere the label is used, and I can't see anywhere it's used other than for display purposes.

@swang2019 could you describe the error or odd behaviour you are seeing?

**Comment by Vultraz** [comment]
The server-side `List` class doesn't override `key` either 🤔

**Comment by swang2019** [comment]
> The label doesn't override the list key. You can see how it works here:
> 
> https://github.com/keystonejs/keystone/blob/master/packages/app-admin-ui/client/classes/List.js#L16
> 
> I had a good look through the code, everywhere the label is used, and I can't see anywhere it's used other than for display purposes.
> 
> @swang2019 could you describe the error or odd behaviour you are seeing?

It's easy to reproduce, code:

keystone.createList('Outcome', {
    fields: {
        something: {type: Text, label: 'something',},
}
   label:'test' ,
});

see what happened...

**Comment by swang2019** [comment]
<img width="493" alt="Screen Shot 2020-07-14 at 12 01 34 AM" src="https://user-images.githubusercontent.com/46506305/87326429-49474e00-c565-11ea-9f59-2fcef3a15768.png">
I don't understand one one actually try itself and review the bug.. it's super easy to reproduce.

**Comment by joselcvarela** [comment]
I am experiencing this issue too.
That means, when defining `label` in `createList` the mutation names are also reworded to whatever the `label` field includes.
For example:
```
keystone.createList('User', {
...
label: 'Awesome User'
})
```

then the mutation name will be:
```
mutation { createAwesomeUser(...) }
```

Could anyone help on this?

**Comment by joselcvarela** [comment]
Now I found the problem. 
In `creatingList` I was using `label` but in Admin UI  some labels still not changed. So I have populated `plural` which caused this mess.
I think the solution is or user `label` in all the Admin UI or add another fiedl `labelPlural` to handle this cases.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
