### ISSUE TITLE
Ability to set the admin key of a list to something other than 'name'

### ISSUE THREAD

**Issue by tomchambers2** [keystonejs/keystone#3034]
### Expected behavior
I have a list called Books which has title, author and numPages. I'd like 'title' to be the key that is used to be made clickable in the admin panel and also for linking to to other lists. I could call title name instead but it's a bit odd and I'm already using name for the person who added the book.

### Actual behavior
The name key is used as the identifier and link to the list item

**Comment by creynders** [comment]
This is already possible, using the `map` configuration option:

```js
var Post = new keystone.List('Post', {
    autokey: { path: 'slug', from: 'title', unique: true },
    map: { name: 'title' },
    defaultSort: '-createdAt'
});
```

**Comment by tomchambers2** [comment]
Great thanks!
