### ISSUE TITLE
Minified exception in admin UI

### ISSUE THREAD

**Issue by lazamar** [keystonejs/keystone#3042]
### Expected behavior
 Load admin tab for model and show records
### Actual behavior
 Stuck in loading animation
### Steps to reproduce the behavior
I am not sure. It started happening in some of my models yesterday when I reinstalled keystone (I am pulling keystone straight from github, v0.4)

![screenshot_2016-06-15_09-56-40](https://cloud.githubusercontent.com/assets/11493705/16074225/6b8ecf58-32e1-11e6-8803-67de6fca3a14.png)

**Comment by mxstbr** [comment]
Can you do `npm run build:dev` and then open it again? That should show an unminified error which is a lot more helpful. :+1:

**Comment by benkroeger** [comment]
check your List's `defaultColumns` property.
Had the same issue today – I used a `propertyName` in `defaultColumns` that wasn't defined on my List (via `List.add()`)

**Comment by dijs** [comment]
I am seeing this also intermittently, I tried commenting out my defaultColumns, but still no luck. It happens on all my different document types.

**Comment by Anjmao** [comment]
I have the same problems, copied blog example and it fails on comments page. @dijs here is tutorial how to link keystone https://github.com/Anjmao/keystone#linking-keystone-for-development-and-testing

**Comment by Anjmao** [comment]
Here is some errors with dev build. I'm using blog demo website code.
<img width="1125" alt="keystoneerrors" src="https://cloud.githubusercontent.com/assets/3028012/16715158/517b3e58-46e1-11e6-94e5-36e23d882e9e.png">

**Comment by mxstbr** [comment]
@Anjmao ah yes, those are new with React 15.2. @JedWatson why u merge stuff without testing it?! We need to pin React to 15.1 until we've resolved those, sorry for the issues!

A quick `npm install react@15.1` should resolve this issue temporarily!

**Comment by Anjmao** [comment]
@mxstbr I installed react@15.1, but some peer dependencies like `react-addons-css-transition-group` need react 15.2 and I got event more errors.

**Comment by JedWatson** [comment]
@mxstbr they're not errors, just warnings. The issue's about getting stuck on refer-loading, which isn't related to React 15.2

...I realise they show up as errors in the console, despite being labelled "Warning". From what I understand, they only show up in the dev build, not in production builds. They're meant to annoy us so we fix things that will break with React 16, not stop us from updating 😛 

The actual issue that I'm seeing here is the list is getting an invalid default column `createdAt` and we need to handle that gracefully (rather than crashing). Same thing happens with all the built-in fields (`id` is another culprit)

**Comment by Anjmao** [comment]
@JedWatson I see problem with id field which is not described in FieldTypes.js. Two files which cause crashes ItemsTableRow.js
```js
var cells = this.props.columns.map((col, i) => {
			var ColumnType = Columns[col.type] || Columns.__unrecognised__;
			var linkTo = !i ? `${Keystone.adminPath}/${this.props.list.path}/${itemId}` : undefined;
                         // crashes if columnType is not defined
			return <ColumnType key={col.path} list={this.props.list} col={col} data={item} linkTo={linkTo} />;
});
```
and RelatedItemsList.js

```js
var cells = this.state.columns.map((col, i) => {
                       // crashes if columnType is not defined
			const ColumnType = Columns[col.type] || Columns.__unrecognised__;
			const linkTo = !i ? `${Keystone.adminPath}/${this.props.refList.path}/${item.id}` : undefined;
                        // crashes if columnType is not defined
			return <ColumnType key={col.path} list={this.props.refList} col={col} data={item} linkTo={linkTo} />;
});
```

Probably we can create new field type called IdType or reuse KeyType ?

**Comment by mxstbr** [comment]
These problems should now all be resolved, I don't have any anymore. I'll close this for now, but feel free to comment again if this is still happening for you!
