### ISSUE TITLE
atTracking and byTracking don't create at and by fields

### ISSUE THREAD

**Issue by thekevinbrown** [keystonejs/keystone#3046]
# Bug report

## Describe the bug

With this list:

```typescript
import { Text } from '@keystonejs/fields';
import { atTracking, byTracking } from '@keystonejs/list-plugins';

export const FormSubmission = {
	fields: {
		formName: { type: Text },
	},
	access: true,
	plugins: [atTracking(), byTracking()],
};

```

I run with `dropDatabase: true` and it does not create any fields for at or by tracking. The Admin UI shows just the `formName` field.

## To Reproduce

Happy to provide a reproduction if needed.

## Expected behaviour

As per [the docs](https://www.keystonejs.com/keystonejs/list-plugins/at-tracking), I expected these plugins to add the needed fields to the list, which they don't seem to do. Do I need to also add the fields myself?

## Screenshots

![Screen Shot 2020-05-26 at 4 49 35 pm](https://user-images.githubusercontent.com/1531750/82868998-e972f480-9f70-11ea-8e98-64965908e70e.png)

## System information

- OS: macOS
- Browser (if applies) N/A

## Additional context

```
"dependencies": {
	"@keystonejs/adapter-knex": "10.0.1",
	"@keystonejs/app-admin-ui": "6.0.2",
	"@keystonejs/app-graphql": "5.1.7",
	"@keystonejs/auth-password": "5.1.8",
	"@keystonejs/fields": "11.0.0",
	"@keystonejs/file-adapters": "file:keystone-file-adapters",
	"@keystonejs/keystone": "9.0.1",
	"@keystonejs/list-plugins": "6.0.0",
// etc
}
```

**Comment by thekevinbrown** [comment]
I think this was mostly confusion over the fact that the Admin UI doesn't show these values in the edit view as read only fields.

Looks like it's working now.

**Comment by MadeByMike** [comment]
Perhaps the should be show now that we have read-only fields
