### ISSUE TITLE
Knox in KeystoneJS  throws  error code 307 for amazon S3  

### ISSUE THREAD

**Issue by justinwen** [keystonejs/keystone#3054]
As dig around on KNOX Github , It is existing bug on KNOX . KNOW didn't handle the 307 redirect in their code. I haven't spent any time to read  the bug report pages. 
For those who interested:
https://github.com/Automattic/knox/issues/66

### Expected behavior
 Keystone can upload files to any S3 region  server. 

### Actual behavior

Keystone admin UI  throws an error with [Error: Amazon returned Http Code: 307]. 

### Steps to reproduce the behavior
1. It only  supports S3 bucket setup to US standard region. Recreate the bucket and point to US standard region. Problem solved. 

2. Bucket name shouldn't contain "DOT", otherwise,  admin UI will throw 301 error code.

**Comment by jstockwin** [comment]
@justinwen You can actually set the `region` config option for S3, which allows you to point at other locations, for example Ireland; either set `S3_REGION=eu-west-1` in your `.env` file, or add the following to `keystone.js`.
```
keystone.set('s3 config', { 
    bucket: 'my-bucket', 
    key: 'my-key', 
    secret: 'my-secret',
    region: 'eu-west-1'
});
```

You can see a list of region names here: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

However, you'll get an error when trying to use a region which only supports Signature Version 4, at least until this knox issue is fixed: https://github.com/Automattic/knox/issues/254

**Comment by mxstbr** [comment]
I'll close this, since it doesn't seems like this is something we can act upon/fix. Thanks for reporting this issue @justinwen!
