### ISSUE TITLE
Sauce labs configuration is breaking build

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#3057]
We're getting consistent errors from our sauce labs integration:

```
Extracting Sauce Connect
Waiting for Sauce Connect readyfile
20 Jun 04:18:14 - Sauce Connect 4.3.16, build 2396 39e807b
20 Jun 04:18:14 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
20 Jun 04:18:14 - Using CA certificate verify path /etc/ssl/certs.
20 Jun 04:18:14 - Starting up; pid 6078
20 Jun 04:18:14 - Command line arguments: sc-4.3.16-linux//bin/sc -i 5266.1 -f sauce-connect-ready-17903 -l /home/travis/sauce-connect.log
20 Jun 04:18:14 - Log file: /home/travis/sauce-connect.log
20 Jun 04:18:14 - Pid file: /tmp/sc_client_5266.1.pid
20 Jun 04:18:14 - Timezone: UTC GMT offset: 0h
20 Jun 04:18:14 - Using no proxy for connecting to Sauce Labs REST API.
20 Jun 04:18:14 - Resolving saucelabs.com to 162.222.75.243 took 3 ms.
20 Jun 04:18:15 - Started scproxy on port 52682.
20 Jun 04:18:15 - Please wait for 'you may start your tests' to start your tests.
20 Jun 04:18:15 - Starting secure remote tunnel VM...
20 Jun 04:18:15 - POST https://saucelabs.com/rest/v1/keystonejs/tunnels: HTTP response code indicated failure.
20 Jun 04:18:15 - Response: {"error": "Too many active user tunnels: 5 >= 5"}.
20 Jun 04:18:15 - Error creating tunnel.
20 Jun 04:18:15 - Cleaning up.
20 Jun 04:18:15 - Sauce Connect could not establish a connection.
20 Jun 04:18:15 - Please check your firewall and proxy settings.
20 Jun 04:18:15 - You can also use sc --doctor to launch Sauce Connect in diagnostic mode.
20 Jun 04:18:15 - Goodbye.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

We need to look into it, in the meantime I'm temporarily turning off those options so that we can at least see linter and unit test results on PRs.

cc @webteckie @jstockwin

**Comment by LorbusChris** [comment]
I used to get an error like this when tinkering around with travis for this: https://github.com/keystonejs/react-easy-universal/pull/22/

I think a tunnel identifier flag like `-i travis-${TRAVIS_JOB_NUMBER}` needs to be passed to the sauce client. However that won't work (or at least used to not work) with the `sauce_connect: true` option on travis. Instead one has to run the client, wait for the tunnel and close the tunnel manually each. 

see the .travis.yml in the PR linked above for an example, it also makes use of nightwatch-autorun though. I'm pretty busy right now, but if nobody else takes this on I can give it a try next weekend or so 

@nkbt

**Comment by jstockwin** [comment]
@JedWatson I believe that sometimes when the build fails, it doesn't close the tunnel afterwards. Try logging in to Sauce Connect and manually closing any active tunnels. Provided the builds are currently passing, that might well fix the problem. I realise that this is quite a temporary fix though...

**Comment by JedWatson** [comment]
Just realised this is good to close after your excellent work, @jstockwin!
