### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#306]
Keystone as a project could benefit significantly from collecting _some_ amount of information about installs and usage. This would help inform both technical and strategic decisions. Of course, these benefits must be weighed against privacy concerns, security risks, legal implications (re: GDPR) and the will of the community.

To give a concrete example, this could be as simple as securely reporting the node and keystone versions at install time (with other info, like IP address, being discarded).

_Without_ this information, the people supporting and developing Keystone can only rely on their personal usage and info gleaned from issues and other online discussions. This makes it _very_ difficult to answer the category of questions that may affect large numbers of users, eg. "can we drop support for node 8?". Conversely, even a _small_ amount of real world data can often make these questions trivial.

Going further, it would be hugely illuminating to collect, for example, the public host name of systems that deployed Keystone. This would let us get a better idea of the kinds of sites and project Keystone was being used for. (However, I'll be the first to admit, this is definitely more invasive, even if it was "opt in" only.)

Obviously, any functionality added in this regard would need to be documented transparently, clear in what it collected and secure.

Work do be done:

- A discussion of the data that would be useful, ethical, and practical to collect
- Engagement of the community for feedback
- Technical design (assuming we move forward with it)
- Implementation
- Documentation
- Support of the infrastructure required to collect the data

Morten Rand-Hendriksen raised adding similar functionality to Wordpress is [2016](https://mor10.com/the-case-for-wordpress-telemetry) and [2017](https://mor10.com/case-telemetry-wordpress). He covers a lot of the issues in those posts and there's discussion in [the associated ticket](https://core.trac.wordpress.org/ticket/38418). I'm sure there are other discussions we should be aware of too.

**Comment by jesstelford** [comment]
Interesting discussion here: https://twitter.com/ahmetb/status/1145747243028238336?s=20

**Comment by jesstelford** [comment]
Latest version of Next.js gives this output:

```
Attention: Next.js now collects completely anonymous telemetry regarding usage.
--
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
```

**Comment by u007** [comment]
nuxtjs telemetry wise is causing long lag in the startup time
