### ISSUE TITLE
[v0.4] Boolean dependsOn broken

### ISSUE THREAD

**Issue by andrewlinfoot** [keystonejs/keystone#3068]
### Expected behavior

Boolean fields should use the dependsOn property properly.
### Actual behavior

If you set a dependsOn condition for a Boolean field in one Model, it will have that condition for all Boolean fields in all models in the admin ui and therefore will not show up when you expect it to.
### Steps to reproduce the behavior

Create 2 Boolean fields in 2 separate models. Set dependsOn: SOME_CONDITION in one field in one model. Don't set a dependsOn condition in the Boolean field in the other model. Check the admin UI and it will have the same dependsOn condition for both fields.

**Comment by geloescht** [comment]
I thought I was able to reproduce this by navigating the admin UI in a certain way, but now I can't anymore. Are you using a revision before 1d16a7428c7be68a2706edd8224cf7a0907feb6d and after 5f0a2e4e927d40b120c0ee724dd31f5b48e719e3, maybe?

**Comment by webteckie** [comment]
Not sure I understand @andrewlinfoot way of duplicating this and/or whether it is the same issue I'm seeing but dependsOn is not working for fields marked `initial` and one fields depends on the other.  This is an existing e2e test that's broken.  It will be soon moved to https://github.com/keystonejs/keystone/tree/master/test/e2e/adminUI/tests/group999FixMe
.

**Comment by incubus8** [comment]
any update on this one?

**Comment by export-mike** [comment]
This is no longer an issue on the current master branch, I have tests for it in the current nightmare testing branch,

please reopen this issue if it reappears
