### ISSUE TITLE
Add native support for socket.io

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#307]
As discussed on this thread in the google group, socket.io integration works but is a bit tricky. We should look into how to make it supported via an option, so other users don't have to figure it out the hard way.

https://groups.google.com/forum/#!topic/keystonejs/FUGZmBJ4dRk

**Comment by jjhesk** [comment]
Is that now supported on with socket.io. If not, where is the best possible place that we can start putting the socket io code into the core library?

**Comment by esparragito** [comment]
I don't know if this helps but I've had success integrating with socket.io with:
````
keystone.start({
	onHttpServerCreated: function(){
		keystone.set('io', io.listen(keystone.httpServer) )
        }
})
````
and then using
````
var socket = keystone.get('io')
socket.on(//some socket event)
````

as middleware. Is there a hitch with this that I've missed?

**Comment by jorisw** [comment]
@esparragito I didn't have much luck with your code example. Only when I followed the longer code example at the bottom of URL that Jed posted, `/socket.io/...` URLs would begin to work on my Keystone app instead of showing `404`.

**Comment by taytayevanson** [comment]
Have you guys tried this before?
https://www.npmjs.com/package/keystone-live

I haven't... it looks interesting though. Check out `apiSockets()` maybe?

**Comment by taytayevanson** [comment]
Has anyone tried this?
https://www.npmjs.com/package/keystone-live

I haven't, but I'm about to. It looks interesting! I'm not familiar with Keystone yet though.
Check out `apiSockets().`

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/add-native-support-for-socketio
