### ISSUE TITLE
Framework/guidelines for worker processes

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#307]
The ability to perform asynchronous, recurring, background processing is required for a number of core pieces of Keystone functionality (ie. email handoff queues, data imports/exports, maybe definable workflows?) and is very common in web apps generally. We need to have an answer (or at least a strong opinion) on how this works.

Some things to consider:

* How are the discrete pieces of functionality packaged and interfaced with?
   - Modules returning a function?
   - Do they configure themselves?
   - How do they report status?
   - What/how/to where do they log? (eg. `debug` lib? What scope?)
* How is the functionality triggered?
   - Recurring? Eg. "Run, finish, sleep for 10 minutes then run again"
   - Repeating? Eg. "Every 10 minutes" (from start app start? "on the hour"?)
   - Scheduled? Eg. "Run at 2pm every Tuesday"
   - Prompted? Ie. run when triggered by another part of the app. It's quite common to use this in combination with one of the above.
* Where the workers are run, eg.
   - In the main app thread (v. handy on Heroku)
   - In a separate thread (nicer, more scalable, harder to "prompt")
* And concurrency?
   - A single thread (either a single "in app" or a single separate worker thread) is much simpler, but of course, sucks for scaling
   - Multi threaded is great but how do we control them? A single queue (redis) feeding multiple worker instances?

In Keystone Next, we used our own [`node-worker` package](https://www.npmjs.com/package/@thinkmill/node-worker). It provides a class that can be extended to implement new workers and implies a standard interface for workers. We've used it to run workers "in thread" and support "recurring" and "prompted" triggers. It also assumes only a single thread is running workers.

Care must also be taken to:

- Have decent logging/debugging options
- Be easy to monitor; possibly support/integrate with our health checks somehow (ie. flag if a worker is failing/hasn't run)
- Be easy to add new workers

@jesstelford notes that Phillip Lauriano (?) from Domain had spend time thinking about all this and had opinions.

**Comment by MadeByMike** [comment]
I'm not sure this should be a Keystone concern. Maybe make a call that we leave this to another library or package and close. @Molomby?

**Comment by molomby** [comment]
Sure :)
