### ISSUE TITLE
adapter-mongoose@8.1.1 incorrect save relationship

### ISSUE THREAD

**Issue by komenixx** [keystonejs/keystone#3078]
### I cannot save relationship field

I Have two schemas:

**`Country`:**
```
keystone.createList('Country', {
    fields: {
        name: { type: Text },
        code: { type: Text }
    },
});
```

and

**`Delivery`:**
```
keystone.createList('Delivery', {
    fields: {
        name: { type: Text },
        code: { type: Text },
        price: { type: Float },
        countries: { type: Relationship, ref: 'Country', many: true }
    },
    adminConfig: {
        defaultColumns: 'code, price, countries, payments'
    },
});
```

In previous version of adapter-mongoose i can save Delivery object with:

```
const cz = Country.findOne({code: 'CZ'})
await Delivery.create({ name: 'DHL', code: 'DHL', price: 9, countires: [cz._id] })
```

Now, with 8.1.1 when i run **same code the countries and not visible in AdminUI**.

Result of `Delivery.findOne({ code: 'DHL' })` is:
```
{
    "_id" : ObjectId("5ed4f581be63246d08910938"),
    "name" : "DHL",
    "code" : "DHL",
    "price" : 9,
    "__v" : 0
}
```

With GraphQL `connect` throught executeQuery works correctly. Problem is only with mongoose access

**Comment by timleslie** [comment]
`countires` <- Is this typo part of the problem?

**Comment by MadeByMike** [comment]
Hoping it's the typo but also noticing this relates to the fairly large version 8.0 changes.

**Comment by timleslie** [comment]
Since you have a many relationship, the countries data will not be stored on the `Delivery` table, so the result of your `Delivery.findOne()` query looks correct to me. What do you expect to see? You have a many-to-many relationship, so this data will be stored in a join table, not on the Delivery table.

**Comment by komenixx** [comment]
@timleslie  No, it isnt typo, i only made mistake when i wrote example here...

@MadeByMike Yes, its relates to 8.0 changes too, its probably relate to [New database schema](https://www.keystonejs.com/discussions/new-data-schema)


Yes, in previous version countries data was stored on the `Delivery` table.. I understand that now exists relationship join table but how can i access to data via Mongoose ? Populate for me doesnt work.

**Comment by timleslie** [comment]
You can access the data in the join table from the model stored in `_manyModels` on base mongoose adapter. In general, keystone does not aim to be a fully fledged ORM for working with the underlying data, so while certain operations are easy, others such as accessing join table data are less easy.

In general we would advise performing queries against the graphQL API if you need to find related data, unless there's a specific reason for bypassing this layer, in which case you're somewhat on your own. Hope this helps.

**Comment by komenixx** [comment]
Yes, it was more comfortable use Mongoose instead of typing complicated graphQL queries for trivial projects like blogs, etc..

In `New database schema` now i can choose from two complicated ways to querying data `oneline`, sadly and probably i am on my own :smile: .

With this update the keystone lost the one of the best values for me. I want to stay before the `New schema update` but in admin-ui is bug -> #2980 :face_with_head_bandage: 


Many thanks for explanation.
