### ISSUE TITLE
Usage analytics

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#3081]
Similar to #3075

I think it would be really valuable to collect anonymised metrics about feature usage for Keystone installs as well, from a back-end perspective. Enabled by default with a warning on first launch maybe?

Would be really valuable to understand:
- Number of lists configured, and number of fields in each list
- Which list options are actually being used in the wild (e.g. track, etc)
- Which Field types are used and what options are configured for them
- Whether various APIs are used (e.g. `UpdateHandler`, `Email`, hooks, etc)

I imagine the implementation being somewhat similar to `debug`... and of course data would be anonymised (so we could see there is a list w/ 15 fields, inc. 1 wysiwyg html field, etc but not the name of the list or the field keys)

Would allow us to focus on features that are being used, and know which APIs are safer to change down the track.

I'm not sure how best to prevent being sent analytics every time keystone starts in dev or production - could potentially create a lot of noise. But I think a hash of e.g. lists and fields would be sufficient to identify an individual keystone app, and we can ignore duplicates when the data is collected.

**Comment by JedWatson** [comment]
I'm going to stress, before anyone else does, that we *must* do this in a way that is clear about the data it captures, how to disable it, and make sure we don't leak _anything_ that could compromise the security or privacy of apps and intellectual property built on Keystone.

While I would really love to know everyone in the world who is using Keystone, and what they are doing with it, the fact that I can't is a somewhat fundamental tenant of open source and while I think adding metrics adds a huge amount of value to us as the development team, breaking trust with our users is absolutely not a thing we will ever do.

Does anybody know how other projects (e.g. Wordpress) have dealt with or implemented this sort of thing?

**Comment by ttsirkia** [comment]
This should be done very carefully. I'm not sure how even to build such tracking system that could collect enogh data to be useful but still maintaining the privacy. To get anything interesting, it should be very low-level tracking of using the API. An overview of models is pretty easy but does it tell enough about the usage?

Might be a bit different but have you checked out how Atom editor uses Google Analytics to collect some statistics?

**Comment by wmertens** [comment]
Not the models, but a list of field types in use would be good I suppose?

**Comment by ttsirkia** [comment]
Here is a link to the mentioned analytics in Atom: https://github.com/atom/metrics

**Comment by Noviny** [comment]
Closing this discussion as concluded/old.
