### ISSUE TITLE
Package dependencies version for the demo projects often fall behind

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#3083]
It's easy to forget to bump the package version in the demo projects. Ideally this would happen whenever Keystone packages were released and probably semi-regularly regardless. @MadeByMike hates this problem:

> I hate this problem
> -- @MadeByMike

Maybe we can hook something into the tail end of our package publishing process to bump the deps for all demo projects, test them and PR in the result?

**Comment by MadeByMike** [comment]
Resolved in #3352
