### ISSUE TITLE
[0.3] incorrect password on signin leads to timeout

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#3088]
### Expected behavior

On the signin page, when providing a registered e-mail, but a wrong password it should show an error.
### Actual behavior

No error is shown and the request times out
### Steps to reproduce the behavior

Try signing in with a wrong password.
### Solution

I think the bug's here: https://github.com/keystonejs/keystone/blob/v0.3.x/lib/session.js#L97
When the passwords do not match `err` has a value `undefined` and `isMatch` is `false`, which means the else-branch is executed and translates to `onFail(undefined)`. I'm guessing the fact no `err` object is provided somehow breaks error handling...

**Comment by Noviny** [comment]
We're closing 0.3 bugs, as we are no longer making updates to 0.3
