### ISSUE TITLE
atTracking 'createdAt' and 'updatedAt' create weird (and/or incorrect) dates in AdminUI

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#3103]
I have an `Article` list in which I want to use the `atTracking` plugin to add `createdAt` and `updatedAt` date fields.  

```
xport default async (keystone) => {
	keystone.createList('Article', {
		queryLimits: {
			maxResults: ARTICLE_MAX_RESULTS
		},
		access: limitListAccessToAdminUsers(false),
		plugins: [
			byTracking({
				createdByField: 'createdBy',
				updatedByField: 'updatedBy'
			}),
			atTracking({ createdAtField: 'createdAt', format: 'dd/mm/yyyy hh:mm' }, { updatedAt: 'updatedAt', format: 'dd/mm/yyyy hh:mm' })
		],
		schemaDoc: 'Published Articles',
		labelField: 'title',
		hooks: {
			resolveInput: listResolveInput,
			validateInput: listValidateInput
		},
      ....
```

However when I create a new Article through the AdminUI the dates for `createdAt` and `updatedAt` show weird and incorrect values that have nothing to do with the current date or time (the images below are from today, the 3rd of June, 2020)

![image](https://user-images.githubusercontent.com/60699805/83638772-f82d5d00-a5a9-11ea-95a1-40184008f4e4.png)

If I update the Article the `updatedAt` field changes, but in a weird way

![image](https://user-images.githubusercontent.com/60699805/83638852-15fac200-a5aa-11ea-8b92-4c4f9fdfaf63.png)

I thought that perhaps the date format was the issue, but when I omitted `format`, I got a more 'normal' date (in this case something like "3/20/2020", but still completely incorrect.  

The MongoDB item for this article shows

![image](https://user-images.githubusercontent.com/60699805/83639077-74c03b80-a5aa-11ea-9274-8835b7e7d642.png)

The current time is

`UTC +2	CEST	Central European Summer Time	Wed, 14:58:17`

**Comment by gautamsi** [comment]
recently `date-fns` was updated (finally) from `v1.30.1` to `v2.x` one of the breaking change is the format string.


one you provided has issues like `mm` means minutes with 0, you have to use `MM` for month. 

full formatting docs - https://date-fns.org/v2.10.0/docs/format

**Comment by ra-external** [comment]
Perfect, thanks.
