### ISSUE TITLE
0.4 model/admin UI bug? 

### ISSUE THREAD

**Issue by steveinatorx** [keystonejs/keystone#3109]
Seems like adding a new List model without a discrete "map" parameter blows up the admin UI now in 0.4 after adding a model in the UI and then attempting to list them. 
Wasnt this an optional param in the past that would just default to the doc _id?

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ItemsRow`.
 /keystone/js/packages.js:49130 warning()
 /keystone/js/packages.js:39783 Object.createElement()
 /keystone/js/admin.js:4087
  Array.map (native)()
 /keystone/js/admin.js:4084 Constructor.renderRow()
 /keystone/js/admin.js:4121 Constructor.render()
 /keystone/js/packages.js:35756 ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext()
 /keystone/js/packages.js:35782 ReactCompositeComponentWrapper._renderValidatedComponent()

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ItemsRow`.
 /keystone/js/packages.js:48738 invariant()
 /keystone/js/packages.js:46842 instantiateReactComponent()
 /keystone/js/packages.js:33567 instantiateChild()
 /keystone/js/packages.js:47346 traverseAllChildrenImpl()
 /keystone/js/packages.js:47362 traverseAllChildrenImpl()
 /keystone/js/packages.js:47434 traverseAllChildren()
 /keystone/js/packages.js:33590 Object.instantiateChildren()
 /keystone/js/packages.js:41146 ReactDOMComponent._reconcilerInstantiateChildren()
 /keystone/js/packages.js:41183 ReactDOMComponent.mountChildren()
 /keystone/js/packages.js:36673 ReactDOMComponent._createInitialChildren()
```

If the behavior has changed is it possible to specify the "map" as the _id ? 
map: "_id" gives me the same error as above. Maybe the react port is missing a default to _id here?

**Comment by mxstbr** [comment]
This definitely sounds like a bug. @keystonejs/core-devs any ideas what could've caused this?

**Comment by steveinatorx** [comment]
another clue: when adding a discrete map parameter to a list - i get the same react errors as above if i dont specifically add said map path to the "defaultColumns" list parameter when trying to view the model list admin UI route.  Perhaps related to this https://github.com/keystonejs/keystone/issues/670 ?

**Comment by Noviny** [comment]
Trying to reproduce this issue failed, so closing. Please comment and reopen with a reproduction case if you are still experiencing it.
