### ISSUE TITLE
Bulk data imports

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#311]
The ability to consume item data in bulk.

Like exports (#310), this functionality changes significantly with scale; it's easy to do a small dinky version of this but throwing significant bulk at it will have the potential to destabilise an app.

Also like exports, imports can be run at the app layer (ie. in node; requiring uploads, background workers, temp files, batching, etc.) or using DB-level tools.

Import functionality may form part of our upgrade strategy for KS4 apps; ie. import from a mongo instance (eg. users could provide connection details in the admin UI).

- Import formats? Excel, JSON, CSV
- Import from existing Keystone instance/MongoDB?
- Specific access control for this or just use create permissions?

**Comment by VinayaSathyanarayana** [comment]
CSV/JSON import will  be a useful feature

**Comment by MadeByMike** [comment]
@molomby did we conclude that stuff in #301 is stuff Keystone should do (or assist with), but bulk imports like this are not a Keystone concern?

**Comment by gautamsi** [comment]
We can use extension or custom action approach to have this. https://github.com/keystonejs/keystone-5/issues/1739

**Comment by MauriceArikoglu** [comment]
did this ever land? its marked completed but I cant find any info in the docs

**Comment by dcousens** [comment]
Hi @MauriceArikoglu, this is not planned
