### ISSUE TITLE
res.apiError is not a function after commit #22076e6c2be4df

### ISSUE THREAD

**Issue by peterpme** [keystonejs/keystone#3111]
### Expected behavior

Log into KeystoneJS
### Actual behavior

Invalid Username / Password
(node error: res.apiError is not a function)

### Steps to reproduce the behavior

Use 0.40 latest commit 
https://github.com/keystonejs/keystone/commit/22076e6c2be4df15c0693deb30244f013a52c8ae#diff-7e3d5f9a07164b4819a17a58ecc48396R7

**Comment by mxstbr** [comment]
@JedWatson pls

**Comment by peterpme** [comment]
Seems to have been fixed here: https://github.com/keystonejs/keystone/commit/22076e6c2be4df15c0693deb30244f013a52c8ae
