### ISSUE TITLE
createReadStream not working in File type

### ISSUE THREAD

**Issue by andyfcx** [keystonejs/keystone#3111]
# Bug report

## Describe the bug
`createReadStream()` in @keystonejs/fields/dist/fields.cjs.js  line 672
Cannot read the file properly, and caused 
`[Error: ENOENT: no such file or directory, stat 'THAT_IMAGE']`
And the `path` on the error shown does not look right (e.g., the absolute path)

Perhaps this is not a real bug, or I just missed up something. 

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:
I am using a customized adapter to Google Cloud Storage
```
const {Storage} = require('@google-cloud/storage');
const Path = require('path')
const gcskeyfile = './configs/gcskeyfile.json';

module.exports.GCSAdapter = class {
    constructor(gcsDir, gcskeyfilePath=gcskeyfile){
        console.log(gcskeyfile)

        process.env.GOOGLE_APPLICATION_CREDENTIALS = gcskeyfilePath
        this.storage = new Storage()
        this.bucket = this.storage.bucket('somebucket')
        this.gcsDir = gcsDir
    }

    getFilename({ id, originalFilename }) {
        return `${id}-${originalFilename}`;
      }
    
    // https://googleapis.dev/nodejs/storage/latest/Bucket.html#upload
    async save({stream, filename, id, mimetype, encoding}) {
        return new Promise((resolve, reject) => {
            console.log("Got :",filename)
            const baseName = Path.basename(filename)

            try {
                const fulfilled = this.bucket.upload(filename, this.getOptions(baseName), (err, file) => {
                    if (err) {console.log(err)};
                console.log(file)})
            }
            catch (err) {console.log(err)}
        })
    }

    getOptions(filename) {
        let destination = `${this.gcsDir}${filename}`;
        // console.log(destination)
        let options = {
            gzip: true,
            destination: destination,
            metadata: {
                cacheControl: 'public, max-age=31536000',
            },
        };

        return options
    }
```

1. Go to the right column and add an image
2. Click on [Create]
3. Scroll down to the console

## Expected behaviour
File should be uploaded successfully

## Screenshots

![image](https://user-images.githubusercontent.com/11717383/83744389-a1e61a00-a68e-11ea-9319-a806f946ee86.png)
![image](https://user-images.githubusercontent.com/11717383/83744425-b0cccc80-a68e-11ea-8ce5-e8d9450c1c43.png)

## System information
- OS: macOS Mojave 10.14.6
- Browser Chrome 80.0.3987.163
- Node.js 10.16.3

**Comment by gautamsi** [comment]
I believe you are working on GCS plugin. have you tried using S3Adapter for this? it seems google cloud storage supports s3 compatible api - https://cloud.google.com/storage/docs/migrating#migration-simple

I was going to write that down for DigitalOcean but found I could use S3Adapter already and added some text here - https://www.keystonejs.com/keystonejs/file-adapters/#s3-compatible-object-storage-providers do you want to try that and let use know if that works for you? some more link at GCS - https://cloud.google.com/storage/docs/interoperability

**Comment by MadeByMike** [comment]
@andfcx, the other file adapters store the src directory in the constructor: https://github.com/keystonejs/keystone/blob/master/packages/file-adapters/lib/local-file.js#L7

And then put the full path together in the save function:

https://github.com/keystonejs/keystone/blob/master/packages/file-adapters/lib/local-file.js#L37

You will need to do something similar.

**Comment by andyfcx** [comment]
Thanks @MadeByMike, currently I changed my `save()` function having `{ stream, filename, mimetype, encoding, id }` as input, and output as `{ id, filename, mimetype }` and successfully uploaded.

However I see `field.cjs.js` `class File` takes mongoDB as default, inserted a json into `file` column in postgres.
Currently I think I will workaround this by using Hooks.

Perhaps `class File` needs an option associated with DB choices?

**Comment by MadeByMike** [comment]
@andyfcx glad you're making progress. I'm thinking an issue might not be the best way to manage this. It's hard for me to imagine the code and offer the best suggestions. I'd be guessing at best :) Could I suggest you make a Pull Request for a Google Cloud Storage adapter?

If you label it as a WIP adapter myself or someone else might be able pull it down and work on it with you. We can answer code specific questions in the PR.
