### ISSUE TITLE
Editor custom admin path is not set

### ISSUE THREAD

**Issue by jankei** [keystonejs/keystone#3112]
### Expected behavior
Editor should open with the correct path

### Actual behavior
Editor admin path is always set to 'keystone'

### Steps to reproduce the behavior
1. use `editable: keystone.content.editable`
2. set `'admin path': 'admin'` in options
3. signin as admin
4. open a post from the client

see editor.js
`3:	var adminPath = (typeof Keystone !== 'undefined' && Keystone.adminPath) ? Keystone.adminPath : '/keystone';
`

**Comment by wmertens** [comment]
Is this still happening? PR would be appreciated :)

**Comment by jankei** [comment]
Yes, still happening. The Keystone instance is undefined because this file is for the client side, not the admin client side. See pull request ;)

**Comment by JedWatson** [comment]
Fixed by #3229
