### ISSUE TITLE
Emptying search box clears UI when empty search

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#3117]
### Steps to reproduce the behavior
1. go to some list
2. put cursor into searchbox
3. type a non-matching string, e.g. "'yualwpioembcaxoynuarft"
4. backspace away the word

### Expected behavior
5. empty search box, the page shows every row again

### Actual behavior
5. empty page, cursor no longer in search box, backspacing will go back in history

**Comment by steveinatorx** [comment]
No longer experiencing this behavior as of recent build https://github.com/keystonejs/keystone/commit/68afd6fcec0dd68481d34c44852de88911bdd87b
Displays search box and list properly. close ?

**Comment by mxstbr** [comment]
Awesome, thanks @steveinatorx!
