### ISSUE TITLE
Last major Admin UI update broke create relationship flow

### ISSUE THREAD

**Issue by zamkevich** [keystonejs/keystone#3118]
## how it works now
![screencast 2020-06-05 17-06-40](https://user-images.githubusercontent.com/13717428/83847635-eeddf500-a74f-11ea-9d70-f823315f1252.gif)

### dependencies
```
"@keystonejs/adapter-mongoose": "^8.1.0",
"@keystonejs/app-admin-ui": "^7.0.1",
"@keystonejs/app-graphql": "^5.1.7",
"@keystonejs/fields": "^12.0.1",
"@keystonejs/keystone": "^10.1.0"
```
### full project 
https://github.com/zamkevich/keystone-tests/tree/relationship-flow-bug

## How did it work
![screencast 2020-06-05 17-15-14](https://user-images.githubusercontent.com/13717428/83847945-762b6880-a750-11ea-854f-934b2eda841d.gif)

### dependencies
```
"@keystonejs/adapter-mongoose": "^8.1.0",
"@keystonejs/app-admin-ui": "^6.0.0",
"@keystonejs/app-graphql": "^5.1.7",
"@keystonejs/fields": "^10.0.0",
"@keystonejs/keystone": "^9.0.0",
```

### full project 
https://github.com/zamkevich/keystone-tests/tree/relationship-flow-work

**Comment by Vultraz** [comment]
Crap. This is probably something I did...

**Comment by Vultraz** [comment]
Tracked down the cause. T'was #2984. Working on a fix.
