### ISSUE TITLE
Keystone Postgres data corruption

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#3119]
# Bug report

I have lists like so:
```
...
keystone.createList('Organization', {
    fields: {
        name: {
            factory: () => faker.company.companyName(),
            type: Text,
        },
        userLinks: {
            type: Relationship, ref: 'OrganizationToUserLink.organization', many: true,
        },
    },
    plugins: [byTracking(), atTracking()],
})

keystone.createList('OrganizationToUserLink', {
    fields: {
        organization: {
            type: Relationship,
            ref: 'Organization.userLinks',
            isRequired: true,
            knexOptions: { isNotNullable: true },
        },
        user: {
            type: Relationship,
            ref: 'User',
            isRequired: true,
            knexOptions: { isNotNullable: true },
        },
    },
    plugins: [byTracking(), atTracking()],
})
```

And CI TEST which does something like:
```
const DELETE_ORGANIZATION_TO_USER_LINK_MUTATION = gql`
    mutation delObj($id: ID!) {
        deleteOrganizationToUserLink(id: $id) { id }
    }
`
...
const link3Id = 54
const client = await makeLoggedInClient(...)
const { data, errors } = await client.mutate(DELETE_ORGANIZATION_TO_USER_LINK_MUTATION, { id: link3Id })
```

When I run this code with a `DEBUG=knex:query,knex:tx` env I can see these queries:
```
...
  knex:query update "public"."OrganizationToUserLink" set "organization" = ? where "organization" = ? undefined +18ms
  knex:query update "public"."OrganizationToUserLink" set "user" = ? where "user" = ? undefined +1ms
  knex:query update "public"."OrganizationToUserLink" set "updatedBy" = ? where "updatedBy" = ? undefined +0ms
  knex:query update "public"."OrganizationToUserLink" set "createdBy" = ? where "createdBy" = ? undefined +0ms
  knex:query delete from "public"."OrganizationToUserLink" where "id" = ? undefined +32ms
...
```

This queries is triggered by the [code](https://github.com/keystonejs/keystone/blob/fd68524135025e4d800b4a98932916736dd50e9d/packages/adapter-knex/lib/adapter-knex.js#L509-L516): 
![image](https://user-images.githubusercontent.com/1394025/83872208-f5b63900-a74a-11ea-8124-012508feadee.png)

It looks strange, why do I need to update something before deleting it.

Then, I raned the code in debug mode. On a screenshot below, I'm trying to delete `OrganizationToUserLink.id == 54` . But, as you can see, it's also trying to set null user column where `OrganizationToUserLink.user.id == 54` :astonished:

![image](https://user-images.githubusercontent.com/1394025/83872392-53e31c00-a74b-11ea-8e6c-40cde64e841c.png)

![image](https://user-images.githubusercontent.com/1394025/83872434-69f0dc80-a74b-11ea-9492-dc3ba316f3b4.png)

The Keystone tries to update the value of neighboring records for all primary keys that refer to other tables. Probably there is missing a test, this code should only update the table references itself.

# additional #

I have a CI test here: https://github.com/8iq/nodejs-hackathon-boilerplate-starter-kit/runs/740039167
There is a reason why my tests fail on Postgres and work well on Mongo. 
Because there is a different way to generate object ID. 
On the Postgres, the mutation also updates other table rows and corrupt the table data.

**Comment by jesstelford** [comment]
This may have been fixed in a very recent version. Can you confirm you're on the latest versions of all the Keystone packages?

**Comment by pahaz** [comment]
Yes. It's looks fixed but there is another problem with the latest version. I need some time to research it.

**Comment by pahaz** [comment]
I've closed this. It solves after an update. But there is another one problem accrued. 

Here is a fix and explanation: 
https://github.com/keystonejs/keystone/pull/3120
https://github.com/keystonejs/keystone/pull/3121

Thanks for all!
