### ISSUE TITLE
Resolve Filter Labels in the Admin UI

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#3122]
Currently filter labels just output the name of the field. The intent is to use common language to represent the filter, e.g. "Date is between Jul 3 2016 and Jul 15 2016".

* * *

- [ ] Boolean
- [ ] Date
- [ ] Datearray
- [ ] Datetime
- [ ] Geopoint
- [ ] Location
- [ ] Number, Money, Number Array
- [ ] Password
- [ ] Relationship
- [ ] Select
- [ ] Code, Color, Email, HTML, Key, Markdown, Name, Textarea, Url

**Comment by mxstbr** [comment]
Done in #3128, amazing!
