### ISSUE TITLE
Initial date/time fields don't have date popup

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#3124]
### Steps to reproduce the behavior
1. make a model with an initial date or datetime type
2. create a new item in the admin UI
3. create popup asks for initial field values
### Expected behavior

4 date field has a date picker
### Actual behavior

4 date field is plain input

**Comment by mxstbr** [comment]
Woah what, how can that happen? (Also, can we finally get rid of that popup? 🙈 )

**Comment by Noviny** [comment]
On 4.0.0beta5, it displays as a plain input, but click on it, and the datepicker appears.

Not sure if this counts as being solved, or if it should be left open and the implementation made clearer.

**Comment by Noviny** [comment]
Closing this as the behaviour is consistent between date pickers.
