### ISSUE TITLE
How set right timezone?

### ISSUE THREAD

**Issue by ivan-vilches** [keystonejs/keystone#3140]
My server is using this timezone:

[keystone]$ date
Sat Jul  9 00:17:44 UTC 2016

I am using a field like this:
createdAt: {
		type:Date, default:Date.now
	}
In the admin it show me a different date time right now:  8:23:07 pm , any way to fix it and set a specific timezone? i.e. America/Santiago

I noticed some weird behaviour when i update each list, my model:
Ticket.js

```javascript
var keystone = require('keystone');
var Types = keystone.Field.Types;

var Ticket = new keystone.List('Ticket',{
	autokey: {from: 'title', path: 'slug', unique:true},
});

Ticket.add({

	title: {
		type: String, initial: true, default:'', required: true
	},
	description: {
		type: Types.Textarea
	},
	priority: {
		type: Types.Select, options: 'Low, Medium, High', default:'Low'
	},
	category: {
		type: Types.Select, options: 'Bug, Feature, Enhancement', default:'Bug'
	},
	status: {
		type: Types.Select, options: 'New, In Progress, Open, On Hold, Declined, Closed', default:'New'
	},
	createdBy:{
		type: Types.Relationship, ref: 'User', index: true, many: false
	},
	assignedTo: {
		type: Types.Relationship, ref: 'User', index: true, many:false
	},
	createdAt: {
		type:Date, default:Date.now
	},
	updatedAt: {
		type: Date, default:Date.now
	}

});
Ticket.defaultColumns = 'title|20%, status|15%, createdBy, assignedTo, createdAt';
Ticket.defaultSort = '-createdAt';
Ticket.register();

```
### Please check the time how it change each time i save:

![keystone](https://cloud.githubusercontent.com/assets/982720/16711470/39f29620-462b-11e6-91f7-01e726aad85a.gif)
 

thanks you.

**Comment by ivan-vilches** [comment]
Fixed setting the timezone on the server.

**Comment by TayyabK** [comment]
How did you set timezone on your local server?

**Comment by mitul69** [comment]
@ivan-vilches  Where is the solution for this ??
