### ISSUE TITLE
Admin interface errors

### ISSUE THREAD

**Issue by samkuhn** [keystonejs/keystone#3143]
I am unable to bring up the admin interface in the latest version on master (23d4cb109e13e8fd7b9e26dffe07fa4dab2017ed):

```
GET /keystone/ 200 685.174 ms
2016-07-09 19:07:80 error building FieldTypes:
Couldn't find preset "stage-2" relative to directory "/root/secondhome/node_modules/keystone" while parsing file: /root/secondhome/node_modules/keystone/admin/client/_stream_0.js
2016-07-09 19:07:04 error building App/index.js:
Couldn't find preset "stage-2" relative to directory "/root/secondhome/node_modules/keystone" while parsing file: /root/secondhome/node_modules/keystone/admin/client/App/index.js
(node:5972) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[19:04:41] ../../14 files was added from pipe
```

node: 6.3.0
npm: 3.10.3

A slightly older version (7b4cdf2c786cdab91b83cb6013a130ea77c150ee) works fine.

**Comment by jstockwin** [comment]
I'm also running into this problem - @keystonejs/core-devs this is pretty crippling...

**Comment by mxstbr** [comment]
@jstockwin yes, I must've forgot to add it to the package.json. Would you mind submitting a PR adding `babel-preset-stage-2` to it? Watching the final at the moment :grin:

**Comment by jstockwin** [comment]
I accidentally pushed to keystonejs/master instead of jstockwin/master for a PR... my bad. 
Probably a good time to make that mistake though. It seems to have fixed this issue.

**Comment by mxstbr** [comment]
Awesome, thanks!
