### ISSUE TITLE
How to add a user role management

### ISSUE THREAD

**Issue by sessionboy** [keystonejs/keystone#3147]
Hello, I need a user role management project system, configure a few administrators, each administrator permissions operation is different, could you tell me how to do this requires. I come from China.

**Comment by mxstbr** [comment]
This is not yet possible, if this is a high priority feature for you please upvote it on ProductPains: https://productpains.com/product/keystonejs

Thanks!

**Comment by wmertens** [comment]
@sessionboy If it's really urgent, you could make several Keystone instances pointing to the same database, each with their own Model configuration and allowed users, so that the users have to log in to their own Keystone, which will allow them to see only what they are allowed to.

**Comment by wmertens** [comment]
In the default Users model you can see the canAccessKeystone virtual, that one needs to be changed so that each instance only allows the users for that instance.

**Comment by Lac** [comment]
@wmertens couldn't you also technically take the express app that keystone exposes, combine it with another, higher-level one and block certain routes (meaning, make them 500) like `/keystone/users`?

**Comment by wmertens** [comment]
@Lac hmmm, to do that you can use keystone hooks to run in express before the keystone routes… Not sure which one though.

**Comment by Lac** [comment]
@wmertens hooks? are those documented? and how would you use them?

**Comment by wmertens** [comment]
@Lac it's one of these hooks https://github.com/keystonejs/keystone/blob/2d79f63d3edf77b294154586b30c9794182ffd7e/server/createApp.js#L85 but I don't know which one, I can't find the call that sets up the /keystone api

**Comment by Lac** [comment]
@wmertens also how would you run those hooks from outside of keystone anyways?

**Comment by wmertens** [comment]
@Lac I don't understand your question? Hooks run in the Keystone server process, which you start with `keystone.start()`.

**Comment by sessionboy** [comment]
Thanks! @wmertens   I'll give it a try
