### ISSUE TITLE
请问keystone有没有自身的角色管理系统，如果没有，需要怎么做

### ISSUE THREAD

**Issue by sessionboy** [keystonejs/keystone#3148]
希望能得到答复

**Comment by mxstbr** [comment]
Sorry, none of us here speak chinese as far as I'm aware!

**Comment by Pylipala** [comment]
@mxstbr, sessionboy asked that if keystone supports authority management. If not, how to do it.

**Comment by mxstbr** [comment]
Ahh, I answered that in his English issue: https://github.com/keystonejs/keystone/issues/3147

Thanks @Pylipala!

**Comment by sessionboy** [comment]
Thanks @mxstbr
