### ISSUE TITLE
JSON/JSONB field type

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#315]
The storage of JSON blobs in the data layer. 

This is often useful when dealing with, for example, external JSON APIs since the raw response can be logged but remain queryable. JSONB values are distinct from Mongo sub documents and subtly different than storing JSON blobs in a text field. The former provides a level of validation (ie. should only accept well-formed values) and it's not expected to be a character-perfect reproduction (eg. key order in objects).

This should present in the interface as a "code" field, that is, preformatted in a fixed-width font.

**Comment by molomby** [comment]
Many field types already persist json values internally, eg. `File` and `Unsplash`.

**Comment by molomby** [comment]
While we're doing this, lets remember that `JSON.parse` and `JSON.stringify`...

* Are synchronous and blocking
* Scale at `O(n)` for the input length

One thing we can do to mitigate this is to make sure that, when being read, **the value is lazily deserialised**.

That is, rather than reading the JSON string from the DB, deserialising it to JS objects and returning that, the field type implementation should create a getter that closures over the string value and deserialises it when accessed (caching the deserialised value internally, for subsequent reads). If done correctly this should be (almost) completely transparent to the consumer.

This is especially important give that we currently (and for the foreseeable future) [load all item fields, regardless of the fields selected by the GraphQL query](https://github.com/keystonejs/keystone/issues/220). Eg. if I have historical info for each of my `Post` items in a 1 MB JSON blob, I don't want the server parsing and creating hundreds of JS objects just so I can read a post's name field (and certainly not when I query the name of 50 post items).

As soon as you have user submittable data that finds its way into a JSON field this becomes a pretty easy way to DOS a site while staying well within any kind of query limit (#1571).

**Comment by molomby** [comment]
More fun here...
[8.14. JSON Types](https://www.postgresql.org/docs/12/datatype-json.html)

> RFC 7159 permits JSON strings to contain Unicode escape sequences denoted by \uXXXX. In the input function for the json type, Unicode escapes are allowed regardless of the database encoding, and are checked only for syntactic correctness (that is, that four hex digits follow \u). However, the input function for jsonb is stricter: it disallows Unicode escapes for non-ASCII characters (those above U+007F) unless the database encoding is UTF8. The jsonb type also rejects \u0000 (because that cannot be represented in PostgreSQL's text type), and it insists that any use of Unicode surrogate pairs to designate characters outside the Unicode Basic Multilingual Plane be correct. Valid Unicode escapes are converted to the equivalent ASCII or UTF8 character for storage; this includes folding surrogate pairs into a single character.

**Comment by molomby** [comment]
More fun... in Postgres, the native `jsonb` type performs stricter validation of strings than either the JavaScript `String` type or the Postgres `text` type:

> However, the input function for jsonb is stricter: it disallows Unicode escapes for non-ASCII characters (those above U+007F) unless the database encoding is UTF8. **The jsonb type also rejects \u0000** (because that cannot be represented in PostgreSQL's text type), and **it insists that any use of Unicode surrogate pairs to designate characters outside the Unicode Basic Multilingual Plane be correct**.

-- [PostgreSQL 12 Docs: 8.14. JSON Types](https://www.postgresql.org/docs/12/datatype-json.html) (emphasis mine)

Ie. right now in Keystone it's possible for a string to be created in JS (as a `String`), added to an object that's later serialised to JSON (still a `String`) and stored in PG as `text` all while being technically invalid in UTF8.

If you were to cast this value to Postgres' native  `jsonb` type (or attempt to store it in a `jsonb` field initially) the stricter validation described above kicks in. When invalid strings are encountered it produces errors like this:

```
ERROR:  invalid input syntax for type json
DETAIL:  Unicode low surrogate must follow a high surrogate.
```
```
ERROR:  unsupported Unicode escape sequence
DETAIL:  \u0000 cannot be converted to text.
```

I think that, for most use cases, the best thing to do with these chars is simply strip them out. This would take effect in the Knex field DB adapter for the JSON type. When using Postgres, we would process the serialised JSON string in Javascript (before passing it to Knex); something like this...

```js
const invalidPatterns = [
   /\\u[Dd][89ABab][0-9A-Fa-f]{2}(?:(?!\\u[Dd][C-Fc-f][0-9A-Fa-f]{2}))/g,
   /\\u0000/g
];
const safeJsonString = invalidPatterns.reduce((s, p) => s.replace(p, ''), JSON.stringify(jsObject));
```

We _are_ silently modifying the persisted value here (which isn't _great_) but doing so to remove invalid sequences and `null` chars seems ok to me...

One last point -- as per the docs extract above, there are more issues if the DB doesn't use UTF8 encoding. Writes will error if the input contains Unicode escapes for non-ASCII characters. Just erring out seems like the right thing to do here -- most systems will/should use UTF8 anyway and, if you're trying to store values in your DB not supported by the encoding it uses, you're always going to have a bad time 🤷🏻‍♂️

**Comment by MurzNN** [comment]
@molomby, thanks for detailed description of problem! I think that the error, if Postgres have non-UTF-8 encoding, is good solution.
About silently modifying the persisted value - maybe implement two storage types on knex backend via some option `useStringStorage`, that will store JSON as `string` without modifying, insead of `jsonb`?

Storage type `jsonb` have great benefit, that we can use in SQL query filtering by exact json keys value, which is not available in `string` storage type.

**Comment by MurzNN** [comment]
Here https://github.com/keystonejs/keystone/pull/5095 is my PR that implements simple JSON field in Keystone-6 (keystone-next).
