### ISSUE TITLE
Question about keystone core

### ISSUE THREAD

**Issue by Anjmao** [keystonejs/keystone#3153]
Hi, I just wanted to fix some bugs, but I stuck at some point and asked question at keystone google group https://groups.google.com/forum/#!topic/keystonejs/UMXg4DAH-FY but seems like this group is not very responsive. Where I can ask such questions to get answer at least after few days ? Thanks :)

**Comment by mxstbr** [comment]
We've been asking people to to move their questions to [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

----

`FieldTypes` is a separate browserify bundle that only bundles the fields. See [`admin/server/app/createStaticRouter.js`](https://github.com/keystonejs/keystone/blob/ccb0eca43324c41ce092eccc97c571488bc4c3c9/admin/server/app/createStaticRouter.js#L34)!
