### ISSUE TITLE
add to Color field property color format (default: 'hex', 'rgb', 'rgba', 'hsl')

### ISSUE THREAD

**Issue by sashamjolnir** [keystonejs/keystone#3166]
`react-color` provides that

**Comment by wmertens** [comment]
We're trying to keep this issue tracker about issues, so unless you feel up to a PR, it would be better to put it at http://productpains.com/product/keystonejs where it can be ranked with other requests.

I'll leave this open for a bit while you decide :)

**Comment by sashamjolnir** [comment]
Ok, I did it.
https://productpains.com/post/keystonejs/add-to-color-field-property-color-format-default-hex-rgb-rgba-hsl

**Comment by wmertens** [comment]
Thanks! Closing this issue.
