### ISSUE TITLE
Path the admin files are hardcoded

### ISSUE THREAD

**Issue by jankei** [keystonejs/keystone#3168]
### Steps to reproduce the behavior
Set `admin path` and try to login
### Expected behavior
Login successfully
### Actual behavior
404 file not found

see admin/server/templates/index.html 3 lines from 32
`
    <script src="/keystone/js/packages.js"></script>
    <script src="/keystone/js/fields.js"></script>
    <script src="/keystone/js/admin.js"></script>
`

**Comment by wmertens** [comment]
closing due to merged :)
