### ISSUE TITLE
Deploy to Heroku button not working

### ISSUE THREAD

**Issue by danurbanowicz** [keystonejs/keystone#3176]
When clicked, the one-click 'Deploy to Heroku' button in the Keystone Readme builds the app without errors but when you try to view the app in a browser, a Heroku error page is generated.

Heroku build log is attached.
[heroku_build_log.txt](https://github.com/keystonejs/keystone/files/371334/heroku_build_log.txt)

App error log:-

`2016-07-19T11:22:45.850364+00:00 app[web.1]:     at NativeConnection.Connection.error (/app/node_modules/mongoose/lib/connection.js:389:8)
2016-07-19T11:22:45.850365+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/connection.js:416:14
2016-07-19T11:22:45.850368+00:00 app[web.1]:     at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:365:7
2016-07-19T11:23:30.902639+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=aqueous-beyond-35114.herokuapp.com request_id=109a9dd9-8c65-477a-81f6-55d00a1829df fwd="213.143.48.102" dyno= connect= service= status=503 bytes=`

**Comment by wmertens** [comment]
looks like it can't access the database?

**Comment by danurbanowicz** [comment]
Yes, looks like that's at least one of the issues.

If anyone wants to test this out, it's pretty easy:-

[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/JedWatson/keystone-starter)

**Comment by danurbanowicz** [comment]
Found the problem, thanks to [Infocinc](http://www.infocinc.com/blog/deploy-keystonejs-to-heroku/)

> The config variable created by the MongoLab Heroku add-on is now called MONGODB_URI. The latest version of KeystoneJS (0.3.19) does not recognize this name. You should rename it to MONGOLAB_URI.

Keystone was failing to connect to the database due to it not recognising Heroku's new config variable key. Fixed this by changing the key in the Heroku dashboard to MONGOLAB_URI

**Comment by wmertens** [comment]
Looks like this is fixed in 0.4: https://github.com/keystonejs/keystone/blob/5dbe7f959c0315afa1105e3bb74c0b454bf01fe7/lib/core/initDatabase.js#L10-L11

Since 0.4 is not that far from release and you have a workaround, I'm going to close this one. Feel free to create a PR to fix 0.3 if it is important to you. (the init is in a different file though)

**Comment by Fitmavincent** [comment]
This problem still exists. No matter which ENV Key I tried. Both MONGOLAB_URI or MONGOLAB_URL fail

**Comment by bassjacob** [comment]
@Fitmavincent Can you share your keystone.js init file?

**Comment by Fitmavincent** [comment]
@bassjacob I was using the Deploy to Heroku button to deploy it.

**Comment by danurbanowicz** [comment]
@Fitmavincent As @bassjacob has said, check that a Heroku mLab addon is provisioned and that the config variable in your Heroku app settings matches what is declared in your keystone.js file in your app's root. It should be MONGOLAB_URI

This is what I use in my keystone.js file:-

`'mongo': process.env.MONGOLAB_URI,`
