### ISSUE TITLE
Navigating to /keystone/signin throws error

### ISSUE THREAD

**Issue by yn5** [keystonejs/keystone#3184]
### Steps to reproduce the behavior
Using a clone of https://github.com/keystonejs/keystone-test-project and its Keystone dependency on the current master branch (https://github.com/keystonejs/keystone/commit/450bf3c75f0748e2f0a9d4c4668654401a0bab08). Navigate to /keystone/signin.

### Expected behavior
Signin form is rendered

### Actual behavior
Keystone throws error:
```
2016-07-20 23:07:15 error building Signin/index.js:
Unknown plugin "add-module-exports" specified in "$PATH_TO_KEYSTONE_PROJECT/node_modules/inline-style-prefixer/package.json" at 0, attempted to resolve relative to "$PATH_TO_KEYSTONE_PROJECT/node_modules/inline-style-prefixer" while parsing file: $PATH_TO_KEYSTONE_PROJECT/node_modules/inline-style-prefixer/static.js
```

**Comment by twig2let** [comment]
@yn5 Not sure what the issue is specifically, seems to be related to babel plugin and presets defined in node_modules/inline-style-prefixer/package.json. Temporary workaround is to comment out lines 42, 51 in inline-style-prefixer/package.json.

**Comment by yn5** [comment]
Thanks for the hint on the temporary workaround @twig2let!

**Comment by JedWatson** [comment]
This is actually the same issue as #3223, there's more detail there and the symptom has been fixes so I think this is good to close.
