### ISSUE TITLE
Using Keystone in tests (without a web server for starters)

### ISSUE THREAD

**Issue by moll** [keystonejs/keystone#319]
Hey,

I'm attempting to write tests for a project that uses Keystone, but the dependency on starting a web server where it's not needed is a little cumbersome. And slow. Is there a way, or could you make one, to let Keystone do its initialization stuff for models without having to start up a web server? Thanks!

Oh right, then again, you'd need a clear cut way to shut and reset _everything_ after each test case. In its current architectural form, a big global state machine, I guess that's not going to be an easy task. :-)

Oh, and I guess if Rob were here, he'd say hi. ;-)

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/using-keystone-in-tests-without-a-web-server-for-starters
