### ISSUE TITLE
Documentation for @keystonejs/fields unclear regarding 'isReadOnly'

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#3191]
In the Changelog for v. 12 (https://github.com/keystonejs/keystone/blob/master/packages/fields/CHANGELOG.md#1200) it says

![image](https://user-images.githubusercontent.com/60699805/85049181-9c132d00-b194-11ea-8577-1d770030f71c.png)

It's unclear whether it should be `isReadOnly` or `isDisabled`

**Comment by gautamsi** [comment]
`isDisabled` is on Field View for a field type - https://github.com/keystonejs/keystone/blob/40151fd0f183291e65976f6de12548bd9ca11469/packages/fields/src/types/Text/views/Field.js#L8

`isDisabled` is internal change. this is aligned with the behavior of fields (enabled or disabled)

`isReadOnly is option for field config when you create a list, this makes the rendering of the field as disbaled/read only.

**Comment by MadeByMike** [comment]
Agree that the changelog was poorly worded regarding an internal prop vs a config option. Will try to remember this next time.
