### ISSUE TITLE
ERROR: node-sass not found.

### ISSUE THREAD

**Issue by dbachko** [keystonejs/keystone#3199]
### Steps to reproduce

Follow the steps from **Linking Keystone for Development and Testing**

And after running **node keystone** I am getting this error:

ERROR: node-sass not found.
Please install the node-sass-middleware from npm to use the `sass` option.
You can do this by running "npm install node-sass-middleware --save".

Node version: v5.12.0

**Comment by wmertens** [comment]
@dbachko at which url did you follow the steps?

Did you get it working with the proposed command? Is this issue about better documentation?

**Comment by radiovisual** [comment]
I have also had this error. I installed keystone via generator-keystone, and selected sass as my preprocessor. Then, after running `node keystone`, I got the same error reported above:

>ERROR: node-sass not found.
 Please install the node-sass-middleware from npm to use the sass option.
You can do this by running "npm install node-sass-middleware --save".

Even after following the instructions and running:

 ```
$ npm install node-sass-middleware --save
```
Then confirming that `node-sass-middleware` and `node-sass` where installed via:

```
$ ls node_modules
```

Running `node keystone` would just report the same error.

Seems [this line](https://github.com/keystonejs/keystone/blob/0e5a4a11d13d4ced058b392b119140f42116dc7e/server/bindSassMiddleware.js#L20) is getting hit even if the module is installed.

I eventually re-installed with the generator and opted not to install a preprocessor to get around the problem for now.

**Comment by terenzeyuen** [comment]
Used to have this, fixed by running npm cache clear, removing node_modules and reinstalling. Seems to be different node version issues.

**Comment by steveinatorx** [comment]
can confirm that this is still happening with https://github.com/keystonejs/keystone/commit/0b05c7f9ff19da9636b8d3a16da50310ae95ff51
resolved for me by running
`npm install node-sass-middleware --save`

**Comment by Noviny** [comment]
This looks like an issue with the generator not coming with all the packages, more than keystone itself.

The generator was recently updated, and this should be solved now, but let me know if you encounter this issue.

**Comment by Mukarrim** [comment]
Surprised to see after years I still am getting these errors with exact same details?
Able to run using (npm install node-sass-middleware --save) but hectic to upload to a remote server (lets say heroku) since it gives error.
