### ISSUE TITLE
View item button in admin UI

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#320]
It'd be nice to be able to view the changes you've just made to an item from the editing interface. I suggest a button right aligned in the toolbar [ View Post ] or whatever your item name.

Perhaps in the model we could store a `previewPath` or something similar that would look like "/blog/post/:key".

**Comment by Yinear** [comment]
Why this is not been merged?

**Comment by morenoh149** [comment]
@Yinear this is not a pull request. If mean #608 then the author said himself that it doesn't solve the most complex usecase. More discussion is needed. @Yinear have your reviewed the pull request? what do you think is missing?

**Comment by Yinear** [comment]
@morenoh149 I need just a simple button like he does.  Or a text label to show the link of the Post.
Maybe I can do it by adding a note to the post title

**Comment by JedWatson** [comment]
Wow, this one is old. Sorry about that. I'll take a look.

**Comment by JedWatson** [comment]
Unfortunately the PR isn't production-ready, this issue among others:

`return this.options.preview.replace(':key', item[this.autokey.path]);`

We need to include proper template parsing so all fields (configurable auto key path, id, etc) are supported.

I'll see if we can get a solution that works in soon based on the work that's been done.

**Comment by albertogasparin** [comment]
I have improved my previews PR with a better, new one. This time the code will handle also more complex scenarios:

```
// simple config and path as a string
var Post = new Keystone.List({
    preview: '/blog/post/:key'
});

// simple config and path as a method
var Post = new Keystone.List({
    preview: function () {
        var date = new Date(this.publishedDate);
	return '/blog/'+ date.getUTCFullYear() +"/"+ this.key
    }
});

// complex config and path as a method
var Post = new Keystone.List({
    preview: {
        label: 'View Post',
        available: function() { return (this.state == 'published'); },
        path: function() { return '/blog/post/' + this.key }
    }
});
```

However, I would rise a question around the naming: `preview` sounds misleading because you are not allowed to view unsaved changes. What about something like `publicPath`?

Moreover, if you want to view items with a "draft" status you have to explicitly add an exception in your front-end views code, otherwise you will get a 404:

```
var q = keystone.list('Post').model.findOne().where('slug', locals.filters.post);

if(!locals.user) { // filter unpublished posts if not logged in
    q.where('state', 'published');
}
...
```

This should be documented somewhere.

**Comment by JedWatson** [comment]
Nice! I agree with you about calling it `preview`, although `publicPath` doesn't seem right either given that you're also defining the button label and availability.

Maybe we should just call it `view`? it's not necessarily "public" (as you note, you could include logic to make draft posts available to authenticated admins)

I don't love "view" but am struggling to come up with something clearer.

**Comment by webteckie** [comment]
viewPath? ☺

**Comment by webteckie** [comment]
Ah, viewPath.path...never mind...

**Comment by albertogasparin** [comment]
Or `link` as suggested in #1059
The functionality provided looks the same

**Comment by ignlg** [comment]
As I'm writing the 0.2.x version of this feature, following what @albertogasparin is doing for 0.3.x, I want to share with you these ideas:

1. `href` instead of `path`. `path` is an important word in the KeystoneJS core so it could lead to confusion whilst `href` has a clear meaning.

2. Every property can be a function, including the label.

	```js
	link: {
		label: function() {
			return "open " + this.title.toLowerCase();
		},
		href: "/article/:key"
	}
	```

3. It accepts an array. We're expanding the toolbar's functionalities so why only one customizable link if we could open it to many?:

	```js
	link: [
		"/article/:key",
		{
			label: function() {
				return "comments of " + this.title.toLowerCase()
			},
			href: "/article/:key/comments"
		}
	]
	```

**Comment by ignlg** [comment]
What about this micro-template? `/post/{slug}/comments`

I've implemented it with:

```js
function(link) {
	var output = link, regex = /\{(.+?)\}/g, match;
	while (match = regex.exec(link)) {
		if (this[match[1]]) {
			output = output.replace(match[0], this[match[1]].toString());
		}
	}
	return output;
}
```

It accepts any of the item properties and, as it has an opening and ending char, is more flexible, ex: `/article/uber{slug}er/`.

**Comment by mdurling** [comment]
What is the status of this feature? It is going to be critical to some work we are doing. Are you expecting it to be available soon?

**Comment by morenoh149** [comment]
@mdurling it's in progress. No eta. Feel free to implement it and share upstream.

**Comment by albertogasparin** [comment]
I've got another idea. What about using a schema virtual field? By using a virtual field it can handle complex logic and the code is shared across both public and admin UI.

``` js
Post.schema.virtual('url').get(function() {
  return '/post/'+this.slug;
});
```

In the admin code we can check if the `url` field is truly and if so the `slug` text will become a link. It is simpler than some of the solutions posted earlier, but it is easier to use.
IMHO, the next step should be a proper "Preview" functionality, which should render the unsaved changes into a public facing template.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/view-item-button-in-admin-ui
