### ISSUE TITLE
how to setting ratelimit to some mutation？

### ISSUE THREAD

**Issue by bookyo** [keystonejs/keystone#3200]
how to setting ratelimit to some mutation？
like limit 60 requests for 60 seconds？

**Comment by MadeByMike** [comment]
Hi @bookyo, Keystone doesn't do rate limiting. There are a lot of different ways you might want to implement it. You might have different rate limits depending on user authentication or IP addresses. The graphQL API is an express app so you can add any third-party middleware to this to implement rate-limiting.

**Comment by bookyo** [comment]
https://github.com/microlinkhq/async-ratelimiter
or
https://github.com/nfriedly/express-rate-limit 
use async-ratelimiter in resolvedata hook work?
I don't know how to use express-rate-limit in mutation？

**Comment by bookyo** [comment]
thank you ver much, i use rate-limiter-flexible resolve it.
