### ISSUE TITLE
KeystoneJS Roadmap

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#322]
**This issue will be updated with more details in the coming weeks to organise the roadmap into a clearer set of tasks and goals against specific releases.**

About six months from our initial launch, KeystoneJS is currently mature enough for production use in websites and projects, and is flexible enough to support a range of use-cases. This is just the start though, and it's about time we started talking about what's next.

From here, our main goals for the project are to:

*	Open the platform up for new field types and functionality through a plugin architecture
*	Improve the appearance and usability of the Admin UI through generic improvements **and** a plugin architecture to support custom UIs and workflows
*	Provide a set of nicer UI options and workflows around relationship fields
*	Support more sophisticated permissions in the Admin UI through some combination of a built-in roles / permissions architecture, and a plugin architecture for custom permissions systems
*	Clean up support for various file-system backends for file and image handling, including local, S3, Azure, etc.
*	Build robust support for nested schemas (or repeating field sets) in Lists
*	Make it easier to develop client-side forms and management functionality
*	Add content management functionality to support more standard CMS requirements alongside the database functionality already present (currently Keystone is more of a content management framework than a content management system; with the right features we believe it can successfully be both)

We will also continue to make ongoing improvements to address common requests, and migrate to Express 4.0 at the right time.

In support of the growing community around KeystoneJS we are also planning:

*	A new guides section to the website, addressing common questions about how to solve certain problems easily with Keystone
*	To generally improve the documentation, including full coverage of currently undocumented features
*	The launch of a KeystoneJS powered discussion website to replace our current Google Group and provide another sophistcated open source reference project

Longer term, we are currently considering options on how to best support KeystoneJS development into the future. In addition to contributions from the community, its development has largely been funded by commercial projects at [thinkmill](http://www.thinkmill.com.au) and [prismatik](http://www.prismatik.com.au) which seems (six months in) to be both sustainable and in the best interests of the project. If anyone has a commercial project they would like the core team to contribute to, which could also help fund the development of KeystoneJS, please get in touch.

We are also considering whether to (a) take on commercial sponsorship, (b) run a kickstarter, and (c) launch a theme marketplace. It is very important to us that KeystoneJS has long-term sustainability as a project, remains independent and provides a valuable tool for the community, so feedback is very welcome and any decisions we make will be with these interests in mind.

**Comment by morenoh149** [comment]
should this issue be closed in favor of a `ROADMAP.md` file at the root of the project?

**Comment by dcousens** [comment]
Closing in favour of https://github.com/keystonejs/keystone/wiki/Roadmap
