### ISSUE TITLE
Boolean field lost field-type and for attributes

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#3227]
The Boolean field seems to have lost its `field-type-boolean` and `for` attributes, which are critical to e2e's operation.

### Steps to reproduce the behavior
Run the e2e app, create a new boolean, and under inspector observe the missing attributes as in the following image (notice how a name field properly shows the same attributes).

![image](https://cloud.githubusercontent.com/assets/5872515/17210626/fe6fa3d4-5491-11e6-8434-5e799db18ed9.png)

### Expected behavior
Should show the aforementioned attributes.

### Actual behavior
Does not show the aforementioned attributes.

**Comment by JedWatson** [comment]
Is there any way we can work around this? I think relying on classes is going to put our component dev efforts and e2e in conflict. We're (prototyping) moving to Aphrodite, which generates class names, in an effort to colocate our styles with the components that use them because right now the whole front-end DOM / CSS structure is a mess and really hard to work with.

I'm fine adding `data-x` attributes if that's required for e2e, but would prefer to avoid using classNames for anything other than styling information, as those concerns should be separate. We're not in jQuery anymore Toto 😉

**Comment by webteckie** [comment]
@JedWatson are you saying that classes like `FormField` are going to disappear?  Also, currently the entire e2e framework for testing fields relies heavily on the pattern that a field have attributes `field-type-xxx=` and  `for=` (what this issue concerns).   If fields going forward will not be consistent with their classes and attributes then this is going to make e2e testing a mess :-)

**Comment by mxstbr** [comment]
> If fields going forward will not be consistent with their classes and attributes then this is going to make e2e testing a mess :-)

They won't just be inconsistent, they'll be randomly generated. This is actually a good point, we should move towards `data-x` attributes instead!

**Comment by jstockwin** [comment]
As long as there is some way to uniquely identify the field elements from each other we should be fine.

**Comment by jstockwin** [comment]
However, has this change been intentionally made here? @jed is talking about why we should move away from the current structure, but is this issue a result of us starting to do that, or was it by accident? If it's going to be a while until we change things, is it worth adding the Boolean class names back so we can make e2e pass?

**Comment by mxstbr** [comment]
> However, has this change been intentionally made here?

The effect wasn't intentional, however the class removal was intentional. /cc @jossmac 

> If it's going to be a while until we change things, is it worth adding the Boolean class names back so we can make e2e pass?

I don't think so to be honest

**Comment by webteckie** [comment]
I'm addressing this (did last night) per the discussion with jed in slack.  Will push soon.

**Comment by mxstbr** [comment]
This is fixed on `master` as far as I can see! Closing!
