### ISSUE TITLE
Provide a way to protect users revoking their own admin permissions

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#323]
As discovered by this google group user: 

https://groups.google.com/forum/#!topic/keystonejs/wsY4ge0yypk

... it is possible to accidentally remove your own admin access.

Because we're *very* flexible with our permissions and user models, this isn't currently something we're able to easily prevent in Keystone's Admin UI, but it's a pretty bad thing to be able to do.

So there should be something we can set on a Model that enforces some kind of validation or state on an Item based on the current user, that lets us prevent this from happening.

Not sure exactly how it would work yet, but this would be really worth fixing.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/provide-a-way-to-protect-users-revoking-their-own-admin-permissions

**Comment by amjad-eremnews** [comment]
Is there a way to allow access to keystone admin, if the user has assigned a role i.e. editor, sub-editor etc. instead of isAdmin? and these role ref to the role model in user model as `role: { type: Types.Relationship, ref: 'Role'}`
