### ISSUE TITLE
Data storage adapter ideas

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#324]
In addition to the initial planned adapter (Mongoose and Knex #297), a number of other ideas have been tabled:

* SQLite -- Actually pretty powerful. Good for small apps and demo.
* In-memory DB -- An adapter without any external dependancies/processes that we can load with data out of a JSON file. This would be _super_ useful for testing. Possibly NeDB? Claims to implement [the important parts of the Mongo API](https://github.com/louischatriot/nedb).
* OpenCRUD -- As in another, external GraphQL endpoint. This could be another KS 5 instance or any other system that conformed with OpenCRUD.
* Prisma -- Specifically the new [Prisma Client](https://www.prisma.io/blog/prisma-client-beta-ahph4o1umail). This would let devs wrap "any database" in a GraphQL layer then interface with it through a consistent data adapter.
* [PostGraphile](https://www.graphile.org) -- "Instant, secure and fast GraphQL API for Postgres"
* ORM adapters (eg. Objection or Bookshelf) -- Like the Knex adapter but also creates model classes and, internally, uses them instead of plain Knex "records". Good for larger systems?
* Write-only flat-file (JSON, CSV, text, etc.) -- A write only adapter that adds (structured?) lines to a file on disk. Could be a nice interface for logging data for later analysis? Either remotely or in-app
* Remote structured data services (Airtable, Google Sheets, etc.) -- Would be pretty cool... 
* Other persistence engines -- Redis, Elasticsearch, ..?
* Data integrations -- Stripe, Algolia, Harvest? (Read-only?)
* System data sources -- File system, system metrics/resources, ..? Actually, probably just lists defs for [osquery](https://github.com/facebook/osquery)

Speaking of all this, our adapter framework might need to support something akin to "feature flags". That is, a way for a (Keystone or List?) adapter to communicate to Keystone which features it supports, eg. readable, writable, updatable, maybe "findable"? As in, can values be searched for or only referenced by ID?.

**Comment by Neo-Zhixing** [comment]
Would it be possible to add support for Google Firestore as well?

**Comment by ahmadawais** [comment]
I'd like to suggest adding the following:

- [Google Cloud Firestore](https://firebase.google.com/docs/firestore) (Firestore pay as you go plan is excellent)
- [Fauna](https://fauna.com) Serverless Database with first-class GraphQL Support

**Comment by yangkghjh** [comment]
Flat-file support will be helpful to use keystone with other static website generators.

**Comment by molomby** [comment]
+ Some kind of configurable REST adapter, as per #1573

**Comment by VinayaSathyanarayana** [comment]
Consider https://hasura.io

**Comment by JumpLink** [comment]
Instead of NeDB Keystone could add support for [LinvoDB](https://github.com/aerys/linvodb3) wich is based on NeDB but has a Mongoose-like features and interfaces which could make it easier to add support for because the mongodb adapter is also using Mongoose. On the other hand, I would also be happy with SQLite over Prisma.
