### ISSUE TITLE
fields.js:7784 Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by jankei** [keystonejs/keystone#3241]
### Steps to reproduce the behavior
 Getting the above error for a relationship input field in the Admin UI

This happens after commit  [Updating common packages bundle with aphrodite/no-important](https://github.com/keystonejs/keystone/commit/c3c5132b7c706bfbb2797a7d770d7a0529756c54)

**Comment by chrisslater** [comment]
I have taken a look and it looks like lodash is not being imported at the top of https://github.com/keystonejs/keystone/blob/master/fields/types/relationship/RelationshipField.js

I have added it locally at it has resolved the issue for me.
