### ISSUE TITLE
Blocks don't works as expected within mixins

### ISSUE THREAD

**Issue by Ventis** [keystonejs/keystone#325]
If you create a mixin with a block x tag, it doesn't insert this within the x tag. This should be fixed in Jade 1.3.1.
https://github.com/visionmedia/jade/commit/ae8e8b7d3a8f06ddf7988154b231a8702d8067a9

This would be helpful for example if you create a new field template for Location that has a dependency on jQuery 2.1.0 (The AdminUI uses jQuery 1.11 I think) and want to replace the included scripts within the block js tag.

**Comment by creynders** [comment]
Solved/stale
