### ISSUE TITLE
TypeError: Cannot read property 'assert' of undefined

### ISSUE THREAD

**Issue by dbachko** [keystonejs/keystone#3250]
### Steps to reproduce the behavior
Run `npm run test-all`

### Expected behavior
Should not throw an error

### Actual behavior
TypeError: Cannot read property 'assert' of undefined

**Comment by jstockwin** [comment]
I think @webteckie is aware of this, and intending to fix it tonight. There's a branch (make-sure-e2e-runs-green) dedicated to getting e2e to pass.

**Comment by jstockwin** [comment]
Ah, I see you've fixed it in your fork. Maybe point a PR at the e2e branch for now, as there's also some refactoring to do.

**Comment by dbachko** [comment]
@jstockwin I created a new pull request into this branch
