### ISSUE TITLE
Search box disappears after not founding something

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#3260]
When I'm on the admin and I search something and it's not found if I delete my search query the search box disappears.

**Comment by mxstbr** [comment]
Are you on the latest `npm` version or `master`?

**Comment by ellipticaldoor** [comment]
I did this for installing keystone:

```
git clone https://github.com/keystonejs/keystone
cd keystone
yo keystone
npm i keystonejs/keystone
```

right now I'm on the master branch

**Comment by wmertens** [comment]
This is a duplicate of #3117
