### ISSUE TITLE
AdminUI users sessions keep resetting on each restart

### ISSUE THREAD

**Issue by mhakmi** [keystonejs/keystone#3260]
I followed the [documentation](https://www.keystonejs.com/keystonejs/keystone/#cookiesecret) and provided value for `cookieSecret`, but nevertheless the user session keep resetting after each restart.

Am I missing something else need to be configured to fix this?

Thanks

**Comment by gautamsi** [comment]
you need some [session store](https://www.keystonejs.com/guides/production/#session-store).

**Comment by mhakmi** [comment]
Thank @gautamsi! That's right, I already have [memorystore](https://www.npmjs.com/package/memorystore), but seems was not working as expected, so once I changed it to another one the issue resolved.
