### ISSUE TITLE
Broken version on npm (0.3.22?)

### ISSUE THREAD

**Issue by sebastiancarlsson** [keystonejs/keystone#3263]
I installed keystone through NPM and got this problem:

https://stackoverflow.com/questions/38740068/adminui-relationship-field-doesnt-load-full-list-of-items/

I investigated this and saw that the release notes for 0.3.22 mentioned changes to relationship fields so I tried to downgrade to 0.3.19 and this fixed the problem. However, the latest release on npm is 0.3.22 but on GitHub it's 0.3.19, the tag 0.3.22 doesn't even exist on GitHub? Was this deleted?

Needless to say, the version on npm should reflect the tag with the "latest release" label on GitHub.

**Comment by JedWatson** [comment]
@mxstbr ping?

**Comment by mxstbr** [comment]
Ah yeah, I possibly forgot to tag those. 🙊 my bad, sorry!

**Comment by mxstbr** [comment]
I'll close this for now since afaik you can't retrospectively tag commits, though I'll gladly be proven wrong if somebody knows how to do that!

**Comment by mxstbr** [comment]
You can find the specific releases by looking at the commits on the v0.3.x branch, there's a commit called "v0.3.22" in there!

**Comment by sebastiancarlsson** [comment]
Ok, thank you for the clarification! Should I post a separate issue regarding the problem I linked to? (0.3.22 seems to break the relationship field inputs in the AdminUI)

**Comment by mxstbr** [comment]
Yes please!

**Comment by sebastiancarlsson** [comment]
#3264
