### ISSUE TITLE
[0.4] It is possible to create an item in nocreate list

### ISSUE THREAD

**Issue by Murmand** [keystonejs/keystone#3284]
I tried to create an "Item" field instead of classic List according to https://github.com/keystonejs/keystone/issues/1522 (the route trick mentioned [here](https://gist.github.com/jeffreypriebe/f093c81c83d7ac5166b3) is quite outdated).

Anyway I keep my List nocreate and nodelete:
```javascript
var homepage = new keystone.List('Homepage', {
    nocreate: true,
    nodelete: true,
    ...
})
```

but it is possible to create a new item in this list through admin homepage.

![Keystone - nocreate](http://www.zbernardova.cz/assets/img/keystone-nocreate.jpg)

**Comment by mxstbr** [comment]
Confirmed, looking into it!
