### ISSUE TITLE
Possible bug regarding the "nav" config object

### ISSUE THREAD

**Issue by ivarni** [keystonejs/keystone#3287]
Hi,

This is using the version of keystone installed by the yeoman generator from [Getting Started](http://keystonejs.com/getting-started/), meaning version `^0.3.19`.

I'm trying to configure the Admin UI by grouping models together in categories while giving each menu item a custom label.

I found that
```
keystone.set('nav', {
	models: [
		{
			label: 'Brukere',
			key: 'users'
		},
	],
});
```
will generate a "models" category with Users (labelled as 'Brukere') as a single item and that
```
keystone.set('nav', {
	models: [
		{
			label: 'Brukere',
			key: 'users'
		},
		'pages',
	],
});
```
will generate a "models" category with Users (labelled as 'Brukere') and Pages labelled as 'Pages'.

### Steps to reproduce the behavior

Given that I have models for `Users` and `Pages`:

If I write 
```
keystone.set('nav', {
	models: [
		{
			label: 'Brukere',
			key: 'users'
		},
		{
			label: 'Sider',
			key: 'pages'
		}
	],
});
```
That is, try to create *two* subitems with custom labels I'm left with only the first one showing up.

### Expected behavior

I expected to be able to label both menu points and get

![image](https://cloud.githubusercontent.com/assets/379849/17461958/bad82ec6-5c9c-11e6-9cc0-0a806fae2e51.png)

### Actual behavior

Instead I get

![image](https://cloud.githubusercontent.com/assets/379849/17461954/89ce3d7a-5c9c-11e6-88c7-42f65f4015af.png)

Is this intended behaviour or is this a bug? 
If it's a bug (and if I manage to fix it) would you welcome a PR?

**Comment by JedWatson** [comment]
It does look like there's a bug here, but try this:

```
keystone.set('nav', {
    models: [
        {
            label: 'Brukere',
            key: 'User'
        },
        {
            label: 'Sider',
            key: 'Page'
        }
    ],
});
```

... that is, use the list `Key` instead of `path` (where path is the lowercase, plural url-friendly version of the list name, and Key is what you specify when creating the `new keystone.List(Key, options)`)

That might work around it for you.

**Comment by ivarni** [comment]
@JedWatson  AFAICT I get the same behaviour, only the first item in the array shows up.

I had a look at the code in the 0.3 branch, [admin/src/views.home.js](https://github.com/keystonejs/keystone/blob/v0.3.x/admin/src/views/home.js#L27) line 27.

```
{navSection.lists.map((list) => {
	var href = list.external ? list.path : '/keystone/' + list.path;
	return (
		<li key={list.path}><a href={href}>{list.label}</a></li>
	);
})}
```
In this case, `path` is `models` for all the elements, meaning React gets the same value in `key={list.path}` which again leads to React thinking every `li` is the same object.

If I swap that for `key={list.key}` (ie, the Key of the List) I get the desired result. Could that be a solution here?

**Comment by ivarni** [comment]
Give me some time to look more at this and I can generate a proper diff, I'm not sure I'm being clear at the moment :)

**Comment by ivarni** [comment]
OK, sorry for this. I missed [this bit](https://github.com/keystonejs/keystone/blob/v0.3.x/lib/core/initNav.js#L62) where it does
```
i.path = i.path || utils.keyToPath(key);
```

Meaning that my config object should have been
```
models: [
    {
        label: 'Brukere',
        key: 'User',
        path: 'users'
    },
    {
        label: 'Sider',
        key: 'Page',
        path: 'pages'
    }
],
```

Then the path gets set correctly for each sub-item in the menu rather than the key for the section be sent to `utils.keyToPath` which converts it to a lowercased representation meaning each sub-item get the path `models` since that was the name of the section.

This can be closed I guess. There's no issue as long as the configuration is correct. Sorry for the noise :)
