### ISSUE TITLE
[Docs] Muliple mistakes

### ISSUE THREAD

**Issue by one-thunder** [keystonejs/keystone#3291]
# Bug report

## Describe the bug

Examples in the following page contains multiple mistakes.
https://www.keystonejs.com/keystonejs/app-admin-ui/ 

## To Reproduce

---

## Expected behaviour

Welp, when someone copy paste it in their code it should be working "out of the clipboard"

## Screenshots

![image](https://user-images.githubusercontent.com/32410574/88431216-8c75ac80-ce02-11ea-8eb6-eb5d7ae1d82d.png)

**Comment by gautamsi** [comment]
fix is in #3292

**Comment by MadeByMike** [comment]
Looks like someone (maybe me) copied and pasted the same mistake :) Thanks @gautamsi for the PR.
