### ISSUE TITLE
Why Admin UI loading slowly, how to solve?

### ISSUE THREAD

**Issue by sessionboy** [keystonejs/keystone#3297]
hi, I want to know Why Admin UI loading slowly, how to solve?

**Comment by wmertens** [comment]
This is a known issue, the first time you load the UI after the server is started it will compile the code for the browser. We are looking at ways to precompile everything, and then it should be fast.

There's a setting that compiles at boot time, so then the server takes longer to start but the load is fast  when you visit the UI. You need to set `KEYSTONE_PREBUILD_ADMIN=true` in your environment..
I'll close this for now, just ask away if you have further questions.

**Comment by sessionboy** [comment]
Thank you! @wmertens

**Comment by wmertens** [comment]
Hi @sessionboy, I need some testers for the webpack branch. If you want to help, install it in your project with `npm i keystonejs/keystone#webpackify`, and then it will build the admin UI at install time.

From then on, loading the admin UI should be pretty instant.
