### ISSUE TITLE
Replace keystone.Email with keystone-email package

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#3303]
I've rewritten `keystone.Email` into its own package: https://www.npmjs.com/package/keystone-email. It's much better, with proper documentation and tests, as well as modular support for different transports 😀 

Next up, I want to replace the internal `keystone.Email` with it and remove that bulk of code + dependencies from core. I think it would be possible to create a backwards-compatible interface to use the new package for the 0.4 release, or at least something that wouldn't be a burden to migrate to when we publish the next version.

(i.e. the `keystone.Email` function would still exist, it would just call out to `keystone-email`)

I think it's reasonable to leave the `keystone-email` dependency out of core, anybody who wants to use `keystone.Email` can install it, and projects that don't need it have less unnecessary packages. We should add a warning if the dependency hasn't been installed, to keep things as seamless as possible.

If anybody wants to pick this up or come back with some ideas on how best to approach it, now is your chance!

**Comment by mxstbr** [comment]
Done
