### ISSUE TITLE
[0.4] admin double tapping loadItem calls, triple tapping on a direct load to  keystone/list?search=xyz URI

### ISSUE THREAD

**Issue by steveinatorx** [keystonejs/keystone#3310]
Looks like the state machine is borked up in the latest builds in master.  After trying to trace this down i also noticed that a direct load to /keystone/list/search?xyz also does a naked loadItem call twice as well as a search call to the API so you often get incorrect results back in the List view. 

My noobie guess as to whats wrong is that it looks like there is something with the cache invalidator in the store.js file and its relationship to updateQueryParams. Im also a bit suspicious of the loadItem call in Admin/client/App/screens/List/index.js function as it seems extraneous on a lot of the UX.

**Comment by JedWatson** [comment]
Thanks @steveinatorx!

@mxstbr @gwyneplaine would you mind taking a look at this?

**Comment by mxstbr** [comment]
> its relationship to updateQueryParams

I'm 99% sure that function doesn't even do anything, it's a relic from the previous non-redux version.

I will take a look at the whole loading logic, possibly pairing with @gwyneplaine. Maybe you want to dig in too @steveinatorx?

**Comment by steveinatorx** [comment]
ive been combing through it for quite a while today and im pretty confused frankly.

I think there is actually two issues here:
1) the basic List URI will call loadItems from both store.js and via componentDidMount() in App/screens/List/index.js. Im not sure which one would be the correct place to call loadItems from.
2) loading a List search URI such as "keystone/posts?search=XYZ" directly from the browser also generates a double tap basic loadItems API call AND a search API call. I wouldn't think that action would need to generate any basic loadItems calls and they will overwrite the search call in the view.

Maybe remove the componentDidMount() call and have @gwyneplaine <https://github.com/gwyneplaine> take a look at the store.js cache ?

**Comment by steveinatorx** [comment]
working on a PR for this...

**Comment by steveinatorx** [comment]
working through regression on a PR for this...

**Comment by mxstbr** [comment]
We need to be calling `loadItems` no matter if we have query strings (e.g. `?search=XZY`) or not. (e.g. if going to list directly `keystone/posts/`) If we just do it from `store.js` won't this break the second case?

What about blocking the `loadItems` call from `componentDidMount` if we have query strings? That way if we have query strings there'll only be a call for the properly filtered items and if there aren't only the call for all the items goes through?

> working through regression on a PR for this...

Definitely submit the PR in progress and we'll take a look! Closesly collaborating with @gwyneplaine this and next week on reworking that whole redux implementation, so keep to get this fixed.

**Comment by steveinatorx** [comment]
I tried blocking loaditems from componentDidMount but the store loadItems kept blowing away the search query values so i tried to override that in active.js. Ill submit a PR shortly just finishing up some dinner ..

**Comment by mxstbr** [comment]
Awesome, thanks!

**Comment by steveinatorx** [comment]
running through tests - almost ready

**Comment by steveinatorx** [comment]
ok @mxstbr hopefully that can get you started at least. So i tried suppressing the set active list in didMount as well - that resolves the double tap call but it then regresses to blow up some of the navigation so i left it in. The listManagement return "null" fixed the render blow up when you get zero results back on a direct load to a  "search query URI" and you can see what i did in active.js to try to override store.js from nuking the search state value when it calls loadItem. And yes - the redux piece definitely needs some TLC ;-)  I'll be happy to help some more tomorrow but im hoping core devs can take over this - the state manager is a pretty fundamental piece of the pie and needs to be refactored properly.

**Comment by steveinatorx** [comment]
couple of warnings in there too:
`VM29797:27 Warning: Failed prop type: transitionEnterTimeout wasn't supplied to ReactCSSTransitionGroup: this can cause unreliable animations and won't be supported in a future version of React. See https://fb.me/react-animation-transition-group-timeout for more information.`

**Comment by steveinatorx** [comment]
not sure what that other diff cruft is i just did a fresh fork but i marked the important lines in the PR with comments...

**Comment by steveinatorx** [comment]
pretty slick guys  @gwyneplaine @mxstbr  . thanks for addressing this. saga looks like a cleaner way to handle all the subsidiary state change jobs then trying to shoehorn into redux overrides

**Comment by mxstbr** [comment]
@steveinatorx thanks, totally agree, good call by @gwyneplaine!
