### ISSUE TITLE
keystone.uid cookie does nothing

### ISSUE THREAD

**Issue by josephg** [keystonejs/keystone#3317]
When I sign in to the keystone admin console I get a `keystone.uid` cookie, which seems to do nothing. If I remove it I still have access to keystone.

Can this cookie be removed?

**Comment by mxstbr** [comment]
cc @JedWatson

**Comment by JohnBain** [comment]
It appears to me to that it's a fake intentionally put there to ward off (the laziest) malicious users. I used the JWT decoder and the secret in the app and it was a valid JWT. 

I got an object literal containing the name "John Doe", which isn't a name in my database. Sorry if I blew your cover, Keystone :)
