### ISSUE TITLE
Updating documents in AdminUI messes up defaultSort order in a List

### ISSUE THREAD

**Issue by rthkr17** [keystonejs/keystone#3320]
A Posts list is set to be sorted by its created_at data, which is fetched from a MongoDB database.
When opening a document from the list to change a data value, and saving it,
that document comes all the way up in the list and stays there no matter what.

In a gist, the documents updated in the AdminUI come to the top of the list, no matter what the sorting options are set to.

A clear and concise description of the bug.

My code for Post Model - 

`const keystone = require('keystone');
const { Select } = require('keystone/lib/fieldTypes');
const Types = keystone.Field.Types;

const Post = new keystone.List('Post', {
	map: { name: 'heading' },
	noedit: false,
	nodelete: true,
	nocreate: true,
	drilldown: 'createdBy',
});

const options = [
  { value: '0', label: "M" },
  { value: '1', label: "F" },
  { value: '2', label: "Both" },
];

Post.add({
	heading: { type: String, required: true },
	activity: { type: String },
	description: { type: String, label: 'Location' },
	createdAt: { type: Date, noedit: true },
	startDate: { type: Date },
	endDate: { type: Date },
	isDeleted: { type: Boolean },
	isBarter: { type: Boolean },
	age: {
		min: { type: Number },
		max: { type: Number },
	},
	followers: {
		min: { type: Number },
		max: { type: Number },
	},
	budget: {
		min: { type: Number },
		max: { type: Number },
	},
	gender: { type: Select, options },
	createdBy: { type: Types.Relationship, ref: 'Brand' },
});
Post.defaultSort = '-createdAt';
Post.defaultColumns = 'heading activity description createdBy';
Post.register();`

## Expected behaviour
Posts should be sorted by createdAt date, even after they have been updated using AdminUI, as the createdAt does not change after document creation.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
