### ISSUE TITLE
missing graphql liberary

### ISSUE THREAD

**Issue by crabby786** [keystonejs/keystone#3321]
# Bug report

## Failed to install @keystonejs/server-side-graphql-client.

npm ERR! 404  '@keystonejs/server-side-graphql-client@latest' is not in the npm registry.

**Comment by Mangrayd** [comment]
the same error, is this package still required?

**Comment by crabby786** [comment]
> the same error, is this package still required?

in the official tutorial: "Server-side graphQL client
This library provides wrapper functions around keystone.executeGraphQL to make it easier to run server-side queries and mutations without needing to write boilerplate GraphQL."

**Comment by timleslie** [comment]
Hi @crabby786 and @Mangrayd, sorry about this, our docs were briefly ahead of our actual published package. The `server-side-graphql-client` package has now been published on `npm` and you should be able to continue following the tutorials.
