### ISSUE TITLE
Wrong format in documentation of DateTime field

### ISSUE THREAD

**Issue by Bravo555** [keystonejs/keystone#3324]
# Bug report

Using a format for the `DateTime` field as described in [documentation](https://www.keystonejs.com/keystonejs/fields/src/types/date-time/#usage) results in the following:
![image](https://user-images.githubusercontent.com/10912424/89107654-d548e900-d432-11ea-99a8-3de9d8cf3b23.png)

The browser console reveals the following information:
![image](https://user-images.githubusercontent.com/10912424/89107672-f8739880-d432-11ea-8022-3bff3a9b4984.png)

Looks like version bump of `date-fns` dependency changed changed format tokens to unicode ones, but this wasn't reflected in the documentation.

A valid example format in the "usage" section would be: `dd/MM/yyyy HH:mm O`. The current format should be replaced with this.

Also it would be nice to point to [format tokens in `date-fns` documentation](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) in the relevant section.

Its a straightforward fix, a PR will shortly follow.

**Comment by timleslie** [comment]
Fixed in #3325
