### ISSUE TITLE
0.3.17 Select for relationship only shows first 100 documents and autocomplete not working

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#3324]
### Steps to reproduce the behavior

Configure a one-to-many relationship between two models. ParentModel and ChildModel.  Create 101 ParentModels.  Create a ChildModel and look for the 101st ParentModel record in the select.  Type the name of the ParentModel, inspect the http activity.  The query param "q" is empty, every record from your ParentModel in the autocomplete request is returned, but only first 100 are rendered.
### Expected behavior

Select should either show everything or implement some sort of infinite scroll to paginate.  

Typing a search term in the keyword search should pass that value to the autocomplete query to filter the model.
### Actual behavior

Fetches all records async, but only shows first 100.  Typing a search term only appears to work within displayed results.

**Comment by mxstbr** [comment]
Is this on `master` or on `0.3.x`?

**Comment by emaddoma** [comment]
I assume master. Installed via npm.  
 
 
   
  
 OMA  
Erik Madsen | Development Manager
Erik.Madsen@offmadisonave.com

MAIN LINE:      480.505.4500
DIRECT LINE:   303-506-0795




offmadisonave.com
Send large files using  my secure ShareFile account. 
  
   
  
  
    
   
  
  
   
  
   
  
  
 
On Aug 15, 2016, at 10:56 PM, Max Stoiber <notifications@github.com> wrote:

 
 Is this on master or on 0.3.x?

**Comment by mxstbr** [comment]
Ahh sorry, didn't see the title! It's `0.3.17`.

**Comment by emaddoma** [comment]
This is what I would categorize as a "show-stopper" for any Keystone app with more than 100 records in a similar setup and we have more than a few that will run afoul of this bug.  We would love to contribute to the project with a fix, but we're buried building applications/sites with Keystone! 😄

**Comment by bradwbradw** [comment]
in my project, I'm seeing the autocomplete JSON indicate `"total":108`, but in the `items` array there are actually only 50 results

`GET: http://app.domain/keystone/api/wineries/autocomplete?context=relationship&q=&list=wines&field=winery`

I'm running version `0.3.22`

**Comment by guillaumew** [comment]
I have the same problem. I hope it will be fixed :)

**Comment by Noviny** [comment]
This is fixed in keystone 4. Closing this as an issue as we are not going to be back-porting it to keystone 3.
