### ISSUE TITLE
Search fires request with every keypress

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#3338]
We really need to debounce the search field, waiting say 250ms after the last keypress before actually requesting results. Otherwise, a request is fired for every single keypress and it causes unnecessary load on the database.

### Steps to reproduce the behavior

Open the Keystone Admin UI and navigate to a List. Type `abc` in the search field, quickly.

### Expected behaviour

The action should set a timeout (which is reset with each keypress) and wait for you to finish typing (or at least pause). A single request for the results `?q=abc` should be made.

### Actual behavior

Three requests are made immediately, one each for `?q=a`, `?q=ab` and `?q=abc`

cc @mxstbr @gwyneplaine

**Comment by mxstbr** [comment]
Yes, just noticed this as well. Should be an easy fix, @gwyneplaine and I will fix that while we're at it!
