### ISSUE TITLE
Field errors in s3 file upload

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#3345]
I have a model with the following code for uploading files to an s3 bucket,

```javascript
var keystone = require('keystone')
var	Types = keystone.Field.Types

var s3_storage = new keystone.Storage({
	adapter: require('keystone-storage-adapter-s3'),
	s3: {
		key: process.env.S3_KEY,
		secret: process.env.S3_SECRET,
		bucket: process.env.S3_BUCKET,
		path: '/assets',
		headers: {
			'x-amz-acl': 'public-read', // add default headers; see below for details
		}
	},
	schema: {
		bucket: true, // optional; store the bucket the file was uploaded to in your db
		etag: true, // optional; store the etag for the resource
		path: true, // optional; store the path of the file in your db
		url: true, // optional; generate & store a public URL
	}
})

var Product = new keystone.List('Product')

Product.add({
	image: { type: Types.File, storage: s3_storage },
})

Product.register()
```

In the admin I upload the image for the product, then  I press save and finally I get the error **"Field errors"**, is something wrong with my code? I'm using the latest current version of master.

**Comment by mxstbr** [comment]
Awesome, this is exactly the kind of bug we're looking for!

Any errors in either the browser console or the terminal?

**Comment by GwonHyeok** [comment]
what is your was s3 region ??

**Comment by GwonHyeok** [comment]
i'm working well 

```javascript
const storage = new keystone.Storage({
	adapter: require('keystone-storage-adapter-s3'),
	s3: {
		path: '/files',
		region: 'ap-northeast-1',
		headers: {
			'x-amz-acl': 'public-read'
		},
	},
	schema: {
		bucket: true, // optional; store the bucket the file was uploaded to in your db
		etag: true, // optional; store the etag for the resource
		path: true, // optional; store the path of the file in your db
		url: true, // optional; generate & store a public URL
	}
});


File.add({
	name: {type: String},
	file: {
		type: Types.File,
		storage: storage,
		label: '대표 이미지'
	},
});
```

**Comment by ellipticaldoor** [comment]
I get the following when I try to upload
![image](https://cloud.githubusercontent.com/assets/3449006/17806427/5fa9309a-65fc-11e6-830f-1919bf5890c7.png)

@GwonHyeok I added my region, 'us-west-2' but I get the same error.

This is what it's appearing in the console:

```
POST /keystone/api/products/57b6d3340c8ebf73e389c83a 500 1768.116 ms
```

**Comment by ellipticaldoor** [comment]
How I can debug this error?

**Comment by mxstbr** [comment]
I'd start by going into `node_modules/keystone/fields/types/file/FileType.js` and putting some `console.log`s in there to find out where the error happens!

**Comment by ellipticaldoor** [comment]
I'm getting an error 400 from amazon, my secret and key is fine because I used the cli tool of amazon and it's uploading files fine.

Maybe it's because of how I configured keystone?

I just added in the .env file the variables like this

S3_BUCKET=bucket.tests
S3_KEY=AGFSGHSGHGHH
S3_SECRET=AJKSJHSJK/ADSDFGGFSF/DHJBHJGDJHGDf
S3_REGION=eu-central-1

**Comment by mxstbr** [comment]
I'm assuming your comment in the other issue was actually meant to be posted here?

**Comment by ellipticaldoor** [comment]
@mxstbr yes!

I found the problem! I'm using the frankfurt region of s3 and it seems like knox (one dependency of keystone) doesn't support this. Here is more info Automattic/knox#254

**Comment by mxstbr** [comment]
Since this is nothing we can fix from our side, I'll close this for now – thanks for reporting it, I'm sure other people will find this helpful as well!

**Comment by ellipticaldoor** [comment]
I'm working on this, I think the best way is to replace knox with the official aws-sdk for uploading files, when I have it I will make a pull request.

**Comment by DerekDomino** [comment]
Is there a PR or ticket issue to follow up on the replacement of knox by the official aws-sdk in KeystoneJS ?

**Comment by askdesigners** [comment]
seriously that lib doesn't support the region?!? Uhhh...

**Comment by sefigrossman** [comment]
Does anyone have a workaround?

**Comment by hari419** [comment]
i'm getting this below error, when i'm trying to upload image to aws s3 using keystonejs. don't know why!!!
upload failed - Amazon returned Http Code: 400
