### ISSUE TITLE
starter project is broken

### ISSUE THREAD

**Issue by yoyoys** [keystonejs/keystone#3346]
# Bug report

## Describe the bug
I've just fresh installed mongodb 4.4.0 on my mac 10.15.6.

`npm init keystone-app keystone-test` is broken now.
I need to update `@keystonejs/keystone` to `13.0.0` to run example.

And auth project is broken, user will not auto-created when connect to db.
(Sorry for missing output logs)

## To Reproduce
1.  just run `npm init keystone-app keystone-test`
2. run `npm run dev`

## Expected behaviour

Run dev and everything got fine.

## Screenshots
none

## System information

- OS: macOS 10.15.6

## Additional context
none

**Comment by ajdegol** [comment]
Can confirm the same issue, got:
`✖ Initialising Keystone instance
TypeError: keystone.createApolloServer is not a function`

Seemed to resolve by bumping keystone to 13.

**Comment by amirmamaghani** [comment]
you can fix that forcing to version ^13 
`yarn install @keystonejs/keystone^13.0.0`

**Comment by vladignatyev** [comment]
@amirmamaghani @ajdegol could you share please the working `package.json` or dependencies/versions list? Many thanks! Faced the similar issue #3349

**Comment by MadeByMike** [comment]
I added an answer in #3349 - @amirmamaghani is correct. Sorry about this folks.

Closing as duplicate
