### ISSUE TITLE
[0.3.x] Cannot supply flags when constructing one RegExp from another

### ISSUE THREAD

**Issue by altmind** [keystonejs/keystone#3347]
### Steps to reproduce the behavior

configure and mount keystone:
    const keystone = require('./config/keystone')(mongoose, app, config);
    keystone.mount('/', app, { ... });

Issue a request to localhost:3000/keystone/signin
### Expected behavior

Application not throwing an error in console
### Actual behavior

Keystone running under node 4.3.2 throws an error while trying to process request

```
TypeError: Cannot supply flags when constructing one RegExp from another
    at new RegExp (native)
    at ...\node_modules\keystone\lib\core\mount.js:229:44
    at Layer.handle [as handle_request] (...\node_modules\express\lib\router\layer.js:95:5)
    at next (...\node_modules\express\lib\router\route.js:131:13)
...
```

I'm using the latest stable keystone version 0.3.22(according to npmjs)
The error happens on line https://github.com/keystonejs/keystone/blob/aa8321c1134a7c5b4834efd3d96d9a2073c4aed9/lib/core/mount.js#L228 (source is from tag 0.3.21, i cannot find tag 0.3.22 that i'm actually using)

It seems like a easy no-brainer fix `new RegExp(/\/\//, 'g')` -> `/\/\//g`.

**Comment by Noviny** [comment]
Closed as we are no longer supporting 0.3 issues
