### ISSUE TITLE
e2e: refactor

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#3359]
Now that e2e is stable, it is time to go back and try to do things a litter better.  This issue captures refactoring items that will be addressed.

   - [X] Port all field Page Objects to the new Field Test Object and generate corresponding list model test config.  Also update the field tests to conform.
       - [X] boolean -- @webteckie
       - [X] code -- @webteckie
       - [X] color -- @jstockwin
       - [X] cloudinaryImage -- @jstockwin
       - [X] cloudinaryImages -- @jstockwin
       - [X] date -- @jstockwin
       - [X] dateArray -- @jstockwin and @webteckie 
       - [X] datetime -- @jstockwin
       - [X] email -- @jstockwin
       - [X] file-- @jstockwin
       - [X] geoPoint-- @jstockwin
       - [X] html -- @jstockwin
       - [X] key-- @jstockwin
       - [X] location -- @webteckie
       - [X] markdown-- @jstockwin
       - [X] money-- @jstockwin
       - [X] name -- @webteckie
       - [X] number @jstockwin
       - [X] numberarray -- @jstockwin
       - [X] password-- @jstockwin
       - [X] relationship -- @webteckie
       - [X] select -- @webteckie
       - [X] textarea -- @webteckie
       - [X] textarray -- @jstockwin
       - [X] text-- @jstockwin
       - [X] url -- @webteckie
       - [X] user -- @webteckie

   - [X] Once all field Page Objects have been ported to the new Field Test Object update all the other group tests to use the new interface.
       - [X] Group003List
       - [X] Group004Item

   - [X] Remove direct Field Test Object knowledge from tests.  Tests should always invoke any Field Test Object via a Page Object command of the form displaying the field.
       - [X] Group001Login -- @webteckie

   - [X] Misc
       - [X] Rename screen Page Objects (home, list, and item) to reflect that they are screens -- @webteckie
       - [X] `itemPage` and `initialFormPage` seem to be interchangeable which is bad. See [here](https://github.com/keystonejs/keystone/commit/6915455e15684fd0be69ab722762247bdcbab020#diff-80152b65f1a198994c48eedde56ea417L55). When fixed, there's a test commented out in group004, which was breaking because of this.
       - [X] Pass options to e.g. `assertUIVisible` on a per-field rather than a per-model basis -- @jstockwin
      - [X] Re-order travis jobs. E2e now runs first, as group005 takes the longest. 

### Expected behavior
e2e is relatively easy to work with and reuse with any keystone app.

### Actual behavior
e2e is a bit difficult to work with and cannot be reused by keystone apps.

**Comment by JedWatson** [comment]
Closed with #3429, nice work @webteckie and @jstockwin!
