### ISSUE TITLE
Error: Cannot find module '@google-cloud/speech'

### ISSUE THREAD

**Issue by garyzhu2** [keystonejs/keystone#3360]
# Bug report

## Describe the bug

After npm installing @google-cloud/speech and rebuilding keystone and running npm install, I cannot seem to require @google-cloud/speech anywhere without the server crashing.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

I have a keystone js file starting with 

const { Keystone } = require('@keystonejs/keystone');
const { PasswordAuthStrategy } = require('@keystonejs/auth-password');
const { GraphQLApp } = require('@keystonejs/app-graphql');
const { AdminUIApp } = require('@keystonejs/app-admin-ui');

const { StaticApp } = require('@keystonejs/app-static');
const {speech} = require('@google-cloud/speech');

and localhost 3000 gives no response from server

## Expected behaviour

The server should give me response. I check error logs and there was a "Error: Cannot find module google-cloud/speech"

## Additional context

I was able to install and require app-static without a problem.

**Comment by garyzhu2** [comment]
closing because `const {speech} = require('@google-cloud/speech')` seems to work..

**Comment by garyzhu2** [comment]
oops that did not work, reopening

**Comment by timleslie** [comment]
This looks like an issue with your installation of `@google-cloud/speech`, not an issue with keystone.

> "Error: Cannot find module google-cloud/speech"

This suggests that this module is not correctly installed.
