### ISSUE TITLE
Module error in v0.4.0-alpha

### ISSUE THREAD

**Issue by LucasIcarus** [keystonejs/keystone#3365]
In `keystone/admin/client/packages.js`

```js
module.exports = [
	'aphrodite/no-important',
        'async',
        // ...
	// other modules
]
```

after it bundled by browerify and loaded in browser, `window.require('aphrodite/no-important')` throw an error that this module couldn't be found, meanwhile, other modules works fine.

I'm running it in Win10-x64 and node 6+, npm 3+, Chromium 52.0.2743.116.

And in `keystone/admin/public/js/packages.js` couldn't find any word about 'aphrodite'

Even it has been uglified, when I format it found this at around 24250 line

```js
  // other numbered module
  ],
  579: [function (e, t, n) {
    function r() {
      for (var e = {}, t = 0; t < arguments.length; t++) {
        var n = arguments[t]
        for (var r in n)o.call(n, r) && (e[r] = n[r])
      }
      return e
    }

    t.exports = r
    var o = Object.prototype.hasOwnProperty
  }, {}],
  async: [function (e, t, n) {
    (function (e, r) {
      !function (e, r) {
  // ... other code
```
First module that has a name is async.. Is that correct? Or is there some change in v0.4.0 haven't been noticed?

Not very good in English, my bad... 

Good day and thanks for this amazing repo.

**Comment by mxstbr** [comment]
I think the issue is that `aphrodite` needs to be there, not `aphrodite/no-important`! Would you mind submitting a PR fixing this?

**Comment by w01fgang** [comment]
There is `aphrodite/no-important` in the [docs](https://www.npmjs.com/package/aphrodite#disabling-important) of `aphrodite` and it's used for remove `!important`.
Maybe it's a bug of `aphrodite`, but `aphrodite/no-important` should work.
Related issue #3223

**Comment by mxstbr** [comment]
No it shouldn't, `aphrodite` is the module, `aphrodite/no-important` refers to a directory inside that module.

So what should be bundled is `aphrodite`, at which point `aphrodite/no-important` might break which is a problem with our build system.

**Comment by w01fgang** [comment]
I start `keystone` and when I see an error `not found aphrodite/no-important`, then I open another console and go to `project_root/node_modules/keystone` and run `npm run build`. When it's finished, I refresh the page and the error disappears and UI works.

**Comment by JedWatson** [comment]
Sounds like we've got a bunk build in the repo. I'll check it out.

@mxstbr actually `aphrodite/no-important` *is* what we want, because that's the explicit name that you require, e.g.

```js
import { css } from 'aphrodite/no-important';
```

The way it's packaged is actually pretty terrible, we've had a lot of problems because of it but I fought that fight on Aphrodite and lost.

**Comment by LucasIcarus** [comment]
Thanks for the reply. 
@w01fgang That will be great if rerun the bundle can fix this. But in windows node_modules is parallel and is not that convenient to rerun build... 
I fork the repo and will do some test, and update the result here.

**Comment by LucasIcarus** [comment]
`npm run build` method confirmed.

with change the script in `package.json` for windows
```js
"scripts": {
    "build": "set NODE_ENV=production&&node build.js | uglifyjs -mc warnings=false,screw_ie8=true -b beautify=false,semicolons=false > ./admin/public/js/packages.js",
    // ... others
```
And run it the packages.js in `keystone/admin/public/js` turned out

```js
581: [function (e, t, n) {
    function r() {
      for (var e = {}, t = 0; t < arguments.length; t++) {
        var n = arguments[t]
        for (var r in n)o.call(n, r) && (e[r] = n[r])
      }
      return e
    }

    t.exports = r
    var o = Object.prototype.hasOwnProperty
  }, {}],
  "aphrodite/no-important": [function (e, t, n) {
    t.exports = e("./lib/no-important.js")
  }, {"./lib/no-important.js": 4}],
  async: [function (e, t, n) {
    (function (e, r) {
      !function (e, r) {

  // ...other code
``` 
Simply replace the packages.js file in test and the UI works. Missing module is back.

Still don't know what causes this but I think a rebuild is required for v0.4.0. Browserify config? missing build before commit change? Anyway, fixed bug, good bug.

Thank you guys all.

**Comment by JedWatson** [comment]
I've updated the bundle, let me know if this is still an issue with a fresh install!
