### ISSUE TITLE
Uncaught ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by mattapperson** [keystonejs/keystone#3367]
Note: running 4.0 off of master on hash 4c7c6c5 

### Steps to reproduce the behavior
1. Go to yoursite.com/keystone
2. Login using valid login info
3. Profit... I mean blow up :)

### Expected behavior
To reach the admin dashboard

### Actual behavior
White screen and browser console shows:
`admin.js:1564 Uncaught ReferenceError: babelHelpers is not defined`

**Comment by JedWatson** [comment]
_sigh_ what on earth is going on with our build!

I can't reproduce this locally... can you give some more information? e.g. is the keystone dep installed from git, or are you running npm link w/ a local clone? etc.

**Comment by mattapperson** [comment]
Installed from GIT

**Comment by mattapperson** [comment]
I'll get any more info I can shortly

**Comment by mattapperson** [comment]
@JedWatson So I got the issue to go away by running npm install inside keystone... Without doing that I can blow away node_modules and re-nstall and it works like 40% of the time, the other times I get the above error. Ill file this under NPM bug or else issue with a keystone build script?

**Comment by JedWatson** [comment]
Given that inconsistency, this sounds more like an npm issue to me ..?
