### ISSUE TITLE
Navigating back to list sometimes hangs

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#3369]
### Steps to reproduce the behavior
1. `node test/e2e/server.js --notest`
1. go to any List, create an item
1. click on the back to list link

### Expected behavior
* Back at list

### Actual behavior
* Spinner never stops

Redux actions:
![image](https://cloud.githubusercontent.com/assets/54934/17839749/39303b28-67f2-11e6-99a2-e55d70f016e3.png)
(the export button didn't work :( )

**Comment by mxstbr** [comment]
Newest `master`? We landed a big chunk of changes regarding exactly that behaviour in #3344 a few days ago.

cc @gwyneplaine

**Comment by wmertens** [comment]
Yup this is on master, at first I thought it was webpack ☺

**Comment by mxstbr** [comment]
Verified, broken since #3344 – for some reason we missed this. On it!
