### ISSUE TITLE
Finish updating multiple items at once

### ISSUE THREAD

**Issue by mxstbr** [keystonejs/keystone#3380]
The `ListView` includes code for an `UpdateModal` of some sort, which even has some local state associated with it – except `showUpdateModal` is always false if I'm not mistaken.

I have yet to find a way to trigger that to open, is there some magic button somewhere, can we remove all of that code or should we add a button somewhere?

**Comment by JedWatson** [comment]
It needs review, got bumped from "before beta" - might be relatively trivial now we've got the new API up and running!

Basically when you use the "manage" UI, there's meant to also be an "update" button that lets you edit items en masse. It brings up this dialog, which lets you set values in the fields you specifically choose and commit them to all the selected items.

**Comment by mxstbr** [comment]
Let's look at this after the beta then!

**Comment by chrisschaub** [comment]
Any progress on this?

**Comment by alsoicode** [comment]
+1 for a status update on bulk item editing. I have an immediate need for just such a feature.

**Comment by gautamsi** [comment]
Keystone 4 is going in maintenance mode. Expect no major change. see #4913 for details.
[Keystone v5](https://github.com/keystonejs/keystone-5)  has mass update feature. PR keystonejs/keystone-5#858 added this recently
