### ISSUE TITLE
Investigate 'nested to-many relationships can be limited' test that only fails on GitHub Actions

### ISSUE THREAD

**Issue by mitchellhamilton** [keystonejs/keystone#3405]
It's been skipped to get #3403 in but we should look into it.

https://github.com/keystonejs/keystone/blob/e383a5792426f9907854910bf6d01f7feb33a994/api-tests/relationships/filtering/nested.test.js#L84-L125

**Comment by timleslie** [comment]
`createItems` does not guarantee the order of the returned items. The test implicitly depends on this order, which is why it would sometimes fail. Test should be updated to be more robust against this property.

**Comment by mitchellhamilton** [comment]
This test was fixed
