### ISSUE TITLE
Happy Birthday Jed! 🎉

### ISSUE THREAD

**Issue by mxstbr** [keystonejs/keystone#3412]
Today is Jeds birthday, I figured it would only be reasonable to congratulate him. Let's all wish him a happy birthday together! 🎊

**Comment by bladey** [comment]
Happy Birthday Jed! 🎈

**Comment by cameronbourke** [comment]
Happy Birthday Jed! I agree with @mxstbr, it is perfectly reasonable to give him a big congrats!

**Comment by twalve** [comment]
![HAPPY BIRTHDAY](https://img.shields.io/badge/style-Jed-green.svg?label=happy%20birthday)

**Comment by weekwood** [comment]
[https://camo.githubusercontent.com/18061cacf15b05c868bf88f70400082a76d24861/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f7374796c652d4a65642d677265656e2e7376673f6c6162656c3d68617070792532306269727468646179](https://camo.githubusercontent.com/18061cacf15b05c868bf88f70400082a76d24861/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f7374796c652d4a65642d677265656e2e7376673f6c6162656c3d68617070792532306269727468646179)

**Comment by weekwood** [comment]
Happy Birthday Jed！

**Comment by BorisBozic** [comment]
Woo hoo, happy birthday Jeddos!

**Comment by SharadKumar** [comment]
👍

**Comment by gmmeyer** [comment]
🍰 🎈 Happy Birthday!

**Comment by wmertens** [comment]
😃 🐣📆, 👴! 💯🔁!

**Comment by snawbel** [comment]
When can this issue be closed? And what would that mean?

**Comment by creynders** [comment]
Woohoo, happy birthday!

**Comment by dariasamo** [comment]
Happy birthday!

**Comment by jstockwin** [comment]
Happy Birthday

**Comment by VinayaSathyanarayana** [comment]
Happy Birthday @JedWatson

**Comment by webteckie** [comment]
Felix Cumpleaños @JedWatson

**Comment by ostruzina** [comment]
Happy birthday Jed!

**Comment by JedWatson** [comment]
Haha thanks everyone, it's been brilliant!

Keystone 4 beta shipped, what more could I ask for 😊

**Comment by sachingill** [comment]
Happy Birthday Jed.

**Comment by Davidcreador** [comment]
Happy Birthday, Jed! Have an awesome day man! Thanks for all the effort you put in everyday. :)

**Comment by mikeerickson** [comment]
Happy Birthday Jed!

**Comment by bvaughn** [comment]
👍 Happy birthday dude!

**Comment by ryardley** [comment]
🎂

**Comment by martinschaer** [comment]
Happy Birthday Jed! 🎉

**Comment by r1b** [comment]
Happy birthday! And congrats to all on the v4 release!!

**Comment by pswoodworth** [comment]
Happy Birthday Jed! Thanks for all your hard work – it makes the rest of our work that much better.  🎊

**Comment by danielmahon** [comment]
![811412_enlrg](https://cloud.githubusercontent.com/assets/1088089/17983144/2512af7e-6ad9-11e6-8979-bb996551873a.jpg)

**Comment by gzhappysky** [comment]
Happy birthday....ha ha
