### ISSUE TITLE
Issues with content field, Add button not displaying, Unable to add Cloudinary or Unsplash blocks

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#3413]
#### Current Behaviour
When I focus the content field no add button is displayed on the left hand side
<img width="1071" alt="Screen Shot 2020-08-18 at 3 04 16 pm" src="https://user-images.githubusercontent.com/42298774/90472588-2ca1c580-e164-11ea-9f95-b4b047514920.png">

#### Expected Behaviour
When I focus the content field I should be able to see a `+` button that shows several block options when clicked. 
<img width="1085" alt="Screen Shot 2020-08-18 at 3 01 05 pm" src="https://user-images.githubusercontent.com/42298774/90472391-bbfaa900-e163-11ea-9e77-fbf5df43a40f.png">

This issue can be resolved by changing...
https://github.com/keystonejs/keystone/blob/4aad74c531fe7ce0de1c31763e50a47bd06766e9/packages/fields-content/src/views/editor/add-block.js#L37

too...
```
if (!blocks || !Object.keys(blocks).length) return;
```

### 2. Unable to add a Cloudinary image block to the content field
If the add button issue is resolved and I try to add a cloudinary image the content field, the field will error
<img width="1070" alt="Screen Shot 2020-08-18 at 3 14 05 pm" src="https://user-images.githubusercontent.com/42298774/90473131-82c33880-e165-11ea-9075-dd740564ab00.png">

The following error is thrown in the console.
```
react-dom.development.js:19731 Uncaught TypeError: create is not a function
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitLifeCycles (react-dom.development.js:19787)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at commitRoot (react-dom.development.js:22381)
```
### 3. Unable to add an Unsplash image block to the content field
When I attempt to add an Unsplash image block to the content field, the field fails to search for images from unsplash and throws a graphql error.
<img width="1072" alt="Screen Shot 2020-08-18 at 3 20 43 pm" src="https://user-images.githubusercontent.com/42298774/90473509-6e337000-e166-11ea-9aaa-51ae1dd99165.png">

This is the graphql query that is called by the unsplash block:
```
query searchImages($query: String!, $page: Int, $perPage: Int, $width: String) {
  searchUnsplash(query: $query, perPage: $perPage, page: $page) {
    total
    totalPages
    results {↵
       id↵
       unsplashId↵ 
       publicUrl: publicUrlTransformed(transformation: {w: $width})
       width
       height
       alt
       user {
         name
         url         
       }
    }
  }
}

variables: {
  page: 1
  perPage: 5
  query: "hello"
  width: "400"
}
```
This is the graphql error returned by the query:
```
Cannot query field "searchUnsplash" on type "Query".
```

## To Reproduce

These issue can be reproduced by setting up the content filed in the blog demo-project. 
Change the `Post.body` field in the schema too...
```
    body: {
      type: Content,
      blocks: [
        [CloudinaryImage.blocks.image, { adapter: cloudinaryAdapter }],
        [
          Unsplash.blocks.unsplashImage,
          {
            attribution: 'vocal.media',
            accessKey: process.env.UNSPLASH_ACCESS_KEY,
            secretKey: process.env.UNSPLASH_SECRET_KEY,
          },
        ],
        [OEmbed.blocks.oEmbed, { adapter: iframelyAdapter }],
        Content.blocks.blockquote,
        Content.blocks.orderedList,
        Content.blocks.unorderedList,
        Content.blocks.link,
        Content.blocks.heading,
      ],
    },
```
You need to install the following packages 
`@keystonejs/fields-cloudinary-image@1.0.1`
`@keystonejs/fields-oembed@1.0.0`
`@keystonejs/fields-unsplash@1.0.0`
`@keystonejs/fields-content@^8.0.0`

Finally you need to set up the `CloudinaryAdapter`, `IframelyOEmbedAdapter` with your cloudinary and iframely API keys, as well as pass in your Unsplash API keys to the Unsplash block. 

```
const cloudinaryAdapter = new CloudinaryAdapter({
  cloudName: CLOUDINARY_CLOUD_NAME,
  apiKey: CLOUDINARY_KEY,
  apiSecret: CLOUDINARY_SECRET,
});
```

```
  iframelyAdapter = new IframelyOEmbedAdapter({
    apiKey: process.env.IFRAMELY_API_KEY,
  });
```

**Comment by Noviny** [comment]
There's a PR up to fix two of these bugs, but the unsplash one we're not going to get to right now.

There is a workaround, which is to add the following field:

```js
    hiddenUnsplashField: {
      type: Unsplash,
      accessKey: process.env.UNSPLASH_ACCESS_KEY,
      secretKey: process.env.UNSPLASH_SECRET_KEY,
      access: false,
    },
```

Add this below your block and leave a comment - this causes the unsplash graphql query to be loaded (it's not loaded if Unsplash is only used in a `block` for reasons that are too complex to fix right now)
