### ISSUE TITLE
Version 4.0.0 Beta

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#3415]
So it's been exactly a year since we merged the `0.4.0` branch into `master`. (see #1612)

Today, 365 days and 4137 commits later, we're nearly at the end of a much more significant refactor than anybody was expecting. Keystone is looking better than ever thanks to the hard work of the core team and an enormous amount of support, bug reports and contributions from our community! 🎉 

And we're nearly done! We're about to publish the first beta of the new version to npm. Please try it out, give us feedback below, and report issues you have working with it.

```
npm install --save keystone@next
```

Aside from fixing any issues that come up, we're now focusing on the upgrade guide, a new website, a new generator and new docs - all of which will be launched by the time we're out of beta. We rely on your feedback to make this the best it can be.

One more thing... in the same way that React [bumped their version from 0.14 to 15.0](https://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html) we're going to be calling our next release `4.0.0`!

The leading zero really understates the fact that Keystone has more than three years of consistent development effort behind it, powers thousands (hundreds of thousands?) of websites and apps, and has been stable on the `0.3.x` branch for over a year.

So we're fixing that, along with everything else.

— Jed, Joss and Max

**Comment by creynders** [comment]
Excellent idea re. v4.0.0!!

**Comment by BorisBozic** [comment]
Great work team #proudworkdad

**Comment by developit** [comment]
Hooray! 😄
Now to go test this out on all my sites haha

**Comment by program247365** [comment]
🎉🎉🎉

**Comment by karlbright** [comment]
Awesome work @JedWatson and others. :+1:

**Comment by cheshrkat** [comment]
SemVer FTW! ;)

**Comment by teamhail** [comment]
Thank you and congrats!

**Comment by Kiina** [comment]
Maybe a quick heads up about what is new in beta.2?

**Comment by atodorovAddison** [comment]
When will be the release of v4.0.0?

**Comment by fedorareis** [comment]
Not to nag, but is there any news on when the stable build of v4.0.0 will be released?

**Comment by jacobsfletch** [comment]
The whole world is waiting, Jed, Joss, and Max!

**Comment by gautamsi** [comment]
still Beta tag after 2 years of develppment? after Facebook, are you also inspired by Gmail (beta tag)?
