### ISSUE TITLE
Display fields of relationship field in Admin UI?

### ISSUE THREAD

**Issue by musiko** [keystonejs/keystone#3417]
Assume there are 3 tables named Level1, Level2, Level3:
```
Level1.add({
name: { type: String, label: "Level 1 Name" },
title: { type: String, label: 'Title' },
});

Level2.add({
name: { type: String, label: "Level 1 Name" },
title: { type: String, label: 'Title' },
level1: { type: Types.Relationship, label: "Level 1", ref: 'Level1' },
});

Level3.add({
name: { type: String, label: "Level 1 Name" },
title: { type: String, label: 'Title' },
level2: { type: Types.Relationship, label: "Level 2", ref: 'Level2' },
});
```
 Is it possible to display fields of relationship field in Admin UI? 
e.g. displaying Level1 in Level3 table:
`Level3.defaultColumns = 'name, title, level2, level2.level1';`

**Comment by zapbuild** [comment]
Hello @musiko 
I am also facing same issue. I have 'disabled' field in User model and I want to show this in Admin UI as a checkbox but unable to find solution.

Please help.
Thanks!

**Comment by mxstbr** [comment]
This is not yet possible, if you want this to happen please upvote it on ProductPains: https://productpains.com/post/keystonejs/relationship-ui-enhancements
