### ISSUE TITLE
Admin API: /api/session does not follow spec

### ISSUE THREAD

**Issue by christroutner** [keystonejs/keystone#3421]
### Steps to reproduce the behavior
This issue was originally reported on [this Admin API thread](https://github.com/keystonejs/keystone/issues/3209). I thought it would help if I reported it as its own separate issue.

I started a new repository last night, [keystone-api-tests](https://github.com/christroutner/keystone-api-tests), where I'll be writing a test script for the new Admin API and [Files field](https://github.com/keystonejs/keystone/issues/3228). The code used in this test script will also be used in the [API documentation](https://github.com/keystonejs/keystone/issues/3296) I'll be contributing. It's very simple right now.

The `/api/sessions` call returns an empty Object for a user that is not logged in, which is detectable on the front end with jQuery using the command `$.isEmptyObject(data)`. However, according to [the spec](https://github.com/keystonejs/keystone/blob/master/admin/server/api/Readme.md#session-api), it should return `undefined`. I'm not sure if that is the same thing.

### Expected behavior
get(/api/session) should return 'undefined' when user is not logged in.

### Actual behavior
get(/api/session) returns an empty Object.

**Comment by JedWatson** [comment]
Sorry @christroutner, that was an unclear spec. What I meant was that the `user` property in the response is `undefined`, e.g.

```js
{ user: undefined }
```

(which, in JSON, means the property is omitted completely)

I'll update the wording in the spec to clarify that!
