### ISSUE TITLE
Relationship on authenticateUserWithPassword Mutation returns AccessDeniedError on first call

### ISSUE THREAD

**Issue by theparthy** [keystonejs/keystone#3422]
Hey,
im not sure if this is a bug or just my lack of knowledge of Keystone.
If i run the sign in mutation i get the error that i don't have permissions to read the company fields. 
When i run the same mutation again i can read the company fields.

I suspect that the Authenticated user is not set to context 
```json
{  "errors": [
    {
      "message": "You do not have access to this resource",
      "name": "AccessDeniedError",
      "time_thrown": "2020-08-19T07:08:36.669Z",
      "data": {
        "type": "query",
        "target": "allCompanies"
      },
      "path": [
        "authenticate",
        "item",
        "company"
      ],
      "uid": "cke11bhry0000orag012y2hyc"
    }
  ],
}
```

```graphql
mutation signin($identity: String, $secret: String) {
  authenticate: authenticateUserWithPassword(
    email: $identity
    password: $secret
  ) {
    item {
      id
      name
      company{
        name
        id
      }
    }
  }
}
```
### User
```
exports.User = {
    access: {
        read: access.userIsAuthed,
        update: access.userIsAuthed,
        create: true,
        delete: access.userIsAdmin,
        auth: true,
    },
    fields: {
        name: {type: Text},
        email: {type: Text, isUnique: true},
        password: {
            type: Password,
            isRequired: true
        },
        isAdmin: {type: Checkbox, access: {update: access.userIsAdmin}},
        company: {
            type: Relationship,
            ref: 'Company.user',
            many: false
        },
    }
};
```
### Company
```js 
exports.Company = {
    access: {
        read: access.userIsCurrentAuth,
        update: access.userIsCurrentAuth,
        create: access.userIsCurrentAuth,
        delete: access.userIsCurrentAuth,
        auth: true,
    },
    fields: {
        name: {type: Text},
        isDeActivated: {
            type: Checkbox, access: {update: access.userIsAdmin}
        },
        user: {
            type: Relationship,
            ref: "User.company",
            many: true
        }
    },
    hooks: {},
};
```

**Comment by Vultraz** [comment]
What version of Keystone are you using? I can't reproduce this one.

**Comment by theparthy** [comment]
I have updated to the newest versions available and still having the issue
``
        "@keystonejs/adapter-mongoose": "^9.0.8",
        "@keystonejs/app-admin-ui": "^7.3.7",
        "@keystonejs/app-graphql": "^6.1.3",
        "@keystonejs/app-static": "^5.1.3",
        "@keystonejs/auth-password": "^5.1.15",
        "@keystonejs/email": "^5.2.0",
        "@keystonejs/fields": "^18.0.0",
        "@keystonejs/fields-wysiwyg-tinymce": "^5.3.11",
        "@keystonejs/file-adapters": "^7.0.8",
        "@keystonejs/keystone": "^17.0.0",
        "@keystonejs/list-plugins": "^7.1.2",
        "@keystonejs/server-side-graphql-client": "^1.1.2",
        "@keystonejs/session": "^8.1.1",
        "apollo-errors": "^1.9.0",
        "apollo-server": "^2.18.1",
        "apollo-server-errors": "^2.4.2",
```

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
