### ISSUE TITLE
How can I create a new page in Admin UI?

### ISSUE THREAD

**Issue by zapbuild** [keystonejs/keystone#3424]
Hello
I have new model say Product and I want to add/edit/delete products in keystone Admin. Please tell me the solution if this is possible.

Thanks

**Comment by jstockwin** [comment]
@zapbuild As this is a support request, not an issue, it'll need to be asked on Stackoverflow instead and this issue will be closed. (However if you link the post here afterwards I'll answer over there too). 

That said, I don't really understand your problem, so you may want to include a few more details in your stackoverflow post. If you've added a product model, then the page will automatically be added in keystone Admin, and you will already be able to add/edit/delete as you have asked - that's the whole point of using k
Keystone!. Have you tried this and it's not working?

**Comment by jstockwin** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
