### ISSUE TITLE
 4.0-Beta-1: Location field does not get geo coordinates from google APIs 

### ISSUE THREAD

**Issue by rafmsou** [keystonejs/keystone#3430]
### Steps to reproduce the behavior
With Google APIs keys set in keystone, try to save a record with a location field filled with some address info.
### Expected behavior
After the save, the lat and lng fields should be updated with data relating the provided address.
### Actual behavior
After the save, the lat and lng fields are blank.

Tested against version 0.3.22 and the same code works fine.
Using the package 4.0.0-beta.1 from NPM.

**Comment by JedWatson** [comment]
Good catch @rafmsou, you're totally correct. That code was missed in the new `updateItem` method, I'll re-implement it.

**Comment by rafmsou** [comment]
Okay, looking forward for it :)

**Comment by jstockwin** [comment]
@JedWatson I still can't get this to work. For me, the lat/long coordinates are filled in, but they're always just 0? 

Also, should only filling in the lat/lng numbers and then saving cause the other fields to be filled in, or is that not a feature? If that should happen, it doesn't..?

@rafmsou Is this working for you after the fix?

**Comment by rafmsou** [comment]
Yep, right after the fix was working fine. Did not test it recently though.
