### ISSUE TITLE
GraphQL "where" clauses break if field has an "_" with Knex adapter

### ISSUE THREAD

**Issue by terrygonguet** [keystonejs/keystone#3431]
# Bug report

## Describe and reproduce the bug

I have a list that looks like this:

```js
keystone.createList("Something", {
  fields: {
    name_en: { type: Text }
    // ...
  }
})
```

And another list (SomethingElse) that has a relation to it.
If I try to query it with a where it fails:

```gql
{
  allSomethingElses(where: { something: { name_en: "stuff" } }) { ... }
}
```

With error: `Cannot destructure property 'rel' of 'fieldAdapter' as it is undefined.`

It might happen with simpler scenarios but that's how it broke for me. Everything works correctly if the name doesn't contain an "_".

I looked at where the error happens (`@keystonejs/adapter-knex/lib/adapter-knex.js:815:19`) but I honestly don't understand why it happens or not. I guess somewhere the adapter thinks that the "_" signifies a condition like "fieldname_not".

## System information

- OS: Win10
- Node 14
- Keystone versions:

```json
{
	"@keystonejs/adapter-knex": "^11.0.1",
	"@keystonejs/adapter-mongoose": "^9.0.1",
	"@keystonejs/app-admin-ui": "^7.3.0",
	"@keystonejs/app-graphql": "^6.0.0",
	"@keystonejs/app-static": "^5.1.2",
	"@keystonejs/auth-password": "^5.1.13",
	"@keystonejs/field-content": "^7.0.3",
	"@keystonejs/fields": "^16.0.0",
	"@keystonejs/fields-authed-relationship": "^1.0.10",
	"@keystonejs/fields-datetime-utc": "^6.0.4",
	"@keystonejs/fields-wysiwyg-tinymce": "^5.3.5",
	"@keystonejs/file-adapters": "^7.0.2",
	"@keystonejs/keystone": "^13.1.0",
	"@keystonejs/server-side-graphql-client": "^1.1.0"
}
```

**Comment by BikramjeetSingh** [comment]
@Noviny I fixed a similar bug in this repository a couple of months ago. If you haven't taken care of it already and don't plan to, can I be assigned this issue?

**Comment by Noviny** [comment]
Ah, sorry, this has since been fixed and should have been closed, my bad. It should be working in the latest version:

https://changelogs.xyz/@keystonejs/adapter-knex#1107
