### ISSUE TITLE
Admin API: Non-Admin users can not get(/keystone/api/{list})

### ISSUE THREAD

**Issue by christroutner** [keystonejs/keystone#3438]
### Steps to reproduce the behavior
I've updated the [keystone-api-tests repository](https://github.com/christroutner/keystone-api-tests) to incorporate tests for non-admin users. Follow the instructions in the readme and run it against a non-admin user.

At present, logged in, non-admin users can not use the Admin API. It would be advantageous if logged in, non-admin users could at least obtain read access to the API.

### Expected behavior
The [API specification](https://github.com/keystonejs/keystone/blob/master/admin/server/api/Readme.md) does not distinguish between admin and non-admin users. I would expect non-admin users to at least have read access (GET), even if they are restricted with write access (POST).

### Actual behavior
The server returns a sign-in page, even though the user is logged in. It would probably be better to return a 403 error if non-admin users should be restricted.

**Comment by mxstbr** [comment]
This is essentially what we want to accomplish with https://productpains.com/post/keystonejs/role-based-admin-system, but we need a proper, holisitic solution for it. I'll close this for now since this is on our roadmap, thanks for the reminder!
