### ISSUE TITLE
Heroku Error R10 (Boot timeout) w/ Long Running Application Updates

### ISSUE THREAD

**Issue by brianjd** [keystonejs/keystone#3447]

**Comment by mxstbr** [comment]
Any logs you can provide?

**Comment by brianjd** [comment]
Nothing particularly useful.  Essentially, on Heroku, if your application doesn't bind to the assigned port within 60seconds you will encounter this error.  I did speak with Heroku support regarding it, and  they are able to temporarily extend this to 120 seconds if needed (in my case it wasn't enough).

**Comment by jstockwin** [comment]
@brianjd A not very good solution to this would be to split your updates into multiple scripts and add them one at a time. Admittedly, not a very nice solution, but it should work... 

Not sure how we're supposed to fix this one really. Applying the updates just takes time...

**Comment by brianjd** [comment]
@jstockwin I think ultimately the boot/init process will have to be reviewed.  One possible solution is to have a proxy bind to the assigned port right away that points to the express application on another port.

**Comment by webteckie** [comment]
@brianjd  I think that an alternative may be to disable automatic updates and, instead, apply them manually after startup.  I think there may also be a defer option for updates although admittedly not sure how it works.  @JedWatson is there such feature and, if so, how would it work?

**Comment by Noviny** [comment]
The defer option is an additional property on an update that means it will not be run until the defer is manually removed. I'd recommend using a local instance to populate your hosted database, and then simply connect the heroku instance. If the updates were already run, this problem won't occur.
