### ISSUE TITLE
Look beyond MongoDB/Mongoose

### ISSUE THREAD

**Issue by iyobo** [keystonejs/keystone#3448]
Keystone's Admin UI is definitely **the best** thing in the NodeJS world in terms of closely matching what I enjoyed back in the Django admin days. Kudos on the KeyStone API too: being able to integrate it into my KoaJS pseudo-framework as the defacto backend admin tool is just boss!

So I was thinking, why limit this awesomeness to just MongoDB alone?
I am thinking of converting keystone to use **[CaminteJS](https://github.com/biggora/caminte)** in my newly created fork.

CaminteJS is a cross-db ORM, and is very similar in form and operations to Mongoose (schemas, relationships, hooks, models et al), except it works with several other Databases besides just MongoDB. It supports both SQL and No-SQL databases like Postgres, MongoDB, Cassandra, and also ReThinkDB and ArangoDB...which IMO are 2 of the most interesting new databases out in the wilds today.

This gives people the flexibility to use whatever databases they want/need to use, which in turn, will only lead to KeystoneJS attracting more of the good kind of attention. 

As an example: For serious applications, I personally despise MongoDB's lack of transactions. Failing a series of interconnected database updates mid-process is an operations nightmare every single time because I can't just roll-back....a luxury given to me by ArangoDB. (_And please no-one start with that "`If you need transactions in MongoDB you are doing it wrong`" rhetoric as that just reveals a lack of exposure to serious software projects, or ones with serious legal ramifications, on your end_)

Give or take the need to add a few more new fields, I really think migrating KeystoneJS to an ORM/ODM as open-minded as CaminteJS is the **next evolutionary step** for KeystoneJS. It's something I intend to start working on in my fork. I just need to hear from the KeystoneJS veterans (e.g. @JedWatson) about thoughts, pointings in the right direction, and basically just a general community feeling about this.

Floor's open!

**Comment by r3wt** [comment]
A cursory glance of the api and the issue tracker reveals a few alarming issues. voting no for now, although i have no official say in the matter. the api is very limited (in context of mongodb specifically). I would be a fan of a mongoose like api that could be used with PostGRES. that would give me back the no hassle scaling and performance i'm accustomed to while keeping the simplicity of development with mongoose. Just my opinion.

**Comment by iyobo** [comment]
@r3wt I agree. I wanted to believe so much that I finally found something "the answer" to flexible data/doc management in NodeJS that I failed to dig a little deeper.

Upon further inspection CaminteJS does seem rather shady. 
Apparently they just forked jugglingDB (another stale project) and didn't change anything. 
It's pretty frustrating the current state of affairs of ODMs in node-land.

Mongoose does appear to be the easiest ODM to work with, with the painful limitation of just being MongoDB only. I guess the first step is for a good yet generic ODM to exist first before Keystone starts thinking of changing it's base. Which likely makes this suggestion/enhancement a bit pre-mature...

**Comment by iyobo** [comment]
Actually, [JugglingDB](https://github.com/1602/jugglingdb) seems to be picking back up since last I checked.
Upcoming release and all and quite a few commits. Look like the developer(s) are back on it.
I think I'll just change the name of this issue to keep things fluid based on whatever happens to be "ready" when we decide it's time to look beyond MongoDB/Mongoose.

**Comment by Noviny** [comment]
Closing this as an issue as a finished discussion.

**Comment by JedWatson** [comment]
I just wanted to leave a closing note here that this is something we're actively investigating for a future version of keystone, allowing the use of pluggable back-ends (e.g. mongoose, bookshelf, or a graphql server)

But 👍 for closing at the moment, as we're trying to get the open issues down to just represent what's really pressing for the current version.

**Comment by quitequinn** [comment]
Was there ever further discussion on this?

**Comment by iyobo** [comment]
This led me to create http://jollofjs.com

**Comment by quitequinn** [comment]
...but I wish it was KeystoneJS. @JedWatson has your team used any other databases with the current Keystone release?

**Comment by iyobo** [comment]
So did I at a point. I think KeystoneJS is probably too tightly coupled with MongoDB at this point that changing that would be a massive, refactor that will also affect legacy projects already using it.
