### ISSUE TITLE
Review error handling and options

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#345]
This issue is inspired by #342 as well as things I've been meaning to get to re: our built in error handling.

We are making some assumptions about how errors should be handled, including `ECONNRESET` and `EADDRINUSE` which in an isolated system should make things easier.

We're also handling, in a basic way, `404` and `500` errors with generic templates.

I think there is potential, however, for these techniques to cause problems when Keystone is used as part of a more complex application or when those errors are thrown for reasons we're not aware of yet.

So while it may be possible to generally improve error handling across the board for common use cases, it may also be dangerous and raise unexpected problems in certain situations.

Our approach is worth a considered review, in terms of how best to handle common or generic errors. There is an up-side to having Keystone implement good generic error handling, but any decisions we make should be controlled with options, so that they can be changed as required. We should also well document when and how developers should take these decisions into their own hands.

Feedback on this would be very welcome.

**Comment by mxstbr** [comment]
This is likely done with the new API in 0.4, so I'll close this for now. Feel free to comment again if that's not the case!
