### ISSUE TITLE
model inheritance weirdness on required fields added to child models

### ISSUE THREAD

**Issue by steveinatorx** [keystonejs/keystone#3452]
I have two models that inherit from a third - Car and Truck inherit from root model Automobile. 

Truck needs some additional required fields that dont exist in Car - so i added them to the Truck model. 

After adding these fields and dropping "Automobile" collection and restarting - Car will never validate because the way that keystonejs  inheritance works AFAICT is that all required indexes are popped onto the root model and all children share the same schema- so i dont see a way that this architecture could support required fields that dont exist in ALL child models.

In addition to the required fields issue - it looks to me like the last model to register in sequence also overwrites previous inherited required fields - including the parent model fields. 

As a workaround - i had to add the net superset of all required fields to every child model and the root model to all models in this structure - and add hidden and default dummy values into the fields that i didnt want a particular child model to show. 

I would think that it might make more sense to have a keystone model architecture that more closely models noSQL and you might want to get rid of inheritance and focus on trying to hammer out embedded objects API and UX perhaps? just my $0.02 and wanted to point this out as i know @JedWatson et al has been looking at subdocuments lately.  

TL;DNR inheritance 'required' seems broken but 'noedit' and 'hidden' inheritance seems to work as designed.

**Comment by Noviny** [comment]
@steveinatorx Thanks for the information. Inheritance is quite odd and likely needs some tidying up. The majority of the complexity stems from the fact that in the database, they are saved to a single model, and mongo can enforce some structural elements.

Closing this as an issue, but appreciate the feedback. It will definitely go into any new round of looking at how keystone does inheritance.
