### ISSUE TITLE
[4.0.0-beta] Created At/Updated At times are not properly formatted. 

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3456]
### Steps to reproduce the behavior

Create a field with `track: true`

### Expected behavior

`Updated At` and `Created At` fields should properly display their respective datetimes in the admin UI. 

### Actual behavior

The times are formatted incorrectly - they're missing preceeding zeros. The following should read "9:02:09", not "9:2:9".

![image](https://cloud.githubusercontent.com/assets/8227759/18241218/d6a33af8-7347-11e6-8186-9ee3f5ec80ac.png)

**Comment by mxstbr** [comment]
@JedWatson over to you

**Comment by JedWatson** [comment]
Sorted. Thanks for the catch, @jstockwin
