### ISSUE TITLE
Remove errant `$` from modal invoked from List delete actions

### ISSUE THREAD

**Issue by twalve** [keystonejs/keystone#3463]
### Steps to reproduce the behavior

Click the trash icon in an admin view to remove a list member in and a confirmation dialog will be displayed. Older versions, before @mxstbr change [https://github.com/keystonejs/keystone/commit/62c1fa9], displayed HTML element tags in the text of the modal.

We tried updating to @next to get the benefit of 62c1fa9.

On @next still, a pesky `$`, dollar sign character, which is an apparent artefact from the mists-of-time shrouded days of templating, remained.
#3459 is looking to solve this issue. And an upcoming change to the PR does just that.
### Expected behavior

The bolded `name` or mapped `name` member would be displayed in the page.

![20160908_screen_keystone_expected](https://cloud.githubusercontent.com/assets/89387/18340461/5f0f6ce8-75e8-11e6-9bc2-dbd19cfeaeed.png)
### Actual behavior

The bolded `name` or mapped `name` member would be displayed in the page, preceded by an errant `$` dollar sign.

![20160908_screen_keystone_next](https://cloud.githubusercontent.com/assets/89387/18340408/19b86bae-75e8-11e6-8801-ee32dce30a6f.png)

**Comment by Noviny** [comment]
I haven't been able to reproduce this. Any more details?

**Comment by Noviny** [comment]
Closing as not reproduced.
