### ISSUE TITLE
BUG: Admin UI intermittently does not display as categories 

### ISSUE THREAD

**Issue by mrprkr** [keystonejs/keystone#3468]
Have never seen this bug before but occasionally the admin UI will stop tracking categories and display all models in a single list `other`. Not sure if this is unique to the repository I'm working on but have rebuilt it and still seeing this issue. Have tried both locally and on remote and still see this behaviour. @JedWatson Can invite you to the source repo if it's helpful to debug.

keystone.js
```js
...
// Configure the navigation bar in Keystone's Admin UI
keystone.set('nav', {
	content: ['HomePage','PublisherAdvertiserPage','NewsAndEvents','About', 'Contact', 'ListingPage','EventsListing','Article','SimplePage','SearchResults','AdDirListing','Newsletter'],
	events: 'Event',
	files: 'Tag',
	territories: ['Territory', 'Flag'],
	settings: ['SiteConfig', 'User']
});
keystone.start()
```

Admin UI View:

![screen shot 2016-09-09 at 16 13 55](https://cloud.githubusercontent.com/assets/6835002/18393239/8a027f66-76ac-11e6-98a6-0ff81c347486.png)

### Steps to reproduce the behaviour
Can't isolate to any particular steps but have replicated the issue in both keystone 0.3.8 and 4.0.0 - beta 2 on both local and remote hosts.

### Expected behavior
Admin UI to display lists in their categories

### Actual behavior
Lists display all together 

### Workaround
Restarting the server temporarily resolves the issue

**Comment by mrprkr** [comment]
Duh, Found in middleware: 
```js
// keystone.set('nav', {});
```

**Comment by JedWatson** [comment]
Glad to hear you figured it out 👍
