### ISSUE TITLE
Warning from Chrome re: TinyMCE

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#3471]
```bash
tinymce.min.js:2

'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
```
### Steps to reproduce the behavior

Go to an item with field `{ Types.Html, wysiwyg: true }`

**Comment by JedWatson** [comment]
@jossmac are you getting this in master? I upgraded tinymce to latest just two days ago.

**Comment by jossmac** [comment]
Will merge master into current branch and check

**Comment by jossmac** [comment]
Seems fine now
