### ISSUE TITLE
Field cannot be both initial:true and noedit:true

### ISSUE THREAD

**Issue by promethe42** [keystonejs/keystone#3473]
### Steps to reproduce the behavior

4.0.0-beta2, set a model field as both `initial:true` and `noedit:true`.
### Expected behavior

The corresponding model field is part of the model creation form and is not editable after creation.
### Actual behavior

The corresponding model field is part of the model creation form, but:
- the form doesn't validate
- an empty error (red rectangle) is displayed in the form
- server returns a 500 status error code

**Comment by promethe42** [comment]
Another issue is the server might not respond with a 500, but will not initialize those fields with the value from the form.

**Comment by AurelioDeRosa** [comment]
This issue is not present in beta-4.

**Comment by thejameskyle** [comment]
Closing based on @AurelioDeRosa's comment. If anyone runs into it in the future, please let us know
