### ISSUE TITLE
Using cloudinary causes blog posts to display [img] tags instead of image

### ISSUE THREAD

**Issue by vrghost242** [keystonejs/keystone#3477]
Have set up keystone.js to use cloudinary for images. The upload on the editor seems to work, I can see the file in the editor and on cloudinary. (Proof below)

http://res.cloudinary.com/keystone-demo/image/upload/v1473696039/y5v9oewncmuopq4d3vwi.jpg

Used the standard settings as per the documentation on the webpage, changes from the keystone.js file below:
```
'wysiwyg override toolbar': false,
'wysiwyg menubar': true,
'wysiwyg skin': 'lightgray',
'wysiwyg cloudinary images': true,
'wysiwyg additional buttons': 'searchreplace visualchars,'
+ ' charmap ltr rtl pagebreak paste, forecolor backcolor,'
+' emoticons media, preview print ',
'wysiwyg additional plugins': 'example, table, advlist, anchor,'
+ ' autolink, autosave, bbcode, charmap, contextmenu, '
+ ' directionality, emoticons, fullpage, hr, media, pagebreak,'
+ ' paste, preview, print, searchreplace, textcolor,'
+ ' visualblocks, visualchars, wordcount',
```
However, the editor does not use the type link, but changes it to [img]. This does work in the editor window:

`[img]http://res.cloudinary.com/keystone-demo/image/upload/v1473696039/y5v9oewncmuopq4d3vwi.jpg[/img]`
Problem is that when you open up the blog, you get

`[img]http://res.cloudinary.com/keystone-demo/image/upload/v1473696039/y5v9oewncmuopq4d3vwi.jpg[/img]
(example can be seen on my webpage: http://www.constructmind.com/blog/post/overview-of-the-uk-intergovernmental-agreement-for-fatca-implementation)`

I checked the documentation and cant find anything.

I also raised this on stackoverflow
http://stackoverflow.com/questions/39458699/image-links-not-rendering-as-html-left-as-img-on-blog

**Comment by wmertens** [comment]
I answered on stackoverflow, everything is working as designed :) Closing non-issue.
