### ISSUE TITLE
Image preview broken

### ISSUE THREAD

**Issue by BorisBozic** [keystonejs/keystone#3482]
### Steps to reproduce the behavior
- click an image preview (to invoke lightbox)
### Expected behavior
- show larger version of the image in lightbox
- clicking again on image should open the raw file in new tab
- (suggested) a way to quickly get to the source image directly. Currently you can do this by figuring out the cloudinary path manually)
### Actual behavior
- preview broken

![screen shot 2016-09-14 at 1 00 16 pm](https://cloud.githubusercontent.com/assets/3838716/18498610/36d9d8c0-7a7b-11e6-96d7-113cd011edfe.png)
![screen shot 2016-09-14 at 1 00 11 pm](https://cloud.githubusercontent.com/assets/3838716/18498611/3a3fecac-7a7b-11e6-9ea1-6abde9bcf084.png)

![admyt](https://cloud.githubusercontent.com/assets/3838716/18498635/588cd0e4-7a7b-11e6-9b48-ec9572cccddc.jpg)

**Comment by Noviny** [comment]
Just checked this on the demo site for a user with an image, and this appears to have been incidentally fixed along the line. Closing this as an issue.

Link to demo user I looked at:
