### ISSUE TITLE
Textarray field doesn't show up as a list when noedit = true

### ISSUE THREAD

**Issue by perazzi** [keystonejs/keystone#3483]
### Steps to reproduce the behavior

1 - Define a field as TextArray
2 - Manually add strings to it 
<img width="772" alt="screen shot 2016-09-14 at 10 16 58 am" src="https://cloud.githubusercontent.com/assets/1730311/18515737/65189e54-7a64-11e6-8462-e2c7873c7174.png">
3 - Update the field in the model, setting noedit:true;
4 - Open the admin panel and edit the item
### Expected behavior

Strings in the array should appear as a list
Something like this:
<img width="313" alt="screen shot 2016-09-14 at 10 18 23 am" src="https://cloud.githubusercontent.com/assets/1730311/18515802/a01ec460-7a64-11e6-8611-fc0d7e812577.png">
### Actual behavior

Strings are concatenated and displayed as a non-editable text field
<img width="391" alt="screen shot 2016-09-14 at 10 20 27 am" src="https://cloud.githubusercontent.com/assets/1730311/18515891/e2627e16-7a64-11e6-9add-9305c8a42df3.png">

Keystone v. 0.3.19

**Comment by jstockwin** [comment]
This has been fixed somewhere along the line, as it works nicely in current master:
![image](https://cloud.githubusercontent.com/assets/8227759/18951900/5da7b4b6-863f-11e6-826b-8881b6e6586e.png)

**Comment by jstockwin** [comment]
@perazzi Is this still an issue on the most recent version of keystone?

**Comment by Noviny** [comment]
Closing this as fixed.
