### ISSUE TITLE
Improve automated tests for Keystone

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#349]
We need to have a look at how to easily and automatically test Keystone so that changes and releases can be made with confidence across a wide number of use cases and configurations.

Some of the functionality can be covered by expanding the automated test coverage now that we have gulp and mocha / must integrated, and this will help considerably.

It might also, I think, be a good idea to set up a sample project (or two?) based on the yeoman generator that cover a wide range of route and model configurations, with test processes that will catch things that may be more difficult to cover using the automated keystone code tests, including the UI.

Any feedback or help getting this right would be welcome, it will be a really valuable addition to the project.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/improve-automated-tests-for-keystone
