### ISSUE TITLE
Relationships dropdown not displaying all elements

### ISSUE THREAD

**Issue by YouriSvahn** [keystonejs/keystone#3493]
Hi,

I'm a bit confused right now. I just noticed something weird, I don't know if it's specific to my case, or if it's "global".

I have a model `Partner` that I associate to events, I have around 100+ Partners added in Keystone at the moment. When I open the dropdown of an event to add some Partners (as shown [here](http://imgur.com/a/k8Gio)), only the 50 first Partners are showing, exactly how the first 50 are showing when I access my Partner model in the back office as you can see [here](http://imgur.com/a/ixaW6).

### Steps to reproduce the behavior

Add a relationship variable to an existent X model with the option `many: true`, populate the related relationship with 50+ items, try to access it via the relationship dropdown in the X model.

### Expected behavior

Shows the entire list of relationships.

### Actual behavior

Only shows the 50 first elements.

Thanks in advance and for the work you have done, I'm having a blast using KeystoneJS !

**Comment by YouriSvahn** [comment]
Little update : tried changing the `perPage` value in the List constructor changes nothing, I hoped it was related, but it's not.

**Comment by bradwbradw** [comment]
@YouriSvahn  I am seeing this happen.  Did you end up solving it?

**Comment by YouriSvahn** [comment]
IIRC, in the end it was the `perPage` value in fault, try changing it and tell me if it allows the admin to display more items.
