### ISSUE TITLE
App/site-wide Cloudinary image folder name

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#3504]
Is it possible to support specifying a folder name for all Cloudinary field types at the application level?

**Comment by danielmahon** [comment]
Yes, set config options `"cloudinary prefix": "folderName"` and `"cloudinary folders": true`.
See http://keystonejs.com/docs/configuration/#services-cloudinary

**Comment by danielmahon** [comment]
@JedWatson can be closed, trying to help you clean up issues ;)

**Comment by jstockwin** [comment]
Thanks @danielmahon
