### ISSUE TITLE
"Getting started" fails on nodeJS > v11, but does not state nodeJS <= v11 as a requirement

### ISSUE THREAD

**Issue by paigeweber13** [keystonejs/keystone#3506]
# Bug report

## Describe the bug

Inotify only supports NodeJS <= v11.x, inotify *seems* to be a dependency of KeystoneJS, but the ["Getting Started" document](https://github.com/keystonejs/keystone/blob/master/docs/quick-start/README.md) claims that KeystoneJS supports higher versions of NodeJS.

The "getting started" page says that Node.js >= 10.x is adequate, but any version >= 11.x fails. Furthermore, the example command output for `node --version` indicates that node  is at version 12.x (suggesting that this version should work), but that fails as well. I assume versions > 11.x are unsupported? If so, perhaps the documentation should mention that.

The problem seems to be with inotify. `npm i` ran fine, but when I tried `npm run dev`, node-gyp fails to build inotify. I finally fixed this problem by downgrading to node v11.x.

## To Reproduce

In my case, I used postgreSQL. I tried NodeJS versions v12.11.0 and v14.8.0, both of which failed.

To reproduce, follow the "getting started" document with a NodeJS version >= v12.x. In short, this means running `npm init keystone-app my-app`, setting up the database, and running `npm run dev`.

## Expected behaviour

I expect the app to be created successfully, allowing me to access an admin panel.

## System information

```
OS:              linux
Distributor ID:	 neon
Description:	 KDE neon User Edition 5.19
Release:	 18.04
Codename:	 bionic
kernel version:  Linux 5.4.0-42-generic x86_64
```

## Additional context

There is [an issue](https://github.com/c4milo/node-inotify/issues/75) open at node-inotify about this that provides more information on the inotify side of this error, but my primary concern is with the documentation. I feel that this should "just work" so that people new to this tool may get started easily.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
