### ISSUE TITLE
Add support for filtering by relationship fields in the admin UI

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#352]
Let's say you have a list posts with a related field author (that links to the authors list). Currently, the "simple search" functionality (#319) available from the admin UI won't dereference this relationship. So if you filter by "Jane" in the admin UI, you'll only get posts with "Jane" in the name, not posts where the author has "Jane" in their name.

Ideally, Keystone would be able to apply these "simple search" filters to related collections and apply them to items in the list being viewed.

Note, this functionality is closely related to, and dependant on, the "Implement configurable search fields" (#343) but is a distinct piece of work.

**Comment by MadeByMike** [comment]
From duplicate issue:

The queries for this kind of filtering already exist:

```graphql
query {
  allPosts(where: { author: { name_contains: "Jane" } }) {
    id
    title
  }
}
```

**Comment by gautamsi** [comment]
what about adding adminConfig item for search

here $search is predefined variable we document that someone has to use

```js
listConfig.adminConfig = { searchQuery: `query <name>($searchText: String!){all<Listname>s(where:{mycondition: $search}){<required fields can be filled by query builder based on view>}`}
```

or we just get the querybuilder based on variable name, 
```js
listConfig.adminConfig = { searchQuery: `{OR: [{field1: $search},{field2_contains: $search}]}` }
```

we will replace the where clause condition from this config value.

**Comment by gautamsi** [comment]
this way I can have it customised for each list.
