### ISSUE TITLE
TypeError: Cannot set property 'templateExt' of undefined - v4

### ISSUE THREAD

**Issue by jephjohnson** [keystonejs/keystone#3522]
When using handlebars with the latest beta, I keep getting the following error. 

"keystone.Email.defaults.templateExt = 'hbs';
                                    ^
TypeError: Cannot set property 'templateExt' of undefined
    at Object.<anonymous> (/Users/Jeff/Documents/heroku/keystones/keystone.js:54:37)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3"

I had to comment comment out the Email defaults to handlebars in 'keystone.js'
//keystone.Email.defaults.templateExt = 'hbs';
//keystone.Email.defaults.templateEngine = require('handlebars');

**Comment by weilitao** [comment]
I have the same problem, please fix that.

**Comment by Rumyra** [comment]
Exactly the same - did the same 'commenting out of lines' 😞

**Comment by luisnomad** [comment]
Same problem here. I tried installing the handlebars module manually, but the error doesn't go away

**Comment by rachelbasse** [comment]
> `keystone.Email` is now a separate package, `keystone-email`. You can remove that entire block of code from your `keystone.js` file! If you want to send emails, just `npm install --save keystone-email` and set it up as mentioned in the docs!
 -- [#222](https://github.com/keystonejs/generator-keystone/issues/222)

**Comment by Noviny** [comment]
Thanks @rachelbasse for your answer! Closing this issue. Please reopen if this does not solve it.
