### ISSUE TITLE
Multiple mutation graphql dose not work KeystoneJS

### ISSUE THREAD

**Issue by maheraldous** [keystonejs/keystone#3537]
I just started using Keystone and when I use this code below in the image, it work and create one user but as long I use the second code it won't work.
I want to create multiple mutation graphql

https://prnt.sc/u97b18

https://prnt.sc/u97bmq
https://prnt.sc/ukmj9q

This issue is closed in here [issue#562](https://github.com/keystonejs/keystone/issues/562#issue-389134930) but seems is not done yet.

**Comment by dylantmarsh** [comment]
You need to nest **data** again. The type `UserCreateInput` is wrapped by `UsersCreateInput`. I tested this and it works fine.

```
mutation createMultipleUsersAtOnce {
  createUsers(data: [
    {
      data: {
        name: "user1",
        email: "user1@test.com"
      }
    },
    {
      data: {
        name: "user2",
        email: "user2@test.com"
    	}
    }
  ]) {
    name
  }
}
```

**Comment by maheraldous** [comment]
Thank you
