### ISSUE TITLE
Cannot get Admin UI

### ISSUE THREAD

**Issue by isa98** [keystonejs/keystone#3552]
I have created keystone project.After starting this project i encountered with this error although i did everything according to the structure.Can anyone help me?

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

![keystone1](https://user-images.githubusercontent.com/57791323/91808932-17d62f00-ec46-11ea-8b6e-b50ade60f17c.png)

**Comment by Nikodermus** [comment]
How did you solve this? I'm experiencing it too, I get the following response in the terminal

```
{"level":30,"time":1610834538198,"pid":51181,"hostname":"nikodermus-mini.local","req":{"id":5,"method":"GET","url":"/__webpack_hmr","headers":{"host":"localhost:3000","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0","accept":"text/event-stream","accept-language":"en,es;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","referer":"http://localhost:3000/admin","cookie":"io=hXy10q7dGuB9heW0AAAA","pragma":"no-cache","cache-control":"no-cache"},"remoteAddress":"::ffff:127.0.0.1","remotePort":54836},"res":{"statusCode":404,"headers":{"x-powered-by":"Express","x-keystone-app-version":"1.0.0","vary":"Origin","access-control-allow-credentials":"true","content-security-policy":"default-src 'none'","x-content-type-options":"nosniff","content-type":"text/html; charset=utf-8","content-length":152}},"responseTime":0,"msg":"request completed"}
```
