### ISSUE TITLE
Documentation: There is no description about "TextArray" Type.

### ISSUE THREAD

**Issue by starcharles** [keystonejs/keystone#3562]
Thanks for your great job!! I'm using keystone.js as a part of new product.

I found that there is no explains about "TextArray"(or NumberArray) type in the model.
[http://keystonejs.com/docs/database/](http://keystonejs.com/docs/database/
)

Is there any mentions about this type elsewhere? if so, add link seems to be better.

**Comment by Noviny** [comment]
Currently, the most up to date documentation on field types is in the repo itself. Here's a link to the text array documentation.

https://github.com/keystonejs/keystone/tree/master/fields/types/textarray

Text Array is a new field type and its documentation should make it to the website soon.

**Comment by starcharles** [comment]
@Noviny Thanks for your reply! yes, I found the docs in the repository. If documentation is maintained on the github, I could write description about types and send PRs.
Anyway , I understand the website is also under updating.

Thanks.
