### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by rturk** [keystonejs/keystone#3565]
### Steps to reproduce the behavior

Upgrade to lastest beta (4)
### Expected behavior

Admin  to work as expected
### Actual behavior

Receive Cannot read property 'id' of undefined error message, can't login to admin

**Comment by AurelioDeRosa** [comment]
Have you tried with a fresh installation of beta-4? If you're using a previous code base, can you give some details about what you have at the moment?

**Comment by mrpatiwi** [comment]
I'm getting this error:
```
Error thrown for request: /keystone/signin
TypeError: Cannot read property 'id' of undefined
```

on:
```
/node_modules/keystone/admin/server/routes/index.js:39:16
```

Clean Beta 5 install

**Comment by mrpatiwi** [comment]
Fixed, I was missing `auth: true` in the config object

**Comment by bassjacob** [comment]
Hi @rturk, I'm going to close this due to inactivity. If this is still an issue feel free to reopen.

**Comment by OskarKlintrot** [comment]
I get this as well with `auth: false`, shouldn't that open up Keystone to the public?

**Comment by sharkattackhq** [comment]
@OskarKlintrot did you find a solution to this? I'm having the same issue trying to integrate Keystone into an existing express app.

**Comment by OskarKlintrot** [comment]
I barely remember what this was about now but I remember hacking with the hooks to be able to integrate Keystone with LDAP/Exchange. I think I did something like adding the user on the first login and then to login the user I used the pre hook to validate the user, then reset the password for the user in Keystone and then login the user with that new password. 

I think this could be helpful: https://github.com/Certaincy/intranet-abandoned/tree/master/keystone/src/auth
