### ISSUE TITLE
regex not work in query of Keystonejs

### ISSUE THREAD

**Issue by playwolf719** [keystonejs/keystone#3566]
### Steps to reproduce the behavior

`

		if(req.body.search_word) {
  			console.log("good");
  			console.log(req.body.search_word);
  			var regex = new RegExp('/'+req.query.search_word+'/','i');
			q.where('name',regex);
		}

		q.exec(function (err, results) {
			// console.log(results);
			locals.data.movies = results;
			next(err);
		});

`
### Expected behavior
get result
### Actual behavior
no result

**Comment by binhwpo** [comment]
Hello @playwolf719 . I'm having this same problem. Could you please tell how did you solve it? Thanks!
