### ISSUE TITLE
Image API similar to current StorageAPI

### ISSUE THREAD

**Issue by arturkasperek** [keystonejs/keystone#3567]
In now moment when I want to make field with multiple images I am forced to use cloudinary. Is there a way to use amazon s3 as a image hosting?

**Comment by christroutner** [comment]
Here is a guide on creating a File or Image API for local hosting:

https://github.com/keystonejs/keystone/blob/master/docs/guides/API-File-Image-Uploads.md

**Comment by arturkasperek** [comment]
Ok, but I need this feature in keystone admin panel, I got couple CloudinaryImages fields and I want make migration to amazon cloudfront. For now moment the quickest solution is implementing new field in keystone cold amazonImages

**Comment by Noviny** [comment]
For S3, we recommend using the [File](https://github.com/keystonejs/keystone/tree/master/fields/types/file) type, along with our [s3-storage-adapter](https://github.com/keystonejs/keystone-storage-adapter-s3).

There isn't currently a way to create a single field that accepts multiple files yet, however I believe #3776 should resolve that concern once it lands.

Until then, a model for holding the images with a relationship to where you want the image stored is the easiest method to get this implementation.

Closing this as an issue. Let me know if this isn't what you're looking for.
