### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by LegitTalon** [keystonejs/keystone#357]
- guide to installing locally
- tests
  - writing
  - running
- commit message conventions
- guide to submitting bugs
  - responsible disclosure of security holes

add other important contributing topics below

**Comment by tivac** [comment]
This was fixed in https://github.com/keystonejs/keystone/commit/52017b3d4379bb3d8c7e4b21ae807ffeba2eac09

**Comment by morenoh149** [comment]
nice
