### ISSUE TITLE
Saving TextArray fields with noedit: true loses data

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#3575]
### Steps to reproduce the behavior

View the details screen in the Admin UI for an item with a `TextArray` field that _contains data_ and has the `noedit: true` option set. Save the item.
### Expected behavior

The existing value should be kept
### Actual behavior

The existing value is removed
### Explanation & Fix

I _think_ what's going on here is that we're not ignoring `noedit` fields in the default configuration when `List.updateItem` is called. Because in HTML forms, submitting no fields implies you've deleted all the items in the array, the value is cleared.

We can resolve this by ignoring `noedit` fields by default in the `UpdateItem` method.

**Comment by Noviny** [comment]
You mean ignore it by default just for `TextArrays`?

**Comment by jossmac** [comment]
@JedWatson heads up - this is also true of `Types.Relationship`
