### ISSUE TITLE
Add WEBP images support

### ISSUE THREAD

**Issue by PoluosmakAndrew** [keystonejs/keystone#358]
Please add by default WEBP header "image/webp" for CloudinaryImage.

ui-cloudinaryimage.js and ui-cloudinaryimages.js

Thanks :-)

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/add-webp-images-support
