### ISSUE TITLE
Nunjucks doesn't work with default config

### ISSUE THREAD

**Issue by Tyguy7** [keystonejs/keystone#3589]
### Steps to reproduce the behavior

run yo keystone
select nunjucks as the template engine
run the server
load localhost:3000 in a browser
### Expected behavior

home page loads
### Actual behavior

500 error is displayed with "template not found: layouts/default.html"

**Comment by brianjd** [comment]
I've experienced the same.  It is possibly related to this [issue](https://github.com/tj/consolidate.js/issues/241). But I didn't have time to fully run it down at the time, so I ended bypassing by creating a Nunjucks instance directly and passing it to Keystone.

**Comment by niftylettuce** [comment]
should be ok now, you can close this, use `consolidate.js@v.0.14.2`

**Comment by LucienBrule** [comment]
This is still an issue in the latest release. I encountered this after running the yeoman generator today.

**Comment by Noviny** [comment]
Hi all, this is an issue in the keystone generator, and is better reported there. As it has since been resolved in the latest version which also updates to Keystone 4, I am closing this as resolved.
