### ISSUE TITLE
Running Out of Memory on Small Servers

### ISSUE THREAD

**Issue by christroutner** [keystonejs/keystone#3609]
I recently upgraded a KeystoneJS install to commit 17e359b434bd155fc0b6bc227cf65f9040d0a42b and keystone is getting killed by the Linux OS for running out of memory. I've been running is successfully on a small Digital Ocean $5 Droplet with 512MB memory before this. Here is a pastebin of my output showing my current commit installation and the out of memory error: 
http://pastebin.com/bdNU8re6

Is this a concern to the project? Why is KeystoneJS growing larger? 

Are there any benchmarks for memory usage of previous versions? 

Is there a memory usage target for v4.0?

**Comment by jstockwin** [comment]
@christroutner I think that's just the nature of node. 

I run keystone on $5 DO droplets, you just need to add some SWAP.
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by christroutner** [comment]
Great tip, @jstockwin. Thanks!

**Comment by peterpme** [comment]
Hey @christroutner,

SWAP files are cool, but you might be able to get away with compiler flags. Compiler flags allow you to optimize your application for your environment.

Node uses a very lazy and greedy garbage collector.

For a 512mb digital ocean box, you can try running the following:

```bash
node --optimize_for_size --max_old_space_size=460 --gc_interval=100 keystone.js
```

**Comment by abale** [comment]
Another suggestion that can work with either suggestion above is using a nodejs process manager (good practice anyway) such as https://github.com/Unitech/pm2 which can trigger a restart if memory usage goes over a specified size.  This can help with memory leaks.  It can also help you keep totals (and logs) of how many times this has happened.

**Comment by mhoffmeyerDC** [comment]
Using a caching reverse proxy can ease the CPU and memory load too! I did it with keystone and Nginx. Example [nginx.conf](https://gist.github.com/mhoffmeyerDC/3a139d612e2ea3635d0a836a0546832d), also see [Nginx Caching Guide](https://www.nginx.com/blog/nginx-caching-guide/).

**Comment by htor** [comment]
Enabling swap is always a good idea on low-memory boxes. Also, make sure you run node with `NODE_ENV=production node keystone.js` and disable in-memory session storage with `keystone.set('session store', 'mongo');` in `keystone.js`.

**Comment by jstockwin** [comment]
Since this isn't really a keystone issue, I'm going to close it to keep the tracker unpolluted. 
Thanks for all the contributions though - hopefully people will find this helpful!
