### ISSUE TITLE
pug engine is not found

### ISSUE THREAD

**Issue by jjhesk** [keystonejs/keystone#3610]
Athough I have declare the pug engine at the `package.json` and I still found this error.

Error thrown for request: /
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

This is the setup at the `keystone.init({...});`

```
"less": "public",

 "views": "templates/views",
  "view engine": "pug",
  "emails": "templates/emails",

```

**Comment by w01fgang** [comment]
@jjhesk the default engine is `jade`, so to use `pug` you need to set `custom engine` option.
I think like this:
```
'view engine': 'pug',
'custom engine': require('pug').__express,
```

**Comment by jstockwin** [comment]
@jjhesk Since you've had a response, and haven't said this is still not working, I'm going to close this. 
Let us know if you still need help though!
