### ISSUE TITLE
Keystone doesn't work with server side react-router

### ISSUE THREAD

**Issue by ryanaleksander** [keystonejs/keystone#3618]
My apology for posting this here, but I can't find the answer myself, and stackoverflow doesn't help either, and I'm kind of short on time. My problem is described in the link below.
http://stackoverflow.com/questions/40091086/cant-integrate-keystonejs-into-express-using-server-side-react-router

Any help would be appreciated. Again, I'm very sorry for the inconvenience.

**Comment by internetErik** [comment]
Sorry I didn't see this issue earlier. Hope I can still help, or help somebody else

There is a an attempt at solving this in the list of keystonejs repos that may give you a start could could be out of date:  https://github.com/keystonejs/universal-keystone-boilerplate

I've made some boilerplate recently that can get you started too:
https://github.com/internetErik/keystone-hbs-universal-react (uses keystone 0.3.x)
https://github.com/internetErik/keystone4-universal-react (uses keystone 0.4.x beta)

you'll want to look at redux-connect (https://github.com/makeomatic/redux-connect) for the async data loading 

I have a client project that I'm working on that also preloads the data from mongo so you don't need to just bring it in through api calls, but I need to move that over to the boilerplate.

**Comment by bassjacob** [comment]
Hi @ryanaleksander, I'm going to close this due to inactivity. Please reopen this if it's still an issue.
