### ISSUE TITLE
Field type code does not respect noedit: true 

### ISSUE THREAD

**Issue by mrprkr** [keystonejs/keystone#3619]
When trying to use a code field to display json data, the editor is still available even with `noedit: true`.
### Steps to reproduce the behaviour

Set option `noedit: true` on field type code. Replicated on 0.3.19 and 4.0.0b3
### Expected behaviour

Field type to be uneditable 
### Actual behaviour

Field type is still editable

**Comment by AurelioDeRosa** [comment]
The issue is no longer present in beta-4.

**Comment by jstockwin** [comment]
@mrprkr Can you confirm that this is now fixed, and if so close this issue? Thanks!

**Comment by mrprkr** [comment]
@jstockwin all good for me now.
