### ISSUE TITLE
Hi,  How I can use field Types.File for multiple files upload feature?

### ISSUE THREAD

**Issue by Herman-Scheer** [keystonejs/keystone#3620]

**Comment by fxp** [comment]
This there a Types.File exists?  @Herman-Scheer

**Comment by christroutner** [comment]
This guide might help you:

https://github.com/keystonejs/keystone/blob/master/docs/guides/API-File-Image-Uploads.md

FYI, this is a more appropriate question for the mailing list:
https://groups.google.com/forum/#!forum/keystonejs
