### ISSUE TITLE
Dynamically constructing field values

### ISSUE THREAD

**Issue by stelio** [keystonejs/keystone#3625]
I was hoping to dynamically construct links in the Admin UI using virtuals, but it seems that the Admin UI doesn't like preformatted HTML

```
var keystone = require('keystone'),
    Types = keystone.Field.Types;

var Producer = new keystone.List('Producers', {
    schema: {collection: 'producers'},
    map: {name: 'name'},
    searchFields: 'name, code',
    path: 'producers',
    label: 'Producers',
    singular: 'Producer',
    plural: 'Producers',
    nodelete: true,
    nocreate: false
});

Producer.add({
    code: {type: String, unique: true},
    name: {type: String},
        portalComplete: {type: Boolean}
});

Producer.schema.virtual('portal').get(function () {
    return '<a href=#>http://localhost/producer/' + this._id +'</a>';
});

Producer.defaultColumns = '_id, code, name, portal, portalComplete';
Producer.register();
```

The Admin UI is encoding the results instead of displaying the plain HTML, is there a way to disable this?

**Comment by SHBelsky** [comment]
Instead of returning the entire link, I normally just construct the URL as if it were to be input directly into an existing anchor tag. Instead of having the function generate an anchor tag, I generate what the `href` property would be, and then use my own anchor tag. I would assume HTML is escaped for the purposes of sanitation and security.

In your example...

Model:
```
Producer.schema.virtual('portal').get(function () {
    return '/producer/' + this._id;
});
```

HTML (if you've passed the entire Producer to your HTML template). I'm assuming you're using Handlebars from the syntax of your existing function.
```
<a href="{{producer.portal}}">{{producer.portal}}</a>
```

**Comment by jstockwin** [comment]
@stelio Was the above sufficient to answer your question, and if so can we close this?

**Comment by jacqueslareau** [comment]
@SHBelsky What about displaying the link inside the Admin UI?
It's kinda the same problem with file uploads. We see there is a file but no download/view links.

**Comment by SHBelsky** [comment]
I don't think that can be done within the Admin UI. Virtuals and the like are a function of Mongoose, not Keystone. You could potentially populate a field with the result of a function that runs every time the document is updated, so it's *sort of* as if the field was a direct reference to the virtual even though it really isn't.

```
YOURMODELHERE.add({
   yourfield: { type: String }
});

YOURMODELHERE.schema.pre('save', function(next) {
// If you only want to run this function if this is a brand new document, include this function.
// If not, you can remove it and the encapsulating if statement from the next function.
   this.wasNew = this.isNew;
   next();
});
YOURMODELHERE.schema.post('save', function () {
   if (this.wasNew) {
      // Run a function here which creates some data for a field you want to be able to see in the adminUI
      this.yourfield = yourvar;
      this.save(function (err) {
         if (err) console.log(err);
       });
});
```

**Comment by Noviny** [comment]
For the reasons discussed above, we're not keen on making it easy to insert arbitrary html, as it opens you up to some big security concerns.

Closing this as an issue, as several workarounds have been provided, and this is not something we will likely look to change.
