### ISSUE TITLE
Admin UI: packages.js:165 Uncaught SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by joeinnes** [keystonejs/keystone#3642]
### Steps to reproduce the behavior

Attempt to access the signin page for the admin backend
### Expected behavior

Signin page loads, I can log in
### Actual behavior

Sign in page fails to load. There seems to be some kind of problem in the 'packages.js' file. Then, react fails to load, which prevents the page from ever displaying. I guess the reason react fails to load is because of the problem in the packages file. The line in question is 165.

`e&&!this.isSetUp?(this.backend.setup(),this.isSetUp=!0):!e&&this.isSetUp&&(this.backend.teardown(),this.isSetUp=!1)},e.prototype.getMonitor=function(){return this.monitor},e.prototype.getBackend=function(){return this.backend},e.prototype.getRegistry=function(){return this.registry},e.prototype.getActions=function(){function e(e){return function(){var r=e.apply(t,arguments)"undefined"!=typeof r&&n(r)}}var t=this,n=this.store.dispatch
`

In particular, it's the 'undefined' that it doesn't like.
### System Details

I'm on OSX, issue occurring in Chrome Version 54.0.2840.71 (64-bit) & Safari.
### What I've tried
- I tried with a couple of browsers
- I deleted the node_modules directory and reran npm install to clean install the version I of Keystone I was on
- I changed the version of keystone up to '4.0.0-beta.3'
- I changed the version of keystone down to '4.0.0-beta.1'

You should be able to see the problem here: https://done.joeinn.es/keystone/signin

**Comment by conrad-vanl** [comment]
I'm getting this issue as well, what's strange is I'm not getting the issue locally, just on the deployed app on heroku.

**Comment by jstockwin** [comment]
@joeinnes This seems to be working fine now? Did you manage to fix it? What was the issue?

**Comment by joeinnes** [comment]
No idea, just started working all on its own, I didn't touch it :S

**Comment by jstockwin** [comment]
Alright, well as long as it's working I'll close this.

**Comment by jjhesk** [comment]
looks like i have the same issue with this 4.0.0-beta5 deploy @jstockwin @joeinnes @conrad-vanl
