### ISSUE TITLE
Cannot overwrite model once compiled issue

### ISSUE THREAD

**Issue by hellopath** [keystonejs/keystone#3645]
Hi there,

I can't get rid of 
`throw new mongoose.Error.OverwriteModelError(name);
      ^
OverwriteModelError: Cannot overwrite `About` model once compiled.`

Locally on my machine is working fine but on production I have that error.
I tried from `About.js` model to call the `removeModel.js` as you suggest [here](https://github.com/keystonejs/keystone/wiki/Unregister-a-Mongoose-Model) like that

```
var keystone = require('keystone');
var Types = keystone.Field.Types;
var removeModel = require('../utils/remove-model')

var About = new keystone.List('About', {
    label: 'About',
    nocreate: true,
    nodelete: true
});

removeModel(About)

About.add({
    profile : { type: Types.Html, wysiwyg: true, height: 250},
    twitter : { type: Types.Url, default : 'Add twitter link' },
    instagram : { type: Types.Url, default : 'Add instagram link' },
    adresse : { type: Types.Html, wysiwyg: true, height: 150},
})

About.register();
```

but with no luck. 
I also tried to drop the database but still nothing. 
Is there anyway to deep clean the Mongoose models? Don't know if something like that is possible.

Thanks for your help

Production server infos:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:    8.6
Codename:   jessie
Node: v6.8.1
Keystone.js: 0.3.22
```

**Comment by luisnomad** [comment]
Same happening here. Where you able to solve this, @hellopath ?

**Comment by creynders** [comment]
Are you sure the About model file isn't required twice on production? That would lead to this error too.

**Comment by hellopath** [comment]
@luisnomad @creynders I couldn't find a solution. I started from a fresh new server instance and it worked. Also it came up that the problematic server was with no space left. I have no idea if it's something to do with.

**Comment by jithumohandas** [comment]
When you initialize the model, use this approach, this might help in resolving the problem

try {
  UserSchema = mongoose.model('User', userSchema);
} catch (e) {
  UserSchema = mongoose.model('User');
}

export {
  UserSchema
};

**Comment by luc-steffens-2014** [comment]
For one-line lovers and avoiding throwing things arround :-) 

`UserSchema = mongoose.modelNames().indexOf('User') < -1 ?  mongoose.model('User', userSchema) : mongoose.model('User')`
