### ISSUE TITLE
Proposal for array type

### ISSUE THREAD

**Issue by cloudever** [keystonejs/keystone#3646]
Recently I've started develop new project, simple eshop.
I've reviewed several solutions including KeystoneJS.
I needed to create arrays of any field type like it's in mongoose using [ ]  
`type: [String]`

As I saw it is unpossible in the KeystoneJS.
Similar solution exist in the [formage](https://github.com/node4good/formage) (on the screenshot).
I propose to add this feature to develop using keystone more great. Thanks.
![1](https://cloud.githubusercontent.com/assets/16993305/19776231/e328031e-9c7b-11e6-8a84-445417b8fb35.png)

**Comment by jossmac** [comment]
Please see #153 and #257

**Comment by jossmac** [comment]
@cloudever we're also very keen to see this feature in Keystone. A lot of the work has already been done and will likely land in an upcoming 4.0 Beta or RC release.

Also, it's worth mentioning that we're trying to keep the issue tracker unpolluted. If you have another feature request please add it on https://productpains.com/product/keystonejs

Thanks!
