### ISSUE TITLE
yo keystone command not found

### ISSUE THREAD

**Issue by jeroenouw** [keystonejs/keystone#3651]
### Steps to reproduce the behavior

I'm new to Keystone so I wanted to try, first thing is going to getting started on their website. After the first command:
`npm install -g generator-keystone`

Then I was changing the directory and after that I wanted to run the generator with yo keystone, but it didn't work. It gave the following:

```
$ yo keystone
bash: yo: command not found
```

What am I doing wrong
### Expected behavior

That it found the yo command.
### Actual behavior

```
$ yo keystone
bash: yo: command not found
```

**Comment by LorbusChris** [comment]
You need to install yo first in order to use yeoman generators
`npm i -g yo`

**Comment by jeroenouw** [comment]
@LorbusChris Thanks! Seems logic now.

**Comment by Ragzzy-R** [comment]
would be nice if its specified in the docs. I was thinking that generator will itself install yeoman

**Comment by Noviny** [comment]
@Ragzzy-R Our new docs findable [here](http://keystonejs.netlify.com/getting-started/yo-generator) are clearer about this process, but we haven't switched the website over.
