### ISSUE TITLE
Admin API: Nested Objects Not Accessible On Returned Lists

### ISSUE THREAD

**Issue by christroutner** [keystonejs/keystone#3652]
### Steps to reproduce the behavior

This issue uses the Post model as an example, but the issue affects any List model with a nested object. Any List model with a nested object returns values with the Admin API that are inaccessible. The Post model that comes with the yeoman generator is a perfect example. Here is the models/Post.js code:

```
var keystone = require('keystone');
var Types = keystone.Field.Types;


/**
 * Post Model
 * ==========
 */

var Post = new keystone.List('Post', {
        map: { name: 'title' },
        autokey: { path: 'slug', from: 'title', unique: true },
});

Post.add({
        title: { type: String, required: true },
        state: { type: Types.Select, options: 'draft, published, archived', default: 'draft', index: true },
        author: { type: Types.Relationship, ref: 'User', index: true },
        publishedDate: { type: Types.Date, index: true, dependsOn: { state: 'published' } },
        image: { type: Types.CloudinaryImage },
        content: {
                brief: { type: Types.Html, wysiwyg: true, height: 150 },
                extended: { type: Types.Html, wysiwyg: true, height: 400 },
        },
        categories: { type: Types.Relationship, ref: 'PostCategory', many: true },
});

Post.schema.virtual('content.full').get(function () {
        return this.content.extended || this.content.brief;
});

Post.defaultColumns = 'title, state|20%, author|20%, publishedDate|20%';
Post.register();
```

The nested object in that example is the `content` object. It nests the `brief` and `extended` objects.

**Steps to Reproduce:**
1. Start a working copy of KeystoneJS with the Post.js model loaded.
2. Install the csrf.js file from issue #3420 to get the Admin API to work.
3. Create a test Post in the Admin API
4. Use the Admin API to GET the posts in the system. Here is some example code you can run from the JavaScript console in a browser like Chrome or Firefox:
   `$.get('/keystone/api/Post/', '', function(data) {debugger;})`
5. Look at the returned value. Here is the output from Chrome dev tools:

![image](https://cloud.githubusercontent.com/assets/9870991/19839093/5fb28278-9e99-11e6-9fa9-059ac3425c25.png)

In this example, a call to `/keystone/api/Posts` returns 4 results. Notice that trying to access `data.results[0].fields.content` returns undefined. Trying to access `data.results[0].fields.content.extended` returns an error. 
### Expected behavior

Nested objects should be accessible with the standard 'dot' notation.
### Actual behavior

Nested objects inside of List models are inaccessible with standard 'dot' notation.

**Comment by abale** [comment]
data.results[0].fields["content.extended"] works ok?

**Comment by christroutner** [comment]
Yes, that does work. I didn't even know it was possible to reference a nested object that way.

**Comment by abale** [comment]
it is because the object is not actually parsed into nested object, it is string-literal (flattened dot notation).

Changing this in the way this method works might break things for any users who have already integrated it as-is.

**Comment by wmertens** [comment]
Yes, this is intended behavior. I am closing this issue.
