### ISSUE TITLE
Error when npm install kerberos@0.0.21 

### ISSUE THREAD

**Issue by q4w56** [keystonejs/keystone#3657]
### Steps to reproduce the behavior
`npm install keystone@4.0.0-beta.3`

or
`npm install kerberos@0.0.21` 

### Actual behavior
make error.
This issue is in kerberos@0.0.21
issue: https://github.com/christkv/kerberos/issues/21
The ubuntu users have to run `sudo apt-get install libkrb5-dev` to solve this issue.

**Comment by jstockwin** [comment]
@q4w56 The issue on kerberos is marked as closed, although as you say it looks as though you have to run that command to get it to work. 

It doesn't sound like there's much that Keystone can do to fix this from our end, so I'm going to close this. Let me know if I'm misunderstanding though!
