### ISSUE TITLE
Add imgur support

### ISSUE THREAD

**Issue by LabLayers** [keystonejs/keystone#367]
I would also love to see support for imgur. They have a straightforward API and they don't have any set pageview limits - it's purely unlimited as long as the image is seen once every 6 months.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/add-imgur-support
