### ISSUE TITLE
Roxy Fileman - a file browser

### ISSUE THREAD

**Issue by jdnichollsc** [keystonejs/keystone#3677]
Hi guys,

What do you think about to use my **Roxy Fileman** integration with **Node.js**?

https://github.com/jdnichollsc/Roxy-Fileman-for-Node.js

Regards, Nicholls

**Comment by jstockwin** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
