### ISSUE TITLE
[0.4] json download fails

### ISSUE THREAD

**Issue by matogertel** [keystonejs/keystone#3680]
### Steps to reproduce the behavior

In the admin list view, the new download button has 2 format options: csv and json. When choosing json,  the download fails. In the console, you see a mongoose error:

`Mongoose model 'error' event fired on 'Post' with error:
 List.getData: fields must be undefined, a string, or an array. Error: List.getData: fields must be undefined, a string, or an array.`

Tested on the syd-js sample site with the latest keystone (mongoose 4.6.6), but also reproduced in my own sites using the latest keystone beta.

### Expected behavior

A json file

### Actual behavior

Nothing

**Comment by KirAndStas** [comment]
I have the same issue.

**Comment by LorbusChris** [comment]
Just guessing, but you might have to use [model-transform](https://github.com/JedWatson/model-transform) on your keystone models.

**Comment by cavilaho** [comment]
Resolved on #3959.

**Comment by jstockwin** [comment]
Nice. I'll close this issue then, and everyone should pull down that fix. Feel free to re-open if you're still having issues.

**Comment by MillerApps** [comment]
This is happening on version 4.0.0-beta.5, wasn't this already fixed?

**Comment by deyanskiq** [comment]
What is the fix for this issue?  I'm using 4.0.0-beta.5 version.
