### ISSUE TITLE
Requesting npm version bump for 4.0.0 beta

### ISSUE THREAD

**Issue by funklos** [keystonejs/keystone#3685]
Hello,

we ran into the same issue as #3545, for which a pr #3569 has already been merged.
As we use keystone via npm there is currently no possibility for us to profit from the fix, since the version number has not been bumped since.

Could you please release a new npm version?

**Comment by JedWatson** [comment]
Sorry for the delay @funklos - I'll get a new version published this weekend.

**Comment by jstockwin** [comment]
Keystone 4.0.0-beta.4 was released a week ago, so I'm marking this as closed. Thanks @JedWatson!
