### ISSUE TITLE
fallback or enhanced error description for missing 'user model' option

### ISSUE THREAD

**Issue by joernroeder** [keystonejs/keystone#3691]
I forgot to set the `user model` option on `keystone.init` and it took me a while to figure this out as the error returned from the route wasn't very specific.

```
Error thrown for request: /keystone/
ReferenceError: Unknown keystone list undefined
```

I would suggest to throw a specific error in the router around https://github.com/keystonejs/keystone/blob/master/admin/server/routes/index.js#L14

```javascript
var userModel = keystone.get('user model');

if (!userModel) {
  throw new ReferenceError('Unspecified user model. See http://keystonejs.com/docs/configuration/#options-database for more information.');
}
var UserList = keystone.list(userModel);
```

Let me know what you think, i'll submit a pull request if you like :)

**Comment by bassjacob** [comment]
I like the idea, but I wonder if it would make more sense to surface this in  https://github.com/keystonejs/keystone/blob/master/lib/core/options.js#L109 ? That way either the fallback or the error is closer to the config initialisation. @JedWatson is there a set of fields outside of the user model that keystone cannot function without?

**Comment by joernroeder** [comment]
@bassjacob i thought about the `.options` as well but i didn't find a good "injection point" for the warning/error without making an abstract  function like `.options` more specific by adding an extra check. At the moment `keystone.get` is equal to `keystone.set` (which is pretty specific at the moment as it sets every option differently) and it just returns the value stored under the given key [options.js#L24](https://github.com/keystonejs/keystone/blob/master/lib/core/options.js#L24).

By switching over the given key similar to the switch in the setter logic would keep all key specific implementation behaviour in one function – or at least on a central location.

```javascript
if (arguments.length === 1) {
  switch (key) {
    case 'user model':
      if (!this._options[key]) {
        throw new ReferenceError('Unspecified user model. See http://keystonejs.com/docs/configuration/#options-database for more information.');
      }
      break;
  }

  return this._options[key];
}
```

**Comment by Noviny** [comment]
Closing this as part of issue triage, but agree that a PR for better error messaging around this would be nice.
