### ISSUE TITLE
Admin UI: Switching page to referenced model calls false API route

### ISSUE THREAD

**Issue by xenurec** [keystonejs/keystone#3695]
### Steps to reproduce the behavior

Keystone version: 4.0.0-beta.1 / 4.0.0-beta.3

1. Open list view for model with fields referencing other models and displaying them as "defaultColumns" (e.g.: Comments referencing Author on http://demo.keystonejs.com/keystone/post-comments)
2. Click on referenced Model in list view (e.g.: author "1221 22" on http://demo.keystonejs.com/keystone/post-comments)

### Expected behavior
Should display detail view of model clicked at.

### Actual behavior
"Error!" output.
Opens correct URL: http://demo.keystonejs.com/keystone/users/5799a396ae8de803007e8ebb
Calls false API route resulting in 404 error: http://demo.keystonejs.com/keystone/api/post-comments/5799a396ae8de803007e8ebb?drilldown=true

**Comment by Noviny** [comment]
@xenurec Using the demo site (now on beta 5), I did not encounter this error. I'm going to close this as an issue, but if you are still experiencing this, let me know.

**Comment by xenurec** [comment]
Yes, it seems to be fixed somehow. Thanks for looking into it.
