### ISSUE TITLE
Admin UI: Text of a textarea overflows the field

### ISSUE THREAD

**Issue by AurelioDeRosa** [keystonejs/keystone#3712]
### Steps to reproduce the behavior

1. Create a `noedit` model with a `textarea` field
2. Save a new entry for the model
3. Show the entry in the admin UI

### Expected behavior

View the whole text of the textarea within a (perhaps scrollable) field

### Actual behavior

The text of the `textarea` overflows the field, overlapping with other text (see image below).

![issue](https://cloud.githubusercontent.com/assets/1430979/20387837/f27b87ac-acb9-11e6-9ef2-0b46e87ffae0.jpg)

**Comment by Noviny** [comment]
Closing this as resolved by #3888. Treating the modals as a separate issue.

Thanks for helping with this @AurelioDeRosa!
