### ISSUE TITLE
Allow "offline" page to be displayed when MongoDB is unavailable

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#372]
As suggested on the Google Group: https://groups.google.com/forum/#!msg/keystonejs/bAgE3JdfQf4/dTKtdT496oEJ

We could add a setting that would display a specific template when MongoDB is unavailable rather than bailing on the process.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/allow-offline-page-to-be-displayed-when-mongodb-is-unavailable
