### ISSUE TITLE
500 Error During CRUD

### ISSUE THREAD

**Issue by mikelunn** [keystonejs/keystone#3735]
### Steps to reproduce the behavior

1. Access Demo [Keystone Demo](http://demo.keystonejs.com/)

1. Log into Admin UI

1. Access any top level model (for instance Posts)

1. Delete a Post

1. Create a Post

### Expected behavior
Post should be created without error.

### Actual behavior
For some reason an unknown error (500 Internal Server Error) is being thrown. This only occurs when a create is made after a delete request. The issue does not occur if full page refresh occurs after delete.

**Comment by mikelunn** [comment]
Sorry this is a duplicate of issue #3545

**Comment by mikelunn** [comment]
It seems the bug found it's way back into 4.0.0-beta.3.

**Comment by jstockwin** [comment]
@mikelunn The issue was in beta.3 in the first place. It was fixed but took a little while to be published (as beta.4). 

It should be fixed in beta.4. If not, please pick this back up in #3545. Thanks!
