### ISSUE TITLE
Run without database

### ISSUE THREAD

**Issue by Pinpickle** [keystonejs/keystone#375]
I want to use Keystone now when I am setting up really simple websites that don't require a database (but do need some logic in the back end), because I love the way it sets everything up.

Currently I don't think it is possible, but I feel as though it wouldn't be too hard to implement given that in this no DB mode, the admin UI is also disabled.

**Comment by dcousens** [comment]
Cool post @frederik,  closing this issue as it can clearly be done.

**Comment by JedWatson** [comment]
correct @dcousens, thanks
