### ISSUE TITLE
`jade` to `pug` deprecation

### ISSUE THREAD

**Issue by VINTproYKT** [keystonejs/keystone#3751]
### Steps to reproduce the behavior
Install Keystone through `generator-keystone`.
### Expected behavior
No deprecation warnings expected before I've seen that `jade` actually is renamed to `pug`.
### Actual behavior
```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

**Comment by pll33** [comment]
keystonejs/generator-keystone#169

**Comment by jstockwin** [comment]
Neither jade nor pug are still explicitly required by keystone itself, so this should be tracked by the issue on generator-keystone as mentioned above. As such, I'm going to close this.
