### ISSUE TITLE
Html field in admin UI not always renders

### ISSUE THREAD

**Issue by Infonautica** [keystonejs/keystone#3752]
### Steps to reproduce the behavior
Create HTML-field in UI, with those options:

```js
ProdQuote.add({
	text: { type: Types.Html, wysiwyg: true, label: 'Текст', default: '<p>Нет такого проекта в России, который мы не смогли бы реализовать...</p>' }
});
```

### Expected behavior
I expect to use html-field in admin UI :D

### Actual behavior
Field not always visible, it's not rendered. Screenshot:
https://gyazo.com/4b15d3103dfdf5e8fcdf7b1894a15a5a
Console log:
https://gyazo.com/e1616fcbe2b77378964a51b0e0dd0539

P.S. This is, actually, the only problem i find in this beta. If you need more info just ask

**Comment by AurelioDeRosa** [comment]
I'm experiencing this issue very often.

**Comment by lglossman** [comment]
+1

**Comment by peterpme** [comment]
I've been getting this error in console: (4.0.0-beta.5)
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by ghuroo** [comment]
check, happens to me too quite often.
I always need to reload the page.

**Comment by Noviny** [comment]
@peterpme I think the problem you are experiencing is actually the one over on #3529.

@Infonautica @ghuroo, From what I understand this problem occurs sometimes but not all the time. Can you get a case that reproduces it 100% of the time?

[Linking](https://github.com/tinymce/tinymce/issues/2319) to an issue on tinyMCE that seems relevant.

**Comment by Noviny** [comment]
Closing this as we haven't got the ability to reproduce. Going to favour other existing open issues.
