### ISSUE TITLE
Wrap keystone.render() with try/catch

### ISSUE THREAD

**Issue by remnev** [keystonejs/keystone#376]
Hi! I often take an error when I surf the Admin UI. It looks like:
```
/www/solutionit.ru/node_modules/keystone/index.js:919
				throw (e);
				       ^
TypeError: path-to-site/node_modules/keystone/templates/views/list.jade:392
    390| 			tbody
    391| 				each item in items.results
  > 392| 					tr(id=item.id)
    393| 						if !list.get('nodelete')
    394| 							td.control: a(href='/keystone/' + list.path + '?delete=' + item.id).control-delete
    395| 						if sortable

Cannot set property '_id' of null
```
And application process crashes. 

https://github.com/JedWatson/keystone/blob/master/routes/views/list.js#L112-L128
I think may be it's some reason to wrap this invoke with try/catch? It's not good when application process crashes. What do you think about it?

**Comment by JedWatson** [comment]
I believe this hasn't been an issue for a while, @remnev please let us know if you ever experience it again.

**Comment by remnev** [comment]
I had the issue when I wrote about it. Since that time I haven't caught it.
I think it was an issue with my hardware environment. But I upgraded it and now the app works fine.

PS: however, I still think than try/catch is a good practice for rendering invokes to prevent for any problems.
