### ISSUE TITLE
No back button should land protected page once sign out is clicked in keystone.js

### ISSUE THREAD

**Issue by samsond** [keystonejs/keystone#3774]
I have opened at stackoverflow but got no answer(https://stackoverflow.com/questions/41041000/no-back-button-should-land-protected-page-once-sign-out-is-clicked-in-keystone-j)

Am using the default admin UI configuration of keystonejs(0.3.19), and I have noticed while i have logged in to the admin UI am able to see the admin UI. And when i clicked sign out, i have been redirected to the signing form.

This okay but when i click the back button on the browser am able to see the previous admin UI where i was been before. and my question is i don’t want to see my previous pages that are protected once i have clicked sign out i.e. keystone should redirect to the sign in page if the requested route is the protected one. If it not natively implemented in keystone to default back to sign in page what directions should i use ?

**Comment by jstockwin** [comment]
This is just browser caching, correct? I.e. if you actually try to do anything after you've clicked back, it won't work?

**Comment by samsond** [comment]
@jstockwin Thanks for your reply, and you are correct it has to do with caching, but i would like to redirect to login if the user logged out like this code i have done in reactjs ...

 


    componentDidMount() {
      // Injected by react-redux:
      let { dispatch } = this.props

      // Check for token and update application state if required
      const token = localStorage.getItem('id_token');
      if (token) {
      dispatch({ type: LOGIN_SUCCESS });
      window.previousLocation = this.props.location
      browserHistory.push(window.previousLocation.pathname);

      }
    }

    componentWillReceiveProps(){
      window.previousLocation = this.props.location
    }

    render() {
      const { dispatch, isAuthenticated, errorMessage} = this.props;
      return (
                <div>
                    {this.props.isAuthenticated === true
                        ? <Component {...this.props}/>
                      : browserHistory.push('/login')
                    }
                </div>
        );
     }

**Comment by Noviny** [comment]
Closing this as a keystone 0.3 issue, as we are not looking to update keystone 0.3 going forward.
