### ISSUE TITLE
sill doParallel extract 709

### ISSUE THREAD

**Issue by javierpelozo** [keystonejs/keystone#3779]
### When trying to install Keystone (npm install keystone -g) this error appeared

`Killed        .....] \ extract:keystone: sill doParallel extract 709`

_Somebody could help me?_

**Comment by jstockwin** [comment]
I don't think keystone should be installed globally, just try `npm install keystone`.
This could also be an out of memory error - what are you running this on?

**Comment by javierpelozo** [comment]
I want to install Keystone on Digital Ocean.
When doing "npm install keystone -g" I get the error mentioned.

**Comment by jstockwin** [comment]
Okay, it's probably a RAM problem, as if you're on the smallest droplet
you'll only have 512mb of RAM which isn't with.

Try adding some SWAP:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by jstockwin** [comment]
Isn't enough*

**Comment by javierpelozo** [comment]
Already solved! Thank you
