### ISSUE TITLE
4.0 Beta 4 - track {createdBy: 'author'} returns null

### ISSUE THREAD

**Issue by VadimShvetsov** [keystonejs/keystone#3780]
Hey, thank you so much for KeystoneJS. It's very handy and cool.
At this moment I can't bind current user to new comment via Admin UI, I suppose you know what's wrong here?

I'm already checkout [#3446](https://github.com/keystonejs/keystone/issues/3446) and this._req.user set right. But anyway author is null in my item.

### Steps to reproduce the behavior

```
const keystone = require('keystone');
const Types = keystone.Field.Types;

const PostComment = new keystone.List('PostComment', {
	label: 'Comments',
	track: {createdBy: 'author'}
});

PostComment.add({
	post: { type: Types.Relationship, initial: true, ref: 'Post', index: true },
	author: { type: Types.Relationship, ref: 'User', index: true },
	commentState: { type: Types.Select, options: ['published', 'draft', 'archived'], default: 'published', index: true },
	publishedOn: { type: Types.Date, default: Date.now, noedit: true, index: true },
}, 'Content', {
	content: { type: Types.Html, wysiwyg: true, height: 300 },
});

PostComment.schema.pre('save', function (next) {
	console.log('current user =>', this._req_user);
	console.log('current item =>', this);
	next();
});

PostComment.defaultColumns = 'author, post, publishedOn, commentState';
PostComment.register();
```

### Expected behavior
Author must be equal this._req_user._id.

### Actual behavior
When I press save on Admin UI I've got item with author: null

P.S. I have some items with previously manually set author field and if I update this items (or maybe just press save without changes) author gets null value too.

**Comment by jstockwin** [comment]
@VadimShvetsov I'm a little confused - why is the expected behaviour here that author should be null? Should author not be the user that created the comment?

Can you not just to `track: {createdBy: true}`, and then the `createdBy` field will be automatically filled?

**Comment by VadimShvetsov** [comment]
@jstockwin Oh, thank you a lot for this, it was my fault. I was edited my post with changing Exprected behaviour with actual. My field with User ref at this moment is 'author' and as documentation says I need to use track: {createdBy: 'author'} in this case.

> **createdBy** _Boolean/String_ - when set to true, enables tracking which user created the item (using the default field name createdBy). To use a custom field name set to a String with the desired name. Defaults to false.

**Comment by jstockwin** [comment]
Ah, I think I see the problem now. 

So doing `track: {createdBy: author}` is going to change the automatic field which is normally `createdBy` to have name `author`. However, you've already got a field called `author`, so it can't do that. 

Try removing the `author: {...}` from your `PostComment.add` entirely.

**Comment by VadimShvetsov** [comment]
@jstockwin Thank you a lot again, it has resolved the common issues, but how I can solve it in if I need to have a opportunity to change post author and get default author as logged in.

**Comment by jstockwin** [comment]
I'm not sure I quite understand exactly what you mean. What exactly do you want `author` to be?

If you're trying to set `author` to the user who has created the comment (and hence the one currently logged in?), then what I said above should be working for you.

If you need to do anything more complicated, you could do it in a pre-save hook, e.g.

```
PostComment.schema.pre('save', function (next) {
	this.author = this._req_user;
	next();
});
```
For this you'll need to remove the track stuff entirely, and keep the `author` bit in your `PostComment.add` bit. However, this is just a long-winded way of doing the first option, I think.

**Comment by VadimShvetsov** [comment]
@jstockwin thank you a lot Jake, yes the main goal is to get opportunity to change user related to Post for example and the second is to get logged in as default. Thanks and have a nice day.

P.S. It isn't obvious in documentation that named track field mustn't be in model.add method.

**Comment by jstockwin** [comment]
@VadimShvetsov No problem. I agree that it would have been nice to have had a descriptive error thrown here so that you could understand what is going on. 

@keystonejs/core-devs Do you think it's worth adding something to do this?
