### ISSUE TITLE
Error 500 at demo site 

### ISSUE THREAD

**Issue by alff0x1f** [keystonejs/keystone#3792]
When I open page of demo site, i get 500 error:
http://demo.keystonejs.com/blog/post/new-post

Sorry, an error occurred loading the page (500)

**Comment by bjwyse** [comment]
But where is the link that brings you to that URL?

The 'write post' button on the blog page links to `http://demo.keystonejs.com/keystone/posts?new`.

**Comment by alff0x1f** [comment]
Links here: http://demo.keystonejs.com/blog

I get 500 error at all post pages:
http://demo.keystonejs.com/blog/post/justtestit
http://demo.keystonejs.com/blog/post/58510ff2879e1704009914d8
http://demo.keystonejs.com/blog/post/new-post
http://demo.keystonejs.com/blog/post/aaaaaa

**Comment by bjwyse** [comment]
I see. Those links are broken and the post count / pagination is broken too.

The count might be including non-published posts but I don't know why the post links are not working.

**Comment by jstockwin** [comment]
This was fixed in [this commit](https://github.com/keystonejs/keystone-demo/commit/e81d81c019274f2b5e3a6f0cd9816a7736660c0f).
