### ISSUE TITLE
Enhancement: Prevent multiple users editing the same post

### ISSUE THREAD

**Issue by lmshaffe** [keystonejs/keystone#3795]
### Steps to reproduce the behavior
Have two users on the same post page editing the post. Have one user make changes and save and then have the second user save their changes. User 1's changes are now gone.
### Expected behavior
If two users are in the same post, only the first user can have access to edit it

**Comment by freew01f** [comment]
why can 2 users edit the same post?
if u want to do it, u have to add version control to it 

in normally, only author can edit the post

**Comment by lmshaffe** [comment]
We have experienced that anyone with access to keystone can edit a post regardless of who the author is. We had two different users editing the same post at the same time on their own respective computers.User 1 saved and their changes were saved. User 2 saved last and their changes overwrote what user 1 just did.

Have you experienced different with 2 users trying to edit a post at the same time?

**Comment by freew01f** [comment]
it is not easy to handle~
I think u have to consider to use version control~
this way u can merge diff version of post ~

**Comment by lmshaffe** [comment]
I am sure it is not easy, that is simply why I posed this as a possible enhancement feature to the team.

**Comment by webteckie** [comment]
I think this will be possible when dynamic permissions support  (see https://github.com/keystonejs/keystone-test-project/pull/21) is in.

**Comment by Noviny** [comment]
There are two issues here. First, do all users have edit rights, and second, if one person has a post open, no person on another computer can edit it.

The first is solved by us adding a permissions scheme. There is an existing issue/discussion around this.

If what you are after is the second, that's a complex piece of architecture (multi-client state shared with server with a notion of checking something out), which we are not looking to build into the core of keystone.

Closing this issue in favor of existing permissions discussion.
