### ISSUE TITLE
keystone.js doesnt start on amazon ubuntu

### ISSUE THREAD

**Issue by asafgaber** [keystonejs/keystone#3798]
Uploaded keystone application to Amazon ubuntu 16.04 instance.

For some reason, keystone.start() isnt able to start the server and gets stuck:

```
ubuntu@ip-xxx-xx-xx-xx:~/projects/boomiz.com$ npm start

> boomiz-com@0.0.0 start /home/ubuntu/projects/boomiz.com
> nodemon keystone.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node keystone.js`
before db
after db
after start
```

console.log('after start') is after keystone.start().

works perfectly on my ubuntu 16.04 desktop.

any idea?

Thanks, Asaf

**Comment by bjwyse** [comment]
What version of KeystoneJS and what version of NodeJS?

**Comment by asafgaber** [comment]
```
node v7.2.1
keystone@0.3.22
```

tried it with `node`  still no go.

found out with strace that there's a problem connecting to db:

```
connect(12, {sa_family=AF_INET, sin_port=htons(27017), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
getsockopt(12, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
```
mongo db is listening (checked) and ive opened all the ports.
anyone encountered this problem on amazon ubuntu 16.04 instance?

**Comment by molomby** [comment]
Just confirming what you mean by "Amazon ubuntu 16.04"... You're talking about Ubuntu 16.04, from an official Canonical AMI, running on EC2, right? Not Amazon Linux, which is a Red Hat based distro..?

So, for example, this..
https://aws.amazon.com/marketplace/pp/B01JBL2I8U

Not this..?
https://aws.amazon.com/marketplace/pp/B00635Y2IW

**Comment by Lurk** [comment]
Keystone not start on node 7.x.

**Comment by Noviny** [comment]
Closing this as a known keystone 0.3 problem. We are no longer actively developing for 0.3. Updating mongoose yourself is the recommended fix if anyone else runs into this problem.

**Comment by internetErik** [comment]
Jost a note: not sure if this will help but you if you're running keystone on port 80 you may need to run it with `sudo`
