### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by Ikhan** [keystonejs/keystone#3799]
Is there any way i could enable debug mode enable. Right now this is I'm getting. "Sorry, an error occurred loading the page (500)" 

Thanks.

**Comment by bjwyse** [comment]
In WebStorm it is simply a matter of choosing Debug from the Run menu and setting breakpoints (you may have to restart WebStorm).

Can't say how to debug for other IDEs though...

**Comment by pavethiran** [comment]
If you are using Chrome, you can use the *Chrome Dev Tools*.

[Chrome Dev Tools Docs](https://developers.google.com/web/tools/chrome-devtools/)

**Comment by Ikhan** [comment]
Thanks.. thats helpful.

**Comment by bassjacob** [comment]
Hi @Ikhan,

depending on whether you're trying to debug the frontend or the backend:

frontend debug (as listed above): [chrome dev tools](https://developers.google.com/web/tools/chrome-devtools/)

backend debug: https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.71mc9ooho
