### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by anddimario** [keystonejs/keystone#38]
Hi, what do you think about a multisite feature? For example a middleware that gets hosts from header used to mapping the sites, i'm using it in a little cms project that i've started months ago:

    // Middleware to get the host for multisite
    app.use(function (req, res, next) {
        // Get the request host and map it to right database into redis 
        var domain = req.headers.host.split(':')[0];
        // Set the parameters mapping
        res.locals.mapping = parameters.vhost[domain];
    
        // Check if site exists, otherwise send error
        if(res.locals.mapping) {
            // Set the view directory
            res.locals.view_dir = __dirname + '/sites/' + res.locals.mapping + '/views';
            // Set favicon if is enabled in configuration parameters
            if (misc_params[res.locals.mapping].favicon) {
                app.use(express.favicon(__dirname + '/sites/' + res.locals.mapping + misc_params[res.locals.mapping].favicon));
            }
            next();
        
        } else {
            utils.applog('error', "Requested and invalid site from: " + req.connection.remoteAddress);
            res.send(parameters.server_error);
        }
    }); 

Best regards.

**Comment by JedWatson** [comment]
Closing this, it's an old issue and not relevant at the moment.

Thanks for the early feedback @anddimario!
