### ISSUE TITLE
Setting `isProtected` on a user stops the password being encrypted. 

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3801]
### Steps to reproduce the behavior

See https://github.com/keystonejs/keystone-demo/issues/59

Clone the keystone demo site, run it, and try to log in.

### Expected behavior

Can log in with the given credentials. 

### Actual behavior

Log in gets rejected.

The `isProtected: true` on the user prevents the password being encrypted, and then things break when you try to sign in.

**Comment by Noviny** [comment]
This was dealt with (quick lookup couldn't find the commit) so that this no longer occurs. Please reopen if it's still a problem.
