### ISSUE TITLE
Relationship is deleted when updating and the field is noedit: true

### ISSUE THREAD

**Issue by AurelioDeRosa** [keystonejs/keystone#3802]
### Steps to reproduce the behavior

1. Create a model with a Relationship field having `noedit: true`
2. Create a document of such model. Be sure to set the relation of the field having `noedit: true`
3. Update the document

### Expected behavior

The relation field doesn't change

### Actual behavior

The relation field is unset

As far as I can tell, the reason is that the form doesn't submit the `noedit: true` field (and this is correct). So, when calling the `updateItem()` function, the following code (file `RelationshipType.js`) is executed:

```js
} else if (item.get(this.path)) {
    item.set(this.path, null);
}
```

This unset the value. I think the `if` should also check that the field is `!noedit`.

**Comment by Noviny** [comment]
#4035 should have fixed this.

If you still experience an issue, let me know.
