### ISSUE TITLE
[4.0.0-beta.4] bug in displaying related models in admin UI

### ISSUE THREAD

**Issue by jacqueslareau** [keystonejs/keystone#3805]
Hi,

There seems to be a bug when loading relationship data of a model in the admin UI.

### Steps to reproduce the behavior

Add a relationship to model and add related items.
Ex: Account.relationship({ path: 'contacts', ref: 'Contact', refPath: 'account' });

### Expected behavior

Should show list of related relationship.

### Actual behavior

When I check the network calls, everything looks fine. Call is fired and the correct json data is returned from the server. It looks like a frond end code bug. The list doesn't get updated with the new data.

It just keeps showing loading indicator:

![image](https://cloud.githubusercontent.com/assets/6105320/21269266/14786f14-c380-11e6-9231-6bc4a5788807.png)

**Comment by freew01f** [comment]
I meet the same problem 
Loading forever

**Comment by AurelioDeRosa** [comment]
This has been fixed with commit #3782.

**Comment by jacqueslareau** [comment]
Thanks. I looked around before posting. Did not saw this.

Maybe release beta.5 containing this, because beta.4 is pretty broken without this.

**Comment by AurelioDeRosa** [comment]
Releasing a new beta might be a good idea. However, you can use the master branch to include the fix. Also, the issue can be closed?

**Comment by jacqueslareau** [comment]
Closing because already fixed in master branch. Fix will be included in next beta release: >4.0.0.beta.4
