### ISSUE TITLE
How to custom the logger tokens to get my zone's datetime?

### ISSUE THREAD

**Issue by playwolf719** [keystonejs/keystone#3811]
Considering that I'm from China, I want to custom the logger tokens to get my zone's datetime. But the following setting seems not to work for me. Please help me with it. The code is below.

`
keystone.init({
    'name': 'mySpace',
    'brand': 'mySpace',
    'less': 'public',
    'static': 'public',
    'favicon': 'public/myicon.ico',
    'views': 'templates/views',
    'view engine': 'jade',
    'emails': 'templates/emails',
    'auto update': true,
    'session': true,
    'auth': true,
    'user model': 'User',
    "port":3001,
    'logger': 'combined',
    "logger options":{
        stream: accessLogStream,
    },

});

keystone.set({
       'logger options': {
        tokens: {
             date: function () { return new Date().toString(); },
         },
  },
 });
`

**Comment by playwolf719** [comment]
@AurelioDeRosa

**Comment by AurelioDeRosa** [comment]
I don't know the answer to this, you should probably ask one of the member of the team (I'm not). Anyway, this is probably more a question for StackOverflow than an issue with the CMS.

**Comment by playwolf719** [comment]
@AurelioDeRosa Thx anyway

**Comment by Noviny** [comment]
The answer to this is that it uses your computer's timezone. Note that if keystone server and admin client are in different timezones you may get some weirdness.
