### ISSUE TITLE
Keystonejs Show all posts created from specific year

### ISSUE THREAD

**Issue by BillGR17** [keystonejs/keystone#3819]
I created all the links to send a number with the specified year that the user wants to see.<br>
Now all i want to set the routes use that year and display the posts created that year.<br>
Basically the number that will go to the routes is for example 2001<br>
What do i need to add here:<br>
***This is the routes***

    var q = keystone.list('Post').paginate({
    	page: req.query.page || 1,
    	perPage: 200,
    	maxPages: 100,
    }).where('state', 'published');

***This is the model***

    var keystone = require('keystone');
    var Types = keystone.Field.Types;
    
    /**
     * Post Model
     * ==========
     */
    
    var Post = new keystone.List('Post', {
    	map: { name: 'title' },
    	autokey: { path: 'slug', from: 'title', unique: true },
    });
    
    Post.add({
    	title: { type: String, required: true },
    	categories: { type: Types.Relationship, ref: 'PostCategory', many: true },
    	state: { type: Types.Select, options: 'draft, published, archived', default: 'published', index: true },
    	publishedDate: { type: Types.Date, index: true, dependsOn: { state: 'published' } },
    	image: { type: Types.CloudinaryImage },
    	pronunciations: { type: Types.CloudinaryImage },
    	answers: { type: Types.CloudinaryImage },
    	content: {
    		extended: { type: Types.Html, wysiwyg: true, height: 300 },
    	},
    
    });
    
    Post.schema.virtual('content.full').get(function () {
    	return this.content.extended || this.content.brief;
    });
    
    Post.defaultColumns = 'title, state|20%, author|20%, publishedDate|20%';
    Post.register();

i already have the year on routes but i don't know how to use where correctly
so far .where('publishedDate').equals('2001')it shows nothing
heres a post in mongodb database from 1-1-2001

    {"_id": ObjectID("5857b9387cf9b55946a5cae3"),
    "slug": "test-exam-2001",
    "title": "Test Exam 2001",
    "state": "published",
    "categories": [
        ObjectID("5857b80a7cf9b55946a5cadf")
    ],
    "__v": 2,
    "content": {
        "extended": "<p>empty</p>"
    },
    "publishedDate": ISODate("2000-12-31T22:00:00.000Z")}

**Comment by BillGR17** [comment]
on stockoverflow someone said this 
view.on('init', function (next) {
   var q = keystone.list('Post').paginate({
      page: req.query.page || 1,
      perPage: 200,
      maxPages: 100,
   }).where('state', 'published');
   q.exec(function (err, results) {
      if (results && !err) {
         locals.yearPosts = results.map(function (curResult) {
            return curResult.getFullYear() === 2016; // Your year goes here
         });
         return next();
      }
      else {
         // You either have no posts or there was an error loading them
      }
   });
});

but i get this error

TypeError: results.map is not a function

**Comment by jstockwin** [comment]
This isn't an issue with keystone, so StackOverflow is the place for this rather than the issue tracker. I've added a comment to the answer over there.
