### ISSUE TITLE
AdminUI: no scroll when content overflows

### ISSUE THREAD

**Issue by slim01** [keystonejs/keystone#3822]
### Steps to reproduce the behavior

The admin ui content does not fit into the div after adding local file uploads. In the moment a file is selected the "filechoser box" gets larger.

### Expected behavior
The box should be able to scroll when the content overflows

### Actual behavior

You are not able to see the whole content and the save button.
![screenshot](https://cloud.githubusercontent.com/assets/12085376/21467786/8af85e5e-c9f9-11e6-92de-8686fd3a81a0.PNG)

**Comment by ghuroo** [comment]
I had the same issue just today!

**Comment by morenoh149** [comment]
PR fixing this available at https://github.com/keystonejs/keystone/pull/4169 please review and merge
