### ISSUE TITLE
noedit URL fields are editable in initial create dialog

### ISSUE THREAD

**Issue by alexkolson** [keystonejs/keystone#3841]
### Steps to reproduce the behavior
Define a URL field as noedit.
Open create dialog for model with noedit URL field.

### Expected behavior
Field is greyed out like on edit page

### Actual behavior
Field is not greyed out and is editable

**Comment by bassjacob** [comment]
Hi @alexkolson,

I think this might be correct behaviour.

If you create a field like `noeditField: { type: keystone.Field.Types.Url, noedit: true },` then it won't show up in the modal.

If you create a field like `	noeditField: { type: keystone.Field.Types.Url, noedit: true, initial: true },` then it will be editable in the modal, but not updatable once set.

Does that describe the behaviour you're seeing? Or is the desire to see the field and it's value, but for it not to be editable?

**Comment by alexkolson** [comment]
Ah yes! The field is called `noedit` after all! Thanks for clearing that up.

The documentation may need to be tweaked slightly from "renders the field as readonly in the admin ui" to something like "Field is only editable upon creation" or something similar.

Thanks again for getting back! I appreciate it and everything you are all doing to make keystone such a fantastic product.
