### ISSUE TITLE
cookieSecret set, yet still forced to sign in between restarts

### ISSUE THREAD

**Issue by AlexanderSopov** [keystonejs/keystone#3843]
# In dev-env I hardcoded to cookieSecret and still, I need to log in between server restarts

## Describe the bug

During development I do a bunch of changes and need to restart the server a bunch of time. Everytime I do, I'm forced to log in again and in the documents and in the console warning, this is due to cookieSecret not being set.

Well... I set the cookieSecret to some hardcoded value, let's say "AngryBirds" or whatever, yet still, I need to log in again inbetween restarts.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Start a new project with users and cms
2. Hardcode a cookieSecret in the "new Keystone" function parameter, i.e.

```
const keystone = new Keystone({
  adapter: new Adapter(adapterConfig),
  onConnect: process.env.CREATE_TABLES !== 'true' && initialiseData,
  cookieSecret: 'AngryBirds',
  cookie: {
    secure: process.env.NODE_ENV === 'production', // Default to true in production
    maxAge: 1000 * 60 * 60 * 24 * 30, // 30 days
    sameSite: false,
  }
});
```

3. Start the Server and go to "localhost:3000" and Login to the admin UI
4. Restart server and try navigating around the admin UI. You will be (at least I am being) prompted to login again.

## Expected behaviour

The session from before server restart should still be valid

## System information

- OS: macOS
- Browser Chrome

**Comment by bookyo** [comment]
sessionStore: new MongoStore({ url: process.env.MONGOURI }),   you can use a mongodb store session, this can solve your issue

**Comment by AlexanderSopov** [comment]
> sessionStore: new MongoStore({ url: process.env.MONGOURI }), you can use a mongodb store session, this can solve your issue

Thank you! This fixed the issue. It should be stated more clearly in the documents. Thank you very much
