### ISSUE TITLE
node-sass not found.

### ISSUE THREAD

**Issue by trentontri** [keystonejs/keystone#3873]
### Steps to reproduce the behavior
when I first run `yo keystone` followed by `node keystone` this is what I see:
Please install the node-sass-middleware from npm to use the `sass` option.
You can do this by running "npm install node-sass-middleware --save".

**Comment by jstockwin** [comment]
This is an issue with the generator rather than with keystone itself. Would you mind closing this and opening an issue over at https://github.com/keystonejs/generator-keystone/issues please?
