### ISSUE TITLE
List of ".relationship()" items is loading indefinitely

### ISSUE THREAD

**Issue by justingosan** [keystonejs/keystone#3879]
Im on the latest beta keystone@0.4

### Steps to reproduce the behavior
* Have 2 models related to each other where Model1 has 1 to many relationship with Model2
* Do:
```
// Relationships
Model1.relationship({
    path: 'model2s',
    ref: 'Model2',
    refPath: 'model1'
});
```
* Populate Models
* Navigate to detail view of a Model1 item

### Expected behavior
Should be able to see list of related Model2 below

### Actual behavior
**List is shows loading animation indefinitely.**
GET operation on list of Model2 items from API is successful and contains result.
No console errors.

**Comment by keyfun** [comment]
same here. it works fine in beta.3

**Comment by Noviny** [comment]
Hi @justingosan and @keyfun, I've been unable to replicate this in beta-5, and am closing this as an issue, however as I did not experience it in older versions of 4, if you have information on what version it's failing on I'm happy to dig in to it.
