### ISSUE TITLE
XSS server side rendering

### ISSUE THREAD

**Issue by pdonald** [keystonejs/keystone#3889]
### Steps to reproduce the behavior

1. Create a user with `</script><script>alert('hacked');</script>` in its name.
2. Log in with the user.

### Expected behavior

You see the admin dashboard.

### Actual behavior

The browser interprets the `</script>` in the user's name as the closing tag and the dashboard is broken.

![image](https://cloud.githubusercontent.com/assets/860965/21937876/a0369128-d9c1-11e6-9266-a94f06848b76.png)

Instead of `JSON.stringify`

```html
<script>
var Keystone = <%- JSON.stringify(keystone) %>;
</script>
```

`serialize-javascript` or something similar should be used in `admin/server/templates/index.html`.

https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0

**Comment by thejameskyle** [comment]
Which version of Keystone are you running?

**Comment by thejameskyle** [comment]
Never mind, confirmed it's still an issue in the latest keystone

**Comment by thejameskyle** [comment]
Moving to #4136
