### ISSUE TITLE
Conatc form 500 server error.. 

### ISSUE THREAD

**Issue by vikramparihar** [keystonejs/keystone#3895]
![keystone](https://cloud.githubusercontent.com/assets/5202442/21972463/c2539880-dbdf-11e6-9fe3-03b552e60cc6.png)

When trying to send empty contact form an internal error occur..

**Comment by bassjacob** [comment]
Hi @vikramparihar, nice to see some Ubuntu :smile: 

it looks like validationErrors is undefined in your view, which likely means that you aren't setting it in your controller to the res.locals object. Can you share the code that renders this view? Is there a public repository that we can take a look at?

**Comment by vikramparihar** [comment]
@bassjacob Thanks for quick replay..  But I haved   solved issue on client side.. I Have added some validation ...  thanks  :)

**Comment by bassjacob** [comment]
No problem :+1: should we close this issue then?

**Comment by vikramparihar** [comment]
Yes.. Thanks
