### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by dani190** [keystonejs/keystone#3903]
Sorry guys, not quite sure what to include here. I have filled out the requested form below but basically i just upgraded to 4.0.0 beta 4 from the latest 3 version and my contact form no longer functions.

### Steps to reproduce the behavior
Upgrade to latest 4.0.0-beta4

### Expected behavior
Project works as intended and contact form works properly

### Actual behavior
My form (Contact page) is giving me a cannot read property of undefined at every value.

`TypeError: /home/cns/templates/views/contact.jade:17
    15|                                 form(method='post')
    16|                                         input(type='hidden', name='action', value='contact')
  > 17|                                         .form-group(class=validationErrors.incidentNumber ? 'has-error' : null)
    18|                                                 label Incident Number
    19|                                                 input(type='text', name='incidentNumber', placeholder="(Required)",                                                        value=formData['incidentNumber']).form-control
    20|                                         .form-group(class=validationErrors.incidentStatus ? 'has-error' : null requ                                                       ired)

Cannot read property 'incidentNumber' of undefined
`

**Comment by bassjacob** [comment]
Hi @dani190, thanks for reporting this.

This looks likes the same issue as https://github.com/keystonejs/keystone/issues/3895. Did you use the keystone generator to start your project?

It's likely that something has changed in the view code between beta3 and beta4. I'll take a look into this and see if I can identify the culprit.

**Comment by dani190** [comment]
Originally I believe I did way back when ya.

Ok thanks. So technically if I try beta3 I may be ok?

**Comment by bassjacob** [comment]
oh, sorry, I thought you meant beta3 when you said 3. No, likely not, it's probably a breaking change in between 3 and 4. Can you paste the router code that renders the contact form here?

**Comment by dani190** [comment]
Sorry, ya I meant I had generated on 3.
Which code would that be? Sorry still learning here. Is it within routes/views?

**Comment by bassjacob** [comment]
yes, I think it would be something like `routes/views/contact.js`

**Comment by dani190** [comment]
`var keystone = require('keystone');
var Enquiry = keystone.list('Enquiry');
var User = keystone.list('User');
var Group = keystone.list('Group');
var db = require('mongoose');


exports = module.exports = function(req, res) {
	
	var view = new keystone.View(req, res);
	var locals = res.locals;
	
	// Set locals
	locals.section = 'contact';
	locals.formData = req.body || {};
	locals.validationErrors = {};
	locals.enquirySubmitted = false;
	locals.enquiryblank = false;
	locals.incidentStatuses = Enquiry.fields.incidentStatus.ops;
	
	view.on('init', function(next) {
		Group.model.find().sort('name').exec(function(err,data){
			if(err)return console.log('error while fetching client list for contact page', err);
			var companies = [];
			for(var i=0; i<data.length; i++){
				companies.push({'groupid': data[i]._id, 'groupName': data[i].name });
			}
			locals.companies = companies
			next();
		});
	});
	// On POST requests, add the Enquiry item to the database
	view.on('post', { action: 'contact' }, function(next) {
		var newEnquiry = new Enquiry.model(),
			updater = newEnquiry.getUpdateHandler(req);
			newEnquiry.wasNew = true;
		
		updater.process(req.body, {
			flashErrors: true,
			fields: 'incidentNumber, impact, incidentSubject, update, incidentStatus, nextUpdate, resolution, updateNumber, groupSelect, dateAndTimeOfIncident, smsmessage, emailmessage, estimateRepairTime',
			errorMessage: 'There was a problem submitting your enquiry:'
		}, function(err) {
			if (err) {
				locals.validationErrors = err.errors;
			} else if (req.body.smsmessage == false && req.body.emailmessage == false){
				locals.enquiryblank = true;
			} else {
				locals.enquirySubmitted = true;
			}
			next();
		});
		
	});
	view.render('contact')
};
`

**Comment by bassjacob** [comment]
Sorry, can you also please post the full jade file? or even better, if the project is open-source a link to the git repository?

**Comment by duythang** [comment]
Hello @bassjacob 
i have same issue like this.
I am using KeyStone Beta 5

Error from "validationErrors".
I tried on Keystone-Demo source code. The issue still happens when i remove **required** addtribute
 
For example i modified:
- Original code "contact.pug" in Keystone-Demo
```ruby
.form-group(class=validationErrors.name ? 'has-error' : null)
						label.col-sm-2.text-left.control-label Name
						.col-sm-10
							input(type='text' name='name.full' value=formData['name.full'] required placeholder="First Last").form-control
```
After removing **required** addtribute
```ruby
.form-group(class=validationErrors.name ? 'has-error' : null)
						label.col-sm-2.text-left.control-label Name
						.col-sm-10
							input(type='text' name='name.full' value=formData['name.full']  placeholder="First Last").form-control
```

Can you check it ?

Thank you

**Comment by dani190** [comment]
@bassjacob Any word on a possible fix? I am still having the issue but have now ran into the relationship issue in version 0.3.22 so I now need to upgrade to 4

**Comment by dani190** [comment]
Has anyone found a solution to this? Still happening for me. Seems to be related to selecting multiple groups in my drop down select. Funny thing is this is totally unrelated to the field its failing on.

**Comment by Noviny** [comment]
From the error message here, the validation errors are not being surfaced as a local variable as expected. My test case would be to check that other locals were rendering/being passed in.

Also `locals.validationErrors = err.errors;` assumes that if there is an `err` it will have an `errors`.

Closing this as an old issue, though if this is an unrecorded breaking change between 3 and 4, this should definitely be documented.
