### ISSUE TITLE
Replace inline try/catch with safeRequire

### ISSUE THREAD

**Issue by bassjacob** [keystonejs/keystone#3908]
### Steps to reproduce the behavior
In current state, the following is copied throughout the codebase:

```javascript
try {
  return require('some unbundled lib');
catch (e) {
  if (e.code === 'MODULE_NOT_FOUND') {
    // do something
  }
  throw e;
}
```

we can replace this in these places with the new safeRequire function from #3907 for consistency.

**Comment by thejameskyle** [comment]
Moving to #4140
