### ISSUE TITLE
Explicit graphql-app schemaName unsupported in @keystone/keystone@17.0.0

### ISSUE THREAD

**Issue by MichaelZaporozhets** [keystonejs/keystone#3909]
# Bug report

## Describe the bug

Setting an explicit configuration value for `schemaName` when initializing `GraphQLApp` currently causes both dev and build to fail. 

Digging a little deeper i've noticed that `getGqlQueries` in ListTypes/list gets the schemaName passed and expects the same name to exist as a key within `this.access`. 

Adding `console.log(schemaName, this.access[schemaName])` @ line 1051 will log 

```
internal { create: true, read: true, update: true, delete: true, auth: true }
mySchemaName undefined
```

However, when I remove my custom schema name, I receive the following instead:

```
internal { create: true, read: true, update: true, delete: true, auth: true }
public {
  create: [Function: userIsAdmin],
  read: [Function: userIsAdminOrOwner],
  update: [Function: userIsAdminOrOwner],
  delete: [Function: userIsAdmin],
  auth: true
}
```

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

2. Add a custom `schemaName` to your `GraphQLApp` initialization config
3. run `yarn dev`

## Expected behaviour

Expect application to run and build successfully

**Comment by timleslie** [comment]
If you want to use a `schemaName` within the `GraphQLApp` then you need to make sure that you have passed in `schemaNames = ['mySchemaName'],` to the `Keystone` constructor, e.g.

```js
keystone = newKeystone({
   ...
  schemaNames = ['mySchemaName'],
});
```

This isn't particularly well documented, we should definitely improve that.

**Comment by MichaelZaporozhets** [comment]
@timleslie makes sense! I'll PR a documentation update

**Comment by MichaelZaporozhets** [comment]
PR Merged. Issue resolved. 🥂
