### ISSUE TITLE
Explicitly provide a list of `initial` field paths when creating new items

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#391]
The form processing for creating new items in the Admin UI currently uses the default field set, rather than explicitly providing a list of the `initial` fields.

This would be fine in almost all cases, except when a field was marked as both `initial` and `noedit` it would be ignored.

Using the combination of both options is a way to implement set-once fields, so we should make sure this use-case actually works properly.

**Comment by wmertens** [comment]
I believe this is still the case in v0.4? Any ideas on how to tackle this?

**Comment by JedWatson** [comment]
This has been implemented in v4
