### ISSUE TITLE
/admin/server/api/s3.js is using old S3File, Underscore is missing (_ is not defined)

### ISSUE THREAD

**Issue by Rmannn** [keystonejs/keystone#3926]
### Steps to reproduce the behavior
Manually add the external plugin uploadimage to tinymce
Update the plugin to use the Keystone.csrf.header['x-csrf-token'] var instead meta
Try to upload to amazon S3.

### Expected behavior
Upload should be working

### Actual behavior
Got an html response from server, _ is not defined as the file /admin/server/api/s3.js is using old S3File prototype to generate s3 headers.
In https://github.com/keystonejs/keystone/blob/master/admin/server/api/s3.js#L23
`Types.S3File.prototype.generateHeaders.call(/*...*/)`
Underscore "_" dependency is missing from S3File

How to get it working using the new Storage Api ? It is working in beta1, not in latest version.

**Comment by stennie** [comment]
FYI: this will be fixed in `4.0.0-rc.2` via #4594.
