### ISSUE TITLE
Errors occur when attempting to run a cloned KeystoneJS project

### ISSUE THREAD

**Issue by KernelDeimos** [keystonejs/keystone#3929]
### Steps to reproduce the behavior
* Create a KeystoneJS project using the generator
  * Select SASS for stylesheets
* Initialise a git repository and push it somewhere
* Clone the git repository somewhere else
* Run npm install to install dependencies

### Expected behavior
KeystoneJS server can now run by running `node keystone` in the project folder.

### Actual behavior
Two errors prevent the server from running.
- The first is resolved by running `npm rebuild sass`.
- The second is resolved by installing a missing dependency with `npm install --save unicode`.

**Comment by bassjacob** [comment]
Hi @KernelDeimos, thanks for reporting.

Can you post the version of the generator and of keystone installed? Is the git project available as open-source to look at?

**Comment by KernelDeimos** [comment]
Hey, sorry for the late reply but here's the information:
Keystone generator: 1.8.5 (as reported by `yo keystone --version`)
Keystone: 0.3.22 (in the package.json file under node_modules/keystone)

The project isn't open source (it's a website for a local business), but I could give you a temporary membership to the repository on GitLab by email.

**Comment by Noviny** [comment]
Closing this as a keystone 0.3 issue. The generator is currently sitting on 0.5.1 and ships with keystone 4's current beta. The generator version here is likely wrong.

@KernelDeimos If this is still a problem with the current generator, let me know, and I'll look in to it.
