### ISSUE TITLE
A lot of modules are deprecated 

### ISSUE THREAD

**Issue by kalmecak** [keystonejs/keystone#3934]
### Steps to reproduce the behavior

* Use keystone version: v0.3.19
* Execute **npm install**

### Expected behavior

I expect to be installed modules needed without warnings

### Actual behavior

On installing node modules I got lot of deprecation warnings

![captura de pantalla 2017-01-24 a la s 11 58 45](https://cloud.githubusercontent.com/assets/1189660/22257903/7d16ea2a-e22d-11e6-859a-d41de70230ce.png)

**Comment by bassjacob** [comment]
Hi @kalmecak, a big part of that is the (hopefully soon) upcoming 4.0 release which has been taking our attention. Is upgrading to 4.0 a possibility for your application? https://github.com/keystonejs/keystone/blob/master/docs/guides/v0.3-to-v4.0-Upgrade-Guide.md

**Comment by thejameskyle** [comment]
There isn't much action to take here. v4 should be out soon which will have updated dependencies
