### ISSUE TITLE
All category post are returned even when category does not exist (v4.0)

### ISSUE THREAD

**Issue by jephjohnson** [keystonejs/keystone#3936]
When entering a category that does not exist in my url:

http://localhost:3000/blog/categorydoesnotexist

All the post returned, however invalid should be returned like what is currently the case on the demo:

http://demo.keystonejs.com/blog/categorydoesnotexist

I built from the latest yo generator and did an npm install of the latest keystone release and running (v4.0). 

Am I missing something?

**Comment by jephjohnson** [comment]
Bump

**Comment by bassjacob** [comment]
hi @jephjohnson, I can't think of a reason from your description. Do you have a codebase I could look at to see what's going on? Can you see what you're doing different from the keystone demo site?

**Comment by jephjohnson** [comment]
Hey there @bassjacob - nothing different at all. This is a fresh build using the keystone boilerplate from yeoman then upgrading to the latest keystone.

To reproduce:
npm install -g generator-keystone
yo keystone

I am selecting handlebars for templating and sass as my pre-processor.

I am then upgrading to the latest keystone:
npm install --save keystone@next

I am not editing any model or view.

**Comment by jephjohnson** [comment]
Bump

**Comment by chrisschaub** [comment]
I had to ...

npm install react --save

**Comment by jephjohnson** [comment]
Thanks @chrisschaub
