### ISSUE TITLE
Admin UI: Elements lists do not compute virtuals when needed fields aren't shown

### ISSUE THREAD

**Issue by ignlg** [keystonejs/keystone#394]
**Easier to explain with an example:**
`User` schema has, among others, this field:
```
isBanned: boolean
```
And a virtual:
```
canLogin: (!isBanned)
```
**Case A, right:**
```
User.defaultColumns = 'canLogin, isBanned';
```
![screen shot 2014-05-30 at 12 02 46](https://cloud.githubusercontent.com/assets/722609/3129333/cd68cf96-e7e1-11e3-9e7d-360d0561a821.png)
**Case B, wrong:**
```
User.defaultColumns = 'canLogin';
```
![screen shot 2014-05-30 at 12 03 42](https://cloud.githubusercontent.com/assets/722609/3129335/d5f8f834-e7e1-11e3-83b8-35ad062daa6f.png)

**Potential solution:**
My first idea to fix it was to add another, optional, property to `User` that overrides the fields used to query the db.

_In example:_
```
User.defaultColumns = 'canLogin';
User.getColumns = 'isBanned, canLogin';
```
Opinions, ideas?

**Comment by mxstbr** [comment]
I'll close this due to inactivity for now, feel free to comment if you still want and/or need this implemented/fixed!
