### ISSUE TITLE
Pre-hook for signin sends user instead of body as param

### ISSUE THREAD

**Issue by OskarKlintrot** [keystonejs/keystone#3944]
### Steps to reproduce the behavior
```
keystone.pre('signin', function() => {
	console.log(this)
})
```

### Expected behavior
Output `req.body`

### Actual behavior
Output `user` from database

____________________________
I don't understand the reason behind this behavior? Wouldn't it make more sense to get the `req.body` to do stuff with, for example to validate against an external service or a JWT to enable SSO?

**Comment by bassjacob** [comment]
what's the error that it throws? is there an error message?

**Comment by bassjacob** [comment]
Sorry, deleted my above comment as it wasn't relevant.

I don't believe this is supported behaviour. keystone.pre uses the [grapplin-hook](https://github.com/keystonejs/grappling-hook) library to create pre hooks on the keystone instance, one of which is the pre:signin hook. this isn't an express middleware, it's a function according to the grapplink-hook spec linked above.

**Comment by bassjacob** [comment]
for the record, you can see the signin hook called here: https://github.com/keystonejs/keystone/blob/c4789388ef09d09f39585f68b2a6fc898b7da040/admin/server/api/session/signin.js#L16

can you elaborate a little on why you want to hijack the keystone signin process?

**Comment by OskarKlintrot** [comment]
Sure, I want to validate the user against Microsoft Active Directory and if the user is valid then I just want to grab the user from the keystone db with the email alone (since the passwords are handled by the AD anyway) if the user exists there. I also want to make it possible to sign in with a JWT to enable SSO. Since I don't mind using Keystone's signin form it feels a bit overkill to implement my own signin with ie passport from scratch since it's such a small piece of Keystone that I don't want to use.

**Comment by OskarKlintrot** [comment]
What's the reason behind having the signin hook _after_ fetching the user from the db? If it was _before_ the whole signin function and included a reference to `req.body` it would have been exactly what I needed. Then I could just add the domain to the email, validate the user against our AD or against a JWT for SSO and then update the password to a random password and set that to the password on the body as well to bypass keystones signin process more or less altogether. Right now IMHO the signin hooks comes a bit to close to each other to be really useful for implementing a custom signin process since the `pre`-hook is so limited and deep down keystones signin process.

**Comment by OskarKlintrot** [comment]
Would [this gist](https://gist.github.com/OskarKlintrot/2c95a2587045df1884ebd0a013fb0cae#file-signin-js-L7) make sense?

**Comment by creynders** [comment]
@OskarKlintrot the reason why the user is retrieved _before_ the pre:signin hook is because it allows you to deny access based on the user, e.g. if you'd want to implement user blacklisting for instance. 

That said, I understand the use case and why you need `req.body`. I'd need to look into it, but if I'm not mistaken we could pass the body as a parameter to the hook handlers. I.e. it would still be called at the exact same spot, but you'd be able to access `req.body` in your hook handler. Would that suffice?

I wrote grappling hook BTW and implemented the hooks into Keystone.

**Comment by creynders** [comment]
I forgot: the change you propose is a VERY breaking change - I don't see that landing soon. But I'm certain we can work out a solution for you.

**Comment by OskarKlintrot** [comment]
You are too fast for me @creynders! I was going to ping you after I updated the issue to describe my actual pain point and not just my misunderstanding about how the hooks are working.

Yes, adding `req.body` along with `user` would suffice even though the user must enter their whole email. Adding `req.body` would make everything so much easier when using a custom validation process! That would make me more than happy! I can try and add it and create a PR if you like!

I realized that as well, it dosen't really feel doable to change the behavior but rather to add a new hook, but at the same time just adding a hook to be able to use usernames instead of email, is it really worth it? I guess we are not so many developers hooking up Keystone to an AD :)

**Comment by OskarKlintrot** [comment]
Would it make sense to add `req.body` to the `post:signin` hook as well to keep the code consistent? And also, would it make more sense to add a ref to the entire `req` instead?

**Comment by creynders** [comment]
Yeah, feel free to create a PR (it'll be faster than waiting for me 😁 ) [Read up here on passing parameters to middleware (i.e. to hook handlers)](https://github.com/keystonejs/grappling-hook#passing-parameters)

Just make sure that it's backwards compatible, i.e. handlers that don't accept parameters (or only `done`) still work. I seem to remember it shouldn't be a problem out-of-the-box.

I'm not a big fan of passing around entire `req` objects, but granted, in this case I think it's most appropriate. @mxstbr what do you think?

**Comment by OskarKlintrot** [comment]
I added `req.body` as a param and it works just fine with functions not taking any arguments. If I understand it correct then `done` is added last of the parameters. Is it possible not to break peoples code when adding a parameter? At least all tests are passing when adding one parameter...

I agree, I try to figure out a use case for it and it could be that someone want to access `req.keystone` but to me personally it makes the most sense to pass only `req.body`.

**Comment by creynders** [comment]
Yeah, `done` is an optional parameter which determines the handler as an asynchronous one. Since no parameters were being passed yet, it shouldn't break anyone's code if you add one now.

**Comment by OskarKlintrot** [comment]
Sounds good, just did a PR if you would like to check it out ;-)

I realized that for example `req.cookies` would be nice to be able to access in my case when I want to enable SSO so I passed `req` as a param.
