### ISSUE TITLE
Usage with yarn leads to builds failing

### ISSUE THREAD

**Issue by michaek** [keystonejs/keystone#3951]
### Steps to reproduce the behavior

```
yarn add keystone
yarn check
```

### Expected behavior

```
yarn check v0.19.1
success Folder in sync.
```

### Actual behavior

```
yarn check v0.19.1
warning "\u001b[2mchokidar#\u001b[22mfsevents#node-pre-gyp@^0.6.29" could be deduped from "0.6.32" to "node-pre-gyp@0.6.32"
error "\u001b[2mrename-function-calls#\u001b[22m\u001b[2mdetective#\u001b[22mesprima-fb" is wrong version: expected "3001.1.0-dev-harmony-fb", got "3001.0001.0000-dev-harmony-fb"
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

### Conclusion

This wouldn't be a huge deal, necessarily, but it leads to failing builds on heroku (still working on how to get the build to pass without `yarn check` passing). This isn't a direct problem with Keystone, it's a problem with the version resolution of esprima-fb, which is a transitive dependency of browserify (> module-deps > detective). The reason that it is a problem for Keystone, is that Keystone ships with browserify as a dependency, which in turn depends on an ancient (March 2014) version of detective.

Is it necessary for Keystone to ship with a front-end build dependency? I don't know enough about the admin internals to know if that's avoidable, but it seems like extending the runtime dependency graph broadly is inviting problems like this.

**Comment by michaek** [comment]
This is likely resolved as a "builds failing" issue by https://github.com/heroku/heroku-buildpack-nodejs/issues/367, but the underlying architectural question probably remains valid.

**Comment by thejameskyle** [comment]
The admin ui is generated with browserify when keystone starts. Can't remove it altogether

**Comment by thejameskyle** [comment]
I'm not sure if there's any fix here for keystone. Seems like something that needs to be resolved with esprima-fb.

I guess I'm just gonna close this 🤷‍♀️
