### ISSUE TITLE
node keystone not working

### ISSUE THREAD

**Issue by Pewpsockemz** [keystonejs/keystone#3957]
Iv'e cloned keystone
start a local mongodb database
ran 'npm install'
ran 'node keystone' and I get 

module.js:471
    throw err;

Ive used the yeoman generator and the demo site with only limited problems but cloning keystone and going through the same steps doesnt work. Ive looked all over to find a solution and havent found anything. I'm guess I havent install a dependency or something but its not clear. 

I'm no developer and just want to try out the beta for keystone. Any help would be greatly appreciated. And if there are supporting documents that I'm missing, a link to them would be nice too. Thanks

**Comment by jstockwin** [comment]
@Pewpsockemz I'm about to head out, so probably won't be able to reply to your response until tomorrow, but there must be some more error logging than this somewhere... 

Are you sure that's the only thing logged to your console?

**Comment by Pewpsockemz** [comment]
Oh sorry there is its:

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\keystone-source\keystone\keystone
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by jstockwin** [comment]
Ah, you've cloned keystone, that's your issue. 

What you really want to do is install the generator. Look on the website and follow getting started. 

Alternatively, with the clone of keystone you should be able to run `node test/e2e/server.js`. that'll run the test instance. 

As I said, you really want to be using the generator though.

**Comment by Pewpsockemz** [comment]
Will the generator have the beta features? the yo keystone app seems to have only the older version of keystone.

**Comment by jstockwin** [comment]
Yes, but once you've ran the generator you can run something like `npm install --save keystone@4.0.0-beta.4`. it should still work. 

Or just clone the demo project which is on `beta.1` then run the same npm install command.

**Comment by Pewpsockemz** [comment]
Ah thanks! You have been very helpful and much appreciated!

**Comment by jstockwin** [comment]
No worries. Please close this if you've got it working!
