### ISSUE TITLE
"Add New" option in Admin UI for relationship fields

### ISSUE THREAD

**Issue by crowecawcaw** [keystonejs/keystone#3962]
When filling in a relationship field for a list I have, it'd be very convenient to be able to include an "Add new..." option that would pop up the modal window for adding a new item.

For example, I currently have two lists, Donations and Persons, where Donations have a donor field that references Persons. When I add a new Donation, sometimes there is an existing Person I select from the typeahead, dropdown menu but other times, I wish there was an "Add New Donor" option that would pop up a model window, let me add a Person quickly, and then finish filling out the Donation. The "Add New" option could be enabled when creating the list:

<pre>Donation.add({
    donor: { type: Types.Relationship, ref: 'Person' , addNewOption: true}
})</pre>

**Comment by jstockwin** [comment]
This exists, but it's `createInline` not `addNewOption`. It's not yet in the documentation though, which is why you've not come across it.

**Comment by jstockwin** [comment]
@crowecawcaw Since you've 👍d my comment, I assume you're happy and am closing this issue. If this is wrong, please re-open and let us know what's still going wrong!
