### ISSUE TITLE
Blog Posts Lost after Update

### ISSUE THREAD

**Issue by redt3am** [keystonejs/keystone#3970]
### Steps to reproduce the behavior
The server was unexpectedly shutoff. After I restart it, I had issues starting the Keystone server, so I changed the Keystone version (was 0.3x) to the latest git version in package.json. After "updating" it worked, but my blog posts are gone. Other changes are still there. 

I looked in the database, and the previous blog posts are still there. 
### Expected behavior
Blog posts still there.
### Actual behavior
Blog posts gone.

**Comment by bassjacob** [comment]
@redt3am Where is your mongodb running? can you check if the posts are still available inside the database?

I'm not aware of anything in keystone that would cause dataloss, but let's see if we can figure out what happened.

**Comment by redt3am** [comment]
I see the posts are still there, but it looks like it is using a new db. I see how there are many versions of my website.  

> show dbs
xxxxx-s-website 0.203125GB
xxxxxand39s-website     0.203125GB
xxxxx-site     0.203125GB
xxxxx-website  0.203125GB
local   0.078125GB

**Comment by redt3am** [comment]
Ok so it looks like it was using the xxxxx-s-website instead of xxxxx-website. I copied the database and now I can see all of my old posts 
db.copyDatabase('xxxxxs-website', 'xxxxxx-s-website', '127.0.0.1')

**Comment by bassjacob** [comment]
great :+1: I'll close this issue then, but please reopen it if things aren't working. :tada:
