### ISSUE TITLE
mongoose connection collection letter filter

### ISSUE THREAD

**Issue by jjhesk** [keystonejs/keystone#3981]
Its the suggestions to mix and match with other frameworks and it often have filtered out the collection name not just by having a prefix but with the letter uppercase of the first letter. I propose to have additional callbacks to get custom letter cases of the collection name. 

The original block [mentioned](https://github.com/keystonejs/keystone/blob/master/index.js#L101-L109)
```javascript

Keystone.prototype.prefixModel = function (key) {
	var modelPrefix = this.get('model prefix');

	if (modelPrefix) {
		key = modelPrefix + '_' + key;
	}

	return require('mongoose/lib/utils').toCollectionName(key);
};
```

solution

```javascript

Keystone.prototype.prefixModel = function (key) {
	var modelPrefix = this.get('model prefix');
    var opts = {pluralization:this.get('collection name puralized') || true};
	if (modelPrefix) {
		key = modelPrefix + '_' + key;
	}

	return require('mongoose/lib/utils').toCollectionName(key, opts);
};
```

Can anyone make a PR for this?

**Comment by jjhesk** [comment]
The test result found out that there are some issues from using the new Letter case based collection name. It affects to the admin display panel from listing out the collection. Still not able to configure it out by checking on the `admin/client/App/screens/list/index.js`. Is that possible to give a hint @JedWatson

**Comment by thejameskyle** [comment]
Moving to #3985
