### ISSUE TITLE
Better date/datetime formatting support, defaults and internationalisation

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#399]
Leading on from #336:

* [All modern browsers support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_compatibility) the [ECMAScript Internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl). Using this to format dates in the browsers current locale should be the default.
* This default should still be override-able in the field config (implemented in #373 👍)
* The user user should also be able to override the format and store their preferences with the other list customisation in the browser (as per #375)
* Additionally, there was an intent for fields like `datetime` to support a format argument (on the field itself). This would use `momentjs` (or similar) to format the date on the server and return the pre-formatted string. (This might not be relevant to the admin UI.)

**Comment by MadeByMike** [comment]
@molomby looks like the related issues here have been merged. What's the status of this now?

**Comment by molomby** [comment]
Parts of this have been implemented but, as a concept, this is very incomplete. That said, I think it's probably dropped off the priority list in favour of more field-type-specific solutions. 🤷🏻‍♂️
