### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridis-com** [keystonejs/keystone#3993]

**Comment by Noviny** [comment]
Hi @lazaridis-com, we're redoing the documentation on #4102 at the moment. Once this lands, these issues should be resolved, as well as giving us a new keystone website with more complete documentation.

I'm closing this as an issue, but if you want to look at the changes in that PR, we'd love the feedback.

**Comment by lazaridis-com** [comment]
> I'm closing this as an issue,

As a general rule, you should not close issues that quick. And of course you should not close issues, until the issue at hand is **solved**.
 
> but if you want to look at the changes in that PR, we'd love the feedback.

Far too much change in one chunk (and I'm currently over the Meteor tutorials). 

(can you please for now reopen this issue, as I'm loosing track?)

**Comment by lazaridis-com** [comment]
@Noviny

**Comment by lazaridis-com** [comment]
@Noviny 

> I'm closing this as an issue,

As a general rule, you should not close issues that quick. And of course you should not close issues, until the issue at hand is **solved**.
 
> but if you want to look at the changes in that PR, we'd love the feedback.

Far too much change in one chunk (and I'm currently over the Meteor tutorials, see meteor/meteor/issues/8368). 

(can you please for now reopen this issue, as I'm loosing track?)

**Comment by lazaridis-com** [comment]
See the Meteor Project for a good `Development.md` example: meteor/meteor/pull/8267

**Comment by Noviny** [comment]
Hey,

Sorry, you're right that this shouldn't have been closed yet.

I'm going to come back to this once the new documentation site has landed, as we're revamping the entire documentation landscape. The issue raised her should be addressed by that.

Thanks for the link to how meteor is doing it, always good to have things to compare to.

**Comment by lazaridis-com** [comment]
@Noviny , here another reference to Meteor, this time "how to not do things": #8492

I tried to help with fixing some issues/PRs there - but its a hell of effort, due to very bad (or non-existent) processes.

As for you documentation:

You should fix 2 things with priority:

* The new user intro (a quick-start which brings e.g. a blog live in 15 min.)
* The new developer intro (a quick-start of how to setup a development environment).

After the quite negative experience @ Meteor, I'll most possibly give keystone another try

**Comment by lazaridis-com** [comment]
@Noviny , here another reference to Meteor, this time "how to not do things": meteor/meteor#8492

I tried to help with fixing some issues/PRs there - but its a hell of effort, due to very bad (or non-existent) processes, and due to a near-abandoned status of the tutorial project.

As for you documentation:

You should fix 2 things with priority:

* The new user intro (a quick-start which brings e.g. a blog live in 15 min.)
* The new developer intro (a quick-start of how to setup a development environment).

After the quite negative experience @ Meteor, I'll most possibly give keystone another try. If so, then I'll provide you with a new-user quick-start document (super tiny).

**Comment by Noviny** [comment]
@lazaridis-com We pretty much agreed with you on those two topics. The three things we are focusing on is a quick-start guide using the generator, a setting up guide for not using the generator, and making our method documentation more complete so there are fewer 'hidden' features.

**Comment by lazaridis-com** [comment]
very nice, but you should not await until this mega-issue (#4102) is processed. You can shrink the README now (I filed this issue over a month ago). Things must flow... flow... flow...
