### ISSUE TITLE
Fix the localisation of the address field

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#40]
The address field is currently pretty specific to Australian addresses, it should be fixed up to better support different international address formats.

Might be good to allow customisation at the model level for enabling and labelling the different subpaths supported by the location field.

Should also possibly tie in to a localisation setting for Keystone itself (shared by date formats, language, etc.)

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/fix-the-localisation-of-the-address-field
