### ISSUE TITLE
User signups

### ISSUE THREAD

**Issue by rudimk** [keystonejs/keystone#400]
Hi! While playing with Keystone, how does one sign up as a Keystone user? I couldn't find the right routes or views.

**Comment by arthurtalkgoal** [comment]
Hi @izifortune 

I tried to modify the ```exports.signin``` to my ```exports.signup```

however, I got the error ```Error: .get() requires callback functions but got a [object Object]``` when I map the route:
```
  app.all('/signup', routes.auth.signup);
```

Can you share more codes of your signup? appreciate it much.

```

exports.signup = function(lookup, req, res, onSuccess, onFail) {
```

**Comment by arthurtalkgoal** [comment]
Oh, I found that https://github.com/JedWatson/sydjs-site contains most of what i need for session and registration!

**Comment by morenoh149** [comment]
solved
