### ISSUE TITLE
s3 file adapter filename option issue

### ISSUE THREAD

**Issue by suqian1988** [keystonejs/keystone#4004]
### Steps to reproduce the behavior

in S3 file adapter,
add below code to have customized file name.
but the file name is still random created string

```js
myFile: {
  type: Types.File,
  storage: storage,
  filename: function (item, file) {
    console.log('item.id='+ item._id);
    return encodeURI(item._id + item.name);
  },
},
```

### Expected behavior

we can plugin our own filename

### Actual behavior

the file name is random string.

**Comment by mhoffmeyerDC** [comment]
I had the same issue with keystone-storage-adapter-s3.

@GwonHyeok had a [bugfix](https://github.com/GwonHyeok/keystone-storage-adapter-s3/commit/9db761ae0d138d02b7b7c59fa7e59f761f5b95e8).

I forked and updated the [README](https://github.com/mhoffmeyerDC/keystone-storage-adapter-s3) with the new option.

**Comment by sktt** [comment]
@mhoffmeyerDC this should already work. 

see the response in the pr https://github.com/keystonejs/keystone-storage-adapter-s3/pull/5
there's also an example in there. 

the generateFilename can look in two different ways
- Synchronous: `function (file, attempt) { return 'filename' }`
- Asynchronous `function (file, attempt, callback) { callback('filename')}`

**Comment by Noviny** [comment]
Thanks @sktt for answering this. Closing this as an issue. Happy to reopen it if you feel this needs changes.
