### ISSUE TITLE
S3 file upload

### ISSUE THREAD

**Issue by suqian1988** [keystonejs/keystone#4005]
### Steps to reproduce the behavior
set header as this:
headers: {
			'x-amz-acl': 'public-read',
		},

upload failed with 403 error
### Expected behavior
upload can success.
### Actual behavior
upload failed with 403 code

**Comment by sktt** [comment]
I also had this problem, and I think it was because 

> This latest signature version is supported in all regions and any new regions after January 30, 2014 will support only Signature Version 4.

That includes eu-central-1 and cn-north-1

But knox does not support it. https://github.com/Automattic/knox/issues/254

I replaced it with the official aws-sdk here: https://github.com/keystonejs/keystone-storage-adapter-s3/pull/15.

**Comment by stennie** [comment]
This issue was resolved in the [`keystone-storage-adapter-s3` v2.0.0 release]( https://github.com/keystonejs/keystone-storage-adapter-s3#change-log), which replaces the unmaintained Knox library with the official AWS JavaScript SDK.
