### ISSUE TITLE
Pre-save hook for password field is broken

### ISSUE THREAD

**Issue by OskarKlintrot** [keystonejs/keystone#4020]
### Steps to reproduce the behavior
Use the latest version from Github master branch. Update password according to [this comment](https://github.com/keystonejs/keystone/issues/1254#issuecomment-85999366) and then run
```
user._.password.compare(password, function (err, isMatch) { console.log('err, isMatch:', err, isMatch) })
```

### Expected behavior
No errors, `isMatch` returns true

### Actual behavior
Err is `Not a valid BCrypt hash.` and `isMatch` is null. 
____________

This issue seems to have been introduced in commit 4296233. If I just go back one version of that file and copy/past into the keystone folder in `node_modules` everything starts to work just fine again.

**Comment by romecode** [comment]
What he said. Getting the same thing... bumped into this creating users via an update file... the password stored ended up being a non hashed string version leading to the mentioned behavior.

**Comment by JedWatson** [comment]
Thanks for the report @OskarKlintrot

I'm pretty sure this is fixed with that commit - turns out you need to access the property on the object using array notation, not `get` and `set` although the other changes from that commit should be good.

Please let me know if you can still replicate it!

**Comment by OskarKlintrot** [comment]
I just copy/pasted `PasswordType.js` into `node_modules` instead of reinstalling everything (which takes a crazy amount of time, even with yarn). Without doing any changes in my own code it's working again now! Thank you @JedWatson! 👍

**Comment by OskarKlintrot** [comment]
Sorry, I was a bit too quick. It still dosen't work. Using a clean install of the latest `master`-branch with the "old" `PasswordType.js` works just fine but not with the latest 2 commits for that file.

**Comment by OskarKlintrot** [comment]
And now it works again... I have been trying to find the issue but it just started to work again without me doing any changes in the code. Strange, I don't really know what to make of it...
