### ISSUE TITLE
Keystone  File Type image url

### ISSUE THREAD

**Issue by shivshankar3578** [keystonejs/keystone#4027]
@keystone 0.3-beta5 
 i'm using storage adapter fs. file upload working but show only filename. i'm using

```
var myStorage = new keystone.Storage({
  adapter: keystone.Storage.Adapters.FS,
  fs: {
    path: keystone.expandPath('./public/uploads/items'),
    publicPath: '/public/uploads/items'   ,
  },
schema: {
	size: true,
 	mimetype: true,
	path: true,
	originalname: true,
	url: true,
	},
});
```
`image:{ type: Types.File, storage: myStorage },`
Update:
i check database this store wrong url. it should be **uploads/items/re7o6E5ziMJBBWte.jpg**
![image](https://cloud.githubusercontent.com/assets/10707846/23580198/f9cbd814-0122-11e7-85a4-ce108374c971.png)

**Comment by soupaJ** [comment]
@shivshankar3578 add a slash to the end of your publicPath in the `fs` options.
Like:
```
  fs: {
    path: keystone.expandPath('./public/uploads/items'),
    publicPath: '/public/uploads/items/',
  },
````

**Comment by Noviny** [comment]
I think @soupaJ has the correct solution. Closing this as answered, but happy to reopen it if we need to.
