### ISSUE TITLE
How to XMLHttpRequest() sends a JSON object to Keystone and stores it into a field of a model

### ISSUE THREAD

**Issue by duythang** [keystonejs/keystone#4040]
Dear Keystone community

I am trying to send a JSON object to Keystone (using  POST request of XMLHttpRequest()) to store it into a field of a model. Although, i send JSON object successfully, JSON object still cannot save into a field of my model. 
These are my codes: 

=======================Model code======================
```ruby
// Ajax.js (Ajax model)
var keystone = require('keystone');
var Types = keystone.Field.Types;

var Ajax = new keystone.List('Ajax');

Ajax.add({
    content: {type: String,},
});

Ajax.register(); 
```

======================Route code======================

```ruby
// Ajaxtest.js (store in route folder)
var keystone = require('keystone'), 
    Ajax = keystone.list('Ajax');

exports = module.exports = function(req, res){
    var view = new keystone.View(req, res),
    locals = res.locals;

    view.on('init', function (next) {
        next();
	});

    view.on('post', function (next){

        var ajaxData = {
                    content: req.body
				};

            var newAjax = new Ajax.model(ajaxData);
            
	   newAjax.save(function(err) {
                    console.log(req.body);
				});
    });
    // Render the view
	view.render('ajax/ajaxtest');
}
```

========================Template code=====================
```ruby
// ajaxtest.twig
<!DOCTYPE html>
<html>
<body>

<h1>The XMLHttpRequest Object</h1>

<button type="button" onclick="loadDoc()">Request data</button>

<p id="demo"></p>
 
<script>
function loadDoc() {
  var myObj = { "name":"John", "age":31};
  var myJSON = JSON.stringify(myObj);
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("demo").innerHTML = this.responseText;
    }
  };
  xhttp.open("POST", "/ajax", true);
  xhttp.setRequestHeader("Content-type", "application/json");
  xhttp.send(myJSON);
}
</script>

</body>
</html>
```

With these codes, at Keystone side, i can receive req.body = "{ name: 'John', age: 31}". However, this string cannot be stored into field "content" of Ajax mode.

Hope you can help me.
Thank you so much

**Comment by creynders** [comment]
Probably because req.body isn't a string, but an object with fields `name` and `age`, which doesn't match your model declaration. You'll have to turn it into a string first, with `content: JSON.stringify(req.body)`

**Comment by duythang** [comment]
@creynders: Great, thank you. i tried and your way is true. But, i am confusing that in ajaxtest.twig, i used JSON.stringify(myObj) before sending. So, why is req.body not string at Keystone server?

**Comment by creynders** [comment]
Because express' body parser automatically parses JSON. I'm closing this for now, but if this is still an issue, you can re-open it.

**Comment by duythang** [comment]
Thank you
