### ISSUE TITLE
How to render a String or Json objest

### ISSUE THREAD

**Issue by duythang** [keystonejs/keystone#4041]
Hello keystone community

As i know, Keystone uses _view.render()_ to render Web page under some engines (e.g., jade, twig) to user typically. So, can Keystone render a String or a Json object ?
I am refering user's case that user uses Ajax (i.e., XMLHttpRequest) to load necessary content to web as this code:

```ruby
 <!DOCTYPE html>
<html>
<body>

<h1>The XMLHttpRequest Object</h1>

<button type="button" onclick="loadDoc()">Request data</button>

<p id="demo"></p>
 
<script>
function loadDoc() {
  var myObj = { "name":"John", "age":31};
  var myJSON = JSON.stringify(myObj);
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("demo").innerHTML = this.responseText;
    }
  };
  xhttp.open("POST", "/keystoneserver", true);
  xhttp.setRequestHeader("Content-type", "application/json");
  xhttp.send(myJSON);
}
</script>

</body>
</html>
```
In this case, **this.responseText** is necessary content which need to be load.

Thank you so much.

**Comment by madhavinath** [comment]
hi..
i need navigating pages in  post login.any help?

**Comment by thejameskyle** [comment]
@duythang I assume you mean you want to preprocess the json response before it reaches the client. Are you not able to do that on the client in JS?

**Comment by Noviny** [comment]
Closing as answered by James.
