### ISSUE TITLE
Can we use multi engine templates at the same time in Keystone

### ISSUE THREAD

**Issue by duythang** [keystonejs/keystone#4049]
Hello
I am confusing that keystone can suppost to use multi engine templates (i.e, twig, pug ...) at the same time.
For example, i want to include a **pug** template inside **twig** template. 

Thank you so much

**Comment by Noviny** [comment]
@duythang We don't have any support for doing this, and I'm not sure what the use-case would be, as this seems to add a lot of complexity to a project for little benefit. Happy to hear your usecase though.
