### ISSUE TITLE
Syntax Error: Invalid number, expected digit but got: \"f\".

### ISSUE THREAD

**Issue by Temkit** [keystonejs/keystone#4049]
# Bug report

Syntax Error: Invalid number, expected digit but got: \"f\".

## Describe the bug

Using KeystoneJS with mongoDB.

when creating a new element with this query :

**with endpoint**

```
mutation{
  createEntree(data:{
  quantite: 12,
  produit: { connect: { id: "5f96d1ad53f63f947f5c9da6" } },
  fournisseur: { connect: { id: "5f974bfce1a960845a382976" } },
  entreprot: { connect: { id: "5f974c0be1a960845a382977" } },
  lot: "12",
  prixAchat: 23,
  garantie: 24
}){id}
}
```
when i delete the line 

` produit: { connect: { id: "5f96d1ad53f63f947f5c9da6" } },`
 
the query works fine.

**on Browser**

> [GraphQL error]: Message: Syntax Error: Invalid number, expected digit but got: "f"., Location: [object Object], Path: createEntree
> CreateItemModal.js:129 Uncaught (in promise) TypeError: Cannot read property 'id' of null
>     at _callee$ (CreateItemModal.js:129)
>     at tryCatch (runtime.js:63)
>     at Generator.invoke [as _invoke] (runtime.js:293)
>     at Generator.next (runtime.js:118)
>     at asyncGeneratorStep (main.88e9afa5761d66bb049b.bundle.js:84072)
>     at _next (main.88e9afa5761d66bb049b.bundle.js:84074)

the wired part is that when i check the document it's saved with all data (product included), and when i do an update there is no error with the green toast ..
## Screenshots

<img width="1004" alt="Capture d’écran 2020-10-27 à 00 54 32" src="https://user-images.githubusercontent.com/13275723/97240729-583dcd80-17ef-11eb-9b2c-2960e0b5bb0e.png">

when i delete the line 

` produit: { connect: { id: "5f96d1ad53f63f947f5c9da6" } },`

<img width="1001" alt="Capture d’écran 2020-10-27 à 00 58 22" src="https://user-images.githubusercontent.com/13275723/97240807-8de2b680-17ef-11eb-8583-5717ad087558.png">

**Comment by Temkit** [comment]
i changed the name of the field _produit_ and it worked .....

**Comment by Temkit** [comment]
The error was du to a hook, i was getting an object ID and assumed ( wrongly ) it was a String ....

**Comment by Redskinsjo** [comment]
can you explain again how you found the solution? 
I am actually having the same error, request works in graphiql, but not in react. 
the error is explicit, it waits a number but found a string. But it works with a string in graphiql.
dont understand why
