### ISSUE TITLE
Custom SMTP & Data storage

### ISSUE THREAD

**Issue by franzsilva** [keystonejs/keystone#405]
Hello, i was wondering if there is a way to use my own smtp and file storage and how would i  accomplish this. 

Thank you

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on productpains:

- https://productpains.com/post/keystonejs/custom-mail-services
- https://productpains.com/post/keystonejs/custom-storage-adapters
