### ISSUE TITLE
Link preview is a span instead of a link

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#4055]
I'm using keystone 4.0.0-beta.5

When I add a file everything works just fine, but in the file field inside the admin I get a link that doesn't work because is a span. When I change the tag from **span** to **a** it works.

``` javascript

const publicPath = 'offers/'
const storage = new Storage({
	adapter: Storage.Adapters.FS,
	fs: {
		path: join(__dirname, '../../../static/' + publicPath),
		publicPath,
	},
	schema: { url: true },
})

// And in my schema
image: { type: Types.File, storage, initial: true, required: true },

```

Also, how I can preview the image in the admin?

![screenshot](https://cloud.githubusercontent.com/assets/3449006/23508147/4313c306-ff48-11e6-8792-66e179a8843a.jpg)

**Comment by giusepperj** [comment]
+1

**Comment by r1cebank** [comment]
+1

**Comment by w0rldart** [comment]
+1

**Comment by gggllm** [comment]
+1

**Comment by w0rldart** [comment]
I think the project is abandoned :cry:

**Comment by ellipticaldoor** [comment]
😢

**Comment by Noviny** [comment]
Rejoice! #4174 has been merged.

(new beta release likely on Monday, which will have the fix in it)

**Comment by proteye** [comment]
+1
