### ISSUE TITLE
Keystone Beta 4.0.0-beta.5 - Issue with Pagination

### ISSUE THREAD

**Issue by whnunlife** [keystonejs/keystone#4056]
Found a issue when updating to 4.0.0-beta.5. While using pagination, I get back only the results in the "where" clause, but the total count returned, is not specific to the conditions of the where clause, but shows the total number of documents in the collection.

Example Query:

```
var q = Contact.paginate({
  page: req.query.page || 1,
  perPage: req.query.limit || 10,
  maxPages: 10
}).where('site', site);
```

Keep in mind, that "site" is a relationship to contact. A contact always has a "site".

In Keystone 0.3.21, the query returns the correct "total" count. So say I have 20 contacts in site "a", I'll get back 10 contacts, with a total of 20 to paginate thru.

But in Keystone 4.0.0-beta.5, with the same query, I get back 10 contacts, but the total displays an incorrect number, say 60 contacts, the total number of documents in the collection.

**Comment by mx781** [comment]
Encountered the same issue. Digging through the source, it seems this can be fixed by passing a `filters` parameter that accounts for all your `where(...)` calls. In your code above, that would translate to:

```
var q = Contact.paginate({
  page: req.query.page || 1,
  perPage: req.query.limit || 10,
  maxPages: 10,
  filters: {"site": site}
}).where('site', site);
```

That aside, it's certainly unintuitive that .paginate has to be called on a list, rather than chaining onto the query. If possible, this would be a nice change in the v4 (or later). While passing `filters` is trivial here, it can be more complicated if you have a lot of conditional where calls.

**Comment by whnunlife** [comment]
Ahhh, very interesting. I'll give this a shot and report back. Thanks.

**Comment by madhavinath** [comment]
got same issue..resoleved it by repalcing where with filters.

**Comment by whnunlife** [comment]
So, after looking at my code, I have a change of conditionals based on the users current nav, where I then add on to the q instance. This could get ugly...

**Comment by thejameskyle** [comment]
Moving to #4078

**Comment by Noviny** [comment]
After talking it through, we've decided to deprecate pagination. Docs have been updated on how to use it without creating this error, closing this in favour of #4126

**Comment by whnunlife** [comment]
@Noviny Dumb question, but where can I find the docs on the latest alpha release, where this has been updated?

And just to confirm, moving forward, there will be no pagination support to use correct?

**Comment by Noviny** [comment]
We have a [beta documentation site](http://censor-conventions-37504.netlify.com/methods/paginate) that we are working on alongside our beta release. Subject to change, but that's the paginate documentation.

Keystone 4 will have pagination as documented there.

**Comment by whnunlife** [comment]
Perfect, thanks!

**Comment by yao23** [comment]
How to user filters for where('id').in(`${id_array}`)?
filters: {'id': [id_array]} not working

@mx781 @Noviny @thejameskyle

**Comment by yao23** [comment]
The following one works:

```
filters:{id:{$in:[id_array]}}
```
