### ISSUE TITLE
Can't access admin UI / make it past sign in page in production

### ISSUE THREAD

**Issue by jabusir** [keystonejs/keystone#4065]
I've read all the relevant issues to this, but still couldn't find a solution. 

My keystone configuration has secureCookies set to false, and the secure property on the cookie object set to false as well. My cookie secret is set to a static string as well, and I've integrated sessionStore according to this:

https://www.keystonejs.com/keystonejs/keystone/#sessionstore

I don't really care for the security of the app, I just want to be able to have the most basic login functionality. 

## Expected behaviour

I expect to type in the email and password and be forwarded to the the admin dashboard. However I keep being rerouted to the sign in page. The backend logs show the request perfectly fine with no errors, and the network tab in the developer tools show a 200 status on the request. 

## System information

The server is deployed on a dockerized EC2 Ubuntu instance, and Firefox is the browser I'm using.

I apologize if this is a redundancy. The relevant issues pertain to setting up nginx, reverse proxies etc... I'm not sure I want to do this as this is just a very minor side project who's security is trivial.

**Comment by nikosolihin** [comment]
Having the same issue. Did you manage to find a fix?

**Comment by jabusir** [comment]
Hi Niko,

Yes. You need to add a mongo session store, otherwise your Keystone application won't scale past a single operation. 

https://www.keystonejs.com/keystonejs/keystone/#sessionstore

Refer to this. Hope it helps
