### ISSUE TITLE
How to avoid using Cloudinary? I want to save the images only in mongoDB not on Cloudinary

### ISSUE THREAD

**Issue by rishabhrawat11** [keystonejs/keystone#4066]

**Comment by Noviny** [comment]
There are a couple of ways to approach this. First, you can extend the underlying mongoose schema to have a field that takes in the binary of an image file, similar to what is discussed here:
http://stackoverflow.com/questions/4796914/store-images-in-a-mongo-database

This method will not have any admin UI available.

Alternately, you could use the [fs storage adapter](https://github.com/keystonejs/keystone/tree/master/lib/storage/adapters/fs) to save the files locally, although not in mongo.

Finally, you could write a new storage adapter that read the image and saved it as a binary to mongo.

**Comment by 00SteinsGate00** [comment]
So for digging up this old Issue, but is there really no way to have an image gallery with an Admin UI without using Cloudinary?
