### ISSUE TITLE
install error!

### ISSUE THREAD

**Issue by robbin-zhongan** [keystonejs/keystone#4073]
### Steps to reproduce the behavior
when i install the project run the shell "yo keystone", i encountered the problem as below.

### Expected behavior
install success.

### Actual behavior
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1036:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1059:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/robbin/keystone-test/zhongan-cms/node_modules/buffertools
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:buffertools@2.1.4 buffertools@2.1.4 install: `node-gyp rebuild`
npm WARN install:buffertools@2.1.4 Exit status 1

**Comment by bassjacob** [comment]
Looks like you're connecting to the internet through a proxy, is that correct?

**Comment by robbin-zhongan** [comment]
No, i don't use a proxy. I can ping the ip as below. 
![image](https://cloud.githubusercontent.com/assets/26134899/23694215/84608edc-0413-11e7-9b24-014ee744ef93.png)

When i reinstall it. it's successful.

**Comment by bassjacob** [comment]
how odd. if it becomes reproducible let us know :smile:
