### ISSUE TITLE
Keystone 4.0.0-beta.5 - Colour picker type doesn't preview selected colour

### ISSUE THREAD

**Issue by tomhardman0** [keystonejs/keystone#4074]
Hi All. Firstly - thank you very much for Keystone, it's excellent. I'm looking to become much more active and contribute to the community so I thought I'd start by raising some issues and seeing if there's anything I can fix myself!

### Steps to reproduce the behavior
Add a field of Types.Color to a model. In the admin UI create a new item in that list. You can see the button for the colour picker, once you've used it to select a colour there is no way to know what that colour looks like (apart from understanding the hex?).

<img width="418" alt="screen shot 2017-03-08 at 08 01 24" src="https://cloud.githubusercontent.com/assets/9137745/23695241/1412f7d8-03d6-11e7-9a75-96b1b34d4b26.png">

### Expected behavior
The colour picker button would show a preview of the colour selected.

### Actual behavior
The colour picker button remains grey.

Thanks all!

**EDIT**: Keystone 4.0.0-beta.5

**Comment by aaronkendall** [comment]
+1

**Comment by rhysburnie** [comment]
Hi,

If you remove the padding from `.base_b0alru-o_O-base_hn2280` which is (0 1em) intended to create the width and instead give the inner span 2em it will work.

```
.base_b0alru-o_O-base_hn2280 {
   /* ... stuff ... */
  padding: 0;
}
.swatch_zyyjt9 {
    border-radius: 1px;
    box-shadow: inset 0 0 0 1px rgba(0,0,0,0.1);
    display: block;
    height: 100%;
    width: 2em;
}
```

**Comment by rhysburnie** [comment]
Actually, you just need this:

```
.base_b0alru-o_O-base_hn2280 {
   /* ... stuff ... */
    padding: 0;
    width: 2.4em; /* more square looking for me */
}
```
