### ISSUE TITLE
File field type errors/problems

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone#4079]
Collecting all issues related to the display of File field types in the admin UI in one place, as this likely needs a look thinking about all of them.

This ticket can be consered resolved when the following are resolved:

- [ ] #4070 
- [ ] #4064 
- [ ] #4055
- [ ] #4027 
- [ ] #4017 
- [ ] #4005 
- [ ] #4004

**Comment by thejameskyle** [comment]
Should this be a milestone/project instead?

**Comment by Noviny** [comment]
Yes.

**Comment by thejameskyle** [comment]
Closing in favor of https://github.com/keystonejs/keystone/milestone/8
