### ISSUE TITLE
SearchFields Option

### ISSUE THREAD

**Issue by PaulMoor** [keystonejs/keystone#4086]
Dear friends, I'm a new to keystone.

I'm wondering is there and option at SearchFields Options Post model to specify all available fields for the search. 

As I understand the SearchFields Options uses the String that specify the fields will be used for the search request. But how to tell Keystone to search all available fields in the model?

Excuse me for maybe such a stupid question.

**Comment by Noviny** [comment]
There is no option to specify all unless you provide all the options.
