### ISSUE TITLE
Nodejs 7.7.1 support (7.6.0 as well?)

### ISSUE THREAD

**Issue by elektrobober** [keystonejs/keystone#4092]
Hey were! I'm finding myself in bit confused situation, while I updated my node js version and tried to run my keystone project. My nodejs current version - 7.7.1, and when I type 'node keystone' (actually well 'gulp', because I'm using it for starting keystone and make some other manipulations) - just nothing happens. 

As I understand where is some issues with events.onMount function, but my knowledge is not so deep.

### Steps to reproduce the behavior
update node version to 7.7.1
run 'node keystone'

### Expected behavior
I expect to see something like this: 
------------------------------------------------
KeystoneJS Started

### Actual behavior
No output in console at all.

To fix this I'm using  npm n package to manage my nodejs version. It's ok with 6.9.4

**Comment by bassjacob** [comment]
Hi @elektrobober,

when you updated your node version, did you rebuild your native modules by running `npm rebuild` inside your repository folder?

**Comment by elektrobober** [comment]
Hi @bassjacob, no, I didn't.
But I try to start the new project from scratch  with yeoman, just like in getting started tutorial at http://keystonejs.com/ and face the same issue.

**Comment by elektrobober** [comment]
And now I try to do `npm rebuild` with node 7.6.0 -  and where is same issue

**Comment by pettyron** [comment]
You're running into the vast difference between the 6.9.x LTS (Long Term Support) and the 7.x Stable release. If you look at your console after running npm install you should see warnings about the modules that will not work with 7.x (Things like UUID and Graceful-fs come to mind of the top of my head). If you install with 6.9.x you should see warnings about what is eventually going to get booted come the LTS release of version 7. In all likelihood you're going to be stuck using the LTS Node. It's going to be a major overhaul to add 7.x support for any module(s) let alone this entire CMS.

https://github.com/nodejs/node/wiki/Breaking-changes-between-v6-and-v7

**Comment by peterpme** [comment]
:wave: 

Node 7.7.2 and Keystone 4.0.0-beta.5 work well together :)

FWIW @pettyron I checked that list against Keystone's source code and didn't see anything crazy :smile:

**Comment by thejameskyle** [comment]
@elektrobober what version of keystone are you using?

**Comment by thejameskyle** [comment]
@elektrobober Just run this in your repo:

```
cat node_modules/keystone/package.json | grep '"version":'
```

**Comment by elektrobober** [comment]
@thejameskyle it's "version": "0.3.22"

**Comment by thejameskyle** [comment]
We're pushing ahead with 4.0 right now which _should_ have support for the latest versions of Node (we need to add Node 7 to our testing matrix).

There are any plans right now to continue supporting Keystone 3 for changes like this. So I'm going to close this issue, but if you would like to work on updating v3 to have Node 7 support yourself I'd be happy to speak to you about it.

**Comment by creynders** [comment]
I'm running keystone 0.3.22 with Node 7.7.1 (as installed with `n`) without any problems. Have you tried running `node keystone.js` directly, i.e. bypassing gulp @elektrobober ?
