### ISSUE TITLE
Setting EJS template delimiter affects admin render

### ISSUE THREAD

**Issue by wosevision** [keystonejs/keystone#4093]
### Steps to reproduce the behavior
Use a custom delimiter (`ejs.delimiter = '$';`) to produce EJS templates (using the `'custom engine'` config option).

### Expected behavior
Delimiter is respected in view templates.

### Actual behavior
Delimiter is overrespected (humbly bowed-down-to) by every EJS template in the realm, including admin UI (such as the signin page).

---------------

It seems logical to provide a delimiter override that won't nuke the rest of the app, right? Maybe something like...?
```
keystone.init({
    'custom delimiter': '$'
})
```

**Comment by thejameskyle** [comment]
- Looks like there are two places where ejs is used in keystone:
  - [admin/server/routes/signin.js](https://github.com/keystonejs/keystone/blob/547dd5fa1b014f5846e9b06e87304066a78aa683/admin/server/routes/signin.js#L22)
  - [admin/server/routes/index.js](https://github.com/keystonejs/keystone/blob/c4789388ef09d09f39585f68b2a6fc898b7da040/admin/server/routes/index.js#L90)
- EJS [allows you to pass a custom delimiter into renders](https://github.com/mde/ejs#custom-delimiters) 

If you update those places in keystone to have a hardcoded delimiter it should prevent keystone from being affected by a custom global delimiter.

**Comment by matthewlynch** [comment]
I'd like to pick this up as a good first PR tonight if no one else is looking at it already 🙂?

**Comment by wosevision** [comment]
@matthewlynch Fine by me if you want dibs! I haven't had a lick of time the past week.
