### ISSUE TITLE
Ability to use a list of master data

### ISSUE THREAD

**Issue by tusharmath** [keystonejs/keystone#410]
First, this is the best CMS tool I have come up with so far. Great Job guys!

My question is 
1. Is there a way to handle master data sets ? I want to be able to select cities and localities which are only available in my database?
2. Is there as way to open the map in the admin ui to be able to save lat, lng by clicking on the map?

**Comment by dcousens** [comment]
Hey @tusharmath, sorry this was ignored.

1. This sounds like a basic query?  Was there any reason you felt you weren't able to do this?
2. I'm not aware,  but maybe @JedWatson could chime in?

**Comment by mxstbr** [comment]
1. Can be done with Select fields, not sure what the problem there is

2. is on ProductPains: https://productpains.com/post/keystonejs/location-fields-with-google-maps-to-get-latitude-and-longitude-autofilled

I'll close this issue for now, feel free to comment again and reopen this!
