### ISSUE TITLE
Generic Array Type

### ISSUE THREAD

**Issue by kadosh1000** [keystonejs/keystone#4106]
@JedWatson @mxstbr 
I think it would be great to have a generic Array type.
So in case I want the user to be able to insert multiple email addresses I would be able to just do something like :

`emails : {type: Types.Array, subType : Types.Email}`

In the db it will be shown the following way:

`email : [
 "email1", "email2"
]`

I think this would be great to have that feature that will allow us to create arrays of whatever type we like.
**This way it would be also possible to let out the TextArray, NumbersArray, CloudinaryImages and LocalFiles types.**

I think the implementation of such type should be pretty easy and won't take a lot of time.

Let me know what you think of it.

**Comment by peterpme** [comment]
Hey @kadosh1000 open up a PR and make it happen! 😄
