### ISSUE TITLE
Model Validation error on creating new model instance

### ISSUE THREAD

**Issue by AMRoche** [keystonejs/keystone#411]
Behaviour Encountered :
Model Validation expects and element to have a value as it has required:true set in its' parameters, but initial:false also set.

Behaviour Expected :
Model Validation should ignore this until it comes to fleshing out the information in the model.

Steps to replicate :
Add a field to the default post model with required:true and initial:false set as parameters with one other parameter also set to required:true.
Try and create a new instance of the model.

**Comment by creynders** [comment]
Stale
