### ISSUE TITLE
many relationship unwanted overwritten 

### ISSUE THREAD

**Issue by suqian1988** [keystonejs/keystone#4110]
### Steps to reproduce the behavior
I have a many relationship in the model, say categories, after I update it with some value, if I update some other fields, say, title, after update title, the categories field is overwritten to empty.
### Expected behavior
don't update the many relationship field.
### Actual behavior
I have a many relationship in the model, say categories, after I update it with some value, if I update some other fields, say, title, after update title, the categories field is overwritten to empty.

**Comment by Noviny** [comment]
This sounds like a symptom of #4030, which we have merged a fix for, and will be solved in the next keystone version.

Does that sound right, or is there something else I should be considering?

**Comment by suqian1988** [comment]
yes, same issue.

when will the new release out? is the fix in github already? May I take a look the code?

thank you so much.

sq

**Comment by Noviny** [comment]
It's fixed on the master branch, you can see the fix we implemented [here](https://github.com/keystonejs/keystone/pull/4035/files).

Can't speculate on when the next release will go out, but I'm going to give a tentative soon.

Closing this as an issue.
