### ISSUE TITLE
4.0.0-beta5 admin not rendering on Ubuntu server

### ISSUE THREAD

**Issue by ghost** [keystonejs/keystone#4122]
Please not: This was not using Yeoman build.
Following the instructions and using the demo version of the keystone beta I got it working fine on my local server but  could not get the React admin panel app to load on an Ubuntu server. The login  showed but once logged in successfully there was no admin panel visible. I inspected the html to see the main React component element wrapper tags were there but nothing else seems to be rendering.

I'm only running on 1g / 1 cpu on a digital Ocean droplet, could this be the reason?

**Comment by matthewlynch** [comment]
Hi Ghost,

Are you getting any 404/500 errors on the Network Tab inside of the browser DevTools?

Could you provide some more information on how the node app is being run on the server?

**Comment by tomheathershub** [comment]
@ghost i have this issue also, i can run my project fine locally (a slightly older version) but local and digital ocean fails with the latest version...

**Comment by matthewlynch** [comment]
@tomheathershub Could you please check if you're getting any console errors or network errors?

**Comment by tomheathershub** [comment]
So when it is running on digital ocean it keeps crashing after login same as @ghost empty main React component element. (see screenshot)

```
(index):31 GET http://46.101.23.220:3000/admin/js/admin.js net::ERR_CONNECTION_REFUSED
(index):30 GET http://46.101.23.220:3000/admin/js/fields.js net::ERR_CONNECTION_REFUSED

```
![image](https://user-images.githubusercontent.com/5075794/29183725-a8d5b0d2-7dfb-11e7-9e5b-eb3354873147.png)

Also on the server side: 

```
theather@london-1:/var/www/keystone-cms/cms$ node keystone.js 
Application Mounted
------------------------------------------------
KeystoneJS Started:
TH Admin is ready on port 3000
------------------------------------------------
Application Started
GET /admin/ 200 67.971 ms
GET /admin/ 200 25.829 ms
Killed

```

**Comment by tomheathershub** [comment]
@ghost @matthewlynch solved this by increasing droplet size from 512mb to 1gb (not surprising really) hope that helps

**Comment by matthewlynch** [comment]
@tomheathershub Thats really strange but I'm glad you solved the issue!

**Comment by Noviny** [comment]
@matthewlynch @tomheathershub I'm closing this as solved. Feel free to reopen/let me know if it isn't.

**Comment by oliverbenns** [comment]
I too get this issue. Also running a 512mb Digital Ocean droplet. It's kind of surprising I'd need to upgrade given it's the only process on the machine.
```
 npm > GET /keystone/ 200 18.205 ms                                                                                                                                 
 npm > Killed
```
