### ISSUE TITLE
Markdown Code causes spacing problems

### ISSUE THREAD

**Issue by cwbuecheler** [keystonejs/keystone#4152]
### Expected behavior

When entering code in Markdown, the resulting HTML should reflect the spacing provided by the user. eg:

&#96;&#96;&#96;
line
&nbsp;&nbsp;indented line
line
&#96;&#96;&#96;

should produce:

&lt;pre&gt;&lt;code&gt;
line
&nbsp;&nbsp;indented line
line
&lt;/code&gt;&lt;/pre&gt;

### Actual/Current behavior

&#96;&#96;&#96;
line
&nbsp;&nbsp;indented line
line
&#96;&#96;&#96;

Produces:

&lt;pre&gt;
&nbsp;&nbsp;&lt;code&gt;line
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indented line
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/code&gt;
&lt;/pre&gt;

for a result of:

```
line
          indented line
        line
```

### Steps to reproduce the actual/current behavior

Create a markdown field, fill it with the above code, and then use {{{this.content.html}}} in a handlebars template (I have not tested in other template languages).

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 0.3.19
| Node             | 7.7.2

**Comment by cwbuecheler** [comment]
Pretty sure the issue is here: 

https://github.com/keystonejs/keystone/blob/v0.3.x/admin/public/js/lib/marked/marked.js#L767

But it doesn't seem like v0.4 uses marked, so it may be fixed in newer versions.

**Comment by Noviny** [comment]
Have confirmed this is working correctly in keystone4, closing this as an issue.

**Comment by cwbuecheler** [comment]
Thanks. I'll make it a priority to upgrade.
