### ISSUE TITLE
No schema methods for CloudinaryImage (single)

### ISSUE THREAD

**Issue by fbeaudet** [keystonejs/keystone#416]
It seems schema methods for CloudinaryImage don't work, but, they work on CloudinaryImages (with a s).
I tried to use the limit() method in a template for a single cloudinary image field and it says it's undefined.
The field apply() method isn't called at all when a view is rendered. I'm currently investigating, if you have an idea about what's going on, please help. Should be simple to fix.

**Comment by mxstbr** [comment]
I'll close this due to inactivity and likelihood of having been fixed—please let me know in the comments if this issue still affects you!
