### ISSUE TITLE
I am not able to upload file with space.Is there any solution for this in keystone?

### ISSUE THREAD

**Issue by Jugalkish** [keystonejs/keystone#4165]

**Comment by sktt** [comment]
I am not able to repro this in keystone-test-project. Can you?

**Comment by Jugalkish** [comment]
Hi Sktt, if you use default keystone setting than file will be uploaded with random file name with no space but when you code for original file name than you will see this issue. Please check and let me know if you have solution

**Comment by sktt** [comment]
Is your actual issue that `originalname` does not work ? If you want a different filename then try to pass a custom `generateFilename` to your storage adapter. For example

```
var storage = new keystone.Storage({
	adapter: keystone.Storage.Adapters.FS,
	fs: {
		path: keystone.expandPath('./uploads'),
		publicPath: '/public/uploads/',
		generateFilename: function(file) {
			return file.orignalname
		}
	},
	schema: {
		url: true
	},
});

```

**Comment by Jugalkish** [comment]
Hi Sktt, Thanks for your suggestion but I have already done that the issue i am facing when i have space in the name of file.It is showing error i think it is because of Java code which i have written for validation of that module.As java do not accept space.I am working on that to correct it.

**Comment by Jugalkish** [comment]
Hi Sktt, Do you know if we can trim space or put special characters at the time of upload the file in file name.

**Comment by Jugalkish** [comment]
It is done after using replace command with originalname..... thanks .... I am closing this
