### ISSUE TITLE
sass files don't compile when switching from less

### ISSUE THREAD

**Issue by johnnyluu** [keystonejs/keystone#4176]
### Expected behavior

I set the project up using the yo generator with less chosen as the default css preprocessor, but now we've decided to use sass instead. I replaced 'less' with 'sass' in keystone.js, and installed node-sass and node-sass-middleware, but the sass files are just not getting compiled.

### Steps to reproduce the actual/current behavior

I tried starting a new project with sass set as default, that worked fine. Then I created another new project with less as default, then tried to switched to sass, it didn't compile either, so it's not likely related to the actual app I've written. Any idea why this is happening?

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0 beta.5
| Node             | 4.2.6

**Comment by Noviny** [comment]
Answered on the [generator](https://github.com/keystonejs/generator-keystone/issues/250) as this was mostly a generator-related concern.
