### ISSUE TITLE
Keystone is not running but display no error

### ISSUE THREAD

**Issue by mrth2** [keystonejs/keystone#4183]
Hi, I am new to KeystoneJS. I have tried the getting started and successfully started new keystone project on http://localhost:3000 using MacOSX.

But when I deploy a new existing project on local, install the node modules then run: "node keystone" but nothing happens, the console stop just after running the command. On the console of mongod has 5 new open connections. Also the site at "http://localhost:3000" can not be reached. I made some researches but did not found any tips to getting the error log. 

Here is the repos of my project: https://github.com/dinopix/pinhook-bloodstock-website.

My current software version:
| Software         | Version
| -------------  | -------
| Keystone        | 0.3.17
| Node               | 7.8.0
| MongoDB       | v3.4.3

**Comment by sktt** [comment]
After a fresh install, keystone will compile its whole frontend js bundle when you start it. It might take a minute depending on your machine. Could that be the case?

also see https://github.com/keystonejs/keystone/issues/2824

**Comment by mrth2** [comment]
Hi, thanks for your comment.
I tried and this is my result:

> keystone: 1279.019ms

After console the time, node seems to hang up, no response and no web service was running, even the mongodb connection still alive until I break the node process. Is there any way for me to catch the log and see wherever it crashed?

**Comment by sktt** [comment]
Maybe.

Try

DEBUG=keystone:* node keystone



On Sat, 8 Apr 2017 at 03:18, Kyle <notifications@github.com> wrote:

Hi, thanks for your comment.
I tried and this is my result:

keystone: 1279.019ms

After console the time, node seems to hang up, no response and no web
service was running, even the mongodb connection still alive until I break
the node process. Is there any way for me to catch the log and see wherever
it crashed?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/keystonejs/keystone/issues/4183#issuecomment-292684985>,
or mute the thread

**Comment by mrth2** [comment]
Here is the debug log:

> DEBUG=keystone:* node keystone
> keystone: 1203.329ms
>   keystone:core:init initializing app +0ms
>   keystone:core:options settings options +1ms
>   keystone:core:options setting session for auth +1ms
>   keystone:core:importer importing  ./views +195ms
>   keystone:core:importer recur +0ms
>   keystone:core:importer recur +1ms
>   keystone:core:importer recur +37ms
>   keystone:core:importer recur +1ms
>   keystone:core:importer recur +0ms
>   keystone:core:importer recur +1ms
>   keystone:core:importer recur +0ms
>   keystone:core:importer recur +0ms
>   keystone:core:importer recur +1ms
>   keystone:core:importer recur +0ms
>   keystone:core:options setting nav +0ms
>   keystone:core:initNav init nav +1ms
>   keystone:core:start mount the express app +28ms
>   keystone:core:mount mounting +1ms
>   keystone:core:mount setting DB URI to : mongodb://localhost/pinhook-bloodstock-website +0ms
>   keystone:core:mount adding request logger +2ms
>   keystone:core:mount enabling frame guard +12ms
>   keystone:core:mount adding keystone routes to express app +0ms
>   keystone:core:routes setting keystone Admin Route +3ms
>   keystone:core:routes setting email test routes +0ms
>   keystone:core:routes setting cloudinary api +1ms
>   keystone:core:mount configuring app routes +9ms
>   keystone:core:mount connecting to mongo +1ms

So may be the node process hanged up after connection to mongodb

**Comment by sktt** [comment]
okay so then see if mongoose have any clues

and maybe check that you dont override logger option for the keystone instance

`keystone.mongoose.set('debug', true)`

**Comment by mrth2** [comment]
Okay thank you for the information. I found out the problem, the project can run only with nodejs 4.0 :)
