### ISSUE TITLE
Feature request: AdminUI add 'datetime' type to as nameIsInitial

### ISSUE THREAD

**Issue by amurchick** [keystonejs/keystone#420]
In /templates/views/list.jade from 43 checking nameIsInitial and allowed only types 'name' and 'text'. 
Can you add type 'datetime' to avoid message (see screen shot)?
![image](https://cloud.githubusercontent.com/assets/1515699/3280645/7298e332-f473-11e3-9bb2-1352cda52385.png)

**Comment by sebmck** [comment]
This would require supporting all field types as the item name. Ping @JedWatson.

**Comment by mxstbr** [comment]
I'll close this due to inactivity, though I think this might be working. Moved to ProductPains: https://productpains.com/post/keystonejs/adminui-add-datetime-type-to-as-nameisinitial
