### ISSUE TITLE
Unique validator

### ISSUE THREAD

**Issue by izifortune** [keystonejs/keystone#421]
Would be useful to add a unique validator like https://github.com/blakehaswell/mongoose-unique-validator ? I Find this plugin very useful for handling unique errors in mongoose. Let me know if you want me to work on a PR

**Comment by sebmck** [comment]
You can get direct access to a lists mongoose schema like so:

```javascript
var keystone = require('keystone'),
	Types = keystone.Field.Types;

var Post = new keystone.List('Post', {
	map: { name: 'title' },
	autokey: { path: 'slug', from: 'title', unique: true }
});

Post.schema; // This is an instance of mongoose.Schema

Post.add({
	title: { type: String, required: true }
});

Post.register();
```

This means that you can add in any plugins you want.
