### ISSUE TITLE
4.0.0-beta.5 Trying to bundle keystone with webpack, consistently hangs at 64%

### ISSUE THREAD

**Issue by GreenGeorge** [keystonejs/keystone#4234]
### Expected behavior
Webpack should be able to run keystone app through loaders and bundle up a server.js package.

### Actual/Current behavior
On `webpack --progress` the building process keeps stalling at 64%. When I remove keystone it bundles fine.
```
 64% [0] building modules 1690/1845 modules 155 active ...de_modules/image-size/lib/readUInt.js
```

### Steps to reproduce the actual/current behavior
```
/* file: web.js */
var keystone = require('keystone);
````
```
/* file: webpack.config.js */
var path = require('path);
module.exports = {
  entry: './src/web.js',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'server.js',
  },
  target: 'node`,
}
````

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5
| Node             | v.7.7.3
| Webpack | 2.4.1

### UPDATE
I left it for some time and it managed to start emitting, at which it produces this errror : 
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
tried using `UV_THREADPOOL_SIZE=100`. same result

**Comment by export-mike** [comment]
What's the reason for wanting keystone to run in a bundle? I assume the
browser too? Why do you need a server.js package?

Keystone only runs in a node environment.

**Comment by jakow** [comment]
@GreenGeorge You need to use keystone (and any project dependency for that matter) as an external dependency, by using webpack's 'externals':
```
  target: 'node', node: {__filename: false, __dirname: false},
  externals: [nodeExternals()],
  entry: './index.ts',
```

I use [webpack-node-externals](https://github.com/liady/webpack-node-externals) to generate a list of node modules to not be included in the bundle.

**Comment by GreenGeorge** [comment]
@jakow I see, this works great! I guess It wasn't clear to me that bundling for server has an entirely different approach than for browsers.

**Comment by export-mike** [comment]
Still don't see the need for bundling the server code. be good to understand what it is your trying to achieve as I might be missing something. 

I typically have the following workflow:

In development:
webpack-dev-server and babel-node

In production:
webpack build files hosted either by node or on s3.
node server transpilled with babel cli tools on post install. that way when the server starts it runs the transpiled code.

**Comment by GreenGeorge** [comment]
@export-mike Yes, I've been toying with a bundled keystone server since @jakow pointed out that solution. I do see how this is actually making it more unwieldy (apparently the updates folder needs to be copied as is right next to the bundled file to start the server).

I'll definitely try out your workflow as it seems reasonable. What I'm trying to achieve with bundling is basically just a streamlined frontend backend coding flow, e.g: having the exact same es6 code in front and back transpiled and transformed by the same tool sharing most of the config. I tend to code everything in one go, switching back and forth between frontend and server coding the needed sections as I encounter them.

**Comment by export-mike** [comment]
@GreenGeorge I understand. 

You should be using just a babel transpile to get the code ready for running in a node environment, meanwhile you need to bundle your app for the browser. webpack is for 'bundling' for a browser. 
 
To keep your syntax inline you can use the same .babelrc file. This does have its drawbacks though as node 7 is the most es6 compliant version to date. so it makes sense to only transpile the features of tomorrow in your node 7 project.

I knocked something together which should help you.
https://github.com/export-mike/keystone-babel-webpack

The client folder is a create react app project. you could as apart of your build get this copied into the keystone public directory at deployment time

**Comment by GreenGeorge** [comment]
@export-mike I see, I misunderstood and thought you were using babel-node on dev and webpack on production for the **server**. Didnt think its the client.

Thanks very much your repo cleared things up for me
