### ISSUE TITLE
4.0.0-beta.5: paginate ignores where

### ISSUE THREAD

**Issue by Allmektiger** [keystonejs/keystone#4253]
```
    var q = keystone.list('Object').
      paginate({ 
        page: req.query.page || 1, 
        perPage: 12, 
      }).
      where('active',true);

    if (locals.filters.type)      q.where('type').in(locals.filters.type);
    if (locals.filters.class)     q.where('class').in(locals.filters.class);

    q.exec(function (err, paging) ......
```

When i try to filtering results and paginate them, **exec** always returns **total** and **totalPages** for all objects and ignore where.
For example, when objects totals amount is 18, and with filtering returns only 6 of them, paginate anyway tells that total=18 and totalPages=2.
Why this happens?

### Environment
Keystone: 4.0.0-beta.5
Node: 6.10.2

**Comment by DianeLooney** [comment]
This seems not intended. Here's a workaround:

```
var filter = {};
if(locals.filters.type) filter.type = {$in: locals.filters.type);
if(locals.filters.class) filter.class = {$in: locals.filters.class);
var q = keystone.list('Object').
      paginate({ 
        page: req.query.page || 1, 
        perPage: 12, 
        filters: filter
      }).
      where('active',true);

q.exec(function (err, paging) ......
````

The filters option passed into paginate needs to be recognized by mongoose's model.find( ... ).

[Link to the relevant line of code](https://github.com/keystonejs/keystone/blob/v4.0.0-beta.5/lib/list/paginate.js#L22)

**Comment by Allmektiger** [comment]
Thank you very much!

**Comment by yao23** [comment]
```
How to user filters for where('id').in(`${id_array}`)?

filters: {'id': [id_array]} not working
```

@DianeLooney

**Comment by yao23** [comment]
```
filters:{id:{$in:[id_array]}}
```
