### ISSUE TITLE
Visually indicate which list(s) are used for authentication

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#426]
Eg, something like (`Users` is the list used for authentication in this example):

![screen shot 2018-10-10 at 10 21 25 am](https://user-images.githubusercontent.com/612020/46704357-563f5b00-cc76-11e8-875b-b7c83e458f62.png)

**Comment by MadeByMike** [comment]
This one is a little old but still seems like a good idea. It's a relatively simple update to the adminUI and would require checking each field against the authStrat provided.

Seems like a good first issues for someone with little Keystone experience but a good grasp of JavaScript.

**Comment by gautamsi** [comment]
I would want to have keystone level tagging for auth list. 

In v4, keystone was a global object injected similarly to FIELD_TYPES package. Can we inject KEYSTONE as webpack package to include global settings and some other config needed for such indication (auth list name).

**Comment by MadeByMike** [comment]
@gautamsi I think that is out of scope for this issue.
