### ISSUE TITLE
next ecommerce example won't run

### ISSUE THREAD

**Issue by aristech** [keystonejs/keystone#4265]
# Bug report

## Describe the bug
Module '"./node_modules/@keystone-next/types/dist/types.cjs"' has no exported member 'KeystoneGraphQLAPI'.

Module '"./node_modules/@keystone-next/types/dist/types.cjs"' has no exported member 'KeystoneListsAPI'.

I cloned the project, renamed .env and run yarn install, on yarn dev, 
 i get the above errors .

I understand that this is under development but i was very excited to find about this.
I have completed the course from Wes Boss long time ago, since it first came out and with keystone looks very promising.

**Comment by JedWatson** [comment]
Nice to see you trying it out @aristech!

It's a bit early as you can see, but thanks for the feedback 😀

I can't reproduce this, can you confirm where you're running the `yarn install`? it needs to be run in the root of the keystone monorepo at the moment and not in the example project, which might be the problem.

(the example is kept up to date with master, while we release new packages weekly at the moment, you can expect this to settle down but not for a few weeks yet)

**Comment by aristech** [comment]
@JedWatson You were right, it needed the base folder as well. 
Great work :+1:
