### ISSUE TITLE
Node version requirements are not listed strictly enough

### ISSUE THREAD

**Issue by jenklu** [keystonejs/keystone#4270]
### Expected behavior

In the "Getting Started - Prerequisites" page, Node is listed as requiring simply 0.10+, which implies any version > 0.10 would work correctly with keystone.

### Actual/Current behavior

However, as described in this question: https://groups.google.com/forum/#!searchin/keystonejs/localhost|sort:relevance/keystonejs/sOouK1Cdd7Y/wUZCiQzcBQAJ on the keystone google groups, when running keystone on Node 7.5, after connecting to the MongoDB, keystone would stop and connecting to localhost://3000 would lead to an empty web page. I had to downgrade to Node 6.10 before I could get even the demo to run correctly. The "Getting Started" documentation should clearly document that Node versions > 7.0 do not work, as I spent 3-4 hours messing around with environment variables on keystone after downloading the newest version of node simply because this was not documented.

### Steps to reproduce the actual/current behavior

I ran through the "Getting Started" page while not having npm, node, or MongoDB, and after starting a MongoDB instance (which should also be listed as a step in the "Getting Started" instructions), I could not connect to my page on Google Chrome.

### Environment

Run on OSX 10.11.1 El Capitan.
| Software         | Version
| ---------------- | -------
| Keystone         |  0.3.22 (listed in npm dependency tree)
| Node             |  7.5 (changed to 6.10, which fixed the problem)

**Comment by kosmaa** [comment]
Thank you @jenklu for this information - you saved me a lot of time figuring this out, I just installed new node version for another project and keystone wouldn't run after.
You forced me to install [node version manager](https://github.com/creationix/nvm) which help in this situation. I hope only that keystonejs will be further developed and there will be support for newer node version.

**Comment by Noviny** [comment]
Have keystone running on 8.2.1 with no problems. Without more details on what the error with 7.5 was, I am closing this, however if anyone can provide details on the error messages received for a particular version of node, happy to look in to them.
