### ISSUE TITLE
Is there any plugin for related posts recommendation in blog post page, like Disqus for comments?

### ISSUE THREAD

**Issue by yao23** [keystonejs/keystone#4273]
Is there any plugin for related posts recommendation in blog post page, like Disqus for comments?

I have already post in KeystoneJS feature community but didn't get any response.
https://keystonejs.canny.io/feature-requests/p/related-posts-plugin

**Comment by Noviny** [comment]
No, there is nothing like this for keystone. I would recommend building the functionality in yourself to your keystone application.
