### ISSUE TITLE
Audit Relationship fields implementation

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#43]
To finish implementing Relationships, we need to:

- [x] Nest the related list type in the GraphQL Schema
- [x] Implement the resolver for relationship types in the GraphQL Resolvers
- [x] Update the client-side query that loads relationships for the item and list views so they request the `id` of relationship field values, and don't just expecting a string
- [ ] Add a custom renderer for Relationship fields in the List view that renders the name and links to the item, for the first 3 items in a relationship (then "... x more")

The last task will rely on having the ability to implement custom cell components ("views") for field types that are used by the List view in the Admin UI, which is technically possible but hasn't been done yet.

**Comment by MadeByMike** [comment]
Most issues here solved. Making https://github.com/keystonejs/keystone/pull/2885 the canonical issue for additional relationship views.
