### ISSUE TITLE
How to save array in model?

### ISSUE THREAD

**Issue by amurchick** [keystonejs/keystone#431]
Scenario:
In `Admin UI` user fill field `tagsList` (space delimited list of user related tags) and I need to save tags in other field `tags` as array of tags (for quick search for `tags` later).
Like this:
```javascript
Groups.add({
	tagsList: { type: String, initial: true, required: true },
	tags: { type: Array, hidden: true }
});

Groups.schema.pre('save', function (next) {
	this.tags = this.tagsList.split(/\s+/);
	next();
});
```
But in `Keystone` no `Array` type in `KeyStone List`.
How I may release this scenario?

**Comment by dcousens** [comment]
@amurchick was your solution to use the tags field type above?

**Comment by amurchick** [comment]
I use @Bubujka solution

**Comment by creynders** [comment]
Answered
