### ISSUE TITLE
Why I modified the .hbs file in templates folder, the app must be restart?

### ISSUE THREAD

**Issue by hope-11** [keystonejs/keystone#4314]
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0
| Node             | 6.1.2

I modify the .hbs file in templates folder, then I refresh the page in browser, there's no change. I must restart the node app, then I can see the change, why?
I think that, .hbs file is client code, the change should be seen immediately, not to be restart the app.
I set the NODE_ENV=development and 'view cache': false, but it's no used.
please help me, thanks!

**Comment by icyretribution** [comment]
this sounds like you may be having issues do to http server caching. Do you have an apache or nginx server in front of your keystone installation?

**Comment by Noviny** [comment]
@icyretribution is correct.
