### ISSUE TITLE
You can't fully delete relationships

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#4332]
I'm on the last commit on master but also this bug is present o the latest beta.

When you have a relationship you can't delete, it just ignore's it.

On a one to may relationship you can delete all of them except the last one.

**Comment by Noviny** [comment]
Can you provide a replication case? We have not encountered this bug and use relationships extensively.

**Comment by JacobPVoronin** [comment]
Same issue. @Noviny here's the case:

Regular `Relationship` field in KeystoneJS (`categories` in this example):

    Post.add({
        author: { type: Types.Relationship, ref: 'User' },
        categories: { type: Types.Relationship, ref: 'PostCategory', many: true }
    });

Initially it's empty, but when I add some value to it, save it and then clear it (so that field is empty again), saving this Model won't update `categories`.

`console.log(this.categories)` in `Post.schema.pre('save', ...` shows that `this.categories` has previous value, while **it should be empty**.

Any ideas on this behavior?

**Comment by ryannhg** [comment]
Hey there,

Installing Keystone `v4.0.0-beta.5` fixed this bug for me.

It looks like the `v4.0.0-beta.8` version has this issue for both:

- Single Relationship Fields
- Many Relationship Fields

As a temporary workaround, I would stick to an earlier beta version like `v4.0.0-beta.5`

Good luck!
Ryan

**Comment by Twansparant** [comment]
Is there a workaround for v4.0.0-beta.8 without editing the **keystone/fields/types/relationship/RelationshipType.js** core file?

**Comment by stennie** [comment]
@Noviny Looks like this bug was introduced with commit 5df6846: when all relationships are removed there will be no references in the data object.

Should this commit be reverted or is there some other context for the change?

**Comment by Noviny** [comment]
The context for the change is that the relationship field being absent from a submission (undefined) should not automatically delete it.

This was causing a bug when calling update where the field was absent it would get deleted unintentionally.

It should definitely be valid to pass no data for a field when saving and not erase it.
