### ISSUE TITLE
MongoError: quota exceeded 

### ISSUE THREAD

**Issue by yao23** [keystonejs/keystone#4333]
### Expected behavior

No error complains.

### Actual/Current behavior

Pops error like the logging:

09:40:29.000
MongoError: quota exceeded at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11) at toError (/app/node_modules/mongodb/lib/utils.js:139:22) at /app/node_modules/mongodb/lib/collection.js:1060:67 at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18 at _combinedTickCallback (internal/process/next_tick.js:73:7) at process._tickCallback (internal/process/next_tick.js:104:9)

### Steps to reproduce the actual/current behavior

every time visit the web application

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | keystone@4.0.0-beta.5
| Node             | v4.4.0

**Comment by export-mike** [comment]
Your db is over it's allowance on your hosting provider,

Please take the following steps before submitting an issue:
0. Debug your code
1. Google the error
2. Search keystone issues
3. Submit the issue to keystone issues

Please try to filter out errors before providing an issue. If your unsure then please do submit an issue. 

Sorry to winge we seem to be getting a lot of issues like this and we need to groom our backlog for future versions of keystone.

**Comment by yao23** [comment]
Actually the db is not over its allowance and the used amount is further less than the size and confirmed with hosting provider support team.
