### ISSUE TITLE
build help

### ISSUE THREAD

**Issue by steveinatorx** [keystonejs/keystone#4337]
What could i be missing here - making a minor change to this file:
admin/client/App/elemental/Modal/dialog.js

and then running what i understand to be the build function:
NODE_ENV=dev npm run build

im not seeing my change in ./admin/public/js/packages.js

**Comment by export-mike** [comment]
Hi where are you making this change? Is this in a fork?

**Comment by steveinatorx** [comment]
no fork - im using the main branch - i do have the keystone module NPM linked per the update instructions from 0.3 to 0.4beta - maybe that is the difference.

Playing with this during the weekend I was able to make my change now in admin/client/App/elemental/Modal/dialog.js and i can get the build to work and the changes are manifested by launching with NODE_ENV=dev node keystone.js. 

closing this one
