### ISSUE TITLE
Order of Execution - pre('save') vs field watch functions

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#4343]
I am unable to find documentation on the order of execution of watch field functions and pre('save') functions.

Google Group: https://groups.google.com/forum/#!topic/keystonejs/kko945oir0I

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5.
| Node             | v6.9.4

**Comment by creynders** [comment]
`watch` is just a `pre('save')` handler too. So it depends on where your pre save handler registration code is. I.e. if it's before adding the fields to the list, they'll be called first. Otherwise they'll be called after.

**Comment by VinayaSathyanarayana** [comment]
@creynders - Thanks. 
Is there a way to get the ordered list of pre('save') handlers that will be executed? Something similar to SQL EXPLAIN PLAN? I need to debug some code-> I need to fix/correct the order of execution --> hence the request.

**Comment by creynders** [comment]
Easiest would be to set breakpoints in your IDE

**Comment by export-mike** [comment]
Closing issue thanks @creynders
