### ISSUE TITLE
Rebuild the initialisation / connection / server start process

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#435]
It would be beneficial to rework the `mount()` and `start()` methods in Keystone to make the process more pluggable, and ensure events happen in the right order.

The outcome should be easier integration into other applications, as well as more stable integration with other systems like `socket.io` and different database setups (this may be related to the issues reported in #41, noted [here](https://github.com/JedWatson/keystone/issues/41#issuecomment-46775081))

**Comment by mxstbr** [comment]
I'll close this for now, since I reckon this has been done. If not, let me know and we'll reopen!
