### ISSUE TITLE
Remove the Mongo ID from the URLs

### ISSUE THREAD

**Issue by harshalyeole-tudip** [keystonejs/keystone#4353]
Is there any way I can hide the _id in URLs generated by the Keystone.Js?

It actually shows the _id of the document stored in the MongoDB.

eg: xyz.com/abc/58a6d7eb177b563c595683ba

**Comment by harshalyeole-tudip** [comment]
Any update here?

**Comment by export-mike** [comment]
Hi can you provide more detail?

**Comment by harshalyeole-tudip** [comment]
When you do KeystoneJs development, it provides us with AdminUI and Website UI with which users will be interacting.

When you browse the uploaded products from the Website UI all the URLs contain the Object Id of the Mongo Document. I want to hide that ObjectId from the URL.
