### ISSUE TITLE
Types.Number - inputFormat

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#4354]
### Expected behavior
Types.Number should support inputFormat similar to Types.Date

### Actual/Current behavior
The display of the Types.Number in the Admin UI ignore the format directive completely.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0-beta.5. 
| Node             | 6.9.4

**Comment by export-mike** [comment]
Can you provide more details on your use case? What is the input and the input format in your scenario?

**Comment by export-mike** [comment]
If you come back with more information please reopen
