### ISSUE TITLE
Mongo Error: [Error: failed to connect to [localhost:27017]]

### ISSUE THREAD

**Issue by MartiniHenry1988** [keystonejs/keystone#4358]
Hi, I am using Keystone from past 1.5 years and now I am getting this error while running node keystone.
Mongo Error:

[Error: failed to connect to [localhost:27017]]

What could be the reason? Why suddenly it stopped working. I have a huge database in that project.

Plus at the current stage how can I backup my database?

**Comment by YejielIMP** [comment]
it sounds like you dont have mongo running
