### ISSUE TITLE
how to add robot.txt file into keystone js and which directory

### ISSUE THREAD

**Issue by akashkuber-tudip** [keystonejs/keystone#4359]
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by jstockwin** [comment]
Put it in `/public`, everything in that folder is served as static content. 

See https://stackoverflow.com/questions/33329974/how-to-serve-a-static-site-within-keystone for more details. 

We're trying to keep this tracker for keystone bugs only. Support requests should be submitted to stackoverflow, so if you need more help then please ask there instead.
