### ISSUE TITLE
Placeholder in Types.Text in keystone

### ISSUE THREAD

**Issue by Mohsin05** [keystonejs/keystone#4360]
Hello, I am new in keystone while defining the model I am not able to put the placeholder input field in the TYPES.TEXT model. I do not know the syntax. Please help me.

 product.add({

  title: {type: String, required: true},

   description: {type: Types.Text,},

 });

**Comment by icyretribution** [comment]
the placeholder is inserted in the template portion of the document structure.
so in other words, to add the placeholder pull up myKeystonejs>templates>target.(pug/hbs whatever your template is)
add a placeholder attribute to your html input with your desire text value.

**Comment by Noviny** [comment]
Closed as an answered question.

**Comment by chasms** [comment]
@icyretribution's answer refers to templates for the view portion of the site, while I believe the OP's question was in regards to the input fields in the admin UI (which is obfuscated in the npm package).

The more relevant answer to this question is here: https://stackoverflow.com/questions/44483381/placeholder-in-types-text-in-keystone
