### ISSUE TITLE
frameguard false does not work

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#4361]
I need to disable frame guard. I am
```
keystone.set('frame guard', false);
```
in my keystone.js. But it is still setting the x-frame sameorigin header. I am going directly at the express server on port 3000. Using beta 5.

**Comment by htor** [comment]
still an issue? it works as expected here on keystone@4.0.0-beta.8.

**Comment by stennie** [comment]
I also can't reproduce this issue with Keystone 4.0.0-beta.8. Setting `frame guard` to `false` appears to have the expected effect of removing the `X-Frame-Options` HTTP header.

Regards,
Stennie
