### ISSUE TITLE
Support for hostnames for static file serving.

### ISSUE THREAD

**Issue by Jexah** [keystonejs/keystone#4365]
### Expected behavior

We should be able to map subdomains to static file paths to optimise traffic (see: cookies).

### Actual/Current behavior

Add the option `static hostname` to the Keystone options that maps to the `static` folder specified in the Keystone options.
```
keystone.init({
	'less': 'public',
	'static': 'public',
	'static hostname': 'cdn.websitename.com',
});
```
In the above case, `cdn.websitename.com` would map to `/public`.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-b5
| Node             | 8.1.0 x86-64

**Comment by export-mike** [comment]
By pointing cdn.websitename.com to your node app it would serve public for you. More information please

**Comment by Jexah** [comment]
To clear up your ambiguous understanding above, in the example you've given, if `public` was the static folder and we had a file `main.js` in the `js` folder, to access that file you could either use `websitename.com/public/js/main.js` or `cdn.websitename.com/public/js/main.js`. We would want this `cdn` subdomain to be restricted to only serving files in the public folder -- or to put it a different way, the subdomain's root would be `/public` -- and so to access the this JavaScript file via the subdomain `cdn` you would use `cdn.websitename.com/js/main.js`.

Ideally we would be able to use hostname routing to point to two different sites on the same instance of Keystone -- but a topic for another day.

**Comment by export-mike** [comment]
I'd do this directly with a custom express middleware. This would give you
full control on what your cdn can access. By simply checking req.host on
all routes other than public.

**Comment by Jexah** [comment]
Ah, alright. If you feel that this doesn't fit bundled in with Keystone feel free to close. Personally it feels like having hostname routing to enable hosting multiple websites on the same Keystone instance would be very powerful. I guess that's just because to me, Keystone feels somewhere between rolling one's own stack and a layman-based CMS (such as Joomla or Wordpress) -- as it comes bundled with all the dependencies required to get a fully functional and integrated site up and running, but you have to configure the dependencies yourself.

Maybe this is one of those things that should be a `plugin`, once that architecture gets released.

Thanks for the feedback!

**Comment by export-mike** [comment]
You can write your middleware as a plugin, a user of your plugin would simply:

app.use(jexahsCdnPlugin());
