### ISSUE TITLE
Rename `app_updates` collection

### ISSUE THREAD

**Issue by cggaurav** [keystonejs/keystone#4366]
I'd like to be able to configure keystone on startup and define a custom collection name instead of `app_updates`.

**Comment by export-mike** [comment]
Could you help by providing more information on what you're trying to achieve?

**Comment by creynders** [comment]
@cggaurav this should be pretty easy to achieve. AFAICT all you need to do is change the string "App_Update" to something like `keystone.get('updates model')` at several places in https://github.com/keystonejs/keystone/blob/master/lib/updates.js
Then, just add `this.set('updates model', 'App_Update');` in https://github.com/keystonejs/keystone/blob/master/index.js#L49
And that should do the trick, I think.

**Comment by Noviny** [comment]
Thanks @creynders for providing an answer.

Going to close this as answered, but feel free to reopen if this doesn't resolve things.
