### ISSUE TITLE
Map Multiple key

### ISSUE THREAD

**Issue by makoy21** [keystonejs/keystone#4372]
This is the default
var Post = new keystone.List('Post', {
    autokey: { path: 'slug', from: 'title', unique: true },
    map: { name: 'title' },
    defaultSort: '-createdAt'
});
 
Does the map can accept multiple key?
like this:

map: {name: ['profile.lastName','profile.firstName']

**Comment by Noviny** [comment]
You should use a virtual to get this effect.
