### ISSUE TITLE
Next/Previous buttons in admin 

### ISSUE THREAD

**Issue by bufke** [keystonejs/keystone#438]
I'll be adding it to a project on behalf of a client. Is this something keystone would be interested in having? If so I can do a proper pull request.

It's non trivial because it should account for any search/filters. I was thinking it could keep an index of where it was on the query and the query as a GET variable. Like

keystone/foos?q=firstname%3A%24text%3ATim&index=5

For reference Django marked such as request for their admin as wontfix. Might not be a popular feature.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/cycle-through-items-with-nextprevious-buttons
