### ISSUE TITLE
Strange formatting in AdminUI add

### ISSUE THREAD

**Issue by masza** [keystonejs/keystone#4385]
### Expected behavior

Add select options the same format what is in List.add declaration

### Actual/Current behavior
Strange formatting. For example when I add smth like this:

```
		projectType: {
			type: Types.Select,
			options: ['Web', 'iOS', 'Android'],
			default: 'Web',
		}
```
Then I get in AdminUI formatted like this:

> I OS

### Environment
Keystone   4.0.0-beta.5       | 
| Node          v8.1.4   |

**Comment by hbuchel** [comment]
Did you try specifying a label for that option? Something like this

```
options: [
   { value: 'Web'},
   { value: 'iOS', label: 'iOS'},
   { value: 'Android'},
]
```

See docs here: http://keystonejs.netlify.com/api/field/select/#options-string-or-array

**Comment by Noviny** [comment]
Thanks @hbuchel for helping answer this. Going to close this as an issue as answered.

Feel free to reply if you're still experiencing this problem.
