### ISSUE TITLE
 The best way to request / handle data from a 3rd party api in keystone app

### ISSUE THREAD

**Issue by elizad** [keystonejs/keystone#4386]
I'm trying to add data from a third party API as GitHub Api into my Keystone App.  Have anybody did that before ?  I really appreciate

**Comment by Noviny** [comment]
Depends what you mean. You can set up an api endpoint using express which will query the external api when hit, that's probably the easiest way. If you mean an external api to the admin panel or to feed data to the database, keystone doesn't currently support that.

Closing this as answered, but feel free to ask if you still need help.
