### ISSUE TITLE
relationship fields: auto create a new data on Admin UI with select2.js

### ISSUE THREAD

**Issue by hoonch3** [keystonejs/keystone#439]
For now, I can add only the data of relationship field which is already existing on Admin UI with select2.js.

How about letting users being able to add a data which is not existing but he wants like wordpress?

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/extensible-select-field!
