### ISSUE TITLE
Following Getting started → Templates causes 500 error

### ISSUE THREAD

**Issue by panczarny** [keystonejs/keystone#4394]
### Steps to reproduce the behavior
Follow guides in http://keystonejs.com/docs/getting-started/
 
### Expected behavior

App behaves as described in http://keystonejs.com/docs/getting-started/

### Actual/Current behavior

App behaves as there was a 500 error, after there is

```
// Handle other errors
keystone.set('500', (err, req, res, next) => {
  let title, message, stack;
  if (err instanceof Error) {
    message = err.message;
    err = err.stack;
  }
  res.err(err, title, message);
});
```

### Debugging results
There is `utils` variable used in `templates/mixins/flash-messages.jade|pug` which was never included.

Action point → you should add these `utils` or remove them from this guide.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | keystone@4.0.0-beta.5 
| Node             | 7.10.1

**Comment by Noviny** [comment]
Thanks for this report. We actually moved the docs to a new location (for now), and updated theme.

[here](http://keystonejs.netlify.com/getting-started/yo-generator) is the new location for the docs. If you find any problems with the new docs, feel free to make a pull request to them.
