### ISSUE TITLE
how to set cloudinary transformation type?

### ISSUE THREAD

**Issue by epubreader** [keystonejs/keystone#4396]
actually value:
the upload image cloudinary  url like this: http://res.cloudinary.com/dshe4tcxc/image/upload/c_fit,f_auto,h_500,w_750/v1501161280/cpoihcf7j4p2bxllsv9y.jpg

Expected value:
using custom transformation type:
http://res.cloudinary.com/dshe4tcxc/image/upload/t_thumbnail/v1501161280/cpoihcf7j4p2bxllsv9y.jpg

after replace c_fit,f_auto,h_500,w_750 with custom transformation type
the url will be shorten and more SEO for search enginine

**Comment by icyretribution** [comment]
It is extremely well documented on cloudinary's website..
Back to the good old RTFM.
[http://cloudinary.com/documentation/image_transformations](http://cloudinary.com/documentation/image_transformations)

**Comment by Noviny** [comment]
Thanks @icyretribution for answering this question.

Closing this as an issue, as it is supported. Please comment if you are still experiencing issues.
