### ISSUE TITLE
Add a natural parser for text input on Date fields

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#44]
It would be really nice if you could type a descriptive string for a date (e.g. "next tuesday", "7th Nov 1998") into a date field and have it parse it for you, in addition to having the date picker.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. Please ask this question on [ProductPains](https://productpains.com/product/keystonejs)!
