### ISSUE TITLE
Demo website is down

### ISSUE THREAD

**Issue by charly37** [keystonejs/keystone#4400]
The website URL for the demo is down on my side: http://demo.keystonejs.com/
Here is the error message:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
![demoko](https://user-images.githubusercontent.com/6162615/28900123-e4ff0b5c-77bc-11e7-893c-5712e043bd9b.PNG)

**Comment by export-mike** [comment]
Thanks for reporting the demo site is back up and running.
