### ISSUE TITLE
Is there any tutorial for using Reactjs on Keystone ? 

### ISSUE THREAD

**Issue by duythang** [keystonejs/keystone#4402]
Is there any tutorial for using Reactjs on Keystone ? 

Thanks

**Comment by internetErik** [comment]
There are some repos that seem to be using keystone with react that may provide some insight:

https://github.com/keystonejs/generator-keystone-react
https://github.com/keystonejs/universal-keystone-boilerplate
https://github.com/keystonejs/react-easy-universal

I also have a boilerplate that I made that I've been using
https://github.com/internetErik/keystone4-universal-react

I haven't updated it in a while, but hopefully I'll get a chance to soon (I'd like to use react router 4 and react fiber)

**Comment by Noviny** [comment]
Closing this, as examples have been found.

@internetErik's boilerplate looks like a really good starting place at the moment.
