### ISSUE TITLE
can't access Slack for the project

### ISSUE THREAD

**Issue by autoboxer** [keystonejs/keystone#4414]
I've posted to Gitter and haven't gotten an answer, and @n-devr reached out to the team several times in the past year on my behalf for help.  The troubleshooting steps we've taken have not been successful and I am unfortunately still without access.  I have updates I'd like to discuss with the team and make, and while I genuinely want to contribute to the project, I'm hampered by the fact that I can't communicate with any core devs.  

To recap: in a phone reset, I lost the 2FA info stored in one of my apps and have been locked out since then (almost a year now).  I believe this should be a quick fix, but without anyone willing to dedicate some time to help me resolve the issue, I've been locked out.  Please, anyone from the project who is a Slack admin, reach out to me so I can get this fixed and start contributing again.
 
### Expected behavior
I can log into Slack for KeystoneJS

### Actual/Current behavior
I can't log into Slack for KeystoneJS as 2FA is preventing it (which can't be fixed on my side, but I believe can be on the Slack admin side)

### Steps to reproduce the actual/current behavior
Try to log in by entering password and getting to the 2FA screen
Be sad because you don't have an entry in any 2FA apps anymore
Read docs and realize there's nothing you can do
:(
repeat

### Environment
Slack

**Comment by stennie** [comment]
In an exciting plot twist, @autoboxer eventually resolved his 2FA issue and ultimately ended up as an admin for the KeystoneJS Community Slack.

There's now an open invite for anyone interested to [join the KeystoneJS Community Slack](https://launchpass.com/keystonejs) for feedback and discussion. Join the KeystoneJS Slack and introduce yourself!

Regards,
Stennie
