### ISSUE TITLE
So, I tried another way, but the login get asking me to sign up

### ISSUE THREAD

**Issue by rleddy** [keystonejs/keystone#4418]
Keystone does support fields. This is a strong point. Rendering is a weak point. 

So, I was just looking at Marko, and they bypassed express rendering but use the routing. Keystone uses (as far as I can tell) the express rendering. 

Today this became something of a roadblock.  1) I want to cannibalize the SydJS site because it has many of the features that I want for my project. But, in the end, its style is not very good. I have made a lot of changes to if upload movies, etc. I wrote new API to connect it to my QT app. But, I need to change the style of the pages. It uses Jade, which is awful in many ways. 2) I would like to drop in some styled HTML from free bootstrap themes and just loop on things like panels. A transition would be easier with handlebars. And, I could do it with the existing code, if I could use more than one rendering engine, and if I could control what stays in memory a little more obviously. 3) etc.

I find that keystone.js shines in getting the variables to the renderer. The backend is good (although extremely slow in loading) But, I have hacked the code so that it can be used by individual users on their content and not other user's content unless they are the admin. So, now I am aware of a hack that I have to deal with.

I find that keystone.js shines in getting the variables to the renderer.  And, it has the idea of fields. I really need the fields. My problem though is that they are more or less built in the backend, and some could be rendered by the client. So, the MVC philosophy is not always that wonderful. I am not sure React is fixing that.

What frustrates the most is that most CMS's do not need so much backend rendering. Sometimes we get stuck with that. But, if I get to a section on an HTML page, I may need to load components late in the game. Keystone.js offers paging in a sensible way. But, that is only one way to decide what to load.  Really you need paging within components.

So, a gallery might have several sections, then you load new items at the end of a section and then you can go back to swiping up and down, left and right. 

Loading section (within a page) rendered components puts less burden on the server, appears fast and allows HTML content to be cloned with new variable substitution.

All you ever need is variable substitution. So, Handlebars is likely a better philosophy than jade. Surely, only JSON lists of variable substitution need to be delivered to the page. On the server contextual variables just have to be put into text. So, why do these stacks become so complicated? 

So, I guess that you only really need socket.io to get JSON. A virtual DOM is nice only because the page properties change in browsers when hidden divs get added in. But, I may only ever need to request some part of a stream, get JSON, and apply it to appropriately selected VDOM, and then render.  It would be nice if the fields of types would appear cleanly in this discourse.  It would be nice if this were really easy to map out, like MyQuery => IO Event. It would be nice if all I had to do was steel some bootstrap theme and bless certain elements as the targets of IO updates. Then, I might just think about semantics. That is all I want to think about.

 
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by Noviny** [comment]
@rleddy thanks for the feedback.

I'm curious, is your modified version of keystone/the website around on github? I'd be interested in having a look.

I can't see an actionable issue in this though, so I'm closing it, and will make sure your points get considered next time we're in a place to make these kinds of changes.

**Comment by rleddy** [comment]
blog/node_modules/keystone/admin/server/api/list/get.js

I am replying to let you know that I made a change in here. But, I am
letting all users be admin, but just one with the user name.  I can clean
that up.

So, I can make a github entry sometime this coming week.

In replying, I will recall that I received this.
