### ISSUE TITLE
Option to Disable Download (CSV, JSON) 

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#4424]
1. Need an option to Enable/Disable CSV,JSON download
2. How to prevent some fields from being exported/downloaded (some fields may contain sensitive information

**Comment by VinayaSathyanarayana** [comment]
Any Suggestions?

**Comment by VinayaSathyanarayana** [comment]
Would appreciate suggestions.

**Comment by Noviny** [comment]
Hi @VinayaSathyanarayana, this kind of granularity, along with permission models isn't built into keystone 4. There is an assumption that you trust anyone with access to your admin panel with approximately the access to your database, including sensible information.

The download aspect really is a data dump, and we'd need to significantly change the feature to accommodate customising fields like this.

I would set up a new api for yourself that could remove sensitive info, and serve up data in your desired format. If you find something nice that works for you, maybe you can contribute it back to the admin ui downloader.

I'm going to close this as an issue, but agree this would be a useful future feature. Feel free to reopen or ask questions if this solution doesn't work for you.
