### ISSUE TITLE
The admin navigation seems never get the label which set in model?

### ISSUE THREAD

**Issue by gary-Shen** [keystonejs/keystone#4425]
Hi. If I Configure the navigation in `keystone.js`.  The Admin UI always show the `key` value not the label I set in model.

`keystone.js`:

```js
keystone.set('nav', {
	works: ['works', 'work-categories'],
	enquiries: 'enquiries',
	users: 'users',
});
```

Model `Post`: 

```js
var Post = new keystone.List('Post', {
	label: 'custom label',
	map: { name: 'title' },
	autokey: { path: 'slug', from: 'title', unique: true },
});
```

If I don't Configure the navigation. it works well.

[initNav.js#L37](https://github.com/keystonejs/keystone/blob/master/lib/core/initNav.js#L37)

Thanks.

**Comment by Noviny** [comment]
Nice catch. Do you think you could contribute a PR that resolves this so it also prefers the label in a custom nav?

**Comment by gary-Shen** [comment]
@Noviny Yes. I think so. I'll do it later.🙂

**Comment by gary-Shen** [comment]
@Noviny  Well, I think I misunderstood the intention of the label set in Model.

If I only want to change the title of the Admin navigation, Just set the key what I want.
```javascript
// Configure the navigation bar in Keystone's Admin UI
keystone.set('nav', {
	works: ['works', 'work-categories'],
	enquiries: 'enquiries',
	recruits: 'recruits',
	'custom label': 'users',
});
```

But if I want to change the performance of the label on other place. The label in my model should be set.

So, There is no need to create another PR for this project.

Thank you all the same. 😂

**Comment by Noviny** [comment]
So... close this issue then?
