### ISSUE TITLE
Proposition of alternative path of developing Keystone

### ISSUE THREAD

**Issue by arturkasperek** [keystonejs/keystone#4429]
KeystoneJS is in my opinion awesome tool. You create collections and out of the box, you have API and admin view for that. But the problem is that keystoneJS give us admin panel with poor customization option, in that area better tool is [admin on rest.](https://github.com/marmelab/admin-on-rest) Since keystone is using REST api I thoughted it would be awesome to make some adapter for that 2 tools to use admin view from admin on rest and backend stuff from keystoneJS ( creating collections, makeing rest API ). Maybe keystone team should more focus on adding backend things and use as a middleware that admin on rest( it is project which have many stars and contributors ) to create admin UI. For end user such a mix would be awasome solution, because he could still create collection out of the box and he can immediately edit that collection and extra he could extend without any problems that admin UI. He could even totally overwrite default view, he could add some custom sites on admin panel. What do you think about my idea?

**Comment by Noviny** [comment]
@arturkasperek Thanks for taking an interest in both what you like (and what you'd like to see improved) about keystone. I'm going to close this as an issue, but wanted to note we're very aware of the pain point the admin UI's uncustomisability is creating, and definitely want to solve it in the future.
