### ISSUE TITLE
How upload mutiple files at one time ?

### ISSUE THREAD

**Issue by huxinmin** [keystonejs/keystone#4438]
Types.File can only upload one file at one time , 
but I need mutiple files, and I have on idea.

**Comment by huxinmin** [comment]
nobody know?

**Comment by Noviny** [comment]
Hey @huxinmin, we've got an open issue for this at #3803, and the context around this in #3228.

Currently there isn't a way to do this. The intended solution was to allow the list field type (or nested field type) to allow multiple file uploads through the admin UI, but this hasn't been implemented.

I'm closing this in favour of the older issue, and I recommend watching that for when we get this resolved.
