### ISSUE TITLE
Can't use `const` in strict-mode in Boom dependency

### ISSUE THREAD

**Issue by vitalbone** [keystonejs/keystone#4439]
Discovered this bug in the Travis build of this PR: https://github.com/keystonejs/keystone/pull/4157
 
### Expected behavior
Should not throw.

### Actual/Current behavior
Throws when trying to require [Hoek](https://www.npmjs.com/package/hoek).

### Steps to reproduce the actual/current behavior
- `nvm use 0.10.x`
- `npm i`
- It will break here and you should see this error:
<img width="755" alt="screen shot 2017-09-22 at 9 07 29 am" src="https://user-images.githubusercontent.com/5966259/30722607-8286d410-9f75-11e7-8e17-bc79fee148dc.png">

### Potential fix
We could place our node 0.10.x - 0.12.x CI build behind a harmony flag? As suggested in this StackOverflow - https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode

### Environment
| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0-beta.5
| Node             | 0.10.48

**Comment by laurenskling** [comment]
Node 0.10 doesn't know what `const` is. Upgrade your Node version.

**Comment by vitalbone** [comment]
Thanks @laurenskling, yes `node@0.10.x` doesn't know what `const` is. That is kind of different to this issue though since the actual problem is more to do with keystone's ongoing support for `node@0.10.x` (as per the Travis builds). Fortunately there has been discussion around moving away from catering for < `node@6.x` over here https://github.com/keystonejs/keystone/pull/4453 so am going to close this.
