### ISSUE TITLE
Error: KeystoneJS failed to start - Check that you are running `mongod` in a separate process.

### ISSUE THREAD

**Issue by Elemino** [keystonejs/keystone#4450]
Hello,

Not sure if I should ask Heroku for help or not but does anybody know how to check that a separate mongo process is running in Heroku? 

Thanks a bunch! Cheers!

**Comment by SHBelsky** [comment]
Heroku won't run a MongoDB instance for you, you need to provide it a connection string to some MongoDB instance. Easiest thing to do is create an mLab instance, which should create an environment variable for you with the connection string (I forget what it's called, I think it's `MONGO_URI` or `MLAB_URI`. It should be clear which variable it is, since it starts with `mongodb://`). Change whatever variable that is to `MONGO_URI` if it isn't already that, then restart your Heroku dyno.

**Comment by Noviny** [comment]
@SHBelsky Thanks for answering this! It's the MONGO_URI you're looking for. Heroku has a guide on setting up [mLab](https://elements.heroku.com/addons/mongolab) as an integration with your heroku app.

**Comment by Elemino** [comment]
First of all I'm happy to learn that mlab still provides this option. I have tried adding the mongo_uri inside the init method and inside a global variable. But, now I know where to look!  I'll update soon. Thanks a ton!

**Comment by Elemino** [comment]
Finally! Got it up and running! One thing I find weird is that mlab will create a new account if you go to their admin page from Heroku. Anyways, thanks guys! So happy it's working now! Can't wait to play with Keystone in prod now!!! Cheers!

**Comment by Anthony4m** [comment]
how did you fix the error

**Comment by Elemino** [comment]
Did you run sudo service mongod restart?

**Comment by Anthony4m** [comment]
am using windows

**Comment by Elemino** [comment]
Is your mongodb service running in the background? 
https://stackoverflow.com/questions/2438055/how-can-i-run-mongodb-as-a-windows-service

**Comment by Elemino** [comment]
Should be something like: const uristring = process.env.MONGOLAB_URI || 'mongodb://yourinstance'; in your keystone file

**Comment by Anthony4m** [comment]
i gave up on keystone and decided to write the site from scratch using express and mongodb
thanks for helping anyway

**Comment by Elemino** [comment]
That's a shame. I would always bet on keystone. The new version is great too! If you share some code maybe it would be easier to debug. In any case, good luck.
