### ISSUE TITLE
Close Greenkeeper PRs and update Dependencies

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#4452]
Our Greenkeeper PRs got out of control, and are now out of date. Trying to get a fresh start, I'm going to close all the currently open Greenkeeper PRs and we'll upgrade the packages using `yarn upgrade-interactive`, checking breaking changes.

@vitalbone you were going to take the Greenkeeper PRs so instead can you please:

* Upgrade everything that looks safe (no breaking changes or easy updates)
* Open an issue for nontrivial package updates so we can track /assign them independently

I'll then enable the new version of Greenkeeper on the repo which is much less noisy.

**Comment by JedWatson** [comment]
@vitalbone this PR also has a list of the latest package versions, easy to see the upgrade ranges in the diff view: #4451

**Comment by stennie** [comment]
@dominikwilkowski re-applied semver notations in #4719 and we are tracking non-trivial updates with [`label:dependencies`](https://github.com/keystonejs/keystone/labels/dependencies).
