### ISSUE TITLE
authedItem is not defined when query is called from keystone.executeGraphQL

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#4457]
# Bug report
`authedItem` is  undefined in custom queries that are called from `keystone.executeGraphQL`

## Describe the bug
Custom queries called from `keystone.executeGraphQL` will not have `authedItem` passed as an argument in the resolver

## To Reproduce

Implement the following changes to the blog example in the keystone repo. 

run `yarn add apollo-server-express` and add `const { gql } = require('apollo-server-express');` to the `index.js` file in the blog example project. 

Then add these two custom queries to the schema by adding the following code to the `index.js` file in the blog example project.
```
keystone.extendGraphQLSchema({
  queries: [
    {
      schema: 'getHello: String',
      resolver: async (obj, args, { authedItem }) => {
        if (!authedItem) throw 'You do not have access to this resource';
        const context = keystone.createContext({ skipAccessControl: true });

        const query = gql`
          {
            getWorld
          }
        `;

        const { data, errors } = await keystone.executeGraphQL({ context, query });

        console.log(data, errors);

        return 'hello ' + data.getWorld;
      },
    },
    {
      schema: 'getWorld: String',
      resolver: async (obj, args, { authedItem }) => {
        if (!authedItem) throw 'You do not have access to this resource';

        return 'world';
      },
    },
  ],
});
```

Run the blog example project and open the graphql playground http://localhost:3000/admin/graphiql

run the following query in the playground 
```
{
  getHello
  getWorld
}
```

Expected result: 
```
{
  "data": {
    "getHello": "hello world",
    "getWorld": "world"
  }
}
```

Actual result: 
```
{
  "data": {
    "getHello": "hello null",
    "getWorld": "world"
  }
}
```

The `getWorld` query when run on its own returns the "world" string, however when it is called  using `keystone.executeGraphQL` in the `getHello` query, the `getWorld` query returns null and throws the following error 
`You do not have access to this resource`.

This is due to `authedItem` being undefined when a query is called from `keystone.executeGraphQL`.

**Comment by molomby** [comment]
**The authentication info is carried by the context.**

In your resolver, when you call `keystone.executeGraphQL()`, you're passing it the _brand new context object_ you created earlier..

```js
const context = keystone.createContext({ skipAccessControl: true });
```

This _new_ context object is separate from the original request context. There's no way for it to automatically assume the auth info from the original context – you need to provide it when you call `createContext()` (as per [the docs](https://www.keystonejs.com/keystonejs/keystone/#config-3)).

The start of your resolver should look something like this (untested code)...

```js
resolver: async (obj, args, authentication) => {
  if (!authentication.authedItem) throw 'You do not have access to this resource';
  const context = keystone.createContext({ authentication, skipAccessControl: true });

  // ... the rest
},
```

This tells `createContext()` to carry the users session forward while also configuring the context so that access control is  not applied.

**Comment by SeanDoyleGit** [comment]
@molomby That has resolved my problem however to get the code working I have to change `authedItem` to `item` when creating the context... 

```
resolver: async (obj, args, { authedItem, ...auth }) => {
  if (!authedItem) throw 'You do not have access to this resource';

  const context = keystone.createContext({ 
    authentication: { item: authedItem, ...auth }, 
    skipAccessControl: true 
  });

  // ... the rest
},
```

Perhaps we should rename `item` to `authedItem` when creating context?

**Comment by SeanDoyleGit** [comment]
The same name change issue occurs with `authedListKey` being renamed to `listKey`.
So the correct code would be...
```
resolver: async (obj, args, { authedItem, authedListKey, ...auth }) => {
  if (!authedItem) throw 'You do not have access to this resource';

  const context = keystone.createContext({ 
    authentication: { item: authedItem, listKey: authedListKey, ...auth }, 
    skipAccessControl: true 
  });

  // ... the rest
},
```

**Comment by timleslie** [comment]
The `context` object itself has a method `createContext` which will carry over the authentication data, so the best way to solve this issue is to do:

```
resolver: async (obj, args, _context) => {
  if (!_context.authedItem) throw 'You do not have access to this resource';

  const context = _context.createContext({ skipAccessControl: true });

  // ... the rest
},
```
