### ISSUE TITLE
What are process.env.GA_PROPERTY and process.env.GA_DOMAIN?

### ISSUE THREAD

**Issue by datnguyenquy94** [keystonejs/keystone#4458]
Just like the title, I am settings up a blog and trying to apply google analytics to it. But I am confused about GA_PROPERTY and GA_DOMAIN. What is it? 

GA_PROPERTY is "Tracking Id" right? And GA_DOMAIN is my domain or google analytics callback url ?

**Comment by jstockwin** [comment]
https://support.google.com/analytics/answer/6164390?hl=en

Looks like `GA_DOMAIN` should just be `auto`

**Comment by datnguyenquy94** [comment]
Oh Thanks for making it clear.
