### ISSUE TITLE
Please provide a `cookie secret` value for session encryption.

### ISSUE THREAD

**Issue by deineryao** [keystonejs/keystone#4463]
Hi Team:
Here is the problem I encountered。

1.I create the project on local，Installation and execution are normal。
2.I submit it to github
3.I login to my vps, then I use `git pull` to get the project from github.
4.on my vps, I execute`npm install` then `npm start`

at this time,The console reported the following information：
```
KeystoneJS Configuration Error:

Please provide a `cookie secret` value for session encryption.
```
Why the local is  normal,but the vps is exception?

vps: vultr
vps system: CentOS Linux release 7.3.1611 (Core)
node:  v8.7.0

**Comment by internetErik** [comment]
The .gitignore ignores the file .env. That file has the cookie secret in it. Create that file with the secret in it on the server and it should work

**Comment by deineryao** [comment]
you are right @internetErik

**Comment by htor** [comment]
@deineryao you can close this issue now, thanks!

**Comment by BuiKimPhat** [comment]
So we make up the cookie secret or where do we get it? and is there any syntax for the cookie secret?

**Comment by htor** [comment]
@BuiKimPhat yes, you make it up. the more random, the better.

**Comment by BuiKimPhat** [comment]
Is there any syntax for this, like: cookie-secret=?????

Vào 15:14 Th 2, 14 thg 5 2018 htor <notifications@github.com> đã viết:

**Comment by theraaz** [comment]
in my `.env` I use it like 
```
COOKIE_SECRET=random-string-here
```

**Comment by stennie** [comment]
The `cookie secret` is a random string value passed through to Express' [cookie parser](https://github.com/expressjs/cookie-parser#cookieparsersecret-options) for signing cookies. This value should be unique for every deployment environment.

Typically this value is set in your project `.env` file using `COOKIE_SECRET=..` (as suggested by @theraaz), but technically you can set in the host environment using whatever means is appropriate (for example, [`ENV` in a Dockerfile](https://docs.docker.com/engine/reference/builder/#env)).

As mentioned by @internetErik, the  `.env` file is intentionally excluded from `git` check-in (via `.gitignore`) so you don't accidentally share the secret used to sign your cookies between different environments.

Regards,
Stennie
