### ISSUE TITLE
Pre render middleware not triggered

### ISSUE THREAD

**Issue by GrofGraf** [keystonejs/keystone#4484]
Prerender middleware is not triggered by default if you navigate to blog post.

```
keystone.pre('render', middleware.<prerender_middleware>);

        ...

exports = module.exports = function (app) {

        ...

        app.get('/blog/post/:post', routes.views.post);

        ...

};
```

If I put it in the route binding, it gets triggered pre routes.
`app.get('/blog/post/:post', middleware.<prerender_middleware>, routes.views.post);`

Do you have any idea how to trigger it pre render?

**Comment by htor** [comment]
what is your middleware code? do you have other pre-render middleware called before/after?

**Comment by stennie** [comment]
Closing out stale issues.

For future questions or bug reports, please fill out the GitHub issue template with expected behaviour, actual behaviour, steps to reproduce, and relevant version details for your environment.

Thanks,
Stennie
