### ISSUE TITLE
keystone not working 

### ISSUE THREAD

**Issue by monkey-yu** [keystonejs/keystone#4485]
hello ,i clone this code ,and want to make it working .but when i input "sudo npm link" finished,the next step error.
i want to know how to make it working ,and it should install mongoDB at local ?

**Comment by GrofGraf** [comment]
Try to follow this steps:
http://keystonejs.com/getting-started/

You should have installed MongoDB and Node.js first, locally.

If you tell what the error is, maybe we can be of more help.
