### ISSUE TITLE
Password Validation/User Update Causes App to Crash

### ISSUE THREAD

**Issue by j-sz** [keystonejs/keystone#4486]
### Expected behavior
- Password validation should **not** run on save/update if the password field has not been updated

### Actual/Current behavior
- Password validation runs and causes the app to crash (because "pass" is undefined)

### Steps to reproduce the actual/current behavior
1. Create a model containing a password field 
1. Create/save a document into the model 
1. Update the same document without changing the password
1. The app crashes as password is undefined

### Environment
- Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1038-aws x86_64)

| Software  | Version
| Keystone  | 4.0.0-beta.7
| Node | 6.11.5

### Workaround
- I believe the issue is related to [this commit](https://github.com/keystonejs/keystone/commit/8ecb80960ffd2ae2f241b0bbb62367821a79ff63), fields/types/password/PasswordType.js, line 203: 
```
	if (rejectCommon && dumbPasswords.check(pass)) {
		messages.push('Password must not be a common, frequently-used password.');
	}
```
- I changed line 203 to: 

```
	if (typeof pass === 'string' && rejectCommon && dumbPasswords.check(pass)) {
		messages.push('Password must not be a common, frequently-used password.');
	}
``` 
- The record updates without crashing the app when `typeof pass === 'string'` is added as a condition to the if statement.

**Comment by gsteinert** [comment]
This appears to have been fixed by e061c72bbdc9655cf58ce1e7f8558937a946c4f1. Suggest this issue can be closed.

**Comment by j-sz** [comment]
Sounds good to me. Thanks!

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:44535)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eWpkp-0034lH-4m
	for greg@biomassiv.es; Wed, 03 Jan 2018 14:35:15 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=oC7GeavKr91kM2yHEneduUB8sYM=; b=WR1KNqkQrUpFhbH2
	e/omKm4+xsaJJ0QF/BWJSdlRGLCtdTNGSBFlfRtDEp4TpdBN861eVvWe/V35wsVI
	meTf+qMGxN2kq/vyigV4BKBAmO6aV89K8tPSTharqkBkA9CM06l3ohybNnROtDgL
	T9lBn1xynRNnqLAgKOR4HNgVvI8=
Received: by filter0145p1las1.sendgrid.net with SMTP id filter0145p1las1-17163-5A4D3E5B-13
        2018-01-03 20:34:35.873813201 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0007p1iad2.sendgrid.net (SG) with ESMTP id FDAhodHVSYuVa8NEMZcxtw
	for <greg@biomassiv.es>; Wed, 03 Jan 2018 20:34:35.868 +0000 (UTC)
Date: Wed, 03 Jan 2018 20:34:35 +0000 (UTC)

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:20097)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eWpkq-0034mK-2T
	for greg@biomassiv.es; Wed, 03 Jan 2018 14:35:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=X8XHeftgOOg3IoaUdUzADrLfo98=; b=NcQztUgac1CxvTkD
	/HrE0fI/A99SciDOBGfKZV9VOeXq7+y0iJQefxxa/9MYzQYdKwtgXKucsBVwmIX8
	d3udzV4pp4lsLvpiY1wqLGexmIpQ2jw9YmHKh6Vo4PuhKy7HBwsndPzeWJ/ObQwV
	Vma5HAZnw7xzgXY14UqGWEx7nHM=
Received: by filter0990p1mdw1.sendgrid.net with SMTP id filter0990p1mdw1-11691-5A4D3E5D-3
        2018-01-03 20:34:37.128626299 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad2.sendgrid.net (SG) with ESMTP id wIRoGX0hRwuY8OBAxXjLQQ
	for <greg@biomassiv.es>; Wed, 03 Jan 2018 20:34:37.104 +0000 (UTC)
Date: Wed, 03 Jan 2018 20:34:37 +0000 (UTC)
