### ISSUE TITLE
create project error

### ISSUE THREAD

**Issue by shunyue1320** [keystonejs/keystone#4486]
RequestError: getaddrinfo ENOENT raw.githubusercontent.com

![image](https://user-images.githubusercontent.com/47295879/100953250-24bc3480-354d-11eb-927a-5a85ecab2df9.png)

excuse me, can you tell me the reason？

**Comment by gautamsi** [comment]
it should be transient issue, is this happenning everytime you run? should have been fixed now if there was any outage for github

**Comment by joeysherman** [comment]
I'm also receiving this error when building out a fresh project. Any Ideas?
![Code_Doyn3DpGlq](https://user-images.githubusercontent.com/18039561/101291127-5c301880-37bb-11eb-93d1-e1600666eca1.png)

**Comment by kobakaxa** [comment]
> RequestError: getaddrinfo ENOENT raw.githubusercontent.com
> 
> ![image](https://user-images.githubusercontent.com/47295879/100953250-24bc3480-354d-11eb-927a-5a85ecab2df9.png)
> 
> excuse me, can you tell me the reason？
