### ISSUE TITLE
Provide tool to perform data integrity scans

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#449]
We have a lot of information about relationships and expected states of data - it would be amazing to harness all this to do an automated scan of the database to check for any violations of our expectations:

```javascript
keystone.createList(/* ... */);
// ...
try {
  await keystone.dataIntegrityCheck()
} catch(error) {
  console.error(error);
}
```

## Why?

I manually deleted some data via mongod and now my relationships are broken, but I didn't realise until I navigated to the page trying to read that data.

I had the following setup:

```javascript
keystone.createList('User', {
  fields: {
    posts: { type: Relationship, ref: 'Post.author', many: true },
  }
});

keystone.createList('Post', {
  fields: {
    author: { type: Relationship, ref: 'User', required: true },
  }
});
```

And I inserted some data, which looked roughly like:

```
user: { "_id" : ObjectId("5b9fadfaa585b8002f7f02d4"), posts: [ObjectId("5bab1a0bc0f6a6001a3f362c")] }
post: { "_id" : ObjectId("5bab1a0bc0f6a6001a3f362c"), author: ObjectId("5b9fadfaa585b8002f7f02d4") }
```

Then I manually deleted the user, so now I have data that looks like:

```
post: { "_id" : ObjectId("5bab1a0bc0f6a6001a3f362c"), author: ObjectId("5b9fadfaa585b8002f7f02d4") }
```

_(note the `author` is still set on the post, but the `user` is deleted!)_

We should be able to report back with something like:

> ```
> Data Integrity Check failed:
> Post
>   (id:"5bab1a0bc0f6a6001a3f362c") author is required and set, but the referenced item (id:"5b9fadfaa585b8002f7f02d4") in the User list does not exist.
> ```

Or, if it was the other way around, and we deleted the post:

> ```
> Data Integrity Check failed:
> User
>   (id:"5b9fadfaa585b8002f7f02d4") A value in 'posts' is set, but the referenced item (id:"5bab1a0bc0f6a6001a3f362c") in the Post list does not exist.
> ```

And potentially offer solutions:

> ```
> $ Would you like these references removed? (n/Y)
> ```

**Comment by MadeByMike** [comment]
This sounds like a good plugin/thrie-party package :)
