### ISSUE TITLE
Session maxAge in cookie signin options is not respected

### ISSUE THREAD

**Issue by hreimer** [keystonejs/keystone#4494]
### Expected behavior

Following [this closed issue #1895](https://github.com/keystonejs/keystone/issues/1895) I was expecting to set the maxAge property of the session cookie, after which the user is automatically signed out, and because its 2017 (and nowhere properly documented, [in the keystonejs npm package in lib/session.js:55 we will find the current syntax](https://github.com/keystonejs/keystone/blob/41c6e1657bf04aa269dd3c1ee3477185b71318bb/lib/session.js#L55)) and the syntax from 2015 doesn't work anymore it is now done for v 4.0.0 like this in the main keystone.js start file:

`'cookie signin options' : {
		'maxAge': 5 * 60 * 1000 //5min
	},`

to set the session timeout to 5min. 

### Actual/Current behavior

Yes, the keystone.uid cookie is set accordingly to the desired maxAge, however there is also a "this.sid" cookie, that get's initialized whenever keystone starts up and has an unlimited (or none) expiry date, and will only get deleted upon browser close since it's a session cookie. If the keystone.uid cookie is deleted, this.sid is still valid and active and therefore the proposed maxAge configuration (which itself should convert the keystone.uid Session cookie to a cookie with expiry date) is useless.

(To be noted, there is no difference in the actual behaviour when I use the built-in express session store or the recommended external "session store" via mongo / connect-mongo)

### Steps to reproduce the actual/current behavior

Just add 

`'cookie signin options' : {
		'maxAge': 5 * 60 * 1000 //5min
	},`

in your keystone.js file, log in and open the developer console in Chrome, Application>Storage>Cookies><yourhost:port> to observe it and try to interact with keystone after the cookie has expired and is deleted, while this.sid is still present.

### Proposal for a possible solution:

in the same lib/session.js file in the keystonejs package, simply add one line:

`			req.session.cookie.maxAge = cookieOpts.maxAge;
`
just above [https://github.com/keystonejs/keystone/blob/41c6e1657bf04aa269dd3c1ee3477185b71318bb/lib/session.js#L60](https://github.com/keystonejs/keystone/blob/41c6e1657bf04aa269dd3c1ee3477185b71318bb/lib/session.js#L60)  to reset that initial Session cookie every time a user signs in and the maxAge property is set.

I am not experienced in PRs and if this is a valid solution or are there other approaches, maybe somebody with more experience in keystonejs could comment and approve/disapprove?  

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta5
| Node             | 6.9.5

**Comment by millsy** [comment]
Added PR #4565 to include this change. Tested it locally and it works as expected with this fix in place.

**Comment by max8hine** [comment]
Any update on this?

**Comment by stennie** [comment]
@max8hine This issue has been [flagged for triage](https://github.com/keystonejs/keystone/labels/4.0-release-candidate) (and has an open PR), but failing tests in master were blocking merging anything with confidence. Tests have now been unblocked (per PR#4643) and we're organising how to attack the backlog for a [4.0.0 GA release](https://github.com/keystonejs/keystone/milestone/5).

Join us on the [Keystone Slack](https://launchpass.com/keystonejs) in #keystone-4-release if you'd like to discuss or flag any blocking/critical issues for a 4.0.0 release.

Regards,
Stennie

**Comment by stennie** [comment]
@max8hine FYI, this change has been tested & merged for v4.0.0-rc.2.

Regards,
Stennie

**Comment by savager** [comment]
@stennie I don't see rc.2 published, will it be soon?
