### ISSUE TITLE
keystone-storage-adapter-s3 v1.1.1 depends on unusable version of knox

### ISSUE THREAD

**Issue by augustbjornberg** [keystonejs/keystone#4498]
### Expected behavior

The File model field type, with the keystone-storage-adapter-s3 module is expected to upload files to AWS S3.

### Actual/Current behavior

File upload with keystone-storage-adapter-s3 seems to be broken, right now it's throwing the same **knox** error as i've seen posted by other users for similar errors.

> TypeError: mime.lookup is not a function

The runtime crashes and no file is uploaded to S3.

### Steps to reproduce the actual/current behavior

Use the File field type with keystone-storage-adapter-s3.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0-beta.7
| Node             | 8.3.0

**Comment by augustbjornberg** [comment]
<img width="408" alt="screen shot 2017-11-13 at 8 13 11 pm" src="https://user-images.githubusercontent.com/1137612/32762604-33fa228a-c8af-11e7-9fdb-3e75afe81684.png">

See you later, crocodile.

**Comment by earmbrust** [comment]
Resolution can be found @ https://github.com/Automattic/knox/issues/326

**Comment by cvn** [comment]
This was fixed by PR #4453 and released in 4.0.0-beta.8.

**Comment by g3r4n** [comment]
@stennie when do you think the next release will be done ? This fix is not in the beta 8

**Comment by stennie** [comment]
@g3r4n This issue needs to be addressed via the [`keystone-storage-adapter-s3`](https://github.com/keystonejs/keystone-storage-adapter-s3) dependency.

It was mentioned by @JedWatson on the [Keystone Slack](https://launchpass.com/keystonejs) earlier today:

> @mikehazell has taken a look and, building on https://github.com/keystonejs/keystone-storage-adapter-s3/pull/29, is going to publish a new version that's using the AWS SDK directly instead of knox. It'll be a new major version of that package.

Regards,
Stennie

**Comment by g3r4n** [comment]
@stennie does this PR is the fix ? https://github.com/keystonejs/keystone-storage-adapter-s3/pull/32

**Comment by stennie** [comment]
@g3r4n The planned fix is https://github.com/keystonejs/keystone-storage-adapter-s3/pull/35, which will be included in the next release of `keystone-storage-adapter-s3`.

Regards,
Stennie

**Comment by g3r4n** [comment]
@stennie thanks for your feedback.

**Comment by mikehazell** [comment]
FYI - @g3r4n keystonejs/keystone-storage-adapter-s3#35 has been released in v2.0.0.

**Comment by g3r4n** [comment]
Thanks @mikehazell for your fix !


To everyone don't forget to apply the [breaking changes](https://github.com/keystonejs/keystone-storage-adapter-s3#breaking-changes) and to generate files name wihout spaces : see this [issue](https://github.com/keystonejs/keystone-storage-adapter-s3/issues/36)

**Comment by g3r4n** [comment]
Working for me now.
@stennie you can close this issue.

**Comment by stennie** [comment]
@g3r4n Thanks for confirming the updated s3 adapter worked for you (and reporting the [bug generating filenames with spaces](https://github.com/keystonejs/keystone-storage-adapter-s3/issues/36)).

This issue should remain open until we bump & test the dependency for the next Keystone release.

Regards,
Stennie
