### ISSUE TITLE
DependsOn doesn't work in combination with initial

### ISSUE THREAD

**Issue by Ventis** [keystonejs/keystone#450]
For example, if you have a select field and you want a piece of the form to only appear when you have selected a certain value, you can do that easily with dependsOn.

```javascript
type: {label:'Type', type: Types.Select, options:waypointTypes, initial: true,required: true, default:'mkw'}},
    {heading:"User Generated Content Requirements", dependsOn:{type:'ugc'}},
    {
        ugcType: {label: 'Type of Content required', type: Types.Select, options: ugcTypes, dependsOn:{type:'ugc'}, initial:true},
        ugcDescription: {label: 'User Generated Content Description', type: Types.Textarea, dependsOn:{type:'ugc'}, initial:true, note: "This descriptions is what the player will see when he completes the waypoint and can see what the player before him created." }
    },
```

However, this code does not work for an initial form. The fields marked with dependsOn are always shown.

**Comment by webteckie** [comment]
@JedWatson is the example above where dependsOn is used in the heading supposed to work?  If so, then it seems to be broken in 0.3.0 (I haven't checked 0.2.x).  @snowkeeper did you test this case with your recent changes to dependsOn?  Regardless, it is a very useful thing to have working and it doesn't seem to be.

**Comment by webteckie** [comment]
I'm going to create a new issue for the list header dependsOn regression.  The issue described in this thread seems to be fixed and this one should be closed.
