### ISSUE TITLE
Do things Manually and see inner

### ISSUE THREAD

**Issue by Zedonboy** [keystonejs/keystone#4500]
Seriously,  keystone promise flexibility and can be customized. 

but Keystone,  does authentication and session out of the box,  
i have checked the routes directory,  i cant see any session commands,  
i want the ability to manually. 

and Docs is good,  but always documents non-real life situation.

**Comment by stennie** [comment]
Keystone uses the [`express-session` middleware](https://www.npmjs.com/package/express-session). The default session store is in-memory for development use, but you can specify an alternative session store implementation and options (for example: `connect-mongo`, `connect-redis`, or your own express-session implementation).

For an example in Keystone 0.3, see: http://keystonejs.com/docs/configuration/#options-database. The configuration will be similar in Keystone 4, but the documentation link is broken at the moment.

Regards,
Stennie
