### ISSUE TITLE
I want to use html model to take place of the front page of keystone which using pug, what should I do?

### ISSUE THREAD

**Issue by LXF5133** [keystonejs/keystone#4503]
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by bi-kim** [comment]
This allows you to write in pure html form.

// File path : routes/index.js 
app.get('/', (req, res) => res.sendFile(keystone.expandPath(keystone.get('views')) + "/sample.html"));
