### ISSUE TITLE
why I create keystone that don't hava FieldTests which can create field freely

### ISSUE THREAD

**Issue by LXF5133** [keystonejs/keystone#4504]
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by stennie** [comment]
Unclear what the actual question/issue is, so closing.

For future questions or bug reports, please fill out the GitHub issue template with expected behaviour, actual behaviour, steps to reproduce, and relevant version details for your environment.

Thanks,
Stennie
