### ISSUE TITLE
Relationship problem

### ISSUE THREAD

**Issue by Belcebur** [keystonejs/keystone#4517]
Hello,

I have 4 models.

- User --> User Model
- Language --> Language Model
- LanguageLevel --> Language Level Model
- UserLanguageLevel --> Relation User vs Language vs Model

How I can create a relationship from User/Language/LanguageLevel models to create new UserLanguageLevel from others models?

Thanks in advance

**Comment by lidJS** [comment]
Maybe this helps,

`/**
 * UserLanguageLevel
 * Intitialize ....
 * const Types = keystone.Field.Types ....
 */

UserLanguageLevel.add({
    User: {
        type: Types.Relationship,
        ref: 'User'
    },
    Language: {
        type: Types.Relationship,
        ref: 'Language'
    },
    LanguageLevel: {
        type: Types.Relationship,
        ref: 'LanguageLevel'
    }
})

/**
 * Creating a model entry
 */

const UserLanguageLevel = keystone.list('UserLanguageLevel').model;

const User = idOfUser
const Language = idOfLanguage
const LanguageLevel = idOfLanguageLevel

const newUserLanguageLevel = new UserLanguageLevel({
    User,
    Language,
    LanguageLevel
})

newUserLanguageLevel.save((err) => {
    if(!err){
        const UserLanguageLevelId = newUserLanguageLevel._id
        console.log(`Created id: ${UserLanguageLevelId}`)
    } else {
        console.log(err)
    }
})

/**
 * Fetiching Data
 */


keystone.list('UserLanguageLevel').model.findOne({
    _id: UserLanguageLevelId
}).exec((err, userLanguageLevel) => {
    if(userLanguageLevel){
        /**
         * found
         */

         /**
          * http://keystonejs.com/docs/database/#relationship-fields
          */
    } else if(err){
        /**
         * Error
         */
        ...
    } else {
        /**
         * Not found
         */
        ...
    }
})`
