### ISSUE TITLE
Types.Text size validation

### ISSUE THREAD

**Issue by shankarjois** [keystonejs/keystone#4520]
### Expected behavior
Types.Text
min and max char limits are not being enforced

### Actual/Current behavior
Types.Text Validations are not enforced

### Steps to reproduce the actual/current behavior
mytext: {
			type: Types.Text,
	                 label: 'mytext'
			default: '123412341234',
			minChar: 0,
			maxChar: 12
		},

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by stennie** [comment]
@shankarjois The options for Text field length are  `min` and `max` (not `minChar` and `maxChar`).

For more information, see [Text Field](http://keystonejs.netlify.com/api/field/text) in the Keystone 4 documentation.

Regards,
Stennie
