### ISSUE TITLE
Setting up custom middleware for Keystone 4

### ISSUE THREAD

**Issue by camslabosz** [keystonejs/keystone#4528]
Is there a simple way to setup custom middleware for Keystone 4?

I am using Keystone as a framework for a RESTful API. Ideally I'd like to use JWT tokens for user authentication because of use for a mobile app. 

While this question is specific to JWT, more generally, it would be good to know how to hook into the middleware to leverage custom per/post methods. 

/routes/index.js

`keystone.pre('jwt', middleware.jwt);`

/routes/middleware.js
```
exports.jwt = function (req, res, next) {
	...
        next()
};
```
I receive the following error

```
if (cache.opts.strict) throw new Error('Hooks for ' + hook + ' are not supported.');
Error: Hooks for pre:jwt are not supported.
```

| Software         | Version
| ---------------- | -------
| Keystone         |  4
| Node             |  7.1.0

**Comment by laurenskling** [comment]
the first param of `pre` should be something like `render` or `routes`. It's a step in the chain. There is not `jwt` step.
