### ISSUE TITLE
The email and password you entered are not valid.

### ISSUE THREAD

**Issue by oacostam** [keystonejs/keystone#4534]
In keystone@4.0.0-beta.5, after default install, I can't login to application. It shows message "The email and password you entered are not valid." Using default config:

? Enter an email address for the first Admin user: user@keystonejs.com
? Enter a password for the first Admin user:
 Please use a temporary password as it will be saved in plain text and change i
t after the first login. admin

Inside updates/0.0.1-admins.js I have:

```
exports.create = {
	User: [
		{ 'name.first': 'Admin', 'name.last': 'User', 'email': 'user@keystonejs.com', 'password': 'admin', 'isAdmin': true },
	],
};
```

This is the content of my database:

// users collection content
```
 db.users.find().pretty();
{
        "_id" : ObjectId("5a3ada0c5c5b6a23ac1fdd7e"),
        "password" : "$2a$10$wVsW2fTlGUrxEb2EFym9BOCwMpgLjvTquh6nzQWy1gwpTRfldpx.C",
        "email" : "user@keystonejs.com",
        "isAdmin" : true,
        "name" : {
                "last" : "User",
                "first" : "Admin"
        },
        "__v" : 0
}

```
```
// app_updates collection content
 db.app_updates.find().pretty();
{
        "_id" : ObjectId("5a3ada0c5c5b6a23ac1fdd7f"),
        "key" : "0.0.1-admins",
        "appliedOn" : ISODate("2017-12-20T21:45:48.496Z"),
        "__v" : 0
}
```

Running on W7, node v8.9.0

**Comment by suiwenfeng** [comment]
have you installed twice with different email/password?
you should use the former since the email/password won`t change when mongodb first initilaized.

**Comment by myadzel** [comment]
I have same problem when I changed user model name.

**Comment by stennie** [comment]
@oacostam I can't reproduce this issue in a fresh install of Keystone v4.0.0-beta.8, so assume this was something specific to your deployment.

Regards,
Stennie
