### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [keystonejs/keystone#4544]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by htor** [comment]
keystone is highly configurable, so if people want to they can use whatever template engine they want to that is compatible with expressjs. if you scaffold your keystone projects with the yeoman generator it will give you a list of engines to choose from. the best way, i think, to have people use template-literal in keystone would be to submit a pull request to the generator repo: https://github.com/keystonejs/generator-keystone.
