### ISSUE TITLE
New Markdown Editor is Stripping Classes from HTML

### ISSUE THREAD

**Issue by cwbuecheler** [keystonejs/keystone#4553]
### Expected behavior
I put raw HTML code into Markdown that includes `<div class="foo"></div>`, and that class attribute carries on through when the item is saved to the database and/or viewed.

### Actual/Current behavior
`<div class="foo">` is reduced to `<div>`. Additionally, HTML entities such as `&laquo;` and `&hellip;` are replaced with their UTF-8 characters (« and …), which is undesirable.

### Steps to reproduce the actual/current behavior
Create a new item (or edit an existing one) that includes a markdown field. Use raw HTML in your markdown with at least one class attribute. Save the item and either hit refresh and look at the code in the markdown box, or go look at the item in whatever your display view is. The class will be stripped.

### Caveat
This is probably a problem with Marked, not Keystone, but I don't know whether it's possible to disable this stripping in Marked. If so, I think Keystone should disable it by default.

### Environment

Ubuntu 16.4 server

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0-beta.7
| Node             | 7.72 (also happens on v8.9.4 locally - Windows 10 machine)

**Comment by cwbuecheler** [comment]
Update: actually, I don't think it's Marked. I think this commit is causing my issue: https://github.com/keystonejs/keystone/commit/5cb6405dfc0b6d59003c996f8a4aa35baa6b2bac#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

I get that safety's important but I need custom classes in my markdown for display purposes. I'm investigating whether I can turn this off, but if someone knows a quick way to do it, please let me know.

**Comment by cwbuecheler** [comment]
Second update, for anyone else running into this type of issue: you can change the sanitize options on a per-markdown-field basis by editing your model. Info on the sanitize options can be found here: https://www.npmjs.com/package/sanitize-html#what-are-the-default-options (that URL is in the Keystone.js code -- thanks!). Here for example is how you would just go ahead and allow all tags and all attributes:

```
content: {
  type: Types.Markdown,
  height: 500,
  sanitizeOptions: {
    allowedTags: false,
    allowedAttributes: false
  }
},
```

The [Markdown field section of the Keystone docs](http://keystonejs.com/docs/database/#fieldtypes-markdown) doesn't currently mention the `sanitizeOptions` option. Should I leave this issue open until that's addressed, or close it out?

**Comment by stennie** [comment]
@cwbuecheler FYI the [Markdown](http://keystonejs.com/docs/database/#fieldtypes-markdown) docs you referenced are for Keystone v0.3.

The `sanitizeOptions` configuration was added for Keystone v4 and is included in the updated documentation: http://keystonejs.netlify.com/api/field/markdown.

Regards,
Stennie
