### ISSUE TITLE
Keystone Express Router Options

### ISSUE THREAD

**Issue by Belcebur** [keystonejs/keystone#4554]
I am using child routes and it does not pass me the parameters of the parent routes. I have seen that in express there is an option to mergeParams when you create the Router, as it is done in keystone?

[http://expressjs.com/es/api.html#express.router](http://expressjs.com/es/api.html#express.router)

Thanks

**Comment by kylemcd** [comment]
When declaring your routes you should be able to do something like this

`app.get('/page/:parent/:child', <middleware>, <routes>);`

From there you can access those variables on that respective page's file in your views folder by requesting it like this.

`req.params.parent` or `req.params.child`

**Comment by Tapudp** [comment]
Hello guys I'm new to open source contribution, I have been practicing to create web apps with node.js/express.js. I curious to code this project I mean focus on this particular issue, as I feel I can play around with routes. Can someone please explain what is need here , I mean which files need what modification. 

I'm sorry if I sound vague, I'm new to this. Thanks

**Comment by autoboxer** [comment]
@Belcebur, it sounds like `mergeParams` will fit your needs, however, this is worth noting from the docs for **express.Router([options])**:

>mergeParams preserves the req.params values from the parent router. If the parent and the child have conflicting param names, the child’s value take precedence.

I haven't tried the solution provided by @kylemcd, however, I'm hoping one of the two will work for you.  Let us know if this answers your question.

**Comment by autoboxer** [comment]
@Tapudp, the easiest place to have ongoing discussion is on the Keystone Slack.  If you're interested in joining, send me an email at jared.j.collier@gmail.com with the email address you'd like to use.  For this particular question, it sounds like it may be answered, so there's probably not be much to do here. 
 If you're not sure where to start, we'll ask for help on issues we identify as priority and you can always take one you feel is within your ability.  There are channels in Slack where you can reach out and ask for help if you want a second opinion or you're stuck trying to solve a problem.
