### ISSUE TITLE
能不能修改图片上传服务商？Can you modify the picture uploads？

### ISSUE THREAD

**Issue by chenyinlong** [keystonejs/keystone#4556]
因为我在中国，所以我想知道是不是可以修改成为本地化的图片服务商，比如：七牛云（https://www.qiniu.com）？
Because I'm in China, I want to know if I can modify it to be a localised picture service provider，for example 七牛云（https://www.qiniu.com）？

**Comment by larskarbo** [comment]
You would need to create another field. Custom fields are not possible (yet) in keystone.

You can fork keystone and add your own custom field. Have a look at the `cloudinaryImage` folder in `field/type`. The important stuff for you is the `cloudinaryimage.prototype.addToSchema` function in `CloudinaryImageType`. There you would have to swap the `cloudinary` library with the one of your choice

**Comment by morenoh149** [comment]
closing as answered, keystone related issue.
