### ISSUE TITLE
Unknown Keystone List 

### ISSUE THREAD

**Issue by vamshi9** [keystonejs/keystone#4557]
### Expected behavior

When I click the research button on the front end of user panel it is supposed to load the page without any errors.

### Actual/Current behavior

![unknownkeystonelisterror](https://user-images.githubusercontent.com/11611776/35374004-1138a2fc-01c7-11e8-80fc-bdaa86e10814.PNG)

**Comment by morenoh149** [comment]
Please share your code.

**Comment by laurenskling** [comment]
Keystone cannot find a list called "research". This is not a problem with keystone, this is a problem with your code. Did you register "research"?
