### ISSUE TITLE
Cannot use AdminUI on IE11

### ISSUE THREAD

**Issue by Alekshar** [keystonejs/keystone#4558]
### Expected behavior
From the AdminUI homepage, I want to get the list of contents for a model.

### Actual/Current behavior
The list is stuck in the loading process

The developer console indicates : 
Unable to get property 'length' of undefined or null reference.
File : admin.js, line : 20476, column : 3

### Steps to reproduce the actual/current behavior
Try to access the AdminUI with IE11. The bug also appears in the Demo website.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  tried with 4.0.0-beta.5 , 7 and 8

**Comment by stennie** [comment]
This appears to be the same issue as #3734 which has a PR under discussion (#4641). We need some testing to confirm the fix works, but I'm going to close this as a duplicate.

Regards,
Stennie
