### ISSUE TITLE
Unknown cloud_name (Cloudinary)

### ISSUE THREAD

**Issue by bkvaiude** [keystonejs/keystone#4563]
![screen shot 2018-02-04 at 3 28 42 pm](https://user-images.githubusercontent.com/1251610/35776358-e9d11e0e-09c0-11e8-8272-a49ad06e9d4b.png)

Image has been uploaded to cloudinary using same access credentials, but not able to fetch and display it in the blog post
 
### Actual/Current behavior

Failed to fetch the image from cloudinary using same credentials

### Expected behavior

Image suppose to be accessible using same access credentials 

### Steps to reproduce the actual/current behavior

Add following setting to the Keystone.js file

keystone.set('cloudinary config', { cloud_name: 'asd', api_key: 'acsd', api_secret: 'asd-asd' });

Create a post on the admin panel by adding image

Visit a blog post as a guest or admin

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | latest
| Node             |  9.3.0

**Comment by shixueqiang** [comment]
I have the same problem, then I add ".env" file to root dir
COOKIE_SECRET=xxxxxxxx
CLOUDINARY_URL=cloudinary:xxxx

**Comment by josselinbuils** [comment]
Hello, you need to set the **CLOUDINARY_URL** environment variable, or call **cloudinary.config** yourself in the **cloudinaryUrl** helper method.
