### ISSUE TITLE
Can't type float number (1.23, 3.44 ) with NumberArray field

### ISSUE THREAD

**Issue by moJiXiang** [keystonejs/keystone#4564]
I use NumberArray Type, I want to save data like [1.33, 4.55, 4.2]， but On the admin UI, I cant type dot,  Then the data saved is [133, 455, 42].

**Comment by hatzipanis** [comment]
+1

Really need this for something we're currently working on. Imagine it's related to #930?

**Comment by stennie** [comment]
@hatzipanis Issue #930 was reported fixed in Keystone 0.3.0. What version of Keystone are you using?

Regards,
Stennie

**Comment by hatzipanis** [comment]
@stennie keystone@4.0.0-beta.5 but I meant that this looks like the same bug that plagued the Number type back then. Although I haven't looked at this deeper yet.

**Comment by hatzipanis** [comment]
Thanks for looking into it @stennie, appreciate it.

Will just have to wait for the RC.

**Comment by ttsirkia** [comment]
I guess this line https://github.com/keystonejs/keystone/blob/master/fields/types/numberarray/NumberArrayField.js#L14 is causing problems.

**Comment by stennie** [comment]
Thanks to @ttsirkia, a fix for this issue has been committed for v4.0.0-rc.2.

Regards,
Stennie
