### ISSUE TITLE
 4.0.0-beta.8 Admin endless loading

### ISSUE THREAD

**Issue by vivien-ps** [keystonejs/keystone#4566]
### Expected behavior
Before migrating from 4.0.0-beta.5 to 4.0.0-beta.8, my admin pages were loading perfectly.

### Actual/Current behavior
Since the update the when I go to any page of the admin, (Out of the admin / page),
I have endless loading and no errors in the console.

### Environment

| Software         | Version
| --------------- | -------
| Keystone        |  4.0.0-beta.8
| Node              |  9.4.0
| Npm               | 5.6.0

**Comment by vivien-ps** [comment]
If you have this case do a full:
npm unistall keynote
check your package.json version
remove the node_modules directory
and do:
npm install keynote@4.0.0-beta.8
npm install

**Comment by mpvillafranca** [comment]
I'm having the same issue. I tried the same but in my case it didn't work. When I go to a model view page inside the admin site, it keep always loading with the thre dots:
![image](https://user-images.githubusercontent.com/5960630/36180030-0c44b74c-111f-11e8-99eb-b1ed5f5fdde1.png)

**Comment by vivien-ps** [comment]
Did you check your package.json ?
Put it here and i can compare to mine if you want.
________________________________

**Comment by PTZ2002** [comment]
Hy,

Could you please write down your package.json data to check if everything is ok?

**Comment by mpvillafranca** [comment]
Sure. Here it is:
![image](https://user-images.githubusercontent.com/5960630/36216375-ec5bbb34-11ae-11e8-82fd-c81781ce49f8.png)

**Comment by PTZ2002** [comment]
Your node and npm version is same as the issue posted by vivien-ps? 
I will make an environment based on your node and npm and I will try to search a solution for your problem.

**Comment by mpvillafranca** [comment]
Just found that the problem comes when you try to use a custom admin panel path as I was using another one, instead of "/keystone". I tried to get it back to default and it worked. So, it maybe might be marked as an issue...

Someone is having the same problem here: #4567 

![image](https://user-images.githubusercontent.com/5960630/36219309-39619234-11b7-11e8-9618-ce68496befe6.png)

![image](https://user-images.githubusercontent.com/5960630/36219320-41a242d6-11b7-11e8-8745-a274f214160a.png)

**Comment by vivien-ps** [comment]
I have a custom path and no problem at all.

**Comment by mpvillafranca** [comment]
But your keystone version in that package.json is 4.0.0-beta.5 not 4.0.0-beta.8.

**Comment by tmvanetten** [comment]
I can make the admin path fail with 4.0.0-beta.5 OR 4.0.0-beta.8 when using a keystone application that was not created with the generator.  If I create a keystone application with the generator then the admin path works.  I believe it has something to do with the fact that non generator created keystone applications created via rpm install do not have the bundle files.  Anyone else seeing this?

**Comment by EternallLight** [comment]
I created my app with the generator and have this issue, too.

**Comment by vivien-ps** [comment]
Sorry wrong Project package.json.
Looking at the right one, the only difference is that you have packages that I am not using.

**Comment by PTZ2002** [comment]
Working on a solution for this bug, will come back with updates :)

**Comment by MillerApps** [comment]
Any news on this?

**Comment by stennie** [comment]
@MillerApps This issue in beta 8 should be resolved via #4567 (PR: #4586).

It's a one line change if you want to try patching your local copy of Keystone: https://patch-diff.githubusercontent.com/raw/keystonejs/keystone/pull/4586.patch.

Regards,
Stennie
