### ISSUE TITLE
Admin UI does not show the list of users when using a custom path

### ISSUE THREAD

**Issue by EternallLight** [keystonejs/keystone#4567]
Hello,

For security reasons, I would like to change the admin path from /keystone to a custom path. 
It was not hard to find that this functionality is already implemented and `keystone.set('admin path', 'customadminpath');` should do the job. After applying this setting, I noticed that the list pages no longer show the list of items and get frozen with endless progress animation. Inspection in dev tools shows that request to /keystone/api/ (in new case, /customadminpath/api) does not go out. If I make a GET request to /customadminpath/api/... manually, I receive a correct response with the list of items, so it rather seems like the front-end application issue. 
I'm slightly familiar and can take a look at this matter. Do you still accept pull request?

Thanks,
Andrey.

**Comment by hugominas** [comment]
yes, same happening with me, but for all list types, when changing back to default path it works again. Let me know if you need help

**Comment by udox-cameron** [comment]
Same here.

**Comment by Noviny** [comment]
At a guess, this means either we are not doing the admin path check correctly as we are doing here:

https://github.com/keystonejs/keystone/blob/171be0c097a9cc74d0ed11920630f092de39f9c6/admin/client/utils/List.js#L229

Or, there is a point where the admin path is not set correctly. Can any of you narrow down which of these two cases it is?

**Comment by udox-cameron** [comment]
I have found the problem it is this line of code, remove it and it works.

https://github.com/keystonejs/keystone/blob/ce14c517cbb748c3d7c2fc0580974e57c8f914dc/admin/client/App/sagas/queryParamsSagas.js#L71

`if (pathname !== `/keystone/${currentList.id}`) return;`

**Comment by tmvanetten** [comment]
confirmed that @udox-cameron 's suggestion does fix it.

**Comment by radames** [comment]
@udox-cameron fix didn't work for me, using 4.0.0-beta.8,

**Comment by udox-cameron** [comment]
@radames did you clear your cache as this is client side code?

**Comment by radames** [comment]
@udox-cameron thanks, you're right the cache was the problem. I've ended up solving it using the proper session `${Keystone.adminPath}` variable

https://github.com/radames/keystone/commit/f10a9233df4c14ce1df2f8c1839255f727bb2b2b#diff-f2d2df298511cc65f89c3f74048449f7L71

https://github.com/radames/keystone/blob/f10a9233df4c14ce1df2f8c1839255f727bb2b2b/admin/client/App/sagas/queryParamsSagas.js#L71

**Comment by Noviny** [comment]
Merged in the fix. Thanks @radames for providing the PR, and everyone else who helped debug it.
