### ISSUE TITLE
Trying to access keystone redirects to my main page

### ISSUE THREAD

**Issue by Awk34** [keystonejs/keystone#457]
I have the angular-fullstack yeoman-generated template, with a `/content` folder inside of it holding keystone. I tried to follow the guide for adding keystone as a sub-app, but whenever I try to visit mysite.com/content/keystone, i just get redirected back to mysite.com. Do you have any idea why this might be? My server.js file is here: http://pastebin.com/kTueV451, and my site is here: andrewkoroluk.com:9000.

**Comment by creynders** [comment]
Stale
