### ISSUE TITLE
How to run REACT.js and Keystone.js togather.

### ISSUE THREAD

**Issue by niro121** [keystonejs/keystone#4570]
Hi,

I want to know if we can run REACT custom admin with keystone. As its hard to update Keystone admin we want to use API's and do an operational back end.

Can we know if this is possible? I can't run both REACT.js and Keystone.js at the same time.

Please help.

**Comment by internetErik** [comment]
If you simply want to write your own admin interface with react, this shouldn't be a problem. You won't need to do anything special in configuring keystone in order to do it. What have you been trying so far?

**Comment by niro121** [comment]
My problem is I can't start my REACT template (https://coreui.io/react/) and run in the keystone in the same port. It always open in two ports.

Basically, my idea is to have the REACT template hosted at /admin folder and user keystone API's to manage and build back end.

Could you let me know if you know how to briefly explain run the two in the same port ?

Great help if you can help.

**Comment by internetErik** [comment]
I'm not familiar with coreui, so you may need to help me a little bit here. Does coreui (with react) provide you with a server that needs to run, or are you introducing the new server?

If not, then you can just route to the page using the express instance that keystone provides.

**Comment by niro121** [comment]
CoreUI is run by npm install and npm start and runs inside the project folder. No need to run as a different server. 

Could you kindly let me know how to write to route to /admin folder in an express instance on Keystone? I'm bit new to this. I know how to route on API in keystone though.

**Comment by internetErik** [comment]
It seems like the npm start for the coreui-react starts a webpack dev server. this ultimately just serves up an html page that refers to the built react code.

In keystone's `routes/index.js`, you can add a new route like this:

```
app.get('/admin', function(request, response) {

response.send('<the index.html from coreui>');

});
```

With this, when you go to `/admin` you should get the core-ui. However, you'll probably get errors with the script not loading for react, so you'll probably need to move the javascript into the `/public` folder.

(This really also doesn't have anything to do with keystone, but is just about express.)

**Comment by niro121** [comment]
Hi Erik,

Sorry for the silence but I was trying my best to get it solved from your input. ROUTE worked but REACT did not work. Even after putting it to /public and importing. Just HTML comes.

I followed this tutorial (https://medium.freecodecamp.org/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0) and got Express API and REACT to run.

It used PROXY method. Is this the correct way?

Is there any way you can help us with some information how to get this working in one Keystone package? Or even a small example code.

I gave my best effort to get this done, need help.

**Comment by internetErik** [comment]
Could you make a repository with what you have tried so far?

**Comment by niro121** [comment]
Hi :) We have finally made it working. Thanks so much.

**Comment by Noviny** [comment]
Glad you got it working, closing this from our issue tracker.

**Comment by siffash** [comment]
@niro121 could you share the workaround? I have the same problem.
