### ISSUE TITLE
if condition in models

### ISSUE THREAD

**Issue by vamshi9** [keystonejs/keystone#4571]
How to add if condition in Models add field?
Ex :- ```Post.add({
             if(true){
                 console.log("something goes here");
             }
          )}```

**Comment by internetErik** [comment]
If is a statement, and you can only use expressions in the body of the function call. Depending on the version of node you are using, you could use a ternary along with object destructuring like this:

```
post.add({
...(
  true ? { something: 'hello' } : {}
)
})
```

If you don't have object destructuring, you could do something like this:

```
post.add(Object.assign(
{},
(true) ? { something: 'hello' } : {}
))
```
