### ISSUE TITLE
npm install fails with node Docker images

### ISSUE THREAD

**Issue by cvn** [keystonejs/keystone#4573]
Hello,

Keystone 4.0.0-beta.8 has a regression where `npm install keystone` fails inside a `node:slim` Docker container. This issue was introduced by PR #4453, specifically the updated [knox dependency](https://github.com/keystonejs/keystone/blob/v4.0.0-beta.8/package.json#L54). It requires git for installation, which is not included in the production-focused node Docker images.

Workaround:

* add `apt-get install git` to the Dockerfile before `npm install`

Possible solutions:

* replace the `keystonejs/knox` dependency with [knox-s3](https://www.npmjs.com/package/knox-s3) (as discussed in Automattic/knox#326)
* publish `keystonejs/knox` to npm
* remove knox altogether, and replace with an alternative like [aws-sdk](https://www.npmjs.com/package/aws-sdk)

If using knox-s3 is good enough for now, I'd be happy to submit a PR. Longer term, eliminating knox seems wise.

@vitalbone, do you have an opinion?

Chad

---

### Expected behavior
`npm install keystone` should work when using the `node:slim` Docker image.

### Actual/Current behavior
It fails. This is the error with node 9.5.0 and npm 5.6.0.

    npm ERR! code ENOGIT
    npm ERR! No git binary found in $PATH
    npm ERR! 
    npm ERR! Failed using git.

For the sake of search indexing, earlier versions of npm also say:

    npm ERR! not found: git

### Steps to reproduce the actual/current behavior

1. Create a Dockerfile:

        FROM node:slim
        RUN npm install keystone

2. Build it:

        docker build .

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.8
| Node             | 9.5.0

**Comment by vitalbone** [comment]
Thanks @cvn , a PR to use [knox-s3](https://www.npmjs.com/package/knox-s3) sounds like the best option for now.
