### ISSUE TITLE
Could Socket.IO be used in KeystoneJS?

### ISSUE THREAD

**Issue by pravosleva** [keystonejs/keystone#4576]
### Expected behavior
Could Socket.IO be used in KeystoneJS? How can I enable it?

### Steps to reproduce the actual/current behavior
Sorry, I have no idea.

### Environment
Ubuntu 16.04

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5
| Node             | 8.9.4

**Comment by ttsirkia** [comment]
Here is some code that I've been using with Keystone 0.3:

__keystone.js__

```javascript
keystone.start({
  onHttpServerCreated : function() {

    var io = require('socket.io');   
    io = io.listen(keystone.httpServer);

    // Attach session to incoming socket
    io.use(function(socket, next) {
      keystone.get('express session')(socket.request, socket.request.res, next);
    });

  }
});

**Comment by autoboxer** [comment]
I’m closing this out as answered

**Comment by molaga** [comment]
After LOT of debugging & googling, @ttsirkia answer is good, but `keystone.get('express session')` has changed to `keystone.expressSession`.
hope it will prevent others frustration :)

https://github.com/keystonejs/keystone/blob/master/docs/guides/v0.3-to-v4.0-Upgrade-Guide.md
