### ISSUE TITLE
Is there a way to sort the uiFields of a (inheritance) model?

### ISSUE THREAD

**Issue by laurenskling** [keystonejs/keystone#4578]
### Expected behavior
Im using inheritance of a model. The parent model `.add()` some fields. My child model also `.add()` some fields, but I want the child fields to be presented on top of the parent fields in the UI.

Is there a way to sort the fields?
Is there a way to "prepend" fields to the List?

### Steps to reproduce the actual/current behavior
Use the inheritance example: http://keystonejs.com/docs/database/#lists-options and try to get child_content on top of the other fields in the UI.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0-beta.8
| Node             | 8.9.4

**Comment by stennie** [comment]
@laurenskling The Keystone GitHub issue queue is for bug reports or feature suggestions. For development questions please ask on [StackOverflow](https://stackoverflow.com/tags/keystonejs) with the `keystonejs` tag.

Regards,
Stennie

**Comment by laurenskling** [comment]
I've created a function that unshifts the fields to the front of the array of fields, so it will be rendered first in the UI. Might somebody be interested in the same thing as I did:

https://www.npmjs.com/package/keystone-list-prepend
