### ISSUE TITLE
Fetching user info

### ISSUE THREAD

**Issue by vamshi9** [keystonejs/keystone#4579]
I am thinking of a way to implement co-admin dashboard(where only a few models are exposed to co-admin). 
`if(user.name == "so and so"){
     expose this model;
}else{
   hide the model
}`
In order to fetch the user info I went to path *node_modules\keystone\admin\client\App\components\Footer*
and tried to export the Footer variable and access it in my models. Since my models are not React files it is showing **unexpected token import** . Is there any other way to fetch the user name, so that it would give a temporary solution for co-admin part.

**Comment by ytsruh** [comment]
Does req.user not work?
