### ISSUE TITLE
Relationship where filters  {relatedList}_some: whereInput not working after update without errors

### ISSUE THREAD

**Issue by Temkit** [keystonejs/keystone#4580]
# Bug report

```
query {
       allItems(where: 
           { role_some: { id: "5fa13d83f96f29ecb6bed061" } }
         ) {
          id
          }
        }
      }
```

no results without error !
but this is working 

```
query {
       allItems(where: 
           { role_some: { name_starts_with_i : "some string" } }
         ) {
          id
          }
        }
      }
```

**Comment by caronbletzer** [comment]
I have the same issue since upgrading adapter-mongoose from 10.0.1 to 10.1.0.  Below is query and aggregation pipeline created by each version.  10.0.1 works, 10.1.0 does not.

query {
    allResourcePolicies(where: { group: { users_some: { id: "5fc51754972562e014f8dd4d" }}}) {
    group {
      name
      users {
        id
        name
      }
    }
    role {
      permissions {
        name
      }
    }
  }

// generated `aggregation` pipeline
// adapter-mongoose - version 10.0.1
[
  {
    $lookup: {
      from: "usergroups",
      as: "ckitcp9930000000y311l1v10_group",
      let: {
        tmpVar: "$group",
      },
      pipeline: [
        {
          $match: {
            $expr: {
              $eq: [
                "$_id",
                "$$tmpVar",
              ],
            },
          },
        },
        {
          $lookup: {
            from: "user_groups_usergroup_users",
            as: "ckitcp9930001000yeuld2j7f_users",
            let: {
              tmpVar: "$_id",
            },
            pipeline: [
              {
                $match: {
                  $expr: {
                    $eq: [
                      "$UserGroup_right_id",
                      "$$tmpVar",
                    ],
                  },
                },
              },
              {
                $lookup: {
                  from: "users",
                  as: "ckitcp9930001000yeuld2j7f_users_0",
                  let: {
                    tmpVar: "$User_left_id",
                  },
                  pipeline: [
                    {
                      $match: {
                        $expr: {
                          $eq: [
                            "$_id",
                            "$$tmpVar",
                          ],
                        },
                      },
                    },
                    {
                      $match: {
                        _id: {
                          $eq: {
                            _bsontype: "ObjectID",
                            id: {
                              "0": 95,
                              "1": 197,
                              "2": 23,
                              "3": 84,
                              "4": 151,
                              "5": 37,
                              "6": 98,
                              "7": 224,
                              "8": 20,
                              "9": 248,
                              "10": 221,
                              "11": 77,
                            },
                          },
                        },
                      },
                    },
                    {
                      $addFields: {
                        id: "$_id",
                      },
                    },
                  ],
                },
              },
              {
                $match: {
                  $expr: {
                    $gt: [
                      {
                        $size: "$ckitcp9930001000yeuld2j7f_users_0",
                      },
                      0,
                    ],
                  },
                },
              },
            ],
          },
        },
        {
          $match: {
            $expr: {
              $gt: [
                {
                  $size: "$ckitcp9930001000yeuld2j7f_users",
                },
                0,
              ],
            },
          },
        },
        {
          $addFields: {
            id: "$_id",
          },
        },
        {
          $project: {
            ckitcp9930001000yeuld2j7f_users: 0,
          },
        },
      ],
    },
  },
  {
    $lookup: {
      from: "organizations",
      as: "ckitcp9950002000yaje467f5_organization",
      let: {
        tmpVar: "$organization",
      },
      pipeline: [
        {
          $match: {
            $expr: {
              $eq: [
                "$_id",
                "$$tmpVar",
              ],
            },
          },
        },
        {
          $match: {
            _id: {
              _bsontype: "ObjectID",
              id: {
                "0": 95,
                "1": 190,
                "2": 246,
                "3": 251,
                "4": 105,
                "5": 69,
                "6": 48,
                "7": 183,
                "8": 71,
                "9": 212,
                "10": 62,
                "11": 218,
              },
            },
          },
        },
        {
          $addFields: {
            id: "$_id",
          },
        },
      ],
    },
  },
  {
    $match: {
      $and: [
        {
          $expr: {
            $eq: [
              {
                $size: "$ckitcp9930000000y311l1v10_group",
              },
              1,
            ],
          },
        },
        {
          $expr: {
            $eq: [
              {
                $size: "$ckitcp9950002000yaje467f5_organization",
              },
              1,
            ],
          },
        },
      ],
    },
  },
  {
    $addFields: {
      id: "$_id",
    },
  },
  {
    $project: {
      ckitcp9930000000y311l1v10_group: 0,
      ckitcp9950002000yaje467f5_organization: 0,
    },
  },
]
// adapter-mongoose - version 10.1.0
[
  {
    $lookup: {
      from: "usergroups",
      as: "ckitci231001nlj0ya295379y_group",
      let: {
        tmpVar: "$group",
      },
      pipeline: [
        {
          $match: {
            $expr: {
              $eq: [
                "$_id",
                "$$tmpVar",
              ],
            },
          },
        },
        {
          $match: {
            users: {
              $eq: {
                _bsontype: "ObjectID",
                id: {
                  "0": 95,
                  "1": 197,
                  "2": 23,
                  "3": 84,
                  "4": 151,
                  "5": 37,
                  "6": 98,
                  "7": 224,
                  "8": 20,
                  "9": 248,
                  "10": 221,
                  "11": 77,
                },
              },
            },
          },
        },
        {
          $addFields: {
            id: "$_id",
          },
        },
      ],
    },
  },
  {
    $match: {
      $and: [
        {
          $expr: {
            $eq: [
              {
                $size: "$ckitci231001nlj0ya295379y_group",
              },
              1,
            ],
          },
        },
        {
          organization: {
            $eq: {
              _bsontype: "ObjectID",
              id: {
                "0": 95,
                "1": 190,
                "2": 246,
                "3": 251,
                "4": 105,
                "5": 69,
                "6": 48,
                "7": 183,
                "8": 71,
                "9": 212,
                "10": 62,
                "11": 218,
              },
            },
          },
        },
      ],
    },
  },
  {
    $addFields: {
      id: "$_id",
    },
  },
  {
    $project: {
      ckitci231001nlj0ya295379y_group: 0,
    },
  },
]

**Comment by gautamsi** [comment]
this could be part of the problem. it fixed some thing but broke this I guess - https://github.com/keystonejs/keystone/pull/4536

**Comment by timleslie** [comment]
Thanks for the bug reports, I've been able to recreate this and will hopefully be able to ship a fix quickly 👍

**Comment by enhancers** [comment]
We were still on a forked version of the lib and so we didn't had the chance to detect the issue. In olders version of keystone it works well (es. v6) but not in later ones. I'm fairly sure that it's due to how the relationships are handled in later versions: previously N-N relationship implied an array stored in the Mongo document, now there is a Mongo collection that handles the relationship (in a more relational style).

We can try to take a look on this but some help would be great

**Comment by enhancers** [comment]
Ok I can confirm that the thesis above is correct. The huge problem is that performance now can't be imporved at all because if you have a N:N relationship il will perform a number of subqueries to retrieve the related items that is equal to the number of scanned documents (if you have 100K documents it will perform 100K queries + the main query).

I think the issue here is to use a strategy for N:N relationships that is correct for relational databases but it's wrong for MongoDb.

@timleslie what do you think?

Thanks!

**Comment by enhancers** [comment]
@timleslie a quick fix is to add "&& relationshipInfo.rel.cardinality !== 'N:N'" in the commented code at row 53 here https://github.com/keystonejs/keystone/pull/4591/commits/91b3d96918858c5b7d5600e77964fb5f76010dfe

In this way it will skip N:N relationships, but still remains the huge performances issue.
