### ISSUE TITLE
when is keystone offline-first?

### ISSUE THREAD

**Issue by anlexN** [keystonejs/keystone#4584]

**Comment by htor** [comment]
never. a quick code search on 'offline' and 'service worker' will pretty much answer your question. https://github.com/keystonejs/keystone/search?utf8=%E2%9C%93&q=offline&type=. 
https://github.com/keystonejs/keystone/search?utf8=%E2%9C%93&q=service+worker&type=

**Comment by anlexN** [comment]
@htor your links can not be accessed.

**Comment by stennie** [comment]
@anlexN I believe @htor's intent was to suggest that there are no results for either of the GitHub search links provided.

Keystone 4 does not currently include any offline-first features, so you would have to implement any desired logic in your application. 

Regards,
Stennie
