### ISSUE TITLE
Can not handle the path "/keystone/signin" as "/" or "/blog" in keystone 4

### ISSUE THREAD

**Issue by zhangshuiyong** [keystonejs/keystone#4598]
I use the keystone 4 at the first time. And I have not used the keystone before. 
I can not handle the path "/keystone/signin" as "/" or "/blog" in keystone 4.

Users should sign in when they want to do something in keystone. And the user signin path is "keystone/signin",But

I can not find the "keystone/signin" view in "templates/view" folder
I can not find the "keystone/signin" routes handler in "routes" folder
I can not find the "keystone/signin" js file in "pubilc" folder

This is very confusing for developer to use the keystone framework !!!

**Comment by ytsruh** [comment]
You either set it in your init method. However I have more luck using this:
keystone.set('admin path' , "admin") 
so example would be keystone.set('admin path' , "/signInUrl")

**Comment by stennie** [comment]
@ytsruh Documentation for Keystone 4 is currently a work in progress. The WIP documentation can be found at: http://keystonejs.netlify.com.

@zhangshuiyong I've labelled this issue for `documentation` since the `admin path` doesn't appear to be noted at the moment.

Regards,
Stennie

**Comment by stennie** [comment]
This issue in beta 8 should be resolved via #4567 (PR: #4586).

It's a one line change if you want to try patching your local copy of Keystone: https://patch-diff.githubusercontent.com/raw/keystonejs/keystone/pull/4586.patch.

Regards,
Stennie
