### ISSUE TITLE
Add Date / DateTime / Timestamp Fields

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#46]
We need to add three fields for managing dates to Keystone:

* `Date` - just a date, no time or timezone information stored. Good for birthdays / etc. We should probably store this as a string in the `YYYY-MM-DD` format.
* `DateTime` - a date with time and timezone information embedded. Needs more discussion on how to store / etc.
* `Timestamp` - a date stored in Epoch time.

The full DateTime field would ideally suit JavaScript + MongoDB + Postgres + GraphQL. The Admin UI should explicitly surface all three parts and let you modify them independently.

Not 100% sure that all three add value, in that `DateTime` and `Timestamp` kind of store the same thing, except (I believe) that storing dates in Epoch time strips them of their timezone.

Over to @molomby / @jesstelford / @dominikwilkowski / @timleslie to discuss.

On the client-side, we'll need a few new components:

* Date Input
* Time Input
* Field components for all three

In terms of client-side libraries, I'd like to use [date-fns](https://date-fns.org/) unless there's a compelling reason to use something else.

**Comment by molomby** [comment]
We can probably close this. It's either been implemented or superseded by more recent issues like #2937 and #2938.

**Comment by molomby** [comment]
The [Temporal proposal](https://tc39.es/proposal-temporal/docs/index.html) is relevant to this. We'll probably revisit some of our field types as it become standard.

> Date has been a long-standing pain point in ECMAScript. This is a proposal for Temporal, a global Object that acts as a top-level namespace [..], that brings a modern date/time API to the ECMAScript language.
