### ISSUE TITLE
CloudinaryImages enhancements

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#46]
- [ ] Remove all button to remove/delete all images from field
- [x] Add re-ordering (uploaded images only)

**Comment by TMcLoone** [comment]
Hi all, any news on adding the drag-and-drop functionality? I'm eager to get started with Keystone but there seems to be a big gap in image management

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. Please ask this question on [productpains.com](https://productpains.com/product/keystonejs)!
