### ISSUE TITLE
node-gyp build error

### ISSUE THREAD

**Issue by byul5810** [keystonejs/keystone#4606]
I received this error when I generate keystone with yo keystone.
what should I do?. Thanks in advance.

<gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.13.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/byul/바탕화면/test6/node_modules/keystone/node_modules/kerberos
gyp ERR! node -v v4.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by kennedybaird** [comment]
I am having this error too.

Thanks

**Comment by 1337cookie** [comment]
Is there more in your output window?

**Comment by 1337cookie** [comment]
ubuntu:
sudo apt-get install -y build-essential
windows in cmd/powershell etc with administrative rights:
npm install -g windows-build-tools

**Comment by BitBruce** [comment]
Having this error as well.

```
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/brucerobinson/Git/brucefun/keystone/node_modules/ursa
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> node-sass@4.5.0 install /Users/brucerobinson/Git/brucefun/keystone/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/darwin-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/darwin-x64-64_binding.node": 

HTTP error 404 Not Found
```

There is no `https://github.com/sass/node-sass/releases/download/v4.5.0/darwin-x64-64_binding.node` file, there are similar files at `/darwin-x64-XX-_binding.node` where `XX` can be 51 or a few other numbers (https://github.com/sass/node-sass/releases/tag/v4.5.0).

I can't seem to find where to edit that url (is it in npm itself somewhere?), but upgrading to the latest 4.9 worked (didn't try an earlier version). Also had to install `npm i node-sass-middleware`.

**Comment by kennedybaird** [comment]
If you are running Linux you need to install build tools, it's not exactly
to do with node.

`sudo apt-get install -y build-essential`

(╯°□°)╯︵

**Comment by BitBruce** [comment]
Installing a higher version of node-sass fixes it. It's more of an issue with the keystone yeomen generator, I will report the issue there and open a PR.

**Comment by BitBruce** [comment]
Seems to be a more complicated issue.

**Comment by 1337cookie** [comment]
The node-gyp is one error and the sass thing is another. You should still follow the macosx guide to get rid of the gyp errors. It might fix your other issues or at least you won't be getting them mixed up.
https://github.com/nodejs/node-gyp#on-mac-os-x

**Comment by stennie** [comment]
`node-gyp` compilation errors are related to the Node.js package toolchain and outside the scope of Keystone.

For general tips resolving `node-gyp` errors, the README is a good starting point: https://github.com/nodejs/node-gyp#node-gyp. If you're still stuck, you could also try [posting a question on StackOverflow](https://stackoverflow.com/tags/node-gyp) with more details of your issue (O/S version, Node.js version, and the specific build error message).

Regards,
Stennie
