### ISSUE TITLE
Node Sass not installed on base install

### ISSUE THREAD

**Issue by spkellydev** [keystonejs/keystone#4611]
Hey I just did a clean install of Keystone and included the Sass loader. 
### Expected behavior

`node keystone` would get the project running

### Actual/Current behavior

```
ERROR: node-sass not found.

Please install the node-sass-middleware from npm to use the `sass` option.
You can do this by running "npm install node-sass-middleware --save".
```
Sass middleware not installed

### Environment

| Software         | Version
| ---------------- | -------
| Keystone          |  "keystone": "4.0.0-beta.5",
| Node               |  $ node --version v8.9.4
| OS                   | Windows 10
| Terminal          | Git Bash for Windows

Installing the module fixed the issue and everything worked as expected. I just figured I'd inform you that there was an issue with the sass module on a base install. Can't wait to try out Keystone, hearing a lot of good things.

**Comment by Norbz** [comment]
Listing node-sass as a keystone dependency would actually be a bad thing. It would require everyone to fetch and install it even when working with other CSS preprocessor. That's why it should be listed in your dev dependencies.

This is really true for node-sass that has a lot of troubles with some WSL installs, and that doesn't support node v9.x

**Comment by laurenskling** [comment]
please no. Node-sass is the reason why I stepped away from sass. Use it if you want, but it has nothing to do with core keystone, right?

**Comment by stennie** [comment]
@spkellydev The Keystone core aims to be non-opinionated and does not require sass.

However, this could be an issue with the Keystone Yeoman generator (`generator-keystone`). Looks like the same issue as: https://github.com/keystonejs/generator-keystone/issues/265.

Regards,
Stennie
