### ISSUE TITLE
How to add cursor hover effect in keystone model property on admin side

### ISSUE THREAD

**Issue by umairjameel321** [keystonejs/keystone#4620]
Earlier I had issue in adding url and found the answer in my [question](https://github.com/keystonejs/keystone/issues/4607#issuecomment-382856648)
Answer given by [epinapala](https://github.com/epinapala)
Now let say I have a Url property  in my model as

` publicUrl: { type: Types.Url, noedit: true},`

It is clickable but when I hover over it, cursor shows a straight pipe line like it shows when we hover on input text box.  I want cursor to be pointer when I hover on it.

**Comment by stennie** [comment]
@umairjameel321 The Keystone GitHub issue queue is for bug reports or feature suggestions. For development questions please ask on [StackOverflow](https://stackoverflow.com/tags/keystonejs) with the `keystonejs` tag.

Regards,
Stennie
