### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#4622]
Has anyone implemented GDPR compliance for a global website based on keystone.js

**Comment by stennie** [comment]
@VinayaSathyanarayana GDPR compliance has a much broader scope around data management and privacy practices. I don't believe there are any feature requirements for Keystone to implement, but you should look into more specific advice for your use case.

FYI: MongoDB has a white paper you can download with more information on data security features and server considerations: [GDPR: Impact to Your Data Management Landscape](https://www.mongodb.com/collateral/gdpr-impact-to-your-data-management-landscape).

Regards,
Stennie
