### ISSUE TITLE
*.keystone.com should be served over https

### ISSUE THREAD

**Issue by htor** [keystonejs/keystone#4625]
this is important when promoting a serious cms like keystone to the world. given that you can get free ssl certs with tools like https://certbot.eff.org this shouldn't be a big task. the certbot will install everything for you and setup a cron job for automatic renewal. setting up a certificate should be done for each subdomain, like demo.keystonejs.com. maybe a wildcard cert would be nice here?

**Comment by stennie** [comment]
This was done as part of the Keystone 4.0 release:
 - https://keystonejs.com
 - https://demo.keystonejs.com

**Comment by htor** [comment]
@stennie nice! when did 4.0 get released?
