### ISSUE TITLE
atTracking doesn't allow editing of createdAt field

### ISSUE THREAD

**Issue by Firfi** [keystonejs/keystone#4626]
# Bug report
atTracking (https://www.keystonejs.com/keystonejs/list-plugins/at-tracking) with `access: { read: true, create: true, update: true}` allows editing (through admin ui) updatedAt, but not createdAt

## Describe the bug
updatedAt can be edited AND saved; createdAt can be edited but the changes aren't saved and there's no error anywhere

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

in model,

```
plugins: [atTracking({
    access: {
      read: true,
      create: true,
      update: true
    },
  })]
```

## Expected behaviour

I can edit createdAt

## Screenshots

![Screenshot 2020-12-30 at 11 08 35 AM](https://user-images.githubusercontent.com/947595/103329473-662dfa00-4a8f-11eb-82bb-8f05f920d633.png)

## System information

- OS: osx
- Browser: chrome
- keystone: 18

**Comment by gautamsi** [comment]
createdAt is specifically removed from the input when updating item.
