### ISSUE TITLE
Why node require in function level in cloudinary.js

### ISSUE THREAD

**Issue by ewdave** [keystonejs/keystone#4627]
I was just going through the `/admin/server/api/cloudinary.js` file and noticed it's importing the cloudinary node library at the function level -- in three separate functions. 

Is there a specific reason it's doing this as against importing it at the package/module level ?  Seeing the `require` action is synchronous.

see - 
- https://github.com/keystonejs/keystone/blob/936f301d62c08f9f3bafed29efff4a343e74e698/admin/server/api/cloudinary.js#L7

- https://github.com/keystonejs/keystone/blob/936f301d62c08f9f3bafed29efff4a343e74e698/admin/server/api/cloudinary.js#L38

- https://github.com/keystonejs/keystone/blob/936f301d62c08f9f3bafed29efff4a343e74e698/admin/server/api/cloudinary.js#L60

**Comment by JedWatson** [comment]
From memory, we went through a whole effort to reduce the initial boot time by only requiring packages you were actually using (when they were first used).

`require` is sync but cached, so you only pay the cost of this once the first time the API route is hit. It's a trade-off with doing the require when Keystone is first required, which would include users that aren't even using coudinary.
