### ISSUE TITLE
How do I implement a fulltext search using keystone.js ?

### ISSUE THREAD

**Issue by linuxenko** [keystonejs/keystone#4631]
Hi 🦄 

I'm thinking about providing search functionality, especially fulltext search using `keystone.js` for my application. What if I would like to make input field that provides search functionality for the user ? It hides a lot of difficulties even for implementation based on the pure mongodb driver. I'd describe them for better understanding.

1. Displaying suggestions when I type
2. Paginated list of the records based filtered by the search text

I'm not sure I know the `keystone.js` functionality good enough, maybe there is a solution for my issue ? How did you make your fulltext search ? Any ideas ? 🤣

**Comment by stennie** [comment]
@linuxenko The Keystone GitHub issue queue is for bug reports or feature suggestions. For development questions please ask on [StackOverflow](https://stackoverflow.com/tags/keystonejs) with the `keystonejs` tag.

Regards,
Stennie
