### ISSUE TITLE
Different roles of Admins in the UI

### ISSUE THREAD

**Issue by luismsaraiva** [keystonejs/keystone#4636]
Hi,
I would like to know of it is possible to have different roles for the admins. For example the manager is the only one to have access to the User Model. And another role is employee he only has access to the Companies that he is associated with.

Thanks!!!

 
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by stennie** [comment]
@luismsaraiva Keystone 4 currently doesn't include a more advanced role/permission feature out of the box. There have been several issues with discussion on how to approach, most notably #2111 and #803.

You can implement something custom in your application in the interim (perhaps using one of the Express RBAC packages), but there is no specific recommendation at the moment.

Regards,
Stennie
