### ISSUE TITLE
How can I use keystone model from other app?

### ISSUE THREAD

**Issue by nevermoreluo** [keystonejs/keystone#4637]
| Software         | Version
| ---------------- | -------
| Keystone         |   4.0.0-beta.5   |
| Node             |  v8.9.1  |

I am new in nodejs, and find out keystone is so much powerfull.
Thank you very much.

We want use keystone model to other app, and I created an file called test.js
```
let keystone = require('keystone');
keystone.init({ mongo: 'mongodb://192.168.20.99:27017/test' });

// Load your Models
keystone.import('models');

let Config = keystone.list('Config');

function test () {
    Config.model.find({}, function (err, config) {
        console.log(err);
        console.log(JSON.stringify(config));
    });
}
test();
```

I'm sure test.js and keystone.js is in the same dir, something like this:
```
my_p
 \__ models
 ....
 \__ keystone.js
 \__ test.js
```

My keystone app just work fire.

But `node test.js` has nothing to return, and nothing in the console log.

When I debug test.js in my webstome, find out  

`Config.model.base.connections[0].host` get null

and in keystone.js I get "192.168.20.99"

How can I get this work?
Sincerely yours

**Comment by nevermoreluo** [comment]
I have an work through by read source code, from keystone version 4.0.0-beta.5.

Add blew code before `keystone.list('config')`
```
keystone.openDatabaseConnection(function () {
    return this;
});
```
Is there any suggestion ?

**Comment by pomeo** [comment]
If anybody will search. Example with code from above.
```
const keystone = require('keystone');
keystone.import('models');
keystone.mongoose.connect('mongodb://192.168.20.99:27017/test', {
	socketTimeoutMS: 0,
	keepAlive: true,
	reconnectTries: 10
});
const Config = keystone.list('Config');
Config.model.find({}, function (err, config) {
       console.log(JSON.stringify(config));
});
```
