### ISSUE TITLE
'context.startAuthedSession' error when attempting user authentication

### ISSUE THREAD

**Issue by ClientsideDesign** [keystonejs/keystone#4639]
# Bug report

Unable to retrieve an access token using `authenticateUserWithPassword`.

## Describe the bug

When trying to use `authenticateUserWithPassword` to retrieve an access token as outlined on [this page](https://www.keystonejs.com/guides/authentication), I get the following error:

`TypeError: context.startAuthedSession is not a function`

- I get an appropriate response if I intentionally provide incorrect user credentials, so I believe these are being processed correctly
- The query in my code (below) works as expected in the GraphQL playground

The full error is:

`TypeError: context.startAuthedSession is not a function at ListAuthProvider._authenticateMutation (/Users/user/Dev/crane/server/node_modules/@keystonejs/keystone/lib/providers/listAuth.js:253:33)`

## To Reproduce

My code is as follows:

    async function authenticate(keystone, email, password) {
      const context = keystone.createContext();
      const keystoneAuth = await keystone.executeGraphQL({
        context,
        query: `mutation signin($email: String, $password: String) {
          authenticate: authenticateUserWithPassword(email: $email, password: $password) {
            item {
              id
            }
            token
          }
        }`,
        variables: { email, password },
      });
      console.log(keystoneAuth);
    }

## Expected behaviour

I expect the code to successfully authenticate the user and provide their ID and an access token.

## System information

- macOS
- Node v14.15.4
- Keystone v18

## Additional context

Thanks for all your hard work - I've been using Keystone for a few months now and it's an excellent application.

**Comment by gautamsi** [comment]
when you already have context why not use that to `startAuthedSession` ?

**Comment by ClientsideDesign** [comment]
Thanks for the quick reply! I couldn't find any documentation on `startAuthedSession`, though I did find your discussion [here](https://github.com/keystonejs/keystone/discussions/3296).

The use-case is that I have a separate front-end app. User credentials (email & password) are posted from the app to the server-side function above, so they can get an access token to make further requests to my Keystone instance.

`authenticateUserWithPassword` seemed like the most natural fit for this, but very open to other suggestions?

**Comment by ClientsideDesign** [comment]
I should have said, do tell me if this isn't a bug and I'm doing something incorrectly.

**Comment by gautamsi** [comment]
I don't know if you have a bug or not, you can call the graphql from the frontend itself rather than have backend proxy function for this. I was thinking like you have a separate way to auth user and you want to create authenticated session.

**Comment by ClientsideDesign** [comment]
Yes you're right I want authenticate users without using the Keystone front-end. The user's credentials are posted to a custom Express endpoint from my app, which should authenticate them and return their access token, using the code above.

[These instructions](https://www.keystonejs.com/guides/authentication#programmatic-authentication) seem to cover my use-case perfectly, but I've tried a few things and am still getting an error.

It's possible I've missed a necessary setup step but other graph queries (using the same approach) are working fine, so I believe it's a bug with `authenticateUserWithPassword`.

Thanks

**Comment by ClientsideDesign** [comment]
Thanks for your input @gautamsi - I believe I've found a solution based on your previous answer. Will update shortly if so.

The main issue seems to be that I needed to provide an `expressSession` in my Express config. More info [here](http://expressjs.com/en/resources/middleware/session.html).

**Comment by ClientsideDesign** [comment]
For anyone else that arrives here, below is the code I am currently using to programatically authorise a user and return their details and an access token. The login process is a bit longwinded, but I can't currently get `authenticateUserWithPassword` to work as I believe it should.

As per [this discussion](https://github.com/keystonejs/keystone/discussions/3296), the session manager package is used to begin and end the user session. `req` and `res` are the usual Express parameters and `authStrategy` is outlined [here](https://www.keystonejs.com/keystonejs/auth-password/#password-auth-strategy).

Please note that I also had to set up an `expressSession` in my Express config. More info [here](http://expressjs.com/en/resources/middleware/session.html).




    module.exports = {
    
      login: async function (keystone, authStrategy, sessionManager, req, res, email, password) {
        const result = await authStrategy.validate({
          email,
          password,
        });
        if (result.success) {
          // User authenticated successfully - get their ID based on their email address
          const context = keystone.createContext({ skipAccessControl: true });
          const userQuery = await keystone.executeGraphQL({
            context,
            query: `query($email: String) {
              allUsers(where: { email: $email }) {
                id email forename surname
              }
            }`,
            variables: { email },
          });
          // Return user details and token
          const user = userQuery.data.allUsers[0];
          const token = await sessionManager.startAuthedSession(req, {
            item: user.id,
            list: 'User'
          });
          user.token = token;
          res.send(user);
        } else {
          // Incorrect login credentials
          res.send(undefined); 
        }
      },
    
      logout: async function (sessionManager, req, res) {
        const logout = await sessionManager.endAuthedSession(req);
        res.send(logout);
      }
    
    }

**Comment by timleslie** [comment]
I think your solution in this case is the right one. The `authenticateUserWithPassword` mutation requires the context to contain a session manager, which it does not have when used on the server the way you are doing. This is not a bug per see, just a limitation of where/how this particular mutation can be used.

**Comment by ClientsideDesign** [comment]
Thanks for advising @timleslie - good to know.
