### ISSUE TITLE
Allow nested object to be provided as values to `field.updateItem` for all complex field types

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#464]
As noted by @webteckie and @metasansana in #201, fields that take objects as values only work with flattened paths when using the `UpdateHandler` to set values (which `keystone.createItems` does).

So far I've updated `Name` and `Location` to accept nested object values as well as flattened paths, the other complex field types also need to be updated:

- [ ] CloudinaryImage
- [ ] Embedly

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/allow-nested-object-to-be-provided-as-values-to-fieldupdateitem-for-all-complex-field-types

**Comment by JedWatson** [comment]
I think these are fixed in 0.4 anyway - Cloudinary definitely is. So we can kill that product pains issue @creynders
