### ISSUE TITLE
New modal does not set the proper content-type on subsequent requests

### ISSUE THREAD

**Issue by nowk** [keystonejs/keystone#4644]
### Expected behavior

Create an entry for one model and navigate (or run other interactions) and be able to create an entry for another model.

### Actual/Current behavior

When you click to create a new entry through the listing page of a model, the modal form it launches, it uses a `content-type` for multipart on the first submission. After, going to create an entry for another model, it then sets the `content-type` to `application/json` but sends the data as a multipart form.

Currently when this happens it returns an "Unknown Error" response, but the error itself is occurring within the body parser middleware because of the `content-type: application/json` and the data submitted as multipart form data.

Reloading the page after this happens sets the `content-type` back to multipart and fixes it for that submission.

### Steps to reproduce the actual/current behavior

Create an entry, then navigate to another model (or say, delete another record from the listing page) and attempt to create an entry for that model.

### Environment

The models both have file based attributes, which explains the multipart stuff, but there are no options to add a file during the initial creation modal.

| Software         | Version
| ---------------- | -------
| Keystone         |  v4.0.0-beta.4
| Node             | 6.13.1

**Comment by autoboxer** [comment]
This was marked as an issue for v4.0.0-beta.4.  @JedWatson, do you know offhand if this was addressed in any of the releases up to v4.0.0-beta-8?

**Comment by nowk** [comment]
@autoboxer Thanks for the reply. I just went ahead and updated to `...beta.8` and so far that seems to have fixed it. So thank you very much.

**Comment by autoboxer** [comment]
@nowk, that's great news, I was just about to offer that as a suggestion.  Glad it's working for you.
