### ISSUE TITLE
Complete `updateItem` implementations for complex fields

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#465]
Some field types still have TODOs for the `updateItem` function, and can only be updated directly (by setting values on an instance) or via the `getRequestHandler` method. These should have proper implementations added.

In line with the work being done in #464, we should add complete implementations for `updateItem` for these field types:

- [ ] AzureFile
- [ ] CloudinaryImages
- [ ] LocalFile
- [ ] LocalFiles
- [ ] S3File

**Comment by danielzurawski** [comment]
Is this also the reason why it's not possible to include CloudinaryImages (plural) in an update script? E.g. you can seed single CloudinaryImage, but not array of images.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/complete-updateitem-implementations-for-complex-fields
