### ISSUE TITLE
Unknown Keystone List 'FIleUpload'

### ISSUE THREAD

**Issue by hurricane987** [keystonejs/keystone#4663]
### Expected behavior

Keystone should register the 'FileUpload' list and make it available to the admin nav.

### Actual/Current behavior

Keystone throws the error "unknown Keystone list 'FileUpload' if I add it to the nav in keystone.js

### Steps to reproduce the actual/current behavior

Create the FileUpload model as described here:
http://keystonejs.netlify.com/guides/api-file-image-uploads

And in keystone.js
`keystone.set('nav', {uploads: 'FileUpload'}`

FileUpload is definitely registered as a Keystone list; the file upload UI is working in the admin panel, and I have assigned a Relationship on another model that references it, can select uploaded files from the associated model, etc. Keystone just throws an error when I try to set it in the nav. Not quite sure what's going on...

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.8
| Node             | 8.11.2

**Comment by hurricane987** [comment]
Nevermind. Not sure what changed, but it's working now.

**Comment by stennie** [comment]
@hurricane98 Glad you're enjoying Keystone! If you figure out what went astray, feel free to leave a comment here to help others who might encounter the same issue.

Regards,
Stennie
