### ISSUE TITLE
Cannot scroll in select dropowns on the create Item modal by mouse in the admin UI

### ISSUE THREAD

**Issue by Gladiolys** [keystonejs/keystone#4671]
# Bug report
Cannot scroll in in selects on the create Item modal by mouse

## Describe the bug
Cannot scroll in select dropowns on the create Item modal by mouse in the admin UI

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Create an item which has a select field with a lot of variants
2. Try and scroll in the select modal by mouse wheel

## Expected behaviour

Should be able to scroll

## Screenshots

Can't show mouse scroll on screenshots

## System information

- OS: all OS
- Browser all browsers

**Comment by mitchellhamilton** [comment]
Can't reproduce this, I'm guessing this was fixed at some point but can't find a PR that seems relevant, if you can still reproduce this, please open a new issue with a video of it broken and a specific browser and OS.
