### ISSUE TITLE
Yarn 2 Berry Keystone Admin-UI Uncaught Error: Cannot find module './public.js

### ISSUE THREAD

**Issue by savager** [keystonejs/keystone#4678]
# Bug report

When migrating (or using) Yarn 2 (Berry). The location admin-ui tries to load "public.js" is not accurate. 

## Describe the bug

Unsure, but I'm guessing it's loading a file relatively.

## To Reproduce

1. yarn create keystone-app my-app (choose starter app, mongo)
2. cd my-app
3. yarn install
4. yarn keystone build
5. yarn dev (runs as expected)

convert to yarn 2:
1. yarn set version berry
2. yarn install
3. yarn keystone build
4. verify yarn .cache directory is built.
5. rm-rf node_modules (now unnecessary)
6. some packages are not updated for yarn 2 yet so we have to add this to .yarnrc.yml

```packageExtensions:
  "@prisma/generator-helper@*":
    dependencies:
      debug: "^4.3.1"
  "@prisma/engine-core@*":
    dependencies:
      strip-ansi: "^6.0.0"
      debug: "^4.3.1"
  "@prisma/sdk@*":
    dependencies:
      debug: "^4.3.1"
  "@keystonejs/app-graphql@*":
    dependencies:
      express: "^4.17.1"
  "graphql-tag@*":
    dependencies:
      graphql: "^15.4.0"
```

7. yarn dev (completes successfully, but webpack configuration can't load ./public.js)

## Expected behaviour

Expect admin-ui to load normally without err.

## Screenshots

![image](https://user-images.githubusercontent.com/1455337/104863320-22464c00-58fb-11eb-8a77-34b1ac3cf131.png)

## System information

- OS: Mac 
- Browser: Chrome

## Additional context

This may be a feature request or a dumb mistake. It's my understanding that one doesn't have to link their node_modules but I could be misunderstanding. Thanks!

**Comment by savager** [comment]
I'm beginning to think it was very premature to think keystonejs would work with yarn 2. I'm also getting keystone build issues. I am going to switch back to yarn 1 for the moment.

**Comment by bladey** [comment]
Hi @savager, thanks for the report. As you determined, best to stick with Yarn 1 now and stay tuned for any updates.
