### ISSUE TITLE
Are CloudinaryImage & CloudinaryImages deprecated in 4.0.0?

### ISSUE THREAD

**Issue by kchou94** [keystonejs/keystone#4686]
Apologies if this is in the wrong location.  I felt like this question would be out of place on StackOverflow.

I've just started working with Keystone and have updated to 4.0.0-rc after initially making a project with [generator-keystone](https://github.com/keystonejs/generator-keystone).  I have been following the [documentation for 4.0.0](keystonejs.netlify.com) and have noticed that on the [`CloudinaryImage`](https://keystonejs.netlify.com/api/field/cloudinaryimage) and [`CloudinaryImages`](https://keystonejs.netlify.com/api/field/cloudinaryimages) Field pages, there's a notice stating:

> Warning: the CloudinaryImages Field has been deprecated. Please use the File and a storage adapter going forward.

However, in both the [upgrade guide](https://keystonejs.netlify.com/guides/v-0-3-to-v-4-0-upgrade-guide) and [file fields upgrade guide](https://github.com/keystonejs/keystone/wiki/File-Fields-Upgrade-Guide), it is stated that only the `AzureFile`, `LocalFile`, `LocalFiles`, and `S3File` types are being replaced by the `File` Field.

Is it safe to keep using `CloudinaryImage` and `CloudinaryImages` in my project?

**Comment by fabripeco** [comment]
I'm also interested in this topic: what is the better way to integrate image/s upload in keystone 4? Cloudinary filed is flagged as deprecated. Is there a 'stable' documentation about it or a suggested way to manage images in keystone? Is it in the roadmap? Thanks a lot!

**Comment by kchou94** [comment]
Thanks for the info!

**Comment by stennie** [comment]
@kchou94 Thanks for reporting! I've removed the incorrect deprecation warnings from the docs as well ;-).

Regards,
Stennie
