### ISSUE TITLE
Recommended approach for caching?

### ISSUE THREAD

**Issue by alsoicode** [keystonejs/keystone#469]
What is a recommended approach for high and low-level caching with Keystone? I've seen [express-view-cache](https://www.npmjs.org/package/express-view-cache) but I'm interested in what more experienced users have to say.

In Django I have access to high-level view and template fragment caching, and also low-level caching for querysets or just about any other hashable value.

What's the equivalent on the Express/Keystone/Node side?

**Comment by dcousens** [comment]
@JedWatson please clarify and close.

**Comment by larsha** [comment]
+1, also interested in caching of data in keystone app. Is there any cache build in or planning on integrating some sort of IMC? Or is it up to each developer to add some sort of cache if they find it necessary?

Keep up the good work, really enjoying working with KeystoneJS!

**Comment by morenoh149** [comment]
express-view-cache seems like a fine solution for caching views in redis, server-side.

with express you can set the [cache-control](http://blog.modulus.io/nodejs-and-express-static-content) header to tell the clients to cache content. I believe this is something outside the scope of keystone as there are many approaches.

here's an express middleware [cache](https://gist.github.com/kkamkou/4351835) that will store info in memory. You could do something similar with mongodb.

**Comment by larsha** [comment]
Thank you @morenoh149!
