### ISSUE TITLE
Security hole in Keystone app?

### ISSUE THREAD

**Issue by intrnet** [keystonejs/keystone#4694]
Is it normal when you can post any file, requesting from any domain, without authorization? Posted files are stored in /tmp folder on server. I tested Keystone app without any changes, fresh installs. You can try on your Keystone app http://jsfiddle.net/N4Jxk/1089/, just change your domain in form action.

What can I do to secure my Keystone app??

**Comment by ttsirkia** [comment]
Related to #4428

**Comment by stennie** [comment]
@intrnet Thanks for reporting! As noted by @ttsirkia, this is related to the `multer` integration and issues #3597 and #4428.

I'm not familiar with the history, but we are going to address this in Keystone 4.0.0-rc.2. I'm going to close as a duplicate of #4428.

Regards,
Stennie

**Comment by intrnet** [comment]
This is a good piece of news. So I can't wait new version, when it happens?
