### ISSUE TITLE
Insert multiple data at once

### ISSUE THREAD

**Issue by ShubhamOrbio** [keystonejs/keystone#4705]
### Expected behavior

Hi I am wondering if I can insert multiple data at once into mongodb collection using keystone js. can anyone help me with this please. i am a beginner in Node js

### Actual/Current behavior

No allowing multiple insert

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node.js          | 
| Browser          |

**Comment by ttsirkia** [comment]
At least `insertMany` from Mongoose is available.

**Comment by stennie** [comment]
@ShubhamOrbio As @ttsirkia mentioned you can use the [`insertMany()` method](http://mongoosejs.com/docs/4.x/docs/api.html#model_Model.insertMany) in the underlying Mongoose API to insert an array of documents.

The Keystone GitHub issue queue is for bug reports or feature suggestions. For development questions please ask on [StackOverflow](https://stackoverflow.com/tags/keystonejs) with the `keystonejs` tag. I'd suggest including details of your environment (Keystone and Node.js versions), a snippet of code that you are trying to use, and any error messages you are encountering.

Regards,
Stennie
