### ISSUE TITLE
Restrict access to keystone admin by domain

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#471]
We've got a use-case where a keystone app is running on multiple domains, but we only want `/keystone/` to be accessible through one of them.

To fix this, we could add the ability to restrict access to the `/keystone/` routes based on `req.headers.host`.

**Comment by milosdakic** [comment]
I'll probably do this one in the next day or so.

Which solution do you guys prefer:
- https://github.com/bmullan91/express-subdomain
- http://www.senchalabs.org/connect/vhost.html

Would be cool not only to restrict the admin to a particular domain, but have it load up only on a subdomain. eg. http://keystone.mysite.com/ will only load the admin UI.

**Comment by grabbou** [comment]
Been using express-subdomain in my previous project, but I am not sure if we need another dependency to implement that feature. Should be pretty easy. As long as Keystone do not have (not sure, maybe it's been already done) real multi-tenancy (create and manage multiple sites) that's not needed.

**Comment by webteckie** [comment]
https://github.com/expressjs/vhost looks pretty handy.  Not sure if it is applicable here.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/restrict-access-to-keystone-admin-by-domain
