### ISSUE TITLE
Cannot delete s3 files

### ISSUE THREAD

**Issue by kumo** [keystonejs/keystone#472]
I created a project using yo and modified the Post model replacing the CloudinaryImage type with S3File. I can upload files to S3 and access them but I am unable to delete them. Should I have done something else?

**Comment by morenoh149** [comment]
can anyone confirm if this is still the case on 0.3.0?

**Comment by kumo** [comment]
@morenoh149 what is the easiest way of checking with 0.3.0?

**Comment by morenoh149** [comment]
take an existing keystone project. change the package.json dependency to something like `"keystone": "git://github.com/keystonejs/keystone.git#master"` try to upload an s3file and share a screenshot if it doesn't work.

**Comment by kumo** [comment]
I can confirm that it still doesn't work and also if I replace a file the old one remains. There are no errors, but the files remain in the S3 Management Console.

Additionally, I was only able to upload a file to an S3 bucket in the standard US region but that seems related to #532

**Comment by morenoh149** [comment]
solved by https://github.com/keystonejs/keystone/pull/1064
