### ISSUE TITLE
Add branded 404 page with some useful starting points

### ISSUE THREAD

**Issue by stennie** [keystonejs/keystone#4736]
The current 404 page is generic, eg: https://keystonejs.com/404

**Comment by gautamsi** [comment]
What about creating snippet registry? I transformed SydJs site into my own fresh boilerplate, this may help create a template with generator. I will give this a spin, probably this week end

**Comment by stennie** [comment]
@gautamsi This issue is to add styling and some starting points to the 404 (not found) page in the Keystone documentation. Users finding the 404 page will be coming from an outdated or incorrect link.

It sounds like you are suggesting "snippet registry" as new content for the documentation? If so, that should be a separate issue.

Regards,
Stennie
