### ISSUE TITLE
keystone/CONTRIBUTING.md is outdated with respect to documentation repository

### ISSUE THREAD

**Issue by eduard-malakhov** [keystonejs/keystone#4750]
### Expected behavior
Contributing guidelines (keystone/CONTRIBUTING.md) must refer to keystonejs/keystone repository as the place to submit documentation changes to.

### Actual/Current behavior
A quote from keystone/CONTRIBUTING.md: "All new features and changes need documentation. They live over at the Keystone-site repo."

**Comment by stennie** [comment]
Thanks for reporting @eduard-malakhov. There's a significant PR in the works for #4653.

For documentation changes in the interim you should be able to click on the "Edit this page" link in the live docs (https://keystonejs.com) to find the relevant source page.

Regards,
Stennie
