### ISSUE TITLE
own method function

### ISSUE THREAD

**Issue by eloyElogio** [keystonejs/keystone#4761]
To create a user or an instance user of role model with private/own posts what method could I use  in order to that?

**Comment by SheaBelsky** [comment]
Do you mean you want a method on the user that returns all posts they've made? I'm not sure what your database structure looks like, but I'm guessing it would look something like this:

```
User.schema.methods.getMyPosts = function(cb) {
    keystone.list("Post").model.find({user: this}).exec(cb);
};
```

This is assuming your `Post` model has a property `user` that is of type `Relationship` to a `User`. If that's the case, you can copy and paste the above function as-is. If not, you'll need to modify it based on however your database structure actually looks.
