### ISSUE TITLE
_req_user not available when running migrations

### ISSUE THREAD

**Issue by perenstrom** [keystonejs/keystone#4768]
### Expected behavior
When running `save` commands on a model during a migration script (as in the example under _Creating items_ on https://keystonejs.com/documentation/database), the revision document for the saved item should contain a user tag.

### Actual/Current behavior
It appears that `_req_user` is not sent to the `history` pre-save hook, since it's not part of a request? This causes the admin interface to crash when trying to parse the name of the user for the revision, since `u` doesn't exist in the revision document.

### Steps to reproduce the actual/current behavior
Create a keystone model with history enabled. In a migration script, save a document to this model. Try to access the document in the admin interface.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.8
| Node.js          | 6.14.3

**Comment by perenstrom** [comment]
It appears the admin interface crashes because of a forked change in our repository. So the crash is not an issue with current master, but instead of changes in https://github.com/keystonejs/keystone/pull/4398.

**Comment by perenstrom** [comment]
A possible solution would be to add a guard around the printing of the user information in that dropdown. (Commenting here to remember it).

**Comment by stennie** [comment]
@perenstrom Thanks for following up on the source of the issue. Since this is specific to changes on a fork, appropriate fixes should be made there as well. The application update framework is unaware of downstream changes/usage.

Regards,
Stennie
