### ISSUE TITLE
Circle dependencies error within keystone.import

### ISSUE THREAD

**Issue by GalochkinKirov** [keystonejs/keystone#4770]
### Expected behavior
`keystone.import('models')`

Imports the models as expected.

### Actual/Current behavior
There is circle dependencies issue if A models has required B module within itself.

### Steps to reproduce the actual/current behavior
1. Create **models/A.js**
2. Create **models/B.js**
3. Create **models/C.js**
4. Import them, keystone.import('models').
5. A.js: console.log(require('./B'))
6. B.js: console.log(require('./A))

### Environment
Keystone = 4.0.0-beta.5 
Node.js= v10.7.0 
Browser = Chrome  67

**Comment by stennie** [comment]
Keystone models should not directly require other models, so your approach is not expected to work.

If you want to express a relationship between models you should instead look into defining [Relationships](https://keystonejs.netlify.com/documentation/database/relationships/).

Regards,
Stennie
