### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by hmoradian** [keystonejs/keystone#4772]
Hi, Thanks very much for this powerful CMS,
If you want your project really up to date, Please update this project with Bootstrap 4 (this time: v4.1.3)
tnx

**Comment by stennie** [comment]
@hmoradian Keystone 4 uses [Elemental UI](http://elemental-ui.com/) for the admin interface. For some of the motivation behind this change, please see issue #2331.

You can use any preferred framework (including Bootstrap) for an application front-end which posts data to Keystone as a backend.

Regards,
Stennie
