### ISSUE TITLE
project created by yo keystone uses v4.0.0-beat5, which is too old.

### ISSUE THREAD

**Issue by zbobyuan** [keystonejs/keystone#4779]
need to update yo keystone to generate codes using keystone v4.0.0 release.

**Comment by stennie** [comment]
@zbobyuan `keystone-generator` does need an update and release but note that it is a [separate GitHub project](https://github.com/keystonejs/generator-keystone/issues) from Keystone core. There is already a PR for updating to Keystone 4, but until an updated package is released you can also just bump the keystone version in the `package.json` for a generated project.

Regards,
Stennie
