### ISSUE TITLE
Dynamic Field Notes

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#4787]
### Expected behavior
If a static text is provided for note, it gets displayed.
If a function is provided for "note" of a Field, the UI should display the output of the function.

### Current Behaviour
Currently nothing is displayed, if a function is provided

### Usage
This can be used to provide Dynamic Suggestions based on either value of current field or value of other fields

### Example
https://github.com/mailcheck/mailcheck

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0

**Comment by stennie** [comment]
@VinayaSathyanarayana The current [Keystone 4 Field API](https://keystonejs.netlify.com/api/field/options/) expects the `note` field option to be a String.

Can you elaborate on your use case for dynamic notes and any expected context/parameters for a function?

Thanks,
Stennie

**Comment by VinayaSathyanarayana** [comment]
Use Case: Provide Suggestions to the end user on what to input in the field.
Example 1: Suggest Corrections to the entered email id
![image](https://user-images.githubusercontent.com/16976677/44981085-376eea00-af8f-11e8-84cc-f98eda2356e3.png)
Ref: https://github.com/mailcheck/mailcheck

The function can be similar to the function that is used for "default". 
The function should return a String - that is displayed on the screen

**Comment by VinayaSathyanarayana** [comment]
Can this be considered for Keystone-5?

**Comment by JedWatson** [comment]
@VinayaSathyanarayana yes, I think this is a good candidate for v5 ✅ 

Would be hard to implement in 4 because the function needs to be client-side, but the `note` is specified server side and we don't have a build process that's capable of splitting code between server-side and client-side in 4 (that's one of the big new additions in 5)
