### ISSUE TITLE
Pre-save hook not populated with saving data object

### ISSUE THREAD

**Issue by PankajGadia** [keystonejs/keystone#4789]
I am new to Keystone Js. Currently i am using 4.0 version of keystone.
I need to add few checks inside before hook, before saving any user.
I tried 2 ways, none helped me getting the details of the user object. 

//case1: 'this' pointer is empty
User.schema.pre('save', (next) => {
    const member = this
    console.log(member)
// prints empty object
    next()
})
//case2: tried with data as parameter
User.schema.pre('save', (data,next) => {
    console.log(data)
// here data is a function (cant decide what it does)
    next()
})

Intrestingly, next is working fine in both cases.
I might be missing something  basic. Kindly help.:)

**Comment by laurenskling** [comment]
You are using arrow functions. Using an arrow function changes the value of `this`. Read into it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

You should be using a plain old function to let `this` actually be the model.

```
User.schema.pre('save', function preSave(next) {
const member = this
console.log(member)
// prints empty object
next()
})
```

**Comment by autoboxer** [comment]
@laurenskling is correct, I'm closing this issue.  If making the changes described doesn't fix the issue, please note it here and reference me in your comment.
