### ISSUE TITLE
Add the ability to set mount path when calling pre-routes middleware

### ISSUE THREAD

**Issue by ronaldcurtis** [keystonejs/keystone#479]
Hey there, there is currently no way to pass in an optional [mount path](http://expressjs.com/api.html#app.use) to keystone.pre('routes', someMiddleware). My use-case is to use [connect-mincer middleware](https://github.com/clarkdave/connect-mincer) as an asset pipeline.

**Comment by mikegleasonjr** [comment]
(Y)

**Comment by creynders** [comment]
I think using keystone.app definitely suffices
