### ISSUE TITLE
Public board to post KeystoneJS related tasks to find freelancer

### ISSUE THREAD

**Issue by e-stonia** [keystonejs/keystone#4792]
I need some tasks regularly to be done in KeystoneJs but I can't find really a good board to post my requirements to find freelancer to do the task for me. My Skype: kasparpalgi

**Comment by stennie** [comment]
@e-stonia There isn't a dedicated job board for Keystone, but any freelancer sites with Node & Express jobs should be relevant. If you do post more details somewhere, tweet [@keystonejs](https://twitter.com/keystonejs) for visibility.

There's also a #gigs channel in the [KeystoneJS Slack](http://community.keystonejs.com), but that is very low traffic at the moment.

Regards,
Stennie
