### ISSUE TITLE
Wysiwig editor is incorrectly transforming URLs

### ISSUE THREAD

**Issue by bishopZ** [keystonejs/keystone#4803]
### Expected behavior

When inserting an Link into the Wysiwig editor, I expect the link I inserted to be the one that appears in the content.

### Actual/Current behavior

I insert a Link into the Wysiwig editor. When I save the article and view what was saved, the URL has been transformed to an incorrect path.

For instance when inserting
`http://domain.com/blog/2018/02/28/chicken-sandwhich`
The URL that is saved is
`../blog/2018/02/28/chicken-sandwhich`
which is not correct. 

Since this link is accessed from a blog page, the resulting link goes to 
`http://domain.com/blog/2018/01/21/../blog/2018/02/28/chicken-sandwhich`

### Steps to reproduce the actual/current behavior

We experience the same behavior when we insert the link through the Wysiwig editor menu, or manually insert the link into the Wysiwig HTML view.

We get the same result with all of the following URL values:
+ `http://domain.com/blog/2018/02/28/chicken-sandwhich`
+ `/blog/2018/02/28/chicken-sandwhich`
+ `../../../blog/2018/02/28/chicken-sandwhich`

### Environment

Our route

`app.get('/blog/:year/:month/:day/:post', routes.views.post);`

Then the view is looking for the `post` param which is not there if the URL has the incorrect format.

`view.on('init', function (next) {
    var q = Post.model.findOne({
      state: 'Published',
      slug: req.params.post
    })`

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0
| Node.js          | 6.11.1
| Browser          | All

**Comment by kraigh** [comment]
We experienced this same issue and were able to fix it by adjusting the TinyMCE plugin settings. You can do so in your keystone.js (inside keystone.init) file like this:

`    'wysiwyg additional options': {
        paste_as_text: true,
        forced_root_block : "",
        force_br_newlines : true,
        force_p_newlines : true,
        relative_urls : false,
        convert_urls: false
    }`

The last two lines there are what's relevant, but the other options we found useful as well, especially when working with non-technical content editors who would copy/paste from word or other sources.

For details on the URL related settings, look here: [https://www.tiny.cloud/docs/configure/url-handling/](https://www.tiny.cloud/docs/configure/url-handling/)

Looking over them now, it looks like you could also set the `document_base_url` if you wanted to continue using relative URLs, and maybe Keystone should do so by default?

**Comment by bishopZ** [comment]
Yes! This works great. Thank you so much.

The only other solution we thought of was to use bit.ly for all internal links, which would have been a major pain point. Thank you again.
