### ISSUE TITLE
Keystone init config doc link broken in autogenerated project

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#4818]
I used `yo keystone` to generate a skeleton project and included extra comments. The link to the `keystone.init` options is listed as `http://keystonejs.com/guide/config`, whereas the actual docs seem to be at `https://keystonejs.com/documentation/configuration`.

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0
| Node.js          | 10.11.0

**Comment by stennie** [comment]
@Vultraz Thanks for reporting! I added a redirect to the Keystone v4 docs equivalent, but the generator also needs a refresh.

Regards,
Stennie
