### ISSUE TITLE
Can't set a custom ID value when inserting new item in List via GraphQL mutation query

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#4824]
# Bug report

## Describe the bug

Can't set a custom ID value when inserting new item in List via GraphQL mutation query:
```graphql
mutation {
  createCountry(data: {
    id: "RU"
    name: "Russia"
  }) {
    id, name
  }
}
```
 - got the error as result:
```
GraphQLError: Field \"id\" is not defined by type \"CountryCreateInput\".
    at ObjectField (keystone/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:73:29)
    at Object.enter (keystone/node_modules/graphql/language/visitor.js:323:29)
    at Object.enter (keystone/node_modules/graphql/utilities/TypeInfo.js:370:25)
    at visit (keystone/node_modules/graphql/language/visitor.js:243:26)
    at Object.validate (keystone/node_modules/graphql/validation/validate.js:69:24)
    at validate (keystone/node_modules/apollo-server-core/dist/requestPipeline.js:221:34)
    at Object.<anonymous> (keystone/node_modules/apollo-server-core/dist/requestPipeline.js:118:42)
    at Generator.next (<anonymous>)
    at fulfilled (keystone/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I use the MongoDB database with MongooseAdapter, which have no problems with custom id values, here is raw query that do this thing:
```
> db.countries.insert({_id:"RU", "Name" : "Russia"})
WriteResult({ "nInserted" : 1 })
```

## To Reproduce

1. Create a simple List, for example "Country":
```js
keystone.createList('Country', {
  fields: {
    id: { type: Text },
    name: { type: Text },
  },
});
```
2. Try to insert new city via GraphQL mutation query:
```graphql
mutation {
  createCountry(data: {
    id: "RU"
    name: "Russia"
  }) {
    id, name
  }
}
```
3. See the error

## Expected behaviour

This mutation query must create the new item with sent id value.

**Comment by MurzNN** [comment]
Same problem is with knex (PostgreSQL) database adapter.

**Comment by MurzNN** [comment]
Seems the source of this problem is that Keystone not add the custom `id` field into Schema of input:
```
input CountryCreateInput {
  name: String
}
```

**Comment by MurzNN** [comment]
I fixed this problem via PR https://github.com/keystonejs/keystone/pull/4826

**Comment by MurzNN** [comment]
Want to add that this is a very valuable feature for several our projects, so we need to use fork of Keystone with this feature implemented. And will be very glad to see the PR accepted.

**Comment by molomby** [comment]
Update: Arbitrary `id` values are now supported (#8648) but still no easy way to set them from outside a hook, eg. via GraphQL. I suppose you could hack around it using a second field if you really needed to, like this:

```ts
lists: Lists = {
  Task: list({
    access: allowAll,
    fields: {
      externallySetId: text({ validation: { isRequired: true } }),
      name: text({ validation: { isRequired: true } }),
    },
    hooks: {
      resolveInput: async ({ listKey, operation, resolvedData }) => {
        if (operation !== 'create') return resolvedData;
        return { ...resolvedData, id: resolvedData.externallySetId };
      },
    },
  }),
});
```

Which would then let you...

```graphql
mutation {
  createTask(data: {
    externallySetId: "AU"
    name: "Australia"
  }) { id name }
}
```

Which should return `{ "id": "AU", "name": "Australia" }`.

It's a little clunky but primarily the point of #8648 is to allow other ID formats, not solve for the issue raised here.

**Comment by gautamsi** [comment]
You can also use id from header value if you are not using keystone admin-ui.
