### ISSUE TITLE
How to add External Link in Admin Panel

### ISSUE THREAD

**Issue by mahayash** [keystonejs/keystone#4837]
`keystone.set('nav', {
	WriteArticle: 'Articles',
	Analytics: [
		{
			label: 'Analytics',
			key: 'Analytics',
			path:
				'https://analytics.google.com/',
		},
	],
});
`
This is the code for adding the external link, but on click doesn't seems to work. Please let me what is the issue into it

**Comment by agent3bood** [comment]
This issue was fixes 2a80fe048504ba7893226246a05cb3bc87054ab1
please update to the latest version of keystone "keystone": "4.0.0"
