### ISSUE TITLE
Wysiwyg in Boilerplate inconsistent with documentation

### ISSUE THREAD

**Issue by culturetogo** [keystonejs/keystone#4848]
# Bug report

## Describe the bug

If you create a boilerplate installation with starter content, the field type Wysiwyg is being imported
index.js:
`
const { Text, Checkbox, Wysiwyg, Password, Relationship } = require('@keystonejs/fields');
`

If you want to use the field type Wysiwyg in a list and you follow the [documentation](https://www.keystonejs.com/keystonejs/fields-wysiwyg-tinymce/)  that says you have to install it via npm i and then import it

`const { Wysiwyg } = require('@keystonejs/fields-wysiwyg-tinymce');
`

an error is thrown (Wysiwyg declared twice). So you first have to remove Wysiwyg from the list of fieldtypes imported form @keystone/fields. No big deal but confusing, especially for unexperienced useres (like me).

## Expected behaviour

Remove Wysiwyg form index.js:

`const { Text, Checkbox, Wysiwyg, Password, Relationship } = require('@keystonejs/fields');`

**Comment by timleslie** [comment]
I wasn't able to find the code `const { Text, Checkbox, Wysiwyg, Password, Relationship } = require('@keystonejs/fields');` anywhere in the repo 🤔 

Please reopen this issue with a specific file path and we'll try to get this fixed 👍
