### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by BigGiantHead** [keystonejs/keystone#4862]
# Bug report

## Describe the bug

I just upgraded my keystonejs modules and LocalFileAdapter doesn't work any more. I turned on full logging and when I try to upload a file I get this error

{
   "level":50,
   "time":1613502721023,
   "pid":8001,
   "hostname":"Ivans-MacBook-Pro.local",
   "name":"graphql",
   "message":"Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).",
   "extensions":{
      "code":"INTERNAL_SERVER_ERROR"
   },
   "uid":"ckl8duzga000069p80k667r5d",
   "name":"BadRequestError",
   "stack":"<Original stack missing>\n    module.exports (node_modules/ensure-error/index.js:43:12)\n    formatError (node_modules/@keystonejs/keystone/lib/Keystone/format-error.js:103:44)\n    node_modules/apollo-server-errors/dist/index.js:168:34\n    Array.map (<anonymous>)\n    Object.formatApolloErrors (node_modules/apollo-server-errors/dist/index.js:166:27)\n    node_modules/apollo-server-express/dist/ApolloServer.js:48:39\n"
}

## To Reproduce

Upgrade your keystone modules to the latest and use a LocalFileAdapter to upload files.

## Expected behaviour

It is supposed to upload files in a specified folder, it simply doesn't work.

## System information

- OS: MacOS
- Browser (if applies) Chrome

**Comment by timleslie** [comment]
HI @BigGiantHead, thanks for the repo. I tried to reproduce this problem and was unable to. I was able to successfully upload files using the latest `LocalFileAdapter` code.

You might want to try completely removing the `node_modules` directory and doing a fresh install to make sure you have all the correct and up to date dependencies.

If you're still having problems, please re-open this issue and include details of the package versions you're using, and also the schema configuration you're using to setup the File field. Good luck!
