### ISSUE TITLE
How to construct raw mongoose queries in keystone5?

### ISSUE THREAD

**Issue by IlchukPasha** [keystonejs/keystone#4870]
## Question about Keystone
I know that you recommend to use keystone.executeQuery to query database, also i saw that issue https://github.com/keystonejs/keystone/issues/1589.
But for a specific reasons on my project i need to use raw mongoose queries.

I saw some examples that used Listname.adapter.find
```
await Availability.adapter.find([
  {....}
]);
```
but i was not able to call aggregate from adapter.

After some research i`ve discovered that i can use adapter.model.aggregate.
For example:
```
await Availability.adapter.model.aggregate([
  {....}
]);
```

Is it a good option to use `adapter.model` to write raw mongoose queries?
and
will you continue to support this option in future?

**Comment by timleslie** [comment]
Hi @IlchukPasha, this is indeed the best way to write mongoose queries against a specific model. This API will not be going away in keystone-5.
