### ISSUE TITLE
keystone with angular 4

### ISSUE THREAD

**Issue by sadhnaprajapati** [keystonejs/keystone#4870]
i want to setup keystone with angular 4 .but  i am not able to find any solution related to that.please help me to setup it.

**Comment by aleygues** [comment]
Hi,

If you are asking about using Angular 4 in the Admin UI: I **don't** recommend it. KeystoneJS is a CMS using ReactJS for the Admin UI, switching to Angular 4 would mean to redevelop almost everything. If you are interested in customizing the Admin UI, the best way is to use ReactJS.

Now if you are asking about developing the client part of your website (front), I think you need a little bit more knowledge about How a website works, especially:
* What's the difference between the back (server) and the front in a Website?
* How Angular works?
* What is an API? What is a REST API? What are CRUD methods? 
* How to develop a website using Angular and a REST API?

Hint: using KeystoneJS, KeystoneJS will be your REST API, you gonna make calls from your Angular Front Website to the API on the server side. In KeystoneJS, you have to develop your own API. Please note that in this case, you will develop **2 applications**, 1 would be your server using KeystoneJS, used to manage data and serve data, the 2nd will be a static website using Angular 4 (so HTML5, SCSS and TS, or HTML, CSS and JS), used to consume data from the server and display them to your end users.

Links to help:
* https://www.pluralsight.com/blog/film-games/whats-difference-front-end-back-end
* https://rubygarage.org/blog/best-javascript-frameworks-for-front-end
* https://en.wikipedia.org/wiki/Web_API
* https://www.bmc.com/blogs/rest-vs-crud-whats-the-difference/
* https://malcoded.com/posts/angular-backend-express

Aurélien.

**Comment by JedWatson** [comment]
Thanks for answering this @aleygues, I hope that helps you @sadhnaprajapati
