### ISSUE TITLE
Sign in using google auth in Admin UI

### ISSUE THREAD

**Issue by bayucakra20** [keystonejs/keystone#4884]
I want to add google auth while sign in to Admin UI, but I cannot find any documentation about it on keystone docs, so is it possible if I implement this on keystone Admin UI?
 
### Expected behavior

Social sign in using google auth in admin ui

### Actual/Current behavior

Sign in using email & password

### Steps to reproduce the actual/current behavior

There is library https://github.com/JohnnyEstilles/keystone-social-login, but it's not compatible yet with latest version of KeystoneJS

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 0.4
| Node.js          | 11.3.0
| Browser          | Google Chrome

**Comment by gautamsi** [comment]
well, best example is https://github.com/JedWatson/sydjs-site, once you enable google login, make sure you have a way to mark that user as admin ( set `isAdmin` field to true in sydjs). you can also create a new user with admin access and have them login and connect google/github/facebook/twitter etc.  
Login using `/signin` page (any provider) then you can access `/keystone` page.

**Comment by bayucakra20** [comment]
thankyou @gautamsi for the response, I just succesfully implement admin login using google auth, because I cannot change the current admin login page, I create a one with a new route, for now it's only work with google login, but I'm consider to replace default login page with email & password login too, I'm  using library called passport and for authenticate to admin, keystone already provide method to authenticate to admin ui, it's on `keystone/lib/session.js`, first of all thanks @gautamsi
