### ISSUE TITLE
Cannot set up the index in the schema

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#4904]
I found that the fields setting for model does not have the ```index``` option to set up the database index but the isUnique etc will create the index automatically.

Is there any way to set up the index? e.g.

```
exports.Sponsor = {
  access: DEFAULT_LIST_ACCESS,
  fields: {
    name: { type: Text, index: true },
    website: { type: Text },
  },
};

```

**Comment by gautamsi** [comment]
right config is `isIndexed`
