### ISSUE TITLE
Money/ Number fields remain unformatted on render

### ISSUE THREAD

**Issue by realThinhIT** [keystonejs/keystone#4911]
I'm currently experiencing bugs about field types: Money or Number. 
Numeral wouldn't format money or number fields.
 
### Expected behavior
It should have been formatted on page load. It works fine on the KeystoneJS demo.

### Actual/Current behavior
- It remained unformatted/ plain number as in the database on listing table page or in edit/ create page (the text input).

![Imgur](https://i.imgur.com/nUkvfLX.jpg)

![Imgur](https://i.imgur.com/Q779uLh.jpg)

### Steps to reproduce the actual/current behavior
1.  Using `type: Types.Money` or `type: Types.Number` on a Number field.

### Environment
| Software         | Version
| ---------------- | -------
| Keystone         | ^4.0.0
| Node.js          | v10.1.0
| Browser          | Chrome 73.0/ Safari 12.0

**Comment by realThinhIT** [comment]
Issue found, please check my pull request: https://github.com/keystonejs/keystone/pull/4912

**Comment by JedWatson** [comment]
Merged the pull request, thanks!
