### ISSUE TITLE
Download uploaded files from admin UI

### ISSUE THREAD

**Issue by vladislav-vasilyev** [keystonejs/keystone#4917]
Hi everybody. How can I download uploaded files from keystone admin UI? I see the only filename with extension string in the list item field but I couldn't download it (this field has the File type). Is it possible to add button/clickable link to download it?

**Comment by autoboxer** [comment]
The file name should be a link to the file.  Clicking on it will either open it or download it depending on the file type and your browser settings.  If that doesn't work, you may want to hover over the file name to see if the link is pointing to the correct location where your file is stored.

**Comment by vladislav-vasilyev** [comment]
@autoboxer How can I do it? Now I have this configuration for the file field:
`var Types = keystone.Field.Types;`

`var storage = new keystone.Storage({`
`	adapter: keystone.Storage.Adapters.FS,`
`	fs: {`
`		path: 'uploads',`
`	},`
`});`

`Enquiry.add({`
`...`
`attachedFile: {`
`		type: Types.File,`
`		storage: storage,`
`		initial: true,`
`	},`
`...`
`});`
`...`

**Comment by abhijithvijayan** [comment]
use cloudinary service for photo uploading

**Comment by vladislav-vasilyev** [comment]
@abhijithvijayan But what if I need to upload .doc, .docx, .pdf, .ppt, .pptx files?

**Comment by abhijithvijayan** [comment]
@vladislav-vasilyev Take a look at this issue

https://github.com/keystonejs/keystone/issues/4070

**Comment by vladislav-vasilyev** [comment]
I updated keystone to 4.0.0 version from 4.0.0-beta.5 and now it works as expected

**Comment by NeoTheSecond** [comment]
<img width="414" alt="Screen Shot 2019-09-19 at 11 21 37 AM" src="https://user-images.githubusercontent.com/32930943/65213258-b5852c80-dacf-11e9-80a4-75bf2381a70e.png">
I'm on keystone 4.2.1 and i still have this problem, i cannot download the file from admin ui

**Comment by kochomati** [comment]
> <img alt="Screen Shot 2019-09-19 at 11 21 37 AM" width="414" src="https://user-images.githubusercontent.com/32930943/65213258-b5852c80-dacf-11e9-80a4-75bf2381a70e.png">
> 
> I'm on keystone 4.2.1 and i still have this problem, i cannot download the file from admin ui

HI @NeoTheSecond - did you manage to solve this? Also needing to allow admins to download files.
