### ISSUE TITLE
doesn't work with custom table name in prisma

### ISSUE THREAD

**Issue by krunaldodiya** [keystonejs/keystone#4929]
hi there,

I have just starting exploring this but i am not sure how to integrate with existing postgresql database with prisma

```
model User {
  id String @id @default(uuid())

  name String
  email   String
  mobile     String

  created_at DateTime @default(now())
  updated_at DateTime @default(now()) @updatedAt

  @@map("users")
}
```

After adding database connection uri into keystone js, I ran yarn dev it is showing that it's running on http://localhost:3000 but
it is showing me this error Invalid `prisma.user.aggregate()` invocation: The table `public.User` does not exist in the current database.

**Comment by timleslie** [comment]
Hi @krunaldodiya,

At the moment we don't support customising the table name used by the prisma adapter. You will need to change the name in your existing database if you want to use the prisma adapter with it.

This is something that we may revisit in the future, but adding support for this feature is not currently on our roadmap.
