### ISSUE TITLE
only admin can add new users

### ISSUE THREAD

**Issue by aniaska4** [keystonejs/keystone#4933]
If the user is "this.isAdmin" I would like to show the "User" List in Admin UI,
If not, the "User" list should not be shown.
==> Only the Admin should have access to User List

How should one implement that?

**Comment by gautamsi** [comment]
This version of KeystoneJS is not designed to handle this. Based on `user.isAdmin` you can prevent anyone to connect to Admin UI, but you can not selectively hide list(s) or field(s) in the Admin Ui. 

[next version ](https://github.com/keystonejs/keystone-5/) has this features, next version is still in alpha and not stable for production use yet.
