### ISSUE TITLE
Multi-tenancy in Keystone JS

### ISSUE THREAD

**Issue by jelordreygulle** [keystonejs/keystone#4936]
How can KeystoneJS be used to implement multi-tenancy? Is it possible at all?

Example use case: A company is creating a new blog platform using KeystoneJS and it wants to allow for multiple blog sites using the same models from one KeystoneJS instance but each blogger should only be able to control their own site.  Or any idea or suggestion
Possible Option

-Docker

**Comment by Rajivkumar1234** [comment]
@laurenskling  do you have suggestion or idea about this one ?

**Comment by nandumoura** [comment]
I have the same question Did you manage to find a solution or even another cms that meets this type of demand?
