### ISSUE TITLE
Cloudinary image upload not working

### ISSUE THREAD

**Issue by HelgaSokolova** [keystonejs/keystone#4939]
Hello

I'm using the latest version of Keystone - v4.1.1 and I'm not able to find any documentation for uploading Cloudinary image through api.
I just use multipart form data to upload image file but it doesn't work without returning any error.
It just ends with timeout error.

It would be great if I get any sample code.

**Comment by autoboxer** [comment]
@HelgaSokolova, could you please post some code, or give more details about what you're doing that's leading to this issue?

**Comment by HelgaSokolova** [comment]
Oh, I've figured out the reason already, I was trying to upload the file larger than 10MB that is limit size of standard Cloudinary account.
