### ISSUE TITLE
yarn create package doesn't install keystone bin

### ISSUE THREAD

**Issue by treshugart** [keystonejs/keystone#4951]
Hey, got a day off and wanted to give v5 a go. I'm following the [intro](https://v5.keystonejs.com/quick-start/) and the `yarn create` script works fine but when I run `yarn start` it fails.

Changing this call to point to `./node_modules/@keystone-alpha/keystone/bin/cli.js` works. I see that `@keystone-alpha/keystone` has a `bin` defined, and on further investigation it seems that `yarn` simply isn't linking this script. I've tried adding `--force` (suggested [here](https://stackoverflow.com/questions/40003932/why-doesnt-yarn-install-all-executables-in-bin-folder)) and it still doesn't work. Using `npm` instead of `yarn` *does* work.

I'm not sure if there's much you can do on this end, but updating the intro to note this as an issue (if you can reproduce it) might be good?

Thanks!

**Comment by laurenskling** [comment]
Hey @treshugart , please move your question to https://github.com/keystonejs/keystone-5
thanks.
