### ISSUE TITLE
puting an img to to the post text

### ISSUE THREAD

**Issue by aniaska4** [keystonejs/keystone#4954]
I want to add images to a post text, but  wysiwyg in Content Extended doesn't have this option. I add image: { type: Types.CloudinaryImage }, in my models, but I want to have another option to add pictures only in the post text. It is possible? Or keystoneJS doesn't handdle this option?

**Comment by laurenskling** [comment]
`'wysiwyg cloudinary images': true` in your `init` should do the trick, is it not documented?

**Comment by aniaska4** [comment]
Great, it is working! Thank you :)
