### ISSUE TITLE
Don't intercept keyboard input for `contenteditable` nodes

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#499]
On this line: https://github.com/keystonejs/keystone-5/pull/495/files#diff-ba3092b23c94bf7f790f398d91c6dba2R47

**Comment by MadeByMike** [comment]
Closing due to 'nevermind' comment in Jess's link

**Comment by jesstelford** [comment]
The `nevermind` comment was referring to moving the code around. It's still an issue I discovered.

**Comment by MadeByMike** [comment]
My mistake sorry!
