### ISSUE TITLE
Prisma adapter fails with create query on relationship field to List item with non-number id

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#5001]
# Bug report

## Describe the bug

Prisma adapter fails with create query on relationship field to List item with non-number id

## To Reproduce

1. Modify the `examples-next/todo` demo via changing id field type of "Todo" list to text and commenting the `trackingFields` (to remove unnecessary fields):
```js
  Todo: list({
    ui: {
      listView: {
        initialColumns: ['label', 'isComplete', 'createdAt', 'createdBy', 'updatedAt', 'updatedBy'],
      },
    },
    fields: {
      label: text({ isRequired: true }),
      isComplete: checkbox(),
      assignedTo: relationship({ ref: 'User.tasks' }),
      finishBy: timestamp(),
    },
    idField: text({
      isUnique: true,
      isIndexed: true,
      access: {
        create: true,
      },
      ui: {
        createView: { fieldMode: 'edit' },
        itemView: { fieldMode: 'read' },
      },
    }),
  }),
```
2. Create new Todo item via Admin UI (with patch from #4826, or directly via code without patch) with id `task_23` - it will be created well.
3. Try to create new user "Alice" without relationship to task - created successfully.
4. Try to create new user "Bob" and select the relationship to some task - you will got the error:
```
 Invalid `prisma.user.create()` invocation: { data: { name: 'Bob', tasks: { connect: [ { id: NaN ~~~ } ] } }, include: { tasks: { select: { id: true } } } } Argument id: Got invalid value NaN on prisma.createOneUser. Provided Float, expected String. 
```

Here is GraphQL query that sent to server:
```graphql
mutation ($data: UserCreateInput!) {
  item: createUser(data: $data) {
    id
    label: name
    __typename
  }
}
```
and query:
```json
{
    "data": {
        "name": "Bob",
        "tasks": {
            "connect": [
                {
                    "id": "task_23"
                }
            ]
        }
    }
}
```

## Expected behaviour

The User item must be created with linked Todo item without errors. With `knex` and `mongoose` adapters this works well.

Seems the problem is in this part of code: https://github.com/keystonejs/keystone/blob/f029a3bd6f54deb7b336427fa33e8bb237e3b5eb/packages/adapter-prisma/lib/adapter-prisma.js#L320
```js
  async _create(_data) {
    return this.model.create({
      data: mapKeys(_data, (value, path) =>
        this.fieldAdaptersByPath[path] && this.fieldAdaptersByPath[path].isRelationship
          ? {
              connect: Array.isArray(value)
*                ? value.map(x => ({ id: Number(x) }))
*                : { id: Number(value) },
            }
          : this.fieldAdaptersByPath[path] && this.fieldAdaptersByPath[path].gqlToPrisma
          ? this.fieldAdaptersByPath[path].gqlToPrisma(value)
          : value
      ),
      include: this._include(),
    });
  }
```
In this function Keystone force the conversion of `id` value to Number always. But we must lookup the target field type and convert to number only if have numeric field type on remote side.

**Comment by MurzNN** [comment]
Quick solution is remove the `Number(...)` conversion from this function, that fixes error with string ids, but broke with numeric ids :)
I can't find the way how to detect target field type in this function, can anybody help with this?

**Comment by MurzNN** [comment]
I tried to add simple field type detection and ignoring number conversion when needed via this ugly code: 
```js
  async _create(_data) {
    return this.model.create({
      data: mapKeys(_data, function(value, path) {
        let refListIdField = this.getListAdapterByKey(this.fieldAdaptersByPath[path].refListKey).fieldAdaptersByPath['id'];
        let refListIdFieldType = refListIdField.field.adapter.fieldName;
        let valueType = 'number';
        if(refListIdFieldType == 'Text') {
          valueType = 'string';
        }
        return this.fieldAdaptersByPath[path] && this.fieldAdaptersByPath[path].isRelationship
          ? {
              connect: Array.isArray(value)
                ? value.map(x => ({ id: valueType == 'number' ? Number(x) : x }))
                : { id: valueType == 'number' ? Number(value) : value },
            }
          : this.fieldAdaptersByPath[path] && this.fieldAdaptersByPath[path].gqlToPrisma
          ? this.fieldAdaptersByPath[path].gqlToPrisma(value)
          : value;
      }),
      include: this._include(),
    });
  }
```
...but try to find the better way.

**Comment by timleslie** [comment]
Thanks for the bug report @MurzNN, this is super useful.

I think this issue can more generally be described as "prisma adapter does not support custom idFields". While we expose an API for this, we haven't yet done any comprehensive testing of this feature. This is something we hope to be able to address more broadly in coming sprints 👍

**Comment by MurzNN** [comment]
Here https://github.com/keystonejs/keystone/pull/5007 is my PR with better implementation of previous code :) I make this because our developing project need the fix already now, hope I imolemented the right way. Please lookup it and comment if something can be done better.

**Comment by timleslie** [comment]
I'm going to close this issue for now, as we don't currently support non-autoincrement idFields. We will revisit this as a feature once the changes in #5635 have been completed.

**Comment by MurzNN** [comment]
Thanks for linking to that issue! I hope landing that changes will eats not so much time, so I'll adapt my changes to new ecosystem and make the new PR. Because my projects can't live now without this feature...

**Comment by MurzNN** [comment]
@timleslie About "as we don't currently support non-autoincrement idFields" - in documentation there is "idField" option https://next.keystonejs.com/apis/schema#id-field which describes, that we can use other field types for id, but there is only one "autoIncrement" field. What is the plans, for example, to use "uuid" field type from Keystone-5?

**Comment by timleslie** [comment]
At the moment the `autoIncrement` field type is the only one which will work as an `idField`. The new changes will definitely include a `uuid` field type, and we're also investigating adding support for other index field types as needed.

**Comment by gautamsi** [comment]
@MurzNN this is the line for `let idField = config.lists[key].idField ?? autoIncrement({});`  idField, you should be able to extend current autoincrement field or create a `cuid` field then pass it as idField option to the field.

**Comment by MurzNN** [comment]
@gautamsi thanks for the tip, but codebase now seems greatly changed, so I must rebase all my patches (BigInt field, pass id value from frontend, and others that actively used on my projects, which sits on pretty-old fork of Keystone now) to fresh code and try to reproduce this issue in fresh Keystone version, and maybe I'll found the better solution.

But I really hope that at this time the #5635 will be implemented, to not do the rebase again right after current rebase ;)

**Comment by gautamsi** [comment]
the best would be to create them as [**Contrib**](https://github.com/keystonejs-contrib/keystonejs-contrib) packages so that no need to rebase often, you can also get the released package to work with.

**Comment by MurzNN** [comment]
Those features need the changes inside Keystone core, so not so easy to implement this as separate packages ;( And implementing them as PR gives more chances to see them integrated to Keystone in new versions. So all universal features I try to create as PR to Keystone, instead of separate packages.
