### ISSUE TITLE
S3Field works in Keystone admin, but not in controller.

### ISSUE THREAD

**Issue by alsoicode** [keystonejs/keystone#505]
Sorry for the post here, but the Google Group isn't yielding any responses after several days. One of my models has an S3Field. The upload works fine from Keystone admin, but from my controller, the form submits and the document is created in MongoDB, and the S3Field is always empty.

Do I need to do something special for the S3Field to work in my controller? My form is set to multipart, the URL for the action parameter of the form is pointed correctly. Can someone point me to an example?

**Comment by JedWatson** [comment]
This should work, all the S3File code has recently been reworked a bit. Can you let us know if you still have issues with it @alsoicode?

**Comment by alsoicode** [comment]
Has the fix been merged to master? or is it in a separate branch?

**Comment by morenoh149** [comment]
@alsoicode multiple fixes have been merged into master and 0.2.x branch. Update and let us know if the problem persists

**Comment by alsoicode** [comment]
Thanks and will do today!

**Comment by alsoicode** [comment]
Sorry for the delay getting back this guys. I'll do my best to get a
project set up asap.
