### ISSUE TITLE
Cancel button for the Search UI in the Details view in the Admin UI is overlapped by form

### ISSUE THREAD

**Issue by Ventis** [keystonejs/keystone#512]
When you open the search dropdown in a Details View the "cancel" button to close the search field is overlapped by the form container beneath it. This makes it hard to click the cancel button as you have to aim somewhere between the search input and the "Cancel" label to get a successful click.

Also, when you have a non editable Text field as the first property in your model, the "cancel" button seems to push the Text field to the right, which is strange since they are not in the same container.

**Comment by izifortune** [comment]
the toolbar got a fixed height of 34px, so part of the cancel button is under the item-name.
I can fix this removing the fixed height but there's a comment there: `stop any jumping around when the form is revealed`. 

Or we can move the cancel button inline after the search one?

**Comment by JedWatson** [comment]
Rebuilt in 0.4, this is safe to close.
