### ISSUE TITLE
Work with video field type. Integration with YouTube or Vimeo

### ISSUE THREAD

**Issue by MioGreen** [keystonejs/keystone#517]
Hello, devs. Do you have any plans for support video field type and integration with services like YouTube or Vimeo like you have for images and Cloudinary?

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/work-with-video-field-type-integration-with-youtube-or-vimeo
