### ISSUE TITLE
select's datatype: integer not working with prisma_postgresql adapter (Next)

### ISSUE THREAD

**Issue by perlohmann** [keystonejs/keystone#5253]
# Bug report
In the auth example if you add a select field with datatype "integer" then the db/schema will still declare the datatype as a string.

## Describe the bug

I would expect a select element with datatype of integer to translate into a db field with the data type of integer and not text (postgres)

## To Reproduce
use prisma_postgresql adapter and then insert following code in the User schema and then run the app. if it is the first time it will fail creating the initial user and if it is an existing project then any new users will fail on creation.
``` typescript
// user state
    state: select({
      dataType: "integer",
      isRequired: true,
      defaultValue: 1,
      // only admins have access to this field
      access: {
        update: ({ session }) => session && session.data.isAdmin,
      },
      options: [
        { label: "Inactive", value: 0 },
        { label: "Pending activation", value: 1 },
        { label: "Active", value: 2 },
      ],
      ui: {
        displayMode: "segmented-control",
        createView: { fieldMode: "hidden" },
      },
    }),
```

**Comment by JedWatson** [comment]
@perlohmann thanks for the report - you are 100% correct about the bug here.

Good news is this was just fixed with #5227 which has been merged & will be released in the coming week (we just have a few more things to finish up before our next set of packages go out)
