### ISSUE TITLE
MailAPI

### ISSUE THREAD

**Issue by grabbou** [keystonejs/keystone#528]
//placeholder// Will be filled soon with structure draft. 

*The point is to create similar to Storage API layer (#526).*

**Supported providers:**
* Mandrill
* Postmark 
* SMTP
* Mailgun (suggested by @louim)
* you tell me?

**Comment by nzfarmer1** [comment]
What is the status with this?  Is there a Mail API yet for a generic SMTP server? thx.

**Comment by morenoh149** [comment]
@nzfarmer1 nope.

**Comment by nzfarmer1** [comment]
ETA?

**Comment by morenoh149** [comment]
@nzfarmer1 as far as I know no one is working on this feature. Free to pick implement.

**Comment by mark-bradshaw** [comment]
I'd suggest also including sendgrid as a possibility on that list.

**Comment by JedWatson** [comment]
Closing in favour of #250, definitely worth looking at nodemailer rather than coming up with our own. Now that Mandrill's no longer offering a free tier, I'm keen to get this picked up.
