### ISSUE TITLE
Keystone Camp - Meetups

### ISSUE THREAD

**Issue by grabbou** [keystonejs/keystone#529]
What about organising meet-ups like others are doing? 

I am living in London on day by day basis so I can organise something like that here + in my home country Poland as well.

We can there present the initial idea of our system, talk about pros & cons and so on. My dream is to have a kind of regular meet-ups about Keystone in multiple cities so we can all collaborate here on presentation we are going to give and prepare it for our speakers! (like me). It'd be very useful because one that's good at speaking and describing might be less experienced in creating catchy slides.

Let's take the world over!

Oh, and guys, to make that happen we need blue T-shirts with Keystone logo! :+1:

**Comment by JedWatson** [comment]
Going to close this because it's a fairly generic issue, if anyone's interested and hasn't been invited to our slack where we can discuss and organise things like this, let me know.
