### ISSUE TITLE
Rewrite Updatehandler

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#533]
Getting ready for custom field types, and as hi lighted in #526, we need to fix the "inversion of control" problems with the `UpdateHandler`.

It currently has hard-coded logic branches to handle the requirements of different built-in field types; these will need to be refactored into a format that field types can register hooks with (or respond to with specific, optional methods).

We're halfway there with things like the `getRequestHandler` methods on some fields, we just need to finish cleaning it up.

**Comment by creynders** [comment]
`updateHandler` will be dropped entirely
