### ISSUE TITLE
Case insesitive query throws server error. 

### ISSUE THREAD

**Issue by ashhitch** [keystonejs/keystone#5362]
when running a case insensitive query the the following error is thrown:

```
Invalid `
prisma.make.findMany()` invocation:
{
 where: {
    name: {
      equals: 'BMW',
      mode: 'insensitive'
        }
          ~~~~~~~~~~~~~~~~~~~~~
      }
    }
      
      Argument name: Got invalid value 
      {
          equals: 'BMW',
        mode: 'insensitive'
    }
      on prisma.findManyMake. Provided Json, expected StringNullableFilter or String or Null.
      
      
```

## To Reproduce

Runn the following query 
```graphql
query {
  allMakes(where: { name_i: "BMW" }) {
    name
    models {
      name
    }
  }
}
```
this also happens in code:

```js
   const res = await models.Make.findMany({
            where: { name_i: make }
          });
```

## Expected behaviour

Return results

## Screenshots

![image](https://user-images.githubusercontent.com/2438290/113612284-8bf70c00-9647-11eb-89f1-58a68450a59e.png)

## System information
- Keystone: `@keystone-next/keystone": "^14.0.1",`

**Comment by timleslie** [comment]
Hi @ashhitch, that's not ideal, this feature should be working. Can you tell me what database adapter you're using? That will help track down what's going on here.

**Comment by ashhitch** [comment]
@timleslie sure I'm using the Prisma / SQLite adapter

**Comment by timleslie** [comment]
@ashhitch Ah, I've just found the issue. The SQLite adapter does not support case insensitive search, due to limitations in SQLite itself. The `name_i` filter option should be disabled when running on SQLite (e.g. it shouldn't exist in the schema at all).. I just found a bug in the code which is stopping this disable step from working, which is why you're seeing it in your schema. I'm going to ship a fix for this in the next release 👍

**Comment by ashhitch** [comment]
@timleslie thanks for the speedy response to this... I am planning on switching to PostgreSQL anyway, SQLite just handy to get going with local dev.
keep up the awesome work 👍

**Comment by timleslie** [comment]
No worries. Good to hear that you're going to do the SQLite -> PostgreSQL upgrade, that's the graduation path that we'd expect most developers to take. SQLite is great for day 1 hacking, but the limitations make it worth making the step up to PostgreSQL worth it 👍
