### ISSUE TITLE
Want to use MongoDB but "The database url must start with postgres://"

### ISSUE THREAD

**Issue by phongyewtong** [keystonejs/keystone#5379]
I just use this command and it keep prompting me to use postgres when I am choosing MongoDB, is this a bug?

i just ran this on mac
npm init keystone-next-app newkeystone
![Screenshot 2021-04-07 at 12 03 23 AM](https://user-images.githubusercontent.com/4919605/113742241-fcc82200-9734-11eb-8b44-7fd14da3d126.png)

**Comment by sirbully** [comment]
Based on the docs, keystone-next supports only postgres and sqlite for now

**Comment by karimarkia** [comment]
You can change the adapter to :  `adapter: 'mongoose',` , and paste your url mongo link.

**Comment by bladey** [comment]
Hi @phongyewtong, it is no longer possible to use `mongodb` with Keystone Next, at this time we are supporting `postgres` only via Prisma -- https://next.keystonejs.com/roadmap#streamlined-back-end-with-prisma

Let us know if you have any further questions, I'm going to close this issue for now.
