### ISSUE TITLE
deafultValue for Fields API doesn't work

### ISSUE THREAD

**Issue by sirbully** [keystonejs/keystone#5399]
# Bug report

Not sure if I'm incorrectly setting the `defaultValue`. I'm using a string and docs say that:
> defaultValue (default: undefined): Can be either a string value or an async function which returns a string value.

## Describe the bug

Configuring a default value for a field doesn't create the object with the default value.

## To Reproduce

1. Set up default value for any field for a schema.
2. Create new object of the schema.

## Expected behaviour

The object is created with the default value configured.

## System information

- OS: macOS

**Comment by timleslie** [comment]
I just tested this on a list with the following config:

```
      label: text({ isRequired: true, defaultValue: () => 'default from function' }),
      test: text({ defaultValue: 'static default' }),
```

and got the following expected results.

![image](https://user-images.githubusercontent.com/616382/117377793-6e071a80-af17-11eb-8521-e28373b2edfe.png)

I'm going to close this issue for now. If this is still an issue then please reopen the issue 👍
