### ISSUE TITLE
Support for ACE Editor

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#544]
I believe that online programming content will be  big in the years to come.  Also CMS use templates and templates have a language and code behind them.  It would be nice to be able to edit these templates online via the Admin UI.  The ACE editor is being used successfully by some online IDEs.  I think keystone and its community will greatly benefit from its integration.  My own project calls for it :-)

For more about ACE:  http://ace.c9.io/

**Comment by tomtomau** [comment]
+1 ace editor is mint, would be really good to have this option

**Comment by ishandutta2007** [comment]
I am facing integrating the front end part left alone the serverside
http://stackoverflow.com/questions/30564518/issues-integrating-ace-editor-with-keystonejs-app

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: 
https://productpains.com/post/keystonejs/support-for-ace-editor
