### ISSUE TITLE
Code field:  Configurable Languages

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#546]
The set of languages supported by the Code field should be configurable.  Perhaps introduce a new option (e.g., "languages") that take new language configuration.  Moreover, the set of languages configured should be easily available as a property in the Code field so that, for example, the language list can be used in the Select field of a list model.  Not sure if it does already but that may require the Select field to support the dependsOn property with a function value:

    Types = keystone.Field.Types;
    lang: { type: Types.Select, options:dependsOn: Types.Code.toSelectOptions }

where the Types.Code exposes the toSelectOptions() method to convert the language list onto an options list for select or some similar construct.

**Comment by creynders** [comment]
Consolidated into #1979
