### ISSUE TITLE
Using the List Item API with context

### ISSUE THREAD

**Issue by junaid33** [keystonejs/keystone#5462]
# Bug report

Please use this form for bug reports only. If you have a question, feature request or want to chat with us, please select the appropriate option here - https://github.com/keystonejs/keystone/issues/new/choose

## Describe the bug

The next-lite example uses the List Item API to interact with Keystone

`import { lists } from '.keystone/api';`
`const posts = await lists.Post.findMany({ resolveFields: 'slug title' });`

But when I add auth to the schema and restrict access control to only show posts the user owns, the lists API still returns all the posts. The graphQL playground only returns the posts owned by the user. 

How can I make the the List Item API respect access controls like the playground does? I saw one way was to use `context.lists` but how we access context on getStaticProps and getServerSideProps?

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Clone and run locally: https://github.com/junaid33/next-lite
2. Go to localhost:3000/signin and signin using: gerald@example.com and helloworld as password
3. You will get redirected to localhost:3000 and see all the posts when Gerald only owns 1 post

## Expected behaviour

Only "Gerald's post" should be showing since that's what the graphQL allPosts search shows.

**Comment by dcousens** [comment]
@junaid33 we cannot reproduce this, and your example is many major versions behind.
Please open a new issue if you have can still replicate this problem.
