### ISSUE TITLE
Prisma client instance keep active in background when Keystone crashes

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#5477]
# Bug report

I catch the problem on debugging keystone app, that postgresql connections limit is full after some time of restarting keystone.
The source of problem is that when keystone-next crashes, the prisma client process stays active, so if keystone crashes 10 times, we will see 10 active prisma client processes.

## To Reproduce

1. Add the simple `onConnect` function that throws the exception in `keystone.ts`:
```js
export default auth.withAuth(
  config({
    db: process.env.DATABASE_URL
      ? { adapter: 'prisma_postgresql', url: process.env.DATABASE_URL, onConnect: (context) => {
          console.log('commected');
          throw 'test'
      } }
      : {
          adapter: 'mongoose',
          url: 'mongodb://localhost/keystone-examples-next-basic',
        },
```
2. Starts the `keystone-next` in dev mode 10 times with waiting when it throws the error and exits.
3. List the active prisma client process instances in memory - you will see about 10 active processes, that eats postgresql connections:
```
$ ps ax | grep -P '\.?prisma\/.+/query-engine' 
4075251 pts/0    Sl     0:00 /app/src/keystone/examples-next/basic/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x --enable-raw-queries --port 44697
4075603 pts/0    Sl     0:00 /app/src/keystone/examples-next/basic/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x --enable-raw-queries --port 42897
```
List the active `keystone-next` instances and see no one:
```
$ ps ax | grep '[k]eystone-next'
```
Also, if I stop the `keystone-next` process via <kbd>Ctrl+C</kbd> - prisma/client/query-engine exits well.

## Expected behaviour

Prisma client instance must die together with keystone-next.

**Comment by Nikitoring** [comment]
Yes, I have this problem too

**Comment by bladey** [comment]
Thanks for reporting this @MurzNN and @Nikitoring, we'll look into this and get back to you.

**Comment by timleslie** [comment]
I can confirm that I'm seeing the same behaviour. If I replace the `process.exit(1)` in `scripts/run/index.ts` with a `process.kill(process.pid, 'SIGTERM')` then prisma is correctly cleaned up.

Hoping to have a solution to this soon that will be available in the next release 👍
