### ISSUE TITLE
wysiwyg cloudinary images seems to be broken

### ISSUE THREAD

**Issue by Globegitter** [keystonejs/keystone#556]
I just tried to play around with the `wysiwyg cloudinary images` option. It does add the button, but when I try uploading a picture a get the error: `Got a bad response from the server`, even though I am getting a `200 OK` ok response and can even see the image:
`{"image":{"url":"http://res.cloudinary.com/keystone-demo/image/upload/v1408468196/ryooxdnq0wjxany29af8.jpg"}}`

Could that be, because I am using the demo credentials, or is that probably a bug?

**Comment by SharadKumar** [comment]
@Globegitter did this work for you in Chrome? 
Still keep the issue open? :)

**Comment by JedWatson** [comment]
Good question - this has been reworked by @sebmck for `0.3.0`, we should ensure it works as expected now in the master branch and then close this if it does.

**Comment by grabbou** [comment]
I remember that wysiwyg upload was quite quirky at the moment I looked into it. Nice that this's been reworked.

**Comment by izifortune** [comment]
Got this error on the 0.3.6, i needed to roll back to the 0.3.4, hope this can help

**Comment by morenoh149** [comment]
closing this in favor of https://github.com/keystonejs/keystone/issues/1304 let me know if it's a different bug
