### ISSUE TITLE
Should the Keystone API conform to the http://jsonapi.org/ spec?

### ISSUE THREAD

**Issue by davidbanham** [keystonejs/keystone#558]
Carrying on discussion from here:

https://github.com/JedWatson/keystone/pull/404

Should Keystone API aim to conform to this spec? Right now, the default list API returns data that looks like the following:

``` json
[
  {
    "slug": "foobar",
    "title": "foobar",
    "author": "538ef22e3bc7438c4f736cc4",
    "_id": "538ef48c190930f85218f8a7",
    "__v": 0,
    "createdAt": "2014-06-04T10:27:24.612Z",
    "state": "draft"
  },
  {
    "__v": 0,
    "_id": "53b4fbaab552fb00002f3653",
    "slug": "sdas",
    "title": "sdas",
    "content": {
      "brief": "<p>asd</p>",
      "extended": "<p>asd</p>"
    },
    "createdAt": "2014-07-03T06:43:54.000Z",
    "state": "draft"
  }
]
```

The only significant difference that I can see is that the jsonapi spec asks for the root element to be a dict and the List API returns an array. I know Angular plays more nicely with dicts than arrays, and @Globegitter has indicated the same about Ember.

I have also been burned by root element arrays in the past. Nothing insurmountable, but multiple times I have said to myself "I really want to add a new property to this response, and the fact that it's just an array is making that a pain in the bum. Now I have to update all the consumers of this endpoint to expect a dict."

A real-world use case I've had this on has been adding a flash messaging system. I was writing the Angular frontend for a Sinatra server, and we wanted the ability to add arbitrary flash messages to all API responses. I wrote a bit of middleware in the Sinatra app that appended something like the following to all responses:

``` json
{
  "data": ["super important client stuff"],
  "flash": [
    {
      "message": "You're pretty great!",
      "level": "info"
    }
  ]
}
```

And then some middleware in the Angular app that checked every API call for a conformant flash property and, if it found one, displayed any messages to the user.

Obviously, this could only be done on endpoints that returned dictionaries. Endpoints that returned arrays were not compatible.

So, should we change all list API calls so that they conform?

**Comment by creynders** [comment]
(Triage note: I think this is a _really_ valid discussion; leaving it open)

**Comment by JedWatson** [comment]
I think at this point, the ship has sailed. Keystone 5 is using GraphQL.
