### ISSUE TITLE
Allow custom methods to be provided for hashing and comparing passwords

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#56]
It would be good to allow projects to provide their own implementation of bcrypt (or any other hash / compare system) for password fields.

This would allow use of different modules (e.g. bcrypt-nodejs vs node.bcrypt.js) depending on developer preferences, and also allow compatibility with other systems (e.g. if you migrated an existing system to Keystone and needed backwards compatibility with a different password hashing system).

Inspired by #55

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. Please ask this question on [productpains.com](https://productpains.com/product/keystonejs)!
