### ISSUE TITLE
Unique fields aren't unique after List.model.collection.drop()

### ISSUE THREAD

**Issue by ignlg** [keystonejs/keystone#560]
*This isn't a KeystoneJS' issue, it's just something about Mongoose (or maybe MongoDB) that you should be aware of.*

After a `List.model.collection.drop()` all data and indexes are gone and, for a short period of time, you can insert duplicated `unique: true` fields without any errors or warnings.

I've discovered this running mocha tests. I dropped and redid the collections after every test and then uniqueness tests (trying to register/update users with an existing email, username) failed, *but* only when they were in the middle of other tests. Running alone they were fine.

I was able to query a `find` with an unique field and I've receive two and three results. After some ~~mad~~ research I've found that the issue came from the `drop`. Now I have replaced `List.model.collection.drop()` with `List.model.remove()`. More inefficient but safe in terms of model integrity.

I haven't got the time to go really deep into it yet but I hope it helps someone.

*If it's a well known issue and I've forgot how to search on Google properly, my apologies.*

**Comment by JedWatson** [comment]
Moved to keystonejs-site repo
