### ISSUE TITLE
New "many" mutations: `updatePosts` / `createPosts`

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#562]
Currently we have these:

| Singular     | Many          |
|--------------|---------------|
| `createPost` | ❌             |
| `Post`       | `allPosts`    |
| `updatePost` | ❌             |
| `deletePost` | `deletePosts` |

The missing mutations would be `createPosts` & `updatePosts` to complete that table.

The input parameters would be the same for the _Many_ case as for the _Singular_ case, but as an Array (and likewise for the return type):

```graphql
input PostsUpdateInput {
  id: ID!
  data: PostUpdateInput
}

input PostsCreateInput {
  data: PostCreateInput
}

type Mutation {
  updatePosts(data: [PostsUpdateInput]): Posts
  createPosts(data: [PostsCreateInput]): Posts
}
```

Which you'd then execute like so:

```graphql
mutation {
  createPosts(data: [
    { data: { title: "Hello" } },
    { data: { title: "A post" } }
  ]) {
    id
    title
  }
}
```

```graphql
mutation {
  updatePosts(data: [
    { id: "abc123", data: { title: "Hello" } },
    { id: "def456", data: { title: "A post" } }
  ]) {
    id
    title
  }
}
```

**Comment by maheraldous** [comment]
I just started using Keystone and when I use this code below in the image, it work and create one user but as long I use the second code it won't work

https://prnt.sc/u97b18

https://prnt.sc/u97bmq
