### ISSUE TITLE
Admin UI:  show relationship values as links

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#564]
When browsing a list entry in the Admin UI, if the value is a relationship reference and its many: attribute is set to false, then the Admin UI shows a "view <Relationship>" link.  However, if the many: attribute is set to true then you cannot browse to the relationships.  I suggest that the relationship reference value be displayed as a link thus enabling you to easily navigate to any relationship reference value.

**Comment by tomasztunik** [comment]
related to this as it is the same component - would be great to be able to quick create related model with relationship field filled in already. Now it takes lots of clicking to create related model. Maybe we could have separate issue for Relationship field type and relationship listings improvements?

**Comment by webteckie** [comment]
@tomasztunik see #282

**Comment by gaurav21r** [comment]
+1

**Comment by JedWatson** [comment]
Going to implement this (linking to relationship values) in 0.4

**Comment by jossmac** [comment]
This is now behaves as expected
