### ISSUE TITLE
Segment control needs null state for no default

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#5648]
I see that Segment control is confusing when there is no default state.

This should be fixed by adding a `indeterminate` or `no selection` state to segment control so it is visible that there is no value set. 

In basic example you can find that if you create an item, it will be shown as "Published" but it is actually has no value set and It would confuse people.

**Comment by bladey** [comment]
Thank you again for this report @gautamsi! We will look into this.

**Comment by mitchellhamilton** [comment]
This was fixed by #6638
