### ISSUE TITLE
Playground is not disabled for production

### ISSUE THREAD

**Issue by mahyarkarimi** [keystonejs/keystone#5652]
GraphQL playround for production is not disabled and either the apollo config passed to the graphql in config API does not take effect. I also tried following config to disable it at all but not working. here is my config for graphql:
...
graphql:{
    apolloConfig :{
      playground: false,
    }
},
...

Thanks.

**Comment by bladey** [comment]
Hi @mahyarkarimi, thanks for the report, I'm looking into this.

**Comment by bladey** [comment]
@mahyarkarimi confirmed that this is a bug we'll look into.

**Comment by bladey** [comment]
Completed.
