### ISSUE TITLE
Add option to show 'tracking fields'

### ISSUE THREAD

**Issue by mjmaix** [keystonejs/keystone#566]
Have an option to show tracking fields (`createdAt`, `updatedAt`, `createdBy` and `updatedBy`) in the Admin UI.

I'm planning to create PR for this.
For now I'm not sure w/c one is better
1. having a separate List options `showTrack : true` or 
2. plug new option on the `track` object `track: { createdAt: true, updatedAt: true, createdBy: true, updatedBy:true, showTrack: true}`

**Comment by morenoh149** [comment]
was this fixed?

**Comment by creynders** [comment]
AFAIK this is fixed, if not please reopen.

**Comment by JedWatson** [comment]
It pretty much is, the UI could be nicer / better integrated, but that'll happen over the course of the next few updates
