### ISSUE TITLE
Add Fields example

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#5680]
We want to have an `example` project which demonstrates how to use the scalar field types. It should demonstrate each of

 * checkbox
 * integer
 * float
 * decimal
 * password
 * select
 * text
 * timestamp

It should include examples of the different type-specific options which are available for each field type. See https://next.keystonejs.com/apis/fields#scalar-types.

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by gautamsi** [comment]
> https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects
this seems to be Thinkmill internal docs, Do you have plan to put his in docs? or a wiki page in github?

**Comment by timleslie** [comment]
> > https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects
> > this seems to be Thinkmill internal docs, Do you have plan to put his in docs? or a wiki page in github?

At this stage we're going to keep these docs internal as that's the most efficient way for us to work on them. We'll make them public once we've got the workflow a bit more polished and in a state that's more ready for general consumption.

**Comment by mitchellhamilton** [comment]
This issue is no longer relevant
