### ISSUE TITLE
Add select field example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5681]
We want to have an example project which demonstrates how to use the select field types. It should demonstrate each of the different configuration options for the select field, as well as cover their implications at the database and graphQL API level. 

It should include examples of the different type-specific options which are available for the select field type. See https://next.keystonejs.com/apis/fields#select

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now, please open-anew as a discussion if you would find this useful
