### ISSUE TITLE
Add image field example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5682]
We want to have an `example` project which demonstrates how to use the image field types. It should demonstrate:
*  how to configure a keystone instance with local image upload capabilities (see https://next.keystonejs.com/apis/config#images)
*  image field  configuration (see https://next.keystonejs.com/apis/fields#image)

See https://next.keystonejs.com/apis/fields#scalar-types.

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
See https://github.com/keystonejs/keystone/pull/7070,  an example is part of that pull request
