### ISSUE TITLE
Add file field example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5683]
We want to have an `example` project which demonstrates how to use the file field types. It should demonstrate:
*  how to configure a keystone instance with local file upload capabilities (see https://next.keystonejs.com/apis/config#files)
*  file field configuration (see https://next.keystonejs.com/apis/fields#file)

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by jesstelford** [comment]
I would also love to see how a client is meant to pass the file data - doesn't have to be framework specific; vanilla JS is fine 👍

**Comment by dcousens** [comment]
See https://github.com/keystonejs/keystone/pull/7070,  an example is part of that pull request
