### ISSUE TITLE
Add Hooks example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5688]
We want to have an example project which demonstrates how to use hooks in keystone. It should demonstrate each of the different hooks available in keystone and how to use them. (see https://next.keystonejs.com/guides/hooks)

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now, please open-anew as a discussion if you would find this useful
