### ISSUE TITLE
Add Access Control example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5689]
We want to have an example project which demonstrates how  access-control works in keystone. It should demonstrate:
how to configure access-control  in keystone:
* at the list level
* at the field level 
As well as demonstrate all the configuration options available for each. (See https://next.keystonejs.com/apis/access-control)

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now, please open-anew as a discussion if you would find this useful
