### ISSUE TITLE
Counts broken by upstream bug in `@graphql-tools/utils` (prevents keystone from working)

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#5697]
There is currently a bug in `@graphql-tools/utils` that has catastrophic impact on Keystone.

Bug report: ardatan/graphql-tools#2955

The issue for Keystone is that our count queries start with an `_` and the bug strips the resolvers that we generate 😬 so although the `_all${list}Meta` queries are defined in the schema, the resolvers are missing and the server will crash. This breaks the first user experience, and all of the screens in the Admin UI rely on counting items. So it's really bad.

The bug was released in a `patch` version, and `@graphql-tools/utils` is a dependency of one of our dependencies, so new installs will get the broken version and there's nothing we can do about it until the upstream bug is fixed and a new patch is released.

@timleslie has opened a PR fixing the bug: ardatan/graphql-tools#2956

We've tested the fix in this PR in keystone: #5693

If you experience this, currently the only known workaround is to force the module resolution in your `package.json` back to `7.9.0`

If you're using **yarn**, you can do this by specifying the `resoltions` key in your `package.json`:

```js
  "resolutions": {
    "@graphql-tools/utils": "7.9.0"
  },
```

We'll keep this issue open until the patch has been released to help increase visibility

**Comment by timleslie** [comment]
This has now been fixed in version `7.10.0` of the upstream package: https://github.com/ardatan/graphql-tools/issues/2955
