### ISSUE TITLE
Add document-field example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5709]
We want to have an example project which demonstrates the document field types,

It should include examples of:
- basic document field customisation
- adding relationships to the document field (see https://next.keystonejs.com/guides/document-fields#inline-relationships)
- adding custom component blocks to the document field (see https://next.keystonejs.com/guides/document-fields#component-blocks) 
- rendering the document in a React app (see https://next.keystonejs.com/guides/document-fields#rendering) 

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now,  please open-anew as a discussion if you would find this useful
