### ISSUE TITLE
Bulk actions

### ISSUE THREAD

**Issue by louim** [keystonejs/keystone#571]
Hello, started to use Keystone today and I can say I quite pleased. Looking at the features list gives me great hope for this project! Thanks you for making this.

I saw that the admin currently does not support "bulk actions". Would it be possible to add that to the feature list? I'm mostly interested by the possibility to delete all items in a list, but other bulk actions would be nice (like updating a certain column). What do you think?

**Comment by morenoh149** [comment]
Could you write up scenarios when you would want this. Also how does a user do a bulk action?

**Comment by louim** [comment]
Like I said, most important for me would be to allow deleting multiple records at the same time. In the list view, each row would have a checkbox, so I can check the ones I want to delete, and there would be a button "delete selected". 

For the edit option, one use case I can think of is product with price, where you want to edit multiple price at the same time. Inline edit would be nice for that. (Editing directly from the list view)

**Comment by creynders** [comment]
:+1: for bulk deletes.

**Comment by tusharmath** [comment]
What about Bulk uploads?

**Comment by youanden** [comment]
:+1:

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/bulk-actions
