### ISSUE TITLE
Add Custom fields example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5711]
We want to have an example project which demonstrates creating a custom field type..
It should demonstrate:
* Creating the different field views 
* Creating the implementation 
* Creating the database adapter 

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by gwyneplaine** [comment]
Subject to change, pending new field types infrastructure work.

**Comment by dcousens** [comment]
See https://github.com/keystonejs/keystone/tree/e98ef486faf338e6595e74f884cb1647f5bf5856/examples/custom-field and https://github.com/keystonejs/keystone/tree/e98ef486faf338e6595e74f884cb1647f5bf5856/examples/custom-field-view
