### ISSUE TITLE
Add data seeding example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5712]
We want to have an example project which demonstrates data seeding in Keystone.
This should use the onConnect() function to check if the database is empty and if so, add some initial values into the database. The aim here is to demonstrate how to seed data into a clean database, particularly for local dev workflows

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by gwyneplaine** [comment]
Closing issue as its no longer in line with our present plans around examples, **most** examples also presently have example data-seeding scripts included

**Comment by dcousens** [comment]
@thiguet nice addition to the :thread:! 
A reminder that
```
import * as PrismaModule from '.myprisma/client';
```

Should be
```
import * as PrismaModule from '@prisma/client';
```

Our examples use `.myprisma` as the Prisma location as this repository is a monorepo, but that may not be so for other developers.

**Comment by thiguet** [comment]
> @thiguet nice addition to the 🧵 A reminder that
> 
> ```ts
> import * as PrismaModule from '.myprisma/client';
> ```
> 
> Should be
> 
> ```ts
> import * as PrismaModule from '@prisma/client';
> ```
> 
> Our examples use `.myprisma` as a custom Prisma location, as this repository is a monorepo, but that may not be so for other developers.

Yeah, I also had issues with that! Nice job!
