### ISSUE TITLE
Add Github SSO example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5713]
We want to have an example project which demonstrates Keystone integration with Github SSO 
This needs to demonstrate how to write a custom mutation which can take an OAuth token from GitHub and use their APIs to associate with a user in keystone and start a session for that user. 

Refer to `keystone-next-lite` implementation
See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by VinayaSathyanarayana** [comment]
Supporting [next-auth](https://next-auth.js.org/) will provide support for a lot of Auth Providers in one go

**Comment by VinayaSathyanarayana** [comment]
The  example has to be Social Login  (for  front end) and also to secure APIs (on the backend)

**Comment by gwyneplaine** [comment]
Closing issue as its no longer in line with our present plans around examples

**Comment by krsnaa** [comment]
@gwyneplaine - I really think KeystoneJS should prioritize next-auth integration - both in the adminUI as well as a pure backend NextJS embedded scenario. This feature goes way beyond mere examples; Oauth/Passwordless is a central AuthN tenet in modern apps, that you get served on a platter with next-auth.

**Comment by tonxxd** [comment]
+1

**Comment by disco-infinex** [comment]
In case anyone missed it, there is now [a `next-auth` example](https://github.com/keystonejs/keystone/tree/main/examples/custom-session-next-auth) using the GitHub provider. It should be fairly trivial to adapt that code for other ID providers.
