### ISSUE TITLE
Add Roles example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5715]
We want to have an example project which demonstrates how rolesworks in keystone.  This example needs to demonstrate how to define roles for users and use these as access control rules. The ecommerce example uses this pattern and is a good reference example.

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now,  please open-anew as a discussion if you would find this useful
