### ISSUE TITLE
Add Custom Field Views example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5716]
We want to have an example project which demonstrates how to create custom field views in Keystone. 

This should cover each customizable view available for field types:
* Field  
* Cell 
* Card Value

As well as how this is integrated with the exported controller class. 

The `star` component [example](https://www.keystonejs.com/tutorials/custom-fields) in keystone 5 is a good example of how to do this  

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now,  please open-anew as a discussion if you would find this useful
