### ISSUE TITLE
Add Validation example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5717]
We want to have an example project which demonstrates how validation works in keystone. It should demonstrate:
how to configure validation in keystone both: 
* at the list level (see: https://next.keystonejs.com/guides/hooks#validating-inputs)
* at the field level, the same mechanism as above exists on each field implementation.

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now,  please open-anew as a discussion if you would find this useful
