### ISSUE TITLE
Add ID Fields example

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#5718]
We want to have an example project which demonstrates the various id fields in keystone. It should demonstrate configuring the following fields: 
* [autoincrement ](https://next.keystonejs.com/apis/fields#auto-increment)
* uuid (contingent on mitchell's field refactor) 

See https://thinkmill.atlassian.net/wiki/spaces/LAT/pages/334135360/Example+Projects for notes on how to create an example project.

**Comment by dcousens** [comment]
Closed for now,  please re-open as a discussion if you would find this useful
