### ISSUE TITLE
Paginate does not work with asycawait

### ISSUE THREAD

**Issue by Globegitter** [keystonejs/keystone#576]
I saw this article (and a few others) a couple weeks ago: http://jakearchibald.com/2014/es7-async-functions/ and thought this would make NodeJS/JS the way it should be.

Turns out there is this really nice library https://github.com/yortus/asyncawait which gives you a syntax that works today and is super close to the ES7 standard.
Using it with mongoose itself has worked fine, so
```js
var finance = await (keystone.list('PostCategory').model.findOne({ key: 'finance'}).exec());
```
works beautifully and turns this into a wonderful synchronous call.

```js
var q = await (keystone.list('Post').paginate({
          page: req.query.page || 1,
          perPage: 4
        })
        .populate('author categories')
        .where('state', 'published')
        .where('categories').in([finance])
        .sort('-publishedDate').exec());
```

Does not work and it just boils down to the use of `paginate`. Switching to `model.find()` everything works fine. So I suppose that `paginate` works a bit different under the hood than `find()`. Do you think that is something that could be fixed from the keystone end?
Would make working with all that stuff really much much nicer.

Also if you are interested in the whole code snippet, I am more than happy to provide that.

Edit: Not that I have much idea about this, but could it be that you are overwriting the exec function and then not returning a promise?

Edit2: Changing https://github.com/JedWatson/keystone/blob/82eb29180bf2d2121692683a1cbcdf6fe1c35de9/lib/list.js#L1148
to `Promise.promisify(function(callback) {` (via [Bluebird](https://github.com/petkaantonov/bluebird)) seems to have done the trick. Will test out if this properly works now.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/return-promise-from-listpaginate
