### ISSUE TITLE
Admin UI: Optionally displaying "heading"-separated fields in "tabs"

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#578]
I have a use case with a `List` that contains a fair number of fields, grouped by headings. It would be nice to be able to (optionally) navigate the form using tabs (for each heading) rather than just scrolling vertically.

Maybe using something like:

```js
var Test = new keystone.List('Test', { headingTabs: true });
```

or something similar.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/admin-ui-optionally-displaying-heading-separated-fields-in-tabs
