### ISSUE TITLE
Remove pagination in Admin UI

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#578]
From @jossmac [here](https://github.com/keystonejs/keystone-5/pull/577#issuecomment-448062428):

> Do we even need pages declared like this? Has there ever been a situation where the item you're looking for isn't on the first page and you thought "I'll go to page 4, that'll help"? Probably not. You're more likely to do one of the following:
> 
> - refine your search
> - refine your filters
> - change the sort order
> - go the next or previous page (potential for pre-fetching)
> - show more items per page (not implemented yet)
> 
> I think this is worth investigating. Many of the UI patterns in Keystone are an artifact of the original Node.js implementation, they've been carried forward over and over without any real interrogation regarding how they benefit the end user.

**Comment by MadeByMike** [comment]
Totally agree remove the pagination

**Comment by Vultraz** [comment]
What does this mean, exactly? Remove the ability to select a specific page to go to?
