### ISSUE TITLE
Segmented Control doesn't send initial selected value

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#5818]
# Bug report

## Describe the bug

Segment fields don't send initial value when creating item or saving item:

![Screen Shot 2021-05-26 at 7 33 04 AM](https://user-images.githubusercontent.com/737821/119926143-27f32300-bfba-11eb-93ca-31124beeb0eb.png)

Field config:

```
status: select({
  options: [
    { label: "Published", value: "published" },
    { label: "Draft", value: "draft" },
  ],
  ui: {
    displayMode: "segmented-control",
  },
}),
```

With that UI, you would expect that “Draft” is selected, but if you submit the form without the Status field being touched, it will set it as Status: “undefined”

The admin panel shows Published and Draft correctly, and defaults to the first one as “selected”.

So if you don’t touch the field when you create a post, it will actually register it as “undefined”.

But if you select Draft and then reselect Published and then hit save/create - then it will correctly set it as the enum value of “published”, or if you click Draft after Published, it sets the value to "draft".

To get around this, you could use isRequired, setDefault, and dataType: enum:

```
status: select({
  isRequired: true,
  defaultValue: "published",
  dataType: "enum",
  options: [
    { label: "Published", value: "published" },
    { label: "Draft", value: "draft" },
  ],
  ui: {
    displayMode: "segmented-control",
  },
}),
```

But seems like the admin segmented-control would rather just send the value of whatever is initially selected.

## To Reproduce

Configure this field and create items:

```
status: select({
  options: [
    { label: "Published", value: "published" },
    { label: "Draft", value: "draft" },
  ],
  ui: {
    displayMode: "segmented-control",
  },
}),
```

## Expected behaviour

Segmented-control sends the value of whatever is initially selected.

## Screenshots

(above)

## System information

N/A

## Additional context

Adapted from `@dl salo` on Slack - https://keystonejs.slack.com/archives/C01STDMEW3S/p1621963953186200

**Comment by gwyneplaine** [comment]
resolved in https://github.com/keystonejs/keystone/pull/5886
instead of fixing it by making the initial value always selected, the segmented control by default no longer 'selects' a value by default. (the initialIndex defaults to -1 now)
