### ISSUE TITLE
Exception when formatting GraphQL error

### ISSUE THREAD

**Issue by tjbp** [keystonejs/keystone#5898]
Keystone attempts to write the following readonly property:

https://github.com/keystonejs/keystone/blob/master/packages-next/keystone/src/lib/server/format-error.ts#L67

Original declaration:

https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-errors/src/index.ts#L7

This causes the following error, which has appeared on Slack a few times:

    Cannot assign to read only property 'path' of object '#<Object>'

I haven't submitted a PR since it's not immediately clear why the `path` property needs to be set.

**Comment by lex0r** [comment]
In my case the error is caused by an attempt by Keystone JS CMS app (the one running on localhost:8000 by default) to render a "many" relationship in ui.displayMode === "cards" mode. For some reason it uses the entity name in lowercase while graphql schema expects it to be starting with a capital. I don't use capitalised names for entities so this might be the condition not covered by any tests?

**Comment by tjbp** [comment]
@lex0r that sounds like a different error - this issue is caused by a bug in the error formatter - does your stack trace refer specifically to line 67 of format-error.ts? This is a generic error message that will be printed in an attempt to assign to a readonly property in TypeScript and so can't be used as an identifier in abstract.

If you _do_ see line 67 of format-error.ts, then remember we only reach the error formatter's code in runtime because an error elsewhere has occurred, so there could be potentially infinite (and unrelated) traces to this issue.

**Comment by gnimmelf** [comment]
[Keystone Newbie writing :point_down::point_down::point_down:]

I may have a related / same issue (if not, I'm sorry for the noise);

```js
{
  "errors": [
    {
      "message": "Cannot assign to read only property 'path' of object '#<Object>'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot assign to read only property 'path' of object '#<Object>'",
            "    at formatError (/home/gnimmelf/workspace/nanoshop/node_modules/@keystone-next/keystone/dist/createApolloServer-c4803901.cjs.dev.js:85:24)",
            "    at /home/gnimmelf/workspace/nanoshop/node_modules/apollo-server-errors/src/index.ts:287:28",
            "    at Array.map (<anonymous>)",
            "    at Object.formatApolloErrors (/home/gnimmelf/workspace/nanoshop/node_modules/apollo-server-errors/src/index.ts:285:25)",
            "    at formatErrors (/home/gnimmelf/workspace/nanoshop/node_modules/apollo-server-core/src/requestPipeline.ts:665:12)",
            "    at /home/gnimmelf/workspace/nanoshop/node_modules/apollo-server-core/src/requestPipeline.ts:649:15",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/home/gnimmelf/workspace/nanoshop/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ]
}
```
The funny thing is that the query I'm passing is working in the GQL Playground, but fails when run through fetch by `node-fetch` using `NextJs::getStaticProps`. This fails with the error listed above:
```js
export async function getStaticProps () {
  const res = await fetch('http://localhost:8055/api/graphql', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    body: JSON.stringify({
      query: `
        allProducts {
            title
            description
        }
    `
    })
  })
  const products = await res.json()

  return {
    props: {
      products
    }
  }
}
```

But this works:
![Screenshot from 2021-06-22 00-26-21](https://user-images.githubusercontent.com/488269/122835608-fb000a80-d2f0-11eb-8906-3cf8f20d1bd3.png)

Any ideas where to start looking if this indeed is wrapped as a generic error as @tjbp suggests?

Cheers!

**Comment by tjbp** [comment]
@gnimmelf yep same error, line 85 of `node_modules/@keystone-next/keystone/dist/createApolloServer-c4803901.cjs.dev.js` is this bug in the latest version. Comment out that line and it should successfully output the underlying error for you.
