### ISSUE TITLE
Error when using the new data api list but works when graphql sudo run

### ISSUE THREAD

**Issue by Temkit** [keystonejs/keystone#5916]
Hi, 

when i try to get some data using : 

`await context.sudo().lists.Role.updateOne({...`

i have this error : 

> Error: Unable to create and/or connect 42 Role.modulesRead<Module>
> 6:11:34 PM web.1 |      at promiseAllRejectWithAllErrors (/Users/sidalitemkit/work/web/savitem-new/savitem-new-keystone/node_modules/@keystone-next/keystone/dist/createSystem-2834b2c4.cjs.dev.js:811:19)
> 6:11:34 PM web.1 |      at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 6:11:34 PM web.1 |      at resolveInputForCreateOrUpdate (/Users/sidalitemkit/work/web/savitem-new/savitem-new-keystone/node_modules/@keystone-next/keystone/dist/createSystem-2834b2c4.cjs.dev.js:1823:41)
> 6:11:34 PM web.1 |      at updateOne (/Users/sidalitemkit/work/web/savitem-new/savitem-new-keystone/node_modules/@keystone-next/keystone/dist/createSystem-2834b2c4.cjs.dev.js:1809:7)
> 6:11:34 PM web.1 |      at Object.runGraphQL [as run] (/Users/sidalitemkit/work/web/savitem-new/savitem-new-keystone/node_modules/@keystone-next/keystone/dist/createSystem-2834b2c4.cjs.dev.js:3643:20)
> 6:11:34 PM web.1 |      at updateItem (/Users/sidalitemkit/work/web/savitem-new/savitem-new-keystone/node_modules/@keystone-next/keystone/dist/createSystem-2834b2c4.cjs.dev.js:2572:18) {
> 6:11:34 PM web.1 |    locations: [ { line: 2, column: 5 } ],
> 6:11:34 PM web.1 |    path: [ 'updateRole' ]
> 6:11:34 PM web.1 |  }

but it`s working when using : 

` await context.sudo().graphql.run({ ...`

and when debugin i have : 

> message: "\nInvalid `prisma.global.findMany()` invocation:\n\n\n  Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: 17)"

i first thougt the problem is coming from the database so changed from DigitalOcean to a heroku postgres database, and since  i have no error using the Grphql API directly so i figured it has something to do with prisma.

**Comment by dcousens** [comment]
I don't think we can investigate this issue with the information provided.
If you are still facing this problem, please open a new issue or a GitHub discussion asking for help to resolve your problem.
