### ISSUE TITLE
Error uploading images - Error: EXDEV, rename '/app/...'

### ISSUE THREAD

**Issue by Ryaan** [keystonejs/keystone#592]
Getting a strange error when trying to upload files to my site on my digital ocean server - the upload directory is on a different partition (using dokku), any advice on how the upload function is actually working would help greatly!

Error: EXDEV, rename '/app/651297494b1bad9a939f0006218ccda2'

This doesn't really tell me much!

Thanks

**Comment by morenoh149** [comment]
are you still interested in a solution?

**Comment by JedWatson** [comment]
@Ryaan please reopen if you still need help with this issue!
