### ISSUE TITLE
Do we add a tracing library to Keystone?

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#594]
We should consider having Application Tracing as part of Keystone-5

References:
https://jaegertracing.io/
https://opentracing.io/

**Comment by MadeByMike** [comment]
What are the benefits here?

**Comment by VinayaSathyanarayana** [comment]
The ability to trace each specific request (especially when part of a large / complex system) is essential to track  and also debug

**Comment by MadeByMike** [comment]
@VinayaSathyanarayana My background is primarily as a front-end dev. I understand what tracing is, but I don't quite see the value of baking this into Keystone (or maybe I need a better explanation)

At first glance it appears like something a user could add with a custom server or middleware? 

It also feels like picking one would be opinionated in the way Keystone tries to avoid.

Is this a space Keystone wants to own or do we just make this easy for developers to add.

**Comment by MadeByMike** [comment]
Closing due to lack of clarity around this. Happy to re-open if this becomes a priority for the community.
