### ISSUE TITLE
Hide models in admin ui depending on one of their fields

### ISSUE THREAD

**Issue by Globegitter** [keystonejs/keystone#607]
On the page that I am currently working on, you can subscribe to a newsletter and see all the people who subscribed on the backend.
I now want to add an **active** field so people can unsubscribe but then hide these entries (i.e. where active === 0) in the backend. Is that currently possible somehow?

Edit: And I suppose I created this issue because I couldn't find anything in the documentation if this feature does exist.

**Comment by dcousens** [comment]
@JedWatson any further thoughts on this?

**Comment by creynders** [comment]
AFAIK this is done in v0.4
