### ISSUE TITLE
a11y - text only alternative for `background-image` gradient text/headings

### ISSUE THREAD

**Issue by mattbx** [keystonejs/keystone#6078]
# Bug report

Please use this form for bug reports only. If you have a question, feature request or want to chat with us, please select the appropriate option here - https://github.com/keystonejs/keystone/issues/new/choose

## Describe the bug
Our `background-image` gradient text headings need a solid fill text alternative for when users are running system high contrast mode

## To Reproduce

All gradient text headings on KS6 have this issue

## Expected behaviour

IBM accessibility checker says: use text only alternative when using system high contrast mode.

## Screenshots

![image](https://user-images.githubusercontent.com/4239139/124891769-a234af80-e01c-11eb-8c97-df4e58b66766.png)
![image](https://user-images.githubusercontent.com/4239139/124892142-f475d080-e01c-11eb-90a8-418290f880a9.png)

## System information

All browsers/OS's

**Comment by bladey** [comment]
Moved to planning doc.
