### ISSUE TITLE
Errant semi-colon in DocumentRenderer

### ISSUE THREAD

**Issue by bishopZ** [keystonejs/keystone#6080]
# Bug report
There's a misplaced semi-colon on line 50 of 
https://github.com/keystonejs/keystone/blob/master/packages-next/document-renderer/src/index.tsx

It outputs the semicolon in the render.

**Comment by bishopZ** [comment]
https://github.com/keystonejs/keystone/blob/master/packages/document-renderer/src/index.tsx

**Comment by bishopZ** [comment]
It's not the one on line 50. I think it's the one on line 137, but if so, there's like other ';' that need to be removed.

**Comment by mitchellhamilton** [comment]
The semicolon on line 137 and the rest of the semicolons in that file don't seem to be in places where they would be in the rendered output. Could you create a reproduction on https://codesandbox.io? (without an actual keystone app, just using the DocumentRenderer)
