### ISSUE TITLE
Website: active-page link styling inconsistencies

### ISSUE THREAD

**Issue by raveling** [keystonejs/keystone#6083]
## Describe the bug

Active-page link styling is inconsistent across global navigation.

## Header

In the global header, the `Why Keystone` `Updates` and `Docs` menu items present blue link styling when the user is on the page.

![CleanShot 2021-07-12 at 11 47 57](https://user-images.githubusercontent.com/6447754/125218858-203bd380-e307-11eb-83f4-5eb27838ea02.png)

I assume this is expected behavior.

However, when the user is on: 

- https://keystonejs.com/for-developers
- https://keystonejs.com/for-organisations
- https://keystonejs.com/for-content-management
 
The active/blue link styling persists on the `Why Keystone` link in global header.
![CleanShot 2021-07-12 at 11 50 33](https://user-images.githubusercontent.com/6447754/125219061-8163a700-e307-11eb-88e5-0c81b1232be6.png)

This may have something to do with the fact that in the mobile menu, pages like `Organisations` are children of `Why Keystone`

![CleanShot 2021-07-12 at 11 51 43](https://user-images.githubusercontent.com/6447754/125219107-98a29480-e307-11eb-8d60-cdfdaf27f035.png)

---

## System information

- OS: Mac OS
- Browser: Chromium, Firefox, Safari

**Comment by bladey** [comment]
Moved to planning doc.

**Comment by dcousens** [comment]
This had been resolved anyway
