### ISSUE TITLE
Wrong type on graphQL __type request

### ISSUE THREAD

**Issue by Temkit** [keystonejs/keystone#6085]
i have a list :
```
const Hired: ListConfig<any, any> = {
 ...
 fields: {
    ...
    hiredDate: timestamp(),
    ...
 }
...
}
```

when i do : 

```
{
  __type(name: "Hired") {
    fields {
      name
      type {
        name
      }
    }
  }
}
```

i got the wrong type from the attribute **hiredDate** which is expected to be Date or Timestamp but i have String type instead

```
...
  {
          "name": "hiredDate",
          "type": {
            "name": "String"
          }
  },
...
```

**Comment by timleslie** [comment]
Hi @Temkit, the Keystone `timestamp` maps to a `String` type in the GraphQL schema, so what you're seeing is the expected behaviour.
