### ISSUE TITLE
Application Updates - can not pad the version numbers with zeros.

### ISSUE THREAD

**Issue by slam02** [keystonejs/keystone#617]
Hi,
when multiples update scripts are within an application, the alphabetically sorted files are not easy to read and error prone.
Example:
0.0.1
0.0.10
0.0.11
0.0.12
0.0.2
0.0.3
.... // snipped for clarity
0.0.9

Zero padding the version number could help to improve the visual experience for alphabetically sorted script lists.
Example:
0.0.01
0.0.02
0.0.03
.... // snipped for clarity
0.0.09
0.0.10
0.0.11
0.0.12

Unfortunately, when zero padding the scripts versions, the scripts are not picked up by keystone.

Thank you,
JF

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/application-updates-allow-padding-the-version-numbers-with-zeros
