### ISSUE TITLE
Unfurl `og:image` previews

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#6177]
We want to generate Open Images for all of our website pages.

This will directly embed images into shared tweets, Slack posts and so on.

Ideally it is a screenshot of the page so you get a preview of the contents rather than just a title / description of the page.

To do this we would visit pages at a mobile breakpoint, take a screenshot, save it and then embed it using the og:image tag on each page of the website.

A good example project exists here: https://github.com/agneym/generate-og-image

However we would prefer to use Playwright.

Deploying the website would trigger this as a GitHub action.

The images would probably be stored in the GitHub repo itself with uniques names based on the page URL.

The sitemap is a good source of truth for all possible URLs we want to create images for - https://keystonejs.com/sitemap.xml

We could also overlay a Keystone logo and a gradient to the bottom of the page to make it more on brand and nice, but this is a bonus task.

**Comment by bladey** [comment]
Going well, still in progress.

**Comment by yoDon** [comment]
Is this work being done in a way to enable keystonejs users to generate og:image previews of the pages on their sites or is it specific to the keystonejs.com homepage?

**Comment by bladey** [comment]
@yoDon specific to the KeystoneJS website, but will be open sourced in the long-term to be a generic library.

**Comment by bladey** [comment]
Moved to planning doc.
