### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by johnlo1992** [keystonejs/keystone#619]
Hi,

I was wondering if KeystoneJS had CORS support, couldn't seem to find the documentation on it from the website.

Best,
John

**Comment by JedWatson** [comment]
Just leaving a note here that `cors` middleware is now baked into Keystone, to use it you can do this:

```
app.all('/api*', keystone.middleware.cors);
```

... where appropriate in your route config.

**Comment by chrisschaub** [comment]
I can never get this to work. I've tried JedWatson's suggestion, but still no dice. Could it be that I have apache up front handling port 80 proxying to node/express on 3000? Add that line to my routes does nothing. Using latest keystone.

**Comment by alancwoo** [comment]
Was also confused about this, but eventually found this issue:
https://github.com/keystonejs/keystone/issues/1374

One needs to add the lines

routes: `app.all('/api*', keystone.middleware.cors);`

keystone.js file in root: `keystone.set('cors allow origin', true);`

**Comment by cvn** [comment]
For POSTing JSON data, in addition to the steps mentioned by @alancwoo, I also had to add the following to routes, to satisfy the preflight OPTIONS request:
```js
app.options('/api*', function(req, res) {
	res.send(200);
});
```

**Comment by TheDucc** [comment]
Thank you @cvn for that wonderful bit of code I needed.

But I still needed more when trying to use my api routes to talk to the new version of angular (2.0.0-rc.4).

```javascript
app.all('/api*', keystone.middleware.cors);
app.options('/api*', function(req, res) {
   res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-XSRF-TOKEN');
   res.sendStatus(200);
});
```

I know this overwrites the  keystone.middleware.cors values, so I though I would post this here in order to get opinions on the validity of this technique.

**Comment by MikelArnaiz** [comment]
I have a weird behaviour. 
I am developing an app with Ionic, locally, if I install the app on the phone these lines work:

index.js
`app.all('/api*', keystone.middleware.cors);
app.options('/api*', function(req, res) {
	res.sendStatus(200);
});`

keystone.js
`keystone.set('cors allow origin', true);`

If I run the app with livereload `ionic run android --device --livereload` the login works, but the api calls don't. I get a 403 Forbidden. If I disable checkAuth it works (without security). My routes/index.js is like:

`exports = module.exports = function(app) {
	app.all('/api*', keystone.middleware.cors);
	app.options('/api*', function(req, res) {
		res.sendStatus(200);
	});

	app.post('/api/signin', sessionAuth.signin);
	app.post('/api/signout', sessionAuth.signout);

	app.all('/api*', sessionAuth.checkAuth);
		
	app.get('/', routes.views.index); // View

	app.get('/api/v1/something', keystone.middleware.api, routes.api.v1.something.getSomething);
};
`
Can be this related to CORS?

**Comment by wmertens** [comment]
You will need to look at the requests in your app, probably the livereload makes them behave differently (maybe the origin changes?). I doubt that Keystone has anything to do with this.

**Comment by steveinatorx** [comment]
i kept getting OPTIONS 404s until i added @cvn suggestion of as it were

`app.options('/api*', function(req, res) {
    res.send(200);
});`

**Comment by useralive003** [comment]
var express = require('express'); 
    var app = express(); 
    var bodyParser = require('body-parser');
    var multer = require('multer');

    app.use(function(req, res, next) { //allow cross origin requests
        res.setHeader("Access-Control-Allow-Methods", "POST, PUT, OPTIONS, DELETE, GET");
        res.header("Access-Control-Allow-Origin", "http://localhost");
        res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
        next();
    });

    /** Serving from the same express Server
    No cors required */
    app.use(express.static('../client'));
    app.use(bodyParser.json());  

    var storage = multer.diskStorage({ //multers disk storage settings
        destination: function (req, file, cb) {
			//console.log(file);
            cb(null, './uploads/');
        },
        filename: function (req, file, cb) {
            var datetimestamp = Date.now();
            cb(null, file.fieldname + '-' + datetimestamp + '.' + file.originalname.split('.')[file.originalname.split('.').length -1]);
        }
    });

    var upload = multer({ //multer settings
                    storage: storage
                }).single('file');

    /** API path that will upload the files */
    app.post('/upload', function(req, res) {
		
		console.log(req.body);
		
        upload(req,res,function(err){
            if(err){
                 res.json({error_code:1,err_desc:err});
                 return;
            }
			
             res.json({error_code:0,err_desc:null});
        });
    });

    app.listen('3000', function(){
        console.log('running on 3000...');
    });
