### ISSUE TITLE
Add `@updatedAt` attribute to `Schema API` field level

### ISSUE THREAD

**Issue by tsui66** [keystonejs/keystone#6195]
### Discussed in https://github.com/keystonejs/keystone/discussions/6194

<div type='discussions-op-text'>

<sup>Originally posted by **Quinton** July 27, 2021</sup>
Automatically stores the time when a record was last updated. If you do not supply a time yourself, the Prisma Client will automatically set the value for fields with this attribute.</div>

**Comment by mitchellhamilton** [comment]
This was added by #6674
