### ISSUE TITLE
Navbar links from item view are incorrect

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#6201]
When in the item view, the links in the Navigation component link to the wrong place (e.g. `/tasks/tasks`).

<img width="751" alt="Screen Shot 2021-07-27 at 4 54 46 pm" src="https://user-images.githubusercontent.com/616382/127111202-195bfb06-a110-441e-9dda-034e7f8f414a.png">

**Comment by gwyneplaine** [comment]
Resolved in #6205
