### ISSUE TITLE
`_isOptimistic @client` GraphQL field incorrectly sent to API when deployed to `now`

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#621]
Using `@voosware/apollo-helpers`'s `_isOptimistic @client` directive works fine locally - Apollo correctly strips that field before sending the query to the GraphQL server.

However, on the same app deployed to `now` v1, the field is _not_ stripped, resulting in GraphQL server errors (because it doesn't know how to resolve the field or what the `@client` directive is).

I can't find any bug reports about this behaviour for Apollo online, so am assuming it's a bug in our code.

NOTE: I've tried mimicking the `now` environment as best as possible locally with `NODE_ENV=production`, etc, but I cannot replicate the incorrect behaviour locally.

**Comment by MadeByMike** [comment]
@jesstelford is this one still an issue?
