### ISSUE TITLE
 Cannot read property 'Cell' of undefined

### ISSUE THREAD

**Issue by pranavkhapra** [keystonejs/keystone#6257]
## Hi.

So apparently i am deploying my back-end part of keystone-next project on Heroku while following the official docs and besides all the small errors i faced during trying to deploy the project which was resolved i faced a new error.

After deploying my app so when i am  logging in with the username after that  instead of showing all the content inside it its just on a loading screen , the console errors are  **Cannot read property 'Cell' of undefined** 

Everything works great on my local machine.

I spent like half day  figuring what to do but  couldn't figure out what actually is the problem ( i thought i was doing something stupid in my code) but apparently many people face the same issue and they have not been answered but was acknowledge but other people  of having same issues same case at the community slack channel.

So if anyone has faced the issue and some method helped them please share.....:)
Thanks.
*(p.s sorry for the bad grammar.)*

**Comment by molomby** [comment]
Are your packages up to date? This sounds a lot like #4914 but that problem was patched in Feb. 

Long shot but another dev mentions clearing their cache helped..

**Comment by ztratify** [comment]
As @molomby mentioned, I was able to resolve this same issue by updating keystone packages: https://github.com/keystonejs/keystone/issues/4914#issuecomment-898723498

**Comment by pranavkhapra** [comment]
Hi sorry for the late response but apparently this issue can be solved by updating the packages and changing the code to the latest version of the docs.
