### ISSUE TITLE
Locking down access to API calls

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#627]
## Situation

Calls to the GraphQL API can be categorised into;

1. `Server-to-API` calls (eg; during server side rendering)
2. `Client-to-API` calls (eg; the user is logging in / requesting more posts / etc).
3. `*-to-API` calls (eg; bots doing `curl` requests, automated scripts, **Cross-Site-Request-Forgeries**, etc).

Currently there's no way of restricting API calls to just the first 2 cases.

### CSRF attacks

Keep in mind [CSRF attacks](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet) are often triggered from the client by a 3rd party website. When that happens, the browser sends along any credential data (eg; cookies), which means just checking credentials is not a protection against this attack.

(_related issue: https://github.com/keystonejs/keystone-5/issues/133_)

### Non-browser requests

When using the GraphQL API to track actions that are later used to make business decisions (eg; CPC/CPM), it is particularly important to lock down who can make the requests.

This is different to CSRF in that it may not be an attack where an API request is triggered _on behalf of someone else_, but rather sending raw requests to an otherwise open API end point.

Credential checking here does not help to limit requests (it's trivial to send valid credentials with `curl` requests, etc).

## Solution

To stop CSRF attacks, we need to have CSRF protection on API requests. This needs to be opt-in as it may be perfectly valid for an API to be used outside the context of a browser:

- [`csurf`](https://github.com/expressjs/csurf)
- [`jwt-csrf`](https://github.com/krakenjs/jwt-csrf)

We must also consider the Server-to-API requests; they will not have CSRF tokens, and so must be validated in some other way (eg; with a specific `Authorisation` header which when used gives access to the API. aka; an API key).

Ideally with this combination, we'd be able to lock-out all `*-to-API` calls.

**Comment by gautamsi** [comment]
I would want to make server to server calls using api key or generated JWT with trimmed access.

for example, you can select lists and its permission level for each list/field on a UI/api and generate a token/api key which gives you restricted access. 

use case, I want to spin a micro service container which can only access Email Queue list and process sending emails, I can generate a token which can read all fields in Email list but only able to save processed field (true/false value).  (there are other better way to achieve this but this is just an example use case)

**Comment by one-thunder** [comment]
Any progress on this?
