### ISSUE TITLE
Title in keystone.init() doesn't work for AdminUI

### ISSUE THREAD

**Issue by Ventis** [keystonejs/keystone#629]
Right now, setting the title in keystone.init() sets it as a local to be used in the default layout but when you navigate to AdminUI views the title will always be Keystone.
It's not hardcoded in the base layout template because that just uses local.title, but it is hardcoded in the AdminUI view routers. For example list.js:

```javascript
keystone.render(req, res, 'list', _.extend(viewLocals, {
	section: keystone.nav.by.list[req.list.key] || {},
	title: 'Keystone: ' + req.list.plural,
	page: 'list',
        ...
	query: req.query
}));
```

This is not a problem for me personally but my clients are pretty confused when the title all of a sudden changes from "Foo" to "Keystone".

**Comment by snowkeeper** [comment]
Fixed by #971.  @Ventis sorry it took so long.
