### ISSUE TITLE
Enhanced support for cloudinary upload options

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#631]
As reported by @JohnnyEstilles in #604, it would be very useful to be able to globally define (and override on a per-field basis) the full set of upload options for Cloudinary.

> First, a global cloudinary upload options that will accept an object with key/value pair for any Cloudinary optional parameters as described in the Cloudinary documentation. For exmaple:

```
keystone.set('cloudinary upload options', { backup: true, use_filename: true } );
```

> And ... a per-field uploadOptions (in both CloudinaryImage and CloudinaryImages) for exactly the same purpose:

```
image: { type: Types.CloudinaryImage, uploadOptions: { backup: true } },
images: { type: Types.CloudinaryImages, uploadOptions: { use_filename: true, unique_filename: true } }
```

**Comment by bringking** [comment]
Was there any progress on this? I am working on the CloudinaryImageField and really need this functionality. I would love to dig into this and finish it up..

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/enhanced-support-for-cloudinary-upload-options
