### ISSUE TITLE
Add ability to categorize list items in Admin UI

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#632]
If I define a list that create items per some type/category then I would like the Admin UI to break up or group the item list by type/category.  Each grouping should have the ability to sort, filter, etc. For example:

    var Vehicle = new keystone.List('Vehicle', {
    Vehicle.add({
         type: { type: Types.Select, options: 'car, bicycle, motorcycle'},
         make: ...,
         model: ...,
         year: ...,
         color: ...
    });

In the Admin UI, when displaying items of Vehicle I like the display broken up by type :

    Cars
        car-1,
        car-2,
        car-3,
        ...

    Bicycles
        bicycle-1,
        bicycle-2,
        bicycle-3,
        ...

    ...

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/add-ability-to-categorize-list-items-in-admin-ui
