### ISSUE TITLE
Nested navigation for global header

### ISSUE THREAD

**Issue by raveling** [keystonejs/keystone#6324]
Adding nested navigation functionality for the global header will make it easier for website users to (1) understand what high-level pages are available, and (2) orient their journey in a way that relates to their unique motives.

## Actions:

- [ ] @raveling describe navigation schema for UI design
- [ ] @mattbx design UI
- [ ] @bladey @mattbx implement frontend code

**Comment by republic-productions** [comment]
Why blocked? I just started using keystone 6 today and the lack of an option to include a top bar global nav type navigation, or any other navigation menus  for that matter is...idk what but it could use to be more extendable. I've forked the repo and an currently in the process of making the code base more extendable.

**Comment by raveling** [comment]
@republic-productions this issue is in relation to the keystonejs.com website header 

Regarding customising navigation in Admin UI, there are a few options available at present:

- https://keystonejs.com/docs/guides/custom-admin-ui-logo
- https://keystonejs.com/docs/guides/custom-admin-ui-navigation
- https://keystonejs.com/docs/guides/custom-admin-ui-pages

We are also looking at other ways to make it more customisable 🙂

**Comment by raveling** [comment]
We can come back to this when we need more sections.
