### ISSUE TITLE
Write a guide on uploading files

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#636]
We need a walkthrough of how to upload files with the GraphQL API:

On the server:
- Use `apollo-upload-client` instead of Apollo's `httpLink`
  - (Is this still the case in newer versions of Apollo?)
- Setup the File Adapter of your choice (File or Cloudinary)

In the client:
- Get the file data from `event.target.files[0]`
- Use the `Upload` graphql type when sending the data to the graphQL server
- For images, extract the `publicUrl` in queries

cc @nathansimpsondesign

**Comment by molomby** [comment]
This would definitely be handy but I'd sure up the fields type reference docs first, eg. #636.

**Comment by gautamsi** [comment]
I figured out this - https://github.com/keystonejs/keystone/discussions/3053#discussioncomment-52869
