### ISSUE TITLE
List Items API documentation errors

### ISSUE THREAD

**Issue by thombuchi** [keystonejs/keystone#6365]
# Bug report

Current documentation in keystone website about List Items API is wrong for certain functions as **createMany, deleteOne and deleteMany**   [docs](https://keystonejs.com/docs/apis/list-items)

## Describe the bug

If you look at the examples for the functions createMany, deleteOne and deleteMany they don't work in current build of keystone next.

For example:
createMany is documented as following:
```
const users = await context.lists.User.createMany({
  data: [
    {
      name: 'Alice',
      posts: [{ create: { title: 'Alices first post' } }],
    },
    {
      name: 'Bob',
      posts: [{ create: { title: 'Bobs first post' } }],
    },
  ],
  query: 'id name posts { id title }',
});
```

But for it to work it should be like:
```
const users = await context.lists.User.createMany({
  data: [
    {data: {
      name: 'Alice',
      posts: [{ create: { title: 'Alices first post' } }],
    }},
    {data: {
      name: 'Bob',
      posts: [{ create: { title: 'Bobs first post' } }],
    }},
  ],
  query: 'id name posts { id title }',
});
```

The same goes to deleteOne: 
current example:
```
const user = await context.lists.User.deleteOne({
  where: { id: '...' },
  query: 'id name posts { id title }',
});
```
and it should be:
```
const user = await context.lists.User.deleteOne({
   id: '...' ,
  query: 'id name posts { id title }',
});
```

deleteMany example also doesn't work but I haven't been able to find which is the correct syntax to make it work correctly.

## To Reproduce

Try any of the examples in current keystone next build.

## Expected behaviour

To have working examples in the docs.

Thanks!

**Comment by timleslie** [comment]
Hi @thombuchi, these APIs have been changed in the latest release which just came out, and the docs correspond to this new release. I suspect you've probably got an out of date install. Let us know if there's something else going on 👍 

See https://keystonejs.com/releases/2021-08-17 for release notes.
