### ISSUE TITLE
How to create a post by combining multiple posts?

### ISSUE THREAD

**Issue by binarykitchen** [keystonejs/keystone#637]
Do you think keystone would be able to create some kind of a "super" post, based on multiple (independent) posts?

So that the author can generate contents by assembling various existing posts together?

**Comment by morenoh149** [comment]
@binarykitchen do you still have this issue?

**Comment by BerkeleyTrue** [comment]
I don't think this needs to be some hard-coded method. This should be do-able using a regular query.

```js
Post.model.find().exec(funciton(err, posts) {
posts.forEach(function(post) {
//combine posts
view.locals.superPost = superPosts;
view.render();
});
});
```

**Comment by JedWatson** [comment]
@binarykitchen you may have solved this given how old the issue is, but a `Relationship` field where `Post` links back to itself should do the trick.

expanding:

```
var Post = new keystone.List('Post');
Post.add({
    postType: { type: Types.Select, options: 'post, superPost' },
    // ...
    subPosts: { type: Types.Relationship, ref: 'Post', many: true }
});
Post.register();
```

then in your route:

```
Post.model.findOne().where('slug', req.params.post).populate('subPosts').exec(funciton(err, post) {
	// post.subPosts is an array of the combined posts
});
```
