### ISSUE TITLE
Embed videos

### ISSUE THREAD

**Issue by binarykitchen** [keystonejs/keystone#638]
Does keystone come with the ability to embed videos?

So that I can insert a `<video>` inside a post, pointing to remote sources?

**Comment by JedWatson** [comment]
Just for reference, we have an [Embedly](http://keystonejs.com/docs/database/#fieldtypes-embedly) field that makes this really easy.

**Comment by PhillyOne** [comment]
@JedWatson is there another way to do this yet? Embedly is kind of a deal breaker as my reason for choosing keystone was that I could host it myself and not have to link to any external saas providers. Embedly is now also pretty costly.
