### ISSUE TITLE
Child processes don't exit when using `session-store-redis`

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#6415]
When the `@keystone-next/session-store-redis` package is used, it never gets past the `GraphQL and Prisma schemas are up to date` step.

It’s something around the client being initialised and it waiting, the `createClient` function needs to be looked into from the Redis package itself.

Console scripts appear to wait for all child process and Redis client is one of them.

It appears if you try to create any Redis client in Keystone file you will get the same result. Therefore the fix should be helpful not only for `session-store-redis`.

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/737821/130902529-c16b846e-1f39-4a87-b45b-12abd0189bfb.png">

_Sourced and adapted from Goncharenko Denis on Keystone Community Slack - https://keystonejs.slack.com/archives/C01STDMEW3S/p1625288844359500_

**Comment by jlarmstrongiv** [comment]
Ahh, I ran into this too.  The main issue is that you need to close the redis client or the postinstall hook will hang.  So if you change your package.json command to `POSTINSTALL=1 keystone-next postinstall` and add a check:
```
if (process.env.POSTINSTALL) {
  redisClient.quit();
}
```
then it will quit automatically and allow the postinstall to finish.  I don’t use `@keystone-next/session-store-redis`, so this will work on custom stores and probably different databases too.

**Comment by bladey** [comment]
Thanks for the solution @jlarmstrongiv, much appreciated!

**Comment by mitchellhamilton** [comment]
This was fixed by #7051
