### ISSUE TITLE
Create item with default relationships?

### ISSUE THREAD

**Issue by liamwooding** [keystonejs/keystone#644]
Is it possible to define a model with a relationship field, and have that relationship field populated by default with one or more items?

I'm working on an ecommerce site where some items can't be sold to certain countries because of distribution rights issues. I've created a Country model, and a relationship field on the Product model so that when products are created you can add countries to a blacklist which we check against when we receive credit card info. However, for the time being the client doesn't want to sell anything at all to the USA (sorry folks).

Is it possible to automatically add the USA to this relationship field on creation?

**Comment by morenoh149** [comment]
@liamwooding is your issue resolved?

**Comment by creynders** [comment]
Solved/stale
