### ISSUE TITLE
CSRF fails

### ISSUE THREAD

**Issue by itzaks** [keystonejs/keystone#647]
Hey!

I'm unable to login (most of the times) and when I do I cannot edit/create any models as I constantly get thrown off by: `keystone.security.csrf.validate`. Logs give me no clues on how to proceed and I'm unsure on how to debug this. I'm running the latest version of keystone.

Errors: `There was an error with your request, please try again.` and `There was a problem with your request, please try again.`

Any ideas on how to debug or proceed with this is much appreciated.

Thanks,
Isak

**Comment by morenoh149** [comment]
@itzaks problem was resolved
