### ISSUE TITLE
Use an array from another Model

### ISSUE THREAD

**Issue by vfermino** [keystonejs/keystone#648]
Hello. I am new to JS, and I've been trying to make a catalog-like website, and I have two models: Product (which represents individual products) and Collection (which is a category or product line, so it can group many products).

`
var keystone = require('keystone'),
	Types = keystone.Field.Types;
var Product = new keystone.List('Product', {
	autokey: { path: 'slug', from: 'name', unique: true },
	map: { name: 'name' },
    defaultSort: '-createdAt'
});
Product.relationship({ path: 'collections', ref: 'Collection', refPath: 'collection' });
Product.add({
	name: { type: String, required: true },
	collections: { type: Types.Select, options: [keystone.List.Collection] }, // My big problem
	publishedDate: { type: Date, default: Date.now },
	banner: { type: Types.CloudinaryImage },
	content: {
        brief: { type: Types.Html, height: 150 },
        extended: { type: Types.Html, height: 400 }
    },
	icon: { type: Types.CloudinaryImages }
});
Product.register();
`

The question for me is: how do I make an array out of the Collections to give the user a dropdown of the Collections an item can belong to? I will probably change them to a list of checkboxes, though.
Thanks.

**Comment by morenoh149** [comment]
@TejasCMehta could you open a new issue for your question. Or use the irc channel/google group/stackoverflow tag
