### ISSUE TITLE
Support columns

### ISSUE THREAD

**Issue by binarykitchen** [keystonejs/keystone#654]
My client very badly wants a CMS where you can define the number of columns. Similar like the Wordpress' Visual Composer plugin http://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431 does.

Say, define how many columns in a 12er-grid, i.E. 1x3, 1x6, 1x3, and then fill out these three textareas with images, pictures through the TinyMCE editor.

This would give users unlimited possibilities to layout their contents and push Keystone a little closer to Wordpress.

Has anyone already hacked anything like that? @JedWatson

**Comment by morenoh149** [comment]
not an issue

**Comment by JedWatson** [comment]
@binarykitchen sorry for the non-response, going through the backlog and saw this. @metasansana was on the mark with the suggestion that the upcoming upgrade will allow for plugins that implement features like this.
