### ISSUE TITLE
Support preloading data from models before listening for requests.

### ISSUE THREAD

**Issue by metasansana** [keystonejs/keystone#658]
I'm working on an application where I need to load configuration data from the database before I start accepting requests.
The workflow goes something like:
* Register models
* Load config data from database and cache it.
* Start accepting requests.

Doing this without rolling my own express/mongoose instances was tricky due to the way the `start` and `mount` functions work together:

[Here] (https://github.com/keystonejs/keystone/blob/master/lib/core/start.js#L78) a function is declared that eventually opens up the port to accept connections.

This gets passed [here](https://github.com/keystonejs/keystone/blob/master/lib/core/start.js#L232) to `mount` which [connects](https://github.com/keystonejs/keystone/blob/4608f487e5f3f8f9a3d96afddaf04e867510cab3/lib/core/mount.js#L545) mongoose to mongodb then calls the function to start listening for connections.

I can't query data until mongoose is connected so I would have to call `mount` in my own code, however by doing that I would have to also include some of the work of `start` in my own code correct?

I can't use any of the hooks `start` provides as loading db data is async. My current solution:
```javascript

keystone.mount({

   onMount: function () {
   
     model.findOne().exec().
     then(function(config) {

         keystone.mount = function(evt) {
                   evt.onMount && evt.onMount();
       };
      keystone.start();
      }).end();
  
  }

})

```

**Comment by stunjiturner** [comment]
any update on the situation?

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains:
https://productpains.com/post/keystonejs/allow-hooking-into-keystone-bootstrap-sequence
