### ISSUE TITLE
After update to Keystone 25.0.3 Admin UI next/babel resolution bug

### ISSUE THREAD

**Issue by savager** [keystonejs/keystone#6583]
After following the Sept 6th release update instructions, I am no longer able to load/use the Admin UI. 

Running yarn dev (keystone-next dev) returns the following:

`<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving 'next/babel' in /Users/savage/Sites/cape/node_modules/@keystone-next/keystone/node_modules/next/dist/compiled/babel for build dependencies doesn't lead to expected result '/Users/savage/Sites/cape/node_modules/next/babel.js', but to '/Users/savage/Sites/cape/node_modules/@keystone-next/keystone/node_modules/next/babel.js' instead. Resolving dependencies are ignored for this path.
<w>  at unknown 4 next/babel
<w>  at file dependencies /Users/savage/Sites/cape/node_modules/@keystone-next/keystone/node_modules/next/dist/compiled/babel/bundle.js
<w>  at file /Users/savage/Sites/cape/node_modules/@keystone-next/keystone/node_modules/next/dist/compiled/babel/bundle.js
<w> `

and then in the browser: 
Error: Cannot find module 'next/dist/shared/lib/constants.js'

My package.json: 
![image](https://user-images.githubusercontent.com/1455337/133684950-80a27b88-61fe-4bd3-aedd-33c9d7f04d96.png)

I am using lerna for a monorepo. root package.json show: 
![image](https://user-images.githubusercontent.com/1455337/133685126-0180aa16-d8f3-47b2-b70d-026fcae98950.png)

I have tried deleting all node_modules, clearing yarn cache, removing yarn.lock, different versions of node. Etc. 

Mac OS X

**Comment by savager** [comment]
This was my fault. I didn't know there was another package in the same monorepo using Next 10. Closing issue, sorry ;)

**Comment by joshmedeski** [comment]
I ran into the same error. I had to remove the next package because the `@keystone-6/core` package has a certain version of NextJS as a dependency.
