### ISSUE TITLE
Cannot use createMany when createOne with the same code can

### ISSUE THREAD

**Issue by b0tm1nd** [keystonejs/keystone#6603]
## Describe the bug

This code works:

>                let users = await keystone.context.lists.Product.createOne({
>                   data: //[
>                     {
>                       title: product.title,
>                       shopify_id: product.id.toString(),
>                       date: Date.now().toString()
>                     },
>                     /*{ 
>                       title: product.title,
>                       shopify_id: product.id,
>                       date: date_ob.now()
>                     },*/
>                   //],
>                   query: 'id ',
>                 });

When this one:

>                 let users = await keystone.context.lists.Product.createMany({
>                   data: [
>                     {
>                       title: product.title,
>                       shopify_id: product.id.toString(),
>                       date: Date.now().toString()
>                     },
>                     /*{ 
>                       title: product.title,
>                       shopify_id: product.id,
>                       date: date_ob.now()
>                     },*/
>                   ],
>                   query: 'id ',
>                 });

throws this error:

> (node:793195) UnhandledPromiseRejectionWarning: GraphQLError: Variable "$items" got invalid value { title: "10 Lunchbox..", shopify_id: "708089..", date: "1632067693395" } at "items[0]"; Field "title" is not defined by type "ProductsCreateInput".

KeystoneJS version 22.0.0

Excerpt from the generated schema.graphql:

> input ProductCreateInput {
>   title: String
>   shopify_id: String
>   date: String
>   accounts: AccountRelateToManyInput
> }
> 
> input ProductsCreateInput {
>   data: ProductCreateInput
> }

I also get same error when trying to use the default Users list.

Same happens when I try to use a raw graphql query via context.graphql.raw or via playground console:

                const { data, errors } = await keystone.context.graphql.raw({
                        query: `mutation {
                          createProducts(data: [{ title: "test", shopify_id: "123", date: "${Date.now()}" }, { title: "test", shopify_id: "123", date: "${Date.now()}" }]) {
                            id 
                          }
                        }`,
                });

**Comment by timleslie** [comment]
Each item in the `createMany` expects a `ProductsCreateInput` item, which has the type:
```
input ProductsCreateInput {
   data: ProductCreateInput
}
```

You need to do:

```
            let users = await keystone.context.lists.Product.createMany({
              data: [
                {
                  data: {
                    title: product.title,
                    shopify_id: product.id.toString(),
                    date: Date.now().toString()
                  },
                }
                /*{
                  data: {
                    title: product.title,
                    shopify_id: product.id,
                    date: date_ob.now()
                  }
                },*/
              ],
              query: 'id ',
            });
```

Note that this API has changed in the latest version of Keystone (`25.0.1`) and the nested `data` keys are no longer used.

**Comment by b0tm1nd** [comment]
Thanks for clarifying. So what will be the syntax in the latest version?

**Comment by b0tm1nd** [comment]
I assume just no need to use "data:" in the above examples.
