### ISSUE TITLE
Default response on malformed json is in HTML

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#663]
I've got a keystone app which exposes a JSON REST API, however if the request contains malformed JSON (not semantically, but syntactically, i.e. it sets `Content-type: application/json` but doesn't provide valid json) a HTML response is rendered:

```html
<html>
    <head>
        <meta charset='utf-8'>
            <title>Error</title>
            <link rel='stylesheet' href='/keystone/styles/error.css'>
            </head>
            <body>
                <div class='error'>
                    <h1 class='error-title'>Sorry, an error occurred loading the page (500)</h1>
                    <div class="error-message"></div>
                </div>
            </body>
        </html>
``` 

I tracked this down to the `default500Handler` in `lib/core/mount.js`. 

I have my own error handlers in place, but unfortunately this error is thrown before they are registered.
I've been trying to hook into the process, but haven't succeeded so far. It's pretty annoying since clients expect and assume a json response.

Any ideas on how I can override the default 500 handler in time?

**Comment by JedWatson** [comment]
> Somewhere down the road I suppose error output formatting will be handled with content negotiation?

Yes, I think we should implement that in the default error handler. Will look into it.

**Comment by JedWatson** [comment]
Closing in favour of #2247
