### ISSUE TITLE
Error when typing quickly into Relationship field

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#6635]
When typing too quickly in a relationship select field, the following error pops up:

![error](https://user-images.githubusercontent.com/737821/134440606-00b4e5d7-2f19-4ffb-b5ed-a1edd6c5835c.jpg)

From Steven Jones:

>Hi :wave: I've noticed that if I type too quickly when selecting an item, the attached error pops up. If I type slowly then it's fine.

_Adapted and paraphrased from Keystone Community Slack - https://keystonejs.slack.com/archives/C01STDMEW3S/p1631004679268600_

**Comment by mitchellhamilton** [comment]
Fixed by #6839
