### ISSUE TITLE
Original filename of uploaded file to image/file fields is not kept

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#6641]
# Bug report

## Describe the bug

When file is uploaded to Keystone item, file name are regenerated:
For images it becomes as uuid like this: `7bcf91af-14f2-4cca-98b1-f8c1b0c593e7.jpg`
For files - the unique suffix is added, like this: `original-file-name-2y8Q9jrq0mGxW7DE1.pdf`
And there is no information in database are stored about original filename of uploaded file!

## To Reproduce

1. Upload file or image with original file name.
2. Lookup the file name and all other fields in database - you will not see your original file name!

## Expected behaviour

File name should be stored at least in database as some field, even if we store the file in directory using uniqueized filename!
And we should show it in Admin UI instead of generated one.

## System information

- Keystone at commit 7a7f3f6d063a58fb7627dbec3be237b4d7e6e26f

**Comment by bladey** [comment]
_Related Keystone Community Slack thread - https://keystonejs.slack.com/archives/C01STDMEW3S/p1632389826435700_
