### ISSUE TITLE
Cloudinary Image not rendered in the admin ui when using postgres as database provider

### ISSUE THREAD

**Issue by kobbiman** [keystonejs/keystone#6668]
# Bug report

## Describe the bug

I was testing out the staging example of ecommerce and found out that Cloudinary Image field is not rendered in the admin ui when using `postgres` as database provider.

### Current Behaviour
<img width="1193" alt="Screen Shot 2021-09-28 at 9 54 27" src="https://user-images.githubusercontent.com/4082685/135037956-65ee2928-50d0-4ef1-a32f-490dc651afb0.png">

### Expected Behaviour
<img width="1032" alt="Screen Shot 2021-09-28 at 9 53 20" src="https://user-images.githubusercontent.com/4082685/135037979-5ee61b2c-11c1-4bc9-8e76-c322edd6faad.png">

Apparently, the value returned by the cloudinary image resolver is a json string which needs to be parsed. I was able to  resolve it by changing...

https://github.com/keystonejs/keystone/blob/8631917d14778468652abb8eda06802d2469646c/packages/cloudinary/src/index.ts#L155

to something like...

```
let val: any = null;
try {
  val  = typeof value === 'string' ? JSON.parse(value) : value;
} catch (err) {}
```

**Comment by bladey** [comment]
Thanks for reporting this @kobbiman, we'll investigate.

**Comment by bladey** [comment]
Hey @kobbiman,

I'm unable to replicate this using either `postgres` or `sqlite`, image previews are coming through for me:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/737821/135386358-96ebb933-589b-49ac-a8a5-c23cee24bf6d.png">

I have used both the current version on npm (09dca57) and the current state of `master` (c8aca95) when this comment was written.

Could you please confirm which exact version you're using?

**Comment by kobbiman** [comment]
Hey @bladey , I cloned the latest version on master and problem still exist.  Below is what I have in the dependency section of package.json for the `examples-staging/ecommerce`

```
"dependencies": {
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/preset-env": "^7.15.6",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.15.0",
    "@babel/runtime": "^7.15.4",
    "@keystone-next/auth": "^33.0.0",
    "@keystone-next/cloudinary": "^8.0.0",
    "@keystone-next/keystone": "^26.0.0",
    "@types/nodemailer": "^6.4.4",
    "dotenv": "^10.0.0",
    "next": "^11.1.0",
    "nodemailer": "^6.6.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "stripe": "^8.178.0"
  }
```
