### ISSUE TITLE
When category or title contain utf-8 character, keystone stop being functional

### ISSUE THREAD

**Issue by doomred** [keystonejs/keystone#668]
Try using category or title like '如何可以让女孩子感觉到我是真心爱她的',
category filter and even reading post is not possible.
The later reports 'Invalid Category'.

The relative code is near L34:templates/views/blog.jade

FYI:
build Keystone using yo keystone,
I am new to node & any further info are welcome :)

**Comment by morenoh149** [comment]
is this still a bug? or is it now a feature request for i18n?

**Comment by morenoh149** [comment]
closing if favor of https://github.com/keystonejs/keystone/issues/802
