### ISSUE TITLE
Content Management

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#67]
It would be great to be able to define a data structure for storing content, where pages would be a single representation instead of a collection.

The structure would be defined in a similar syntax to models:

	keystone.set(‘content', {
		home: {
			title: String,
			headerImage: Types.CloudinaryImage,
			intro: { Types.Html, wysiwyg: true }
		},
		about: {
			title: { type: String, default: 'About' },
			content: { Types.Html, wysiwyg: true }
		}
	});

… then there would be an easy way to retrieve content for a particular page, something like this:

	keystone.getContent(‘about’, callback);

Page content would be stored on a page-per-document basis, in a collection called `app_content`.

**Comment by marekgoczol** [comment]
it's been open for over a year now, I would appreciate any timing update on that.

**Comment by J4G-** [comment]
So this isn't being targeted for 0.3?

**Comment by itzaks** [comment]
Hm that's too bad. Still checking up on this issue now and then for updates. I'm eager to help if there's something I can do.

**Comment by acontreras89** [comment]
:+1:

**Comment by creynders** [comment]
TBH I don't really see the need for this (at least not for static page generation). You can achieve "static" pages, by creating a Pages collection and creating a view which resolves a url parameter to determine what "page" needs to be shown. 
See 
* https://github.com/d-pac/d-pac.cms/blob/master/app/models/pages.js
* https://github.com/d-pac/d-pac.cms/blob/master/app/routes/views/page.js
* https://github.com/d-pac/d-pac.cms/blob/master/app/routes/index.js#L52

All you need to do is create a Page, fill out the `slug` field. Then if you surf to `//<host>/content/<slug>` it'll show whatever you filled out content wise. Obviously if you need multiple page types, i.e. with various fields you'd need multiple collections. But that would be the same with the above approach.

**Comment by acontreras89** [comment]
@creynders, as you can see in the original comment, the idea is to be able to manage (maybe completely) different pages from the same "collection". For now, you either create a different collection for each different layout or you limit yourself (and the people who'll be working with the CMS later on) to generic fields (like having a couple of `WYSIWYG` editors to compose the whole page.)

On the other hand, I can't help it but feel like this feature would make a huge difference when it comes to internationalization.

**Comment by creynders** [comment]
@acontreras89 ah yes, didn't read it thoroughly enough I realise! Ok, nvm my other post!

**Comment by lojack** [comment]
I wrote about an approach that accomplishes this using list inheritance a little while ago. The approach is a bit different than what @JedWatson proposed. But you can read about it @ http://rob.codes/creating-a-page-router-in-keystonejs/

If enough people find this useful I should be able to pull this functionality out into its own library or integrate it with keystone.

**Comment by acontreras89** [comment]
thanks for sharing your experience, @lojack 
Your approach is somewhat similar to what we were talking
> create a different collection for each different layout

Of course we can work around the lack of centralized _static_ content management, but having this functionality would likely make things easier :grin:

**Comment by Mentioum** [comment]
My way allows pages to be created within the same collection?

I just created a collection which allows the user to change the slugs.

Then if I go to through that collection before I do other routes which might match the same pattern checking against the requested URL for a match.  If I find a match I parse the item, if I don't i continue down the other routes.

Each 'page' in that collection then has a Select dropdown for the template they want to use for that page which is populated on startup from a template folders contents.  It then shows the correct fields for that template using 'dependsOn:'

The handlebars template then has a switch statement in it which loads a different partials depending on template options and other page settings.

Works fine IMO.  I'd like a more efficient way of checking perhaps but tbh its going to be just fine unless you've got hundreds of custom pages.

If anyone is looking for an example of more detail please do get in touch.

**Comment by charleslouis** [comment]
Hey there !

Thanks for sharing @Mentioum and for offering a more detailed example !

We're looking into this solution as well as discussed here : https://groups.google.com/forum/#!topic/keystonejs/yIqUNaD_H30 since we just figured out keystone doens't offer a single representation for single pages instead of a collection.

Would you mind putting together a Gist example or screen captures to illustrate how you achieve this ?
Mainly :
- how do we implement dependsOn in the model and create the dropdown ?
- how to populate the template list from the /templates folder ?

I'll start digging this meanwhile, but that would be awesome !

**Comment by charleslouis** [comment]
Based on @Mentioum solution, here is how we are handleling this at the moment :
Disclaimer : this solution is not advanced/better, but the code example might help some people.

1 - We've duplicated Post.js model to create a Page.js model 

2- created a dropdown with templates
`template: { type: Types.Select, options: 'page, about, team, contact, portfolio', default: 'page'},`

3- display someField if the selected template is 'about'
`someField: { type: String, dependsOn: { template: 'about' } },`

and it works :)

Now, I'd like to have an OR operator in `dependsOn: { template: 'about' }`, so that I can do something like `dependsOn: { template: 'about' OR 'legal' } ` or `dependsOn: { template: 'about || legal' } `

Any idea on how to make this happen ?

Thanks !

Full code example for Page.js here : https://gist.github.com/charleslouis/ff5cc15ce7d2f3aee59d

**Comment by ignlg** [comment]
What about allowing functions?
```
dependsOn: { template: checkTemplate }
```

That way it's easy to be extremely flexible:
```
function checkTemplate(template) {
  return (template === 'about' || template === 'legal');
}
```

It's the easiest way to allow any behaviour, complex or not.

**Comment by charleslouis** [comment]
Yes indeed @ignlg !! Thank you very much !

**Comment by Mentioum** [comment]
@charleslouis and @ignlg The dependsOn object takes an array or a list of comma separated variables (String) as well as just a single value so I believe so you can have multiple template values show the same fields if you choose to.  I actually called my model 'SpecialPages' and ended up storing all sorts of stuff in there:

```javascript
var keystone = require('keystone');
var Types = keystone.Field.Types;

/**
 * Special Page Model
 * ==================
 */
var Pages = [
  'About',
  'Home',
  'Facilities',
  'Gallery',
  'Team',
  'FAQ',
  'Contact',
  'Book a Tour',
  'Help'
];

var SpecialPage = new keystone.List('SpecialPage', {
  map: {name: 'title'},
  plural: 'SpecialPages'
});


SpecialPage.add({
  active: {type: Types.Boolean },
  title: { type: String, required: true, intial: true},
  page: {type: Types.Select, options: Pages, note: 'Choose which page this custom data is for.  Make sure there is only one SpecialPage per SpecialPage type Active.' },
  home: {
    testimonies: {type: Types.Relationship, ref: 'Testimony', many: true, dependsOn: {page:'Home'}},
    segments: {type: Types.Relationship, ref: 'Segment', many: true, dependsOn: {page: 'Home'}},
    carouselSegments: {type: Types.Relationship, ref: 'Segment', many: true, dependsOn: {page: 'Home'}},
    videoUrl: {type: Types.Url, note: 'This will be the video URL for the home page.', dependsOn: {page: 'Home'}},
    videoTitle: {type: Types.Text, note: 'This will be the title under the video at the top of the page.', dependsOn: {page: 'Home'}},
    videoText: {type: Types.Text, note: 'This will be the small text under the video at the top of the page.', dependsOn: {page: 'Home'}},
    videoImage: {type: Types.Relationship, ref: 'Image', note: 'This image will show on mobile intead of the video.', dependsOn: {page: 'Home'}}
  },
  facilities:{
    introduction:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'Facilities'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'Facilities'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'Facilities'} }
  },
  team:{
    introduction:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'Team'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'Team'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'Team'} }
  },
  help:{
    introduction:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'Help'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'Help'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'Help'}},
    faq: {
      thumbnailTitle: {type: Types.Text, note: 'This is the title which will appear on the FAQ thumbnail Text ', dependsOn:{page: 'Help'}},
      thumbnailText: {type: Types.Text, note: 'This is the text which will appear on the FAQ thumbnail Text ', dependsOn:{page: 'Help'}},
      thumbnailImage: {type: Types.Relationship, ref: 'Image', note: 'This image will be used for the thumnail linking to the FAQ page.', dependsOn:{page: 'Help'}},
    }
  },
  gallery: {
    introduction: {type: Types.Html, wysiwyg: true, dependsOn: {page: 'Gallery'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'Gallery'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'Gallery'}},
  },
  faq: {
    introduction:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'FAQ'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'FAQ'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'FAQ'}},
  },
  about:{
    introduction:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'About'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'About'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'About'}},
  },
  contact:{
    introduction:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'Contact'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'Contact'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'Contact'}},
  },
  tour:{
    introduction:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'Book a Tour'}},
    successText:{type: Types.Html, wysiwyg: true, dependsOn: {page: 'Book a Tour'}},
    bannerImage: {type: Types.Relationship, ref: 'Image', note: 'The image which appears at the top of the page.', dependsOn: {page: 'Book a Tour'}},
    bannerText: {type: Types.Text, note: 'This text will appear overlaying the banner image.', dependsOn: {page: 'Book a Tour'}},
  },
  meta: {type: Types.Relationship, ref:'Meta'},
});

SpecialPage.defaultColumns = 'title, page, active';
SpecialPage.register();
```

**Comment by snowkeeper** [comment]
We recently updated dependsOn to accept mongoose style expression operators.  I have not updated the docs yet.  For more info you can checkout the [README](https://github.com/snowkeeper/expression-match#keystone-dependson) for expression-search.  It has a Keystone example collection.

**Comment by charleslouis** [comment]
Thanks @Mentioum and @snowkeeper !

**Comment by Mentioum** [comment]
Ah good to know @snowkeeper !

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!
