### ISSUE TITLE
Uploading local files doesnt recognize extensions with numbers like .mp4

### ISSUE THREAD

**Issue by rkmax** [keystonejs/keystone#6747]
# Bug report

## Describe the bug

Uploading local files doesnt recognize extensions with numbers like .mp4

## To Reproduce

1. add a files section to the config
```
files: {
   upload: 'local',
   local: {
     storagePath: '/tmp/files'
   }
}
```
2. add a file fields to a model
````
import {file} from "@keystone-next/keystone/fields";
file: file(),
````
3. Go to the admin ui and create a mp4 file like `background.mp4`
4. after save the file the file is named like `background.mp4-aw3bzgn7Ce1jMTe5hfD1`

The generateSafeFilename function is not able to recognize the ext of the file resulting in `${urlSafeName}-${id}` the regex used for that `/^([^:\n].*?)(\.[A-Za-z]+)?$/` only look for letters

## Expected behaviour

after save the file the file should be named like `background-aw3bzgn7Ce1jMTe5hfD1.mp4`

**Comment by dcousens** [comment]
Resolved by #6714
