### ISSUE TITLE
Specify custom "Success" messages per list

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#677]
## What

Imagine this flow:

- I run a blog site where people can submit their own posts.
- I receive an email telling me I got a new post.
- I click the link to load up Keystone on that post.
- I now have to change the `status` to `Approved`
- I click `Save`
- _An email is sent to the author, **and** the post is now live on the site_
- I see:
  <img width="377" alt="screen shot 2019-02-09 at 2 18 40 pm" src="https://user-images.githubusercontent.com/612020/52515873-9e4aaa80-2c75-11e9-809c-0259c0d734f3.png">

That success message _"<label> Saved Successfully"_ is not very informative of what actually happened.

Ideally, I'd be able to specify a custom message to better describe what happened (an email was sent, and the post is live at `<url>`). Something like:

<img width="392" alt="screen shot 2019-02-09 at 2 38 20 pm" src="https://user-images.githubusercontent.com/612020/52516036-5e38f700-2c78-11e9-9f5b-6d0f0a771bf5.png">

## How

One possible solutions is as part of the `afterChange()` hook (which currently expects `undefined` as the return type);

```javascript
keystone.createList('Post', {
  fields: {
    approved: { type: Checkbox },
    /* ... */
  },
  hooks: {
    afterChange({ updatedItem, existingItem }) {
      if (updatedItem.approved && !existingItem.approved) {
        sendApprovalEmail(updatedItem);
        return {
          message: `
**${updatedItem.title}**

✅ Changes saved successfully.<br />
✉️ ${updatedItem.author.name} has been notified of approval.<br />
🔗 <a href="${updatedItem.url}">View the post online here</a>
          `,
        },
      }
    },
  },
});
```

**Comment by MadeByMike** [comment]
Relates to #1452

**Comment by gautamsi** [comment]
I think this is more than custom actions
