### ISSUE TITLE
Issues with long index names in migrations with Prisma and Postgres

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#6812]
When using migrations and complex data schemas with a Postgres database, Prisma is throwing errors as it is truncating long index names when running migrations.

```
EngineError: P3006
Migration `20211011130400_new_required_validation_defaults` failed to apply cleanly to the shadow database.
Error:
db error: ERROR: relation "_Organisation_categories_OrganisationCategory_organisations_AB_" already exists
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:354
   1: sql_migration_connector::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/lib.rs:342
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:108
```

Prisma state the issue is fixed [here](https://github.com/prisma/prisma/issues/9415) but it is still an issue even when upgrading Prisma packages to 3.3.0 and above. It may be an underlying Postgres issue.

A workaround is to shorten field names so not exceeded index limits.

It is unknown when this will be fixed, needs further investigation and could be a core Postgres issue.
 
Related Prisma Issue - https://github.com/prisma/prisma/issues/9415

_Adapted and sourced from Ben Booth in the Keystone Community Slack - https://keystonejs.slack.com/archives/C01STDMEW3S/p1633988631173200_

**Comment by mitchellhamilton** [comment]
The fundamental issue here is that [Postgres has a limit on identifiers of 63 bytes by default and it will truncate identifiers that are longer than that](https://www.postgresql.org/docs/14/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) so if you end up with long names, they're gonna be truncated and they might not be unique after being truncated.

I suppose we could allow people to set the name of the relation (which Prisma will then add `_` to the front and make that the name of the join table)? We could also change the name of the relations that we generate so we only include one side so it would be harder to run into the limit? (this would ofc require migrations for many-many existing relationships)

**Comment by dcousens** [comment]
> We could also change the name of the relations that we generate so we only include one side so it would be harder to run into the limit?

I know this would trigger required migrations for many,  but we don't necessarily have a choice around this without from what I can see.  
That solution will decrease the frequency of occurrence for this bug to something within somewhat acceptable limits.

Building POSTGRESQL yourself with `NAMEDATALEN` > 64 is a non-starter  and truncating or mapping the index names to something shorter (say using a hash function) is probably too harsh on our DX too.

**Comment by rburgst** [comment]
I think at the very least it would be nice to print out an error when booting pointing to this issue (or recommending shorter field names).
