### ISSUE TITLE
You guys have a Dynamic Schema CMS!

### ISSUE THREAD

**Issue by reggi** [keystonejs/keystone#687]
I was looking for a project just like this! I just wrote out exactly what I wanted. I'm wondering your thoughts @JedWatson!!

https://gist.github.com/reggi/a54ee1cc617a44ede878

I'd love to see a text-editor page for the specific model template in the backend. I'd also love to be able to create a new model from the CMS itself.

This is not an issue and is open for discussion. Feel free to close immediately / tell me where to move this!

**Comment by morenoh149** [comment]
@reggi invited you to the slack
