### ISSUE TITLE
Examples/document-field GraphQL error 

### ISSUE THREAD

**Issue by Gerosullivan** [keystonejs/keystone#6887]
# Bug report

## Describe the bug

GraphQL error encountered in `examples/document-field` when I run `yarn dev:site`:
```
GraphQL errors occurred:
Cannot query field "allAuthors" on type "Query". Did you mean "authors" or "author"?
```

## To Reproduce

1. Clone `keystone` repo.
2. `yarn install` in root directory
3. `cd examples/document-field` and then `yarn install` again
4. `yarn dev` and then `yarn dev:site`
5. Server error in app running on port 3001

## Screenshots

![image](https://user-images.githubusercontent.com/739146/140611083-b00da54b-8f35-4e69-9fad-5fde5323bb4e.png)

## System information

- OS: macOS BigSur 11.4
- Browser Chrome Version 95.0.4638.69

**Comment by bladey** [comment]
Hi @Gerosullivan, thanks for the report, will be fixed in https://github.com/keystonejs/keystone/pull/6889
