### ISSUE TITLE
`keystone-next postinstall` fails when upgrading packages if schema update is required

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#6888]
Common issue thats been around for months when users are upgrading when a schema update is required — run `yarn` to update/upgrade packages which triggers `keystone-next postinstall`, which fails because there is an underlying schema update and it doesn’t know how to deal with it, running `keystone-next postinstall` triggers the update (only occurs if there are package updates, not if already `success Already up-to-date` with `yarn`).

Video showing 2x `yarn` for clarity, then `keystone-next postinstall`, then 2x `yarn` again to get to a clean state:

https://user-images.githubusercontent.com/737821/140628906-69982af6-579f-462c-87cb-967d03022d38.mov

**Comment by mitchellhamilton** [comment]
This isn't really an issue we can solve. This user is presumably using yarn workspaces and it doesn't look like yarn will show the output of postinstall when it isn't from the root of the repo.
