### ISSUE TITLE
Move from jest to @playwright/test for admin UI integration tests

### ISSUE THREAD

**Issue by gwyneplaine** [keystonejs/keystone#6930]
At the moment integration tests and smoke tests are failing in CI non-deterministically at an unacceptable rate. 
The working short term solution is to apply `async-retry` to these tests to reduce the probability of failure, however the likely best response is to migrate to the @playwright/test test-runner which handles retries for these classes of errors natively.

**Comment by dcousens** [comment]
@gwyneplaine these test failures started appearing en-mass with the bump to nextjs-12.   I think establishing the underlying reason why they are failing will be more useful than migrating test frameworks;  to ensure that switching is not a wasted effort.

**Comment by gwyneplaine** [comment]
> @gwyneplaine these test failures started appearing en-mass with the bump to nextjs-12. I think establishing the underlying reason with a barebones reproduction will be more useful than migrating test frameworks; to ensure that switching is not a wasted effort.

yep, that's reasonable, let's talk about this when you're in, I'd like to pair on what that minimal viable reproduction could look like, since this is quite the annoying heisenbug

**Comment by aaronpowell** [comment]
If this is still something on your radar, I'm happy to reach out to the Playwright team to see if they can offer any advice on migration.
