### ISSUE TITLE
examples/blog instructions arent working

### ISSUE THREAD

**Issue by gregpalaci** [keystonejs/keystone#6963]
Follow https://github.com/keystonejs/keystone/tree/main/examples/blog

yarn; yarn dev

to work

![Screenshot from 2021-11-17 15-00-26](https://user-images.githubusercontent.com/1177690/142273622-0d79ddad-aabc-4174-ab22-82d82832046e.png)

node 14

**Comment by thekarinka** [comment]
Still does not work for me :/
