### ISSUE TITLE
BUG: crashes when deleting item on admin overview page with more than 50 items

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#699]
If there's a list with more than 50 items (i.e. they don't all fit on the item list overview screen in the admin UI) then keystone crashes whenever you try to delete an item using the garbage bin on the all but the last "page" of the overview. 

Everything works perfect if you click on the item and use the "delete"-button on the item editor screen however.

Overview:

![item overview](https://www.evernote.com/shard/s59/sh/f32794fb-5a13-4694-bd0f-a9e0ae70628e/e079ea3e62f596802492c8b78d224f44/res/5b3498e2-61d7-4d92-b105-6a61e1a174ff/skitch.png)

Error:

![Error](https://www.evernote.com/shard/s59/sh/f00ddd5a-e6ac-4e48-b2a7-38e4c1c2aaa9/b65ae794f9a60ddd9daf249dc25852c3/res/9912af69-a9ad-46fb-ba9e-0ce8cfbd64ea/skitch.png)

And console output:

![Console output](https://www.evernote.com/shard/s59/sh/a5dd6fc4-7541-4518-8a58-100dc0267c38/1dc6fee5740757a8865cfa6305e84bb7/res/b9a3cbe6-85ed-44e0-96b9-b7f18d60ad52/skitch.png)

**Comment by sebmck** [comment]
Can't replicate this issue, it's most likely been fixed. Feel free to reopen or create a new issue if this is still a problem.
