### ISSUE TITLE
Dark-theme presentation issues on branding portal

### ISSUE THREAD

**Issue by raveling** [keystonejs/keystone#6999]
The "download assets" element on https://keystonejs.com/branding looks great in light-theme, but is not legible when the theme is set to dark.

![CleanShot 2021-11-26 at 09 16 39](https://user-images.githubusercontent.com/6447754/143504176-b205131e-cf6b-44bd-bb05-9a5c4dcceeab.png)
![CleanShot 2021-11-26 at 09 16 45](https://user-images.githubusercontent.com/6447754/143504178-e9acf943-e08b-4b51-aa1d-d7747343d87f.png)

**Comment by JedWatson** [comment]
Fixed by #7002
