### ISSUE TITLE
Dark mode issue with the announcement banner

### ISSUE THREAD

**Issue by banuragprdxn** [keystonejs/keystone#7035]
Visit the website and see the announcement banner. It appears fine on light mode however it doesn't work as expected when the user switches to or is in dark mode.

This is how it looks on light mode
![image](https://user-images.githubusercontent.com/26105313/144218364-80ff2fbb-f292-4ef6-9615-83d07c04e4c4.png)

And this is how it looks on dark mode
![image](https://user-images.githubusercontent.com/26105313/144218300-c51f5539-e69b-4288-9487-56257fe8229e.png)

I'm checking this on Windows 11 Google Chrome Version 96.0.4664.45 (Official Build) (64-bit).

This seems related (and could use similar fix) as #6999

**Comment by JedWatson** [comment]
Thanks for picking that up! You were right about the fix, I've just opened a PR 👍

**Comment by banuragprdxn** [comment]
Thank you for the quick fix and kudos on the v6 release! 🔥
