### ISSUE TITLE
Postinstall does not respect package manager

### ISSUE THREAD

**Issue by sladg** [keystonejs/keystone#7066]
Steps to reproduce:
- create new project,
- use `pnpm install`,
- postinstall script will run with npm generating `package-lock.json` and messing up versions (prisma binaries).

I'm not able to get `pnpm` working as I'm either facing problem with npm vs pnpm or Prisma binaries / schema not getting generated properly in case I ignore postinstall hooks.

<img width="1440" alt="Screenshot 2021-12-09 at 20 50 55" src="https://user-images.githubusercontent.com/26263265/145465995-d6a95e48-a13c-467c-ad3d-ac3b6506eeb0.png">

Would be super useful to have guide for manual post installs steps so in case of any issues, we can run those manually instead of relying on `keystone postinstall`.

**Comment by bladey** [comment]
Hi @sladg,

Thanks for the report, I'll investigate this with the team.

**Comment by dcousens** [comment]
I cannot reproduce.
My steps

```bash
mkdir issue-7066
cd issue-7066/
pnpm init
pnpm install @keystone-6/core
vim keystone.ts
```

```typescript
import { config } from '@keystone-6/core'

export default config({
  db: {
    provider: 'sqlite',
    url: 'file:./keystone-example.db',
  },
  lists: {},
})
```

```bash
$ pnpm keystone dev
as keystone > /usr/bin/pnpm keystone dev
✨ Starting Keystone
```

Happy to re-open if anyone can reproduce and comment with steps
