### ISSUE TITLE
Keystone build gets stuck

### ISSUE THREAD

**Issue by Thiggel** [keystonejs/keystone#7071]
I tried building my keystone app for production, but the build script got stuck.

### Steps to reproduce:

`$ yarn build`

### Results

I expected the script to run through successfully, but it just started hanging forever at the following point:

```
λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
```

I use node version `16.13.1`. These are my dependencies:
```
{
  "name": "keystone-app",
  "version": "3.0.0",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development DISABLE_LOGGING=true nodemon --exec keystone-next dev --ext 'ts,js,json'",
    "start": "keystone-next start",
    "build": "keystone-next build",
    "postinstall": "keystone-next postinstall"
  },
  "dependencies": {
    "@keystone-next/auth": "^32.0.0",
    "@keystone-next/fields-document": "^9.0.0",
    "@keystone-next/keystone": "^25.0.3",
    "@mailchimp/mailchimp_transactional": "^1.0.46",
    "cross-env": "^7.0.3",
    "dotenv": "^10.0.0",
    "fs-extra": "^10.0.0",
    "handlebars": "^4.7.7",
    "nodemailer": "^6.7.2",
    "nodemon": "^2.0.15",
    "typescript": "^4.4.3"
  }
}
```

**Comment by bladey** [comment]
Hey @Thiggel!

I can't reproduce this with the details you've provided, could you please provide further details such as your `keystone.ts` file?

**Comment by bladey** [comment]
@Thiggel are you using a custom logo? - https://github.com/keystonejs/keystone/issues/7086

**Comment by Thiggel** [comment]
Hey @bladey, yeah I figured that I was using a custom logo, but for me it also didn't work changing the extension to .jpg or others, just including the Image React component already let the build script hang forever. I ended up removing the custom logo.

**Comment by bladey** [comment]
Thanks @Thiggel, we'll get this resolved as soon as possible.

**Comment by gideonmaina** [comment]
Hello. Any resolution to this that does not involve logos?
My build is stuck at  `(Static)  automatically rendered as static HTML (uses no initial props)`. The only change done is updating the `schema.ts` file. 

P.S. running the app via **dev** script works fine.

**Comment by linus-ha** [comment]
Hi @gideonmaina. I'm having the same problem currently. There was already a new issue created  #8760

**Comment by dcousens** [comment]
Reported upstream https://github.com/vercel/next.js/issues/54494

**Comment by johiny** [comment]
> For me it worked by providing this in `package.json` (using yarn)
> 
> ```json
> "resolutions": {
>     "@keystone-6/core/next": "13.4.12"
> }
> ```

thanks man you save my hours

**Comment by Jeet345** [comment]
> For me it worked by providing this in `package.json` (using yarn)
> 
> ```json
> "resolutions": {
>     "@keystone-6/core/next": "13.4.12"
> }
> ```

FOR NPM USE THIS: 
`"overrides": {
    "next": "13.4.12"
  },`
