### ISSUE TITLE
New field: twitter

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#71]
It would be great to have a twitter field that could equalise input of twitter usernames (whether the user inputs a @ at the start, a full twitter url, or just the username) and expose functions for generating each of the three variations.

**Comment by sebmck** [comment]
@JedWatson Probably best to close this until it's either requested or after the React version has been released and we can spend time developing additional field types, what are your thoughts?

**Comment by AmayAgrawal** [comment]
Can u please elaborate on this point a little bit or explain with example

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!
