### ISSUE TITLE
GraphQL nullability is different than `isRequired`

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#710]
# Everything is `null`able

Issue #699 highlights a great example where fields can return a value of `null` based on filters the query may impose on that field.

This holds true even when `isRequired` is set on that field.

... We need to document this.

**Comment by MadeByMike** [comment]
@jesstelford this one is a little un-clear to me. Is it possible to add some more information so that I or someone outside the core team could action this issue?

**Comment by molomby** [comment]
I think @jesstelford means.. _if we add `where` arguments to all field types then, depending on the query, any field can have a null value_.

I'd agree that, usually, everything is `null`able but for different reasons -- enabling the `isRequired` option doesn't say anything about existing data. It just means you can't specify a `null` value for creates and updates.

**Comment by jesstelford** [comment]
Great clarification @molomby, thanks 👍

@MadeByMike we need docs _somewhere_ that point out all queries for all fields have the potential to return `null`, and users should handle that case correctly. Additionally, we should document that adding `isRequired` only has an impact on the validation done during a create or update mutation, but makes no guarantees about the value returned from the API.
