### ISSUE TITLE
Typescript does not allow `resolveInput` field hook to return `undefined`

### ISSUE THREAD

**Issue by nderkim** [keystonejs/keystone#7105]
### Steps to reproduce

On `keystone-6 1.0.0`

![Screen Shot 2021-12-21 at 1 18 19 pm](https://user-images.githubusercontent.com/44968616/146859679-962ebdb8-97be-40c6-be44-4b5b9818af34.png)

but if I return `null` instead of `undefined` and then run a mutation where `author` is _not_ changed, I get:

```
PrismaClientValidationError: 
Invalid `prisma.article.update()` invocation:

{
  where: {
    id: 'ckxfcvj9y2718kc8843815tmo'
  },
  data: {
    ...
    author: null,
            ~~~~
    ...
  }
}

Argument author for data.author must not be null. Please use undefined instead.
```

### Expected result
Allow `resolveInput` field hook to return `undefined`

**Comment by dcousens** [comment]
Fixed in https://github.com/keystonejs/keystone/pull/7111
