### ISSUE TITLE
List items Created/Updated display in Admin UI

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#713]
This may be a subjective thing but to me the Created/Updated display when showing list items in the Admin UI looks too much of an attention-getter with its current style.  Perhaps consider updating style class .item-details-meta as follows:

    .item-details-meta {
         /* background-color: #fafafa; */
         /* border-left: 4px solid #eaeaea; */
         color: #aaa;
         /* padding: 6px 10px; */
    }

If it doesn't fly with others you may close the issue :-)

**Comment by JedWatson** [comment]
Has changed considerably in 0.4, let's open a new issue to discuss that design if we think we need to once it is nearly ready for release.
