### ISSUE TITLE
session-store-redis package breaks with now officially updated redis@4 

### ISSUE THREAD

**Issue by PhilBookst** [keystonejs/keystone#7131]
"npm install redis" now installs redis@4 which includes breaking changes like type definitions and method names.
The package @keystone6/session-store-redis uses redis@3 and breaks when installing redis@4 with the following error:

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received undefined

Error happened on node v14.18

**Comment by bladey** [comment]
Thanks for reporting this @PhilBookst.

**Comment by dcousens** [comment]
Fixed in #7051,  see that for progress
