### ISSUE TITLE
Document field has vague GraphQL type

### ISSUE THREAD

**Issue by WillSquire** [keystonejs/keystone#7151]
Creating a dynamic page from a `document` loses all typing. Querying `document(hydrateRelationships: true)` just returns JSON, rather than strict types. In strapi, this keeps the types and I would do `...on ComponentHero { ... }` to return them. Keeping strict types means I can use types on the front end from GraphQL and don't have to write them/keep them in sync manually.

Even types that exist for other API calls, i.e. when using'fields.relationship`, are lost as JSON.

**Comment by dcousens** [comment]
Maybe a question, or a feature request, but not an issue (which we reserve for faults or bugs).
Maybe related
- https://github.com/keystonejs/keystone/discussions/8905
