### ISSUE TITLE
Mongo queries can fail when filtering on to-many relationship fields

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#718]
In particular, when adding a field to an existing database, and existing records _do not have that field_, you will end up with:

```
$in requires an array as a second argument, found: missing
```

For a concrete example, see [this SO question](https://stackoverflow.com/questions/51642472/in-requires-an-array-as-a-second-argument-found-missing).

## Example

For example, start with these lists:

```javascript
keystone.createList('User', {
  fields: {
    name: { type: String }
  },
});
keystone.createList('Event', {
  fields: {
    title: { type: String },
  }
});
```

Fire up KS5, and insert some data.

Now, modify the lists like so:

```diff
 keystone.createList('User', {
   fields: {
     name: { type: String }
   },
 });
 keystone.createList('Event', {
   fields: {
     title: { type: String },
+    owners: { type: Relationship, many: true },
   }
 });
```

Immediately try to run the following query:

```graphql
query {
  allEvents(where: { owners_some: { name_contains: "foo" } }) {
    id
  }
}
```

Then you'll get the above error:

```
$in requires an array as a second argument, found: missing
```

## Investigation

When doing a relationship lookup, we join on the tables like so (note: This is not a complete query):

```json
{
    "aggregate": "events",
    "pipeline": [{
      "$lookup": {
        "from": "users",
        "as": "cjs42bc8k001n6tpf876ajuwl_owners",
        "let": {
          "cjs42bc8k001n6tpf876ajuwl_owners_ids": "$owners"
        },
        "pipeline": [{
          "$match": {
            "$expr": {
              "$in": ["$_id", "$$cjs42bc8k001n6tpf876ajuwl_owners_ids"]
            }
          }
        }
      }
    }
  }
```

The `$in` operator is trying to match the list of IDs stored in the `events.owners` field to the `users.id` field. But, there is no `owners` field on existing `events` records. So, come `$in` time, Mongo will error out.

This is roughly equivalent to this in JS:

```javascript
const record = {};
record.owners.includes('abc123');
```

## Workaround

Add a `owners: []` field to all existing records before trying to run the query:

```javascript
db.events.update(
  // Filter by items that don't have the given array
  { owners: { $exists: false }},
  // Insert that array
  { $set: { owners: [] }},
  // Don't stop at the first item
  { multi: true }
);
```

**Comment by timleslie** [comment]
Fixed in #1838 and #1844
