### ISSUE TITLE
Improve support for isRequired on Relationships

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#719]
Due to the use of back-references, the `isRequired` flag is tricky to enforce for Relationship fields. At the moment I don't believe it's adequately implemented. This tasks needs someone to go through the Relationship field and ensure that the `isRequired` semantics are correctly implemented across all use cases.

**Comment by jesstelford** [comment]
Just got stung by this:

```javascript
keystone.createList('User', {
  fields: {
    name: { type: Text },
  },
});

keystone.createList('Post', {
  fields: {
    author: {
      type: Relationship,
      ref: 'User',
      isRequired: true,
    }
  }
});
```

The `isRequired` check appears to do nothing:

```graphql
mutation createPost {
  createPost(data:{}) {
    id
    author {
      id
    }
  }
}
```

Successfully creates a new item.

---

I think the most basic implementation should at least:

1. Set the field as required in the graphQL schema. (currently it's just `input PostCreateInput { author: UserRelateToOneInput }`)
2. Check for at least one of the possible operations (`create` / `connect` / `disconnect` / `disconnectAll`) having any value.

**Comment by MadeByMike** [comment]
We should update the docs until this is resolved.

**Comment by christopherliu** [comment]
Hello! It looks like isRequired is not supported on relationships in [Keystone v6](https://keystonejs.com/docs/apis/fields#relationship) as well as v5. Is this the proper channel to hear updates on this, given that the issue is closed, or should I open a new feature request issue?

**Comment by dcousens** [comment]
Hi @christopherliu,  there is an open feature request / question around this https://github.com/keystonejs/keystone/discussions/7310,  we'll endeavour to try and answer with our reasoning for why `isRequired` is missing soon
