### ISSUE TITLE
Can you add any example for option "dependsOn"

### ISSUE THREAD

**Issue by superpan3000** [keystonejs/keystone#719]
I have a model below

    var User = new keystone.List('User')
    User.add({
        email: { type: Types.Email, initial: true, required: true, index: true },
        country: { type: Types.Select, options: ['usa', 'thailand', 'vietnam'], emptyOption: false},
        city: { depends on country field but how to fill here?!!! }
    })

I see you supported the dependsOn option in document page

    dependsOn Object	The field will only be displayed when the paths specified in the object match the current data for the item

But don't see any example for this? Can you help me? Thanks :)

**Comment by sokki** [comment]
+1 for the ability to pass a function to dependsOn (and maybe other things like options)

In my case, I need to hide a field depending on a fieldvalue of a document that is linked by a relation ...

**Comment by jossmac** [comment]
@superpan3000 the depends on argument also accepts an `array`, so I recommend the following setup:

```js
var countryOptions = ['usa', 'thailand', 'vietnam'];
User.add({
    email: { type: Types.Email, initial: true, required: true, index: true },
    country: { type: Types.Select, options: countryOptions, emptyOption: false},
    city: { type: String, dependsOn: { country: countryOptions } }
});
```

That being said, `dependsOn` could really benefit from a function that must return a `boolean` value

**Comment by manuelxaguilar** [comment]
Yes, what @superpan3000 said. 

Did you figure out how to do this?

**Comment by mxstbr** [comment]
Moved to `keystonejs-site`: https://github.com/keystonejs/keystonejs-site/issues/87
