### ISSUE TITLE
RegExp check in validations for text fails on valid/safe strings

### ISSUE THREAD

**Issue by usmanity** [keystonejs/keystone#7193]
One my `username` field for users, I want to validate the username before saving but I am getting intermittent failures with seemingly safe / valid strings like `usmanity` or `usmanity2`. When I was testing, I would create a username in the same pattern e.g. `username1` and `username2`, the only difference being the number to make sure I'm not introducing any variance past that. 
In one run, did not matter if it was my first or tenth attempt, it would just save the username and everything was good to go and in another run whether it was my first or fifth attempt, it would fail while validating. 

The following is my field and its validation:
```
      username: text({
        validation: {
          isRequired: true,
          length: {
            min: 3,
            max: 32,
          },
          match: {
            regex: RegExp(/^[a-zA-Z0-9_\-\.]+$/, "g"),
            explanation:
              "Username can only include alphanumeric characters, dashes, underscores, and dots but no spaces",
          },
        },
```

A user should be able to sign up with a valid username like `example_foo` or `example123` and fail only when they use something like `example!` or `foo example`. 

I'm using Keystone.js `@keystone-6/core@^1.0.1`

**Comment by kennedybaird** [comment]
I can report having continued issues with the built-in regex matching (glad I searched so I can stop driving myself insane).

Mine is very simple, 17-19 number identifier.

Works sometimes, other times doesn't allow it - as in, I can try clicking save multiple times and it may end up working.

```js

  match: {
    regex: /([0-9]{17,19})/g,
    explanation: 'That does not seem to be a valid numerical identifier',
 }
 ```

**Comment by AhmedBG** [comment]
I have the same problem as @kennedybaird,

The only to make it work, is to write something in the input, clear everything inside then retype your text. That way it passes but I always have the explanation under the input 🤷🏼 

Also using `1.0.1`

**Comment by AhmedBG** [comment]
@kennedybaird @usmanity 

The problem was the flag `g` in the regEx, removing it will solve the problem.

Why? the problem is explained [here](https://stackoverflow.com/questions/71641710/multiple-regex-not-working-with-conditions) knowing that the regEx.test is directly in the condition in [this line of code](https://github.com/keystonejs/keystone/blob/main/packages/core/src/fields/types/text/index.ts#L117)

**Comment by usmanity** [comment]
@AhmedBG Great catch, thanks for the helpful solution.
