### ISSUE TITLE
Unable to Query items with empty relationship field value using GraphQL API

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#7212]
I can't find a way to query List items with empty relationship field value via GraphQL or even with Keystone Query API.

Eg from `examples/blog` -  query posts where `Post.author` is empty, or authors with `Author.posts` is empty.

In former API there was `author_is_null` field, but in current API I can't find alternative to it.

In Prisma API it's possible for one relationship:
```js
await context.prisma.post.findMany({
  where: {
    author: {
      is: null,
    },
  },
})
```
and for multiple:
```js
await context.prisma.author.findMany({
  where: {
    posts: {
      none: {},
    },
  },
})
```

So, please implement some way to query this using Keystone's Query API and GraphQL API.

**Comment by mitchellhamilton** [comment]
For a to-one relationship, you can do this:

```graphql
query {
  posts(where: { author: null }) {
    id
  }
}
```

For a to-many relationship, the syntax is the same as you showed with prisma, you can do this:

```graphql
query {
  authors(where: { posts: { none: {} } }) {
    id
  }
}
```
