### ISSUE TITLE
`getPrismaModelForList` / `runWithPrisma` functions is not importable in recent Keystone versions

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#7228]
Sometimes we need to run some direct prisma queries on Lists, having a Keystone's List name. 
But because of [this prisma issue](https://github.com/prisma/prisma/issues/11260) we can't easily do this.

So, in younger versions of Keystone-6 there was a function `getPrismaModelForList`, but in recent versions it is reworked to `runWithPrisma`.

And the problem is that it is not exported to compiled version Keystone, so we can't import it into Keystone-based projects to reuse.

Can you please make the `function runWithPrisma()` importable, or provide any other solution to get Prisma Model from Keystone List name?

Alternative solution can be adding function to Keystone DB API (or Query API?), something like `context.db.User.getPrismaClient()`

**Comment by MurzNN** [comment]
Workaround is to create in each project a custom ugly function like this:
```js
export function listNameToPrismaModel(listKey: string) {
  return listKey.toLowerCase() + listKey.slice(1);
}
```
But much better to import a same ugly function from Keystone Core ;-P

**Comment by dcousens** [comment]
@MurzNN if you still need this, could you open a feature request GitHub discussion?
