### ISSUE TITLE
Missing license SPDX for @keystone-6/document-renderer & @keystone-6/fields-document

### ISSUE THREAD

**Issue by alex-boutin-ingeno** [keystonejs/keystone#7230]
@keystone-6/auth and @keystone-6/core 
mention the MIT license in `package.json` but it is not mentioned in @keystone-6/document-renderer and @keystone-6/fields-document. I believe it should be included for consistency.

**Comment by bladey** [comment]
Thanks @alex-boutin-ingeno, I'll run this by the team.

**Comment by dcousens** [comment]
Conceptually,  we'd want the license at the root to be distributed automatically,  but short of over-complicating the publish process,  I think we'll simply add the `LICENSE` to each sub package.

**Comment by raveling** [comment]
https://github.com/keystonejs/keystone/pull/7244

**Comment by dcousens** [comment]
Resolved in #7244
