### ISSUE TITLE
Lack of information in the official documentation

### ISSUE THREAD

**Issue by noor-codes** [keystonejs/keystone#7243]
### In the documentation
- The maximum and minimum values for a float and decimal value are mentioned but never specified. Need to know what is the minimum and maximum value needed for these fields.

![image](https://user-images.githubusercontent.com/28804764/151695997-4cde4944-949c-41cd-8214-650222c742e2.png)

- ### For Integer we have the right information.

![image](https://user-images.githubusercontent.com/28804764/151696095-ffc7b3b1-acbf-4f7e-b1cf-439548a465ea.png)

Link to the Issue in the docs: 

1. https://keystonejs.com/docs/apis/fields#float
2. https://keystonejs.com/docs/apis/fields#decimal

I would have made a pull request to fix the issue but I don't have the right information. Hope this helps get things better. 

Thanks

**Comment by bladey** [comment]
Thanks @noor-codes, I'll run this by the team and get back to you.

**Comment by dcousens** [comment]
Hi @noor-codes,

What `default` would you expect for float and decimal?

**Comment by noor-codes** [comment]
I think I have the wrong mental modal here. 

Is the default value a limit of the database or just a way to show how validations work? I'm very confused.

**Comment by dcousens** [comment]
The default values represent validation the minimum and maximum values that are accepted by Keystone; [checked in Javascript.](https://github.com/keystonejs/keystone/blob/main/packages/core/src/fields/types/integer/index.ts#L87-L96)

The `validation.` limits are not applied by database constraints.

**Comment by noor-codes** [comment]
That makes sense now. 

What about the float and decimal values. What is the maximum and minimum value accepted by Keystone?

**Comment by noor-codes** [comment]
Anyway, I got the main answer I was looking for. Closing this issue now.
