### ISSUE TITLE
Would be great to have lib/updates.js refactored into a separate library

### ISSUE THREAD

**Issue by domharrington** [keystonejs/keystone#725]
I would like to use the database update handler functionality in a project that is not using keystone. Have you considered refactoring it out into a separate library? Would you accept a pull request using a refactored out version?

**Comment by morenoh149** [comment]
stale

**Comment by morenoh149** [comment]
@webteckie sorry didn't know it was a good idea. Closed mostly for not getting a response.

**Comment by domharrington** [comment]
Apologies on the lack of response. I was going to pick this up much sooner than now but due to the christmas holidays i didnt have as much free time as I would have liked.

I'm glad you think it's a good idea and I hope to still build a solution for this, but if someone else has more time than I that would be great too.

Thanks

**Comment by webteckie** [comment]
I may be able to collaborate on this as well.  @JedWatson can you please setup the repo for this under keystonejs and allow @domharrington and I access?  Not too sure of the logistics of this in github as I mainly work in BitBucket.  But I'll submit a PR soon to improve on the work I submitted via PR #870.

**Comment by domharrington** [comment]
I've just tackled this problem and released a module:
https://www.npmjs.com/package/database-updates

It is not totally compatible (I dropped .coffee file support) but if you're interested on incorporating this into keystone, I can re-add that and do the integration. Let me know

**Comment by webteckie** [comment]
@domharrington interesting you really did do a standalone db updates :-)  It wasn't too clear by quickly skimming the code...is it compatible with keystone's createItems?  If not, how would people that currently use createItems use your module?  Not sure what the .coffee file support you talk about is.

**Comment by domharrington** [comment]
@webteckie i'm not actually too familiar with the `createItems` functionality. Is it documented anywhere? Or maybe you can briefly explain?

The .coffee support i'm referring to is here: https://github.com/keystonejs/keystone/blob/master/lib/updates.js#L137

**Comment by mxstbr** [comment]
I'll close this for now since we're revamping the UpdateHandler at the moment.
