### ISSUE TITLE
startup - async config

### ISSUE THREAD

**Issue by pazams** [keystonejs/keystone#7274]
### Discussed in https://github.com/keystonejs/keystone/discussions/7273

<div type='discussions-op-text'>

<sup>Originally posted by **pazams** February  7, 2022</sup>
`keystone.ts` interface is a default export of `KeystoneConfig`.
However, let's consider that some of the values in `KeystoneConfig` (e.g. db.url) needs to be fetched from a remote secret storage service. How should this type of async call work considering the interface for `keystone.ts` is a synchronous export of `KeystoneConfig`?</div>

**Comment by dcousens** [comment]
See #7273 instead, this is not a bug
