### ISSUE TITLE
Suggest blocks to add within the Content editor

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#728]
When using the Content Editor, there may be specific things that can make the content "better".

As an example; If writing an article, and the user types "video", we could prompt to suggest "Add a video to your post?" which when clicked opens the "Add Video" block immediately below the paragraph where "video" was detected.

This would need to be configurable somehow from the Keystone side.

NOTE: This is _not_ templates.

**Comment by ralexrdz** [comment]
I would love to have a LocalImage block that stores the Image as the File Type does, instead of adding it as data:image inside the mongoose document. I'm gettin a `PayloadTooLargeError: request entity too large` when images are larger than 70kb
