### ISSUE TITLE
Broken Link in the Docs

### ISSUE THREAD

**Issue by noor-codes** [keystonejs/keystone#7281]
## Broken Link in the Docs

Link to the url in the docs (Keystone-v6) => https://keystonejs.com/docs/guides/custom-fields

![image](https://user-images.githubusercontent.com/28804764/153812159-c55882d5-5a6f-4bb2-9017-97d20b71207c.png)

**Comment by noor-codes** [comment]
I just tried to fix this issue with a pull request but the link in the looks good to me.https://github.com/keystonejs/keystone/blob/974d7aa014a0c590f9cf978fd974217f768acd1d/docs/pages/docs/guides/custom-fields.mdx#L20

![image](https://user-images.githubusercontent.com/28804764/153820383-73898ef4-1112-41f8-9a35-9cdd02df0c35.png)



### Maybe this page needs to be rebuild. The files will recompile and the issue will be resolved. 
I searched a lot to get here.

**Comment by dcousens** [comment]
This was resolved in 974d7aa014

**Comment by noor-codes** [comment]
Awesome
