### ISSUE TITLE
Preparing Admin UI app

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#7311]
I tried many times to build or run my app but failed to build, and there is not yarn error log.

`yarn dev`

or

`yarn build`

It stucked forever without return

![image](https://user-images.githubusercontent.com/7088330/156053949-083f7fc1-7559-4d91-9d1f-4acad505e803.png)

![image](https://user-images.githubusercontent.com/7088330/156054241-f6a2855c-6d75-4283-8668-61251ce779e4.png)

`node -v >v14.19.0`
package.json
```
    "@keystone-6/auth": "1.0.2",
    "@keystone-6/core": "1.0.1",
```

**Comment by dcousens** [comment]
Hi @arthurtalkgoal ,  we can't reproduce this without additional information.
Happy for you to re-open the issue if you can provide us steps with how to reproduce.
