### ISSUE TITLE
Install Fails: 🚨 There was an error loading your Keystone config

### ISSUE THREAD

**Issue by ScottAgirs** [keystonejs/keystone#7316]
1. `yarn create keystone-app`
2. cd into new `keystone-app`
3. `yarn dev`

After running the above steps I get the below error.

```bash
🚨 There was an error loading your Keystone config
Error: Cannot find module '/Users/scottagirs/ks-app/.keystone/admin/.next/server/pages/api/__keystone_api_build'
```

<img width="1368" alt="Screen Shot 2022-03-02 at 11 13 06 AM" src="https://user-images.githubusercontent.com/11737572/156336259-88000b31-4dcb-4bc9-9d9b-ee30d86b90ef.png">
<img width="355" alt="Screen Shot 2022-03-02 at 11 19 31 AM" src="https://user-images.githubusercontent.com/11737572/156336276-931ad6bc-df14-42e6-b0b8-c40ee184a2c8.png">

Suddenly my Keystone install started failing in one of my projects.

Another works fine even after removing `node_modules` and `.keystone` and re-installing.

I have also:
- tried spinning up a new project with `yarn create keystone-app`. This fails too.
- tried manually changing the Keystone package versions after running `yarn create keystone-app` to `1.0.0`.
- tried using  `npm`, `pnpm` instead of `yarn`. 

None of the above solves the issue.

**Comment by ScottAgirs** [comment]
## `package.json` of the fresh app

```json
{
  "name": "keystone-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall"
  },
  "dependencies": {
    "@keystone-6/auth": "^1.0.0",
    "@keystone-6/core": "^1.0.0",
    "@keystone-6/fields-document": "^1.0.0",
    "@prisma/client": "3.6.0",
    "typescript": "^4.5.4"
  },
  "engines": {
    "node": "^14.15 || ^16.13"
  },
  "devDependencies": {
    "prisma": "3.6.0"
  }
}

```

### also tried:

```json
{
  "name": "keystone-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall"
  },
  "dependencies": {
    "@keystone-6/auth": "^1.0.1",
    "@keystone-6/core": "^1.0.1",
    "@keystone-6/fields-document": "^1.0.1",
    "@prisma/client": "3.6.0",
    "typescript": "^4.5.4"
  },
  "engines": {
    "node": "^14.15 || ^16.13"
  },
  "devDependencies": {
    "prisma": "3.6.0"
  }
}

```

**Comment by ScottAgirs** [comment]
## **Update**

It seems that this error is not blocking.

While it persists in the console logs in development, in production it is not present.

Additionally, even though the error is present, it is not blocking the application from being functional.

If the application is not working, this may be a result of another dependency, for example, on the frontend as it was in my case.

I will update this issue if I find the cause of this error.

**Comment by ScottAgirs** [comment]
# Here is how I fixed this:

1. Clean all yarn caches (you can start by running `yarn cache clean`
2. Deleted the `.keystone` and `node_modules` folders
3. Restarted my Mac
4. Reinstalled all.

**Comment by simonmaris** [comment]
fyi, the same just happened to me and it was because I had something else running on the same port. 🙈
So not a very descriptive error message but there you go :)
