### ISSUE TITLE
Authentication failed with `create keystone-app`

### ISSUE THREAD

**Issue by moritzgvt** [keystonejs/keystone#7317]
## Reproduce

- Do the basic installation:

```
npm init keystone-app

cd my-app

npm run dev
```

- Create user
- Logout
- Try to log back in with the created user

## Expected
- Login works

## Actually
- Authentication failure

![Screenshot 2022-03-02 at 17 14 10](https://user-images.githubusercontent.com/39989672/156413241-bb623358-335d-4089-90bd-a2d92870936d.png)

There are some JS errors in the console:
![Screenshot 2022-03-02 at 17 14 39](https://user-images.githubusercontent.com/39989672/156413255-b5b02e06-de54-473f-a0c0-458ca9a63701.png)

Happens in all major Browsers.
node v14.18.1
npm v8.4.1

**Comment by Tangcuyu** [comment]
I got same error message with basic installation.

yarn create keystone-app
cd my-app
yarn dev

![image](https://user-images.githubusercontent.com/10055945/159400155-a007d1d3-47a2-4b09-81aa-0d4cea5bbe08.png)

node v16.13.0
Any idea?

Thanks

**Comment by dcousens** [comment]
Cannot reproduce this, but I'm wondering if this is somewhat similar to https://github.com/keystonejs/keystone/discussions/7915#discussioncomment-3688919 - @moritzgvt what credentials are you providing in the first screen?

**Comment by dcousens** [comment]
Cannot reproduce this, but I'm wondering if this is somewhat similar to https://github.com/keystonejs/keystone/discussions/7915#discussioncomment-3696037

@moritzgvt, @Tangcuyu can you try the `/init` process using the credentials name `test`, email `test`, password `testtest`?
