### ISSUE TITLE
Post not related when creating a related post from a user 

### ISSUE THREAD

**Issue by leopoldkristjansson** [keystonejs/keystone#7348]
I am following the Walk-through lessons here: https://keystonejs.com/docs/walkthroughs/lesson-2

I have Posts and Users. I click on "Create Related Post" from a specific User. It creates the post and adds the post to the list of related Posts. After a refresh the post is gone.

I would expect the post to be related to the user.

Here is a screencast showing the issue.

https://user-images.githubusercontent.com/2579324/158035828-55856d0b-3603-4e90-86eb-001e979183df.mov

I am following the Walk-through lesson using npm and SQLite

**Comment by dcousens** [comment]
Hi @leopoldkristjansson,  any particular reason you decide to close this issue?  The video seems to present your problem well.

**Comment by dcousens** [comment]
Thanks for the follow up @leopoldkristjansson,  this kind of feedback where everything seems wrong at first glance is great fodder for our design team.  :pray:

**Comment by raveling** [comment]
@leopoldkristjansson thanks very much for sharing this 🙇 

You're 100% right about the UX not being great here.

We're doing a big redesign of Admin UI and this issue has been captured, so we do intend to make it better in the future. 

Hope this helps! 🙏

**Comment by leopoldkristjansson** [comment]
OK, great to know that these kind of things are being prioritized and worked on! On a general note, regarding UI/UX issues - the Github issues list is the place to add them, no?

**Comment by raveling** [comment]
> regarding UI/UX issues - the Github issues list is the place to add them, no?

Issues are good for UI/UX problems 🙏 

Feature requests go [here](https://github.com/keystonejs/keystone/discussions/new?category=feature-requests) and General Q&A is best poster [here](https://github.com/keystonejs/keystone/discussions/new?category=questions)

Hope this helps!
