### ISSUE TITLE
Keystone 6 custom field view

### ISSUE THREAD

**Issue by dongalor** [keystonejs/keystone#7349]
Tried implementing by myself, then went to examples and had the same error:

`Module not found: Can't resolve '../../fields/related-links/components'`

Tried different node versions, yarn and npm running, no result

Thank you in advance

![image](https://user-images.githubusercontent.com/42974/158048793-09439dd8-f9aa-4ff8-a426-e6806fccfa9e.png)

**Comment by dongalor** [comment]
Guys, it's pretty strange, but it seems keystone has nothing to do with my error. My friend started same example inside his environment and everything works.

**Comment by dongalor** [comment]
Guys, sorry for bothering you. Problem is solved, I've completely removed all the nvm setup and did it from scratch.

**Comment by hhimanshu** [comment]
@dongalor , did your problem solve? What did you do?

**Comment by dcousens** [comment]
Maybe related https://github.com/keystonejs/keystone/discussions/7379
