### ISSUE TITLE
 Cannot read properties of undefined (reading 'getDataFromStream')

### ISSUE THREAD

**Issue by williamhqs** [keystonejs/keystone#7384]
Hi, I just want to upload a `file` type field:

```
HardwarePackage: list({
    fields: {
      name: text({ validation: { isRequired: true } }),
      version: text({
        validation: { isRequired: true },
        isIndexed: true
      }),
      description: text({ validation: { isRequired: true } }),
      package: file(),
}
```

When upload the files then got the error as title described when press the "save" button.

<img width="1108" alt="Screen Shot 2022-03-20 at 1 58 13 AM" src="https://user-images.githubusercontent.com/354829/159132859-6330b4e9-ab9e-4a69-8156-42b1b1e4555f.png">

Thanks!

**Comment by dcousens** [comment]
Hi @williamhqs,  did you resolve your problem?

**Comment by williamhqs** [comment]
@dcousens yes, so I close it. I missed the configuration.

**Comment by RetryingOOS** [comment]
@williamhqs I have the same problem right now. How did you end up solving it?
