### ISSUE TITLE
Error: Unable to use Firmware as a List name - it has an ambiguous plural (Firmware). 

### ISSUE THREAD

**Issue by williamhqs** [keystonejs/keystone#7385]
As the title described I got:
`
Error: Unable to use Firmware as a List name - it has an ambiguous plural (Firmware). Please choose another name for your list.`

And here is my list:

```
Firmware: list({
    fields: {
      name: text({ validation: { isRequired: true } }),
    }
  }),
```

I am not sure what's wrong with the name. `Firmware`'s plural is still the same I think, but how to solve it? And I got this link in Stackoverflow https://stackoverflow.com/questions/49771957/keystonejs-plural-option-not-working-in-adminui

but seems it's V5 version solution.

Thanks!

**Comment by raveling** [comment]
@williamhqs 
Unfortunately this isn’t currently possible, but it should be. We’ve added it to our backlog for future support 🙂

**Comment by dcousens** [comment]
You can now use `graphql.plural` to provide an unambiguous plural _for only the GraphQL API_.
The addition of configuration for `ui.plural` now supports (and defaults to) [ambiguous plurals in the UI](https://github.com/keystonejs/keystone/pull/7657).
- #7657

Related to https://github.com/keystonejs/keystone/discussions/7550, see example in that discussion for help
