### ISSUE TITLE
The wysiwyg does not indicate when you enter the field 

### ISSUE THREAD

**Issue by forrestLyman** [keystonejs/keystone#739]
The cursor only appears after you start typing. The editor works perfectly well, but little things like this can be confusing for new users.

**Comment by morenoh149** [comment]
could you provide a screencap?

**Comment by morenoh149** [comment]
will be fixed by #791

**Comment by morenoh149** [comment]
the other issue was referring to something else. I'm opening this back up.

**Comment by snowkeeper** [comment]
This can be fixed by upgrading tinymce to 4.1.7.

How are those libraries managed?  @JedWatson should I submit a PR with the updated tinymce folder or do you pull those in another way?

**Comment by morenoh149** [comment]
really? I got as far as observing the input field is unusually small in the final result. That's what was causing the input field to not get focus on click.

@snowkeeper could we use the npm module? http://www.tinymce.com/wiki.php/Installation_using_package_managers if that works anything like the various other dependencies keystone already has this would be the way to go.

**Comment by morenoh149** [comment]
I've been looking into this here and there. I notice it's only an issue on chrome. And it's an issue with the input area being smaller than the square that looks like a textarea. Possible solution update version of tinymce bundled with keystone from 4.0.7 https://github.com/keystonejs/keystone/blob/e476f75dedec1cfc8eb4591939131e380bee28ad/public/js/lib/tinymce/tinymce.min.js to 4.1.8 https://github.com/tinymce/tinymce/blob/master/changelog.txt

Perhaps also change the bundling scheme. Would a git submodule be more maintainable?

**Comment by JedWatson** [comment]
I've just updated the bundled TinyMCE to 4.1.7 (last published version) and it seems to fix the issue for me. Would be nice to actually handle focus with a standard blue border on the field too, will have to check whether that event is supported in the TinyMCE API.

@morenoh149 we can't just pull a git submodule, as we have some customisations (including custom theme). We just need to update it more often :)

I really like the look of Squire, maybe in a future version we can ship that by default and allow TinyMCE as a plugin.

**Comment by JedWatson** [comment]
I've implemented the focus event now, and updated the custom theme to match the standard focus style for inputs in Keystone.
