### ISSUE TITLE
Default Filter List option

### ISSUE THREAD

**Issue by costasmicha** [keystonejs/keystone#741]
Can you add a default filter option for Lists for the admin ui ,like defaultSort and defaultColumns.

**Comment by meelis79** [comment]
any update? This is useful feature, I was surprised this feature does not exist.

**Comment by mxstbr** [comment]
This is done in 0.4!

**Comment by kadosh1000** [comment]
@mxstbr Can you please provide us a usage example of that feature?

**Comment by zewt112** [comment]
+1 Is this documented?

**Comment by ytzvan** [comment]
Is this feature documented?

**Comment by koloboid** [comment]
@mxstbr any suggestion?

**Comment by PankajGadia** [comment]
Has anyone any reference to the code sample for this or any documentation to follow?

**Comment by OliverSoop** [comment]
Correct me if I am wrong, but I would say that this is not done.

**Comment by michaek** [comment]
@mxstbr It seems this may have been closed erroneously. If it's not something Keystone wants to support, that's fine, but the status of this issue is encouraging users to expect it to be implemented, and it is not.

**Comment by michaek** [comment]
For what it's worth, this looks like it would work in Keystone 4: https://github.com/michaek/keystone/commit/108944edd9bba99e9b6c1b091615261614e35e0d I haven't looked into Keystone 5 at all.
