### ISSUE TITLE
Text fields in component blocks lose focus when updated

### ISSUE THREAD

**Issue by christopherliu** [keystonejs/keystone#7411]
**Steps to reproduce:**

1. Add a component block with a text field (simple example below)
2. Create a page that renders a document with that component block.
3. Add a renderer that binds that block to state.

Example below:
```typescript
export default function Page() {
    const [value, setValue] = useState();

    function updateContents({ target }) {
        setValue(target.value);
    }

    const componentBlockRenderers: InferRenderersForComponentBlocks<typeof componentBlocks> = {
        textField: ({ bindTo }) => {
            return <TextField key="textField" onChange={updateContents} value={value}></TextField>;
        }
    };
}
```

**Expected behavior**

Ideally, whenever someone types in TextField, state is immediately updated, so the virtual DOM remains in sync with the regular DOM and doesn't lose focus.

**Additional context**

Not sure, but this might be because Keystone generates a new Component whenever rerendering the page: https://github.com/keystonejs/keystone/blob/main/packages/document-renderer/src/index.tsx#L167

**Comment by mitchellhamilton** [comment]
The component block renderers need to be defined outside of your React component, Keystone isn't creating a new component when re-rendering the but by creating componentBlockRenderers in render, that is creating new components on every render so React is re-mounting them on every render. You can use React Context to pass information down to a component block renderer.
