### ISSUE TITLE
select shouldn't show Clear button if `validation.isRequired` is true

### ISSUE THREAD

**Issue by tv42** [keystonejs/keystone#7413]
Define a field like

```
      status: select({
        options: [
          { label: "Published", value: "published" },
          { label: "Draft", value: "draft" },
        ],
        defaultValue: "draft",
        validation: {
          isRequired: true,
        },
        ui: {
          displayMode: "segmented-control",
        },
      }),
```

Since the field is required, and has a default value, I expected the UI to show a widget that lets the user pick one of the options, but *be forced to pick one*.

Right now, user can click "Clear" and "Save changes" and get an error message "Status is required". But why let them get into that dead end, in the first place?

![image](https://user-images.githubusercontent.com/419909/161134111-a765d661-10a2-44c2-9045-9e84a6a99971.png)

**Comment by IdkMan2Usertive** [comment]
+ Upvote
