### ISSUE TITLE
Disable logging about migration logging when using `@keystone-6/core/testing`

### ISSUE THREAD

**Issue by emmatown** [keystonejs/keystone#7418]
These are unhelpful since every test wipes and sets up the db again so these messages show up a lot.

We actually already skip them when `process.env.TEST_ADAPTER` is present (which is what we happen to use in our API tests to determine) but what we happen to use in our tests should not be what makes us skip these logs, they should just never be shown when using the APIs from `@keystone-6/core/testing`.

It's especially bad with Jest since it adds a stack trace and a bunch of spacing around every log
![screenshot of keystone](https://user-images.githubusercontent.com/11481355/161173169-89db1efd-6f95-4b32-ae33-7aa38db87740.png)

**Comment by dcousens** [comment]
I don't think this is relevant in recent versions
