### ISSUE TITLE
connect-redis support

### ISSUE THREAD

**Issue by artzte** [keystonejs/keystone#742]
Am I missing something, or is the connect-redis session store option NYI? Should this option be removed from the docs until it is implemented?

/lib/core/mount.js

			case 'redis':
				// default session store for using Redis
				// TODO: Implement this option
				break;
			case 'connect-redis':
				// TODO: Implement this option
				break;

**Comment by gmmeyer** [comment]
It may be loaded by default, but that doesn't seem to indicate that the default actually does anything, which, I think, is the problem.

**Comment by morenoh149** [comment]
@gmmeyer easy one

**Comment by gmmeyer** [comment]
It is implemented, or at least it will be in a future release of 0.2.x. (I can't speak for the release schedule.)

I have one running on a hacked up version of Keystone 0.2.x that is working on both development and on production for me. The code from that hacked up version has been merged into the 0.2.x branch of the code.

So, either include the 0.2.x branch directly into your project, or wait for the next release on NPM that includes it. Enabling it is relatively simple, all you need to do is include that, include express sessions, and then set the proper environment variables for redis.

**Comment by stonean** [comment]
I have it running and it appears to be operating correctly, but I didn't include express sessions. What behavior would I see without sessions?

**Comment by morenoh149** [comment]
@stonean not sure. If you don't have sessions enabled then is the connect-redis ever used to store anything? I'm thinking not.

**Comment by gmmeyer** [comment]
Yea, it shouldn't wouldn't store anything. Try logging in and see what happens.

**Comment by stonean** [comment]
I have logged in with a 2 dyno setup on Heroku, which is why I'm super confused right now. Working off of master.

**Comment by stonean** [comment]
Looks like it is configured properly in the source:

node_modules/keystone/lib/core/mount.js

      var SessionStore = require(sessionStore)(session);

where session is `session = require('express-session')`

and sessionStore is `sessionStore = 'connect-redis';`

This was from a quick grep, so I may be pointing out some invalid code here ...

**Comment by gmmeyer** [comment]
Yea, if you're on master it should work. Express sessions [is a dependency for master](https://github.com/keystonejs/keystone/blob/master/package.json#L26).
