### ISSUE TITLE
Link popup in the document field is not showing when adding/editing a link

### ISSUE THREAD

**Issue by ducntq** [keystonejs/keystone#7427]
### How to reproduce
Code is here: https://github.com/ducntq/cms
Using: KeystoneJS 6 (1.0.1)
Nodejs version: 16.14.0
OS: Windows 10; Ubuntu 20.04
Database: Postgresql
Browser: Chrome 99.0.4844.84

### Expected behavior
Link popup will show, allow to change link on text
![image](https://user-images.githubusercontent.com/907013/161393843-aaac5443-050e-4332-adca-d28b19631343.png)

### Actual behavior
Link popup is not showing whenever I try to add/edit a link.
![image](https://user-images.githubusercontent.com/907013/161393856-99a5c52c-777c-46b6-aaf3-c51f007b5186.png)

### Logs
No logs on nodejs, no logs on Chrome.

**Comment by raveling** [comment]
@ducntq thanks for sharing this. Confirming it's a bug 🐛 

We've added it to the backlog.

Note: the link popup should work correctly if you create the item and then edit it on the item page (as opposed to the create drawer/modal that slides in from the right side of the viewport).

**Comment by mitchellhamilton** [comment]
This was fixed by #7556
