### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by jlarmstrongiv** [keystonejs/keystone#7429]
I am using Keystone in a monorepo with a few other apps, and it’s the only one that doesn’t support React 18 yet.  Unfortunately, this blocks me from upgrading as monorepos and peer dependencies essentially require the same version of React for everything.

Luckily, NextJS already supports React 18.  Unfortunately, I can’t tell what else is incompatible because I cannot see the logs from https://github.com/keystonejs/keystone/pull/7410

Anyway, I’d just like to put this on the radar.  Thanks for making KeystoneJS!  It’s been pretty fun to work with.

**Comment by dcousens** [comment]
Please follow https://github.com/keystonejs/keystone/pull/7410,  we are tracking the upgrade to React 18 in that pull request
