### ISSUE TITLE
Configure cloudinary path for wysiwyg uploads

### ISSUE THREAD

**Issue by marcusberner** [keystonejs/keystone#746]
When uploading images from the wysiwyg editor the configurations for prefix and folder are not used. All images are uploaded to the root. A solution where these configurations would apply or adding separate folder configurations for the wysiwyg editor would be helpful.

**Comment by morenoh149** [comment]
A pull request with a proposed solution is welcome

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. Moved this to ProductPains! (https://productpains.com/post/keystonejs/cloudinary-configuration-for-wysiwyg-uploads)!
