### ISSUE TITLE
 export CSV utf-8 character

### ISSUE THREAD

**Issue by gilloud** [keystonejs/keystone#748]
Related to #340 closed issue,
I confirm the encoding issue to read csv utf-8 characters.

To solve this issue we need to add BOM on csv file as this stackoverflow explain : 
https://github.com/wdavidw/node-csv/issues/84

what's the best plan ? waiting the fix in node-csv ? use the fix purposed in this issue ?

regards,

**Comment by eladvider-softangible** [comment]
@JedWatson this issue need to be reopened in version 0.3.13. The transformation from csv to babyparse  made the issue to happen again. The only way to solve it is either to add `res.end("\ufeff"  + content, 'utf-8');` or add the line `res.write(new Buffer('EFBBBF', 'hex'));` before calling res.end.

**Comment by mxstbr** [comment]
> version 0.3.13

Please update to the newest version (0.3.21), try again and let us know if this issue still exists!
