### ISSUE TITLE
Keystone crashes inside Turborepo

### ISSUE THREAD

**Issue by remainstheday** [keystonejs/keystone#7518]
Keystone fails to find dependencies while running `yarn dev`  inside a new [Turborepo](https://github.com/vercel/turborepo)  project.

## Steps to reproduce
1. Install Turborepo in a new project `npx create-turbo@latest`
2. navigate to the apps folder or wherever you plan to install Keystone `cd apps/`
3. install keystone `yarn create keystone-app`
4. navigate back to the root directory `cd ../`
5. add `.keystone/**` to `turbo.json` Pipeline:
`"pipeline": {"build": {"dependsOn": [
        "^build"
      ],
      "outputs": [
        ".next/**",
        ".keystone/admin/.next/**"
      ]}}
`

7. build project from root directory `cd ../ && yarn build`
8. observe error message from inside `./keystone`

## Expected Behavior
After running the steps above you would expect the keystone admin to be running on `http://localhost:3000` without any console errors

## Screenshot
![Screen Shot 2022-05-06 at 10 12 17 PM](https://user-images.githubusercontent.com/4063510/167235764-5c8c0c76-311e-4780-8fae-f52cb6acbf32.png)

## Versions
Node: `v16.13.1` (latest)
Keystone: `v6` (latest)
Turborepo: `1.2.8` (latest)

https://stackoverflow.com/questions/72149282/keystone-crashes-inside-turborepo

**Comment by borisno2** [comment]
HI @remainstheday,
Thanks for posting this issue. I have just been having a look at this, and it looks to be an issue with the `next` version that the `npx create-turbo@latest` is pinned to. Running this installs `next` `12.0.8` and is pinned to that version. Keystone requires at least version `12.1.0`. 

When I changed my `./apps/web/package.json` to:
```
  "dependencies": {
    "next": "^12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "ui": "*"
  },
```

The error no longer occurred.
Let us know if this helps.
Thanks!

**Comment by remainstheday** [comment]
@borisno2 This worked for me! Thank You.
