### ISSUE TITLE
Issue with populating relational items using list adapter 

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#752]
I have tried to test the twitter auth strategy (and possibly refactor little bit for a PR), but getting stuck due to https://github.com/keystonejs/keystone-5/blob/bd06ddbfd630040fed2b423ebe7157317b1e32f3/packages/core/auth/Twitter.js#L198-L202

error: `.adapter.findOne(...).populate is not a function`

found that it is executing the query before population in`onPostRead` at https://github.com/keystonejs/keystone-5/blob/bd06ddbfd630040fed2b423ebe7157317b1e32f3/packages/core/adapters/index.js#L102-L106

should this be used with `adapter.model.findOne`, but that may become the adapter specific implementation. KS4 `view.query` takes last parameter as what other list/field to be populated. is there something similar exist for adapter or is there a plan to have such option in `adapter.<query functions e.g. findOne>`?

**Comment by dcousens** [comment]
@gautamsi has this issue served its purpose?

**Comment by gautamsi** [comment]
@dcousens not yet, I do not know if this is implemented to populated related filed in the adapter methods, this was required to minimize number of queries inside any package which would have to query multiple things from adapter like the case of Login in #801 which was further refactored in #980. 
 specific line is question :

https://github.com/keystonejs/keystone-5/blob/51e7330abe22d1f3cf2d5babedcb0ce37b54b564/packages/passport-auth/lib/Passport.js#L98-L105

this could easily be done in one query when populating related field was possible. Similar capability existed in Keystone 4 with mongoose as schema plugins, not sure what plans we may have here.
