### ISSUE TITLE
Can not access GraphQL API explorer after deployment to heroku 

### ISSUE THREAD

**Issue by mattJurz** [keystonejs/keystone#7524]
I have deployed the app to Heroku using this guide [guide](https://elements.heroku.com/buttons/keystonejs/keystone-6-heroku-example)

The admin UI interface works well together with the Postgress connection. The admin can be available here: https://czyste-pragnienia-backend.herokuapp.com/

I only have an issue with accessing the GraphQL API when entering this URL https://czyste-pragnienia-backend.herokuapp.com/api/graphql I get an error  _GET query missing._

Any help appreciated

**Comment by dcousens** [comment]
Hi @mattJurz,

Did you resolve your problem?
