### ISSUE TITLE
Custom GraphQL resolvers not replacing defaults

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone#7527]
```typescript
export const extendGraphqlSchema = graphQLSchemaExtension<Context>({
  // ...
  resolvers: {
    Mutation: {
      // TODO: this isn't working, it isn't being called, nor is a Post actually deleted
      deletePost: (root, { id }, context) => {
        return context.db.Post.updateOne({
          where: { id },
          data: {
            isDeleted: true
          }
        });
      }
    },
  },
  // ...
})
```

See working example of the problem in https://github.com/keystonejs/keystone/commit/285b9485ac621406dcfe9c95fa43cf75992db4cd

**Comment by borisno2** [comment]
So this looks to be an issue with the `mergeSchema` in `@graphql-tools/schema` just [here](https://github.com/ardatan/graphql-tools/blob/f456a4ad6291019c35248cdca2e1cbdf6b7aacae/packages/schema/src/merge-schemas.ts#L27)... adding `extractedResolvers.push(config.resolvers);` to after the `for` loop pushes the custom GraphQl resolver into the array and it works.

something like this 
```javascript
for (const schema of schemas) {
        extractedTypeDefs.push(schema);
        extractedResolvers.push(utils.getResolversFromSchema(schema));
        extractedSchemaExtensions.push(merge.extractExtensionsFromSchema(schema));
    }
    extractedResolvers.push(config.resolvers);
    return makeExecutableSchema({
        parseOptions: config,
        ...config,
        typeDefs: extractedTypeDefs,
        resolvers: extractedResolvers,
        schemaExtensions: extractedSchemaExtensions,
```

Looking deeper I have found this Github issue https://github.com/ardatan/graphql-tools/issues/4367 with a PR that has been open for a month, will follow up on that PR.

**Comment by borisno2** [comment]
New PR in upstream package https://github.com/ardatan/graphql-tools/pull/4455

**Comment by borisno2** [comment]
Updated PR in upstream package https://github.com/ardatan/graphql-tools/pull/4463

**Comment by dcousens** [comment]
If we don't have a resolution,  could we drop using `graphql-tools` and write something that works for us?
