### ISSUE TITLE
keystone.sid Cookie Expiry / Secure

### ISSUE THREAD

**Issue by eknowles** [keystonejs/keystone#754]
No support for session expiry or secure only.

lib/session.js

**Comment by morenoh149** [comment]
stale

**Comment by cmosgh** [comment]
is it possbile to have it secure? or any proper way of changing it to secure ?

**Comment by creynders** [comment]
@cmosgh I think you can use `keystone.set('session options', { cookie: { secure: true }});`
Keystone uses the `express-session` module and AFAICT all `session options` are passed to it [here](https://github.com/keystonejs/keystone/blob/65fcda03f9f3e61fd83907e2b5746c398d844bbb/lib/core/mount.js#L205)
And express-session [accepts a `cookie: { secure: true }` option](https://github.com/expressjs/session#cookie-options)

**Comment by cmosgh** [comment]
thank you! @creynders

**Comment by cmosgh** [comment]
@creynders , unfortunately no csrf validation is possible after setting this. should I open a ticket for this?

**Comment by morenoh149** [comment]
@cmosgh I think you should open a ticket

**Comment by Norbz** [comment]
I encounter the same error when setting the cookie to secure:true (Keystone beta 4.0.0 rc7)
