### ISSUE TITLE
Safari logout doesnt work

### ISSUE THREAD

**Issue by MichalNemec** [keystonejs/keystone#7566]
create basic keystone and create user.
Then do logout
it just refreshes the page. Maybe it has something to do with extending user schema

logging out correctly

safari Version 15.5 (17613.2.7.1.8)

chrome works normally.

**Comment by borisno2** [comment]
Hi @MichalNemec
I am not able to replicate on the same version of Safari with the keystone `with-auth` example. Do you have a minimal keystone example where this issue exists?
Thanks,

**Comment by MichalNemec** [comment]
> Hi @MichalNemec
> I am not able to replicate on the same version of Safari with the keystone `with-auth` example. Do you have a minimal keystone example where this issue exists?
> Thanks,

Unfortunately i dont. But from testing ive done. I just could not log out, maybe macos version has to do with this? because i.e. some sessions are not stored or cookies not set on my macbook. Google chrome just worked out of the box. Lets see if there is more people with this problem, so it can be fixed.

**Comment by ClientsideDesign** [comment]
Hi @MichalNemec 

I had this issue in Chrome but not Safari weirdly. Adjusting my [session config](https://keystonejs.com/docs/apis/session#stateless-vs-stored-sessions) seemed to fix the problem:

    let sessionMaxAge = 60 * 60 * 24 * 30; // 30 days
    const session = statelessSessions({
        maxAge: sessionMaxAge,
        secret: sessionSecret!
    });

Have only tested locally. The issue seemed to be having a value for `secure`, but I couldn't say why removing it fixed the problem.

**Comment by borisno2** [comment]
Closing this one as not reproducible, if any further information comes to light feel free to reopen
