### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by jhohlfeld** [keystonejs/keystone#7596]
## Steps to reproduce

1. Quick install keystone:

```bash
yarn create keystone-app
cd my-app
yarn dev
```

2. Open admin ui, create a user
3. select Users list
4. select Posts list
5. select Users again

## Expected behavior

The UI loads without errors.
Instead, on the JS console, I get this error:

<img width="1050" alt="Bildschirmfoto 2022-06-03 um 09 26 33" src="https://user-images.githubusercontent.com/497141/171808775-58d2d931-22aa-4163-a4d0-f27d3a935220.png">

node -v                 
v16.15.1

"dependencies": {
    "@keystone-6/auth": "^1.0.1",
    "@keystone-6/core": "^1.0.1",
    "@keystone-6/fields-document": "^1.0.1",
    "typescript": "^4.5.4"
  }

console log: [localhost-1654241207258.log](https://github.com/keystonejs/keystone/files/8830423/localhost-1654241207258.log)

**Comment by jhohlfeld** [comment]
There is another error when opening the signing view:

<img width="400" alt="Bildschirmfoto 2022-06-03 um 09 35 45" src="https://user-images.githubusercontent.com/497141/171809570-a2376ed8-7857-4dba-905b-3b883631b6d0.png">
<img width="600" alt="Bildschirmfoto 2022-06-03 um 09 35 52" src="https://user-images.githubusercontent.com/497141/171809579-cd1b2062-0d41-4054-b191-052ae1f0baaa.png">
[localhost-1654241757689.log](https://github.com/keystonejs/keystone/files/8830454/localhost-1654241757689.log)

**Comment by ClientsideDesign** [comment]
Thanks for flagging @jhohlfeld - also seeing this issue
