### ISSUE TITLE
Error doing production build. Redis store session

### ISSUE THREAD

**Issue by chukwumaijem** [keystonejs/keystone#7606]
Hi, I'm trying to build keystone-6 for production and I'm getting some weird errors. My project uses a Postgres database and Redis for stored sessions. Both Redis and Postgres are running on docker. Here are the issues I encountered

# **NODE_ENV**
- I set NODE_ENV to production and ran yarn install, it failed on `keystone postinstall` script. With error Error: Schema must contain uniquely named types but contains multiple types named "OrderDirection".  I changed NODE_ENV back to development and installation worked

# **Stored Session**
- keystone postinstall and keystone build need the redis server started before they work. Which is weird.
- Even with redis is started the commands still get stuck after some time. keystone build gets stuck on
λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
I left it one time and for over 30mins nothing else happened. I changed the app to stateless session and postinstall and build completed. But the issue with NODE_ENV persists.

I'm working with node 16

## Stateless session building with NODE_ENV=production

![Screenshot from 2022-06-08 09-09-21](https://user-images.githubusercontent.com/17248267/172566370-acca717c-164e-4ca2-9f5a-e8100c25a7e5.png)

## Redis StoredSession - Build is stuck.

![Screenshot from 2022-06-08 09-14-03](https://user-images.githubusercontent.com/17248267/172566993-7f6da363-82e5-4364-8ab6-0580f751dc62.png)

**Comment by chukwumaijem** [comment]
I added some logs to the prod script. Turns out the scripts get to the end but wouldn't exit.

![Screenshot from 2022-06-08 20-09-29](https://user-images.githubusercontent.com/17248267/172701411-b5b444c2-f7e7-4f8b-926d-7d2e2dd0e9bd.png)

**Comment by borisno2** [comment]
Hi @chukwumaijem, can you please confirm the versions of `keystone-6/core` and and `@keystone-6/session-store-redis` you are using?

**Comment by chukwumaijem** [comment]
Forgot to close this. I updated to the June 9th release and everything works now.
