### ISSUE TITLE
Timestamp field in list view does not observe users locale

### ISSUE THREAD

**Issue by xenobytezero** [keystonejs/keystone#7609]
When looking at the timestamp field in the list view, the displayed format does not match the users locale.

This is because the `packages\keystone\src\fields\types\timestamp\views\utils.ts` function `formatOutput()` just uses the standard `date.toLocaleString()`, which according to MDN is entirely browser dependent. On my Chrome 103.0.5060.42 with an `en-GB` locale dates are still displayed as `10/29/2013, 8:31:20 PM`.

Very quick solution off the top of my head, but the following would make the function use the correct locale.

```typescript
date.toLocaleString(window.navigator.userLanguage || window.navigator.language)
```

I assume there are a few other places where this is an issue, since `formatOutput` is used in multiple places.

**Comment by dcousens** [comment]
I think relying on the browser to determine the locale, using `toLocaleString` without arguments is still the most predictable behaviour.

I don't think using `window.navigator.userLanguage || window.navigator.language` is accurate behaviour either, as the users operating system time and date preferences are often configured independent of their language setting.
