### ISSUE TITLE
S3File formatted representation is escaped in the Admin UI List

### ISSUE THREAD

**Issue by sarriaroman** [keystonejs/keystone#762]
When a custom format is done with the "format" function of the S3File the output is formatted in the List showing in case is being used the HTML text.

**Comment by morenoh149** [comment]
I think you just want to unescape the html returned. We escape it to prevent potential XSS attacks. See `unescaped attributes` http://jade-lang.com/reference/attributes/ and change it in your codebase. If you feel this is a feature that should be added to keystone please submit a pull request for review.

**Comment by morenoh149** [comment]
I'm marking this as solved.

**Comment by sarriaroman** [comment]
I think this is not solved, I will implement the change but in the new version based on React. If you give a "format" function and the developer takes the risk of use HTML, he is responsable in an attack situation, maybe create a flag to enable it in a list when HTML is used but in this way this format method is not completely useful, even is taking the value of the format in the list.
