### ISSUE TITLE
is one of filter not working properly for integer field

### ISSUE THREAD

**Issue by pawan123e** [keystonejs/keystone#7638]
![filter](https://user-images.githubusercontent.com/26507643/174059709-a6e90cb6-1445-446a-8031-a65f78fe9e6b.png)

Here in the input box, we can add only 1 item.

**Comment by mitchellhamilton** [comment]
You can have multiple items by separating numbers with a comma. We're planning on improving the UX around this in the future so it's clear how to use it.

**Comment by pawan123e** [comment]
Okay, great!

**Comment by gautamsi** [comment]
you can not use `,` in this field as this is clearing non numeric input on entry in field. a fix is still needed
