### ISSUE TITLE
Typescript error on `graphql.omit`

### ISSUE THREAD

**Issue by nderkim** [keystonejs/keystone#7660]
When you configure a list with graphql `create` omitted

![Screen Shot 2022-06-23 at 5 19 34 pm](https://user-images.githubusercontent.com/44968616/175435378-660de0ca-6a49-482b-b748-6b641838151e.png)

it causes a typescript error in `.keystone/types.d.ts`

![screen_shot_2022-06-23_at_5 18 40_pm](https://user-images.githubusercontent.com/44968616/175435260-1e514131-3b7c-4da7-bc1d-1c8efcebfb2a.png)

**Comment by dcousens** [comment]
Tracking in https://github.com/keystonejs/keystone/pull/8256
