### ISSUE TITLE
Infinite loop on setting config.ui.isAccessAllowed = false

### ISSUE THREAD

**Issue by chiu0602** [keystonejs/keystone#7662]
Actually I have set 
```isAccessAllowed: context.session?.data?.role === 'admin'```
, but for easy demonstration, I used `false` instead.

```
export default withAuth(
  config({
    ui: {
      isAccessAllowed: () => false,
      ...
    },
    ...
  },
  ...
```

Expected:
User cannot login.

Actual:
After inputting correct credentials and press "Sign in", infinite loop (successful login but jump back to login page).

**Comment by mitchellhamilton** [comment]
We can’t seem to reproduce this issue based on the code you’ve shown. Could you provide a GitHub repo that reproduces this problem?

**Comment by dcousens** [comment]
@chiu0602 can you still reproduce this?

**Comment by flexdinesh** [comment]
Tracking here #8028
