### ISSUE TITLE
Database Update docs

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#769]
I'd love some documentation on how the updating mechanism works in keystonejs. Specifically, see `updates/0.0.1-admin.js` is
```
/**
 * This script automatically creates a default Admin user when an
 * empty database is used for the first time. You can use this
 * technique to insert data into any List you have defined.
 */

exports.create = {
  User: [{
    'name.first': 'Admin',
    'name.last': 'User',
    email: 'info@foo.com',
    password: 'dummypass', //replace this manually when you sign in
    isAdmin: true
  }]
};

/**
 * The following is the older version of this update script, it is
 * left here for reference as an example of how more complex updates
 * can be structured.
 */
/*
var keystone = require('keystone'),
  async = require('async'),
  User = keystone.list('User');

var admins = [{
  email: 'user@keystonejs.com',
  password: 'admin',
  name: {
    first: 'Admin',
    last: 'User'
  }
}];

function createAdmin(admin, done) {

  var newAdmin = new User.model(admin);

  newAdmin.isAdmin = true;
  newAdmin.save(function(err) {
    if (err) {
      console.error("Error adding admin " + admin.email + " to the database:");
      console.error(err);
    } else {
      console.log("Added admin " + admin.email + " to the database.");
    }
    done(err);
  });
}

exports = module.exports = function(done) {
  async.forEach(admins, createAdmin, done);
};
*/
```
What update options are available? Can I deploy scripts that fill the database with dummy users? Can I deploy scripts that initialize the database with sample website copy that admins can later modify through the adminUI?

**Comment by mahnunchik** [comment]
+1

**Comment by mzgol** [comment]
Is there any way to define updates that *are not* performed on fresh databases but are on existing ones? Say I change the schema of the model and I want to migrate older data. New data in new databases will have correct new schema from the beginning so updates assuming the older one would fail.

I can probably detect via duck-typing what shape the model is in and decide whether to apply updates only then but that seems fragile.

**Comment by antoineclaval** [comment]
@mgol I'm looking for a way to doing actual update too

**Comment by morenoh149** [comment]
the thing is mongo is "schemaless" so there is no need to stop the db to drop or add columns like in a tradtional RDBMS.

So I don't think tracking a database version number is necessary. To solve this issue I think all that would have to be documented is that any mongoose actions are valid within an update script. Ideally demonstrate filling the db with users, products and companies from the `faker` npm module.

**Comment by antoineclaval** [comment]
What about updating a value, without changing the schema ?

@morenoh149  your first comment here create a user with info@foo.com as a e-mail address. What if i want to create a migration script to change the e-mail address to info@bar.com ?

**Comment by morenoh149** [comment]
not sure. @JedWatson if I were to write an update script like
```javascript
exports.findOneAndUpdate(
  { email: 'info@foo.com' },
  { email: 'info@bar.com' }
);
```
would that work? I'm reading through https://github.com/keystonejs/keystone/blob/master/lib/updates.js#L108

**Comment by webteckie** [comment]
See [this gist](https://gist.github.com/JedWatson/10739959)  Basically in the updates file you can have a function that takes a callback.  Thus, @morenoh149 example would be:
```
function(done) {

    // you can do whatever you want here and then make sure you call done(err).  For example:

    let myList = keystone.list('MyList');
    myList.findOneAndUpdate(
       { email: 'info@foo.com' },
       { email: 'info@bar.com' },
       done
    );
}
```

The shorthand syntax described in that gist is excellent for recreating text fixtures!

**Comment by mxstbr** [comment]
Since this is a documentation issue, I've moved it to https://github.com/keystonejs/keystonejs-site/issues/88!
