### ISSUE TITLE
Missing documentation on how to change default port from CLI

### ISSUE THREAD

**Issue by machineghost** [keystonejs/keystone#7697]
This, *link* (**NOTE:** Github is messing up this link if I provide it: it's supposed to be https://github.com/keystonejs/keystone/discussions/ + 7696, but it somehow turns into a pull request link), got turned into a discussion.  However, it's still an issue, and the issue is that the way to run Keystone on another port isn't provided anywhere within the documentation.

This should be a trivial addition.

**Comment by dcousens** [comment]
The relevant part of `keystone dev` and `keystone start`, two CLI scripts provided by Keystone
https://github.com/keystonejs/keystone/blob/24c59baff3db26c4f2425994237bb440e0820b00/packages/core/src/scripts/run/dev.ts#L234

https://github.com/keystonejs/keystone/blob/24c59baff3db26c4f2425994237bb440e0820b00/packages/core/src/scripts/run/start.ts#L47

The relevant documentation

https://github.com/keystonejs/keystone/blob/24c59baff3db26c4f2425994237bb440e0820b00/docs/pages/docs/apis/config.mdx#L211

The nuance here is that this behaviour is only part of the provided `keystone` CLI scripts, if you don't use them, this isn't inherently part of the Keystone core.

**Comment by dcousens** [comment]
I don't think we want to encourage `process.env.PORT`, as you should be configuring this yourself in your own Keystone configuration
