### ISSUE TITLE
Arrays returned from query api are not iterable.

### ISSUE THREAD

**Issue by GalStan** [keystonejs/keystone#7718]
If you try to query some array from db via `query` api you will get array with null as prototype. 

```typescript
const { roles } = await context.query.AuthUser.findOne({
  where: { id: item.authUserId as string },
  query: "roles { name }"
});

return Array.prototype.map.call(roles, role => role.name).join(", ");
```
`roles` there is a 'demilitarized' object so I have to use array prototype explicitly.

At the moment I found only this ugly workaround to sort it out.
There is no such problem with `prisma` api.

**Comment by dcousens** [comment]
@GalStan I cannot reproduce this.

Can you please add a complete example that we can use to reproduce the problem.
Until then we can close the issue.
