### ISSUE TITLE
Firebase init twice, The default Firebase app already exists

### ISSUE THREAD

**Issue by tranlehaiquan** [keystonejs/keystone#7719]
Intall firebase-admin
```
yarn add firebase-admin
```

Add to file keystone
```
import admin from "firebase-admin";
console.log('this')
const firebase = admin.initializeApp({
      credential: admin.credential.cert(credential as any),
    });
```

Expect firebase just init one time.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/17347993/179244686-c02e8a09-024c-43d5-8aa8-0d20c0883514.png">

Node: v16.14.1

**Comment by flexdinesh** [comment]
Keystone server hot reloads in dev mode when you make changes. So if you have initialise something only once it needs to be included in `db.onConnect` method. 

More here — [onConnect is not hot reloaded](https://keystonejs.com/releases/2021-11-02#on-connect-is-not-hot-reloaded)

```
export default config({
  db: {
    provider: 'sqlite',
    url: process.env.DATABASE_URL || 'file:./keystone-example.db',
    async onConnect(context: Context) {
     // anything you add here will be invoked only once
    },
  },
  lists,
});

```

**Comment by quantran020173** [comment]
Hi @flexdinesh 
I already find using with onConntect, but Is it really weird to wrap everything on onConnect?

**Comment by flexdinesh** [comment]
It's not @quantran020173. If you don't want to write a lot of code inside onConnect to keep your file readable you could write your code in another file and import it as a method in onConnect.

```
import {initExternalService} from './another-file'

export default config({
  db: {
    provider: 'sqlite',
    url: process.env.DATABASE_URL || 'file:./keystone-example.db',
    async onConnect(context: Context) {
     initExternalService()
    },
  },
  lists,
});
```
