### ISSUE TITLE
Documentation: Field appearance not up to date with the latest API

### ISSUE THREAD

**Issue by nemonemi** [keystonejs/keystone#7723]
https://keystonejs.com/docs/walkthroughs/lesson-2#configure-a-field-s-appearance

The documentation mentions properties that don't exist in the latest version.
```ts
       ui: {
          displayMode: 'cards',
          cardFields: ['name', 'email'],
          inlineEdit: { fields: ['name', 'email'] },
          linkToItem: true,
          inlineCreate: { fields: ['name', 'email'] },
       },
```

![image](https://user-images.githubusercontent.com/77624664/179578620-ca1d70f9-1222-4df7-a60d-345f7cf36c7a.png)

```ts
"dependencies": {
    "@keystone-6/auth": "^4.0.0",
    "@keystone-6/core": "^2.1.0",
    "@keystone-6/fields-document": "^4.0.0",
    "typescript": "^4.7.4"
  },
  "engines": {
    "node": "^14.15 || ^16.13"
  },
  "volta": {
    "node": "16.14.0",
    "yarn": "1.22.18"
  },
  "packageManager": "yarn@3.0.2"
```

**Comment by mitchellhamilton** [comment]
In your editor screenshot, it looks like you're looking at the list level ui config rather than the relationship field ui config, the properties documented exist on the relationship field ui config
