### ISSUE TITLE
Admin UI filter does not stick

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#773]
If I filter a list by some criteria and view a filtered item the:

    (a) when I use the browser's back link the filter is still active
    (b) when I use the Admin UI's back link the filter is not longer active

Shouldn't the filter stay active until it is cleared or the page is refreshed?

**Comment by BerkeleyTrue** [comment]
Is this still an issue?

**Comment by webteckie** [comment]
@BerkeleyTrue dont know has anyone fixed it?  I won't be able to test it until later tonight(EST).

**Comment by webteckie** [comment]
@BerkeleyTrue this is still an issue.

**Comment by BerkeleyTrue** [comment]
I call dibs

**Comment by metasansana** [comment]
Go for it! :)

**Comment by webteckie** [comment]
By the way this is still an issue in 0.4

**Comment by mxstbr** [comment]
This is definitely fixed with #2566!
