### ISSUE TITLE
Fields marked as non-nullable generate SDL that indicates they are nullable

### ISSUE THREAD

**Issue by pc-erin** [keystonejs/keystone#7736]
For the following schema entry:

```ts
Post: list({
  fields: {
    title: text({
      validation: { isRequired: true },
    }),
  }
}),
```

A Prisma model is generated:

```prisma
model Post {
  id          String    @id @default(cuid())
  title       String    @default("")
}
```

And then an SDL type is generated from that:

```gql
type Post {
  id: ID!
  title: String
}
```

I would expect the `title` field in the SDL file to have a `!` on the end indicating it is non-nullable.

Not completely sure if this is an issue with Keystone or Prisma, or if I'm just missing something.

**Comment by mitchellhamilton** [comment]
This is expected behavior so that adding field-level access control is not a breaking change to your GraphQL schema. You can add `graphql: { output: { isNonNull: true } }` if you won't need field-level access control on it and then the field will be non-nullable in the GraphQL schema.

**Comment by pc-erin** [comment]
Ah, that makes sense. Thank you!
