### ISSUE TITLE
Keystone server crashes with too many request

### ISSUE THREAD

**Issue by IamMattL** [keystonejs/keystone#7778]
### Discussed in https://github.com/keystonejs/keystone/discussions/7753

<div type='discussions-op-text'>

<sup>Originally posted by **IamMattL** August  1, 2022</sup>
Hi,

I find that the keystone server dies when you refresh the admin page a few times, which then i have to start up the server again. This happens in dev and production, is this a bug or a configuration issue? I've looked for this issue on github and the Docs but cant find anything about it.

This seems to be a linux issue as it doesn't happen on windows.

Running on Ubuntu 20.04

Here is the console output

```
$ yarn dev
yarn run v1.22.19
$ keystone dev
✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
✨ The database is already in sync with the Prisma schema.
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app
event - compiled client and server successfully in 14.1s (1315 modules)
✅ Admin UI ready
wait  - compiling /api/__keystone_api_build...
event - compiled successfully in 285 ms (196 modules)
wait  - compiling /init (client and server)...
event - compiled client and server successfully in 581 ms (1341 modules)
Error: aborted
    at connResetException (node:internal/errors:691:14)
    at abortIncoming (node:_http_server:597:17)
    at socketOnClose (node:_http_server:591:3)
    at Socket.emit (node:events:532:35)
    at TCP.<anonymous> (node:net:687:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jamie-lord** [comment]
@dcousens any update on this issue? We would love to use Keystone for our product but this is a show-stopping problem as Keystone is unusable when hosted on Linux.

**Comment by dcousens** [comment]
@jamie-lord @IamMattL this will be resolved in the next release, hopefully today

**Comment by dcousens** [comment]
@jamie-lord @IamMattL this has been resolved in https://github.com/keystonejs/keystone/releases/tag/2022-08-19 - I will update with additional details as soon as I can.

**Comment by dcousens** [comment]
Hi @jamie-lord and @IamMattL,
The following CVE and security advisory was issued for this problem upstream in nextjs, and has been resolved as part of our recent update to [nextjs@v12.2.4](https://github.com/vercel/next.js/releases/tag/v12.2.4).
- https://github.com/vercel/next.js/security/advisories/GHSA-wff4-fpwg-qqv3

Thanks for your patience,
