### ISSUE TITLE
Multiple instances of graphql

### ISSUE THREAD

**Issue by skindc** [keystonejs/keystone#7816]
It seems the recent release of the 19th August 2022 upgraded graphql dependency to fix a security vulnerability, yet the @keystone-6/auth package did not and this now causes issues with build.
To replicate...
Upgrade keystone dependencies to the below as per recent release.
```
"@keystone-6/auth": "4.0.1",
"@keystone-6/core": "2.2.0",
"@keystone-6/document-renderer": "1.1.1",
"@keystone-6/fields-document": "4.1.0",
"@keystone-ui/fields": "7.1.1",
```

Try and run yarn.
You will see....
```
Error: Cannot use GraphQLScalarType "{ name: "String", description: "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", specifiedByURL: undefined, serialize: [function serialize], parseValue: [function parseValue], parseLiteral: [function parseLiteral], extensions: {}, astNode: undefined, extensionASTNodes: [] }" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/skin/Projects/activeProjects/0197_LL_SiteRebuild/lokalliving-stack/keystone6/node_modules/@keystone-6/core/node_modules/graphql/jsutils/instanceOf.js:35:13)
    ...
```
On inspection of the dependency tree we can see this is true.
```
├─┬ @keystone-6/auth@4.0.1
│ └── graphql@15.8.0
├─┬ @keystone-6/core@2.2.0
│ ├─┬ @apollo/client@3.6.9
│ │ ├─┬ @graphql-typed-document-node/core@3.1.1
│ │ │ └── graphql@16.6.0 deduped
│ │ ├─┬ graphql-tag@2.12.6
│ │ │ └── graphql@16.6.0 deduped
│ │ └── graphql@16.6.0
│ ├─┬ @graphql-tools/schema@9.0.1
│ │ ├─┬ @graphql-tools/merge@8.3.3
│ │ │ └── graphql@16.6.0 deduped
│ │ ├─┬ @graphql-tools/utils@8.10.0
│ │ │ └── graphql@16.6.0 deduped
│ │ └── graphql@16.6.0 deduped
│ ├─┬ @graphql-ts/extend@0.4.1
│ │ └── graphql@16.6.0 deduped
│ ├─┬ @graphql-ts/schema@0.5.3
│ │ └── graphql@16.6.0 deduped
│ ├─┬ @types/apollo-upload-client@17.0.1
│ │ └── graphql@16.6.0 deduped
│ ├─┬ apollo-server-core@3.10.1
│ │ ├─┬ @apollo/utils.usagereporting@1.0.0
│ │ │ ├─┬ @apollo/utils.dropunuseddefinitions@1.1.0
│ │ │ │ └── graphql@16.6.0 deduped
│ │ │ ├─┬ @apollo/utils.printwithreducedwhitespace@1.1.0
│ │ │ │ └── graphql@16.6.0 deduped
│ │ │ ├─┬ @apollo/utils.removealiases@1.0.0
│ │ │ │ └── graphql@16.6.0 deduped
│ │ │ ├─┬ @apollo/utils.sortast@1.1.0
│ │ │ │ └── graphql@16.6.0 deduped
│ │ │ ├─┬ @apollo/utils.stripsensitiveliterals@1.2.0
│ │ │ │ └── graphql@16.6.0 deduped
│ │ │ └── graphql@16.6.0 deduped
│ │ ├─┬ @apollographql/apollo-tools@0.5.4
│ │ │ └── graphql@16.6.0 deduped
│ │ ├─┬ @graphql-tools/mock@8.7.3
│ │ │ └── graphql@16.6.0 deduped
│ │ ├─┬ @graphql-tools/schema@8.5.1
│ │ │ ├─┬ @graphql-tools/merge@8.3.1
│ │ │ │ └── graphql@16.6.0 deduped
│ │ │ ├─┬ @graphql-tools/utils@8.9.0
│ │ │ │ └── graphql@16.6.0 deduped
│ │ │ └── graphql@16.6.0 deduped
│ │ ├─┬ apollo-server-plugin-base@3.6.2
│ │ │ └── graphql@16.6.0 deduped
│ │ └── graphql@16.6.0 deduped
│ ├─┬ apollo-server-errors@3.3.1
│ │ └── graphql@16.6.0 deduped
│ ├─┬ apollo-server-express@3.10.1
│ │ └── graphql@16.6.0 deduped
│ ├─┬ apollo-server-types@3.6.2
│ │ └── graphql@16.6.0 deduped
│ ├─┬ apollo-upload-client@17.0.0
│ │ └── graphql@16.6.0 deduped
│ ├─┬ graphql-type-json@0.3.2
│ │ └── graphql@16.6.0 deduped
│ ├─┬ graphql-upload@15.0.2
│ │ └── graphql@16.6.0 deduped
│ └── graphql@15.8.0
└─┬ @keystone-6/fields-document@4.1.0
  └── graphql@15.8.0
```

This can be also confirmed by inspecting the source code `packages/auth/package.json`

It seems auth package missed the upgrade.
This is actually a non issue for me as I have built my own Auth and Access extension based on the original so I not longer need the @keystone-6/auth package, yet others are going to experience this problem I believe.

**Comment by skindc** [comment]
Ah, it seems that although I do have my own Auth extension in my local code base I am still using the Signin and Init jsx pages from the auth package, so I do infact need it the auth package until I resolve those myself.

For others facing this issue you can apply a temporary work around. In the package.json of your project add...
```
"resolutions": {
    "graphql": "16.6.0"
  },
  ```
  This will force the auth package to use this latest version and provide a means to continue development / releases until this is fixed.

**Comment by jschuur** [comment]
Additional discuss [here](https://github.com/keystonejs/keystone/issues/7116#issuecomment-1221147489) about how the most recent update breaks using npm entirely (but you can just use yarn in the mean time).

**Comment by dcousens** [comment]
Thanks for the in-depth report @skindc, we'll be looking to fix this tomorrow.

**Comment by dcousens** [comment]
As pointed out by @skindc in the OP, we upgraded `graphql-upload` in the following pull request

- https://github.com/keystonejs/keystone/pull/7803

We upgraded that package to resolve a [security vulnerability](https://github.com/keystonejs/keystone/security/dependabot/18) in one the transitive dependencies of that package (`graphql-upload` < `busboy` < `dicer`).

Unfortunately, we didn't notice that the maintainer of `graphql-upload` had bumped `"graphql": ^16` in an earlier version, [_as a peer dependency_](https://github.com/jaydenseric/graphql-upload/commit/e9f9668b3bc996c27572de9467dbd9580706e35d) when undertaking this upgrade.
Many of our dependencies tend to rely on `graphql` as a range, something typically akin to `14 - 16` or `^15.0.0 || >= ^16.0.0`.

This has resulted in the following outcomes

- If you use `npm`, [`npm` will **automatically** install `peerDependencies`](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md), which will result in two versions of `graphql`, `graphql@15` for Keystone, and `graphql@16` for packagse that accepted `^16` in their range.
- If you use `yarn`, `yarn will **not** automatically install the `peerDependencies`, and you will be left with what resolves using the package ranges, which is `^15.8.0`.

As we use `yarn` to maintain the project, we did not notice this discrepancy as part of our testing suite.

### What now
This now leaves us between a rock and a hard place, we can either:

- Revert to the vulnerable version of `graphql-upload`, or
- **Recommend a workaround** until we upgrade to `graphql@16` (https://github.com/keystonejs/keystone/pull/7817), a *breaking* change

In reviewing the `graphql-upload` change, that forcing that package to use `graphql@^15.8.0` will only reduce the verbosity of some GraphQL error messages in the interim.
You may, when submitting an invalid `graphql-upload` request, be presented with 
```json
        "message": "Upload literal unsupported.",
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED"
        }
```

And not 
```json
        "message": "Expected value of type \"ImageFieldInput\", found true.",
        "locations": [
          {
            "line": 2,
            "column": 29
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED"
        }
```

### Proposed workaround
For now, with the knowledge of the estimated impact of this recommendation, our recommended workaround time is for `npm` users to force their `npm` to resolve `graphql` to `graphql@^15.8.0`, by running `npm install graphql@^15.8.0` in your project.
This will present the following `npm WARN` message:

```bash
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: graphql-upload@15.0.2
npm WARN Found: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   graphql@"15" from the root project
npm WARN   30 more (@apollo/client, @apollo/utils.dropunuseddefinitions, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^16.3.0" from graphql-upload@15.0.2
npm WARN node_modules/graphql-upload
npm WARN   graphql-upload@"^15.0.2" from @keystone-6/core@2.2.0
npm WARN   node_modules/@keystone-6/core
npm WARN 
npm WARN Conflicting peer dependency: graphql@16.6.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^16.3.0" from graphql-upload@15.0.2
npm WARN   node_modules/graphql-upload
npm WARN     graphql-upload@"^15.0.2" from @keystone-6/core@2.2.0
npm WARN     node_modules/@keystone-6/core
```

An alternative approach for this is as suggested by @skindc, which is to resolve `graphql` yourself, however for compatibility with `keystone-6/*` we recommend, as we are not currently supporting `graphql@16` (and doing so will be a breaking change).

```json
	"resolutions": {
		"graphql": "^15.8.0"
	},
```

We endeavour to fix this with a major update in the near future, but hopefully this helps everyone who runs into this problem in the short interim.

**Comment by skindc** [comment]
Thank you for a very immediate response.
Sorry for suggesting  the resolution for forward dependency upgrade, I thought this was the intention.

**Comment by dcousens** [comment]
Thanks for reporting the issue @skindc!  No worries about the recommendation, we're all trying to help :+1:

**Comment by jlarmstrongiv** [comment]
Yes, I was surprised by this error running `npx create-keystone-app` followed by npm commands.  You can also workaround this issue via npm overrides:

```json
{
  "overrides": {
    "graphql-upload@15.0.2": {
      "graphql": "^15.8.0"
    }
  }
}
```

I’m very happy to see all the dependency updates!  Upgrading jest and other deps helped solve a lot of problems for me.  Looking forward to updating to graphql@16 too.

**Comment by jlarmstrongiv** [comment]
Related https://github.com/keystonejs/keystone/pull/7817

**Comment by bladey** [comment]
Thanks for this information, solved my issue!

**Comment by dmythro** [comment]
> I’m very happy to see all the dependency updates! Upgrading jest and other deps helped solve a lot of problems for me. I see that prisma@4 was merged, and I’m looking forward to updating to graphql@16 too.

Oh yes! Waiting for `graphql@16` upgrade too :)

**Comment by dcousens** [comment]
This has been resolved with the [newest major release](https://github.com/keystonejs/keystone/releases/tag/2022-10-19) :package:.

Please don't forget to remove your `resolutions` or `overrides` when upgrading.

**Comment by eaglestorm** [comment]
This is still not fixed.  It fails with both npm and yarn with the same error.  when I try to install used both npx and yarn.

Duplicate "graphql" modules cannot be used at the same time since different

node version 16.18

**Comment by dcousens** [comment]
@eaglestorm can you please show your steps to reproduce?

**Comment by eaglestorm** [comment]
> @eaglestorm can you please show your steps to reproduce?

all i did was the initial npx create command and it failed with Error: Cannot use GraphQLObjectType "Post" from another module or realm.  not really any steps.

**Comment by jaydenseric** [comment]
@eaglestorm run `npm ls graphql` to view what is installing a different version of `graphql` somewhere in your `node_modules`.

**Comment by eaglestorm** [comment]
shows all the same graphql version
+-- @keystone-6/auth@5.0.0
| `-- graphql@16.6.0 deduped
+-- @keystone-6/core@3.0.1
| +-- @apollo/client@3.6.9
| | +-- graphql-tag@2.12.6
| | | `-- graphql@16.6.0 deduped
| | `-- graphql@16.6.0 deduped
| +-- @graphql-ts/extend@1.0.0
| | `-- graphql@16.6.0 deduped
| +-- @graphql-ts/schema@0.6.0
| | `-- graphql@16.6.0 deduped
| +-- @graphql-typed-document-node/core@3.1.1
| | `-- graphql@16.6.0 deduped
| +-- @types/apollo-upload-client@17.0.1
| | +-- @apollo/client@3.7.1
| | | `-- graphql@16.6.0 deduped
| | `-- graphql@16.6.0 deduped
| +-- apollo-server-core@3.10.3
| | +-- @apollo/utils.usagereporting@1.0.0
| | | +-- @apollo/utils.dropunuseddefinitions@1.1.0
| | | | `-- graphql@16.6.0 deduped
| | | +-- @apollo/utils.printwithreducedwhitespace@1.1.0
| | | | `-- graphql@16.6.0 deduped
| | | +-- @apollo/utils.removealiases@1.0.0
| | | | `-- graphql@16.6.0 deduped
| | | +-- @apollo/utils.sortast@1.1.0
| | | | `-- graphql@16.6.0 deduped
| | | +-- @apollo/utils.stripsensitiveliterals@1.2.0
| | | | `-- graphql@16.6.0 deduped
| | | `-- graphql@16.6.0 deduped
| | +-- @apollographql/apollo-tools@0.5.4
| | | `-- graphql@16.6.0 deduped
| | +-- @graphql-tools/mock@8.7.7
| | | +-- @graphql-tools/schema@9.0.5
| | | | +-- @graphql-tools/merge@8.3.7
| | | | | `-- graphql@16.6.0 deduped
| | | | `-- graphql@16.6.0 deduped
| | | +-- @graphql-tools/utils@8.13.0
| | | | `-- graphql@16.6.0 deduped
| | | `-- graphql@16.6.0 deduped
| | +-- @graphql-tools/schema@8.5.1
| | | +-- @graphql-tools/merge@8.3.1
| | | | +-- @graphql-tools/utils@8.9.0
| | | | | `-- graphql@16.6.0 deduped
| | | | `-- graphql@16.6.0 deduped
| | | +-- @graphql-tools/utils@8.9.0
| | | | `-- graphql@16.6.0 deduped
| | | `-- graphql@16.6.0 deduped
| | +-- apollo-server-plugin-base@3.6.3
| | | `-- graphql@16.6.0 deduped
| | `-- graphql@16.6.0 deduped
| +-- apollo-server-errors@3.3.1
| | `-- graphql@16.6.0 deduped
| +-- apollo-server-express@3.10.3
| | `-- graphql@16.6.0 deduped
| +-- apollo-server-types@3.6.3
| | `-- graphql@16.6.0 deduped
| +-- apollo-upload-client@17.0.0
| | `-- graphql@16.6.0 deduped
| +-- graphql-upload@15.0.2
| | `-- graphql@16.6.0 deduped
| `-- graphql@16.6.0 deduped
+-- @keystone-6/fields-document@5.0.0
| `-- graphql@16.6.0 deduped
`-- graphql@16.6.0

**Comment by dcousens** [comment]
@eaglestorm can you please open a different issue with any relevant information.
I don't think your issue is related to this.

**Comment by ttbarnes** [comment]
I am still getting this issue unfortunately after upgrading to the latest packages - getting this error with `npm ls graphql`

```cmd
invalid: "^16.3.0" from node_modules/graphql-upload
```


Node version: 16.4.2

Dependency versions: 

```js
"@graphql-tools/schema": "^9.0.9",
"@keystone-6/auth": "5.0.0",
"@keystone-6/core": "3.0.2",
"@keystone-6/fields-document": "5.0.1",
```
