### ISSUE TITLE
Enhancement for Location fields with google maps to get latitude and longitude autofilled

### ISSUE THREAD

**Issue by quchie** [keystonejs/keystone#79]
Hi keystone team! Thank you for such an amazing project. I , am now working on a gmaps.js enhancement for my personal project. Its a basic click on the google maps to auto fill the lat lang on the Location field. What do you guys think? Should i do a pr on this? The code need some review tough. :)

![keystone location](https://f.cloud.github.com/assets/793331/1649621/f0b7d82a-5a15-11e3-84bc-8469723c0f0e.png)

**Comment by xianlin** [comment]
so still nobody find the implementation of this cool feature...

**Comment by morenoh149** [comment]
@dcousens why was this closed?

**Comment by VinayaSathyanarayana** [comment]
Any updates on this?

**Comment by morenoh149** [comment]
none

**Comment by kadosh1000** [comment]
It is a very good feature to allow showing the map and drop a pin, also it would be amazing instead of all the text fields to just show one and let the google automplete do it's magic there

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!
