### ISSUE TITLE
POST /contact fails with handlebars templates enabled.

### ISSUE THREAD

**Issue by clickslide** [keystonejs/keystone#793]
Hello,

I have Keystone installed using Handlebars for its templates. When I attempt to send an email via Mandrill, I get the following error:

````
POST /contact 200 48ms
{ ...../KeystoneBlog/templates/emails/enquiry-notification/email.jade']
  errno: 34,
  code: 'ENOENT',
  path: '...../KeystoneBlog/templates/emails/enquiry-notification/email.jade' }

````
Is there something I'm missing? It seems that the mandrill implementation only works with Jade templates... Perhaps I'm mistaken.

**Comment by ekynoxe** [comment]
It's interesting, overriding the template engine for the views for swig requires to use:

    'view engine': 'swig',
    'custom engine': swig.renderFile

Whereas doing the same in a model using `new keystone.Email()` seems to only need:

    'view engine': 'swig',
    'custom engine': swig

Without the renderFile

Using the override as suggested by @sebmck does seem to work though, as the `lib/email.js` file's code shows.

**Comment by ekynoxe** [comment]
I'd be happy to help solve this one, but I'd need some steer as I've not contributed to anything yet (shame on me). I'll go look at the docs and guidelines.

**Comment by ekynoxe** [comment]
@JedWatson @sebmck Is the proposed solution therefore to add a new 'email engine' option and use consolidate.js only on emails rendering based on this option?

It seems to me that all that's **really** missing right now is in the generator: a set of templates to cater for handlebars and update the swig ones so setting up a project with the generator doesn't end-up in a problem like @clickslide had.
And perhaps a modification the the generated Enquiry.js model to reflect what users have chosen.

I'm keen to help and to start with a relatively small one. Let me know what you think.

**Comment by davideberlein** [comment]
@JedWatson @kittens @ekynoxe Do we have any progress on this topic yet?

I'm on the latest 3.x commit and can't get Handlebars to work with email.
When I try to setup the Email with handlebars I get the exception that: 

> Error: Missing helper: "underscoreFormat" at model.<anonymous> 

which is located in the [index.js](/keystonejs/generator-keystone/blob/master/app/templates/templates/default-hbs/views/helpers/index.js) of the project generated by generator-keystone.

I could start trying to register these now by hand before passing the handlebars engine into Email but I don't think this is the right way to go....

What is your opinion on the topic?

**Comment by mxstbr** [comment]
This is a very old issue and no longer relevant. If you take a look on the master branch at `admin/server/api`, we have a completely new API which should support all usecases. Feel free to open a new issue if this still persists for you!
