### ISSUE TITLE
Broken related resources links in docs guide choosing db

### ISSUE THREAD

**Issue by jalezi** [keystonejs/keystone#7996]
### Steps to reproduce
Go to: https://keystonejs.com/docs/guides/choosing-a-database.
In related resources section click on either link.
Both resolves to 404.

- "Fields API" navigates to `https://keystonejs.com/fields/overview` instead of `https://keystonejs.com/docs/fields/overview`
- "DB Config Api" navigates to `https://keystonejs.com/config/config#db` instead of `https://keystonejs.com/docs/config/config#db`

### Expected
No `404`.

**Comment by flexdinesh** [comment]
Thanks for reporting @jalezi. This has been fixed in #8002.
