### ISSUE TITLE
Check our licensees before OSS

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#800]
We could adopt the [BlueOak model license](https://blueoakcouncil.org/license/1.0.0?, or at least [one of the top rated licences here](https://blueoakcouncil.org/list#gold)

**Comment by sskras** [comment]
@mxstbr commented [Mar 12, 2019](#issuecomment-471980559):

> Also, while BlueOak is cool it is not officially an open source license (not approved by the OSI), 

After almost 5 years it already is. Please see: https://github.com/spdx/license-list-XML/issues/2352
