### ISSUE TITLE
Module not found: Can't resolve '@keystone-6/core/context'

### ISSUE THREAD

**Issue by salvatorericcardi** [keystonejs/keystone#8006]
### **How to reproduce the problem**
Simply import @keystone-6/core/context module and you will have a module not found error

### **What I'm expecting**
I need to use getContext to bring content on frontend

### **The error**
![error](https://user-images.githubusercontent.com/29570607/196109219-52b275c5-6ccc-49a5-b0c5-a43a96422f8b.png)

### **Contextual informations**
Node version 16.15.0
Browser Google Chrome

**Comment by gautamsi** [comment]
next major update is not released which contains `getContext` code. wait for next major release
