### ISSUE TITLE
TypeError: Cannot destructure property 'operation' of 'access' as it is undefined.

### ISSUE THREAD

**Issue by riccardi1997** [keystonejs/keystone#8024]
### How to reproduce the problem
Try to reproduce this example by clicking [here](https://github.com/keystonejs/keystone/tree/main/examples/embedded-nextjs) and run `npm run dev` after cloned the example.

### What I'm expecting
I'm expecting the server start but I receive an error after `keystone postintstall` command. 

### The error
![error](https://user-images.githubusercontent.com/29570607/196919205-e38a7b84-9d6e-48cb-9d29-f2891a563594.png)

### Contextual informations
There is also a syntax error [here](https://github.com/keystonejs/keystone/blob/main/examples/embedded-nextjs/with.js) at line 15 on `const { connect, context }` with error code ts(2339). Now getContext is available but it doesn't work properly.

### Greetings
I hope to be helpful. Thanks

**Comment by mmachatschek** [comment]
I ran into the same issue. I suppose [this change](https://github.com/keystonejs/keystone/pull/7968/files#diff-4e89868a26b75da76e42152ddc2af3928f661aecafb350b195578de76574696e) breaks this.

**Comment by dcousens** [comment]
Thanks @riccardi1997, that is a different issue and I have opened a pull request to fix that Javascript example.
