### ISSUE TITLE
Next.js starts after npm start and KeyStone not

### ISSUE THREAD

**Issue by riccardi1997** [keystonejs/keystone#8065]
### How to reproduce the problem
Run `npm start` on cmd

### What I'm expecting 
Starting KeyStone and Next.js at the same time, the first on a port of the server and the other one on another. Instead start only Next.js after build and not also KeyStone. It should work as `npm run dev`, where KeyStone start on port 8000 and Next.js on port 3000. I followed the embedded next.js example and I'm using these settings in my package.json:
```
"scripts": {
    "postinstall": "keystone postinstall",
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }
```

**Comment by borisno2** [comment]
Hi @riccardi1997,
Thanks for reaching out, we have just released a new blog for embedding Keystone into Next https://keystonejs.com/blog/nextjs-keystone and the old Embedded Next.js example is now outdated.

If you are wanting to still start keystone to have the Admin UI available, you will need to add `keystone build` to your build step (ie `keystone build && next build`) and `keystone start` to your start command using something like `concurrently`  to start both keystone and next processes at the same time.
