### ISSUE TITLE
Adding items to nested lists is broken

### ISSUE THREAD

**Issue by GitCloneJames** [keystonejs/keystone#8086]
Creating a starter app using 
```
npx create-keystone-app
```

- Start the app and create new user logged in. 
- Start to create a new post, give it a title etc, 
- under tags, create new tag. 

**Expected Result**

Tag will be added and displayed in the post

**Actual Result** 

The entire page reloads, and neither the post nor the tag are saved.

**Comment by GitCloneJames** [comment]
Maybe unrelated but once an item is created, when editing, tags can be added. 

When opening the 'create tag' form, the frontend throws an error ; 

 <form> cannot appear as a descendant of <form>
 
 and sure enough creating tags in create mode has a form inside a form, but not in edit mode

**Comment by borisno2** [comment]
Thanks @GitCloneJames, It looks like this is the same as https://github.com/keystonejs/keystone/issues/8149 - feel free to follow along there, I am going to close this ticket.
