### ISSUE TITLE
'Community Slack' advertised on website and documentation only allows keystonejs.com emails

### ISSUE THREAD

**Issue by GitCloneJames** [keystonejs/keystone#8090]
As advised in the subject; 

You can use any account with the domain:
keystonejs.com
thinkmill.com.au
Don’t have an email address from one of those domains?
Contact the workspace administrator at KeystoneJS for an invitation.

**Comment by dcousens** [comment]
Thanks for reporting this @GitCloneJames, I can reproduce this.  @flexdinesh I think the link needs to be re-generated.

**Comment by flexdinesh** [comment]
This is fixed now. Link regenerated. Thanks for the report @GitCloneJames.
