### ISSUE TITLE
One-sided relationships are broken

### ISSUE THREAD

**Issue by fkrauthan** [keystonejs/keystone#8098]
I just updated my project to the latest version of keystone and when having a list like this:

```
export const Post = list({
   access: allowAll,
    fields: {
        author: relationship({ ref: "User", many: false }),
    },
});
```

and try to access it from the UI the page just shows an endless spinner. When looking at the developer tools it seems like it is triggering a search that is invalid:

```
{"errors":[{"message":"Cannot query field \"authorCount\" on type \"Post\". Did you mean \"author\"?","locations":[{"line":6,"column":5}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"authorCount\" on type \"Post\". Did you mean \"author\"?","    at Object.Field 
```

So right now all my lists that use one-sided relationships can't be accessed from the UI anymore.

**Comment by dcousens** [comment]
Hi @fkrauthan,  please see [today's release that fixes this](https://github.com/keystonejs/keystone/releases/tag/2022-11-18).
If you find any other regressions, please let us know :yellow_heart:

**Comment by fkrauthan** [comment]
Perfect that fixes it. Thank you so much for the quick turnaround. I am really looking forward using the grouping and moving items to the sidebar feature :)
