### ISSUE TITLE
Client-side models for Backbone and Angular with underscore functions

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#81]
It would be really useful for Backbone and Angular apps to auto-generate models based on their Keystone definitions, especially if we replicated the underscore functionality and auto-wired an API interface for them to talk to.

Discussion here: https://groups.google.com/forum/#!topic/keystonejs/jiJLvbeG3cA

**Comment by wmertens** [comment]
Is this still a desired feature? Seems that Keystone is focused mostly on React now? Should this issue be closed?
