### ISSUE TITLE
The Notion mode does’t change

### ISSUE THREAD

**Issue by kamenskiyyyy** [keystonejs/keystone#8102]
1. Go to https://keystonejs.com/docs/guides/document-field-demo
2. Try to change Notice mode.

I'm expecting a change in Notice mode

Link for video: https://disk.yandex.ru/d/wIb3Tq8biEo9UQ

**Comment by borisno2** [comment]
Hi @kamenskiyyyy 
Thanks for spotting and taking the time to log an issue, a fix is in the works!
