### ISSUE TITLE
Docs / SEO: Sitelink for Getting Started links to V5 docs

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [keystonejs/keystone#8106]
This is super minor and annoying to address but the Keystone.js Site links include "Getting Started" which sends users to the old V5 page.

![image](https://user-images.githubusercontent.com/58131578/202940693-640d687a-8bcb-4a6d-8596-ba6a1b3fdc28.png)

A sneaky way to handle this would be putitng a 301 redirect on the base URL:

https://v5.keystonejs.com/quick-start/

And in the mean time add a query string for all internal links back to the page so you know not to trigger the redirect,

You'd only have to do this until google gets the hint and updates to the new URL:

https://keystonejs.com/docs/getting-started

If you do nothing people will continue clicking and google will continue clowning everyone 🤡

**Comment by flexdinesh** [comment]
Thanks for the report @TheRealFlyingCoder. We've added robots noindex to all v5 pages and manually removed the site link from the Google console. The v5 getting started link shouldn't show up anymore.

- https://github.com/keystonejs/keystone-5/pull/399
