### ISSUE TITLE
Using `::` as default for host does not work in all intances

### ISSUE THREAD

**Issue by fkrauthan** [keystonejs/keystone#8131]
It looks like keystone if nothing is provided specifies `::` as `host` when creating the httpServer. However depending on the system and OS this does not bind to ipv4 AND ipv6. Areas that I've noticed is having issues like this:

* Docker on Windows (seen by myself)
* codesandbox.io samples (reported by someone in slack)

Other tools like Remix-Serve use the `listen` method without a host unless a host is specified ([code](https://github.com/remix-run/remix/blob/main/packages/remix-serve/cli.ts)).

**Current workaround:**

```
        server: {
            options: {
                 host: "",
            },
        }
```

The only downside the console log message when starting is now saying `http://:3000` but it listens on all interfaces now.

**Comment by mkastner** [comment]
@fkrauthan I can't find server.options.host in the documentation:

https://keystonejs.com/docs/config/config#server

Or is there another place where I need to set the host option? I'm using FreeBSD for keystone-6 production and have been banging my head for days now on this error:

```
 Starting Keystone
node:events:491 
      throw er; // Unhandled 'error' event 
      ^                        

Error: listen EPROTONOSUPPORT: protocol not supported :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1446:21)                                                                                       
    at listenInCluster (node:net:1511:12)
    at doListen (node:net:1660:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)                                                                             

Emitted 'error' event on Server instance at: 

    at emitErrorNT (node:net:1490:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {

  code: 'EPROTONOSUPPORT',                                                                                                                             

  errno: -43,
  syscall: 'listen',
  address: '::',
  port: 3000 
} 
``` 

What bothers me somewhat even more is that there's no stack trace or otherwise traceable message which indicates at which location the code this error was raised. Logging could definitely need some improvement in keystone.

**Comment by fkrauthan** [comment]
@mkastner I think it is an undocumented option. But it does exist. The error you are seeing is strange (currently it just does not specify a host so node would select the protocol). Could it be that you are on the latest NodeJS version? Sometimes strange errors like this are triggered because of that.

**Comment by mkastner** [comment]
@fkrauthan Thanks for your reply. The app runs on v16.18.1, not too fancy. I'm not sure, but I think someone mentioned somewhere, that there are slight differences in how some OSs handle blank host information. So I wouldn't be surprised if it's FreeBSD-related.

**Comment by fkrauthan** [comment]
So did you try just using the latest keystone and NOT setting any host? otherwise, you can set the `host` config (or `HOST` env variable) to ether `0.0.0.0` or `localhost` or whatever you need in your case.

**Comment by mkastner** [comment]
I'm on keystone-6 (core 3.1.2) and I initially hadn't any host setting at all, which seemed to have caused the problem

`Error: listen EPROTONOSUPPORT: protocol not supported :::3000`

But setting a blank host in the option works. That's good enough for the time being.

**Comment by fkrauthan** [comment]
Ah yeah you are not on the fixed version (core 4.0.0 contains my changes that fix it). So you ether have to use the workaround of empty string or update the core.

**Comment by mkastner** [comment]
@fkrauthan I am not familiar with all changes taking place in 4.0.0 . Therefore I've been reluctant to actually to upgrade core. It's a major release most likely including breaking changes. They might affect other dependencies like auth and also my own code.

I'll give it a shot.

**Comment by dcousens** [comment]
@mkastner are you using Typescript?  The documentation that needs to be added is that `options` is the [`http.createServer` options](https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener)

**Comment by mkastner** [comment]
@tcousens Thanks! That's a great information.
