### ISSUE TITLE
Inline create not wroking. It refreshes the whole page

### ISSUE THREAD

**Issue by arcadio-nseng** [keystonejs/keystone#8140]
**Steps to reproduce**
1. Create a new keystone app as described in the getting started documentation
2. Start the app in development mode and open the admin UI in the browser
3. Try o create a Post with some tags (by creating these tags inline) 

While using cards as display mode with inlineCreate property in a related field, the related item should be created without refreshing the page to keep editing other fields, however, actually hitting the button create refreshes the page without saving either the related item or the parent one.

**Comment by borisno2** [comment]
Hi @arcadio-nseng thanks for logging this issue. Looks like we have two issues logged for this (#8149) I am going to close this one, feel free to follow #8149 where we will track progress.
Thanks,
