### ISSUE TITLE
npm init/create reuses cached version without @latest scope

### ISSUE THREAD

**Issue by adamjkb** [keystonejs/keystone#8154]
### Reproduction

Bit tricky, but if you have a previously created a keystone app using the `npm init keystone-app` there is a chance it will try to reuse a cached version. It does notify you by printing: 

```bash
⚠️  You're running an old version of create-keystone-app, please update to 8.1.0
✔ What directory should create-keystone-app generate your app into? · ks-auth-unresponsive
```

I hadn't managed to find a way to update it cleanly.

### Proposed solution

Use `@latest` scope in docs to guide people to always pull the latest create-keystone-app. This seems to be "industry standard" way of telling people to use their create app. [NextJS](https://nextjs.org/docs/getting-started#automatic-setup), [SvelteKit](https://kit.svelte.dev/docs/creating-a-project)

Happy to create a PR!

**Comment by flexdinesh** [comment]
Thanks for highlighting this @adamjkb. `@latest` will be helpful to make sure users always get the latest scaffolded keystone app. PR welcome.

```
yarn create keystone-app@latest
```
