### ISSUE TITLE
Show upload progress in AdminUI for S3 uploads

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#816]
After investigating the bug in https://github.com/keystonejs/keystone/issues/532 is was determined that uploads were failing but the adminUI reported no errors. I suggest we do something more intelligent with the response object. Display a progress bar of the upload and display an error if the file wasn't stored to S3 properly. @JedWatson let me know if you think this is a good idea. See https://github.com/keystonejs/keystone/blob/master/lib/fieldTypes/s3file.js#L271 https://github.com/LearnBoost/knox#put If someone is interested in adding this functionality comment below. @weekwood @webteckie

**Comment by morenoh149** [comment]
@weekwood any progress on this?

**Comment by weekwood** [comment]
@morenoh149 I will send PR tom

**Comment by morenoh149** [comment]
@weekwood if you don't have access to the keystone repo you can fork it and make the pull request from your own branch. See https://help.github.com/articles/using-pull-requests/

**Comment by weekwood** [comment]
![image](https://cloud.githubusercontent.com/assets/310350/5690565/3e8996fa-98cd-11e4-80df-d27c1c2d8829.png)
how can I update progress after I click save button, if I call 
```
this.props.paths.progress
```
it is only works after refresh page.. any way to make it real time update from React? add a **setInterval**?

**Comment by morenoh149** [comment]
Can you share what values you get if you add `console.log('progress is', amountProgress);` inside your `uploader.on()`

**Comment by weekwood** [comment]
I got 
```
progress is { percent: 0, written: 65536, total: 132178731 }

````

**Comment by morenoh149** [comment]
interesting! Now the issue is getting the data from the server to the react view. Perhaps a socket.io instance? ping @BerkeleyTrue

**Comment by morenoh149** [comment]
@weekwood two ways I can think of doing this.
* Use socket.io to do a pseudo push (or update) to the client (react component).
* Rerender the client with setInterval http://facebook.github.io/react/docs/displaying-data.html Would require the backend to respond with the current progress

pick one :)

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/show-upload-progress-in-adminui-for-uploads!
