### ISSUE TITLE
import_core3.graphQLSchemaExtension

### ISSUE THREAD

**Issue by sumitsharma7667** [keystonejs/keystone#8161]
While updating keystone to 7 december release  i am facing this error.
<img width="580" alt="Screenshot 2022-12-07 at 5 07 47 PM" src="https://user-images.githubusercontent.com/67309779/206170149-520d40ec-0120-481f-ac2b-6132bd98717a.png">
I tried with deleted the folders .keystone folder/node_modules/ or yarn.lock file but it not works for me.
Node -v 16.13.0 or 17.9.1  

"dependencies": {
    "@k6-contrib/fields-azure": "^3.0.1",
    "@k6-contrib/list-plugins": "^3.0.0",
    "@keystone-6/auth": "^6.0.0",
    "@keystone-6/core": "^4.0.1"
  },
"devDependencies": {
    "@types/node": "^18.11.11",
    "@types/speakeasy": "^2.0.7"
  }

**Comment by sumitsharma7667** [comment]
https://github.com/keystonejs/keystone/blob/main/examples/extend-graphql-schema-graphql-ts/schema.ts

**Comment by flexdinesh** [comment]
You're probably upgrading from `@keystone-6/core@2.x`. This is a breaking change with `@keystone-6/core@3.x`. More info in release notes here - [major release 19 October 2022](https://github.com/keystonejs/keystone/releases/tag/2022-10-19) and the specific pull request #7943.
