### ISSUE TITLE
Can't change host by server.options.host in keystone.ts in production mode (start)

### ISSUE THREAD

**Issue by mkastner** [keystonejs/keystone#8215]
In production:

I'm on a FreeBSD machine with the public ip XXX.XXX.XXX.XXX.
The keystone app runs in a Jail which has the IP 10.66.66.21.

Despite having set server.options.host in keystone.ts in production
to 10.66.66.21 the application starts up with an error (excerpt):

```
at processTicksAndRejections (node:internal/process/task_queues:83:21) {                                                            
  code: 'EADDRNOTAVAIL',                                                                                                                
  errno: -49,                                                                                                                           
  syscall: 'listen',                                                                                                                    
  address: 'XXX.XXX.XXX.XXX',                                                                                                           
  port: 3000                                                                                                                            
}        
```

I was hoping to be able to set the ip manually:

```
export default withAuth(
  config({
    db: {
      // the database options
    },
    // => The server.options.host 
    //       is never used. Instead I get host machine's IP
    server: {
      options: {
         host: '10.66.66.21',
      },
    },
    lists,
    session,
  })
);
```

The keystone app should use the ip set in server.options.host.

**Comment by dcousens** [comment]
@mkastner `code: 'EADDRNOTAVAIL'` seems to be pretty telling, 10.66.66.21 is not available to bind.  I don't know about your setup, but that seems to me that `server.options.host` _is_ being used?

**Comment by mkastner** [comment]
@dcousens I apologize for not having been clear. 

EADDRNOTAVAIL is saying that the server's **public IP address 'XXX.XXX.XXX.XXX'**  cannot be reached. The Xs stand for the ciphers of the public IP like 142.250.74.206 as opposed to 10.66.66.21 which is the local container address.

The keystone server never tries to bind to 10.66.66.21, instead it tries to bind to the host's public 142.250.74.206 (an example IP not my real one).

But it should not try to bind to 142.250.74.206 (again, not my real IP, just an example) but it should try to bind to 10.66.66.21.

And that happens, despite setting

```
    server: {
      options: {
         host: '10.66.66.21',
      },
    },
```
    
in keystone.ts in production mode.

**Comment by dcousens** [comment]
If you are in a container, _how_ can it attempt binding to your public address?

**Comment by borisno2** [comment]
Hi @mkastner 
I have had a go of this on Mac and `keystone start` is picking up this option correctly for me.
```ts
  server: {
    options: {
      host: '10.2xx.1xx.1xx',
    },
  },
```
and when starting I get
```bash
### % yarn start
yarn run v1.22.19
$ keystone start
✨ Starting Keystone
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Preparing Admin UI Next.js app
✅ Admin UI ready
⭐️ Server listening on 10.2xx.1xx.1xx:3000 (http://10.2xx.1xx.1xx:3000/)
```
and can confirm it is only running on that IP:
```bash
### % netstat -an | grep 3000
tcp4       0      0  10.2xx.1xx.1xx.3000    *.*                    LISTEN 
```

**Comment by mkastner** [comment]
@borisno2 Which keystone/core version are you using and which node version?

**Comment by borisno2** [comment]
@mkastner That is with the latest `@keystone/core` (4.0.1) and node version `v18.12.1` although I get the same result with node version `v16.18.1`

**Comment by mkastner** [comment]
@borisno2 D.... right you are!!! I f..... up big time. Of course it was the HOST variable. Echoing $HOST in the jail rendered the container host's hostname. Therefore nothing ever changed, no matter what I entered in keystone.ts' config.

I am now officially promoted from total moron to ultimate moron.

**Comment by mkastner** [comment]
@dcousens My bad. Hostname was passed on from the host to the container. In my ignorance I wasn't aware of that behaviour. I am really sorry for having wasted your time on a problem which was entirely based on my misconception and stupidity. Thanks for being so helpful and patient.

**Comment by dcousens** [comment]
Thanks for the write-up and reporting the issue @mkastner, although in the end it wasn't a bug, I guarantee you have helped many a weary traveler sometime in the future :yellow_heart:

**Comment by borisno2** [comment]
> @borisno2 D.... right you are!!! I f..... up big time. Of course it was the HOST variable. Echoing $HOST in the jail rendered the container host's hostname. Therefore nothing ever changed, no matter what I entered in keystone.ts' config.
> 
> I am now officially promoted from total moron to ultimate moron.

All good @mkastner glad we could help out to get to the bottom of it
