### ISSUE TITLE
Update Prisma to remove dependency on OpenSSL 1 (Railway & Ubuntu 22)

### ISSUE THREAD

**Issue by limegorilla** [keystonejs/keystone#8217]
Railway has updated their builder, nixpacks to v1. This major update migrates away from Debian 11 & OpenSSL 1 to Ubuntu 22 & OpenSSL 3. See [here](https://railway.app/changelog/2022-12-16-public-api-priority-boarding#:~:text=Please%20let%20us%20know%20if%20you%20encounter%20any%20issues.%20In%20particular%2C%20the%20upgrade%20to%20OpenSSL%203%20may%20have%20unexpected%20breaking%20changes%2C%20so%20be%20sure%20to%20reach%20out%20if%20you%20need%20a%20hand)

Current workaround is to set a railway variable `NIXPACKS_DEBIAN` to `1` which will re-enable OpenSSL 1.

Can we update our Prisma package to a version supporting OpenSSL 3 (https://github.com/prisma/prisma/releases/tag/3.13.0)

**Comment by borisno2** [comment]
Hi @limegorilla `@keystone-6/core` version `3.0.0` and later are using Prisma version `4.3.1`
What version of Keystone are you using that you are having issues with?

**Comment by marekryb** [comment]
While I am not using Railway, I also recently faced problem with Prisma/OpenSSL mismatch when building docker images based on alpine linux (https://github.com/prisma/prisma/issues/16553).

This was solved in Prisma 4.8.0 (https://github.com/prisma/prisma/releases). I am assuming this is the version that @limegorilla would like to update to.

+1 for updating Prisma.

**Comment by borisno2** [comment]
@marekryb we are currently working on upgrading to Prisma 4.8

**Comment by dcousens** [comment]
This issue is effectively tracking against https://github.com/keystonejs/keystone/pull/7964

**Comment by limegorilla** [comment]
> Hi @limegorilla `@keystone-6/core` version `3.0.0` and later are using Prisma version `4.3.1`
> What version of Keystone are you using that you are having issues with?

Apologies! Lost this in emails. Currently running `@keystone/core` version `3.0.2` (or newer - I definitely updated late December, I'm not sure what's happened there.)

@marekryb is correct, `4.8+` would fix this. As of commenting, #7964 is blocked by an issue with prisma & relationships in mySQL: https://github.com/prisma/prisma/issues/17103

**Comment by borisno2** [comment]
Prisma has been upgraded to 4.11 in #7964 and will go out in the next minor release

**Comment by borisno2** [comment]
Released in https://github.com/keystonejs/keystone/releases/tag/2023-03-02
