### ISSUE TITLE
Error: An error occurred when loading Admin Metadata

### ISSUE THREAD

**Issue by Delph** [keystonejs/keystone#8224]
When attempting to log in to the admin area, you are greeted by `Error: An error occurred when loading Admin Metadata`, coming from `useKeystone`, which in turn comes from `useAdminMeta`. Refreshing the page fixes the issue and you are logged in. Interestingly, I've been able to reproduce this fairly reliably in Firefox and rarely in Brave. In Brave on production (behind an nginx reverse proxy) it happens every time, which I've also reproduced locally, but I can't seem to fix.

Attempting to debug it in Firefox, stepping through `useAdminMeta` causes the issue not to occur, I believe there's a race condition between retrieving the data from the server and the client attempting to rerender.

Firefox 108.0 (64-bit)
Brave 1.45.127 Chromium: 107.0.5304.110 (64-bit)

**Comment by kayyali18** [comment]
https://github.com/keystonejs/keystone/issues/8223
Please see similar issue #8223

**Comment by borisno2** [comment]
See comment on #8223 Thanks!
