### ISSUE TITLE
Leaks internals when isAccessAllowed is false

### ISSUE THREAD

**Issue by alan-bradbury** [keystonejs/keystone#8270]
Set isAccessAllowed: (context) => false,

The internals shouldn't be leaked with the error messages if you can't login.

![image](https://user-images.githubusercontent.com/10155751/214128419-9c6423de-86e4-4c67-bc05-60b8ee34580f.png)

Microsoft Edge Version 109.0.1518.61

**Comment by borisno2** [comment]
Hi @alan-bradbury
I am unable to replicate this on `@keystone-6/core@4.0.1`, are you able to post some minimal steps to reproduce this error? Can you also share your keystone package versions?
Thanks

**Comment by alan-bradbury** [comment]
Interesting, here is my auth setup:

import { createAuth } from '@keystone-6/auth';
import { statelessSessions } from '@keystone-6/core/session';

const { withAuth } = createAuth({
    identityField: 'email',
    initFirstItem: {
        fields: [ 'username', 'email', 'password' ],
    },
    listKey: 'User',
    secretField: 'password',
    sessionData: 'id',
});

const session = statelessSessions({
    maxAge: 60 * 60 * 24 * 30,
    secret: '-- DEV COOKIE SECRET; CHANGE ME --',
});

export { withAuth, session };

and my keystone versions:

"@keystone-6/auth": "^6.0.0",
"@keystone-6/core": "^4.0.1",

It only happens when login is successful, but I don't know what it's trying to do at that point as it should be rejecting everyone.

**Comment by borisno2** [comment]
Maybe related to #8234 ??  Which we should be releasing soon

**Comment by borisno2** [comment]
Hi @alan-bradbury 
A new release went out last week with this fix, will close this issue now, please reopen it if you are still seeing this error
