### ISSUE TITLE
An error occurred when loading Admin Metadata [Production-only]

### ISSUE THREAD

**Issue by devmor-j** [keystonejs/keystone#8277]
### Reproduction Steps

1. Create a new keystone-app@9.0.0
2. build the project `npm run build` (though you could but you don't have to initialize the first user in dev mode)
3. start the project (`npm start`)
4. open the server (on `localhost:3000`)
5. initialize the app and create the first user (admin)
6. log out
7. log in
8. will show a button to **reload** the page and a thrown error on dev-tools console
9. reload the page it will work fine (but every login will repeat step-8)

**This only occurs on *production* build (*dev* is ok)**

#### Already Tried Solutions

- use not `secure` cookies (`secure: false`)
- have read these issues:
  - https://github.com/keystonejs/keystone/issues/8224
  - https://github.com/keystonejs/keystone/issues/8223
  - https://github.com/keystonejs/keystone/issues/4902
- https://gist.github.com/molomby/6fa22c165e0025f0f83d55195f3c6e37 which was informative but we don't use nginx on our stack we use apache2

### Expectation

Load admin panel without refresh (throw no error)

### Screenshot

> This shot was taken after pressing login button (user with correct username and password)

![Screenshot_20230128_101347](https://user-images.githubusercontent.com/88786674/215252784-2a254f4e-50fe-4fce-b75b-2d7bda6f9664.png)

### System

- Browser: Chrome v110.0.5481.24 (Official Build) dev (64-bit) 
- Linux: 5.15.85-1-MANJARO
- Node: v18.12.1

#### `Package.json`

```json
{
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall",
    "migrate": "keystone prisma migrate deploy"
  },
  "dependencies": {
    "@keystone-6/auth": "^6.0.0",
    "@keystone-6/core": "^4.0.1",
    "@keystone-6/fields-document": "^6.0.0",
    "axios": "^1.2.3",
    "compression": "^1.7.4",
    "http-errors": "^2.0.0",
    "slash": "^5.0.0",
    "typescript": "^4.9.4"
  },
  "engines": {
    "node": "^18.12.1"
  },
  "devDependencies": {
    "@types/http-errors": "^2.0.1"
  }
}
```

**Comment by Delph** [comment]
#8234 fixes this, but it's not yet been built with a new release.

**Comment by dcousens** [comment]
@Delph indeed! Hopefully only days away from the upcoming release now.

**Comment by borisno2** [comment]
Hi @Delph , A new release went out last week with this fix, will close this issue now, please reopen if you are still seeing this error
