### ISSUE TITLE
Unable to remove an image(or file) that doesn't exist

### ISSUE THREAD

**Issue by devmor-j** [keystonejs/keystone#8312]
### Repro

1- create an image model using `image` function from `"@keystone-6/core/fields"`
2- launch admin panel and create an image
3- manually remove that file on your system disk
4- try to remove or modify the image inside admin panel
5- throws an error related to `beforeOperation` hook

### Expectation

should be able to remove images or files even when the file physically does not exist.

### Shot

![Keystone-6 - Unable to remove an image(or file) that doesn't exist](https://user-images.githubusercontent.com/88786674/219022364-0ca90115-72fd-40db-83c6-2ef27914d03e.png)

### System

- Browser: Chrome v110.0.5481.24 (Official Build) dev (64-bit)
- Linux: 5.15.85-1-MANJARO
- Node: v18.14

#### Package.json

```json
{
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall",
    "migrate": "keystone prisma migrate deploy"
  },
  "dependencies": {
    "@keystone-6/auth": "^6.0.0",
    "@keystone-6/core": "^4.0.1",
    "@keystone-6/fields-document": "^6.0.0",
    "axios": "^1.2.3",
    "compression": "^1.7.4",
    "http-errors": "^2.0.0",
    "slash": "^5.0.0",
    "typescript": "^4.9.4"
  },
  "engines": {
    "node": "^18.12.1"
  },
  "devDependencies": {
    "@types/http-errors": "^2.0.1"
  }
}
```

Note: I have no hook on image model. I guess the `beforeOperation` hook (discussed above) is internal and related to keystone's stuff.

**Comment by dcousens** [comment]
Maybe, I'm not completely convinced this is an error that I would want to squash.
Why did you delete something manually?

**Comment by devmor-j** [comment]
Because of keystone's default option `preserve: false` we have links to images that no longer exist but we had lost them in an accident.

@dcousens

**Comment by dcousens** [comment]
@devmor-j I can understand that might result in this situation.

However, to squash this error by default could result in a situation - for example if something is misconfigured - where `image` fields are deleted without the corresponding files being deleted (as they could not be "found").

The end result is the same, something external is going wrong, and should be resolved; and in both instances I'd recommend manual reconciliation to prevent any further loss of integrity.

**Comment by dcousens** [comment]
@devmor-j maybe a helpful outcome could be a feature request for a script or utility that we could provide to help "reconcile" the database against your storage and vice versa.
