### ISSUE TITLE
v0.3.0: Implement the sticky toolbar in React

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#833]
We used to have a (custom) jQuery plugin that made the toolbar stick at the bottom of the screen when the item details view scrolled.

It needs to be re-implemented in React.

**Comment by BerkeleyTrue** [comment]
Can I call dibs on this?

**Comment by snowkeeper** [comment]
#850 added the previous code unless you want to see if it can be done in a different way.

**Comment by BerkeleyTrue** [comment]
Nah. This issue should be closed.
