### ISSUE TITLE
.keystone/types broken when list-level graphql.omit option provided

### ISSUE THREAD

**Issue by acburdine** [keystonejs/keystone#8349]
Full repo with reproduction here: https://github.com/acburdine/keystone-type-mismatch

1. Generate a new Keystone app
2. Modify one of the list schemas by adding the following:

```ts
list({ 
  fields: { /* ...list fields here */ },
  graphql: {
    omit: ["update"],
  }
})
```

3. Run `keystone postinstall --fix` to regenerate the built types
4. Notice type errors anywhere that list's type is referenced.

This definitely worked prior to `@keystone-6/core^5.0.0`, we noticed the type errors in our apps when upgrading to the latest version.

My guess is - the changes in [this commit](https://github.com/keystonejs/keystone/commit/7c723d9618e57ca4323fce808e5741172c522b5a) and [this commit](https://github.com/keystonejs/keystone/commit/7ebc68ebef2215e57f2317e9db9a50c68cf421a8) caused the removal of the previously-invalid "input" types from each list's generated "TypeInfo" type, thus making it such that it no longer "extends" from [BaseListTypeInfo](https://github.com/keystonejs/keystone/blob/5051e5a724f13008ce1b606858b565830f349b98/packages/core/src/types/type-info.ts#L6). This causes an individual list TypeInfo to no longer satisfy the generic type constraints required by many of the different Keystone schema building functions.

I'm not entirely sure what the best fix would be (otherwise I'd submit a PR with said fix 😉) - I _think_ making the different input fields [here](https://github.com/keystonejs/keystone/blob/5051e5a724f13008ce1b606858b565830f349b98/packages/core/src/types/type-info.ts#L12-L16) optional would do the trick? that may cause other issues, however.

As a semi-related sidenote, is there a reason the list-level graphql omit config wasn't changed to match the field-level syntax? As it currently stands, if you wanted to remove "create" from a specific field, and "update" from the whole list, you'd end up with a configuration like this:

```ts
list({
  fields: {
    somefield: text({
      graphql: {
        omit: { create: true }
      }
    }),
  },
  graphql: {
    omit: ["update"]
  }
});
```
other than the aforementioned typing issues, this config _works_ just fine, but it might be confusing to some to have one syntax in one spot and a different one in another 😅

**Comment by dcousens** [comment]
> is there a reason the list-level graphql omit config wasn't changed to match the field-level syntax

No, we'll have to put out a release to resolve that tomorrow.  We aren't adhering to the "breaking change" we have published so I think the update will be a patch.

> I think making the different input fields [here](https://github.com/keystonejs/keystone/blob/5051e5a724f13008ce1b606858b565830f349b98/packages/core/src/types/type-info.ts#L12-L16) optional would do the trick
I think you're right, but maybe not optional as the types don't actually exist. 
Maybe it's something else.

What we need to help that work though, is a configuration that can reproduce the problems you're experiencing.
I'll work on that tomorrow too :+1::yellow_heart:

**Comment by acburdine** [comment]
Submitted #8352 to fix the list-level graphql omit syntax.

Re: the typing issues, I found a solution that _works_, though I'm not sure how clean of a solution it is:

```ts
type CommonListTypeInputs = {
  where: GraphQLInput;
  uniqueWhere: {
    readonly id?: string | null;
  } & GraphQLInput;
  orderBy: Record<string, 'asc' | 'desc' | null>;
}

export type BaseListTypeInfo = {
    key: string;
    isSingleton: boolean;
    fields: string;
    item: BaseItem;
    inputs:
      | CommonListTypeInputs
      | (CommonListTypeInputs & { create: GraphQLInput })
      | (CommonListTypeInputs & { update: GraphQLInput })
      | (CommonListTypeInputs & { create: GraphQLInput, update: GraphQLInput })

    /**
     * WARNING: may be renamed in patch
     */
    prisma:
      | { [K in any]: never } // empty object type since {} doesn't work
      | { create: Record<string, any>; }
      | { update: Record<string, any>; }
      | {
          create: Record<string, any>;
          update: Record<string, any>;
        };

    all: BaseKeystoneTypeInfo;
};
```

I know it fixes the typing issues in my specific case, I'm not sure if it causes typing issues anywhere else in the codebase though 😬

**Comment by dcousens** [comment]
Thanks for the headsup @acburdine, something is wrong with our deployment.
[https://github.com/keystonejs/keystone/pull/8338](https://github.com/keystonejs/keystone/pull/8338/files#diff-c6f73c8ef17a064d650f34f59f7e1accea47cc773a0c423785a5134b5f5bed05) shows the `nextRelease` worked as expected.
