### ISSUE TITLE
Upgrade @keystone-6/core from 2.30 to 3.0.0

### ISSUE THREAD

**Issue by stefan9541** [keystonejs/keystone#8365]
I faced an error while trying to upgrade using yarn @keystone-6/core to 3.0.0 from ^2.3.0
The error might change depending on my tsconfig  target setting, this one I've got if I set it to "ES6"
Node version 14.9.0
![image](https://user-images.githubusercontent.com/45336682/222746021-f0869a42-3f5e-41ac-99f2-62deaa68716f.png)

Then if I changed it to "esnext" it starts complaining about all of my imports

![image](https://user-images.githubusercontent.com/45336682/222747475-db37be1c-74df-4b90-a936-64bd0ecc497e.png)

My tsconfig.json
![image](https://user-images.githubusercontent.com/45336682/222748793-8db20054-08e0-4ef1-9da1-1884b666218c.png)

Packages
![image](https://user-images.githubusercontent.com/45336682/222748880-6984c8c7-538a-45fd-8061-1e420b9c47d1.png)

**Comment by dcousens** [comment]
Hi @stefan9541, for posterity, what did you do to resolve your problem?
