### ISSUE TITLE
Storing a password using updateHandler

### ISSUE THREAD

**Issue by sabarasaba** [keystonejs/keystone#837]
Hello, I got a model with a password field and I'm trying to save data using the updateHandler but it always fails. The documentation for Type.Password says: 
```
{path}_compare - when provided to the updateHandler, it will be checked against {path} and validation will fail if they don't match."
```

But I couldnt get it to work. Could anyone provide an example of how would that work ?

**Comment by morenoh149** [comment]
issues must include reproducible code and copy of related error messages

**Comment by sabarasaba** [comment]
I'm just asking for a working example of something that you don't have on your documentation, no need for reproducible code.

**Comment by morenoh149** [comment]
@sabarasaba I guess what I was getting at was - what did you try? i.e. post your code so we can look at it and point out what's wrong

**Comment by JedWatson** [comment]
@sabarasaba there's a working example of updating a password field using the `UpdateHandler` in the SydJS site here: https://github.com/JedWatson/sydjs-site/blob/master/routes/views/me.js

The corresponding form code is here: https://github.com/JedWatson/sydjs-site/blob/master/templates/views/site/me.jade#L172-L182

Hope this helps. If you're still stuck, let us know more information about how you can't get it to work.

**Comment by sabarasaba** [comment]
Awesome, thats exactly what I was looking for. Thanks Jed ! :hand:
