### ISSUE TITLE
Unable to create JSON field in List Level Hook 

### ISSUE THREAD

**Issue by tommyboylab** [keystonejs/keystone#8377]
I am trying to add JSON data through a list level hook but am having an issue with Prisma throwing an error.

Currently my steps are related to creating a json field on an List designed for Images.
- Create a list with set of params (in my case name, alt, thumb, image, json)
- Create a list level hook which you add data to some fields (in my case thumb, json)
- Find that Prisma throws an error without any logging in console

- I should be able to populate the json field with json data. In my case it looks like the following:

```
  {
    Vibrant: [ 36, 193, 224 ],
    DarkVibrant: [ 35, 119, 140 ],
    LightVibrant: [ 250, 203, 108 ],
    Muted: [ 82, 132, 124 ],
    DarkMuted: [ 31, 56, 60 ],
    LightMuted: [ 188, 188, 188 ]
  }
```

This is output of resolvedData after transformation in `resolveInput` hook
```
{
  id: undefined,
  name: 'Test Image',
  altText: 'Testing',
  thumbnail: './public/images/7769d899-803b-46a2-b75a-e4b12887e159.svg',
  palette: {
    Vibrant: [ 36, 193, 224 ],
    DarkVibrant: [ 35, 119, 140 ],
    LightVibrant: [ 250, 203, 108 ],
    Muted: [ 82, 132, 124 ],
    DarkMuted: [ 31, 56, 60 ],
    LightMuted: [ 188, 188, 188 ]
  },
  image: {
    id: '7769d899-803b-46a2-b75a-e4b12887e159',
    extension: 'png',
    width: 2166,
    height: 1160,
    filesize: 608952
  }
}

```

This is Prisma
<img width="711" alt="Screenshot 2023-03-06 at 21 36 51" src="https://user-images.githubusercontent.com/44362297/223225074-6a20ba98-9242-43fa-a217-586df1525848.png">

I've determined the issue is with the json field as the same works just adding data to the thumb field.

**Comment by dcousens** [comment]
Hi @tommyboylab,

Can you please add a minimal reproduction configuration?
As is, I don't know how you're causing this problem.
