### ISSUE TITLE
endSession mutation doesn't end the session.

### ISSUE THREAD

**Issue by relusion** [keystonejs/keystone#8393]
1. KeystoneJS is deployed behind a reverse proxy (Azure Static Web App API), making it possible to access the GraphQL endpoint via https://domainname/api/graphql.
2. The user logs in using their credentials. A session is established, and a session cookie is created.
3. The user attempts to log off using the endSession mutation.
4. Even though the Graph API returns "true", the session cookie is not reset and the session is not terminated

When the endSession mutation executed the session cookie is reset and session is cancelled. Instead endSession returns "true" and does not reset  the session cookie.

I'll try to add screenshot later today.

**Comment by relusion** [comment]
it appears that there might be an issue with an Azure service not passing through the cookie. I am going to put this on hold for now, and I will update the issue once I have additional details.

**Comment by ganobrega** [comment]
Hi @relusion !

Maybe can be the `credentials` option in `fetcher`.

Look that code i'm using:
```
export const fetcher = (query, variables) =>
    axios
        .post(
            endpoint,
            { query, variables },
            { credentials: 'include', mode: 'cors' }
        )
        .then((r) => r.data.data);
```

**Comment by dcousens** [comment]
Cannot reproduce, please re-open if you can provide steps to re-produce
