### ISSUE TITLE
Common Middleware and Import Route Controllers

### ISSUE THREAD

**Issue by jjhesk** [keystonejs/keystone#840]
I think it would be more easy to implement api base by having done in this fashion when i edit the index.js in route folder:

```javascript

keystone.pre('api', middleware.initAPI);


var api = {
    A: importRoutes('./api/interface_1'),
    B: importRoutes('./api/interface_2')
}



exports = module.exports = function (app) {

    app.post('/api/A/additem', api.A);
    app.post('/api/B/addmoreitem', api.B);


};

```

Any thoughts?

**Comment by morenoh149** [comment]
is it anything like this? https://github.com/pillarjs/router https://pillarjs.github.io/ also btw @JedWatson express 5 will have the routing extracted out into its own middleware.

**Comment by mxstbr** [comment]
We're completely revamping the way you interact with the newly creating API in 0.4, and have big plans. I'll close this for now as it's on our radar!
