### ISSUE TITLE
Package vulnerabilities reported in npm audit

### ISSUE THREAD

**Issue by andrejmoltok** [keystonejs/keystone#8416]
Hello Dev team,

After installing, through `yarn add`, I've got 5 high severity vulnerabilities report upon npm audit.
If I `--force` the fix, it installes a previous version of the `core`, version 2.3.1 and yet the same vulnerabilities are reported.

Here they are:

`undici  <=5.19.0`
`Severity: high`
`Regular Expression Denial of Service in Headers - https://github.com/advisories/GHSA-r6ch-mqf9-qc9w`
`CRLF Injection in Nodejs ‘undici’ via host - https://github.com/advisories/GHSA-5r9g-qh6m-jxff`
`fix available via npm audit fix --force`
`Will install @keystone-6/core@2.3.1, which is a breaking change`
`node_modules/undici`
`  @prisma/engine-core  2.0.0-1 - 2.0.0-previewnull-1 || 2.0.1-1 - 2.0.1-dev.3 || 2.1.0-dev.1 - 4.12.0-integration-test-ecosystem-update.2`
`  Depends on vulnerable versions of undici`
`  node_modules/@prisma/engine-core`
`    @prisma/internals  <=4.12.0-integration-test-ecosystem-update.2`
`    Depends on vulnerable versions of @prisma/engine-core`
`    node_modules/@prisma/internals`
`      @keystone-6/core  <=0.0.0-rc-20230220024700 || >=3.0.0`
`      Depends on vulnerable versions of @prisma/internals`
`      Depends on vulnerable versions of @prisma/migrate`
`      node_modules/@keystone-6/core`
`      @prisma/migrate  3.0.3-dev.1 - 3.0.3-dev.2 || >=3.16.0-dev.1`
`     Depends on vulnerable versions of @prisma/internals`
`      node_modules/@prisma/migrate`

I am using the latest version of npm and node.js on Win10 laptop.

Thakns for taking tiime to look into this.

**Comment by borisno2** [comment]
Hi @andrejmoltok thanks for taking the time to report this, this is a known issue and more details can be found here #8356
