### ISSUE TITLE
Add color picker to color field

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#842]
This isn't a blocker but I'm logging it because I thought it was done.

The React color field had a number of issues (color preview not showing up, no picker, etc) - I've cleaned it up and it works properly now but I've disabled the picker control for now.

@sebmck want to have a look and see why it's not working? (other than the fact that I commented it out)

I thought you had it all up and running.

**Comment by jeremyzahner** [comment]
I guess this is not working atm?

**Comment by JedWatson** [comment]
@jeremyzahner we've added it in master, it'll be released with 0.4.0, this should have been closed :)

**Comment by riyadhalnur** [comment]
@JedWatson so  the fix isn't in v0.3 but in v0.4?
