### ISSUE TITLE
Issues with default Boolean values in createItems

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#843]
We suspect there may be an issue where `updateItems` is not respecting default Boolean values correctly, because `undefined` values are treated as a submitted `false` value by the field's `updateItem` method - see #841

The behaviour needs to be tested and, if it's an issue, we need to find a workaround that preserves our ability to respect `undefined` false values (as would be submitted by an HTML form)

**Comment by jjhesk** [comment]
@webteckie @JedWatson Good job. Keep up with the great work!

**Comment by JedWatson** [comment]
@webteckie from what I understand, the `doc` from the first reference and the one that's passed as the second argument to the save callback are exactly the same object. It's provided as an argument to the callback in case that is in a different scope and doesn't have access to the object that `save` was called on.

The code I was worried about is this block here:

```
_.each(list.fields, function(field) {
	// skip relationship fields on the first pass.
	if (field.type !== 'relationship') {
		field.updateItem(doc, data);
	}
});
```

All fields have their `updateItem` method called on the new document, which would set `Boolean` fields to false even when no value is provided.

However it looks like this check in `Boolean.updateItem` is ensuring the correct behaviour: `item.get(this.path) !== false`

So I'm now going to happily close this issue. Thanks for making sure it works correctly!

**Comment by webteckie** [comment]
@JedWatson just for completeness sake and so there's no confusion the second argument you see passed to the save callback is something I added here in this issue and it's not in the code...in case that's what you were referring to:-)

**Comment by JedWatson** [comment]
@webteckie I meant that mongoose passes the second argument for that reason, in your example above you add an argument to the function to receive it, whereas Keystone's implementation ignores it.

So all clear :)
