### ISSUE TITLE
nextjs example build error when deploying to Vercel

### ISSUE THREAD

**Issue by wchorski** [keystonejs/keystone#8430]
tried the 'build to vercel' button on the nextjs example (as well as the backend / frontend nextjs example)

```
Error: Build failed with 1 error:
--
15:04:58.144 | keystone.ts:2:30: ERROR: Could not resolve "./../example-utils"

```

**Comment by austinpickett** [comment]
yeah it looks like they're referencing this file: https://github.com/keystonejs/keystone/blob/main/examples/example-utils.ts

However, when I moved it into the project I got a slew of new errors:
`
<html>
<body>


https://nextjs.org/telemetry
--
09:42:36.770 |  
09:42:36.908 | info  - Skipping validation of types
09:42:36.908 | info  - Skipping linting
09:42:37.022 | info  - Creating an optimized production build...
09:42:53.309 | info  - Compiled successfully
09:42:53.313 | info  - Collecting page data...
09:43:00.545 | info  - Generating static pages (0/9)
09:43:00.605 | TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.
09:43:00.605 | at Html (/vercel/path0/.keystone/admin/.next/server/pages/_document.js:686:13)


</body>
</html>
`
