### ISSUE TITLE
Relationship mapping in update scripts

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone#844]
After many months away from Keystone, I'm back and redoing one of my earlier sites where Keystone was only used for part of the site. (and I wanted to play with the new shiny bits!)

However, I'm having issues with the create scripts. So I was reading #334 and decided that I liked what @LegitTalon was suggesting and thought I'd give it a go.

__My issue is in the update scripts how can I setup a User and populate a relationship (many) field type?__

So I have two update scripts:

### File: `./updates/0.0.1-roles.js`
``` javascript
exports.create = {
	Role: [
		{ name: 'Member' },
		{ name: 'Administrator' },
		{ name: 'Speaker' }
	]
};
```

### File: `./updates/0.0.2-admins.js`
``` javascript
exports.create = {
	User: [
		{ 'name.first': 'Admin', 'name.last': 'User', email: 'admin@keystonejs.com', password: 'admin', isAdmin: true, roles: [ 'Member', 'Administrator' ] }
	]
};
```

And the output is:
```
------------------------------------------------
Successfully applied update 0.0.1-roles.
------------------------------------------------
Applying update 0.0.2-admins...
------------------------------------------------
Update 0.0.2-admins failed with error:
{ type: 'invalid ref',
  srcData:
   { 'name.first': 'Admin',
     'name.last': 'User',
     email: 'admin@keystonejs.com',
     password: 'admin',
     isAdmin: true,
     roles: [ 'Member' ],
     __doc:
      { __v: 0,
        isAdmin: true,
        password: '$2a$10$u7xyETeUCeDUd2foAfhV2uGxH4wi9IygADLZPwtkk6wcU0dsPk0zW',
        email: 'admin@keystonejs.com',
        roles: [],
        name: { last: 'User', first: 'Admin' },
        _id: 54a3db35b1342dd31c34fd02 } },
  message: 'Relationship User.roles contains an invalid reference.' }
```

Which seems to be from [./lib/core/createItems.js#L225](https://github.com/keystonejs/keystone/blob/master/lib/core/createItems.js#L225)

**Comment by JedWatson** [comment]
@jamlen While we could simplify things by turning one of the properties (in your case `name`) into the `__ref` field, in a lot of cases it's less "safe" as keys are dynamically generated, fields can be validated or updated based on schema config, etc.

So in my opinion explicitly defining a `__ref` property in the update script is clunky but much clearer once you know to do it.

I'm open for suggestions on how we could do it otherwise syntactically, the one that comes to mind for me is:

```
exports.create = {
    Role: [
        { name: 'Member' },
        { name: 'Administrator' },
        { name: 'Speaker' },
    ],
    Role__ref: 'name',
    User: [
        { 'name.first': 'Admin', 'name.last': 'User', email: 'admin@keystonejs.com', password: 'admin', isAdmin: true, roles: [ 'Member', 'Administrator' ] },
        { 'name.first': 'Member', 'name.last': 'User', email: 'test-01@keystonejs.com', password: 'test', isAdmin: true, roles: [ 'Member' ] }
    ]
};
```

I'm not sure that's a huge improvement though.

We could alternatively allow object-syntax definition:

```
exports.create = {
    Role: {
        member: { name: 'Member' },
        administrator: { name: 'Administrator' },
        speaker: { name: 'Speaker' }
    },
    User: [
        { 'name.first': 'Admin', 'name.last': 'User', email: 'admin@keystonejs.com', password: 'admin', isAdmin: true, roles: [ 'member', 'administrator' ] },
        { 'name.first': 'Member', 'name.last': 'User', email: 'test-01@keystonejs.com', password: 'test', isAdmin: true, roles: [ 'member' ] }
    ]
};
```

**Comment by jamlen** [comment]
@JedWatson could we make use of the `autokey` if it is set on the list?

**Comment by eaton** [comment]
New to the project, but digging in deep and pretty impressed. I'm digging through the process of setting up a (fairly large) initial data load for a project, and ran into a similarly problem with references.

Barring the ability to specify a custom _id field for a schema ala mongoose, I think the object-syntax definition would be the next best thing. Referring to things by their incoming key in the import file feels a bit less magical than a __ref property that isn't actually persisted once the update is complete.

**Comment by mxstbr** [comment]
I'll close this due to inactivity, let me know if this should still be considered at the current state of things!

**Comment by Twansparant** [comment]
This method does not seem to work anymore in v4...
Any workarounds for this?

**Comment by mjimenezmartin** [comment]
Any news about this? Did anyone solve it for v4?

**Comment by pandey-mohit** [comment]
Any news about this? Did anyone solve it for v4?
