### ISSUE TITLE
Keystone needs a clean shutdown interface.

### ISSUE THREAD

**Issue by metasansana** [keystonejs/keystone#845]
Following up from #828. I'm now running into :
`Keystone failed to start: address already in use
Please check you are not already running a server on the specified port.`

This is logged when the start module detects `uncaughtException` with an error code of `EADDRINUSE`. The thing is, I'm calling `keystone.httpServer.close()`  after each test. So I should not
get this right?

I wrote some mocha tests to demo this error [here](https://gist.github.com/metasansana/6b67f9985e9b821808d0).

I have not been able to determine the code path in `start.js` that causes this (there is a lot going on in there) but I think a keystone native `shutdown` method will make integration and functional tests a lot easier.

I wrote a [similar](https://gist.github.com/metasansana/d4215508ad2e01e4fc21) set of tests using node's `http.Server` object just to compare, they work.

**Comment by metasansana** [comment]
Thanks @snowkeeper

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/keystone-needs-a-clean-shutdown-interface
