### ISSUE TITLE
Linter doesn't understand JSX

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#847]
@morenoh149 @sebmck 

New tests implementation looks great.

I've noticed that the linter is now throwing a lot of issues because it doesn't understand JSX though, is there a plugin or alternative package we can use that is JSX-aware?

Alternatively perhaps we should exclude the JSX files until we find a workaround, I think it's better to lint fewer files than a get bunch of false-positives in the report.

**Comment by sebmck** [comment]
There's [JSXHint](https://github.com/STRML/JSXHint/) (which also has a `--6to5` flag ;)).
