### ISSUE TITLE
Pages not found

### ISSUE THREAD

**Issue by adrianbienias** [keystonejs/keystone#8475]
A bunch of links placed in comments in Keystone source code reference to subpages of https://keystonejs.com/docs/apis/
Unfortunately, those pages (e.g. https://keystonejs.com/docs/apis/config#sqlite) show 404 Page Not Found.

In https://keystonejs.com/ footer, resources section links to https://keystonejs.com/docs/apis/ as well, and also to https://keystonejs.com/docs/guides that seems to be broken too.

**Comment by dcousens** [comment]
Should be fixed by https://github.com/keystonejs/keystone/pull/8476, please re-open if not
