### ISSUE TITLE
Model Events and schedules

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone#849]
I need to be able to add events and an event may or may not have a schedule. I've been trying to figure out the best way to model these in Keystone.

It seems to be a candidate for a new field type, so you can add the event details and then add the schedule items. You might also want to add multiple schedules for an event spanning multiple rooms or even campuses.

Has anyone already tackled this and how have you approached it?

Event registration will be something I'll need to consider at a later date too, but not right now!

**Comment by morenoh149** [comment]
We have an event model in our open source site. https://github.com/r3dm/shpe-sfba/blob/master/models/Event.js But it doesn't have everything you mentioned.

**Comment by morenoh149** [comment]
stale

**Comment by jamlen** [comment]
I would hardly call something that has been open for 13 days `stale`! I was hoping for input specifically on the Event -> Schedule relation and how to model that.

**Comment by morenoh149** [comment]
@jamlen 13 days since the last comment I made personally = stale in my book. But w/e.
Isn't this more of a software design question? Those are not issues. Should be directed towards the IRC channel, gitter, stackoverflow or google groups. IMO

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/model-events-and-schedules
