### ISSUE TITLE
How to translate the admin ui ? 

### ISSUE THREAD

**Issue by littlebang** [keystonejs/keystone#851]
Where can i find the admin ui ,and how to translate it with other language.
Thanks

**Comment by weekwood** [comment]
@littlebang follow http://keystonejs.com/zh/docs/getting-started/ to start.

**Comment by littlebang** [comment]
@weekwood I mean the Admin UIs,its auto generated

**Comment by weekwood** [comment]
@littlebang check out Fields, if you want.

**Comment by littlebang** [comment]
@weekwood  The modal have a label option can change the default display ,but if i want change the `Save` button's Text  ,or other action's label ,should be possible ?

**Comment by weekwood** [comment]
@littlebang  same as #834 ?

**Comment by littlebang** [comment]
Maybe not

**Comment by morenoh149** [comment]
@littlebang you're going to have to dig into the fieldtypes and manually change the display text until keystone adds support for i18n

For example a quick search for `save` through the code base spits out this https://github.com/keystonejs/keystone/blob/59bd164f6a68513f68462f85c3ab15417e369756/admin/src/views/item/index.js#L125 Change `Save` to whatever you want. Repeat until you translate the entire ui into your target language.

**Comment by morenoh149** [comment]
https://github.com/keystonejs/keystone/issues/802

**Comment by littlebang** [comment]
@morenoh149  Thanks

**Comment by wuhaixing** [comment]
@littlebang There is a post about How does KeystoneJS render it's Admin UI https://gist.github.com/wuhaixing/0cc7fcdaa1be3bc9f6d3 ,hope it’s help

**Comment by littlebang** [comment]
@wuhaixing  Get.
