### ISSUE TITLE
Select option expansion logic for arrays of strings is broken

### ISSUE THREAD

**Issue by simonswiss** [keystonejs/keystone#851]
I am creating a `Player` list with a `position` field using a `Select` type.

In my select, I have the 5 positions on a basketball court:

```javascript
keystone.createList("Player", {
  fields: {
    position: {
      type: Select,
      options: [
        "Point Guard",
        "Shooting Guard",
        "Small Forward",
        "Power Forward",
        "Center"
      ]
    }
  }
});
```

Doing so triggers the following errors:

```
Error: 
Enum value "PlayerPositionType.Guard" can only be defined once.
Enum value "PlayerPositionType.Forward" can only be defined once.
```

Same deal happens if I pass the options as an array of objects, or a comma separated string.

FWI My workaround was to pass a comma separated string with underscores instead of spaces (`"point_guard, shooting_guard, small_forward, power_forward, center"`) and let the `humanize()` method format it, but I don't think it's ideal!

**Comment by MadeByMike** [comment]
Possibly relates to #1768
