### ISSUE TITLE
File Preview not possible

### ISSUE THREAD

**Issue by TomKremer** [keystonejs/keystone#8538]
Hello,

I'm using s3 file uploads and I need to preview them in the browser. I tried embed or iframe but that doesn't work since files are uploaded with application/octet-stream. I want to preview pdfs and when I change the S3 metadata to application/pdf, both iframe and embed correctly show the file.

https://github.com/keystonejs/keystone/blob/1d0e6cdea6ecd3234ed24eb7c3b3794e0a9cfbca/packages/core/src/lib/assets/s3.ts#L66

Does anyone have an idea how to solve this issue?

Many thanks
Tom

**Comment by Rahulcheerio** [comment]
> Hello,
> 
> I'm using s3 file uploads and I need to preview them in the browser. I tried embed or iframe but that doesn't work since files are uploaded with application/octet-stream. I want to preview pdfs and when I change the S3 metadata to application/pdf, both iframe and embed correctly show the file.
> 
> https://github.com/keystonejs/keystone/blob/1d0e6cdea6ecd3234ed24eb7c3b3794e0a9cfbca/packages/core/src/lib/assets/s3.ts#L66
> 
> Does anyone have an idea how to solve this issue?
> 
> Many thanks Tom

Hi @TomKremer , Can you please explain this issue using any image , such that I can get to know for which things it is working for you and for what others not working .

Also @gautamsi , Can I work on this issue ?

**Comment by TomKremer** [comment]
Hi,
it's only when using the file storage (type: "file"). With images, the content type is correctly set, the issue only exists on files other than images. From what I found is that file extensions can't be trusted but I'm not clear on why this is restricted or what the security concern is.

**Comment by dcousens** [comment]
I have opened a feature request in https://github.com/keystonejs/keystone/discussions/8913, please add any commentary there
