### ISSUE TITLE
Admin list page shows empty results if one of the results field is NULL in the database

### ISSUE THREAD

**Issue by josemf** [keystonejs/keystone#8548]
Create a list with a few text fields. Run `yarn dev` to start the app. Add some contents to the list.

Modify one of the string fields in the database to be NULLABLE. Update one of the values so one of the string fields will have null value.

Go to the Admin app and verify the issue.

I would really hope that a string NULL value would not prevent all results from appearing in the list view for that list. Also if the list is in a many-to-many relationship it also breaks that other list edit view.
 

[Empty list image](https://ibb.co/d2rnY5D)

I'm using latest (as of 4th May 2023 keystone core 5.2, node 18, and Google Chrome).

A remark: While I understand keystone lists will make any string value as non nullable with a default of empty string, CMS migrations to KeystoneJS might make it impractical to enforce that on a consistent basis. 

Thank you for your help!

**Comment by dcousens** [comment]
Cannot reproduce this
```typescript
import { config, list } from '@keystone-6/core'
import { text } from '@keystone-6/core/fields'

export default config({
  db: {
    provider: 'sqlite',
    url: 'file:./issue-8548.db',
  },
  lists: {
    User: list({
      access: () => true,
      fields: {
        name: text({ db: { isNullable: true } })
      }
    })
  },
})
```

```json
{
  "name": "testing",
  "license": "MIT",
  "dependencies": {
    "@keystone-6/core": "^5.7.0",
    "@prisma/client": "^4.16.2"
  },
  "devDependencies": {
    "prisma": "^4.16.2"
  }
}
```
