### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by Sabanhe** [keystonejs/keystone#8554]
I created new project with keystonejs I created database and included database credentials in keystone.ts file. When I run yarn dev it in browser and in terminal I'm seeing the error message TypeError: Cannot read properties of null (reading 'useContext')

It should show admin login screen

Server Error
TypeError: Cannot read properties of null (reading 'useContext')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.useContext
file:///C:/Users/User/Documents/keystone/test/node_modules/react/cjs/react.development.js (1618:21)
useTheme
file:///C:/Users/User/Documents/keystone/test/node_modules/@keystone-ui/core/dist/keystone-ui-core.cjs.dev.js (839:13)
BaseCSS
file:///C:/Users/User/Documents/keystone/test/node_modules/@keystone-ui/core/dist/keystone-ui-core.cjs.dev.js (1286:7)
renderWithHooks
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8674:16)
renderIndeterminateComponent
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8748:15)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8983:7)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderNode
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9328:12)
renderChildrenArray
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9277:7)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9185:7)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9009:9)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderIndeterminateComponent
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8802:7)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8983:7)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderIndeterminateComponent
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8802:7)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8983:7)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderIndeterminateComponent
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8802:7)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8983:7)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderNode
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9328:12)
renderChildrenArray
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9277:7)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9185:7)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9009:9)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderNode
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9328:12)
renderChildrenArray
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9277:7)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9185:7)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9009:9)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderContextProvider
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8947:3)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9060:11)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderContextProvider
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8947:3)
renderElement
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9060:11)
renderNodeDestructiveImpl
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9149:11)
renderNodeDestructive
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (9121:14)
renderIndeterminateComponent
file:///C:/Users/User/Documents/keystone/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js (8802:7)

node -v v18.15.0

**Comment by unbywyd** [comment]
https://github.com/keystonejs/keystone/issues/8553

**Comment by molotow11** [comment]
@unbywyd 
Thanks so much!
For some reason, I am still have this error, even with `"next": "13.3.4"` in package.json
`TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react.useContext)(...)' as it is null.`

**Comment by gautamsi** [comment]
Use resolutions not just dependency
