### ISSUE TITLE
front-end error TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by jvinezof-viaconsulting** [keystonejs/keystone#8574]
I follow the steps of lesson 1 https://keystonejs.com/docs/walkthroughs/lesson-1 but instalation not working, on open localhost:3000 show this error:
![image](https://github.com/keystonejs/keystone/assets/41655632/38baf655-fe96-4133-b3b7-2ee3f309ed27)

My keystone.js code:
```
import { config, list } from '@keystone-6/core';
import { allowAll } from '@keystone-6/core/access';
import { text } from '@keystone-6/core/fields';

export default config({
  db: {
    provider: 'sqlite',
    url: 'file:./keystone.db',
  },
  lists: {
    User: list({
      access: allowAll,
      fields: {
        name: text({ validation: { isRequired: true } }),
        email: text({ validation: { isRequired: true }, isIndexed: 'unique' }),
      },
    }),
  },
});
```

Node Version: v16.18.0
Yarn Version: 1.22.19
@keystone-6/core Version: ^5.2.0

**Comment by rozsival** [comment]
This issue is related to #8575.
