### ISSUE TITLE
CLI build and prisma migrate commands never exit 

### ISSUE THREAD

**Issue by kam237zasada** [keystonejs/keystone#8581]
Just create new Keystone app with `yarn create-keystone-app` then try to execute command `yarn build` -> 'keystone build'

The expected behaviour is to build production ready output in `.keystone/admin` and **exit process** when this will be successfully done. But now the process is never exited even when build is done successful which is very inconvenient because basically there is no chance to go to another command when we want to deploy application - build hang out forever without exit after success.

<img width="567" alt="Screenshot 2023-05-18 at 08 17 29" src="https://github.com/keystonejs/keystone/assets/57039178/a93b41ea-b872-4d93-bbb9-f2941e40a6ec">

node version 16.19.1 but I also tried with newest LTS 18
next version - I tried with 13.2.2, 13.2.3, 13.3, 13.4.2 

But I believe that this is no related to other similar issues with hang out build command with:` info  - Creating an optimized production build ...` because I saw that this is related to some next versions above 13.2.3 and I also had that issue but figured it out changing next version, so the message disappeared after build but still build process is not exited.

When I simply added `process.exit()` in `keystone-6-core-scripts-cli.cjs.prod.js` at the end of function build which is responsible for that, everything went as expected.

Also there is the same issue with `keystone prisma migrate` CLI commands.

**Comment by velimd** [comment]
Hi, did you find a fix or any more info for this issue?

**Comment by kam237zasada** [comment]
@velimd Hi, the simplest workaround which I found is to create some `build.js `file in root directory, export build script from keystone and just add process.exit() after it will be executed, something like this:

```
const scripts = require("@keystone-6/core/scripts/cli");

(async () => {
  await scripts.cli(__dirname, ["build"]);
  process.exit();
})();
```

Then instead of using built-in `keystone build` I added custom simple script to package.json to execute build.js ->
```
"scripts": {
...
 "build": "cross-env NODE_ENV=production node build.js"
 }
 ```

**Comment by Arithmetics** [comment]
also seeing this

**Comment by nedgar** [comment]
Same. Thanks for the workaround.

**Comment by cyanonoob** [comment]
also seeing this, workaround worked. seems related to #8760

**Comment by ARkrOSClou** [comment]
```
  "overrides": { "next": "13.4.12" },
  "resolutions": { "next": "13.4.12" }
```
overrides for **npm**
resolutions for **yarn**
or both

**Comment by dcousens** [comment]
Maybe related to https://github.com/vercel/next.js/issues/54494
