### ISSUE TITLE
Text field isNonNull has defaultValue in graphql introspection query even though it is not given

### ISSUE THREAD

**Issue by nadaru-fr** [keystonejs/keystone#8594]
When adding `graphql: { isNonNull: { create: true } }` to a `text` field the introspection query generates a default value to `""` even though it is not filled

The problem with this is that my graphql codegen interprets a mandatory parameter with a default values as optional and defeats the purpose. 

Example:
```
    name: text({
      validation: { isRequired: true },
      graphql: { isNonNull: { create: true, read: true } },
    })
```

Generates
```
{
    "name": "name",
    "description": null,
    "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
            "kind": "SCALAR",
            "name": "String",
            "ofType": null
        }
    },
    "defaultValue": "\"\"", <--- Here's the issue (should be null)
    "isDeprecated": false,
    "deprecationReason": null
}
```

**Comment by borisno2** [comment]
Hi @nadaru-fr
Currently the default of `""` is used unless `db: { isNullable: true}` is also specified. 

So setting the following should resolve this for you.

```ts
    name: text({
      validation: { isRequired: true },
      graphql: { isNonNull: { create: true, read: true } },
     db: { isNullable: true}
    })
```

For more details on the background to this or if you want to provide feedback as to whether this behaviour should be different see #7158
