### ISSUE TITLE
Recommended architecture and implementation for long running tasks in Keystone

### ISSUE THREAD

**Issue by SharadKumar** [keystonejs/keystone#860]
Hi guys,
I am working on an app whose need is growing with time! 

We first required scheduled jobs, so we implemented some using [`agenda`](https://www.npmjs.com/package/agenda) and it worked out fine. Yes, so far running within the same process as web/Keystone!

Now while accommodating a new requirement to let web users upload a large CSV (500-50000 rows, about 25 columns with few KBs to MBs of size), we can see how current implementation is not suitable to simply parse that CSV in web process. It is clear that we need to put this and our jobs into a background process to scale any further and save crashes and serious bottlenecks we can see in dev.

So I started out researching options and modules for child process management, design and architecture approaches suitable for Node, and most importantly the considerations for a Keystone app. Within first 30 minutes I realised, too many options/modules, lot of chatter and not able to narrow down on one clear winner yet. So I think it is best to ask the community using Keystone on what practices and patterns are being followed for production class scalable apps. Any experiences, architecture or infra setup notes, and implementation details you can share in regards to Keystone or Node in general. Any references that I must read. How would you go about it, if you were tasked to?

Thanks in advance.

--Sharad

PS: Some of the links I found relevant are:
- https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node
- https://github.com/audreyt/node-webworker-threads
- http://nodejs.org/api/cluster.html
- https://github.com/LearnBoost/cluster

**Comment by morenoh149** [comment]
This is architecture and will require a lot of judgement calls. Some links:
http://gearman.org/
https://github.com/iarna/abraxas
http://zeromq.org/

If it's simple enough you could get away with forking a child process. And if the computation is cpu intensive you'll probably want to hand it off to a different lang/platform (c++/java/clojure/go/etc).
