### ISSUE TITLE
Keystone.connect() is broken

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#864]
Not sure if this was a change from moving from express 3 to express 4 or not. Currently an express 4 object has `name = ""`. The connect function checks that name = `app`. This function is brittle and should either change to blindly accept and assign from an options object OR eliminate the function altogether and delegate this responsibility to either the `init` or `set` methods.
If this function is kept, it should throw an error if no assignment was made `Error: Connect() was called but no connection was made`. 
![screenshot 2015-01-05 12 16 31](https://cloud.githubusercontent.com/assets/587438/5619322/94a9c524-94d5-11e4-982e-a04556cd0694.png)

**Comment by BerkeleyTrue** [comment]
@webteckie Are you using keystone to set routes? We are having major issues trying to add keystone into an existing isomorphic react/flux app. 

We would like to have keystone be as minimal as possible, but we are finding the keystone not playing nicely with the express server we have built up.

Basically we want keystone just for models and admin panel.

**Comment by webteckie** [comment]
@BerkeleyTrue The following sequence does not work for you?  It works fine for me.  Yeah, all routes are set via keystone.  Currently the express app doesn't do anything outside of keystone but I've set it that way just in case.  In the future I may just go with keystone's internal express app.

	var express = require('express')(),
		mongoose = require('mongoose'),
		keystone = require('keystone');

	var app = keystone.connect(express, mongoose);

	app.init( {...});

	app.start();

**Comment by BerkeleyTrue** [comment]
@webteckie You are basically using keystone without any modifications. The way you are using it there is no point in using the connect method. Just let keystone handle it.

We are trying to integrate an already existing express app without changing our whole structure. Thanks for your comments anyways.

Turns out keystone needs a lot of fixes to work stand with an existing express app.

**Comment by morenoh149** [comment]
:)
