### ISSUE TITLE
Fix jshints warnings and jscs violations

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#865]
I recently went in and fixed most of the jshint warnings in the codebase. Currently there are 24 warnings left but these are more interesting cases (unreachable code, global variable declarations, weird return values, etc). Fixing these would be great for a beginner
```

admin/src/components/toolbar.js
  line 43   col 33  Expected '!==' and instead saw '!='.
  line 43   col 62  Expected '!==' and instead saw '!='.
  line 45   col 48  Expected '!==' and instead saw '!='.
  line 52   col 56  Expected '===' and instead saw '=='.
  line 12   col 18  '$' is not defined.
  line 13   col 13  '$' is not defined.
  line 14   col 16  '$' is not defined.

admin/src/views/item/index.js
  line 155  col 1   Unnecessary semicolon.

fields/components/inputDate.js
  line 8    col 11  Label 'format' on YYYY-MM-DD statement.
  line 8    col 23  Missing semicolon.
  line 13   col 21  'Pikaday' is not defined.

fields/types/cloudinaryimage/cloudinaryimage.js
  line 60   col 6   'alert' is not defined.

fields/types/cloudinaryimages/cloudinaryimages.js
  line 120  col 5   'alert' is not defined.

fields/types/date/date.js
  line 23   col 17  Label 'formatString' on Do MMM YYYY statement.
  line 23   col 30  Missing semicolon.

fields/types/datetime/datetime.js
  line 28   col 17  Label 'formatString' on Do MMM YYYY, h:mm:ss a statement.
  line 28   col 41  Missing semicolon.

fields/types/embedly/embedly.js
  line 42   col 3   Unreachable 'return' after 'return'.

fields/types/html/html.js
  line 80   col 15  'i' is already defined.

fields/types/relationship/relationship.js
  line 109  col 19  Empty block.
  line 109  col 7   'field' is not defined.
  line 111  col 14  'field' is not defined.
  line 118  col 11  'value' is not defined.

lib/core/start.js
  line 188  col 28  'https' is not defined.

  ⚠  24 warnings
```
Moving forward. No new code should be accepted without corresponding tests and passing jshint.

**Comment by morenoh149** [comment]
closing this. I just realized the path to satisfying jshint and jscs will be very long.

**Comment by creynders** [comment]
@morenoh149 Probably you know this already, but just in case you don't; this will help with the major bulk of jshint errors: https://github.com/jshint/fixmyjs

**Comment by sebmck** [comment]
Just a quick note, but if you're refactoring `Expected '!==' and instead saw '!='.` be **extremely** careful as in some places the type inference is critical.

**Comment by morenoh149** [comment]
@creynders I didn't know that thanks!
@sebmck that makes me sad. I can't possibly analyze every instance of that myself. We really do need to expand the tests.

**Comment by BerkeleyTrue** [comment]
Someone in the know should go and mark those conditionals to be ignored by jshint.

**Comment by creynders** [comment]
For the moment I'd let those conditionals be what they are and jshint-tag them so jshint won't choke on them. With the tags it's easy to find them later on and replace them with `!==` if necessary

**Comment by morenoh149** [comment]
@creynders the big one is the code style errors from jscs. In the current master there are over 35,000 violations :(( Are there any tools for fixing those?

**Comment by creynders** [comment]
@morenoh149 not that I know of, unfortunately. With Webstorm you can manually set your preferences just so, and reformat all code, but unfortunately it won't read the settings automatically from a `.jscsrc` file. I got some time next Thursday, I'll have a look what results it'll produce. Things get a little complicated because of the jsx code in the views. Wouldn't it be better to give them a `.jsx` extension or something? ping @JedWatson

**Comment by metasansana** [comment]
@morenoh149 35,000 violations! Just curious; but it's not going into the `node_modules` folder right?

**Comment by morenoh149** [comment]
@metasansana pretty sure I ignore it here https://github.com/keystonejs/keystone/blob/master/Makefile#L6

**Comment by sillero** [comment]
+1 on @creynders suggestion about using `.jsx` instead of `.js`

just started fiddling with the keystone admin ui and that is the first thing I noticed. I usually use `.jsx` and that helps me visually identify react components and with packaging and validation

**Comment by morenoh149** [comment]
closing this issue there are no jscs rule violations given the current ruleset
