### ISSUE TITLE
`ui.listView.initialSort` prevents sorting by "No field"

### ISSUE THREAD

**Issue by devmor-j** [keystonejs/keystone#8687]
### Repro

1. Add initialSort field to ui like so:

```ts
export default list({
  ui: {
    listView: {
      initialSort: { direction: "DESC", field: "id" },
      ...,
```

2. Go to admin dashboard and disable sort (set to no field)
3. Sort won't disable and will stay on the initialSort field

### Expectation

Expect the sort to be disabled when I select the `No field` option.

### Env

Tested on Google Chrome Version 114.0.5735.198 (Official Build) (64-bit)
Node Version: 18.16.0

My `package.json`:
```json
{
  "dependencies": {
    "@apollo/server-plugin-landing-page-graphql-playground": "^4.0.1",
    "@keystone-6/auth": "^7.0.1",
    "@keystone-6/core": "^5.3.2",
    "@keystone-6/fields-document": "^8.0.0",
    "axios": "^1.4.0",
    "compression": "^1.7.4",
    "http-errors": "^2.0.0",
    "slash": "^5.1.0",
    "typescript": "^5.1.6"
  },
  "engines": {
    "node": "^18.16.0"
  },
  "devDependencies": {
    "@types/http-errors": "^2.0.1"
  }
}
```

**Comment by dcousens** [comment]
Replacing with https://github.com/keystonejs/keystone/pull/8909
