### ISSUE TITLE
Prisma 5 support

### ISSUE THREAD

**Issue by demsey2** [keystonejs/keystone#8705]
Prisma 5 has been released and provides a lot of improvements.

More info:
https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5
https://www.youtube.com/watch?v=6rlKp_eBdZA

Could you guys provide any insights about that? I would like to know if that has been talked about or planned already. Is that a significant change on your side? When can we expect Keystone to support it?

**Comment by dcousens** [comment]
The pull request https://github.com/keystonejs/keystone/pull/8693 is upcoming, but it will be a breaking change

**Comment by demsey2** [comment]
That's excellent news. Thanks for the quick update.

**Comment by iamandrewluca** [comment]
Released in https://github.com/keystonejs/keystone/releases/tag/2024-04-16
