### ISSUE TITLE
'tsx seed-data.ts' vs 'tsx seed-data.tsx'

### ISSUE THREAD

**Issue by cmuc24** [keystonejs/keystone#8708]
https://github.com/keystonejs/keystone/tree/main/examples/usecase-todo#optional-add-sample-data

works only with an update of package.json
from
https://github.com/keystonejs/keystone/blob/36185ae7976501e05d724c4f86f3bcd8a453f3aa/examples/usecase-todo/package.json#L11

to
"seed-data": "tsx seed-data.**tsx**"

**Comment by dcousens** [comment]
Thanks @cmuc24 , this was a mistake :)
https://github.com/keystonejs/keystone/pull/8709
