### ISSUE TITLE
Add Debug to files for fine grained debugging

### ISSUE THREAD

**Issue by BerkeleyTrue** [keystonejs/keystone#871]
[debug](https://github.com/visionmedia/debug) is an awesome module that allows fine grain debug output  with the addition of a environmental variable.

## Why?

Lets say you are trying to figure out why a list view is not rendering. You could pop open node-inspector and wait for the code to load, then step through the code, constantly pausing to check the value of objects. But with debug, you just start with DEBUG=keystone:routes:views:list node keystone.js and BAM! you got super awesome fun time debug logging of that single file printing out!

What do you guys think? I can start with a PR if the keystone community approves!

**Comment by wuhaixing** [comment]
+1

**Comment by JedWatson** [comment]
Sounds great, @BerkeleyTrue. :shipit:

**Comment by BerkeleyTrue** [comment]
Sweet! Will add to a couple of files.

**Comment by suqian1988** [comment]
how to print the debug messages into a file?
