### ISSUE TITLE
Field visible when `graphql.omit: true`

### ISSUE THREAD

**Issue by pc-erin** [keystonejs/keystone#8714]
### Steps to reproduce the problem

Create a text field.
Set `ui.itemView.fieldMode` to "hidden".
Set `graphql.omit.update` to `true`.

### What you expected to happen

The field is not visible.

### What actually happens

The field is still visible.

**Comment by dcousens** [comment]
@pc-erin can you please attach a screenshot and your schema?
I cannot reproduce this behaviour.

**Comment by tv42** [comment]
It seems the fix is wrong. See #9216.
