### ISSUE TITLE
Local Image storage

### ISSUE THREAD

**Issue by ginmartini** [keystonejs/keystone#872]
I would prefer to keep images on my own server, maybe with the possibly of other cloud options when traffic starts to grow. I don't have any experience with cloudinary.com, but making it dependent on third party service for core functionality makes me hesitant to use it. How hard would it be to implement own solution?

**Comment by morenoh149** [comment]
have you tried http://keystonejs.com/docs/database/#fieldtypes-localfile ?

**Comment by ginmartini** [comment]
No, I haven't. Sorry, my mistake.

**Comment by ViswanathLekshmanan** [comment]
Update in URL https://keystonejs.com/api/field/localfile
