### ISSUE TITLE
Move the "Style Guide" out of the Admin UI

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#872]
Whilst it's relevant to the Admin UI, it makes more sense to have the style guide be closer to the arch-ui packages on which it's based.

It also removes any confusion for developers who may land on that page / codebase and wonder what its purpose is.

For context, see: https://github.com/keystonejs/keystone-5/pull/867#issuecomment-474241440

**Comment by MadeByMike** [comment]
This is now your domain?

**Comment by timleslie** [comment]
Fixed in https://github.com/keystonejs/keystone/pull/1339
