### ISSUE TITLE
Use Code Style checker

### ISSUE THREAD

**Issue by BerkeleyTrue** [keystonejs/keystone#873]
Some options have been remove from jshint, such as trailing white space, as these have been deemed as stylistic choice. 

We could include [JSCS](https://github.com/jscs-dev/node-jscs) which will enforce code style choice that jshint will no longer support. There are also [AirBNB defaults](https://github.com/airbnb/javascript) available.

**Comment by JedWatson** [comment]
:+1:

**Comment by BerkeleyTrue** [comment]
alright! I'll make a PR soon.
