### ISSUE TITLE
Scrolling issue on desktop breakpoints

### ISSUE THREAD

**Issue by k9ordon** [keystonejs/keystone#8754]
Since the recent update to core@5.4.0, we have encountered an issue with scrolling on desktop breakpoints. It appears to be possibly related to the feature in PR #8702 @lahirurane-rau

Specifically:
- The sidebar is completely unscrollable.
- The main content can only be scrolled at the tablet breakpoint and lower.

To assist in diagnosing this issue, I've created a reproducible example on CodeSandbox: https://codesandbox.io/p/sandbox/keystone-6-sandbox-forked-mvtzcf

**Comment by dcousens** [comment]
Fixed in #8755 and #8702
