### ISSUE TITLE
Error: socket hang up (`keystone dev` on Windows)

### ISSUE THREAD

**Issue by devmanbr** [keystonejs/keystone#8756]
simply installing keystonejs according to the guide available on the website, when starting `npm run dev`, and, after the UI is generated, I see the following error in the terminal, and the process is terminated:
```
Failed to proxy http://127.0.0.1:51377/init Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at Socket.socketCloseListener (node:_http_client:420:25)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
}
unhandledRejection Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at Socket.socketCloseListener (node:_http_client:420:25)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
}
```

how to solve?

I've tried starting from scratch several times and to no avail.

**Comment by dcousens** [comment]
@devmanbr do you have this error when you use `keystone build` and then `keystone start`?

**Comment by devmanbr** [comment]
I've just tried. following the steps you provided, everything works. however, it is a process that takes a long time, and is very uncomfortable while developing an application, as it directly affects productivity.

is there any solution or insight as to what is causing the problem? I've spent hours trying to figure out why, and I haven't been able to determine.

ps. I currently use Windows

**Comment by dcousens** [comment]
I don't have any insight, unfortunately.

I don't have a Windows development environment either, so I can't attempt to reproduce the issue easily.

**Comment by devmanbr** [comment]
can someone from the team tell me if this has a possibility of correction?

**Comment by gautamsi** [comment]
Which guide did you follow? I work on Windows and do not see this issue. 

seeing this error - `Failed to proxy http://127.0.0.1:51377/init Error: socket hang up` shows it may be something else and not keystone.

**Comment by dcousens** [comment]
Without reproduction steps, I think I'll mark this as not resolved
