### ISSUE TITLE
Build command gets stuck

### ISSUE THREAD

**Issue by leonardodipace** [keystonejs/keystone#8760]
## Bug description
The `npm run build` command does not terminate and hangs indefinitely.

## Steps to reproduce
1. Run `npm run build` in the terminal.
2. Observe that the command does not finish and no error is thrown.

## Expected behavior
The `npm run build` command should complete successfully and produce an optimized production build.

## Screenshots
![image](https://github.com/keystonejs/keystone/assets/63299726/814d7cee-684a-49a7-a95b-e6cad58ee2c6)

## Environment
- Node version: v18.17.1
- OS: Debian on WSL

**Comment by nitoba** [comment]
the same problem here

**Comment by flippinjoe** [comment]
Pretty sure this is related to the latest next version. I resolved this problem with the following:
- Add overrides for next ```"overrides": { "next": "13.4.12" }```
- remove both node_modules & package-lock.json (or yarn.lock if you're into that thing)
- npm install 

Good to go

**Comment by Tekipeps** [comment]
@flippinjoe This doesn't work for me. I removed yarn.lock and node_modules then set the overrides in package.json but the build still gets stuck.

**Comment by ARkrOSClou** [comment]
> Pretty sure this is related to the latest next version. I resolved this problem with the following:
> 
> * Add overrides for next `"overrides": { "next": "13.4.12" }`
> * remove both node_modules & package-lock.json (or yarn.lock if you're into that thing)
> * npm install
> 
> Good to go

```
  "overrides": { "next": "13.4.12" },
  "resolutions": { "next": "13.4.12" }
```

overrides for npm 
resolutions for yarn

**Comment by ARkrOSClou** [comment]
> @flippinjoe This doesn't work for me. I removed yarn.lock and node_modules then set the overrides in package.json but the build still gets stuck.

```
  "overrides": { "next": "13.4.12" },
  "resolutions": { "next": "13.4.12" }
```
overrides for **npm**
resolutions for **yarn**
or both

**Comment by flippinjoe** [comment]
For yarn you'd have to do "resolutions" I believe

**Comment by dcousens** [comment]
https://github.com/vercel/next.js/issues/54494

**Comment by dcousens** [comment]
Fixed in https://github.com/keystonejs/keystone/pull/8788

**Comment by skindc** [comment]
Any news when this might be released?
