### ISSUE TITLE
UI relationship search error for `id` fields of type `Int`

### ISSUE THREAD

**Issue by linus-ha** [keystonejs/keystone#8784]
0.  `nvm use 18` Using node 18 as required by some dependency
1. `yarn create keystone-app test-ks` as recommended on your website
2. `cd test-ks`
3. edit `keystone.ts`, so that the database config looks like this:
```js
    db: {
      provider: 'postgresql',
      url: "postgres://postgres:password@localhost/testDb?schema=public",
      enableLogging: false,
      useMigrations: false,
      idField: {
        type: "Int",
        kind: "autoincrement",
      },
    },
```
4. start a clean local PostgreSQL DB via docker  
    `docker run -it --rm -p 5432:5432 -e POSTGRES_PASSWORD=password postgres`
5. `yarn dev` start keystone
6. Open http://localhost:3000/ , create your user, create a post and try to search in the author relationship field by any non-numeric character, for example, be the user's name.
7. → Error, as searching for string values on an integer ID field makes no sense (see UI's GraphQL query in the browser dev tools)

Searching by label field when connecting items in relationship fields (for example, the `name` field of users in create-keystone-app) should be possible in the UI (i.e. `Linus`). When searching by int-convertible search teams, everything works as expected (i.e. `1`).

![grafik](https://github.com/keystonejs/keystone/assets/30652341/87ec6342-a065-4beb-8bde-2e03eda8f82c)
![grafik](https://github.com/keystonejs/keystone/assets/30652341/c12190b3-4dd9-4c6c-bf25-f38ddae68432)

- Firefox
- node -v → v18.16.0
- yarn -v → 1.22.19
- keystone → 5.5.1

`package.json`
```json
{
  "name": "keystone-app",
  "version": "1.0.2",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone build --no-ui --frozen"
  },
  "dependencies": {
    "@keystone-6/auth": "^7.0.0",
    "@keystone-6/core": "^5.0.0",
    "@keystone-6/fields-document": "^7.0.0",
    "typescript": "^4.9.5"
  }
}
```

```
yarn keystone prisma -v
yarn run v1.22.19
$ /home/linus/temp/test-ks/node_modules/.bin/keystone prisma -v
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : rhel-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/libquery_engine-rhel-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/migration-engine-rhel-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by linus-ha** [comment]
As far as I understand, this could be fixed here: https://github.com/keystonejs/keystone/blob/32f7a6ad4a5a51a58988e7be495c96b06771b9b7/packages/core/src/fields/types/relationship/views/RelationshipSelect.tsx#L54
Therefore, we need to know the list's ID type. This info is not present in `ListMeta`.
If I miss something here, please let me know.

**Comment by tv42** [comment]
I worked around this by assuming that numeric ID fields are going to be autoincrement:

```diff
--- a/node_modules/@keystone-6/core/src/fields/types/relationship/views/RelationshipSelect.tsx	2023-09-10 12:28:11.929019205 -0600
+++ b/node_modules/@keystone-6/core/src/fields/types/relationship/views/RelationshipSelect.tsx	2023-09-10 12:42:13.917386661 -0600
@@ -50,7 +50,8 @@
 
     const trimmedSearch = search.trim();
     const conditions: Record<string, any>[] = [];
-    if (trimmedSearch.length > 0) {
+    // https://github.com/keystonejs/keystone/issues/8784
+    if (list.fields["id"].fieldMeta.kind == "autoincrement" && trimmedSearch.length > 0) {
       conditions.push({ id: { equals: trimmedSearch } });
     }
 
```

It's not perfect, but it keeps my CMS from crashing!

**Comment by tv42** [comment]
Actually, deploying this is a huge pain. How on earth do I tell npm to substitute my forked git repo for the `@keystone-6/core` dependency while also having my code change show up built in `dist/`? NPM can't cope with subdirectories (https://github.com/npm/npm/issues/2974), and if I use something like https://gitpkg.vercel.app/ it seems the package in the `packages/core` subdirectory doesn't know how to build itself? Or is there a magical incantation of scripts that works when you have only the subdirectory checked out?

**Comment by linus-ha** [comment]
I've used pnpm's/yarn's patch feature. Working great in CI
