### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by abhi-markan** [keystonejs/keystone#8830]
Keystone = Error: An error `occured` while resolving relationship fields.

Expect = Error: An error occurred while resolving relationship fields.

Please ensure you add spell check as part of your CI.

**Comment by dcousens** [comment]
Fixed by #8831

**Comment by dcousens** [comment]
> Please ensure you add spell check as part of your CI.

I actually haven't seen this before, do you have any examples?

**Comment by ttbarnes** [comment]
@dcousens Using [this package](https://www.npmjs.com/package/cspell) in a project, just need to setup a `.cspell.json`, can then add an npm script that can then be executed as part of github workflow. We found lots of spelling mistakes 😄

**Comment by dcousens** [comment]
@ttbarnes interesting, how is it discerning variable names from spelling mistakes?

**Comment by dcousens** [comment]
@ttbarnes are you open to adding that to our `.github` workflows? :)

**Comment by ttbarnes** [comment]
@dcousens i am planning to give it a go 😊 ❤️
