### ISSUE TITLE
Framework NextJS App Directory Database Change

### ISSUE THREAD

**Issue by wchorski** [keystonejs/keystone#8853]
## Problem

1. Initialized a project with [examples/framework-nextjs-app-directory](https://github.com/keystonejs/keystone/tree/main/examples/framework-nextjs-app-directory) 
2. Tried to change db to self hosted postgres instance
3. got error in the frontend

> [!error] Error: Unknown datasource postgresql provided to PrismaClient constructor.Available datasources: sqlite
Read more at https://pris.ly/d/client-constructor

## Config
`keystone.ts`
```ts
export default config({
  db: {
    provider: 'postgresql',
    url: DB_URL + envs.DB_COLLECTION + '?connect_timeout=300',
    onConnect: async (context: Context) => {
      await seedDemoData(context);
    },

    // WARNING: this is only needed for our monorepo examples, dont do this
    // prismaClientPath: 'node_modules/.myprisma/client',
  },
  server: {
    port: Number(envs.BACKEND_PORT),
    cors: { origin: [envs.FRONTEND_URL], credentials: true },
  },
  lists,
});
```

## backend 

I got the backend UI working fine by switching the port to `3001` instead and the data is persisted in `postgresql` database

Why is NextJS frontend still only accepts `sqlite` as a datasource?

Will this problem also carry over to production?

**Comment by borisno2** [comment]
Hi @wchorski 
The error you are receiving points to a mismatch between your Keystone config and the generated Prisma schema and client. When using Keystone's `getContext` - what is used by the `framework-nextjs-app-directory` example, when you change anything in your Keystone config (your `keystone.ts` file), you will need to get Keystone to regenerate the schemas and Prisma client, you do this by running `keystone dev` or `keystone build --no-ui`.

**Comment by wchorski** [comment]
Thanks @borisno2 for taking the time to help. 

When I started from the base files from the example and before I hit `npm install`, I changed out the database and endpoint. That seemed to do the trick.

The Prisma datasource didn't seem to update even though I'd run `npm run keystone:dev` when previously using the **sqlite** db
