### ISSUE TITLE
How to unit test models, views and routes?

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone#888]
Dusting off #216 I wondered if there was any progress on it but also how are people going about testing their models, views and routes? Some documented guides would be nice and actually the Yeoman Generator should scaffold tests with the appropriate keystone helpers.

I am especially interesting in testing the `models` and `views`.

Have any of you written any `keystone-helpers` for testing?

**Comment by morenoh149** [comment]
@jamlen you're asking how to test your project's models/views/routes correct? We should add a userland test suite to the generators and example keystone sites. We could learn together @jamlen currently reading http://mochajs.org/

**Comment by dgitsio** [comment]
Hi @jamlen and @morenoh149 ,

I have a similar need to start testing the models in my project and here's [a gist](https://gist.github.com/dgitsio/21f8172ce828112f0ee2) that steps through a process that helped me get started.  It's definitely a hack, based on just copying some code from the KeystoneJS/keystone project itself, but bereft of a formal approach it's letting me move forward.  I hope it's useful!

**Comment by JohnnyEstilles** [comment]
I'm not sure if I'm speaking out of school here, but it seems to me that tests such as the gist generously shared by @dgitsio test Keystone core functionality (which we should be testing within Keystone itself), and not your application code (for which I'm a firm believer we should all be writing tests).

That said, I think its a great idea to move our existing helpers in to a `keystone-helpers` module we could all `npm --save-dev install` into our Keystone apps to assist us with unit testing.

My two centavos ... :-)

**Comment by dgitsio** [comment]
@JohnnyEstilles Yes you are right that gist confuses the issue of wanting to test one's own application Keystone Lists since it runs using a List from core; I was going for brevity by not including a custom List but not the best example for sure.

In the hopes of isolating an application's Lists for testing, today we run into problems following [@JedWatson's otherwise helpful advice on stackoverflow from March](http://stackoverflow.com/questions/22231078/how-do-i-unit-test-keystonejs-models) since I think executing calls like ```keystone.import('models');``` require Cloudinary config, etc. to be coupled in with our efforts.  Also having to deal directly with mongoose seems suboptimal given the goals of List/Item abstraction.

More thought and effort over time will hit upon better testing solutions, I'm sure.

**Comment by celiao** [comment]
Any more progress or insights on the issue of unit testing?

**Comment by webteckie** [comment]
@celiao I had a similar need to unit test my models.  Eventually came up with https://www.npmjs.com/package/keystonejs-stub  So far it meets my needs.  I published it in case it may help someone else.

**Comment by celiao** [comment]
@webteckie thanks for the tip.  In my case, I wanted to keep Keystone intact to the extent possible.  Here's what I came up with to test my Mongoose plugin named `AutoCounter`, which I use to add a counters to my Keystone models as needed.  I wouldn't mind getting feedback, as I'm new to Javascript, MongoDB, Mongoose, and KeystoneJS.  Hopefully it will help @JedWatson and the community consider features needed for a Keystone test framework. Also worth mentioning for ideas is the [Django test framework](https://docs.djangoproject.com/en/1.8/topics/testing/), which is easy-to-use and full-featured, and includes test databases, test clients for APIs, fixtures, in-memory email, factories, etc.  I would love to avoid dipping down to Mongoose, and have more commonly-used patterns available as Keystone-level commands (wouldn't we all!).
```
var expect = require('must');
var mongoose = require('mongoose');
var async = require('async');
var _ = require('underscore');

var keystone = require('keystone');
var Types = keystone.Field.Types;

var autoCounter = require('../../models/AutoCounter')

describe('AutoCounter', function() {
    var testName = 'testAutoCounter'; // Will be name of test database
    var testModelName = 'Test';

    before(function(done) {
        keystone.init({
            'name': testName,
            'cookie secret': 'YOUR SECRET COOKIE HERE',
        });
        keystone.start();
        done();
    });

    afterEach(function(done) {
        // Delete test model, as used in keystone/test/helpers/removeModels.js
        delete mongoose.models[testModelName];
        delete mongoose.modelSchemas[testModelName];

        // Drop collections in test database
        mongo = keystone.get('mongo');
        var conn = mongoose.createConnection(mongo, function(err) {
            var collections = _.keys(conn.collections);
            async.series([
                function(callback) {
                    async.forEach(collections, function(collectionName, cb) {
                        var collection = conn.collections[collectionName];
                        collection.drop(function(err) {
                            if (err) { cb(err); }
                            cb(null);
                        });
                    });
                    callback(null);
                },
                function(callback) {
                    conn.close(function(err) {
                        if (err) { callback(err); }
                        callback();
                    });
                }], function(err) {
                    if (err) { done(err); }
                    done();
            });
        });
    });

    after(function(done) {
        // keystone.stop();

        // Drop test database
        mongo = keystone.get('mongo');
        var conn = mongoose.createConnection(mongo, function(err) {
            conn.db.dropDatabase(function(err) {
                conn.close(function(err) {
                    if (err) { done(err); }
                    done();
                });
            });
        });
    });

    function defineModel(options) {
        Test = new keystone.List('Test');
        Test.add({ 'number': { type: Types.Number } });
        Test.schema.plugin(autoCounter, options);
        Test.register();
    }

    function createItem(callback) {
        Test = keystone.list(testModelName);
        newTest = new Test.model();
        newTest.save(function(err) {
            if (err) {
                console.error('Error adding test to the database.');
                callback(err);
            } else {
                console.log('Added test to the database.');
                callback();
            }
        });
    };

    it('must require an autoCounterList option', function() {
        function missingOption() {
            options = { 'path': 'number' };
            defineModel(options);
        }
        missingOption.must.throw('autoCounterList option required.');
    });

    it('must require a path option', function() {
        function missingOption() {
            options = { autoCounterList: 'testNumberCounter' };
            defineModel(options);
        }
        missingOption.must.throw('path option required.');
    });

    it('must start counter at 1 and increment by 1', function(done) {
        options = { autoCounterList: 'testNumberCounter', path: 'number' };
        async.series([
            function(callback) {
                defineModel(options);
                callback(null);
            },
            function(callback) {
                createItem(callback);
            },
            function(callback) {
                createItem(callback);
            },
            function(callback) {
                keystone.list(testModelName).model.find()
                        .exec(function(err, tests) {
                    expect(err).must.be.null;
                    (tests.length).must.eql(2);
                    (tests[0].number).must.eql(1);
                    (tests[1].number).must.eql(2);
                });
                callback(null);
            },
        ], function(err) {
            if (err) { done(err); }
            done();
        });
    });

});
```

**Comment by webteckie** [comment]
@celiao I believe you're doing some sort of integration testing.  That's not what the keystonejs-stub npm is for; it is for unit testing individual modules, which eliminates any external dependencies (e.g., mongo db) and only calls for mocking direct SUT module's dependency methods.  I also do integration testing and do not use keystonejs-stub for that; instead, I use the actual software as would be ran in production.

**Comment by ericelliott** [comment]
Here's how I'm testing routes in the `universal-keystone-boilerplate`:

```
import test from 'tape';
import request from 'supertest';
import keystone from 'test/helpers/keystone';

const app = keystone.app;
const route = '/';

test(`GET ${ route }`, assert => {
  assert.test(route, assert => {
    const msg = 'should not return an error';

    request(app)
      .get(route)
      .expect(200)
      .end(err => {
        assert.error(err, msg);
        assert.end();
      });
  });
});
```

From there, it's easy to run assertions against the response body. We should also add cross-browser testing with something like Sauce Labs, but some minimal route testing is a good first step.

**Comment by morenoh149** [comment]
these are free for OSS https://www.browserstack.com/pricing & https://saucelabs.com/opensauce/

**Comment by morenoh149** [comment]
@ericelliott we want something like your route tester here? https://github.com/keystonejs/keystone/blob/master/test/lib/server.http.test.js#L5

**Comment by ericelliott** [comment]
@morenoh149 I suggest we mimic the [functional route tests from the Universal Keystone Boilerplate](https://github.com/ericelliott/universal-keystone-boilerplate/tree/master/source/test/functional/routes).

Note that they actually launch a real Keystone app server *with a database connection*, and then close them when they're done.

I think we should also mimic the folder structure: `test/functional/routes`.

**Comment by ericelliott** [comment]
@JedWatson What's with the TODO comment in that test? If the test fails, why doesn't it fail the builds?

**Comment by mxstbr** [comment]
@webteckie has done a ton of work on this, so I'll close this for now as we don't need the issue to remind us to do it. :+1:
