### ISSUE TITLE
Keystone repo VSCode devcontainer build fails

### ISSUE THREAD

**Issue by sharrief** [keystonejs/keystone#8880]
Summary 
_VSCode_ devcontainer.json specifies Node v14 but Node >=16.14 required for pnpm

### Repro
1. Install VScode, Docker Desktop
2. Clone keystonejs repo
3. Open repo in VSCode
4. Re-open the repo in a VSCode devcontainer

**Expected**
Container builds and runs post install commands successfully
**Actual**
Container build fails when running  "postCreateCommand": "pnpm install"

Screenshot of VSCode terminal after failing to build container:

![image](https://github.com/keystonejs/keystone/assets/17752660/dc190130-0f1a-417f-a3ad-c3d4d057603b)

Host OS is MacOS Sonoma 14.0, Apple Silicon

**Comment by sharrief** [comment]
### Fix

- Set `build.args.VARIANT` in devcontainer.json to Node version "16". 

**OR**

- Remove `args.Variant` from `build` in devcontainer.json. Set `VARIANT` in Dockerfile to "16"

The `build.args` set in devcontainer.json seem to override `ARG` in Dockerfile. I don't think the arg needs to be set in both places, but perhaps there are other non-devcontainer systems that rely on the Dockerfile.

In any case, I am looking to start contributing to Keystone by tackling some bugs and documentation. Would like to make the change to this/these files my first Github OSS PR if that's alright 😁

**Comment by ggpwnkthx** [comment]
This should be fixed by #9104
