### ISSUE TITLE
keystone prisma migrate dev broken in latest version

### ISSUE THREAD

**Issue by yorkeJohn** [keystonejs/keystone#8888]
Keystone version: 5.7.0

Steps to reproduce:
1. Run `npx keystone prisma migrate dev` from a local terminal
2. See error message "Error: Prisma Migrate has detected that the environment is non-interactive, which is not supported."
3. Run `npx keystone prisma migrate reset --force` to reset the database
4. Run `npx keystone prisma migrate dev` again. When prompted "Enter a name for the new migration", no input can be made
5. The only way to exit the command is to press ctrl+C

Expected behaviour:
1. Run `npx keystone prisma migrate dev` from a local terminal
2. Get prompted to enter a name for the migration
3. A new migration is generated

Workaround:
Downgrade to Keystone 5.5.1 (might be able to go newer, but this was the working version that I had in another project)

**Comment by stuible** [comment]
I imagine this has the same cause as my issue: https://github.com/keystonejs/keystone/issues/8858

**Comment by dcousens** [comment]
Fixed in #8898, will be published soon

**Comment by yorkeJohn** [comment]
When is this targeted for release?
