### ISSUE TITLE
Add graphql voyager link to admin UI

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#890]
GraphQL voyager is a handy way to visual the relationship between lists in a keystone system.

It might be a useful addition to support in the same way that we support the graphiql interface. I haven't looked into this very deeply, but it looks like there are react components we could drop in to the appropriate place.

https://github.com/APIs-guru/graphql-voyager

To see voyager running on your schema at the moment, you can follow these steps:

 1. https://apis.guru/graphql-voyager/
 2. Click "Custom Schema"
 3. Click "Copy Introspection Query"
 4. Go to your graphiql console and hit Ctrl-V to paste the introspection query
 5. Execute the query, copy the result, and paste it into the form on the graphql voyager website

Having a one click way to achieve all this from the Admin UI would be 👍

**Comment by schickling** [comment]
@timleslie do you want to visualize the Keystone (data) schema or the generated GraphQL schema?

We're currently sketching out similar things for Prisma Admin:

![image](https://user-images.githubusercontent.com/1567498/55276069-2270f400-52ef-11e9-85ae-b41d945e8d3e.png)

**Comment by timleslie** [comment]
@schickling In this particular instance I'm thinking about the problem of visualising the graphQL schema itself, rather than the internal Keystone schema. This is useful in the case where you're in the middle of doing development and want to see how things are structured at the API level.

I agree that it would also be cool to have a tool which could work at the Keystone level, where there are more interesting and complex concerns, such as access-control and hooks.

**Comment by JedWatson** [comment]
I love the idea of generating a view like that of the Keystone schema. Especially if we could render additional meta (like access control and hooks), would give a really helpful overview of the setup!
