### ISSUE TITLE
Add tool to check for dead links in website/docs

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#892]
It's all too easy when updating the docs content to move/rename/edit a file in such a way that breaks a link somewhere.

It would be great to come up with a solution for this. It could be either a static analysis tool or a dynamic web crawler which runs over the netlify deploy during CI. These decisions are left an exercise for whoever chooses to pick up this issue 👍

**Comment by molomby** [comment]
I took a lightweight/prototype-like swing at this with the [`markdown-link-check` package](https://www.npmjs.com/package/markdown-link-check). It works ok.

Create a `config.json` with either this, which catches links with incorrect casing:

```json
{"replacementPatterns": [{ "pattern": "^/", "replacement": "https://github.com/keystonejs/keystone/tree/master/" }]}
```

Or with your own working directory path, which allows local change that aren't in master but might not catch incorrect casing if your filesystem isn't case-sensitive enough:

```json
{"replacementPatterns": [{ "pattern": "^/", "replacement": "/Users/molomby/projects/keystone/keystone-5/" }]}
```

Then run something like:

```sh
find . -name \*.md \
  ! -path '*/.changeset/*' ! -path '*/node_modules/*' ! -path '*/CHANGELOG.md' \
  -exec markdown-link-check --config config.json --quiet {} \;
```

Of course, this assumes our links use local file paths, not the doc site URL paths -- see #2041.

**Comment by molomby** [comment]
Related #2820

**Comment by timleslie** [comment]
Fixed by https://github.com/keystonejs/keystone/pull/4969 🚀
