### ISSUE TITLE
Implement new design for React LocalFiles field

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#895]
To complete #782

Should also update the `LocalFile` design to match

![screen shot 2015-01-13 at 12 02 15 pm](https://cloud.githubusercontent.com/assets/872310/5714410/4eb3a330-9b1c-11e4-8e37-cbdd1e1bb5cc.png)

**Comment by jjhesk** [comment]
this is very nice. I think if the color can be customized with a easy change location that will be perfect and people dont need to hack around in order to get the nice result.

**Comment by JedWatson** [comment]
@jjhesk yes, with or shortly after 0.3.0 you will be able to include your own stylesheet and override the LESS variables Keystone uses to style the Admin UI.

**Comment by tenhaus** [comment]
It doesn't look like support for the format field was written in. Am I missing it?

**Comment by sebmck** [comment]
Impossible since it’s rendered clientside.

**Comment by tenhaus** [comment]
Sorry, but I'm trying to find a way to write my own rendering code. The format field was in the documentation. What's the best way to plug in and render my own fields?

**Comment by morenoh149** [comment]
@tenhaus custom fieldtypes? Don't think we're there yet.

**Comment by tenhaus** [comment]
For example, I'd like to change the admin ui rending of a local file to show a preview of the file (if it's an image)

**Comment by tenhaus** [comment]
If I could just catch calls to fields.js and point the LocalFile react code to my own code, that would be wonderful

**Comment by tenhaus** [comment]
It looks like I should fork?

**Comment by morenoh149** [comment]
@tenhaus do whatever you want it's OSS. Just don't rebrand and pass it off as a new project. That's not nice.
