### ISSUE TITLE
Using Turborepo with KeystoneJS with a Nextjs package version higher than 13.4.12 breaks redirects

### ISSUE THREAD

**Issue by tommyboylab** [keystonejs/keystone#8950]
Issue originates form here:
https://github.com/keystonejs/keystone/discussions/8949

I'm trying to use Turbo to run a Keystone / NextJS app dir  application and found an issue with re-directs after updating the package version beyond 13.4.12. Specifically `Fast Refresh had to perform a full reload`

Example is taken from `@keystone-6/example-framework-nextjs-app-directory` with reworked Prisma and next.config.js / keystone.ts to add rewrites to `/admin` . 

Inspiration was taken from `borisno2/on-the-hill-drama-club` and uses similar next.config.js (without ts-gql)

rewrites should redirect me to the admin page from localhost:3000/admin to localhost:4000/admin

![Screenshot 2023-12-08 165734](https://github.com/keystonejs/keystone/assets/44362297/41b55ede-de88-49ef-bab2-eff7f5dc18c8)

Node: 20.10.0
NextJS (in screenshot): 14.0.4

Tried setting NODE_ENV to catch errors but there isn't any

Nextjs Changelogs
https://github.com/vercel/next.js/releases/tag/v13.4.13

**Comment by borisno2** [comment]
Hi @tommyboylab 
I don't use Turbo for dev, I know the command is there but it has never really worked for me. I tend to run each command in `@borisno2/on-the-hill-drama-club` (`dev:watch` `dev:keystone` `dev:next`) separately as `dev:watch` (`keystone dev --no-server` removes the files next files required for `dev:keystone` while it is starting up. I am running nextjs 14.0.4 thought and am not seeing this particular error.

**Comment by tommyboylab** [comment]
Hi @borisno2 thank you for your answer.. I was finding that Turbo was working as I expected it to before 13.4.12, anything afterwards ended up with this error once visiting the /admin redirect. I think it has something to do with the baseURL changes in 13.4.13 but I can't be sure.


I'll follow your suggestion and run each separately -- and thank you for the example provided by `@borisno2/on-the-hill-drama-club` as it helps me visualize the structure of a monorepo application built with Keystone.

**Comment by tommyboylab** [comment]
Found this is an issue with how NextJS past 13.4.13 spawns in a separate child process.

While I'm not going to look into how to implement a check for the existence of Keystone in the creating of the client, I beleive something like this could be used to implement a fix for this issue and fix issues with Turbo repos.

Just thanking Payload here for discovering this and ended up with a similar issue. 
https://payloadcms.com/docs/local-api/overview#nextjs-conflict-with-local-api

Closing this ticket now as it needs to be implemented for this specific use case.
