### ISSUE TITLE
Node 20 (LTS) support

### ISSUE THREAD

**Issue by Josef-Reichardt** [keystonejs/keystone#8987]
Project setup fails on node 20 (current LTS - with yarn and npm) because of a dependency which is not compatible to node 20:

```sh
@keystone-6/core > @prisma/migrate > mssql > tedious > @azure/identity > @azure/msal-node@1.18.4

error @azure/msal-node@1.18.4: The engine "node" is incompatible with this module. Expected version "10 || 12 || 14 || 16 || 18". Got "20.4.0"
```

I've created the app via `yarn create keystone-app` and the setup proceeds with `npm` automatically because it fails with `yarn`:

![grafik](https://github.com/keystonejs/keystone/assets/1203740/21524c12-b413-4efa-863f-4acec351fe73)

But after that, when I remove `package-lock.json` and `node_module` because I want to work with `yarn` instead of `npm` and run `yarn install` it reports the following error:

![grafik](https://github.com/keystonejs/keystone/assets/1203740/2b24bc39-4e07-463b-b494-d464d38b1c00)

`npm install` only displays a warning for that:

![grafik](https://github.com/keystonejs/keystone/assets/1203740/6b8198eb-f15f-4705-bfff-657913e49437)

Tested on node v20.4.0 and v20.11.0.

**Comment by dcousens** [comment]
Probably the best option for this is to resolve that dependency, if you aren't using it, to nothing

**Comment by Josef-Reichardt** [comment]
Yes, this works. Thanks for the workaround but it's not a very good first use experience. The reason is that `@keystone-6/core` uses `@prisma/migrate` version `4.16.2` (the latest version is `5.8.1` at the moment).

Are there plans to update this dependency?

---
I have solved it by the mentioned workaround for now in my `package.json`:

```json
{
  ...
  "dependencies": {
    "@keystone-6/auth": "^7.0.0",
    "@keystone-6/core": "^5.0.0",
    "@keystone-6/fields-document": "^7.0.0",
    "typescript": "^4.9.5"
  },
  "resolutionsComments": {
    "@prisma/migrate": "Required until https://github.com/keystonejs/keystone/issues/8987 is resolved!"
  },
  "resolutions": {
    "@prisma/migrate": "5.8.1"
  }
}
```

This displays a warning but it seems to work.

```
warning Resolution field "@prisma/migrate@5.8.1" is incompatible with requested version "@prisma/migrate@4.16.2"
```

**Comment by fkrauthan** [comment]
Any updates on this?

**Comment by iamandrewluca** [comment]
A workaround we did is to stub that package completely with an empty package as we use `postgresql` only

**packages/mssql/package.json**

```json
{
	"name": "mssql",
	"version": "9.1.1"
}
```

Then install it explicitly

```bash
npm install mssql@file:packages/mssql
```

**Comment by Forux** [comment]
Problem is still there and yes it is strange first time experience

**Comment by Jeanclaudeaoun** [comment]
Got it to work like this instead @Josef-Reichardt 
or maybe this only fixed the issue in my case since i am using yarn workspaces

```json
{
  "name": "keystone-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone build --no-ui --frozen"
  },
  "dependencies": {
    "@keystone-6/auth": "^7.0.0",
    "@keystone-6/core": "^5.0.0",
    "@keystone-6/fields-document": "^7.0.0",
    "typescript": "^4.9.5"
  },
  "resolutions": {
    "**/@azure/msal-node": "2.7.0"
  }
}
```

**Comment by dcousens** [comment]
@Jeanclaudeaoun we have updated `prisma` in the newest major of `@keystone-6/core: ^6.0.0` - can you update to that instead?

**Comment by gautamsi** [comment]
@dcousens should this be unpinned and replaced with 22 LTS version of issue, I remember seeing some problems but that may be my own specific config.

**Comment by dcousens** [comment]
Maybe lets simply make a pull request that bumps to `22`?
