### ISSUE TITLE
WYSIWYG indent switched?

### ISSUE THREAD

**Issue by peteruithoven** [keystonejs/keystone#900]
Looks like the WYSIWYG editor's indent button icons are switched? 
![screen shot 2015-01-13 at 23 10 37](https://cloud.githubusercontent.com/assets/523210/5730348/afd42b50-9b79-11e4-99a6-08ed32e8cdf8.png)

**Comment by morenoh149** [comment]
lol confirmed

**Comment by sebmck** [comment]
What branch/version are you on? Hopefully I didn't do something stupid with #796

**Comment by peteruithoven** [comment]
I installed it trough using the generator (yeoman):
```
npm install -g generator-keystone
yo keystone
```

**Comment by JedWatson** [comment]
Looks like this has been the case for a little while. Whoops! I'll fix it now in master
