### ISSUE TITLE
Calling GraphQL api consume multiple connections

### ISSUE THREAD

**Issue by ChuckJonas** [keystonejs/keystone#9002]
I have an app connected to a heroku pg hobby instance (max 20 connections).  When I hit a GraphQL endpoint, I see the connections spike from 1 up the 20 and the request fails with error "too many connections"

I expect that backend would retain the single connection across all API calls.

Some of the fields I am querying are "virtual" and make `query` calls to 

```
const { roasts } = await context.query.Coffee.findOne({
            where: { id: item.id.toString() },
```

**Comment by ChuckJonas** [comment]
Looks like I misunderstood how [primsa handles connection pooling](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections#optimizing-the-connection-pool).  

Adding a `?connection_limit=15` query param to the pg connection string solved the issue.

**Comment by dcousens** [comment]
@ChuckJonas maybe https://github.com/keystonejs/keystone/discussions/9010 could help, `Prisma` can be difficult sometimes
