### ISSUE TITLE
EPERM: operation not permitted, unlink query_engine-windows.dll.nod

### ISSUE THREAD

**Issue by AliEmili** [keystonejs/keystone#9035]
- cloned my project which is working on linux distros, on my windows 11
- npm i
- after installing packages it seems to build and post install

in mentioned step it faces an error:

Error: EPERM: operation not permitted, unlink 'blah blah\node_modules\.prisma\client\query_engine-windows.dll.node'] {
  code: -32000,
  data: {
    stack: "Error: EPERM: operation not permitted, unlink 'blah blah \\ node_modules\\.prisma\\client\\query_engine-windows.dll.node'"
  },
  name: 'GeneratorError'

- node version v20.11.1 
- npm version 10.2.4 
- keystone core version: ^5.7.2

**Comment by gautamsi** [comment]
this has been bugging me for long see https://github.com/prisma/prisma/issues/9184

**Comment by iamandrewluca** [comment]
To be closed in favour of issue mentioned above.
