### ISSUE TITLE
Choose coding style

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#905]
Re https://github.com/keystonejs/keystone/pull/884
any of these http://jscs.info/overview.html#presets or a custom one for keystone

**Comment by creynders** [comment]
@morenoh149 I've just been experimenting with jshint, jscs, editorconfig and code style preference sets in Webstorm for one of my own projects. I think it's pretty doable to get everything uniform. Webstorm goes a long way in a) pointing out errors against any of the configured rules b) fixing these automatically. Not all errors are fixed automatically unfortunately (yet?)

Anyway, once a code style has been chosen I'll gladly _try_ to get the entire code base to adhere to it, unless you want to do it yourself.

**Comment by creynders** [comment]
Oh, and if it works, I think it's a good idea to share the Webstorm code style preset file for others to use as well.

**Comment by morenoh149** [comment]
@creynders definitely you could do it! I don't think there would be an easy way for myself to do it (I use vim)

**Comment by creynders** [comment]
@morenoh149 AFAICT the jscs docs are wrong/unclear regarding the `disAllowMultipleVarDecl` rule. It says it's equal to jshint's `onevar` rule, but the example they provide as "valid" would not pass the `onevar` rule, which _does_ have to do with variable hoisting.

I have no idea whether it's WAI or a bug, but actually it's the opposite of the `onevar` rule, i.e. you can't declare multiple variables with a single var statement. Meaning, this is valid:

```
var a="foo";
doSomething();
var b="baz";
// fails `onevar`, passes `disAllowMultipleVarDecl`
```

However, this is not:

```
var a= "foo",
  b="baz";
// passess `onevar`, failes `disAllowMultipleVarDecl`
```

WAI or not; very confusing, to say the least.

**Comment by morenoh149** [comment]
what's WAI?

**Comment by creynders** [comment]
Works as intended

**Comment by JedWatson** [comment]
I've implemented ESLint with appropriate config, and it lints our JSX as well which is great. Currently working through the warnings list with @vitalbone and @leo7568.
