### ISSUE TITLE
About setting cookie Issue

### ISSUE THREAD

**Issue by linhanyang** [keystonejs/keystone#906]
I want to set up so that two domain names to share session information, whether you can configure Cookie domain options，How to configure it?

for example：
www.example.com
bbb.example.com

**Comment by andrewlinfoot** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)
