### ISSUE TITLE
Add ability to stage changed content for publication

### ISSUE THREAD

**Issue by lojack** [keystonejs/keystone#909]
Right now, if a user edits published content, the changes go live immediately. Frequently, an editor may want to change an already published piece of content, and want to save their changes to either preview or finalize their content and publish at a later date.

Two related issues, #320 and #608 could then allow users to preview unpublished/staged content prior to publishing.

**Comment by morenoh149** [comment]
This could be done by adding a boolean to the model `draft`. In your app have a global setting `ShowDrafts` and in your view have a conditional
```
if (Environment.ShowDrafts === true && post.draft === true) {
  // render drafts
}
```

**Comment by lojack** [comment]
@morenoh149 that works if the content has never been published. What I'm trying to address is content that is already published, and a draft revision is created. If we simply have a boolean field, then that would unpublish the published content any time you set the boolean to draft.

This could potentially be easily accomplished with Document Versioning. If something like #244 is merged, then all that'd need to be done is set the default state to "Unpublished" when creating a new version, and verify that the most recent published version of the content is what's visible on the frontend.

**Comment by morenoh149** [comment]
ah versioning! sounds good. Will probably merge that pull request sometime in 0.3.x After the react and express 4 upgrades land.

**Comment by tivac** [comment]
http://prismic.io supports this, and it seems pretty great.

**Comment by morenoh149** [comment]
@lojack https://github.com/keystonejs/keystone/issues/244 landed

**Comment by JedWatson** [comment]
#244 doesn't really solve this, I'm putting it on the backlog while we work on core features for 0.4. Should be easier to see a way to generically implement it after that release.

**Comment by Mentioum** [comment]
Also interested in support for this.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/add-ability-to-stage-changed-content-for-publication
