### ISSUE TITLE
Field.updateItem() incorrectly handles undefined (blank form fields), can't set DB

### ISSUE THREAD

**Issue by danielmahon** [keystonejs/keystone#913]
the field update currently skips any `undefined` field, which includes blank text fields... which dont get updated to the DB

has this come up yet? I cant be the first to notice it, seems too important ;)

https://github.com/keystonejs/keystone/blob/ce66dc972927b3f4ac2e2de32ba2cb0354f89f25/fields/types/Type.js#L327-L343

**Comment by danielmahon** [comment]
looks like it may be a problem with the React template not sending the empty string value to the POST request

**Comment by danielmahon** [comment]
OK, React is sending the form-data properly, body-parser is parsing (as designed) and removing blank keys, this means when the form-data object reaches the `updateItem` function the key doesnt exist and returns `undefined`. You have an if statement excluding `undefined` values from being set. 

```
	// This is a deliberate type coercion so that numbers from forms play nice
	if (value !== undefined && value != item.get(this.path)) { // jshint ignore:line
		item.set(this.path, value);
	}
```

if I change to the following it works, what was the reason for filtering out `undefined` values?

```
	// This is a deliberate type coercion so that numbers from forms play nice
	if (value != item.get(this.path)) { // jshint ignore:line
		item.set(this.path, value);
	}
```

**Comment by JedWatson** [comment]
The theory for ignoring undefined values in `updateItem` was (from memory) so you could submit _some_ values without having it null-out any values you hadn't provided.

I.e. making data processing work more or less the same way this does:

```
mything.field1 = 'new value';
console.log(mything.field2); // 'value_2'
mything.save(function() {
    console.log(mything.field1); // 'new value'
    console.log(mything.field2); // 'value_2'
});

Looks like the body-parser has changed its behaviour, it certainly didn't used to remove blank keys... there's a big difference between submitting a blank value and not submitting a value at all, we should be able to differentiate between them.

**Comment by sebmck** [comment]
@danielmahon Is this happening on multipart POST requests?

**Comment by danielmahon** [comment]
Yes. Though no file need be selected.

- -

*Daniel Mahon*mahonstudios.com <http://www.mahonstudios.com/> |
daniel@mahonstudios.com
Mahon Studios

**Comment by sebmck** [comment]
Would most likely be a result of multer doing

```javascript
req.body = qs.parse(req.body);
```
