### ISSUE TITLE
"telemetry disable is an unknown command"

### ISSUE THREAD

**Issue by DavidMulder0** [keystonejs/keystone#9289]
Run `npx keystone telemetry disable`

Telemetry should be disabled. Instead `"telemetry disable is an unknown command"` is outputted.

OS Name: Microsoft Windows 11 Enterprise
OS Version: Windows 10.0.22621 N/A Build 22621
Node Version: v20.10.0

**Comment by DavidMulder0** [comment]
Minor thought, the right thing to do might be to discard any telemetry data collected from the period this command was broken.

**Comment by dcousens** [comment]
Fixed in #9290
