### ISSUE TITLE
'Parameter schema or schemaPath must be passed' error when running npm run dev after @keystone-6/core update to 6.2.0

### ISSUE THREAD

**Issue by JoinThisBand** [keystonejs/keystone#9294]
**Summary**

Updating @keystone-6/core from 6.1.0 to 6.2.0. and running `npm run dev` or `npm run build` throws error `Parameter schema or schemaPath must be passed`. Full error from `npm run dev` below.

Rolling back update to @keystone-6/core@6.1.0 removes error / builds successfully.

    ✨ Starting Keystone
    ⭐️ Server listening on :3000 (http://localhost:3000/)
    ⭐️ GraphQL API available at /api/graphql
    ✨ Generating GraphQL and Prisma schemas
    Error: Parameter schema or schemaPath must be passed.
        at Object.formatSchema (/node_modules/@prisma/internals/dist/engine-commands/formatSchema.js:48:11)
        at getArtifacts (/node_modules/@keystone-6/core/dist/createExpressServer-aedf6d31.cjs.dev.js:346:40)
        at Object.generateArtifacts (/node_modules/@keystone-6/core/dist/createExpressServer-aedf6d31.cjs.dev.js:356:27)
        at /node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js:1045:39
        at initKeystone (/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js:1129:6)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Expected Behaviour**

Keystone dev server starts successfully or production build completes successfully.

**Additional Info**

Node version v18.19.0 but also attempted with v20.10.0.

Many thanks!

**Comment by borisno2** [comment]
Hey @JoinThisBand - what version of Prisma do you have installed? I got this error when I had Prisma pinned to 5.13 once I changed to 5.18 - the latest - the error went away.

**Comment by JoinThisBand** [comment]
Ah thanks for the tip @borisno2 - I'll give that a try and report back.

**Comment by JoinThisBand** [comment]
Found the problem - I'd added some overrides to package.json, which I think came from a thread on the Keystone Slack channel, to allow an Prisma to be updated.

    "overrides": {
      "@prisma/client": "5.4.1",
      "@prisma/migrate": "5.4.1",
      "@prisma/internals": "5.4.1"
    }

Have removed this and everything is working great now.

Thanks for the pointing me in the right direction and to you and the team for all your work!
