### ISSUE TITLE
Number field doesn't allow decimals

### ISSUE THREAD

**Issue by snawbel** [keystonejs/keystone#930]
Great project!

This kills my attempts at inputting a decimal number: 

`var newValue = event.target.value.replace(/[^\d]/g, '');`

It wouldn't be too hard to cobble together a more permissive regexp, but I wanted to check if that's the way to go before submitting a PR?

**Comment by JedWatson** [comment]
Thanks @snawbel, I've just tweaked that RegExp to allow decimals.

**Comment by snawbel** [comment]
Thanks. (I could have made a PR but wasn't sure how much of a strict "valid number" check the RegExp should be.)
