### ISSUE TITLE
CodeMirror text area full screen (F11) not working properly

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#931]
You should be able to do F11 in the CodeMirror Types.Code text area but doing so has the wrong behavior.  The whole Admin UI screen goes full screen and not just the text area.  See http://codemirror.net/demo/fullscreen.html for feature.

**Comment by mxstbr** [comment]
I'm pretty sure this is fixed now, feel free to comment again if you're still having this issue!

**Comment by moledet** [comment]
still not work 14/09/2016 chrome

**Comment by sxlwar** [comment]
[http://codemirror.net/demo/fullscreen.html ](url)

not work
