### ISSUE TITLE
v0.3.0:  Code Field support for CodeMirror Language Modes

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#934]
Continuing on with Code Field enhancements ( #933 #835 #546 ) I think that the Code Field editing experience would be better if it supports CodeMirror Language Modes (see http://codemirror.net/mode/index.html).  Once a proper language has been configured for the lang option in the Code Field keystone should imply and use a corresponding Language Mode.

**Comment by JedWatson** [comment]
Is this related to #834?

**Comment by webteckie** [comment]
@JedWatson definitely they are all related but I chose to add issues for each feature in case it may be useful to split the work.   Not sure.  If you feel it is all one big feature then feel free to consolidate :-)  By the way, I would work on it in my spare time (minimal) but I would need a WIKI section title something like "Adding/Updating a Keystone Field" that outlines all the areas that must be considered when adding/updating a keystone field--perhaps you can put one together?  But I'm hoping someone faster and more knowledgeable can pick these up :-)
