### ISSUE TITLE
Meeting in San Francisco, Jan 23rd - Feb 2nd 2015

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#935]
Hi everyone,

Sorry for using our issue tracker for this, but I couldn't think of a better way to reach the broader Keystone community. (might be a good idea to start a mailing list!)

I'll be travelling from Sydney to Silicon Valley for the React.js conference (28th and 29th Jan) and staying in San Francisco for a few days on either side - arriving on Friday the 23rd and flying out on Feb 2nd.

Since it'll be my first trip to the US in a very long time, it would be great to meet up with people (or companies) who are using KeystoneJS in and around SF while I'm there.

If you're up for a chat, coffee, drink or whatever (I'll certainly be spending time working on Keystone while I'm there) ping me at jed at keystonejs.com.

**Comment by morenoh149** [comment]
yes!
