### ISSUE TITLE
Cryptic error message for unrelated `MODULE_NOT_FOUND` error

### ISSUE THREAD

**Issue by marekryb** [keystonejs/keystone#9358]
```typescript
// schema.ts
import { list } from '@keystone-6/core'
import { type Lists } from '.keystone/types'
import { value } from 'non-existing-module' // <------

export const lists = {
  Test: list({
    fields: {},
    access: () => value,
  }),
} satisfies Lists
```
This is compiled without any error by esbuild (`.keystone/config.js`)
```javascript
// schema.ts
var import_core = require("@keystone-6/core");
var import_non_existing_module = require("non-existing-module");
var lists = {
  Test: (0, import_core.list)({
    fields: {},
    access: () => import_non_existing_module.value
  })
};
```
But when you do any keystone command (dev/build), it results in very cryptic message:
```
(base) exar@exar:~/os/keystone/examples/omit$ pnpm build

> @keystone-6/example-omit@ build /home/exar/os/keystone/examples/omit
> keystone build

🚨 keystone build has not been run
 ELIFECYCLE  Command failed with exit code 1.
```
Above is simplest reproduction, but actually I am hit by this every now and then in a project where I have `paths` defined in `tsconfig.json`. Editor does not report any error since module resolve fine in 'normal' context.

I am pretty sure this returned some actually helpful error message some versions ago. Will check later.

**Comment by dcousens** [comment]
Related code can be seen -> https://github.com/keystonejs/keystone/blob/main/packages/core/src/scripts/utils.ts#L16

We aren't filtering errors well enough
