### ISSUE TITLE
Finish TinyMCE Wysiwyg Field Implementation

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#936]
There are some things left to complete the WYSIWYG field added in #929:

- [ ] Allow options to be provided from the field to TinyMCE (so users can customise the toolbar, plugins, etc)
- [ ] Review default toolbar items and plugins (anyone have any suggested changes?)
- [ ] Finish the docs
- [ ] Can we get focus styling for the field, and should we make any other theme tweaks?
- [ ] Add integration tests

**Comment by jesstelford** [comment]
- [ ] When loading the static assets, respect any `adminPath` the user has set.

**Comment by JedWatson** [comment]
> respect any adminPath the user has set.

Good catch, I thought of that when I was coding it but forgot to add it to the list. Late nights 😉 

This is actually pretty tricky to pull off because it requires passing config from the Admin UI to the Field and persisting it (we need this value to end up all the way in the `Editor` component)

But I'm keen to see if we can do it!

Just to show how far we've come, check out all the tinymce-specific wysiwyg options that were on Keystone back in v4: https://keystonejs.com/documentation/configuration/admin-ui-options/

These are global keystone config keys 😱

Some of the things in the new TinyMCE field type are a little bit convoluted compared to how this all worked before in a monolithic project, but I'm really loving how well we've implemented our separation of concerns and the whole extensibility in Keystone 5 😁

**Comment by jesstelford** [comment]
> we need this value to end up all the way in the Editor component

There's a mechanism for this baked into #874: `process.env.assetPrefix`

> Just to show how far we've come

😱 Oh no! That was all _global_!? So no per-field configs? Loving the #929 implementation even more now 🎉

**Comment by Vultraz** [comment]
#2449 for the first thing.
