### ISSUE TITLE
CLI docs has repeating commands

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#9360]
When looking at the CLI docs, there is repeating content when viewed on the Keystone 6 website:

<img width="837" alt="Screenshot 2024-10-11 at 9 57 03 am" src="https://github.com/user-attachments/assets/d51a50c6-a969-4b30-84a7-8ce1034f926e">

Seems there is an `else` syntax in the actual docs, is this expected?

<img width="753" alt="Screenshot 2024-10-11 at 9 56 03 am" src="https://github.com/user-attachments/assets/03111882-ba68-4280-be50-98f3f9cd7af7">

Direct link to code:

https://github.com/keystonejs/keystone/edit/main/docs/content/docs/guides/cli.md

**Comment by dcousens** [comment]
Not expected, the latter half is what should have been retained, the former removed.
Pull requests accepted :yellow_heart:
