### ISSUE TITLE
v0.3.0:  Select field configured with {required: true, initial: true, noedit: true} not working

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#938]
@jedwatson I think this is a blocker for 0.3.0.  I just upgraded to the latest 0.3.0 and there seems to be an issue with the create item modal.  I have a Types.Select field that's required and should be filled initially but it's not letting me.  The select field is configured with {required: true, initial: true, noedit: true}, which has been working fine.  I tried both Chrome Version 39.0.2171.99 m and IE11; same issue.

**Comment by JedWatson** [comment]
Good catch @webteckie - this was actually broken for all field types.

Fields should be editable in the create form when they're set to `initial: true` even with `noedit: false`.

The react components weren't implementing this logic.

I've added a new method to the base Field class called `shouldRenderField` that they now all pay attention to, encapsulating this logic.

**Comment by webteckie** [comment]
@JedWatson confirming that this now works as expected.  Thanks!
