### ISSUE TITLE
Support customisable columns for relationships

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#94]
When lists of related items are displayed on the item details screen, the `defaultColumns` setting from the related `List` is used.

The information you want to see is usually different in this context compared to the main List UI, so it would be good to be able to specify an alternate `columns` property on relationships (probably as part of the `List.relationship()` call).

**Comment by martinduparc** [comment]
That would be a great feature to have.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/support-customisable-columns-for-relationships)!
