### ISSUE TITLE
v0.3.0: Select field not behaving properly

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#940]
@jedwatson I think this is a blocker for 0.3.0  The select seems to have various issues!  For example, as soon as I create an item and submit the initial form then on the follow-up form the select options do not show.  If I type a character then it will show.  If I tried to scroll down the options it wont let me.

**Comment by jdr0dn3y** [comment]
I just tested this, and cannot duplicate this specific issue. however, there is an issue with the 'numeric' option for the selector. It causes a rendering error in the browser:

```
TypeError: undefined is not a function (evaluating 'op.value.toLowerCase()')
performapp.js:44971
mountComponentIntoNodeapp.js:33517
(anonymous function)app.js:39800
ReactMount__renderNewRootComponentapp.js:40926
renderapp.js:39869
React_renderapp.js:40926
renderapp.js:794
global code54c802c9b182a6621f520dbc:101
3keystone.min.css:11
```

I'm using the keystone-demo to test currently.

**Comment by webteckie** [comment]
The select issues seem to be random.  I think @JedWatson just gonna have to play with it to see if he can duplicate some of it.  Otherwise, there seem to be workarounds for getting around these so it may not be a blocker for releasing 0.3.0; but some annoyances should be expected.

**Comment by JedWatson** [comment]
I've fixed the numeric select issue with a hack workaround, because that was a real blocker.

It's fine for now but should be fixed in the actual select control itself (there's an issue for it)

Will look into the rest of the issues soon.

**Comment by webteckie** [comment]
@JedWatson I think select is really broken in 0.3.0.  Other than unexpected intermittent behaviors (e.g., you have to type a letter for things to show in the list) filtering doesn't work either when using relationships refs.  For example:

foo: { type: Types.Relationship, ref: 'Bar', many: false, filters: { type: 'one-thing' }

You would expect to see just 'one-thing' but all things shows up.
