### ISSUE TITLE
Instructions for "how to add Keystone to already existing express app" aren't working

### ISSUE THREAD

**Issue by phillee** [keystonejs/keystone#941]
The instructions at https://github.com/keystonejs/keystone/wiki/How-to-Add-Keystone-to-an-Already-Existing-Express-App aren't working for me. 

1. mongoose isn't defined - is this just require('mongoose')?
2. I can access /keystone without logging in
3. /keystone/signin isn't a route
4. Opening an item such as /keystone/post/[id] errors with id not found for undefined

**Comment by morenoh149** [comment]
this highly dependent on your particular needs but I'll attempt to help.
* good catch you should define mongoose as well. I'll add that.
* this recipe doesn't cover the authentication for the adminUI. You must add `auth: true` to the `init()` call.
* should be addressed by number 2
* need more code to diagnose this
feel free to reply with details.

**Comment by phillee** [comment]
Cool, /keystone and /keystone/signin work now. However new issue - /keystone redirects to /keystone/signin even when I'm already signed in.

Here's my code: https://gist.github.com/phillee/0df54b96d0154fff8da0

**Comment by morenoh149** [comment]
hmm that sounds very familiar. Can't remember what I did to solve it. I'm sure if your restart the server and add some console.log's you'll solve it. Make sure there is a valid user in your db (you could use mongohub gui on osx). And perhaps change your user model to `User`. Perhaps share anything odd you see in your server console output.

**Comment by BerkeleyTrue** [comment]
@phillee Which version of keystone are you using?

**Comment by morenoh149** [comment]
@phillee it just hit me! I saw that behavior when I attempted to set the `canAccessKeystone` field on the user model directly in mongodb. See http://keystonejs.com/docs/getting-started/ search for `canAccessKeystone`. For us we had to set the `isAdmin` variable instead https://github.com/r3dm/shpe-sfba/blob/52833d42f3f0fac04f6441d375f3e927bdd57571/models/User.js#L37 Does this solve your issue?

**Comment by phillee** [comment]
Thanks @morenoh149! I had to put this on the backburner since I couldn't get it working. Will report back when I've tried your suggestions!
