### ISSUE TITLE
If editing an item and user inadvertently click some other item the changes are lost

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#942]
This is a usability issue I suppose.  The worst case is having typed a very long text and having it discarded because your mouse was over some other link on the page when clicked.

**Comment by JedWatson** [comment]
Do you mean that it's possible to navigate away from the page without warning that you've entered changes?

If so, that's the same as 0.2.x so let's remove the **v0.3.0** from the title. Otherwise can you give a little more info?

**Comment by webteckie** [comment]
Yeah, that's what I meant.  ok, title edited.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/warning-when-navigating-away-from-page-and-when-there-are-pending-changes
