### ISSUE TITLE
moduleRoot issue

### ISSUE THREAD

**Issue by alanshaw** [keystonejs/keystone#943]
The inaccessible `moduleRoot` is a little problematic when trying to test my keystone app.

I'm using tape and have an initial test that requires my app so that subsequent tests can test it.

The test is in `test/example.js` and it does a `var keystone = require('keystone')` along with other requires at the top of the file, **before** the app is required and started.

The problem is that because this is the first time keystone is required the `moduleRoot` is at `test/` and not the root of the project.

Can we talk about this? I mean, I could obviously `require('keystone')` in the tests after my app has been required, but that feels like a bit of a hack, and is going to be confusing to new developers coming to the project.

Could the moduleRoot be set automatically when `keystone.init` or `keystone.start` is called? That would probably fix the issue since `module.parent` would be my app at that point. What do you think?

**Comment by morenoh149** [comment]
Related https://github.com/keystonejs/keystone/issues/652

**Comment by JohnnyEstilles** [comment]
@alanshaw, check out my comment in #652.

**Comment by JohnnyEstilles** [comment]
Closing ... duplicate issue. Essentially the same issue as #652. Let's continue the discussion in that thread.
