### ISSUE TITLE
localFile type field problems

### ISSUE THREAD

**Issue by jazz-ik** [keystonejs/keystone#944]
Hi!

Someone can help me with my problem? I want to use localFile type for field. I use next settings and can save images in right folder. But I can't to see them in admin UI, I always get next url in src attribute of img
```
http://localhost:3000/keystone/concerts/public/upload/concerts/1422028257178-dfdfdfdfd.jpg 
```
and 404 error
Keystone version: 0.2.40

```
localFile: {
		type: Types.LocalFile,
		dest: 'public/upload/concerts',
		datePrefix: 'x',
		format: function (item, file) {
			return '<img src="'+ file.href +'" style="max-width: 300px">'
		}
}
```
where I made a mistake? 

Thanks!

**Comment by jesse1ae** [comment]
It's a little difficult to see those options without code markdown (https://guides.github.com/features/mastering-markdown/)

In the format function, are you wrapping an `<a>` element around that `<img>`?

**Comment by jazz-ik** [comment]
Sorry, I edited my comment.

Yes, in admin UI I have code:
```
<a href="public/upload/concerts/1422035410157-dfdfdfdfd.jpg" target="_blank" class="field-value">
<img src="public/upload/concerts/1422035410157-dfdfdfdfd.jpg" style="max-width: 300px">
</a>
```
but in Network I have 404 Not Found for this image and request to url:
```
http://localhost:3000/keystone/concerts/public/upload/concerts/1422035410157-dfdfdfdfd.jpg
```

I tried a lot of different ways, and can't understand where is mistake.

**Comment by jesse1ae** [comment]
Try taking "public" out of the URL. By default that is the static (root) directory for publicly served files and so it shouldn't be in the URL.

**Comment by jazz-ik** [comment]
I've solved problem. 
This is correct code:
```
localFile: {
		type: Types.LocalFile,
		dest: 'public/upload/concerts',
		prefix: '/upload/concerts/',
		datePrefix: 'x',
		format: function (item, file) {
			return '<img src="/upload/concerts/'+ file.filename +'" style="max-width: 300px">'
		}
	}
```
