### ISSUE TITLE
Documentation # hash anchor links

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#945]
I'm a big fan of being able to link directly to what you want someone else to read. Github has an amazing feature that lets you link directly to a specific line in some code, e.g., https://github.com/r3dm/shpe-sfba/blob/52833d42f3f0fac04f6441d375f3e927bdd57571/public/js/lib/jquery/jquery-2.1.1.js#L4348

The keystone docs should be enhanced to have `#anchors` on every heading and subheading. This is a good example https://github.com/TuxedoJS/TuxedoJS#Graceful-Degradation I want to be able to link directly to `Setting up your Routes and Middleware` on http://keystonejs.com/docs/getting-started/

**Comment by JohnnyEstilles** [comment]
@morenoh149 AFAIK, all the headings/subheadings on the Keystone docs already have anchors. You can directly link to `Setting up your Routes and Middleware` using http://keystonejs.com/docs/getting-started/#routesviews-settingup.

I assume you're trying to say that you want some sort of visual representation of the anchor next to the heading/subheading so it can be easily bookmarked. If I understood you correctly, then I love the idea.

That said, the readme.md for [TuxedoJS](https://github.com/TuxedoJS/TuxedoJS) is not, in my opinion, the best example for this. I think their extra hash marks at the end of every heading is not only visually unappealing, but unnecessarily redundant. GitHub already automatically provides a linkable anchor to the left of every heading/subheading when you hover over it.

The KeystoneJS docs are very tastefully styled, so personally I would favor the GitHub-style heading/subheading anchors that appear only on hover. I believe these would be less intrusive and more visually appealing.

I noticed that all anchors/headings (at least all the ones I saw after a quick look) are coded as follows:

```html
<a name="routesviews-settingup"></a>
<h3>Setting up your Routes and Middleware</h3>
````

If they are, we could probably add the visual anchors programatically.

**Comment by morenoh149** [comment]
:( `<a name="routesviews-settingup">` I've never seen this convention until you pointed it out. Most docs I've read have `<foo id='routesviews-settingup'>` and it'd be on the heading `h1, h2, ...`. Github style works for me. And indeed would be a small program to add. I could get to it at some point if it isn't implemented.

**Comment by JohnnyEstilles** [comment]
I don't know the pattern is an intentional convention or not, but the pattern does exist throughout the docs, so I took advantage of it to automate the anchor-link feature.

[Here](https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/getting-started.jade#L236) is the example you mentioned.

**Comment by JohnnyEstilles** [comment]
#946 was merged yesterday. While there was an issue with the *post-merge* build of the docs, of which I already [informed](https://github.com/keystonejs/keystone/commit/8e866deffbef3ddc35a9d786150a12df21e15cc8#commitcomment-9430058) @JedWatson, it's probably safe to close this issue. I'm sure @JedWatson will resolve the issue soon. :-)
