### ISSUE TITLE
In memory (JSON) DB adapter

### ISSUE THREAD

**Issue by mitchellhamilton** [keystonejs/keystone#947]
This would be really helpful for things like codesandbox and potentially a good idea for examples since it wouldn’t require installing a db  or downloading any binaries.

**Comment by JedWatson** [comment]
Would SQlite be a good solution for what you're wanting here without the in-memory limitation? (it might still need binaries, I guess)

Running through a tutorial and losing data every time you restart the process might be a bit annoying.

**Comment by JedWatson** [comment]
This looks interesting: https://github.com/techfort/LokiJS

**Comment by mitchellhamilton** [comment]
> Would SQlite be a good solution for what you're wanting here without the in-memory limitation? (it might still need binaries, I guess)

Yeah, in memory probably isn't strictly the requirement, the more important thing is having something that can be installed through npm without any binaries(including binaries installed through npm)

> Running through a tutorial and losing data every time you restart the process might be a bit annoying.

Good point 👍 

I saw https://github.com/kripken/sql.js/ a while ago and if we can get it to work with knex then maybe we could just use the knex adapter.

**Comment by molomby** [comment]
See of course, #324

**Comment by jesstelford** [comment]
This is in progress here: https://github.com/keystonejs/keystone/pull/1310
