### ISSUE TITLE
Expose JSON API

### ISSUE THREAD

**Issue by cameronjroe** [keystonejs/keystone#948]
I'm not sure if Keystone is able to do this, but I think it would be a fantastic feature to be able to configure Keystone in such a way that it exposes a public json api for use with a client-side spa. I think this would help when using Angular or Backbone on the front-end. The great part is that one could manage their api via the cms and define what data they would like to expose.

**Comment by morenoh149** [comment]
I'll close this in favor of https://github.com/keystonejs/keystone/pull/404 if that's not quite what you'd like I could reopen this.
