### ISSUE TITLE
Query on relationship field

### ISSUE THREAD

**Issue by shauntrennery** [keystonejs/keystone#949]
Is it possible to query

```javascript
Request.add({
  app: {type: Types.Relationship, ref: 'App', index: true},
  user: {type: Types.Relationship, ref: 'User', index: true},
  status: {type: String, index: true},
  lastMessageDateTimeStamp: {type: Types.Datetime}
});
```

with a query like:

```javascript
{ app: 54be24a441a10a948a08d741,
  status: 'Open',
  '$or': 
   [ { 'user.name.first': /Blake/i },
     { 'user.name.last': /Blake/i } ] }
```

I've included the following populate setting in the query.
```javascript
.populate({
        path: 'user',
        select: 'name status lastSeen'
      })
```

I'm not getting any results back.

**Comment by morenoh149** [comment]
Try
```javascript
Request.find({ app: 54be24a441a10a948a08d741,
  status: 'Open',
  '$or': 
   [ { 'user.name.first': /Blake/i },
     { 'user.name.last': /Blake/i } ] },
  function(err, docs) {
    if(err) throw err;
    console.log('docs:', docs);
  });
```

**Comment by shauntrennery** [comment]
Pretty much exactly what my statement looks like. I'm afraid it does not work as user is not populated.

**Comment by JohnnyEstilles** [comment]
@shauntrennery, sorry to be the bearer of bad news, but unfortunately mongoose does not provide a means to query on populated fields. As per the [Mongoose documentation](http://mongoosejs.com/docs/3.4.x/docs/populate.html) "there are no joins in MongoDB".

`.populate()` is just a convenience method to help us reference documents in other collections.

There is not way to filter by related fields in a single query in MongoDB or Mongoose.

Closing ... not a Keystone issue.
