### ISSUE TITLE
Add 'create' option for relationship fields in the Admin UI

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#95]
Would allow users to add a new item for a relationship field, inline

Need to figure out the best format to submit the data in, and how to handle a mix of required / initial fields (other than name).

Might be best handled via an ajax call (then link the item on save).

**Comment by albertogasparin** [comment]
Bump :+1: 
This should be easier now with React. I think that the first release could be a modal with the initial fields only.

**Comment by pieer** [comment]
This feature is blocking me from any further development on my project.
How far are we from this implementation?
I'm happy to give a hand if I can get some direction.
IMO a modal is a nice to have, but it's not really necessary atm, implementing a simple link to a related object with ids initialised would rock my world.

**Comment by creynders** [comment]
Hi @pieer a helping hand would definitely be welcome for this. Shall we invite you to the development slack for easier communication on how to tackle this?

**Comment by pieer** [comment]
Yes please

**Comment by gaurav21r** [comment]
I too would like to contribute (in any non REACT way i can :tongue: , this is one of the few features missing in keystone to be used in a large scale project of ours which has got funding. Our exact requirement is #1324

**Comment by milosdakic** [comment]
+1

**Comment by morenoh149** [comment]
@gaurav21r if you have funding you should definitely contribute to development. If you'd like to join the slack send your email.

**Comment by gaurav21r** [comment]
@morenoh149 Am just waiting for the Green Signal from Business and will send the Keystone Core team an official proposal.

**Comment by datnordstrom** [comment]
1+

**Comment by jossmac** [comment]
This should now be possible using react-select's `newOptionCreator`. We could add the same `allowCreate` flag to the relationship field

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/add-create-option-for-relationship-fields-in-the-admin-ui)!
