### ISSUE TITLE
Use sub domain prefix

### ISSUE THREAD

**Issue by bang88** [keystonejs/keystone#950]
I want to use a sub domain to load the uploaded files,but  the  `href` method normalize it with   `path.join `,so i can't get the result as expected

**Comment by morenoh149** [comment]
@littlebang could you fix it up in a pull request?

**Comment by JohnnyEstilles** [comment]
@littlebang, can you be a little more specific? I don't quite understand what you're trying to achieve.

Are you talking about a `LocalFile` field type? Is your intention to upload to a different sub-domain (while running multiple instances of Keystone)? Or do you have multiple domains (including a sub-domain) pointing to the a single instance of Keystone and you just want to serve the uploaded file from the sub-domain?

Maybe you can provide some code for your use case.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/use-sub-domain-prefix
