### ISSUE TITLE
Translate Keystone docs into Spanish

### ISSUE THREAD

**Issue by JohnnyEstilles** [keystonejs/keystone#953]
## Synopsis

I believe translating the Keystone website/documentation into Spanish will be very valuable to the Spanish speaking Node.js community. Spanish is the second most spoken language un the work, with more 400 million native speakers worldwide. It is the official language of 20 countries, including Mexico, Spain, Colombia, Argentina, Perú, Venezuela, Chile, Ecuador, Guatemala, Cuba, Bolivia, Dominican Republic, Honduras, Paraguay, El Salvador, Nicaragua, Costa Rica, Panamá, Uruguay and Equatorial Guinea, along with the US Territory of Puerto Rico.

I've been pinged by a number of Spanish speaking Node.js developers in Puerto Rico and Panamá requesting the translation of the Keystone docs.

I have started the Spanish translation in the [doc-es](https://github.com/JohnnyEstilles/keystone/tree/docs-es) branch of my Keystone fork. This is still a work in progress. Anyone wants to proofread, comment and/or contribute is more than welcome.

Will continue pushing my progress into this branch and will submit a PR once the final draft is complete.
## Translation Status
- [x] es/templates/mixins/docsnav.jade
- [x] es/templates/layout/base.jade
- [x] es/page/404.jade
- [x] es/page/home.jade
- [x] es/page/starting.jade
- [x] es/page/examples.jade
- [ ] es/page/docs/configuration.jade (In Progress ...)
- [ ]  es/page/docs/database.jade
- [x] es/page/docs/getting-started.jade
- [x] es/page/docs/index.jade
- [x]  <del>es/page/docs/views.jade</del> (Deprecated)

> NOTE: It seems line the `page/docs/views.jade` is no longer being used, so I did not translate it.
## Other Edits

In addition to the translation I took the liberty to make the following changes:
- added localized Spanish version of templates/layout/base.jade in order to translate footer (maybe we should just factor out the footer of the layout, so that it can be translated in every language)
- Replaced references to KeystoneJS Google Group with Gitter Room (I suggest we replace this in the other translations as well)
## Translation Branch

Anyone interested in review my progress can check out the following branch on my Keystone JS fork:

[https://github.com/JohnnyEstilles/keystone/tree/docs-es/docs/content/es](https://github.com/JohnnyEstilles/keystone/tree/docs-es/docs/content/es).

**Comment by JohnnyEstilles** [comment]
## Spanish translation status

folder | filename | status
--- | --- | :---:
es/templates/mixins | docsnav.jade | Done!
es/templates/layout | base.jade | Done!
es/page | 404.jade | Done!
 | home.jade | Done!
 | starting.jade | Done!
 | examples.jade | Done!
es/page/docs | configuration.jade | -
 | database.jade | -
 | getting-started.jade | -
 | index.jade | -
 | views.jade | -

## Other Edits

In addition to the translation I took the liberty to make the following changes:
- added localized Spanish version of templates/layout/base.jade in order to translate footer
- Replaced references to KeystoneJS Google Group with Gitter Room

## Translation Branch

Anyone interested in review my progress can check out the following branch on my Keystone JS fork:

[https://github.com/JohnnyEstilles/keystone/tree/docs-es/docs/content/es](https://github.com/JohnnyEstilles/keystone/tree/docs-es/docs/content/es).

**Comment by webteckie** [comment]
@JohnnyEstilles muy bien (nice job)!!!  Some comments on the main page:

applicaciones-->aplicaciones (El "framework" de código abierto para el desarrollo de sitios web basados en datos, applicaciones...)

codifición-->codificación (En ocaciones, la codifición asincrónica...)

imágin-->imagen (¿Desea validar una forma, subir una imágin...)

encripción-->encriptación? (Keystone ofrece manejo de sesion y autenticación, e incluye la encripción...)

Hey-->Hay (Hey muchos "frameworks"...)

Keyston-->Keystone (Keyston no hace eso.)

last-->las (reemplace last que no)

casas-->características (Utilice las casas)

signigfica-->quiere decir (Esto signigfica que cualquier cosa que...)

Keystone esta diseñado para ser cual ligero como usted desee - usted las características que usted desee incluir. --> Keystone esta diseñado para ser tan liviano como usted desee - usted decide las características que usted desee incluir.

Cree-->Usted puede crear (Cree sus propias rutas,..)

modules-->modulos (es la gran cantidad the modules disponibles...)

¿Parece esto lo que busca?-->¿Parece a esto lo que busca?

**Comment by JohnnyEstilles** [comment]
@webteckie ... thanks for the corrections. I really appreciate you taking the time to look at it. I've already made de corrections and pushed the changes to the `docs-es` branch.

**Comment by JohnnyEstilles** [comment]
My apologies for taking so long with this translation. Got a bit busy here. Still working on `es/page/docs/configuration.jade`.

**Comment by flowck** [comment]
@JohnnyEstilles nice, i'm doing the same for Portuguese.

**Comment by JohnnyEstilles** [comment]
@flowck ... Awesome! The more the merrier! :-)

**Comment by mxstbr** [comment]
Is there any update on this, is this still current or can this be closed?

**Comment by Noviny** [comment]
Closing this as it has not been updated in a while.
