### ISSUE TITLE
Can we remove the build files from the repo?

### ISSUE THREAD

**Issue by danielmahon** [keystonejs/keystone#955]
Shouldn't building be handled by an npm hook? I have been working on a few feature branches that make it hard to create a clean rebase/history when Im expected to checkin the built files (less, app.js).

**Comment by morenoh149** [comment]
so you're working on parts of the code that would trigger a rebuild? Which file exactly?

**Comment by danielmahon** [comment]
creating new field types, which includes changes to react and less, both of which get "compiled" and commited

**Comment by morenoh149** [comment]
ah and this file https://github.com/keystonejs/keystone/blob/master/public/build/js/app.js has be rebuilt? any others?

**Comment by danielmahon** [comment]
It makes sense to me to include the `gulp build-scripts` to the `prepublish` script in package.json.

`/public/styles/keystone.min.css` is committed also which can be taken out since it will be compiled on first run anyway

**Comment by JedWatson** [comment]
@danielmahon I was planning to remove them once I got the on-init build process in place (see #957) but would be happy to do this first since it's causing you issues.

If you could submit a PR with the changes needed to `package.json` and `.npmignore` (is anything else needed?) I'd be glad to merge it, otherwise I'll get to it as soon as I can.

**Comment by danielmahon** [comment]
@JedWatson Ill work on a PR today, one thing ive been struggling with is the "proper way" to build/deploy this on heroku once I take out app.js. If we use the `prepublish` script to build the npm module it's fine because the build file will be included in the published module. But for my current setup, my current app is pointing to a forked branch of keystone. This means I need to build on heroku, but it's tricky because my app is isnt building... keystone as a dependency needs to. Im just not sure how to go about doing it without adding all of keystone's build requirements as my app's dependencies, and then running `gulp --cwd ./node_modules/keystone build-scripts` in the `postinstall` script. Seems kinda hacky and I also dont think Im going about it correctly. Suggestions?

**Comment by dcousens** [comment]
@jedwatson I think is worth looking at once we have extracted the admin UI from keystone core.

**Comment by JedWatson** [comment]
Actually it's been done, I missed this issue when I was committing the fix. Thanks for the bump!
