### ISSUE TITLE
On-start building of Admin JS app.js

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#957]
We need to change the build process for `app.js` so that it is built when Keystone is started, including _only_ the fields that are actually used by models.

This will both remove the need for a built file to be included in the npm package (and github project, see #955) _and_ let us dramatically reduce the file size of app.js in most cases (it is currently 1.6mb)

i.e. if you don't need CodeMirror because you don't have Code fields, we _really_ shouldn't be adding that 300kb to the file size.

My current idea is to dynamically write the `/admin/src/fields.js` file (or equivalent) when Keystone is started, then use browserify to build `/public/build/js/app.js` (or equivalent) on `start()` after the models have been defined. `fields.js` would be built to only require the field types that have been used by models (this feature is already in place).

In the future it would make room to dynamically include custom (non-core) field types in the build tool, which we'll need.

The actual method may be different, e.g. we may build a separate `fields.js` bundle that dynamically requires and exposes just the field types in use, leaving the build of the main `app.js` separate. This would be good to experiment with during implementation.

A similar process should replace the less middleware that builds the stylesheet too, but that's another issue.

**Comment by sononix** [comment]
To some extent shouldnt this be taken care by including the relevant task in the gulp/grunt files - Ive only just download the repo so I still feeling my way around the architecture - kicking the wheels to some extent

does that mean that app.js needs to be 'restarted' everytime a change is made to app.js - similar to raising a sails app each time -- what is best practice in development then

**Comment by morenoh149** [comment]
@JedWatson could we get an eta for when this would get done?
If the eta is > 1 week could we perhaps work on getting a `postinstall` step working. I believe we could get the `postinstall` done in < 1 week. @lojack @JohnnyEstilles 

As of right now the master branch of this project is not working for a significant number of devs.

**Comment by JedWatson** [comment]
@morenoh149 happy for you to set it up as a postinstall and see if that solves the problem. I haven't had a similar experience with any of my other react packages (all are built before submitting to npm) so I don't know why this is a special case. However, I can't reproduce the issue at all (while many others can) so anything we can do to narrow down the cause or even provide a band-aid at this point would be good.

**Comment by JedWatson** [comment]
The first part of this is complete, we've now got a proper Browserify build running when Keystone starts.

The fields being bundled still need to be dynamically built based on the field types in use, see https://github.com/keystonejs/keystone/blob/master/admin/app/static.js#L18

This needs to be replace with a dynamic version of https://github.com/keystonejs/keystone/blob/master/admin/src/fields.js (and the corresponding `filters.js` in the elemental branch)

**Comment by wmertens** [comment]
@JedWatson I think we should close this one in favor of building a one-size-fits-all with dynamic loading. We don't have a tracking issue for that one yet though, but imho the path will be `webpack runtime build` -> `proxy react components` -> `webpack static build`.

**Comment by mxstbr** [comment]
Sounds pretty good to me @wmertens!

**Comment by gautamsi** [comment]
Keystone 4 is going in maintenance mode. Expect no major change. see #4913 for details.

This one seems to be related to 0.3.x. Open another issue if needed.
