### ISSUE TITLE
Add a search option to the front end 

### ISSUE THREAD

**Issue by WagnerMatos** [keystonejs/keystone#96]
I was thinking about adding a search feature on each page (blog, wiki, whatever) and also a global that one that could be used on header or something.

I thought the search used in the admin is really nice, so it'd be basically adding that to users that are not logged in.

I'd been more than happy in doing this, then submit it as a merge request as long as you point me in the right direction.

**Comment by Nitish27** [comment]
Hi JedWatson
i want to add search on frontend for posts.
can u help me how can i do this.

**Comment by adamjhickey** [comment]
Any update on this?

**Comment by alterx** [comment]
@JedWatson @WagnerMatos any updates on this one? Allowing the users to search on the front end is a feature that most blogs need. If there's no work on this issue, could someone point me out to the place in which I could manually add indexes to the underlying mongodb collections and use mongo's built in search?

**Comment by Nitish27** [comment]
keystone.list('Post').model.find({title: new RegExp('^'+req.body.search+'$', "i")}, function(err, results) {
                //Do your action here..
                locals.data.locations = results;
                if (results == ''){
                    locals.data.invalid = 'Invalid search';
                }
                next(err);
            });

**Comment by morenoh149** [comment]
@alterx to add indexes you do that in the mongoshell or programmatically in some init code for your project.

**Comment by alterx** [comment]
@morenoh149 thanks, yeah. Just wanted to know if there´s some place in which, by convention, that code should go however I think I´ll try @Nitish27´s code first. The site is small and that should suffice.
Thanks guys.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/add-a-search-option-to-the-front-end)!
