### ISSUE TITLE
It's not possible to delete a text field

### ISSUE THREAD

**Issue by bravomartin** [keystonejs/keystone#963]
Once you have saved some text in a text field (text, html, textarea), there is no way of deleting it.
Apparently when you submit an empty field it just ignores it. 
You can submit a space, but then in templates `if` will return true.

**Comment by danielmahon** [comment]
@bravomartin Have you updated Keystone to the latest version? Sounds like #914

**Comment by bravomartin** [comment]
I hadn't. Updated and it works! Thanks
