### ISSUE TITLE
git clone repo error

### ISSUE THREAD

**Issue by sononix** [keystonejs/keystone#964]
after git cloning the repo - Ive changed the version from 0.2.42 to 0.3.0 and ran 

sudo npm install - results in this error

  SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_ext.10.5
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ms/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/ms/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ms/CODE/NODE/KEY/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.5
 
> fsevents@0.3.5 install /Users/ms/CODE/NODE/KEY/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_ext.10.5
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ms/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/ms/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ms/CODE/NODE/KEY/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.5

**Comment by snowkeeper** [comment]
Changing the package version has no effect on the install.   I just did a test and got a clean install. 

One thing I notice is you are using `sudo npm install` on a `nvm` setup.  You should not be installing with `sudo`.  Using `nvm` should place `node` and `npm` into your user PATH.

This would suggest a local error.  The first thing you should  do is make sure `nvm` has properly set up node and npm so you do not use `sudo` anymore.

I also notice 
```
ld: library not found for -lgcc_ext.10.5
```
Make failed to build.  Do you have the proper gcc libraries?

Are you on a mac?  If so check out this SO: http://stackoverflow.com/a/22515259

**Comment by tomasztunik** [comment]
@sononix  - are you using io.js by any chance instead of node? there are some problems with it now with node-gyp among the few that are being ironed out - for the time being it's better to stick with nodejs for keystone development

**Comment by sononix** [comment]
nope using nodejs with nvm for management - cant get pass this - have parked keystone until I figure out what is causing an error on my system 
trying to track down how 'make' is building these files out

**Comment by JedWatson** [comment]
@sononix out of curiosity, what are you trying to do (big picture)?

It looks like something in watchify is failing on the install - you may get some answers opening an issue on that project.

You only need to check out the repo to actually build Keystone, which you probably want to do using `npm link`.

If you want to use Keystone in a project then you'd declare it as a dependency in your package.json and `npm install` from there (which won't install the devDependencies like watchify)

**Comment by sononix** [comment]
I wanted to use the development branch and not the 2.42 though i see now its has been update so I can that go :)
M
