### ISSUE TITLE
I recommend keystone document can show us an overall framework map, which can help to understand the source code

### ISSUE THREAD

**Issue by janryWang** [keystonejs/keystone#965]

**Comment by janryWang** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by morenoh149** [comment]
I was thinking of what a diagram would look like. Try cloning the repo and expanding all folders. That gives you a decent idea of what the areas of the code are. Some UML diagram might be useful.

**Comment by janryWang** [comment]
@morenoh149 
Okay, thank you very much
