### ISSUE TITLE
How to nested query relational data?

### ISSUE THREAD

**Issue by janryWang** [keystonejs/keystone#966]
This is my data structure, I want to implement a relational query, but the query is nested data fields.I know after reading mongoose document the basic usage of nested queries, but when I tested but nothing returns.Please help me, I will be grateful.
`
        //Define
    
    var TimeLine = new keystone.List('TimeLine', {
        hidden:true
    });
    TimeLine.add({//timeline datameta
        article:{type:Types.Relationship,ref:'Article'}
        music:{type:Types.Relationship,ref:'Music'},
        album:{type:Types.Relationship,ref:'Album'},
        video:{type:Types.Relationship,ref:'Video'}
    });

    var Article = new keystone.List('Article', {
        map: { name: 'title' },
        autokey: { path: 'slug', from: 'title', unique: true }
    });

    Article.add({
        title: { type: String, required: true },
        state: { type: Types.Select, options: 'draft, published, archived', default: 'draft', index: true },
        author: { type: Types.Relationship, ref: 'User', index: true },
        publishedDate: { type: Types.Date, index: true, dependsOn: { state: 'published' } },
        image: { type: Types.CloudinaryImage },
        content: {
            brief: { type: Types.Html, wysiwyg: true, height: 150 },
            extended: { type: Types.Html, wysiwyg: true, height: 400 }
        }
    });

    Article.schema.pre('save', function(next) {
        var Timeline = keystone.list('TimeLine').model;
        var _this = this;
        Timeline.findOne({
              article:this._id
        }).exec(function(err,result){
            if(!result){
                var _timeline = new Timeline();
                _timeline.article = _this._id;
                _timeline.save();
            }
        });
        next();
    });
    Music,Album,Video.....
    //Usage

    var timeline = keystone.list('TimeLine').model;
    timeline.find({
        "article.title":"xxxxxxxxx"//Here is a nested query
    }).populate('article').exec(function (err, result) {
        console.log(err,result);//This is the query results, but it can not     return anything.
    });

    //nothing return!!!
`

**Comment by morenoh149** [comment]
you're never actually assigning a post to a timeline. You've declared the relationship types but never the link between them. Try setting the `Timeline.article = articleInstance` somewhere in your code. Most relationships can also be set from the adminUI.

Also you probably want your timeline to hold a reference to an *Array* of posts.

**Comment by janryWang** [comment]
@morenoh149 
This is my code,I forgot show the plugin.But still can not query data

```
	Post.schema.pre('save', function(next) {
		var Timeline = keystone.list('TimeLine').model;
		var _this = this;
		Timeline.findOne({
			article:this._id
		}).exec(function(err,result){
			if(!result){
				var _timeline = new Timeline();
				_timeline.article = _this._id;
				_timeline.save();
			}
		});
		next();
    });
```

**Comment by snowkeeper** [comment]
Are you sure you have an `_id` property at that point.  Change `Article.schema.pre` to `post` and check `_timeline.save` for errors
```javascript
Article.schema.post('save', function() {
        var Timeline = keystone.list('TimeLine').model;
        var _this = this;
        Timeline.findOne({
            article:this._id
        }, function(err,result){
            if(!result){
                var _timeline = new Timeline();
                _timeline.article = _this._id;
                _timeline.save(function(err) {
                    if(err) {} //see if you have errors
                });
            }
        });
 });
```

**Comment by janryWang** [comment]
@snowkeeper 
There is no problem, but then I found mongodb itself does not seem to support nested query references, unless with the program

**Comment by morenoh149** [comment]
@janryWang is your problem solved?

**Comment by janryWang** [comment]
@morenoh149 I chose an alternative, use elasticsearch to query datas.
