### ISSUE TITLE
Function thread order troubles

### ISSUE THREAD

**Issue by vfermino** [keystonejs/keystone#967]
Hello. I'm using Keystone to develop a website and I am having a little trouble with a single route.
There is a route called "contact.js" that is used to send enquiries to our database. There is also a model for Themes, which are based on CSS files that we upload and set to boolean values to customize the appearance in an easy way. The Theme model is loaded on the middleware.js route, and it loads the themes on all pages, except the contact.js one.
**middleware.js**
```
exports.themes = function(req, res, next) {
	console.log('1 ' + res.locals.themes); // I log this just to check which will appear first
	Theme.model.find().sort('name').exec(function(err, themes) {
		res.locals.themes = themes;
		console.log(themes);
	});
	console.log('2');
	next();
};
```
**contact.js**
```
var keystone = require('keystone'),
	Enquiry = keystone.list('Enquiry');

exports = module.exports = function(req, res) {
	
	var view = new keystone.View(req, res),
		locals = res.locals;
	
	locals.enquiryTypes = Enquiry.fields.enquiryType.ops;
	locals.formData = req.body || {};
	locals.validationErrors = {};
	locals.enquirySubmitted = false;
	
	view.on('post', { action: 'contact' }, function(next) {
		
		var newEnquiry = new Enquiry.model(),
			updater = newEnquiry.getUpdateHandler(req);
		updater.process(req.body, {
			flashErrors: true,
			fields: 'name, email, phone, company, enquiryType, message',
			errorMessage: 'There was a problem with your enquiry:'
		}, function(err) {
			if (err) {
				locals.validationErrors = err.errors;
			} else {
				locals.enquirySubmitted = true;
			}
			next();
		});
		
	});
	
	view.render('contact');
	
};
```
**layout.jade**
```
block css
		if themes
			each theme in themes
				if theme.state
					link(href='/stylesheets/'+theme.css.filename,rel='stylesheet')
```
I will post more info if it helps. It's just weird because the Themes from the middleware are loaded **after** the contact page is rendered, which doesn't happen with the other views.
Do I need to change something in the index.js route, preloading the middleware or setting a different attribute to my app.all('/contact', routes.views.contact);?
Thanks.
**EDIT:**
A simple log:
```
1 undefined
2
GET / 304 409ms
[ { __v: 0,
    _id: 54c2238f181160b11cde526d,
    customcss: '',
    name: 'Fonte',
    slug: 'fonte',
    state: true,
    css:
     { filename: 'fonte.css',
       path: 'public/stylesheets/',
       size: 22,
       filetype: 'text/css' } },
  { __v: 0,
    _id: 54c0d974dde3023a13c4b98e,
    customcss: 'body{background:#f00 !important}',
    name: 'PadrÃ£o',
    slug: 'padrao',
    state: false,
    css:
     { filename: 'padrao.css',
       path: 'public/stylesheets/',
       size: 32,
       filetype: 'text/css' } } ]
1 undefined
2
GET /contact 200 164ms
[ { __v: 0,
    _id: 54c2238f181160b11cde526d,
    customcss: '',
    name: 'Fonte',
    slug: 'fonte',
    state: true,
    css:
     { filename: 'fonte.css',
       path: 'public/stylesheets/',
       size: 22,
       filetype: 'text/css' } },
  { __v: 0,
    _id: 54c0d974dde3023a13c4b98e,
    customcss: 'body{background:#f00 !important}',
    name: 'PadrÃ£o',
    slug: 'padrao',
    state: false,
    css:
     { filename: 'padrao.css',
       path: 'public/stylesheets/',
       size: 32,
       filetype: 'text/css' } } ]
```

**Comment by morenoh149** [comment]
the themes from the middleware are loaded after hitting `/` as well. The mongoose query seems like it's happening asynchronously so you keep seeing `1, 2, GET, <themesArray>`. How is it you say it's working on all routes except `/solution`?

**Comment by webteckie** [comment]
@vfermino wouldn't you then want the theme middleware to complete fetching the themes before continuing on?  For example:

```
exports.themes = function(req, res, next) {
    console.log('1 ' + res.locals.themes); // I log this just to check which will appear first
    Theme.model.find().sort('name').exec(function(err, themes) {
        res.locals.themes = themes;
        console.log(themes);
        next();                        // continue on now that themes are loaded
    });
    console.log('2');
};
```

**Comment by vfermino** [comment]
Putting the next(); inside actually worked fine. Thanks a lot. Problem solved.
Apparently that was the very reason that it was working asynchronously, although I still don't quite understand why it only "malfunctioned" on a single view. Maybe it's because Mongoose also had the load other models in that case.

**Comment by webteckie** [comment]
@vfermino it is still working asynchronously...previously you had it working asynchronously and concurrently, which does not guarantee execution order.
