### ISSUE TITLE
Add a Geo field to the core set

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#969]
The Location field has Geo info but some use cases do not require all that other information configured in it.  A standalone Geo field can satisfy many use cases without the extra overhead.

**Comment by JedWatson** [comment]
+1 I will add this on the plane back to Sydney. Need something easy to do ;)

**Comment by webteckie** [comment]
@JedWatson cool that would clean up my code a bit :-)

**Comment by webteckie** [comment]
@JedWatson great will check it out.  A new issue should be opened to get docs updated.

**Comment by webteckie** [comment]
@JedWatson some bugs here:

1) The regex is not allowing for "-" coordinates
2) I cannot set a default.  I'm assuming defaults are:  default: [lng-value,lat-value] ?

**Comment by JedWatson** [comment]
@webteckie thanks for the review. Both those issues should be fixed now :)

**Comment by webteckie** [comment]
@JedWatson looks pretty good now. thanks!

**Comment by webteckie** [comment]
@JedWatson another [more serious] bug.  Items based on a model with a GeoPoint field in it but that do not show the GeoPoint field form (because the dependsOn dependency is false) fail with the following when the item is saved (the GeoPoint is not even a required field):

![image](https://cloud.githubusercontent.com/assets/5872515/6072631/dac1b10c-ad71-11e4-8ff5-19c9a7295869.png)

**Comment by JedWatson** [comment]
Would you mind opening a new issue with that @webteckie? @sebmck or I'll take a look.

**Comment by webteckie** [comment]
ok, will do.  btw, don't fields have unit tests?

**Comment by sebmck** [comment]
@webteckie Not really, it's on our todo list.
