### ISSUE TITLE
Add Search UI to the Details view in the Admin UI

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#97]
If you're looking at an item in the Admin UI and want to search for another one, you currently have to navigate back to the list view and then search.

It would be nice to be able to search (probably just using the 'simple' search feature, not the full filters UI) right from the item screen without going back to the list view.

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/add-search-ui-to-the-details-view-in-the-admin-ui)!
