### ISSUE TITLE
dependsOn broken for list headings

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#970]
The following enhancement (done via 0ef857d), has regressed.  Once the regression is addressed the feature should also be documented:

v0.1.38 / 2013-11-06

added; ability to use dependsOn with headers, thanks itzaks
new syntax is { heading: 'Heading with dependency', dependsOn: { field: 'value'} }

**Comment by snowkeeper** [comment]
It looks like this just needs the logic added into the React templates.  I can look at it before too long.  @JedWatson do you still want to pull over the expression-match module and tie it in?

**Comment by snowkeeper** [comment]
Fixed by #972

**Comment by snowkeeper** [comment]
Closed prematurely, still needs documentation

**Comment by snowkeeper** [comment]
documented by #974
