### ISSUE TITLE
Master branch install

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#973]
So, we're going to be starting a few major builds on Keystone. We've been working in 0.2 but think we should probably just use 0.3.0. Are there any install instructions for 0.3.0 ... I've almost got it going, just wonder if there is something already written up. Thanks for any help.

**Comment by snowkeeper** [comment]
0.3.0 is close to being released.  For any changes you might need to make check out the [Wiki](https://github.com/keystonejs/keystone/issues).  

If you are still using `List.addPattern("standard meta")` you need to switch to the [list tracking feature](http://keystonejs.com/docs/database/#lists-options)

Express has been upgraded from 3 to 4.

**Comment by chrisschaub** [comment]
I'm really just trying to understand the steps to run from git master branch, not the yo generator. The docs seems to point to running two environments (a 2x and 3x) alongside with npm link. So, I really think I just want to build node_modules/keystone from scratch ... trying to figure out the way to do that. Thanks for nay help. The rest seems to work.

**Comment by snowkeeper** [comment]
sorry... `npm install keystonejs/keystone` will install the 0.3.0 branch.

**Comment by chrisschaub** [comment]
Ahh, thanks. I was thrown by the version numbers in history.md which show
v0.2.42 as the version! Didn't realize that 0.3.0 would be a git tag or
something upon release. Thanks!

On Sat, Jan 31, 2015 at 8:03 AM, Brett Newman <notifications@github.com>
wrote:

> sorry... npm install keystonejs/keystone will install the 0.3.0 branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/973#issuecomment-72318905>.
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
Are there any downsides starting with 0.3.0 now? Seems pretty solid. I have a 30-45 day project I need to nail. Am willing to roll up sleeves and send patches as needed. Thanks again.

**Comment by morenoh149** [comment]
@chrisschaub I'd go with 0.3.0. If there are any bugs in the react components we can fix them
