### ISSUE TITLE
Add configuration for defaultColumns, createFields to Lists

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#979]
At the moment, we're showing all the fields as the default column set and in the create modal. It's not particularly usable, and you can't change it.

We've discussed a few different ideas here but for now I propose bringing forward two list options from Keystone 4: `defaultColumns` and `createFields`.

Both are space-separated lists of field paths, like this for your average User list config:

```js
  fields: {
    name: { type: Text },
    email: { type: Text, isUnique: true },
    dob: {
      type: CalendarDay,
      format: 'Do MMMM YYYY',
      yearRangeFrom: 1901,
      yearRangeTo: getYear(new Date()),
    },
    password: { type: Password },
    isAdmin: { type: Checkbox },
    avatar: { type: File, adapter: avatarFileAdapter },
  },
  createFields: ['name', 'email', 'password', 'isAdmin'],
  defaultColumns: ['name', 'email', 'isAdmin'],
  labelResolver: item => `${item.name} <${item.email}>`,
```

Both could default to "all fields" as they currently do.

**Comment by jesstelford** [comment]
We already have `defaultColumns`:

https://github.com/keystonejs/keystone-5/blob/a0216eeb8b225b7ed079404697dc9e1b78f4c237/demo-projects/blog/schema.js#L65-L69

**Comment by jesstelford** [comment]
#867 introduces a `.isEditable()` function on field types which does the things you mention except for being configurable at schema-definition time. We could update the default implementation of `.isEditable()` to look at the schema to see if the field is listed or not 👍

**Comment by dcousens** [comment]
@jesstelford should this issue close then?

**Comment by jesstelford** [comment]
@dcousens #867 didn't get merged. Gotta Cherry pick those changes out
