### ISSUE TITLE
Deep Populate: Populating something that has been populated

### ISSUE THREAD

**Issue by johnlo1992** [keystonejs/keystone#979]
Hi,

I was looking at the example posted here https://github.com/LearnBoost/mongoose/issues/1888 and was wondering if it were possible to take it one level further?

For example,
```
Category.model.findOne().exec(function(err, category) {
  category.populateRelated('posts[author]', function(err) {
    // posts is populated, and each author on each post is populated
  });
});
```
How could I populate say the articles from an author List within the populateRelated function?
`posts[author[articles]]`?

Thanks very much!

**Comment by pr1ntr** [comment]
+1 to do this recursively

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
