### ISSUE TITLE
Working with master branch

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#981]
So, I've ...

get master branch
% git clone https://github.com/keystonejs/keystone.git keystone

installed node modules
% npm install

installed latest keystone master
% npm install keystonejs/keystone

% edit package.json to have start script for "node index.js"
% npm start

see these two lines
> keystone@0.2.42 start /Users/foo/dev/horton/keystone
> node index.js

and then nothing. Do I need to manually create the db? I'm just wondering if the install for the master branch is different than the 0.2.0 branch? The git tree looks somewhat different. I'm just trying to get going on working with master (0.3.0 candidate) instead of 0.2.0. Thanks for any help!

**Comment by morenoh149** [comment]
make sure mongo is already running on your machine http://docs.mongodb.org/manual/tutorial/manage-mongodb-processes/

**Comment by chrisschaub** [comment]
It is, and the 0.2.0 worked locally just fine.

On Mon, Feb 2, 2015 at 1:45 PM, Harry Moreno <notifications@github.com>
wrote:

> make sure mongo is already running on your machine
> http://docs.mongodb.org/manual/tutorial/manage-mongodb-processes/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/981#issuecomment-72523749>.
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
I thought it would just pick up the default mongo configs for working
locally? Do I have to add mongo connection strings someplace? My stuff is
all default on osx and worked for 0.2.0.

On Mon, Feb 2, 2015 at 1:47 PM, Christopher Schaub <chris@schaub.com> wrote:

> It is, and the 0.2.0 worked locally just fine.
>
> On Mon, Feb 2, 2015 at 1:45 PM, Harry Moreno <notifications@github.com>
> wrote:
>
>> make sure mongo is already running on your machine
>> http://docs.mongodb.org/manual/tutorial/manage-mongodb-processes/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/keystonejs/keystone/issues/981#issuecomment-72523749>
>> .
>>
>
>
>
> --
> Christopher Schaub
> http://chris.schaub.com
>
>


-- 
Christopher Schaub
http://chris.schaub.com

**Comment by morenoh149** [comment]
no the default port and address could work. I just use an .env file in my project. But I believe keystone will work with a default mongo running on the same machine.

I don't get why you're cloning the project and then using npm to install keystone master. I personally would fork the master branch. Then reference this repo as a dependency in your project. Like this https://github.com/r3dm/shpe-sfba/blob/master/package.json#L16

**Comment by chrisschaub** [comment]
My bad, I was confused about how the repo was structured. Closing.
