### ISSUE TITLE
Something's not right with the new logger settings

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#983]
I'm getting this when request are logged using the default config:

`GET /keystone/posts/54cafdaf3ec6e2925ff49ee9 200 276.108 ms - -`

The dev output setting should display this:

`:method :url :status :response-time ms - :res[content-length]`

It looks like `res[content-length]` is not being set, it probably should be though?

Would be great if someone can look into this.

**Comment by JedWatson** [comment]
FYI docs are here: https://github.com/expressjs/morgan

**Comment by snowkeeper** [comment]
The `compression` middleware removes the `Content-Length header` .

When I set `compress: false` I get the correct string with colored status.

**Comment by JedWatson** [comment]
Right, thanks for the sleuthing @snowkeeper! Maybe we should just provide our own default config for the logger instead of using the default `dev` setting.

**Comment by JedWatson** [comment]
Fixed by @sebmck and #995
