### ISSUE TITLE
Preemptively create issues with answers to common errors / warnings

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#983]
As folks build out their Keystone app, they're inevitably going to run into error outputs or warnings, which they'll then drop into Google to find an answer for.

It would be great if we could preemptively create issues for those and answer them so when Googler's Google, they land on our issue with the answer in the first comment and they can continue being awesome 🎉

NOTE: This is not in exclusion to our docs, just solving for the case where GitHub has excellent SEO. Could also make sense to do it on StackOverflow too.

**Comment by jesstelford** [comment]
Here's a great example: https://github.com/expressjs/session/issues/556

<img width="626" alt="Screen Shot 2019-04-02 at 11 51 32 am" src="https://user-images.githubusercontent.com/612020/55368487-c7810c00-553d-11e9-9b95-422483a8392f.png">

The 16 emoji responses here show that folks have landed on this issue, probably without reading the docs, and have been helped and on their way asap 👍

**Comment by MadeByMike** [comment]
We've got a big task to change\update our error messages. Once this is done let's grab all the console logs from the main packages and see what issues we can create for each of them. That's a better starting point.
