### ISSUE TITLE
Need Docs: MongoDB version

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#987]
Does the master branch require greater than mongodb 2.4?

**Comment by JedWatson** [comment]
Yes, we're using a few features that expect at least 2.4

I'll add this to the docs...

**Comment by JedWatson** [comment]
Sorry - I may have misread, it doesn't require _greater_ than 2.4, it require _2.4 or greater_. I've added it to the english docs.

**Comment by weekwood** [comment]
add zh via #999 @JedWatson

**Comment by chrisschaub** [comment]
Thanks.

**Comment by JohnnyEstilles** [comment]
Do not close. Still needs ES docs.

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/102
