### ISSUE TITLE
Needs Docs: New Geo Field

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#988]
Need to document the new Geo field I created, as per #969 

I'm also considering renaming it to GeoPoint but that shouldn't be a blocker. Will make a call before it gets released.

**Comment by BerkeleyTrue** [comment]
+1 GeoPoint as this is what I have seen with other ODM/ORM's

**Comment by JedWatson** [comment]
@BerkeleyTrue I was considering allowing different types of Geo data to be stored (points, paths, etc) but I actually think this would be more easily done with different field types. I'll rename it to GeoPoint now.

**Comment by andrewlinfoot** [comment]
We're closing all documentation requests to keep the issue tracker unpolluted. I've moved this request over to the documentation repo: https://github.com/keystonejs/keystonejs-site/issues/101
