### ISSUE TITLE
Cannot read property 'note' of undefined; TextArray type

### ISSUE THREAD

**Issue by vfermino** [keystonejs/keystone#991]
```
var keystone = require('keystone'),
	Types = keystone.Field.Types,
	collections = Types.Select;
var Product = new keystone.List('Product', {
	autokey: { path: 'slug', from: 'name', unique: true },
	map: { name: 'name' },
    defaultSort: 'name',
	label: 'Products',
	collections: {
        type: Types.Relationship,
        ref: 'Collection',
        many: true
	}
});

Product.add({
	name: { type: String, required: true, label: 'Product name' },
	code: { type: Types.NumberArray, label: 'Codes' }, // This is the one giving me trouble
	publishedDate: { type: Date, default: Date.now, label: 'Publishing date' },
	banner: { type: Types.CloudinaryImage, label: 'Banner' },
	description: { type: String, label: 'Description' },
	linkDatasheet: { type: String, label: 'Datasheet'},
	version: { type: Types.Number, label: 'Document Version' },
	content: { type: Types.Html, height: 1000, wysiwyg: true, label: 'Content' },
	state: { type: Types.Select, options: 'draft, published, hidden, invisible', default: 'draft', index: true, label: 'State' },
	tags: {type: Types.TextArray, default:'', note:'',label:'Tags'}, // This is the second one giving me trouble
	icon: { type: Types.CloudinaryImage, label: 'Icon' },
	collections: {
		type: Types.Relationship,
		ref: 'Collection',
		many: true, label: 'Collections'
	}
});

Product.register();
```
So, I can't use array types, for some reason. Neither NumberArray nor TextArray. Am I missing something? They always point out to the "cannot read property 'note' of undefined" error, unless I change their types. Are these array types deprecated or something I'm missing? Thanks. I'm using Keystone 0.2.28.

**Comment by JohnnyEstilles** [comment]
NumberArray and TextArray are not available on 0.2.28. They will be available in the upcoming 0.3.0 release.

**Comment by vfermino** [comment]
So there's absolutely nothing I can do about it? Well, I guess I could make a single String and split it later, but still... bummers.

**Comment by JohnnyEstilles** [comment]
Those are among the field types that are being added on 0.3.x. I understand that it will be released soon, but unfortunately I don't have an exact ETA.

**Comment by snowkeeper** [comment]
@vfermino as @JohnnyEstilles said 0.3.0 is nearing release.  If you want to go ahead and work with 0.3.0 you can and it would also help the community as a final tester.

Install with
```
npm install keystonejs/keystone
```

**Comment by vfermino** [comment]
I installed it, and had to change a few stuff that was wrong with my code and it's great so far. Thanks. I will use the latest version whenever possible.
