### ISSUE TITLE
Admin UI Home Page Nav Link display styling

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#994]
Could the Admin UI home page emphasize the keys in the nav link display like this (this is subjective; if it doesn't fly with the UX team then close it):

![image](https://cloud.githubusercontent.com/assets/5872515/6054760/eb392c20-acbf-11e4-8ed6-4624f15855b7.png)

or like this:

![image](https://cloud.githubusercontent.com/assets/5872515/6054735/9348e4b0-acbf-11e4-8a37-a52fa82d0770.png)

or like this:

![image](https://cloud.githubusercontent.com/assets/5872515/6054721/3535cb9a-acbf-11e4-80ae-dff133f03a4b.png)

Instead of like this:

![image](https://cloud.githubusercontent.com/assets/5872515/6054584/48358a34-acbd-11e4-8e88-53d5ae96fac4.png)

**Comment by SharadKumar** [comment]
My personal preference is that existing styling is quite decent as is.

Though I would love to see Model links stacked in two columns (within group) instead of heaps of whitespace on the right with single column. I believe this was done a while back but commented out.

**Comment by snowkeeper** [comment]
I was scrolling through, got to the last, thought I like that one, and then realized that was what you didn't like.  

We also have a lot of dead space on the homepage.  Is there any interest in having a homepage that has a few configurable options like recent entries to a list or lists.

**Comment by morenoh149** [comment]
The homepage for the adminUI could have way more things. Ideas ![wordpress ui](http://www.yourinspirationweb.com/en/wp-content/uploads/2010/06/admin-panel.jpg)

![shopify ui](http://cdn.shopify.com/s/files/1/0070/7032/files/partial-refunds.jpg?667)

**Comment by snowkeeper** [comment]
@JedWatson is this something that you would like Keystone to incorporate?  If so should we create a new Issue to discuss what features everyone would like in a homepage?

**Comment by webteckie** [comment]
ok :-)  Like I said it was a subjective thing.  I do agree that the page needs to be more Dashboard-ish and that may handle it for me :-)

**Comment by morenoh149** [comment]
I'd be happy with a spec for how to add adminUI dashboard widgets (react components). @leonardsouza in the gitter has been asking how to add a setting config page to the adminUI. I think that ability would be great.

**Comment by leonardsouza** [comment]
+1 for a widget spec.

**Comment by webteckie** [comment]
Closing this issue.  New issues can be opened for any suggestions that came up in the thread.

**Comment by JedWatson** [comment]
Just FYI, this sort of capability is something I'd really like to support - both adding your own CSS (which would let you do what you were after, @webteckie) and replacing the default Admin UI Homepage with custom React component(s).
