### ISSUE TITLE
GeoPoint field with "dependsOn: false" prevents form from being submitted

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#997]
@JedWatson Opening this new issue per discussion in #969.  Items based on a model with a GeoPoint field in it but that do not show the GeoPoint field form (because the dependsOn dependency is false) fail with the following when the item is saved (the GeoPoint is not even a required field):

![image](https://cloud.githubusercontent.com/assets/5872515/6072631/dac1b10c-ad71-11e4-8ff5-19c9a7295869.png)

**Comment by sebmck** [comment]
@webteckie Can you provide a copy of your model?

**Comment by sebmck** [comment]
Nevermind, fixed.

**Comment by webteckie** [comment]
@sebmck ok, if it gets merge I can give it a quick test.  tnx

**Comment by sebmck** [comment]
@webteckie It's already in master.

**Comment by webteckie** [comment]
@sebmck yeah, just realized that...testing :-)
